QGIS API Documentation: QgsRasterMatrix Class Reference
QgsRasterMatrix Class Reference
#include <qgsrastermatrix.h>
Public Types
enum TwoArgOperator {
opPLUS, opMINUS, opMUL, opDIV,
opPOW, opEQ, opNE, opGT,
opLT, opGE, opLE, opAND,
opOR
}
enum OneArgOperator {
opSQRT, opSIN, opCOS, opTAN,
opASIN, opACOS, opATAN, opSIGN
}
Public Member Functions
QgsRasterMatrix ()
Takes ownership of data array.
QgsRasterMatrix (int nCols, int nRows, float *data, double nodataValue)
QgsRasterMatrix (const QgsRasterMatrix &m)
~QgsRasterMatrix ()
bool isNumber () const
Returns true if matrix is 1x1 (=scalar number)
double number () const
float * data ()
Returns data array (but not ownership)
float * takeData ()
Returns data and ownership.
void setData (int cols, int rows, float *data, double nodataValue)
int nColumns () const
int nRows () const
double nodataValue () const
void setNodataValue (double d)
QgsRasterMatrix & operator= (const QgsRasterMatrix &m)
bool add (const QgsRasterMatrix &other)
Adds another matrix to this one.
bool subtract (const QgsRasterMatrix &other)
Subtracts another matrix from this one.
bool multiply (const QgsRasterMatrix &other)
bool divide (const QgsRasterMatrix &other)
bool power (const QgsRasterMatrix &other)
bool equal (const QgsRasterMatrix &other)
bool notEqual (const QgsRasterMatrix &other)
bool greaterThan (const QgsRasterMatrix &other)
bool lesserThan (const QgsRasterMatrix &other)
bool greaterEqual (const QgsRasterMatrix &other)
bool lesserEqual (const QgsRasterMatrix &other)
bool logicalAnd (const QgsRasterMatrix &other)
bool logicalOr (const QgsRasterMatrix &other)
bool squareRoot ()
bool sinus ()
bool asinus ()
bool cosinus ()
bool acosinus ()
bool tangens ()
bool atangens ()
bool changeSign ()
Private Member Functions
bool twoArgumentOperation (TwoArgOperator op, const QgsRasterMatrix &other)
+,-,*,/,^,<,>,<=,>=,=,!=, and, or
bool oneArgumentOperation (OneArgOperator op)
bool testPowerValidity (double base, double power)
Private Attributes
int mColumns
int mRows
float * mData
double mNodataValue
Detailed Description
Definition at line 21 of file qgsrastermatrix.h.
Member Enumeration Documentation
enum QgsRasterMatrix::OneArgOperator
Enumerator:
opSQRT
opSIN
opCOS
opTAN
opASIN
opACOS
opATAN
opSIGN
Definition at line 42 of file qgsrastermatrix.h.
enum QgsRasterMatrix::TwoArgOperator
Enumerator:
opPLUS
opMINUS
opMUL
opDIV
opPOW
opEQ
opNE
opGT
opLT
opGE
opLE
opAND
opOR
Definition at line 25 of file qgsrastermatrix.h.
Constructor & Destructor Documentation
QgsRasterMatrix::QgsRasterMatrix ()
Takes ownership of data array.
Definition at line 23 of file qgsrastermatrix.cpp.
QgsRasterMatrix::QgsRasterMatrix (int nCols, int nRows, float * data, double nodataValue)
Note
note available in python bindings
Definition at line 27 of file qgsrastermatrix.cpp.
QgsRasterMatrix::QgsRasterMatrix (const QgsRasterMatrix & m)
Definition at line 32 of file qgsrastermatrix.cpp.
References operator=().
QgsRasterMatrix::~QgsRasterMatrix ()
Definition at line 37 of file qgsrastermatrix.cpp.
References mData.
Member Function Documentation
bool QgsRasterMatrix::acosinus ()
Definition at line 155 of file qgsrastermatrix.cpp.
References oneArgumentOperation(), and opACOS.
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::add (const QgsRasterMatrix & other)
Adds another matrix to this one.
Definition at line 70 of file qgsrastermatrix.cpp.
References opPLUS, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::asinus ()
Definition at line 145 of file qgsrastermatrix.cpp.
References oneArgumentOperation(), and opASIN.
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::atangens ()
Definition at line 165 of file qgsrastermatrix.cpp.
References oneArgumentOperation(), and opATAN.
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::changeSign ()
Definition at line 170 of file qgsrastermatrix.cpp.
References oneArgumentOperation(), and opSIGN.
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::cosinus ()
Definition at line 150 of file qgsrastermatrix.cpp.
References oneArgumentOperation(), and opCOS.
Referenced by QgsRasterCalcNode::calculate().
float* QgsRasterMatrix::data () inline
Returns data array (but not ownership)
Note
not available in python bindings
Definition at line 67 of file qgsrastermatrix.h.
Referenced by QgsRasterCalculator::processCalculation(), setData(), and takeData().
bool QgsRasterMatrix::divide (const QgsRasterMatrix & other)
Definition at line 85 of file qgsrastermatrix.cpp.
References opDIV, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::equal (const QgsRasterMatrix & other)
Definition at line 95 of file qgsrastermatrix.cpp.
References opEQ, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::greaterEqual (const QgsRasterMatrix & other)
Definition at line 115 of file qgsrastermatrix.cpp.
References opGE, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::greaterThan (const QgsRasterMatrix & other)
Definition at line 105 of file qgsrastermatrix.cpp.
References opGT, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::isNumber () const inline
Returns true if matrix is 1x1 (=scalar number)
Definition at line 62 of file qgsrastermatrix.h.
Referenced by QgsRasterCalculator::processCalculation(), and twoArgumentOperation().
bool QgsRasterMatrix::lesserEqual (const QgsRasterMatrix & other)
Definition at line 120 of file qgsrastermatrix.cpp.
References opLE, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::lesserThan (const QgsRasterMatrix & other)
Definition at line 110 of file qgsrastermatrix.cpp.
References opLT, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::logicalAnd (const QgsRasterMatrix & other)
Definition at line 125 of file qgsrastermatrix.cpp.
References opAND, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::logicalOr (const QgsRasterMatrix & other)
Definition at line 130 of file qgsrastermatrix.cpp.
References opOR, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::multiply (const QgsRasterMatrix & other)
Definition at line 80 of file qgsrastermatrix.cpp.
References opMUL, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
int QgsRasterMatrix::nColumns () const inline
Definition at line 74 of file qgsrastermatrix.h.
Referenced by QgsRasterCalcNode::calculate(), operator=(), and twoArgumentOperation().
double QgsRasterMatrix::nodataValue () const inline
Definition at line 77 of file qgsrastermatrix.h.
Referenced by QgsRasterCalcNode::calculate(), operator=(), QgsRasterCalculator::processCalculation(), setData(), and twoArgumentOperation().
bool QgsRasterMatrix::notEqual (const QgsRasterMatrix & other)
Definition at line 100 of file qgsrastermatrix.cpp.
References opNE, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
int QgsRasterMatrix::nRows () const inline
Definition at line 75 of file qgsrastermatrix.h.
Referenced by QgsRasterCalcNode::calculate(), operator=(), and twoArgumentOperation().
double QgsRasterMatrix::number () const inline
Definition at line 63 of file qgsrastermatrix.h.
Referenced by QgsRasterCalculator::processCalculation(), and twoArgumentOperation().
bool QgsRasterMatrix::oneArgumentOperation (OneArgOperator op) private
Definition at line 175 of file qgsrastermatrix.cpp.
References mColumns, mData, mNodataValue, mRows, opACOS, opASIN, opATAN, opCOS, opSIGN, opSIN, opSQRT, and opTAN.
Referenced by acosinus(), asinus(), atangens(), changeSign(), cosinus(), sinus(), squareRoot(), and tangens().
QgsRasterMatrix & QgsRasterMatrix::operator= (const QgsRasterMatrix & m)
Definition at line 42 of file qgsrastermatrix.cpp.
References mColumns, mData, mNodataValue, mRows, nColumns(), nodataValue(), and nRows().
Referenced by QgsRasterMatrix().
bool QgsRasterMatrix::power (const QgsRasterMatrix & other)
Definition at line 90 of file qgsrastermatrix.cpp.
References opPOW, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
void QgsRasterMatrix::setData (int cols, int rows, float * data, double nodataValue)
Definition at line 54 of file qgsrastermatrix.cpp.
References data(), mColumns, mData, mNodataValue, mRows, and nodataValue().
Referenced by QgsRasterCalcNode::calculate().
void QgsRasterMatrix::setNodataValue (double d) inline
Definition at line 78 of file qgsrastermatrix.h.
bool QgsRasterMatrix::sinus ()
Definition at line 140 of file qgsrastermatrix.cpp.
References oneArgumentOperation(), and opSIN.
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::squareRoot ()
Definition at line 135 of file qgsrastermatrix.cpp.
References oneArgumentOperation(), and opSQRT.
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::subtract (const QgsRasterMatrix & other)
Subtracts another matrix from this one.
Definition at line 75 of file qgsrastermatrix.cpp.
References opMINUS, and twoArgumentOperation().
Referenced by QgsRasterCalcNode::calculate().
float * QgsRasterMatrix::takeData ()
Returns data and ownership.
Sets data and nrows, ncols of this matrix to 0
Note
not available in python bindings
Definition at line 63 of file qgsrastermatrix.cpp.
References data(), mColumns, mData, and mRows.
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::tangens ()
Definition at line 160 of file qgsrastermatrix.cpp.
References oneArgumentOperation(), and opTAN.
Referenced by QgsRasterCalcNode::calculate().
bool QgsRasterMatrix::testPowerValidity (double base, double power) private
Definition at line 541 of file qgsrastermatrix.cpp.
Referenced by twoArgumentOperation().
bool QgsRasterMatrix::twoArgumentOperation (TwoArgOperator op, const QgsRasterMatrix & other) private
+,-,*,/,^,<,>,<=,>=,=,!=, and, or
Definition at line 227 of file qgsrastermatrix.cpp.
References isNumber(), mColumns, mData, mNodataValue, mRows, nColumns(), nodataValue(), nRows(), number(), opAND, opDIV, opEQ, opGE, opGT, opLE, opLT, opMINUS, opMUL, opNE, opOR, opPLUS, opPOW, and testPowerValidity().
Referenced by add(), divide(), equal(), greaterEqual(), greaterThan(), lesserEqual(), lesserThan(), logicalAnd(), logicalOr(), multiply(), notEqual(), power(), and subtract().
Member Data Documentation
int QgsRasterMatrix::mColumns private
Definition at line 107 of file qgsrastermatrix.h.
Referenced by oneArgumentOperation(), operator=(), setData(), takeData(), and twoArgumentOperation().
float* QgsRasterMatrix::mData private
Definition at line 109 of file qgsrastermatrix.h.
Referenced by oneArgumentOperation(), operator=(), setData(), takeData(), twoArgumentOperation(), and ~QgsRasterMatrix().
double QgsRasterMatrix::mNodataValue private
Definition at line 110 of file qgsrastermatrix.h.
Referenced by oneArgumentOperation(), operator=(), setData(), and twoArgumentOperation().
int QgsRasterMatrix::mRows private
Definition at line 108 of file qgsrastermatrix.h.
Referenced by oneArgumentOperation(), operator=(), setData(), takeData(), and twoArgumentOperation().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/analysis/raster/qgsrastermatrix.h
/tmp/buildd/qgis-2.0.1/src/analysis/raster/qgsrastermatrix.cpp