QGIS API Documentation: QgsFields Class Reference
QgsFields Class Reference
QGIS core library
Container of fields for a vector layer.
#include <qgsfield.h>
Classes
struct Field
Public Types
enum FieldOrigin { OriginUnknown, OriginProvider, OriginJoin, OriginEdit }
typedef struct QgsFields::Field Field
Public Member Functions
void clear ()
Remove all fields.
bool append (const QgsField &field, FieldOrigin origin=OriginProvider, int originIndex=-1)
Append a field. The field must have unique name, otherwise it is rejected (returns false)
void remove (int fieldIdx)
Remove a field with the given index.
void extend (const QgsFields &other)
Extend with fields from an other QgsFields container.
bool isEmpty () const
Check whether the container is empty.
int count () const
Return number of items.
int size () const
Return number of items.
const QgsField & operator[] (int i) const
Get field at particular index (must be in range 0..N-1)
QgsField & operator[] (int i)
Get field at particular index (must be in range 0..N-1)
const QgsField & at (int i) const
Get field at particular index (must be in range 0..N-1)
const QgsField & field (int fieldIdx) const
Get field at particular index (must be in range 0..N-1)
const QgsField & field (const QString &name) const
Get field at particular index (must be in range 0..N-1)
FieldOrigin fieldOrigin (int fieldIdx) const
Get field's origin (value from an enumeration)
int fieldOriginIndex (int fieldIdx) const
Get field's origin index (its meaning is specific to each type of origin)
int indexFromName (const QString &name) const
Look up field's index from name. Returns -1 on error.
QList< QgsField > toList () const
Utility function to return a list of QgsField instances.
Protected Attributes
QVector< Field > mFields
internal storage of the container
QHash< QString, int > mNameToIndex
map for quick resolution of name to index
Detailed Description
Container of fields for a vector layer.
In addition to storing a list of QgsField instances, it also:
allows quick lookups of field names to index in the list
keeps track of where the field definition comes from (vector data provider, joined layer or newly added from an editing operation)
Definition at line 162 of file qgsfield.h.
Member Typedef Documentation
typedef struct QgsFields::Field QgsFields::Field
Member Enumeration Documentation
enum QgsFields::FieldOrigin
Enumerator:
OriginUnknown
it has not been specified where the field comes from
OriginProvider
field comes from the underlying data provider of the vector layer (originIndex = index in provider's fields)
OriginJoin
field comes from a joined layer (originIndex / 1000 = index of the join, originIndex % 1000 = index within the join)
OriginEdit
field has been temporarily added in editing mode (originIndex = index in the list of added attributes)
Definition at line 166 of file qgsfield.h.
Member Function Documentation
bool QgsFields::append (const QgsField & field, FieldOrigin origin = OriginProvider, int originIndex = -1)
Append a field. The field must have unique name, otherwise it is rejected (returns false)
Definition at line 137 of file qgsfield.cpp.
References mFields, mNameToIndex, QgsField::name(), and OriginProvider.
Referenced by QgsOverlayAnalyzer::combineFieldLists(), QgsGeometryAnalyzer::convexHull(), extend(), QgsGeometryAnalyzer::extent(), QgsVectorLayerJoinBuffer::updateFields(), and QgsVectorLayerEditBuffer::updateFields().
const QgsField& QgsFields::at (int i) const inline
Get field at particular index (must be in range 0..N-1)
Definition at line 205 of file qgsfield.h.
Referenced by extend(), QgsFeature::fieldNameIndex(), QgsDataDefinedButton::init(), QgsPalLayerSettings::readDataDefinedProperty(), QgsProjectFileTransform::transform0110to1000(), and QgsDiagramSettings::writeXML().
void QgsFields::clear ()
Remove all fields.
Definition at line 131 of file qgsfield.cpp.
References mFields, and mNameToIndex.
int QgsFields::count () const inline
Return number of items.
Definition at line 196 of file qgsfield.h.
Referenced by QgsAttributeDialog::accept(), QgsVectorLayerEditBuffer::addAttribute(), QgsVectorLayerEditBuffer::addFeature(), QgsVectorLayerFeatureIterator::addJoinedAttributes(), QgsOfflineEditing::applyFeaturesAdded(), QgsVectorLayer::attributeDisplayName(), QgsVectorDataProvider::attributeIndexes(), QgsVectorLayerEditBuffer::changeAttributeValue(), QgsVectorLayer::checkedState(), QgsOverlayAnalyzer::combineFieldLists(), QgsVectorLayerEditBuffer::commitChanges(), QgsOfflineEditing::copyVectorLayer(), QgsFormAnnotationItem::createDesignerWidget(), QgsVectorFileWriter::createFeature(), QgsVectorLayerEditBuffer::deleteAttribute(), QgsVectorLayer::editType(), QgsAttributeAction::expandAction(), extend(), QgsVectorLayer::fieldEditable(), QgsVectorDataProvider::fieldNameIndex(), QgsFeature::fieldNameIndex(), QgsVectorLayer::fieldNameIndex(), QgsVectorDataProvider::fieldNameMap(), QgsVectorDataProvider::fillMinMaxCache(), QgsComposerAttributeTable::getHeaderLabels(), QgsZonalStatistics::getUniqueFieldName(), QgsVectorLayerImport::importLayer(), QgsDataDefinedButton::init(), QgsComposerAttributeTable::initializeAliasMap(), QgsLabel::labelField(), QgsVectorLayer::labelOnTop(), QgsAttributeTableModel::loadAttributes(), QgsExpressionBuilderWidget::loadFieldNames(), QgsVectorLayer::pendingAllAttributesList(), QgsVectorLayer::pendingPkAttributesList(), QgsSearchQueryBuilder::populateFields(), QgsQueryBuilder::populateFields(), QgsExpression::NodeColumnRef::prepare(), QgsAttributeDialog::QgsAttributeDialog(), QgsFeature::QgsFeature(), QgsVectorFileWriter::QgsVectorFileWriter(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), QgsVectorLayerUndoCommandAddAttribute::QgsVectorLayerUndoCommandAddAttribute(), QgsVectorLayer::range(), QgsLabel::readLabelField(), QgsVectorLayer::setCheckedState(), QgsVectorLayer::setDisplayField(), QgsVectorLayer::setEditType(), QgsVectorLayer::setFieldEditable(), QgsFeature::setFields(), QgsVectorLayer::setLabelOnTop(), QgsFeatureRequest::setSubsetOfAttributes(), QgsProjectFileTransform::transform0110to1000(), QgsVectorLayerJoinBuffer::updateFields(), QgsVectorLayer::valueMap(), and QgsVectorLayer::valueRelation().
void QgsFields::extend (const QgsFields & other)
Extend with fields from an other QgsFields container.
Definition at line 156 of file qgsfield.cpp.
References append(), at(), count(), fieldOrigin(), and fieldOriginIndex().
const QgsField& QgsFields::field (int fieldIdx) const inline
Get field at particular index (must be in range 0..N-1)
Definition at line 207 of file qgsfield.h.
Referenced by remove(), and QgsVectorLayerJoinBuffer::updateFields().
const QgsField& QgsFields::field (const QString & name) const inline
Get field at particular index (must be in range 0..N-1)
Definition at line 209 of file qgsfield.h.
FieldOrigin QgsFields::fieldOrigin (int fieldIdx) const inline
Get field's origin (value from an enumeration)
Definition at line 212 of file qgsfield.h.
Referenced by QgsVectorLayerEditBuffer::changeAttributeValue(), QgsVectorLayerEditBuffer::deleteAttribute(), extend(), QgsVectorLayer::fieldEditable(), QgsVectorLayerJoinBuffer::joinForFieldIndex(), QgsVectorLayer::maximumValue(), QgsVectorLayer::minimumValue(), QgsVectorLayer::pendingPkAttributesList(), QgsVectorLayerFeatureIterator::prepareJoins(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute(), and QgsVectorLayer::uniqueValues().
int QgsFields::fieldOriginIndex (int fieldIdx) const inline
Get field's origin index (its meaning is specific to each type of origin)
Definition at line 214 of file qgsfield.h.
Referenced by QgsVectorLayerEditBuffer::deleteAttribute(), extend(), QgsVectorLayerJoinBuffer::joinForFieldIndex(), QgsVectorLayer::pendingPkAttributesList(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute(), and QgsVectorLayerUndoCommandAddAttribute::undo().
int QgsFields::indexFromName (const QString & name) const inline
Look up field's index from name. Returns -1 on error.
Definition at line 217 of file qgsfield.h.
Referenced by QgsVectorLayerJoinBuffer::cacheJoinLayer(), QgsPalLayerSettings::dataDefinedValue(), and QgsVectorLayerFeatureIterator::prepareJoins().
bool QgsFields::isEmpty () const inline
Check whether the container is empty.
Definition at line 194 of file qgsfield.h.
Referenced by QgsExpressionBuilderWidget::loadFieldNames(), and QgsAttributeDialog::QgsAttributeDialog().
const QgsField& QgsFields::operator[] (int i) const inline
Get field at particular index (must be in range 0..N-1)
Definition at line 201 of file qgsfield.h.
QgsField& QgsFields::operator[] (int i) inline
Get field at particular index (must be in range 0..N-1)
Definition at line 203 of file qgsfield.h.
void QgsFields::remove (int fieldIdx)
Remove a field with the given index.
Definition at line 150 of file qgsfield.cpp.
References field(), mFields, mNameToIndex, and QgsField::name().
Referenced by QgsVectorLayerEditBuffer::updateFields().
int QgsFields::size () const inline
Return number of items.
Definition at line 198 of file qgsfield.h.
Referenced by QgsVectorLayerEditBuffer::commitChanges(), QgsGml::QgsGml(), QgsVectorFileWriter::QgsVectorFileWriter(), QgsPalLayerSettings::readDataDefinedProperty(), and QgsVectorLayer::setDisplayField().
QList< QgsField > QgsFields::toList () const
Utility function to return a list of QgsField instances.
Definition at line 164 of file qgsfield.cpp.
References mFields.
Referenced by QgsDualView::columnBoxInit(), and QgsGeometryAnalyzer::eventLayer().
Member Data Documentation
QVector<Field> QgsFields::mFields protected
internal storage of the container
Definition at line 224 of file qgsfield.h.
Referenced by append(), clear(), remove(), and toList().
QHash<QString, int> QgsFields::mNameToIndex protected
map for quick resolution of name to index
Definition at line 227 of file qgsfield.h.
Referenced by append(), clear(), and remove().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/qgsfield.h
/tmp/buildd/qgis-2.0.1/src/core/qgsfield.cpp