QGIS API Documentation: QgsComposerItemGroup Class Reference
QgsComposerItemGroup Class Reference
MapComposer
A container for grouping several QgsComposerItems.
#include <qgscomposeritemgroup.h>
Public Slots
void itemDestroyed ()
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
void repaint ()
Signals
void childItemDeleted (QgsComposerItem *item)
Signals inherited from QgsComposerItem
void rotationChanged (double newRotation)
Is emitted on rotation change to notify north arrow pictures.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
Public Member Functions
QgsComposerItemGroup (QgsComposition *c)
~QgsComposerItemGroup ()
virtual int type () const
return correct graphics item type.
void addItem (QgsComposerItem *item)
Adds an item to the group.
void removeItems ()
Removes the items but does not delete them.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
Draw outline and ev.
void setSceneRect (const QRectF &rectangle)
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
bool writeXML (QDomElement &elem, QDomDocument &doc) const
stores state in Dom node
bool readXML (const QDomElement &itemElem, const QDomDocument &doc)
sets state from Dom document
QSet< QgsComposerItem * > items ()
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected ()
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
void updateCursor (const QPointF &itemPos)
Update mouse cursor at (item) position.
double rotation () const
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
Protected Member Functions
void drawFrame (QPainter *p)
Draw black frame around item.
Protected Member Functions inherited from QgsComposerItem
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
Qt::CursorShape cursorForPosition (const QPointF &itemCoordPos)
Finds out the appropriate cursor for the current mouse position in the widget (e.g.
QgsComposerItem::MouseMoveAction mouseMoveActionForPosition (const QPointF &itemCoordPos)
Finds out which mouse move action to choose depending on the cursor position inside the widget.
void changeItemRectangle (const QPointF &currentPosition, const QPointF &mouseMoveStartPos, const QGraphicsRectItem *originalItem, double dx, double dy, QGraphicsRectItem *changeItem)
Changes the rectangle of an item depending on current mouse action (resize or move)
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle (mRotation)
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Private Attributes
QSet< QgsComposerItem * > mItems
QRectF mSceneBoundingRectangle
Additional Inherited Members
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Protected Attributes inherited from QgsComposerItem
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
Detailed Description
A container for grouping several QgsComposerItems.
Definition at line 24 of file qgscomposeritemgroup.h.
Constructor & Destructor Documentation
QgsComposerItemGroup::QgsComposerItemGroup (QgsComposition * c)
Definition at line 24 of file qgscomposeritemgroup.cpp.
QgsComposerItemGroup::~QgsComposerItemGroup ()
Definition at line 31 of file qgscomposeritemgroup.cpp.
References QgsComposerItem::mComposition, and mItems.
Member Function Documentation
void QgsComposerItemGroup::addItem (QgsComposerItem * item) virtual
Adds an item to the group.
All the group members are deleted if the group is deleted
Reimplemented from QgsComposerItem.
Definition at line 44 of file qgscomposeritemgroup.cpp.
References itemDestroyed(), mItems, mSceneBoundingRectangle, setSceneRect(), and QgsComposerItem::setSelected().
Referenced by QgsComposerView::groupItems(), and readXML().
void QgsComposerItemGroup::childItemDeleted (QgsComposerItem * item) signal
void QgsComposerItemGroup::drawFrame (QPainter * p) protected virtual
Draw black frame around item.
Reimplemented from QgsComposerItem.
Definition at line 162 of file qgscomposeritemgroup.cpp.
References QgsComposerItem::mComposition, QgsComposerItem::mFrame, QgsComposition::plotStyle(), and QgsComposition::Preview.
Referenced by paint().
void QgsComposerItemGroup::itemDestroyed () slot
Definition at line 109 of file qgscomposeritemgroup.cpp.
References mItems.
Referenced by addItem().
QSet<QgsComposerItem*> QgsComposerItemGroup::items () inline
Definition at line 57 of file qgscomposeritemgroup.h.
Referenced by QgsComposerView::keyPressEvent(), readXML(), and QgsComposition::removeComposerItem().
void QgsComposerItemGroup::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0)
Draw outline and ev.
selection handles
Definition at line 114 of file qgscomposeritemgroup.cpp.
References drawFrame(), and QgsComposerItem::drawSelectionBoxes().
bool QgsComposerItemGroup::readXML (const QDomElement & itemElem, const QDomDocument & doc) virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is the Dom document
Implements QgsComposerItem.
Definition at line 197 of file qgscomposeritemgroup.cpp.
References QgsComposerItem::_readXML(), addItem(), items(), QgsComposerItem::mComposition, QgsComposerItem::mTemplateUuid, QgsComposerItem::mUuid, and QgsComposerItem::uuid().
Referenced by QgsComposition::addItemsFromXML().
void QgsComposerItemGroup::removeItems () virtual
Removes the items but does not delete them.
Reimplemented from QgsComposerItem.
Definition at line 98 of file qgscomposeritemgroup.cpp.
References mItems.
Referenced by QgsComposerView::ungroupItems().
void QgsComposerItemGroup::setSceneRect (const QRectF & rectangle) virtual
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
Reimplemented from QgsComposerItem.
Definition at line 125 of file qgscomposeritemgroup.cpp.
References mItems.
Referenced by addItem().
virtual int QgsComposerItemGroup::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerItem.
Definition at line 32 of file qgscomposeritemgroup.h.
References QgsComposerItem::ComposerItemGroup.
bool QgsComposerItemGroup::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
stores state in Dom node
Parameters
elem is Dom element corresponding to 'Composer' tag
doc is the Dom document
Implements QgsComposerItem.
Definition at line 180 of file qgscomposeritemgroup.cpp.
References QgsComposerItem::_writeXML(), and mItems.
Member Data Documentation
QSet<QgsComposerItem*> QgsComposerItemGroup::mItems private
Definition at line 69 of file qgscomposeritemgroup.h.
Referenced by addItem(), itemDestroyed(), removeItems(), setSceneRect(), writeXML(), and ~QgsComposerItemGroup().
QRectF QgsComposerItemGroup::mSceneBoundingRectangle private
Definition at line 70 of file qgscomposeritemgroup.h.
Referenced by addItem().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/composer/qgscomposeritemgroup.h
/tmp/buildd/qgis-2.0.1/src/core/composer/qgscomposeritemgroup.cpp