QGIS API Documentation: QgsMultiBandColorRendererWidget Class Reference
QgsMultiBandColorRendererWidget Class Reference
#include <qgsmultibandcolorrendererwidget.h>
Public Slots
void loadMinMax (int theBandNo, double theMin, double theMax, int theOrigin)
Public Member Functions
QgsMultiBandColorRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent=QgsRectangle())
~QgsMultiBandColorRendererWidget ()
QgsRasterRenderer * renderer ()
void setFromRenderer (const QgsRasterRenderer *r)
QString min (int index=0)
QString max (int index=0)
void setMin (QString value, int index=0)
void setMax (QString value, int index=0)
int selectedBand (int index=0)
Public Member Functions inherited from QgsRasterRendererWidget
QgsRasterRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent)
virtual ~QgsRasterRendererWidget ()
void setRasterLayer (QgsRasterLayer *layer)
const QgsRasterLayer * rasterLayer () const
virtual QString stdDev ()
virtual void setStdDev (QString value)
Static Public Member Functions
static QgsRasterRendererWidget * create (QgsRasterLayer *layer, const QgsRectangle &theExtent)
Private Slots
void onBandChanged (int)
Private Member Functions
void createValidators ()
void setCustomMinMaxValues (QgsMultiBandColorRenderer *r, const QgsRasterDataProvider *provider, int redBand, int GreenBand, int blueBand)
void setMinMaxValue (const QgsContrastEnhancement *ce, QLineEdit *minEdit, QLineEdit *maxEdit)
Reads min/max values from contrast enhancement and fills values into the min/max line edits.
Private Attributes
QgsRasterMinMaxWidget * mMinMaxWidget
Additional Inherited Members
Public Types inherited from QgsRasterRendererWidget
enum LoadMinMaxAlgo { Estimate, Actual, CurrentExtent, CumulativeCut }
Protected Member Functions inherited from QgsRasterRendererWidget
QString displayBandName (int band) const
Returns a band name for display.
Protected Attributes inherited from QgsRasterRendererWidget
QgsRasterLayer * mRasterLayer
QgsRectangle mExtent
Current extent.
Detailed Description
Definition at line 31 of file qgsmultibandcolorrendererwidget.h.
Constructor & Destructor Documentation
QgsMultiBandColorRendererWidget::QgsMultiBandColorRendererWidget (QgsRasterLayer * layer, const QgsRectangle & extent = QgsRectangle())
Definition at line 22 of file qgsmultibandcolorrendererwidget.cpp.
References QgsRasterInterface::bandCount(), createValidators(), QgsRasterLayer::dataProvider(), QgsRasterRendererWidget::displayBandName(), loadMinMax(), mMinMaxWidget, QgsRasterRendererWidget::mRasterLayer, onBandChanged(), QgsRasterLayer::renderer(), QgsRasterMinMaxWidget::setExtent(), setFromRenderer(), and tr.
QgsMultiBandColorRendererWidget::~QgsMultiBandColorRendererWidget ()
Definition at line 73 of file qgsmultibandcolorrendererwidget.cpp.
Member Function Documentation
static QgsRasterRendererWidget* QgsMultiBandColorRendererWidget::create (QgsRasterLayer * layer, const QgsRectangle & theExtent) inline static
Definition at line 37 of file qgsmultibandcolorrendererwidget.h.
void QgsMultiBandColorRendererWidget::createValidators () private
Definition at line 98 of file qgsmultibandcolorrendererwidget.cpp.
Referenced by QgsMultiBandColorRendererWidget().
void QgsMultiBandColorRendererWidget::loadMinMax (int theBandNo, double theMin, double theMax, int theOrigin) slot
Definition at line 194 of file qgsmultibandcolorrendererwidget.cpp.
References QgsDebugMsg.
Referenced by QgsMultiBandColorRendererWidget().
QString QgsMultiBandColorRendererWidget::max (int index = 0) virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 304 of file qgsmultibandcolorrendererwidget.cpp.
QString QgsMultiBandColorRendererWidget::min (int index = 0) virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 285 of file qgsmultibandcolorrendererwidget.cpp.
void QgsMultiBandColorRendererWidget::onBandChanged (int index) private slot
Definition at line 183 of file qgsmultibandcolorrendererwidget.cpp.
References mMinMaxWidget, and QgsRasterMinMaxWidget::setBands().
Referenced by QgsMultiBandColorRendererWidget().
QgsRasterRenderer * QgsMultiBandColorRendererWidget::renderer () virtual
Implements QgsRasterRendererWidget.
Definition at line 77 of file qgsmultibandcolorrendererwidget.cpp.
References QgsRasterLayer::dataProvider(), QgsRasterRendererWidget::mRasterLayer, and setCustomMinMaxValues().
int QgsMultiBandColorRendererWidget::selectedBand (int index = 0) virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 359 of file qgsmultibandcolorrendererwidget.cpp.
void QgsMultiBandColorRendererWidget::setCustomMinMaxValues (QgsMultiBandColorRenderer * r, const QgsRasterDataProvider * provider, int redBand, int GreenBand, int blueBand) private
Definition at line 108 of file qgsmultibandcolorrendererwidget.cpp.
References QgsRasterDataProvider::dataType(), QgsContrastEnhancement::NoEnhancement, QgsMultiBandColorRenderer::setBlueContrastEnhancement(), QgsContrastEnhancement::setContrastEnhancementAlgorithm(), QgsMultiBandColorRenderer::setGreenContrastEnhancement(), QgsContrastEnhancement::setMaximumValue(), QgsContrastEnhancement::setMinimumValue(), and QgsMultiBandColorRenderer::setRedContrastEnhancement().
Referenced by renderer().
void QgsMultiBandColorRendererWidget::setFromRenderer (const QgsRasterRenderer * r)
Definition at line 264 of file qgsmultibandcolorrendererwidget.cpp.
References QgsMultiBandColorRenderer::blueBand(), QgsMultiBandColorRenderer::blueContrastEnhancement(), QgsMultiBandColorRenderer::greenBand(), QgsMultiBandColorRenderer::greenContrastEnhancement(), QgsMultiBandColorRenderer::redBand(), QgsMultiBandColorRenderer::redContrastEnhancement(), setMinMaxValue(), and tr.
Referenced by QgsMultiBandColorRendererWidget().
void QgsMultiBandColorRendererWidget::setMax (QString value, int index = 0) virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 341 of file qgsmultibandcolorrendererwidget.cpp.
void QgsMultiBandColorRendererWidget::setMin (QString value, int index = 0) virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 323 of file qgsmultibandcolorrendererwidget.cpp.
void QgsMultiBandColorRendererWidget::setMinMaxValue (const QgsContrastEnhancement * ce, QLineEdit * minEdit, QLineEdit * maxEdit) private
Reads min/max values from contrast enhancement and fills values into the min/max line edits.
Definition at line 241 of file qgsmultibandcolorrendererwidget.cpp.
References QgsContrastEnhancement::contrastEnhancementAlgorithm(), QgsContrastEnhancement::maximumValue(), and QgsContrastEnhancement::minimumValue().
Referenced by setFromRenderer().
Member Data Documentation
QgsRasterMinMaxWidget* QgsMultiBandColorRendererWidget::mMinMaxWidget private
Definition at line 63 of file qgsmultibandcolorrendererwidget.h.
Referenced by onBandChanged(), and QgsMultiBandColorRendererWidget().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/gui/raster/qgsmultibandcolorrendererwidget.h
/tmp/buildd/qgis-2.0.1/src/gui/raster/qgsmultibandcolorrendererwidget.cpp