QGIS API Documentation: QgsContextHelp Class Reference
QgsContextHelp Class Reference
QGIS core library
Provides a context based help browser for a dialog.
#include <qgscontexthelp.h>
Static Public Member Functions
static void run (QString context)
Private Slots
void processExited ()
void error (QProcess::ProcessError error)
Private Member Functions
QgsContextHelp ()
Constructor.
~QgsContextHelp ()
Destructor.
QProcess * start ()
void showContext (QString context)
void init ()
Private Attributes
QProcess * mProcess
Static Private Attributes
static QgsContextHelp * gContextHelp = 0
static QHash< QString, QString > gContextHelpTexts
Detailed Description
Provides a context based help browser for a dialog.
The help text is stored in SQLite and accessed by a context identifier unique to each dialog. This is a singleton class which invokes the help viewer using QProcess and ensures that only one viewer is open. The viewer will be terminated if open when the main application quits.
Definition at line 35 of file qgscontexthelp.h.
Constructor & Destructor Documentation
QgsContextHelp::QgsContextHelp () private
Constructor.
Definition at line 43 of file qgscontexthelp.cpp.
References mProcess, and start().
Referenced by run().
QgsContextHelp::~QgsContextHelp () private
Destructor.
Definition at line 48 of file qgscontexthelp.cpp.
References mProcess.
Member Function Documentation
void QgsContextHelp::error (QProcess::ProcessError error) private slot
Definition at line 81 of file qgscontexthelp.cpp.
References QgsMessageLog::logMessage(), and tr.
Referenced by start().
void QgsContextHelp::init () private
Definition at line 6 of file qgscontexthelp_texts.cpp.
References gContextHelpTexts.
Referenced by showContext().
void QgsContextHelp::processExited () private slot
Definition at line 102 of file qgscontexthelp.cpp.
References gContextHelp.
Referenced by start().
void QgsContextHelp::run (QString context) static
Definition at line 32 of file qgscontexthelp.cpp.
References gContextHelp, QgsContextHelp(), and showContext().
Referenced by QgsNewHttpConnection::on_buttonBox_helpRequested(), QgsSublayersDialog::on_buttonBox_helpRequested(), QgsNewVectorLayerDialog::on_buttonBox_helpRequested(), QgsQueryBuilder::on_buttonBox_helpRequested(), QgsSearchQueryBuilder::on_buttonBox_helpRequested(), and QgsOWSSourceSelect::on_mDialogButtonBox_helpRequested().
void QgsContextHelp::showContext (QString context) private
Definition at line 86 of file qgscontexthelp.cpp.
References gContextHelpTexts, init(), mProcess, QgsApplication::reportStyleSheet(), and tr.
Referenced by run().
QProcess * QgsContextHelp::start () private
Definition at line 53 of file qgscontexthelp.cpp.
References error(), QgsApplication::helpAppPath(), QgsApplication::isRunningFromBuildDir(), processExited(), and QgsDebugMsg.
Referenced by QgsContextHelp().
Member Data Documentation
QgsContextHelp * QgsContextHelp::gContextHelp = 0 static private
Definition at line 54 of file qgscontexthelp.h.
Referenced by processExited(), and run().
QHash< QString, QString > QgsContextHelp::gContextHelpTexts static private
Definition at line 57 of file qgscontexthelp.h.
Referenced by init(), and showContext().
QProcess* QgsContextHelp::mProcess private
Definition at line 55 of file qgscontexthelp.h.
Referenced by QgsContextHelp(), showContext(), and ~QgsContextHelp().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/qgscontexthelp.h
/tmp/buildd/qgis-2.0.1/src/core/qgscontexthelp.cpp
/tmp/buildd/qgis-2.0.1/src/core/qgscontexthelp_texts.cpp