QGIS API Documentation: QgsCoordinateTransformCache Class Reference
QgsCoordinateTransformCache Class Reference
Cache coordinate transform by authid of source/dest transformation to avoid the overhead of initialisation for each redraw.
#include <qgscrscache.h>
Public Member Functions
~QgsCoordinateTransformCache ()
const QgsCoordinateTransform * transform (const QString &srcAuthId, const QString &destAuthId)
Returns coordinate transformation.
void invalidateCrs (const QString &crsAuthId)
Removes transformations where a changed crs is involved from the cache.
Static Public Member Functions
static
QgsCoordinateTransformCache * instance ()
Private Attributes
QHash< QPair< QString, QString >
, QgsCoordinateTransform * > mTransforms
Static Private Attributes
static
QgsCoordinateTransformCache * mInstance = 0
Detailed Description
Cache coordinate transform by authid of source/dest transformation to avoid the overhead of initialisation for each redraw.
Definition at line 28 of file qgscrscache.h.
Constructor & Destructor Documentation
QgsCoordinateTransformCache::~QgsCoordinateTransformCache ()
Definition at line 32 of file qgscrscache.cpp.
References mInstance, and mTransforms.
Member Function Documentation
QgsCoordinateTransformCache * QgsCoordinateTransformCache::instance () static
Definition at line 23 of file qgscrscache.cpp.
References mInstance.
Referenced by QgsMapRenderer::render(), QgsMapRenderer::tr(), and transform().
void QgsCoordinateTransformCache::invalidateCrs (const QString & crsAuthId)
Removes transformations where a changed crs is involved from the cache.
Definition at line 60 of file qgscrscache.cpp.
References mTransforms.
const QgsCoordinateTransform * QgsCoordinateTransformCache::transform (const QString & srcAuthId, const QString & destAuthId)
Returns coordinate transformation.
Cache keeps ownership
Parameters
srcAuthId auth id string of source crs
destAuthId auth id string of dest crs
Definition at line 42 of file qgscrscache.cpp.
References instance(), and mTransforms.
Referenced by QgsMapRenderer::render(), and QgsMapRenderer::tr().
Member Data Documentation
QgsCoordinateTransformCache * QgsCoordinateTransformCache::mInstance = 0 static private
Definition at line 41 of file qgscrscache.h.
Referenced by instance(), and ~QgsCoordinateTransformCache().
QHash< QPair< QString, QString >, QgsCoordinateTransform* > QgsCoordinateTransformCache::mTransforms private
Definition at line 42 of file qgscrscache.h.
Referenced by invalidateCrs(), transform(), and ~QgsCoordinateTransformCache().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/qgscrscache.h
/tmp/buildd/qgis-2.0.1/src/core/qgscrscache.cpp