QGIS API Documentation: QgsPseudoColorShader Class Reference
QgsPseudoColorShader Class Reference
QGIS core library
A raster color shader that highlighs low values in blue and high values in red.
#include <qgspseudocolorshader.h>
Public Member Functions
QgsPseudoColorShader (double theMinimumValue=0.0, double theMaximumValue=255.0)
bool shade (double, int *, int *, int *)
generates and new RGB value based on one input value
bool shade (double, double, double, int *, int *, int *)
generates and new RGB value based on original RGB value
void setMaximumValue (double)
Set the maximum value.
void setMinimumValue (double)
Return the minimum value.
double classBreakMin1 () const
double classBreakMax1 () const
double classBreakMin2 () const
double classBreakMax2 () const
double classBreakMin3 () const
Public Member Functions inherited from QgsRasterShaderFunction
QgsRasterShaderFunction (double theMinimumValue=0.0, double theMaximumValue=255.0)
virtual ~QgsRasterShaderFunction ()
virtual bool shade (double, int *, int *, int *, int *)
generates and new RGBA value based on one input value
virtual bool shade (double, double, double, double, int *, int *, int *, int *)
generates and new RGBA value based on original RGBA value
double minimumMaximumRange () const
double minimumValue () const
double maximumValue () const
virtual void legendSymbologyItems (QList< QPair< QString, QColor > > &symbolItems) const
Private Member Functions
void setClassBreaks ()
Private Attributes
double mBreakSize
double mClassBreakMin1
double mClassBreakMax1
double mClassBreakMin2
double mClassBreakMax2
double mClassBreakMin3
Additional Inherited Members
Protected Attributes inherited from QgsRasterShaderFunction
double mMaximumValue
User defineable maximum value for the shading function.
double mMinimumValue
User defineable minimum value for the shading function.
double mMinimumMaximumRange
Minimum maximum range for the shading function.
Detailed Description
A raster color shader that highlighs low values in blue and high values in red.
Definition at line 29 of file qgspseudocolorshader.h.
Constructor & Destructor Documentation
QgsPseudoColorShader::QgsPseudoColorShader (double theMinimumValue = 0.0, double theMaximumValue = 255.0)
Definition at line 25 of file qgspseudocolorshader.cpp.
References setClassBreaks().
Member Function Documentation
double QgsPseudoColorShader::classBreakMax1 () const inline
Definition at line 48 of file qgspseudocolorshader.h.
double QgsPseudoColorShader::classBreakMax2 () const inline
Definition at line 50 of file qgspseudocolorshader.h.
double QgsPseudoColorShader::classBreakMin1 () const inline
Definition at line 47 of file qgspseudocolorshader.h.
double QgsPseudoColorShader::classBreakMin2 () const inline
Definition at line 49 of file qgspseudocolorshader.h.
double QgsPseudoColorShader::classBreakMin3 () const inline
Definition at line 51 of file qgspseudocolorshader.h.
void QgsPseudoColorShader::setClassBreaks () private
Definition at line 84 of file qgspseudocolorshader.cpp.
References mBreakSize, mClassBreakMax1, mClassBreakMax2, mClassBreakMin1, mClassBreakMin2, mClassBreakMin3, QgsRasterShaderFunction::mMinimumMaximumRange, and QgsRasterShaderFunction::mMinimumValue.
Referenced by QgsPseudoColorShader(), setMaximumValue(), and setMinimumValue().
void QgsPseudoColorShader::setMaximumValue (double theValue) virtual
Set the maximum value.
Set the maximum value for the raster shader.
Parameters
theValue The new maximum value
Reimplemented from QgsRasterShaderFunction.
Definition at line 100 of file qgspseudocolorshader.cpp.
References QgsRasterShaderFunction::mMaximumValue, QgsRasterShaderFunction::mMinimumMaximumRange, QgsRasterShaderFunction::mMinimumValue, and setClassBreaks().
void QgsPseudoColorShader::setMinimumValue (double theValue) virtual
Return the minimum value.
Set the maximum value for the raster shader.
Parameters
theValue The new minimum value
Reimplemented from QgsRasterShaderFunction.
Definition at line 112 of file qgspseudocolorshader.cpp.
References QgsRasterShaderFunction::mMaximumValue, QgsRasterShaderFunction::mMinimumMaximumRange, QgsRasterShaderFunction::mMinimumValue, and setClassBreaks().
bool QgsPseudoColorShader::shade (double theValue, int * theReturnRedValue, int * theReturnGreenValue, int * theReturnBlueValue)
generates and new RGB value based on one input value
Definition at line 31 of file qgspseudocolorshader.cpp.
References mClassBreakMax1, mClassBreakMax2, mClassBreakMin1, mClassBreakMin2, mClassBreakMin3, QgsRasterShaderFunction::mMaximumValue, QgsRasterShaderFunction::mMinimumMaximumRange, and QgsRasterShaderFunction::mMinimumValue.
bool QgsPseudoColorShader::shade (double theRedValue, double theGreenValue, double theBlueValue, int * theReturnRedValue, int * theReturnGreenValue, int * theReturnBlueValue)
generates and new RGB value based on original RGB value
Definition at line 71 of file qgspseudocolorshader.cpp.
Member Data Documentation
double QgsPseudoColorShader::mBreakSize private
Definition at line 56 of file qgspseudocolorshader.h.
Referenced by setClassBreaks().
double QgsPseudoColorShader::mClassBreakMax1 private
Definition at line 58 of file qgspseudocolorshader.h.
Referenced by setClassBreaks(), and shade().
double QgsPseudoColorShader::mClassBreakMax2 private
Definition at line 60 of file qgspseudocolorshader.h.
Referenced by setClassBreaks(), and shade().
double QgsPseudoColorShader::mClassBreakMin1 private
Definition at line 57 of file qgspseudocolorshader.h.
Referenced by setClassBreaks(), and shade().
double QgsPseudoColorShader::mClassBreakMin2 private
Definition at line 59 of file qgspseudocolorshader.h.
Referenced by setClassBreaks(), and shade().
double QgsPseudoColorShader::mClassBreakMin3 private
Definition at line 61 of file qgspseudocolorshader.h.
Referenced by setClassBreaks(), and shade().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/raster/qgspseudocolorshader.h
/tmp/buildd/qgis-2.0.1/src/core/raster/qgspseudocolorshader.cpp