QGIS API Documentation: QgsDetailedItemWidget Class Reference
QgsDetailedItemWidget Class Reference
QGIS gui library.
A widget renderer for detailed item views.
#include <qgsdetaileditemwidget.h>
Public Member Functions
QgsDetailedItemWidget (QWidget *parent=0)
~QgsDetailedItemWidget ()
void setData (QgsDetailedItemData theData)
void setChecked (bool theFlag)
Private Attributes
QgsDetailedItemData mData
Detailed Description
A widget renderer for detailed item views.
See Also
also QgsDetailedItem and QgsDetailedItemData.
Definition at line 27 of file qgsdetaileditemwidget.h.
Constructor & Destructor Documentation
QgsDetailedItemWidget::QgsDetailedItemWidget (QWidget * parent = 0)
Definition at line 19 of file qgsdetaileditemwidget.cpp.
QgsDetailedItemWidget::~QgsDetailedItemWidget ()
Definition at line 26 of file qgsdetaileditemwidget.cpp.
Member Function Documentation
void QgsDetailedItemWidget::setChecked (bool theFlag)
Definition at line 40 of file qgsdetaileditemwidget.cpp.
Referenced by QgsDetailedItemDelegate::paintAsWidget().
void QgsDetailedItemWidget::setData (QgsDetailedItemData theData)
Definition at line 30 of file qgsdetaileditemwidget.cpp.
References QgsDetailedItemData::category(), QgsDetailedItemData::detail(), QgsDetailedItemData::icon(), QgsDetailedItemData::isCheckable(), QgsDetailedItemData::isChecked(), and QgsDetailedItemData::title().
Referenced by QgsDetailedItemDelegate::paintAsWidget().
Member Data Documentation
QgsDetailedItemData QgsDetailedItemWidget::mData private
Definition at line 37 of file qgsdetaileditemwidget.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/gui/qgsdetaileditemwidget.h
/tmp/buildd/qgis-2.0.1/src/gui/qgsdetaileditemwidget.cpp