QGIS API Documentation: QgsVectorColorRampV2 Class Reference
QgsVectorColorRampV2 Class Reference
#include <qgsvectorcolorrampv2.h>
Public Member Functions
virtual ~QgsVectorColorRampV2 ()
virtual int count () const =0
virtual double value (int index) const =0
virtual QColor color (double value) const =0
virtual QString type () const =0
virtual QgsVectorColorRampV2 * clone () const =0
virtual QgsStringMap properties () const =0
Detailed Description
Definition at line 24 of file qgsvectorcolorrampv2.h.
Constructor & Destructor Documentation
virtual QgsVectorColorRampV2::~QgsVectorColorRampV2 () inline virtual
Definition at line 27 of file qgsvectorcolorrampv2.h.
Member Function Documentation
virtual QgsVectorColorRampV2* QgsVectorColorRampV2::clone () const pure virtual
Implemented in QgsCptCityColorRampV2, QgsVectorColorBrewerColorRampV2, QgsVectorRandomColorRampV2, and QgsVectorGradientColorRampV2.
Referenced by QgsGraduatedSymbolRendererV2::clone(), QgsCategorizedSymbolRendererV2::clone(), QgsStyleV2::colorRamp(), and QgsGraduatedSymbolRendererV2::createRenderer().
virtual QColor QgsVectorColorRampV2::color (double value) const pure virtual
Implemented in QgsVectorColorBrewerColorRampV2, QgsVectorRandomColorRampV2, and QgsVectorGradientColorRampV2.
Referenced by QgsSymbolLayerV2Utils::colorRampPreviewPixmap(), QgsGraduatedSymbolRendererV2::createRenderer(), QgsSingleBandPseudoColorRendererWidget::on_mClassifyButton_clicked(), QgsVectorGradientColorRampV2::setColor1(), QgsVectorGradientColorRampV2::setColor2(), and QgsGraduatedSymbolRendererV2::updateColorRamp().
virtual int QgsVectorColorRampV2::count () const pure virtual
Implemented in QgsVectorColorBrewerColorRampV2, QgsVectorRandomColorRampV2, and QgsVectorGradientColorRampV2.
Referenced by QgsSingleBandPseudoColorRendererWidget::on_mClassifyButton_clicked().
virtual QgsStringMap QgsVectorColorRampV2::properties () const pure virtual
Implemented in QgsCptCityColorRampV2, QgsVectorColorBrewerColorRampV2, QgsVectorRandomColorRampV2, and QgsVectorGradientColorRampV2.
Referenced by QgsSymbolLayerV2Utils::saveColorRamp().
virtual QString QgsVectorColorRampV2::type () const pure virtual
Implemented in QgsCptCityColorRampV2, QgsVectorColorBrewerColorRampV2, QgsVectorRandomColorRampV2, and QgsVectorGradientColorRampV2.
Referenced by QgsSymbolLayerV2Utils::saveColorRamp().
virtual double QgsVectorColorRampV2::value (int index) const pure virtual
Implemented in QgsVectorColorBrewerColorRampV2, QgsVectorRandomColorRampV2, and QgsVectorGradientColorRampV2.
Referenced by QgsSingleBandPseudoColorRendererWidget::on_mClassifyButton_clicked().
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsvectorcolorrampv2.h