QGIS API Documentation: QgsNewVectorLayerDialog Class Reference
QgsNewVectorLayerDialog Class Reference
#include <qgsnewvectorlayerdialog.h>
Public Member Functions
QgsNewVectorLayerDialog (QWidget *parent=0, Qt::WFlags fl=QgisGui::ModalDialogFlags)
~QgsNewVectorLayerDialog ()
QGis::WkbType selectedType () const
Returns the selected geometry type.
void attributes (QList< QPair< QString, QString > > &at) const
Appends the chosen attribute names and types to at.
QString selectedFileFormat () const
Returns the file format for storage.
int selectedCrsId () const
Returns the selected crs id.
Static Public Member Functions
static QString runAndCreateLayer (QWidget *parent=0, QString *enc=0)
Protected Slots
void on_mAddAttributeButton_clicked ()
void on_mRemoveAttributeButton_clicked ()
void on_mTypeBox_currentIndexChanged (int index)
void on_pbnChangeSpatialRefSys_clicked ()
void on_buttonBox_helpRequested ()
void nameChanged (QString)
void selectionChanged ()
Private Attributes
QPushButton * mOkButton
int mCrsId
Detailed Description
Definition at line 26 of file qgsnewvectorlayerdialog.h.
Constructor & Destructor Documentation
QgsNewVectorLayerDialog::QgsNewVectorLayerDialog (QWidget * parent = 0, Qt::WFlags fl = QgisGui::ModalDialogFlags)
Definition at line 32 of file qgsnewvectorlayerdialog.cpp.
References QgsCoordinateReferenceSystem::authid(), QgsCoordinateReferenceSystem::createFromOgcWmsCrs(), QgsCoordinateReferenceSystem::description(), GEO_EPSG_CRS_AUTHID, QgsApplication::getThemeIcon(), mCrsId, mOkButton, nameChanged(), selectionChanged(), QgsCoordinateReferenceSystem::srsid(), tr, and QgsCoordinateReferenceSystem::validate().
QgsNewVectorLayerDialog::~QgsNewVectorLayerDialog ()
Definition at line 83 of file qgsnewvectorlayerdialog.cpp.
Member Function Documentation
void QgsNewVectorLayerDialog::attributes (QList< QPair< QString, QString > > & at) const
Appends the chosen attribute names and types to at.
Definition at line 186 of file qgsnewvectorlayerdialog.cpp.
References QgsDebugMsg.
Referenced by runAndCreateLayer().
void QgsNewVectorLayerDialog::nameChanged (QString name) protected slot
Definition at line 206 of file qgsnewvectorlayerdialog.cpp.
Referenced by QgsNewVectorLayerDialog().
void QgsNewVectorLayerDialog::on_buttonBox_helpRequested () inline protected slot
Definition at line 51 of file qgsnewvectorlayerdialog.h.
References QgsContextHelp::run().
void QgsNewVectorLayerDialog::on_mAddAttributeButton_clicked () protected slot
Definition at line 143 of file qgsnewvectorlayerdialog.cpp.
References mOkButton.
void QgsNewVectorLayerDialog::on_mRemoveAttributeButton_clicked () protected slot
Definition at line 158 of file qgsnewvectorlayerdialog.cpp.
References mOkButton.
void QgsNewVectorLayerDialog::on_mTypeBox_currentIndexChanged (int index) protected slot
Definition at line 89 of file qgsnewvectorlayerdialog.cpp.
References QgsDebugMsg.
void QgsNewVectorLayerDialog::on_pbnChangeSpatialRefSys_clicked () protected slot
Definition at line 167 of file qgsnewvectorlayerdialog.cpp.
References QgsCoordinateReferenceSystem::authid(), QgsCoordinateReferenceSystem::createFromOgcWmsCrs(), QgsCoordinateReferenceSystem::description(), mCrsId, QgsGenericProjectionSelector::selectedAuthId(), QgsGenericProjectionSelector::setMessage(), QgsGenericProjectionSelector::setSelectedCrsId(), and QgsCoordinateReferenceSystem::srsid().
QString QgsNewVectorLayerDialog::runAndCreateLayer (QWidget * parent = 0, QString * enc = 0) static
Definition at line 218 of file qgsnewvectorlayerdialog.cpp.
References attributes(), cast_to_fptr, QgsEncodingFileDialog::encoding(), QgsProviderRegistry::instance(), QgsCoordinateReferenceSystem::InternalCrsId, QgsProviderRegistry::library(), QgsDebugMsg, selectedCrsId(), selectedFileFormat(), selectedType(), tr, and QGis::WKBUnknown.
int QgsNewVectorLayerDialog::selectedCrsId () const
Returns the selected crs id.
Definition at line 138 of file qgsnewvectorlayerdialog.cpp.
References mCrsId.
Referenced by runAndCreateLayer().
QString QgsNewVectorLayerDialog::selectedFileFormat () const
Returns the file format for storage.
Definition at line 199 of file qgsnewvectorlayerdialog.cpp.
Referenced by runAndCreateLayer().
QGis::WkbType QgsNewVectorLayerDialog::selectedType () const
Returns the selected geometry type.
Definition at line 121 of file qgsnewvectorlayerdialog.cpp.
References QGis::WKBLineString, QGis::WKBPoint, QGis::WKBPolygon, and QGis::WKBUnknown.
Referenced by runAndCreateLayer().
void QgsNewVectorLayerDialog::selectionChanged () protected slot
Definition at line 211 of file qgsnewvectorlayerdialog.cpp.
Referenced by QgsNewVectorLayerDialog().
Member Data Documentation
int QgsNewVectorLayerDialog::mCrsId private
Definition at line 57 of file qgsnewvectorlayerdialog.h.
Referenced by on_pbnChangeSpatialRefSys_clicked(), QgsNewVectorLayerDialog(), and selectedCrsId().
QPushButton* QgsNewVectorLayerDialog::mOkButton private
Definition at line 56 of file qgsnewvectorlayerdialog.h.
Referenced by on_mAddAttributeButton_clicked(), on_mRemoveAttributeButton_clicked(), and QgsNewVectorLayerDialog().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/gui/qgsnewvectorlayerdialog.h
/tmp/buildd/qgis-2.0.1/src/gui/qgsnewvectorlayerdialog.cpp