QGIS API Documentation: QgsPalettedRendererWidget Class Reference
QgsPalettedRendererWidget Class Reference
#include <qgspalettedrendererwidget.h>
Public Member Functions
QgsPalettedRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent=QgsRectangle())
~QgsPalettedRendererWidget ()
QgsRasterRenderer * renderer ()
void setFromRenderer (const QgsRasterRenderer *r)
Public Member Functions inherited from QgsRasterRendererWidget
QgsRasterRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent)
virtual ~QgsRasterRendererWidget ()
void setRasterLayer (QgsRasterLayer *layer)
const QgsRasterLayer * rasterLayer () const
virtual QString min (int index=0)
virtual QString max (int index=0)
virtual void setMin (QString value, int index=0)
virtual void setMax (QString value, int index=0)
virtual QString stdDev ()
virtual void setStdDev (QString value)
virtual int selectedBand (int index=0)
Static Public Member Functions
static QgsRasterRendererWidget * create (QgsRasterLayer *layer, const QgsRectangle &theExtent)
Private Slots
void on_mTreeWidget_itemDoubleClicked (QTreeWidgetItem *item, int column)
Additional Inherited Members
Public Types inherited from QgsRasterRendererWidget
enum LoadMinMaxAlgo { Estimate, Actual, CurrentExtent, CumulativeCut }
Protected Member Functions inherited from QgsRasterRendererWidget
QString displayBandName (int band) const
Returns a band name for display.
Protected Attributes inherited from QgsRasterRendererWidget
QgsRasterLayer * mRasterLayer
QgsRectangle mExtent
Current extent.
Detailed Description
Definition at line 26 of file qgspalettedrendererwidget.h.
Constructor & Destructor Documentation
QgsPalettedRendererWidget::QgsPalettedRendererWidget (QgsRasterLayer * layer, const QgsRectangle & extent = QgsRectangle())
Definition at line 23 of file qgspalettedrendererwidget.cpp.
References QgsRasterInterface::bandCount(), QgsRasterLayer::dataProvider(), QgsRasterRendererWidget::displayBandName(), QgsRasterRendererWidget::mRasterLayer, QgsRasterLayer::renderer(), and setFromRenderer().
QgsPalettedRendererWidget::~QgsPalettedRendererWidget ()
Definition at line 46 of file qgspalettedrendererwidget.cpp.
Member Function Documentation
static QgsRasterRendererWidget* QgsPalettedRendererWidget::create (QgsRasterLayer * layer, const QgsRectangle & theExtent) inline static
Definition at line 32 of file qgspalettedrendererwidget.h.
void QgsPalettedRendererWidget::on_mTreeWidget_itemDoubleClicked (QTreeWidgetItem * item, int column) private slot
Definition at line 63 of file qgspalettedrendererwidget.cpp.
QgsRasterRenderer * QgsPalettedRendererWidget::renderer () virtual
Implements QgsRasterRendererWidget.
Definition at line 51 of file qgspalettedrendererwidget.cpp.
References QgsRasterLayer::dataProvider(), and QgsRasterRendererWidget::mRasterLayer.
void QgsPalettedRendererWidget::setFromRenderer (const QgsRasterRenderer * r)
Definition at line 75 of file qgspalettedrendererwidget.cpp.
References QgsPalettedRasterRenderer::colors(), QgsRasterDataProvider::colorTable(), QgsRasterLayer::dataProvider(), QgsRasterRendererWidget::mRasterLayer, and QgsPalettedRasterRenderer::nColors().
Referenced by QgsPalettedRendererWidget().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/gui/raster/qgspalettedrendererwidget.h
/tmp/buildd/qgis-2.0.1/src/gui/raster/qgspalettedrendererwidget.cpp