QGIS API Documentation: QgsDetailedItemData Class Reference
QgsDetailedItemData Class Reference
QGIS gui library.
This class is the data only representation of a QgsDetailedItemWidget, designed to be used in custom views.
#include <qgsdetaileditemdata.h>
Public Member Functions
QgsDetailedItemData ()
~QgsDetailedItemData ()
void setTitle (const QString theTitle)
void setDetail (const QString theDetail)
void setCategory (const QString theCategory)
void setIcon (const QPixmap theIcon)
void setCheckable (const bool theFlag)
void setChecked (const bool theFlag)
void setEnabled (bool theFlag)
void setRenderAsWidget (bool theFlag)
This is a hint to the delegate to render using a widget rather than manually painting every part of the list item.
QString title () const
QString detail () const
QString category () const
QPixmap icon () const
bool isCheckable () const
bool isChecked () const
bool isEnabled () const
bool isRenderedAsWidget () const
Private Attributes
QString mTitle
QString mDetail
QString mCategory
QString mLibraryName
QPixmap mPixmap
bool mCheckableFlag
bool mCheckedFlag
bool mEnabledFlag
bool mRenderAsWidgetFlag
Detailed Description
This class is the data only representation of a QgsDetailedItemWidget, designed to be used in custom views.
Definition at line 29 of file qgsdetaileditemdata.h.
Constructor & Destructor Documentation
QgsDetailedItemData::QgsDetailedItemData ()
Definition at line 19 of file qgsdetaileditemdata.cpp.
References mEnabledFlag, and mRenderAsWidgetFlag.
QgsDetailedItemData::~QgsDetailedItemData ()
Definition at line 25 of file qgsdetaileditemdata.cpp.
Member Function Documentation
QString QgsDetailedItemData::category () const
Definition at line 74 of file qgsdetaileditemdata.cpp.
References mCategory.
Referenced by QgsDetailedItemDelegate::paintManually(), and QgsDetailedItemWidget::setData().
QString QgsDetailedItemData::detail () const
Definition at line 69 of file qgsdetaileditemdata.cpp.
References mDetail.
Referenced by QgsDetailedItemDelegate::height(), QgsDetailedItemDelegate::paintManually(), and QgsDetailedItemWidget::setData().
QPixmap QgsDetailedItemData::icon () const
Definition at line 79 of file qgsdetaileditemdata.cpp.
References mPixmap.
Referenced by QgsDetailedItemDelegate::paintManually(), and QgsDetailedItemWidget::setData().
bool QgsDetailedItemData::isCheckable () const
Definition at line 84 of file qgsdetaileditemdata.cpp.
References mCheckableFlag.
Referenced by QgsDetailedItemDelegate::paintManually(), and QgsDetailedItemWidget::setData().
bool QgsDetailedItemData::isChecked () const
Definition at line 89 of file qgsdetaileditemdata.cpp.
References mCheckedFlag.
Referenced by QgsDetailedItemDelegate::paintAsWidget(), QgsDetailedItemDelegate::paintManually(), and QgsDetailedItemWidget::setData().
bool QgsDetailedItemData::isEnabled () const
Definition at line 104 of file qgsdetaileditemdata.cpp.
References mEnabledFlag.
Referenced by QgsDetailedItemDelegate::paintManually().
bool QgsDetailedItemData::isRenderedAsWidget () const
Definition at line 94 of file qgsdetaileditemdata.cpp.
References mRenderAsWidgetFlag.
Referenced by QgsDetailedItemDelegate::paint(), and QgsDetailedItemDelegate::sizeHint().
void QgsDetailedItemData::setCategory (const QString theCategory)
Definition at line 39 of file qgsdetaileditemdata.cpp.
References mCategory.
void QgsDetailedItemData::setCheckable (const bool theFlag)
Definition at line 49 of file qgsdetaileditemdata.cpp.
References mCheckableFlag.
void QgsDetailedItemData::setChecked (const bool theFlag)
Definition at line 54 of file qgsdetaileditemdata.cpp.
References mCheckedFlag.
void QgsDetailedItemData::setDetail (const QString theDetail)
Definition at line 34 of file qgsdetaileditemdata.cpp.
References mDetail.
void QgsDetailedItemData::setEnabled (bool theFlag)
Definition at line 99 of file qgsdetaileditemdata.cpp.
References mEnabledFlag.
void QgsDetailedItemData::setIcon (const QPixmap theIcon)
Definition at line 44 of file qgsdetaileditemdata.cpp.
References mPixmap.
void QgsDetailedItemData::setRenderAsWidget (bool theFlag)
This is a hint to the delegate to render using a widget rather than manually painting every part of the list item.
Note
the delegate may completely ignore this depending on the delegate implementation.
Definition at line 59 of file qgsdetaileditemdata.cpp.
References mRenderAsWidgetFlag.
void QgsDetailedItemData::setTitle (const QString theTitle)
Definition at line 29 of file qgsdetaileditemdata.cpp.
References mTitle.
QString QgsDetailedItemData::title () const
Definition at line 64 of file qgsdetaileditemdata.cpp.
References mTitle.
Referenced by QgsDetailedItemDelegate::paintManually(), and QgsDetailedItemWidget::setData().
Member Data Documentation
QString QgsDetailedItemData::mCategory private
Definition at line 61 of file qgsdetaileditemdata.h.
Referenced by category(), and setCategory().
bool QgsDetailedItemData::mCheckableFlag private
Definition at line 64 of file qgsdetaileditemdata.h.
Referenced by isCheckable(), and setCheckable().
bool QgsDetailedItemData::mCheckedFlag private
Definition at line 65 of file qgsdetaileditemdata.h.
Referenced by isChecked(), and setChecked().
QString QgsDetailedItemData::mDetail private
Definition at line 60 of file qgsdetaileditemdata.h.
Referenced by detail(), and setDetail().
bool QgsDetailedItemData::mEnabledFlag private
Definition at line 66 of file qgsdetaileditemdata.h.
Referenced by isEnabled(), QgsDetailedItemData(), and setEnabled().
QString QgsDetailedItemData::mLibraryName private
Definition at line 62 of file qgsdetaileditemdata.h.
QPixmap QgsDetailedItemData::mPixmap private
Definition at line 63 of file qgsdetaileditemdata.h.
Referenced by icon(), and setIcon().
bool QgsDetailedItemData::mRenderAsWidgetFlag private
Definition at line 67 of file qgsdetaileditemdata.h.
Referenced by isRenderedAsWidget(), QgsDetailedItemData(), and setRenderAsWidget().
QString QgsDetailedItemData::mTitle private
Definition at line 59 of file qgsdetaileditemdata.h.
Referenced by setTitle(), and title().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/gui/qgsdetaileditemdata.h
/tmp/buildd/qgis-2.0.1/src/gui/qgsdetaileditemdata.cpp