QGIS API Documentation: QgsVectorLayerUndoCommand Class Reference
QgsVectorLayerUndoCommand Class Reference
#include <qgsvectorlayerundocommand.h>
Public Member Functions
QgsVectorLayerUndoCommand (QgsVectorLayerEditBuffer *buffer)
QgsVectorLayer * layer ()
QgsGeometryCache * cache ()
virtual int id () const
virtual bool mergeWith (QUndoCommand *)
Protected Attributes
QgsVectorLayerEditBuffer * mBuffer
Detailed Description
Definition at line 35 of file qgsvectorlayerundocommand.h.
Constructor & Destructor Documentation
QgsVectorLayerUndoCommand::QgsVectorLayerUndoCommand (QgsVectorLayerEditBuffer * buffer) inline
Definition at line 38 of file qgsvectorlayerundocommand.h.
Member Function Documentation
QgsGeometryCache* QgsVectorLayerUndoCommand::cache () inline
Definition at line 43 of file qgsvectorlayerundocommand.h.
References QgsVectorLayer::cache(), QgsVectorLayerEditBuffer::L, and mBuffer.
Referenced by QgsVectorLayerUndoCommandChangeGeometry::QgsVectorLayerUndoCommandChangeGeometry(), QgsVectorLayerUndoCommandAddFeature::redo(), QgsVectorLayerUndoCommandChangeGeometry::redo(), QgsVectorLayerUndoCommandAddFeature::undo(), and QgsVectorLayerUndoCommandChangeGeometry::undo().
virtual int QgsVectorLayerUndoCommand::id () const inline virtual
Reimplemented in QgsVectorLayerUndoCommandChangeGeometry.
Definition at line 45 of file qgsvectorlayerundocommand.h.
QgsVectorLayer* QgsVectorLayerUndoCommand::layer () inline
Definition at line 42 of file qgsvectorlayerundocommand.h.
References QgsVectorLayerEditBuffer::L, and mBuffer.
Referenced by QgsVectorLayerUndoCommandAddAttribute::QgsVectorLayerUndoCommandAddAttribute(), QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute(), QgsVectorLayerUndoCommandChangeGeometry::undo(), QgsVectorLayerUndoCommandChangeAttribute::undo(), and QgsVectorLayerUndoCommandAddAttribute::undo().
virtual bool QgsVectorLayerUndoCommand::mergeWith (QUndoCommand *) inline virtual
Definition at line 46 of file qgsvectorlayerundocommand.h.
Member Data Documentation
QgsVectorLayerEditBuffer* QgsVectorLayerUndoCommand::mBuffer protected
Definition at line 49 of file qgsvectorlayerundocommand.h.
Referenced by cache(), layer(), QgsVectorLayerUndoCommandChangeAttribute::QgsVectorLayerUndoCommandChangeAttribute(), QgsVectorLayerUndoCommandChangeGeometry::QgsVectorLayerUndoCommandChangeGeometry(), QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute(), QgsVectorLayerUndoCommandDeleteFeature::QgsVectorLayerUndoCommandDeleteFeature(), QgsVectorLayerUndoCommandAddFeature::redo(), QgsVectorLayerUndoCommandDeleteFeature::redo(), QgsVectorLayerUndoCommandChangeGeometry::redo(), QgsVectorLayerUndoCommandChangeAttribute::redo(), QgsVectorLayerUndoCommandAddAttribute::redo(), QgsVectorLayerUndoCommandDeleteAttribute::redo(), QgsVectorLayerUndoCommandAddFeature::undo(), QgsVectorLayerUndoCommandDeleteFeature::undo(), QgsVectorLayerUndoCommandChangeGeometry::undo(), QgsVectorLayerUndoCommandChangeAttribute::undo(), QgsVectorLayerUndoCommandAddAttribute::undo(), and QgsVectorLayerUndoCommandDeleteAttribute::undo().
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.0.1/src/core/qgsvectorlayerundocommand.h