QGIS API Documentation: QgsRendererRangeV2 Class Reference
QgsRendererRangeV2 Class Reference
#include <qgsgraduatedsymbolrendererv2.h>
Public Member Functions
QgsRendererRangeV2 ()
QgsRendererRangeV2 (double lowerValue, double upperValue, QgsSymbolV2 *symbol, QString label)
QgsRendererRangeV2 (const QgsRendererRangeV2 &range)
~QgsRendererRangeV2 ()
QgsRendererRangeV2 & operator= (const QgsRendererRangeV2 &range)
double lowerValue () const
double upperValue () const
QgsSymbolV2 * symbol () const
QString label () const
void setSymbol (QgsSymbolV2 *s)
void setLabel (QString label)
void setLowerValue (double lowerValue)
void setUpperValue (double upperValue)
QString dump () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
Protected Attributes
double mLowerValue
double mUpperValue
QgsSymbolV2 * mSymbol
QString mLabel
Detailed Description
Definition at line 21 of file qgsgraduatedsymbolrendererv2.h.
Constructor & Destructor Documentation
QgsRendererRangeV2::QgsRendererRangeV2 ()
Definition at line 33 of file qgsgraduatedsymbolrendererv2.cpp.
QgsRendererRangeV2::QgsRendererRangeV2 (double lowerValue, double upperValue, QgsSymbolV2 * symbol, QString label)
Definition at line 38 of file qgsgraduatedsymbolrendererv2.cpp.
QgsRendererRangeV2::QgsRendererRangeV2 (const QgsRendererRangeV2 & range)
Definition at line 46 of file qgsgraduatedsymbolrendererv2.cpp.
References QgsSymbolV2::clone(), and mSymbol.
QgsRendererRangeV2::~QgsRendererRangeV2 ()
Definition at line 54 of file qgsgraduatedsymbolrendererv2.cpp.
References mSymbol.
Member Function Documentation
QString QgsRendererRangeV2::dump () const
Definition at line 115 of file qgsgraduatedsymbolrendererv2.cpp.
References QgsSymbolV2::dump(), mLabel, mLowerValue, mSymbol, and mUpperValue.
QString QgsRendererRangeV2::label () const
Definition at line 87 of file qgsgraduatedsymbolrendererv2.cpp.
References mLabel.
Referenced by labelLessThan(), QgsGraduatedSymbolRendererV2::legendSymbolItems(), QgsGraduatedSymbolRendererV2::legendSymbologyItems(), QgsGraduatedSymbolRendererV2::save(), and setLabel().
double QgsRendererRangeV2::lowerValue () const
Definition at line 72 of file qgsgraduatedsymbolrendererv2.cpp.
References mLowerValue.
Referenced by QgsRuleBasedRendererV2::refineRuleRanges(), QgsGraduatedSymbolRendererV2::save(), setLowerValue(), and valueLessThan().
QgsRendererRangeV2 & QgsRendererRangeV2::operator= (const QgsRendererRangeV2 & range)
Definition at line 59 of file qgsgraduatedsymbolrendererv2.cpp.
References QgsSymbolV2::clone(), mLabel, mLowerValue, mSymbol, and mUpperValue.
void QgsRendererRangeV2::setLabel (QString label)
Definition at line 100 of file qgsgraduatedsymbolrendererv2.cpp.
References label(), and mLabel.
void QgsRendererRangeV2::setLowerValue (double lowerValue)
Definition at line 110 of file qgsgraduatedsymbolrendererv2.cpp.
References lowerValue(), and mLowerValue.
void QgsRendererRangeV2::setSymbol (QgsSymbolV2 * s)
Definition at line 92 of file qgsgraduatedsymbolrendererv2.cpp.
References mSymbol.
void QgsRendererRangeV2::setUpperValue (double upperValue)
Definition at line 105 of file qgsgraduatedsymbolrendererv2.cpp.
References mUpperValue, and upperValue().
QgsSymbolV2 * QgsRendererRangeV2::symbol () const
Definition at line 82 of file qgsgraduatedsymbolrendererv2.cpp.
References mSymbol.
Referenced by QgsGraduatedSymbolRendererV2::legendSymbolItems(), QgsGraduatedSymbolRendererV2::legendSymbologyItems(), QgsRuleBasedRendererV2::refineRuleRanges(), QgsGraduatedSymbolRendererV2::save(), QgsGraduatedSymbolRendererV2::setScaleMethod(), QgsGraduatedSymbolRendererV2::updateColorRamp(), and QgsGraduatedSymbolRendererV2::updateSymbols().
void QgsRendererRangeV2::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const
Definition at line 120 of file qgsgraduatedsymbolrendererv2.cpp.
References QgsSymbolLayerV2Utils::createFunctionElement(), mLabel, mLowerValue, mSymbol, mUpperValue, and QgsSymbolV2::toSld().
double QgsRendererRangeV2::upperValue () const
Definition at line 77 of file qgsgraduatedsymbolrendererv2.cpp.
References mUpperValue.
Referenced by QgsRuleBasedRendererV2::refineRuleRanges(), QgsGraduatedSymbolRendererV2::save(), and setUpperValue().
Member Data Documentation
QString QgsRendererRangeV2::mLabel protected
Definition at line 51 of file qgsgraduatedsymbolrendererv2.h.
Referenced by dump(), label(), operator=(), setLabel(), and toSld().
double QgsRendererRangeV2::mLowerValue protected
Definition at line 49 of file qgsgraduatedsymbolrendererv2.h.
Referenced by dump(), lowerValue(), operator=(), setLowerValue(), and toSld().
QgsSymbolV2* QgsRendererRangeV2::mSymbol protected
Definition at line 50 of file qgsgraduatedsymbolrendererv2.h.
Referenced by dump(), operator=(), QgsRendererRangeV2(), setSymbol(), symbol(), toSld(), and ~QgsRendererRangeV2().
double QgsRendererRangeV2::mUpperValue protected
Definition at line 49 of file qgsgraduatedsymbolrendererv2.h.
Referenced by dump(), operator=(), setUpperValue(), toSld(), and upperValue().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsgraduatedsymbolrendererv2.h
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsgraduatedsymbolrendererv2.cpp