QGIS API Documentation: QgsCptCityColorRampItem Class Reference
QgsCptCityColorRampItem Class Reference
Item that represents a layer that can be opened with one of the providers.
#include <qgscptcityarchive.h>
Public Member Functions
QgsCptCityColorRampItem (QgsCptCityDataItem *parent, QString name, QString path, QString variantName=QString(), bool initialize=false)
QgsCptCityColorRampItem (QgsCptCityDataItem *parent, QString name, QString path, QStringList variantList, bool initialize=false)
~QgsCptCityColorRampItem ()
virtual bool equal (const QgsCptCityDataItem *other)
virtual int leafCount () const
const QgsCptCityColorRampV2 & ramp () const
QIcon icon ()
QIcon icon (const QSize &size)
void init ()
Public Member Functions inherited from QgsCptCityDataItem
QgsCptCityDataItem (QgsCptCityDataItem::Type type, QgsCptCityDataItem *parent, QString name, QString path)
virtual ~QgsCptCityDataItem ()
bool hasChildren ()
int rowCount ()
virtual void refresh ()
virtual QVector
< QgsCptCityDataItem * > createChildren ()
virtual void populate ()
bool isPopulated ()
virtual void addChildItem (QgsCptCityDataItem *child, bool refresh=false)
virtual void deleteChildItem (QgsCptCityDataItem *child)
virtual QgsCptCityDataItem * removeChildItem (QgsCptCityDataItem *child)
virtual QWidget * paramWidget ()
virtual QList< QAction * > actions ()
virtual bool acceptDrop ()
virtual bool handleDrop (const QMimeData *, Qt::DropAction)
Type type () const
QgsCptCityDataItem * parent () const
void setParent (QgsCptCityDataItem *parent)
QVector< QgsCptCityDataItem * > children () const
QString name () const
QString path () const
QString info () const
QString shortInfo () const
void setIcon (QIcon icon)
void setToolTip (QString msg)
QString toolTip () const
bool isValid ()
Protected Attributes
bool mInitialised
QgsCptCityColorRampV2 mRamp
QList< QIcon > mIcons
Protected Attributes inherited from QgsCptCityDataItem
Type mType
QgsCptCityDataItem * mParent
QVector< QgsCptCityDataItem * > mChildren
bool mPopulated
QString mName
QString mPath
QString mInfo
QString mShortInfo
QString mToolTip
QIcon mIcon
bool mValid
Additional Inherited Members
Public Types inherited from QgsCptCityDataItem
enum Type {
ColorRamp, Collection, Directory, Selection,
AllRamps
}
Public Slots inherited from QgsCptCityDataItem
void emitBeginInsertItems (QgsCptCityDataItem *parent, int first, int last)
void emitEndInsertItems ()
void emitBeginRemoveItems (QgsCptCityDataItem *parent, int first, int last)
void emitEndRemoveItems ()
Signals inherited from QgsCptCityDataItem
void beginInsertItems (QgsCptCityDataItem *parent, int first, int last)
void endInsertItems ()
void beginRemoveItems (QgsCptCityDataItem *parent, int first, int last)
void endRemoveItems ()
Static Public Member Functions inherited from QgsCptCityDataItem
static int findItem (QVector< QgsCptCityDataItem * > items, QgsCptCityDataItem *item)
Detailed Description
Item that represents a layer that can be opened with one of the providers.
Definition at line 195 of file qgscptcityarchive.h.
Constructor & Destructor Documentation
QgsCptCityColorRampItem::QgsCptCityColorRampItem (QgsCptCityDataItem * parent, QString name, QString path, QString variantName = QString(), bool initialize = false)
Definition at line 710 of file qgscptcityarchive.cpp.
References init(), and QgsCptCityDataItem::mPopulated.
QgsCptCityColorRampItem::QgsCptCityColorRampItem (QgsCptCityDataItem * parent, QString name, QString path, QStringList variantList, bool initialize = false)
Definition at line 721 of file qgscptcityarchive.cpp.
References init(), and QgsCptCityDataItem::mPopulated.
QgsCptCityColorRampItem::~QgsCptCityColorRampItem () inline
Definition at line 207 of file qgscptcityarchive.h.
Member Function Documentation
bool QgsCptCityColorRampItem::equal (const QgsCptCityDataItem * other) virtual
Reimplemented from QgsCptCityDataItem.
Definition at line 788 of file qgscptcityarchive.cpp.
References QgsCptCityDataItem::mName, QgsCptCityDataItem::mPath, ramp(), QgsCptCityDataItem::type(), and QgsCptCityColorRampV2::variantName().
QIcon QgsCptCityColorRampItem::icon () virtual
Reimplemented from QgsCptCityDataItem.
Definition at line 801 of file qgscptcityarchive.cpp.
Referenced by icon().
QIcon QgsCptCityColorRampItem::icon (const QSize & size) virtual
Reimplemented from QgsCptCityDataItem.
Definition at line 806 of file qgscptcityarchive.cpp.
References QgsSymbolLayerV2Utils::colorRampPreviewIcon(), QgsVectorGradientColorRampV2::count(), icon(), init(), mIcons, QgsCptCityDataItem::mInfo, mRamp, and QgsCptCityDataItem::mValid.
void QgsCptCityColorRampItem::init ()
Definition at line 733 of file qgscptcityarchive.cpp.
References QgsVectorGradientColorRampV2::count(), QgsCptCityColorRampV2::fileName(), QgsCptCityColorRampV2::hasMultiStops(), QgsVectorGradientColorRampV2::isDiscrete(), QgsCptCityColorRampV2::loadFile(), QgsCptCityDataItem::mInfo, mInitialised, QgsCptCityDataItem::mName, mRamp, QgsCptCityDataItem::mShortInfo, QgsCptCityDataItem::mValid, QgsCptCityDataItem::path(), QgsDebugMsg, QgsCptCityColorRampV2::setVariantName(), tr, QgsCptCityColorRampV2::variantList(), and QgsCptCityColorRampV2::variantName().
Referenced by QgsCptCityCollectionItem::childrenRamps(), icon(), and QgsCptCityColorRampItem().
virtual int QgsCptCityColorRampItem::leafCount () const inline virtual
Reimplemented from QgsCptCityDataItem.
Definition at line 212 of file qgscptcityarchive.h.
const QgsCptCityColorRampV2& QgsCptCityColorRampItem::ramp () const inline
Definition at line 215 of file qgscptcityarchive.h.
Referenced by equal().
Member Data Documentation
QList< QIcon > QgsCptCityColorRampItem::mIcons protected
Definition at line 224 of file qgscptcityarchive.h.
Referenced by icon().
bool QgsCptCityColorRampItem::mInitialised protected
Definition at line 222 of file qgscptcityarchive.h.
Referenced by init().
QgsCptCityColorRampV2 QgsCptCityColorRampItem::mRamp protected
Definition at line 223 of file qgscptcityarchive.h.
Referenced by icon(), and init().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgscptcityarchive.h
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgscptcityarchive.cpp