QGIS API Documentation: QgsDirectoryItem Class Reference
QgsDirectoryItem Class Reference
A directory: contains subdirectories and layers.
#include <qgsdataitem.h>
Public Types
enum Column {
Name, Size, Date, Permissions,
Owner, Group, Type
}
Public Member Functions
QgsDirectoryItem (QgsDataItem *parent, QString name, QString path)
~QgsDirectoryItem ()
QVector< QgsDataItem * > createChildren ()
virtual bool equal (const QgsDataItem *other)
virtual QWidget * paramWidget ()
Public Member Functions inherited from QgsDataCollectionItem
QgsDataCollectionItem (QgsDataItem *parent, QString name, QString path=QString::null)
~QgsDataCollectionItem ()
void setPopulated ()
void addChild (QgsDataItem *item)
Public Member Functions inherited from QgsDataItem
QgsDataItem (QgsDataItem::Type type, QgsDataItem *parent, QString name, QString path)
virtual ~QgsDataItem ()
bool hasChildren ()
int rowCount ()
virtual void refresh ()
virtual void populate ()
bool isPopulated ()
virtual void addChildItem (QgsDataItem *child, bool refresh=false)
virtual void deleteChildItem (QgsDataItem *child)
virtual QgsDataItem * removeChildItem (QgsDataItem *child)
virtual QList< QAction * > actions ()
virtual bool acceptDrop ()
virtual bool handleDrop (const QMimeData *, Qt::DropAction)
virtual bool setCrs (QgsCoordinateReferenceSystem crs)
virtual Capability capabilities ()
Type type () const
QgsDataItem * parent () const
void setParent (QgsDataItem *parent)
QVector< QgsDataItem * > children () const
QIcon icon () const
QString name () const
QString path () const
void setIcon (QIcon icon)
void setToolTip (QString msg)
QString toolTip () const
Static Public Attributes
static QVector< QLibrary * > mLibraries = QVector<QLibrary*>()
Additional Inherited Members
Public Slots inherited from QgsDataItem
void emitBeginInsertItems (QgsDataItem *parent, int first, int last)
void emitEndInsertItems ()
void emitBeginRemoveItems (QgsDataItem *parent, int first, int last)
void emitEndRemoveItems ()
Signals inherited from QgsDataItem
void beginInsertItems (QgsDataItem *parent, int first, int last)
void endInsertItems ()
void beginRemoveItems (QgsDataItem *parent, int first, int last)
void endRemoveItems ()
Static Public Member Functions inherited from QgsDataCollectionItem
static const QIcon & iconDir ()
static const QIcon & iconDataCollection ()
Protected Attributes inherited from QgsDataItem
Type mType
QgsDataItem * mParent
QVector< QgsDataItem * > mChildren
bool mPopulated
QString mName
QString mPath
QString mToolTip
QIcon mIcon
Detailed Description
A directory: contains subdirectories and layers.
Definition at line 223 of file qgsdataitem.h.
Member Enumeration Documentation
enum QgsDirectoryItem::Column
Enumerator:
Name
Size
Date
Permissions
Owner
Group
Type
Definition at line 227 of file qgsdataitem.h.
Constructor & Destructor Documentation
QgsDirectoryItem::QgsDirectoryItem (QgsDataItem * parent, QString name, QString path)
Definition at line 406 of file qgsdataitem.cpp.
References cast_to_fptr, QgsDataItem::Directory, QgsDataCollectionItem::iconDir(), QgsProviderRegistry::instance(), QgsDataItem::mIcon, mLibraries, QgsDataItem::mType, QgsDataProvider::NoDataCapabilities, QgsProviderRegistry::providerLibrary(), QgsProviderRegistry::providerList(), and QgsDebugMsg.
Referenced by createChildren().
QgsDirectoryItem::~QgsDirectoryItem ()
Definition at line 447 of file qgsdataitem.cpp.
Member Function Documentation
QVector< QgsDataItem * > QgsDirectoryItem::createChildren () virtual
Reimplemented from QgsDataItem.
Definition at line 451 of file qgsdataitem.cpp.
References QgsDataItem::capabilities(), cast_to_fptr, QgsDataItem::children(), QgsDataProvider::Dir, QgsDataProvider::File, QgsZipItem::itemFromPath(), mLibraries, QgsDataItem::mPath, QgsDataItem::name(), QgsDataItem::path(), QgsDebugMsg, QgsDebugMsgLevel, and QgsDirectoryItem().
bool QgsDirectoryItem::equal (const QgsDataItem * other) virtual
Reimplemented from QgsDataItem.
Definition at line 523 of file qgsdataitem.cpp.
References QgsDataItem::path(), and QgsDataItem::type().
QWidget * QgsDirectoryItem::paramWidget () virtual
Reimplemented from QgsDataItem.
Definition at line 533 of file qgsdataitem.cpp.
References QgsDataItem::mPath.
Member Data Documentation
QVector< QLibrary * > QgsDirectoryItem::mLibraries = QVector<QLibrary*>() static
Note
not available via python bindings
Definition at line 248 of file qgsdataitem.h.
Referenced by createChildren(), and QgsDirectoryItem().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/qgsdataitem.h
/tmp/buildd/qgis-2.0.1/src/core/qgsdataitem.cpp