QGIS API Documentation: QgsRendererV2Registry Class Reference
QgsRendererV2Registry Class Reference
Registry of renderers.
#include <qgsrendererv2registry.h>
Public Member Functions
bool addRenderer (QgsRendererV2AbstractMetadata *metadata)
add a renderer to registry. Takes ownership of the metadata object.
bool removeRenderer (QString rendererName)
remove renderer from registry
QgsRendererV2AbstractMetadata * rendererMetadata (QString rendererName)
get metadata for particular renderer. Returns NULL if not found in registry.
QStringList renderersList ()
return a list of available renderers
Static Public Member Functions
static QgsRendererV2Registry * instance ()
Protected Member Functions
QgsRendererV2Registry ()
protected constructor
~QgsRendererV2Registry ()
Protected Attributes
QMap< QString,
QgsRendererV2AbstractMetadata * > mRenderers
QStringList mRenderersOrder
list to keep order in which renderers have been added
Static Protected Attributes
static QgsRendererV2Registry * mInstance = NULL
Detailed Description
Registry of renderers.
This is a singleton, renderers can be added / removed at any time
Definition at line 136 of file qgsrendererv2registry.h.
Constructor & Destructor Documentation
QgsRendererV2Registry::QgsRendererV2Registry () protected
protected constructor
Definition at line 26 of file qgsrendererv2registry.cpp.
References addRenderer(), QgsPointDisplacementRenderer::create(), QgsSingleSymbolRendererV2::create(), QgsCategorizedSymbolRendererV2::create(), QgsGraduatedSymbolRendererV2::create(), QgsRuleBasedRendererV2::create(), QgsSingleSymbolRendererV2::createFromSld(), QgsRuleBasedRendererV2::createFromSld(), and tr.
Referenced by instance().
QgsRendererV2Registry::~QgsRendererV2Registry () protected
Definition at line 51 of file qgsrendererv2registry.cpp.
References mRenderers.
Member Function Documentation
bool QgsRendererV2Registry::addRenderer (QgsRendererV2AbstractMetadata * metadata)
add a renderer to registry. Takes ownership of the metadata object.
Definition at line 69 of file qgsrendererv2registry.cpp.
References mRenderers, mRenderersOrder, and QgsRendererV2AbstractMetadata::name().
Referenced by QgsRendererV2Registry().
QgsRendererV2Registry * QgsRendererV2Registry::instance () static
Definition at line 60 of file qgsrendererv2registry.cpp.
References mInstance, and QgsRendererV2Registry().
Referenced by QgsFeatureRendererV2::load(), and QgsFeatureRendererV2::loadSld().
bool QgsRendererV2Registry::removeRenderer (QString rendererName)
remove renderer from registry
Definition at line 79 of file qgsrendererv2registry.cpp.
References mRenderers, and mRenderersOrder.
QgsRendererV2AbstractMetadata * QgsRendererV2Registry::rendererMetadata (QString rendererName)
get metadata for particular renderer. Returns NULL if not found in registry.
Definition at line 90 of file qgsrendererv2registry.cpp.
References mRenderers.
Referenced by QgsFeatureRendererV2::load(), and QgsFeatureRendererV2::loadSld().
QStringList QgsRendererV2Registry::renderersList ()
return a list of available renderers
Definition at line 95 of file qgsrendererv2registry.cpp.
References mRenderersOrder.
Member Data Documentation
QgsRendererV2Registry * QgsRendererV2Registry::mInstance = NULL static protected
Definition at line 159 of file qgsrendererv2registry.h.
Referenced by instance().
QMap<QString, QgsRendererV2AbstractMetadata*> QgsRendererV2Registry::mRenderers protected
Definition at line 161 of file qgsrendererv2registry.h.
Referenced by addRenderer(), removeRenderer(), rendererMetadata(), and ~QgsRendererV2Registry().
QStringList QgsRendererV2Registry::mRenderersOrder protected
list to keep order in which renderers have been added
Definition at line 164 of file qgsrendererv2registry.h.
Referenced by addRenderer(), removeRenderer(), and renderersList().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsrendererv2registry.h
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsrendererv2registry.cpp