QGIS API Documentation: QgsComposerTable Class Reference
QgsComposerTable Class Reference
A class to display feature attributes in the print composer.
#include <qgscomposertable.h>
Public Member Functions
QgsComposerTable (QgsComposition *composition)
virtual ~QgsComposerTable ()
virtual int type () const
return correct graphics item type.
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint.
virtual bool writeXML (QDomElement &elem, QDomDocument &doc) const =0
stores state in Dom element
virtual bool readXML (const QDomElement &itemElem, const QDomDocument &doc)=0
sets state from Dom document
void setLineTextDistance (double d)
double lineTextDistance () const
void setHeaderFont (const QFont &f)
QFont headerFont () const
void setContentFont (const QFont &f)
QFont contentFont () const
void setShowGrid (bool show)
bool showGrid () const
void setGridStrokeWidth (double w)
double gridStrokeWidth () const
void setGridColor (const QColor &c)
QColor gridColor () const
void adjustFrameToSize ()
Adapts the size of the frame to match the content.
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected ()
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
virtual void setSceneRect (const QRectF &rectangle)
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
void updateCursor (const QPointF &itemPos)
Update mouse cursor at (item) position.
double rotation () const
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
Protected Member Functions
virtual bool getFeatureAttributes (QList< QgsAttributeMap > &attributeMaps)
Retrieves feature attributes.
virtual QMap< int, QString > getHeaderLabels () const
virtual bool calculateMaxColumnWidths (QMap< int, double > &maxWidthMap, const QList< QgsAttributeMap > &attributeMaps) const
Calculate the maximum width values of the vector attributes.
void adaptItemFrame (const QMap< int, double > &maxWidthMap, const QList< QgsAttributeMap > &attributeMaps)
Adapts the size of the item frame to match the content.
void drawHorizontalGridLines (QPainter *p, int nAttributes)
void drawVerticalGridLines (QPainter *p, const QMap< int, double > &maxWidthMap)
bool tableWriteXML (QDomElement &itemElem, QDomDocument &doc) const
bool tableReadXML (const QDomElement &itemElem, const QDomDocument &doc)
Protected Member Functions inherited from QgsComposerItem
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
Qt::CursorShape cursorForPosition (const QPointF &itemCoordPos)
Finds out the appropriate cursor for the current mouse position in the widget (e.g.
QgsComposerItem::MouseMoveAction mouseMoveActionForPosition (const QPointF &itemCoordPos)
Finds out which mouse move action to choose depending on the cursor position inside the widget.
void changeItemRectangle (const QPointF &currentPosition, const QPointF &mouseMoveStartPos, const QGraphicsRectItem *originalItem, double dx, double dy, QGraphicsRectItem *changeItem)
Changes the rectangle of an item depending on current mouse action (resize or move)
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle (mRotation)
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Protected Attributes
double mLineTextDistance
Distance between table lines and text.
QFont mHeaderFont
QFont mContentFont
bool mShowGrid
double mGridStrokeWidth
QColor mGridColor
Protected Attributes inherited from QgsComposerItem
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
Additional Inherited Members
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
void repaint ()
Signals inherited from QgsComposerItem
void rotationChanged (double newRotation)
Is emitted on rotation change to notify north arrow pictures.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
Detailed Description
A class to display feature attributes in the print composer.
Definition at line 29 of file qgscomposertable.h.
Constructor & Destructor Documentation
QgsComposerTable::QgsComposerTable (QgsComposition * composition)
Definition at line 22 of file qgscomposertable.cpp.
QgsComposerTable::~QgsComposerTable () virtual
Definition at line 31 of file qgscomposertable.cpp.
Member Function Documentation
void QgsComposerTable::adaptItemFrame (const QMap< int, double > & maxWidthMap, const QList< QgsAttributeMap > & attributeMaps) protected
Adapts the size of the item frame to match the content.
Note
not available in python bindings
Definition at line 202 of file qgscomposertable.cpp.
References QgsComposerItem::fontAscentMillimeters(), mContentFont, mGridStrokeWidth, mHeaderFont, mLineTextDistance, and QgsComposerItem::setSceneRect().
Referenced by adjustFrameToSize(), and paint().
void QgsComposerTable::adjustFrameToSize ()
Adapts the size of the frame to match the content.
This is normally done in the paint method, but sometimes it needs to be done before the first render
Definition at line 117 of file qgscomposertable.cpp.
References adaptItemFrame(), calculateMaxColumnWidths(), and getFeatureAttributes().
bool QgsComposerTable::calculateMaxColumnWidths (QMap< int, double > & maxWidthMap, const QList< QgsAttributeMap > & attributeMaps) const protected virtual
Calculate the maximum width values of the vector attributes.
Definition at line 172 of file qgscomposertable.cpp.
References getHeaderLabels(), mContentFont, mHeaderFont, and QgsComposerItem::textWidthMillimeters().
Referenced by adjustFrameToSize(), and paint().
QFont QgsComposerTable::contentFont () const inline
Definition at line 51 of file qgscomposertable.h.
void QgsComposerTable::drawHorizontalGridLines (QPainter * p, int nAttributes) protected
Definition at line 224 of file qgscomposertable.cpp.
References QgsComposerItem::fontAscentMillimeters(), mContentFont, mGridStrokeWidth, mHeaderFont, and mLineTextDistance.
Referenced by paint().
void QgsComposerTable::drawVerticalGridLines (QPainter * p, const QMap< int, double > & maxWidthMap) protected
Note
not available in python bindings
Definition at line 241 of file qgscomposertable.cpp.
References mGridStrokeWidth, and mLineTextDistance.
Referenced by paint().
virtual bool QgsComposerTable::getFeatureAttributes (QList< QgsAttributeMap > & attributeMaps) inline protected virtual
Retrieves feature attributes.
Note
not available in python bindings
Reimplemented in QgsComposerAttributeTable.
Definition at line 79 of file qgscomposertable.h.
Referenced by adjustFrameToSize(), and paint().
virtual QMap<int, QString> QgsComposerTable::getHeaderLabels () const inline protected virtual
Reimplemented in QgsComposerAttributeTable, and QgsComposerTextTable.
Definition at line 80 of file qgscomposertable.h.
Referenced by calculateMaxColumnWidths(), and paint().
QColor QgsComposerTable::gridColor () const inline
Definition at line 60 of file qgscomposertable.h.
double QgsComposerTable::gridStrokeWidth () const inline
Definition at line 57 of file qgscomposertable.h.
QFont QgsComposerTable::headerFont () const inline
Definition at line 48 of file qgscomposertable.h.
double QgsComposerTable::lineTextDistance () const inline
Definition at line 45 of file qgscomposertable.h.
void QgsComposerTable::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget) virtual
Reimplementation of QCanvasItem::paint.
Reimplemented in QgsComposerAttributeTable.
Definition at line 36 of file qgscomposertable.cpp.
References adaptItemFrame(), calculateMaxColumnWidths(), QgsComposerItem::drawBackground(), QgsComposerItem::drawFrame(), drawHorizontalGridLines(), QgsComposerItem::drawSelectionBoxes(), QgsComposerItem::drawText(), drawVerticalGridLines(), QgsComposerItem::fontAscentMillimeters(), getFeatureAttributes(), getHeaderLabels(), mContentFont, mGridColor, mGridStrokeWidth, mHeaderFont, mLineTextDistance, and mShowGrid.
virtual bool QgsComposerTable::readXML (const QDomElement & itemElem, const QDomDocument & doc) pure virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is Dom document
Implements QgsComposerItem.
Implemented in QgsComposerAttributeTable, and QgsComposerTextTable.
void QgsComposerTable::setContentFont (const QFont & f) inline
Definition at line 50 of file qgscomposertable.h.
void QgsComposerTable::setGridColor (const QColor & c) inline
Definition at line 59 of file qgscomposertable.h.
void QgsComposerTable::setGridStrokeWidth (double w) inline
Definition at line 56 of file qgscomposertable.h.
void QgsComposerTable::setHeaderFont (const QFont & f) inline
Definition at line 47 of file qgscomposertable.h.
void QgsComposerTable::setLineTextDistance (double d) inline
Definition at line 44 of file qgscomposertable.h.
void QgsComposerTable::setShowGrid (bool show) inline
Definition at line 53 of file qgscomposertable.h.
bool QgsComposerTable::showGrid () const inline
Definition at line 54 of file qgscomposertable.h.
bool QgsComposerTable::tableReadXML (const QDomElement & itemElem, const QDomDocument & doc) protected
Definition at line 143 of file qgscomposertable.cpp.
References QgsComposerItem::_readXML(), mContentFont, mGridColor, mGridStrokeWidth, mHeaderFont, mLineTextDistance, and mShowGrid.
Referenced by QgsComposerTextTable::readXML(), and QgsComposerAttributeTable::readXML().
bool QgsComposerTable::tableWriteXML (QDomElement & itemElem, QDomDocument & doc) const protected
Definition at line 130 of file qgscomposertable.cpp.
References QgsComposerItem::_writeXML(), mContentFont, mGridColor, mGridStrokeWidth, mHeaderFont, mLineTextDistance, and mShowGrid.
Referenced by QgsComposerAttributeTable::writeXML().
virtual int QgsComposerTable::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerItem.
Reimplemented in QgsComposerAttributeTable, and QgsComposerTextTable.
Definition at line 36 of file qgscomposertable.h.
References QgsComposerItem::ComposerTable.
virtual bool QgsComposerTable::writeXML (QDomElement & elem, QDomDocument & doc) const pure virtual
stores state in Dom element
Parameters
elem is Dom element corresponding to 'Composer' tag
doc is the Dom document
Implements QgsComposerItem.
Implemented in QgsComposerAttributeTable, and QgsComposerTextTable.
Member Data Documentation
QFont QgsComposerTable::mContentFont protected
Definition at line 71 of file qgscomposertable.h.
Referenced by adaptItemFrame(), calculateMaxColumnWidths(), drawHorizontalGridLines(), paint(), QgsComposerAttributeTable::setSceneRect(), tableReadXML(), and tableWriteXML().
QColor QgsComposerTable::mGridColor protected
Definition at line 75 of file qgscomposertable.h.
Referenced by paint(), tableReadXML(), and tableWriteXML().
double QgsComposerTable::mGridStrokeWidth protected
Definition at line 74 of file qgscomposertable.h.
Referenced by adaptItemFrame(), drawHorizontalGridLines(), drawVerticalGridLines(), paint(), QgsComposerAttributeTable::setSceneRect(), tableReadXML(), and tableWriteXML().
QFont QgsComposerTable::mHeaderFont protected
Definition at line 70 of file qgscomposertable.h.
Referenced by adaptItemFrame(), calculateMaxColumnWidths(), drawHorizontalGridLines(), paint(), QgsComposerAttributeTable::setSceneRect(), tableReadXML(), and tableWriteXML().
double QgsComposerTable::mLineTextDistance protected
Distance between table lines and text.
Definition at line 68 of file qgscomposertable.h.
Referenced by adaptItemFrame(), drawHorizontalGridLines(), drawVerticalGridLines(), paint(), QgsComposerAttributeTable::setSceneRect(), tableReadXML(), and tableWriteXML().
bool QgsComposerTable::mShowGrid protected
Definition at line 73 of file qgscomposertable.h.
Referenced by paint(), tableReadXML(), and tableWriteXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/composer/qgscomposertable.h
/tmp/buildd/qgis-2.0.1/src/core/composer/qgscomposertable.cpp