QGIS API Documentation: QgsSymbolLayerV2Utils Class Reference
QgsSymbolLayerV2Utils Class Reference
#include <qgssymbollayerv2utils.h>
Static Public Member Functions
static QString encodeColor (QColor color)
static QColor decodeColor (QString str)
static QString encodeSldAlpha (int alpha)
static int decodeSldAlpha (QString str)
static QString encodeSldFontStyle (QFont::Style style)
static QFont::Style decodeSldFontStyle (QString str)
static QString encodeSldFontWeight (int weight)
static int decodeSldFontWeight (QString str)
static QString encodePenStyle (Qt::PenStyle style)
static Qt::PenStyle decodePenStyle (QString str)
static QString encodePenJoinStyle (Qt::PenJoinStyle style)
static Qt::PenJoinStyle decodePenJoinStyle (QString str)
static QString encodePenCapStyle (Qt::PenCapStyle style)
static Qt::PenCapStyle decodePenCapStyle (QString str)
static QString encodeSldLineJoinStyle (Qt::PenJoinStyle style)
static Qt::PenJoinStyle decodeSldLineJoinStyle (QString str)
static QString encodeSldLineCapStyle (Qt::PenCapStyle style)
static Qt::PenCapStyle decodeSldLineCapStyle (QString str)
static QString encodeBrushStyle (Qt::BrushStyle style)
static Qt::BrushStyle decodeBrushStyle (QString str)
static QString encodeSldBrushStyle (Qt::BrushStyle style)
static Qt::BrushStyle decodeSldBrushStyle (QString str)
static QString encodePoint (QPointF point)
static QPointF decodePoint (QString str)
static QString encodeRealVector (const QVector< qreal > &v)
static QVector< qreal > decodeRealVector (const QString &s)
static QString encodeSldRealVector (const QVector< qreal > &v)
static QVector< qreal > decodeSldRealVector (const QString &s)
static QString encodeOutputUnit (QgsSymbolV2::OutputUnit unit)
static QgsSymbolV2::OutputUnit decodeOutputUnit (QString str)
static QString encodeSldUom (QgsSymbolV2::OutputUnit unit, double *scaleFactor)
static QgsSymbolV2::OutputUnit decodeSldUom (QString str, double *scaleFactor)
static QString encodeScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod)
static QgsSymbolV2::ScaleMethod decodeScaleMethod (QString str)
static QIcon symbolPreviewIcon (QgsSymbolV2 *symbol, QSize size)
static QIcon symbolLayerPreviewIcon (QgsSymbolLayerV2 *layer, QgsSymbolV2::OutputUnit u, QSize size)
static QIcon colorRampPreviewIcon (QgsVectorColorRampV2 *ramp, QSize size)
static void drawStippledBackround (QPainter *painter, QRect rect)
static QPixmap symbolPreviewPixmap (QgsSymbolV2 *symbol, QSize size)
static QPixmap colorRampPreviewPixmap (QgsVectorColorRampV2 *ramp, QSize size)
static QgsSymbolV2 * loadSymbol (QDomElement &element)
static QgsSymbolLayerV2 * loadSymbolLayer (QDomElement &element)
static QDomElement saveSymbol (QString symbolName, QgsSymbolV2 *symbol, QDomDocument &doc)
static bool createSymbolLayerV2ListFromSld (QDomElement &element, QGis::GeometryType geomType, QgsSymbolLayerV2List &layers)
static QgsSymbolLayerV2 * createFillLayerFromSld (QDomElement &element)
static QgsSymbolLayerV2 * createLineLayerFromSld (QDomElement &element)
static QgsSymbolLayerV2 * createMarkerLayerFromSld (QDomElement &element)
static bool convertPolygonSymbolizerToPointMarker (QDomElement &element, QgsSymbolLayerV2List &layerList)
static bool hasExternalGraphic (QDomElement &element)
static bool hasWellKnownMark (QDomElement &element)
static bool needFontMarker (QDomElement &element)
static bool needSvgMarker (QDomElement &element)
static bool needEllipseMarker (QDomElement &element)
static bool needMarkerLine (QDomElement &element)
static bool needLinePatternFill (QDomElement &element)
static bool needPointPatternFill (QDomElement &element)
static bool needSvgFill (QDomElement &element)
static void fillToSld (QDomDocument &doc, QDomElement &element, Qt::BrushStyle brushStyle, QColor color=QColor())
static bool fillFromSld (QDomElement &element, Qt::BrushStyle &brushStyle, QColor &color)
static void lineToSld (QDomDocument &doc, QDomElement &element, Qt::PenStyle penStyle, QColor color, double width=-1, const Qt::PenJoinStyle *penJoinStyle=0, const Qt::PenCapStyle *penCapStyle=0, const QVector< qreal > *customDashPattern=0, double dashOffset=0.0)
static bool lineFromSld (QDomElement &element, Qt::PenStyle &penStyle, QColor &color, double &width, Qt::PenJoinStyle *penJoinStyle=0, Qt::PenCapStyle *penCapStyle=0, QVector< qreal > *customDashPattern=0, double *dashOffset=0)
static void externalGraphicToSld (QDomDocument &doc, QDomElement &element, QString path, QString mime, QColor color, double size=-1)
static bool externalGraphicFromSld (QDomElement &element, QString &path, QString &mime, QColor &color, double &size)
static void wellKnownMarkerToSld (QDomDocument &doc, QDomElement &element, QString name, QColor color, QColor borderColor=QColor(), double borderWidth=-1, double size=-1)
static bool wellKnownMarkerFromSld (QDomElement &element, QString &name, QColor &color, QColor &borderColor, double &borderWidth, double &size)
static void externalMarkerToSld (QDomDocument &doc, QDomElement &element, QString path, QString format, int *markIndex=0, QColor color=QColor(), double size=-1)
static bool externalMarkerFromSld (QDomElement &element, QString &path, QString &format, int &markIndex, QColor &color, double &size)
static void labelTextToSld (QDomDocument &doc, QDomElement &element, QString label, QFont font, QColor color=QColor(), double size=-1)
static QString ogrFeatureStylePen (double width, double mmScaleFactor, double mapUnitsScaleFactor, const QColor &c, Qt::PenJoinStyle joinStyle=Qt::MiterJoin, Qt::PenCapStyle capStyle=Qt::FlatCap, double offset=0.0, const QVector< qreal > *dashPattern=0)
Create ogr feature style string for pen.
static QString ogrFeatureStyleBrush (const QColor &fillColr)
Create ogr feature style string for brush.
static void createRotationElement (QDomDocument &doc, QDomElement &element, QString rotationFunc)
static bool rotationFromSldElement (QDomElement &element, QString &rotationFunc)
static void createOpacityElement (QDomDocument &doc, QDomElement &element, QString alphaFunc)
static bool opacityFromSldElement (QDomElement &element, QString &alphaFunc)
static void createDisplacementElement (QDomDocument &doc, QDomElement &element, QPointF offset)
static bool displacementFromSldElement (QDomElement &element, QPointF &offset)
static void createOnlineResourceElement (QDomDocument &doc, QDomElement &element, QString path, QString format)
static bool onlineResourceFromSldElement (QDomElement &element, QString &path, QString &format)
static void createGeometryElement (QDomDocument &doc, QDomElement &element, QString geomFunc)
static bool geometryFromSldElement (QDomElement &element, QString &geomFunc)
static bool createFunctionElement (QDomDocument &doc, QDomElement &element, QString function)
static bool functionFromSldElement (QDomElement &element, QString &function)
static QDomElement createSvgParameterElement (QDomDocument &doc, QString name, QString value)
static QgsStringMap getSvgParameterList (QDomElement &element)
static QDomElement createVendorOptionElement (QDomDocument &doc, QString name, QString value)
static QgsStringMap getVendorOptionList (QDomElement &element)
static QgsStringMap parseProperties (QDomElement &element)
static void saveProperties (QgsStringMap props, QDomDocument &doc, QDomElement &element)
static QgsSymbolV2Map loadSymbols (QDomElement &element)
static QDomElement saveSymbols (QgsSymbolV2Map &symbols, QString tagName, QDomDocument &doc)
static void clearSymbolMap (QgsSymbolV2Map &symbols)
static QgsVectorColorRampV2 * loadColorRamp (QDomElement &element)
static QDomElement saveColorRamp (QString name, QgsVectorColorRampV2 *ramp, QDomDocument &doc)
static QColor parseColor (QString colorStr)
parse color definition with format "rgb(0,0,0)" or "0,0,0"
static double lineWidthScaleFactor (const QgsRenderContext &c, QgsSymbolV2::OutputUnit u)
Returns the line width scale factor depending on the unit and the paint device.
static double pixelSizeScaleFactor (const QgsRenderContext &c, QgsSymbolV2::OutputUnit u)
Returns scale factor painter units -> pixel dimensions.
static QgsRenderContext createRenderContext (QPainter *p)
Creates a render context for a pixel based device.
static void multiplyImageOpacity (QImage *image, qreal alpha)
Multiplies opacity of image pixel values with a (global) transparency value.
static void blurImageInPlace (QImage &image, const QRect &rect, int radius, bool alphaOnly)
Blurs an image in place, e.g.
static void sortVariantList (QList< QVariant > &list, Qt::SortOrder order)
Sorts the passed list in requested order.
static QPointF pointOnLineWithDistance (const QPointF &startPoint, const QPointF &directionPoint, double distance)
Returns a point on the line from startPoint to directionPoint that is a certain distance away from the starting point.
static QStringList listSvgFiles ()
Return a list of all available svg files.
static QStringList listSvgFilesAt (QString directory)
Return a list of svg files at the specified directory.
static QString symbolNameToPath (QString name)
Get symbol's path from its name.
static QString symbolPathToName (QString path)
Get symbols's name from its path.
Detailed Description
Definition at line 41 of file qgssymbollayerv2utils.h.
Member Function Documentation
void QgsSymbolLayerV2Utils::blurImageInPlace (QImage & image, const QRect & rect, int radius, bool alphaOnly) static
Blurs an image in place, e.g.
creating Qt-independent drop shadows
Note
added in 1.9
Definition at line 2637 of file qgssymbollayerv2utils.cpp.
Referenced by QgsPalLabeling::drawLabelShadow().
void QgsSymbolLayerV2Utils::clearSymbolMap (QgsSymbolV2Map & symbols) static
Definition at line 2493 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSingleSymbolRendererV2::create(), QgsCategorizedSymbolRendererV2::create(), QgsGraduatedSymbolRendererV2::create(), and QgsRuleBasedRendererV2::create().
QIcon QgsSymbolLayerV2Utils::colorRampPreviewIcon (QgsVectorColorRampV2 * ramp, QSize size) static
Definition at line 523 of file qgssymbollayerv2utils.cpp.
References colorRampPreviewPixmap().
Referenced by QgsCptCityColorRampItem::icon().
QPixmap QgsSymbolLayerV2Utils::colorRampPreviewPixmap (QgsVectorColorRampV2 * ramp, QSize size) static
Definition at line 528 of file qgssymbollayerv2utils.cpp.
References QgsVectorColorRampV2::color(), and drawStippledBackround().
Referenced by colorRampPreviewIcon().
bool QgsSymbolLayerV2Utils::convertPolygonSymbolizerToPointMarker (QDomElement & element, QgsSymbolLayerV2List & layerList) static
Definition at line 1221 of file qgssymbollayerv2utils.cpp.
References MathUtils::angle(), decodeSldAlpha(), displacementFromSldElement(), encodeColor(), encodePoint(), fillFromSld(), QgsSymbolLayerV2Registry::instance(), lineFromSld(), QgsDebugMsg, qgsDoubleNear(), rotationFromSldElement(), and size.
Referenced by createSymbolLayerV2ListFromSld().
void QgsSymbolLayerV2Utils::createDisplacementElement (QDomDocument & doc, QDomElement & element, QPointF offset) static
Definition at line 2031 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleFillSymbolLayerV2::toSld(), QgsLinePatternFillSymbolLayer::toSld(), QgsSimpleMarkerSymbolLayerV2::writeSldMarker(), QgsSvgMarkerSymbolLayerV2::writeSldMarker(), and QgsFontMarkerSymbolLayerV2::writeSldMarker().
QgsSymbolLayerV2 * QgsSymbolLayerV2Utils::createFillLayerFromSld (QDomElement & element) static
Definition at line 966 of file qgssymbollayerv2utils.cpp.
References QgsSymbolLayerV2Registry::createSymbolLayerFromSld(), QgsSymbolLayerV2Registry::instance(), needLinePatternFill(), needPointPatternFill(), needSvgFill(), and QgsDebugMsg.
Referenced by createSymbolLayerV2ListFromSld().
bool QgsSymbolLayerV2Utils::createFunctionElement (QDomDocument & doc, QDomElement & element, QString function) static
Definition at line 2232 of file qgssymbollayerv2utils.cpp.
References QgsOgcUtils::expressionToOgcFilter(), QgsExpression::hasParserError(), and QgsExpression::parserErrorString().
Referenced by createGeometryElement(), createOpacityElement(), createRotationElement(), QgsRendererRangeV2::toSld(), QgsRendererCategoryV2::toSld(), QgsRuleBasedRendererV2::Rule::toSld(), and QgsMarkerLineSymbolLayerV2::toSld().
void QgsSymbolLayerV2Utils::createGeometryElement (QDomDocument & doc, QDomElement & element, QString geomFunc) static
Definition at line 2189 of file qgssymbollayerv2utils.cpp.
References createFunctionElement().
Referenced by QgsEllipseSymbolLayerV2::toSld(), QgsSimpleFillSymbolLayerV2::toSld(), QgsSimpleLineSymbolLayerV2::toSld(), QgsMarkerSymbolLayerV2::toSld(), QgsMarkerLineSymbolLayerV2::toSld(), QgsSVGFillSymbolLayer::toSld(), QgsLinePatternFillSymbolLayer::toSld(), and QgsPointPatternFillSymbolLayer::toSld().
QgsSymbolLayerV2 * QgsSymbolLayerV2Utils::createLineLayerFromSld (QDomElement & element) static
Definition at line 989 of file qgssymbollayerv2utils.cpp.
References QgsSymbolLayerV2Registry::createSymbolLayerFromSld(), QgsSymbolLayerV2Registry::instance(), needMarkerLine(), and QgsDebugMsg.
Referenced by QgsSVGFillSymbolLayer::createFromSld(), QgsLinePatternFillSymbolLayer::createFromSld(), and createSymbolLayerV2ListFromSld().
QgsSymbolLayerV2 * QgsSymbolLayerV2Utils::createMarkerLayerFromSld (QDomElement & element) static
Definition at line 1008 of file qgssymbollayerv2utils.cpp.
References QgsSymbolLayerV2Registry::createSymbolLayerFromSld(), QgsSymbolLayerV2Registry::instance(), needEllipseMarker(), needFontMarker(), needSvgMarker(), and QgsDebugMsg.
Referenced by QgsMarkerLineSymbolLayerV2::createFromSld(), QgsCentroidFillSymbolLayerV2::createFromSld(), and createSymbolLayerV2ListFromSld().
void QgsSymbolLayerV2Utils::createOnlineResourceElement (QDomDocument & doc, QDomElement & element, QString path, QString format) static
Definition at line 2269 of file qgssymbollayerv2utils.cpp.
References symbolPathToName().
Referenced by externalGraphicToSld(), and externalMarkerToSld().
void QgsSymbolLayerV2Utils::createOpacityElement (QDomDocument & doc, QDomElement & element, QString alphaFunc) static
Definition at line 2011 of file qgssymbollayerv2utils.cpp.
References createFunctionElement().
QgsRenderContext QgsSymbolLayerV2Utils::createRenderContext (QPainter * p) static
Creates a render context for a pixel based device.
Definition at line 2591 of file qgssymbollayerv2utils.cpp.
References QgsRenderContext::setPainter(), QgsRenderContext::setRasterScaleFactor(), and QgsRenderContext::setScaleFactor().
Referenced by QgsSymbolV2::bigSymbolPreviewImage(), QgsSymbolV2::drawPreviewIcon(), and symbolLayerPreviewIcon().
void QgsSymbolLayerV2Utils::createRotationElement (QDomDocument & doc, QDomElement & element, QString rotationFunc) static
Definition at line 1990 of file qgssymbollayerv2utils.cpp.
References createFunctionElement().
Referenced by QgsSVGFillSymbolLayer::toSld(), QgsLinePatternFillSymbolLayer::toSld(), QgsEllipseSymbolLayerV2::writeSldMarker(), QgsSimpleMarkerSymbolLayerV2::writeSldMarker(), QgsSvgMarkerSymbolLayerV2::writeSldMarker(), and QgsFontMarkerSymbolLayerV2::writeSldMarker().
QDomElement QgsSymbolLayerV2Utils::createSvgParameterElement (QDomDocument & doc, QString name, QString value) static
Definition at line 2310 of file qgssymbollayerv2utils.cpp.
Referenced by fillToSld(), labelTextToSld(), and lineToSld().
bool QgsSymbolLayerV2Utils::createSymbolLayerV2ListFromSld (QDomElement & element, QGis::GeometryType geomType, QgsSymbolLayerV2List & layers) static
Definition at line 818 of file qgssymbollayerv2utils.cpp.
References convertPolygonSymbolizerToPointMarker(), createFillLayerFromSld(), createLineLayerFromSld(), createMarkerLayerFromSld(), QgsSymbolLayerV2Registry::createSymbolLayerFromSld(), QgsSymbolLayerV2Registry::instance(), QgsSymbolLayerV2::layerType(), QGis::Line, QGis::Point, QGis::Polygon, and QgsDebugMsg.
Referenced by QgsSingleSymbolRendererV2::createFromSld(), and QgsRuleBasedRendererV2::Rule::createFromSld().
QDomElement QgsSymbolLayerV2Utils::createVendorOptionElement (QDomDocument & doc, QString name, QString value) static
Definition at line 2340 of file qgssymbollayerv2utils.cpp.
Referenced by QgsMarkerLineSymbolLayerV2::toSld(), QgsPointPatternFillSymbolLayer::toSld(), and QgsEllipseSymbolLayerV2::writeSldMarker().
Qt::BrushStyle QgsSymbolLayerV2Utils::decodeBrushStyle (QString str) static
Definition at line 249 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleFillSymbolLayerV2::create(), and decodeSldBrushStyle().
QColor QgsSymbolLayerV2Utils::decodeColor (QString str) static
Definition at line 46 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSVGFillSymbolLayer::applyDataDefinedSettings(), QgsLinePatternFillSymbolLayer::applyDataDefinedSettings(), QgsSimpleFillSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsEllipseSymbolLayerV2::create(), QgsSimpleFillSymbolLayerV2::create(), QgsSimpleLineSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsPointDisplacementRenderer::create(), QgsVectorGradientColorRampV2::create(), QgsFontMarkerSymbolLayerV2::create(), QgsLinePatternFillSymbolLayer::create(), QgsPalLayerSettings::dataDefinedValEval(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), and QgsSvgMarkerSymbolLayerV2::renderPoint().
QgsSymbolV2::OutputUnit QgsSymbolLayerV2Utils::decodeOutputUnit (QString str) static
Definition at line 341 of file qgssymbollayerv2utils.cpp.
References QgsSymbolV2::MapUnit, and QgsSymbolV2::MM.
Referenced by QgsEllipseSymbolLayerV2::create(), QgsSimpleFillSymbolLayerV2::create(), QgsSimpleLineSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsVectorFieldSymbolLayer::create(), QgsSvgMarkerSymbolLayerV2::create(), QgsMarkerLineSymbolLayerV2::create(), QgsSVGFillSymbolLayer::create(), QgsFontMarkerSymbolLayerV2::create(), QgsLinePatternFillSymbolLayer::create(), QgsPointPatternFillSymbolLayer::create(), and loadSymbol().
Qt::PenCapStyle QgsSymbolLayerV2Utils::decodePenCapStyle (QString str) static
Definition at line 199 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), and QgsSimpleLineSymbolLayerV2::create().
Qt::PenJoinStyle QgsSymbolLayerV2Utils::decodePenJoinStyle (QString str) static
Definition at line 161 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), and QgsSimpleLineSymbolLayerV2::create().
Qt::PenStyle QgsSymbolLayerV2Utils::decodePenStyle (QString str) static
Definition at line 139 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleFillSymbolLayerV2::create(), and QgsSimpleLineSymbolLayerV2::create().
QPointF QgsSymbolLayerV2Utils::decodePoint (QString str) static
Definition at line 320 of file qgssymbollayerv2utils.cpp.
Referenced by QgsEllipseSymbolLayerV2::create(), QgsSimpleFillSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsSvgMarkerSymbolLayerV2::create(), QgsFontMarkerSymbolLayerV2::create(), QgsPalLayerSettings::dataDefinedValEval(), QgsMarkerSymbolLayerV2::markerOffset(), QgsPalLayerSettings::registerFeature(), and QgsSvgMarkerSymbolLayerV2::renderPoint().
QVector< qreal > QgsSymbolLayerV2Utils::decodeRealVector (const QString & s) static
Definition at line 414 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleLineSymbolLayerV2::create().
QgsSymbolV2::ScaleMethod QgsSymbolLayerV2Utils::decodeScaleMethod (QString str) static
Definition at line 473 of file qgssymbollayerv2utils.cpp.
References QgsSymbolV2::ScaleArea, and QgsSymbolV2::ScaleDiameter.
Referenced by QgsSimpleMarkerSymbolLayerV2::create(), QgsSingleSymbolRendererV2::create(), QgsCategorizedSymbolRendererV2::create(), and QgsGraduatedSymbolRendererV2::create().
int QgsSymbolLayerV2Utils::decodeSldAlpha (QString str) static
Definition at line 70 of file qgssymbollayerv2utils.cpp.
Referenced by convertPolygonSymbolizerToPointMarker(), fillFromSld(), and lineFromSld().
Qt::BrushStyle QgsSymbolLayerV2Utils::decodeSldBrushStyle (QString str) static
Definition at line 300 of file qgssymbollayerv2utils.cpp.
References decodeBrushStyle().
Referenced by fillFromSld().
QFont::Style QgsSymbolLayerV2Utils::decodeSldFontStyle (QString str) static
Definition at line 92 of file qgssymbollayerv2utils.cpp.
int QgsSymbolLayerV2Utils::decodeSldFontWeight (QString str) static
Definition at line 112 of file qgssymbollayerv2utils.cpp.
Qt::PenCapStyle QgsSymbolLayerV2Utils::decodeSldLineCapStyle (QString str) static
Definition at line 218 of file qgssymbollayerv2utils.cpp.
Referenced by lineFromSld().
Qt::PenJoinStyle QgsSymbolLayerV2Utils::decodeSldLineJoinStyle (QString str) static
Definition at line 180 of file qgssymbollayerv2utils.cpp.
Referenced by lineFromSld().
QVector< qreal > QgsSymbolLayerV2Utils::decodeSldRealVector (const QString & s) static
Definition at line 443 of file qgssymbollayerv2utils.cpp.
Referenced by lineFromSld().
QgsSymbolV2::OutputUnit QgsSymbolLayerV2Utils::decodeSldUom (QString str, double * scaleFactor) static
Definition at line 377 of file qgssymbollayerv2utils.cpp.
References QgsSymbolV2::MapUnit, and QgsSymbolV2::MM.
bool QgsSymbolLayerV2Utils::displacementFromSldElement (QDomElement & element, QPointF & offset) static
Definition at line 2049 of file qgssymbollayerv2utils.cpp.
Referenced by convertPolygonSymbolizerToPointMarker(), QgsSimpleFillSymbolLayerV2::createFromSld(), QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsSvgMarkerSymbolLayerV2::createFromSld(), QgsFontMarkerSymbolLayerV2::createFromSld(), and QgsLinePatternFillSymbolLayer::createFromSld().
void QgsSymbolLayerV2Utils::drawStippledBackround (QPainter * painter, QRect rect) static
Definition at line 551 of file qgssymbollayerv2utils.cpp.
Referenced by colorRampPreviewPixmap().
QString QgsSymbolLayerV2Utils::encodeBrushStyle (Qt::BrushStyle style) static
Definition at line 226 of file qgssymbollayerv2utils.cpp.
Referenced by encodeSldBrushStyle(), and QgsSimpleFillSymbolLayerV2::properties().
QString QgsSymbolLayerV2Utils::encodeColor (QColor color) static
Definition at line 41 of file qgssymbollayerv2utils.cpp.
Referenced by convertPolygonSymbolizerToPointMarker(), QgsSymbolV2::dump(), fcnRampColor(), fncColorCmyka(), fncColorHsla(), fncColorHsva(), fncColorRgba(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleFillSymbolLayerV2::properties(), QgsSimpleLineSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsVectorGradientColorRampV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsLinePatternFillSymbolLayer::properties(), and QgsPointDisplacementRenderer::save().
QString QgsSymbolLayerV2Utils::encodeOutputUnit (QgsSymbolV2::OutputUnit unit) static
Definition at line 328 of file qgssymbollayerv2utils.cpp.
References QgsSymbolV2::MapUnit, and QgsSymbolV2::MM.
Referenced by QgsPalLabeling::drawLabelBackground(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleFillSymbolLayerV2::properties(), QgsSimpleLineSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsVectorFieldSymbolLayer::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsMarkerLineSymbolLayerV2::properties(), QgsSVGFillSymbolLayer::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsLinePatternFillSymbolLayer::properties(), and QgsPointPatternFillSymbolLayer::properties().
QString QgsSymbolLayerV2Utils::encodePenCapStyle (Qt::PenCapStyle style) static
Definition at line 188 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleLineSymbolLayerV2::properties().
QString QgsSymbolLayerV2Utils::encodePenJoinStyle (Qt::PenJoinStyle style) static
Definition at line 150 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleLineSymbolLayerV2::properties().
QString QgsSymbolLayerV2Utils::encodePenStyle (Qt::PenStyle style) static
Definition at line 125 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleFillSymbolLayerV2::properties(), and QgsSimpleLineSymbolLayerV2::properties().
QString QgsSymbolLayerV2Utils::encodePoint (QPointF point) static
Definition at line 315 of file qgssymbollayerv2utils.cpp.
Referenced by convertPolygonSymbolizerToPointMarker(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleFillSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), and QgsPointPatternFillSymbolLayer::toSld().
QString QgsSymbolLayerV2Utils::encodeRealVector (const QVector< qreal > & v) static
Definition at line 399 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleLineSymbolLayerV2::properties().
QString QgsSymbolLayerV2Utils::encodeScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod) static
Definition at line 457 of file qgssymbollayerv2utils.cpp.
References QgsSymbolV2::ScaleArea, and QgsSymbolV2::ScaleDiameter.
Referenced by QgsSimpleMarkerSymbolLayerV2::properties(), QgsSingleSymbolRendererV2::save(), QgsCategorizedSymbolRendererV2::save(), and QgsGraduatedSymbolRendererV2::save().
QString QgsSymbolLayerV2Utils::encodeSldAlpha (int alpha) static
Definition at line 65 of file qgssymbollayerv2utils.cpp.
Referenced by fillToSld(), and lineToSld().
QString QgsSymbolLayerV2Utils::encodeSldBrushStyle (Qt::BrushStyle style) static
Definition at line 269 of file qgssymbollayerv2utils.cpp.
References encodeBrushStyle().
Referenced by fillToSld().
QString QgsSymbolLayerV2Utils::encodeSldFontStyle (QFont::Style style) static
Definition at line 81 of file qgssymbollayerv2utils.cpp.
Referenced by labelTextToSld().
QString QgsSymbolLayerV2Utils::encodeSldFontWeight (int weight) static
Definition at line 100 of file qgssymbollayerv2utils.cpp.
Referenced by labelTextToSld().
QString QgsSymbolLayerV2Utils::encodeSldLineCapStyle (Qt::PenCapStyle style) static
Definition at line 207 of file qgssymbollayerv2utils.cpp.
Referenced by lineToSld().
QString QgsSymbolLayerV2Utils::encodeSldLineJoinStyle (Qt::PenJoinStyle style) static
Definition at line 169 of file qgssymbollayerv2utils.cpp.
Referenced by lineToSld().
QString QgsSymbolLayerV2Utils::encodeSldRealVector (const QVector< qreal > & v) static
Definition at line 428 of file qgssymbollayerv2utils.cpp.
Referenced by lineToSld().
QString QgsSymbolLayerV2Utils::encodeSldUom (QgsSymbolV2::OutputUnit unit, double * scaleFactor) static
Definition at line 356 of file qgssymbollayerv2utils.cpp.
References QgsSymbolV2::MapUnit, and QgsSymbolV2::MM.
Referenced by QgsSymbolV2::toSld().
bool QgsSymbolLayerV2Utils::externalGraphicFromSld (QDomElement & element, QString & path, QString & mime, QColor & color, double & size) static
Definition at line 1807 of file qgssymbollayerv2utils.cpp.
References onlineResourceFromSldElement(), and QgsDebugMsg.
Referenced by QgsSvgMarkerSymbolLayerV2::createFromSld(), and QgsSVGFillSymbolLayer::createFromSld().
void QgsSymbolLayerV2Utils::externalGraphicToSld (QDomDocument & doc, QDomElement & element, QString path, QString mime, QColor color, double size = -1) static
Definition at line 1787 of file qgssymbollayerv2utils.cpp.
References createOnlineResourceElement().
Referenced by QgsSVGFillSymbolLayer::toSld(), and QgsSvgMarkerSymbolLayerV2::writeSldMarker().
bool QgsSymbolLayerV2Utils::externalMarkerFromSld (QDomElement & element, QString & path, QString & format, int & markIndex, QColor & color, double & size) static
Definition at line 1862 of file qgssymbollayerv2utils.cpp.
References fillFromSld(), onlineResourceFromSldElement(), and QgsDebugMsg.
Referenced by QgsFontMarkerSymbolLayerV2::createFromSld().
void QgsSymbolLayerV2Utils::externalMarkerToSld (QDomDocument & doc, QDomElement & element, QString path, QString format, int * markIndex = 0, QColor color = QColor(), double size = -1) static
Definition at line 1832 of file qgssymbollayerv2utils.cpp.
References createOnlineResourceElement(), fillToSld(), and qgsDoubleNear().
Referenced by QgsFontMarkerSymbolLayerV2::writeSldMarker().
bool QgsSymbolLayerV2Utils::fillFromSld (QDomElement & element, Qt::BrushStyle & brushStyle, QColor & color) static
Definition at line 1526 of file qgssymbollayerv2utils.cpp.
References decodeSldAlpha(), decodeSldBrushStyle(), getSvgParameterList(), QgsDebugMsg, size, and wellKnownMarkerFromSld().
Referenced by convertPolygonSymbolizerToPointMarker(), QgsSimpleFillSymbolLayerV2::createFromSld(), externalMarkerFromSld(), and wellKnownMarkerFromSld().
void QgsSymbolLayerV2Utils::fillToSld (QDomDocument & doc, QDomElement & element, Qt::BrushStyle brushStyle, QColor color = QColor()) static
Definition at line 1475 of file qgssymbollayerv2utils.cpp.
References createSvgParameterElement(), encodeSldAlpha(), encodeSldBrushStyle(), and wellKnownMarkerToSld().
Referenced by externalMarkerToSld(), labelTextToSld(), QgsSimpleFillSymbolLayerV2::toSld(), and wellKnownMarkerToSld().
bool QgsSymbolLayerV2Utils::functionFromSldElement (QDomElement & element, QString & function) static
Definition at line 2247 of file qgssymbollayerv2utils.cpp.
References QgsExpression::dump(), QgsOgcUtils::expressionFromOgcFilter(), QgsExpression::hasParserError(), QgsExpression::parserErrorString(), and QgsDebugMsg.
Referenced by geometryFromSldElement(), opacityFromSldElement(), and rotationFromSldElement().
bool QgsSymbolLayerV2Utils::geometryFromSldElement (QDomElement & element, QString & geomFunc) static
Definition at line 2223 of file qgssymbollayerv2utils.cpp.
References functionFromSldElement().
QgsStringMap QgsSymbolLayerV2Utils::getSvgParameterList (QDomElement & element) static
Definition at line 2318 of file qgssymbollayerv2utils.cpp.
Referenced by fillFromSld(), and lineFromSld().
QgsStringMap QgsSymbolLayerV2Utils::getVendorOptionList (QDomElement & element) static
Definition at line 2348 of file qgssymbollayerv2utils.cpp.
Referenced by QgsEllipseSymbolLayerV2::createFromSld(), QgsMarkerLineSymbolLayerV2::createFromSld(), and needEllipseMarker().
bool QgsSymbolLayerV2Utils::hasExternalGraphic (QDomElement & element) static
Definition at line 1031 of file qgssymbollayerv2utils.cpp.
References QgsDebugMsg.
Referenced by needSvgFill(), and needSvgMarker().
bool QgsSymbolLayerV2Utils::hasWellKnownMark (QDomElement & element) static
Definition at line 1070 of file qgssymbollayerv2utils.cpp.
Referenced by needMarkerLine().
void QgsSymbolLayerV2Utils::labelTextToSld (QDomDocument & doc, QDomElement & element, QString label, QFont font, QColor color = QColor(), double size = -1) static
Definition at line 2078 of file qgssymbollayerv2utils.cpp.
References createSvgParameterElement(), encodeSldFontStyle(), encodeSldFontWeight(), and fillToSld().
bool QgsSymbolLayerV2Utils::lineFromSld (QDomElement & element, Qt::PenStyle & penStyle, QColor & color, double & width, Qt::PenJoinStyle * penJoinStyle = 0, Qt::PenCapStyle * penCapStyle = 0, QVector< qreal > * customDashPattern = 0, double * dashOffset = 0) static
Definition at line 1656 of file qgssymbollayerv2utils.cpp.
References decodeSldAlpha(), decodeSldLineCapStyle(), decodeSldLineJoinStyle(), decodeSldRealVector(), getSvgParameterList(), and QgsDebugMsg.
Referenced by convertPolygonSymbolizerToPointMarker(), QgsSimpleFillSymbolLayerV2::createFromSld(), QgsSimpleLineSymbolLayerV2::createFromSld(), QgsSVGFillSymbolLayer::createFromSld(), and wellKnownMarkerFromSld().
void QgsSymbolLayerV2Utils::lineToSld (QDomDocument & doc, QDomElement & element, Qt::PenStyle penStyle, QColor color, double width = -1, const Qt::PenJoinStyle * penJoinStyle = 0, const Qt::PenCapStyle * penCapStyle = 0, const QVector< qreal > * customDashPattern = 0, double dashOffset = 0.0) static
Note
not available in python bindings
Definition at line 1579 of file qgssymbollayerv2utils.cpp.
References createSvgParameterElement(), encodeSldAlpha(), encodeSldLineCapStyle(), encodeSldLineJoinStyle(), encodeSldRealVector(), and qgsDoubleNear().
Referenced by QgsSimpleFillSymbolLayerV2::toSld(), QgsSimpleLineSymbolLayerV2::toSld(), QgsSVGFillSymbolLayer::toSld(), and wellKnownMarkerToSld().
double QgsSymbolLayerV2Utils::lineWidthScaleFactor (const QgsRenderContext & c, QgsSymbolV2::OutputUnit u) static
Returns the line width scale factor depending on the unit and the paint device.
Definition at line 2550 of file qgssymbollayerv2utils.cpp.
References QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), QgsSymbolV2::MM, and QgsRenderContext::scaleFactor().
Referenced by QgsSimpleFillSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSVGFillSymbolLayer::applyPattern(), QgsMarkerSymbolLayerV2::markerOffset(), QgsSymbolV2RenderContext::outputLineWidth(), QgsSimpleMarkerSymbolLayerV2::prepareCache(), QgsEllipseSymbolLayerV2::preparePath(), QgsPointDisplacementRenderer::renderFeature(), QgsEllipseSymbolLayerV2::renderPoint(), QgsVectorFieldSymbolLayer::renderPoint(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsSimpleFillSymbolLayerV2::renderPolygon(), QgsSimpleLineSymbolLayerV2::renderPolyline(), QgsMarkerLineSymbolLayerV2::renderPolyline(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), QgsEllipseSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), and QgsFontMarkerSymbolLayerV2::startRender().
QStringList QgsSymbolLayerV2Utils::listSvgFiles () static
Return a list of all available svg files.
Definition at line 2771 of file qgssymbollayerv2utils.cpp.
References QgsApplication::svgPaths().
QStringList QgsSymbolLayerV2Utils::listSvgFilesAt (QString directory) static
Return a list of svg files at the specified directory.
Definition at line 2795 of file qgssymbollayerv2utils.cpp.
QgsVectorColorRampV2 * QgsSymbolLayerV2Utils::loadColorRamp (QDomElement & element) static
Definition at line 2503 of file qgssymbollayerv2utils.cpp.
References QgsVectorGradientColorRampV2::create(), QgsVectorRandomColorRampV2::create(), QgsVectorColorBrewerColorRampV2::create(), QgsCptCityColorRampV2::create(), parseProperties(), and QgsDebugMsg.
Referenced by QgsCategorizedSymbolRendererV2::create(), QgsGraduatedSymbolRendererV2::create(), QgsStyleV2::importXML(), and QgsStyleV2::load().
QgsSymbolV2 * QgsSymbolLayerV2Utils::loadSymbol (QDomElement & element) static
Definition at line 684 of file qgssymbollayerv2utils.cpp.
References decodeOutputUnit(), loadSymbolLayer(), QgsDebugMsg, QgsSymbolV2::setAlpha(), QgsSymbolV2::setOutputUnit(), and QgsSymbolLayerV2::setSubSymbol().
Referenced by QgsAnnotationItem::_readXML(), QgsPointDisplacementRenderer::create(), QgsStyleV2::importXML(), QgsStyleV2::load(), loadSymbols(), and QgsComposerMap::readXML().
QgsSymbolLayerV2 * QgsSymbolLayerV2Utils::loadSymbolLayer (QDomElement & element) static
Definition at line 752 of file qgssymbollayerv2utils.cpp.
References QgsSymbolLayerV2Registry::createSymbolLayer(), QgsSymbolLayerV2Registry::instance(), parseProperties(), QgsDebugMsg, QgsSymbolLayerV2::setLocked(), and QgsSymbolLayerV2::setRenderingPass().
Referenced by loadSymbol().
QgsSymbolV2Map QgsSymbolLayerV2Utils::loadSymbols (QDomElement & element) static
Definition at line 2401 of file qgssymbollayerv2utils.cpp.
References loadSymbol(), QgsDebugMsg, QgsSymbolLayerV2::setSubSymbol(), QgsSymbolV2::symbolLayer(), and QgsSymbolV2::symbolLayerCount().
Referenced by QgsSingleSymbolRendererV2::create(), QgsCategorizedSymbolRendererV2::create(), QgsGraduatedSymbolRendererV2::create(), QgsRuleBasedRendererV2::create(), QgsStyleV2::importXML(), and QgsComposerSymbolV2Item::readXML().
void QgsSymbolLayerV2Utils::multiplyImageOpacity (QImage * image, qreal alpha) static
Multiplies opacity of image pixel values with a (global) transparency value.
Definition at line 2607 of file qgssymbollayerv2utils.cpp.
References QgsDebugMsg.
Referenced by QgsSVGFillSymbolLayer::applyPattern(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), and QgsSvgMarkerSymbolLayerV2::renderPoint().
bool QgsSymbolLayerV2Utils::needEllipseMarker (QDomElement & element) static
Definition at line 1133 of file qgssymbollayerv2utils.cpp.
References getVendorOptionList().
Referenced by createMarkerLayerFromSld().
bool QgsSymbolLayerV2Utils::needFontMarker (QDomElement & element) static
Definition at line 1088 of file qgssymbollayerv2utils.cpp.
References QgsDebugMsg.
Referenced by createMarkerLayerFromSld().
bool QgsSymbolLayerV2Utils::needLinePatternFill (QDomElement & element) static
Definition at line 1164 of file qgssymbollayerv2utils.cpp.
References MathUtils::angle(), rotationFromSldElement(), size, and wellKnownMarkerFromSld().
Referenced by createFillLayerFromSld().
bool QgsSymbolLayerV2Utils::needMarkerLine (QDomElement & element) static
Definition at line 1151 of file qgssymbollayerv2utils.cpp.
References hasWellKnownMark().
Referenced by createLineLayerFromSld().
bool QgsSymbolLayerV2Utils::needPointPatternFill (QDomElement & element) static
Definition at line 1201 of file qgssymbollayerv2utils.cpp.
Referenced by createFillLayerFromSld().
bool QgsSymbolLayerV2Utils::needSvgFill (QDomElement & element) static
Definition at line 1207 of file qgssymbollayerv2utils.cpp.
References hasExternalGraphic().
Referenced by createFillLayerFromSld().
bool QgsSymbolLayerV2Utils::needSvgMarker (QDomElement & element) static
Definition at line 1128 of file qgssymbollayerv2utils.cpp.
References hasExternalGraphic().
Referenced by createMarkerLayerFromSld().
QString QgsSymbolLayerV2Utils::ogrFeatureStyleBrush (const QColor & fillColr) static
Create ogr feature style string for brush.
Parameters
fillColr fill color
Definition at line 2179 of file qgssymbollayerv2utils.cpp.
Referenced by QgsSimpleFillSymbolLayerV2::ogrFeatureStyle().
QString QgsSymbolLayerV2Utils::ogrFeatureStylePen (double width, double mmScaleFactor, double mapUnitsScaleFactor, const QColor & c, Qt::PenJoinStyle joinStyle = Qt::MiterJoin, Qt::PenCapStyle capStyle = Qt::FlatCap, double offset = 0.0, const QVector< qreal > * dashPattern = 0) static
Create ogr feature style string for pen.
Definition at line 2105 of file qgssymbollayerv2utils.cpp.
References qgsDoubleNear().
Referenced by QgsSimpleFillSymbolLayerV2::ogrFeatureStyle(), and QgsSimpleLineSymbolLayerV2::ogrFeatureStyle().
bool QgsSymbolLayerV2Utils::onlineResourceFromSldElement (QDomElement & element, QString & path, QString & format) static
Definition at line 2291 of file qgssymbollayerv2utils.cpp.
References QgsDebugMsg.
Referenced by externalGraphicFromSld(), and externalMarkerFromSld().
bool QgsSymbolLayerV2Utils::opacityFromSldElement (QDomElement & element, QString & alphaFunc) static
Definition at line 2021 of file qgssymbollayerv2utils.cpp.
References functionFromSldElement().
QColor QgsSymbolLayerV2Utils::parseColor (QString colorStr) static
parse color definition with format "rgb(0,0,0)" or "0,0,0"
Definition at line 2538 of file qgssymbollayerv2utils.cpp.
Referenced by QgsCptCityArchive::gradientColorMap(), and QgsColorBrewerPalette::listSchemeColors().
QgsStringMap QgsSymbolLayerV2Utils::parseProperties (QDomElement & element) static
Definition at line 2368 of file qgssymbollayerv2utils.cpp.
References QgsDebugMsg.
Referenced by loadColorRamp(), and loadSymbolLayer().
double QgsSymbolLayerV2Utils::pixelSizeScaleFactor (const QgsRenderContext & c, QgsSymbolV2::OutputUnit u) static
Returns scale factor painter units -> pixel dimensions.
Definition at line 2571 of file qgssymbollayerv2utils.cpp.
References QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), QgsSymbolV2::MM, QgsRenderContext::rasterScaleFactor(), and QgsRenderContext::scaleFactor().
Referenced by QgsSVGFillSymbolLayer::applyPattern(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), and QgsSymbolV2RenderContext::outputPixelSize().
QPointF QgsSymbolLayerV2Utils::pointOnLineWithDistance (const QPointF & startPoint, const QPointF & directionPoint, double distance) static
Returns a point on the line from startPoint to directionPoint that is a certain distance away from the starting point.
Definition at line 2761 of file qgssymbollayerv2utils.cpp.
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsComposerMap::drawGrid(), and QgsComposerItem::imageSizeConsideringRotation().
bool QgsSymbolLayerV2Utils::rotationFromSldElement (QDomElement & element, QString & rotationFunc) static
Definition at line 2000 of file qgssymbollayerv2utils.cpp.
References functionFromSldElement().
Referenced by convertPolygonSymbolizerToPointMarker(), QgsEllipseSymbolLayerV2::createFromSld(), QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsSvgMarkerSymbolLayerV2::createFromSld(), QgsSVGFillSymbolLayer::createFromSld(), QgsFontMarkerSymbolLayerV2::createFromSld(), QgsLinePatternFillSymbolLayer::createFromSld(), and needLinePatternFill().
QDomElement QgsSymbolLayerV2Utils::saveColorRamp (QString name, QgsVectorColorRampV2 * ramp, QDomDocument & doc) static
Definition at line 2526 of file qgssymbollayerv2utils.cpp.
References QgsVectorColorRampV2::properties(), saveProperties(), and QgsVectorColorRampV2::type().
Referenced by QgsCategorizedSymbolRendererV2::save(), and QgsGraduatedSymbolRendererV2::save().
void QgsSymbolLayerV2Utils::saveProperties (QgsStringMap props, QDomDocument & doc, QDomElement & element) static
Definition at line 2390 of file qgssymbollayerv2utils.cpp.
Referenced by saveColorRamp(), and saveSymbol().
QDomElement QgsSymbolLayerV2Utils::saveSymbol (QString symbolName, QgsSymbolV2 * symbol, QDomDocument & doc) static
Definition at line 787 of file qgssymbollayerv2utils.cpp.
References _nameForSymbolType(), QgsSymbolV2::alpha(), QgsSymbolLayerV2::isLocked(), QgsSymbolLayerV2::layerType(), QgsSymbolLayerV2::properties(), QgsDebugMsg, QgsSymbolLayerV2::renderingPass(), saveProperties(), QgsSymbolLayerV2::subSymbol(), QgsSymbolV2::symbolLayer(), QgsSymbolV2::symbolLayerCount(), and QgsSymbolV2::type().
Referenced by QgsAnnotationItem::_writeXML(), QgsPointDisplacementRenderer::save(), saveSymbols(), and QgsComposerMap::writeXML().
QDomElement QgsSymbolLayerV2Utils::saveSymbols (QgsSymbolV2Map & symbols, QString tagName, QDomDocument & doc) static
Definition at line 2479 of file qgssymbollayerv2utils.cpp.
References saveSymbol().
Referenced by QgsStyleV2::exportXML(), QgsSingleSymbolRendererV2::save(), QgsCategorizedSymbolRendererV2::save(), QgsGraduatedSymbolRendererV2::save(), QgsRuleBasedRendererV2::save(), QgsStyleV2::save(), and QgsComposerSymbolV2Item::writeXML().
void QgsSymbolLayerV2Utils::sortVariantList (QList< QVariant > & list, Qt::SortOrder order) static
Sorts the passed list in requested order.
Definition at line 2747 of file qgssymbollayerv2utils.cpp.
References qgsVariantGreaterThan(), and qgsVariantLessThan().
QIcon QgsSymbolLayerV2Utils::symbolLayerPreviewIcon (QgsSymbolLayerV2 * layer, QgsSymbolV2::OutputUnit u, QSize size) static
Definition at line 509 of file qgssymbollayerv2utils.cpp.
References createRenderContext(), and QgsSymbolLayerV2::drawPreviewIcon().
QString QgsSymbolLayerV2Utils::symbolNameToPath (QString name) static
Get symbol's path from its name.
Definition at line 2820 of file qgssymbollayerv2utils.cpp.
References QgsProject::instance(), QgsDebugMsg, and QgsApplication::svgPaths().
Referenced by QgsSVGFillSymbolLayer::create(), QgsPalLabeling::drawLabelBackground(), and QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2().
QString QgsSymbolLayerV2Utils::symbolPathToName (QString path) static
Get symbols's name from its path.
Definition at line 2897 of file qgssymbollayerv2utils.cpp.
References QgsProject::instance(), QgsApplication::svgPaths(), and QgsProject::writePath().
Referenced by createOnlineResourceElement(), QgsSvgMarkerSymbolLayerV2::properties(), and QgsSVGFillSymbolLayer::properties().
QIcon QgsSymbolLayerV2Utils::symbolPreviewIcon (QgsSymbolV2 * symbol, QSize size) static
Definition at line 489 of file qgssymbollayerv2utils.cpp.
References symbolPreviewPixmap().
Referenced by QgsLegendModel::addVectorLayerItemsV2(), and QgsComposerSymbolV2Item::readXML().
QPixmap QgsSymbolLayerV2Utils::symbolPreviewPixmap (QgsSymbolV2 * symbol, QSize size) static
Definition at line 494 of file qgssymbollayerv2utils.cpp.
References QgsSymbolV2::drawPreviewIcon().
Referenced by QgsSingleSymbolRendererV2::legendSymbologyItems(), QgsCategorizedSymbolRendererV2::legendSymbologyItems(), QgsGraduatedSymbolRendererV2::legendSymbologyItems(), QgsRuleBasedRendererV2::legendSymbologyItems(), and symbolPreviewIcon().
bool QgsSymbolLayerV2Utils::wellKnownMarkerFromSld (QDomElement & element, QString & name, QColor & color, QColor & borderColor, double & borderWidth, double & size) static
Definition at line 1942 of file qgssymbollayerv2utils.cpp.
References fillFromSld(), lineFromSld(), and QgsDebugMsg.
Referenced by QgsEllipseSymbolLayerV2::createFromSld(), QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsLinePatternFillSymbolLayer::createFromSld(), fillFromSld(), and needLinePatternFill().
void QgsSymbolLayerV2Utils::wellKnownMarkerToSld (QDomDocument & doc, QDomElement & element, QString name, QColor color, QColor borderColor = QColor(), double borderWidth = -1, double size = -1) static
Definition at line 1906 of file qgssymbollayerv2utils.cpp.
References fillToSld(), lineToSld(), and qgsDoubleNear().
Referenced by fillToSld(), QgsLinePatternFillSymbolLayer::toSld(), QgsEllipseSymbolLayerV2::writeSldMarker(), and QgsSimpleMarkerSymbolLayerV2::writeSldMarker().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgssymbollayerv2utils.h
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgssymbollayerv2utils.cpp