QGIS API Documentation: QgsVectorLayerUndoCommandAddAttribute Class Reference
QgsVectorLayerUndoCommandAddAttribute Class Reference
#include <qgsvectorlayerundocommand.h>
Public Member Functions
QgsVectorLayerUndoCommandAddAttribute (QgsVectorLayerEditBuffer *buffer, const QgsField &field)
virtual void undo ()
virtual void redo ()
Public Member Functions inherited from QgsVectorLayerUndoCommand
QgsVectorLayerUndoCommand (QgsVectorLayerEditBuffer *buffer)
QgsVectorLayer * layer ()
QgsGeometryCache * cache ()
virtual int id () const
virtual bool mergeWith (QUndoCommand *)
Private Attributes
QgsField mField
int mFieldIndex
Additional Inherited Members
Protected Attributes inherited from QgsVectorLayerUndoCommand
QgsVectorLayerEditBuffer * mBuffer
Detailed Description
Definition at line 114 of file qgsvectorlayerundocommand.h.
Constructor & Destructor Documentation
QgsVectorLayerUndoCommandAddAttribute::QgsVectorLayerUndoCommandAddAttribute (QgsVectorLayerEditBuffer * buffer, const QgsField & field)
Definition at line 312 of file qgsvectorlayerundocommand.cpp.
References QgsFields::count(), QgsVectorLayerUndoCommand::layer(), mFieldIndex, and QgsVectorLayer::pendingFields().
Member Function Documentation
void QgsVectorLayerUndoCommandAddAttribute::redo () virtual
Definition at line 330 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerEditBuffer::attributeAdded(), QgsVectorLayerEditBuffer::handleAttributeAdded(), QgsVectorLayerEditBuffer::mAddedAttributes, QgsVectorLayerUndoCommand::mBuffer, mField, mFieldIndex, and QgsVectorLayerEditBuffer::updateLayerFields().
void QgsVectorLayerUndoCommandAddAttribute::undo () virtual
Definition at line 319 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerEditBuffer::attributeDeleted(), QgsFields::fieldOriginIndex(), QgsVectorLayerEditBuffer::handleAttributeDeleted(), QgsVectorLayerUndoCommand::layer(), QgsVectorLayerEditBuffer::mAddedAttributes, QgsVectorLayerUndoCommand::mBuffer, mFieldIndex, QgsVectorLayer::pendingFields(), and QgsVectorLayerEditBuffer::updateLayerFields().
Member Data Documentation
QgsField QgsVectorLayerUndoCommandAddAttribute::mField private
Definition at line 123 of file qgsvectorlayerundocommand.h.
Referenced by redo().
int QgsVectorLayerUndoCommandAddAttribute::mFieldIndex private
Definition at line 124 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandAddAttribute(), redo(), and undo().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/qgsvectorlayerundocommand.h
/tmp/buildd/qgis-2.0.1/src/core/qgsvectorlayerundocommand.cpp