QGIS API Documentation: QgsCptCityArchive Class Reference
QgsCptCityArchive Class Reference
#include <qgscptcityarchive.h>
Public Member Functions
QgsCptCityArchive (QString archiveName=DEFAULT_CPTCITY_ARCHIVE, QString baseDir=QString())
~QgsCptCityArchive ()
QString baseDir () const
void setBaseDir (QString dirName)
QString copyingFileName (const QString &dirName) const
QString descFileName (const QString &dirName) const
bool isEmpty ()
QString archiveName () const
QVector< QgsCptCityDataItem * > rootItems () const
QVector< QgsCptCityDataItem * > selectionItems () const
Static Public Member Functions
static QString baseDir (QString archiveName)
static QString defaultBaseDir ()
static QString findFileName (const QString &target, const QString &startDir, const QString &baseDir)
static QMap< QString, QString > copyingInfo (const QString &fileName)
static QMap< QString, QString > description (const QString &fileName)
static QMap< double, QPair
< QColor, QColor > > gradientColorMap (const QString &fileName)
note not available in python bindings
static void initArchives (bool loadAll=false)
static void initArchive (QString archiveName, QString archiveBaseDir)
static void initDefaultArchive ()
static void clearArchives ()
static QgsCptCityArchive * defaultArchive ()
static QMap< QString,
QgsCptCityArchive * > archiveRegistry ()
Protected Attributes
QString mArchiveName
QString mBaseDir
QVector< QgsCptCityDataItem * > mRootItems
QVector< QgsCptCityDataItem * > mSelectionItems
Static Protected Attributes
static QString mDefaultArchiveName
static QMap< QString,
QgsCptCityArchive * > mArchiveRegistry
static QMap< QString, QMap
< QString, QString > > mCopyingInfoMap
Detailed Description
Definition at line 33 of file qgscptcityarchive.h.
Constructor & Destructor Documentation
QgsCptCityArchive::QgsCptCityArchive (QString archiveName = DEFAULT_CPTCITY_ARCHIVE, QString baseDir = QString())
Definition at line 45 of file qgscptcityarchive.cpp.
References QgsCptCityDataItem::isValid(), mBaseDir, mRootItems, mSelectionItems, QgsDebugMsg, and tr.
Referenced by initArchive().
QgsCptCityArchive::~QgsCptCityArchive ()
Definition at line 90 of file qgscptcityarchive.cpp.
References mRootItems, and mSelectionItems.
Member Function Documentation
QString QgsCptCityArchive::archiveName () const inline
Definition at line 57 of file qgscptcityarchive.h.
Referenced by defaultBaseDir(), initArchive(), and QgsCptCityBrowserModel::QgsCptCityBrowserModel().
QMap< QString, QgsCptCityArchive * > QgsCptCityArchive::archiveRegistry () static
Definition at line 42 of file qgscptcityarchive.cpp.
References mArchiveRegistry.
QString QgsCptCityArchive::baseDir () const
Definition at line 100 of file qgscptcityarchive.cpp.
References defaultBaseDir(), and mBaseDir.
Referenced by copyingFileName(), defaultBaseDir(), descFileName(), findFileName(), initArchives(), and initDefaultArchive().
QString QgsCptCityArchive::baseDir (QString archiveName) static
Definition at line 110 of file qgscptcityarchive.cpp.
References DEFAULT_CPTCITY_ARCHIVE, defaultBaseDir(), and mArchiveRegistry.
void QgsCptCityArchive::clearArchives () static
Definition at line 485 of file qgscptcityarchive.cpp.
References mArchiveRegistry.
QString QgsCptCityArchive::copyingFileName (const QString & dirName) const
Definition at line 157 of file qgscptcityarchive.cpp.
References baseDir(), and findFileName().
QgsStringMap QgsCptCityArchive::copyingInfo (const QString & fileName) static
Definition at line 169 of file qgscptcityarchive.cpp.
References mCopyingInfoMap, and QgsDebugMsg.
QgsCptCityArchive * QgsCptCityArchive::defaultArchive () static
Definition at line 413 of file qgscptcityarchive.cpp.
References DEFAULT_CPTCITY_ARCHIVE, mArchiveRegistry, and mDefaultArchiveName.
QString QgsCptCityArchive::defaultBaseDir () static
Definition at line 121 of file qgscptcityarchive.cpp.
References archiveName(), baseDir(), DEFAULT_CPTCITY_ARCHIVE, and QgsApplication::pkgDataPath().
Referenced by baseDir(), QgsCptCityColorRampV2::cloneGradientRamp(), QgsCptCityColorRampV2::copyingFileName(), QgsCptCityColorRampV2::descFileName(), QgsCptCityDirectoryItem::dirEntries(), QgsCptCityColorRampV2::fileName(), QgsCptCitySelectionItem::parseXML(), QgsCptCityDirectoryItem::QgsCptCityDirectoryItem(), and QgsCptCityDirectoryItem::rampsMap().
QString QgsCptCityArchive::descFileName (const QString & dirName) const
Definition at line 163 of file qgscptcityarchive.cpp.
References baseDir(), and findFileName().
QgsStringMap QgsCptCityArchive::description (const QString & fileName) static
Definition at line 270 of file qgscptcityarchive.cpp.
References QgsDebugMsg.
Referenced by QgsCptCityDirectoryItem::QgsCptCityDirectoryItem().
QString QgsCptCityArchive::findFileName (const QString & target, const QString & startDir, const QString & baseDir) static
Definition at line 136 of file qgscptcityarchive.cpp.
References baseDir().
Referenced by copyingFileName(), QgsCptCityColorRampV2::copyingFileName(), descFileName(), and QgsCptCityColorRampV2::descFileName().
QMap< double, QPair< QColor, QColor > > QgsCptCityArchive::gradientColorMap (const QString & fileName) static
note not available in python bindings
Definition at line 319 of file qgscptcityarchive.cpp.
References QgsSymbolLayerV2Utils::parseColor(), and QgsDebugMsg.
Referenced by QgsCptCityColorRampV2::loadFile().
void QgsCptCityArchive::initArchive (QString archiveName, QString archiveBaseDir) static
Definition at line 423 of file qgscptcityarchive.cpp.
References archiveName(), mArchiveRegistry, QgsCptCityArchive(), and QgsDebugMsg.
Referenced by initArchives(), and initDefaultArchive().
void QgsCptCityArchive::initArchives (bool loadAll = false) static
Definition at line 445 of file qgscptcityarchive.cpp.
References baseDir(), DEFAULT_CPTCITY_ARCHIVE, initArchive(), mDefaultArchiveName, QgsApplication::pkgDataPath(), and QgsDebugMsg.
void QgsCptCityArchive::initDefaultArchive () static
Definition at line 432 of file qgscptcityarchive.cpp.
References baseDir(), DEFAULT_CPTCITY_ARCHIVE, initArchive(), mArchiveRegistry, and QgsApplication::pkgDataPath().
bool QgsCptCityArchive::isEmpty ()
Definition at line 407 of file qgscptcityarchive.cpp.
References mRootItems.
QVector< QgsCptCityDataItem* > QgsCptCityArchive::rootItems () const inline
Definition at line 66 of file qgscptcityarchive.h.
Referenced by QgsCptCityBrowserModel::addRootItems().
QVector<QgsCptCityDataItem*> QgsCptCityArchive::selectionItems () const inline
Definition at line 67 of file qgscptcityarchive.h.
Referenced by QgsCptCityBrowserModel::addRootItems().
void QgsCptCityArchive::setBaseDir (QString dirName) inline
Definition at line 44 of file qgscptcityarchive.h.
Member Data Documentation
QString QgsCptCityArchive::mArchiveName protected
Definition at line 71 of file qgscptcityarchive.h.
QMap< QString, QgsCptCityArchive * > QgsCptCityArchive::mArchiveRegistry static protected
Definition at line 74 of file qgscptcityarchive.h.
Referenced by archiveRegistry(), baseDir(), clearArchives(), defaultArchive(), initArchive(), and initDefaultArchive().
QString QgsCptCityArchive::mBaseDir protected
Definition at line 72 of file qgscptcityarchive.h.
Referenced by baseDir(), and QgsCptCityArchive().
QMap< QString, QMap< QString, QString > > QgsCptCityArchive::mCopyingInfoMap static protected
Definition at line 79 of file qgscptcityarchive.h.
Referenced by copyingInfo().
QString QgsCptCityArchive::mDefaultArchiveName static protected
Definition at line 73 of file qgscptcityarchive.h.
Referenced by defaultArchive(), and initArchives().
QVector< QgsCptCityDataItem* > QgsCptCityArchive::mRootItems protected
Definition at line 76 of file qgscptcityarchive.h.
Referenced by isEmpty(), QgsCptCityArchive(), and ~QgsCptCityArchive().
QVector<QgsCptCityDataItem*> QgsCptCityArchive::mSelectionItems protected
Definition at line 77 of file qgscptcityarchive.h.
Referenced by QgsCptCityArchive(), and ~QgsCptCityArchive().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgscptcityarchive.h
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgscptcityarchive.cpp