QGIS API Documentation: QgsVectorRandomColorRampV2 Class Reference
QgsVectorRandomColorRampV2 Class Reference
#include <qgsvectorcolorrampv2.h>
Public Member Functions
QgsVectorRandomColorRampV2 (int count=DEFAULT_RANDOM_COUNT, int hueMin=DEFAULT_RANDOM_HUE_MIN, int hueMax=DEFAULT_RANDOM_HUE_MAX, int satMin=DEFAULT_RANDOM_SAT_MIN, int satMax=DEFAULT_RANDOM_SAT_MAX, int valMin=DEFAULT_RANDOM_VAL_MIN, int valMax=DEFAULT_RANDOM_VAL_MAX)
virtual double value (int index) const
virtual QColor color (double value) const
virtual QString type () const
virtual QgsVectorColorRampV2 * clone () const
virtual QgsStringMap properties () const
void updateColors ()
int count () const
int hueMin () const
int hueMax () const
int satMin () const
int satMax () const
int valMin () const
int valMax () const
void setCount (int val)
void setHueMin (int val)
void setHueMax (int val)
void setSatMin (int val)
void setSatMax (int val)
void setValMin (int val)
void setValMax (int val)
Public Member Functions inherited from QgsVectorColorRampV2
virtual ~QgsVectorColorRampV2 ()
Static Public Member Functions
static QgsVectorColorRampV2 * create (const QgsStringMap &properties=QgsStringMap())
Protected Attributes
int mCount
int mHueMin
int mHueMax
int mSatMin
int mSatMax
int mValMin
int mValMax
QList< QColor > mColors
Detailed Description
Definition at line 109 of file qgsvectorcolorrampv2.h.
Constructor & Destructor Documentation
QgsVectorRandomColorRampV2::QgsVectorRandomColorRampV2 (int count = DEFAULT_RANDOM_COUNT, int hueMin = DEFAULT_RANDOM_HUE_MIN, int hueMax = DEFAULT_RANDOM_HUE_MAX, int satMin = DEFAULT_RANDOM_SAT_MIN, int satMax = DEFAULT_RANDOM_SAT_MAX, int valMin = DEFAULT_RANDOM_VAL_MIN, int valMax = DEFAULT_RANDOM_VAL_MAX)
Definition at line 225 of file qgsvectorcolorrampv2.cpp.
References updateColors().
Referenced by clone(), and create().
Member Function Documentation
QgsVectorColorRampV2 * QgsVectorRandomColorRampV2::clone () const virtual
Implements QgsVectorColorRampV2.
Definition at line 268 of file qgsvectorcolorrampv2.cpp.
References mCount, mHueMax, mHueMin, mSatMax, mSatMin, mValMax, mValMin, and QgsVectorRandomColorRampV2().
QColor QgsVectorRandomColorRampV2::color (double value) const virtual
Implements QgsVectorColorRampV2.
Definition at line 257 of file qgsvectorcolorrampv2.cpp.
References mColors.
int QgsVectorRandomColorRampV2::count () const inline virtual
Implements QgsVectorColorRampV2.
Definition at line 131 of file qgsvectorcolorrampv2.h.
Referenced by create().
QgsVectorColorRampV2 * QgsVectorRandomColorRampV2::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 233 of file qgsvectorcolorrampv2.cpp.
References count(), DEFAULT_RANDOM_COUNT, DEFAULT_RANDOM_HUE_MAX, DEFAULT_RANDOM_HUE_MIN, DEFAULT_RANDOM_SAT_MAX, DEFAULT_RANDOM_SAT_MIN, DEFAULT_RANDOM_VAL_MAX, DEFAULT_RANDOM_VAL_MIN, hueMax(), hueMin(), QgsVectorRandomColorRampV2(), satMax(), satMin(), valMax(), and valMin().
Referenced by QgsSymbolLayerV2Utils::loadColorRamp().
int QgsVectorRandomColorRampV2::hueMax () const inline
Definition at line 133 of file qgsvectorcolorrampv2.h.
Referenced by create().
int QgsVectorRandomColorRampV2::hueMin () const inline
Definition at line 132 of file qgsvectorcolorrampv2.h.
Referenced by create().
QgsStringMap QgsVectorRandomColorRampV2::properties () const virtual
Implements QgsVectorColorRampV2.
Definition at line 273 of file qgsvectorcolorrampv2.cpp.
References mCount, mHueMax, mHueMin, mSatMax, mSatMin, mValMax, and mValMin.
int QgsVectorRandomColorRampV2::satMax () const inline
Definition at line 135 of file qgsvectorcolorrampv2.h.
Referenced by create().
int QgsVectorRandomColorRampV2::satMin () const inline
Definition at line 134 of file qgsvectorcolorrampv2.h.
Referenced by create().
void QgsVectorRandomColorRampV2::setCount (int val) inline
Definition at line 139 of file qgsvectorcolorrampv2.h.
void QgsVectorRandomColorRampV2::setHueMax (int val) inline
Definition at line 141 of file qgsvectorcolorrampv2.h.
void QgsVectorRandomColorRampV2::setHueMin (int val) inline
Definition at line 140 of file qgsvectorcolorrampv2.h.
void QgsVectorRandomColorRampV2::setSatMax (int val) inline
Definition at line 143 of file qgsvectorcolorrampv2.h.
void QgsVectorRandomColorRampV2::setSatMin (int val) inline
Definition at line 142 of file qgsvectorcolorrampv2.h.
void QgsVectorRandomColorRampV2::setValMax (int val) inline
Definition at line 145 of file qgsvectorcolorrampv2.h.
void QgsVectorRandomColorRampV2::setValMin (int val) inline
Definition at line 144 of file qgsvectorcolorrampv2.h.
virtual QString QgsVectorRandomColorRampV2::type () const inline virtual
Implements QgsVectorColorRampV2.
Definition at line 123 of file qgsvectorcolorrampv2.h.
void QgsVectorRandomColorRampV2::updateColors ()
Definition at line 286 of file qgsvectorcolorrampv2.cpp.
References mColors, mCount, mHueMax, mHueMin, mSatMax, mSatMin, mValMax, and mValMin.
Referenced by QgsVectorRandomColorRampV2().
int QgsVectorRandomColorRampV2::valMax () const inline
Definition at line 137 of file qgsvectorcolorrampv2.h.
Referenced by create().
int QgsVectorRandomColorRampV2::valMin () const inline
Definition at line 136 of file qgsvectorcolorrampv2.h.
Referenced by create().
double QgsVectorRandomColorRampV2::value (int index) const virtual
Implements QgsVectorColorRampV2.
Definition at line 251 of file qgsvectorcolorrampv2.cpp.
References mColors.
Member Data Documentation
QList<QColor> QgsVectorRandomColorRampV2::mColors protected
Definition at line 150 of file qgsvectorcolorrampv2.h.
Referenced by color(), updateColors(), and value().
int QgsVectorRandomColorRampV2::mCount protected
Definition at line 148 of file qgsvectorcolorrampv2.h.
Referenced by clone(), properties(), and updateColors().
int QgsVectorRandomColorRampV2::mHueMax protected
Definition at line 149 of file qgsvectorcolorrampv2.h.
Referenced by clone(), properties(), and updateColors().
int QgsVectorRandomColorRampV2::mHueMin protected
Definition at line 149 of file qgsvectorcolorrampv2.h.
Referenced by clone(), properties(), and updateColors().
int QgsVectorRandomColorRampV2::mSatMax protected
Definition at line 149 of file qgsvectorcolorrampv2.h.
Referenced by clone(), properties(), and updateColors().
int QgsVectorRandomColorRampV2::mSatMin protected
Definition at line 149 of file qgsvectorcolorrampv2.h.
Referenced by clone(), properties(), and updateColors().
int QgsVectorRandomColorRampV2::mValMax protected
Definition at line 149 of file qgsvectorcolorrampv2.h.
Referenced by clone(), properties(), and updateColors().
int QgsVectorRandomColorRampV2::mValMin protected
Definition at line 149 of file qgsvectorcolorrampv2.h.
Referenced by clone(), properties(), and updateColors().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsvectorcolorrampv2.h
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsvectorcolorrampv2.cpp