QGIS API Documentation: QgsFontMarkerSymbolLayerV2 Class Reference
QgsFontMarkerSymbolLayerV2 Class Reference
#include <qgsmarkersymbollayerv2.h>
Public Member Functions
QgsFontMarkerSymbolLayerV2 (QString fontFamily=DEFAULT_FONTMARKER_FONT, QChar chr=DEFAULT_FONTMARKER_CHR, double pointSize=DEFAULT_FONTMARKER_SIZE, QColor color=DEFAULT_FONTMARKER_COLOR, double angle=DEFAULT_FONTMARKER_ANGLE)
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
void renderPoint (const QPointF &point, QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
void writeSldMarker (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
QString fontFamily () const
void setFontFamily (QString family)
QChar character () const
void setCharacter (QChar ch)
Public Member Functions inherited from QgsMarkerSymbolLayerV2
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
void setSize (double size)
double size () const
void setScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod)
QgsSymbolV2::ScaleMethod scaleMethod () const
void setOffset (QPointF offset)
QPointF offset ()
virtual void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
void setOffsetUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit offsetUnit () const
void setSizeUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit sizeUnit () const
virtual void setOutputUnit (QgsSymbolV2::OutputUnit unit)
virtual QgsSymbolV2::OutputUnit outputUnit () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual void setColor (const QColor &color)
virtual QColor color () const
virtual ~QgsSymbolLayerV2 ()
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Protected Attributes
QString mFontFamily
QChar mChr
QPointF mChrOffset
QFont mFont
double mOrigSize
Protected Attributes inherited from QgsMarkerSymbolLayerV2
double mAngle
double mSize
QgsSymbolV2::OutputUnit mSizeUnit
QPointF mOffset
QgsSymbolV2::OutputUnit mOffsetUnit
QgsSymbolV2::ScaleMethod mScaleMethod
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Additional Inherited Members
Protected Member Functions inherited from QgsMarkerSymbolLayerV2
QgsMarkerSymbolLayerV2 (bool locked=false)
void markerOffset (QgsSymbolV2RenderContext &context, double &offsetX, double &offsetY)
Static Protected Member Functions inherited from QgsMarkerSymbolLayerV2
static QPointF _rotatedOffset (const QPointF &offset, double angle)
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 184 of file qgsmarkersymbollayerv2.h.
Constructor & Destructor Documentation
QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2 (QString fontFamily = DEFAULT_FONTMARKER_FONT, QChar chr = DEFAULT_FONTMARKER_CHR, double pointSize = DEFAULT_FONTMARKER_SIZE, QColor color = DEFAULT_FONTMARKER_COLOR, double angle = DEFAULT_FONTMARKER_ANGLE)
Definition at line 1110 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolLayerV2::color(), fontFamily(), QgsMarkerSymbolLayerV2::mAngle, mChr, QgsSymbolLayerV2::mColor, mFontFamily, QgsSymbolV2::MM, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetUnit, QgsMarkerSymbolLayerV2::mSize, and QgsMarkerSymbolLayerV2::mSizeUnit.
Referenced by clone(), create(), and createFromSld().
Member Function Documentation
QChar QgsFontMarkerSymbolLayerV2::character () const inline
Definition at line 219 of file qgsmarkersymbollayerv2.h.
QgsSymbolLayerV2 * QgsFontMarkerSymbolLayerV2::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1217 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::mAngle, mChr, QgsSymbolLayerV2::mColor, mFontFamily, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetUnit, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeUnit, QgsFontMarkerSymbolLayerV2(), QgsMarkerSymbolLayerV2::setOffset(), QgsMarkerSymbolLayerV2::setOffsetUnit(), and QgsMarkerSymbolLayerV2::setSizeUnit().
QgsSymbolLayerV2 * QgsFontMarkerSymbolLayerV2::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 1122 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolLayerV2::color(), QgsSymbolLayerV2Utils::decodeColor(), QgsSymbolLayerV2Utils::decodeOutputUnit(), QgsSymbolLayerV2Utils::decodePoint(), DEFAULT_FONTMARKER_ANGLE, DEFAULT_FONTMARKER_CHR, DEFAULT_FONTMARKER_COLOR, DEFAULT_FONTMARKER_FONT, DEFAULT_FONTMARKER_SIZE, fontFamily(), QgsFontMarkerSymbolLayerV2(), QgsMarkerSymbolLayerV2::setOffset(), QgsMarkerSymbolLayerV2::setOffsetUnit(), and QgsMarkerSymbolLayerV2::setSizeUnit().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsFontMarkerSymbolLayerV2::createFromSld (QDomElement & element) static
Definition at line 1254 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolLayerV2::color(), QgsSymbolLayerV2Utils::displacementFromSldElement(), QgsSymbolLayerV2Utils::externalMarkerFromSld(), fontFamily(), QgsMarkerSymbolLayerV2::offset(), QgsDebugMsg, QgsFontMarkerSymbolLayerV2(), QgsSymbolLayerV2Utils::rotationFromSldElement(), QgsMarkerSymbolLayerV2::setAngle(), QgsMarkerSymbolLayerV2::setOffset(), and QgsMarkerSymbolLayerV2::size().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QString QgsFontMarkerSymbolLayerV2::fontFamily () const inline
Definition at line 216 of file qgsmarkersymbollayerv2.h.
Referenced by create(), createFromSld(), and QgsFontMarkerSymbolLayerV2().
QString QgsFontMarkerSymbolLayerV2::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1151 of file qgsmarkersymbollayerv2.cpp.
QgsStringMap QgsFontMarkerSymbolLayerV2::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1203 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeColor(), QgsSymbolLayerV2Utils::encodeOutputUnit(), QgsSymbolLayerV2Utils::encodePoint(), QgsMarkerSymbolLayerV2::mAngle, mChr, QgsSymbolLayerV2::mColor, mFontFamily, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetUnit, QgsMarkerSymbolLayerV2::mSize, and QgsMarkerSymbolLayerV2::mSizeUnit.
void QgsFontMarkerSymbolLayerV2::renderPoint (const QPointF & point, QgsSymbolV2RenderContext & context) virtual
Implements QgsMarkerSymbolLayerV2.
Definition at line 1171 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::_rotatedOffset(), QgsSymbolV2RenderContext::alpha(), QgsSymbolV2::DataDefinedSizeScale, QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsMarkerSymbolLayerV2::mAngle, mChr, mChrOffset, QgsSymbolLayerV2::mColor, mFont, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetUnit, mOrigSize, QgsMarkerSymbolLayerV2::mSize, QgsRenderContext::painter(), QgsSymbolV2RenderContext::renderContext(), QgsSymbolV2RenderContext::renderHints(), QgsSymbolV2RenderContext::selected(), and QgsRenderContext::selectionColor().
void QgsFontMarkerSymbolLayerV2::setCharacter (QChar ch) inline
Definition at line 220 of file qgsmarkersymbollayerv2.h.
void QgsFontMarkerSymbolLayerV2::setFontFamily (QString family) inline
Definition at line 217 of file qgsmarkersymbollayerv2.h.
void QgsFontMarkerSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 1156 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mChr, mChrOffset, mFont, mFontFamily, mOrigSize, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeUnit, and QgsSymbolV2RenderContext::renderContext().
void QgsFontMarkerSymbolLayerV2::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 1166 of file qgsmarkersymbollayerv2.cpp.
void QgsFontMarkerSymbolLayerV2::writeSldMarker (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsMarkerSymbolLayerV2.
Definition at line 1226 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::createDisplacementElement(), QgsSymbolLayerV2Utils::createRotationElement(), QgsSymbolLayerV2Utils::externalMarkerToSld(), QgsMarkerSymbolLayerV2::mAngle, mChr, QgsSymbolLayerV2::mColor, mFontFamily, QgsMarkerSymbolLayerV2::mOffset, and QgsMarkerSymbolLayerV2::mSize.
Member Data Documentation
QChar QgsFontMarkerSymbolLayerV2::mChr protected
Definition at line 225 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), properties(), QgsFontMarkerSymbolLayerV2(), renderPoint(), startRender(), and writeSldMarker().
QPointF QgsFontMarkerSymbolLayerV2::mChrOffset protected
Definition at line 227 of file qgsmarkersymbollayerv2.h.
Referenced by renderPoint(), and startRender().
QFont QgsFontMarkerSymbolLayerV2::mFont protected
Definition at line 228 of file qgsmarkersymbollayerv2.h.
Referenced by renderPoint(), and startRender().
QString QgsFontMarkerSymbolLayerV2::mFontFamily protected
Definition at line 224 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), properties(), QgsFontMarkerSymbolLayerV2(), startRender(), and writeSldMarker().
double QgsFontMarkerSymbolLayerV2::mOrigSize protected
Definition at line 229 of file qgsmarkersymbollayerv2.h.
Referenced by renderPoint(), and startRender().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsmarkersymbollayerv2.h
/tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsmarkersymbollayerv2.cpp