QGIS API Documentation: /tmp/buildd/qgis-2.0.1/src/core/qgsapplication.cpp File Reference
qgsapplication.cpp File Reference
#include "qgsapplication.h"
#include "qgslogger.h"
#include "qgsmaplayerregistry.h"
#include "qgsproviderregistry.h"
#include "qgsexception.h"
#include "qgsgeometry.h"
#include <QDir>
#include <QFile>
#include <QFileOpenEvent>
#include <QMessageBox>
#include <QPalette>
#include <QProcess>
#include <QSettings>
#include <QIcon>
#include <QPixmap>
#include <netinet/in.h>
#include "qgsconfig.h"
#include <gdal.h>
#include <ogr_api.h>
#include <cpl_conv.h>
#include <sqlite3.h>
Functions
QObject * ABISYM (QgsApplication::mFileOpenEventReceiver)
QStringList ABISYM (QgsApplication::mFileOpenEventList)
QString ABISYM (QgsApplication::mPrefixPath)
QString ABISYM (QgsApplication::mPluginPath)
QString ABISYM (QgsApplication::mPkgDataPath)
QString ABISYM (QgsApplication::mLibraryPath)
QString ABISYM (QgsApplication::mLibexecPath)
QString ABISYM (QgsApplication::mThemeName)
QStringList ABISYM (QgsApplication::mDefaultSvgPaths)
QMap< QString, QString > ABISYM (QgsApplication::mSystemEnvVars)
QString ABISYM (QgsApplication::mConfigPath)
bool ABISYM (QgsApplication::mRunningFromBuildDir)
QString ABISYM (QgsApplication::mBuildSourcePath)
QString ABISYM (QgsApplication::mBuildOutputPath)
QStringList ABISYM (QgsApplication::mGdalSkipList)
Function Documentation
QObject* ABISYM (QgsApplication::mFileOpenEventReceiver)
Referenced by QgsApplication::buildOutputPath(), QgsApplication::buildSourcePath(), QgsApplication::isRunningFromBuildDir(), QgsApplication::skippedGdalDrivers(), and QgsApplication::systemEnvVars().
QStringList ABISYM (QgsApplication::mFileOpenEventList)
QString ABISYM (QgsApplication::mPrefixPath)
QString ABISYM (QgsApplication::mPluginPath)
QString ABISYM (QgsApplication::mPkgDataPath)
QString ABISYM (QgsApplication::mLibraryPath)
QString ABISYM (QgsApplication::mLibexecPath)
QString ABISYM (QgsApplication::mThemeName)
QStringList ABISYM (QgsApplication::mDefaultSvgPaths)
QMap<QString, QString> ABISYM (QgsApplication::mSystemEnvVars)
QString ABISYM (QgsApplication::mConfigPath)
bool ABISYM (QgsApplication::mRunningFromBuildDir)
QString ABISYM (QgsApplication::mBuildSourcePath)
QString ABISYM (QgsApplication::mBuildOutputPath)
QStringList ABISYM (QgsApplication::mGdalSkipList)