QGIS API Documentation: /tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgsgraduatedsymbolrendererv2.cpp File Reference
qgsgraduatedsymbolrendererv2.cpp File Reference
#include "qgsgraduatedsymbolrendererv2.h"
#include "qgssymbolv2.h"
#include "qgssymbollayerv2utils.h"
#include "qgsvectorcolorrampv2.h"
#include "qgsfeature.h"
#include "qgsvectorlayer.h"
#include "qgslogger.h"
#include "qgsvectordataprovider.h"
#include <QDomDocument>
#include <QDomElement>
#include <QSettings>
#include <limits>
#include <cmath>
#include <ctime>
Functions
static QList< double > _calcEqualIntervalBreaks (double minimum, double maximum, int classes)
static QList< double > _calcQuantileBreaks (QList< double > values, int classes)
static QList< double > _calcPrettyBreaks (double minimum, double maximum, int classes)
static QList< double > _calcStdDevBreaks (QList< double > values, int classes, QList< int > &labels)
static QList< double > _calcJenksBreaks (QList< double > values, int classes, double minimum, double maximum, int maximumSize=1000)
bool valueLessThan (const QgsRendererRangeV2 &r1, const QgsRendererRangeV2 &r2)
bool valueGreaterThan (const QgsRendererRangeV2 &r1, const QgsRendererRangeV2 &r2)
bool labelLessThan (const QgsRendererRangeV2 &r1, const QgsRendererRangeV2 &r2)
bool labelGreaterThan (const QgsRendererRangeV2 &r1, const QgsRendererRangeV2 &r2)
Function Documentation
static QList<double> _calcEqualIntervalBreaks (double minimum, double maximum, int classes) static
Definition at line 385 of file qgsgraduatedsymbolrendererv2.cpp.
Referenced by QgsGraduatedSymbolRendererV2::createRenderer().
static QList<double> _calcJenksBreaks (QList< double > values, int classes, double minimum, double maximum, int maximumSize = 1000) static
Definition at line 641 of file qgsgraduatedsymbolrendererv2.cpp.
References MathUtils::max(), and QgsDebugMsg.
Referenced by QgsGraduatedSymbolRendererV2::createRenderer().
static QList<double> _calcPrettyBreaks (double minimum, double maximum, int classes) static
Definition at line 448 of file qgsgraduatedsymbolrendererv2.cpp.
References QgsDebugMsg.
Referenced by _calcStdDevBreaks(), and QgsGraduatedSymbolRendererV2::createRenderer().
static QList<double> _calcQuantileBreaks (QList< double > values, int classes) static
Definition at line 410 of file qgsgraduatedsymbolrendererv2.cpp.
Referenced by QgsGraduatedSymbolRendererV2::createRenderer().
static QList<double> _calcStdDevBreaks (QList< double > values, int classes, QList< int > & labels) static
Definition at line 599 of file qgsgraduatedsymbolrendererv2.cpp.
References _calcPrettyBreaks().
Referenced by QgsGraduatedSymbolRendererV2::createRenderer().
bool labelGreaterThan (const QgsRendererRangeV2 & r1, const QgsRendererRangeV2 & r2)
Definition at line 1201 of file qgsgraduatedsymbolrendererv2.cpp.
References labelLessThan().
bool labelLessThan (const QgsRendererRangeV2 & r1, const QgsRendererRangeV2 & r2)
Definition at line 1196 of file qgsgraduatedsymbolrendererv2.cpp.
References QgsRendererRangeV2::label().
bool valueGreaterThan (const QgsRendererRangeV2 & r1, const QgsRendererRangeV2 & r2)
Definition at line 1178 of file qgsgraduatedsymbolrendererv2.cpp.
References valueLessThan().
bool valueLessThan (const QgsRendererRangeV2 & r1, const QgsRendererRangeV2 & r2)
Definition at line 1173 of file qgsgraduatedsymbolrendererv2.cpp.
References QgsRendererRangeV2::lowerValue().