QGIS API Documentation: /tmp/buildd/qgis-2.0.1/src/core/qgsogcutils.cpp File Reference
qgsogcutils.cpp File Reference
#include "qgsogcutils.h"
#include "qgsexpression.h"
#include "qgsgeometry.h"
#include <QStringList>
#include <QTextStream>
#include <netinet/in.h>
Functions
static const QMap< QString, int > & binaryOperatorsTagNamesMap ()
static int binaryOperatorFromTagName (const QString &tagName)
static QString binaryOperatorToTagName (QgsExpression::BinaryOperator op)
static bool isBinaryOperator (const QString &tagName)
static bool isSpatialOperator (const QString &tagName)
static QMap< QString, QString > binarySpatialOpsMap ()
static bool isBinarySpatialOperator (const QString &fnName)
static QString tagNameForSpatialOperator (const QString &fnName)
static bool isGeometryColumn (const QgsExpression::Node *node)
Variables
static const QString GML_NAMESPACE = "http://www.opengis.net/gml"
Function Documentation
static int binaryOperatorFromTagName (const QString & tagName) static
Definition at line 1480 of file qgsogcutils.cpp.
References binaryOperatorsTagNamesMap().
Referenced by isBinaryOperator(), and QgsOgcUtils::nodeBinaryOperatorFromOgcFilter().
static const QMap<QString, int>& binaryOperatorsTagNamesMap () static
Definition at line 1455 of file qgsogcutils.cpp.
References QgsExpression::boAnd, QgsExpression::boDiv, QgsExpression::boEQ, QgsExpression::boGE, QgsExpression::boGT, QgsExpression::boLE, QgsExpression::boLike, QgsExpression::boLT, QgsExpression::boMinus, QgsExpression::boMul, QgsExpression::boNE, QgsExpression::boOr, and QgsExpression::boPlus.
Referenced by binaryOperatorFromTagName(), and binaryOperatorToTagName().
static QString binaryOperatorToTagName (QgsExpression::BinaryOperator op) static
Definition at line 1486 of file qgsogcutils.cpp.
References binaryOperatorsTagNamesMap().
Referenced by QgsOgcUtils::expressionBinaryOperatorToOgcFilter().
static QMap<QString, QString> binarySpatialOpsMap () static
Definition at line 2044 of file qgsogcutils.cpp.
Referenced by isBinarySpatialOperator(), and tagNameForSpatialOperator().
static bool isBinaryOperator (const QString & tagName) static
Definition at line 1491 of file qgsogcutils.cpp.
References binaryOperatorFromTagName().
Referenced by QgsOgcUtils::nodeFromOgcFilter().
static bool isBinarySpatialOperator (const QString & fnName) static
Definition at line 2060 of file qgsogcutils.cpp.
References binarySpatialOpsMap().
Referenced by QgsOgcUtils::expressionFunctionToOgcFilter().
static bool isGeometryColumn (const QgsExpression::Node * node) static
Definition at line 2070 of file qgsogcutils.cpp.
References QgsExpression::NodeFunction::fnIndex(), QgsExpression::Functions(), QgsExpression::Function::name(), QgsExpression::Node::nodeType(), and QgsExpression::ntFunction.
Referenced by QgsOgcUtils::expressionFunctionToOgcFilter().
static bool isSpatialOperator (const QString & tagName) static
Definition at line 1497 of file qgsogcutils.cpp.
Referenced by QgsOgcUtils::nodeFromOgcFilter().
static QString tagNameForSpatialOperator (const QString & fnName) static
Definition at line 2065 of file qgsogcutils.cpp.
References binarySpatialOpsMap().
Referenced by QgsOgcUtils::expressionFunctionToOgcFilter().
Variable Documentation
const QString GML_NAMESPACE = "http://www.opengis.net/gml" static
Definition at line 16 of file qgsogcutils.cpp.