QGIS API Documentation: /tmp/buildd/qgis-2.0.1/src/core/symbology-ng/qgssymbologyv2conversion.cpp File Reference
qgssymbologyv2conversion.cpp File Reference
#include "qgssymbologyv2conversion.h"
#include "qgslogger.h"
#include "qgsmarkersymbollayerv2.h"
#include "qgslinesymbollayerv2.h"
#include "qgsfillsymbollayerv2.h"
#include "qgssinglesymbolrendererv2.h"
#include "qgsgraduatedsymbolrendererv2.h"
#include "qgscategorizedsymbolrendererv2.h"
Classes
struct QgsOldSymbolMeta
Functions
static QgsOldSymbolMeta readSymbolMeta (const QDomNode &synode)
static QColor readSymbolColor (const QDomNode &synode, bool fillColor)
static double readOutlineWidth (const QDomNode &synode)
static Qt::PenStyle readOutlineStyle (const QDomNode &synode)
static Qt::BrushStyle readBrushStyle (const QDomNode &synode)
static QString readMarkerSymbolName (const QDomNode &synode)
static float readMarkerSymbolSize (const QDomNode &synode)
static QgsSymbolV2 * readOldSymbol (const QDomNode &synode, QGis::GeometryType geomType)
static QgsFeatureRendererV2 * readOldSingleSymbolRenderer (const QDomNode &rnode, QGis::GeometryType geomType)
static QgsFeatureRendererV2 * readOldGraduatedSymbolRenderer (const QDomNode &rnode, QGis::GeometryType geomType)
static QgsFeatureRendererV2 * readOldUniqueValueRenderer (const QDomNode &rnode, QGis::GeometryType geomType)
Function Documentation
static Qt::BrushStyle readBrushStyle (const QDomNode & synode) static
Definition at line 97 of file qgssymbologyv2conversion.cpp.
References QgsSymbologyV2Conversion::qString2BrushStyle().
Referenced by readOldSymbol().
static QString readMarkerSymbolName (const QDomNode & synode) static
Definition at line 104 of file qgssymbologyv2conversion.cpp.
Referenced by readOldSymbol().
static float readMarkerSymbolSize (const QDomNode & synode) static
Definition at line 115 of file qgssymbologyv2conversion.cpp.
References DEFAULT_POINT_SIZE.
Referenced by readOldSymbol().
static QgsFeatureRendererV2* readOldGraduatedSymbolRenderer (const QDomNode & rnode, QGis::GeometryType geomType) static
Definition at line 202 of file qgssymbologyv2conversion.cpp.
References QgsGraduatedSymbolRendererV2::Custom, QgsGraduatedSymbolRendererV2::EqualInterval, QgsOldSymbolMeta::label, QgsOldSymbolMeta::lowerValue, QgsGraduatedSymbolRendererV2::Quantile, readOldSymbol(), readSymbolMeta(), QgsGraduatedSymbolRendererV2::setMode(), and QgsOldSymbolMeta::upperValue.
Referenced by QgsSymbologyV2Conversion::readOldRenderer().
static QgsFeatureRendererV2* readOldSingleSymbolRenderer (const QDomNode & rnode, QGis::GeometryType geomType) static
Definition at line 190 of file qgssymbologyv2conversion.cpp.
References readOldSymbol().
Referenced by QgsSymbologyV2Conversion::readOldRenderer().
static QgsSymbolV2* readOldSymbol (const QDomNode & synode, QGis::GeometryType geomType) static
Definition at line 128 of file qgssymbologyv2conversion.cpp.
References MathUtils::angle(), QGis::Line, QGis::Point, QGis::Polygon, readBrushStyle(), readMarkerSymbolName(), readMarkerSymbolSize(), readOutlineStyle(), readOutlineWidth(), readSymbolColor(), and size.
Referenced by readOldGraduatedSymbolRenderer(), readOldSingleSymbolRenderer(), and readOldUniqueValueRenderer().
static QgsFeatureRendererV2* readOldUniqueValueRenderer (const QDomNode & rnode, QGis::GeometryType geomType) static
Definition at line 251 of file qgssymbologyv2conversion.cpp.
References QgsOldSymbolMeta::label, QgsOldSymbolMeta::lowerValue, readOldSymbol(), and readSymbolMeta().
Referenced by QgsSymbologyV2Conversion::readOldRenderer().
static Qt::PenStyle readOutlineStyle (const QDomNode & synode) static
Definition at line 90 of file qgssymbologyv2conversion.cpp.
References QgsSymbologyV2Conversion::qString2PenStyle().
Referenced by readOldSymbol().
static double readOutlineWidth (const QDomNode & synode) static
Definition at line 82 of file qgssymbologyv2conversion.cpp.
Referenced by readOldSymbol().
static QColor readSymbolColor (const QDomNode & synode, bool fillColor) static
Definition at line 72 of file qgssymbologyv2conversion.cpp.
Referenced by readOldSymbol().
static QgsOldSymbolMeta readSymbolMeta (const QDomNode & synode) static
Definition at line 36 of file qgssymbologyv2conversion.cpp.
References QgsOldSymbolMeta::label, QgsOldSymbolMeta::lowerValue, and QgsOldSymbolMeta::upperValue.
Referenced by readOldGraduatedSymbolRenderer(), and readOldUniqueValueRenderer().