Quantum GIS API Documentation: QgsMessageLog Class Reference
QgsMessageLog Class Reference
QGIS core library
Interface for logging messages from QGIS in GUI independent way.
#include <qgsmessagelog.h>
Signals
void messageReceived (QString message, QString tag, int level)
Static Public Member Functions
static QgsMessageLog * instance ()
static void logMessage (QString message, QString tag=QString::null, int level=0)
add a message to the instance (and create it if necessary)
Private Member Functions
QgsMessageLog ()
void emitMessage (QString message, QString tag, int level)
Static Private Attributes
static QgsMessageLog * sInstance = 0
Detailed Description
Interface for logging messages from QGIS in GUI independent way.
This class provides abstraction of a tabbed window for showing messages to the user. By default QgsMessageLogOutput will be used if not overridden with another message log creator function.
QGIS application uses QgsMessageLog class for logging messages in a dockable window for the user.
Note:
added in 1.9
Definition at line 33 of file qgsmessagelog.h.
Constructor & Destructor Documentation
QgsMessageLog::QgsMessageLog () [private]
Definition at line 25 of file qgsmessagelog.cpp.
References sInstance.
Referenced by instance().
Member Function Documentation
void QgsMessageLog::emitMessage (QString message, QString tag, int level) [private]
Definition at line 46 of file qgsmessagelog.cpp.
References messageReceived().
Referenced by logMessage().
QgsMessageLog * QgsMessageLog::instance () [static]
Definition at line 31 of file qgsmessagelog.cpp.
References QgsMessageLog(), and sInstance.
Referenced by logMessage(), QgsMessageLogConsole::QgsMessageLogConsole(), and QgsMessageLogViewer::QgsMessageLogViewer().
void QgsMessageLog::logMessage (QString message, QString tag = QString::null, int level = 0) [static]
add a message to the instance (and create it if necessary)
Definition at line 39 of file qgsmessagelog.cpp.
References emitMessage(), instance(), and QgsDebugMsg.
Referenced by QgsVectorFileWriter::addFeature(), QgsGeometry::addPart(), QgsGeometry::addRing(), QgsGeometry::closestVertexWithContext(), QgsVectorLayer::commitChanges(), QgsGeometry::contains(), createGeosCollection(), createGeosCoordSequence(), createGeosLinearRing(), createGeosLineString(), createGeosPolygon(), QgsRasterLayer::draw(), QgsGeometry::fromMultiPoint(), QgsGeometry::fromMultiPolygon(), QgsGeometry::fromMultiPolyline(), QgsGeometry::fromWkt(), QgsVectorLayerImport::importLayer(), QgsGeometry::isGeosEmpty(), QgsGeometry::isGeosValid(), QgsMapRenderer::layerExtentToOutputExtent(), QgsRasterLayer::loadProvider(), QgsRasterLayer::loadProviderLibrary(), QgsDistanceArea::measureLine(), QgsDistanceArea::measurePolygon(), QgsCoordinateReferenceSystem::openDb(), QgsProviderRegistry::provider(), QgsRasterLayer::readValue(), QgsGeometry::reshapeLine(), QgsGeometry::reshapePolygon(), QgsCoordinateReferenceSystem::saveAsUserCRS(), QgsRasterLayer::setDataProvider(), QgsDistanceArea::setEllipsoid(), QgsVectorDataProvider::setEncoding(), QgsMessageOutputConsole::showMessage(), QgsCoordinateTransform::transformCoords(), and QgsRasterLayer::writeXml().
void QgsMessageLog::messageReceived (QString message, QString tag, int level) [signal]
Referenced by emitMessage().
Member Data Documentation
QgsMessageLog * QgsMessageLog::sInstance = 0 [static, private]
Definition at line 51 of file qgsmessagelog.h.
Referenced by instance(), and QgsMessageLog().
The documentation for this class was generated from the following files:
src/core/qgsmessagelog.h
src/core/qgsmessagelog.cpp