Quantum GIS API Documentation: QgsExpression::NodeList Class Reference
QgsExpression::NodeList Class Reference
#include <qgsexpression.h>
Public Member Functions
NodeList ()
virtual ~NodeList ()
void append (Node *node)
int count ()
QList< Node * > list ()
virtual QString dump () const
virtual void toOgcFilter (QDomDocument &doc, QDomElement &element) const
Protected Attributes
QList< Node * > mList
Detailed Description
Definition at line 243 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::NodeList::NodeList () [inline]
Definition at line 246 of file qgsexpression.h.
virtual QgsExpression::NodeList::~NodeList () [inline, virtual]
Definition at line 247 of file qgsexpression.h.
Member Function Documentation
void QgsExpression::NodeList::append (Node * node) [inline]
Definition at line 248 of file qgsexpression.h.
Referenced by QgsExpression::NodeFunction::createFromOgcFilter().
int QgsExpression::NodeList::count () [inline]
Definition at line 249 of file qgsexpression.h.
QString QgsExpression::NodeList::dump () const [virtual]
Definition at line 743 of file qgsexpression.cpp.
References QgsExpression::Node::dump().
QList<Node*> QgsExpression::NodeList::list () [inline]
Definition at line 250 of file qgsexpression.h.
void QgsExpression::NodeList::toOgcFilter (QDomDocument & doc, QDomElement & element) const [virtual]
Definition at line 754 of file qgsexpression.cpp.
References QgsExpression::Node::toOgcFilter().
Member Data Documentation
QList<Node*> QgsExpression::NodeList::mList [protected]
Definition at line 256 of file qgsexpression.h.
The documentation for this class was generated from the following files:
src/core/qgsexpression.h
src/core/qgsexpression.cpp