Quantum GIS API Documentation: QgsExpression::NodeUnaryOperator Class Reference
QgsExpression::NodeUnaryOperator Class Reference
#include <qgsexpression.h>
Public Member Functions
NodeUnaryOperator (UnaryOperator op, Node *operand)
~NodeUnaryOperator ()
UnaryOperator op ()
Node * operand ()
virtual bool prepare (QgsExpression *parent, const QgsFieldMap &fields)
virtual QVariant eval (QgsExpression *parent, QgsFeature *f)
virtual QString dump () const
virtual void toOgcFilter (QDomDocument &doc, QDomElement &element) const
virtual QStringList referencedColumns () const
virtual bool needsGeometry () const
virtual void accept (Visitor &v)
Static Public Member Functions
static QgsExpression::Node * createFromOgcFilter (QDomElement &element, QString &errorMessage)
Protected Attributes
UnaryOperator mOp
Node * mOperand
Detailed Description
Definition at line 259 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::NodeUnaryOperator::NodeUnaryOperator (UnaryOperator op, Node * operand) [inline]
Definition at line 262 of file qgsexpression.h.
QgsExpression::NodeUnaryOperator::~NodeUnaryOperator () [inline]
Definition at line 263 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::NodeUnaryOperator::accept (Visitor & v) [inline, virtual]
Implements QgsExpression::Node.
Definition at line 277 of file qgsexpression.h.
References QgsExpression::Visitor::visit().
QgsExpression::Node * QgsExpression::NodeUnaryOperator::createFromOgcFilter (QDomElement & element, QString & errorMessage) [static]
Reimplemented from QgsExpression::Node.
Definition at line 823 of file qgsexpression.cpp.
References QgsExpression::createFromOgcFilter(), and QgsExpression::UnaryOgcOperatorText.
QString QgsExpression::NodeUnaryOperator::dump () const [virtual]
Implements QgsExpression::Node.
Definition at line 797 of file qgsexpression.cpp.
References QgsExpression::UnaryOperatorText.
QVariant QgsExpression::NodeUnaryOperator::eval (QgsExpression * parent, QgsFeature * f) [virtual]
Implements QgsExpression::Node.
Definition at line 764 of file qgsexpression.cpp.
References ENSURE_NO_EVAL_ERROR, getDoubleValue(), getIntValue(), getTVLValue(), isDoubleSafe(), isIntSafe(), NOT, SET_EVAL_ERROR, tvl2variant(), QgsExpression::uoMinus, and QgsExpression::uoNot.
virtual bool QgsExpression::NodeUnaryOperator::needsGeometry () const [inline, virtual]
Implements QgsExpression::Node.
Definition at line 276 of file qgsexpression.h.
UnaryOperator QgsExpression::NodeUnaryOperator::op () [inline]
Definition at line 265 of file qgsexpression.h.
Node* QgsExpression::NodeUnaryOperator::operand () [inline]
Definition at line 266 of file qgsexpression.h.
bool QgsExpression::NodeUnaryOperator::prepare (QgsExpression * parent, const QgsFieldMap & fields) [virtual]
Implements QgsExpression::Node.
Definition at line 792 of file qgsexpression.cpp.
virtual QStringList QgsExpression::NodeUnaryOperator::referencedColumns () const [inline, virtual]
Implements QgsExpression::Node.
Definition at line 275 of file qgsexpression.h.
void QgsExpression::NodeUnaryOperator::toOgcFilter (QDomDocument & doc, QDomElement & element) const [virtual]
Reimplemented from QgsExpression::Node.
Definition at line 802 of file qgsexpression.cpp.
References QgsExpression::UnaryOperatorText, QgsExpression::uoMinus, and QgsExpression::uoNot.
Member Data Documentation
UnaryOperator QgsExpression::NodeUnaryOperator::mOp [protected]
Definition at line 280 of file qgsexpression.h.
Node* QgsExpression::NodeUnaryOperator::mOperand [protected]
Definition at line 281 of file qgsexpression.h.
The documentation for this class was generated from the following files:
src/core/qgsexpression.h
src/core/qgsexpression.cpp