Quantum GIS API Documentation: QgsPieDiagram Class Reference
QgsPieDiagram Class Reference
#include <qgsdiagram.h>
Public Member Functions
QgsPieDiagram ()
~QgsPieDiagram ()
void renderDiagram (const QgsAttributeMap &att, QgsRenderContext &c, const QgsDiagramSettings &s, const QPointF &position)
Draws the diagram at the given position (in pixel coordinates)
QString diagramName () const
Private Attributes
QBrush mCategoryBrush
QPen mPen
Detailed Description
Definition at line 76 of file qgsdiagram.h.
Constructor & Destructor Documentation
QgsPieDiagram::QgsPieDiagram ()
Definition at line 241 of file qgsdiagram.cpp.
References mCategoryBrush, and mPen.
QgsPieDiagram::~QgsPieDiagram ()
Definition at line 247 of file qgsdiagram.cpp.
Member Function Documentation
QString QgsPieDiagram::diagramName () const [inline, virtual]
Implements QgsDiagram.
Definition at line 83 of file qgsdiagram.h.
void QgsPieDiagram::renderDiagram (const QgsAttributeMap & att, QgsRenderContext & c, const QgsDiagramSettings & s, const QPointF & position) [virtual]
Draws the diagram at the given position (in pixel coordinates)
Implements QgsDiagram.
Definition at line 251 of file qgsdiagram.cpp.
References QgsDiagramSettings::categoryColors, QgsDiagramSettings::categoryIndices, mCategoryBrush, mPen, QgsRenderContext::painter(), QgsDiagramSettings::penColor, QgsDiagram::setPenWidth(), QgsDiagramSettings::size, and QgsDiagram::sizePainterUnits().
Member Data Documentation
QBrush QgsPieDiagram::mCategoryBrush [private]
Definition at line 86 of file qgsdiagram.h.
Referenced by QgsPieDiagram(), and renderDiagram().
QPen QgsPieDiagram::mPen [private]
Definition at line 87 of file qgsdiagram.h.
Referenced by QgsPieDiagram(), and renderDiagram().
The documentation for this class was generated from the following files:
src/core/qgsdiagram.h
src/core/qgsdiagram.cpp