Quantum GIS API Documentation: QgsMarkerCatalogue Class Reference
QgsMarkerCatalogue Class Reference
Catalogue of point symbols.
#include <qgsmarkercatalogue.h>
Public Slots
void refreshList ()
Signals
void markersRefreshed ()
Public Member Functions
~QgsMarkerCatalogue ()
Destructor.
QStringList list ()
List of available markers.
QImage imageMarker (QString fullName, double size, QPen pen, QBrush brush, double opacity=1.0)
Returns pixmap of the marker.
QPicture pictureMarker (QString fullName, double size, QPen pen, QBrush brush, double opacity=1.0)
Returns qpicture of the marker.
Static Public Member Functions
static QgsMarkerCatalogue * instance ()
Access to canonical QgsMarkerCatalogue instance.
static bool svgMarker (QPainter *thepPainter, QString name, double size)
Returns a pixmap given a file name of a svg marker NOTE: this method needs to be public static for QgsMarkerDialog::visualizeMarkers.
Private Member Functions
QgsMarkerCatalogue ()
Constructor.
void hardMarker (QPainter *thepPainter, int imageSize, QString name, double size, QPen pen, QBrush brush)
Hard coded.
bool fontMarker (QPainter *thepPainter, QString name, double size)
Private Attributes
QStringList mList
List of availabel markers.
Static Private Attributes
static QgsMarkerCatalogue * mMarkerCatalogue = 0
Detailed Description
Catalogue of point symbols.
Definition at line 30 of file qgsmarkercatalogue.h.
Constructor & Destructor Documentation
QgsMarkerCatalogue::~QgsMarkerCatalogue ()
Destructor.
Definition at line 100 of file qgsmarkercatalogue.cpp.
QgsMarkerCatalogue::QgsMarkerCatalogue () [private]
Constructor.
Definition at line 48 of file qgsmarkercatalogue.cpp.
References refreshList().
Referenced by instance().
Member Function Documentation
bool QgsMarkerCatalogue::fontMarker (QPainter * thepPainter, QString name, double size) [private]
Definition at line 238 of file qgsmarkercatalogue.cpp.
Referenced by imageMarker().
void QgsMarkerCatalogue::hardMarker (QPainter * thepPainter, int imageSize, QString name, double size, QPen pen, QBrush brush) [private]
Hard coded.
Definition at line 285 of file qgsmarkercatalogue.cpp.
References DEG2RAD, and QgsDebugMsgLevel.
Referenced by imageMarker(), and pictureMarker().
QImage QgsMarkerCatalogue::imageMarker (QString fullName, double size, QPen pen, QBrush brush, double opacity = 1.0)
Returns pixmap of the marker.
Parameters:
fullName full name, e.g. hard:circle, svg:/home/usr1/marker1.svg
size size of image
pen pen to use
brush brush to use
opacity opacity to use
Definition at line 114 of file qgsmarkercatalogue.cpp.
References fontMarker(), hardMarker(), QgsDebugMsg, size, and svgMarker().
Referenced by QgsSymbol::cache(), QgsSymbol::cache2(), QgsSymbol::getPointSymbolAsImage(), and QgsContinuousColorRenderer::renderFeature().
QgsMarkerCatalogue * QgsMarkerCatalogue::instance () [static]
Access to canonical QgsMarkerCatalogue instance.
Definition at line 104 of file qgsmarkercatalogue.cpp.
References mMarkerCatalogue, and QgsMarkerCatalogue().
Referenced by QgsSymbol::cache(), QgsSymbol::cache2(), QgsSymbol::getPointSymbolAsImage(), and QgsContinuousColorRenderer::renderFeature().
QStringList QgsMarkerCatalogue::list ()
List of available markers.
Definition at line 95 of file qgsmarkercatalogue.cpp.
References mList.
void QgsMarkerCatalogue::markersRefreshed () [signal]
Referenced by refreshList().
QPicture QgsMarkerCatalogue::pictureMarker (QString fullName, double size, QPen pen, QBrush brush, double opacity = 1.0)
Returns qpicture of the marker.
Parameters:
fullName full name, e.g. hard:circle, svg:/home/usr1/marker1.svg
size size of marker
pen pen to use
brush brush to use
opacity opacity to use
Definition at line 191 of file qgsmarkercatalogue.cpp.
References hardMarker(), QgsDebugMsg, size, and svgMarker().
void QgsMarkerCatalogue::refreshList () [slot]
Definition at line 53 of file qgsmarkercatalogue.cpp.
References markersRefreshed(), mList, QgsDebugMsg, and QgsApplication::svgPaths().
Referenced by QgsMarkerCatalogue().
bool QgsMarkerCatalogue::svgMarker (QPainter * thepPainter, QString name, double size) [static]
Returns a pixmap given a file name of a svg marker NOTE: this method needs to be public static for QgsMarkerDialog::visualizeMarkers.
Definition at line 272 of file qgsmarkercatalogue.cpp.
Referenced by imageMarker(), and pictureMarker().
Member Data Documentation
QStringList QgsMarkerCatalogue::mList [private]
List of availabel markers.
Definition at line 79 of file qgsmarkercatalogue.h.
Referenced by list(), and refreshList().
QgsMarkerCatalogue * QgsMarkerCatalogue::mMarkerCatalogue = 0 [static, private]
Definition at line 76 of file qgsmarkercatalogue.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/core/symbology/qgsmarkercatalogue.h
src/core/symbology/qgsmarkercatalogue.cpp