Quantum GIS API Documentation: QgsFreakOutShader Class Reference
QgsFreakOutShader Class Reference
QGIS core library
A colorful false color shader that will frighten your granny and make your dogs howl.
#include <qgsfreakoutshader.h>
Public Member Functions
QgsFreakOutShader (double theMinimumValue=0.0, double theMaximumValue=255.0)
bool shade (double, int *, int *, int *)
generates and new RGB value based on one input value
bool shade (double, double, double, int *, int *, int *)
generates and new RGB value based on original RGB value
void setMaximumValue (double)
Set the maximum value.
void setMinimumValue (double)
Return the minimum value.
double classBreakMin1 () const
double classBreakMax1 () const
double classBreakMin2 () const
double classBreakMax2 () const
double classBreakMin3 () const
Private Member Functions
void setClassBreaks ()
Private Attributes
double mBreakSize
double mClassBreakMin1
double mClassBreakMax1
double mClassBreakMin2
double mClassBreakMax2
double mClassBreakMin3
Detailed Description
A colorful false color shader that will frighten your granny and make your dogs howl.
Definition at line 29 of file qgsfreakoutshader.h.
Constructor & Destructor Documentation
QgsFreakOutShader::QgsFreakOutShader (double theMinimumValue = 0.0, double theMaximumValue = 255.0)
Definition at line 25 of file qgsfreakoutshader.cpp.
References setClassBreaks().
Member Function Documentation
double QgsFreakOutShader::classBreakMax1 () const [inline]
Definition at line 48 of file qgsfreakoutshader.h.
Referenced by QgsRasterLayer::legendSymbologyItems().
double QgsFreakOutShader::classBreakMax2 () const [inline]
Definition at line 50 of file qgsfreakoutshader.h.
Referenced by QgsRasterLayer::legendSymbologyItems().
double QgsFreakOutShader::classBreakMin1 () const [inline]
Definition at line 47 of file qgsfreakoutshader.h.
Referenced by QgsRasterLayer::legendSymbologyItems().
double QgsFreakOutShader::classBreakMin2 () const [inline]
Definition at line 49 of file qgsfreakoutshader.h.
double QgsFreakOutShader::classBreakMin3 () const [inline]
Definition at line 51 of file qgsfreakoutshader.h.
void QgsFreakOutShader::setClassBreaks () [private]
Definition at line 30 of file qgsfreakoutshader.cpp.
References mBreakSize, mClassBreakMax1, mClassBreakMax2, mClassBreakMin1, mClassBreakMin2, mClassBreakMin3, QgsRasterShaderFunction::mMinimumMaximumRange, and QgsRasterShaderFunction::mMinimumValue.
Referenced by QgsFreakOutShader(), setMaximumValue(), and setMinimumValue().
void QgsFreakOutShader::setMaximumValue (double theValue) [virtual]
Set the maximum value.
Set the maximum value for the raster shader.
Parameters:
theValue The new maximum value
Reimplemented from QgsRasterShaderFunction.
Definition at line 46 of file qgsfreakoutshader.cpp.
References QgsRasterShaderFunction::mMaximumValue, QgsRasterShaderFunction::mMinimumMaximumRange, QgsRasterShaderFunction::mMinimumValue, and setClassBreaks().
void QgsFreakOutShader::setMinimumValue (double theValue) [virtual]
Return the minimum value.
Set the maximum value for the raster shader.
Parameters:
theValue The new minimum value
Reimplemented from QgsRasterShaderFunction.
Definition at line 58 of file qgsfreakoutshader.cpp.
References QgsRasterShaderFunction::mMaximumValue, QgsRasterShaderFunction::mMinimumMaximumRange, QgsRasterShaderFunction::mMinimumValue, and setClassBreaks().
bool QgsFreakOutShader::shade (double theValue, int * theReturnRedValue, int * theReturnGreenValue, int * theReturnBlueValue) [virtual]
generates and new RGB value based on one input value
Reimplemented from QgsRasterShaderFunction.
Definition at line 65 of file qgsfreakoutshader.cpp.
References mClassBreakMax1, mClassBreakMax2, mClassBreakMin1, mClassBreakMin2, mClassBreakMin3, QgsRasterShaderFunction::mMaximumValue, QgsRasterShaderFunction::mMinimumMaximumRange, and QgsRasterShaderFunction::mMinimumValue.
bool QgsFreakOutShader::shade (double theRedValue, double theGreenValue, double theBlueValue, int * theReturnRedValue, int * theReturnGreenValue, int * theReturnBlueValue) [virtual]
generates and new RGB value based on original RGB value
Reimplemented from QgsRasterShaderFunction.
Definition at line 112 of file qgsfreakoutshader.cpp.
Member Data Documentation
double QgsFreakOutShader::mBreakSize [private]
Definition at line 56 of file qgsfreakoutshader.h.
Referenced by setClassBreaks().
double QgsFreakOutShader::mClassBreakMax1 [private]
Definition at line 58 of file qgsfreakoutshader.h.
Referenced by setClassBreaks(), and shade().
double QgsFreakOutShader::mClassBreakMax2 [private]
Definition at line 60 of file qgsfreakoutshader.h.
Referenced by setClassBreaks(), and shade().
double QgsFreakOutShader::mClassBreakMin1 [private]
Definition at line 57 of file qgsfreakoutshader.h.
Referenced by setClassBreaks(), and shade().
double QgsFreakOutShader::mClassBreakMin2 [private]
Definition at line 59 of file qgsfreakoutshader.h.
Referenced by setClassBreaks(), and shade().
double QgsFreakOutShader::mClassBreakMin3 [private]
Definition at line 61 of file qgsfreakoutshader.h.
Referenced by setClassBreaks(), and shade().
The documentation for this class was generated from the following files:
src/core/raster/qgsfreakoutshader.h
src/core/raster/qgsfreakoutshader.cpp