Quantum GIS API Documentation: QgsTextDiagram Class Reference
QgsTextDiagram Class Reference
#include <qgsdiagram.h>
Public Types
enum Shape { Circle = 0, Rectangle, Triangle }
enum Orientation { Horizontal = 0, Vertical }
Public Member Functions
QgsTextDiagram ()
~QgsTextDiagram ()
void renderDiagram (const QgsAttributeMap &att, QgsRenderContext &c, const QgsDiagramSettings &s, const QPointF &position)
Draws the diagram at the given position (in pixel coordinates)
QString diagramName () const
Private Member Functions
void lineEllipseIntersection (const QPointF &lineStart, const QPointF &lineEnd, const QPointF &ellipseMid, double r1, double r2, QList< QPointF > &result) const
Calculates intersection points between a line and an ellipse.
Private Attributes
Orientation mOrientation
Shape mShape
QBrush mBrush
QPen mPen
Detailed Description
Definition at line 43 of file qgsdiagram.h.
Member Enumeration Documentation
enum QgsTextDiagram::Orientation
Enumerator:
Horizontal
Vertical
Definition at line 53 of file qgsdiagram.h.
enum QgsTextDiagram::Shape
Enumerator:
Circle
Rectangle
Triangle
Definition at line 46 of file qgsdiagram.h.
Constructor & Destructor Documentation
QgsTextDiagram::QgsTextDiagram ()
Definition at line 61 of file qgsdiagram.cpp.
References mBrush, and mPen.
QgsTextDiagram::~QgsTextDiagram ()
Definition at line 69 of file qgsdiagram.cpp.
Member Function Documentation
QString QgsTextDiagram::diagramName () const [inline, virtual]
Implements QgsDiagram.
Definition at line 63 of file qgsdiagram.h.
void QgsTextDiagram::lineEllipseIntersection (const QPointF & lineStart, const QPointF & lineEnd, const QPointF & ellipseMid, double r1, double r2, QList< QPointF > & result) const [private]
Calculates intersection points between a line and an ellipse.
Returns:
intersection points
Definition at line 210 of file qgsdiagram.cpp.
Referenced by renderDiagram().
void QgsTextDiagram::renderDiagram (const QgsAttributeMap & att, QgsRenderContext & c, const QgsDiagramSettings & s, const QPointF & position) [virtual]
Draws the diagram at the given position (in pixel coordinates)
Implements QgsDiagram.
Definition at line 73 of file qgsdiagram.cpp.
References QgsDiagramSettings::backgroundColor, QgsDiagramSettings::categoryColors, QgsDiagramSettings::categoryIndices, Circle, Horizontal, lineEllipseIntersection(), QgsDiagramSettings::maxScaleDenominator, mBrush, QgsDiagramSettings::minScaleDenominator, mOrientation, mPen, mShape, QgsRenderContext::painter(), QgsDiagramSettings::penColor, Rectangle, QgsRenderContext::rendererScale(), QgsDiagram::scaledFont(), QgsDiagram::setPenWidth(), QgsDiagramSettings::size, and QgsDiagram::sizePainterUnits().
Member Data Documentation
QBrush QgsTextDiagram::mBrush [private]
Definition at line 68 of file qgsdiagram.h.
Referenced by QgsTextDiagram(), and renderDiagram().
Orientation QgsTextDiagram::mOrientation [private]
Definition at line 66 of file qgsdiagram.h.
Referenced by renderDiagram().
QPen QgsTextDiagram::mPen [private]
Definition at line 69 of file qgsdiagram.h.
Referenced by QgsTextDiagram(), and renderDiagram().
Shape QgsTextDiagram::mShape [private]
Definition at line 67 of file qgsdiagram.h.
Referenced by renderDiagram().
The documentation for this class was generated from the following files:
src/core/qgsdiagram.h
src/core/qgsdiagram.cpp