Quantum GIS API Documentation: QgsDiagram Class Reference
QgsDiagram Class Reference
Base class for all diagram types.
#include <qgsdiagram.h>
Public Member Functions
virtual ~QgsDiagram ()
virtual void renderDiagram (const QgsAttributeMap &att, QgsRenderContext &c, const QgsDiagramSettings &s, const QPointF &position)=0
Draws the diagram at the given position (in pixel coordinates)
virtual QString diagramName () const =0
Protected Member Functions
void setPenWidth (QPen &pen, const QgsDiagramSettings &s, const QgsRenderContext &c)
QSizeF sizePainterUnits (const QSizeF &size, const QgsDiagramSettings &s, const QgsRenderContext &c)
QFont scaledFont (const QgsDiagramSettings &s, const QgsRenderContext &c)
Detailed Description
Base class for all diagram types.
Definition at line 29 of file qgsdiagram.h.
Constructor & Destructor Documentation
virtual QgsDiagram::~QgsDiagram () [inline, virtual]
Definition at line 32 of file qgsdiagram.h.
Member Function Documentation
virtual QString QgsDiagram::diagramName () const [pure virtual]
Implemented in QgsPieDiagram, and QgsTextDiagram.
Referenced by QgsDiagramRendererV2::_writeXML().
virtual void QgsDiagram::renderDiagram (const QgsAttributeMap & att, QgsRenderContext & c, const QgsDiagramSettings & s, const QPointF & position) [pure virtual]
Draws the diagram at the given position (in pixel coordinates)
Implemented in QgsPieDiagram, and QgsTextDiagram.
Referenced by QgsDiagramRendererV2::renderDiagram().
QFont QgsDiagram::scaledFont (const QgsDiagramSettings & s, const QgsRenderContext & c) [protected]
Definition at line 46 of file qgsdiagram.cpp.
References QgsDiagramSettings::font, QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), QgsDiagramSettings::MM, QgsRenderContext::scaleFactor(), and QgsDiagramSettings::sizeType.
Referenced by QgsTextDiagram::renderDiagram().
void QgsDiagram::setPenWidth (QPen & pen, const QgsDiagramSettings & s, const QgsRenderContext & c) [protected]
Definition at line 21 of file qgsdiagram.cpp.
References QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), QgsDiagramSettings::MM, QgsDiagramSettings::penWidth, QgsRenderContext::scaleFactor(), and QgsDiagramSettings::sizeType.
Referenced by QgsTextDiagram::renderDiagram(), and QgsPieDiagram::renderDiagram().
QSizeF QgsDiagram::sizePainterUnits (const QSizeF & size, const QgsDiagramSettings & s, const QgsRenderContext & c) [protected]
Definition at line 33 of file qgsdiagram.cpp.
References QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), QgsDiagramSettings::MM, QgsRenderContext::scaleFactor(), QgsDiagramSettings::size, and QgsDiagramSettings::sizeType.
Referenced by QgsTextDiagram::renderDiagram(), and QgsPieDiagram::renderDiagram().
The documentation for this class was generated from the following files:
src/core/qgsdiagram.h
src/core/qgsdiagram.cpp