Quantum GIS API Documentation: QgsExpression::Visitor Class Reference
QgsExpression::Visitor Class Reference
support for visitor pattern - algorithms dealing with the expressions may be implemented without modifying the Node classes
#include <qgsexpression.h>
Public Member Functions
virtual ~Visitor ()
virtual void visit (NodeUnaryOperator *n)=0
virtual void visit (NodeBinaryOperator *n)=0
virtual void visit (NodeInOperator *n)=0
virtual void visit (NodeFunction *n)=0
virtual void visit (NodeLiteral *n)=0
virtual void visit (NodeColumnRef *n)=0
virtual void visit (NodeCondition *n)=0
Detailed Description
support for visitor pattern - algorithms dealing with the expressions may be implemented without modifying the Node classes
Definition at line 450 of file qgsexpression.h.
Constructor & Destructor Documentation
virtual QgsExpression::Visitor::~Visitor () [inline, virtual]
Definition at line 453 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::Visitor::visit (NodeUnaryOperator * n) [pure virtual]
Referenced by QgsExpression::NodeUnaryOperator::accept(), QgsExpression::NodeBinaryOperator::accept(), QgsExpression::NodeInOperator::accept(), QgsExpression::NodeFunction::accept(), QgsExpression::NodeLiteral::accept(), QgsExpression::NodeColumnRef::accept(), and QgsExpression::NodeCondition::accept().
virtual void QgsExpression::Visitor::visit (NodeBinaryOperator * n) [pure virtual]
virtual void QgsExpression::Visitor::visit (NodeInOperator * n) [pure virtual]
virtual void QgsExpression::Visitor::visit (NodeFunction * n) [pure virtual]
virtual void QgsExpression::Visitor::visit (NodeLiteral * n) [pure virtual]
virtual void QgsExpression::Visitor::visit (NodeColumnRef * n) [pure virtual]
virtual void QgsExpression::Visitor::visit (NodeCondition * n) [pure virtual]
The documentation for this class was generated from the following file:
src/core/qgsexpression.h