Quantum GIS API Documentation: QgsExpression::NodeFunction Class Reference
QgsExpression::NodeFunction Class Reference
#include <qgsexpression.h>
Public Member Functions
NodeFunction (int fnIndex, NodeList *args)
virtual ~NodeFunction ()
int fnIndex ()
NodeList * args ()
virtual bool prepare (QgsExpression *parent, const QgsFieldMap &fields)
virtual QVariant eval (QgsExpression *parent, QgsFeature *f)
virtual QString dump () const
virtual void toOgcFilter (QDomDocument &doc, QDomElement &element) const
virtual QStringList referencedColumns () const
virtual bool needsGeometry () const
virtual void accept (Visitor &v)
Static Public Member Functions
static QgsExpression::Node * createFromOgcFilter (QDomElement &element, QString &errorMessage)
Protected Attributes
int mFnIndex
NodeList * mArgs
Detailed Description
Definition at line 341 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::NodeFunction::NodeFunction (int fnIndex, NodeList * args) [inline]
Definition at line 344 of file qgsexpression.h.
virtual QgsExpression::NodeFunction::~NodeFunction () [inline, virtual]
Definition at line 346 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::NodeFunction::accept (Visitor & v) [inline, virtual]
Implements QgsExpression::Node.
Definition at line 360 of file qgsexpression.h.
References QgsExpression::Visitor::visit().
NodeList* QgsExpression::NodeFunction::args () [inline]
Definition at line 349 of file qgsexpression.h.
QgsExpression::Node * QgsExpression::NodeFunction::createFromOgcFilter (QDomElement & element, QString & errorMessage) [static]
Reimplemented from QgsExpression::Node.
Definition at line 1384 of file qgsexpression.cpp.
References QgsExpression::NodeList::append(), QgsExpression::BuiltinFunctions(), QgsExpression::createFromOgcFilter(), and QgsExpression::FunctionDef::mName.
QString QgsExpression::NodeFunction::dump () const [virtual]
Implements QgsExpression::Node.
Definition at line 1363 of file qgsexpression.cpp.
References QgsExpression::BuiltinFunctions(), QgsExpression::FunctionDef::mName, and QgsExpression::FunctionDef::mParams.
QVariant QgsExpression::NodeFunction::eval (QgsExpression * parent, QgsFeature * f) [virtual]
Implements QgsExpression::Node.
Definition at line 1324 of file qgsexpression.cpp.
References QgsExpression::BuiltinFunctions(), ENSURE_NO_EVAL_ERROR, QgsExpression::Node::eval(), isNull(), and QgsExpression::FunctionDef::mFcn.
int QgsExpression::NodeFunction::fnIndex () [inline]
Definition at line 348 of file qgsexpression.h.
virtual bool QgsExpression::NodeFunction::needsGeometry () const [inline, virtual]
Implements QgsExpression::Node.
Definition at line 359 of file qgsexpression.h.
References QgsExpression::Node::needsGeometry().
bool QgsExpression::NodeFunction::prepare (QgsExpression * parent, const QgsFieldMap & fields) [virtual]
Implements QgsExpression::Node.
Definition at line 1350 of file qgsexpression.cpp.
References QgsExpression::Node::prepare().
virtual QStringList QgsExpression::NodeFunction::referencedColumns () const [inline, virtual]
Implements QgsExpression::Node.
Definition at line 358 of file qgsexpression.h.
References QgsExpression::Node::referencedColumns().
void QgsExpression::NodeFunction::toOgcFilter (QDomDocument & doc, QDomElement & element) const [virtual]
Reimplemented from QgsExpression::Node.
Definition at line 1372 of file qgsexpression.cpp.
References QgsExpression::BuiltinFunctions(), QgsExpression::FunctionDef::mName, and QgsExpression::FunctionDef::mParams.
Member Data Documentation
NodeList* QgsExpression::NodeFunction::mArgs [protected]
Definition at line 365 of file qgsexpression.h.
int QgsExpression::NodeFunction::mFnIndex [protected]
Definition at line 364 of file qgsexpression.h.
The documentation for this class was generated from the following files:
src/core/qgsexpression.h
src/core/qgsexpression.cpp