Quantum GIS API Documentation: QgsGraphArc Class Reference
QgsGraphArc Class Reference
QGIS network analysis library.
This class implement a graph edge.
#include <qgsgraph.h>
Public Member Functions
QgsGraphArc ()
QVariant property (int propertyIndex) const
return property value
QVector< QVariant > properties () const
get array of proertyes
int outVertex () const
return index of outgoing vertex
int inVertex () const
return index of incoming vertex
Private Attributes
QVector< QVariant > mProperties
int mOut
int mIn
Friends
class QgsGraph
Detailed Description
This class implement a graph edge.
Definition at line 44 of file qgsgraph.h.
Constructor & Destructor Documentation
QgsGraphArc::QgsGraphArc ()
Definition at line 85 of file qgsgraph.cpp.
Member Function Documentation
int QgsGraphArc::inVertex () const
return index of incoming vertex
Definition at line 100 of file qgsgraph.cpp.
References mIn.
Referenced by QgsGraphAnalyzer::dijkstra(), and QgsGraphAnalyzer::shortestTree().
int QgsGraphArc::outVertex () const
return index of outgoing vertex
Definition at line 105 of file qgsgraph.cpp.
References mOut.
Referenced by QgsGraphAnalyzer::shortestTree().
QVector< QVariant > QgsGraphArc::properties () const
get array of proertyes
Definition at line 95 of file qgsgraph.cpp.
References mProperties.
Referenced by QgsGraphAnalyzer::shortestTree().
QVariant QgsGraphArc::property (int propertyIndex) const
return property value
Parameters:
propertyIndex property index
Definition at line 90 of file qgsgraph.cpp.
References mProperties.
Referenced by QgsGraphAnalyzer::dijkstra().
Friends And Related Function Documentation
friend class QgsGraph [friend]
Definition at line 77 of file qgsgraph.h.
Member Data Documentation
int QgsGraphArc::mIn [private]
Definition at line 75 of file qgsgraph.h.
Referenced by QgsGraph::addArc(), and inVertex().
int QgsGraphArc::mOut [private]
Definition at line 74 of file qgsgraph.h.
Referenced by QgsGraph::addArc(), and outVertex().
QVector< QVariant > QgsGraphArc::mProperties [private]
Definition at line 72 of file qgsgraph.h.
Referenced by QgsGraph::addArc(), properties(), and property().
The documentation for this class was generated from the following files:
src/analysis/network/qgsgraph.h
src/analysis/network/qgsgraph.cpp