Quantum GIS API Documentation: QgsSymbologyV2Conversion Class Reference
QgsSymbologyV2Conversion Class Reference
#include <qgssymbologyv2conversion.h>
Static Public Member Functions
static QgsSymbolV2 * symbolV1toV2 (const QgsSymbol *s)
return a symbol in new symbology as close as possible to old symbol
static QgsSymbol * symbolV2toV1 (QgsSymbolV2 *s)
return a symbol in old symbology as close as possible to new symbol
static void rendererV1toV2 (QgsVectorLayer *layer)
convert layer from old symbology to new symbology
static void rendererV2toV1 (QgsVectorLayer *layer)
convert layer from new symbology to old symbology
Detailed Description
Definition at line 22 of file qgssymbologyv2conversion.h.
Member Function Documentation
void QgsSymbologyV2Conversion::rendererV1toV2 (QgsVectorLayer * layer) [static]
convert layer from old symbology to new symbology
Note:
not all properties will be preserved
Definition at line 160 of file qgssymbologyv2conversion.cpp.
References QgsGraduatedSymbolRenderer::classificationField(), QgsUniqueValueRenderer::classificationField(), QgsGraduatedSymbolRendererV2::Custom, QgsFeatureRendererV2::defaultRenderer(), QgsGraduatedSymbolRenderer::Empty, QgsGraduatedSymbolRenderer::EqualInterval, QgsGraduatedSymbolRendererV2::EqualInterval, QgsVectorLayer::geometryType(), QgsVectorLayer::isUsingRendererV2(), QgsSymbol::label(), QgsSymbol::lowerValue(), QgsGraduatedSymbolRenderer::mode(), QgsRenderer::name(), QgsVectorLayer::pendingFields(), QgsGraduatedSymbolRenderer::Quantile, QgsGraduatedSymbolRendererV2::Quantile, QgsVectorLayer::renderer(), QgsGraduatedSymbolRendererV2::setMode(), QgsVectorLayer::setRenderer(), QgsVectorLayer::setRendererV2(), QgsVectorLayer::setUsingRendererV2(), QgsSingleSymbolRenderer::symbol(), QgsUniqueValueRenderer::symbols(), QgsGraduatedSymbolRenderer::symbols(), symbolV1toV2(), and QgsSymbol::upperValue().
void QgsSymbologyV2Conversion::rendererV2toV1 (QgsVectorLayer * layer) [static]
convert layer from new symbology to old symbology
Note:
not all properties will be preserved
Definition at line 262 of file qgssymbologyv2conversion.cpp.
References QgsSingleSymbolRenderer::addSymbol(), QgsGraduatedSymbolRenderer::addSymbol(), QgsCategorizedSymbolRendererV2::categories(), QgsGraduatedSymbolRendererV2::classAttribute(), QgsCategorizedSymbolRendererV2::classAttribute(), QgsGraduatedSymbolRenderer::Empty, QgsGraduatedSymbolRenderer::EqualInterval, QgsGraduatedSymbolRendererV2::EqualInterval, QgsVectorLayer::fieldNameIndex(), QgsVectorLayer::geometryType(), QgsUniqueValueRenderer::insertValue(), QgsVectorLayer::isUsingRendererV2(), QgsRendererRangeV2::label(), QgsRendererRangeV2::lowerValue(), QgsGraduatedSymbolRendererV2::mode(), QgsGraduatedSymbolRenderer::Quantile, QgsGraduatedSymbolRendererV2::Quantile, QgsGraduatedSymbolRendererV2::ranges(), QgsVectorLayer::rendererV2(), QgsUniqueValueRenderer::setClassificationField(), QgsGraduatedSymbolRenderer::setClassificationField(), QgsSymbol::setLabel(), QgsSymbol::setLowerValue(), QgsVectorLayer::setRenderer(), QgsVectorLayer::setRendererV2(), QgsSymbol::setUpperValue(), QgsVectorLayer::setUsingRendererV2(), QgsRendererRangeV2::symbol(), QgsSingleSymbolRendererV2::symbol(), QgsRendererCategoryV2::symbol(), symbolV2toV1(), QgsFeatureRendererV2::type(), QgsRendererRangeV2::upperValue(), and QgsRendererCategoryV2::value().
QgsSymbolV2 * QgsSymbologyV2Conversion::symbolV1toV2 (const QgsSymbol * s) [static]
return a symbol in new symbology as close as possible to old symbol
Note:
not all properties will be preserved
Definition at line 33 of file qgssymbologyv2conversion.cpp.
References MathUtils::angle(), QgsSymbol::brush(), QgsSymbol::color(), QgsSymbol::fillColor(), QGis::Line, QgsSymbol::lineWidth(), QgsSymbol::pen(), QGis::Point, QgsSymbol::pointSize(), QgsSymbol::pointSymbolName(), QGis::Polygon, size, and QgsSymbol::type().
Referenced by rendererV1toV2().
QgsSymbol * QgsSymbologyV2Conversion::symbolV2toV1 (QgsSymbolV2 * s) [static]
return a symbol in old symbology as close as possible to new symbol
Note:
not all properties will be preserved
Definition at line 93 of file qgssymbologyv2conversion.cpp.
References QgsSimpleFillSymbolLayerV2::borderColor(), QgsSimpleMarkerSymbolLayerV2::borderColor(), QgsSimpleFillSymbolLayerV2::borderStyle(), QgsSimpleFillSymbolLayerV2::borderWidth(), QgsSimpleFillSymbolLayerV2::brushStyle(), QgsSymbolLayerV2::color(), QgsSymbolV2::Fill, QgsSymbolLayerV2::layerType(), QgsSymbolV2::Line, QGis::Line, QgsSymbolV2::Marker, QgsSimpleMarkerSymbolLayerV2::name(), QgsSvgMarkerSymbolLayerV2::path(), QgsSimpleLineSymbolLayerV2::penStyle(), QGis::Point, QGis::Polygon, QgsSymbol::setColor(), QgsSymbol::setFillColor(), QgsSymbol::setFillStyle(), QgsSymbol::setLineStyle(), QgsSymbol::setLineWidth(), QgsSymbol::setNamedPointSymbol(), QgsSymbol::setPointSize(), QgsMarkerSymbolLayerV2::size(), QgsSymbolV2::symbolLayer(), QgsSymbolV2::symbolLayerCount(), QgsSymbolLayerV2::type(), and QgsLineSymbolLayerV2::width().
Referenced by rendererV2toV1().
The documentation for this class was generated from the following files:
src/core/symbology-ng/qgssymbologyv2conversion.h
src/core/symbology-ng/qgssymbologyv2conversion.cpp