Quantum GIS API Documentation: QgsLabelAttributes Class Reference
QgsLabelAttributes Class Reference
QGIS core library
A class to store attributes needed for label rendering.
#include <qgslabelattributes.h>
Public Types
enum Units { MapUnits = 0, PointUnits }
Public Member Functions
QgsLabelAttributes (bool def=true)
Constructor.
~QgsLabelAttributes ()
void setText (const QString &text)
bool textIsSet (void) const
const QString text (void) const
void setFamily (const QString &family)
bool familyIsSet (void) const
const QString family (void) const
void setBold (bool enable)
bool boldIsSet (void) const
bool bold (void) const
void setItalic (bool enable)
bool italicIsSet (void) const
bool italic (void) const
void setUnderline (bool enable)
bool underlineIsSet (void) const
bool underline (void) const
void setStrikeOut (bool enable)
bool strikeOutIsSet (void) const
bool strikeOut (void) const
void setSize (double size, int type)
bool sizeIsSet (void) const
int sizeType (void) const
double size (void) const
void setColor (const QColor &color)
bool colorIsSet (void) const
const QColor & color (void) const
void setOffset (double x, double y, int type)
bool offsetIsSet (void) const
int offsetType (void) const
double xOffset (void) const
double yOffset (void) const
void setAngle (double angle)
bool angleIsSet (void) const
double angle (void) const
bool angleIsAuto (void) const
void setAutoAngle (bool state)
void setAlignment (int alignment)
bool alignmentIsSet (void) const
int alignment (void) const
bool bufferEnabled () const
void setBufferEnabled (bool useBufferFlag)
void setBufferSize (double size, int type)
bool bufferSizeIsSet (void) const
int bufferSizeType (void) const
double bufferSize (void) const
void setBufferColor (const QColor &color)
bool bufferColorIsSet (void) const
QColor bufferColor (void) const
void setBufferStyle (Qt::BrushStyle style)
bool bufferStyleIsSet (void) const
Qt::BrushStyle bufferStyle (void) const
void setBorderColor (const QColor &color)
bool borderColorIsSet (void) const
QColor borderColor (void) const
void setBorderWidth (int width)
bool borderWidthIsSet (void) const
int borderWidth (void) const
void setBorderStyle (Qt::PenStyle style)
bool borderStyleIsSet (void) const
Qt::PenStyle borderStyle (void) const
bool multilineEnabled () const
void setMultilineEnabled (bool useMultiline)
bool selectedOnly () const
void setSelectedOnly (bool selectedonly)
Static Public Member Functions
static QString unitsName (int units)
static int unitsCode (const QString &name)
static QString alignmentName (int alignment)
static int alignmentCode (const QString &name)
Protected Attributes
QString mText
bool mTextIsSet
QFont mFont
Font (family, weight, italic, underline, strikeout)
bool mFamilyIsSet
bool mBoldIsSet
bool mItalicIsSet
bool mUnderlineIsSet
bool mStrikeOutIsSet
int mSizeType
Font size, size type.
double mSize
bool mSizeIsSet
QColor mColor
Color.
bool mColorIsSet
int mOffsetType
Offset.
double mXOffset
double mYOffset
bool mOffsetIsSet
double mAngle
Angle (degrees)
bool mAngleIsSet
bool mAngleIsAuto
int mAlignment
Alignment.
bool mAlignmentIsSet
bool mBufferEnabledFlag
Buffer enablement.
int mBufferSizeType
Buffer size, size type.
double mBufferSize
bool mBufferSizeIsSet
QBrush mBufferBrush
Buffer brush (color, style)
bool mBufferColorIsSet
bool mBufferStyleIsSet
QPen mBorderPen
Border pen (color, width, style)
bool mBorderColorIsSet
bool mBorderWidthIsSet
bool mBorderStyleIsSet
bool mMultilineEnabledFlag
Multiline enablement.
bool mSelectedOnly
Label only selected.
Detailed Description
A class to store attributes needed for label rendering.
Label attributes: border (color, width, style) / / text bounding box / / +-----------/--+ buffer (color, pattern) | / | / | +----+ |/ --+ | |Text| / |--- text size | +----+ /| --+ | | +--------------+ | | | | >|----|<--- buffer width | >|<--- border width
Text:
font family
size type (map units, points)
size (in points - device independent)
bold
italic
underline
color
Position:
(coordinates)
offset type (map units, points)
x offset, y offset (measured in text coordinate system, not in map coordinate system)
angle
alignment (from a point calculated by angle and offset)
Buffer:
buffer size type (map units, points)
buffer size
buffer color
buffer brush
Border:
border width
border color
border style
Each attribute is either set or unset.
Definition at line 76 of file qgslabelattributes.h.
Member Enumeration Documentation
enum QgsLabelAttributes::Units
Enumerator:
MapUnits
PointUnits
Definition at line 87 of file qgslabelattributes.h.
Constructor & Destructor Documentation
QgsLabelAttributes::QgsLabelAttributes (bool def = true)
Constructor.
Parameters:
def if true, defaults are set, if false all all attributes are unset
Definition at line 27 of file qgslabelattributes.cpp.
References mBoldIsSet, mFamilyIsSet, mFont, mItalicIsSet, mUnderlineIsSet, PointUnits, setAlignment(), setAngle(), setAutoAngle(), setBorderColor(), setBorderStyle(), setBorderWidth(), setBufferColor(), setBufferSize(), setBufferStyle(), setColor(), setOffset(), setSize(), and setText().
QgsLabelAttributes::~QgsLabelAttributes ()
Definition at line 89 of file qgslabelattributes.cpp.
Member Function Documentation
int QgsLabelAttributes::alignment (void) const
Definition at line 178 of file qgslabelattributes.cpp.
References mAlignment.
Referenced by QgsLabel::renderLabel(), setAlignment(), and QgsLabel::writeXML().
int QgsLabelAttributes::alignmentCode (const QString & name) [static]
Definition at line 480 of file qgslabelattributes.cpp.
Referenced by QgsLabel::readXML().
bool QgsLabelAttributes::alignmentIsSet (void) const
Definition at line 173 of file qgslabelattributes.cpp.
References mAlignmentIsSet.
Referenced by QgsLabel::writeXML().
QString QgsLabelAttributes::alignmentName (int alignment) [static]
Definition at line 464 of file qgslabelattributes.cpp.
References QgsDebugMsg.
Referenced by QgsLabel::writeXML().
double QgsLabelAttributes::angle (void) const
Definition at line 151 of file qgslabelattributes.cpp.
References mAngle.
Referenced by QgsLabel::renderLabel(), setAngle(), and QgsLabel::writeXML().
bool QgsLabelAttributes::angleIsAuto (void) const
Definition at line 156 of file qgslabelattributes.cpp.
References mAngleIsAuto.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::angleIsSet (void) const
Definition at line 146 of file qgslabelattributes.cpp.
References mAngleIsSet.
Referenced by QgsLabel::writeXML().
bool QgsLabelAttributes::bold (void) const
Definition at line 212 of file qgslabelattributes.cpp.
References mFont.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::boldIsSet (void) const
Definition at line 207 of file qgslabelattributes.cpp.
References mBoldIsSet.
Referenced by QgsLabel::writeXML().
QColor QgsLabelAttributes::borderColor (void) const
Definition at line 384 of file qgslabelattributes.cpp.
References mBorderPen.
bool QgsLabelAttributes::borderColorIsSet (void) const
Definition at line 379 of file qgslabelattributes.cpp.
References mBorderColorIsSet.
Qt::PenStyle QgsLabelAttributes::borderStyle (void) const
Definition at line 417 of file qgslabelattributes.cpp.
References mBorderPen.
bool QgsLabelAttributes::borderStyleIsSet (void) const
Definition at line 412 of file qgslabelattributes.cpp.
References mBorderStyleIsSet.
int QgsLabelAttributes::borderWidth (void) const
Definition at line 400 of file qgslabelattributes.cpp.
References mBorderPen.
bool QgsLabelAttributes::borderWidthIsSet (void) const
Definition at line 395 of file qgslabelattributes.cpp.
References mBorderWidthIsSet.
QColor QgsLabelAttributes::bufferColor (void) const
Definition at line 350 of file qgslabelattributes.cpp.
References mBufferBrush.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::bufferColorIsSet (void) const
Definition at line 345 of file qgslabelattributes.cpp.
References mColorIsSet.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::bufferEnabled () const
Definition at line 308 of file qgslabelattributes.cpp.
References mBufferEnabledFlag.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
double QgsLabelAttributes::bufferSize (void) const
Definition at line 333 of file qgslabelattributes.cpp.
References mBufferSize.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::bufferSizeIsSet (void) const
Definition at line 323 of file qgslabelattributes.cpp.
References mBufferSizeIsSet.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
int QgsLabelAttributes::bufferSizeType (void) const
Definition at line 328 of file qgslabelattributes.cpp.
References mBufferSizeType.
Referenced by QgsLabel::writeXML().
Qt::BrushStyle QgsLabelAttributes::bufferStyle (void) const
Definition at line 367 of file qgslabelattributes.cpp.
References mBufferBrush.
bool QgsLabelAttributes::bufferStyleIsSet (void) const
Definition at line 362 of file qgslabelattributes.cpp.
References mBufferStyleIsSet.
const QColor & QgsLabelAttributes::color (void) const
Definition at line 302 of file qgslabelattributes.cpp.
References mColor.
Referenced by QgsLabel::renderLabel(), setColor(), and QgsLabel::writeXML().
bool QgsLabelAttributes::colorIsSet (void) const
Definition at line 297 of file qgslabelattributes.cpp.
References mColorIsSet.
Referenced by QgsLabel::writeXML().
const QString QgsLabelAttributes::family (void) const
Definition at line 195 of file qgslabelattributes.cpp.
References mFont.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::familyIsSet (void) const
Definition at line 190 of file qgslabelattributes.cpp.
References mFamilyIsSet.
Referenced by QgsLabel::writeXML().
bool QgsLabelAttributes::italic (void) const
Definition at line 229 of file qgslabelattributes.cpp.
References mFont.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::italicIsSet (void) const
Definition at line 224 of file qgslabelattributes.cpp.
References mItalicIsSet.
Referenced by QgsLabel::writeXML().
bool QgsLabelAttributes::multilineEnabled () const
Definition at line 423 of file qgslabelattributes.cpp.
References mMultilineEnabledFlag.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::offsetIsSet (void) const
Definition at line 119 of file qgslabelattributes.cpp.
References mOffsetIsSet.
Referenced by QgsLabel::writeXML().
int QgsLabelAttributes::offsetType (void) const
Definition at line 124 of file qgslabelattributes.cpp.
References mOffsetType.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::selectedOnly () const
Definition at line 433 of file qgslabelattributes.cpp.
References mSelectedOnly.
Referenced by QgsLabel::renderLabel(), setSelectedOnly(), and QgsLabel::writeXML().
void QgsLabelAttributes::setAlignment (int alignment)
Definition at line 167 of file qgslabelattributes.cpp.
References alignment(), mAlignment, and mAlignmentIsSet.
Referenced by QgsLabelAttributes(), and QgsLabel::readXML().
void QgsLabelAttributes::setAngle (double angle)
Definition at line 140 of file qgslabelattributes.cpp.
References angle(), mAngle, and mAngleIsSet.
Referenced by QgsLabelAttributes(), and QgsLabel::readXML().
void QgsLabelAttributes::setAutoAngle (bool state)
Definition at line 161 of file qgslabelattributes.cpp.
References mAngleIsAuto.
Referenced by QgsLabelAttributes(), and QgsLabel::readXML().
void QgsLabelAttributes::setBold (bool enable)
Definition at line 201 of file qgslabelattributes.cpp.
References mBoldIsSet, and mFont.
Referenced by QgsLabel::readXML().
void QgsLabelAttributes::setBorderColor (const QColor & color)
Definition at line 373 of file qgslabelattributes.cpp.
References mBorderColorIsSet, and mBorderPen.
Referenced by QgsLabelAttributes().
void QgsLabelAttributes::setBorderStyle (Qt::PenStyle style)
Definition at line 406 of file qgslabelattributes.cpp.
References mBorderPen, and mBorderStyleIsSet.
Referenced by QgsLabelAttributes().
void QgsLabelAttributes::setBorderWidth (int width)
Definition at line 389 of file qgslabelattributes.cpp.
References mBorderPen, and mBorderWidthIsSet.
Referenced by QgsLabelAttributes().
void QgsLabelAttributes::setBufferColor (const QColor & color)
Definition at line 339 of file qgslabelattributes.cpp.
References mBufferBrush, and mBufferColorIsSet.
Referenced by QgsLabelAttributes(), and QgsLabel::readXML().
void QgsLabelAttributes::setBufferEnabled (bool useBufferFlag)
Definition at line 312 of file qgslabelattributes.cpp.
References mBufferEnabledFlag.
Referenced by QgsLabel::readXML().
void QgsLabelAttributes::setBufferSize (double size, int type)
Definition at line 316 of file qgslabelattributes.cpp.
References mBufferSize, mBufferSizeIsSet, mBufferSizeType, and size().
Referenced by QgsLabelAttributes(), and QgsLabel::readXML().
void QgsLabelAttributes::setBufferStyle (Qt::BrushStyle style)
Definition at line 356 of file qgslabelattributes.cpp.
References mBufferBrush, and mBufferStyleIsSet.
Referenced by QgsLabelAttributes().
void QgsLabelAttributes::setColor (const QColor & color)
Definition at line 291 of file qgslabelattributes.cpp.
References color(), mColor, and mColorIsSet.
Referenced by QgsLabelAttributes(), and QgsLabel::readXML().
void QgsLabelAttributes::setFamily (const QString & family)
Definition at line 184 of file qgslabelattributes.cpp.
References mFamilyIsSet, and mFont.
Referenced by QgsLabel::readXML().
void QgsLabelAttributes::setItalic (bool enable)
Definition at line 218 of file qgslabelattributes.cpp.
References mFont, and mItalicIsSet.
Referenced by QgsLabel::readXML().
void QgsLabelAttributes::setMultilineEnabled (bool useMultiline)
Definition at line 427 of file qgslabelattributes.cpp.
References mMultilineEnabledFlag.
Referenced by QgsLabel::readXML().
void QgsLabelAttributes::setOffset (double x, double y, int type)
Definition at line 111 of file qgslabelattributes.cpp.
References mOffsetIsSet, mOffsetType, mXOffset, and mYOffset.
Referenced by QgsLabelAttributes(), and QgsLabel::readXML().
void QgsLabelAttributes::setSelectedOnly (bool selectedonly)
Definition at line 437 of file qgslabelattributes.cpp.
References mSelectedOnly, and selectedOnly().
Referenced by QgsLabel::readXML().
void QgsLabelAttributes::setSize (double size, int type)
Definition at line 268 of file qgslabelattributes.cpp.
References mSize, mSizeIsSet, mSizeType, and size().
Referenced by QgsLabelAttributes(), QgsLabel::readXML(), and QgsQuickPrint::scaleTextLabels().
void QgsLabelAttributes::setStrikeOut (bool enable)
Definition at line 251 of file qgslabelattributes.cpp.
References mFont, and mStrikeOutIsSet.
Referenced by QgsLabel::readXML().
void QgsLabelAttributes::setText (const QString & text)
Definition at line 93 of file qgslabelattributes.cpp.
References mText, mTextIsSet, and text().
Referenced by QgsLabelAttributes(), and QgsLabel::readXML().
void QgsLabelAttributes::setUnderline (bool enable)
Definition at line 235 of file qgslabelattributes.cpp.
References mFont, and mUnderlineIsSet.
Referenced by QgsLabel::readXML().
double QgsLabelAttributes::size (void) const
Definition at line 285 of file qgslabelattributes.cpp.
References mSize.
Referenced by QgsLabel::renderLabel(), QgsQuickPrint::scaleTextLabels(), setBufferSize(), setSize(), and QgsLabel::writeXML().
bool QgsLabelAttributes::sizeIsSet (void) const
Definition at line 275 of file qgslabelattributes.cpp.
References mSizeIsSet.
Referenced by QgsLabel::writeXML().
int QgsLabelAttributes::sizeType (void) const
Definition at line 280 of file qgslabelattributes.cpp.
References mSizeType.
Referenced by QgsLabel::renderLabel(), QgsQuickPrint::scaleTextLabels(), and QgsLabel::writeXML().
bool QgsLabelAttributes::strikeOut (void) const
Definition at line 262 of file qgslabelattributes.cpp.
References mFont.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::strikeOutIsSet (void) const
Definition at line 257 of file qgslabelattributes.cpp.
References mStrikeOutIsSet.
Referenced by QgsLabel::writeXML().
const QString QgsLabelAttributes::text (void) const
Definition at line 104 of file qgslabelattributes.cpp.
References mText.
Referenced by QgsLabel::renderLabel(), setText(), and QgsLabel::writeXML().
bool QgsLabelAttributes::textIsSet (void) const
Definition at line 99 of file qgslabelattributes.cpp.
References mTextIsSet.
Referenced by QgsLabel::writeXML().
bool QgsLabelAttributes::underline (void) const
Definition at line 246 of file qgslabelattributes.cpp.
References mFont.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
bool QgsLabelAttributes::underlineIsSet (void) const
Definition at line 241 of file qgslabelattributes.cpp.
References mUnderlineIsSet.
Referenced by QgsLabel::writeXML().
int QgsLabelAttributes::unitsCode (const QString & name) [static]
Definition at line 453 of file qgslabelattributes.cpp.
References MapUnits, and PointUnits.
Referenced by QgsLabel::readXML().
QString QgsLabelAttributes::unitsName (int units) [static]
Definition at line 443 of file qgslabelattributes.cpp.
References MapUnits.
Referenced by QgsLabel::writeXML().
double QgsLabelAttributes::xOffset (void) const
Definition at line 129 of file qgslabelattributes.cpp.
References mXOffset.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
double QgsLabelAttributes::yOffset (void) const
Definition at line 134 of file qgslabelattributes.cpp.
References mYOffset.
Referenced by QgsLabel::renderLabel(), and QgsLabel::writeXML().
Member Data Documentation
int QgsLabelAttributes::mAlignment [protected]
Alignment.
Definition at line 227 of file qgslabelattributes.h.
Referenced by alignment(), and setAlignment().
bool QgsLabelAttributes::mAlignmentIsSet [protected]
Definition at line 228 of file qgslabelattributes.h.
Referenced by alignmentIsSet(), and setAlignment().
double QgsLabelAttributes::mAngle [protected]
Angle (degrees)
Definition at line 222 of file qgslabelattributes.h.
Referenced by angle(), and setAngle().
bool QgsLabelAttributes::mAngleIsAuto [protected]
Definition at line 224 of file qgslabelattributes.h.
Referenced by angleIsAuto(), and setAutoAngle().
bool QgsLabelAttributes::mAngleIsSet [protected]
Definition at line 223 of file qgslabelattributes.h.
Referenced by angleIsSet(), and setAngle().
bool QgsLabelAttributes::mBoldIsSet [protected]
Definition at line 201 of file qgslabelattributes.h.
Referenced by boldIsSet(), QgsLabelAttributes(), and setBold().
bool QgsLabelAttributes::mBorderColorIsSet [protected]
Definition at line 244 of file qgslabelattributes.h.
Referenced by borderColorIsSet(), and setBorderColor().
QPen QgsLabelAttributes::mBorderPen [protected]
Border pen (color, width, style)
Definition at line 243 of file qgslabelattributes.h.
Referenced by borderColor(), borderStyle(), borderWidth(), setBorderColor(), setBorderStyle(), and setBorderWidth().
bool QgsLabelAttributes::mBorderStyleIsSet [protected]
Definition at line 246 of file qgslabelattributes.h.
Referenced by borderStyleIsSet(), and setBorderStyle().
bool QgsLabelAttributes::mBorderWidthIsSet [protected]
Definition at line 245 of file qgslabelattributes.h.
Referenced by borderWidthIsSet(), and setBorderWidth().
QBrush QgsLabelAttributes::mBufferBrush [protected]
Buffer brush (color, style)
Definition at line 238 of file qgslabelattributes.h.
Referenced by bufferColor(), bufferStyle(), setBufferColor(), and setBufferStyle().
bool QgsLabelAttributes::mBufferColorIsSet [protected]
Definition at line 239 of file qgslabelattributes.h.
Referenced by setBufferColor().
bool QgsLabelAttributes::mBufferEnabledFlag [protected]
Buffer enablement.
Definition at line 231 of file qgslabelattributes.h.
Referenced by bufferEnabled(), and setBufferEnabled().
double QgsLabelAttributes::mBufferSize [protected]
Definition at line 234 of file qgslabelattributes.h.
Referenced by bufferSize(), and setBufferSize().
bool QgsLabelAttributes::mBufferSizeIsSet [protected]
Definition at line 235 of file qgslabelattributes.h.
Referenced by bufferSizeIsSet(), and setBufferSize().
int QgsLabelAttributes::mBufferSizeType [protected]
Buffer size, size type.
Definition at line 233 of file qgslabelattributes.h.
Referenced by bufferSizeType(), and setBufferSize().
bool QgsLabelAttributes::mBufferStyleIsSet [protected]
Definition at line 240 of file qgslabelattributes.h.
Referenced by bufferStyleIsSet(), and setBufferStyle().
QColor QgsLabelAttributes::mColor [protected]
Color.
Definition at line 212 of file qgslabelattributes.h.
Referenced by color(), and setColor().
bool QgsLabelAttributes::mColorIsSet [protected]
Definition at line 213 of file qgslabelattributes.h.
Referenced by bufferColorIsSet(), colorIsSet(), and setColor().
bool QgsLabelAttributes::mFamilyIsSet [protected]
Definition at line 200 of file qgslabelattributes.h.
Referenced by familyIsSet(), QgsLabelAttributes(), and setFamily().
QFont QgsLabelAttributes::mFont [protected]
Font (family, weight, italic, underline, strikeout)
Definition at line 199 of file qgslabelattributes.h.
Referenced by bold(), family(), italic(), QgsLabelAttributes(), setBold(), setFamily(), setItalic(), setStrikeOut(), setUnderline(), strikeOut(), and underline().
bool QgsLabelAttributes::mItalicIsSet [protected]
Definition at line 202 of file qgslabelattributes.h.
Referenced by italicIsSet(), QgsLabelAttributes(), and setItalic().
bool QgsLabelAttributes::mMultilineEnabledFlag [protected]
Multiline enablement.
Definition at line 249 of file qgslabelattributes.h.
Referenced by multilineEnabled(), and setMultilineEnabled().
bool QgsLabelAttributes::mOffsetIsSet [protected]
Definition at line 219 of file qgslabelattributes.h.
Referenced by offsetIsSet(), and setOffset().
int QgsLabelAttributes::mOffsetType [protected]
Offset.
Definition at line 216 of file qgslabelattributes.h.
Referenced by offsetType(), and setOffset().
bool QgsLabelAttributes::mSelectedOnly [protected]
Label only selected.
Definition at line 252 of file qgslabelattributes.h.
Referenced by selectedOnly(), and setSelectedOnly().
double QgsLabelAttributes::mSize [protected]
Definition at line 208 of file qgslabelattributes.h.
Referenced by setSize(), and size().
bool QgsLabelAttributes::mSizeIsSet [protected]
Definition at line 209 of file qgslabelattributes.h.
Referenced by setSize(), and sizeIsSet().
int QgsLabelAttributes::mSizeType [protected]
Font size, size type.
Definition at line 207 of file qgslabelattributes.h.
Referenced by setSize(), and sizeType().
bool QgsLabelAttributes::mStrikeOutIsSet [protected]
Definition at line 204 of file qgslabelattributes.h.
Referenced by setStrikeOut(), and strikeOutIsSet().
QString QgsLabelAttributes::mText [protected]
Definition at line 195 of file qgslabelattributes.h.
Referenced by setText(), and text().
bool QgsLabelAttributes::mTextIsSet [protected]
Definition at line 196 of file qgslabelattributes.h.
Referenced by setText(), and textIsSet().
bool QgsLabelAttributes::mUnderlineIsSet [protected]
Definition at line 203 of file qgslabelattributes.h.
Referenced by QgsLabelAttributes(), setUnderline(), and underlineIsSet().
double QgsLabelAttributes::mXOffset [protected]
Definition at line 217 of file qgslabelattributes.h.
Referenced by setOffset(), and xOffset().
double QgsLabelAttributes::mYOffset [protected]
Definition at line 218 of file qgslabelattributes.h.
Referenced by setOffset(), and yOffset().
The documentation for this class was generated from the following files:
src/core/qgslabelattributes.h
src/core/qgslabelattributes.cpp