Quantum GIS API Documentation: QgsLineVectorLayerDirector Class Reference
QgsLineVectorLayerDirector Class Reference
QGIS network analysis library.
Determine making the graph from vector line layer.
#include <qgslinevectorlayerdirector.h>
Public Member Functions
QgsLineVectorLayerDirector (QgsVectorLayer *vl, int directionFieldId, const QString &directDirectionValue, const QString &reverseDirectionValue, const QString &bothDirectionValue, int defaultDirection)
virtual ~QgsLineVectorLayerDirector ()
Destructor.
void makeGraph (QgsGraphBuilderInterface *builder, const QVector< QgsPoint > &additionalPoints, QVector< QgsPoint > &tiedPoints) const
Make a graph using RgGraphBuilder.
QString name () const
return Director name
Private Attributes
QgsVectorLayer * mVectorLayer
int mDirectionFieldId
QString mDirectDirectionValue
QString mReverseDirectionValue
QString mBothDirectionValue
int mDefaultDirection
Detailed Description
Determine making the graph from vector line layer.
Definition at line 34 of file qgslinevectorlayerdirector.h.
Constructor & Destructor Documentation
QgsLineVectorLayerDirector::QgsLineVectorLayerDirector (QgsVectorLayer * vl, int directionFieldId, const QString & directDirectionValue, const QString & reverseDirectionValue, const QString & bothDirectionValue, int defaultDirection)
Parameters:
vl source vector layer
directionFieldId feield contain road direction value
directDirectionValue value for one-way road
reverseDirectionValue value for reverse one-way road
bothDirectionValue value for road
defaultDirection 1 - direct direction, 2 - reverse direction, 3 - both direction
Definition at line 102 of file qgslinevectorlayerdirector.cpp.
References mBothDirectionValue, mDefaultDirection, mDirectDirectionValue, mDirectionFieldId, mReverseDirectionValue, and mVectorLayer.
QgsLineVectorLayerDirector::~QgsLineVectorLayerDirector () [virtual]
Destructor.
Definition at line 118 of file qgslinevectorlayerdirector.cpp.
Member Function Documentation
void QgsLineVectorLayerDirector::makeGraph (QgsGraphBuilderInterface * builder, const QVector< QgsPoint > & additionalPoints, QVector< QgsPoint > & tiedPoints) const [virtual]
Make a graph using RgGraphBuilder.
Parameters:
builder The graph builder
additionalPoints Vector of points that must be tied to the graph
tiedPoints Vector of tied points
Note:
if tiedPoints[i]==QgsPoint(0.0,0.0) then tied failed.
Reimplemented from QgsGraphDirector.
Definition at line 128 of file qgslinevectorlayerdirector.cpp.
References QgsGraphBuilderInterface::addArc(), QgsGraphBuilderInterface::addVertex(), QgsGeometry::asMultiPolyline(), QgsGeometry::asPolyline(), QgsFeature::attributeMap(), QgsGraphDirector::buildProgress(), QgsGraphBuilderInterface::coordinateTransformationEnabled(), QgsMapLayer::crs(), QgsGraphBuilderInterface::destinationCrs(), QgsGraphBuilderInterface::distanceArea(), QgsVectorLayer::featureCount(), QgsFeature::geometry(), mBothDirectionValue, mDefaultDirection, mDirectDirectionValue, mDirectionFieldId, QgsDistanceArea::measureLine(), TiePointInfo::mFirstPoint, TiePointInfo::mLastPoint, TiePointInfo::mLength, QgsGraphDirector::mProperterList, mReverseDirectionValue, TiePointInfo::mTiedPoint, mVectorLayer, my_binary_search(), QgsVectorLayer::nextFeature(), QgsVectorLayer::select(), QgsCoordinateTransform::setDestCRS(), QgsCoordinateTransform::setSourceCrs(), QgsPoint::sqrDist(), TiePointInfoCompare(), QgsGraphBuilderInterface::topologyTolerance(), QgsCoordinateTransform::transform(), QGis::WKBLineString, QGis::WKBMultiLineString, QgsGeometry::wkbType(), QgsPoint::x(), and QgsPoint::y().
QString QgsLineVectorLayerDirector::name () const [virtual]
return Director name
Implements QgsGraphDirector.
Definition at line 123 of file qgslinevectorlayerdirector.cpp.
Member Data Documentation
QString QgsLineVectorLayerDirector::mBothDirectionValue [private]
Definition at line 76 of file qgslinevectorlayerdirector.h.
Referenced by makeGraph(), and QgsLineVectorLayerDirector().
int QgsLineVectorLayerDirector::mDefaultDirection [private]
Definition at line 79 of file qgslinevectorlayerdirector.h.
Referenced by makeGraph(), and QgsLineVectorLayerDirector().
QString QgsLineVectorLayerDirector::mDirectDirectionValue [private]
Definition at line 72 of file qgslinevectorlayerdirector.h.
Referenced by makeGraph(), and QgsLineVectorLayerDirector().
int QgsLineVectorLayerDirector::mDirectionFieldId [private]
Definition at line 70 of file qgslinevectorlayerdirector.h.
Referenced by makeGraph(), and QgsLineVectorLayerDirector().
QString QgsLineVectorLayerDirector::mReverseDirectionValue [private]
Definition at line 74 of file qgslinevectorlayerdirector.h.
Referenced by makeGraph(), and QgsLineVectorLayerDirector().
QgsVectorLayer* QgsLineVectorLayerDirector::mVectorLayer [private]
Definition at line 68 of file qgslinevectorlayerdirector.h.
Referenced by makeGraph(), and QgsLineVectorLayerDirector().
The documentation for this class was generated from the following files:
src/analysis/network/qgslinevectorlayerdirector.h
src/analysis/network/qgslinevectorlayerdirector.cpp