Quantum GIS API Documentation: QgsSearchTreeValue Class Reference
QgsSearchTreeValue Class Reference
#include <qgssearchtreenode.h>
Public Types
enum Type { valError, valString, valNumber, valNull }
Public Member Functions
QgsSearchTreeValue ()
QgsSearchTreeValue (QString string)
QgsSearchTreeValue (double number)
QgsSearchTreeValue (int error, QString errorMsg)
bool isNumeric ()
bool isError ()
bool isNull ()
QString & string ()
double number ()
Static Public Member Functions
static QgsSearchTreeValue compare (QgsSearchTreeValue &value1, QgsSearchTreeValue &value2, Qt::CaseSensitivity=Qt::CaseSensitive)
Private Attributes
Type mType
QString mString
double mNumber
Detailed Description
Definition at line 257 of file qgssearchtreenode.h.
Member Enumeration Documentation
enum QgsSearchTreeValue::Type
Enumerator:
valError
valString
valNumber
valNull
Definition at line 261 of file qgssearchtreenode.h.
Constructor & Destructor Documentation
QgsSearchTreeValue::QgsSearchTreeValue () [inline]
Definition at line 269 of file qgssearchtreenode.h.
Referenced by compare().
QgsSearchTreeValue::QgsSearchTreeValue (QString string) [inline]
Definition at line 270 of file qgssearchtreenode.h.
QgsSearchTreeValue::QgsSearchTreeValue (double number) [inline]
Definition at line 271 of file qgssearchtreenode.h.
QgsSearchTreeValue::QgsSearchTreeValue (int error, QString errorMsg) [inline]
Definition at line 272 of file qgssearchtreenode.h.
Member Function Documentation
QgsSearchTreeValue QgsSearchTreeValue::compare (QgsSearchTreeValue & value1, QgsSearchTreeValue & value2, Qt::CaseSensitivity cs = Qt::CaseSensitive) [static]
Definition at line 905 of file qgssearchtreenode.cpp.
References isNumeric(), number(), QgsDebugMsgLevel, QgsSearchTreeValue(), and string().
Referenced by QgsSearchTreeNode::checkAgainst().
bool QgsSearchTreeValue::isError () [inline]
Definition at line 278 of file qgssearchtreenode.h.
Referenced by QgsSearchTreeNode::checkAgainst(), and QgsSearchTreeNode::getValue().
bool QgsSearchTreeValue::isNull () [inline]
Definition at line 279 of file qgssearchtreenode.h.
Referenced by QgsSearchTreeNode::checkAgainst().
bool QgsSearchTreeValue::isNumeric () [inline]
Definition at line 277 of file qgssearchtreenode.h.
Referenced by QgsSearchTreeNode::checkAgainst(), compare(), and QgsSearchTreeNode::valueAgainst().
double QgsSearchTreeValue::number () [inline]
Definition at line 282 of file qgssearchtreenode.h.
Referenced by QgsSearchTreeNode::checkAgainst(), compare(), QgsSearchTreeNode::getValue(), and QgsSearchTreeNode::valueAgainst().
QString& QgsSearchTreeValue::string () [inline]
Definition at line 281 of file qgssearchtreenode.h.
Referenced by QgsSearchTreeNode::checkAgainst(), compare(), QgsSearchTreeNode::getValue(), and QgsSearchTreeNode::valueAgainst().
Member Data Documentation
double QgsSearchTreeValue::mNumber [private]
Definition at line 287 of file qgssearchtreenode.h.
QString QgsSearchTreeValue::mString [private]
Definition at line 286 of file qgssearchtreenode.h.
Type QgsSearchTreeValue::mType [private]
Definition at line 285 of file qgssearchtreenode.h.
The documentation for this class was generated from the following files:
src/core/qgssearchtreenode.h
src/core/qgssearchtreenode.cpp