Quantum GIS API Documentation: QgsExpression::NodeLiteral Class Reference
QgsExpression::NodeLiteral Class Reference
#include <qgsexpression.h>
Public Member Functions
NodeLiteral (QVariant value)
QVariant value ()
virtual bool prepare (QgsExpression *parent, const QgsFieldMap &fields)
virtual QVariant eval (QgsExpression *parent, QgsFeature *f)
virtual QString dump () const
virtual void toOgcFilter (QDomDocument &doc, QDomElement &element) const
virtual QStringList referencedColumns () const
virtual bool needsGeometry () const
virtual void accept (Visitor &v)
Static Public Member Functions
static QgsExpression::Node * createFromOgcFilter (QDomElement &element, QString &errorMessage)
Protected Attributes
QVariant mValue
Detailed Description
Definition at line 368 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::NodeLiteral::NodeLiteral (QVariant value) [inline]
Definition at line 371 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::NodeLiteral::accept (Visitor & v) [inline, virtual]
Implements QgsExpression::Node.
Definition at line 384 of file qgsexpression.h.
References QgsExpression::Visitor::visit().
QgsExpression::Node * QgsExpression::NodeLiteral::createFromOgcFilter (QDomElement & element, QString & errorMessage) [static]
Reimplemented from QgsExpression::Node.
Definition at line 1476 of file qgsexpression.cpp.
References QgsExpression::boConcat, and QgsExpression::createFromOgcFilter().
QString QgsExpression::NodeLiteral::dump () const [virtual]
Implements QgsExpression::Node.
Definition at line 1437 of file qgsexpression.cpp.
QVariant QgsExpression::NodeLiteral::eval (QgsExpression * parent, QgsFeature * f) [virtual]
Implements QgsExpression::Node.
Definition at line 1426 of file qgsexpression.cpp.
virtual bool QgsExpression::NodeLiteral::needsGeometry () const [inline, virtual]
Implements QgsExpression::Node.
Definition at line 383 of file qgsexpression.h.
bool QgsExpression::NodeLiteral::prepare (QgsExpression * parent, const QgsFieldMap & fields) [virtual]
Implements QgsExpression::Node.
Definition at line 1431 of file qgsexpression.cpp.
virtual QStringList QgsExpression::NodeLiteral::referencedColumns () const [inline, virtual]
Implements QgsExpression::Node.
Definition at line 382 of file qgsexpression.h.
void QgsExpression::NodeLiteral::toOgcFilter (QDomDocument & doc, QDomElement & element) const [virtual]
Reimplemented from QgsExpression::Node.
Definition at line 1451 of file qgsexpression.cpp.
QVariant QgsExpression::NodeLiteral::value () [inline]
Definition at line 373 of file qgsexpression.h.
Referenced by QgsExpression::NodeBinaryOperator::toOgcFilter().
Member Data Documentation
QVariant QgsExpression::NodeLiteral::mValue [protected]
Definition at line 387 of file qgsexpression.h.
The documentation for this class was generated from the following files:
src/core/qgsexpression.h
src/core/qgsexpression.cpp