Quantum GIS API Documentation: QgsFillSymbolV2 Class Reference
QgsFillSymbolV2 Class Reference
#include <qgssymbolv2.h>
Public Member Functions
QgsFillSymbolV2 (QgsSymbolLayerV2List layers=QgsSymbolLayerV2List())
void setAngle (double angle)
void renderPolygon (const QPolygonF &points, QList< QPolygonF > *rings, const QgsFeature *f, QgsRenderContext &context, int layer=-1, bool selected=false)
virtual QgsSymbolV2 * clone () const
Static Public Member Functions
static QgsFillSymbolV2 * createSimple (const QgsStringMap &properties)
Create a fill symbol with one symbol layer: SimpleFill with specified properties.
Detailed Description
Definition at line 250 of file qgssymbolv2.h.
Constructor & Destructor Documentation
QgsFillSymbolV2::QgsFillSymbolV2 (QgsSymbolLayerV2List layers = QgsSymbolLayerV2List())
Definition at line 545 of file qgssymbolv2.cpp.
References QgsSymbolV2::mLayers.
Referenced by clone(), and createSimple().
Member Function Documentation
QgsSymbolV2 * QgsFillSymbolV2::clone () const [virtual]
Implements QgsSymbolV2.
Definition at line 585 of file qgssymbolv2.cpp.
References QgsSymbolV2::cloneLayers(), QgsSymbolV2::mAlpha, QgsSymbolV2::mOutputUnit, QgsFillSymbolV2(), QgsSymbolV2::setAlpha(), and QgsSymbolV2::setOutputUnit().
QgsFillSymbolV2 * QgsFillSymbolV2::createSimple (const QgsStringMap & properties) [static]
Create a fill symbol with one symbol layer: SimpleFill with specified properties.
This is a convenience method for easier creation of fill symbols.
Note:
added in v1.7
Definition at line 373 of file qgssymbolv2.cpp.
References QgsSimpleFillSymbolLayerV2::create(), and QgsFillSymbolV2().
void QgsFillSymbolV2::renderPolygon (const QPolygonF & points, QList< QPolygonF > * rings, const QgsFeature * f, QgsRenderContext & context, int layer = -1, bool selected = false)
Definition at line 552 of file qgssymbolv2.cpp.
References QgsSymbolV2::Fill, QgsSymbolV2::Line, QgsSymbolV2::mAlpha, QgsSymbolV2::mLayers, QgsSymbolV2::mOutputUnit, QgsSymbolV2::mRenderHints, QgsFillSymbolLayerV2::renderPolygon(), and QgsLineSymbolLayerV2::renderPolygonOutline().
void QgsFillSymbolV2::setAngle (double angle)
Definition at line 593 of file qgssymbolv2.cpp.
References QgsSymbolV2::mLayers, and QgsFillSymbolLayerV2::setAngle().
Referenced by QgsSingleSymbolRendererV2::symbolForFeature().
The documentation for this class was generated from the following files:
src/core/symbology-ng/qgssymbolv2.h
src/core/symbology-ng/qgssymbolv2.cpp