Quantum GIS API Documentation: QgsSlopeFilter Class Reference
QgsSlopeFilter Class Reference
Calculates slope values in a window of 3x3 cells based on first order derivatives in x- and y- directions.
#include <qgsslopefilter.h>
Public Member Functions
QgsSlopeFilter (const QString &inputFile, const QString &outputFile, const QString &outputFormat)
~QgsSlopeFilter ()
float processNineCellWindow (float *x11, float *x21, float *x31, float *x12, float *x22, float *x32, float *x13, float *x23, float *x33)
Calculates output value from nine input values.
Detailed Description
Calculates slope values in a window of 3x3 cells based on first order derivatives in x- and y- directions.
Definition at line 24 of file qgsslopefilter.h.
Constructor & Destructor Documentation
QgsSlopeFilter::QgsSlopeFilter (const QString & inputFile, const QString & outputFile, const QString & outputFormat)
Definition at line 20 of file qgsslopefilter.cpp.
QgsSlopeFilter::~QgsSlopeFilter ()
Definition at line 26 of file qgsslopefilter.cpp.
Member Function Documentation
float QgsSlopeFilter::processNineCellWindow (float * x11, float * x21, float * x31, float * x12, float * x22, float * x32, float * x13, float * x23, float * x33) [virtual]
Calculates output value from nine input values.
The input values and the output value can be equal to the nodata value if not present or outside of the border. Must be implemented by subclasses
Implements QgsDerivativeFilter.
Definition at line 31 of file qgsslopefilter.cpp.
References QgsDerivativeFilter::calcFirstDerX(), QgsDerivativeFilter::calcFirstDerY(), M_PI, and QgsNineCellFilter::mOutputNodataValue.
Referenced by QgsRelief::processNineCellWindow().
The documentation for this class was generated from the following files:
src/analysis/raster/qgsslopefilter.h
src/analysis/raster/qgsslopefilter.cpp