Quantum GIS API Documentation: QgsGraphBuilderInterface Class Reference
QgsGraphBuilderInterface Class Reference
QGIS network analysis library.
Determine interface for creating a graph.
#include <qgsgraphbuilderintr.h>
Public Member Functions
QgsGraphBuilderInterface (const QgsCoordinateReferenceSystem &crs, bool ctfEnabled=true, double topologyTolerance=0.0, const QString &ellipsoidID="WGS84")
QgsGraphBuilderInterface constructor.
virtual ~QgsGraphBuilderInterface ()
Destructor.
QgsCoordinateReferenceSystem & destinationCrs ()
get destinaltion Crs
bool coordinateTransformationEnabled ()
get coordinate transformation enabled
double topologyTolerance ()
get topology tolerance
QgsDistanceArea * distanceArea ()
get measurement tool
virtual void addVertex (int id, const QgsPoint &pt)
add vertex
virtual void addArc (int pt1id, const QgsPoint &pt1, int pt2id, const QgsPoint &pt2, const QVector< QVariant > &properties)
add arc
Private Attributes
QgsCoordinateReferenceSystem mCrs
QgsDistanceArea mDa
bool mCtfEnabled
double mTopologyTolerance
Detailed Description
Determine interface for creating a graph.
Contains the settings of the graph. QgsGraphBuilder and QgsGraphDirector is a Builder pattern
Definition at line 34 of file qgsgraphbuilderintr.h.
Constructor & Destructor Documentation
QgsGraphBuilderInterface::QgsGraphBuilderInterface (const QgsCoordinateReferenceSystem & crs, bool ctfEnabled = true, double topologyTolerance = 0.0, const QString & ellipsoidID = "WGS84") [inline]
QgsGraphBuilderInterface constructor.
Parameters:
crs Coordinate reference system for new graph vertex
ctfEnabled enable coordinate transform from source graph CRS to CRS graph
topologyTolerance sqrt distance between source point as one graph vertex
ellipsoidID ellipsoid for edge measurement
Definition at line 44 of file qgsgraphbuilderintr.h.
virtual QgsGraphBuilderInterface::~QgsGraphBuilderInterface () [inline, virtual]
Destructor.
Definition at line 53 of file qgsgraphbuilderintr.h.
Member Function Documentation
virtual void QgsGraphBuilderInterface::addArc (int pt1id, const QgsPoint & pt1, int pt2id, const QgsPoint & pt2, const QVector< QVariant > & properties) [inline, virtual]
add arc
Parameters:
pt1id first vertex identificator
pt1 first vertex coordinate
pt2id second vertex identificator
pt2 second vertex coordinate
properties arc properties
Note:
pt1id, pt1 and pt2id, pt2 is a redundant interface. You can use vertex coordinates or their identificators.
Reimplemented in QgsGraphBuilder.
Definition at line 101 of file qgsgraphbuilderintr.h.
Referenced by QgsLineVectorLayerDirector::makeGraph().
virtual void QgsGraphBuilderInterface::addVertex (int id, const QgsPoint & pt) [inline, virtual]
add vertex
Parameters:
id vertex identifier
pt vertex coordinate
Note:
id and pt are redundant. You can use pt or id to identify the vertex
Reimplemented in QgsGraphBuilder.
Definition at line 86 of file qgsgraphbuilderintr.h.
Referenced by QgsLineVectorLayerDirector::makeGraph().
bool QgsGraphBuilderInterface::coordinateTransformationEnabled () [inline]
get coordinate transformation enabled
Definition at line 63 of file qgsgraphbuilderintr.h.
Referenced by QgsLineVectorLayerDirector::makeGraph().
QgsCoordinateReferenceSystem& QgsGraphBuilderInterface::destinationCrs () [inline]
get destinaltion Crs
Definition at line 57 of file qgsgraphbuilderintr.h.
Referenced by QgsLineVectorLayerDirector::makeGraph().
QgsDistanceArea* QgsGraphBuilderInterface::distanceArea () [inline]
get measurement tool
Definition at line 75 of file qgsgraphbuilderintr.h.
Referenced by QgsLineVectorLayerDirector::makeGraph().
double QgsGraphBuilderInterface::topologyTolerance () [inline]
get topology tolerance
Definition at line 69 of file qgsgraphbuilderintr.h.
Referenced by QgsLineVectorLayerDirector::makeGraph().
Member Data Documentation
QgsCoordinateReferenceSystem QgsGraphBuilderInterface::mCrs [private]
Definition at line 111 of file qgsgraphbuilderintr.h.
bool QgsGraphBuilderInterface::mCtfEnabled [private]
Definition at line 115 of file qgsgraphbuilderintr.h.
QgsDistanceArea QgsGraphBuilderInterface::mDa [private]
Definition at line 113 of file qgsgraphbuilderintr.h.
double QgsGraphBuilderInterface::mTopologyTolerance [private]
Definition at line 117 of file qgsgraphbuilderintr.h.
The documentation for this class was generated from the following file:
src/analysis/network/qgsgraphbuilderintr.h