Quantum GIS API Documentation: MyLine Class Reference
MyLine Class Reference
Public Member Functions
MyLine (QPointF p1, QPointF p2)
double angle ()
QPointF diffForInterval (double interval)
double length ()
Protected Attributes
bool mVertical
bool mIncreasing
double mT
double mLength
Detailed Description
Definition at line 243 of file qgslinesymbollayerv2.cpp.
Constructor & Destructor Documentation
MyLine::MyLine (QPointF p1, QPointF p2) [inline]
Definition at line 246 of file qgslinesymbollayerv2.cpp.
References mIncreasing, mLength, mT, and mVertical.
Member Function Documentation
double MyLine::angle (void) [inline]
Definition at line 272 of file qgslinesymbollayerv2.cpp.
References M_PI, mIncreasing, mT, and mVertical.
Referenced by _averageAngle(), QgsMarkerLineSymbolLayerV2::renderPolylineCentral(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), and QgsMarkerLineSymbolLayerV2::renderPolylineVertex().
QPointF MyLine::diffForInterval (double interval) [inline]
Definition at line 282 of file qgslinesymbollayerv2.cpp.
References mIncreasing, mT, and mVertical.
Referenced by QgsMarkerLineSymbolLayerV2::renderPolylineInterval().
double MyLine::length () [inline]
Definition at line 293 of file qgslinesymbollayerv2.cpp.
References mLength.
Referenced by QgsMarkerLineSymbolLayerV2::renderPolylineInterval().
Member Data Documentation
bool MyLine::mIncreasing [protected]
Definition at line 297 of file qgslinesymbollayerv2.cpp.
Referenced by angle(), diffForInterval(), and MyLine().
double MyLine::mLength [protected]
Definition at line 299 of file qgslinesymbollayerv2.cpp.
Referenced by length(), and MyLine().
double MyLine::mT [protected]
Definition at line 298 of file qgslinesymbollayerv2.cpp.
Referenced by angle(), diffForInterval(), and MyLine().
bool MyLine::mVertical [protected]
Definition at line 296 of file qgslinesymbollayerv2.cpp.
Referenced by angle(), diffForInterval(), and MyLine().
The documentation for this class was generated from the following file:
src/core/symbology-ng/qgslinesymbollayerv2.cpp