Quantum GIS API Documentation: QgsExpression::Node Class Reference
QgsExpression::Node Class Reference
#include <qgsexpression.h>
Public Member Functions
virtual ~Node ()
virtual QVariant eval (QgsExpression *parent, QgsFeature *f)=0
virtual bool prepare (QgsExpression *parent, const QgsFieldMap &fields)=0
virtual QString dump () const =0
virtual void toOgcFilter (QDomDocument &doc, QDomElement &element) const
virtual QStringList referencedColumns () const =0
virtual bool needsGeometry () const =0
virtual void accept (Visitor &v)=0
Static Public Member Functions
static QgsExpression::Node * createFromOgcFilter (QDomElement &element, QString &errorMessage)
Detailed Description
Definition at line 219 of file qgsexpression.h.
Constructor & Destructor Documentation
virtual QgsExpression::Node::~Node () [inline, virtual]
Definition at line 222 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::Node::accept (Visitor & v) [pure virtual]
Implemented in QgsExpression::NodeCondition, QgsExpression::NodeColumnRef, QgsExpression::NodeLiteral, QgsExpression::NodeFunction, QgsExpression::NodeInOperator, QgsExpression::NodeBinaryOperator, and QgsExpression::NodeUnaryOperator.
Referenced by QgsExpression::acceptVisitor().
QgsExpression::Node * QgsExpression::Node::createFromOgcFilter (QDomElement & element, QString & errorMessage) [static]
Reimplemented in QgsExpression::NodeColumnRef, QgsExpression::NodeLiteral, QgsExpression::NodeFunction, QgsExpression::NodeBinaryOperator, and QgsExpression::NodeUnaryOperator.
Definition at line 630 of file qgsexpression.cpp.
References QgsExpression::BinaryOgcOperatorText, QgsExpression::boAnd, QgsExpression::boGE, QgsExpression::boLE, and QgsExpression::UnaryOgcOperatorText.
virtual QString QgsExpression::Node::dump () const [pure virtual]
Implemented in QgsExpression::NodeCondition, QgsExpression::NodeColumnRef, QgsExpression::NodeLiteral, QgsExpression::NodeFunction, QgsExpression::NodeInOperator, QgsExpression::NodeBinaryOperator, and QgsExpression::NodeUnaryOperator.
Referenced by QgsExpression::dump(), QgsExpression::NodeList::dump(), and QgsExpression::NodeCondition::dump().
virtual QVariant QgsExpression::Node::eval (QgsExpression * parent, QgsFeature * f) [pure virtual]
Implemented in QgsExpression::NodeCondition, QgsExpression::NodeColumnRef, QgsExpression::NodeLiteral, QgsExpression::NodeFunction, QgsExpression::NodeInOperator, QgsExpression::NodeBinaryOperator, and QgsExpression::NodeUnaryOperator.
Referenced by QgsExpression::NodeInOperator::eval(), QgsExpression::NodeFunction::eval(), QgsExpression::NodeCondition::eval(), and QgsExpression::evaluate().
virtual bool QgsExpression::Node::needsGeometry () const [pure virtual]
Implemented in QgsExpression::NodeCondition, QgsExpression::NodeColumnRef, QgsExpression::NodeLiteral, QgsExpression::NodeFunction, QgsExpression::NodeInOperator, QgsExpression::NodeBinaryOperator, and QgsExpression::NodeUnaryOperator.
Referenced by QgsExpression::needsGeometry(), QgsExpression::NodeInOperator::needsGeometry(), QgsExpression::NodeFunction::needsGeometry(), and QgsExpression::NodeCondition::needsGeometry().
virtual bool QgsExpression::Node::prepare (QgsExpression * parent, const QgsFieldMap & fields) [pure virtual]
Implemented in QgsExpression::NodeCondition, QgsExpression::NodeColumnRef, QgsExpression::NodeLiteral, QgsExpression::NodeFunction, QgsExpression::NodeInOperator, QgsExpression::NodeBinaryOperator, and QgsExpression::NodeUnaryOperator.
Referenced by QgsExpression::prepare(), QgsExpression::NodeInOperator::prepare(), QgsExpression::NodeFunction::prepare(), and QgsExpression::NodeCondition::prepare().
virtual QStringList QgsExpression::Node::referencedColumns () const [pure virtual]
Implemented in QgsExpression::NodeCondition, QgsExpression::NodeColumnRef, QgsExpression::NodeLiteral, QgsExpression::NodeFunction, QgsExpression::NodeInOperator, QgsExpression::NodeBinaryOperator, and QgsExpression::NodeUnaryOperator.
Referenced by QgsExpression::referencedColumns(), QgsExpression::NodeInOperator::referencedColumns(), QgsExpression::NodeFunction::referencedColumns(), and QgsExpression::NodeCondition::referencedColumns().
virtual void QgsExpression::Node::toOgcFilter (QDomDocument & doc, QDomElement & element) const [inline, virtual]
Reimplemented in QgsExpression::NodeCondition, QgsExpression::NodeColumnRef, QgsExpression::NodeLiteral, QgsExpression::NodeFunction, QgsExpression::NodeInOperator, QgsExpression::NodeBinaryOperator, and QgsExpression::NodeUnaryOperator.
Definition at line 233 of file qgsexpression.h.
Referenced by QgsExpression::NodeList::toOgcFilter(), QgsExpression::NodeBinaryOperator::toOgcFilter(), QgsExpression::NodeInOperator::toOgcFilter(), and QgsExpression::toOgcFilter().
The documentation for this class was generated from the following files:
src/core/qgsexpression.h
src/core/qgsexpression.cpp