Quantum GIS API Documentation: src/analysis/network/qgslinevectorlayerdirector.cpp File Reference
src/analysis/network/qgslinevectorlayerdirector.cpp File Reference
implementation of QgsLineVectorLayerDirector
#include "qgslinevectorlayerdirector.h"
#include "qgsgraphbuilderintr.h"
#include <qgsvectorlayer.h>
#include <qgsvectordataprovider.h>
#include <qgspoint.h>
#include <qgsgeometry.h>
#include <qgsdistancearea.h>
#include <QString>
#include <QtAlgorithms>
#include <limits>
#include <algorithm>
Classes
class QgsPointCompare
struct TiePointInfo
Functions
template<typename RandIter , typename Type , typename CompareOp >
RandIter my_binary_search (RandIter begin, RandIter end, Type val, CompareOp comp)
bool TiePointInfoCompare (const TiePointInfo &a, const TiePointInfo &b)
Detailed Description
implementation of QgsLineVectorLayerDirector
Definition in file qgslinevectorlayerdirector.cpp.
Function Documentation
template<typename RandIter , typename Type , typename CompareOp > RandIter my_binary_search (RandIter begin, RandIter end, Type val, CompareOp comp)
Definition at line 58 of file qgslinevectorlayerdirector.cpp.
Referenced by QgsLineVectorLayerDirector::makeGraph().
bool TiePointInfoCompare (const TiePointInfo & a, const TiePointInfo & b)
Definition at line 94 of file qgslinevectorlayerdirector.cpp.
References TiePointInfo::mFirstPoint, TiePointInfo::mLastPoint, QgsPoint::x(), and QgsPoint::y().
Referenced by QgsLineVectorLayerDirector::makeGraph().