Quantum GIS API Documentation: src/core/symbology-ng/qgsmarkersymbollayerv2.cpp File Reference
src/core/symbology-ng/qgsmarkersymbollayerv2.cpp File Reference
#include "qgsmarkersymbollayerv2.h"
#include "qgssymbollayerv2utils.h"
#include "qgsrendercontext.h"
#include "qgsapplication.h"
#include "qgslogger.h"
#include "qgsproject.h"
#include "qgssvgcache.h"
#include <QPainter>
#include <QSvgRenderer>
#include <QFileInfo>
#include <QDir>
#include <QDomDocument>
#include <QDomElement>
#include <cmath>
Defines
#define M_PI 3.14159265358979323846
#define DEG2RAD(x) ((x)*M_PI/180)
Functions
static QPointF _rotatedOffset (const QPointF &offset, double angle)
Define Documentation
#define DEG2RAD (x) ((x)*M_PI/180)
Definition at line 39 of file qgsmarkersymbollayerv2.cpp.
Referenced by _rotatedOffset(), and QgsSimpleMarkerSymbolLayerV2::prepareShape().
#define M_PI 3.14159265358979323846
Definition at line 36 of file qgsmarkersymbollayerv2.cpp.
Function Documentation
static QPointF _rotatedOffset (const QPointF & offset, double angle) [static]
Definition at line 42 of file qgsmarkersymbollayerv2.cpp.
References DEG2RAD.
Referenced by QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), and QgsFontMarkerSymbolLayerV2::renderPoint().