QGIS API Documentation: QgsManageConnectionsDialog Class Reference
QgsManageConnectionsDialog Class Reference
#include <qgsmanageconnectionsdialog.h>
Public Types
enum Mode { Export, Import }
enum Type {
WMS, PostGIS, WFS, MSSQL,
WCS, Oracle
}
Public Slots
void doExportImport ()
void selectAll ()
void clearSelection ()
void selectionChanged ()
Public Member Functions
QgsManageConnectionsDialog (QWidget *parent=NULL, Mode mode=Export, Type type=WMS, QString fileName="")
Private Member Functions
bool populateConnections ()
QDomDocument saveOWSConnections (const QStringList &connections, const QString &service)
QDomDocument saveWFSConnections (const QStringList &connections)
QDomDocument savePgConnections (const QStringList &connections)
QDomDocument saveMssqlConnections (const QStringList &connections)
QDomDocument saveOracleConnections (const QStringList &connections)
void loadOWSConnections (const QDomDocument &doc, const QStringList &items, const QString &service)
void loadWFSConnections (const QDomDocument &doc, const QStringList &items)
void loadPgConnections (const QDomDocument &doc, const QStringList &items)
void loadMssqlConnections (const QDomDocument &doc, const QStringList &items)
void loadOracleConnections (const QDomDocument &doc, const QStringList &items)
Private Attributes
QString mFileName
Mode mDialogMode
Type mConnectionType
Detailed Description
Definition at line 25 of file qgsmanageconnectionsdialog.h.
Member Enumeration Documentation
enum QgsManageConnectionsDialog::Mode
Enumerator
Export
Import
Definition at line 30 of file qgsmanageconnectionsdialog.h.
enum QgsManageConnectionsDialog::Type
Enumerator
WMS
PostGIS
WFS
MSSQL
WCS
Oracle
Definition at line 36 of file qgsmanageconnectionsdialog.h.
Constructor & Destructor Documentation
QgsManageConnectionsDialog::QgsManageConnectionsDialog (QWidget * parent = NULL, Mode mode = Export, Type type = WMS, QString fileName = "")
Definition at line 27 of file qgsmanageconnectionsdialog.cpp.
References clearSelection(), doExportImport(), Import, mDialogMode, populateConnections(), selectAll(), selectionChanged(), and tr.
Member Function Documentation
void QgsManageConnectionsDialog::clearSelection () slot
Definition at line 960 of file qgsmanageconnectionsdialog.cpp.
Referenced by QgsManageConnectionsDialog().
void QgsManageConnectionsDialog::doExportImport () slot
Definition at line 75 of file qgsmanageconnectionsdialog.cpp.
References Export, file, loadMssqlConnections(), loadOracleConnections(), loadOWSConnections(), loadPgConnections(), loadWFSConnections(), mConnectionType, mDialogMode, mFileName, MSSQL, Oracle, PostGIS, saveMssqlConnections(), saveOracleConnections(), saveOWSConnections(), savePgConnections(), saveWFSConnections(), tr, WCS, WFS, and WMS.
Referenced by QgsManageConnectionsDialog().
void QgsManageConnectionsDialog::loadMssqlConnections (const QDomDocument & doc, const QStringList & items) private
Definition at line 780 of file qgsmanageconnectionsdialog.cpp.
References tr.
Referenced by doExportImport().
void QgsManageConnectionsDialog::loadOracleConnections (const QDomDocument & doc, const QStringList & items) private
Definition at line 870 of file qgsmanageconnectionsdialog.cpp.
References tr.
Referenced by doExportImport().
void QgsManageConnectionsDialog::loadOWSConnections (const QDomDocument & doc, const QStringList & items, const QString & service) private
Definition at line 522 of file qgsmanageconnectionsdialog.cpp.
References tr.
Referenced by doExportImport().
void QgsManageConnectionsDialog::loadPgConnections (const QDomDocument & doc, const QStringList & items) private
Definition at line 690 of file qgsmanageconnectionsdialog.cpp.
References tr.
Referenced by doExportImport().
void QgsManageConnectionsDialog::loadWFSConnections (const QDomDocument & doc, const QStringList & items) private
Definition at line 609 of file qgsmanageconnectionsdialog.cpp.
References tr.
Referenced by doExportImport().
bool QgsManageConnectionsDialog::populateConnections () private
Definition at line 200 of file qgsmanageconnectionsdialog.cpp.
References Export, file, mConnectionType, mDialogMode, mFileName, MSSQL, Oracle, PostGIS, tr, WCS, WFS, and WMS.
Referenced by QgsManageConnectionsDialog().
QDomDocument QgsManageConnectionsDialog::saveMssqlConnections (const QStringList & connections) private
Definition at line 439 of file qgsmanageconnectionsdialog.cpp.
Referenced by doExportImport().
QDomDocument QgsManageConnectionsDialog::saveOracleConnections (const QStringList & connections) private
Definition at line 480 of file qgsmanageconnectionsdialog.cpp.
Referenced by doExportImport().
QDomDocument QgsManageConnectionsDialog::saveOWSConnections (const QStringList & connections, const QString & service) private
Definition at line 335 of file qgsmanageconnectionsdialog.cpp.
Referenced by doExportImport().
QDomDocument QgsManageConnectionsDialog::savePgConnections (const QStringList & connections) private
Definition at line 398 of file qgsmanageconnectionsdialog.cpp.
Referenced by doExportImport().
QDomDocument QgsManageConnectionsDialog::saveWFSConnections (const QStringList & connections) private
Definition at line 371 of file qgsmanageconnectionsdialog.cpp.
Referenced by doExportImport().
void QgsManageConnectionsDialog::selectAll () slot
Definition at line 954 of file qgsmanageconnectionsdialog.cpp.
Referenced by QgsManageConnectionsDialog().
void QgsManageConnectionsDialog::selectionChanged () slot
Definition at line 70 of file qgsmanageconnectionsdialog.cpp.
Referenced by QgsManageConnectionsDialog().
Member Data Documentation
Type QgsManageConnectionsDialog::mConnectionType private
Definition at line 74 of file qgsmanageconnectionsdialog.h.
Referenced by doExportImport(), and populateConnections().
Mode QgsManageConnectionsDialog::mDialogMode private
Definition at line 73 of file qgsmanageconnectionsdialog.h.
Referenced by doExportImport(), populateConnections(), and QgsManageConnectionsDialog().
QString QgsManageConnectionsDialog::mFileName private
Definition at line 72 of file qgsmanageconnectionsdialog.h.
Referenced by doExportImport(), and populateConnections().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmanageconnectionsdialog.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmanageconnectionsdialog.cpp