QGIS API Documentation: QgsLineSymbolV2 Class Reference
QgsLineSymbolV2 Class Reference
#include <qgssymbolv2.h>
Public Member Functions
QgsLineSymbolV2 (QgsSymbolLayerV2List layers=QgsSymbolLayerV2List())
void setWidth (double width)
double width ()
void renderPolyline (const QPolygonF &points, const QgsFeature *f, QgsRenderContext &context, int layer=-1, bool selected=false)
virtual QgsSymbolV2 * clone () const
Public Member Functions inherited from QgsSymbolV2
virtual ~QgsSymbolV2 ()
SymbolType type () const
QgsSymbolLayerV2 * symbolLayer (int layer)
int symbolLayerCount ()
bool insertSymbolLayer (int index, QgsSymbolLayerV2 *layer)
insert symbol layer to specified index
bool appendSymbolLayer (QgsSymbolLayerV2 *layer)
append symbol layer at the end of the list
bool deleteSymbolLayer (int index)
delete symbol layer at specified index
QgsSymbolLayerV2 * takeSymbolLayer (int index)
remove symbol layer from the list and return pointer to it
bool changeSymbolLayer (int index, QgsSymbolLayerV2 *layer)
delete layer at specified index and set a new one
void startRender (QgsRenderContext &context, const QgsFields *fields=0)
void stopRender (QgsRenderContext &context)
void setColor (const QColor &color)
QColor color () const
void drawPreviewIcon (QPainter *painter, QSize size)
QImage bigSymbolPreviewImage ()
QString dump () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
QgsSymbolV2::OutputUnit outputUnit () const
void setOutputUnit (QgsSymbolV2::OutputUnit u)
QgsMapUnitScale mapUnitScale () const
void setMapUnitScale (const QgsMapUnitScale &scale)
qreal alpha () const
Get alpha transparency 1 for opaque, 0 for invisible.
void setAlpha (qreal alpha)
Set alpha transparency 1 for opaque, 0 for invisible.
void setRenderHints (int hints)
int renderHints () const
QSet< QString > usedAttributes () const
void setLayer (const QgsVectorLayer *layer)
const QgsVectorLayer * layer () const
Static Public Member Functions
static QgsLineSymbolV2 * createSimple (const QgsStringMap &properties)
Create a line symbol with one symbol layer: SimpleLine with specified properties.
Static Public Member Functions inherited from QgsSymbolV2
static QgsSymbolV2 * defaultSymbol (QGis::GeometryType geomType)
return new default symbol for specified geometry type
Additional Inherited Members
Public Types inherited from QgsSymbolV2
enum OutputUnit { MM = 0, MapUnit, Mixed }
enum SymbolType { Marker, Line, Fill }
enum ScaleMethod { ScaleArea, ScaleDiameter }
enum RenderHint { DataDefinedSizeScale = 1, DataDefinedRotation = 2 }
Protected Member Functions inherited from QgsSymbolV2
QgsSymbolV2 (SymbolType type, QgsSymbolLayerV2List layers)
QgsSymbolLayerV2List cloneLayers () const
bool isSymbolLayerCompatible (SymbolType t)
check whether a symbol layer type can be used within the symbol (marker-marker, line-line, fill-fill/line)
Protected Attributes inherited from QgsSymbolV2
SymbolType mType
QgsSymbolLayerV2List mLayers
qreal mAlpha
Symbol opacity (in the range 0 - 1)
int mRenderHints
const QgsVectorLayer * mLayer
Detailed Description
Definition at line 251 of file qgssymbolv2.h.
Constructor & Destructor Documentation
QgsLineSymbolV2::QgsLineSymbolV2 (QgsSymbolLayerV2List layers = QgsSymbolLayerV2List())
Definition at line 597 of file qgssymbolv2.cpp.
References QgsSymbolV2::mLayers.
Referenced by clone(), and createSimple().
Member Function Documentation
QgsSymbolV2 * QgsLineSymbolV2::clone () const virtual
Implements QgsSymbolV2.
Definition at line 656 of file qgssymbolv2.cpp.
References QgsSymbolV2::cloneLayers(), QgsSymbolV2::mAlpha, QgsLineSymbolV2(), and QgsSymbolV2::setAlpha().
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsVectorFieldSymbolLayer::clone(), QgsSVGFillSymbolLayer::clone(), and QgsLinePatternFillSymbolLayer::clone().
QgsLineSymbolV2 * QgsLineSymbolV2::createSimple (const QgsStringMap & properties) static
Create a line symbol with one symbol layer: SimpleLine with specified properties.
This is a convenience method for easier creation of line symbols.
Note
added in v1.7
Definition at line 459 of file qgssymbolv2.cpp.
References QgsSimpleLineSymbolLayerV2::create(), and QgsLineSymbolV2().
Referenced by QgsComposerMap::createDefaultGridLineSymbol(), and QgsComposerMap::readXML().
void QgsLineSymbolV2::renderPolyline (const QPolygonF & points, const QgsFeature * f, QgsRenderContext & context, int layer = -1, bool selected = false)
Definition at line 637 of file qgssymbolv2.cpp.
References QgsSymbolV2::layer(), QgsSymbolV2::mAlpha, QgsSymbolV2::mapUnitScale(), QgsSymbolV2::mLayers, QgsSymbolV2::mRenderHints, QgsSymbolV2::outputUnit(), and QgsLineSymbolLayerV2::renderPolyline().
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsComposerMap::drawGridLine(), QgsVectorFieldSymbolLayer::renderPoint(), and QgsImageFillSymbolLayer::renderPolygon().
void QgsLineSymbolV2::setWidth (double width)
Definition at line 604 of file qgssymbolv2.cpp.
References QgsSymbolV2::layer(), QgsSymbolV2::mLayers, QgsLineSymbolLayerV2::setWidth(), width(), and QgsLineSymbolLayerV2::width().
Referenced by QgsComposerMap::readXML(), QgsComposerMap::setGridPenWidth(), QgsLinePatternFillSymbolLayer::setLineWidth(), QgsSingleSymbolRendererV2::symbolForFeature(), QgsGraduatedSymbolRendererV2::symbolForFeature(), and QgsCategorizedSymbolRendererV2::symbolForFeature().
double QgsLineSymbolV2::width ()
Definition at line 624 of file qgssymbolv2.cpp.
References QgsSymbolV2::layer(), QgsSymbolV2::mLayers, and QgsLineSymbolLayerV2::width().
Referenced by QgsComposerMap::gridPen(), setWidth(), and QgsLinePatternFillSymbolLayer::toSld().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbolv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbolv2.cpp