QGIS API Documentation: QgsMarkerSymbolV2 Class Reference
QgsMarkerSymbolV2 Class Reference
#include <qgssymbolv2.h>
Public Member Functions
QgsMarkerSymbolV2 (QgsSymbolLayerV2List layers=QgsSymbolLayerV2List())
void setAngle (double angle)
double angle ()
void setSize (double size)
double size ()
void setScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod)
ScaleMethod scaleMethod ()
void renderPoint (const QPointF &point, const QgsFeature *f, QgsRenderContext &context, int layer=-1, bool selected=false)
virtual QgsSymbolV2 * clone () const
Public Member Functions inherited from QgsSymbolV2
virtual ~QgsSymbolV2 ()
SymbolType type () const
QgsSymbolLayerV2 * symbolLayer (int layer)
int symbolLayerCount ()
bool insertSymbolLayer (int index, QgsSymbolLayerV2 *layer)
insert symbol layer to specified index
bool appendSymbolLayer (QgsSymbolLayerV2 *layer)
append symbol layer at the end of the list
bool deleteSymbolLayer (int index)
delete symbol layer at specified index
QgsSymbolLayerV2 * takeSymbolLayer (int index)
remove symbol layer from the list and return pointer to it
bool changeSymbolLayer (int index, QgsSymbolLayerV2 *layer)
delete layer at specified index and set a new one
void startRender (QgsRenderContext &context, const QgsFields *fields=0)
void stopRender (QgsRenderContext &context)
void setColor (const QColor &color)
QColor color () const
void drawPreviewIcon (QPainter *painter, QSize size)
QImage bigSymbolPreviewImage ()
QString dump () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
QgsSymbolV2::OutputUnit outputUnit () const
void setOutputUnit (QgsSymbolV2::OutputUnit u)
QgsMapUnitScale mapUnitScale () const
void setMapUnitScale (const QgsMapUnitScale &scale)
qreal alpha () const
Get alpha transparency 1 for opaque, 0 for invisible.
void setAlpha (qreal alpha)
Set alpha transparency 1 for opaque, 0 for invisible.
void setRenderHints (int hints)
int renderHints () const
QSet< QString > usedAttributes () const
void setLayer (const QgsVectorLayer *layer)
const QgsVectorLayer * layer () const
Static Public Member Functions
static QgsMarkerSymbolV2 * createSimple (const QgsStringMap &properties)
Create a marker symbol with one symbol layer: SimpleMarker with specified properties.
Static Public Member Functions inherited from QgsSymbolV2
static QgsSymbolV2 * defaultSymbol (QGis::GeometryType geomType)
return new default symbol for specified geometry type
Additional Inherited Members
Public Types inherited from QgsSymbolV2
enum OutputUnit { MM = 0, MapUnit, Mixed }
enum SymbolType { Marker, Line, Fill }
enum ScaleMethod { ScaleArea, ScaleDiameter }
enum RenderHint { DataDefinedSizeScale = 1, DataDefinedRotation = 2 }
Protected Member Functions inherited from QgsSymbolV2
QgsSymbolV2 (SymbolType type, QgsSymbolLayerV2List layers)
QgsSymbolLayerV2List cloneLayers () const
bool isSymbolLayerCompatible (SymbolType t)
check whether a symbol layer type can be used within the symbol (marker-marker, line-line, fill-fill/line)
Protected Attributes inherited from QgsSymbolV2
SymbolType mType
QgsSymbolLayerV2List mLayers
qreal mAlpha
Symbol opacity (in the range 0 - 1)
int mRenderHints
const QgsVectorLayer * mLayer
Detailed Description
Definition at line 224 of file qgssymbolv2.h.
Constructor & Destructor Documentation
QgsMarkerSymbolV2::QgsMarkerSymbolV2 (QgsSymbolLayerV2List layers = QgsSymbolLayerV2List())
Definition at line 484 of file qgssymbolv2.cpp.
References QgsSymbolV2::mLayers.
Referenced by clone(), and createSimple().
Member Function Documentation
double QgsMarkerSymbolV2::angle (void)
Definition at line 502 of file qgssymbolv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolV2::layer(), and QgsSymbolV2::mLayers.
Referenced by QgsMarkerLineSymbolLayerV2::renderOffsetVertexAlongLine(), QgsMarkerLineSymbolLayerV2::renderPolylineCentral(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), QgsMarkerLineSymbolLayerV2::renderPolylineVertex(), and setAngle().
QgsSymbolV2 * QgsMarkerSymbolV2::clone () const virtual
Implements QgsSymbolV2.
Definition at line 586 of file qgssymbolv2.cpp.
References QgsSymbolV2::cloneLayers(), QgsSymbolV2::mAlpha, QgsMarkerSymbolV2(), and QgsSymbolV2::setAlpha().
Referenced by QgsPointDisplacementRenderer::clone(), QgsMarkerLineSymbolLayerV2::clone(), QgsPointPatternFillSymbolLayer::clone(), and QgsCentroidFillSymbolLayerV2::clone().
QgsMarkerSymbolV2 * QgsMarkerSymbolV2::createSimple (const QgsStringMap & properties) static
Create a marker symbol with one symbol layer: SimpleMarker with specified properties.
This is a convenience method for easier creation of marker symbols.
Note
added in v1.7
Definition at line 448 of file qgssymbolv2.cpp.
References QgsSimpleMarkerSymbolLayerV2::create(), and QgsMarkerSymbolV2().
void QgsMarkerSymbolV2::renderPoint (const QPointF & point, const QgsFeature * f, QgsRenderContext & context, int layer = -1, bool selected = false)
Definition at line 568 of file qgssymbolv2.cpp.
References QgsSymbolV2::layer(), QgsSymbolV2::mAlpha, QgsSymbolV2::mapUnitScale(), QgsSymbolV2::mLayers, QgsSymbolV2::mRenderHints, QgsSymbolV2::outputUnit(), and QgsMarkerSymbolLayerV2::renderPoint().
Referenced by QgsPointPatternFillSymbolLayer::applyPattern(), QgsPointDisplacementRenderer::drawGroup(), QgsAnnotationItem::drawMarkerSymbol(), QgsMarkerLineSymbolLayerV2::renderOffsetVertexAlongLine(), QgsCentroidFillSymbolLayerV2::renderPolygon(), QgsMarkerLineSymbolLayerV2::renderPolylineCentral(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), and QgsMarkerLineSymbolLayerV2::renderPolylineVertex().
QgsSymbolV2::ScaleMethod QgsMarkerSymbolV2::scaleMethod ()
Definition at line 556 of file qgssymbolv2.cpp.
References DEFAULT_SCALE_METHOD, QgsSymbolV2::layer(), QgsSymbolV2::mLayers, and QgsMarkerSymbolLayerV2::scaleMethod().
void QgsMarkerSymbolV2::setAngle (double angle)
Definition at line 491 of file qgssymbolv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), angle(), QgsSymbolV2::layer(), QgsSymbolV2::mLayers, and QgsMarkerSymbolLayerV2::setAngle().
Referenced by QgsMarkerLineSymbolLayerV2::renderOffsetVertexAlongLine(), QgsMarkerLineSymbolLayerV2::renderPolylineCentral(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), QgsMarkerLineSymbolLayerV2::renderPolylineVertex(), QgsSingleSymbolRendererV2::symbolForFeature(), QgsGraduatedSymbolRendererV2::symbolForFeature(), and QgsCategorizedSymbolRendererV2::symbolForFeature().
void QgsMarkerSymbolV2::setScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod)
Definition at line 547 of file qgssymbolv2.cpp.
References QgsSymbolV2::layer(), QgsSymbolV2::mLayers, and QgsMarkerSymbolLayerV2::setScaleMethod().
Referenced by QgsFeatureRendererV2::setScaleMethodToSymbol(), QgsSingleSymbolRendererV2::symbolForFeature(), QgsGraduatedSymbolRendererV2::symbolForFeature(), and QgsCategorizedSymbolRendererV2::symbolForFeature().
void QgsMarkerSymbolV2::setSize (double size)
Definition at line 514 of file qgssymbolv2.cpp.
References QgsSymbolV2::layer(), QgsSymbolV2::mLayers, QgsMarkerSymbolLayerV2::setSize(), QgsMarkerSymbolLayerV2::size(), and size().
Referenced by QgsComposerLegend::drawSymbolV2(), QgsMarkerLineSymbolLayerV2::setWidth(), QgsSingleSymbolRendererV2::symbolForFeature(), QgsGraduatedSymbolRendererV2::symbolForFeature(), and QgsCategorizedSymbolRendererV2::symbolForFeature().
double QgsMarkerSymbolV2::size (void)
Definition at line 532 of file qgssymbolv2.cpp.
References QgsSymbolV2::layer(), QgsSymbolV2::mLayers, and QgsMarkerSymbolLayerV2::size().
Referenced by QgsComposerLegend::drawSymbolV2(), QgsMarkerLineSymbolLayerV2::estimateMaxBleed(), QgsAnnotationItem::scaledSymbolSize(), setSize(), and QgsMarkerLineSymbolLayerV2::width().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbolv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbolv2.cpp