QGIS API Documentation: QgsVectorLayerEditBuffer Class Reference
QgsVectorLayerEditBuffer Class Reference
#include <qgsvectorlayereditbuffer.h>
Signals
void layerModified ()
This signal is emitted when modifications has been done on layer.
void featureAdded (QgsFeatureId fid)
void featureDeleted (QgsFeatureId fid)
void geometryChanged (QgsFeatureId fid, QgsGeometry &geom)
void attributeValueChanged (QgsFeatureId fid, int idx, const QVariant &)
void attributeAdded (int idx)
void attributeDeleted (int idx)
void committedAttributesDeleted (const QString &layerId, const QgsAttributeList &deletedAttributes)
Signals emitted after committing changes.
void committedAttributesAdded (const QString &layerId, const QList< QgsField > &addedAttributes)
void committedFeaturesAdded (const QString &layerId, const QgsFeatureList &addedFeatures)
void committedFeaturesRemoved (const QString &layerId, const QgsFeatureIds &deletedFeatureIds)
void committedAttributeValuesChanges (const QString &layerId, const QgsChangedAttributesMap &changedAttributesValues)
void committedGeometriesChanges (const QString &layerId, const QgsGeometryMap &changedGeometries)
Public Member Functions
QgsVectorLayerEditBuffer (QgsVectorLayer *layer)
~QgsVectorLayerEditBuffer ()
bool isModified () const
Returns true if the provider has been modified since the last commit.
bool addFeature (QgsFeature &f)
Adds a feature.
bool addFeatures (QgsFeatureList &features)
Insert a copy of the given features into the layer (but does not commit it)
bool deleteFeature (QgsFeatureId fid)
delete a feature from the layer (but does not commit it)
bool changeGeometry (QgsFeatureId fid, QgsGeometry *geom)
change feature's geometry
bool changeAttributeValue (QgsFeatureId fid, int field, const QVariant &newValue, const QVariant &oldValue=QVariant())
changed an attribute value (but does not commit it)
bool addAttribute (const QgsField &field)
add an attribute field (but does not commit it) returns true if the field was added
bool deleteAttribute (int attr)
delete an attribute field (but does not commit it)
bool commitChanges (QStringList &commitErrors)
Attempts to commit any changes to disk.
void rollBack ()
Stop editing and discard the edits.
const QgsFeatureMap & addedFeatures ()
New features which are not commited.
const QgsChangedAttributesMap & changedAttributeValues ()
Changed attributes values which are not commited.
const QgsAttributeList & deletedAttributeIds ()
deleted attributes fields which are not commited.
const QList< QgsField > & addedAttributes ()
added attributes fields which are not commited
const QgsGeometryMap & changedGeometries ()
Changed geometries which are not commited.
const QgsFeatureIds deletedFeatureIds ()
Protected Slots
void undoIndexChanged (int index)
Protected Member Functions
void updateFields (QgsFields &fields)
void updateFeatureGeometry (QgsFeature &f)
Update feature with uncommited geometry updates.
void updateChangedAttributes (QgsFeature &f)
Update feature with uncommited attribute updates.
void handleAttributeAdded (int index)
update added and changed features after addition of an attribute
void handleAttributeDeleted (int index)
update added and changed features after removal of an attribute
void updateAttributeMapIndex (QgsAttributeMap &attrs, int index, int offset) const
Updates an index in an attribute map to a new value (for updates of changed attributes)
void updateLayerFields ()
Protected Attributes
QgsVectorLayer * L
QgsFeatureIds mDeletedFeatureIds
Deleted feature IDs which are not commited.
QgsFeatureMap mAddedFeatures
New features which are not commited.
QgsChangedAttributesMap mChangedAttributeValues
Changed attributes values which are not commited.
QgsAttributeList mDeletedAttributeIds
deleted attributes fields which are not commited.
QList< QgsField > mAddedAttributes
added attributes fields which are not commited
QgsGeometryMap mChangedGeometries
Changed geometries which are not commited.
Friends
class QgsVectorLayer
class QgsVectorLayerUndoCommand
class QgsVectorLayerUndoCommandAddFeature
class QgsVectorLayerUndoCommandDeleteFeature
class QgsVectorLayerUndoCommandChangeGeometry
class QgsVectorLayerUndoCommandChangeAttribute
class QgsVectorLayerUndoCommandAddAttribute
class QgsVectorLayerUndoCommandDeleteAttribute
Detailed Description
Definition at line 33 of file qgsvectorlayereditbuffer.h.
Constructor & Destructor Documentation
QgsVectorLayerEditBuffer::QgsVectorLayerEditBuffer (QgsVectorLayer * layer)
Definition at line 24 of file qgsvectorlayereditbuffer.cpp.
References L, undoIndexChanged(), and QgsMapLayer::undoStack().
QgsVectorLayerEditBuffer::~QgsVectorLayerEditBuffer ()
Definition at line 30 of file qgsvectorlayereditbuffer.cpp.
Member Function Documentation
bool QgsVectorLayerEditBuffer::addAttribute (const QgsField & field)
add an attribute field (but does not commit it) returns true if the field was added
Note
added in version 1.2
Definition at line 192 of file qgsvectorlayereditbuffer.cpp.
References QgsVectorDataProvider::AddAttributes, QgsVectorDataProvider::capabilities(), QgsFields::count(), QgsVectorLayer::dataProvider(), L, QgsField::name(), QgsVectorLayer::pendingFields(), QgsVectorLayerUndoCommandAddAttribute, QgsVectorDataProvider::supportedType(), and QgsMapLayer::undoStack().
Referenced by QgsVectorLayer::addAttribute().
const QList<QgsField>& QgsVectorLayerEditBuffer::addedAttributes () inline
added attributes fields which are not commited
Definition at line 104 of file qgsvectorlayereditbuffer.h.
Referenced by QgsVectorLayerFeatureSource::QgsVectorLayerFeatureSource().
const QgsFeatureMap& QgsVectorLayerEditBuffer::addedFeatures () inline
New features which are not commited.
Definition at line 95 of file qgsvectorlayereditbuffer.h.
Referenced by QgsFeatureListModel::data(), QgsAttributeTableFilterModel::filterAcceptsRow(), and QgsVectorLayerFeatureSource::QgsVectorLayerFeatureSource().
bool QgsVectorLayerEditBuffer::addFeature (QgsFeature & f)
Adds a feature.
Parameters
f feature to add
Returns
True in case of success and False in case of error
Definition at line 96 of file qgsvectorlayereditbuffer.cpp.
References QgsVectorDataProvider::AddFeatures, QgsFeature::attributes(), QgsVectorDataProvider::capabilities(), QgsFields::count(), QgsVectorLayer::dataProvider(), L, QgsVectorLayer::mUpdatedFields, QgsVectorLayerUndoCommandAddFeature, and QgsMapLayer::undoStack().
Referenced by QgsVectorLayer::addFeature(), and addFeatures().
bool QgsVectorLayerEditBuffer::addFeatures (QgsFeatureList & features)
Insert a copy of the given features into the layer (but does not commit it)
Definition at line 112 of file qgsvectorlayereditbuffer.cpp.
References addFeature(), QgsVectorDataProvider::AddFeatures, QgsVectorDataProvider::capabilities(), QgsVectorLayer::dataProvider(), L, and QgsVectorLayer::updateExtents().
Referenced by QgsVectorLayer::addFeatures(), and QgsVectorLayerEditUtils::splitFeatures().
void QgsVectorLayerEditBuffer::attributeAdded (int idx) signal
Referenced by QgsVectorLayerUndoCommandAddAttribute::redo(), and QgsVectorLayerUndoCommandDeleteAttribute::undo().
void QgsVectorLayerEditBuffer::attributeDeleted (int idx) signal
Referenced by QgsVectorLayerUndoCommandDeleteAttribute::redo(), and QgsVectorLayerUndoCommandAddAttribute::undo().
void QgsVectorLayerEditBuffer::attributeValueChanged (QgsFeatureId fid, int idx, const QVariant &) signal
Referenced by QgsVectorLayerUndoCommandChangeAttribute::redo(), and QgsVectorLayerUndoCommandChangeAttribute::undo().
bool QgsVectorLayerEditBuffer::changeAttributeValue (QgsFeatureId fid, int field, const QVariant & newValue, const QVariant & oldValue = QVariant())
changed an attribute value (but does not commit it)
Definition at line 172 of file qgsvectorlayereditbuffer.cpp.
References QgsVectorDataProvider::capabilities(), QgsVectorDataProvider::ChangeAttributeValues, QgsFields::count(), QgsVectorLayer::dataProvider(), FID_IS_NEW, QgsFields::fieldOrigin(), L, mAddedFeatures, QgsFields::OriginJoin, QgsVectorLayer::pendingFields(), QgsVectorLayerUndoCommandChangeAttribute, and QgsMapLayer::undoStack().
Referenced by QgsVectorLayer::changeAttributeValue().
const QgsChangedAttributesMap& QgsVectorLayerEditBuffer::changedAttributeValues () inline
Changed attributes values which are not commited.
Definition at line 98 of file qgsvectorlayereditbuffer.h.
Referenced by QgsFeatureListModel::data(), QgsAttributeTableFilterModel::filterAcceptsRow(), and QgsVectorLayerFeatureSource::QgsVectorLayerFeatureSource().
const QgsGeometryMap& QgsVectorLayerEditBuffer::changedGeometries () inline
Changed geometries which are not commited.
Definition at line 107 of file qgsvectorlayereditbuffer.h.
Referenced by QgsVectorLayerFeatureSource::QgsVectorLayerFeatureSource().
bool QgsVectorLayerEditBuffer::changeGeometry (QgsFeatureId fid, QgsGeometry * geom)
change feature's geometry
Note
added in version 1.2
Definition at line 149 of file qgsvectorlayereditbuffer.cpp.
References QgsVectorDataProvider::capabilities(), QgsVectorDataProvider::ChangeGeometries, QgsVectorLayer::dataProvider(), FID_IS_NEW, QgsVectorLayer::hasGeometryType(), L, mAddedFeatures, QgsVectorLayerUndoCommandChangeGeometry, and QgsMapLayer::undoStack().
Referenced by QgsVectorLayerEditUtils::addPart(), QgsVectorLayerEditUtils::addRing(), QgsVectorLayer::changeGeometry(), QgsVectorLayerEditUtils::deleteVertex(), QgsVectorLayerEditUtils::insertVertex(), QgsVectorLayerEditUtils::moveVertex(), QgsVectorLayerEditUtils::splitFeatures(), QgsVectorLayerEditUtils::splitParts(), and QgsVectorLayerEditUtils::translateFeature().
bool QgsVectorLayerEditBuffer::commitChanges (QStringList & commitErrors)
Attempts to commit any changes to disk.
Returns the result of the attempt. If a commit fails, the in-memory changes are left alone.
This allows editing to continue if the commit failed on e.g. a disallowed value in a Postgres database - the user can re-edit and try again.
The commits occur in distinct stages, (add attributes, add features, change attribute values, change geometries, delete features, delete attributes) so if a stage fails, it's difficult to roll back cleanly. Therefore any error message also includes which stage failed so that the user has some chance of repairing the damage cleanly.
Definition at line 238 of file qgsvectorlayereditbuffer.cpp.
References QgsVectorDataProvider::AddAttributes, QgsVectorDataProvider::addAttributes(), QgsVectorDataProvider::AddFeatures, QgsVectorDataProvider::addFeatures(), QgsFeature::attributes(), QgsVectorDataProvider::capabilities(), QgsVectorDataProvider::ChangeAttributeValues, QgsVectorDataProvider::changeAttributeValues(), QgsVectorDataProvider::ChangeGeometries, QgsVectorDataProvider::changeGeometryValues(), QgsVectorDataProvider::clearErrors(), committedAttributesAdded(), committedAttributesDeleted(), committedAttributeValuesChanges(), committedFeaturesAdded(), committedFeaturesRemoved(), committedGeometriesChanges(), QgsFields::count(), QgsVectorLayer::dataProvider(), QgsVectorDataProvider::DeleteAttributes, QgsVectorDataProvider::deleteAttributes(), QgsVectorDataProvider::DeleteFeatures, QgsVectorDataProvider::deleteFeatures(), QgsVectorDataProvider::errors(), featureAdded(), featureDeleted(), FID_TO_STRING, QgsVectorDataProvider::hasErrors(), QgsMapLayer::id(), QgsFeature::id(), L, QgsField::length(), mAddedAttributes, mAddedFeatures, mChangedAttributeValues, mChangedGeometries, mDeletedAttributeIds, mDeletedFeatureIds, QgsVectorLayer::mSelectedFeatureIds, QgsField::name(), QgsVectorLayer::pendingFields(), QgsField::precision(), QgsVectorLayer::providerType(), QgsFields::size(), QgsVectorLayer::storageType(), tr, QgsField::type(), QgsField::typeName(), and QgsVectorLayer::updateFields().
Referenced by QgsVectorLayer::commitChanges().
void QgsVectorLayerEditBuffer::committedAttributesAdded (const QString & layerId, const QList< QgsField > & addedAttributes) signal
Referenced by commitChanges().
void QgsVectorLayerEditBuffer::committedAttributesDeleted (const QString & layerId, const QgsAttributeList & deletedAttributes) signal
Signals emitted after committing changes.
Note
added in v1.6
Referenced by commitChanges().
void QgsVectorLayerEditBuffer::committedAttributeValuesChanges (const QString & layerId, const QgsChangedAttributesMap & changedAttributesValues) signal
Referenced by commitChanges().
void QgsVectorLayerEditBuffer::committedFeaturesAdded (const QString & layerId, const QgsFeatureList & addedFeatures) signal
Referenced by commitChanges().
void QgsVectorLayerEditBuffer::committedFeaturesRemoved (const QString & layerId, const QgsFeatureIds & deletedFeatureIds) signal
Referenced by commitChanges().
void QgsVectorLayerEditBuffer::committedGeometriesChanges (const QString & layerId, const QgsGeometryMap & changedGeometries) signal
Referenced by commitChanges().
bool QgsVectorLayerEditBuffer::deleteAttribute (int attr)
delete an attribute field (but does not commit it)
Definition at line 215 of file qgsvectorlayereditbuffer.cpp.
References QgsVectorDataProvider::capabilities(), QgsFields::count(), QgsVectorLayer::dataProvider(), QgsVectorDataProvider::DeleteAttributes, QgsFields::fieldOrigin(), QgsFields::fieldOriginIndex(), L, mDeletedAttributeIds, QgsFields::OriginJoin, QgsFields::OriginProvider, QgsVectorLayer::pendingFields(), QgsVectorLayerUndoCommandDeleteAttribute, and QgsMapLayer::undoStack().
Referenced by QgsVectorLayer::deleteAttribute().
const QgsAttributeList& QgsVectorLayerEditBuffer::deletedAttributeIds () inline
deleted attributes fields which are not commited.
The list is kept sorted.
Definition at line 101 of file qgsvectorlayereditbuffer.h.
Referenced by QgsVectorLayerFeatureSource::QgsVectorLayerFeatureSource().
const QgsFeatureIds QgsVectorLayerEditBuffer::deletedFeatureIds () inline
Definition at line 109 of file qgsvectorlayereditbuffer.h.
Referenced by QgsVectorLayerFeatureSource::QgsVectorLayerFeatureSource().
bool QgsVectorLayerEditBuffer::deleteFeature (QgsFeatureId fid)
delete a feature from the layer (but does not commit it)
Definition at line 128 of file qgsvectorlayereditbuffer.cpp.
References QgsVectorDataProvider::capabilities(), QgsVectorLayer::dataProvider(), QgsVectorDataProvider::DeleteFeatures, FID_IS_NEW, L, mAddedFeatures, mDeletedFeatureIds, QgsVectorLayerUndoCommandDeleteFeature, and QgsMapLayer::undoStack().
Referenced by QgsVectorLayer::deleteFeature().
void QgsVectorLayerEditBuffer::featureAdded (QgsFeatureId fid) signal
Referenced by commitChanges(), QgsVectorLayerUndoCommandAddFeature::redo(), and QgsVectorLayerUndoCommandDeleteFeature::undo().
void QgsVectorLayerEditBuffer::featureDeleted (QgsFeatureId fid) signal
Referenced by commitChanges(), QgsVectorLayerUndoCommandDeleteFeature::redo(), and QgsVectorLayerUndoCommandAddFeature::undo().
void QgsVectorLayerEditBuffer::geometryChanged (QgsFeatureId fid, QgsGeometry & geom) signal
Referenced by QgsVectorLayerUndoCommandChangeGeometry::redo(), and QgsVectorLayerUndoCommandChangeGeometry::undo().
void QgsVectorLayerEditBuffer::handleAttributeAdded (int index) protected
update added and changed features after addition of an attribute
Definition at line 552 of file qgsvectorlayereditbuffer.cpp.
References mAddedFeatures, mChangedAttributeValues, and updateAttributeMapIndex().
Referenced by QgsVectorLayerUndoCommandAddAttribute::redo(), and QgsVectorLayerUndoCommandDeleteAttribute::undo().
void QgsVectorLayerEditBuffer::handleAttributeDeleted (int index) protected
update added and changed features after removal of an attribute
Definition at line 569 of file qgsvectorlayereditbuffer.cpp.
References mAddedFeatures, mChangedAttributeValues, and updateAttributeMapIndex().
Referenced by QgsVectorLayerUndoCommandDeleteAttribute::redo(), and QgsVectorLayerUndoCommandAddAttribute::undo().
bool QgsVectorLayerEditBuffer::isModified () const
Returns true if the provider has been modified since the last commit.
Definition at line 35 of file qgsvectorlayereditbuffer.cpp.
References L, and QgsMapLayer::undoStack().
Referenced by QgsVectorLayer::isModified(), and rollBack().
void QgsVectorLayerEditBuffer::layerModified () signal
This signal is emitted when modifications has been done on layer.
Referenced by undoIndexChanged().
void QgsVectorLayerEditBuffer::rollBack ()
Stop editing and discard the edits.
Definition at line 519 of file qgsvectorlayereditbuffer.cpp.
References isModified(), L, mAddedAttributes, mAddedFeatures, mChangedAttributeValues, mChangedGeometries, mDeletedAttributeIds, and QgsMapLayer::undoStack().
Referenced by QgsVectorLayer::rollBack().
void QgsVectorLayerEditBuffer::undoIndexChanged (int index) protected slot
Definition at line 41 of file qgsvectorlayereditbuffer.cpp.
References layerModified(), and QgsDebugMsg.
Referenced by QgsVectorLayerEditBuffer().
void QgsVectorLayerEditBuffer::updateAttributeMapIndex (QgsAttributeMap & attrs, int index, int offset) const protected
Updates an index in an attribute map to a new value (for updates of changed attributes)
Definition at line 594 of file qgsvectorlayereditbuffer.cpp.
Referenced by handleAttributeAdded(), and handleAttributeDeleted().
void QgsVectorLayerEditBuffer::updateChangedAttributes (QgsFeature & f) protected
Update feature with uncommited attribute updates.
Definition at line 71 of file qgsvectorlayereditbuffer.cpp.
References QgsFeature::attributes(), QgsFeature::id(), mAddedAttributes, mChangedAttributeValues, and mDeletedAttributeIds.
void QgsVectorLayerEditBuffer::updateFeatureGeometry (QgsFeature & f) protected
Update feature with uncommited geometry updates.
Definition at line 64 of file qgsvectorlayereditbuffer.cpp.
References QgsFeature::id(), mChangedGeometries, and QgsFeature::setGeometry().
void QgsVectorLayerEditBuffer::updateFields (QgsFields & fields) protected
Definition at line 49 of file qgsvectorlayereditbuffer.cpp.
References QgsFields::append(), mAddedAttributes, mDeletedAttributeIds, QgsFields::OriginEdit, and QgsFields::remove().
Referenced by QgsVectorLayer::updateFields().
void QgsVectorLayerEditBuffer::updateLayerFields () protected
Definition at line 607 of file qgsvectorlayereditbuffer.cpp.
References L, and QgsVectorLayer::updateFields().
Referenced by QgsVectorLayerUndoCommandAddAttribute::redo(), QgsVectorLayerUndoCommandDeleteAttribute::redo(), QgsVectorLayerUndoCommandAddAttribute::undo(), and QgsVectorLayerUndoCommandDeleteAttribute::undo().
Friends And Related Function Documentation
friend class QgsVectorLayer friend
Definition at line 159 of file qgsvectorlayereditbuffer.h.
friend class QgsVectorLayerUndoCommand friend
Definition at line 161 of file qgsvectorlayereditbuffer.h.
friend class QgsVectorLayerUndoCommandAddAttribute friend
Definition at line 166 of file qgsvectorlayereditbuffer.h.
Referenced by addAttribute().
friend class QgsVectorLayerUndoCommandAddFeature friend
Definition at line 162 of file qgsvectorlayereditbuffer.h.
Referenced by addFeature().
friend class QgsVectorLayerUndoCommandChangeAttribute friend
Definition at line 165 of file qgsvectorlayereditbuffer.h.
Referenced by changeAttributeValue().
friend class QgsVectorLayerUndoCommandChangeGeometry friend
Definition at line 164 of file qgsvectorlayereditbuffer.h.
Referenced by changeGeometry().
friend class QgsVectorLayerUndoCommandDeleteAttribute friend
Definition at line 167 of file qgsvectorlayereditbuffer.h.
Referenced by deleteAttribute().
friend class QgsVectorLayerUndoCommandDeleteFeature friend
Definition at line 163 of file qgsvectorlayereditbuffer.h.
Referenced by deleteFeature().
Member Data Documentation
QgsVectorLayer* QgsVectorLayerEditBuffer::L protected
Definition at line 158 of file qgsvectorlayereditbuffer.h.
Referenced by addAttribute(), addFeature(), addFeatures(), changeAttributeValue(), changeGeometry(), commitChanges(), deleteAttribute(), deleteFeature(), isModified(), QgsVectorLayerEditBuffer(), rollBack(), and updateLayerFields().
QList<QgsField> QgsVectorLayerEditBuffer::mAddedAttributes protected
added attributes fields which are not commited
Definition at line 185 of file qgsvectorlayereditbuffer.h.
Referenced by commitChanges(), QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute(), QgsVectorLayerUndoCommandAddAttribute::redo(), QgsVectorLayerUndoCommandDeleteAttribute::redo(), rollBack(), QgsVectorLayerUndoCommandAddAttribute::undo(), QgsVectorLayerUndoCommandDeleteAttribute::undo(), updateChangedAttributes(), and updateFields().
QgsFeatureMap QgsVectorLayerEditBuffer::mAddedFeatures protected
New features which are not commited.
Definition at line 176 of file qgsvectorlayereditbuffer.h.
Referenced by changeAttributeValue(), changeGeometry(), commitChanges(), deleteFeature(), QgsVectorLayer::extent(), handleAttributeAdded(), handleAttributeDeleted(), QgsVectorLayer::maximumValue(), QgsVectorLayer::minimumValue(), QgsVectorLayer::pendingFeatureCount(), QgsVectorLayerUndoCommandChangeAttribute::QgsVectorLayerUndoCommandChangeAttribute(), QgsVectorLayerUndoCommandChangeGeometry::QgsVectorLayerUndoCommandChangeGeometry(), QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute(), QgsVectorLayerUndoCommandDeleteFeature::QgsVectorLayerUndoCommandDeleteFeature(), QgsVectorLayerUndoCommandAddFeature::redo(), QgsVectorLayerUndoCommandDeleteFeature::redo(), QgsVectorLayerUndoCommandChangeGeometry::redo(), QgsVectorLayerUndoCommandChangeAttribute::redo(), rollBack(), QgsVectorLayerUndoCommandAddFeature::undo(), QgsVectorLayerUndoCommandDeleteFeature::undo(), QgsVectorLayerUndoCommandChangeGeometry::undo(), QgsVectorLayerUndoCommandChangeAttribute::undo(), QgsVectorLayerUndoCommandDeleteAttribute::undo(), and QgsVectorLayer::uniqueValues().
QgsChangedAttributesMap QgsVectorLayerEditBuffer::mChangedAttributeValues protected
Changed attributes values which are not commited.
Definition at line 179 of file qgsvectorlayereditbuffer.h.
Referenced by commitChanges(), handleAttributeAdded(), handleAttributeDeleted(), QgsVectorLayer::maximumValue(), QgsVectorLayer::minimumValue(), QgsVectorLayerUndoCommandChangeAttribute::QgsVectorLayerUndoCommandChangeAttribute(), QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute(), QgsVectorLayerUndoCommandChangeAttribute::redo(), rollBack(), QgsVectorLayerUndoCommandChangeAttribute::undo(), QgsVectorLayerUndoCommandDeleteAttribute::undo(), QgsVectorLayer::uniqueValues(), and updateChangedAttributes().
QgsGeometryMap QgsVectorLayerEditBuffer::mChangedGeometries protected
Changed geometries which are not commited.
Definition at line 188 of file qgsvectorlayereditbuffer.h.
Referenced by commitChanges(), QgsVectorLayer::extent(), QgsVectorLayerUndoCommandChangeGeometry::QgsVectorLayerUndoCommandChangeGeometry(), QgsVectorLayerUndoCommandChangeGeometry::redo(), rollBack(), QgsVectorLayerUndoCommandChangeGeometry::undo(), and updateFeatureGeometry().
QgsAttributeList QgsVectorLayerEditBuffer::mDeletedAttributeIds protected
deleted attributes fields which are not commited.
The list is kept sorted.
Definition at line 182 of file qgsvectorlayereditbuffer.h.
Referenced by commitChanges(), deleteAttribute(), QgsVectorLayer::maximumValue(), QgsVectorLayer::minimumValue(), QgsVectorLayerUndoCommandDeleteAttribute::redo(), rollBack(), QgsVectorLayerUndoCommandDeleteAttribute::undo(), QgsVectorLayer::uniqueValues(), updateChangedAttributes(), and updateFields().
QgsFeatureIds QgsVectorLayerEditBuffer::mDeletedFeatureIds protected
Deleted feature IDs which are not commited.
Note a feature can be added and then deleted again before the change is committed - in that case the added feature would be removed from mAddedFeatures only and not entered here.
Definition at line 173 of file qgsvectorlayereditbuffer.h.
Referenced by commitChanges(), deleteFeature(), QgsVectorLayer::extent(), QgsVectorLayer::maximumValue(), QgsVectorLayer::minimumValue(), QgsVectorLayer::pendingFeatureCount(), QgsVectorLayerUndoCommandDeleteFeature::redo(), QgsVectorLayerUndoCommandDeleteFeature::undo(), and QgsVectorLayer::uniqueValues().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsvectorlayereditbuffer.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsvectorlayereditbuffer.cpp