QGIS API Documentation: QgsRasterLayerRenderer Class Reference
QgsRasterLayerRenderer Class Reference
Implementation of threaded rendering for raster layers.
#include <qgsrasterlayerrenderer.h>
Public Member Functions
QgsRasterLayerRenderer (QgsRasterLayer *layer, QgsRenderContext &rendererContext)
~QgsRasterLayerRenderer ()
virtual bool render ()
Do the rendering (based on data stored in the class)
Public Member Functions inherited from QgsMapLayerRenderer
QgsMapLayerRenderer (const QString &layerID)
virtual ~QgsMapLayerRenderer ()
QStringList errors () const
Return list of errors (problems) that happened during the rendering.
QString layerID () const
Get access to the ID of the layer rendered by this class.
Protected Attributes
QPainter * mPainter
const QgsMapToPixel * mMapToPixel
QgsRasterViewPort * mRasterViewPort
QgsRasterPipe * mPipe
Protected Attributes inherited from QgsMapLayerRenderer
QStringList mErrors
QString mLayerID
Detailed Description
Implementation of threaded rendering for raster layers.
Note
added in 2.4
Definition at line 34 of file qgsrasterlayerrenderer.h.
Constructor & Destructor Documentation
QgsRasterLayerRenderer::QgsRasterLayerRenderer (QgsRasterLayer * layer, QgsRenderContext & rendererContext)
Definition at line 24 of file qgsrasterlayerrenderer.cpp.
References QgsRenderContext::coordinateTransform(), QgsMapLayer::crs(), QgsRasterLayer::dataProvider(), QgsCoordinateTransform::destCRS(), QgsCoordinateTransform::destinationDatumTransform(), QgsRenderContext::extent(), QgsMapLayer::extent(), QgsRasterLayer::height(), QgsRectangle::intersect(), QgsRectangle::isEmpty(), QgsMessageLog::logMessage(), QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), mMapToPixel, mPainter, mPipe, mRasterViewPort, QgsRenderContext::painter(), QgsRasterLayer::pipe(), QgsDebugMsg, QgsDebugMsgLevel, QgsRenderContext::rasterScaleFactor(), QgsRenderContext::scaleFactor(), QgsRectangle::set(), QgsRasterDataProvider::setDpi(), QgsRectangle::setMinimal(), QgsPoint::setX(), QgsCoordinateTransform::sourceDatumTransform(), QgsMapToPixel::toMapCoordinatesF(), QgsRectangle::toString(), tr, QgsMapToPixel::transform(), QgsCoordinateTransform::transformBoundingBox(), QgsException::what(), QgsRasterLayer::width(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
QgsRasterLayerRenderer::~QgsRasterLayerRenderer ()
Definition at line 165 of file qgsrasterlayerrenderer.cpp.
References mPipe, and mRasterViewPort.
Member Function Documentation
bool QgsRasterLayerRenderer::render () virtual
Do the rendering (based on data stored in the class)
Implements QgsMapLayerRenderer.
Definition at line 171 of file qgsrasterlayerrenderer.cpp.
References QgsRasterPipe::last(), QgsRasterViewPort::mDestCRS, mMapToPixel, mPainter, mPipe, mRasterViewPort, QgsRasterViewPort::mSrcCRS, QgsRasterPipe::projector(), QgsDebugMsg, and QgsRasterProjector::setCRS().
Referenced by QgsRasterLayer::draw().
Member Data Documentation
const QgsMapToPixel* QgsRasterLayerRenderer::mMapToPixel protected
Definition at line 45 of file qgsrasterlayerrenderer.h.
Referenced by QgsRasterLayerRenderer(), and render().
QPainter* QgsRasterLayerRenderer::mPainter protected
Definition at line 44 of file qgsrasterlayerrenderer.h.
Referenced by QgsRasterLayerRenderer(), and render().
QgsRasterPipe* QgsRasterLayerRenderer::mPipe protected
Definition at line 48 of file qgsrasterlayerrenderer.h.
Referenced by QgsRasterLayerRenderer(), render(), and ~QgsRasterLayerRenderer().
QgsRasterViewPort* QgsRasterLayerRenderer::mRasterViewPort protected
Definition at line 46 of file qgsrasterlayerrenderer.h.
Referenced by QgsRasterLayerRenderer(), render(), and ~QgsRasterLayerRenderer().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/raster/qgsrasterlayerrenderer.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/raster/qgsrasterlayerrenderer.cpp