QGIS API Documentation: QgsSymbolV2RenderContext Class Reference
QgsSymbolV2RenderContext Class Reference
#include <qgssymbolv2.h>
Public Member Functions
QgsSymbolV2RenderContext (QgsRenderContext &c, QgsSymbolV2::OutputUnit u, qreal alpha=1.0, bool selected=false, int renderHints=0, const QgsFeature *f=0, const QgsFields *=0, const QgsMapUnitScale &mapUnitScale=QgsMapUnitScale())
~QgsSymbolV2RenderContext ()
QgsRenderContext & renderContext ()
const QgsRenderContext & renderContext () const
QgsSymbolV2::OutputUnit outputUnit () const
void setOutputUnit (QgsSymbolV2::OutputUnit u)
QgsMapUnitScale mapUnitScale () const
void setMapUnitScale (const QgsMapUnitScale &scale)
qreal alpha () const
Get alpha transparency 1 for opaque, 0 for invisible.
void setAlpha (qreal alpha)
Set alpha transparency 1 for opaque, 0 for invisible.
bool selected () const
void setSelected (bool selected)
int renderHints () const
void setRenderHints (int hints)
void setFeature (const QgsFeature *f)
const QgsFeature * feature () const
Current feature being rendered - may be null.
const QgsFields * fields () const
Fields of the layer.
double outputLineWidth (double width) const
double outputPixelSize (double size) const
QgsSymbolV2RenderContext & operator= (const QgsSymbolV2RenderContext &)
Private Attributes
QgsRenderContext & mRenderContext
QgsSymbolV2::OutputUnit mOutputUnit
QgsMapUnitScale mMapUnitScale
qreal mAlpha
bool mSelected
int mRenderHints
const QgsFeature * mFeature
const QgsFields * mFields
Detailed Description
Definition at line 162 of file qgssymbolv2.h.
Constructor & Destructor Documentation
QgsSymbolV2RenderContext::QgsSymbolV2RenderContext (QgsRenderContext & c, QgsSymbolV2::OutputUnit u, qreal alpha = 1.0, bool selected = false, int renderHints = 0, const QgsFeature * f = 0, const QgsFields * fields = 0, const QgsMapUnitScale & mapUnitScale = QgsMapUnitScale())
Definition at line 414 of file qgssymbolv2.cpp.
QgsSymbolV2RenderContext::~QgsSymbolV2RenderContext ()
Definition at line 420 of file qgssymbolv2.cpp.
Member Function Documentation
qreal QgsSymbolV2RenderContext::alpha () const inline
Get alpha transparency 1 for opaque, 0 for invisible.
Definition at line 179 of file qgssymbolv2.h.
Referenced by QgsGradientFillSymbolLayerV2::applyGradient(), QgsSVGFillSymbolLayer::applyPattern(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsShapeburstFillSymbolLayerV2::renderPolygon(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsMarkerLineSymbolLayerV2::startRender(), QgsGradientFillSymbolLayerV2::startRender(), QgsShapeburstFillSymbolLayerV2::startRender(), and QgsCentroidFillSymbolLayerV2::startRender().
const QgsFeature* QgsSymbolV2RenderContext::feature () const inline
Current feature being rendered - may be null.
Definition at line 193 of file qgssymbolv2.h.
Referenced by QgsSVGFillSymbolLayer::applyDataDefinedSettings(), QgsLinePatternFillSymbolLayer::applyDataDefinedSettings(), QgsPointPatternFillSymbolLayer::applyDataDefinedSettings(), QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleFillSymbolLayerV2::applyDataDefinedSymbology(), QgsGradientFillSymbolLayerV2::applyDataDefinedSymbology(), QgsShapeburstFillSymbolLayerV2::applyDataDefinedSymbology(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsSimpleLineSymbolLayerV2::dxfColor(), QgsSimpleFillSymbolLayerV2::dxfColor(), QgsSimpleLineSymbolLayerV2::dxfWidth(), QgsSimpleFillSymbolLayerV2::dxfWidth(), QgsImageFillSymbolLayer::dxfWidth(), QgsMarkerSymbolLayerV2::markerOffset(), QgsMarkerLineSymbolLayerV2::renderOffsetVertexAlongLine(), QgsEllipseSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsVectorFieldSymbolLayer::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsImageFillSymbolLayer::renderPolygon(), QgsCentroidFillSymbolLayerV2::renderPolygon(), QgsSimpleLineSymbolLayerV2::renderPolyline(), QgsMarkerLineSymbolLayerV2::renderPolyline(), QgsMarkerLineSymbolLayerV2::renderPolylineCentral(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), QgsMarkerLineSymbolLayerV2::renderPolylineVertex(), QgsEllipseSymbolLayerV2::startRender(), QgsEllipseSymbolLayerV2::writeDxf(), and QgsSimpleMarkerSymbolLayerV2::writeDxf().
const QgsFields* QgsSymbolV2RenderContext::fields (void) const inline
Fields of the layer.
Currently only available in startRender() calls to allow symbols with data-defined properties prepare the expressions (other times fields() returns null)
Note
added in 2.4
Definition at line 199 of file qgssymbolv2.h.
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsEllipseSymbolLayerV2::startRender(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsVectorFieldSymbolLayer::startRender(), QgsSvgMarkerSymbolLayerV2::startRender(), QgsMarkerLineSymbolLayerV2::startRender(), QgsGradientFillSymbolLayerV2::startRender(), QgsShapeburstFillSymbolLayerV2::startRender(), QgsSVGFillSymbolLayer::startRender(), QgsLinePatternFillSymbolLayer::startRender(), QgsPointPatternFillSymbolLayer::startRender(), and QgsCentroidFillSymbolLayerV2::startRender().
QgsMapUnitScale QgsSymbolV2RenderContext::mapUnitScale () const inline
Definition at line 175 of file qgssymbolv2.h.
QgsSymbolV2RenderContext & QgsSymbolV2RenderContext::operator= (const QgsSymbolV2RenderContext &)
Definition at line 436 of file qgssymbolv2.cpp.
double QgsSymbolV2RenderContext::outputLineWidth (double width) const
Definition at line 426 of file qgssymbolv2.cpp.
References QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mMapUnitScale, mOutputUnit, and mRenderContext.
Referenced by QgsPointDisplacementRenderer::drawCircle(), QgsPointDisplacementRenderer::drawGroup(), and QgsPointDisplacementRenderer::drawLabels().
double QgsSymbolV2RenderContext::outputPixelSize (double size) const
Definition at line 431 of file qgssymbolv2.cpp.
References mMapUnitScale, mOutputUnit, mRenderContext, and QgsSymbolLayerV2Utils::pixelSizeScaleFactor().
QgsSymbolV2::OutputUnit QgsSymbolV2RenderContext::outputUnit () const inline
Definition at line 172 of file qgssymbolv2.h.
QgsRenderContext& QgsSymbolV2RenderContext::renderContext () inline
Definition at line 168 of file qgssymbolv2.h.
Referenced by QgsFillSymbolLayerV2::_renderPolygon(), QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleFillSymbolLayerV2::applyDataDefinedSymbology(), QgsSVGFillSymbolLayer::applyPattern(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsPointDisplacementRenderer::drawCircle(), QgsPointDisplacementRenderer::drawLabels(), QgsVectorFieldSymbolLayer::drawPreviewIcon(), QgsSimpleLineSymbolLayerV2::dxfWidth(), QgsMarkerSymbolLayerV2::markerOffset(), QgsSimpleMarkerSymbolLayerV2::prepareCache(), QgsEllipseSymbolLayerV2::preparePath(), QgsMarkerLineSymbolLayerV2::renderOffsetVertexAlongLine(), QgsEllipseSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsVectorFieldSymbolLayer::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsSimpleFillSymbolLayerV2::renderPolygon(), QgsGradientFillSymbolLayerV2::renderPolygon(), QgsShapeburstFillSymbolLayerV2::renderPolygon(), QgsImageFillSymbolLayer::renderPolygon(), QgsCentroidFillSymbolLayerV2::renderPolygon(), QgsSimpleLineSymbolLayerV2::renderPolygonOutline(), QgsSimpleLineSymbolLayerV2::renderPolyline(), QgsMarkerLineSymbolLayerV2::renderPolyline(), QgsMarkerLineSymbolLayerV2::renderPolylineCentral(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), QgsMarkerLineSymbolLayerV2::renderPolylineVertex(), QgsEllipseSymbolLayerV2::startRender(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsVectorFieldSymbolLayer::startRender(), QgsSvgMarkerSymbolLayerV2::startRender(), QgsMarkerLineSymbolLayerV2::startRender(), QgsGradientFillSymbolLayerV2::startRender(), QgsFontMarkerSymbolLayerV2::startRender(), QgsShapeburstFillSymbolLayerV2::startRender(), QgsSVGFillSymbolLayer::startRender(), QgsLinePatternFillSymbolLayer::startRender(), QgsPointPatternFillSymbolLayer::startRender(), QgsCentroidFillSymbolLayerV2::startRender(), QgsVectorFieldSymbolLayer::stopRender(), QgsMarkerLineSymbolLayerV2::stopRender(), QgsSVGFillSymbolLayer::stopRender(), QgsPointPatternFillSymbolLayer::stopRender(), QgsCentroidFillSymbolLayerV2::stopRender(), and QgsSimpleMarkerSymbolLayerV2::writeDxf().
const QgsRenderContext& QgsSymbolV2RenderContext::renderContext () const inline
Definition at line 169 of file qgssymbolv2.h.
int QgsSymbolV2RenderContext::renderHints () const inline
Note
added in 1.5
Definition at line 187 of file qgssymbolv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleLineSymbolLayerV2::dxfWidth(), QgsEllipseSymbolLayerV2::preparePath(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsMarkerLineSymbolLayerV2::startRender(), QgsEllipseSymbolLayerV2::writeDxf(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), and QgsSvgMarkerSymbolLayerV2::writeDxf().
bool QgsSymbolV2RenderContext::selected () const inline
Definition at line 183 of file qgssymbolv2.h.
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsMarkerLineSymbolLayerV2::renderOffsetVertexAlongLine(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsSimpleFillSymbolLayerV2::renderPolygon(), QgsGradientFillSymbolLayerV2::renderPolygon(), QgsShapeburstFillSymbolLayerV2::renderPolygon(), QgsImageFillSymbolLayer::renderPolygon(), QgsCentroidFillSymbolLayerV2::renderPolygon(), QgsSimpleLineSymbolLayerV2::renderPolyline(), QgsMarkerLineSymbolLayerV2::renderPolylineCentral(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), and QgsMarkerLineSymbolLayerV2::renderPolylineVertex().
void QgsSymbolV2RenderContext::setAlpha (qreal alpha) inline
Set alpha transparency 1 for opaque, 0 for invisible.
Definition at line 181 of file qgssymbolv2.h.
void QgsSymbolV2RenderContext::setFeature (const QgsFeature * f) inline
Definition at line 191 of file qgssymbolv2.h.
void QgsSymbolV2RenderContext::setMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 176 of file qgssymbolv2.h.
void QgsSymbolV2RenderContext::setOutputUnit (QgsSymbolV2::OutputUnit u) inline
Definition at line 173 of file qgssymbolv2.h.
void QgsSymbolV2RenderContext::setRenderHints (int hints) inline
Note
added in 1.5
Definition at line 189 of file qgssymbolv2.h.
void QgsSymbolV2RenderContext::setSelected (bool selected) inline
Definition at line 184 of file qgssymbolv2.h.
Member Data Documentation
qreal QgsSymbolV2RenderContext::mAlpha private
Definition at line 211 of file qgssymbolv2.h.
const QgsFeature* QgsSymbolV2RenderContext::mFeature private
Definition at line 214 of file qgssymbolv2.h.
const QgsFields* QgsSymbolV2RenderContext::mFields private
Definition at line 215 of file qgssymbolv2.h.
QgsMapUnitScale QgsSymbolV2RenderContext::mMapUnitScale private
Definition at line 210 of file qgssymbolv2.h.
Referenced by outputLineWidth(), and outputPixelSize().
QgsSymbolV2::OutputUnit QgsSymbolV2RenderContext::mOutputUnit private
Definition at line 209 of file qgssymbolv2.h.
Referenced by outputLineWidth(), and outputPixelSize().
QgsRenderContext& QgsSymbolV2RenderContext::mRenderContext private
Definition at line 208 of file qgssymbolv2.h.
Referenced by outputLineWidth(), and outputPixelSize().
int QgsSymbolV2RenderContext::mRenderHints private
Definition at line 213 of file qgssymbolv2.h.
bool QgsSymbolV2RenderContext::mSelected private
Definition at line 212 of file qgssymbolv2.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbolv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbolv2.cpp