QGIS API Documentation: QgsMapRendererJob Class Reference
QgsMapRendererJob Class Reference abstract
Abstract base class for map rendering implementations.
#include <qgsmaprendererjob.h>
Classes
struct Error
Public Types
typedef QList< Error > Errors
Signals
void finished ()
emitted when asynchronous rendering is finished (or canceled).
Public Member Functions
QgsMapRendererJob (const QgsMapSettings &settings)
virtual ~QgsMapRendererJob ()
virtual void start ()=0
Start the rendering job and immediately return.
virtual void cancel ()=0
Stop the rendering job - does not return until the job has terminated.
virtual void waitForFinished ()=0
Block until the job has finished.
virtual bool isActive () const =0
Tell whether the rendering job is currently running in background.
virtual QgsLabelingResults * takeLabelingResults ()=0
Get pointer to internal labeling engine (in order to get access to the results)
Errors errors () const
List of errors that happened during the rendering job - available when the rendering has been finished.
void setCache (QgsMapRendererCache *cache)
Assign a cache to be used for reading and storing rendered images of individual layers.
void setRequestedGeometryCacheForLayers (const QStringList &layerIds)
Set which vector layers should be cached while rendering.
int renderingTime () const
Find out how log it took to finish the job (in miliseconds)
Protected Member Functions
LayerRenderJobs prepareJobs (QPainter *painter, QgsPalLabeling *labelingEngine)
void cleanupJobs (LayerRenderJobs &jobs)
bool needTemporaryImage (QgsMapLayer *ml)
void updateLayerGeometryCaches ()
called when rendering has finished to update all layers' geometry caches
Static Protected Member Functions
static bool reprojectToLayerExtent (const QgsCoordinateTransform *ct, bool layerCrsGeographic, QgsRectangle &extent, QgsRectangle &r2)
Convenience function to project an extent into the layer source CRS, but also split it into two extents if it crosses the +/- 180 degree line.
static QImage composeImage (const QgsMapSettings &settings, const LayerRenderJobs &jobs)
static void drawLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext, QgsPalLabeling *labelingEngine, QPainter *painter)
static void drawOldLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext)
static void drawNewLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext, QgsPalLabeling *labelingEngine)
Protected Attributes
QgsMapSettings mSettings
Errors mErrors
QgsMapRendererCache * mCache
QStringList mRequestedGeomCacheForLayers
list of layer IDs for which the geometry cache should be updated
QMap< QString, QgsGeometryCache > mGeometryCaches
map of geometry caches
QTime mRenderingStart
int mRenderingTime
Detailed Description
Abstract base class for map rendering implementations.
The API is designed in a way that rendering is done asynchronously, therefore the caller is not blocked while the rendering is in progress. Non-blocking operation is quite important because the rendering can take considerable amount of time.
Common use case: 0. prepare QgsMapSettings with rendering configuration (extent, layer, map size, ...)
create QgsMapRendererJob subclass with QgsMapSettings instance
connect to job's finished() signal
call start(). Map rendering will start in background, the function immediately returns
at some point, slot connected to finished() signal is called, map rendering is done
It is possible to cancel the rendering job while it is active by calling cancel() function.
The following subclasses are available:
QgsMapRendererSequentialJob - renders map in one background thread to an image
QgsMapRendererParallelJob - renders map in multiple background threads to an image
QgsMapRendererCustomPainterJob - renders map with given QPainter in one background thread
Note
added in 2.4
Definition at line 78 of file qgsmaprendererjob.h.
Member Typedef Documentation
typedef QList<Error> QgsMapRendererJob::Errors
Definition at line 112 of file qgsmaprendererjob.h.
Constructor & Destructor Documentation
QgsMapRendererJob::QgsMapRendererJob (const QgsMapSettings & settings)
Definition at line 35 of file qgsmaprendererjob.cpp.
virtual QgsMapRendererJob::~QgsMapRendererJob () inline virtual
Definition at line 85 of file qgsmaprendererjob.h.
Member Function Documentation
virtual void QgsMapRendererJob::cancel () pure virtual
Stop the rendering job - does not return until the job has terminated.
Does nothing if the rendering is not active.
Implemented in QgsMapRendererCustomPainterJob, QgsMapRendererSequentialJob, and QgsMapRendererParallelJob.
Referenced by QgsMapOverviewCanvas::refresh(), QgsMapCanvas::stopRendering(), and QgsMapCanvas::~QgsMapCanvas().
void QgsMapRendererJob::cleanupJobs (LayerRenderJobs & jobs) protected
Note
not available in python bindings
Definition at line 269 of file qgsmaprendererjob.cpp.
References LayerRenderJob::cached, LayerRenderJob::context, QgsMapLayerRenderer::errors(), LayerRenderJob::img, LayerRenderJob::layerId, QgsMapLayerRenderer::layerID(), mCache, mErrors, QgsRenderContext::painter(), QgsDebugMsg, LayerRenderJob::renderer, QgsRenderContext::renderingStopped(), QgsMapRendererCache::setCacheImage(), QgsRenderContext::setPainter(), and updateLayerGeometryCaches().
Referenced by QgsMapRendererCustomPainterJob::futureFinished(), and QgsMapRendererParallelJob::renderLayersFinished().
QImage QgsMapRendererJob::composeImage (const QgsMapSettings & settings, const LayerRenderJobs & jobs) static protected
Definition at line 305 of file qgsmaprendererjob.cpp.
References QgsMapSettings::backgroundColor(), LayerRenderJob::blendMode, LayerRenderJob::img, QgsMapSettings::outputImageFormat(), and QgsMapSettings::outputSize().
Referenced by QgsMapRendererParallelJob::renderedImage(), QgsMapRendererSequentialJob::renderedImage(), and QgsMapRendererParallelJob::renderLayersFinished().
void QgsMapRendererJob::drawLabeling (const QgsMapSettings & settings, QgsRenderContext & renderContext, QgsPalLabeling * labelingEngine, QPainter * painter) static protected
Definition at line 248 of file qgsmaprenderercustompainterjob.cpp.
References drawNewLabeling(), drawOldLabeling(), QgsRenderContext::fromMapSettings(), QgsDebugMsg, QgsRenderContext::setLabelingEngine(), and QgsRenderContext::setPainter().
Referenced by QgsMapRendererCustomPainterJob::doRender(), and QgsMapRendererParallelJob::renderLabelsStatic().
void QgsMapRendererJob::drawNewLabeling (const QgsMapSettings & settings, QgsRenderContext & renderContext, QgsPalLabeling * labelingEngine) static protected
Definition at line 314 of file qgsmaprenderercustompainterjob.cpp.
References QgsPalLabeling::drawLabeling(), QgsPalLabeling::exit(), QgsRenderContext::renderingStopped(), QgsRenderContext::setCoordinateTransform(), QgsRenderContext::setExtent(), and QgsMapSettings::visibleExtent().
Referenced by drawLabeling().
void QgsMapRendererJob::drawOldLabeling (const QgsMapSettings & settings, QgsRenderContext & renderContext) static protected
Definition at line 272 of file qgsmaprenderercustompainterjob.cpp.
References QgsMapLayer::crs(), QgsMapLayer::drawLabels(), QgsCoordinateReferenceSystem::geographicFlag(), QgsMapSettings::hasCrsTransformEnabled(), QgsMapLayer::hasScaleBasedVisibility(), QgsMapLayerRegistry::instance(), QgsMapSettings::layers(), QgsMapSettings::layerTransfrom(), QgsMapLayerRegistry::mapLayer(), QgsMapLayer::maximumScale(), QgsMapLayer::minimumScale(), QgsRenderContext::renderingStopped(), reprojectToLayerExtent(), QgsMapSettings::scale(), QgsRenderContext::setCoordinateTransform(), QgsRenderContext::setExtent(), QgsMapLayer::type(), QgsMapLayer::VectorLayer, and QgsMapSettings::visibleExtent().
Referenced by drawLabeling().
QgsMapRendererJob::Errors QgsMapRendererJob::errors () const
List of errors that happened during the rendering job - available when the rendering has been finished.
Definition at line 49 of file qgsmaprendererjob.cpp.
References mErrors.
Referenced by QgsMapRendererSequentialJob::internalFinished(), and QgsMapCanvas::rendererJobFinished().
void QgsMapRendererJob::finished () signal
emitted when asynchronous rendering is finished (or canceled).
Referenced by QgsMapRendererParallelJob::cancel(), QgsMapRendererCustomPainterJob::cancel(), QgsMapRendererCustomPainterJob::futureFinished(), QgsMapRendererSequentialJob::internalFinished(), QgsMapRendererParallelJob::renderingFinished(), QgsMapRendererParallelJob::renderLayersFinished(), QgsMapRendererParallelJob::start(), QgsMapRendererSequentialJob::start(), QgsMapRendererCustomPainterJob::start(), QgsMapRendererParallelJob::waitForFinished(), QgsMapRendererCustomPainterJob::waitForFinished(), and QgsMapRendererCustomPainterJob::waitForFinishedWithEventLoop().
virtual bool QgsMapRendererJob::isActive () const pure virtual
Tell whether the rendering job is currently running in background.
Implemented in QgsMapRendererCustomPainterJob, QgsMapRendererSequentialJob, and QgsMapRendererParallelJob.
bool QgsMapRendererJob::needTemporaryImage (QgsMapLayer * ml) protected
Definition at line 339 of file qgsmaprenderercustompainterjob.cpp.
References QgsMapLayer::blendMode(), QgsVectorLayer::featureBlendMode(), QgsVectorLayer::layerTransparency(), mSettings, QgsMapSettings::testFlag(), QgsMapLayer::type(), QgsMapSettings::UseAdvancedEffects, and QgsMapLayer::VectorLayer.
Referenced by prepareJobs().
LayerRenderJobs QgsMapRendererJob::prepareJobs (QPainter * painter, QgsPalLabeling * labelingEngine) protected
Note
not available in python bindings
Definition at line 132 of file qgsmaprendererjob.cpp.
References QgsMapSettings::Antialiasing, LayerRenderJob::blendMode, QgsMapLayer::blendMode(), LayerRenderJob::cached, QgsMapRendererCache::cacheImage(), QgsMapRendererCache::clearCacheImage(), LayerRenderJob::context, QgsMapLayer::createMapRenderer(), QgsMapLayer::crs(), QgsMapLayer::extent(), QgsRenderContext::fromMapSettings(), QgsCoordinateReferenceSystem::geographicFlag(), QgsMapSettings::hasCrsTransformEnabled(), QgsMapLayer::hasScaleBasedVisibility(), QgsMapLayer::id(), LayerRenderJob::img, QgsMapRendererCache::init(), QgsMapLayerRegistry::instance(), QgsVectorLayer::isEditable(), QgsRectangle::isFinite(), isNull(), LayerRenderJob::layerId, QgsMapSettings::layers(), QgsMapSettings::layerTransfrom(), QgsMapLayerRegistry::mapLayer(), QgsMapLayer::maximumScale(), mCache, mErrors, mGeometryCaches, QgsMapLayer::minimumScale(), mRequestedGeomCacheForLayers, mSettings, QgsMapLayer::name(), needTemporaryImage(), QgsMapSettings::outputImageFormat(), QgsMapSettings::outputSize(), QgsDebugMsg, LayerRenderJob::renderer, reprojectToLayerExtent(), QgsMapSettings::scale(), QgsRenderContext::setCoordinateTransform(), QgsRenderContext::setExtent(), QgsRenderContext::setLabelingEngine(), QgsRenderContext::setPainter(), QgsMapSettings::testFlag(), QgsRectangle::toString(), QgsMapLayer::type(), QgsMapLayer::VectorLayer, QgsMapSettings::visibleExtent(), and QgsPalLabeling::willUseLayer().
Referenced by QgsMapRendererParallelJob::start(), and QgsMapRendererCustomPainterJob::start().
int QgsMapRendererJob::renderingTime () const inline
Find out how log it took to finish the job (in miliseconds)
Definition at line 127 of file qgsmaprendererjob.h.
Referenced by QgsMapCanvas::rendererJobFinished().
bool QgsMapRendererJob::reprojectToLayerExtent (const QgsCoordinateTransform * ct, bool layerCrsGeographic, QgsRectangle & extent, QgsRectangle & r2) static protected
Convenience function to project an extent into the layer source CRS, but also split it into two extents if it crosses the +/- 180 degree line.
Modifies the given extent to be in the source CRS coordinates, and if it was split, returns true, and also sets the contents of the r2 parameter
Definition at line 60 of file qgsmaprendererjob.cpp.
References QgsCoordinateTransform::destCRS(), QgsCoordinateReferenceSystem::geographicFlag(), QgsDebugMsg, QgsCoordinateTransform::ReverseTransform, QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsCoordinateTransform::transform(), QgsCoordinateTransform::transformBoundingBox(), QgsPoint::x(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by drawOldLabeling(), and prepareJobs().
void QgsMapRendererJob::setCache (QgsMapRendererCache * cache)
Assign a cache to be used for reading and storing rendered images of individual layers.
Does not take ownership of the object.
Definition at line 54 of file qgsmaprendererjob.cpp.
References mCache.
Referenced by QgsMapCanvas::refreshMap(), and QgsMapRendererSequentialJob::start().
void QgsMapRendererJob::setRequestedGeometryCacheForLayers (const QStringList & layerIds) inline
Set which vector layers should be cached while rendering.
Note
The way how geometries are cached is really suboptimal - this method may be removed in future releases
Definition at line 124 of file qgsmaprendererjob.h.
Referenced by QgsMapCanvas::refreshMap().
virtual void QgsMapRendererJob::start () pure virtual
Start the rendering job and immediately return.
Does nothing if the rendering is already in progress.
Implemented in QgsMapRendererCustomPainterJob, QgsMapRendererSequentialJob, and QgsMapRendererParallelJob.
Referenced by QgsMapOverviewCanvas::refresh(), and QgsMapCanvas::refreshMap().
virtual QgsLabelingResults* QgsMapRendererJob::takeLabelingResults () pure virtual
Get pointer to internal labeling engine (in order to get access to the results)
Implemented in QgsMapRendererCustomPainterJob, QgsMapRendererSequentialJob, and QgsMapRendererParallelJob.
Referenced by QgsMapCanvas::rendererJobFinished().
void QgsMapRendererJob::updateLayerGeometryCaches () protected
called when rendering has finished to update all layers' geometry caches
Definition at line 327 of file qgsmaprenderercustompainterjob.cpp.
References QgsMapLayerRegistry::instance(), and mGeometryCaches.
Referenced by cleanupJobs().
virtual void QgsMapRendererJob::waitForFinished () pure virtual
Block until the job has finished.
Implemented in QgsMapRendererCustomPainterJob, QgsMapRendererSequentialJob, and QgsMapRendererParallelJob.
Member Data Documentation
QgsMapRendererCache* QgsMapRendererJob::mCache protected
Definition at line 164 of file qgsmaprendererjob.h.
Referenced by cleanupJobs(), prepareJobs(), QgsMapRendererSequentialJob::renderedImage(), setCache(), and QgsMapRendererSequentialJob::start().
Errors QgsMapRendererJob::mErrors protected
Definition at line 162 of file qgsmaprendererjob.h.
Referenced by cleanupJobs(), errors(), QgsMapRendererSequentialJob::internalFinished(), prepareJobs(), QgsMapRendererSequentialJob::start(), and QgsMapRendererCustomPainterJob::start().
QMap<QString, QgsGeometryCache> QgsMapRendererJob::mGeometryCaches protected
map of geometry caches
Definition at line 169 of file qgsmaprendererjob.h.
Referenced by prepareJobs(), and updateLayerGeometryCaches().
QTime QgsMapRendererJob::mRenderingStart protected
Definition at line 171 of file qgsmaprendererjob.h.
Referenced by QgsMapRendererCustomPainterJob::futureFinished(), QgsMapRendererSequentialJob::internalFinished(), QgsMapRendererParallelJob::renderingFinished(), QgsMapRendererParallelJob::start(), QgsMapRendererSequentialJob::start(), and QgsMapRendererCustomPainterJob::start().
int QgsMapRendererJob::mRenderingTime protected
Definition at line 172 of file qgsmaprendererjob.h.
Referenced by QgsMapRendererCustomPainterJob::futureFinished(), QgsMapRendererSequentialJob::internalFinished(), and QgsMapRendererParallelJob::renderingFinished().
QStringList QgsMapRendererJob::mRequestedGeomCacheForLayers protected
list of layer IDs for which the geometry cache should be updated
Definition at line 167 of file qgsmaprendererjob.h.
Referenced by prepareJobs().
QgsMapSettings QgsMapRendererJob::mSettings protected
Definition at line 161 of file qgsmaprendererjob.h.
Referenced by QgsMapRendererCustomPainterJob::doRender(), needTemporaryImage(), prepareJobs(), QgsMapRendererSequentialJob::QgsMapRendererSequentialJob(), QgsMapRendererParallelJob::renderedImage(), QgsMapRendererSequentialJob::renderedImage(), QgsMapRendererParallelJob::renderLayersFinished(), QgsMapRendererParallelJob::start(), QgsMapRendererSequentialJob::start(), and QgsMapRendererCustomPainterJob::start().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsmaprendererjob.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsmaprenderercustompainterjob.cpp
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsmaprendererjob.cpp