QGIS API Documentation: QgsRasterRendererWidget Class Reference
QgsRasterRendererWidget Class Reference abstract
#include <qgsrasterrendererwidget.h>
Public Types
enum LoadMinMaxAlgo { Estimate, Actual, CurrentExtent, CumulativeCut }
Public Member Functions
QgsRasterRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent)
virtual ~QgsRasterRendererWidget ()
virtual QgsRasterRenderer * renderer ()=0
void setRasterLayer (QgsRasterLayer *layer)
const QgsRasterLayer * rasterLayer () const
virtual QString min (int index=0)
virtual QString max (int index=0)
virtual void setMin (QString value, int index=0)
virtual void setMax (QString value, int index=0)
virtual QString stdDev ()
virtual void setStdDev (QString value)
virtual int selectedBand (int index=0)
Protected Member Functions
QString displayBandName (int band) const
Returns a band name for display.
Protected Attributes
QgsRasterLayer * mRasterLayer
QgsRectangle mExtent
Current extent.
Detailed Description
Definition at line 28 of file qgsrasterrendererwidget.h.
Member Enumeration Documentation
enum QgsRasterRendererWidget::LoadMinMaxAlgo
Enumerator
Estimate
Actual
CurrentExtent
CumulativeCut
Definition at line 38 of file qgsrasterrendererwidget.h.
Constructor & Destructor Documentation
QgsRasterRendererWidget::QgsRasterRendererWidget (QgsRasterLayer * layer, const QgsRectangle & extent) inline
Definition at line 31 of file qgsrasterrendererwidget.h.
virtual QgsRasterRendererWidget::~QgsRasterRendererWidget () inline virtual
Definition at line 36 of file qgsrasterrendererwidget.h.
Member Function Documentation
QString QgsRasterRendererWidget::displayBandName (int band) const protected
Returns a band name for display.
First choice is color name, otherwise band number
Definition at line 23 of file qgsrasterrendererwidget.cpp.
References QgsRasterDataProvider::colorInterpretationName(), QgsRasterLayer::dataProvider(), QgsRasterInterface::generateBandName(), and mRasterLayer.
Referenced by QgsMultiBandColorRendererWidget::QgsMultiBandColorRendererWidget(), QgsPalettedRendererWidget::QgsPalettedRendererWidget(), QgsSingleBandGrayRendererWidget::QgsSingleBandGrayRendererWidget(), and QgsSingleBandPseudoColorRendererWidget::QgsSingleBandPseudoColorRendererWidget().
virtual QString QgsRasterRendererWidget::max (int index = 0) inline virtual
Reimplemented in QgsMultiBandColorRendererWidget, and QgsSingleBandGrayRendererWidget.
Definition at line 52 of file qgsrasterrendererwidget.h.
References index.
Referenced by QgsSingleBandPseudoColorRendererWidget::on_mClassifyButton_clicked(), QgsRasterHistogramWidget::rendererMinMax(), and QgsSingleBandPseudoColorRendererWidget::resetClassifyButton().
virtual QString QgsRasterRendererWidget::min (int index = 0) inline virtual
Reimplemented in QgsMultiBandColorRendererWidget, and QgsSingleBandGrayRendererWidget.
Definition at line 51 of file qgsrasterrendererwidget.h.
References index.
Referenced by QgsSingleBandPseudoColorRendererWidget::on_mClassifyButton_clicked(), QgsRasterHistogramWidget::rendererMinMax(), and QgsSingleBandPseudoColorRendererWidget::resetClassifyButton().
const QgsRasterLayer* QgsRasterRendererWidget::rasterLayer () const inline
Definition at line 49 of file qgsrasterrendererwidget.h.
virtual QgsRasterRenderer* QgsRasterRendererWidget::renderer () pure virtual
Implemented in QgsSingleBandPseudoColorRendererWidget, QgsMultiBandColorRendererWidget, QgsPalettedRendererWidget, and QgsSingleBandGrayRendererWidget.
virtual int QgsRasterRendererWidget::selectedBand (int index = 0) inline virtual
Reimplemented in QgsMultiBandColorRendererWidget, and QgsSingleBandGrayRendererWidget.
Definition at line 57 of file qgsrasterrendererwidget.h.
References index.
Referenced by QgsRasterHistogramWidget::applyHistoMax(), QgsRasterHistogramWidget::applyHistoMin(), QgsRasterHistogramWidget::rendererMinMax(), and QgsRasterHistogramWidget::rendererSelectedBands().
virtual void QgsRasterRendererWidget::setMax (QString value, int index = 0) inline virtual
Reimplemented in QgsMultiBandColorRendererWidget, and QgsSingleBandGrayRendererWidget.
Definition at line 54 of file qgsrasterrendererwidget.h.
References index.
Referenced by QgsRasterHistogramWidget::applyHistoMax().
virtual void QgsRasterRendererWidget::setMin (QString value, int index = 0) inline virtual
Reimplemented in QgsMultiBandColorRendererWidget, and QgsSingleBandGrayRendererWidget.
Definition at line 53 of file qgsrasterrendererwidget.h.
References index.
Referenced by QgsRasterHistogramWidget::applyHistoMin().
void QgsRasterRendererWidget::setRasterLayer (QgsRasterLayer * layer) inline
Definition at line 48 of file qgsrasterrendererwidget.h.
virtual void QgsRasterRendererWidget::setStdDev (QString value) inline virtual
Definition at line 56 of file qgsrasterrendererwidget.h.
virtual QString QgsRasterRendererWidget::stdDev () inline virtual
Definition at line 55 of file qgsrasterrendererwidget.h.
Member Data Documentation
QgsRectangle QgsRasterRendererWidget::mExtent protected
Current extent.
Definition at line 65 of file qgsrasterrendererwidget.h.
QgsRasterLayer* QgsRasterRendererWidget::mRasterLayer protected
Definition at line 60 of file qgsrasterrendererwidget.h.
Referenced by displayBandName(), QgsSingleBandPseudoColorRendererWidget::on_mClassifyButton_clicked(), QgsSingleBandPseudoColorRendererWidget::on_mLoadFromBandButton_clicked(), QgsMultiBandColorRendererWidget::QgsMultiBandColorRendererWidget(), QgsPalettedRendererWidget::QgsPalettedRendererWidget(), QgsSingleBandGrayRendererWidget::QgsSingleBandGrayRendererWidget(), QgsSingleBandPseudoColorRendererWidget::QgsSingleBandPseudoColorRendererWidget(), QgsSingleBandGrayRendererWidget::renderer(), QgsPalettedRendererWidget::renderer(), QgsMultiBandColorRendererWidget::renderer(), QgsSingleBandPseudoColorRendererWidget::renderer(), and QgsPalettedRendererWidget::setFromRenderer().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/raster/qgsrasterrendererwidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/raster/qgsrasterrendererwidget.cpp