QGIS API Documentation: QgsSymbolLayerV2 Class Reference
QgsSymbolLayerV2 Class Reference abstract
#include <qgssymbollayerv2.h>
Public Member Functions
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString layerType () const =0
virtual void startRender (QgsSymbolV2RenderContext &context)=0
virtual void stopRender (QgsSymbolV2RenderContext &context)=0
virtual QgsSymbolLayerV2 * clone () const =0
virtual void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
virtual QgsStringMap properties () const =0
virtual void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)=0
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
virtual void setOutputUnit (QgsSymbolV2::OutputUnit unit)
virtual QgsSymbolV2::OutputUnit outputUnit () const
virtual void setMapUnitScale (const QgsMapUnitScale &scale)
virtual QgsMapUnitScale mapUnitScale () const
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
virtual Qt::PenStyle dxfPenStyle () const
Protected Member Functions
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsFields *fields, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Protected Attributes
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Static Protected Attributes
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 45 of file qgssymbollayerv2.h.
Constructor & Destructor Documentation
virtual QgsSymbolLayerV2::~QgsSymbolLayerV2 () inline virtual
Definition at line 65 of file qgssymbollayerv2.h.
QgsSymbolLayerV2::QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked = false) inline protected
Definition at line 133 of file qgssymbollayerv2.h.
Member Function Documentation
virtual QgsSymbolLayerV2* QgsSymbolLayerV2::clone () const pure virtual
Implemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsFontMarkerSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsVectorFieldSymbolLayer, QgsSimpleLineSymbolLayerV2, and QgsEllipseSymbolLayerV2.
virtual QColor QgsSymbolLayerV2::color (void) const inline virtual
Reimplemented in QgsLinePatternFillSymbolLayer.
Definition at line 50 of file qgssymbollayerv2.h.
Referenced by QgsGradientFillSymbolLayerV2::applyDataDefinedSymbology(), QgsGradientFillSymbolLayerV2::applyGradient(), QgsSimpleLineSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsSimpleFillSymbolLayerV2::create(), QgsGradientFillSymbolLayerV2::create(), QgsFontMarkerSymbolLayerV2::create(), QgsShapeburstFillSymbolLayerV2::create(), QgsSimpleLineSymbolLayerV2::createFromSld(), QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsSimpleFillSymbolLayerV2::createFromSld(), QgsFontMarkerSymbolLayerV2::createFromSld(), dxfColor(), QgsSimpleFillSymbolLayerV2::fillColor(), QgsSimpleMarkerSymbolLayerV2::fillColor(), QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2(), QgsGradientFillSymbolLayerV2::QgsGradientFillSymbolLayerV2(), QgsShapeburstFillSymbolLayerV2::QgsShapeburstFillSymbolLayerV2(), QgsSimpleFillSymbolLayerV2::QgsSimpleFillSymbolLayerV2(), QgsSimpleLineSymbolLayerV2::QgsSimpleLineSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::setBorderColor(), QgsMarkerLineSymbolLayerV2::setColor(), and QgsCentroidFillSymbolLayerV2::setColor().
void QgsSymbolLayerV2::copyDataDefinedProperties (QgsSymbolLayerV2 * destLayer) const protected
Copies data defined properties of this layer to another symbol layer.
Definition at line 177 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties, removeDataDefinedProperties(), and setDataDefinedProperty().
Referenced by QgsSimpleLineSymbolLayerV2::clone(), QgsSimpleFillSymbolLayerV2::clone(), QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsMarkerLineSymbolLayerV2::clone(), QgsGradientFillSymbolLayerV2::clone(), QgsShapeburstFillSymbolLayerV2::clone(), and QgsSVGFillSymbolLayer::clone().
const QgsExpression * QgsSymbolLayerV2::dataDefinedProperty (const QString & property) const virtual
Definition at line 29 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties.
Referenced by dataDefinedPropertyString(), QgsEllipseSymbolLayerV2::hasDataDefinedProperty(), QgsSimpleMarkerSymbolLayerV2::startRender(), and QgsEllipseSymbolLayerV2::writeSldMarker().
QString QgsSymbolLayerV2::dataDefinedPropertyString (const QString & property) const virtual
Definition at line 49 of file qgssymbollayerv2.cpp.
References dataDefinedProperty(), and QgsExpression::expression().
virtual void QgsSymbolLayerV2::drawPreviewIcon (QgsSymbolV2RenderContext & context, QSize size) pure virtual
Implemented in QgsFillSymbolLayerV2, QgsLineSymbolLayerV2, QgsMarkerSymbolLayerV2, and QgsVectorFieldSymbolLayer.
Referenced by QgsSymbolLayerV2Utils::symbolLayerPreviewIcon().
QColor QgsSymbolLayerV2::dxfColor (const QgsSymbolV2RenderContext & context) const virtual
Reimplemented in QgsImageFillSymbolLayer, QgsSimpleFillSymbolLayerV2, and QgsSimpleLineSymbolLayerV2.
Definition at line 104 of file qgssymbollayerv2.cpp.
References color().
QVector< qreal > QgsSymbolLayerV2::dxfCustomDashPattern (QgsSymbolV2::OutputUnit & unit) const virtual
Reimplemented in QgsSimpleLineSymbolLayerV2.
Definition at line 110 of file qgssymbollayerv2.cpp.
Qt::PenStyle QgsSymbolLayerV2::dxfPenStyle () const virtual
Reimplemented in QgsImageFillSymbolLayer, QgsSimpleFillSymbolLayerV2, and QgsSimpleLineSymbolLayerV2.
Definition at line 116 of file qgssymbollayerv2.cpp.
double QgsSymbolLayerV2::dxfWidth (const QgsDxfExport & e, const QgsSymbolV2RenderContext & context) const virtual
Reimplemented in QgsImageFillSymbolLayer, QgsLineSymbolLayerV2, QgsSimpleFillSymbolLayerV2, and QgsSimpleLineSymbolLayerV2.
Definition at line 97 of file qgssymbollayerv2.cpp.
virtual double QgsSymbolLayerV2::estimateMaxBleed () const inline virtual
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
Eg, polygons drawn with an outline will draw half the width of the outline outside of the polygon. This amount is estimated, since it may be affected by data defined symbology rules.
Reimplemented in QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsImageFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsSimpleFillSymbolLayerV2, and QgsSimpleLineSymbolLayerV2.
Definition at line 96 of file qgssymbollayerv2.h.
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsImageFillSymbolLayer::estimateMaxBleed(), and QgsSymbolLayerV2Utils::estimateMaxSymbolBleed().
QgsExpression * QgsSymbolLayerV2::expression (const QString & property) const protected virtual
Definition at line 39 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties.
Referenced by QgsSVGFillSymbolLayer::applyDataDefinedSettings(), QgsLinePatternFillSymbolLayer::applyDataDefinedSettings(), QgsPointPatternFillSymbolLayer::applyDataDefinedSettings(), QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleFillSymbolLayerV2::applyDataDefinedSymbology(), QgsGradientFillSymbolLayerV2::applyDataDefinedSymbology(), QgsShapeburstFillSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleLineSymbolLayerV2::dxfColor(), QgsSimpleFillSymbolLayerV2::dxfColor(), QgsSimpleLineSymbolLayerV2::dxfWidth(), QgsSimpleFillSymbolLayerV2::dxfWidth(), QgsImageFillSymbolLayer::dxfWidth(), QgsEllipseSymbolLayerV2::preparePath(), QgsEllipseSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsMarkerLineSymbolLayerV2::renderPolyline(), QgsMarkerLineSymbolLayerV2::renderPolylineInterval(), QgsMarkerLineSymbolLayerV2::renderPolylineVertex(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsMarkerSymbolLayerV2::startRender(), QgsEllipseSymbolLayerV2::writeDxf(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), and QgsSvgMarkerSymbolLayerV2::writeDxf().
virtual QColor QgsSymbolLayerV2::fillColor () const inline virtual
Get fill color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented in QgsSvgMarkerSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Definition at line 63 of file qgssymbollayerv2.h.
Referenced by QgsGradientFillSymbolLayerV2::applyGradient(), QgsSVGFillSymbolLayer::createFromSld(), and QgsLinePatternFillSymbolLayer::createFromSld().
bool QgsSymbolLayerV2::hasDataDefinedProperties () const inline
Definition at line 116 of file qgssymbollayerv2.h.
bool QgsSymbolLayerV2::isLocked () const inline
Definition at line 90 of file qgssymbollayerv2.h.
Referenced by QgsSymbolLayerV2Utils::saveSymbol().
virtual QString QgsSymbolLayerV2::layerType () const pure virtual
Implemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsFontMarkerSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsVectorFieldSymbolLayer, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsSimpleLineSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Referenced by QgsSymbolLayerV2Utils::createSymbolLayerV2ListFromSld(), QgsSymbolLayerV2Utils::saveSymbol(), QgsMarkerLineSymbolLayerV2::toSld(), QgsPointPatternFillSymbolLayer::toSld(), and QgsMarkerSymbolLayerV2::writeSldMarker().
virtual QgsMapUnitScale QgsSymbolLayerV2::mapUnitScale () const inline virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsImageFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsLineSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsEllipseSymbolLayerV2, QgsVectorFieldSymbolLayer, and QgsSimpleLineSymbolLayerV2.
Definition at line 102 of file qgssymbollayerv2.h.
virtual QString QgsSymbolLayerV2::ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const inline virtual
Reimplemented in QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, and QgsSimpleLineSymbolLayerV2.
Definition at line 77 of file qgssymbollayerv2.h.
virtual QColor QgsSymbolLayerV2::outlineColor () const inline virtual
Get outline color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented in QgsSvgMarkerSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Definition at line 57 of file qgssymbollayerv2.h.
virtual QgsSymbolV2::OutputUnit QgsSymbolLayerV2::outputUnit () const inline virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsImageFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsLineSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsEllipseSymbolLayerV2, QgsVectorFieldSymbolLayer, and QgsSimpleLineSymbolLayerV2.
Definition at line 99 of file qgssymbollayerv2.h.
References QgsSymbolV2::Mixed.
void QgsSymbolLayerV2::prepareExpressions (const QgsFields * fields, double scale = -1.0) protected virtual
Definition at line 121 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties.
Referenced by QgsEllipseSymbolLayerV2::startRender(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsSvgMarkerSymbolLayerV2::startRender(), QgsMarkerLineSymbolLayerV2::startRender(), QgsGradientFillSymbolLayerV2::startRender(), QgsShapeburstFillSymbolLayerV2::startRender(), QgsSVGFillSymbolLayer::startRender(), QgsLinePatternFillSymbolLayer::startRender(), and QgsPointPatternFillSymbolLayer::startRender().
virtual QgsStringMap QgsSymbolLayerV2::properties () const pure virtual
Implemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsFontMarkerSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsVectorFieldSymbolLayer, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsSimpleLineSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Referenced by QgsSymbolLayerV2Utils::saveSymbol().
void QgsSymbolLayerV2::removeDataDefinedProperties () virtual
Definition at line 71 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties.
Referenced by copyDataDefinedProperties().
void QgsSymbolLayerV2::removeDataDefinedProperty (const QString & property) virtual
Definition at line 61 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties.
Referenced by setDataDefinedProperty(), and QgsHighlight::setSymbol().
int QgsSymbolLayerV2::renderingPass () const inline
Definition at line 106 of file qgssymbollayerv2.h.
Referenced by QgsVectorLayerRenderer::drawRendererV2Levels(), QgsVectorFileWriter::exportFeaturesSymbolLevels(), QgsSymbolLayerV2Utils::saveSymbol(), and QgsRuleBasedRendererV2::stopRender().
void QgsSymbolLayerV2::saveDataDefinedProperties (QgsStringMap & stringMap) const protected
Saves data defined properties to string map.
Definition at line 165 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties.
Referenced by QgsEllipseSymbolLayerV2::properties(), QgsSimpleLineSymbolLayerV2::properties(), QgsSimpleFillSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsMarkerLineSymbolLayerV2::properties(), QgsGradientFillSymbolLayerV2::properties(), QgsShapeburstFillSymbolLayerV2::properties(), QgsSVGFillSymbolLayer::properties(), QgsLinePatternFillSymbolLayer::properties(), and QgsPointPatternFillSymbolLayer::properties().
virtual void QgsSymbolLayerV2::setColor (const QColor & color) inline virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsLinePatternFillSymbolLayer, and QgsMarkerLineSymbolLayerV2.
Definition at line 51 of file qgssymbollayerv2.h.
Referenced by QgsSimpleFillSymbolLayerV2::setFillColor(), QgsSimpleMarkerSymbolLayerV2::setFillColor(), and QgsHighlight::setSymbol().
void QgsSymbolLayerV2::setDataDefinedProperty (const QString & property, const QString & expressionString) virtual
Definition at line 55 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties, and removeDataDefinedProperty().
Referenced by copyDataDefinedProperties(), QgsEllipseSymbolLayerV2::create(), QgsSimpleLineSymbolLayerV2::create(), QgsSimpleFillSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsSvgMarkerSymbolLayerV2::create(), QgsMarkerLineSymbolLayerV2::create(), QgsGradientFillSymbolLayerV2::create(), QgsShapeburstFillSymbolLayerV2::create(), QgsSVGFillSymbolLayer::create(), QgsLinePatternFillSymbolLayer::create(), and QgsPointPatternFillSymbolLayer::create().
virtual void QgsSymbolLayerV2::setFillColor (const QColor & color) inline virtual
Set fill color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented in QgsSvgMarkerSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Definition at line 60 of file qgssymbollayerv2.h.
Referenced by QgsHighlight::setSymbol().
void QgsSymbolLayerV2::setLocked (bool locked) inline
Definition at line 89 of file qgssymbollayerv2.h.
Referenced by QgsSymbolV2::cloneLayers(), and QgsSymbolLayerV2Utils::loadSymbolLayer().
virtual void QgsSymbolLayerV2::setMapUnitScale (const QgsMapUnitScale & scale) inline virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsImageFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsLineSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsEllipseSymbolLayerV2, QgsVectorFieldSymbolLayer, and QgsSimpleLineSymbolLayerV2.
Definition at line 101 of file qgssymbollayerv2.h.
virtual void QgsSymbolLayerV2::setOutlineColor (const QColor & color) inline virtual
Set outline color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented in QgsSvgMarkerSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Definition at line 54 of file qgssymbollayerv2.h.
Referenced by QgsHighlight::setSymbol().
virtual void QgsSymbolLayerV2::setOutputUnit (QgsSymbolV2::OutputUnit unit) inline virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsImageFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsLineSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsEllipseSymbolLayerV2, QgsVectorFieldSymbolLayer, and QgsSimpleLineSymbolLayerV2.
Definition at line 98 of file qgssymbollayerv2.h.
void QgsSymbolLayerV2::setRenderingPass (int renderingPass) inline
Definition at line 105 of file qgssymbollayerv2.h.
Referenced by QgsSymbolV2::cloneLayers(), and QgsSymbolLayerV2Utils::loadSymbolLayer().
virtual bool QgsSymbolLayerV2::setSubSymbol (QgsSymbolV2 * symbol) inline virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsImageFillSymbolLayer, QgsMarkerLineSymbolLayerV2, and QgsVectorFieldSymbolLayer.
Definition at line 85 of file qgssymbollayerv2.h.
Referenced by QgsVectorFieldSymbolLayer::clone(), QgsSymbolLayerV2Utils::loadSymbol(), and QgsSymbolLayerV2Utils::loadSymbols().
virtual void QgsSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) pure virtual
Implemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsFontMarkerSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsVectorFieldSymbolLayer, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsSimpleLineSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Referenced by QgsSymbolV2::drawPreviewIcon(), QgsLineSymbolLayerV2::drawPreviewIcon(), and QgsFillSymbolLayerV2::drawPreviewIcon().
virtual void QgsSymbolLayerV2::stopRender (QgsSymbolV2RenderContext & context) pure virtual
Implemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsFontMarkerSymbolLayerV2, QgsGradientFillSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsVectorFieldSymbolLayer, QgsSimpleFillSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsSimpleLineSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Referenced by QgsSymbolV2::drawPreviewIcon(), QgsMarkerSymbolLayerV2::drawPreviewIcon(), QgsLineSymbolLayerV2::drawPreviewIcon(), and QgsFillSymbolLayerV2::drawPreviewIcon().
virtual QgsSymbolV2* QgsSymbolLayerV2::subSymbol () inline virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsImageFillSymbolLayer, QgsMarkerLineSymbolLayerV2, and QgsVectorFieldSymbolLayer.
Definition at line 83 of file qgssymbollayerv2.h.
Referenced by QgsSymbolLayerV2Utils::saveSymbol(), and QgsHighlight::setSymbol().
virtual void QgsSymbolLayerV2::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const inline virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, QgsSVGFillSymbolLayer, QgsMarkerSymbolLayerV2, QgsMarkerLineSymbolLayerV2, QgsVectorFieldSymbolLayer, QgsSimpleFillSymbolLayerV2, QgsSimpleLineSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Definition at line 74 of file qgssymbollayerv2.h.
QgsSymbolV2::SymbolType QgsSymbolLayerV2::type () const inline
Definition at line 87 of file qgssymbollayerv2.h.
Referenced by QgsSymbolV2::appendSymbolLayer(), QgsSymbolV2::changeSymbolLayer(), QgsGradientFillSymbolLayerV2::create(), QgsSymbolV2::insertSymbolLayer(), and QgsVectorFieldSymbolLayer::setVectorFieldType().
QSet< QString > QgsSymbolLayerV2::usedAttributes () const virtual
Reimplemented in QgsCentroidFillSymbolLayerV2, QgsPointPatternFillSymbolLayer, and QgsVectorFieldSymbolLayer.
Definition at line 142 of file qgssymbollayerv2.cpp.
References mDataDefinedProperties.
Referenced by QgsPointPatternFillSymbolLayer::usedAttributes(), and QgsCentroidFillSymbolLayerV2::usedAttributes().
bool QgsSymbolLayerV2::writeDxf (QgsDxfExport & e, double mmMapUnitScaleFactor, const QString & layerName, const QgsSymbolV2RenderContext * context, const QgsFeature * f, const QPointF & shift = QPointF(0.0, 0.0)) const virtual
Reimplemented in QgsSvgMarkerSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Definition at line 81 of file qgssymbollayerv2.cpp.
Member Data Documentation
QColor QgsSymbolLayerV2::mColor protected
Definition at line 138 of file qgssymbollayerv2.h.
Referenced by QgsGradientFillSymbolLayerV2::applyDataDefinedSymbology(), QgsShapeburstFillSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleLineSymbolLayerV2::clone(), QgsSimpleFillSymbolLayerV2::clone(), QgsSimpleMarkerSymbolLayerV2::clone(), QgsGradientFillSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsShapeburstFillSymbolLayerV2::clone(), QgsCentroidFillSymbolLayerV2::clone(), QgsLinePatternFillSymbolLayer::color(), QgsSimpleLineSymbolLayerV2::dxfColor(), QgsSimpleMarkerSymbolLayerV2::ogrFeatureStyle(), QgsSimpleFillSymbolLayerV2::ogrFeatureStyle(), QgsSimpleLineSymbolLayerV2::properties(), QgsSimpleFillSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsGradientFillSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsShapeburstFillSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2(), QgsGradientFillSymbolLayerV2::QgsGradientFillSymbolLayerV2(), QgsShapeburstFillSymbolLayerV2::QgsShapeburstFillSymbolLayerV2(), QgsSimpleFillSymbolLayerV2::QgsSimpleFillSymbolLayerV2(), QgsSimpleLineSymbolLayerV2::QgsSimpleLineSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsMarkerLineSymbolLayerV2::setColor(), QgsCentroidFillSymbolLayerV2::setColor(), QgsMarkerLineSymbolLayerV2::setSubSymbol(), QgsCentroidFillSymbolLayerV2::setSubSymbol(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsSimpleLineSymbolLayerV2::toSld(), QgsSimpleFillSymbolLayerV2::toSld(), QgsSimpleMarkerSymbolLayerV2::writeSldMarker(), and QgsFontMarkerSymbolLayerV2::writeSldMarker().
QMap< QString, QgsExpression* > QgsSymbolLayerV2::mDataDefinedProperties protected
Definition at line 141 of file qgssymbollayerv2.h.
Referenced by copyDataDefinedProperties(), dataDefinedProperty(), expression(), prepareExpressions(), removeDataDefinedProperties(), removeDataDefinedProperty(), saveDataDefinedProperties(), setDataDefinedProperty(), and usedAttributes().
bool QgsSymbolLayerV2::mLocked protected
Definition at line 137 of file qgssymbollayerv2.h.
int QgsSymbolLayerV2::mRenderingPass protected
Definition at line 139 of file qgssymbollayerv2.h.
QgsSymbolV2::SymbolType QgsSymbolLayerV2::mType protected
Definition at line 136 of file qgssymbollayerv2.h.
const bool QgsSymbolLayerV2::selectFillBorder = false static protected
Definition at line 145 of file qgssymbollayerv2.h.
Referenced by QgsImageFillSymbolLayer::renderPolygon().
const bool QgsSymbolLayerV2::selectFillStyle = false static protected
Definition at line 146 of file qgssymbollayerv2.h.
Referenced by QgsSimpleFillSymbolLayerV2::startRender().
const bool QgsSymbolLayerV2::selectionIsOpaque = true static protected
Definition at line 144 of file qgssymbollayerv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsGradientFillSymbolLayerV2::startRender(), and QgsShapeburstFillSymbolLayerV2::startRender().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2.cpp