QGIS API Documentation: QgsComposerItemCommand Class Reference
QgsComposerItemCommand Class Reference
Undo command to undo/redo all composer item related changes.
#include <qgscomposeritemcommand.h>
Public Member Functions
QgsComposerItemCommand (QgsComposerItem *item, const QString &text, QUndoCommand *parent=0)
virtual ~QgsComposerItemCommand ()
void undo ()
Reverses the command.
void redo ()
Replays the command.
void savePreviousState ()
Saves current item state as previous state.
void saveAfterState ()
Saves current item state as after state.
QDomDocument previousState () const
QDomDocument afterState () const
bool containsChange () const
Returns true if previous state and after state are valid and different.
const QgsComposerItem * item () const
Protected Member Functions
void saveState (QDomDocument &stateDoc) const
void restoreState (QDomDocument &stateDoc) const
Protected Attributes
QgsComposerItem * mItem
Target item of the command.
QDomDocument mPreviousState
XML that saves the state before executing the command.
QDomDocument mAfterState
XML containing the state after executing the command.
bool mFirstRun
Flag to prevent the first redo() if the command is pushed to the undo stack.
Detailed Description
Undo command to undo/redo all composer item related changes.
Definition at line 27 of file qgscomposeritemcommand.h.
Constructor & Destructor Documentation
QgsComposerItemCommand::QgsComposerItemCommand (QgsComposerItem * item, const QString & text, QUndoCommand * parent = 0)
Definition at line 22 of file qgscomposeritemcommand.cpp.
QgsComposerItemCommand::~QgsComposerItemCommand () virtual
Definition at line 27 of file qgscomposeritemcommand.cpp.
Member Function Documentation
QDomDocument QgsComposerItemCommand::afterState () const inline
Definition at line 44 of file qgscomposeritemcommand.h.
Referenced by QgsComposerMergeCommand::mergeWith().
bool QgsComposerItemCommand::containsChange () const
Returns true if previous state and after state are valid and different.
Definition at line 46 of file qgscomposeritemcommand.cpp.
References mAfterState, and mPreviousState.
Referenced by QgsComposition::endCommand().
const QgsComposerItem* QgsComposerItemCommand::item () const inline
Definition at line 49 of file qgscomposeritemcommand.h.
Referenced by QgsComposerMergeCommand::mergeWith().
QDomDocument QgsComposerItemCommand::previousState () const inline
Definition at line 43 of file qgscomposeritemcommand.h.
void QgsComposerItemCommand::redo ()
Replays the command.
Definition at line 36 of file qgscomposeritemcommand.cpp.
References mAfterState, mFirstRun, and restoreState().
void QgsComposerItemCommand::restoreState (QDomDocument & stateDoc) const protected
Definition at line 72 of file qgscomposeritemcommand.cpp.
References QgsProject::dirty(), QgsProject::instance(), mItem, QgsComposerItem::readXML(), and QgsComposerItem::repaint().
Referenced by redo(), and undo().
void QgsComposerItemCommand::saveAfterState ()
Saves current item state as after state.
Definition at line 56 of file qgscomposeritemcommand.cpp.
References mAfterState, and saveState().
Referenced by QgsComposition::alignSelectedItemsBottom(), QgsComposition::alignSelectedItemsHCenter(), QgsComposition::alignSelectedItemsLeft(), QgsComposition::alignSelectedItemsRight(), QgsComposition::alignSelectedItemsTop(), QgsComposition::alignSelectedItemsVCenter(), QgsComposition::endCommand(), QgsComposition::lockSelectedItems(), QgsComposerMouseHandles::mouseReleaseEvent(), QgsComposition::unlockAllItems(), and QgsComposition::updateZValues().
void QgsComposerItemCommand::savePreviousState ()
Saves current item state as previous state.
Definition at line 51 of file qgscomposeritemcommand.cpp.
References mPreviousState, and saveState().
Referenced by QgsComposition::alignSelectedItemsBottom(), QgsComposition::alignSelectedItemsHCenter(), QgsComposition::alignSelectedItemsLeft(), QgsComposition::alignSelectedItemsRight(), QgsComposition::alignSelectedItemsTop(), QgsComposition::alignSelectedItemsVCenter(), QgsComposition::beginCommand(), QgsComposition::lockSelectedItems(), QgsComposerMouseHandles::mouseReleaseEvent(), QgsComposition::unlockAllItems(), and QgsComposition::updateZValues().
void QgsComposerItemCommand::saveState (QDomDocument & stateDoc) const protected
Definition at line 61 of file qgscomposeritemcommand.cpp.
References mItem, and QgsComposerItem::writeXML().
Referenced by saveAfterState(), and savePreviousState().
void QgsComposerItemCommand::undo ()
Reverses the command.
Definition at line 31 of file qgscomposeritemcommand.cpp.
References mPreviousState, and restoreState().
Member Data Documentation
QDomDocument QgsComposerItemCommand::mAfterState protected
XML containing the state after executing the command.
Definition at line 57 of file qgscomposeritemcommand.h.
Referenced by containsChange(), QgsComposerMergeCommand::mergeWith(), redo(), and saveAfterState().
bool QgsComposerItemCommand::mFirstRun protected
Flag to prevent the first redo() if the command is pushed to the undo stack.
Definition at line 60 of file qgscomposeritemcommand.h.
Referenced by redo().
QgsComposerItem* QgsComposerItemCommand::mItem protected
Target item of the command.
Definition at line 53 of file qgscomposeritemcommand.h.
Referenced by QgsComposerMergeCommand::mergeWith(), restoreState(), and saveState().
QDomDocument QgsComposerItemCommand::mPreviousState protected
XML that saves the state before executing the command.
Definition at line 55 of file qgscomposeritemcommand.h.
Referenced by containsChange(), savePreviousState(), and undo().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposeritemcommand.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposeritemcommand.cpp