QGIS API Documentation: QgsOptionsDialogBase Class Reference
QgsOptionsDialogBase Class Reference
QGIS gui library.
A base dialog for options and properties dialogs that offers vertical tabs.
#include <qgsoptionsdialogbase.h>
Public Member Functions
QgsOptionsDialogBase (QString settingsKey, QWidget *parent=0, Qt::WindowFlags fl=0, QSettings *settings=0)
Constructor.
~QgsOptionsDialogBase ()
void initOptionsBase (bool restoreUi=true, QString title=QString())
Set up the base ui connections for vertical tabs.
void setSettings (QSettings *settings)
void restoreOptionsBaseUi (QString title=QString())
Restore the base ui.
bool iconOnly ()
determine if the options list is in icon only mode
Protected Slots
void updateOptionsListVerticalTabs ()
void optionsStackedWidget_CurrentChanged (int indx)
void optionsStackedWidget_WidgetRemoved (int indx)
void warnAboutMissingObjects ()
Protected Member Functions
void showEvent (QShowEvent *e)
void paintEvent (QPaintEvent *e)
virtual void updateWindowTitle ()
Protected Attributes
QString mOptsKey
bool mInit
QListWidget * mOptListWidget
QStackedWidget * mOptStackedWidget
QSplitter * mOptSplitter
QDialogButtonBox * mOptButtonBox
QString mDialogTitle
bool mIconOnly
QPointer< QSettings > mSettings
bool mDelSettings
Detailed Description
A base dialog for options and properties dialogs that offers vertical tabs.
It handles saving/restoring of geometry, splitter and current tab states, switching vertical tabs between icon/text to icon-only modes (splitter collapsed to left), and connecting QDialogButtonBox's accepted/rejected signals to dialog's accept/reject slots
To use: 1) Start with copy of qgsoptionsdialog_template.ui and build options/properties dialog. 2) In source file for dialog, inherit this class instead of QDialog, then in constructor: ... setupUi(this); // set up .ui file objects initOptionsBase(false); // set up this class to use .ui objects, optionally restoring base ui ... restoreOptionsBaseUi(); // restore the base ui with initOptionsBase or use this later on
Note
added in 1.9
Definition at line 49 of file qgsoptionsdialogbase.h.
Constructor & Destructor Documentation
QgsOptionsDialogBase::QgsOptionsDialogBase (QString settingsKey, QWidget * parent = 0, Qt::WindowFlags fl = 0, QSettings * settings = 0)
Constructor.
Parameters
settingsKey QSettings subgroup key for saving/restore ui states, e.g. "ProjectProperties".
parent parent object (owner)
fl widget flags
settings custom QSettings pointer
Definition at line 30 of file qgsoptionsdialogbase.cpp.
QgsOptionsDialogBase::~QgsOptionsDialogBase ()
Definition at line 39 of file qgsoptionsdialogbase.cpp.
References mDelSettings, mInit, mOptsKey, mOptSplitter, mOptStackedWidget, and mSettings.
Member Function Documentation
bool QgsOptionsDialogBase::iconOnly () inline
determine if the options list is in icon only mode
Definition at line 80 of file qgsoptionsdialogbase.h.
void QgsOptionsDialogBase::initOptionsBase (bool restoreUi = true, QString title = QString())
Set up the base ui connections for vertical tabs.
Parameters
restoreUi Whether to restore the base ui at this time.
title the window title
Definition at line 56 of file qgsoptionsdialogbase.cpp.
References mDelSettings, mDialogTitle, mInit, mOptButtonBox, mOptListWidget, mOptSplitter, mOptStackedWidget, mSettings, optionsStackedWidget_CurrentChanged(), optionsStackedWidget_WidgetRemoved(), restoreOptionsBaseUi(), size, and updateOptionsListVerticalTabs().
void QgsOptionsDialogBase::optionsStackedWidget_CurrentChanged (int indx) protected slot
Definition at line 265 of file qgsoptionsdialogbase.cpp.
References mOptListWidget, and updateWindowTitle().
Referenced by initOptionsBase(), and showEvent().
void QgsOptionsDialogBase::optionsStackedWidget_WidgetRemoved (int indx) protected slot
Definition at line 274 of file qgsoptionsdialogbase.cpp.
References mOptListWidget.
Referenced by initOptionsBase().
void QgsOptionsDialogBase::paintEvent (QPaintEvent * e) protected
Definition at line 208 of file qgsoptionsdialogbase.cpp.
References mInit, and updateOptionsListVerticalTabs().
void QgsOptionsDialogBase::restoreOptionsBaseUi (QString title = QString())
Restore the base ui.
Sometimes useful to do at end of subclass's constructor.
Parameters
title the window title (it does not need to be defined if previously given to initOptionsBase();
Definition at line 144 of file qgsoptionsdialogbase.cpp.
References mDialogTitle, mInit, mOptListWidget, mOptsKey, mOptSplitter, mOptStackedWidget, mSettings, and updateWindowTitle().
Referenced by initOptionsBase().
void QgsOptionsDialogBase::setSettings (QSettings * settings)
Definition at line 133 of file qgsoptionsdialogbase.cpp.
References mDelSettings, and mSettings.
void QgsOptionsDialogBase::showEvent (QShowEvent * e) protected
Definition at line 193 of file qgsoptionsdialogbase.cpp.
References mInit, mOptListWidget, optionsStackedWidget_CurrentChanged(), updateOptionsListVerticalTabs(), and warnAboutMissingObjects().
void QgsOptionsDialogBase::updateOptionsListVerticalTabs () protected slot
Definition at line 229 of file qgsoptionsdialogbase.cpp.
References mIconOnly, mInit, mOptListWidget, and mOptSplitter.
Referenced by initOptionsBase(), paintEvent(), and showEvent().
void QgsOptionsDialogBase::updateWindowTitle () protected virtual
Definition at line 216 of file qgsoptionsdialogbase.cpp.
References mDialogTitle, and mOptListWidget.
Referenced by optionsStackedWidget_CurrentChanged(), and restoreOptionsBaseUi().
void QgsOptionsDialogBase::warnAboutMissingObjects () protected slot
Definition at line 280 of file qgsoptionsdialogbase.cpp.
References tr.
Referenced by showEvent().
Member Data Documentation
bool QgsOptionsDialogBase::mDelSettings protected
Definition at line 105 of file qgsoptionsdialogbase.h.
Referenced by initOptionsBase(), setSettings(), and ~QgsOptionsDialogBase().
QString QgsOptionsDialogBase::mDialogTitle protected
Definition at line 100 of file qgsoptionsdialogbase.h.
Referenced by initOptionsBase(), restoreOptionsBaseUi(), and updateWindowTitle().
bool QgsOptionsDialogBase::mIconOnly protected
Definition at line 101 of file qgsoptionsdialogbase.h.
Referenced by updateOptionsListVerticalTabs().
bool QgsOptionsDialogBase::mInit protected
Definition at line 95 of file qgsoptionsdialogbase.h.
Referenced by initOptionsBase(), paintEvent(), restoreOptionsBaseUi(), showEvent(), updateOptionsListVerticalTabs(), and ~QgsOptionsDialogBase().
QDialogButtonBox* QgsOptionsDialogBase::mOptButtonBox protected
Definition at line 99 of file qgsoptionsdialogbase.h.
Referenced by initOptionsBase().
QListWidget* QgsOptionsDialogBase::mOptListWidget protected
Definition at line 96 of file qgsoptionsdialogbase.h.
Referenced by initOptionsBase(), optionsStackedWidget_CurrentChanged(), optionsStackedWidget_WidgetRemoved(), restoreOptionsBaseUi(), showEvent(), updateOptionsListVerticalTabs(), and updateWindowTitle().
QString QgsOptionsDialogBase::mOptsKey protected
Definition at line 94 of file qgsoptionsdialogbase.h.
Referenced by restoreOptionsBaseUi(), and ~QgsOptionsDialogBase().
QSplitter* QgsOptionsDialogBase::mOptSplitter protected
Definition at line 98 of file qgsoptionsdialogbase.h.
Referenced by initOptionsBase(), restoreOptionsBaseUi(), updateOptionsListVerticalTabs(), and ~QgsOptionsDialogBase().
QStackedWidget* QgsOptionsDialogBase::mOptStackedWidget protected
Definition at line 97 of file qgsoptionsdialogbase.h.
Referenced by initOptionsBase(), restoreOptionsBaseUi(), and ~QgsOptionsDialogBase().
QPointer<QSettings> QgsOptionsDialogBase::mSettings protected
Definition at line 104 of file qgsoptionsdialogbase.h.
Referenced by initOptionsBase(), restoreOptionsBaseUi(), setSettings(), and ~QgsOptionsDialogBase().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsoptionsdialogbase.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsoptionsdialogbase.cpp