QGIS API Documentation: QgsPalGeometry Class Reference
QgsPalGeometry Class Reference
#include <qgspalgeometry.h>
Public Member Functions
QgsPalGeometry (QgsFeatureId id, QString text, GEOSGeometry *g, qreal ltrSpacing=0.0, qreal wordSpacing=0.0, bool curvedLabeling=false)
~QgsPalGeometry ()
const GEOSGeometry * getGeosGeometry ()
void releaseGeosGeometry (const GEOSGeometry *)
const char * strId ()
QString text ()
pal::LabelInfo * info (QFontMetricsF *fm, const QgsMapToPixel *xform, double fontScale, double maxinangle, double maxoutangle)
const QMap
< QgsPalLayerSettings::DataDefinedProperties,
QVariant > & dataDefinedValues () const
void addDataDefinedValue (QgsPalLayerSettings::DataDefinedProperties p, QVariant v)
void setIsDiagram (bool d)
bool isDiagram () const
void setIsPinned (bool f)
bool isPinned () const
void setDefinedFont (QFont f)
QFont definedFont ()
QFontMetricsF * getLabelFontMetrics ()
void setDiagramAttributes (const QgsAttributes &attrs)
const QgsAttributes & diagramAttributes ()
void feature (QgsFeature &feature)
Protected Attributes
GEOSGeometry * mG
QString mText
QByteArray mStrId
QgsFeatureId mId
LabelInfo * mInfo
bool mIsDiagram
bool mIsPinned
QFont mDefinedFont
QFontMetricsF * mFontMetrics
qreal mLetterSpacing
qreal mWordSpacing
bool mCurvedLabeling
QMap
< QgsPalLayerSettings::DataDefinedProperties,
QVariant > mDataDefinedValues
Stores attribute values for data defined properties.
QgsAttributes mDiagramAttributes
Stores attribute values for diagram rendering.
Detailed Description
Definition at line 9 of file qgspalgeometry.h.
Constructor & Destructor Documentation
QgsPalGeometry::QgsPalGeometry (QgsFeatureId id, QString text, GEOSGeometry * g, qreal ltrSpacing = 0.0, qreal wordSpacing = 0.0, bool curvedLabeling = false) inline
Definition at line 12 of file qgspalgeometry.h.
References FID_TO_STRING.
QgsPalGeometry::~QgsPalGeometry () inline
Definition at line 29 of file qgspalgeometry.h.
Member Function Documentation
void QgsPalGeometry::addDataDefinedValue (QgsPalLayerSettings::DataDefinedProperties p, QVariant v) inline
Definition at line 108 of file qgspalgeometry.h.
Referenced by QgsPalLayerSettings::registerFeature().
const QMap< QgsPalLayerSettings::DataDefinedProperties, QVariant >& QgsPalGeometry::dataDefinedValues () const inline
Definition at line 107 of file qgspalgeometry.h.
Referenced by QgsPalLabeling::drawLabeling().
QFont QgsPalGeometry::definedFont () inline
Definition at line 117 of file qgspalgeometry.h.
Referenced by QgsPalLabeling::drawLabeling().
const QgsAttributes& QgsPalGeometry::diagramAttributes () inline
Definition at line 122 of file qgspalgeometry.h.
void QgsPalGeometry::feature (QgsFeature & feature) inline
Definition at line 124 of file qgspalgeometry.h.
References QgsFeature::setAttributes(), QgsFeature::setFeatureId(), and QgsFeature::setValid().
Referenced by QgsPalLabeling::drawLabeling().
const GEOSGeometry* QgsPalGeometry::getGeosGeometry () inline
Definition at line 39 of file qgspalgeometry.h.
QFontMetricsF* QgsPalGeometry::getLabelFontMetrics () inline
Definition at line 119 of file qgspalgeometry.h.
pal::LabelInfo* QgsPalGeometry::info (QFontMetricsF * fm, const QgsMapToPixel * xform, double fontScale, double maxinangle, double maxoutangle) inline
Definition at line 51 of file qgspalgeometry.h.
References QgsMapToPixel::toMapCoordinates(), QgsMapToPixel::toMapCoordinatesF(), QgsPoint::x(), and QgsPoint::y().
Referenced by QgsPalLayerSettings::registerFeature().
bool QgsPalGeometry::isDiagram () const inline
Definition at line 111 of file qgspalgeometry.h.
Referenced by QgsPalLabeling::drawLabeling().
bool QgsPalGeometry::isPinned () const inline
Definition at line 114 of file qgspalgeometry.h.
Referenced by QgsPalLabeling::drawLabeling().
void QgsPalGeometry::releaseGeosGeometry (const GEOSGeometry *) inline
Definition at line 43 of file qgspalgeometry.h.
void QgsPalGeometry::setDefinedFont (QFont f) inline
Definition at line 116 of file qgspalgeometry.h.
Referenced by QgsPalLayerSettings::registerFeature().
void QgsPalGeometry::setDiagramAttributes (const QgsAttributes & attrs) inline
Definition at line 121 of file qgspalgeometry.h.
Referenced by QgsPalLabeling::registerDiagramFeature().
void QgsPalGeometry::setIsDiagram (bool d) inline
Definition at line 110 of file qgspalgeometry.h.
Referenced by QgsPalLabeling::registerDiagramFeature().
void QgsPalGeometry::setIsPinned (bool f) inline
Definition at line 113 of file qgspalgeometry.h.
Referenced by QgsPalLayerSettings::registerFeature().
const char* QgsPalGeometry::strId () inline
Definition at line 48 of file qgspalgeometry.h.
Referenced by QgsPalLabeling::drawLabeling(), QgsPalLabeling::registerDiagramFeature(), and QgsPalLayerSettings::registerFeature().
QString QgsPalGeometry::text (void) inline
Definition at line 49 of file qgspalgeometry.h.
Member Data Documentation
bool QgsPalGeometry::mCurvedLabeling protected
Definition at line 143 of file qgspalgeometry.h.
QMap< QgsPalLayerSettings::DataDefinedProperties, QVariant > QgsPalGeometry::mDataDefinedValues protected
Stores attribute values for data defined properties.
Definition at line 145 of file qgspalgeometry.h.
QFont QgsPalGeometry::mDefinedFont protected
Definition at line 139 of file qgspalgeometry.h.
QgsAttributes QgsPalGeometry::mDiagramAttributes protected
Stores attribute values for diagram rendering.
Definition at line 148 of file qgspalgeometry.h.
QFontMetricsF* QgsPalGeometry::mFontMetrics protected
Definition at line 140 of file qgspalgeometry.h.
GEOSGeometry* QgsPalGeometry::mG protected
Definition at line 132 of file qgspalgeometry.h.
QgsFeatureId QgsPalGeometry::mId protected
Definition at line 135 of file qgspalgeometry.h.
LabelInfo* QgsPalGeometry::mInfo protected
Definition at line 136 of file qgspalgeometry.h.
bool QgsPalGeometry::mIsDiagram protected
Definition at line 137 of file qgspalgeometry.h.
bool QgsPalGeometry::mIsPinned protected
Definition at line 138 of file qgspalgeometry.h.
qreal QgsPalGeometry::mLetterSpacing protected
Definition at line 141 of file qgspalgeometry.h.
QByteArray QgsPalGeometry::mStrId protected
Definition at line 134 of file qgspalgeometry.h.
QString QgsPalGeometry::mText protected
Definition at line 133 of file qgspalgeometry.h.
qreal QgsPalGeometry::mWordSpacing protected
Definition at line 142 of file qgspalgeometry.h.
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgspalgeometry.h