QGIS API Documentation: QgsVectorLayerUndoCommandDeleteAttribute Class Reference
QgsVectorLayerUndoCommandDeleteAttribute Class Reference
#include <qgsvectorlayerundocommand.h>
Public Member Functions
QgsVectorLayerUndoCommandDeleteAttribute (QgsVectorLayerEditBuffer *buffer, int fieldIndex)
virtual void undo ()
virtual void redo ()
Public Member Functions inherited from QgsVectorLayerUndoCommand
QgsVectorLayerUndoCommand (QgsVectorLayerEditBuffer *buffer)
QgsVectorLayer * layer ()
QgsGeometryCache * cache ()
virtual int id () const
virtual bool mergeWith (QUndoCommand *)
Private Attributes
int mFieldIndex
bool mProviderField
int mOriginIndex
QgsField mOldField
QMap< QgsFeatureId, QVariant > mDeletedValues
Additional Inherited Members
Protected Attributes inherited from QgsVectorLayerUndoCommand
QgsVectorLayerEditBuffer * mBuffer
Detailed Description
Definition at line 128 of file qgsvectorlayerundocommand.h.
Constructor & Destructor Documentation
QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute (QgsVectorLayerEditBuffer * buffer, int fieldIndex)
Definition at line 342 of file qgsvectorlayerundocommand.cpp.
References QgsFeature::attribute(), QgsFields::fieldOrigin(), QgsFields::fieldOriginIndex(), QgsFeature::id(), QgsVectorLayerUndoCommand::layer(), QgsVectorLayerEditBuffer::mAddedAttributes, QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mChangedAttributeValues, mDeletedValues, mFieldIndex, mOldField, mOriginIndex, mProviderField, QgsFields::OriginProvider, and QgsVectorLayer::pendingFields().
Member Function Documentation
void QgsVectorLayerUndoCommandDeleteAttribute::redo () virtual
Definition at line 407 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerEditBuffer::attributeDeleted(), QgsVectorLayerEditBuffer::handleAttributeDeleted(), QgsVectorLayerEditBuffer::mAddedAttributes, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mDeletedAttributeIds, mFieldIndex, mOriginIndex, mProviderField, and QgsVectorLayerEditBuffer::updateLayerFields().
void QgsVectorLayerUndoCommandDeleteAttribute::undo () virtual
Definition at line 373 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerEditBuffer::attributeAdded(), FID_IS_NEW, QgsVectorLayerEditBuffer::handleAttributeAdded(), QgsFeature::id(), QgsVectorLayerEditBuffer::mAddedAttributes, QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mChangedAttributeValues, QgsVectorLayerEditBuffer::mDeletedAttributeIds, mDeletedValues, mFieldIndex, mOldField, mOriginIndex, mProviderField, QgsFeature::setAttribute(), and QgsVectorLayerEditBuffer::updateLayerFields().
Member Data Documentation
QMap<QgsFeatureId, QVariant> QgsVectorLayerUndoCommandDeleteAttribute::mDeletedValues private
Definition at line 142 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandDeleteAttribute(), and undo().
int QgsVectorLayerUndoCommandDeleteAttribute::mFieldIndex private
Definition at line 137 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandDeleteAttribute(), redo(), and undo().
QgsField QgsVectorLayerUndoCommandDeleteAttribute::mOldField private
Definition at line 140 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandDeleteAttribute(), and undo().
int QgsVectorLayerUndoCommandDeleteAttribute::mOriginIndex private
Definition at line 139 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandDeleteAttribute(), redo(), and undo().
bool QgsVectorLayerUndoCommandDeleteAttribute::mProviderField private
Definition at line 138 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandDeleteAttribute(), redo(), and undo().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsvectorlayerundocommand.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsvectorlayerundocommand.cpp