QGIS API Documentation: QgsAddRemoveMultiFrameCommand Class Reference
QgsAddRemoveMultiFrameCommand Class Reference
#include <qgsaddremovemultiframecommand.h>
Public Types
enum State { Added = 0, Removed }
Public Member Functions
QgsAddRemoveMultiFrameCommand (State s, QgsComposerMultiFrame *multiFrame, QgsComposition *c, const QString &text, QUndoCommand *parent=0)
~QgsAddRemoveMultiFrameCommand ()
void redo ()
void undo ()
Private Member Functions
QgsAddRemoveMultiFrameCommand ()
void switchState ()
bool checkFirstRun ()
Private Attributes
QgsComposerMultiFrame * mMultiFrame
QgsComposition * mComposition
State mState
bool mFirstRun
Detailed Description
Definition at line 26 of file qgsaddremovemultiframecommand.h.
Member Enumeration Documentation
enum QgsAddRemoveMultiFrameCommand::State
Enumerator
Added
Removed
Definition at line 30 of file qgsaddremovemultiframecommand.h.
Constructor & Destructor Documentation
QgsAddRemoveMultiFrameCommand::QgsAddRemoveMultiFrameCommand (State s, QgsComposerMultiFrame * multiFrame, QgsComposition * c, const QString & text, QUndoCommand * parent = 0)
Definition at line 24 of file qgsaddremovemultiframecommand.cpp.
QgsAddRemoveMultiFrameCommand::~QgsAddRemoveMultiFrameCommand ()
Definition at line 33 of file qgsaddremovemultiframecommand.cpp.
References mMultiFrame, mState, and Removed.
QgsAddRemoveMultiFrameCommand::QgsAddRemoveMultiFrameCommand () private
Definition at line 29 of file qgsaddremovemultiframecommand.cpp.
Member Function Documentation
bool QgsAddRemoveMultiFrameCommand::checkFirstRun () private
Definition at line 77 of file qgsaddremovemultiframecommand.cpp.
References mFirstRun.
Referenced by redo(), and undo().
void QgsAddRemoveMultiFrameCommand::redo ()
Definition at line 41 of file qgsaddremovemultiframecommand.cpp.
References checkFirstRun(), and switchState().
void QgsAddRemoveMultiFrameCommand::switchState () private
Definition at line 59 of file qgsaddremovemultiframecommand.cpp.
References Added, QgsComposition::addMultiFrame(), QgsProject::dirty(), QgsProject::instance(), mComposition, mMultiFrame, mState, Removed, and QgsComposition::removeMultiFrame().
Referenced by redo(), and undo().
void QgsAddRemoveMultiFrameCommand::undo ()
Definition at line 50 of file qgsaddremovemultiframecommand.cpp.
References checkFirstRun(), and switchState().
Member Data Documentation
QgsComposition* QgsAddRemoveMultiFrameCommand::mComposition private
Definition at line 49 of file qgsaddremovemultiframecommand.h.
Referenced by switchState().
bool QgsAddRemoveMultiFrameCommand::mFirstRun private
Definition at line 51 of file qgsaddremovemultiframecommand.h.
Referenced by checkFirstRun().
QgsComposerMultiFrame* QgsAddRemoveMultiFrameCommand::mMultiFrame private
Definition at line 48 of file qgsaddremovemultiframecommand.h.
Referenced by switchState(), and ~QgsAddRemoveMultiFrameCommand().
State QgsAddRemoveMultiFrameCommand::mState private
Definition at line 50 of file qgsaddremovemultiframecommand.h.
Referenced by switchState(), and ~QgsAddRemoveMultiFrameCommand().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgsaddremovemultiframecommand.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgsaddremovemultiframecommand.cpp