QGIS API Documentation: QgsSingleBoxScaleBarStyle Class Reference
QgsSingleBoxScaleBarStyle Class Reference
MapComposer
Scalebar style that draws a single box with alternating color for the segments.
#include <qgssingleboxscalebarstyle.h>
Public Member Functions
QgsSingleBoxScaleBarStyle (const QgsComposerScaleBar *bar)
~QgsSingleBoxScaleBarStyle ()
QString name () const
void draw (QPainter *p, double xOffset=0) const
Public Member Functions inherited from QgsScaleBarStyle
QgsScaleBarStyle (const QgsComposerScaleBar *bar)
virtual ~QgsScaleBarStyle ()
virtual void drawLabels (QPainter *p) const
virtual QRectF calculateBoxSize () const
Private Member Functions
QgsSingleBoxScaleBarStyle ()
Additional Inherited Members
Protected Attributes inherited from QgsScaleBarStyle
const QgsComposerScaleBar * mScaleBar
Detailed Description
Scalebar style that draws a single box with alternating color for the segments.
Definition at line 26 of file qgssingleboxscalebarstyle.h.
Constructor & Destructor Documentation
QgsSingleBoxScaleBarStyle::QgsSingleBoxScaleBarStyle (const QgsComposerScaleBar * bar)
Definition at line 22 of file qgssingleboxscalebarstyle.cpp.
QgsSingleBoxScaleBarStyle::~QgsSingleBoxScaleBarStyle ()
Definition at line 32 of file qgssingleboxscalebarstyle.cpp.
QgsSingleBoxScaleBarStyle::QgsSingleBoxScaleBarStyle () private
Definition at line 27 of file qgssingleboxscalebarstyle.cpp.
Member Function Documentation
void QgsSingleBoxScaleBarStyle::draw (QPainter * p, double xOffset = 0) const virtual
draw method
Parameters
p painter object
xOffset x offset
Implements QgsScaleBarStyle.
Definition at line 37 of file qgssingleboxscalebarstyle.cpp.
References QgsComposerScaleBar::boxContentSpace(), QgsComposerScaleBar::brush(), QgsScaleBarStyle::drawLabels(), QgsComposerScaleBar::font(), QgsComposerItem::fontAscentMillimeters(), QgsComposerScaleBar::height(), QgsComposerScaleBar::labelBarSpace(), QgsScaleBarStyle::mScaleBar, QgsComposerScaleBar::pen(), and QgsComposerScaleBar::segmentPositions().
QString QgsSingleBoxScaleBarStyle::name () const virtual
Implements QgsScaleBarStyle.
Definition at line 77 of file qgssingleboxscalebarstyle.cpp.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgssingleboxscalebarstyle.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgssingleboxscalebarstyle.cpp