QGIS API Documentation: QgsComposerRasterSymbolItem Class Reference
QgsComposerRasterSymbolItem Class Reference
#include <qgscomposerlegenditem.h>
Public Member Functions
QgsComposerRasterSymbolItem ()
QgsComposerRasterSymbolItem (const QString &text)
QgsComposerRasterSymbolItem (const QIcon &icon, const QString &text)
virtual ~QgsComposerRasterSymbolItem ()
virtual QStandardItem * clone () const
virtual void writeXML (QDomElement &elem, QDomDocument &doc) const
virtual void readXML (const QDomElement &itemElem, bool xServerAvailable=true)
Read item content from xml.
void setLayerID (const QString &id)
QString layerID () const
ItemType itemType () const
void setColor (const QColor &c)
QColor color () const
Public Member Functions inherited from QgsComposerLegendItem
QgsComposerLegendItem (QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
QgsComposerLegendItem (const QString &text, QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
QgsComposerLegendItem (const QIcon &icon, const QString &text, QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
virtual ~QgsComposerLegendItem ()
QgsComposerLegendStyle::Style style () const
void setStyle (QgsComposerLegendStyle::Style style)
virtual QString userText () const
virtual void setUserText (const QString &text)
Private Attributes
QString mLayerID
QColor mColor
Additional Inherited Members
Public Types inherited from QgsComposerLegendItem
enum ItemType {
GroupItem = QStandardItem::UserType, LayerItem, SymbologyV2Item, RasterSymbolItem,
StyleItem
}
Protected Member Functions inherited from QgsComposerLegendItem
void writeXMLChildren (QDomElement &elem, QDomDocument &doc) const
Protected Attributes inherited from QgsComposerLegendItem
QgsComposerLegendStyle::Style mStyle
QString mUserText
Detailed Description
Definition at line 97 of file qgscomposerlegenditem.h.
Constructor & Destructor Documentation
QgsComposerRasterSymbolItem::QgsComposerRasterSymbolItem ()
Definition at line 150 of file qgscomposerlegenditem.cpp.
Referenced by clone().
QgsComposerRasterSymbolItem::QgsComposerRasterSymbolItem (const QString & text)
Definition at line 154 of file qgscomposerlegenditem.cpp.
QgsComposerRasterSymbolItem::QgsComposerRasterSymbolItem (const QIcon & icon, const QString & text)
Definition at line 158 of file qgscomposerlegenditem.cpp.
QgsComposerRasterSymbolItem::~QgsComposerRasterSymbolItem () virtual
Definition at line 162 of file qgscomposerlegenditem.cpp.
Member Function Documentation
QStandardItem * QgsComposerRasterSymbolItem::clone () const virtual
Implements QgsComposerLegendItem.
Definition at line 166 of file qgscomposerlegenditem.cpp.
References mLayerID, QgsComposerRasterSymbolItem(), and setLayerID().
QColor QgsComposerRasterSymbolItem::color (void) const inline
Definition at line 115 of file qgscomposerlegenditem.h.
Referenced by QgsComposerLegend::drawSymbolItem().
ItemType QgsComposerRasterSymbolItem::itemType () const inline virtual
Implements QgsComposerLegendItem.
Definition at line 112 of file qgscomposerlegenditem.h.
References QgsComposerLegendItem::RasterSymbolItem.
QString QgsComposerRasterSymbolItem::layerID () const inline
Definition at line 111 of file qgscomposerlegenditem.h.
void QgsComposerRasterSymbolItem::readXML (const QDomElement & itemElem, bool xServerAvailable = true) virtual
Read item content from xml.
Parameters
itemElem item to read from
xServerAvailable Read item icons if true (QIcon needs x-server)
Implements QgsComposerLegendItem.
Definition at line 184 of file qgscomposerlegenditem.cpp.
References mColor, setColor(), setLayerID(), and QgsComposerLegendItem::setUserText().
void QgsComposerRasterSymbolItem::setColor (const QColor & c) inline
Definition at line 114 of file qgscomposerlegenditem.h.
Referenced by QgsLegendModel::addRasterLayerItems(), and readXML().
void QgsComposerRasterSymbolItem::setLayerID (const QString & id) inline
Definition at line 110 of file qgscomposerlegenditem.h.
Referenced by QgsLegendModel::addRasterLayerItems(), clone(), and readXML().
void QgsComposerRasterSymbolItem::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
Implements QgsComposerLegendItem.
Definition at line 174 of file qgscomposerlegenditem.cpp.
References mColor, mLayerID, and QgsComposerLegendItem::userText().
Member Data Documentation
QColor QgsComposerRasterSymbolItem::mColor private
Definition at line 119 of file qgscomposerlegenditem.h.
Referenced by readXML(), and writeXML().
QString QgsComposerRasterSymbolItem::mLayerID private
Definition at line 118 of file qgscomposerlegenditem.h.
Referenced by clone(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerlegenditem.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerlegenditem.cpp