QGIS API Documentation: QgsSvgMarkerSymbolLayerV2 Class Reference
QgsSvgMarkerSymbolLayerV2 Class Reference
#include <qgsmarkersymbollayerv2.h>
Public Member Functions
QgsSvgMarkerSymbolLayerV2 (QString name=DEFAULT_SVGMARKER_NAME, double size=DEFAULT_SVGMARKER_SIZE, double angle=DEFAULT_SVGMARKER_ANGLE, QgsSymbolV2::ScaleMethod scaleMethod=DEFAULT_SCALE_METHOD)
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
void renderPoint (const QPointF &point, QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
void writeSldMarker (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
QString path () const
void setPath (QString path)
QColor fillColor () const
Get fill color.
void setFillColor (const QColor &c)
Set fill color.
QColor outlineColor () const
Get outline color.
void setOutlineColor (const QColor &c)
Set outline color.
double outlineWidth () const
void setOutlineWidth (double w)
void setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outlineWidthUnit () const
void setOutlineWidthMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & outlineWidthMapUnitScale () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
void setMapUnitScale (const QgsMapUnitScale &scale)
QgsMapUnitScale mapUnitScale () const
bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
Public Member Functions inherited from QgsMarkerSymbolLayerV2
void startRender (QgsSymbolV2RenderContext &context)
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
void setSize (double size)
double size () const
void setScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod)
QgsSymbolV2::ScaleMethod scaleMethod () const
void setOffset (QPointF offset)
QPointF offset ()
virtual void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
void setOffsetUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit offsetUnit () const
void setOffsetMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & offsetMapUnitScale () const
void setSizeUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit sizeUnit () const
void setSizeMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & sizeMapUnitScale () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
void setMapUnitScale (const QgsMapUnitScale &scale)
QgsMapUnitScale mapUnitScale () const
void setHorizontalAnchorPoint (HorizontalAnchorPoint h)
HorizontalAnchorPoint horizontalAnchorPoint () const
void setVerticalAnchorPoint (VerticalAnchorPoint v)
VerticalAnchorPoint verticalAnchorPoint () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual ~QgsSymbolLayerV2 ()
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
virtual Qt::PenStyle dxfPenStyle () const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Protected Attributes
QString mPath
QColor mFillColor
QColor mOutlineColor
double mOutlineWidth
QgsSymbolV2::OutputUnit mOutlineWidthUnit
QgsMapUnitScale mOutlineWidthMapUnitScale
double mOrigSize
Protected Attributes inherited from QgsMarkerSymbolLayerV2
double mAngle
double mSize
QgsSymbolV2::OutputUnit mSizeUnit
QgsMapUnitScale mSizeMapUnitScale
QPointF mOffset
QgsSymbolV2::OutputUnit mOffsetUnit
QgsMapUnitScale mOffsetMapUnitScale
QgsSymbolV2::ScaleMethod mScaleMethod
HorizontalAnchorPoint mHorizontalAnchorPoint
VerticalAnchorPoint mVerticalAnchorPoint
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Additional Inherited Members
Public Types inherited from QgsMarkerSymbolLayerV2
enum HorizontalAnchorPoint { Left, HCenter, Right }
enum VerticalAnchorPoint { Top, VCenter, Bottom }
Protected Member Functions inherited from QgsMarkerSymbolLayerV2
QgsMarkerSymbolLayerV2 (bool locked=false)
void markerOffset (const QgsSymbolV2RenderContext &context, double &offsetX, double &offsetY) const
void markerOffset (const QgsSymbolV2RenderContext &context, double width, double height, double &offsetX, double &offsetY) const
void markerOffset (const QgsSymbolV2RenderContext &context, double width, double height, QgsSymbolV2::OutputUnit widthUnit, QgsSymbolV2::OutputUnit heightUnit, double &offsetX, double &offsetY, const QgsMapUnitScale &widthMapUnitScale, const QgsMapUnitScale &heightMapUnitScale) const
Protected Member Functions inherited from QgsSymbolLayerV2
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsFields *fields, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Static Protected Member Functions inherited from QgsMarkerSymbolLayerV2
static QPointF _rotatedOffset (const QPointF &offset, double angle)
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 147 of file qgsmarkersymbollayerv2.h.
Constructor & Destructor Documentation
QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2 (QString name = DEFAULT_SVGMARKER_NAME, double size = DEFAULT_SVGMARKER_SIZE, double angle = DEFAULT_SVGMARKER_ANGLE, QgsSymbolV2::ScaleMethod scaleMethod = DEFAULT_SCALE_METHOD)
Definition at line 979 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsMarkerSymbolLayerV2::mAngle, mFillColor, QgsSymbolV2::MM, QgsMarkerSymbolLayerV2::mOffset, mOutlineColor, mOutlineWidth, mOutlineWidthUnit, mPath, QgsMarkerSymbolLayerV2::mScaleMethod, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::scaleMethod(), QgsMarkerSymbolLayerV2::size(), and QgsSymbolLayerV2Utils::symbolNameToPath().
Referenced by clone(), create(), and createFromSld().
Member Function Documentation
QgsSymbolLayerV2 * QgsSvgMarkerSymbolLayerV2::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1318 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolLayerV2::copyDataDefinedProperties(), QgsMarkerSymbolLayerV2::mAngle, mFillColor, QgsMarkerSymbolLayerV2::mHorizontalAnchorPoint, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetMapUnitScale, QgsMarkerSymbolLayerV2::mOffsetUnit, mOutlineColor, mOutlineWidth, mOutlineWidthMapUnitScale, mOutlineWidthUnit, mPath, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, QgsMarkerSymbolLayerV2::mVerticalAnchorPoint, QgsSvgMarkerSymbolLayerV2(), setFillColor(), QgsMarkerSymbolLayerV2::setHorizontalAnchorPoint(), QgsMarkerSymbolLayerV2::setOffset(), QgsMarkerSymbolLayerV2::setOffsetMapUnitScale(), QgsMarkerSymbolLayerV2::setOffsetUnit(), setOutlineColor(), setOutlineWidth(), setOutlineWidthMapUnitScale(), setOutlineWidthUnit(), QgsMarkerSymbolLayerV2::setSizeMapUnitScale(), QgsMarkerSymbolLayerV2::setSizeUnit(), and QgsMarkerSymbolLayerV2::setVerticalAnchorPoint().
QgsSymbolLayerV2 * QgsSvgMarkerSymbolLayerV2::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 993 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSvgCache::containsParams(), QgsSymbolLayerV2Utils::decodeMapUnitScale(), QgsSymbolLayerV2Utils::decodeOutputUnit(), QgsSymbolLayerV2Utils::decodePoint(), QgsSymbolLayerV2Utils::decodeScaleMethod(), DEFAULT_SCALE_METHOD, DEFAULT_SVGMARKER_ANGLE, DEFAULT_SVGMARKER_NAME, DEFAULT_SVGMARKER_SIZE, fillColor(), QgsSvgCache::instance(), outlineColor(), outlineWidth(), QgsSvgMarkerSymbolLayerV2(), QgsMarkerSymbolLayerV2::scaleMethod(), QgsSymbolLayerV2::setDataDefinedProperty(), setFillColor(), QgsMarkerSymbolLayerV2::setHorizontalAnchorPoint(), QgsMarkerSymbolLayerV2::setOffset(), QgsMarkerSymbolLayerV2::setOffsetMapUnitScale(), QgsMarkerSymbolLayerV2::setOffsetUnit(), setOutlineColor(), setOutlineWidth(), setOutlineWidthMapUnitScale(), setOutlineWidthUnit(), QgsMarkerSymbolLayerV2::setSizeMapUnitScale(), QgsMarkerSymbolLayerV2::setSizeUnit(), QgsMarkerSymbolLayerV2::setVerticalAnchorPoint(), and QgsMarkerSymbolLayerV2::size().
Referenced by QgsPalLabeling::drawLabelBackground(), and QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsSvgMarkerSymbolLayerV2::createFromSld (QDomElement & element) static
Definition at line 1395 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::displacementFromSldElement(), QgsSymbolLayerV2Utils::externalGraphicFromSld(), fillColor(), QgsMarkerSymbolLayerV2::offset(), path(), QgsDebugMsg, QgsSvgMarkerSymbolLayerV2(), QgsSymbolLayerV2Utils::rotationFromSldElement(), QgsMarkerSymbolLayerV2::setAngle(), setFillColor(), QgsMarkerSymbolLayerV2::setOffset(), and QgsMarkerSymbolLayerV2::size().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QColor QgsSvgMarkerSymbolLayerV2::fillColor () const inline virtual
Get fill color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 179 of file qgsmarkersymbollayerv2.h.
Referenced by create(), createFromSld(), renderPoint(), and setPath().
QString QgsSvgMarkerSymbolLayerV2::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1124 of file qgsmarkersymbollayerv2.cpp.
QgsMapUnitScale QgsSvgMarkerSymbolLayerV2::mapUnitScale () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 1359 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::mapUnitScale(), and mOutlineWidthMapUnitScale.
QColor QgsSvgMarkerSymbolLayerV2::outlineColor () const inline virtual
Get outline color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 182 of file qgsmarkersymbollayerv2.h.
Referenced by create(), renderPoint(), and setPath().
double QgsSvgMarkerSymbolLayerV2::outlineWidth () const inline
Definition at line 185 of file qgsmarkersymbollayerv2.h.
Referenced by create(), renderPoint(), and setPath().
const QgsMapUnitScale& QgsSvgMarkerSymbolLayerV2::outlineWidthMapUnitScale () const inline
Definition at line 192 of file qgsmarkersymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsSvgMarkerSymbolLayerV2::outlineWidthUnit () const inline
Definition at line 189 of file qgsmarkersymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsSvgMarkerSymbolLayerV2::outputUnit () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 1343 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolV2::Mixed, mOutlineWidthUnit, and QgsMarkerSymbolLayerV2::outputUnit().
QString QgsSvgMarkerSymbolLayerV2::path () const inline
Definition at line 176 of file qgsmarkersymbollayerv2.h.
Referenced by createFromSld(), renderPoint(), and setPath().
QgsStringMap QgsSvgMarkerSymbolLayerV2::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1294 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeMapUnitScale(), QgsSymbolLayerV2Utils::encodeOutputUnit(), QgsSymbolLayerV2Utils::encodePoint(), QgsSymbolLayerV2Utils::encodeScaleMethod(), QgsMarkerSymbolLayerV2::mAngle, mFillColor, QgsMarkerSymbolLayerV2::mHorizontalAnchorPoint, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetMapUnitScale, QgsMarkerSymbolLayerV2::mOffsetUnit, mOutlineColor, mOutlineWidth, mOutlineWidthMapUnitScale, mOutlineWidthUnit, mPath, QgsMarkerSymbolLayerV2::mScaleMethod, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, QgsMarkerSymbolLayerV2::mVerticalAnchorPoint, QgsSymbolLayerV2::saveDataDefinedProperties(), and QgsSymbolLayerV2Utils::symbolPathToName().
void QgsSvgMarkerSymbolLayerV2::renderPoint (const QPointF & point, QgsSymbolV2RenderContext & context) virtual
Implements QgsMarkerSymbolLayerV2.
Definition at line 1142 of file qgsmarkersymbollayerv2.cpp.
References _fixQPictureDPI(), QgsMarkerSymbolLayerV2::_rotatedOffset(), QgsSymbolV2RenderContext::alpha(), QgsMarkerSymbolLayerV2::angle(), QgsSymbolV2::DataDefinedSizeScale, QgsSymbolLayerV2Utils::decodeColor(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), fillColor(), QgsRenderContext::forceVectorOutput(), QgsSvgCache::instance(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsMarkerSymbolLayerV2::mAngle, QgsMarkerSymbolLayerV2::markerOffset(), mFillColor, QgsSymbolV2::MM, mOutlineColor, mOutlineWidth, mPath, QgsMarkerSymbolLayerV2::mScaleMethod, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, QgsSymbolLayerV2Utils::multiplyImageOpacity(), outlineColor(), outlineWidth(), QgsRenderContext::painter(), path(), qgsDoubleNear(), QgsRenderContext::rasterScaleFactor(), QgsSymbolV2RenderContext::renderContext(), QgsSymbolV2RenderContext::renderHints(), QgsSymbolV2::ScaleArea, QgsSymbolV2::ScaleDiameter, QgsRenderContext::scaleFactor(), QgsSymbolV2RenderContext::selected(), QgsRenderContext::selectionColor(), QgsMarkerSymbolLayerV2::size(), QgsSvgCache::svgAsImage(), and QgsSvgCache::svgAsPicture().
Referenced by QgsPalLabeling::drawLabelBackground().
void QgsSvgMarkerSymbolLayerV2::setFillColor (const QColor & color) inline virtual
Set fill color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 180 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), create(), createFromSld(), and setPath().
void QgsSvgMarkerSymbolLayerV2::setMapUnitScale (const QgsMapUnitScale & scale) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 1353 of file qgsmarkersymbollayerv2.cpp.
References mOutlineWidthMapUnitScale, and QgsMarkerSymbolLayerV2::setMapUnitScale().
void QgsSvgMarkerSymbolLayerV2::setOutlineColor (const QColor & color) inline virtual
Set outline color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 183 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), create(), and setPath().
void QgsSvgMarkerSymbolLayerV2::setOutlineWidth (double w) inline
Definition at line 186 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), create(), and setPath().
void QgsSvgMarkerSymbolLayerV2::setOutlineWidthMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 191 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), and create().
void QgsSvgMarkerSymbolLayerV2::setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 188 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), and create().
void QgsSvgMarkerSymbolLayerV2::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 1337 of file qgsmarkersymbollayerv2.cpp.
References mOutlineWidthUnit, and QgsMarkerSymbolLayerV2::setOutputUnit().
void QgsSvgMarkerSymbolLayerV2::setPath (QString path)
Definition at line 1102 of file qgsmarkersymbollayerv2.cpp.
References QgsSvgCache::containsParams(), fillColor(), QgsSvgCache::instance(), mPath, outlineColor(), outlineWidth(), path(), setFillColor(), setOutlineColor(), and setOutlineWidth().
void QgsSvgMarkerSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 1129 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolV2RenderContext::fields(), mOrigSize, QgsMarkerSymbolLayerV2::mSize, QgsSymbolLayerV2::prepareExpressions(), QgsSymbolV2RenderContext::renderContext(), QgsRenderContext::rendererScale(), and QgsMarkerSymbolLayerV2::startRender().
void QgsSvgMarkerSymbolLayerV2::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 1137 of file qgsmarkersymbollayerv2.cpp.
bool QgsSvgMarkerSymbolLayerV2::writeDxf (QgsDxfExport & e, double mmMapUnitScaleFactor, const QString & layerName, const QgsSymbolV2RenderContext * context, const QgsFeature * f, const QPointF & shift = QPointF(0.0, 0.0)) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 1435 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::_rotatedOffset(), QgsMarkerSymbolLayerV2::angle(), QgsSymbolV2::DataDefinedSizeScale, QgsSymbolLayerV2Utils::decodePoint(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsMarkerSymbolLayerV2::mAngle, QgsSymbolV2::MM, QgsMarkerSymbolLayerV2::mOffset, mPath, QgsMarkerSymbolLayerV2::mScaleMethod, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeUnit, QgsMarkerSymbolLayerV2::offset(), qgsDoubleNear(), QgsSymbolV2RenderContext::renderHints(), QgsSymbolV2::ScaleArea, QgsSymbolV2::ScaleDiameter, and QgsMarkerSymbolLayerV2::size().
void QgsSvgMarkerSymbolLayerV2::writeSldMarker (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsMarkerSymbolLayerV2.
Definition at line 1368 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::createDisplacementElement(), QgsSymbolLayerV2Utils::createRotationElement(), QgsSymbolLayerV2Utils::externalGraphicToSld(), QgsMarkerSymbolLayerV2::mAngle, mFillColor, QgsMarkerSymbolLayerV2::mOffset, mPath, and QgsMarkerSymbolLayerV2::mSize.
Member Data Documentation
QColor QgsSvgMarkerSymbolLayerV2::mFillColor protected
Definition at line 207 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), properties(), QgsSvgMarkerSymbolLayerV2(), renderPoint(), and writeSldMarker().
double QgsSvgMarkerSymbolLayerV2::mOrigSize protected
Definition at line 212 of file qgsmarkersymbollayerv2.h.
Referenced by startRender().
QColor QgsSvgMarkerSymbolLayerV2::mOutlineColor protected
Definition at line 208 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), properties(), QgsSvgMarkerSymbolLayerV2(), and renderPoint().
double QgsSvgMarkerSymbolLayerV2::mOutlineWidth protected
Definition at line 209 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), properties(), QgsSvgMarkerSymbolLayerV2(), and renderPoint().
QgsMapUnitScale QgsSvgMarkerSymbolLayerV2::mOutlineWidthMapUnitScale protected
Definition at line 211 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), mapUnitScale(), properties(), and setMapUnitScale().
QgsSymbolV2::OutputUnit QgsSvgMarkerSymbolLayerV2::mOutlineWidthUnit protected
Definition at line 210 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), outputUnit(), properties(), QgsSvgMarkerSymbolLayerV2(), and setOutputUnit().
QString QgsSvgMarkerSymbolLayerV2::mPath protected
Definition at line 203 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), properties(), QgsSvgMarkerSymbolLayerV2(), renderPoint(), setPath(), writeDxf(), and writeSldMarker().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsmarkersymbollayerv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsmarkersymbollayerv2.cpp