QGIS API Documentation: QgsExpression::NodeBinaryOperator Class Reference
QgsExpression::NodeBinaryOperator Class Reference
#include <qgsexpression.h>
Public Member Functions
NodeBinaryOperator (BinaryOperator op, Node *opLeft, Node *opRight)
~NodeBinaryOperator ()
BinaryOperator op () const
Node * opLeft () const
Node * opRight () const
virtual NodeType nodeType () const
virtual bool prepare (QgsExpression *parent, const QgsFields &fields)
virtual QVariant eval (QgsExpression *parent, const QgsFeature *f)
virtual QString dump () const
virtual QStringList referencedColumns () const
virtual bool needsGeometry () const
virtual void accept (Visitor &v) const
int precedence () const
Public Member Functions inherited from QgsExpression::Node
virtual ~Node ()
Protected Member Functions
bool compare (double diff)
int computeInt (int x, int y)
double computeDouble (double x, double y)
QDateTime computeDateTimeFromInterval (QDateTime d, QgsExpression::Interval *i)
Protected Attributes
BinaryOperator mOp
Node * mOpLeft
Node * mOpRight
Detailed Description
Definition at line 428 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::NodeBinaryOperator::NodeBinaryOperator (BinaryOperator op, Node * opLeft, Node * opRight) inline
Definition at line 431 of file qgsexpression.h.
QgsExpression::NodeBinaryOperator::~NodeBinaryOperator () inline
Definition at line 432 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::NodeBinaryOperator::accept (Visitor & v) const inline virtual
Implements QgsExpression::Node.
Definition at line 445 of file qgsexpression.h.
References QgsExpression::Visitor::visit().
bool QgsExpression::NodeBinaryOperator::compare (double diff) protected
Definition at line 2202 of file qgsexpression.cpp.
References QgsExpression::boEQ, QgsExpression::boGE, QgsExpression::boGT, QgsExpression::boLE, QgsExpression::boLT, and QgsExpression::boNE.
QDateTime QgsExpression::NodeBinaryOperator::computeDateTimeFromInterval (QDateTime d, QgsExpression::Interval * i) protected
Definition at line 2229 of file qgsexpression.cpp.
References QgsExpression::boMinus, QgsExpression::boPlus, and QgsExpression::Interval::seconds().
double QgsExpression::NodeBinaryOperator::computeDouble (double x, double y) protected
Definition at line 2239 of file qgsexpression.cpp.
References QgsExpression::boDiv, QgsExpression::boMinus, QgsExpression::boMod, QgsExpression::boMul, and QgsExpression::boPlus.
int QgsExpression::NodeBinaryOperator::computeInt (int x, int y) protected
Definition at line 2216 of file qgsexpression.cpp.
References QgsExpression::boDiv, QgsExpression::boMinus, QgsExpression::boMod, QgsExpression::boMul, and QgsExpression::boPlus.
QString QgsExpression::NodeBinaryOperator::dump () const virtual
Implements QgsExpression::Node.
Definition at line 2305 of file qgsexpression.cpp.
References QgsExpression::BinaryOperatorText, and precedence().
QVariant QgsExpression::NodeBinaryOperator::eval (QgsExpression * parent, const QgsFeature * f) virtual
Implements QgsExpression::Node.
Definition at line 2030 of file qgsexpression.cpp.
References AND, QgsExpression::boAnd, QgsExpression::boConcat, QgsExpression::boDiv, QgsExpression::boEQ, QgsExpression::boGE, QgsExpression::boGT, QgsExpression::boILike, QgsExpression::boIs, QgsExpression::boIsNot, QgsExpression::boLE, QgsExpression::boLike, QgsExpression::boLT, QgsExpression::boMinus, QgsExpression::boMod, QgsExpression::boMul, QgsExpression::boNE, QgsExpression::boNotILike, QgsExpression::boNotLike, QgsExpression::boOr, QgsExpression::boPlus, QgsExpression::boPow, QgsExpression::boRegexp, ENSURE_NO_EVAL_ERROR, getDateTimeValue(), getDoubleValue(), getInterval(), getIntValue(), getStringValue(), getTVLValue(), isDateTimeSafe(), isDoubleSafe(), isIntervalSafe(), isIntSafe(), isNull(), OR, QgsExpression::setEvalErrorString(), tr, tvl2variant(), TVL_False, TVL_True, and TVL_Unknown.
virtual bool QgsExpression::NodeBinaryOperator::needsGeometry () const inline virtual
Implements QgsExpression::Node.
Definition at line 444 of file qgsexpression.h.
virtual NodeType QgsExpression::NodeBinaryOperator::nodeType () const inline virtual
Implements QgsExpression::Node.
Definition at line 438 of file qgsexpression.h.
References QgsExpression::ntBinaryOperator.
BinaryOperator QgsExpression::NodeBinaryOperator::op () const inline
Definition at line 434 of file qgsexpression.h.
Referenced by QgsOgcUtils::expressionBinaryOperatorToOgcFilter().
Node* QgsExpression::NodeBinaryOperator::opLeft () const inline
Definition at line 435 of file qgsexpression.h.
Referenced by QgsOgcUtils::expressionBinaryOperatorToOgcFilter().
Node* QgsExpression::NodeBinaryOperator::opRight () const inline
Definition at line 436 of file qgsexpression.h.
Referenced by QgsOgcUtils::expressionBinaryOperatorToOgcFilter().
int QgsExpression::NodeBinaryOperator::precedence () const
Definition at line 2260 of file qgsexpression.cpp.
References QgsExpression::boAnd, QgsExpression::boConcat, QgsExpression::boDiv, QgsExpression::boEQ, QgsExpression::boGE, QgsExpression::boGT, QgsExpression::boILike, QgsExpression::boIs, QgsExpression::boIsNot, QgsExpression::boLE, QgsExpression::boLike, QgsExpression::boLT, QgsExpression::boMinus, QgsExpression::boMod, QgsExpression::boMul, QgsExpression::boNE, QgsExpression::boNotILike, QgsExpression::boNotLike, QgsExpression::boOr, QgsExpression::boPlus, QgsExpression::boPow, and QgsExpression::boRegexp.
Referenced by dump().
bool QgsExpression::NodeBinaryOperator::prepare (QgsExpression * parent, const QgsFields & fields) virtual
Implements QgsExpression::Node.
Definition at line 2253 of file qgsexpression.cpp.
virtual QStringList QgsExpression::NodeBinaryOperator::referencedColumns () const inline virtual
Implements QgsExpression::Node.
Definition at line 443 of file qgsexpression.h.
Member Data Documentation
BinaryOperator QgsExpression::NodeBinaryOperator::mOp protected
Definition at line 455 of file qgsexpression.h.
Node* QgsExpression::NodeBinaryOperator::mOpLeft protected
Definition at line 456 of file qgsexpression.h.
Node* QgsExpression::NodeBinaryOperator::mOpRight protected
Definition at line 457 of file qgsexpression.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.cpp