QGIS API Documentation: QgsComposerView Class Reference
QgsComposerView Class Reference
MapComposer | QGIS gui library.
Widget to display the composer items.
#include <qgscomposerview.h>
Public Types
enum Tool {
Select = 0, AddArrow, AddHtml, AddMap,
AddLegend, AddLabel, AddScalebar, AddPicture,
AddRectangle, AddEllipse, AddTriangle, AddTable,
MoveItemContent, Pan, Zoom
}
Current tool.
enum ClipboardMode { ClipboardModeCut, ClipboardModeCopy }
enum PasteMode { PasteModeCursor, PasteModeCenter, PasteModeInPlace }
enum ToolStatus { Inactive, Active, ActiveUntilMouseRelease }
Signals
void selectedItemChanged (QgsComposerItem *selected)
Is emitted when selected item changed.
void itemRemoved (QgsComposerItem *)
Is emitted when a composer item has been removed from the scene.
void actionFinished ()
Current action (e.g.
void cursorPosChanged (QPointF)
Is emitted when mouse cursor coordinates change.
void zoomLevelChanged ()
Is emitted when the view zoom changes.
void composerViewShow (QgsComposerView *)
Emitted before composerview is shown.
void composerViewHide (QgsComposerView *)
Emitted before composerview is hidden.
void compositionSet (QgsComposition *)
Emitted when the composition is set for the view.
Public Member Functions
QgsComposerView (QWidget *parent=0, const char *name=0, Qt::WindowFlags f=0)
void groupItems ()
Add an item group containing the selected items.
void ungroupItems ()
Ungroups the selected items.
void copyItems (ClipboardMode mode)
Cuts or copies the selected items.
void pasteItems (PasteMode mode)
Pastes items from clipboard.
void deleteSelectedItems ()
Deletes selected items.
void selectAll ()
Selects all items.
void selectNone ()
Deselects all items.
void selectInvert ()
Inverts current selection.
QgsComposerView::Tool currentTool () const
void setCurrentTool (QgsComposerView::Tool t)
void setComposition (QgsComposition *c)
Sets the composition for the view.
QgsComposition * composition ()
Returns the composition or 0 in case of error.
QMainWindow * composerWindow ()
Returns the composer main window.
void setPaintingEnabled (bool enabled)
bool paintingEnabled () const
void updateRulers ()
Update rulers with current scene rect.
void setHorizontalRuler (QgsComposerRuler *r)
void setVerticalRuler (QgsComposerRuler *r)
void setZoomLevel (double zoomLevel)
Set zoom level, where a zoom level of 1.0 corresponds to 100%.
void setPreviewModeEnabled (bool enabled)
Sets whether a preview effect should be used to alter the view's appearance.
void setPreviewMode (QgsPreviewEffect::PreviewMode mode)
Sets the preview mode which should be used to modify the view's appearance.
Protected Member Functions
void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
void mouseMoveEvent (QMouseEvent *)
void mouseDoubleClickEvent (QMouseEvent *e)
void keyPressEvent (QKeyEvent *e)
void keyReleaseEvent (QKeyEvent *e)
void wheelEvent (QWheelEvent *event)
void paintEvent (QPaintEvent *event)
void hideEvent (QHideEvent *e)
void showEvent (QShowEvent *e)
void resizeEvent (QResizeEvent *event)
void scrollContentsBy (int dx, int dy)
Private Member Functions
void addShape (Tool currentTool)
Draw a shape on the canvas.
QCursor defaultCursorForTool (Tool currentTool)
Returns the default mouse cursor for a tool.
void wheelZoom (QWheelEvent *event)
Zoom composition from a mouse wheel event.
void updateRubberBand (QPointF &pos)
Redraws the rubber band.
void removeRubberBand ()
Removes the rubber band and cleans up.
void startMarqueeSelect (QPointF &scenePoint)
Starts a marquee selection.
void endMarqueeSelect (QMouseEvent *e)
Finalises a marquee selection.
void startMarqueeZoom (QPointF &scenePoint)
Starts a zoom in marquee.
void endMarqueeZoom (QMouseEvent *e)
Finalises a marquee zoom.
Private Attributes
QgsComposerView::Tool mCurrentTool
Current composer tool.
QgsComposerView::Tool mPreviousTool
Previous composer tool.
QGraphicsRectItem * mRubberBandItem
Rubber band item.
QGraphicsLineItem * mRubberBandLineItem
Rubber band item for arrows.
QgsComposerItem * mMoveContentItem
Item to move content.
QPointF mMoveContentStartPos
Start position of content move.
QPointF mRubberBandStartPos
Start of rubber band creation.
bool mMarqueeSelect
True if user is currently selecting by marquee.
bool mMarqueeZoom
True if user is currently zooming by marquee.
QgsComposerView::ToolStatus mTemporaryZoomStatus
True if user is currently temporarily activating the zoom tool by holding control+space.
bool mPaintingEnabled
QgsComposerRuler * mHorizontalRuler
QgsComposerRuler * mVerticalRuler
bool mToolPanning
True if user is currently panning by clicking and dragging with the pan tool.
bool mMousePanning
True if user is currently panning by holding the middle mouse button.
bool mKeyPanning
True if user is currently panning by holding the space key.
bool mMovingItemContent
True if user is currently dragging with the move item content tool.
QPoint mMouseLastXY
QPoint mMouseCurrentXY
QPoint mMousePressStartPos
QgsPreviewEffect * mPreviewEffect
Detailed Description
Widget to display the composer items.
Manages the composer tools and the mouse/key events. Creates the composer items according to the current map tools and keeps track of the rubber band item.
Definition at line 48 of file qgscomposerview.h.
Member Enumeration Documentation
enum QgsComposerView::ClipboardMode
Enumerator
ClipboardModeCut
ClipboardModeCopy
Definition at line 74 of file qgscomposerview.h.
enum QgsComposerView::PasteMode
Enumerator
PasteModeCursor
PasteModeCenter
PasteModeInPlace
Definition at line 80 of file qgscomposerview.h.
enum QgsComposerView::Tool
Current tool.
Enumerator
Select
AddArrow
AddHtml
AddMap
AddLegend
AddLabel
AddScalebar
AddPicture
AddRectangle
AddEllipse
AddTriangle
AddTable
MoveItemContent
Pan
Zoom
Definition at line 55 of file qgscomposerview.h.
enum QgsComposerView::ToolStatus
Enumerator
Inactive
Active
ActiveUntilMouseRelease
Definition at line 87 of file qgscomposerview.h.
Constructor & Destructor Documentation
QgsComposerView::QgsComposerView (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags f = 0)
Definition at line 49 of file qgscomposerview.cpp.
References mPreviewEffect.
Member Function Documentation
void QgsComposerView::actionFinished () signal
Current action (e.g.
adding composer map) has been finished. The purpose of this signal is that QgsComposer may set the selection tool again
Referenced by addShape(), mousePressEvent(), and mouseReleaseEvent().
void QgsComposerView::addShape (Tool currentTool) private
Draw a shape on the canvas.
Definition at line 429 of file qgscomposerview.cpp.
References actionFinished(), QgsComposition::addComposerShape(), AddRectangle, AddTriangle, composition(), QgsComposerShape::Ellipse, mRubberBandItem, QgsComposition::pushAddRemoveCommand(), QgsComposerShape::Rectangle, removeRubberBand(), selectedItemChanged(), QgsComposerItem::setSelected(), QgsComposerShape::setShapeType(), QgsComposerShape::setUseSymbolV2(), tr, and QgsComposerShape::Triangle.
Referenced by mouseReleaseEvent().
void QgsComposerView::composerViewHide (QgsComposerView *) signal
Emitted before composerview is hidden.
Referenced by hideEvent().
void QgsComposerView::composerViewShow (QgsComposerView *) signal
Emitted before composerview is shown.
Referenced by showEvent().
QMainWindow * QgsComposerView::composerWindow ()
Returns the composer main window.
Definition at line 1698 of file qgscomposerview.cpp.
QgsComposition * QgsComposerView::composition ()
Returns the composition or 0 in case of error.
Definition at line 1638 of file qgscomposerview.cpp.
Referenced by addShape(), copyItems(), deleteSelectedItems(), endMarqueeSelect(), groupItems(), keyPressEvent(), keyReleaseEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), pasteItems(), selectAll(), selectInvert(), selectNone(), setCurrentTool(), ungroupItems(), wheelEvent(), and wheelZoom().
void QgsComposerView::compositionSet (QgsComposition *) signal
Emitted when the composition is set for the view.
Referenced by setComposition().
void QgsComposerView::copyItems (ClipboardMode mode)
Cuts or copies the selected items.
Definition at line 1060 of file qgscomposerview.cpp.
References ClipboardModeCopy, ClipboardModeCut, composition(), QgsComposerItemGroup::items(), QgsComposition::removeComposerItem(), and QgsComposition::selectedComposerItems().
QgsComposerView::Tool QgsComposerView::currentTool () const inline
Definition at line 120 of file qgscomposerview.h.
Referenced by wheelEvent().
void QgsComposerView::cursorPosChanged (QPointF) signal
Is emitted when mouse cursor coordinates change.
Referenced by mouseMoveEvent().
QCursor QgsComposerView::defaultCursorForTool (Tool currentTool) private
Returns the default mouse cursor for a tool.
Definition at line 391 of file qgscomposerview.cpp.
References AddArrow, AddEllipse, AddHtml, AddLabel, AddLegend, AddMap, AddPicture, AddRectangle, AddScalebar, AddTable, AddTriangle, cross_hair_cursor, MoveItemContent, Pan, Select, Zoom, and zoom_in.
Referenced by keyReleaseEvent(), mouseReleaseEvent(), and setCurrentTool().
void QgsComposerView::deleteSelectedItems ()
Deletes selected items.
Definition at line 1151 of file qgscomposerview.cpp.
References composition(), QgsComposition::removeComposerItem(), and QgsComposition::selectedComposerItems().
void QgsComposerView::endMarqueeSelect (QMouseEvent * e) private
Finalises a marquee selection.
Definition at line 499 of file qgscomposerview.cpp.
References composition(), mMarqueeSelect, mRubberBandItem, QgsComposerItem::positionLock(), removeRubberBand(), QgsComposition::selectedComposerItems(), selectedItemChanged(), and QgsComposerItem::setSelected().
Referenced by mouseReleaseEvent().
void QgsComposerView::endMarqueeZoom (QMouseEvent * e) private
Finalises a marquee zoom.
Definition at line 585 of file qgscomposerview.cpp.
References ActiveUntilMouseRelease, Inactive, mMarqueeZoom, mPreviousTool, mRubberBandItem, mTemporaryZoomStatus, removeRubberBand(), QgsRectangle::scale(), setCurrentTool(), and QgsRectangle::toRectF().
Referenced by mouseReleaseEvent().
void QgsComposerView::groupItems ()
Add an item group containing the selected items.
Definition at line 1651 of file qgscomposerview.cpp.
References QgsComposerItemGroup::addItem(), composition(), QgsComposition::selectedComposerItems(), selectedItemChanged(), and QgsComposerItem::setSelected().
void QgsComposerView::hideEvent (QHideEvent * e) protected
Definition at line 1597 of file qgscomposerview.cpp.
References composerViewHide().
void QgsComposerView::itemRemoved (QgsComposerItem *) signal
Is emitted when a composer item has been removed from the scene.
Referenced by ungroupItems().
void QgsComposerView::keyPressEvent (QKeyEvent * e) protected
Definition at line 1242 of file qgscomposerview.cpp.
References Active, ActiveUntilMouseRelease, composition(), Inactive, QgsComposerMergeCommand::ItemMove, mCurrentTool, mKeyPanning, mMarqueeZoom, mMouseCurrentXY, mMouseLastXY, mMousePanning, mMovingItemContent, mPreviousTool, mRubberBandItem, mRubberBandLineItem, mTemporaryZoomStatus, mToolPanning, QgsComposition::selectedComposerItems(), setCurrentTool(), QgsComposition::setPreventCursorChange(), tr, Zoom, zoom_in, and zoom_out.
void QgsComposerView::keyReleaseEvent (QKeyEvent * e) protected
Definition at line 1383 of file qgscomposerview.cpp.
References ActiveUntilMouseRelease, composition(), defaultCursorForTool(), Inactive, mCurrentTool, mKeyPanning, mMarqueeZoom, mPreviousTool, mTemporaryZoomStatus, Pan, setCurrentTool(), QgsComposition::setPreventCursorChange(), Zoom, zoom_in, and zoom_out.
void QgsComposerView::mouseDoubleClickEvent (QMouseEvent * e) protected
Definition at line 1055 of file qgscomposerview.cpp.
void QgsComposerView::mouseMoveEvent (QMouseEvent * e) protected
Definition at line 921 of file qgscomposerview.cpp.
References AddArrow, AddEllipse, AddHtml, AddLabel, AddLegend, AddMap, AddPicture, AddRectangle, AddTable, AddTriangle, composition(), cursorPosChanged(), mCurrentTool, mHorizontalRuler, mKeyPanning, mMarqueeSelect, mMarqueeZoom, mMouseCurrentXY, mMouseLastXY, mMousePanning, mMoveContentItem, mMoveContentStartPos, MoveItemContent, mRubberBandLineItem, mRubberBandStartPos, mToolPanning, mVerticalRuler, Select, QgsComposerMap::setOffset(), QgsComposerRuler::updateMarker(), updateRubberBand(), and updateRulers().
void QgsComposerView::mousePressEvent (QMouseEvent * e) protected
Definition at line 131 of file qgscomposerview.cpp.
References actionFinished(), AddArrow, QgsComposition::addComposerScaleBar(), AddEllipse, AddHtml, AddLabel, AddLegend, AddMap, AddPicture, AddRectangle, AddScalebar, AddTable, AddTriangle, QgsComposerScaleBar::applyDefaultSize(), QgsComposition::composerItemAt(), QgsComposition::composerMapItems(), composition(), mCurrentTool, mKeyPanning, mMouseLastXY, mMousePanning, mMousePressStartPos, mMoveContentItem, mMoveContentStartPos, mMovingItemContent, QgsComposerMouseHandles::mouseActionForScenePos(), QgsComposerMouseHandles::MoveItem, MoveItemContent, mRubberBandItem, mRubberBandLineItem, mRubberBandStartPos, mToolPanning, QgsComposerMouseHandles::NoAction, Pan, QgsComposerItem::positionLock(), QgsComposition::pushAddRemoveCommand(), QgsRectangle::scale(), Select, QgsComposerItem::selected(), QgsComposition::selectedComposerItems(), selectedItemChanged(), QgsComposition::selectionHandles(), QgsComposerMouseHandles::SelectItem, QgsComposerScaleBar::setComposerMap(), QgsComposerItem::setPositionLock(), QgsComposition::setPreventCursorChange(), QgsComposerItem::setSceneRect(), QgsComposerItem::setSelected(), QgsComposition::snapPointToGrid(), startMarqueeSelect(), startMarqueeZoom(), QgsRectangle::toRectF(), tr, and Zoom.
void QgsComposerView::mouseReleaseEvent (QMouseEvent * e) protected
Definition at line 626 of file qgscomposerview.cpp.
References actionFinished(), AddArrow, QgsComposition::addComposerArrow(), QgsComposition::addComposerLabel(), QgsComposition::addComposerLegend(), QgsComposition::addComposerMap(), QgsComposition::addComposerPicture(), QgsComposition::addComposerTable(), QgsAddRemoveMultiFrameCommand::Added, AddEllipse, QgsComposerHtml::addFrame(), AddHtml, AddLabel, AddLegend, AddMap, AddPicture, AddRectangle, addShape(), AddTable, AddTriangle, QgsComposerLabel::adjustSizeToText(), QgsComposition::beginCommand(), QgsComposition::beginMultiFrameCommand(), QgsComposition::composerMapItems(), composition(), defaultCursorForTool(), QgsComposition::endCommand(), endMarqueeSelect(), endMarqueeZoom(), QgsComposition::endMultiFrameCommand(), QgsComposerMouseHandles::isDragging(), QgsComposerMouseHandles::isResizing(), mCurrentTool, mMarqueeSelect, mMarqueeZoom, mMousePanning, mMousePressStartPos, mMoveContentItem, mMoveContentStartPos, mMovingItemContent, QgsComposerItem::moveContent(), MoveItemContent, mRubberBandItem, mRubberBandLineItem, mRubberBandStartPos, mToolPanning, Pan, QgsComposition::pushAddRemoveCommand(), removeRubberBand(), QgsRectangle::scale(), Select, selectedItemChanged(), QgsComposition::selectionHandles(), QgsComposerAttributeTable::setComposerMap(), QgsComposerMap::setOffset(), QgsComposition::setPreventCursorChange(), QgsComposerPicture::setSceneRect(), QgsComposerItem::setSceneRect(), QgsComposerAttributeTable::setSceneRect(), QgsComposerItem::setSelected(), QgsComposerLabel::setText(), QgsComposition::snapPointToGrid(), QgsRectangle::toRectF(), tr, QgsComposition::undoStack(), QgsComposerLegend::updateLegend(), and Zoom.
void QgsComposerView::paintEvent (QPaintEvent * event) protected
Definition at line 1584 of file qgscomposerview.cpp.
References mPaintingEnabled.
bool QgsComposerView::paintingEnabled () const inline
Definition at line 135 of file qgscomposerview.h.
void QgsComposerView::pasteItems (PasteMode mode)
Pastes items from clipboard.
Definition at line 1114 of file qgscomposerview.cpp.
References QgsComposition::addItemsFromXML(), composition(), PasteModeCursor, PasteModeInPlace, Select, and setCurrentTool().
void QgsComposerView::removeRubberBand () private
Removes the rubber band and cleans up.
Definition at line 473 of file qgscomposerview.cpp.
References mRubberBandItem.
Referenced by addShape(), endMarqueeSelect(), endMarqueeZoom(), and mouseReleaseEvent().
void QgsComposerView::resizeEvent (QResizeEvent * event) protected
Definition at line 1609 of file qgscomposerview.cpp.
References updateRulers(), and zoomLevelChanged().
void QgsComposerView::scrollContentsBy (int dx, int dy) protected
Definition at line 1616 of file qgscomposerview.cpp.
References updateRulers().
void QgsComposerView::selectAll ()
Selects all items.
Definition at line 1171 of file qgscomposerview.cpp.
References composition(), QgsComposerItem::positionLock(), selectedItemChanged(), and QgsComposerItem::setSelected().
void QgsComposerView::selectedItemChanged (QgsComposerItem * selected) signal
Is emitted when selected item changed.
If 0, no item is selected
Referenced by addShape(), endMarqueeSelect(), groupItems(), mousePressEvent(), mouseReleaseEvent(), selectAll(), and selectInvert().
void QgsComposerView::selectInvert ()
Inverts current selection.
Definition at line 1211 of file qgscomposerview.cpp.
References composition(), QgsComposerItem::positionLock(), QgsComposerItem::selected(), selectedItemChanged(), and QgsComposerItem::setSelected().
void QgsComposerView::selectNone ()
Deselects all items.
Definition at line 1201 of file qgscomposerview.cpp.
References composition().
void QgsComposerView::setComposition (QgsComposition * c)
Sets the composition for the view.
If the composition is being set manually and not by a QgsComposer, then this must be set BEFORE adding any items to the composition.
Definition at line 1622 of file qgscomposerview.cpp.
References compositionSet(), mHorizontalRuler, mVerticalRuler, and QgsComposerRuler::setComposition().
void QgsComposerView::setCurrentTool (QgsComposerView::Tool t)
Definition at line 78 of file qgscomposerview.cpp.
References AddArrow, AddEllipse, AddHtml, AddLabel, AddLegend, AddMap, AddPicture, AddRectangle, AddScalebar, AddTable, AddTriangle, composition(), defaultCursorForTool(), mCurrentTool, Pan, QgsComposition::setPreventCursorChange(), and Zoom.
Referenced by endMarqueeZoom(), keyPressEvent(), keyReleaseEvent(), and pasteItems().
void QgsComposerView::setHorizontalRuler (QgsComposerRuler * r) inline
Definition at line 140 of file qgscomposerview.h.
void QgsComposerView::setPaintingEnabled (bool enabled) inline
Definition at line 134 of file qgscomposerview.h.
void QgsComposerView::setPreviewMode (QgsPreviewEffect::PreviewMode mode)
Sets the preview mode which should be used to modify the view's appearance.
Preview modes are only used if setPreviewMode is set to true.
Parameters
mode PreviewMode to be used to draw the view
Note
added in 2.3
See also
setPreviewModeEnabled
Definition at line 1574 of file qgscomposerview.cpp.
References mPreviewEffect, and QgsPreviewEffect::setMode().
void QgsComposerView::setPreviewModeEnabled (bool enabled)
Sets whether a preview effect should be used to alter the view's appearance.
Parameters
enabled Set to true to enable the preview effect on the view
Note
added in 2.3
See also
setPreviewMode
Definition at line 1564 of file qgscomposerview.cpp.
References mPreviewEffect.
void QgsComposerView::setVerticalRuler (QgsComposerRuler * r) inline
Definition at line 141 of file qgscomposerview.h.
void QgsComposerView::setZoomLevel (double zoomLevel)
Set zoom level, where a zoom level of 1.0 corresponds to 100%.
Definition at line 1548 of file qgscomposerview.cpp.
References updateRulers(), and zoomLevelChanged().
void QgsComposerView::showEvent (QShowEvent * e) protected
Definition at line 1603 of file qgscomposerview.cpp.
References composerViewShow().
void QgsComposerView::startMarqueeSelect (QPointF & scenePoint) private
Starts a marquee selection.
Definition at line 483 of file qgscomposerview.cpp.
References mMarqueeSelect, mRubberBandItem, and mRubberBandStartPos.
Referenced by mousePressEvent().
void QgsComposerView::startMarqueeZoom (QPointF & scenePoint) private
Starts a zoom in marquee.
Definition at line 569 of file qgscomposerview.cpp.
References mMarqueeZoom, mRubberBandItem, and mRubberBandStartPos.
Referenced by mousePressEvent().
void QgsComposerView::ungroupItems ()
Ungroups the selected items.
Definition at line 1676 of file qgscomposerview.cpp.
References composition(), itemRemoved(), QgsComposerItemGroup::removeItems(), and QgsComposition::selectedComposerItems().
void QgsComposerView::updateRubberBand (QPointF & pos) private
Redraws the rubber band.
Definition at line 1014 of file qgscomposerview.cpp.
References mRubberBandItem, and mRubberBandStartPos.
Referenced by mouseMoveEvent().
void QgsComposerView::updateRulers ()
Update rulers with current scene rect.
Definition at line 461 of file qgscomposerview.cpp.
References mHorizontalRuler, mVerticalRuler, and QgsComposerRuler::setSceneTransform().
Referenced by mouseMoveEvent(), resizeEvent(), scrollContentsBy(), setZoomLevel(), and wheelZoom().
void QgsComposerView::wheelEvent (QWheelEvent * event) protected
Definition at line 1431 of file qgscomposerview.cpp.
References QgsComposerItem::beginCommand(), QgsComposition::composerItemAt(), composition(), currentTool(), MoveItemContent, mRubberBandItem, mRubberBandLineItem, tr, and wheelZoom().
void QgsComposerView::wheelZoom (QWheelEvent * event) private
Zoom composition from a mouse wheel event.
Definition at line 1470 of file qgscomposerview.cpp.
References QgsRectangle::center(), composition(), QgsComposerMap::previewMode(), QgsComposerMap::Render, QgsComposerMap::updateCachedImage(), updateRulers(), QgsMapCanvas::WheelNothing, QgsMapCanvas::WheelZoomAndRecenter, QgsMapCanvas::WheelZoomToMouseCursor, and zoomLevelChanged().
Referenced by wheelEvent().
void QgsComposerView::zoomLevelChanged () signal
Is emitted when the view zoom changes.
Referenced by resizeEvent(), setZoomLevel(), and wheelZoom().
Member Data Documentation
QgsComposerView::Tool QgsComposerView::mCurrentTool private
Current composer tool.
Definition at line 181 of file qgscomposerview.h.
Referenced by keyPressEvent(), keyReleaseEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and setCurrentTool().
QgsComposerRuler* QgsComposerView::mHorizontalRuler private
Definition at line 205 of file qgscomposerview.h.
Referenced by mouseMoveEvent(), setComposition(), and updateRulers().
bool QgsComposerView::mKeyPanning private
True if user is currently panning by holding the space key.
Definition at line 216 of file qgscomposerview.h.
Referenced by keyPressEvent(), keyReleaseEvent(), mouseMoveEvent(), and mousePressEvent().
bool QgsComposerView::mMarqueeSelect private
True if user is currently selecting by marquee.
Definition at line 197 of file qgscomposerview.h.
Referenced by endMarqueeSelect(), mouseMoveEvent(), mouseReleaseEvent(), and startMarqueeSelect().
bool QgsComposerView::mMarqueeZoom private
True if user is currently zooming by marquee.
Definition at line 199 of file qgscomposerview.h.
Referenced by endMarqueeZoom(), keyPressEvent(), keyReleaseEvent(), mouseMoveEvent(), mouseReleaseEvent(), and startMarqueeZoom().
QPoint QgsComposerView::mMouseCurrentXY private
Definition at line 222 of file qgscomposerview.h.
Referenced by keyPressEvent(), and mouseMoveEvent().
QPoint QgsComposerView::mMouseLastXY private
Definition at line 221 of file qgscomposerview.h.
Referenced by keyPressEvent(), mouseMoveEvent(), and mousePressEvent().
bool QgsComposerView::mMousePanning private
True if user is currently panning by holding the middle mouse button.
Definition at line 214 of file qgscomposerview.h.
Referenced by keyPressEvent(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPoint QgsComposerView::mMousePressStartPos private
Definition at line 223 of file qgscomposerview.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QgsComposerItem* QgsComposerView::mMoveContentItem private
Item to move content.
Definition at line 190 of file qgscomposerview.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPointF QgsComposerView::mMoveContentStartPos private
Start position of content move.
Definition at line 192 of file qgscomposerview.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool QgsComposerView::mMovingItemContent private
True if user is currently dragging with the move item content tool.
Definition at line 219 of file qgscomposerview.h.
Referenced by keyPressEvent(), mousePressEvent(), and mouseReleaseEvent().
bool QgsComposerView::mPaintingEnabled private
Definition at line 203 of file qgscomposerview.h.
Referenced by paintEvent().
QgsPreviewEffect* QgsComposerView::mPreviewEffect private
Definition at line 225 of file qgscomposerview.h.
Referenced by QgsComposerView(), setPreviewMode(), and setPreviewModeEnabled().
QgsComposerView::Tool QgsComposerView::mPreviousTool private
Previous composer tool.
Definition at line 183 of file qgscomposerview.h.
Referenced by endMarqueeZoom(), keyPressEvent(), and keyReleaseEvent().
QGraphicsRectItem* QgsComposerView::mRubberBandItem private
Rubber band item.
Definition at line 186 of file qgscomposerview.h.
Referenced by addShape(), endMarqueeSelect(), endMarqueeZoom(), keyPressEvent(), mousePressEvent(), mouseReleaseEvent(), removeRubberBand(), startMarqueeSelect(), startMarqueeZoom(), updateRubberBand(), and wheelEvent().
QGraphicsLineItem* QgsComposerView::mRubberBandLineItem private
Rubber band item for arrows.
Definition at line 188 of file qgscomposerview.h.
Referenced by keyPressEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and wheelEvent().
QPointF QgsComposerView::mRubberBandStartPos private
Start of rubber band creation.
Definition at line 194 of file qgscomposerview.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), startMarqueeSelect(), startMarqueeZoom(), and updateRubberBand().
QgsComposerView::ToolStatus QgsComposerView::mTemporaryZoomStatus private
True if user is currently temporarily activating the zoom tool by holding control+space.
Definition at line 201 of file qgscomposerview.h.
Referenced by endMarqueeZoom(), keyPressEvent(), and keyReleaseEvent().
bool QgsComposerView::mToolPanning private
True if user is currently panning by clicking and dragging with the pan tool.
Definition at line 212 of file qgscomposerview.h.
Referenced by keyPressEvent(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QgsComposerRuler* QgsComposerView::mVerticalRuler private
Definition at line 206 of file qgscomposerview.h.
Referenced by mouseMoveEvent(), setComposition(), and updateRulers().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgscomposerview.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgscomposerview.cpp