QGIS API Documentation: QgsAttributeTableFilterModel Class Reference
QgsAttributeTableFilterModel Class Reference
#include <qgsattributetablefiltermodel.h>
Public Types
enum FilterMode {
ShowAll, ShowSelected, ShowVisible, ShowFilteredList,
ShowEdited
}
Public Slots
void extentsChanged ()
Is called upon every change of the visible extents on the map canvas.
Public Member Functions
QgsAttributeTableFilterModel (QgsMapCanvas *canvas, QgsAttributeTableModel *sourceModel, QObject *parent=NULL)
Make sure, the master model is already loaded, so the selection will get synchronized.
void setSourceModel (QgsAttributeTableModel *sourceModel)
void setSelectedOnTop (bool selectedOnTop)
Changes the sort order of the features.
bool selectedOnTop ()
Returns if selected features are currently shown on top.
virtual void setFilteredFeatures (QgsFeatureIds ids)
Specify a list of features, which the filter will accept.
QgsFeatureIds filteredFeatures ()
void setFilterMode (FilterMode filterMode)
Set the filter mode the filter will use.
FilterMode filterMode ()
QgsVectorLayer * layer () const
Returns the layer this filter acts on.
QgsVectorLayerCache * layerCache () const
Returns the layerCache this filter acts on.
QgsAttributeTableModel * masterModel () const
Returns the table model this filter is using.
QgsFeatureId rowToId (const QModelIndex &row)
Returns the feature id for a given model index.
QModelIndex fidToIndex (QgsFeatureId fid)
QModelIndexList fidToIndexList (QgsFeatureId fid)
virtual QModelIndex mapToMaster (const QModelIndex &proxyIndex) const
virtual QModelIndex mapFromMaster (const QModelIndex &sourceIndex) const
Protected Member Functions
bool filterAcceptsRow (int sourceRow, const QModelIndex &sourceParent) const
Returns true if the source row will be accepted.
void generateListOfVisibleFeatures ()
Updates the list of currently visible features on the map canvas.
bool lessThan (const QModelIndex &left, const QModelIndex &right) const
Used by the sorting algorithm.
virtual void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sort by the given column using the given order.
Private Slots
void selectionChanged ()
Private Attributes
QgsFeatureIds mFilteredFeatures
QgsMapCanvas * mCanvas
FilterMode mFilterMode
bool mSelectedOnTop
QgsAttributeTableModel * mTableModel
Detailed Description
Definition at line 31 of file qgsattributetablefiltermodel.h.
Member Enumeration Documentation
enum QgsAttributeTableFilterModel::FilterMode
Enumerator
ShowAll
ShowSelected
ShowVisible
ShowFilteredList
ShowEdited
Definition at line 36 of file qgsattributetablefiltermodel.h.
Constructor & Destructor Documentation
QgsAttributeTableFilterModel::QgsAttributeTableFilterModel (QgsMapCanvas * canvas, QgsAttributeTableModel * sourceModel, QObject * parent = NULL)
Make sure, the master model is already loaded, so the selection will get synchronized.
Parameters
parent parent object (owner)
sourceModel The QgsAttributeTableModel to use as source (mostly referred to as master model)
canvas The mapCanvas. Used to identify the currently visible features.
Definition at line 30 of file qgsattributetablefiltermodel.cpp.
References layer(), selectionChanged(), setSourceModel(), and QgsAttributeTableModel::SortRole.
Member Function Documentation
void QgsAttributeTableFilterModel::extentsChanged () slot
Is called upon every change of the visible extents on the map canvas.
When a change is signalled, the filter is updated and invalidated if needed.
Definition at line 211 of file qgsattributetablefiltermodel.cpp.
References generateListOfVisibleFeatures().
Referenced by setFilterMode().
QModelIndex QgsAttributeTableFilterModel::fidToIndex (QgsFeatureId fid) virtual
Implements QgsFeatureModel.
Definition at line 310 of file qgsattributetablefiltermodel.cpp.
References mapFromMaster(), and masterModel().
QModelIndexList QgsAttributeTableFilterModel::fidToIndexList (QgsFeatureId fid)
Definition at line 315 of file qgsattributetablefiltermodel.cpp.
References mapFromMaster(), and masterModel().
bool QgsAttributeTableFilterModel::filterAcceptsRow (int sourceRow, const QModelIndex & sourceParent) const protected
Returns true if the source row will be accepted.
Parameters
sourceRow row from the source model
sourceParent parent index in the source model
Definition at line 168 of file qgsattributetablefiltermodel.cpp.
References QgsVectorLayerEditBuffer::addedFeatures(), QgsVectorLayerEditBuffer::changedAttributeValues(), QgsVectorLayer::editBuffer(), layer(), masterModel(), mFilteredFeatures, mFilterMode, rowToId(), QgsAttributeTableModel::rowToId(), QgsVectorLayer::selectedFeaturesIds(), ShowAll, ShowEdited, ShowFilteredList, ShowSelected, and ShowVisible.
QgsFeatureIds QgsAttributeTableFilterModel::filteredFeatures ()
Definition at line 133 of file qgsattributetablefiltermodel.cpp.
References index, and rowToId().
FilterMode QgsAttributeTableFilterModel::filterMode () inline
Definition at line 89 of file qgsattributetablefiltermodel.h.
Referenced by setFilterMode().
void QgsAttributeTableFilterModel::generateListOfVisibleFeatures () protected
Updates the list of currently visible features on the map canvas.
Is called automatically when the filter mode is adjusted or the extents changed.
Definition at line 231 of file qgsattributetablefiltermodel.cpp.
References QgsFeatureRendererV2::capabilities(), QgsFeatureIterator::close(), QgsMapCanvas::extent(), QgsFeatureRendererV2::Filter, QgsVectorLayerCache::getFeatures(), QgsFeature::id(), layer(), QgsAttributeTableModel::layerCache(), QgsMapCanvas::mapSettings(), QgsMapSettings::mapToLayerCoordinates(), QgsMapSettings::mapToPixel(), masterModel(), QgsMapLayer::maximumScale(), mCanvas, mFilteredFeatures, QgsFeatureIterator::nextFeature(), QgsDebugMsg, QgsVectorLayer::rendererV2(), QgsMapSettings::scale(), QgsFeatureRendererV2::ScaleDependent, QgsRenderContext::setExtent(), QgsRenderContext::setMapToPixel(), QgsRenderContext::setRendererScale(), QgsFeatureRendererV2::startRender(), QgsFeatureRendererV2::stopRender(), QgsMapSettings::visibleExtent(), and QgsFeatureRendererV2::willRenderFeature().
Referenced by extentsChanged(), selectionChanged(), and setFilterMode().
QgsVectorLayer* QgsAttributeTableFilterModel::layer () const inline
Returns the layer this filter acts on.
Returns
Abovementioned layer
Definition at line 96 of file qgsattributetablefiltermodel.h.
Referenced by QgsAttributeTableView::contextMenuEvent(), QgsFeatureListModel::data(), filterAcceptsRow(), generateListOfVisibleFeatures(), QgsAttributeTableDelegate::layer(), lessThan(), QgsAttributeTableFilterModel(), QgsFeatureListModel::setDisplayExpression(), and QgsAttributeTableView::setModel().
QgsVectorLayerCache* QgsAttributeTableFilterModel::layerCache () const inline
Returns the layerCache this filter acts on.
Returns
The layer cache
Definition at line 103 of file qgsattributetablefiltermodel.h.
Referenced by QgsFeatureListModel::data(), QgsFeatureListModel::featureByIndex(), and QgsFeatureListModel::layerCache().
bool QgsAttributeTableFilterModel::lessThan (const QModelIndex & left, const QModelIndex & right) const protected
Used by the sorting algorithm.
Compares the two model indices. Will also consider the selection state of the feature in case selected features are to be shown on top.
Definition at line 42 of file qgsattributetablefiltermodel.cpp.
References layer(), masterModel(), mSelectedOnTop, rowToId(), QgsVectorLayer::selectedFeaturesIds(), and QgsAttributeTableModel::SortRole.
QModelIndex QgsAttributeTableFilterModel::mapFromMaster (const QModelIndex & sourceIndex) const virtual
Definition at line 332 of file qgsattributetablefiltermodel.cpp.
Referenced by QgsFeatureListModel::fidToIdx(), fidToIndex(), fidToIndexList(), and QgsFeatureListModel::mapFromMaster().
QModelIndex QgsAttributeTableFilterModel::mapToMaster (const QModelIndex & proxyIndex) const virtual
Definition at line 326 of file qgsattributetablefiltermodel.cpp.
Referenced by QgsFeatureListModel::mapToMaster().
QgsAttributeTableModel* QgsAttributeTableFilterModel::masterModel () const inline
Returns the table model this filter is using.
Returns
the table model in quesion
Definition at line 110 of file qgsattributetablefiltermodel.h.
Referenced by QgsFeatureListModel::fidToIdx(), fidToIndex(), fidToIndexList(), filterAcceptsRow(), generateListOfVisibleFeatures(), QgsFeatureListModel::idxToFid(), lessThan(), QgsFeatureListModel::masterModel(), rowToId(), and sort().
QgsFeatureId QgsAttributeTableFilterModel::rowToId (const QModelIndex & row)
Returns the feature id for a given model index.
Parameters
row A model index of the row in question
Returns
The feature id of the feature visible in the provided row
Definition at line 305 of file qgsattributetablefiltermodel.cpp.
References masterModel(), and QgsAttributeTableModel::rowToId().
Referenced by filterAcceptsRow(), filteredFeatures(), and lessThan().
bool QgsAttributeTableFilterModel::selectedOnTop ()
Returns if selected features are currently shown on top.
Returns
True if selected are shown on top
Definition at line 121 of file qgsattributetablefiltermodel.cpp.
References mSelectedOnTop.
Referenced by setSelectedOnTop().
void QgsAttributeTableFilterModel::selectionChanged () private slot
Definition at line 217 of file qgsattributetablefiltermodel.cpp.
References generateListOfVisibleFeatures(), mFilterMode, mSelectedOnTop, ShowSelected, and sort().
Referenced by QgsAttributeTableFilterModel().
void QgsAttributeTableFilterModel::setFilteredFeatures (QgsFeatureIds ids) virtual
Specify a list of features, which the filter will accept.
The filter mode will automatically be adjusted to show only these features (ShowFilteredList).
Parameters
ids The list of feature ids which will be accepted by the filter
Definition at line 126 of file qgsattributetablefiltermodel.cpp.
References mFilteredFeatures, setFilterMode(), and ShowFilteredList.
Referenced by QgsDualView::setFilteredFeatures().
void QgsAttributeTableFilterModel::setFilterMode (FilterMode filterMode)
Set the filter mode the filter will use.
Parameters
filterMode Sets the current mode of the filter
Definition at line 144 of file qgsattributetablefiltermodel.cpp.
References extentsChanged(), filterMode(), generateListOfVisibleFeatures(), mCanvas, mFilterMode, ShowSelected, and ShowVisible.
Referenced by setFilteredFeatures(), and QgsDualView::setFilterMode().
void QgsAttributeTableFilterModel::setSelectedOnTop (bool selectedOnTop)
Changes the sort order of the features.
If set to true, selected features will be sorted on top, regardless of the current sort column
Parameters
selectedOnTop Specify, if selected features should be sorted on top
Definition at line 100 of file qgsattributetablefiltermodel.cpp.
References mSelectedOnTop, selectedOnTop(), and sort().
Referenced by QgsDualView::setSelectedOnTop().
void QgsAttributeTableFilterModel::setSourceModel (QgsAttributeTableModel * sourceModel)
Definition at line 114 of file qgsattributetablefiltermodel.cpp.
References mTableModel.
Referenced by QgsAttributeTableFilterModel().
void QgsAttributeTableFilterModel::sort (int column, Qt::SortOrder order = Qt::AscendingOrder) protected virtual
Sort by the given column using the given order.
Prefetches all the data from the layer to speed up sorting.
Parameters
column The column which should be sorted
order The order (Qt::AscendingOrder or Qt::DescendingOrder)
Definition at line 94 of file qgsattributetablefiltermodel.cpp.
References masterModel(), and QgsAttributeTableModel::prefetchColumnData().
Referenced by selectionChanged(), and setSelectedOnTop().
Member Data Documentation
QgsMapCanvas* QgsAttributeTableFilterModel::mCanvas private
Definition at line 171 of file qgsattributetablefiltermodel.h.
Referenced by generateListOfVisibleFeatures(), and setFilterMode().
QgsFeatureIds QgsAttributeTableFilterModel::mFilteredFeatures private
Definition at line 170 of file qgsattributetablefiltermodel.h.
Referenced by filterAcceptsRow(), generateListOfVisibleFeatures(), and setFilteredFeatures().
FilterMode QgsAttributeTableFilterModel::mFilterMode private
Definition at line 172 of file qgsattributetablefiltermodel.h.
Referenced by filterAcceptsRow(), selectionChanged(), and setFilterMode().
bool QgsAttributeTableFilterModel::mSelectedOnTop private
Definition at line 173 of file qgsattributetablefiltermodel.h.
Referenced by lessThan(), selectedOnTop(), selectionChanged(), and setSelectedOnTop().
QgsAttributeTableModel* QgsAttributeTableFilterModel::mTableModel private
Definition at line 174 of file qgsattributetablefiltermodel.h.
Referenced by setSourceModel().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsattributetablefiltermodel.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsattributetablefiltermodel.cpp