QGIS API Documentation: QgsException Class Reference
QgsException Class Reference
QGIS core library
Defines a qgis exception class.
#include <qgsexception.h>
Public Member Functions
QgsException (QString const &what)
virtual ~QgsException () throw ()
QString what () const throw ()
Private Attributes
QString what_
description of exception
Detailed Description
Defines a qgis exception class.
Definition at line 25 of file qgsexception.h.
Constructor & Destructor Documentation
QgsException::QgsException (QString const & what) inline
Definition at line 28 of file qgsexception.h.
virtual QgsException::~QgsException () throw () inline virtual
Definition at line 32 of file qgsexception.h.
Member Function Documentation
QString QgsException::what () const throw () inline
Definition at line 35 of file qgsexception.h.
Referenced by QgsVectorLayerRenderer::drawRendererV2(), QgsVectorLayerRenderer::drawRendererV2Levels(), QgsVectorFileWriter::exportFeaturesSymbolLevels(), QgsMapToolIdentify::identifyRasterLayer(), QgsMapToolIdentify::identifyVectorLayer(), QgsVectorLayerImport::importLayer(), QgsMapSettings::layerExtentToOutputExtent(), QgsMapRenderer::layerExtentToOutputExtent(), QgsMapSettings::layerToMapCoordinates(), QgsMapRenderer::layerToMapCoordinates(), QgsMapSettings::mapToLayerCoordinates(), QgsMapRenderer::mapToLayerCoordinates(), QgsVectorLayer::metadata(), QgsApplication::notify(), QgsMapSettings::outputExtentToLayerExtent(), QgsMapRenderer::outputExtentToLayerExtent(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsVectorLayerRenderer::render(), QgsMapRendererParallelJob::renderLabelsStatic(), QgsMapRendererParallelJob::renderLayerStatic(), QgsMapRendererCustomPainterJob::staticRender(), and QgsVectorFileWriter::writeAsVectorFormat().
Member Data Documentation
QString QgsException::what_ private
description of exception
Definition at line 43 of file qgsexception.h.
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexception.h