QGIS API Documentation: QgsSvgAnnotationItem Class Reference
QgsSvgAnnotationItem Class Reference
#include <qgssvgannotationitem.h>
Public Member Functions
QgsSvgAnnotationItem (QgsMapCanvas *canvas)
~QgsSvgAnnotationItem ()
void writeXML (QDomDocument &doc) const
void readXML (const QDomDocument &doc, const QDomElement &itemElem)
void paint (QPainter *painter)
function to be implemented by derived classes
void setFilePath (const QString &file)
QString filePath () const
Public Member Functions inherited from QgsAnnotationItem
QgsAnnotationItem (QgsMapCanvas *mapCanvas)
virtual ~QgsAnnotationItem ()
void updatePosition ()
called on changed extent or resize event to update position of the item
QRectF boundingRect () const
default implementation for canvas items
virtual QSizeF minimumFrameSize () const
QgsAnnotationItem::MouseMoveAction moveActionForPosition (const QPointF &pos) const
Returns the mouse move behaviour for a given position.
Qt::CursorShape cursorShapeForAction (MouseMoveAction moveAction) const
Returns suitable cursor shape for mouse move action.
void setMapPositionFixed (bool fixed)
bool mapPositionFixed () const
virtual void setMapPosition (const QgsPoint &pos)
QgsPoint mapPosition () const
void setFrameSize (const QSizeF &size)
QSizeF frameSize () const
void setOffsetFromReferencePoint (const QPointF &offset)
QPointF offsetFromReferencePoint () const
void setMarkerSymbol (QgsMarkerSymbolV2 *symbol)
Set symbol that is drawn on map position.
const QgsMarkerSymbolV2 * markerSymbol () const
void setFrameBorderWidth (double w)
double frameBorderWidth () const
void setFrameColor (const QColor &c)
QColor frameColor () const
void setFrameBackgroundColor (const QColor &c)
QColor frameBackgroundColor () const
void _writeXML (QDomDocument &doc, QDomElement &itemElem) const
void _readXML (const QDomDocument &doc, const QDomElement &annotationElem)
Public Member Functions inherited from QgsMapCanvasItem
Q_DECL_DEPRECATED void setPanningOffset (const QPoint &point)
sets current offset, to be called from QgsMapCanvas
QgsRectangle rect () const
returns canvas item rectangle
void setRect (const QgsRectangle &r)
sets canvas item rectangle
QgsPoint toMapCoordinates (const QPoint &point)
transformation from screen coordinates to map coordinates
QPointF toCanvasCoordinates (const QgsPoint &point)
transformation from map coordinates to screen coordinates
Private Attributes
QSvgRenderer mSvgRenderer
QString mFilePath
Additional Inherited Members
Public Types inherited from QgsAnnotationItem
enum MouseMoveAction {
NoAction, MoveMapPosition, MoveFramePosition, ResizeFrameUp,
ResizeFrameDown, ResizeFrameLeft, ResizeFrameRight, ResizeFrameLeftUp,
ResizeFrameRightUp, ResizeFrameLeftDown, ResizeFrameRightDown
}
Protected Member Functions inherited from QgsAnnotationItem
void updateBoundingRect ()
void updateBalloon ()
Check where to attach the balloon connection between frame and map point.
void drawFrame (QPainter *p)
void drawMarkerSymbol (QPainter *p)
void drawSelectionBoxes (QPainter *p)
QLineF segment (int index)
Returns frame width in painter units.
QPointF pointOnLineWithDistance (const QPointF &startPoint, const QPointF &directionPoint, double distance) const
Returns a point on the line from startPoint to directionPoint that is a certain distance away from the starting point.
double scaledSymbolSize () const
Returns the symbol size scaled in (mapcanvas) pixels.
Protected Member Functions inherited from QgsMapCanvasItem
QgsMapCanvasItem (QgsMapCanvas *mapCanvas)
protected constructor: cannot be constructed directly
virtual ~QgsMapCanvasItem ()
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
paint function called by map canvas
void updateCanvas ()
schedules map canvas for repaint
bool setRenderContextVariables (QPainter *p, QgsRenderContext &context) const
Sets render context parameters.
Protected Attributes inherited from QgsAnnotationItem
bool mMapPositionFixed
True: the item stays at the same map position, False: the item stays on same screen position.
QgsPoint mMapPosition
Map position (in case mMapPositionFixed is true)
QPointF mOffsetFromReferencePoint
Describes the shift of the item content box to the reference point.
QSizeF mFrameSize
Size of the frame (without balloon)
QRectF mBoundingRect
Bounding rect (including item frame and balloon)
QgsMarkerSymbolV2 * mMarkerSymbol
Point symbol that is to be drawn at the map reference location.
double mFrameBorderWidth
Width of the frame.
QColor mFrameColor
Frame / balloon color.
QColor mFrameBackgroundColor
int mBalloonSegment
Segment number where the connection to the map point is attached.
QPointF mBalloonSegmentPoint1
First segment point for drawing the connection (ccw direction)
QPointF mBalloonSegmentPoint2
Second segment point for drawing the balloon connection (ccw direction)
Protected Attributes inherited from QgsMapCanvasItem
QgsMapCanvas * mMapCanvas
pointer to map canvas
QgsRectangle mRect
canvas item rectangle (in map coordinates)
QPoint mPanningOffset
offset from normal position due current panning operation, used when converting map coordinates to move map canvas items
QSizeF mItemSize
cached size of the item (to return in boundingRect())
Detailed Description
Definition at line 24 of file qgssvgannotationitem.h.
Constructor & Destructor Documentation
QgsSvgAnnotationItem::QgsSvgAnnotationItem (QgsMapCanvas * canvas)
Definition at line 24 of file qgssvgannotationitem.cpp.
QgsSvgAnnotationItem::~QgsSvgAnnotationItem ()
Definition at line 29 of file qgssvgannotationitem.cpp.
Member Function Documentation
QString QgsSvgAnnotationItem::filePath () const inline
Definition at line 37 of file qgssvgannotationitem.h.
Referenced by readXML().
void QgsSvgAnnotationItem::paint (QPainter * painter) virtual
function to be implemented by derived classes
Implements QgsMapCanvasItem.
Definition at line 59 of file qgssvgannotationitem.cpp.
References QgsAnnotationItem::drawFrame(), QgsAnnotationItem::drawMarkerSymbol(), QgsAnnotationItem::drawSelectionBoxes(), QgsAnnotationItem::mFrameSize, QgsAnnotationItem::mMapPositionFixed, QgsAnnotationItem::mOffsetFromReferencePoint, and mSvgRenderer.
void QgsSvgAnnotationItem::readXML (const QDomDocument & doc, const QDomElement & itemElem) virtual
Implements QgsAnnotationItem.
Definition at line 48 of file qgssvgannotationitem.cpp.
References QgsAnnotationItem::_readXML(), filePath(), QgsProject::instance(), QgsProject::readPath(), and setFilePath().
void QgsSvgAnnotationItem::setFilePath (const QString & file)
Definition at line 100 of file qgssvgannotationitem.cpp.
References file, mFilePath, and mSvgRenderer.
Referenced by readXML().
void QgsSvgAnnotationItem::writeXML (QDomDocument & doc) const virtual
Implements QgsAnnotationItem.
Definition at line 34 of file qgssvgannotationitem.cpp.
References QgsAnnotationItem::_writeXML(), QgsProject::instance(), and mFilePath.
Member Data Documentation
QString QgsSvgAnnotationItem::mFilePath private
Definition at line 41 of file qgssvgannotationitem.h.
Referenced by setFilePath(), and writeXML().
QSvgRenderer QgsSvgAnnotationItem::mSvgRenderer private
Definition at line 40 of file qgssvgannotationitem.h.
Referenced by paint(), and setFilePath().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgssvgannotationitem.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgssvgannotationitem.cpp