QGIS API Documentation: QgsLineSymbolLayerV2 Class Reference
QgsLineSymbolLayerV2 Class Reference abstract
#include <qgssymbollayerv2.h>
Public Member Functions
virtual void renderPolyline (const QPolygonF &points, QgsSymbolV2RenderContext &context)=0
virtual void renderPolygonOutline (const QPolygonF &points, QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
virtual void setWidth (double width)
virtual double width () const
void setWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit widthUnit () const
void setWidthMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & widthMapUnitScale () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
void setMapUnitScale (const QgsMapUnitScale &scale)
QgsMapUnitScale mapUnitScale () const
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString layerType () const =0
virtual void startRender (QgsSymbolV2RenderContext &context)=0
virtual void stopRender (QgsSymbolV2RenderContext &context)=0
virtual QgsSymbolLayerV2 * clone () const =0
virtual void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
virtual QgsStringMap properties () const =0
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
virtual Qt::PenStyle dxfPenStyle () const
Protected Member Functions
QgsLineSymbolLayerV2 (bool locked=false)
Protected Member Functions inherited from QgsSymbolLayerV2
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsFields *fields, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Protected Attributes
double mWidth
QgsSymbolV2::OutputUnit mWidthUnit
QgsMapUnitScale mWidthMapUnitScale
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Additional Inherited Members
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 259 of file qgssymbollayerv2.h.
Constructor & Destructor Documentation
QgsLineSymbolLayerV2::QgsLineSymbolLayerV2 (bool locked = false) protected
Definition at line 204 of file qgssymbollayerv2.cpp.
Member Function Documentation
void QgsLineSymbolLayerV2::drawPreviewIcon (QgsSymbolV2RenderContext & context, QSize size) virtual
Implements QgsSymbolLayerV2.
Definition at line 385 of file qgssymbollayerv2.cpp.
References renderPolyline(), QgsSymbolLayerV2::startRender(), and QgsSymbolLayerV2::stopRender().
double QgsLineSymbolLayerV2::dxfWidth (const QgsDxfExport & e, const QgsSymbolV2RenderContext & context) const virtual
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsSimpleLineSymbolLayerV2.
Definition at line 407 of file qgssymbollayerv2.cpp.
References width(), and widthUnit().
QgsMapUnitScale QgsLineSymbolLayerV2::mapUnitScale () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 379 of file qgssymbollayerv2.cpp.
References mWidthMapUnitScale.
Referenced by QgsSimpleLineSymbolLayerV2::mapUnitScale(), and QgsMarkerLineSymbolLayerV2::mapUnitScale().
QgsSymbolV2::OutputUnit QgsLineSymbolLayerV2::outputUnit () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 369 of file qgssymbollayerv2.cpp.
References mWidthUnit.
Referenced by QgsSimpleLineSymbolLayerV2::outputUnit(), and QgsMarkerLineSymbolLayerV2::outputUnit().
void QgsLineSymbolLayerV2::renderPolygonOutline (const QPolygonF & points, QList< QPolygonF > * rings, QgsSymbolV2RenderContext & context) virtual
Note
added in v1.7
Reimplemented in QgsSimpleLineSymbolLayerV2.
Definition at line 397 of file qgssymbollayerv2.cpp.
References renderPolyline().
Referenced by QgsSymbolV2::drawPreviewIcon(), and QgsFillSymbolV2::renderPolygon().
virtual void QgsLineSymbolLayerV2::renderPolyline (const QPolygonF & points, QgsSymbolV2RenderContext & context) pure virtual
Implemented in QgsMarkerLineSymbolLayerV2, and QgsSimpleLineSymbolLayerV2.
Referenced by drawPreviewIcon(), renderPolygonOutline(), and QgsLineSymbolV2::renderPolyline().
void QgsLineSymbolLayerV2::setMapUnitScale (const QgsMapUnitScale & scale) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 374 of file qgssymbollayerv2.cpp.
References mWidthMapUnitScale.
Referenced by QgsSimpleLineSymbolLayerV2::setMapUnitScale(), and QgsMarkerLineSymbolLayerV2::setMapUnitScale().
void QgsLineSymbolLayerV2::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 364 of file qgssymbollayerv2.cpp.
References mWidthUnit.
Referenced by QgsSimpleLineSymbolLayerV2::setOutputUnit(), and QgsMarkerLineSymbolLayerV2::setOutputUnit().
virtual void QgsLineSymbolLayerV2::setWidth (double width) inline virtual
Reimplemented in QgsMarkerLineSymbolLayerV2.
Definition at line 267 of file qgssymbollayerv2.h.
Referenced by QgsHighlight::setSymbol(), and QgsLineSymbolV2::setWidth().
void QgsLineSymbolLayerV2::setWidthMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 273 of file qgssymbollayerv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::clone().
void QgsLineSymbolLayerV2::setWidthUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 270 of file qgssymbollayerv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::clone(), and QgsSimpleLineSymbolLayerV2::create().
virtual double QgsLineSymbolLayerV2::width () const inline virtual
Reimplemented in QgsMarkerLineSymbolLayerV2.
Definition at line 268 of file qgssymbollayerv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::create(), QgsSimpleLineSymbolLayerV2::createFromSld(), QgsSimpleLineSymbolLayerV2::dxfWidth(), dxfWidth(), QgsSimpleLineSymbolLayerV2::QgsSimpleLineSymbolLayerV2(), QgsHighlight::setSymbol(), QgsLineSymbolV2::setWidth(), and QgsLineSymbolV2::width().
const QgsMapUnitScale& QgsLineSymbolLayerV2::widthMapUnitScale () const inline
Definition at line 274 of file qgssymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsLineSymbolLayerV2::widthUnit () const inline
Definition at line 271 of file qgssymbollayerv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::dxfWidth(), dxfWidth(), and QgsHighlight::setSymbol().
Member Data Documentation
double QgsLineSymbolLayerV2::mWidth protected
Definition at line 289 of file qgssymbollayerv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleLineSymbolLayerV2::clone(), QgsSimpleLineSymbolLayerV2::dxfWidth(), QgsSimpleLineSymbolLayerV2::estimateMaxBleed(), QgsSimpleLineSymbolLayerV2::ogrFeatureStyle(), QgsSimpleLineSymbolLayerV2::properties(), QgsSimpleLineSymbolLayerV2::QgsSimpleLineSymbolLayerV2(), QgsSimpleLineSymbolLayerV2::startRender(), and QgsSimpleLineSymbolLayerV2::toSld().
QgsMapUnitScale QgsLineSymbolLayerV2::mWidthMapUnitScale protected
Definition at line 291 of file qgssymbollayerv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleLineSymbolLayerV2::clone(), QgsSimpleLineSymbolLayerV2::dxfWidth(), QgsSimpleLineSymbolLayerV2::mapUnitScale(), mapUnitScale(), QgsSimpleLineSymbolLayerV2::properties(), QgsSimpleLineSymbolLayerV2::setMapUnitScale(), setMapUnitScale(), and QgsSimpleLineSymbolLayerV2::startRender().
QgsSymbolV2::OutputUnit QgsLineSymbolLayerV2::mWidthUnit protected
Definition at line 290 of file qgssymbollayerv2.h.
Referenced by QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSimpleLineSymbolLayerV2::clone(), QgsSimpleLineSymbolLayerV2::dxfWidth(), QgsSimpleLineSymbolLayerV2::outputUnit(), outputUnit(), QgsSimpleLineSymbolLayerV2::properties(), QgsSimpleLineSymbolLayerV2::setOutputUnit(), setOutputUnit(), and QgsSimpleLineSymbolLayerV2::startRender().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2.cpp