QGIS API Documentation: QgsProjectFileTransform Class Reference
QgsProjectFileTransform Class Reference
#include <qgsprojectfiletransform.h>
Classes
struct transform
Public Member Functions
~QgsProjectFileTransform ()
QgsProjectFileTransform (QDomDocument &domDocument, QgsProjectVersion version)
bool updateRevision (QgsProjectVersion version)
void dump ()
Static Public Member Functions
static void convertRasterProperties (QDomDocument &doc, QDomNode &parentNode, QDomElement &rasterPropertiesElem, QgsRasterLayer *rlayer)
Private Member Functions
void transformNull ()
void transform081to090 ()
void transform091to0100 ()
void transform0100to0110 ()
void transform0110to1000 ()
void transform1100to1200 ()
void transform1400to1500 ()
void transform1800to1900 ()
void transform2200to2300 ()
Static Private Member Functions
static int rasterBandNumber (const QDomElement &rasterPropertiesElem, const QString &bandName, QgsRasterLayer *rlayer)
static void transformContrastEnhancement (QDomDocument &doc, const QDomElement &rasterproperties, QDomElement &rendererElem)
static void transformRasterTransparency (QDomDocument &doc, const QDomElement &orig, QDomElement &rendererElem)
Private Attributes
QDomDocument mDom
QgsProjectVersion mCurrentVersion
Static Private Attributes
static transform transformers []
Detailed Description
Definition at line 36 of file qgsprojectfiletransform.h.
Constructor & Destructor Documentation
QgsProjectFileTransform::~QgsProjectFileTransform () inline
Definition at line 41 of file qgsprojectfiletransform.h.
QgsProjectFileTransform::QgsProjectFileTransform (QDomDocument & domDocument, QgsProjectVersion version) inline
Create an instance from a Dom and a supplied version
Parameters
domDocument The Dom document to use as content
version Version number
Definition at line 47 of file qgsprojectfiletransform.h.
Member Function Documentation
void QgsProjectFileTransform::convertRasterProperties (QDomDocument & doc, QDomNode & parentNode, QDomElement & rasterPropertiesElem, QgsRasterLayer * rlayer) static
Definition at line 612 of file qgsprojectfiletransform.cpp.
References QgsRasterInterface::bandStatistics(), QgsRasterLayer::dataProvider(), QgsRasterBandStats::maximumValue, QgsRasterBandStats::minimumValue, QgsDebugMsg, rasterBandNumber(), and transformContrastEnhancement().
Referenced by QgsRasterLayer::readSymbology(), and transform1800to1900().
void QgsProjectFileTransform::dump ()
Prints the contents via QgsDebugMsg()
Definition at line 83 of file qgsprojectfiletransform.cpp.
References QgsProjectVersion::majorVersion(), mCurrentVersion, mDom, QgsProjectVersion::minorVersion(), QgsDebugMsg, and QgsProjectVersion::subVersion().
int QgsProjectFileTransform::rasterBandNumber (const QDomElement & rasterPropertiesElem, const QString & bandName, QgsRasterLayer * rlayer) static private
Definition at line 827 of file qgsprojectfiletransform.cpp.
Referenced by convertRasterProperties().
void QgsProjectFileTransform::transform0100to0110 () private
Definition at line 264 of file qgsprojectfiletransform.cpp.
References mDom, outlineWidth, and widthScaleFactor.
void QgsProjectFileTransform::transform0110to1000 () private
Definition at line 305 of file qgsprojectfiletransform.cpp.
References QgsFields::at(), QgsFields::count(), QgsVectorLayer::dataProvider(), QgsVectorDataProvider::fields(), QgsMapLayer::isValid(), and mDom.
void QgsProjectFileTransform::transform081to090 () private
Definition at line 99 of file qgsprojectfiletransform.cpp.
References mDom, and QgsDebugMsg.
void QgsProjectFileTransform::transform091to0100 () private
Definition at line 205 of file qgsprojectfiletransform.cpp.
References mDom, and QgsDebugMsg.
void QgsProjectFileTransform::transform1100to1200 () private
Definition at line 368 of file qgsprojectfiletransform.cpp.
References mDom, QgsDebugMsg, and QgsPropertyValue::writeXML().
void QgsProjectFileTransform::transform1400to1500 () private
Definition at line 402 of file qgsprojectfiletransform.cpp.
References mDom.
void QgsProjectFileTransform::transform1800to1900 () private
Definition at line 463 of file qgsprojectfiletransform.cpp.
References convertRasterProperties(), mDom, QgsDebugMsg, and QgsMapLayer::readLayerXML().
void QgsProjectFileTransform::transform2200to2300 () private
Definition at line 601 of file qgsprojectfiletransform.cpp.
References mDom.
void QgsProjectFileTransform::transformContrastEnhancement (QDomDocument & doc, const QDomElement & rasterproperties, QDomElement & rendererElem) static private
Definition at line 849 of file qgsprojectfiletransform.cpp.
Referenced by convertRasterProperties().
void QgsProjectFileTransform::transformNull () inline private
Definition at line 80 of file qgsprojectfiletransform.h.
void QgsProjectFileTransform::transformRasterTransparency (QDomDocument & doc, const QDomElement & orig, QDomElement & rendererElem) static private
Definition at line 942 of file qgsprojectfiletransform.cpp.
bool QgsProjectFileTransform::updateRevision (QgsProjectVersion version)
Definition at line 62 of file qgsprojectfiletransform.cpp.
References mCurrentVersion, mDom, QgsProjectFileTransform::transform::to, transformers, and QgsProjectFileTransform::transform::transformFunc.
Member Data Documentation
QgsProjectVersion QgsProjectFileTransform::mCurrentVersion private
Definition at line 75 of file qgsprojectfiletransform.h.
Referenced by dump(), and updateRevision().
QDomDocument QgsProjectFileTransform::mDom private
Definition at line 74 of file qgsprojectfiletransform.h.
Referenced by dump(), transform0100to0110(), transform0110to1000(), transform081to090(), transform091to0100(), transform1100to1200(), transform1400to1500(), transform1800to1900(), transform2200to2300(), and updateRevision().
QgsProjectFileTransform::transform QgsProjectFileTransform::transformers static private
Initial value:
=
{
  {PFV( 0, 8, 0 ), PFV( 0, 8, 1 ), &QgsProjectFileTransform::transformNull},
  {PFV( 0, 8, 1 ), PFV( 0, 9, 0 ), &QgsProjectFileTransform::transform081to090},
  {PFV( 0, 9, 0 ), PFV( 0, 9, 1 ), &QgsProjectFileTransform::transformNull},
  {PFV( 0, 9, 1 ), PFV( 0, 10, 0 ), &QgsProjectFileTransform::transform091to0100},
  {PFV( 0, 9, 2 ), PFV( 0, 11, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 0, 10, 0 ), PFV( 0, 11, 0 ), &QgsProjectFileTransform::transform0100to0110},
  {PFV( 0, 11, 0 ), PFV( 1, 0, 0 ), &QgsProjectFileTransform::transform0110to1000},
  {PFV( 1, 0, 0 ), PFV( 1, 1, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 1, 0, 2 ), PFV( 1, 1, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 1, 1, 0 ), PFV( 1, 2, 0 ), &QgsProjectFileTransform::transform1100to1200},
  {PFV( 1, 2, 0 ), PFV( 1, 3, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 1, 3, 0 ), PFV( 1, 4, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 1, 4, 0 ), PFV( 1, 5, 0 ), &QgsProjectFileTransform::transform1400to1500},
  {PFV( 1, 5, 0 ), PFV( 1, 6, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 1, 6, 0 ), PFV( 1, 7, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 1, 7, 0 ), PFV( 1, 8, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 1, 8, 0 ), PFV( 1, 9, 0 ), &QgsProjectFileTransform::transform1800to1900},
  {PFV( 1, 9, 0 ), PFV( 2, 0, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 2, 0, 0 ), PFV( 2, 1, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 2, 1, 0 ), PFV( 2, 2, 0 ), &QgsProjectFileTransform::transformNull},
  {PFV( 2, 2, 0 ), PFV( 2, 3, 0 ), &QgsProjectFileTransform::transform2200to2300},
}
Definition at line 72 of file qgsprojectfiletransform.h.
Referenced by updateRevision().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsprojectfiletransform.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsprojectfiletransform.cpp