QGIS API Documentation: QgsVectorColorBrewerColorRampV2 Class Reference
QgsVectorColorBrewerColorRampV2 Class Reference
#include <qgsvectorcolorrampv2.h>
Public Member Functions
QgsVectorColorBrewerColorRampV2 (QString schemeName=DEFAULT_COLORBREWER_SCHEMENAME, int colors=DEFAULT_COLORBREWER_COLORS)
virtual double value (int index) const
virtual QColor color (double value) const
virtual QString type () const
virtual QgsVectorColorRampV2 * clone () const
virtual QgsStringMap properties () const
QString schemeName () const
virtual int count () const
int colors () const
void setSchemeName (QString schemeName)
void setColors (int colors)
Public Member Functions inherited from QgsVectorColorRampV2
virtual ~QgsVectorColorRampV2 ()
Static Public Member Functions
static QgsVectorColorRampV2 * create (const QgsStringMap &properties=QgsStringMap())
static QStringList listSchemeNames ()
static QList< int > listSchemeVariants (QString schemeName)
Protected Member Functions
void loadPalette ()
Protected Attributes
QString mSchemeName
int mColors
QList< QColor > mPalette
Detailed Description
Definition at line 187 of file qgsvectorcolorrampv2.h.
Constructor & Destructor Documentation
QgsVectorColorBrewerColorRampV2::QgsVectorColorBrewerColorRampV2 (QString schemeName = DEFAULT_COLORBREWER_SCHEMENAME, int colors = DEFAULT_COLORBREWER_COLORS)
Definition at line 392 of file qgsvectorcolorrampv2.cpp.
References loadPalette().
Referenced by clone(), and create().
Member Function Documentation
QgsVectorColorRampV2 * QgsVectorColorBrewerColorRampV2::clone () const virtual
Implements QgsVectorColorRampV2.
Definition at line 443 of file qgsvectorcolorrampv2.cpp.
References mColors, mSchemeName, and QgsVectorColorBrewerColorRampV2().
QColor QgsVectorColorBrewerColorRampV2::color (double value) const virtual
Implements QgsVectorColorRampV2.
Definition at line 432 of file qgsvectorcolorrampv2.cpp.
References mPalette.
int QgsVectorColorBrewerColorRampV2::colors () const inline
Definition at line 207 of file qgsvectorcolorrampv2.h.
Referenced by create().
virtual int QgsVectorColorBrewerColorRampV2::count () const inline virtual
Implements QgsVectorColorRampV2.
Definition at line 206 of file qgsvectorcolorrampv2.h.
QgsVectorColorRampV2 * QgsVectorColorBrewerColorRampV2::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 398 of file qgsvectorcolorrampv2.cpp.
References colors(), DEFAULT_COLORBREWER_COLORS, DEFAULT_COLORBREWER_SCHEMENAME, QgsVectorColorBrewerColorRampV2(), and schemeName().
Referenced by QgsSymbolLayerV2Utils::loadColorRamp().
QStringList QgsVectorColorBrewerColorRampV2::listSchemeNames () static
Definition at line 416 of file qgsvectorcolorrampv2.cpp.
References QgsColorBrewerPalette::listSchemes().
QList< int > QgsVectorColorBrewerColorRampV2::listSchemeVariants (QString schemeName) static
Definition at line 421 of file qgsvectorcolorrampv2.cpp.
References QgsColorBrewerPalette::listSchemeVariants().
void QgsVectorColorBrewerColorRampV2::loadPalette () protected
Definition at line 411 of file qgsvectorcolorrampv2.cpp.
References QgsColorBrewerPalette::listSchemeColors(), mColors, mPalette, and mSchemeName.
Referenced by QgsVectorColorBrewerColorRampV2().
QgsStringMap QgsVectorColorBrewerColorRampV2::properties () const virtual
Implements QgsVectorColorRampV2.
Definition at line 448 of file qgsvectorcolorrampv2.cpp.
References mColors, and mSchemeName.
QString QgsVectorColorBrewerColorRampV2::schemeName () const inline
Definition at line 205 of file qgsvectorcolorrampv2.h.
Referenced by create().
void QgsVectorColorBrewerColorRampV2::setColors (int colors) inline
Definition at line 210 of file qgsvectorcolorrampv2.h.
void QgsVectorColorBrewerColorRampV2::setSchemeName (QString schemeName) inline
Definition at line 209 of file qgsvectorcolorrampv2.h.
virtual QString QgsVectorColorBrewerColorRampV2::type () const inline virtual
Implements QgsVectorColorRampV2.
Definition at line 199 of file qgsvectorcolorrampv2.h.
double QgsVectorColorBrewerColorRampV2::value (int index) const virtual
Implements QgsVectorColorRampV2.
Definition at line 426 of file qgsvectorcolorrampv2.cpp.
References mPalette.
Member Data Documentation
int QgsVectorColorBrewerColorRampV2::mColors protected
Definition at line 220 of file qgsvectorcolorrampv2.h.
Referenced by clone(), loadPalette(), and properties().
QList<QColor> QgsVectorColorBrewerColorRampV2::mPalette protected
Definition at line 221 of file qgsvectorcolorrampv2.h.
Referenced by color(), loadPalette(), and value().
QString QgsVectorColorBrewerColorRampV2::mSchemeName protected
Definition at line 219 of file qgsvectorcolorrampv2.h.
Referenced by clone(), loadPalette(), and properties().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsvectorcolorrampv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsvectorcolorrampv2.cpp