QGIS API Documentation: QgsCoordinateTransform Class Reference
QgsCoordinateTransform Class Reference
QGIS core library
Class for doing transforms between two map coordinate systems.
#include <qgscoordinatetransform.h>
Public Types
enum TransformDirection { ForwardTransform, ReverseTransform }
Enum used to indicate the direction (forward or inverse) of the transform.
Public Slots
void initialise ()
initialise is used to actually create the Transformer instance
bool readXML (QDomNode &theNode)
bool writeXML (QDomNode &theNode, QDomDocument &theDoc)
Signals
void invalidTransformInput () const
Signal when an invalid pj_transform() has occured.
Public Member Functions
QgsCoordinateTransform ()
QgsCoordinateTransform (const QgsCoordinateReferenceSystem &theSource, const QgsCoordinateReferenceSystem &theDest)
Constructs a QgsCoordinateTransform using QgsCoordinateReferenceSystem objects.
QgsCoordinateTransform (long theSourceSrsId, long theDestSrsId)
Constructs a QgsCoordinateTransform using CRS ID of source and destination CRS.
QgsCoordinateTransform (QString theSourceWkt, QString theDestWkt)
QgsCoordinateTransform (long theSourceSrid, QString theDestWkt, QgsCoordinateReferenceSystem::CrsType theSourceCRSType=QgsCoordinateReferenceSystem::PostgisCrsId)
~QgsCoordinateTransform ()
destructor
QgsCoordinateTransform * clone () const
void setSourceCrs (const QgsCoordinateReferenceSystem &theCRS)
void setDestCRS (const QgsCoordinateReferenceSystem &theCRS)
const
QgsCoordinateReferenceSystem & sourceCrs () const
const
QgsCoordinateReferenceSystem & destCRS () const
QgsPoint transform (const QgsPoint p, TransformDirection direction=ForwardTransform) const
QgsPoint transform (const double x, const double y, TransformDirection direction=ForwardTransform) const
QgsRectangle transformBoundingBox (const QgsRectangle theRect, TransformDirection direction=ForwardTransform) const
void transformInPlace (double &x, double &y, double &z, TransformDirection direction=ForwardTransform) const
void transformInPlace (QVector< double > &x, QVector< double > &y, QVector< double > &z, TransformDirection direction=ForwardTransform) const
void transformPolygon (QPolygonF &poly, TransformDirection direction=ForwardTransform) const
QgsRectangle transform (const QgsRectangle theRect, TransformDirection direction=ForwardTransform) const
void transformCoords (const int &numPoint, double *x, double *y, double *z, TransformDirection direction=ForwardTransform) const
bool isInitialised () const
bool isShortCircuited ()
void setDestCRSID (long theCRSID)
int sourceDatumTransform () const
void setSourceDatumTransform (int dt)
int destinationDatumTransform () const
void setDestinationDatumTransform (int dt)
Static Public Member Functions
static QList< QList< int > > datumTransformations (const QgsCoordinateReferenceSystem &srcCRS, const QgsCoordinateReferenceSystem &destCRS)
Returns list of datum transformations for the given src and dest CRS.
static QString datumTransformString (int datumTransform)
static bool datumTransformCrsInfo (int datumTransform, int &epsgNr, QString &srcProjection, QString &dstProjection, QString &remarks, QString &scope, bool &preferred, bool &deprecated)
Gets name of source and dest geographical CRS (to show in a tooltip)
Private Member Functions
void setFinder ()
void addNullGridShifts (QString &srcProjString, QString &destProjString)
In certain situations, null grid shifts have to be added to src / dst proj string.
Static Private Member Functions
static QString stripDatumTransform (const QString &proj4)
Removes +nadgrids and +towgs84 from proj4 string.
static void searchDatumTransform (const QString &sql, QList< int > &transforms)
Private Attributes
bool mShortCircuit
bool mInitialisedFlag
QgsCoordinateReferenceSystem mSourceCRS
QgsCoordinateReferenceSystem mDestCRS
projPJ mSourceProjection
projPJ mDestinationProjection
int mSourceDatumTransform
int mDestinationDatumTransform
Detailed Description
Class for doing transforms between two map coordinate systems.
This class can convert map coordinates to a different coordinate reference system. It is normally associated with a map layer and is used to transform between the layer's coordinate system and the coordinate system of the map canvas, although it can be used in a more general sense to transform coordinates.
All references to source and destination coordinate systems refer to layer and map canvas respectively. All operations are from the perspective of the layer. For example, a forward transformation transforms coordinates from the layers coordinate system to the map canvas.
Definition at line 52 of file qgscoordinatetransform.h.
Member Enumeration Documentation
enum QgsCoordinateTransform::TransformDirection
Enum used to indicate the direction (forward or inverse) of the transform.
Enumerator
ForwardTransform
Transform from source to destination CRS.
ReverseTransform
Transform from destination to source CRS.
Definition at line 94 of file qgscoordinatetransform.h.
Constructor & Destructor Documentation
QgsCoordinateTransform::QgsCoordinateTransform ()
Default constructor. Make sure you use initialised() manually if you use this one!
Definition at line 40 of file qgscoordinatetransform.cpp.
References setFinder().
Referenced by clone().
QgsCoordinateTransform::QgsCoordinateTransform (const QgsCoordinateReferenceSystem & theSource, const QgsCoordinateReferenceSystem & theDest)
Constructs a QgsCoordinateTransform using QgsCoordinateReferenceSystem objects.
Parameters
theSource CRS, typically of the layer's coordinate system
theDest CRS, typically of the map canvas coordinate system
Definition at line 51 of file qgscoordinatetransform.cpp.
References initialise(), mDestCRS, mSourceCRS, and setFinder().
QgsCoordinateTransform::QgsCoordinateTransform (long theSourceSrsId, long theDestSrsId)
Constructs a QgsCoordinateTransform using CRS ID of source and destination CRS.
Definition at line 65 of file qgscoordinatetransform.cpp.
References initialise().
QgsCoordinateTransform::QgsCoordinateTransform (QString theSourceWkt, QString theDestWkt)
Constructs a QgsCoordinateTransform using the Well Known Text representation of the layer and map canvas coordinate systems
Parameters
theSourceWkt Wkt, typically of the layer's coordinate system
theDestWkt Wkt, typically of the map canvas coordinate system
Definition at line 78 of file qgscoordinatetransform.cpp.
References QgsCoordinateReferenceSystem::createFromWkt(), initialise(), mDestCRS, mSourceCRS, and setFinder().
QgsCoordinateTransform::QgsCoordinateTransform (long theSourceSrid, QString theDestWkt, QgsCoordinateReferenceSystem::CrsType theSourceCRSType = QgsCoordinateReferenceSystem::PostgisCrsId)
Constructs a QgsCoordinateTransform using a Spatial Reference Id of the layer and map canvas coordinate system as Wkt
Parameters
theSourceSrid Spatial Ref Id of the layer's coordinate system
theDestWkt Wkt of the map canvas coordinate system
theSourceCRSType On of the enum members defined in QgsCoordinateReferenceSystem::CrsType
Definition at line 96 of file qgscoordinatetransform.cpp.
References QgsCoordinateReferenceSystem::createFromId(), QgsCoordinateReferenceSystem::createFromWkt(), initialise(), mDestCRS, mSourceCRS, and setFinder().
QgsCoordinateTransform::~QgsCoordinateTransform ()
destructor
Definition at line 117 of file qgscoordinatetransform.cpp.
References mDestinationProjection, and mSourceProjection.
Member Function Documentation
void QgsCoordinateTransform::addNullGridShifts (QString & srcProjString, QString & destProjString) private
In certain situations, null grid shifts have to be added to src / dst proj string.
Definition at line 998 of file qgscoordinatetransform.cpp.
References QgsCoordinateReferenceSystem::authid(), mDestCRS, mDestinationDatumTransform, mSourceCRS, and mSourceDatumTransform.
Referenced by initialise().
QgsCoordinateTransform * QgsCoordinateTransform::clone () const
Definition at line 130 of file qgscoordinatetransform.cpp.
References destCRS(), destinationDatumTransform(), initialise(), QgsCoordinateTransform(), setDestinationDatumTransform(), setSourceDatumTransform(), sourceCrs(), sourceDatumTransform(), and tr.
QList< QList< int > > QgsCoordinateTransform::datumTransformations (const QgsCoordinateReferenceSystem & srcCRS, const QgsCoordinateReferenceSystem & destCRS) static
Returns list of datum transformations for the given src and dest CRS.
Note
not available in python bindings
Definition at line 782 of file qgscoordinatetransform.cpp.
References QgsCoordinateReferenceSystem::geographicCRSAuthId(), and searchDatumTransform().
Referenced by QgsMapCanvas::getDatumTransformInfo().
bool QgsCoordinateTransform::datumTransformCrsInfo (int datumTransform, int & epsgNr, QString & srcProjection, QString & dstProjection, QString & remarks, QString & scope, bool & preferred, bool & deprecated) static
Gets name of source and dest geographical CRS (to show in a tooltip)
Returns
epsgNr epsg code of the transformation (or 0 if not in epsg db)
Definition at line 951 of file qgscoordinatetransform.cpp.
References QgsCoordinateReferenceSystem::createFromOgcWmsCrs(), QgsCoordinateReferenceSystem::description(), and QgsApplication::srsDbFilePath().
Referenced by QgsDatumTransformDialog::load().
QString QgsCoordinateTransform::datumTransformString (int datumTransform) static
Definition at line 897 of file qgscoordinatetransform.cpp.
References QgsApplication::srsDbFilePath().
Referenced by initialise(), and QgsDatumTransformDialog::load().
const QgsCoordinateReferenceSystem& QgsCoordinateTransform::destCRS () const inline
Get the QgsCoordinateReferenceSystem representation of the map canvas coordinate system
Returns
QgsCoordinateReferenceSystem of the map canvas coordinate system
Definition at line 122 of file qgscoordinatetransform.h.
Referenced by QgsDistanceArea::_copy(), clone(), QgsVectorFileWriter::createSymbolLayerTable(), QgsVectorFileWriter::exportFeaturesSymbolLevels(), QgsDistanceArea::measureLine(), operator<<(), QgsMapRenderer::outputExtentToLayerExtent(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsMapRendererJob::reprojectToLayerExtent(), and QgsVectorFileWriter::writeAsVectorFormat().
int QgsCoordinateTransform::destinationDatumTransform () const inline
Definition at line 230 of file qgscoordinatetransform.h.
Referenced by clone(), and QgsRasterLayerRenderer::QgsRasterLayerRenderer().
void QgsCoordinateTransform::initialise () slot
initialise is used to actually create the Transformer instance
Definition at line 159 of file qgscoordinatetransform.cpp.
References addNullGridShifts(), QgsCoordinateReferenceSystem::authid(), QgsCRSCache::crsByAuthId(), datumTransformString(), QgsCRSCache::instance(), QgsCoordinateReferenceSystem::isValid(), mDestCRS, mDestinationDatumTransform, mDestinationProjection, mInitialisedFlag, mShortCircuit, mSourceCRS, mSourceDatumTransform, mSourceProjection, QgsDebugMsg, QgsDebugMsgLevel, stripDatumTransform(), and QgsCoordinateReferenceSystem::toProj4().
Referenced by clone(), QgsCoordinateTransform(), readXML(), setDestCRS(), setDestCRSID(), setSourceCrs(), and QgsCoordinateTransformCache::transform().
void QgsCoordinateTransform::invalidTransformInput () const signal
Signal when an invalid pj_transform() has occured.
Referenced by transformCoords().
bool QgsCoordinateTransform::isInitialised () const inline
Flag to indicate whether the coordinate systems have been initialised
Returns
true if initialised, otherwise false
Definition at line 201 of file qgscoordinatetransform.h.
Referenced by operator<<().
bool QgsCoordinateTransform::isShortCircuited () inline
See if the transform short circuits because src and dest are equivalent
Returns
bool True if it short circuits
Definition at line 206 of file qgscoordinatetransform.h.
Referenced by operator<<().
bool QgsCoordinateTransform::readXML (QDomNode & theNode) slot
Restores state from the given Dom node.
Parameters
theNode The node from which state will be restored
Returns
bool True on success, False on failure
Definition at line 715 of file qgscoordinatetransform.cpp.
References initialise(), mDestCRS, mDestinationDatumTransform, mSourceCRS, mSourceDatumTransform, QgsDebugMsg, and QgsCoordinateReferenceSystem::readXML().
void QgsCoordinateTransform::searchDatumTransform (const QString & sql, QList< int > & transforms) static private
Definition at line 870 of file qgscoordinatetransform.cpp.
References QgsApplication::srsDbFilePath().
Referenced by datumTransformations().
void QgsCoordinateTransform::setDestCRS (const QgsCoordinateReferenceSystem & theCRS)
Mutator for dest QgsCoordinateReferenceSystem
Parameters
theCRS of the destination coordinate system
Definition at line 144 of file qgscoordinatetransform.cpp.
References initialise(), and mDestCRS.
Referenced by QgsAtlasComposition::computeExtent(), and QgsDistanceArea::setEllipsoid().
void QgsCoordinateTransform::setDestCRSID (long theCRSID)
Change the destination coordinate system by passing it a qgis srsid A QGIS srsid is a unique key value to an entry on the tbl_srs in the srs.db sqlite database.
Note
This slot will usually be called if the project properties change and a different coordinate system is selected.
This coord transform will be reinitialised when this slot is called to check if short circuiting is needed or not etc.
Parameters
theCRSID - A long representing the srsid of the srs to be used
todo Add some logic here to determine if the srsid is a system or user one
Definition at line 150 of file qgscoordinatetransform.cpp.
References QgsCoordinateReferenceSystem::createFromSrsId(), initialise(), and mDestCRS.
void QgsCoordinateTransform::setDestinationDatumTransform (int dt) inline
Definition at line 231 of file qgscoordinatetransform.h.
Referenced by clone(), and QgsCoordinateTransformCache::transform().
void QgsCoordinateTransform::setFinder () private
Finder for PROJ grid files.
Definition at line 766 of file qgscoordinatetransform.cpp.
References finder().
Referenced by QgsCoordinateTransform().
void QgsCoordinateTransform::setSourceCrs (const QgsCoordinateReferenceSystem & theCRS)
Set the source (layer) QgsCoordinateReferenceSystem
Parameters
theCRS QgsCoordinateReferenceSystem representation of the layer's coordinate system
Definition at line 139 of file qgscoordinatetransform.cpp.
References initialise(), and mSourceCRS.
Referenced by QgsAtlasComposition::computeExtent(), QgsDistanceArea::setSourceAuthId(), and QgsDistanceArea::setSourceCrs().
void QgsCoordinateTransform::setSourceDatumTransform (int dt) inline
Definition at line 229 of file qgscoordinatetransform.h.
Referenced by clone(), and QgsCoordinateTransformCache::transform().
const QgsCoordinateReferenceSystem& QgsCoordinateTransform::sourceCrs () const inline
Get the QgsCoordinateReferenceSystem representation of the layer's coordinate system
Returns
QgsCoordinateReferenceSystem of the layer's coordinate system
Definition at line 116 of file qgscoordinatetransform.h.
Referenced by QgsDistanceArea::_copy(), clone(), QgsDistanceArea::convertMeasurement(), QgsDistanceArea::measureLine(), operator<<(), QgsMapRenderer::outputExtentToLayerExtent(), and QgsVectorLayerRenderer::render().
int QgsCoordinateTransform::sourceDatumTransform () const inline
Definition at line 228 of file qgscoordinatetransform.h.
Referenced by clone(), and QgsRasterLayerRenderer::QgsRasterLayerRenderer().
QString QgsCoordinateTransform::stripDatumTransform (const QString & proj4) static private
Removes +nadgrids and +towgs84 from proj4 string.
Definition at line 850 of file qgscoordinatetransform.cpp.
Referenced by initialise().
QgsPoint QgsCoordinateTransform::transform (const QgsPoint p, TransformDirection direction = ForwardTransform) const
Transform the point from Source Coordinate System to Destination Coordinate System If the direction is ForwardTransform then coordinates are transformed from layer CS –> map canvas CS, otherwise points are transformed from map canvas CS to layerCS.
Parameters
p Point to transform
direction TransformDirection (defaults to ForwardTransform)
Returns
QgsPoint in Destination Coordinate System
Definition at line 276 of file qgscoordinatetransform.cpp.
References mInitialisedFlag, mShortCircuit, QgsDebugMsg, transformCoords(), QgsPoint::x(), and QgsPoint::y().
Referenced by QgsDistanceArea::bearing(), QgsRasterProjector::calcCP(), QgsRasterProjector::checkCols(), QgsRasterProjector::checkRows(), QgsMapRenderer::layerToMapCoordinates(), QgsMapRenderer::mapToLayerCoordinates(), QgsDistanceArea::measureLine(), QgsDistanceArea::measurePolygon(), QgsVectorLayerRenderer::render(), QgsInvertedPolygonRenderer::renderFeature(), QgsLabel::renderLabel(), QgsMapRendererJob::reprojectToLayerExtent(), QgsRasterLayerSaveAsDialog::setResolution(), QgsMapRenderer::splitLayersExtent(), transform(), and transformBoundingBox().
QgsPoint QgsCoordinateTransform::transform (const double x, const double y = 0, TransformDirection direction = ForwardTransform) const
Transform the point specified by x,y from Source Coordinate System to Destination Coordinate System If the direction is ForwardTransform then coordinates are transformed from layer CS –> map canvas CS, otherwise points are transformed from map canvas CS to layerCS.
Parameters
x x cordinate of point to transform
y y coordinate of point to transform
direction TransformDirection (defaults to ForwardTransform)
Returns
QgsPoint in Destination Coordinate System
Definition at line 299 of file qgscoordinatetransform.cpp.
References QgsDebugMsg, and transform().
QgsRectangle QgsCoordinateTransform::transform (const QgsRectangle theRect, TransformDirection direction = ForwardTransform) const
Transform a QgsRectangle to the dest Coordinate system If the direction is ForwardTransform then coordinates are transformed from layer CS –> map canvas CS, otherwise points are transformed from map canvas CS to layerCS.
Parameters
theRect rect to transform
direction TransformDirection (defaults to ForwardTransform)
Returns
QgsRectangle in Destination Coordinate System
Definition at line 313 of file qgscoordinatetransform.cpp.
References mInitialisedFlag, mShortCircuit, QgsDebugMsg, transformCoords(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
QgsRectangle QgsCoordinateTransform::transformBoundingBox (const QgsRectangle theRect, TransformDirection direction = ForwardTransform) const
Transform a QgsRectangle to the dest Coordinate system If the direction is ForwardTransform then coordinates are transformed from layer CS –> map canvas CS, otherwise points are transformed from map canvas CS to layerCS. It assumes that rect is a bounding box, and creates a bounding box in the proejcted CS, so that all points in source rectangle is within returned rectangle.
Parameters
theRect rect to transform
direction TransformDirection (defaults to ForwardTransform)
Returns
QgsRectangle in Destination Coordinate System
Definition at line 523 of file qgscoordinatetransform.cpp.
References QgsRectangle::combineExtentWith(), QgsRectangle::height(), QgsRectangle::isEmpty(), mInitialisedFlag, mShortCircuit, QgsDebugMsg, QgsRectangle::setMinimal(), QgsRectangle::toString(), transform(), transformCoords(), QgsRectangle::width(), QgsRectangle::xMinimum(), and QgsRectangle::yMinimum().
Referenced by QgsMapRenderer::layerExtentToOutputExtent(), QgsMapRenderer::outputExtentToLayerExtent(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsMapRendererJob::reprojectToLayerExtent(), QgsMapRenderer::setDestinationCrs(), QgsExtentGroupBox::setOutputExtent(), and QgsMapRenderer::splitLayersExtent().
void QgsCoordinateTransform::transformCoords (const int & numPoint, double * x, double * y, double * z, TransformDirection direction = ForwardTransform) const
Transform an array of coordinates to a different Coordinate System If the direction is ForwardTransform then coordinates are transformed from layer CS –> map canvas CS, otherwise points are transformed from map canvas CS to layerCS.
Parameters
numPoint number of coordinates in arrays
x array of x coordinates to transform
y array of y coordinates to transform
z array of z coordinates to transform
direction TransformDirection (defaults to ForwardTransform)
Returns
QgsRectangle in Destination Coordinate System
Definition at line 609 of file qgscoordinatetransform.cpp.
References ForwardTransform, invalidTransformInput(), QgsCoordinateReferenceSystem::isValid(), QgsMessageLog::logMessage(), mDestCRS, mDestinationProjection, mSourceCRS, mSourceProjection, QgsDebugMsg, ReverseTransform, QgsCoordinateReferenceSystem::toProj4(), and tr.
Referenced by transform(), transformBoundingBox(), transformInPlace(), and transformPolygon().
void QgsCoordinateTransform::transformInPlace (double & x, double & y, double & z, TransformDirection direction = ForwardTransform) const
Definition at line 349 of file qgscoordinatetransform.cpp.
References mInitialisedFlag, mShortCircuit, QgsDebugMsg, and transformCoords().
Referenced by QgsFeatureRendererV2::_getPoint(), QgsRasterProjector::preciseSrcRowCol(), QgsPalLabeling::registerDiagramFeature(), QgsPalLayerSettings::registerFeature(), and QgsGeometry::transformVertex().
void QgsCoordinateTransform::transformInPlace (QVector< double > & x, QVector< double > & y, QVector< double > & z, TransformDirection direction = ForwardTransform) const
Note
not available in python bindings
Definition at line 411 of file qgscoordinatetransform.cpp.
References mInitialisedFlag, mShortCircuit, QgsDebugMsg, and transformCoords().
void QgsCoordinateTransform::transformPolygon (QPolygonF & poly, TransformDirection direction = ForwardTransform) const
Definition at line 370 of file qgscoordinatetransform.cpp.
References mInitialisedFlag, mShortCircuit, QgsDebugMsg, and transformCoords().
Referenced by QgsFeatureRendererV2::_getLineString(), and QgsFeatureRendererV2::_getPolygon().
bool QgsCoordinateTransform::writeXML (QDomNode & theNode, QDomDocument & theDoc) slot
Stores state to the given Dom node in the given document
Parameters
theNode The node in which state will be restored
theDoc The document in which state will be stored
Returns
bool True on success, False on failure
Definition at line 734 of file qgscoordinatetransform.cpp.
References mDestCRS, mDestinationDatumTransform, mSourceCRS, mSourceDatumTransform, and QgsCoordinateReferenceSystem::writeXML().
Member Data Documentation
QgsCoordinateReferenceSystem QgsCoordinateTransform::mDestCRS private
QgsCoordinateReferenceSystem of the destination (map canvas) coordinate system
Definition at line 275 of file qgscoordinatetransform.h.
Referenced by addNullGridShifts(), initialise(), QgsCoordinateTransform(), readXML(), setDestCRS(), setDestCRSID(), transformCoords(), and writeXML().
int QgsCoordinateTransform::mDestinationDatumTransform private
Definition at line 288 of file qgscoordinatetransform.h.
Referenced by addNullGridShifts(), initialise(), readXML(), and writeXML().
projPJ QgsCoordinateTransform::mDestinationProjection private
Proj4 data structure of the destination projection (map canvas coordinate system)
Definition at line 285 of file qgscoordinatetransform.h.
Referenced by initialise(), transformCoords(), and ~QgsCoordinateTransform().
bool QgsCoordinateTransform::mInitialisedFlag private
flag to show whether the transform is properly initialised or not
Definition at line 265 of file qgscoordinatetransform.h.
Referenced by initialise(), transform(), transformBoundingBox(), transformInPlace(), and transformPolygon().
bool QgsCoordinateTransform::mShortCircuit private
Flag to indicate that the source and destination coordinate systems are equal and not transformation needs to be done
Definition at line 260 of file qgscoordinatetransform.h.
Referenced by initialise(), transform(), transformBoundingBox(), transformInPlace(), and transformPolygon().
QgsCoordinateReferenceSystem QgsCoordinateTransform::mSourceCRS private
QgsCoordinateReferenceSystem of the source (layer) coordinate system
Definition at line 270 of file qgscoordinatetransform.h.
Referenced by addNullGridShifts(), initialise(), QgsCoordinateTransform(), readXML(), setSourceCrs(), transformCoords(), and writeXML().
int QgsCoordinateTransform::mSourceDatumTransform private
Definition at line 287 of file qgscoordinatetransform.h.
Referenced by addNullGridShifts(), initialise(), readXML(), and writeXML().
projPJ QgsCoordinateTransform::mSourceProjection private
Proj4 data structure of the source projection (layer coordinate system)
Definition at line 280 of file qgscoordinatetransform.h.
Referenced by initialise(), transformCoords(), and ~QgsCoordinateTransform().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgscoordinatetransform.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgscoordinatetransform.cpp