QGIS API Documentation: QgsVectorLayerSelectionManager Class Reference
QgsVectorLayerSelectionManager Class Reference
#include <qgsvectorlayerselectionmanager.h>
Public Member Functions
QgsVectorLayerSelectionManager (QgsVectorLayer *layer, QObject *parent=0)
virtual int selectedFeatureCount ()
The number of features that are selected in this layer.
virtual void select (const QgsFeatureIds &ids)
Select features.
virtual void deselect (const QgsFeatureIds &ids)
Deselect features.
virtual void setSelectedFeatures (const QgsFeatureIds &ids)
Change selection to the new set of features.
virtual const QgsFeatureIds & selectedFeaturesIds () const
Return reference to identifiers of selected features.
Public Member Functions inherited from QgsIFeatureSelectionManager
QgsIFeatureSelectionManager (QObject *parent)
Private Attributes
QgsVectorLayer * mLayer
Additional Inherited Members
Signals inherited from QgsIFeatureSelectionManager
void selectionChanged (const QgsFeatureIds selected, const QgsFeatureIds deselected, const bool clearAndSelect)
This signal is emitted when selection was changed.
Detailed Description
Definition at line 23 of file qgsvectorlayerselectionmanager.h.
Constructor & Destructor Documentation
QgsVectorLayerSelectionManager::QgsVectorLayerSelectionManager (QgsVectorLayer * layer, QObject * parent = 0) explicit
Definition at line 20 of file qgsvectorlayerselectionmanager.cpp.
References mLayer, and QgsIFeatureSelectionManager::selectionChanged().
Member Function Documentation
void QgsVectorLayerSelectionManager::deselect (const QgsFeatureIds & ids) virtual
Deselect features.
Parameters
ids Feature ids to deselect
Implements QgsIFeatureSelectionManager.
Definition at line 37 of file qgsvectorlayerselectionmanager.cpp.
References QgsVectorLayer::deselect(), and mLayer.
void QgsVectorLayerSelectionManager::select (const QgsFeatureIds & ids) virtual
Select features.
Parameters
ids Feature ids to select
Implements QgsIFeatureSelectionManager.
Definition at line 32 of file qgsvectorlayerselectionmanager.cpp.
References mLayer, and QgsVectorLayer::select().
int QgsVectorLayerSelectionManager::selectedFeatureCount () virtual
The number of features that are selected in this layer.
Returns
See description
Implements QgsIFeatureSelectionManager.
Definition at line 27 of file qgsvectorlayerselectionmanager.cpp.
References mLayer, and QgsVectorLayer::selectedFeatureCount().
const QgsFeatureIds & QgsVectorLayerSelectionManager::selectedFeaturesIds () const virtual
Return reference to identifiers of selected features.
Returns
A list of QgsFeatureIds
See also
selectedFeatures()
Implements QgsIFeatureSelectionManager.
Definition at line 47 of file qgsvectorlayerselectionmanager.cpp.
References mLayer, and QgsVectorLayer::selectedFeaturesIds().
void QgsVectorLayerSelectionManager::setSelectedFeatures (const QgsFeatureIds & ids) virtual
Change selection to the new set of features.
Dismisses the current selection. Will emit the selectionChanged(QgsFeatureIds, QgsFeatureIds, bool) signal with the clearAndSelect flag set.
Parameters
ids The ids which will be the new selection
Implements QgsIFeatureSelectionManager.
Definition at line 42 of file qgsvectorlayerselectionmanager.cpp.
References mLayer, and QgsVectorLayer::setSelectedFeatures().
Member Data Documentation
QgsVectorLayer* QgsVectorLayerSelectionManager::mLayer private
Definition at line 68 of file qgsvectorlayerselectionmanager.h.
Referenced by deselect(), QgsVectorLayerSelectionManager(), select(), selectedFeatureCount(), selectedFeaturesIds(), and setSelectedFeatures().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsvectorlayerselectionmanager.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsvectorlayerselectionmanager.cpp