QGIS API Documentation: QgsVectorLayerEditUtils Class Reference
QgsVectorLayerEditUtils Class Reference
#include <qgsvectorlayereditutils.h>
Public Member Functions
QgsVectorLayerEditUtils (QgsVectorLayer *layer)
QgsGeometryCache * cache ()
bool insertVertex (double x, double y, QgsFeatureId atFeatureId, int beforeVertex)
Insert a new vertex before the given vertex number, in the given ring, item (first number is index 0), and feature Not meaningful for Point geometries.
bool moveVertex (double x, double y, QgsFeatureId atFeatureId, int atVertex)
Moves the vertex at the given position number, ring and item (first number is index 0), and feature to the given coordinates.
bool deleteVertex (QgsFeatureId atFeatureId, int atVertex)
Deletes a vertex from a feature.
int addRing (const QList< QgsPoint > &ring)
Adds a ring to polygon/multipolygon features.
int addPart (const QList< QgsPoint > &ring, QgsFeatureId featureId)
Adds a new part polygon to a multipart feature.
int translateFeature (QgsFeatureId featureId, double dx, double dy)
Translates feature by dx, dy.
int splitParts (const QList< QgsPoint > &splitLine, bool topologicalEditing=false)
Splits parts cut by the given line.
int splitFeatures (const QList< QgsPoint > &splitLine, bool topologicalEditing=false)
Splits features cut by the given line.
int addTopologicalPoints (QgsGeometry *geom)
Adds topological points for every vertex of the geometry.
int addTopologicalPoints (const QgsPoint &p)
Adds a vertex to segments which intersect point p but don't already have a vertex there.
int insertSegmentVerticesForSnap (const QList< QgsSnappingResult > &snapResults)
Inserts vertices to the snapped segments.
Protected Member Functions
int boundingBoxFromPointList (const QList< QgsPoint > &list, double &xmin, double &ymin, double &xmax, double &ymax) const
Little helper function that gives bounding box from a list of points.
Protected Attributes
QgsVectorLayer * L
Detailed Description
Definition at line 25 of file qgsvectorlayereditutils.h.
Constructor & Destructor Documentation
QgsVectorLayerEditUtils::QgsVectorLayerEditUtils (QgsVectorLayer * layer)
Definition at line 25 of file qgsvectorlayereditutils.cpp.
Member Function Documentation
int QgsVectorLayerEditUtils::addPart (const QList< QgsPoint > & ring, QgsFeatureId featureId)
Adds a new part polygon to a multipart feature.
Returns
0 in case of success, 1 if selected feature is not multipart, 2 if ring is not a valid geometry, 3 if new polygon ring not disjoint with existing rings, 4 if no feature was selected, 5 if several features are selected, 6 if selected geometry not found
Definition at line 138 of file qgsvectorlayereditutils.cpp.
References QgsGeometry::addPart(), cache(), QgsVectorLayerEditBuffer::changeGeometry(), QgsVectorLayer::editBuffer(), QgsGeometryCache::geometry(), QgsFeature::geometry(), QgsVectorLayer::geometryType(), QgsVectorLayer::getFeatures(), QgsVectorLayer::hasGeometryType(), L, and QgsFeatureIterator::nextFeature().
Referenced by QgsVectorLayer::addPart().
int QgsVectorLayerEditUtils::addRing (const QList< QgsPoint > & ring)
Adds a ring to polygon/multipolygon features.
Returns
0 in case of success, 1 problem with feature type, 2 ring not closed, 3 ring not valid, 4 ring crosses existing rings, 5 no feature found where ring can be inserted
Definition at line 100 of file qgsvectorlayereditutils.cpp.
References QgsGeometry::addRing(), boundingBoxFromPointList(), QgsVectorLayerEditBuffer::changeGeometry(), QgsVectorLayer::editBuffer(), QgsFeatureRequest::ExactIntersect, QgsFeature::geometry(), QgsVectorLayer::getFeatures(), QgsVectorLayer::hasGeometryType(), QgsFeature::id(), L, QgsFeatureIterator::nextFeature(), QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsRectangle::setYMaximum(), and QgsRectangle::setYMinimum().
Referenced by QgsVectorLayer::addRing().
int QgsVectorLayerEditUtils::addTopologicalPoints (QgsGeometry * geom)
Adds topological points for every vertex of the geometry.
Parameters
geom the geometry where each vertex is added to segments of other features
Note
geom is not going to be modified by the function
Returns
0 in case of success
Definition at line 462 of file qgsvectorlayereditutils.cpp.
References QgsGeometry::asMultiPolygon(), QgsGeometry::asMultiPolyline(), QgsGeometry::asPolygon(), QgsGeometry::asPolyline(), QgsVectorLayer::hasGeometryType(), L, QGis::WKBLineString, QGis::WKBLineString25D, QGis::WKBMultiLineString, QGis::WKBMultiLineString25D, QGis::WKBMultiPolygon, QGis::WKBMultiPolygon25D, QGis::WKBPolygon, QGis::WKBPolygon25D, and QgsGeometry::wkbType().
Referenced by QgsVectorLayer::addTopologicalPoints(), splitFeatures(), and splitParts().
int QgsVectorLayerEditUtils::addTopologicalPoints (const QgsPoint & p)
Adds a vertex to segments which intersect point p but don't already have a vertex there.
If a feature already has a vertex at position p, no additional vertex is inserted. This method is useful for topological editing.
Parameters
p position of the vertex
Returns
0 in case of success
Definition at line 570 of file qgsvectorlayereditutils.cpp.
References QgsMapLayer::crs(), QGis::Feet, QgsVectorLayer::hasGeometryType(), insertSegmentVerticesForSnap(), L, QgsCoordinateReferenceSystem::mapUnits(), QGis::Meters, QgsSnapper::SnapToSegment, QgsSnapper::SnapToVertex, and QgsVectorLayer::snapWithContext().
int QgsVectorLayerEditUtils::boundingBoxFromPointList (const QList< QgsPoint > & list, double & xmin, double & ymin, double & xmax, double & ymax) const protected
Little helper function that gives bounding box from a list of points.
Returns
0 in case of success
Definition at line 654 of file qgsvectorlayereditutils.cpp.
References MathUtils::max().
Referenced by addRing(), splitFeatures(), and splitParts().
QgsGeometryCache* QgsVectorLayerEditUtils::cache () inline
Definition at line 30 of file qgsvectorlayereditutils.h.
Referenced by addPart(), deleteVertex(), insertVertex(), moveVertex(), and translateFeature().
bool QgsVectorLayerEditUtils::deleteVertex (QgsFeatureId atFeatureId, int atVertex)
Deletes a vertex from a feature.
Definition at line 76 of file qgsvectorlayereditutils.cpp.
References cache(), QgsVectorLayerEditBuffer::changeGeometry(), QgsGeometry::deleteVertex(), QgsVectorLayer::editBuffer(), QgsGeometryCache::geometry(), QgsFeature::geometry(), QgsVectorLayer::getFeatures(), QgsVectorLayer::hasGeometryType(), L, and QgsFeatureIterator::nextFeature().
Referenced by QgsVectorLayer::deleteVertex().
int QgsVectorLayerEditUtils::insertSegmentVerticesForSnap (const QList< QgsSnappingResult > & snapResults)
Inserts vertices to the snapped segments.
This is useful for topological editing if snap to segment is enabled.
Parameters
snapResults results collected from the snapping operation
Returns
0 in case of success
Definition at line 628 of file qgsvectorlayereditutils.cpp.
References QgsVectorLayer::hasGeometryType(), insertVertex(), L, QgsPoint::x(), and QgsPoint::y().
Referenced by addTopologicalPoints(), and QgsVectorLayer::insertSegmentVerticesForSnap().
bool QgsVectorLayerEditUtils::insertVertex (double x, double y, QgsFeatureId atFeatureId, int beforeVertex)
Insert a new vertex before the given vertex number, in the given ring, item (first number is index 0), and feature Not meaningful for Point geometries.
Definition at line 30 of file qgsvectorlayereditutils.cpp.
References cache(), QgsVectorLayerEditBuffer::changeGeometry(), QgsVectorLayer::editBuffer(), QgsGeometryCache::geometry(), QgsFeature::geometry(), QgsVectorLayer::getFeatures(), QgsVectorLayer::hasGeometryType(), QgsGeometry::insertVertex(), L, and QgsFeatureIterator::nextFeature().
Referenced by insertSegmentVerticesForSnap(), and QgsVectorLayer::insertVertex().
bool QgsVectorLayerEditUtils::moveVertex (double x, double y, QgsFeatureId atFeatureId, int atVertex)
Moves the vertex at the given position number, ring and item (first number is index 0), and feature to the given coordinates.
Definition at line 53 of file qgsvectorlayereditutils.cpp.
References cache(), QgsVectorLayerEditBuffer::changeGeometry(), QgsVectorLayer::editBuffer(), QgsGeometryCache::geometry(), QgsFeature::geometry(), QgsVectorLayer::getFeatures(), QgsVectorLayer::hasGeometryType(), L, QgsGeometry::moveVertex(), and QgsFeatureIterator::nextFeature().
Referenced by QgsVectorLayer::moveVertex().
int QgsVectorLayerEditUtils::splitFeatures (const QList< QgsPoint > & splitLine, bool topologicalEditing = false)
Splits features cut by the given line.
Parameters
splitLine line that splits the layer features
topologicalEditing true if topological editing is enabled
Returns
0 in case of success, 4 if there is a selection but no feature split
Definition at line 189 of file qgsvectorlayereditutils.cpp.
References QgsVectorLayerEditBuffer::addFeatures(), addTopologicalPoints(), boundingBoxFromPointList(), QgsVectorLayerEditBuffer::changeGeometry(), QgsMapLayer::crs(), QgsVectorLayer::dataProvider(), QgsVectorDataProvider::defaultValue(), QgsVectorLayer::editBuffer(), QgsFeatureRequest::ExactIntersect, QgsCoordinateReferenceSystem::geographicFlag(), QgsVectorLayer::getFeatures(), QgsVectorLayer::hasGeometryType(), QgsRectangle::height(), QgsRectangle::isEmpty(), L, QgsFeatureIterator::nextFeature(), QgsVectorDataProvider::pkAttributeIndexes(), QgsVectorLayer::selectedFeatures(), QgsVectorLayer::selectedFeaturesIds(), QgsFeature::setAttributes(), QgsFeature::setGeometry(), QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsRectangle::setYMaximum(), QgsRectangle::setYMinimum(), QgsGeometry::splitGeometry(), QgsRectangle::width(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by QgsVectorLayer::splitFeatures().
int QgsVectorLayerEditUtils::splitParts (const QList< QgsPoint > & splitLine, bool topologicalEditing = false)
Splits parts cut by the given line.
Parameters
splitLine line that splits the layer feature parts
topologicalEditing true if topological editing is enabled
Returns
0 in case of success, 4 if there is a selection but no feature split
Definition at line 327 of file qgsvectorlayereditutils.cpp.
References QgsGeometry::addPart(), addTopologicalPoints(), boundingBoxFromPointList(), QgsVectorLayerEditBuffer::changeGeometry(), QgsMapLayer::crs(), QgsVectorLayer::editBuffer(), QgsFeatureRequest::ExactIntersect, QgsCoordinateReferenceSystem::geographicFlag(), QgsFeature::geometry(), QgsVectorLayer::getFeatures(), QgsVectorLayer::hasGeometryType(), QgsRectangle::height(), QgsFeature::id(), QgsRectangle::isEmpty(), L, QgsFeatureIterator::nextFeature(), QgsDebugMsg, QgsVectorLayer::selectedFeatures(), QgsVectorLayer::selectedFeaturesIds(), QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsRectangle::setYMaximum(), QgsRectangle::setYMinimum(), QgsGeometry::splitGeometry(), QgsRectangle::width(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by QgsVectorLayer::splitParts().
int QgsVectorLayerEditUtils::translateFeature (QgsFeatureId featureId, double dx, double dy)
Translates feature by dx, dy.
Parameters
featureId id of the feature to translate
dx translation of x-coordinate
dy translation of y-coordinate
Returns
0 in case of success
Definition at line 164 of file qgsvectorlayereditutils.cpp.
References cache(), QgsVectorLayerEditBuffer::changeGeometry(), QgsVectorLayer::editBuffer(), QgsGeometryCache::geometry(), QgsFeature::geometry(), QgsVectorLayer::getFeatures(), QgsVectorLayer::hasGeometryType(), L, QgsFeatureIterator::nextFeature(), and QgsGeometry::translate().
Referenced by QgsVectorLayer::translateFeature().
Member Data Documentation
QgsVectorLayer* QgsVectorLayerEditUtils::L protected
Definition at line 124 of file qgsvectorlayereditutils.h.
Referenced by addPart(), addRing(), addTopologicalPoints(), deleteVertex(), insertSegmentVerticesForSnap(), insertVertex(), moveVertex(), splitFeatures(), splitParts(), and translateFeature().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsvectorlayereditutils.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsvectorlayereditutils.cpp