QGIS API Documentation: QgsBlendModeComboBox Class Reference
QgsBlendModeComboBox Class Reference
QGIS gui library.
A combobox which lets the user select blend modes from a predefined list.
#include <qgsblendmodecombobox.h>
Public Slots
void updateModes ()
Public Member Functions
QgsBlendModeComboBox (QWidget *parent=0)
virtual ~QgsBlendModeComboBox ()
QPainter::CompositionMode blendMode ()
Function to read the selected blend mode as QPainter::CompositionMode.
void setBlendMode (QPainter::CompositionMode blendMode)
Function to set the selected blend mode from QPainter::CompositionMode.
Private Member Functions
QStringList blendModesList () const
Returns a list of grouped blend modes (with seperators)
Private Attributes
std::vector< int > mBlendModeToListIndex
Used to map blend modes across to their corresponding.
std::vector< int > mListIndexToBlendMode
Detailed Description
A combobox which lets the user select blend modes from a predefined list.
Definition at line 28 of file qgsblendmodecombobox.h.
Constructor & Destructor Documentation
QgsBlendModeComboBox::QgsBlendModeComboBox (QWidget * parent = 0)
Definition at line 27 of file qgsblendmodecombobox.cpp.
References updateModes().
QgsBlendModeComboBox::~QgsBlendModeComboBox () virtual
Definition at line 32 of file qgsblendmodecombobox.cpp.
Member Function Documentation
QPainter::CompositionMode QgsBlendModeComboBox::blendMode ()
Function to read the selected blend mode as QPainter::CompositionMode.
Function to read the selected blend mode.
Definition at line 102 of file qgsblendmodecombobox.cpp.
References QgsMapRenderer::getCompositionMode(), and mListIndexToBlendMode.
QStringList QgsBlendModeComboBox::blendModesList () const private
Returns a list of grouped blend modes (with seperators)
Definition at line 41 of file qgsblendmodecombobox.cpp.
References tr.
Referenced by updateModes().
void QgsBlendModeComboBox::setBlendMode (QPainter::CompositionMode blendMode)
Function to set the selected blend mode from QPainter::CompositionMode.
Function to set the selected blend mode.
Definition at line 108 of file qgsblendmodecombobox.cpp.
References QgsMapRenderer::getBlendModeEnum(), and mBlendModeToListIndex.
void QgsBlendModeComboBox::updateModes () slot
Definition at line 65 of file qgsblendmodecombobox.cpp.
References blendModesList(), index, mBlendModeToListIndex, and mListIndexToBlendMode.
Referenced by QgsBlendModeComboBox().
Member Data Documentation
std::vector<int> QgsBlendModeComboBox::mBlendModeToListIndex private
Used to map blend modes across to their corresponding.
Definition at line 45 of file qgsblendmodecombobox.h.
Referenced by setBlendMode(), and updateModes().
std::vector<int> QgsBlendModeComboBox::mListIndexToBlendMode private
Definition at line 46 of file qgsblendmodecombobox.h.
Referenced by blendMode(), and updateModes().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsblendmodecombobox.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsblendmodecombobox.cpp