QGIS API Documentation: QgsSingleCategoryDiagramRenderer Class Reference
QgsSingleCategoryDiagramRenderer Class Reference
Renders the diagrams for all features with the same settings.
#include <qgsdiagramrendererv2.h>
Public Member Functions
QgsSingleCategoryDiagramRenderer ()
~QgsSingleCategoryDiagramRenderer ()
QgsDiagramRendererV2 * clone () const
Returns new instance that is equivalent to this one.
QString rendererName () const
QList< QString > diagramAttributes () const
Returns attribute indices needed for diagram rendering.
void setDiagramSettings (const QgsDiagramSettings &s)
QList< QgsDiagramSettings > diagramSettings () const
Returns list with all diagram settings in the renderer.
void readXML (const QDomElement &elem, const QgsVectorLayer *layer)
void writeXML (QDomElement &layerElem, QDomDocument &doc, const QgsVectorLayer *layer) const
Public Member Functions inherited from QgsDiagramRendererV2
QgsDiagramRendererV2 ()
virtual ~QgsDiagramRendererV2 ()
virtual QSizeF sizeMapUnits (const QgsFeature &feature, const QgsRenderContext &c)
Returns size of the diagram for a feature in map units.
void renderDiagram (const QgsFeature &feature, QgsRenderContext &c, const QPointF &pos)
void setDiagram (QgsDiagram *d)
QgsDiagram * diagram () const
Protected Member Functions
bool diagramSettings (const QgsFeature &feature, const QgsRenderContext &c, QgsDiagramSettings &s)
Returns diagram settings for a feature (or false if the diagram for the feature is not to be rendered).
QSizeF diagramSize (const QgsFeature &, const QgsRenderContext &c)
Returns size of the diagram (in painter units) or an invalid size in case of error.
Protected Member Functions inherited from QgsDiagramRendererV2
QgsDiagramRendererV2 (const QgsDiagramRendererV2 &other)
void convertSizeToMapUnits (QSizeF &size, const QgsRenderContext &context) const
Converts size from mm to map units.
void _readXML (const QDomElement &elem, const QgsVectorLayer *layer)
void _writeXML (QDomElement &rendererElem, QDomDocument &doc, const QgsVectorLayer *layer) const
Private Attributes
QgsDiagramSettings mSettings
Additional Inherited Members
Static Protected Member Functions inherited from QgsDiagramRendererV2
static int dpiPaintDevice (const QPainter *)
Returns the paint device dpi (or -1 in case of error.
Protected Attributes inherited from QgsDiagramRendererV2
QgsDiagram * mDiagram
Reference to the object that does the real diagram rendering.
Detailed Description
Renders the diagrams for all features with the same settings.
Definition at line 213 of file qgsdiagramrendererv2.h.
Constructor & Destructor Documentation
QgsSingleCategoryDiagramRenderer::QgsSingleCategoryDiagramRenderer ()
Definition at line 385 of file qgsdiagramrendererv2.cpp.
Referenced by clone().
QgsSingleCategoryDiagramRenderer::~QgsSingleCategoryDiagramRenderer ()
Definition at line 389 of file qgsdiagramrendererv2.cpp.
Member Function Documentation
QgsDiagramRendererV2 * QgsSingleCategoryDiagramRenderer::clone () const virtual
Returns new instance that is equivalent to this one.
Note
added in 2.4
Implements QgsDiagramRendererV2.
Definition at line 393 of file qgsdiagramrendererv2.cpp.
References QgsSingleCategoryDiagramRenderer().
QList<QString> QgsSingleCategoryDiagramRenderer::diagramAttributes () const inline virtual
Returns attribute indices needed for diagram rendering.
Implements QgsDiagramRendererV2.
Definition at line 223 of file qgsdiagramrendererv2.h.
QList< QgsDiagramSettings > QgsSingleCategoryDiagramRenderer::diagramSettings () const virtual
Returns list with all diagram settings in the renderer.
Implements QgsDiagramRendererV2.
Definition at line 410 of file qgsdiagramrendererv2.cpp.
References mSettings.
bool QgsSingleCategoryDiagramRenderer::diagramSettings (const QgsFeature & feature, const QgsRenderContext & c, QgsDiagramSettings & s) protected virtual
Returns diagram settings for a feature (or false if the diagram for the feature is not to be rendered).
Used internally within renderDiagram()
Parameters
feature the feature
c render context
s out: diagram settings for the feature
Implements QgsDiagramRendererV2.
Definition at line 398 of file qgsdiagramrendererv2.cpp.
References mSettings.
QSizeF QgsSingleCategoryDiagramRenderer::diagramSize (const QgsFeature & features, const QgsRenderContext & c) protected virtual
Returns size of the diagram (in painter units) or an invalid size in case of error.
Implements QgsDiagramRendererV2.
Definition at line 405 of file qgsdiagramrendererv2.cpp.
References QgsFeature::attributes(), QgsDiagramRendererV2::mDiagram, and mSettings.
void QgsSingleCategoryDiagramRenderer::readXML (const QDomElement & elem, const QgsVectorLayer * layer) virtual
Implements QgsDiagramRendererV2.
Definition at line 417 of file qgsdiagramrendererv2.cpp.
References QgsDiagramRendererV2::_readXML(), mSettings, and QgsDiagramSettings::readXML().
QString QgsSingleCategoryDiagramRenderer::rendererName () const inline virtual
Implements QgsDiagramRendererV2.
Definition at line 221 of file qgsdiagramrendererv2.h.
void QgsSingleCategoryDiagramRenderer::setDiagramSettings (const QgsDiagramSettings & s) inline
Definition at line 225 of file qgsdiagramrendererv2.h.
void QgsSingleCategoryDiagramRenderer::writeXML (QDomElement & layerElem, QDomDocument & doc, const QgsVectorLayer * layer) const virtual
Implements QgsDiagramRendererV2.
Definition at line 429 of file qgsdiagramrendererv2.cpp.
References QgsDiagramRendererV2::_writeXML(), mSettings, and QgsDiagramSettings::writeXML().
Member Data Documentation
QgsDiagramSettings QgsSingleCategoryDiagramRenderer::mSettings private
Definition at line 238 of file qgsdiagramrendererv2.h.
Referenced by diagramSettings(), diagramSize(), readXML(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdiagramrendererv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdiagramrendererv2.cpp