QGIS API Documentation: QgsLegacyHelpers Class Reference
QgsLegacyHelpers Class Reference
#include <qgslegacyhelpers.h>
Static Public Member Functions
static Q_DECL_DEPRECATED const
QString convertEditType (QgsVectorLayer::EditType editType, QgsEditorWidgetConfig &cfg, QgsVectorLayer *vl, const QString &name, const QDomElement editTypeElement=QDomElement())
static Q_DECL_DEPRECATED
QgsVectorLayer::EditType convertEditType (const QString &editType, const QgsEditorWidgetConfig &cfg, QgsVectorLayer *vl, const QString &name)
Private Member Functions
QgsLegacyHelpers ()
Detailed Description
Definition at line 23 of file qgslegacyhelpers.h.
Constructor & Destructor Documentation
QgsLegacyHelpers::QgsLegacyHelpers () inline private
Definition at line 30 of file qgslegacyhelpers.h.
Member Function Documentation
const QString QgsLegacyHelpers::convertEditType (QgsVectorLayer::EditType editType, QgsEditorWidgetConfig & cfg, QgsVectorLayer * vl, const QString & name, const QDomElement editTypeElement = QDomElement()) static
Definition at line 20 of file qgslegacyhelpers.cpp.
References QgsVectorLayer::Calendar, QgsVectorLayer::CheckBox, QgsVectorLayer::Classification, QgsVectorLayer::Color, QgsVectorLayer::DialRange, QgsVectorLayer::EditorWidgetV2, QgsVectorLayer::EditRange, QgsVectorLayer::Enumeration, QgsFields::fieldNameIndex(), QgsVectorLayer::FileName, QgsVectorLayer::Hidden, QgsVectorLayer::Immutable, QgsVectorLayer::LineEdit, QgsVectorLayer::pendingFields(), QgsVectorLayer::Photo, QgsVectorLayer::setFieldEditable(), QgsVectorLayer::SliderRange, QgsVectorLayer::TextEdit, QgsVectorLayer::UniqueValues, QgsVectorLayer::UniqueValuesEditable, QgsVectorLayer::UuidGenerator, QgsVectorLayer::ValueMap, QgsVectorLayer::ValueRelation, and QgsVectorLayer::WebView.
Referenced by QgsVectorLayer::editType(), and QgsVectorLayer::setEditType().
QgsVectorLayer::EditType QgsLegacyHelpers::convertEditType (const QString & editType, const QgsEditorWidgetConfig & cfg, QgsVectorLayer * vl, const QString & name) static
Definition at line 207 of file qgslegacyhelpers.cpp.
References QgsVectorLayer::Calendar, QgsVectorLayer::CheckBox, QgsVectorLayer::Classification, QgsVectorLayer::Color, QgsVectorLayer::DialRange, QgsVectorLayer::EditorWidgetV2, QgsVectorLayer::EditRange, QgsVectorLayer::Enumeration, QgsVectorLayer::fieldEditable(), QgsVectorLayer::fieldNameIndex(), QgsVectorLayer::FileName, QgsVectorLayer::Hidden, QgsVectorLayer::Immutable, QgsVectorLayer::LineEdit, QgsVectorLayer::Photo, QgsVectorLayer::SliderRange, QgsVectorLayer::TextEdit, QgsVectorLayer::UniqueValues, QgsVectorLayer::UniqueValuesEditable, QgsVectorLayer::UuidGenerator, QgsVectorLayer::ValueMap, and QgsVectorLayer::WebView.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgslegacyhelpers.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgslegacyhelpers.cpp