QGIS API Documentation: QgsAttributeFormInterface Class Reference
QgsAttributeFormInterface Class Reference
#include <qgsattributeforminterface.h>
Public Member Functions
QgsAttributeFormInterface (QgsAttributeForm *form)
virtual bool acceptChanges (const QgsFeature &feature)
virtual void initForm ()
virtual void featureChanged ()
QgsAttributeForm * form ()
const QgsFeature & feature ()
Private Attributes
QgsAttributeForm * mForm
Detailed Description
Definition at line 22 of file qgsattributeforminterface.h.
Constructor & Destructor Documentation
QgsAttributeFormInterface::QgsAttributeFormInterface (QgsAttributeForm * form) explicit
Definition at line 21 of file qgsattributeforminterface.cpp.
Member Function Documentation
bool QgsAttributeFormInterface::acceptChanges (const QgsFeature & feature) virtual
Definition at line 26 of file qgsattributeforminterface.cpp.
Referenced by QgsAttributeForm::save().
const QgsFeature & QgsAttributeFormInterface::feature ()
Definition at line 46 of file qgsattributeforminterface.cpp.
References QgsAttributeForm::feature(), and mForm.
Referenced by QgsAttributeFormLegacyInterface::featureChanged().
void QgsAttributeFormInterface::featureChanged () virtual
Reimplemented in QgsAttributeFormLegacyInterface.
Definition at line 36 of file qgsattributeforminterface.cpp.
Referenced by QgsAttributeForm::setFeature().
QgsAttributeForm * QgsAttributeFormInterface::form ()
Definition at line 41 of file qgsattributeforminterface.cpp.
References mForm.
Referenced by QgsAttributeFormLegacyInterface::featureChanged().
void QgsAttributeFormInterface::initForm () virtual
Definition at line 32 of file qgsattributeforminterface.cpp.
Referenced by QgsAttributeForm::init().
Member Data Documentation
QgsAttributeForm* QgsAttributeFormInterface::mForm private
Definition at line 38 of file qgsattributeforminterface.h.
Referenced by feature(), and form().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsattributeforminterface.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsattributeforminterface.cpp