QGIS API Documentation: QgsExpressionBuilderWidget Class Reference
QgsExpressionBuilderWidget Class Reference
A reusable widget that can be used to build a expression string.
#include <qgsexpressionbuilderwidget.h>
Public Slots
void currentChanged (const QModelIndex &index, const QModelIndex &)
void on_expressionTree_doubleClicked (const QModelIndex &index)
void on_txtExpressionString_textChanged ()
void on_txtSearchEdit_textChanged ()
void on_lblPreview_linkActivated (QString link)
void on_mValueListWidget_itemDoubleClicked (QListWidgetItem *item)
void operatorButtonClicked ()
void showContextMenu (const QPoint &)
void loadSampleValues ()
void loadAllValues ()
Signals
void expressionParsed (bool isValid)
Emitted when the user changes the expression in the widget.
Public Member Functions
QgsExpressionBuilderWidget (QWidget *parent)
~QgsExpressionBuilderWidget ()
void setLayer (QgsVectorLayer *layer)
Sets layer in order to get the fields and values.
void loadFieldNames ()
Loads all the field names from the layer.
void loadFieldNames (const QgsFields &fields)
void setGeomCalculator (const QgsDistanceArea &da)
Sets geometry calculator used in distance/area calculations.
QString expressionText ()
Gets the expression string that has been set in the expression area.
void setExpressionText (const QString &expression)
Sets the expression string for the widget.
void registerItem (QString group, QString label, QString expressionText, QString helpText="", QgsExpressionItem::ItemType type=QgsExpressionItem::ExpressionNode)
Registers a node item for the expression builder.
bool isExpressionValid ()
void saveToRecent (QString key)
void loadRecent (QString key)
Private Slots
void setExpressionState (bool state)
Private Member Functions
void fillFieldValues (int fieldIndex, int countLimit)
QString loadFunctionHelp (QgsExpressionItem *functionName)
Private Attributes
QgsVectorLayer * mLayer
QStandardItemModel * mModel
QgsExpressionItemSearchProxy * mProxyModel
QMap< QString,
QgsExpressionItem * > mExpressionGroups
QgsFeature mFeature
QgsExpressionHighlighter * highlighter
bool mExpressionValid
QgsDistanceArea mDa
Detailed Description
A reusable widget that can be used to build a expression string.
See QgsExpressionBuilderDialog for exmaple of usage.
Definition at line 107 of file qgsexpressionbuilderwidget.h.
Constructor & Destructor Documentation
QgsExpressionBuilderWidget::QgsExpressionBuilderWidget (QWidget * parent)
Definition at line 28 of file qgsexpressionbuilderwidget.cpp.
References currentChanged(), expressionParsed(), QgsExpression::functionCount(), QgsExpression::Functions(), QgsExpression::Function::group(), QgsExpression::Function::helptext(), highlighter, loadAllValues(), loadSampleValues(), mModel, mProxyModel, QgsExpression::Function::name(), operatorButtonClicked(), QgsExpression::Function::params(), registerItem(), setExpressionState(), showContextMenu(), QgsExpression::specialColumns(), and tr.
QgsExpressionBuilderWidget::~QgsExpressionBuilderWidget ()
Definition at line 115 of file qgsexpressionbuilderwidget.cpp.
Member Function Documentation
void QgsExpressionBuilderWidget::currentChanged (const QModelIndex & index, const QModelIndex &) slot
Definition at line 127 of file qgsexpressionbuilderwidget.cpp.
References QgsExpressionItem::Field, QgsExpressionItem::getItemType(), loadFunctionHelp(), mLayer, mModel, and mProxyModel.
Referenced by QgsExpressionBuilderWidget().
void QgsExpressionBuilderWidget::expressionParsed (bool isValid) signal
Emitted when the user changes the expression in the widget.
Users of this widget should connect to this signal to decide if to let the user continue.
Parameters
isValid Is true if the expression the user has typed is valid.
Referenced by on_txtExpressionString_textChanged(), and QgsExpressionBuilderWidget().
QString QgsExpressionBuilderWidget::expressionText ()
Gets the expression string that has been set in the expression area.
Returns
The expression as a string.
Definition at line 290 of file qgsexpressionbuilderwidget.cpp.
Referenced by saveToRecent().
void QgsExpressionBuilderWidget::fillFieldValues (int fieldIndex, int countLimit) private
Definition at line 191 of file qgsexpressionbuilderwidget.cpp.
References mLayer, and QgsVectorLayer::uniqueValues().
Referenced by loadAllValues(), and loadSampleValues().
bool QgsExpressionBuilderWidget::isExpressionValid ()
Definition at line 244 of file qgsexpressionbuilderwidget.cpp.
References mExpressionValid.
void QgsExpressionBuilderWidget::loadAllValues () slot
Definition at line 437 of file qgsexpressionbuilderwidget.cpp.
References QgsVectorLayer::fieldNameIndex(), fillFieldValues(), mLayer, mModel, and mProxyModel.
Referenced by QgsExpressionBuilderWidget(), and showContextMenu().
void QgsExpressionBuilderWidget::loadFieldNames ()
Loads all the field names from the layer.
Remarks
Should this really be public couldn't we just do this for the user?
Definition at line 165 of file qgsexpressionbuilderwidget.cpp.
References mLayer, and QgsVectorLayer::pendingFields().
void QgsExpressionBuilderWidget::loadFieldNames (const QgsFields & fields)
Definition at line 175 of file qgsexpressionbuilderwidget.cpp.
References QgsExpressionHighlighter::addFields(), QgsFields::count(), QgsExpressionItem::Field, highlighter, QgsFields::isEmpty(), and registerItem().
QString QgsExpressionBuilderWidget::loadFunctionHelp (QgsExpressionItem * functionName) private
Definition at line 456 of file qgsexpressionbuilderwidget.cpp.
References QgsExpressionItem::Field, QgsExpressionItem::getHelpText(), QgsExpressionItem::getItemType(), QgsExpression::helptext(), and QgsApplication::reportStyleSheet().
Referenced by currentChanged().
void QgsExpressionBuilderWidget::loadRecent (QString key)
Definition at line 267 of file qgsexpressionbuilderwidget.cpp.
References mExpressionGroups, registerItem(), and tr.
Referenced by saveToRecent().
void QgsExpressionBuilderWidget::loadSampleValues () slot
Definition at line 423 of file qgsexpressionbuilderwidget.cpp.
References QgsVectorLayer::fieldNameIndex(), fillFieldValues(), mLayer, mModel, and mProxyModel.
Referenced by QgsExpressionBuilderWidget(), and showContextMenu().
void QgsExpressionBuilderWidget::on_expressionTree_doubleClicked (const QModelIndex & index) slot
Definition at line 149 of file qgsexpressionbuilderwidget.cpp.
References QgsExpressionItem::getExpressionText(), QgsExpressionItem::getItemType(), QgsExpressionItem::Header, mModel, and mProxyModel.
void QgsExpressionBuilderWidget::on_lblPreview_linkActivated (QString link) slot
Definition at line 384 of file qgsexpressionbuilderwidget.cpp.
References QgsMessageViewer::setMessageAsHtml(), and tr.
void QgsExpressionBuilderWidget::on_mValueListWidget_itemDoubleClicked (QListWidgetItem * item) slot
Definition at line 393 of file qgsexpressionbuilderwidget.cpp.
void QgsExpressionBuilderWidget::on_txtExpressionString_textChanged () slot
Definition at line 300 of file qgsexpressionbuilderwidget.cpp.
References QgsExpression::evalErrorString(), QgsExpression::evaluate(), expressionParsed(), QgsVectorLayer::getFeatures(), QgsExpression::hasEvalError(), QgsExpression::hasParserError(), QgsFeature::isValid(), mDa, mFeature, mLayer, QgsFeatureIterator::nextFeature(), QgsExpression::parserErrorString(), QgsVectorLayer::pendingFields(), QgsExpression::setGeomCalculator(), and tr.
void QgsExpressionBuilderWidget::on_txtSearchEdit_textChanged () slot
Definition at line 375 of file qgsexpressionbuilderwidget.cpp.
References mProxyModel.
void QgsExpressionBuilderWidget::operatorButtonClicked () slot
Definition at line 399 of file qgsexpressionbuilderwidget.cpp.
Referenced by QgsExpressionBuilderWidget().
void QgsExpressionBuilderWidget::registerItem (QString group, QString label, QString expressionText, QString helpText = "", QgsExpressionItem::ItemType type = QgsExpressionItem::ExpressionNode)
Registers a node item for the expression builder.
Parameters
group The group the item will be show in the tree view. If the group doesn't exsit it will be created.
label The label that is show to the user for the item in the tree.
expressionText The text that is inserted into the expression area when the user double clicks on the item.
helpText The help text that the user will see when item is selected.
type The type of the expression item.
Definition at line 219 of file qgsexpressionbuilderwidget.cpp.
References QgsExpression::group(), QgsExpressionItem::Header, mExpressionGroups, and mModel.
Referenced by loadFieldNames(), loadRecent(), and QgsExpressionBuilderWidget().
void QgsExpressionBuilderWidget::saveToRecent (QString key)
Definition at line 249 of file qgsexpressionbuilderwidget.cpp.
References expressionText(), and loadRecent().
void QgsExpressionBuilderWidget::setExpressionState (bool state) private slot
Definition at line 451 of file qgsexpressionbuilderwidget.cpp.
References mExpressionValid.
Referenced by QgsExpressionBuilderWidget().
void QgsExpressionBuilderWidget::setExpressionText (const QString & expression)
Sets the expression string for the widget.
Definition at line 295 of file qgsexpressionbuilderwidget.cpp.
void QgsExpressionBuilderWidget::setGeomCalculator (const QgsDistanceArea & da)
Sets geometry calculator used in distance/area calculations.
Note
added in version 2.0
Definition at line 285 of file qgsexpressionbuilderwidget.cpp.
References mDa.
void QgsExpressionBuilderWidget::setLayer (QgsVectorLayer * layer)
Sets layer in order to get the fields and values.
Note
this needs to be called before calling loadFieldNames().
Definition at line 122 of file qgsexpressionbuilderwidget.cpp.
References mLayer.
void QgsExpressionBuilderWidget::showContextMenu (const QPoint & pt) slot
Definition at line 406 of file qgsexpressionbuilderwidget.cpp.
References QgsExpressionItem::Field, QgsExpressionItem::getItemType(), loadAllValues(), loadSampleValues(), mLayer, mModel, mProxyModel, and tr.
Referenced by QgsExpressionBuilderWidget().
Member Data Documentation
QgsExpressionHighlighter* QgsExpressionBuilderWidget::highlighter private
Definition at line 187 of file qgsexpressionbuilderwidget.h.
Referenced by loadFieldNames(), and QgsExpressionBuilderWidget().
QgsDistanceArea QgsExpressionBuilderWidget::mDa private
Definition at line 189 of file qgsexpressionbuilderwidget.h.
Referenced by on_txtExpressionString_textChanged(), and setGeomCalculator().
QMap<QString, QgsExpressionItem*> QgsExpressionBuilderWidget::mExpressionGroups private
Definition at line 185 of file qgsexpressionbuilderwidget.h.
Referenced by loadRecent(), and registerItem().
bool QgsExpressionBuilderWidget::mExpressionValid private
Definition at line 188 of file qgsexpressionbuilderwidget.h.
Referenced by isExpressionValid(), and setExpressionState().
QgsFeature QgsExpressionBuilderWidget::mFeature private
Definition at line 186 of file qgsexpressionbuilderwidget.h.
Referenced by on_txtExpressionString_textChanged().
QgsVectorLayer* QgsExpressionBuilderWidget::mLayer private
Definition at line 182 of file qgsexpressionbuilderwidget.h.
Referenced by currentChanged(), fillFieldValues(), loadAllValues(), loadFieldNames(), loadSampleValues(), on_txtExpressionString_textChanged(), setLayer(), and showContextMenu().
QStandardItemModel* QgsExpressionBuilderWidget::mModel private
Definition at line 183 of file qgsexpressionbuilderwidget.h.
Referenced by currentChanged(), loadAllValues(), loadSampleValues(), on_expressionTree_doubleClicked(), QgsExpressionBuilderWidget(), registerItem(), and showContextMenu().
QgsExpressionItemSearchProxy* QgsExpressionBuilderWidget::mProxyModel private
Definition at line 184 of file qgsexpressionbuilderwidget.h.
Referenced by currentChanged(), loadAllValues(), loadSampleValues(), on_expressionTree_doubleClicked(), on_txtSearchEdit_textChanged(), QgsExpressionBuilderWidget(), and showContextMenu().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsexpressionbuilderwidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsexpressionbuilderwidget.cpp