QGIS API Documentation: QgsExpressionBuilderDialog Class Reference
QgsExpressionBuilderDialog Class Reference
A generic dialog for building expression strings.
#include <qgsexpressionbuilderdialog.h>
Public Member Functions
QgsExpressionBuilderDialog (QgsVectorLayer *layer, QString startText=QString(), QWidget *parent=NULL, QString key="generic")
QgsExpressionBuilderWidget * expressionBuilder ()
The builder widget that is used by the dialog.
void setExpressionText (const QString &text)
QString expressionText ()
void setGeomCalculator (const QgsDistanceArea &da)
Sets geometry calculator used in distance/area calculations.
Protected Member Functions
virtual void done (int r)
Is called when the dialog get accepted or rejected Used to save geometry.
virtual void accept ()
Private Attributes
QString mRecentKey
Detailed Description
A generic dialog for building expression strings.
Remarks
This class also shows an example on how to use QgsExpressionBuilderWidget
Definition at line 26 of file qgsexpressionbuilderdialog.h.
Constructor & Destructor Documentation
QgsExpressionBuilderDialog::QgsExpressionBuilderDialog (QgsVectorLayer * layer, QString startText = QString(), QWidget * parent = NULL, QString key = "generic")
Definition at line 19 of file qgsexpressionbuilderdialog.cpp.
References mRecentKey.
Member Function Documentation
void QgsExpressionBuilderDialog::accept () protected virtual
Definition at line 59 of file qgsexpressionbuilderdialog.cpp.
References mRecentKey.
void QgsExpressionBuilderDialog::done (int r) protected virtual
Is called when the dialog get accepted or rejected Used to save geometry.
Parameters
r result value (unused)
Definition at line 51 of file qgsexpressionbuilderdialog.cpp.
QgsExpressionBuilderWidget * QgsExpressionBuilderDialog::expressionBuilder ()
The builder widget that is used by the dialog.
Definition at line 36 of file qgsexpressionbuilderdialog.cpp.
QString QgsExpressionBuilderDialog::expressionText ()
Definition at line 46 of file qgsexpressionbuilderdialog.cpp.
Referenced by QgsFieldExpressionWidget::editExpression(), and QgsDataDefinedButton::showExpressionDialog().
void QgsExpressionBuilderDialog::setExpressionText (const QString & text)
Definition at line 41 of file qgsexpressionbuilderdialog.cpp.
Referenced by QgsDualView::previewExpressionBuilder().
void QgsExpressionBuilderDialog::setGeomCalculator (const QgsDistanceArea & da)
Sets geometry calculator used in distance/area calculations.
Note
added in version 2.0
Definition at line 65 of file qgsexpressionbuilderdialog.cpp.
Referenced by QgsFieldExpressionWidget::editExpression().
Member Data Documentation
QString QgsExpressionBuilderDialog::mRecentKey private
Definition at line 55 of file qgsexpressionbuilderdialog.h.
Referenced by accept(), and QgsExpressionBuilderDialog().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsexpressionbuilderdialog.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsexpressionbuilderdialog.cpp