QGIS API Documentation: QgsComposerItem Class Reference
QgsComposerItem Class Reference abstract
MapComposer
A item that forms part of a map composition.
#include <qgscomposeritem.h>
Public Types
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Public Slots
virtual void setRotation (double r)
Sets the item rotation.
virtual void setItemRotation (double r, bool adjustPosition=false)
Sets the item rotation.
void repaint ()
Signals
void itemRotationChanged (double newRotation)
Is emitted on item rotation change.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
void frameChanged ()
Emitted if the item's frame style changes.
Public Member Functions
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual int type () const
return correct graphics item type.
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected () const
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
int page () const
Gets the page the item is currently on.
QPointF pagePos () const
Returns the item's position relative to its current page.
void updatePagePos (double newPageWidth, double newPageHeight)
Moves the item so that it retains its relative position on the page when the paper size changes.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft, int page=-1)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft, bool posIncludesFrame=false, int page=-1)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
virtual void setSceneRect (const QRectF &rectangle)
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
virtual bool writeXML (QDomElement &elem, QDomDocument &doc) const =0
stores state in Dom element
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
virtual bool readXML (const QDomElement &itemElem, const QDomDocument &doc)=0
sets state from Dom document
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
virtual void setFrameOutlineWidth (double outlineWidth)
Sets frame outline width.
double frameOutlineWidth () const
Returns the frame's outline width.
Qt::PenJoinStyle frameJoinStyle () const
Returns the join style used for drawing the item's frame.
void setFrameJoinStyle (Qt::PenJoinStyle style)
Sets join style used when drawing the item's frame.
virtual double estimatedFrameBleed () const
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
virtual QRectF rectWithFrame () const
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop, int flags=Qt::TextWordWrap) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font descent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightMillimeters (const QFont &font) const
Returns the font height in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
double itemRotation () const
Returns the rotation for the composer item.
Q_DECL_DEPRECATED double rotation () const
Returns the rotation for the composer item.
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
virtual int numberExportLayers () const
Get the number of layers that this item requires for exporting as layers.
virtual void setCurrentExportLayer (int layerIdx=-1)
Sets the current layer to draw for exporting.
Protected Member Functions
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height, double rotation) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Q_DECL_DEPRECATED bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
QRectF largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height, double rotation) const
Calculates corner point after rotation and scaling.
Q_DECL_DEPRECATED bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height, double rotation)
Calculates width / height of the bounding box of a rotated rectangle.
Q_DECL_DEPRECATED void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Protected Attributes
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
Qt::PenJoinStyle mFrameJoinStyle
Frame join style.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mItemRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
int mCurrentExportLayer
The layer that needs to be exported.
Private Member Functions
void init (bool manageZValue)
Private Attributes
QString mId
QString mUuid
QString mTemplateUuid
Friends
class QgsComposerItemGroup
Detailed Description
A item that forms part of a map composition.
Definition at line 36 of file qgscomposeritem.h.
Member Enumeration Documentation
enum QgsComposerItem::ItemPositionMode
Enumerator
UpperLeft
UpperMiddle
UpperRight
MiddleLeft
Middle
MiddleRight
LowerLeft
LowerMiddle
LowerRight
Definition at line 77 of file qgscomposeritem.h.
enum QgsComposerItem::ItemType
Enumerator
ComposerItem
ComposerArrow
ComposerItemGroup
ComposerLabel
ComposerLegend
ComposerMap
ComposerPaper
ComposerPicture
ComposerScaleBar
ComposerShape
ComposerTable
ComposerAttributeTable
ComposerTextTable
ComposerFrame
Definition at line 41 of file qgscomposeritem.h.
enum QgsComposerItem::MouseMoveAction
Describes the action (move or resize in different directon) to be done during mouse move.
Enumerator
MoveItem
ResizeUp
ResizeDown
ResizeLeft
ResizeRight
ResizeLeftUp
ResizeRightUp
ResizeLeftDown
ResizeRightDown
NoAction
Definition at line 63 of file qgscomposeritem.h.
Constructor & Destructor Documentation
QgsComposerItem::QgsComposerItem (QgsComposition * composition, bool manageZValue = true)
Constructor.
Parameters
composition parent composition
manageZValue true if the z-Value of this object should be managed by mComposition
Definition at line 49 of file qgscomposeritem.cpp.
References init().
QgsComposerItem::QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition * composition, bool manageZValue = true)
Constructor with box position and composer object.
Parameters
x x coordinate of item
y y coordinate of item
width width of item
height height of item
composition parent composition
manageZValue true if the z-Value of this object should be managed by mComposition
Definition at line 74 of file qgscomposeritem.cpp.
References init().
QgsComposerItem::~QgsComposerItem () virtual
Definition at line 120 of file qgscomposeritem.cpp.
References deleteAlignItems(), mBoundingResizeRectangle, mComposition, mEffect, and QgsComposition::removeItemFromZList().
Member Function Documentation
bool QgsComposerItem::_readXML (const QDomElement & itemElem, const QDomDocument & doc)
Reads parameter that are not subclass specific in document.
Usually called from readXML methods of subclasses
Definition at line 232 of file qgscomposeritem.cpp.
References composition(), QgsSymbolLayerV2Utils::decodePenJoinStyle(), QgsMapRenderer::getCompositionMode(), mBackground, mComposition, mFrame, mFrameJoinStyle, mLastUsedPositionMode, mLastValidViewScaleFactor, mTemplateUuid, mUuid, page(), QgsComposition::paperHeight(), positionLock(), setBackgroundColor(), setBlendMode(), setId(), setItemRotation(), setPositionLock(), setSceneRect(), setTransparency(), QgsComposition::spaceBetweenPages(), and UpperLeft.
Referenced by QgsComposerFrame::readXML(), QgsComposerItemGroup::readXML(), QgsComposerShape::readXML(), QgsComposerArrow::readXML(), QgsComposerPicture::readXML(), QgsComposerLabel::readXML(), QgsComposerLegend::readXML(), QgsComposerScaleBar::readXML(), QgsComposerMap::readXML(), and QgsComposerTable::tableReadXML().
bool QgsComposerItem::_writeXML (QDomElement & itemElem, QDomDocument & doc) const
Writes parameter that are not subclass specific in document.
Usually called from writeXML methods of subclasses
Definition at line 145 of file qgscomposeritem.cpp.
References QgsSymbolLayerV2Utils::encodePenJoinStyle(), QgsMapRenderer::getBlendModeEnum(), mBackground, mBlendMode, mFrame, mFrameJoinStyle, mId, mItemPositionLocked, mItemRotation, mLastUsedPositionMode, mLastValidViewScaleFactor, mTransparency, mUuid, page(), and pagePos().
Referenced by QgsComposerTable::tableWriteXML(), QgsComposerFrame::writeXML(), QgsComposerItemGroup::writeXML(), QgsComposerTextTable::writeXML(), QgsComposerShape::writeXML(), QgsComposerArrow::writeXML(), QgsComposerPicture::writeXML(), QgsComposerLabel::writeXML(), QgsComposerLegend::writeXML(), QgsComposerScaleBar::writeXML(), and QgsComposerMap::writeXML().
virtual void QgsComposerItem::addItem (QgsComposerItem * item) inline virtual
Composite operations for item groups do nothing per default.
Reimplemented in QgsComposerItemGroup.
Definition at line 317 of file qgscomposeritem.h.
double QgsComposerItem::angle (const QPointF & p1, const QPointF & p2) const protected
Returns angle of the line from p1 to p2 (clockwise, starting at N)
Definition at line 772 of file qgscomposeritem.cpp.
References M_PI.
Referenced by QgsComposerArrow::drawHardcodedMarker(), and QgsComposerArrow::drawSVGMarker().
QColor QgsComposerItem::backgroundColor () const inline
Gets the background color for this item.
Returns
background color
Note
introduced in 2.0
Definition at line 287 of file qgscomposeritem.h.
Referenced by QgsComposerMap::cache(), QgsComposerMultiFrame::createNewFrame(), and setBackgroundColor().
void QgsComposerItem::beginCommand (const QString & commandText, QgsComposerMergeCommand::Context c = QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
Parameters
commandText command title
c context for mergeable commands (unknown for non-mergeable commands
Definition at line 423 of file qgscomposeritem.cpp.
References QgsComposition::beginCommand(), and mComposition.
Referenced by QgsComposerView::wheelEvent().
virtual void QgsComposerItem::beginItemCommand (const QString & text) inline virtual
Reimplemented in QgsComposerFrame.
Definition at line 323 of file qgscomposeritem.h.
Referenced by QgsComposition::removeComposerItem().
QPainter::CompositionMode QgsComposerItem::blendMode () const inline
Returns the item's composition blending mode.
Definition at line 297 of file qgscomposeritem.h.
Referenced by QgsComposerMultiFrame::createNewFrame(), setBlendMode(), QgsComposerMap::setGridBlendMode(), and QgsComposerMap::setOverviewBlendMode().
void QgsComposerItem::cancelCommand ()
Definition at line 439 of file qgscomposeritem.cpp.
References QgsComposition::cancelCommand(), and mComposition.
const QgsComposition* QgsComposerItem::composition () const inline
Definition at line 320 of file qgscomposeritem.h.
Referenced by _readXML(), QgsAtlasComposition::computeExtent(), page(), pagePos(), QgsComposerMap::QgsComposerMap(), QgsComposerAttributeTable::readXML(), setItemPosition(), and updatePagePos().
QgsComposition* QgsComposerItem::composition () inline
Definition at line 321 of file qgscomposeritem.h.
bool QgsComposerItem::cornerPointOnRotatedAndScaledRect (double & x, double & y, double width, double height, double rotation) const protected
Calculates corner point after rotation and scaling.
Definition at line 1027 of file qgscomposeritem.cpp.
References M_PI.
Referenced by QgsComposerPicture::cornerPointOnRotatedAndScaledRect(), QgsComposerMap::cornerPointOnRotatedAndScaledRect(), cornerPointOnRotatedAndScaledRect(), and imageSizeConsideringRotation().
bool QgsComposerItem::cornerPointOnRotatedAndScaledRect (double & x, double & y, double width, double height) const protected
Calculates corner point after rotation and scaling.
Deprecated:
Use bool cornerPointOnRotatedAndScaledRect(double& x, double& y, double width, double height, double rotation) instead
Definition at line 1021 of file qgscomposeritem.cpp.
References cornerPointOnRotatedAndScaledRect(), and mItemRotation.
void QgsComposerItem::deleteAlignItems () protected
Definition at line 1161 of file qgscomposeritem.cpp.
References deleteHAlignSnapItem(), and deleteVAlignSnapItem().
Referenced by ~QgsComposerItem().
void QgsComposerItem::deleteHAlignSnapItem () protected
Definition at line 1141 of file qgscomposeritem.cpp.
References mHAlignSnapItem.
Referenced by deleteAlignItems().
void QgsComposerItem::deleteVAlignSnapItem () protected
Definition at line 1151 of file qgscomposeritem.cpp.
References mVAlignSnapItem.
Referenced by deleteAlignItems().
void QgsComposerItem::drawArrowHead (QPainter * p, double x, double y, double angle, double arrowHeadWidth) const protected
Draws arrowhead.
Definition at line 687 of file qgscomposeritem.cpp.
References M_PI.
Referenced by QgsComposerArrow::drawHardcodedMarker().
void QgsComposerItem::drawBackground (QPainter * p) protected virtual
Draw background.
Reimplemented in QgsComposerShape.
Definition at line 623 of file qgscomposeritem.cpp.
References mBackground.
Referenced by QgsComposerFrame::paint(), QgsComposerLabel::paint(), QgsComposerArrow::paint(), QgsComposerTable::paint(), QgsComposerScaleBar::paint(), QgsComposerPicture::paint(), QgsComposerMap::paint(), and QgsComposerLegend::paintAndDetermineSize().
void QgsComposerItem::drawFrame (QPainter * p) protected virtual
Draw black frame around item.
Reimplemented in QgsComposerShape, and QgsComposerItemGroup.
Definition at line 477 of file qgscomposeritem.cpp.
References mFrame.
Referenced by QgsComposerFrame::paint(), QgsComposerLabel::paint(), QgsComposerArrow::paint(), QgsComposerTable::paint(), QgsComposerScaleBar::paint(), QgsComposerPicture::paint(), QgsComposerMap::paint(), QgsComposerLegend::paintAndDetermineSize(), and setFrameEnabled().
void QgsComposerItem::drawSelectionBoxes (QPainter * p) protected virtual
Draw selection boxes around item.
Definition at line 447 of file qgscomposeritem.cpp.
References QgsApplication::activeThemePath(), QgsApplication::defaultThemePath(), lockSymbolSize(), mComposition, mItemPositionLocked, QgsComposition::plotStyle(), and QgsComposition::Preview.
Referenced by QgsComposerFrame::paint(), QgsComposerLabel::paint(), QgsComposerItemGroup::paint(), QgsComposerArrow::paint(), QgsComposerShape::paint(), QgsComposerTable::paint(), QgsComposerScaleBar::paint(), QgsComposerPicture::paint(), QgsComposerMap::paint(), and QgsComposerLegend::paintAndDetermineSize().
void QgsComposerItem::drawText (QPainter * p, double x, double y, const QString & text, const QFont & font) const
Draws Text.
Takes care about all the composer specific issues (calculation to pixel, scaling of font and painter to work around the Qt font bug)
Definition at line 661 of file qgscomposeritem.cpp.
References FONT_WORKAROUND_SCALE, and scaledFontPixelSize().
Referenced by QgsNumericScaleBarStyle::draw(), QgsComposerMap::drawAnnotation(), QgsComposerLegend::drawGroupItemTitle(), QgsScaleBarStyle::drawLabels(), QgsComposerLegend::drawLayerItemTitle(), QgsComposerLegend::drawSymbolItem(), QgsComposerLegend::drawTitle(), QgsComposerLabel::paint(), and QgsComposerTable::paint().
void QgsComposerItem::drawText (QPainter * p, const QRectF & rect, const QString & text, const QFont & font, Qt::AlignmentFlag halignment = Qt::AlignLeft, Qt::AlignmentFlag valignment = Qt::AlignTop, int flags = Qt::TextWordWrap) const
Like the above, but with a rectangle for multiline text.
Parameters
p painter to use
rect rectangle to draw into
text text to draw
font font to use
halignment optional horizontal alignment
valignment optional vertical alignment
flags allows for passing Qt::TextFlags to control appearance of rendered text
Definition at line 673 of file qgscomposeritem.cpp.
References FONT_WORKAROUND_SCALE, and scaledFontPixelSize().
bool QgsComposerItem::effectsEnabled () const inline
Returns true if effects (eg blend modes) are enabled for the item.
Note
introduced in 2.0
Definition at line 310 of file qgscomposeritem.h.
Referenced by setEffectsEnabled().
void QgsComposerItem::endCommand ()
Finish current command and push it onto the undo stack.
Definition at line 431 of file qgscomposeritem.cpp.
References QgsComposition::endCommand(), and mComposition.
virtual void QgsComposerItem::endItemCommand () inline virtual
Reimplemented in QgsComposerFrame.
Definition at line 330 of file qgscomposeritem.h.
Referenced by QgsComposition::removeComposerItem().
double QgsComposerItem::estimatedFrameBleed () const virtual
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
For instance, if the item has a 2mm frame outline, then 1mm of this frame is drawn outside the item's rect. In this case the return value will be 1.0
Note
introduced in 2.2
Reimplemented in QgsComposerShape.
Definition at line 407 of file qgscomposeritem.cpp.
References hasFrame().
Referenced by rectWithFrame(), and setItemPosition().
double QgsComposerItem::fontAscentMillimeters (const QFont & font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
Definition at line 738 of file qgscomposeritem.cpp.
References FONT_WORKAROUND_SCALE, and scaledFontPixelSize().
Referenced by QgsComposerTable::adaptItemFrame(), QgsNumericScaleBarStyle::calculateBoxSize(), QgsScaleBarStyle::calculateBoxSize(), QgsDoubleBoxScaleBarStyle::draw(), QgsSingleBoxScaleBarStyle::draw(), QgsTicksScaleBarStyle::draw(), QgsComposerLegend::drawGroupItemTitle(), QgsComposerTable::drawHorizontalGridLines(), QgsScaleBarStyle::drawLabels(), QgsComposerLegend::drawLayerItemTitle(), QgsComposerLegend::drawTitle(), QgsComposerMap::maxExtension(), QgsComposerTable::paint(), and QgsComposerAttributeTable::setSceneRect().
double QgsComposerItem::fontDescentMillimeters (const QFont & font) const
Returns the font descent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
Definition at line 745 of file qgscomposeritem.cpp.
References FONT_WORKAROUND_SCALE, and scaledFontPixelSize().
Referenced by QgsComposerLegend::drawTitle().
double QgsComposerItem::fontHeightCharacterMM (const QFont & font, const QChar & c) const
Returns the font height of a character in millimeters.
Note
this method was added in version 1.7
Definition at line 731 of file qgscomposeritem.cpp.
References FONT_WORKAROUND_SCALE, and scaledFontPixelSize().
Referenced by QgsComposerMap::drawCoordinateAnnotation(), and QgsComposerLegend::drawSymbolItem().
double QgsComposerItem::fontHeightMillimeters (const QFont & font) const
Returns the font height in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
Font height equals the font ascent+descent+1 (for baseline).
Note
Added in version 2.4
Definition at line 752 of file qgscomposeritem.cpp.
References FONT_WORKAROUND_SCALE, and scaledFontPixelSize().
Referenced by QgsComposerLabel::adjustSizeToText().
void QgsComposerItem::frameChanged () signal
Emitted if the item's frame style changes.
Note
: this function was introduced in version 2.2
Referenced by QgsComposerShape::createDefaultShapeStyleSymbol(), QgsComposerShape::refreshSymbol(), setFrameEnabled(), setFrameJoinStyle(), and setFrameOutlineWidth().
Qt::PenJoinStyle QgsComposerItem::frameJoinStyle () const inline
Returns the join style used for drawing the item's frame.
Returns
Join style for outline frame
Note
introduced in 2.3
See also
hasFrame
setFrameJoinStyle
Definition at line 240 of file qgscomposeritem.h.
Referenced by QgsComposerMultiFrame::createNewFrame().
double QgsComposerItem::frameOutlineWidth () const inline
Returns the frame's outline width.
Only used if hasFrame is true.
Returns
Frame outline width
Note
introduced in 2.3
See also
hasFrame
setFrameOutlineWidth
Definition at line 232 of file qgscomposeritem.h.
Referenced by QgsComposerMultiFrame::createNewFrame().
QGraphicsLineItem * QgsComposerItem::hAlignSnapItem () protected
Return horizontal align snap item.
Creates a new graphics line if 0
Definition at line 1117 of file qgscomposeritem.cpp.
References mHAlignSnapItem.
bool QgsComposerItem::hasBackground () const inline
Whether this item has a Background or not.
Returns
true if there is a Background around this item, otherwise false.
Note
introduced since 2.0
See also
hasBackground
Definition at line 273 of file qgscomposeritem.h.
Referenced by QgsComposerMap::cache(), QgsComposerMultiFrame::createNewFrame(), QgsComposerMap::draw(), QgsComposerMap::numberExportLayers(), QgsComposerShape::readXML(), and QgsComposerMap::shouldDrawPart().
bool QgsComposerItem::hasFrame () const inline
Whether this item has a frame or not.
Returns
true if there is a frame around this item, otherwise false.
Note
introduced since 1.8
See also
hasFrame
Definition at line 208 of file qgscomposeritem.h.
Referenced by QgsComposerLabel::adjustSizeToText(), QgsComposerMultiFrame::createNewFrame(), estimatedFrameBleed(), QgsComposerMap::numberExportLayers(), QgsComposerLabel::paint(), QgsComposerShape::readXML(), and QgsComposerMap::shouldDrawPart().
double QgsComposerItem::horizontalViewScaleFactor () const protected
Returns the zoom factor of the graphics view.
Returns
the factor or -1 in case of error (e.g. graphic view does not exist)
Note
: this function was introduced in version 1.2
Definition at line 790 of file qgscomposeritem.cpp.
References mLastValidViewScaleFactor.
Referenced by QgsComposerMap::cache(), QgsComposerArrow::drawSVGMarker(), lockSymbolSize(), and rectHandlerBorderTolerance().
QString QgsComposerItem::id () const inline
Get item's id (which is not necessarly unique)
Note
this method was added in version 1.7
Definition at line 401 of file qgscomposeritem.h.
Referenced by QgsComposerMap::draw(), QgsComposition::getComposerItemById(), and setId().
bool QgsComposerItem::imageSizeConsideringRotation (double & width, double & height, double rotation) const protected
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Definition at line 957 of file qgscomposeritem.cpp.
References cornerPointOnRotatedAndScaledRect(), QgsSymbolLayerV2Utils::pointOnLineWithDistance(), and qgsDoubleNear().
Referenced by QgsComposerPicture::imageSizeConsideringRotation(), QgsComposerMap::imageSizeConsideringRotation(), and imageSizeConsideringRotation().
bool QgsComposerItem::imageSizeConsideringRotation (double & width, double & height) const protected
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Deprecated:
Use bool imageSizeConsideringRotation(double& width, double& height, double rotation) instead
Definition at line 880 of file qgscomposeritem.cpp.
References imageSizeConsideringRotation(), and mItemRotation.
void QgsComposerItem::init (bool manageZValue) private
Definition at line 100 of file qgscomposeritem.cpp.
References QgsComposition::addItemToZList(), mComposition, mEffect, and mFrameJoinStyle.
Referenced by QgsComposerItem().
void QgsComposerItem::itemChanged () signal
Used e.g.
by the item widgets to update the gui elements
Referenced by QgsComposerScaleBar::applyDefaultSettings(), QgsComposerScaleBar::applyDefaultSize(), QgsComposerPicture::loadPicture(), QgsComposerMap::moveContent(), QgsComposerMap::overviewExtentChanged(), QgsComposerShape::readXML(), QgsComposerAttributeTable::readXML(), QgsComposerArrow::readXML(), QgsComposerPicture::readXML(), QgsComposerLabel::readXML(), QgsComposerLegend::readXML(), QgsComposerMap::readXML(), QgsComposerScaleBar::setAlignment(), QgsComposerScaleBar::setBoxContentSpace(), QgsComposerScaleBar::setComposerMap(), QgsComposerScaleBar::setFont(), QgsComposerScaleBar::setLineCapStyle(), QgsComposerScaleBar::setLineJoinStyle(), QgsComposerMap::setMapRotation(), QgsComposerMap::setNewAtlasFeatureExtent(), QgsComposerMap::setNewScale(), QgsComposerScaleBar::setNumSegments(), QgsComposerScaleBar::setNumSegmentsLeft(), QgsComposerScaleBar::setNumUnitsPerSegment(), QgsComposerMap::setPreviewMode(), QgsComposerPicture::setSceneRect(), QgsComposerMap::setSceneRect(), QgsComposerScaleBar::setStyle(), QgsComposerLabel::setText(), QgsComposerScaleBar::setUnits(), QgsComposerMap::toggleAtlasPreview(), QgsComposerScaleBar::updateSegmentSize(), and QgsComposerMap::zoomContent().
double QgsComposerItem::itemRotation () const inline
Returns the rotation for the composer item.
Note
this method was added in version 2.1
Definition at line 388 of file qgscomposeritem.h.
Referenced by QgsComposerItemGroup::addItem().
void QgsComposerItem::itemRotationChanged (double newRotation) signal
Is emitted on item rotation change.
Referenced by setItemRotation().
QRectF QgsComposerItem::largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const protected
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
Parameters
originalRect QRectF to be rotated and scaled
boundsRect QRectF specifying the bounds which the rotated and scaled rectangle must fit within
rotation the rotation in degrees to be applied to the rectangle
Definition at line 886 of file qgscomposeritem.cpp.
References M_DEG2RAD.
Referenced by QgsComposerPicture::setPictureRotation(), and QgsComposerPicture::setSceneRect().
ItemPositionMode QgsComposerItem::lastUsedPositionMode () inline
Returns item's last used position mode.
Note
: This property has no effect on actual's item position, which is always the top-left corner.
: this method was added in version 2.0
Definition at line 179 of file qgscomposeritem.h.
double QgsComposerItem::lockSymbolSize () const protected
Returns the size of the lock symbol depending on the composer zoom level and the item size.
Note
: this function was introduced in version 1.2
Definition at line 827 of file qgscomposeritem.cpp.
References horizontalViewScaleFactor().
Referenced by drawSelectionBoxes().
void QgsComposerItem::move (double dx, double dy)
Moves item in canvas coordinates.
Definition at line 493 of file qgscomposeritem.cpp.
References setSceneRect().
Referenced by QgsComposition::addItemsFromXML(), and QgsComposerScaleBar::correctXPositionAlignment().
virtual void QgsComposerItem::moveContent (double dx, double dy) inline virtual
Move Content of item.
Does nothing per default (but implemented in composer map)
Parameters
dx move in x-direction (canvas coordinates)
dy move in y-direction(canvas coordinates)
Reimplemented in QgsComposerMap.
Definition at line 128 of file qgscomposeritem.h.
Referenced by QgsComposerView::mouseReleaseEvent().
virtual int QgsComposerItem::numberExportLayers () const inline virtual
Get the number of layers that this item requires for exporting as layers.
Returns
0 if this item is to be placed on the same layer as the previous item, 1 if it should be placed on its own layer, and >1 if it requires multiple export layers
Note
this method was added in version 2.4
Reimplemented in QgsComposerMap.
Definition at line 417 of file qgscomposeritem.h.
int QgsComposerItem::page () const
Gets the page the item is currently on.
Returns
page number for item
See also
pagePos
updatePagePos
Note
this method was added in version 2.4
Definition at line 499 of file qgscomposeritem.cpp.
References composition(), QgsComposition::paperHeight(), and QgsComposition::spaceBetweenPages().
Referenced by _readXML(), _writeXML(), pagePos(), and updatePagePos().
QPointF QgsComposerItem::pagePos () const
Returns the item's position relative to its current page.
Returns
position relative to the page's top left corner.
See also
page
updatePagePos
Note
this method was added in version 2.4
Definition at line 512 of file qgscomposeritem.cpp.
References composition(), page(), QgsComposition::paperHeight(), and QgsComposition::spaceBetweenPages().
Referenced by _writeXML(), and updatePagePos().
double QgsComposerItem::pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
Definition at line 759 of file qgscomposeritem.cpp.
Referenced by scaledFontPixelSize().
bool QgsComposerItem::positionLock () const inline
Returns position lock for mouse drags (true means locked)
Note
this method was added in version 1.2
Definition at line 384 of file qgscomposeritem.h.
Referenced by _readXML(), QgsComposerView::endMarqueeSelect(), QgsComposerView::mousePressEvent(), QgsComposerView::selectAll(), QgsComposerView::selectInvert(), and QgsComposition::unlockAllItems().
bool QgsComposerItem::readSettings (void) virtual
read state from project
Definition at line 141 of file qgscomposeritem.cpp.
virtual bool QgsComposerItem::readXML (const QDomElement & itemElem, const QDomDocument & doc) pure virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is Dom document
Implemented in QgsComposerMap, QgsComposerScaleBar, QgsComposerLegend, QgsComposerLabel, QgsComposerPicture, QgsComposerArrow, QgsComposerAttributeTable, QgsPaperItem, QgsComposerShape, QgsComposerTextTable, QgsComposerTable, QgsComposerItemGroup, and QgsComposerFrame.
Referenced by QgsComposerItemCommand::restoreState().
double QgsComposerItem::rectHandlerBorderTolerance () const protected
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
Definition at line 809 of file qgscomposeritem.cpp.
References horizontalViewScaleFactor().
QRectF QgsComposerItem::rectWithFrame () const virtual
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
The bounds are returned in the item's coordinate system (see Qt's QGraphicsItem docs for more details about QGraphicsItem coordinate systems). The results differ from Qt's rect() function, as rect() makes no allowances for the portion of outlines which are drawn outside of the item.
Note
introduced in 2.2
See also
estimatedFrameBleed
Definition at line 417 of file qgscomposeritem.cpp.
References estimatedFrameBleed().
Referenced by QgsComposerMouseHandles::collectAlignCoordinates().
virtual void QgsComposerItem::removeItems () inline virtual
Reimplemented in QgsComposerItemGroup.
Definition at line 318 of file qgscomposeritem.h.
bool QgsComposerItem::removeSettings (void) virtual
delete settings from project file
Definition at line 143 of file qgscomposeritem.cpp.
void QgsComposerItem::repaint () slot
Definition at line 1167 of file qgscomposeritem.cpp.
Referenced by QgsComposerTable::adjustFrameToSize(), QgsPaperItem::initialize(), QgsComposerShape::QgsComposerShape(), QgsComposerItemCommand::restoreState(), and QgsComposerTable::setHeaderHAlignment().
void QgsComposerItem::rotate (double angle, double & x, double & y) const protected
Rotates a point / vector.
Parameters
angle rotation angle in degrees, counterclockwise
x in/out: x coordinate before / after the rotation
y in/out: y cooreinate before / after the rotation
Definition at line 1107 of file qgscomposeritem.cpp.
References M_PI.
Referenced by QgsComposerMap::mapPolygon(), QgsComposerMap::mapToItemCoords(), sizeChangedByRotation(), and QgsComposerMap::transformShift().
Q_DECL_DEPRECATED double QgsComposerItem::rotation () const inline
Returns the rotation for the composer item.
Deprecated:
Use itemRotation() instead
Definition at line 394 of file qgscomposeritem.h.
QFont QgsComposerItem::scaledFontPixelSize (const QFont & font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
Definition at line 764 of file qgscomposeritem.cpp.
References FONT_WORKAROUND_SCALE, and pixelFontSize().
Referenced by drawText(), fontAscentMillimeters(), fontDescentMillimeters(), fontHeightCharacterMM(), fontHeightMillimeters(), and textWidthMillimeters().
virtual bool QgsComposerItem::selected () const inline virtual
Is selected.
Definition at line 111 of file qgscomposeritem.h.
Referenced by QgsComposerMouseHandles::collectAlignCoordinates(), QgsComposerMouseHandles::mouseActionForPosition(), QgsComposerView::mousePressEvent(), QgsComposerView::selectInvert(), and QgsComposerMouseHandles::selectionChanged().
void QgsComposerItem::setBackgroundColor (const QColor & backgroundColor)
Sets the background color for this item.
Parameters
backgroundColor new background color
Returns
nothing
Note
introduced in 2.0
Definition at line 634 of file qgscomposeritem.cpp.
References backgroundColor(), and mBackgroundColor.
Referenced by _readXML(), QgsComposerMultiFrame::createNewFrame(), and QgsComposerMap::QgsComposerMap().
void QgsComposerItem::setBackgroundEnabled (bool drawBackground) inline
Set whether this item has a Background drawn around it or not.
Parameters
drawBackground draw Background
Returns
nothing
Note
introduced in 2.0
See also
hasBackground
Definition at line 281 of file qgscomposeritem.h.
Referenced by QgsComposerMultiFrame::createNewFrame().
void QgsComposerItem::setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
Definition at line 640 of file qgscomposeritem.cpp.
References blendMode(), mBlendMode, mEffect, and QgsComposerEffect::setCompositionMode().
Referenced by _readXML(), and QgsComposerMultiFrame::createNewFrame().
virtual void QgsComposerItem::setCurrentExportLayer (int layerIdx = -1) inline virtual
Sets the current layer to draw for exporting.
Parameters
layerIdx can be set to -1 to draw all item layers, and must be less than numberExportLayers()
Note
this method was added in version 2.4
Definition at line 423 of file qgscomposeritem.h.
void QgsComposerItem::setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
Note
introduced in 2.0
Definition at line 654 of file qgscomposeritem.cpp.
References effectsEnabled(), mEffect, and mEffectsEnabled.
Referenced by QgsComposition::setUseAdvancedEffects().
void QgsComposerItem::setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
Parameters
drawFrame draw frame
Returns
nothing
Note
introduced in 1.8
See also
hasFrame
Definition at line 373 of file qgscomposeritem.cpp.
References drawFrame(), frameChanged(), and mFrame.
Referenced by QgsComposerMultiFrame::createNewFrame(), QgsComposerShape::QgsComposerShape(), and QgsComposerShape::setUseSymbolV2().
void QgsComposerItem::setFrameJoinStyle (Qt::PenJoinStyle style)
Sets join style used when drawing the item's frame.
Parameters
style Join style for outline frame
Returns
nothing
Note
introduced in 2.3
See also
setFrameEnabled
frameJoinStyle
Definition at line 392 of file qgscomposeritem.cpp.
References frameChanged(), and mFrameJoinStyle.
Referenced by QgsComposerMultiFrame::createNewFrame().
void QgsComposerItem::setFrameOutlineWidth (double outlineWidth) virtual
Sets frame outline width.
Parameters
outlineWidth new width for outline frame
Returns
nothing
Note
introduced in 2.2
See also
setFrameEnabled
Reimplemented in QgsComposerMap.
Definition at line 379 of file qgscomposeritem.cpp.
References frameChanged(), and outlineWidth.
Referenced by QgsComposerMultiFrame::createNewFrame(), and QgsComposerMap::setFrameOutlineWidth().
void QgsComposerItem::setId (const QString & id) virtual
Set item's id (which is not necessarly unique)
Note
this method was added in version 1.7
Definition at line 1172 of file qgscomposeritem.cpp.
References id(), and mId.
Referenced by _readXML().
void QgsComposerItem::setItemPosition (double x, double y, ItemPositionMode itemPoint = UpperLeft, int page = -1)
Moves the item to a new position (in canvas coordinates)
Definition at line 529 of file qgscomposeritem.cpp.
Referenced by QgsComposition::addItemsFromXML().
void QgsComposerItem::setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint = UpperLeft, bool posIncludesFrame = false, int page = -1)
Sets item position and width / height in one go.
Parameters
x item position x
y item position y
width item width
height item height
itemPoint item position mode
posIncludesFrame set to true if the position and size arguments include the item's frame border
page if page > 0, y is interpreted as relative to the origin of the specified page, if page <= 0, y is in absolute canvas coordinates
Note
: this method was added in version 1.6
Definition at line 536 of file qgscomposeritem.cpp.
References composition(), estimatedFrameBleed(), LowerLeft, LowerMiddle, LowerRight, Middle, MiddleLeft, MiddleRight, mItemRotation, mLastUsedPositionMode, QgsComposition::paperHeight(), setSceneRect(), QgsComposition::spaceBetweenPages(), UpperMiddle, and UpperRight.
void QgsComposerItem::setItemRotation (double r, bool adjustPosition = false) virtual slot
Sets the item rotation.
Parameters
r item rotation in degrees
adjustPosition set to true if item should be shifted so that rotation occurs around item center. If false, rotation occurs around item origin
Note
this method was added in version 2.1
Definition at line 849 of file qgscomposeritem.cpp.
References itemRotationChanged(), mItemRotation, and sizeChanged().
Referenced by _readXML(), QgsComposerItemGroup::addItem(), QgsComposerShape::readXML(), QgsComposerLabel::readXML(), and setRotation().
void QgsComposerItem::setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
Note
this method was added in version 1.2
Definition at line 488 of file qgscomposeritem.cpp.
References mItemPositionLocked.
Referenced by _readXML(), QgsComposerView::mousePressEvent(), and QgsComposition::unlockAllItems().
void QgsComposerItem::setRotation (double r) virtual slot
Sets the item rotation.
Deprecated:
Use setItemRotation(double rotation) instead
Reimplemented in QgsComposerMap.
Definition at line 842 of file qgscomposeritem.cpp.
References setItemRotation().
void QgsComposerItem::setSceneRect (const QRectF & rectangle) virtual
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
Reimplemented in QgsComposerAttributeTable, QgsComposerMap, QgsComposerShape, QgsComposerPicture, QgsPaperItem, QgsComposerArrow, and QgsComposerItemGroup.
Definition at line 595 of file qgscomposeritem.cpp.
References sizeChanged().
Referenced by _readXML(), QgsComposerTable::adaptItemFrame(), QgsComposerArrow::adaptItemSceneRect(), QgsComposerItemGroup::addItem(), QgsComposerLegend::adjustBoxSize(), QgsComposerScaleBar::adjustBoxSize(), QgsComposerLabel::adjustSizeToText(), QgsComposerView::mousePressEvent(), QgsComposerView::mouseReleaseEvent(), move(), QgsComposerLegend::paintAndDetermineSize(), setItemPosition(), QgsComposerItemGroup::setSceneRect(), QgsComposerArrow::setSceneRect(), QgsPaperItem::setSceneRect(), QgsComposerPicture::setSceneRect(), QgsComposerShape::setSceneRect(), QgsComposerMap::setSceneRect(), and QgsComposerAttributeTable::setSceneRect().
void QgsComposerItem::setSelected (bool s) virtual
Set selected, selected item should be highlighted.
Definition at line 132 of file qgscomposeritem.cpp.
References QgsDebugMsg.
Referenced by QgsComposerItemGroup::addItem(), QgsComposition::addItemsFromXML(), QgsComposerView::addShape(), QgsComposerView::endMarqueeSelect(), QgsComposerView::groupItems(), QgsComposerView::mousePressEvent(), QgsComposerView::mouseReleaseEvent(), QgsComposerView::selectAll(), QgsComposerView::selectInvert(), QgsComposition::selectNextByZOrder(), QgsComposition::sendItemAddedSignal(), QgsComposition::setSelectedItem(), and QgsComposition::unlockAllItems().
void QgsComposerItem::setTransparency (int transparency)
Sets the item's transparency.
Definition at line 647 of file qgscomposeritem.cpp.
References mTransparency, and transparency().
Referenced by _readXML().
void QgsComposerItem::sizeChanged () signal
Emitted if the rectangle changes.
Referenced by setItemRotation(), setSceneRect(), and updatePagePos().
void QgsComposerItem::sizeChangedByRotation (double & width, double & height, double rotation) protected
Calculates width / height of the bounding box of a rotated rectangle.
Definition at line 1070 of file qgscomposeritem.cpp.
References rotate().
Referenced by QgsComposerPicture::sizeChangedByRotation(), QgsComposerMap::sizeChangedByRotation(), and sizeChangedByRotation().
void QgsComposerItem::sizeChangedByRotation (double & width, double & height) protected
Calculates width / height of the bounding box of a rotated rectangle.
Deprecated:
Use void sizeChangedByRotation(double& width, double& height, double rotation) instead
Definition at line 1064 of file qgscomposeritem.cpp.
References mItemRotation, and sizeChangedByRotation().
double QgsComposerItem::textWidthMillimeters (const QFont & font, const QString & text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
Definition at line 724 of file qgscomposeritem.cpp.
References FONT_WORKAROUND_SCALE, and scaledFontPixelSize().
Referenced by QgsComposerLabel::adjustSizeToText(), QgsNumericScaleBarStyle::calculateBoxSize(), QgsScaleBarStyle::calculateBoxSize(), QgsComposerTable::calculateMaxColumnWidths(), QgsComposerMap::drawCoordinateAnnotation(), QgsComposerLegend::drawGroupItemTitle(), QgsScaleBarStyle::drawLabels(), QgsComposerLegend::drawLayerItemTitle(), QgsComposerLegend::drawSymbolItem(), QgsComposerLegend::drawTitle(), QgsComposerMap::maxExtension(), and QgsComposerScaleBar::paint().
int QgsComposerItem::transparency () const inline
Returns the item's transparency.
Definition at line 303 of file qgscomposeritem.h.
Referenced by setTransparency().
virtual int QgsComposerItem::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented in QgsComposerPicture, QgsComposerAttributeTable, QgsComposerScaleBar, QgsComposerMap, QgsComposerTable, QgsPaperItem, QgsComposerShape, QgsComposerLegend, QgsComposerArrow, QgsComposerFrame, QgsComposerLabel, QgsComposerItemGroup, and QgsComposerTextTable.
Definition at line 105 of file qgscomposeritem.h.
Referenced by QgsComposition::nearestSnapLine(), QgsComposition::refreshZList(), QgsComposition::removeComposerItem(), and QgsComposition::writeXML().
virtual void QgsComposerItem::updateItem () inline virtual
Updates item, with the possibility to do custom update for subclasses.
Reimplemented in QgsComposerMap.
Definition at line 397 of file qgscomposeritem.h.
Referenced by QgsComposerMap::updateItem().
void QgsComposerItem::updatePagePos (double newPageWidth, double newPageHeight)
Moves the item so that it retains its relative position on the page when the paper size changes.
Parameters
newPageWidth new width of the page in mm
newPageHeight new height of the page in mm
See also
page
pagePos
Note
this method was added in version 2.4
Definition at line 520 of file qgscomposeritem.cpp.
References composition(), page(), pagePos(), and sizeChanged().
Referenced by QgsComposition::setPaperSize().
QString QgsComposerItem::uuid () const inline
Get item identification name.
Note
this method was added in version 2.0
there is not setter since one can't manually set the id
Definition at line 410 of file qgscomposeritem.h.
Referenced by QgsComposition::getComposerItemByUuid(), and QgsComposerItemGroup::readXML().
QGraphicsLineItem * QgsComposerItem::vAlignSnapItem () protected
Return vertical align snap item.
Creates a new graphics line if 0
Definition at line 1129 of file qgscomposeritem.cpp.
References mVAlignSnapItem.
bool QgsComposerItem::writeSettings (void) virtual
stores state in project
Definition at line 139 of file qgscomposeritem.cpp.
virtual bool QgsComposerItem::writeXML (QDomElement & elem, QDomDocument & doc) const pure virtual
stores state in Dom element
Parameters
elem is Dom element corresponding to 'Composer' tag
doc is the Dom document
Implemented in QgsComposerMap, QgsComposerScaleBar, QgsComposerLegend, QgsComposerLabel, QgsComposerPicture, QgsComposerArrow, QgsComposerAttributeTable, QgsPaperItem, QgsComposerTable, QgsComposerShape, QgsComposerTextTable, QgsComposerItemGroup, and QgsComposerFrame.
Referenced by QgsComposerItemCommand::saveState(), and QgsComposition::writeXML().
virtual void QgsComposerItem::zoomContent (int delta, double x, double y) inline virtual
Zoom content of item.
Does nothing per default (but implemented in composer map)
Parameters
delta value from wheel event that describes magnitude and direction (positive /negative number)
x x-position of mouse cursor (in item coordinates)
y y-position of mouse cursor (in item coordinates)
Reimplemented in QgsComposerMap.
Definition at line 134 of file qgscomposeritem.h.
Friends And Related Function Documentation
friend class QgsComposerItemGroup friend
Definition at line 589 of file qgscomposeritem.h.
Member Data Documentation
bool QgsComposerItem::mBackground protected
True if item background needs to be painted.
Definition at line 459 of file qgscomposeritem.h.
Referenced by _readXML(), _writeXML(), QgsComposerShape::drawBackground(), and drawBackground().
QColor QgsComposerItem::mBackgroundColor protected
Background color.
Definition at line 461 of file qgscomposeritem.h.
Referenced by setBackgroundColor().
QPainter::CompositionMode QgsComposerItem::mBlendMode protected
Composition blend mode for item.
Definition at line 476 of file qgscomposeritem.h.
Referenced by _writeXML(), and setBlendMode().
QGraphicsRectItem* QgsComposerItem::mBoundingResizeRectangle protected
Rectangle used during move and resize actions.
Definition at line 452 of file qgscomposeritem.h.
Referenced by ~QgsComposerItem().
QgsComposition* QgsComposerItem::mComposition protected
Definition at line 443 of file qgscomposeritem.h.
Referenced by _readXML(), QgsComposerMap::assignFreeId(), beginCommand(), QgsComposerFrame::beginItemCommand(), QgsPaperItem::calculatePageMargin(), cancelCommand(), QgsComposerPicture::clippedImageRect(), QgsComposerMap::composerMapPosForItem(), QgsComposerMap::containsAdvancedEffects(), QgsComposerMap::containsWMSLayer(), QgsComposerMap::currentMapExtent(), QgsComposerLabel::displayText(), QgsComposerMap::draw(), QgsComposerItemGroup::drawFrame(), QgsComposerMap::drawGrid(), QgsComposerMap::drawOverviewMapExtent(), drawSelectionBoxes(), QgsComposerShape::drawShapeUsingSymbol(), QgsComposerArrow::drawSVGMarker(), QgsComposerLegend::drawSymbolV2(), endCommand(), QgsComposerFrame::endItemCommand(), QgsComposerPicture::evalPictureExpression(), QgsComposerAttributeTable::getFeatureAttributes(), QgsComposerLabel::htmlUnitsToMM(), QgsComposerPicture::init(), init(), QgsComposerMap::initGridAnnotationFormatFromProject(), QgsPaperItem::initialize(), QgsComposerLegend::layerIdList(), QgsComposerMap::layersToRender(), QgsComposerMap::mapRenderer(), QgsComposerScaleBar::mapWidth(), QgsComposerMap::overviewExtentChanged(), QgsComposerLabel::paint(), QgsPaperItem::paint(), QgsComposerTable::paint(), QgsComposerPicture::paint(), QgsComposerMap::paint(), QgsComposerAttributeTable::QgsComposerAttributeTable(), QgsComposerLabel::QgsComposerLabel(), QgsComposerMap::QgsComposerMap(), QgsComposerShape::QgsComposerShape(), QgsComposerItemGroup::readXML(), QgsComposerPicture::readXML(), QgsComposerLegend::readXML(), QgsComposerScaleBar::readXML(), QgsComposerLabel::refreshExpressionContext(), QgsComposerMap::scale(), QgsComposerMap::setNewScale(), QgsComposerMap::setOverviewFrameMap(), QgsComposerPicture::setRotationMap(), QgsComposerPicture::setSceneRect(), QgsComposerMap::storeCurrentLayerSet(), QgsComposerMap::syncLayerSet(), QgsComposerPicture::updatePictureExpression(), QgsComposerMap::zoomContent(), ~QgsComposerItem(), and QgsComposerItemGroup::~QgsComposerItemGroup().
int QgsComposerItem::mCurrentExportLayer protected
The layer that needs to be exported.
Note
: if -1, all layers are to be exported
: this member was added in version 2.4
Definition at line 490 of file qgscomposeritem.h.
Referenced by QgsComposerMap::draw(), and QgsComposerMap::shouldDrawPart().
QgsComposerItem::MouseMoveAction QgsComposerItem::mCurrentMouseMoveAction protected
Definition at line 445 of file qgscomposeritem.h.
QgsComposerEffect* QgsComposerItem::mEffect protected
Definition at line 478 of file qgscomposeritem.h.
Referenced by init(), setBlendMode(), setEffectsEnabled(), and ~QgsComposerItem().
bool QgsComposerItem::mEffectsEnabled protected
Definition at line 477 of file qgscomposeritem.h.
Referenced by setEffectsEnabled().
bool QgsComposerItem::mFrame protected
True if item fram needs to be painted.
Definition at line 457 of file qgscomposeritem.h.
Referenced by _readXML(), _writeXML(), QgsComposerItemGroup::drawFrame(), QgsComposerShape::drawFrame(), drawFrame(), QgsComposerMap::maxExtension(), and setFrameEnabled().
Qt::PenJoinStyle QgsComposerItem::mFrameJoinStyle protected
Frame join style.
Definition at line 463 of file qgscomposeritem.h.
Referenced by _readXML(), _writeXML(), init(), and setFrameJoinStyle().
QGraphicsLineItem* QgsComposerItem::mHAlignSnapItem protected
Definition at line 453 of file qgscomposeritem.h.
Referenced by deleteHAlignSnapItem(), and hAlignSnapItem().
QString QgsComposerItem::mId private
Definition at line 581 of file qgscomposeritem.h.
Referenced by _writeXML(), QgsComposerMap::id(), and setId().
bool QgsComposerItem::mItemPositionLocked protected
True if item position and size cannot be changed with mouse move.
Note
: this member was added in version 1.2
Definition at line 467 of file qgscomposeritem.h.
Referenced by _writeXML(), drawSelectionBoxes(), and setPositionLock().
double QgsComposerItem::mItemRotation protected
Item rotation in degrees, clockwise.
Definition at line 473 of file qgscomposeritem.h.
Referenced by _writeXML(), cornerPointOnRotatedAndScaledRect(), imageSizeConsideringRotation(), QgsComposerLabel::itemShiftAdjustSize(), setItemPosition(), setItemRotation(), and sizeChangedByRotation().
QPointF QgsComposerItem::mLastMouseEventPos protected
Position of the last mouse move event (in scene coordinates)
Definition at line 449 of file qgscomposeritem.h.
ItemPositionMode QgsComposerItem::mLastUsedPositionMode protected
The item's position mode.
Note
: this member was added in version 2.0
Definition at line 485 of file qgscomposeritem.h.
Referenced by _readXML(), _writeXML(), and setItemPosition().
double QgsComposerItem::mLastValidViewScaleFactor mutable protected
Backup to restore item appearance if no view scale factor is available.
Definition at line 470 of file qgscomposeritem.h.
Referenced by _readXML(), _writeXML(), QgsComposerMap::cache(), and horizontalViewScaleFactor().
QPointF QgsComposerItem::mMouseMoveStartPos protected
Start point of the last mouse move action (in scene coordinates)
Definition at line 447 of file qgscomposeritem.h.
QString QgsComposerItem::mTemplateUuid private
Definition at line 585 of file qgscomposeritem.h.
Referenced by _readXML(), and QgsComposerItemGroup::readXML().
int QgsComposerItem::mTransparency protected
Item transparency.
Definition at line 481 of file qgscomposeritem.h.
Referenced by _writeXML(), and setTransparency().
QString QgsComposerItem::mUuid private
Definition at line 583 of file qgscomposeritem.h.
Referenced by _readXML(), _writeXML(), and QgsComposerItemGroup::readXML().
QGraphicsLineItem* QgsComposerItem::mVAlignSnapItem protected
Definition at line 454 of file qgscomposeritem.h.
Referenced by deleteVAlignSnapItem(), and vAlignSnapItem().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposeritem.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposeritem.cpp