QGIS API Documentation: QgsMapToolZoom Class Reference
QgsMapToolZoom Class Reference
QGIS gui library.
A map tool for zooming into the map.
#include <qgsmaptoolzoom.h>
Public Member Functions
QgsMapToolZoom (QgsMapCanvas *canvas, bool zoomOut)
constructor
~QgsMapToolZoom ()
virtual void canvasMoveEvent (QMouseEvent *e)
Overridden mouse move event.
virtual void canvasPressEvent (QMouseEvent *e)
Overridden mouse press event.
virtual void canvasReleaseEvent (QMouseEvent *e)
Overridden mouse release event.
virtual bool isTransient ()
Check whether this MapTool performs a zoom or pan operation.
virtual void deactivate ()
called when map tool is being deactivated
Public Member Functions inherited from QgsMapTool
virtual ~QgsMapTool ()
virtual destructor
virtual void canvasDoubleClickEvent (QMouseEvent *e)
Mouse double click event for overriding. Default implementation does nothing.
virtual void wheelEvent (QWheelEvent *e)
Mouse wheel event for overriding.
virtual void keyPressEvent (QKeyEvent *e)
Key event for overriding. Default implementation does nothing.
virtual void keyReleaseEvent (QKeyEvent *e)
Key event for overriding.
virtual Q_DECL_DEPRECATED void renderComplete ()
Called when rendering has finished.
void setAction (QAction *action)
Use this to associate a QAction to this maptool.
QAction * action ()
Return associated action with map tool or NULL if no action is associated.
void setButton (QAbstractButton *button)
Use this to associate a button to this maptool.
QAbstractButton * button ()
Return associated button with map tool or NULL if no button is associated.
virtual void setCursor (QCursor cursor)
Set a user defined cursor.
virtual bool isEditTool ()
Check whether this MapTool performs an edit operation.
virtual void activate ()
called when set as currently active map tool
QgsMapCanvas * canvas ()
returns pointer to the tool's map canvas
QString toolName ()
Emit map tool changed with the old tool.
Protected Attributes
QRect mZoomRect
stores actual zoom rect
bool mZoomOut
indicates whether we're zooming in or out
bool mDragging
Flag to indicate a map canvas drag operation is taking place.
QgsRubberBand * mRubberBand
Protected Attributes inherited from QgsMapTool
QgsMapCanvas * mCanvas
pointer to map canvas
QCursor mCursor
cursor used in map tool
QAction * mAction
optionally map tool can have pointer to action which will be used to set that action as active
QAbstractButton * mButton
optionally map tool can have pointer to a button which will be used to set that action as active
QString mToolName
translated name of the map tool
Additional Inherited Members
Signals inherited from QgsMapTool
void messageEmitted (QString message, QgsMessageBar::MessageLevel=QgsMessageBar::INFO)
emit a message
void messageDiscarded ()
emit signal to clear previous message
Static Public Member Functions inherited from QgsMapTool
static double searchRadiusMM ()
Get search radius in mm.
static double searchRadiusMU (const QgsRenderContext &context)
Get search radius in map units for given context.
static double searchRadiusMU (QgsMapCanvas *canvas)
Get search radius in map units for given canvas.
Protected Member Functions inherited from QgsMapTool
QgsMapTool (QgsMapCanvas *canvas)
constructor takes map canvas as a parameter
QgsPoint toMapCoordinates (const QPoint &point)
transformation from screen coordinates to map coordinates
QgsPoint toLayerCoordinates (QgsMapLayer *layer, const QPoint &point)
transformation from screen coordinates to layer's coordinates
QgsPoint toLayerCoordinates (QgsMapLayer *layer, const QgsPoint &point)
transformation from map coordinates to layer's coordinates
QgsPoint toMapCoordinates (QgsMapLayer *layer, const QgsPoint &point)
transformation from layer's coordinates to map coordinates (which is different in case reprojection is used)
QgsRectangle toLayerCoordinates (QgsMapLayer *layer, const QgsRectangle &rect)
trnasformation of the rect from map coordinates to layer's coordinates
QPoint toCanvasCoordinates (const QgsPoint &point)
transformation from map coordinates to screen coordinates
Detailed Description
A map tool for zooming into the map.
See also
QgsMapTool
Definition at line 28 of file qgsmaptoolzoom.h.
Constructor & Destructor Documentation
QgsMapToolZoom::QgsMapToolZoom (QgsMapCanvas * canvas, bool zoomOut)
constructor
Definition at line 29 of file qgsmaptoolzoom.cpp.
References QgsMapTool::mCursor, zoom_in, and zoom_out.
QgsMapToolZoom::~QgsMapToolZoom ()
Definition at line 37 of file qgsmaptoolzoom.cpp.
References mRubberBand.
Member Function Documentation
void QgsMapToolZoom::canvasMoveEvent (QMouseEvent * e) virtual
Overridden mouse move event.
Reimplemented from QgsMapTool.
Definition at line 43 of file qgsmaptoolzoom.cpp.
References QgsMapTool::mCanvas, mDragging, mRubberBand, mZoomRect, QGis::Polygon, and QgsRubberBand::setToCanvasRectangle().
void QgsMapToolZoom::canvasPressEvent (QMouseEvent * e) virtual
Overridden mouse press event.
Reimplemented from QgsMapTool.
Definition at line 64 of file qgsmaptoolzoom.cpp.
References mZoomRect.
void QgsMapToolZoom::canvasReleaseEvent (QMouseEvent * e) virtual
Overridden mouse release event.
Reimplemented from QgsMapTool.
Definition at line 73 of file qgsmaptoolzoom.cpp.
References QgsRectangle::center(), QgsMapCanvas::extent(), QgsMapCanvas::getCoordinateTransform(), QgsRectangle::height(), QgsMapTool::mCanvas, mDragging, mRubberBand, mZoomOut, mZoomRect, QgsRectangle::normalize(), QgsDebugMsg, QgsMapCanvas::refresh(), QgsRectangle::scale(), QgsMapCanvas::setExtent(), QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsRectangle::setYMaximum(), QgsRectangle::setYMinimum(), QgsMapToPixel::toMapCoordinates(), QgsRectangle::toString(), QgsPoint::toString(), QgsRectangle::width(), QgsPoint::x(), QgsPoint::y(), and QgsMapCanvas::zoomWithCenter().
void QgsMapToolZoom::deactivate () virtual
called when map tool is being deactivated
Reimplemented from QgsMapTool.
Definition at line 149 of file qgsmaptoolzoom.cpp.
References mRubberBand.
virtual bool QgsMapToolZoom::isTransient () inline virtual
Check whether this MapTool performs a zoom or pan operation.
If it does, we will be able to perform the zoom and then resume operations with the original / previously used tool.
Reimplemented from QgsMapTool.
Definition at line 45 of file qgsmaptoolzoom.h.
Member Data Documentation
bool QgsMapToolZoom::mDragging protected
Flag to indicate a map canvas drag operation is taking place.
Definition at line 57 of file qgsmaptoolzoom.h.
Referenced by canvasMoveEvent(), and canvasReleaseEvent().
QgsRubberBand* QgsMapToolZoom::mRubberBand protected
Definition at line 59 of file qgsmaptoolzoom.h.
Referenced by canvasMoveEvent(), canvasReleaseEvent(), deactivate(), and ~QgsMapToolZoom().
bool QgsMapToolZoom::mZoomOut protected
indicates whether we're zooming in or out
Definition at line 54 of file qgsmaptoolzoom.h.
Referenced by canvasReleaseEvent().
QRect QgsMapToolZoom::mZoomRect protected
stores actual zoom rect
Definition at line 51 of file qgsmaptoolzoom.h.
Referenced by canvasMoveEvent(), canvasPressEvent(), and canvasReleaseEvent().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaptoolzoom.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaptoolzoom.cpp