QGIS API Documentation: QgsAttributeTableAction Class Reference
QgsAttributeTableAction Class Reference
#include <qgsdualview.h>
Public Slots
void execute ()
void featureForm ()
Public Member Functions
QgsAttributeTableAction (const QString &name, QgsDualView *dualView, int action, const QModelIndex &fieldIdx)
Private Attributes
QgsDualView * mDualView
int mAction
QModelIndex mFieldIdx
Detailed Description
Definition at line 238 of file qgsdualview.h.
Constructor & Destructor Documentation
QgsAttributeTableAction::QgsAttributeTableAction (const QString & name, QgsDualView * dualView, int action, const QModelIndex & fieldIdx) inline
Definition at line 243 of file qgsdualview.h.
Member Function Documentation
void QgsAttributeTableAction::execute () slot
Definition at line 422 of file qgsdualview.cpp.
References QgsAttributeTableModel::executeAction(), mAction, QgsDualView::masterModel(), mDualView, and mFieldIdx.
void QgsAttributeTableAction::featureForm () slot
Definition at line 427 of file qgsdualview.cpp.
References QgsDualView::AttributeEditor, QgsDualView::masterModel(), mDualView, mFieldIdx, QgsAttributeTableModel::rowToId(), QgsDualView::setCurrentEditSelection(), and QgsDualView::setView().
Member Data Documentation
int QgsAttributeTableAction::mAction private
Definition at line 253 of file qgsdualview.h.
Referenced by execute().
QgsDualView* QgsAttributeTableAction::mDualView private
Definition at line 252 of file qgsdualview.h.
Referenced by execute(), and featureForm().
QModelIndex QgsAttributeTableAction::mFieldIdx private
Definition at line 254 of file qgsdualview.h.
Referenced by execute(), and featureForm().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsdualview.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsdualview.cpp