QGIS API Documentation: QgsMarkerSymbolLayerV2 Class Reference
QgsMarkerSymbolLayerV2 Class Reference abstract
#include <qgssymbollayerv2.h>
Public Types
enum HorizontalAnchorPoint { Left, HCenter, Right }
enum VerticalAnchorPoint { Top, VCenter, Bottom }
Public Member Functions
void startRender (QgsSymbolV2RenderContext &context)
virtual void renderPoint (const QPointF &point, QgsSymbolV2RenderContext &context)=0
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
void setSize (double size)
double size () const
void setScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod)
QgsSymbolV2::ScaleMethod scaleMethod () const
void setOffset (QPointF offset)
QPointF offset ()
virtual void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
virtual void writeSldMarker (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
void setOffsetUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit offsetUnit () const
void setOffsetMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & offsetMapUnitScale () const
void setSizeUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit sizeUnit () const
void setSizeMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & sizeMapUnitScale () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
void setMapUnitScale (const QgsMapUnitScale &scale)
QgsMapUnitScale mapUnitScale () const
void setHorizontalAnchorPoint (HorizontalAnchorPoint h)
HorizontalAnchorPoint horizontalAnchorPoint () const
void setVerticalAnchorPoint (VerticalAnchorPoint v)
VerticalAnchorPoint verticalAnchorPoint () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString layerType () const =0
virtual void stopRender (QgsSymbolV2RenderContext &context)=0
virtual QgsSymbolLayerV2 * clone () const =0
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
virtual QgsStringMap properties () const =0
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
virtual Qt::PenStyle dxfPenStyle () const
Protected Member Functions
QgsMarkerSymbolLayerV2 (bool locked=false)
void markerOffset (const QgsSymbolV2RenderContext &context, double &offsetX, double &offsetY) const
void markerOffset (const QgsSymbolV2RenderContext &context, double width, double height, double &offsetX, double &offsetY) const
void markerOffset (const QgsSymbolV2RenderContext &context, double width, double height, QgsSymbolV2::OutputUnit widthUnit, QgsSymbolV2::OutputUnit heightUnit, double &offsetX, double &offsetY, const QgsMapUnitScale &widthMapUnitScale, const QgsMapUnitScale &heightMapUnitScale) const
Protected Member Functions inherited from QgsSymbolLayerV2
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsFields *fields, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Static Protected Member Functions
static QPointF _rotatedOffset (const QPointF &offset, double angle)
Protected Attributes
double mAngle
double mSize
QgsSymbolV2::OutputUnit mSizeUnit
QgsMapUnitScale mSizeMapUnitScale
QPointF mOffset
QgsSymbolV2::OutputUnit mOffsetUnit
QgsMapUnitScale mOffsetMapUnitScale
QgsSymbolV2::ScaleMethod mScaleMethod
HorizontalAnchorPoint mHorizontalAnchorPoint
VerticalAnchorPoint mVerticalAnchorPoint
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Static Private Member Functions
static
QgsMarkerSymbolLayerV2::HorizontalAnchorPoint decodeHorizontalAnchorPoint (const QString &str)
static
QgsMarkerSymbolLayerV2::VerticalAnchorPoint decodeVerticalAnchorPoint (const QString &str)
Private Attributes
QgsExpression * mOffsetExpression
QgsExpression * mHorizontalAnchorExpression
QgsExpression * mVerticalAnchorExpression
Additional Inherited Members
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 158 of file qgssymbollayerv2.h.
Member Enumeration Documentation
enum QgsMarkerSymbolLayerV2::HorizontalAnchorPoint
Enumerator
Left
HCenter
Right
Definition at line 162 of file qgssymbollayerv2.h.
enum QgsMarkerSymbolLayerV2::VerticalAnchorPoint
Enumerator
Top
VCenter
Bottom
Definition at line 169 of file qgssymbollayerv2.h.
Constructor & Destructor Documentation
QgsMarkerSymbolLayerV2::QgsMarkerSymbolLayerV2 (bool locked = false) protected
Definition at line 195 of file qgssymbollayerv2.cpp.
References mHorizontalAnchorExpression, mOffsetExpression, and mVerticalAnchorExpression.
Member Function Documentation
QPointF QgsMarkerSymbolLayerV2::_rotatedOffset (const QPointF & offset, double angle) static protected
Definition at line 295 of file qgssymbollayerv2.cpp.
References DEG2RAD.
Referenced by QgsEllipseSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsEllipseSymbolLayerV2::writeDxf(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), and QgsSvgMarkerSymbolLayerV2::writeDxf().
double QgsMarkerSymbolLayerV2::angle (void) const inline
Definition at line 183 of file qgssymbollayerv2.h.
Referenced by QgsMarkerSymbolV2::angle(), QgsVectorFieldSymbolLayer::convertPolarToCartesian(), QgsSimpleMarkerSymbolLayerV2::create(), QgsSvgMarkerSymbolLayerV2::create(), QgsFontMarkerSymbolLayerV2::create(), QgsEllipseSymbolLayerV2::createFromSld(), QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsSvgMarkerSymbolLayerV2::createFromSld(), QgsFontMarkerSymbolLayerV2::createFromSld(), QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsMarkerSymbolV2::setAngle(), QgsEllipseSymbolLayerV2::writeDxf(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), QgsSvgMarkerSymbolLayerV2::writeDxf(), QgsEllipseSymbolLayerV2::writeSldMarker(), QgsSimpleMarkerSymbolLayerV2::writeSldMarker(), QgsSvgMarkerSymbolLayerV2::writeSldMarker(), and QgsFontMarkerSymbolLayerV2::writeSldMarker().
QgsMarkerSymbolLayerV2::HorizontalAnchorPoint QgsMarkerSymbolLayerV2::decodeHorizontalAnchorPoint (const QString & str) static private
Definition at line 302 of file qgssymbollayerv2.cpp.
References HCenter, Left, and Right.
Referenced by markerOffset().
QgsMarkerSymbolLayerV2::VerticalAnchorPoint QgsMarkerSymbolLayerV2::decodeVerticalAnchorPoint (const QString & str) static private
Definition at line 318 of file qgssymbollayerv2.cpp.
References Bottom, Top, and VCenter.
Referenced by markerOffset().
void QgsMarkerSymbolLayerV2::drawPreviewIcon (QgsSymbolV2RenderContext & context, QSize size) virtual
Implements QgsSymbolLayerV2.
Reimplemented in QgsVectorFieldSymbolLayer.
Definition at line 222 of file qgssymbollayerv2.cpp.
References renderPoint(), startRender(), and QgsSymbolLayerV2::stopRender().
HorizontalAnchorPoint QgsMarkerSymbolLayerV2::horizontalAnchorPoint () const inline
Definition at line 218 of file qgssymbollayerv2.h.
Referenced by markerOffset().
QgsMapUnitScale QgsMarkerSymbolLayerV2::mapUnitScale () const virtual
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsVectorFieldSymbolLayer.
Definition at line 355 of file qgssymbollayerv2.cpp.
References mOffsetMapUnitScale, and mSizeMapUnitScale.
Referenced by QgsEllipseSymbolLayerV2::mapUnitScale(), QgsVectorFieldSymbolLayer::mapUnitScale(), QgsSimpleMarkerSymbolLayerV2::mapUnitScale(), and QgsSvgMarkerSymbolLayerV2::mapUnitScale().
void QgsMarkerSymbolLayerV2::markerOffset (const QgsSymbolV2RenderContext & context, double & offsetX, double & offsetY) const protected
Definition at line 229 of file qgssymbollayerv2.cpp.
References mSize, mSizeMapUnitScale, and mSizeUnit.
Referenced by markerOffset(), QgsEllipseSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsEllipseSymbolLayerV2::writeDxf(), and QgsSimpleMarkerSymbolLayerV2::writeDxf().
void QgsMarkerSymbolLayerV2::markerOffset (const QgsSymbolV2RenderContext & context, double width, double height, double & offsetX, double & offsetY) const protected
Definition at line 234 of file qgssymbollayerv2.cpp.
References markerOffset(), mSizeMapUnitScale, and mSizeUnit.
void QgsMarkerSymbolLayerV2::markerOffset (const QgsSymbolV2RenderContext & context, double width, double height, QgsSymbolV2::OutputUnit widthUnit, QgsSymbolV2::OutputUnit heightUnit, double & offsetX, double & offsetY, const QgsMapUnitScale & widthMapUnitScale, const QgsMapUnitScale & heightMapUnitScale) const protected
Note
available in python bindings as markerOffset2
Definition at line 239 of file qgssymbollayerv2.cpp.
References Bottom, decodeHorizontalAnchorPoint(), QgsSymbolLayerV2Utils::decodePoint(), decodeVerticalAnchorPoint(), QgsExpression::evaluate(), QgsSymbolV2RenderContext::feature(), HCenter, horizontalAnchorPoint(), Left, QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mHorizontalAnchorExpression, mHorizontalAnchorPoint, mOffset, mOffsetExpression, mOffsetMapUnitScale, mOffsetUnit, mVerticalAnchorExpression, mVerticalAnchorPoint, offset(), QgsSymbolV2RenderContext::renderContext(), Right, Top, VCenter, and verticalAnchorPoint().
QPointF QgsMarkerSymbolLayerV2::offset () inline
Definition at line 192 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsSvgMarkerSymbolLayerV2::createFromSld(), QgsFontMarkerSymbolLayerV2::createFromSld(), markerOffset(), and QgsSvgMarkerSymbolLayerV2::writeDxf().
const QgsMapUnitScale& QgsMarkerSymbolLayerV2::offsetMapUnitScale () const inline
Definition at line 203 of file qgssymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsMarkerSymbolLayerV2::offsetUnit () const inline
Definition at line 200 of file qgssymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsMarkerSymbolLayerV2::outputUnit () const virtual
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsVectorFieldSymbolLayer.
Definition at line 340 of file qgssymbollayerv2.cpp.
References QgsSymbolV2::Mixed, mOffsetUnit, and mSizeUnit.
Referenced by QgsEllipseSymbolLayerV2::outputUnit(), QgsVectorFieldSymbolLayer::outputUnit(), QgsSimpleMarkerSymbolLayerV2::outputUnit(), and QgsSvgMarkerSymbolLayerV2::outputUnit().
virtual void QgsMarkerSymbolLayerV2::renderPoint (const QPointF & point, QgsSymbolV2RenderContext & context) pure virtual
Implemented in QgsFontMarkerSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, QgsVectorFieldSymbolLayer, and QgsEllipseSymbolLayerV2.
Referenced by drawPreviewIcon(), and QgsMarkerSymbolV2::renderPoint().
QgsSymbolV2::ScaleMethod QgsMarkerSymbolLayerV2::scaleMethod () const inline
Definition at line 189 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::create(), QgsSvgMarkerSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2(), and QgsMarkerSymbolV2::scaleMethod().
void QgsMarkerSymbolLayerV2::setAngle (double angle) inline
Definition at line 182 of file qgssymbollayerv2.h.
References MathUtils::angle().
Referenced by QgsEllipseSymbolLayerV2::create(), QgsEllipseSymbolLayerV2::createFromSld(), QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsSvgMarkerSymbolLayerV2::createFromSld(), QgsFontMarkerSymbolLayerV2::createFromSld(), and QgsMarkerSymbolV2::setAngle().
void QgsMarkerSymbolLayerV2::setHorizontalAnchorPoint (HorizontalAnchorPoint h) inline
Definition at line 217 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsEllipseSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsSvgMarkerSymbolLayerV2::create(), and QgsFontMarkerSymbolLayerV2::create().
void QgsMarkerSymbolLayerV2::setMapUnitScale (const QgsMapUnitScale & scale) virtual
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsVectorFieldSymbolLayer.
Definition at line 349 of file qgssymbollayerv2.cpp.
References mOffsetMapUnitScale, and mSizeMapUnitScale.
Referenced by QgsEllipseSymbolLayerV2::setMapUnitScale(), QgsVectorFieldSymbolLayer::setMapUnitScale(), QgsSimpleMarkerSymbolLayerV2::setMapUnitScale(), and QgsSvgMarkerSymbolLayerV2::setMapUnitScale().
void QgsMarkerSymbolLayerV2::setOffset (QPointF offset) inline
Definition at line 191 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsEllipseSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsVectorFieldSymbolLayer::create(), QgsSvgMarkerSymbolLayerV2::create(), QgsFontMarkerSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsSvgMarkerSymbolLayerV2::createFromSld(), and QgsFontMarkerSymbolLayerV2::createFromSld().
void QgsMarkerSymbolLayerV2::setOffsetMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 202 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsEllipseSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsVectorFieldSymbolLayer::create(), QgsSvgMarkerSymbolLayerV2::create(), and QgsFontMarkerSymbolLayerV2::create().
void QgsMarkerSymbolLayerV2::setOffsetUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 199 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsEllipseSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsVectorFieldSymbolLayer::create(), QgsSvgMarkerSymbolLayerV2::create(), and QgsFontMarkerSymbolLayerV2::create().
void QgsMarkerSymbolLayerV2::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsVectorFieldSymbolLayer.
Definition at line 334 of file qgssymbollayerv2.cpp.
References mOffsetUnit, and mSizeUnit.
Referenced by QgsEllipseSymbolLayerV2::setOutputUnit(), QgsVectorFieldSymbolLayer::setOutputUnit(), QgsSimpleMarkerSymbolLayerV2::setOutputUnit(), and QgsSvgMarkerSymbolLayerV2::setOutputUnit().
void QgsMarkerSymbolLayerV2::setScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod) inline
Definition at line 188 of file qgssymbollayerv2.h.
Referenced by QgsMarkerSymbolV2::setScaleMethod().
void QgsMarkerSymbolLayerV2::setSize (double size) inline
Definition at line 185 of file qgssymbollayerv2.h.
References size.
Referenced by QgsEllipseSymbolLayerV2::create(), QgsVectorFieldSymbolLayer::create(), and QgsMarkerSymbolV2::setSize().
void QgsMarkerSymbolLayerV2::setSizeMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 208 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsEllipseSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsVectorFieldSymbolLayer::create(), QgsSvgMarkerSymbolLayerV2::create(), and QgsFontMarkerSymbolLayerV2::create().
void QgsMarkerSymbolLayerV2::setSizeUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 205 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsEllipseSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsVectorFieldSymbolLayer::create(), QgsSvgMarkerSymbolLayerV2::create(), and QgsFontMarkerSymbolLayerV2::create().
void QgsMarkerSymbolLayerV2::setVerticalAnchorPoint (VerticalAnchorPoint v) inline
Definition at line 220 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsEllipseSymbolLayerV2::create(), QgsSimpleMarkerSymbolLayerV2::create(), QgsSvgMarkerSymbolLayerV2::create(), and QgsFontMarkerSymbolLayerV2::create().
double QgsMarkerSymbolLayerV2::size (void) const inline
Definition at line 186 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::create(), QgsSvgMarkerSymbolLayerV2::create(), QgsEllipseSymbolLayerV2::createFromSld(), QgsSimpleMarkerSymbolLayerV2::createFromSld(), QgsSvgMarkerSymbolLayerV2::createFromSld(), QgsFontMarkerSymbolLayerV2::createFromSld(), QgsVectorFieldSymbolLayer::drawPreviewIcon(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsMarkerSymbolV2::setSize(), QgsMarkerSymbolV2::size(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), and QgsSvgMarkerSymbolLayerV2::writeDxf().
const QgsMapUnitScale& QgsMarkerSymbolLayerV2::sizeMapUnitScale () const inline
Definition at line 209 of file qgssymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsMarkerSymbolLayerV2::sizeUnit () const inline
Definition at line 206 of file qgssymbollayerv2.h.
void QgsMarkerSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Reimplemented in QgsVectorFieldSymbolLayer.
Definition at line 214 of file qgssymbollayerv2.cpp.
References QgsSymbolLayerV2::expression(), mHorizontalAnchorExpression, mOffsetExpression, and mVerticalAnchorExpression.
Referenced by drawPreviewIcon(), QgsEllipseSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), and QgsSvgMarkerSymbolLayerV2::startRender().
void QgsMarkerSymbolLayerV2::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsVectorFieldSymbolLayer, and QgsEllipseSymbolLayerV2.
Definition at line 461 of file qgssymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::createGeometryElement(), and writeSldMarker().
VerticalAnchorPoint QgsMarkerSymbolLayerV2::verticalAnchorPoint () const inline
Definition at line 221 of file qgssymbollayerv2.h.
Referenced by markerOffset().
virtual void QgsMarkerSymbolLayerV2::writeSldMarker (QDomDocument & doc, QDomElement & element, QgsStringMap props) const inline virtual
Reimplemented in QgsFontMarkerSymbolLayerV2, QgsSvgMarkerSymbolLayerV2, QgsSimpleMarkerSymbolLayerV2, and QgsEllipseSymbolLayerV2.
Definition at line 196 of file qgssymbollayerv2.h.
References QgsSymbolLayerV2::layerType().
Referenced by QgsMarkerLineSymbolLayerV2::toSld(), toSld(), and QgsPointPatternFillSymbolLayer::toSld().
Member Data Documentation
double QgsMarkerSymbolLayerV2::mAngle protected
Definition at line 239 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsEllipseSymbolLayerV2::QgsEllipseSymbolLayerV2(), QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2(), QgsEllipseSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsEllipseSymbolLayerV2::writeDxf(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), QgsSvgMarkerSymbolLayerV2::writeDxf(), QgsEllipseSymbolLayerV2::writeSldMarker(), QgsSimpleMarkerSymbolLayerV2::writeSldMarker(), QgsSvgMarkerSymbolLayerV2::writeSldMarker(), and QgsFontMarkerSymbolLayerV2::writeSldMarker().
QgsExpression* QgsMarkerSymbolLayerV2::mHorizontalAnchorExpression private
Definition at line 255 of file qgssymbollayerv2.h.
Referenced by markerOffset(), QgsMarkerSymbolLayerV2(), and startRender().
HorizontalAnchorPoint QgsMarkerSymbolLayerV2::mHorizontalAnchorPoint protected
Definition at line 247 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), markerOffset(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsSvgMarkerSymbolLayerV2::properties(), and QgsFontMarkerSymbolLayerV2::properties().
QPointF QgsMarkerSymbolLayerV2::mOffset protected
Definition at line 243 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), markerOffset(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsVectorFieldSymbolLayer::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsEllipseSymbolLayerV2::QgsEllipseSymbolLayerV2(), QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::writeDxf(), QgsSimpleMarkerSymbolLayerV2::writeSldMarker(), QgsSvgMarkerSymbolLayerV2::writeSldMarker(), and QgsFontMarkerSymbolLayerV2::writeSldMarker().
QgsExpression* QgsMarkerSymbolLayerV2::mOffsetExpression private
Definition at line 254 of file qgssymbollayerv2.h.
Referenced by markerOffset(), QgsMarkerSymbolLayerV2(), and startRender().
QgsMapUnitScale QgsMarkerSymbolLayerV2::mOffsetMapUnitScale protected
Definition at line 245 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), mapUnitScale(), markerOffset(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsVectorFieldSymbolLayer::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), and setMapUnitScale().
QgsSymbolV2::OutputUnit QgsMarkerSymbolLayerV2::mOffsetUnit protected
Definition at line 244 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), markerOffset(), outputUnit(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsVectorFieldSymbolLayer::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), and setOutputUnit().
QgsSymbolV2::ScaleMethod QgsMarkerSymbolLayerV2::mScaleMethod protected
Definition at line 246 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), and QgsSvgMarkerSymbolLayerV2::writeDxf().
double QgsMarkerSymbolLayerV2::mSize protected
Definition at line 240 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), markerOffset(), QgsSimpleMarkerSymbolLayerV2::ogrFeatureStyle(), QgsSimpleMarkerSymbolLayerV2::prepareCache(), QgsEllipseSymbolLayerV2::preparePath(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsVectorFieldSymbolLayer::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSvgMarkerSymbolLayerV2::QgsSvgMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsSvgMarkerSymbolLayerV2::startRender(), QgsFontMarkerSymbolLayerV2::startRender(), QgsEllipseSymbolLayerV2::writeDxf(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), QgsSvgMarkerSymbolLayerV2::writeDxf(), QgsSimpleMarkerSymbolLayerV2::writeSldMarker(), QgsSvgMarkerSymbolLayerV2::writeSldMarker(), and QgsFontMarkerSymbolLayerV2::writeSldMarker().
QgsMapUnitScale QgsMarkerSymbolLayerV2::mSizeMapUnitScale protected
Definition at line 242 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), mapUnitScale(), markerOffset(), QgsSimpleMarkerSymbolLayerV2::prepareCache(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsVectorFieldSymbolLayer::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), setMapUnitScale(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsFontMarkerSymbolLayerV2::startRender(), and QgsSimpleMarkerSymbolLayerV2::writeDxf().
QgsSymbolV2::OutputUnit QgsMarkerSymbolLayerV2::mSizeUnit protected
Definition at line 241 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), markerOffset(), outputUnit(), QgsSimpleMarkerSymbolLayerV2::prepareCache(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsVectorFieldSymbolLayer::properties(), QgsSvgMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::properties(), QgsFontMarkerSymbolLayerV2::QgsFontMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), setOutputUnit(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsFontMarkerSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::writeDxf(), and QgsSvgMarkerSymbolLayerV2::writeDxf().
QgsExpression* QgsMarkerSymbolLayerV2::mVerticalAnchorExpression private
Definition at line 256 of file qgssymbollayerv2.h.
Referenced by markerOffset(), QgsMarkerSymbolLayerV2(), and startRender().
VerticalAnchorPoint QgsMarkerSymbolLayerV2::mVerticalAnchorPoint protected
Definition at line 248 of file qgssymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2::clone(), QgsSvgMarkerSymbolLayerV2::clone(), QgsFontMarkerSymbolLayerV2::clone(), markerOffset(), QgsEllipseSymbolLayerV2::properties(), QgsSimpleMarkerSymbolLayerV2::properties(), QgsSvgMarkerSymbolLayerV2::properties(), and QgsFontMarkerSymbolLayerV2::properties().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2.cpp