QGIS API Documentation: QgsMapLayerProxyModel Class Reference
QgsMapLayerProxyModel Class Reference
The QgsMapLayerProxModel class provides an easy to use model to display the list of layers in widgets.
#include <qgsmaplayerproxymodel.h>
Public Types
enum Filter {
RasterLayer = 1, NoGeometry = 2, PointLayer = 4, LineLayer = 8,
PolygonLayer = 16, HasGeometry = PointLayer | LineLayer | PolygonLayer, VectorLayer = NoGeometry | HasGeometry, PluginLayer = 32,
All = RasterLayer | PolygonLayer | PluginLayer
}
Public Member Functions
QgsMapLayerProxyModel (QObject *parent=0)
QgsMapLayerProxModel creates a proxy model with a QgsMapLayerModel as source model.
QgsMapLayerModel * sourceLayerModel ()
layerModel returns the QgsMapLayerModel used in this QSortFilterProxyModel
QgsMapLayerProxyModel * setFilters (Filters filters)
setFilters set flags that affect how layers are filtered
const Filters & filters () const
bool filterAcceptsRow (int source_row, const QModelIndex &source_parent) const
bool lessThan (const QModelIndex &left, const QModelIndex &right) const
Private Attributes
Filters mFilters
QgsMapLayerModel * mModel
Detailed Description
The QgsMapLayerProxModel class provides an easy to use model to display the list of layers in widgets.
Note
added in 2.3
Definition at line 27 of file qgsmaplayerproxymodel.h.
Member Enumeration Documentation
enum QgsMapLayerProxyModel::Filter
Enumerator
RasterLayer
NoGeometry
PointLayer
LineLayer
PolygonLayer
HasGeometry
VectorLayer
PluginLayer
All
Definition at line 32 of file qgsmaplayerproxymodel.h.
Constructor & Destructor Documentation
QgsMapLayerProxyModel::QgsMapLayerProxyModel (QObject * parent = 0) explicit
QgsMapLayerProxModel creates a proxy model with a QgsMapLayerModel as source model.
It can be used to filter the layers list in a widget.
Definition at line 21 of file qgsmaplayerproxymodel.cpp.
References mModel.
Member Function Documentation
bool QgsMapLayerProxyModel::filterAcceptsRow (int source_row, const QModelIndex & source_parent) const
Definition at line 36 of file qgsmaplayerproxymodel.cpp.
References All, QgsVectorLayer::geometryType(), HasGeometry, QgsVectorLayer::hasGeometryType(), index, QGis::Line, LineLayer, mFilters, NoGeometry, QGis::NoGeometry, PluginLayer, QgsMapLayer::PluginLayer, QGis::Point, PointLayer, QGis::Polygon, PolygonLayer, RasterLayer, QgsMapLayer::RasterLayer, QgsMapLayer::type(), VectorLayer, and QgsMapLayer::VectorLayer.
const Filters& QgsMapLayerProxyModel::filters () const inline
Definition at line 63 of file qgsmaplayerproxymodel.h.
Referenced by QgsMapLayerComboBox::filters(), and setFilters().
bool QgsMapLayerProxyModel::lessThan (const QModelIndex & left, const QModelIndex & right) const
Definition at line 79 of file qgsmaplayerproxymodel.cpp.
QgsMapLayerProxyModel * QgsMapLayerProxyModel::setFilters (Filters filters)
setFilters set flags that affect how layers are filtered
Parameters
filters are Filter flags
Note
added in 2.3
Definition at line 29 of file qgsmaplayerproxymodel.cpp.
References filters(), and mFilters.
Referenced by QgsMapLayerComboBox::setFilters().
QgsMapLayerModel* QgsMapLayerProxyModel::sourceLayerModel () inline
layerModel returns the QgsMapLayerModel used in this QSortFilterProxyModel
Definition at line 55 of file qgsmaplayerproxymodel.h.
Referenced by QgsMapLayerComboBox::setLayer().
Member Data Documentation
Filters QgsMapLayerProxyModel::mFilters private
Definition at line 66 of file qgsmaplayerproxymodel.h.
Referenced by filterAcceptsRow(), and setFilters().
QgsMapLayerModel* QgsMapLayerProxyModel::mModel private
Definition at line 67 of file qgsmaplayerproxymodel.h.
Referenced by QgsMapLayerProxyModel().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaplayerproxymodel.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaplayerproxymodel.cpp