QGIS API Documentation: QgsPreviewEffect Class Reference
QgsPreviewEffect Class Reference
QGIS gui library.
A graphics effect which can be applied to a widget to simulate various printing and color blindness modes.
#include <qgsprevieweffect.h>
Public Types
enum PreviewMode { PreviewGrayscale, PreviewMono, PreviewProtanope, PreviewDeuteranope }
Public Member Functions
QgsPreviewEffect (QObject *parent)
~QgsPreviewEffect ()
void setMode (PreviewMode mode)
Sets the mode for the preview effect, which controls how the effect modifies a widgets appearance.
PreviewMode mode () const
Returns the mode used for the preview effect.
Protected Member Functions
virtual void draw (QPainter *painter)
Private Member Functions
QRgb simulateColorBlindness (QRgb &originalColor, PreviewMode type)
void simulateProtanopeLMS (double &L, double &M, double &S)
void simulateDeuteranopeLMS (double &L, double &M, double &S)
Private Attributes
PreviewMode mMode
Detailed Description
A graphics effect which can be applied to a widget to simulate various printing and color blindness modes.
Definition at line 28 of file qgsprevieweffect.h.
Member Enumeration Documentation
enum QgsPreviewEffect::PreviewMode
Enumerator
PreviewGrayscale
PreviewMono
PreviewProtanope
PreviewDeuteranope
Definition at line 33 of file qgsprevieweffect.h.
Constructor & Destructor Documentation
QgsPreviewEffect::QgsPreviewEffect (QObject * parent)
Definition at line 22 of file qgsprevieweffect.cpp.
QgsPreviewEffect::~QgsPreviewEffect ()
Definition at line 30 of file qgsprevieweffect.cpp.
Member Function Documentation
void QgsPreviewEffect::draw (QPainter * painter) protected virtual
Definition at line 41 of file qgsprevieweffect.cpp.
References mMode, PreviewDeuteranope, PreviewGrayscale, PreviewMono, PreviewProtanope, and simulateColorBlindness().
PreviewMode QgsPreviewEffect::mode () const inline
Returns the mode used for the preview effect.
Returns
PreviewMode currently used by the effect
Note
added in 2.3
See also
setMode
Definition at line 55 of file qgsprevieweffect.h.
Referenced by QgsMapCanvas::previewMode(), and setMode().
void QgsPreviewEffect::setMode (QgsPreviewEffect::PreviewMode mode)
Sets the mode for the preview effect, which controls how the effect modifies a widgets appearance.
Parameters
mode PreviewMode to use to draw the widget
Note
added in 2.3
See also
mode
Definition at line 35 of file qgsprevieweffect.cpp.
References mMode, and mode().
Referenced by QgsComposerView::setPreviewMode(), and QgsMapCanvas::setPreviewMode().
QRgb QgsPreviewEffect::simulateColorBlindness (QRgb & originalColor, QgsPreviewEffect::PreviewMode mode) private
Definition at line 106 of file qgsprevieweffect.cpp.
References PreviewDeuteranope, PreviewProtanope, simulateDeuteranopeLMS(), and simulateProtanopeLMS().
Referenced by draw().
void QgsPreviewEffect::simulateDeuteranopeLMS (double & L, double & M, double & S) private
Definition at line 152 of file qgsprevieweffect.cpp.
Referenced by simulateColorBlindness().
void QgsPreviewEffect::simulateProtanopeLMS (double & L, double & M, double & S) private
Definition at line 145 of file qgsprevieweffect.cpp.
Referenced by simulateColorBlindness().
Member Data Documentation
PreviewMode QgsPreviewEffect::mMode private
Definition at line 62 of file qgsprevieweffect.h.
Referenced by draw(), and setMode().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsprevieweffect.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsprevieweffect.cpp