QGIS API Documentation: QgsInvertedPolygonRenderer Class Reference
QgsInvertedPolygonRenderer Class Reference
QgsInvertedPolygonRenderer is a polygon-only feature renderer used to display features inverted, where the exterior is turned to an interior and where the exterior theoretically spans the entire plane, allowing to mask the surroundings of some features.
#include <qgsinvertedpolygonrenderer.h>
Classes
struct CombinedFeature
Structure where the reversed geometry is built during renderFeature.
struct FeatureDecoration
Class used to represent features that must be rendered with decorations (selection, vertex markers)
Public Member Functions
QgsInvertedPolygonRenderer (const QgsFeatureRendererV2 *embeddedRenderer=0)
Constructor.
virtual ~QgsInvertedPolygonRenderer ()
virtual QgsFeatureRendererV2 * clone ()
Used to clone this feature renderer.
virtual void startRender (QgsRenderContext &context, const QgsFields &fields)
virtual bool renderFeature (QgsFeature &feature, QgsRenderContext &context, int layer=-1, bool selected=false, bool drawVertexMarker=false)
Renders a given feature.
virtual void stopRender (QgsRenderContext &context)
The actual rendering will take place here.
virtual QString dump () const
virtual QList< QString > usedAttributes ()
Proxy that will call this method on the embedded renderer.
virtual int capabilities ()
Proxy that will call this method on the embedded renderer.
virtual QgsSymbolV2List symbols ()
Proxy that will call this method on the embedded renderer.
virtual QgsSymbolV2 * symbolForFeature (QgsFeature &feature)
Proxy that will call this method on the embedded renderer.
virtual QgsSymbolV2List symbolsForFeature (QgsFeature &feat)
Proxy that will call this method on the embedded renderer.
virtual QgsLegendSymbologyList legendSymbologyItems (QSize iconSize)
Proxy that will call this method on the embedded renderer.
virtual QgsLegendSymbolList legendSymbolItems (double scaleDenominator=-1, QString rule="")
Proxy that will call this method on the embedded renderer.
virtual bool willRenderFeature (QgsFeature &feat)
Proxy that will call this method on the embedded renderer.
virtual QDomElement save (QDomDocument &doc)
Creates an XML representation of the renderer.
void setEmbeddedRenderer (const QgsFeatureRendererV2 *subRenderer)
sets the embedded renderer
const QgsFeatureRendererV2 * embeddedRenderer () const
bool preprocessingEnabled () const
void setPreprocessingEnabled (bool enabled)
Public Member Functions inherited from QgsFeatureRendererV2
QString type () const
virtual Q_DECL_DEPRECATED void startRender (QgsRenderContext &context, const QgsVectorLayer *vlayer)
virtual ~QgsFeatureRendererV2 ()
bool usingSymbolLevels () const
void setUsingSymbolLevels (bool usingSymbolLevels)
virtual QDomElement writeSld (QDomDocument &doc, const QgsVectorLayer &layer) const
create the SLD UserStyle element following the SLD v1.1 specs
virtual void toSld (QDomDocument &doc, QDomElement &element) const
used from subclasses to create SLD Rule elements following SLD v1.1 specs
void setVertexMarkerAppearance (int type, int size)
set type and size of editing vertex markers for subsequent rendering
virtual QString rotationField () const
return rotation field name (or empty string if not set or not supported by renderer)
virtual void setRotationField (QString fieldName)
sets rotation field of renderer (if supported by the renderer)
Static Public Member Functions
static QgsFeatureRendererV2 * create (QDomElement &element)
Creates a renderer out of an XML, for loading.
Static Public Member Functions inherited from QgsFeatureRendererV2
static QgsFeatureRendererV2 * defaultRenderer (QGis::GeometryType geomType)
return a new renderer - used by default in vector layers
static QgsFeatureRendererV2 * load (QDomElement &symbologyElem)
create a renderer from XML element
static QgsFeatureRendererV2 * loadSld (const QDomNode &node, QGis::GeometryType geomType, QString &errorMessage)
create a new renderer according to the information contained in the UserStyle element of a SLD style document
Private Types
typedef QVector< CombinedFeature > FeatureCategoryVector
Private Member Functions
QgsInvertedPolygonRenderer (const QgsInvertedPolygonRenderer &)
Private copy constructor.
QgsInvertedPolygonRenderer & operator= (const QgsInvertedPolygonRenderer &)
Private assignment operator.
Private Attributes
QScopedPointer
< QgsFeatureRendererV2 > mSubRenderer
Embedded renderer.
FeatureCategoryVector mFeaturesCategories
where features are stored, based on the index of their symbol category
QMap< QByteArray, int > mSymbolCategories
maps a category to an index
QgsPolygon mExtentPolygon
the polygon used as exterior ring that covers the current extent
QgsRenderContext mContext
the context used for rendering
QgsFields mFields
fields of each feature
QList< FeatureDecoration > mFeatureDecorations
bool mPreprocessingEnabled
whether to preprocess (merge) geometries before rendering
Additional Inherited Members
Public Types inherited from QgsFeatureRendererV2
enum Capabilities {
SymbolLevels = 1, RotationField = 1 << 1, MoreSymbolsPerFeature = 1 << 2, Filter = 1 << 3,
ScaleDependent = 1 << 4
}
Protected Member Functions inherited from QgsFeatureRendererV2
QgsFeatureRendererV2 (QString type)
void renderFeatureWithSymbol (QgsFeature &feature, QgsSymbolV2 *symbol, QgsRenderContext &context, int layer, bool selected, bool drawVertexMarker)
void renderVertexMarker (QPointF &pt, QgsRenderContext &context)
render editing vertex marker at specified point
void renderVertexMarkerPolyline (QPolygonF &pts, QgsRenderContext &context)
render editing vertex marker for a polyline
void renderVertexMarkerPolygon (QPolygonF &pts, QList< QPolygonF > *rings, QgsRenderContext &context)
render editing vertex marker for a polygon
void setScaleMethodToSymbol (QgsSymbolV2 *symbol, int scaleMethod)
Static Protected Member Functions inherited from QgsFeatureRendererV2
static const unsigned char * _getPoint (QPointF &pt, QgsRenderContext &context, const unsigned char *wkb)
static const unsigned char * _getLineString (QPolygonF &pts, QgsRenderContext &context, const unsigned char *wkb)
static const unsigned char * _getPolygon (QPolygonF &pts, QList< QPolygonF > &holes, QgsRenderContext &context, const unsigned char *wkb)
Protected Attributes inherited from QgsFeatureRendererV2
QString mType
bool mUsingSymbolLevels
int mCurrentVertexMarkerType
The current type of editing marker.
int mCurrentVertexMarkerSize
The current size of editing marker.
Detailed Description
QgsInvertedPolygonRenderer is a polygon-only feature renderer used to display features inverted, where the exterior is turned to an interior and where the exterior theoretically spans the entire plane, allowing to mask the surroundings of some features.
It is designed on top of another feature renderer, which is called "embedded" Most of the methods are then only proxies to the embedded renderer.
Features are collected to form one "inverted" polygon during renderFeature() and rendered on stopRender().
Note
added in 2.4
Definition at line 40 of file qgsinvertedpolygonrenderer.h.
Member Typedef Documentation
typedef QVector<CombinedFeature> QgsInvertedPolygonRenderer::FeatureCategoryVector private
Definition at line 136 of file qgsinvertedpolygonrenderer.h.
Constructor & Destructor Documentation
QgsInvertedPolygonRenderer::QgsInvertedPolygonRenderer (const QgsFeatureRendererV2 * embeddedRenderer = 0)
Constructor.
Parameters
embeddedRenderer optional embeddedRenderer. If null, a default one will be assigned
Definition at line 30 of file qgsinvertedpolygonrenderer.cpp.
References QgsFeatureRendererV2::defaultRenderer(), mSubRenderer, QGis::Polygon, and setEmbeddedRenderer().
Referenced by clone(), and create().
QgsInvertedPolygonRenderer::~QgsInvertedPolygonRenderer () virtual
Definition at line 44 of file qgsinvertedpolygonrenderer.cpp.
QgsInvertedPolygonRenderer::QgsInvertedPolygonRenderer (const QgsInvertedPolygonRenderer &) private
Private copy constructor.
See also
clone()
Member Function Documentation
int QgsInvertedPolygonRenderer::capabilities () virtual
Proxy that will call this method on the embedded renderer.
Reimplemented from QgsFeatureRendererV2.
Definition at line 398 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
Referenced by renderFeature().
QgsFeatureRendererV2 * QgsInvertedPolygonRenderer::clone () virtual
Used to clone this feature renderer.
Implements QgsFeatureRendererV2.
Definition at line 328 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer, preprocessingEnabled(), QgsInvertedPolygonRenderer(), and setPreprocessingEnabled().
Referenced by setEmbeddedRenderer().
QgsFeatureRendererV2 * QgsInvertedPolygonRenderer::create (QDomElement & element) static
Creates a renderer out of an XML, for loading.
Definition at line 343 of file qgsinvertedpolygonrenderer.cpp.
References QgsFeatureRendererV2::load(), QgsInvertedPolygonRenderer(), setEmbeddedRenderer(), and setPreprocessingEnabled().
Referenced by QgsRendererV2Registry::QgsRendererV2Registry().
QString QgsInvertedPolygonRenderer::dump () const virtual
Returns
a textual representation of the renderer
Reimplemented from QgsFeatureRendererV2.
Definition at line 319 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
const QgsFeatureRendererV2 * QgsInvertedPolygonRenderer::embeddedRenderer () const
Returns
the current embedded renderer
Definition at line 60 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
QgsLegendSymbolList QgsInvertedPolygonRenderer::legendSymbolItems (double scaleDenominator = -1, QString rule = "") virtual
Proxy that will call this method on the embedded renderer.
Note
not available in python bindings
Reimplemented from QgsFeatureRendererV2.
Definition at line 425 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
QgsLegendSymbologyList QgsInvertedPolygonRenderer::legendSymbologyItems (QSize iconSize) virtual
Proxy that will call this method on the embedded renderer.
Reimplemented from QgsFeatureRendererV2.
Definition at line 416 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
QgsInvertedPolygonRenderer& QgsInvertedPolygonRenderer::operator= (const QgsInvertedPolygonRenderer &) private
Private assignment operator.
See also
clone()
bool QgsInvertedPolygonRenderer::preprocessingEnabled () const inline
Returns
true if the geometries are to be preprocessed (merged with an union) before rendering.
Definition at line 112 of file qgsinvertedpolygonrenderer.h.
Referenced by clone(), and save().
bool QgsInvertedPolygonRenderer::renderFeature (QgsFeature & feature, QgsRenderContext & context, int layer = -1, bool selected = false, bool drawVertexMarker = false) virtual
Renders a given feature.
This will here collect features. The actual rendering will be postponed to stopRender()
Parameters
feature the feature to render
context the rendering context
layer the symbol layer to render, if that makes sense
selected whether this feature has been selected (this will add decorations)
drawVertexMarker whether this feature has vertex markers (in edit mode usually)
Returns
true if the rendering was ok
Reimplemented from QgsFeatureRendererV2.
Definition at line 123 of file qgsinvertedpolygonrenderer.cpp.
References capabilities(), QgsRenderContext::coordinateTransform(), QgsInvertedPolygonRenderer::CombinedFeature::feature, QgsInvertedPolygonRenderer::CombinedFeature::geometries, QgsFeature::geometry(), mFeatureDecorations, mFeaturesCategories, QgsFeatureRendererV2::MoreSymbolsPerFeature, mPreprocessingEnabled, mSubRenderer, mSymbolCategories, QgsRenderContext::painter(), and QgsCoordinateTransform::transform().
QDomElement QgsInvertedPolygonRenderer::save (QDomDocument & doc) virtual
Creates an XML representation of the renderer.
Used for saving purpose
Parameters
doc the XML document where to create the XML subtree
Returns
the created XML subtree
Reimplemented from QgsFeatureRendererV2.
Definition at line 356 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer, preprocessingEnabled(), and RENDERER_TAG_NAME.
void QgsInvertedPolygonRenderer::setEmbeddedRenderer (const QgsFeatureRendererV2 * subRenderer)
sets the embedded renderer
Parameters
subRenderer the embedded renderer (will be cloned)
Definition at line 48 of file qgsinvertedpolygonrenderer.cpp.
References clone(), and mSubRenderer.
Referenced by create(), and QgsInvertedPolygonRenderer().
void QgsInvertedPolygonRenderer::setPreprocessingEnabled (bool enabled) inline
Parameters
enabled enables or disables the preprocessing. When enabled, geometries will be merged with an union before being rendered. It allows to fix some rendering artefacts (when rendering overlapping polygons for instance). This will involve some CPU-demanding computations and is thus disabled by default.
Definition at line 119 of file qgsinvertedpolygonrenderer.h.
Referenced by clone(), and create().
void QgsInvertedPolygonRenderer::startRender (QgsRenderContext & context, const QgsFields & fields) virtual
Implements QgsFeatureRendererV2.
Definition at line 65 of file qgsinvertedpolygonrenderer.cpp.
References QgsRenderContext::coordinateTransform(), QgsRenderContext::mapToPixel(), mContext, mExtentPolygon, mFeatureDecorations, mFeaturesCategories, mFields, mSubRenderer, mSymbolCategories, QgsRenderContext::painter(), QgsRenderContext::setCoordinateTransform(), QgsRenderContext::setExtent(), and QgsMapToPixel::toMapCoordinates().
void QgsInvertedPolygonRenderer::stopRender (QgsRenderContext & context) virtual
The actual rendering will take place here.
Features collected during renderFeature() are rendered using the embedded feature renderer
Implements QgsFeatureRendererV2.
Definition at line 215 of file qgsinvertedpolygonrenderer.cpp.
References QgsGeometry::asMultiPolygon(), QgsGeometry::asPolygon(), QgsGeometry::difference(), QgsInvertedPolygonRenderer::FeatureDecoration::drawMarkers, QgsInvertedPolygonRenderer::FeatureDecoration::feature, QgsGeometry::fromMultiPolygon(), QgsGeometry::fromPolygon(), QgsFeature::geometry(), QgsInvertedPolygonRenderer::FeatureDecoration::layer, mContext, mExtentPolygon, mFeatureDecorations, mFeaturesCategories, mFields, mPreprocessingEnabled, mSubRenderer, QgsRenderContext::painter(), QgsInvertedPolygonRenderer::FeatureDecoration::selected, QgsFeature::setGeometry(), QgsGeometry::unaryUnion(), QGis::WKBMultiPolygon, QGis::WKBMultiPolygon25D, QGis::WKBPolygon, QGis::WKBPolygon25D, and QgsGeometry::wkbType().
QgsSymbolV2 * QgsInvertedPolygonRenderer::symbolForFeature (QgsFeature & feature) virtual
Proxy that will call this method on the embedded renderer.
Implements QgsFeatureRendererV2.
Definition at line 371 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
QgsSymbolV2List QgsInvertedPolygonRenderer::symbols () virtual
Proxy that will call this method on the embedded renderer.
Implements QgsFeatureRendererV2.
Definition at line 389 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
QgsSymbolV2List QgsInvertedPolygonRenderer::symbolsForFeature (QgsFeature & feat) virtual
Proxy that will call this method on the embedded renderer.
Reimplemented from QgsFeatureRendererV2.
Definition at line 380 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
QList< QString > QgsInvertedPolygonRenderer::usedAttributes () virtual
Proxy that will call this method on the embedded renderer.
Implements QgsFeatureRendererV2.
Definition at line 407 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
bool QgsInvertedPolygonRenderer::willRenderFeature (QgsFeature & feat) virtual
Proxy that will call this method on the embedded renderer.
Reimplemented from QgsFeatureRendererV2.
Definition at line 434 of file qgsinvertedpolygonrenderer.cpp.
References mSubRenderer.
Member Data Documentation
QgsRenderContext QgsInvertedPolygonRenderer::mContext private
the context used for rendering
Definition at line 147 of file qgsinvertedpolygonrenderer.h.
Referenced by startRender(), and stopRender().
QgsPolygon QgsInvertedPolygonRenderer::mExtentPolygon private
the polygon used as exterior ring that covers the current extent
Definition at line 144 of file qgsinvertedpolygonrenderer.h.
Referenced by startRender(), and stopRender().
QList<FeatureDecoration> QgsInvertedPolygonRenderer::mFeatureDecorations private
Definition at line 164 of file qgsinvertedpolygonrenderer.h.
Referenced by renderFeature(), startRender(), and stopRender().
FeatureCategoryVector QgsInvertedPolygonRenderer::mFeaturesCategories private
where features are stored, based on the index of their symbol category
See also
mSymbolCategories
Definition at line 138 of file qgsinvertedpolygonrenderer.h.
Referenced by renderFeature(), startRender(), and stopRender().
QgsFields QgsInvertedPolygonRenderer::mFields private
fields of each feature
Definition at line 150 of file qgsinvertedpolygonrenderer.h.
Referenced by startRender(), and stopRender().
bool QgsInvertedPolygonRenderer::mPreprocessingEnabled private
whether to preprocess (merge) geometries before rendering
Definition at line 167 of file qgsinvertedpolygonrenderer.h.
Referenced by renderFeature(), and stopRender().
QScopedPointer<QgsFeatureRendererV2> QgsInvertedPolygonRenderer::mSubRenderer private
Embedded renderer.
Definition at line 128 of file qgsinvertedpolygonrenderer.h.
Referenced by capabilities(), clone(), dump(), embeddedRenderer(), legendSymbolItems(), legendSymbologyItems(), QgsInvertedPolygonRenderer(), renderFeature(), save(), setEmbeddedRenderer(), startRender(), stopRender(), symbolForFeature(), symbols(), symbolsForFeature(), usedAttributes(), and willRenderFeature().
QMap<QByteArray, int> QgsInvertedPolygonRenderer::mSymbolCategories private
maps a category to an index
Definition at line 141 of file qgsinvertedpolygonrenderer.h.
Referenced by renderFeature(), and startRender().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsinvertedpolygonrenderer.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsinvertedpolygonrenderer.cpp