QGIS API Documentation: QgsExpression::NodeColumnRef Class Reference
QgsExpression::NodeColumnRef Class Reference
#include <qgsexpression.h>
Public Member Functions
NodeColumnRef (QString name)
QString name () const
virtual NodeType nodeType () const
virtual bool prepare (QgsExpression *parent, const QgsFields &fields)
virtual QVariant eval (QgsExpression *parent, const QgsFeature *f)
virtual QString dump () const
virtual QStringList referencedColumns () const
virtual bool needsGeometry () const
virtual void accept (Visitor &v) const
Public Member Functions inherited from QgsExpression::Node
virtual ~Node ()
Protected Attributes
QString mName
int mIndex
Detailed Description
Definition at line 530 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::NodeColumnRef::NodeColumnRef (QString name) inline
Definition at line 533 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::NodeColumnRef::accept (Visitor & v) const inline virtual
Implements QgsExpression::Node.
Definition at line 545 of file qgsexpression.h.
References QgsExpression::Visitor::visit().
QString QgsExpression::NodeColumnRef::dump () const virtual
Implements QgsExpression::Node.
Definition at line 2487 of file qgsexpression.cpp.
References QgsExpression::quotedColumnRef().
QVariant QgsExpression::NodeColumnRef::eval (QgsExpression * parent, const QgsFeature * f) virtual
Implements QgsExpression::Node.
Definition at line 2460 of file qgsexpression.cpp.
References QgsFeature::attribute().
QString QgsExpression::NodeColumnRef::name () const inline
Definition at line 535 of file qgsexpression.h.
Referenced by QgsOgcUtils::expressionColumnRefToOgcFilter().
virtual bool QgsExpression::NodeColumnRef::needsGeometry () const inline virtual
Implements QgsExpression::Node.
Definition at line 543 of file qgsexpression.h.
virtual NodeType QgsExpression::NodeColumnRef::nodeType () const inline virtual
Implements QgsExpression::Node.
Definition at line 537 of file qgsexpression.h.
References QgsExpression::ntColumnRef.
bool QgsExpression::NodeColumnRef::prepare (QgsExpression * parent, const QgsFields & fields) virtual
Implements QgsExpression::Node.
Definition at line 2472 of file qgsexpression.cpp.
References QgsFields::count(), QgsExpression::mEvalErrorString, and tr.
virtual QStringList QgsExpression::NodeColumnRef::referencedColumns () const inline virtual
Implements QgsExpression::Node.
Definition at line 542 of file qgsexpression.h.
Member Data Documentation
int QgsExpression::NodeColumnRef::mIndex protected
Definition at line 549 of file qgsexpression.h.
QString QgsExpression::NodeColumnRef::mName protected
Definition at line 548 of file qgsexpression.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.cpp