QGIS API Documentation: QgsFeatureListViewDelegate Class Reference
QgsFeatureListViewDelegate Class Reference
#include <qgsfeaturelistviewdelegate.h>
Public Types
enum Element { EditElement, SelectionElement }
Signals
void editButtonClicked (QModelIndex &index)
Public Member Functions
QgsFeatureListViewDelegate (QgsFeatureListModel *listModel, QObject *parent=0)
void setEditSelectionModel (QItemSelectionModel *editSelectionModel)
Element positionToElement (const QPoint &pos)
void setFeatureSelectionModel (QgsFeatureSelectionModel *featureSelectionModel)
void setCurrentFeatureEdited (bool state)
Static Public Attributes
static int const sIconSize = 24
Protected Member Functions
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Private Attributes
QgsFeatureSelectionModel * mFeatureSelectionModel
QItemSelectionModel * mEditSelectionModel
QgsFeatureListModel * mListModel
bool mCurrentFeatureEdited
Set to true if the current edit selection has been edited.
Detailed Description
Definition at line 14 of file qgsfeaturelistviewdelegate.h.
Member Enumeration Documentation
enum QgsFeatureListViewDelegate::Element
Enumerator
EditElement
SelectionElement
Definition at line 21 of file qgsfeaturelistviewdelegate.h.
Constructor & Destructor Documentation
QgsFeatureListViewDelegate::QgsFeatureListViewDelegate (QgsFeatureListModel * listModel, QObject * parent = 0) explicit
Definition at line 16 of file qgsfeaturelistviewdelegate.cpp.
Member Function Documentation
void QgsFeatureListViewDelegate::editButtonClicked (QModelIndex & index) signal
void QgsFeatureListViewDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected virtual
Definition at line 57 of file qgsfeaturelistviewdelegate.cpp.
References QgsApplication::getThemePixmap(), icon(), QgsFeatureListModel::FeatureInfo::isEdited, QgsFeatureListModel::FeatureInfo::isNew, QgsFeatureSelectionModel::isSelected(), QgsFeatureListModel::mapToMaster(), mCurrentFeatureEdited, mEditSelectionModel, mFeatureSelectionModel, and mListModel.
QgsFeatureListViewDelegate::Element QgsFeatureListViewDelegate::positionToElement (const QPoint & pos)
Definition at line 24 of file qgsfeaturelistviewdelegate.cpp.
References EditElement, SelectionElement, and sIconSize.
Referenced by QgsFeatureListView::mousePressEvent().
void QgsFeatureListViewDelegate::setCurrentFeatureEdited (bool state)
Definition at line 41 of file qgsfeaturelistviewdelegate.cpp.
References mCurrentFeatureEdited.
Referenced by QgsFeatureListView::setCurrentFeatureEdited().
void QgsFeatureListViewDelegate::setEditSelectionModel (QItemSelectionModel * editSelectionModel)
Definition at line 46 of file qgsfeaturelistviewdelegate.cpp.
References mEditSelectionModel.
Referenced by QgsFeatureListView::setModel().
void QgsFeatureListViewDelegate::setFeatureSelectionModel (QgsFeatureSelectionModel * featureSelectionModel)
Definition at line 36 of file qgsfeaturelistviewdelegate.cpp.
References mFeatureSelectionModel.
Referenced by QgsFeatureListView::setModel().
QSize QgsFeatureListViewDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const protected virtual
Definition at line 51 of file qgsfeaturelistviewdelegate.cpp.
References sIconSize.
Member Data Documentation
bool QgsFeatureListViewDelegate::mCurrentFeatureEdited private
Set to true if the current edit selection has been edited.
Definition at line 49 of file qgsfeaturelistviewdelegate.h.
Referenced by paint(), and setCurrentFeatureEdited().
QItemSelectionModel* QgsFeatureListViewDelegate::mEditSelectionModel private
Definition at line 46 of file qgsfeaturelistviewdelegate.h.
Referenced by paint(), and setEditSelectionModel().
QgsFeatureSelectionModel* QgsFeatureListViewDelegate::mFeatureSelectionModel private
Definition at line 45 of file qgsfeaturelistviewdelegate.h.
Referenced by paint(), and setFeatureSelectionModel().
QgsFeatureListModel* QgsFeatureListViewDelegate::mListModel private
Definition at line 47 of file qgsfeaturelistviewdelegate.h.
Referenced by paint().
int const QgsFeatureListViewDelegate::sIconSize = 24 static
Definition at line 19 of file qgsfeaturelistviewdelegate.h.
Referenced by positionToElement(), and sizeHint().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsfeaturelistviewdelegate.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsfeaturelistviewdelegate.cpp