QGIS API Documentation: QgsLabelingResults Class Reference
QgsLabelingResults Class Reference
Class that stores computed placement from labeling engine.
#include <qgspallabeling.h>
Public Member Functions
QgsLabelingResults ()
~QgsLabelingResults ()
QList< QgsLabelPosition > labelsAtPosition (const QgsPoint &p) const
return infos about labels at a given (map) position
QList< QgsLabelPosition > labelsWithinRect (const QgsRectangle &r) const
return infos about labels within a given (map) rectangle
Private Member Functions
QgsLabelingResults (const QgsLabelingResults &)
Private Attributes
QgsLabelSearchTree * mLabelSearchTree
Friends
class QgsPalLabeling
Detailed Description
Class that stores computed placement from labeling engine.
Note
added in 2.4
Definition at line 685 of file qgspallabeling.h.
Constructor & Destructor Documentation
QgsLabelingResults::QgsLabelingResults ()
Definition at line 5081 of file qgspallabeling.cpp.
References mLabelSearchTree.
QgsLabelingResults::~QgsLabelingResults ()
Definition at line 5086 of file qgspallabeling.cpp.
References mLabelSearchTree.
QgsLabelingResults::QgsLabelingResults (const QgsLabelingResults &) inline private
Definition at line 697 of file qgspallabeling.h.
Member Function Documentation
QList< QgsLabelPosition > QgsLabelingResults::labelsAtPosition (const QgsPoint & p) const
return infos about labels at a given (map) position
Definition at line 5092 of file qgspallabeling.cpp.
References QgsLabelSearchTree::label(), and mLabelSearchTree.
Referenced by QgsPalLabeling::labelsAtPosition().
QList< QgsLabelPosition > QgsLabelingResults::labelsWithinRect (const QgsRectangle & r) const
return infos about labels within a given (map) rectangle
Definition at line 5110 of file qgspallabeling.cpp.
References QgsLabelSearchTree::labelsInRect(), and mLabelSearchTree.
Referenced by QgsPalLabeling::labelsWithinRect().
Friends And Related Function Documentation
friend class QgsPalLabeling friend
Definition at line 701 of file qgspallabeling.h.
Member Data Documentation
QgsLabelSearchTree* QgsLabelingResults::mLabelSearchTree private
Definition at line 699 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabeling(), labelsAtPosition(), labelsWithinRect(), QgsLabelingResults(), and ~QgsLabelingResults().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgspallabeling.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgspallabeling.cpp