QGIS API Documentation: QgsCoordinateReferenceSystem Class Reference
QgsCoordinateReferenceSystem Class Reference
QGIS core library
Class for storing a coordinate reference system (CRS)
#include <qgscoordinatereferencesystem.h>
Public Types
enum CrsType { InternalCrsId, PostgisCrsId, EpsgCrsId }
Public Member Functions
QgsCoordinateReferenceSystem ()
Default constructor.
~QgsCoordinateReferenceSystem ()
QgsCoordinateReferenceSystem (QString theDefinition)
QgsCoordinateReferenceSystem (const long theId, CrsType theType=PostgisCrsId)
QgsCoordinateReferenceSystem (const QgsCoordinateReferenceSystem &srs)
copy constructor
QgsCoordinateReferenceSystem & operator= (const QgsCoordinateReferenceSystem &srs)
Assignment operator.
bool createFromId (const long theId, CrsType theType=PostgisCrsId)
bool createFromOgcWmsCrs (QString theCrs)
Set up this CRS from the given OGC CRS.
bool createFromSrid (const long theSrid)
bool createFromWkt (const QString &theWkt)
bool createFromSrsId (const long theSrsId)
bool createFromProj4 (const QString &theProjString)
bool createFromString (const QString &theDefinition)
bool createFromUserInput (const QString &theDefinition)
bool isValid () const
void validate ()
long findMatchingProj ()
bool operator== (const QgsCoordinateReferenceSystem &theSrs) const
bool operator!= (const QgsCoordinateReferenceSystem &theSrs) const
bool readXML (QDomNode &theNode)
bool writeXML (QDomNode &theNode, QDomDocument &theDoc) const
long srsid () const
long postgisSrid () const
QString authid () const
QString description () const
QString projectionAcronym () const
QString ellipsoidAcronym () const
QString toWkt () const
QString toProj4 () const
Get the Proj Proj4 string representation of this srs.
bool geographicFlag () const
bool axisInverted () const
QGis::UnitType mapUnits () const
void setValidationHint (QString html)
QString validationHint ()
bool saveAsUserCRS (QString name)
Copied from QgsCustomProjectionDialog /// Please refactor into SQL handler !!! ///.
QString geographicCRSAuthId () const
Returns auth id of related geographic CRS.
Static Public Member Functions
static void setupESRIWktFix ()
static void setCustomSrsValidation (CUSTOM_CRS_VALIDATION f)
Sets custom function to force valid CRS QGIS uses implementation in QgisGui::customSrsValidation.
static CUSTOM_CRS_VALIDATION customSrsValidation ()
Gets custom function.
static int syncDb ()
Private Types
typedef QMap< QString, QString > RecordMap
Private Member Functions
void setInternalId (long theSrsId)
void setSrid (long theSrid)
void setDescription (QString theDescription)
void setProj4String (QString theProj4String)
void setGeographicFlag (bool theGeoFlag)
void setEpsg (long theEpsg)
void setAuthId (QString theID)
void setProjectionAcronym (QString theProjectionAcronym)
void setEllipsoidAcronym (QString theEllipsoidAcronym)
void debugPrint ()
RecordMap getRecord (QString theSql)
void setMapUnits ()
Work out the projection units and set the appropriate local variable.
long getRecordCount ()
Helper for getting number of user CRS already in db.
bool loadFromDb (QString db, QString expression, QString value)
Static Private Member Functions
static QString proj4FromSrsId (const int theSrsId)
A static helper function to find out the proj4 string for a srsid.
static int openDb (QString path, sqlite3 **db, bool readonly=true)
static QString quotedValue (QString value)
Helper for sql-safe value quoting.
static bool loadIDs (QHash< int, QString > &wkts)
static bool loadWkts (QHash< int, QString > &wkts, const char *filename)
static bool syncDatumTransform (const QString &dbPath)
Private Attributes
long mSrsId
The internal sqlite3 srs.db primary key for this srs.
QString mDescription
A textual description of the srs.
QString mProjectionAcronym
The official proj4 acronym for the projection family.
QString mEllipsoidAcronym
The official proj4 acronym for the ellipoid.
bool mGeoFlag
Whether this is a geographic or projected coordinate system.
QGis::UnitType mMapUnits
The map units.
long mSRID
If available, the Postgis spatial_ref_sys identifier for this srs (defaults to 0)
QString mAuthId
If available the authority identifier for this srs.
bool mIsValidFlag
Whether this srs is properly defined and valid.
OGRSpatialReferenceH mCRS
QString mValidationHint
QString mWkt
QString mProj4
int mAxisInverted
Whether this is a coordinate system has inverted axis.
Static Private Attributes
static CUSTOM_CRS_VALIDATION mCustomSrsValidation = NULL
Detailed Description
Class for storing a coordinate reference system (CRS)
Definition at line 50 of file qgscoordinatereferencesystem.h.
Member Typedef Documentation
typedef QMap<QString, QString> QgsCoordinateReferenceSystem::RecordMap private
A string based associative array used for passing records around
Definition at line 421 of file qgscoordinatereferencesystem.h.
Member Enumeration Documentation
enum QgsCoordinateReferenceSystem::CrsType
Enumerator
InternalCrsId
PostgisCrsId
EpsgCrsId
Definition at line 54 of file qgscoordinatereferencesystem.h.
Constructor & Destructor Documentation
QgsCoordinateReferenceSystem::QgsCoordinateReferenceSystem ()
Default constructor.
Definition at line 51 of file qgscoordinatereferencesystem.cpp.
References mCRS.
QgsCoordinateReferenceSystem::~QgsCoordinateReferenceSystem ()
Definition at line 90 of file qgscoordinatereferencesystem.cpp.
References mCRS.
QgsCoordinateReferenceSystem::QgsCoordinateReferenceSystem (QString theDefinition) explicit
Constructs a CRS object from a string definition as defined in the createFromString member function (by default a WKT definition).
Parameters
theDefinition A String containing a coordinate reference system definition.
Definition at line 63 of file qgscoordinatereferencesystem.cpp.
References createFromString(), and mCRS.
QgsCoordinateReferenceSystem::QgsCoordinateReferenceSystem (const long theId, CrsType theType = PostgisCrsId)
Use this constructor when you want to create a CRS object using a postgis SRID, an EpsgCrsId id or a QGIS CRS_ID.
Note
We encourage you to use EpsgCrsId, Wkt or Proj4 to describe CRS's in your code wherever possible. QGSI CRS_IDs are not guaranteed to be permanent / involatile.
Parameters
theId The ID no valid for the chosen coordinate system id type
theType One of the types described in QgsCoordinateReferenceSystem::CrsType
Definition at line 77 of file qgscoordinatereferencesystem.cpp.
References createFromId(), and mCRS.
QgsCoordinateReferenceSystem::QgsCoordinateReferenceSystem (const QgsCoordinateReferenceSystem & srs)
copy constructor
Definition at line 257 of file qgscoordinatereferencesystem.cpp.
References mCRS.
Member Function Documentation
QString QgsCoordinateReferenceSystem::authid () const
Get the authority identifier for this srs
Returns
QString the Authority identifier for this srs
Note
added in 1.5
Definition at line 833 of file qgscoordinatereferencesystem.cpp.
References mAuthId.
Referenced by QgsCoordinateTransform::addNullGridShifts(), QgsRasterProjector::block(), QgsRasterProjector::calc(), QgsOfflineEditing::copyVectorLayer(), createFromWkt(), QgsMapCanvas::getDatumTransformInfo(), QgsCoordinateTransform::initialise(), QgsNewVectorLayerDialog::on_pbnChangeSpatialRefSys_clicked(), operator==(), QgsMapRenderer::outputExtentToLayerExtent(), QgsRasterCalculator::processCalculation(), QgsNewVectorLayerDialog::QgsNewVectorLayerDialog(), QgsOWSSourceSelect::QgsOWSSourceSelect(), saveAsUserCRS(), QgsDatumTransformStore::transformation(), QgsMapRenderer::transformation(), QgsRasterLayerSaveAsDialog::updateCrsGroup(), QgsMapCanvas::updateDatumTransformEntries(), and writeXML().
bool QgsCoordinateReferenceSystem::axisInverted () const
return if axis is inverted (eg. for WMS 1.3)
Returns
bool Whether this is crs axis is inverted
Note
added in 1.8
Definition at line 404 of file qgscoordinatereferencesystem.cpp.
References mAuthId, mAxisInverted, and mCRS.
bool QgsCoordinateReferenceSystem::createFromId (const long theId, CrsType theType = PostgisCrsId)
Definition at line 95 of file qgscoordinatereferencesystem.cpp.
References createFromOgcWmsCrs(), createFromSrid(), createFromSrsId(), EpsgCrsId, InternalCrsId, PostgisCrsId, and QgsDebugMsg.
Referenced by createFromString(), QgsRasterLayerSaveAsDialog::on_mChangeCrsPushButton_clicked(), QgsCoordinateReferenceSystem(), QgsCoordinateTransform::QgsCoordinateTransform(), and readXML().
bool QgsCoordinateReferenceSystem::createFromOgcWmsCrs (QString theCrs)
Set up this CRS from the given OGC CRS.
Sets this CRS to the given OGC WMS-format Coordinate Reference Systems.
Return values
false if not given an valid label
Definition at line 210 of file qgscoordinatereferencesystem.cpp.
References createFromSrsId(), loadFromDb(), mAxisInverted, mIsValidFlag, and QgsApplication::srsDbFilePath().
Referenced by createFromId(), createFromWkt(), QgsGml::crs(), QgsCRSCache::crsByAuthId(), QgsCoordinateTransform::datumTransformCrsInfo(), QgsOWSSourceSelect::descriptionForAuthId(), QgsOWSSourceSelect::on_mChangeCRSButton_clicked(), QgsNewVectorLayerDialog::on_pbnChangeSpatialRefSys_clicked(), QgsNewVectorLayerDialog::QgsNewVectorLayerDialog(), QgsProjectionSelector::QgsProjectionSelector(), QgsRasterLayerSaveAsDialog::QgsRasterLayerSaveAsDialog(), QgsDistanceArea::setSourceAuthId(), and QgsCRSCache::updateCRSCache().
bool QgsCoordinateReferenceSystem::createFromProj4 (const QString & theProjString)
Set up this srs by passing it a proj4 style formatted string. The string will be parsed and the projection and ellipsoid members set and the remainder of the proj4 string will be stored in the parameters member. The reason for this is so that we can easily present the user with 'natural language' representation of the projection and ellipsoid by looking them up in the srs.bs sqlite database. Also having the ellipse and proj elements stripped out is helpful to speed up globbing queries (see below).
We try to match the proj string to and srsid using the following logic:
perform a whole text search on srs name (if not null). The srs name will have been set if this method has been delegated to from createFromWkt.
if the above does not match perform a whole text search on proj4 string (if not null)
if none of the above match convert the proj4 string to an OGR CRS then check if its a geocs or a proj cs (using ogr isGeographic) then sequentially walk through the database (first users qgis.db srs tbl then system srs.db tbl), converting each entry into an ogr srs and using isSame or isSameGeocs (essentially calling the == overloaded operator). We'll try to be smart about this and first parse out the proj and ellpse strings and only check for a match in entities that have the same ellps and proj entries so that it doesn't munch yer cpu so much.
Parameters
theProjString A proj4 format string
Returns
bool TRUE if success else false
Definition at line 511 of file qgscoordinatereferencesystem.cpp.
References createFromSrsId(), findMatchingProj(), getRecord(), LAT_PREFIX_LEN, mEllipsoidAcronym, mIsValidFlag, mProjectionAcronym, mWkt, QgsDebugMsg, quotedValue(), and setProj4String().
Referenced by createFromString(), createFromWkt(), QgsProjectionSelector::QgsProjectionSelector(), readXML(), and QgsDistanceArea::setEllipsoid().
bool QgsCoordinateReferenceSystem::createFromSrid (const long theSrid)
Set up this srs by fetching the appropriate information from the sqlite backend. First the system level read only srs.db will be checked and then the users ~/.qgis/qgis.db database will be checked for a match.
Note
Any members will be overwritten during this process.
Parameters
theSrid The postgis SRID for the desired spatial reference system.
Definition at line 308 of file qgscoordinatereferencesystem.cpp.
References loadFromDb(), and QgsApplication::srsDbFilePath().
Referenced by createFromId().
bool QgsCoordinateReferenceSystem::createFromSrsId (const long theSrsId)
Set up this srs by fetching the appropriate information from the sqlite backend. If the srsid is < 100000, only the system srs.db will be checked. If the srsid > 100000 the srs will be retrieved from the ~/.qgis/qgis.db
Note
Any members will be overwritten during this process.
Parameters
theSrsId The QGIS SrsId for the desired spatial reference system.
Returns
bool TRUE if success else false
Definition at line 313 of file qgscoordinatereferencesystem.cpp.
References loadFromDb(), QgsApplication::qgisUserDbFilePath(), QgsApplication::srsDbFilePath(), and USER_CRS_START_ID.
Referenced by createFromId(), createFromOgcWmsCrs(), createFromProj4(), QgsCoordinateTransform::setDestCRSID(), and QgsDistanceArea::setSourceCrs().
bool QgsCoordinateReferenceSystem::createFromString (const QString & theDefinition)
Set up this srs from a string definition, by default a WKT definition. Otherwise the string defines a authority, followed by a colon, followed by the definition. The authority can be one of "epsg", "postgis", "internal" for integer definitions, and "wkt" or "proj4" for string definitions. The implementation of each authority uses the corresponding createFrom... function.
Parameters
theDefinition A String containing a coordinate reference system definition.
Definition at line 116 of file qgscoordinatereferencesystem.cpp.
References createFromId(), createFromProj4(), createFromWkt(), EpsgCrsId, InternalCrsId, PostgisCrsId, saveAsUserCRS(), srsid(), toProj4(), and tr.
Referenced by QgsCoordinateReferenceSystem(), and QgsDatumTransformDialog::updateTitle().
bool QgsCoordinateReferenceSystem::createFromUserInput (const QString & theDefinition)
Set up this srs from a various text formats.
Valid formats: WKT string, "EPSG:n", "EPSGA:n", "AUTO:proj_id,unit_id,lon0,lat0", "urn:ogc:def:crs:EPSG::n", PROJ.4 string, filename (with WKT, XML or PROJ.4 string), well known name (such as NAD27, NAD83, WGS84 or WGS72), ESRI::[WKT string] (directly or in a file), "IGNF:xxx"
For more details on supported formats see OGRSpatialReference::SetFromUserInput() (http://www.gdal.org/ogr/classOGRSpatialReference.html#aec3c6a49533fe457ddc763d699ff8796)
Note
this function generates a WKT string using OSRSetFromUserInput() and passes it to createFromWkt() function.
Parameters
theDefinition A String containing a coordinate reference system definition.
Note
added in 1.8
Definition at line 160 of file qgscoordinatereferencesystem.cpp.
References createFromWkt(), and setupESRIWktFix().
bool QgsCoordinateReferenceSystem::createFromWkt (const QString & theWkt)
Set up this srs using a Wkt spatial ref sys definition. The wkt will be converted to a proj4 string using OGR helper functions. After this the srs databasses will be searched for matches. First the system level read only srs.db will be checked and then the users ~/.qgis/qgis.db database will be checked for a match.
Note
Any members will be overwritten during this process.
SRID and EpsgCrsId may be blank if no match can be found on srs db.
Parameters
theWkt The Wkt for the desired spatial reference system.
Returns
bool TRUE if success else false
Definition at line 430 of file qgscoordinatereferencesystem.cpp.
References authid(), createFromOgcWmsCrs(), createFromProj4(), mCRS, mIsValidFlag, mProj4, mSrsId, mWkt, QgsDebugMsg, saveAsUserCRS(), toProj4(), and tr.
Referenced by createFromString(), createFromUserInput(), and QgsCoordinateTransform::QgsCoordinateTransform().
CUSTOM_CRS_VALIDATION QgsCoordinateReferenceSystem::customSrsValidation () static
Gets custom function.
Note
not available in python bindings
Definition at line 1421 of file qgscoordinatereferencesystem.cpp.
References mCustomSrsValidation.
Referenced by QgsMapLayer::readLayerXML().
void QgsCoordinateReferenceSystem::debugPrint () private
Print the description if debugging
Definition at line 1426 of file qgscoordinatereferencesystem.cpp.
References QGis::Degrees, QGis::Feet, mapUnits(), mDescription, QGis::Meters, mIsValidFlag, mSrsId, QgsDebugMsg, toProj4(), and toWkt().
Referenced by setProj4String().
QString QgsCoordinateReferenceSystem::description () const
Get the Description
Returns
QString the Description A textual description of the srs.
Note
A zero length string will be returned if the description is uninitialised
Definition at line 838 of file qgscoordinatereferencesystem.cpp.
References mDescription.
Referenced by QgsCoordinateTransform::datumTransformCrsInfo(), QgsOWSSourceSelect::descriptionForAuthId(), QgsNewVectorLayerDialog::on_pbnChangeSpatialRefSys_clicked(), operator<<(), QgsNewVectorLayerDialog::QgsNewVectorLayerDialog(), QgsRasterLayerSaveAsDialog::updateCrsGroup(), QgsDatumTransformDialog::updateTitle(), and writeXML().
QString QgsCoordinateReferenceSystem::ellipsoidAcronym () const
Get the Ellipsoid Acronym
Returns
QString theEllipsoidAcronym The official proj4 acronym for the ellipoid
Note
A zero length string will be returned if the ellipsoidAcronym is uninitialised
Definition at line 862 of file qgscoordinatereferencesystem.cpp.
References mEllipsoidAcronym.
Referenced by operator<<(), saveAsUserCRS(), and writeXML().
long QgsCoordinateReferenceSystem::findMatchingProj ()
This is a globbing function to try to find a record in the database that matches a CRS defined only by a proj4string. The goal is to learn what the tbl_srs.srs_id value is for the CRS. Internally the source CRS is converted to an OGR srs object using the proj4string call and then every record in the database that matches projection and ellipsoid will be converted to an OGR srs in turn and compared to the source CRS. There are some gotchas with using ogr isSame() srs comparison, but its more effective than using straight string comparison of proj4params.
Note
The ellipsoid and projection acronyms must be set as well as the proj4string!
Returns
long the SrsId of the matched CRS
Definition at line 1028 of file qgscoordinatereferencesystem.cpp.
References mEllipsoidAcronym, mIsValidFlag, mProjectionAcronym, openDb(), QgsApplication::qgisUserDbFilePath(), QgsDebugMsg, quotedValue(), QgsApplication::srsDbFilePath(), and toProj4().
Referenced by createFromProj4().
QString QgsCoordinateReferenceSystem::geographicCRSAuthId () const
Returns auth id of related geographic CRS.
Definition at line 2155 of file qgscoordinatereferencesystem.cpp.
References geographicFlag(), mAuthId, and mCRS.
Referenced by QgsCoordinateTransform::datumTransformations().
bool QgsCoordinateReferenceSystem::geographicFlag () const
Get this Geographic? flag
Returns
bool theGeoFlag Whether this is a geographic or projected coordinate system
Definition at line 891 of file qgscoordinatereferencesystem.cpp.
References mGeoFlag.
Referenced by QgsMapRendererJob::drawOldLabeling(), geographicCRSAuthId(), QgsMapRendererJob::prepareJobs(), QgsVectorLayerRenderer::render(), QgsMapRendererJob::reprojectToLayerExtent(), QgsVectorLayerEditUtils::splitFeatures(), QgsMapRenderer::splitLayersExtent(), QgsVectorLayerEditUtils::splitParts(), and writeXML().
QgsCoordinateReferenceSystem::RecordMap QgsCoordinateReferenceSystem::getRecord (QString theSql) private
Get a record from the srs.db or qgis.db backends, given an sql statment.
Note
only handles queries that return a single record.
it will first try the system srs.db then the users qgis.db!
Parameters
theSql The sql query to execute
Returns
An associative array of field name <-> value pairs
Definition at line 708 of file qgscoordinatereferencesystem.cpp.
References openDb(), QgsApplication::qgisUserDbFilePath(), QgsDebugMsg, QgsDebugMsgLevel, and QgsApplication::srsDbFilePath().
Referenced by createFromProj4().
long QgsCoordinateReferenceSystem::getRecordCount () private
Helper for getting number of user CRS already in db.
Definition at line 1543 of file qgscoordinatereferencesystem.cpp.
References QgsApplication::qgisUserDbFilePath(), and QgsDebugMsg.
Referenced by saveAsUserCRS().
bool QgsCoordinateReferenceSystem::isValid () const
Find out whether this CRS is correctly initialised and usable
Definition at line 506 of file qgscoordinatereferencesystem.cpp.
References mIsValidFlag.
Referenced by QgsRasterProjector::block(), QgsVectorLayerImport::importLayer(), QgsCoordinateTransform::initialise(), QgsOWSSourceSelect::QgsOWSSourceSelect(), QgsProjectionSelector::QgsProjectionSelector(), readXML(), QgsMapLayer::setCrs(), QgsCoordinateTransform::transformCoords(), and QgsDatumTransformDialog::updateTitle().
bool QgsCoordinateReferenceSystem::loadFromDb (QString db, QString expression, QString value) private
Definition at line 320 of file qgscoordinatereferencesystem.cpp.
References mAuthId, mAxisInverted, mCRS, mDescription, mEllipsoidAcronym, mGeoFlag, mIsValidFlag, mProj4, mProjectionAcronym, mSRID, mSrsId, mWkt, openDb(), QgsDebugMsg, QgsDebugMsgLevel, quotedValue(), setMapUnits(), setProj4String(), and USER_CRS_START_ID.
Referenced by createFromOgcWmsCrs(), createFromSrid(), and createFromSrsId().
bool QgsCoordinateReferenceSystem::loadIDs (QHash< int, QString > & wkts) static private
Definition at line 1630 of file qgscoordinatereferencesystem.cpp.
Referenced by syncDb().
bool QgsCoordinateReferenceSystem::loadWkts (QHash< int, QString > & wkts, const char * filename) static private
Definition at line 1582 of file qgscoordinatereferencesystem.cpp.
Referenced by syncDb().
QGis::UnitType QgsCoordinateReferenceSystem::mapUnits () const
Get the units that the projection is in
Returns
QGis::UnitType that gives the units for the coordinate system
Definition at line 896 of file qgscoordinatereferencesystem.cpp.
References mMapUnits.
Referenced by QgsVectorLayerEditUtils::addTopologicalPoints(), QgsDistanceArea::convertMeasurement(), QgsTransectSample::createSample(), QgsVectorFileWriter::createSymbolLayerTable(), debugPrint(), QgsVectorFileWriter::exportFeaturesSymbolLevels(), and QgsVectorFileWriter::writeAsVectorFormat().
int QgsCoordinateReferenceSystem::openDb (QString path, sqlite3 ** db, bool readonly = true) static private
Definition at line 1395 of file qgscoordinatereferencesystem.cpp.
References QgsMessageLog::logMessage(), QgsDebugMsg, QgsDebugMsgLevel, and tr.
Referenced by findMatchingProj(), getRecord(), loadFromDb(), and proj4FromSrsId().
bool QgsCoordinateReferenceSystem::operator!= (const QgsCoordinateReferenceSystem & theSrs) const
Overloaded != operator used to compare to CRS's. Returns opposite bool value to operator ==
Definition at line 1137 of file qgscoordinatereferencesystem.cpp.
QgsCoordinateReferenceSystem & QgsCoordinateReferenceSystem::operator= (const QgsCoordinateReferenceSystem & srs)
Assignment operator.
Definition at line 264 of file qgscoordinatereferencesystem.cpp.
References mAuthId, mAxisInverted, mCRS, mDescription, mEllipsoidAcronym, mGeoFlag, mIsValidFlag, mMapUnits, mProj4, mProjectionAcronym, mSRID, mSrsId, mValidationHint, and mWkt.
Referenced by readXML().
bool QgsCoordinateReferenceSystem::operator== (const QgsCoordinateReferenceSystem & theSrs) const
Overloaded == operator used to compare to CRS's. Internally it will delegate to the equals method described below
Definition at line 1131 of file qgscoordinatereferencesystem.cpp.
References authid(), and mIsValidFlag.
long QgsCoordinateReferenceSystem::postgisSrid () const
Get the postgis srid for this srs
Returns
long theSRID the Postgis spatial_ref_sys identifier for this srs (defaults to 0)
Definition at line 828 of file qgscoordinatereferencesystem.cpp.
References mSRID.
Referenced by writeXML().
QString QgsCoordinateReferenceSystem::proj4FromSrsId (const int theSrsId) static private
A static helper function to find out the proj4 string for a srsid.
Parameters
theSrsId The srsid used for the lookup
Returns
QString The proj4 string
Definition at line 1333 of file qgscoordinatereferencesystem.cpp.
References openDb(), QgsApplication::qgisUserDbFilePath(), QgsDebugMsg, QgsApplication::srsDbFilePath(), and USER_CRS_START_ID.
QString QgsCoordinateReferenceSystem::projectionAcronym () const
Get the Projection Acronym
Returns
QString theProjectionAcronym The official proj4 acronym for the projection family
Note
A zero length string will be returned if the projectionAcronym is uninitialised
Definition at line 850 of file qgscoordinatereferencesystem.cpp.
References mProjectionAcronym.
Referenced by operator<<(), saveAsUserCRS(), and writeXML().
QString QgsCoordinateReferenceSystem::quotedValue (QString value) static private
Helper for sql-safe value quoting.
Definition at line 1575 of file qgscoordinatereferencesystem.cpp.
Referenced by createFromProj4(), findMatchingProj(), loadFromDb(), saveAsUserCRS(), syncDatumTransform(), and syncDb().
bool QgsCoordinateReferenceSystem::readXML (QDomNode & theNode)
Restores state from the given Dom node.
Parameters
theNode The node from which state will be restored
Returns
bool True on success, False on failure
Definition at line 1156 of file qgscoordinatereferencesystem.cpp.
References createFromId(), createFromProj4(), GEOCRS_ID, QgsCRSCache::instance(), InternalCrsId, isValid(), mIsValidFlag, mSrsId, operator=(), QgsDebugMsg, saveAsUserCRS(), setAuthId(), setDescription(), setEllipsoidAcronym(), setGeographicFlag(), setInternalId(), setMapUnits(), setProj4String(), setProjectionAcronym(), setSrid(), srsid(), toProj4(), tr, and USER_CRS_START_ID.
Referenced by QgsMapLayer::readLayerXML(), QgsMapSettings::readXML(), and QgsCoordinateTransform::readXML().
bool QgsCoordinateReferenceSystem::saveAsUserCRS (QString name)
Copied from QgsCustomProjectionDialog /// Please refactor into SQL handler !!! ///.
Save the proj4-string as a custom CRS
Returns
bool true if success else false
Definition at line 1461 of file qgscoordinatereferencesystem.cpp.
References authid(), ellipsoidAcronym(), getRecordCount(), QgsMessageLog::logMessage(), mIsValidFlag, mProj4, projectionAcronym(), QgsApplication::qgisUserDbFilePath(), QgsDebugMsg, quotedValue(), setInternalId(), toProj4(), tr, and USER_CRS_START_ID.
Referenced by createFromString(), createFromWkt(), readXML(), and QgsDistanceArea::setEllipsoid().
void QgsCoordinateReferenceSystem::setAuthId (QString theID) private
Set the authority identifier for this srs
Parameters
theID the authority identifier for this srs (defaults to 0)
Definition at line 909 of file qgscoordinatereferencesystem.cpp.
References mAuthId.
Referenced by readXML().
void QgsCoordinateReferenceSystem::setCustomSrsValidation (CUSTOM_CRS_VALIDATION f) static
Sets custom function to force valid CRS QGIS uses implementation in QgisGui::customSrsValidation.
Note
not available in python bindings
Definition at line 1416 of file qgscoordinatereferencesystem.cpp.
References mCustomSrsValidation.
Referenced by QgsMapLayer::readLayerXML().
void QgsCoordinateReferenceSystem::setDescription (QString theDescription) private
Set the Description
Parameters
theDescription A textual description of the srs.
Definition at line 917 of file qgscoordinatereferencesystem.cpp.
References mDescription.
Referenced by readXML().
void QgsCoordinateReferenceSystem::setEllipsoidAcronym (QString theEllipsoidAcronym) private
Set the ellipsoid acronym
Parameters
theEllipsoidAcronym the acronym (must be a valid proj4 ellipsoid acronym)
Definition at line 957 of file qgscoordinatereferencesystem.cpp.
References mEllipsoidAcronym.
Referenced by readXML().
void QgsCoordinateReferenceSystem::setEpsg (long theEpsg) private
Set the EpsgCrsId identifier for this srs
Parameters
theEpsg the ESPG identifier for this srs (defaults to 0)
Definition at line 949 of file qgscoordinatereferencesystem.cpp.
References mAuthId.
void QgsCoordinateReferenceSystem::setGeographicFlag (bool theGeoFlag) private
Set this Geographic? flag
Parameters
theGeoFlag Whether this is a geographic or projected coordinate system
Definition at line 945 of file qgscoordinatereferencesystem.cpp.
References mGeoFlag.
Referenced by readXML().
void QgsCoordinateReferenceSystem::setInternalId (long theSrsId) private
Set the QGIS SrsId
Parameters
theSrsId The internal sqlite3 srs.db primary key for this srs
Definition at line 905 of file qgscoordinatereferencesystem.cpp.
References mSrsId.
Referenced by readXML(), and saveAsUserCRS().
void QgsCoordinateReferenceSystem::setMapUnits () private
Work out the projection units and set the appropriate local variable.
Definition at line 962 of file qgscoordinatereferencesystem.cpp.
References QGis::Degrees, QGis::Feet, mCRS, QGis::Meters, mIsValidFlag, mMapUnits, QgsDebugMsg, QgsDebugMsgLevel, qgsDoubleNear(), and QGis::UnknownUnit.
Referenced by loadFromDb(), readXML(), and setProj4String().
void QgsCoordinateReferenceSystem::setProj4String (QString theProj4String) private
Definition at line 921 of file qgscoordinatereferencesystem.cpp.
References debugPrint(), mCRS, mIsValidFlag, mProj4, mWkt, and setMapUnits().
Referenced by createFromProj4(), loadFromDb(), and readXML().
void QgsCoordinateReferenceSystem::setProjectionAcronym (QString theProjectionAcronym) private
Set the projection acronym
Parameters
theProjectionAcronym the acronym (must be a valid proj4 projection acronym)
Definition at line 953 of file qgscoordinatereferencesystem.cpp.
References mProjectionAcronym.
Referenced by readXML().
void QgsCoordinateReferenceSystem::setSrid (long theSrid) private
Set the postgis srid
Parameters
theSrid The postgis spatial_ref_sys key for this srs
Definition at line 913 of file qgscoordinatereferencesystem.cpp.
References mSRID.
Referenced by readXML().
void QgsCoordinateReferenceSystem::setupESRIWktFix () static
Make sure that ESRI WKT import is done properly. This is required for proper shapefile CRS import when using gdal>= 1.9.
Note
This function is called by createFromUserInput() and QgsOgrProvider::crs(), there is usually no need to call it from elsewhere.
This function sets CPL config option GDAL_FIX_ESRI_WKT to a proper value, unless it has been set by the user through the commandline or an environment variable. For more details refer to OGRSpatialReference::morphFromESRI() .
added in 1.8
Definition at line 187 of file qgscoordinatereferencesystem.cpp.
References QgsDebugMsg, and QgsLogger::warning().
Referenced by createFromUserInput().
void QgsCoordinateReferenceSystem::setValidationHint (QString html)
Set user hint for validation
Definition at line 1448 of file qgscoordinatereferencesystem.cpp.
References mValidationHint.
Referenced by QgsMapLayer::readLayerXML(), and QgsMapLayer::setCrs().
long QgsCoordinateReferenceSystem::srsid () const
Get the SrsId - if possible
Returns
long theSrsId The internal sqlite3 srs.db primary key for this srs
Definition at line 823 of file qgscoordinatereferencesystem.cpp.
References mSrsId.
Referenced by createFromString(), QgsTransectSample::createSample(), QgsMapRenderer::destinationCrs(), QgsMapToolIdentify::featureDerivedAttributes(), QgsComposerScaleBar::mapWidth(), QgsOWSSourceSelect::on_mChangeCRSButton_clicked(), QgsRasterLayerSaveAsDialog::on_mChangeCrsPushButton_clicked(), QgsNewVectorLayerDialog::on_pbnChangeSpatialRefSys_clicked(), QgsNewVectorLayerDialog::QgsNewVectorLayerDialog(), QgsProjectionSelector::QgsProjectionSelector(), readXML(), QgsMapRenderer::setDestinationCrs(), QgsDistanceArea::setEllipsoid(), and writeXML().
bool QgsCoordinateReferenceSystem::syncDatumTransform (const QString & dbPath) static private
Definition at line 1963 of file qgscoordinatereferencesystem.cpp.
References QgsDebugMsgLevel, qgsDoubleToString(), quotedValue(), and QgsApplication::srsDbFilePath().
Referenced by syncDb().
int QgsCoordinateReferenceSystem::syncDb () static
Update proj.4 parameters in our database from proj.4
Returns
number of updated CRS on success and negative number of failed updates in case of errors.
Note
added in 1.8
Definition at line 1699 of file qgscoordinatereferencesystem.cpp.
References loadIDs(), loadWkts(), QgsDebugMsg, QgsDebugMsgLevel, quotedValue(), QgsApplication::srsDbFilePath(), syncDatumTransform(), and tr.
QString QgsCoordinateReferenceSystem::toProj4 () const
Get the Proj Proj4 string representation of this srs.
If proj and ellps keys are found in the parameters, they will be stripped out and the Projection and ellipsoid acronyms will be overridden with these.
Returns
QString theProj4String Proj4 format specifies that define this srs.
Note
A zero length string will be returned if the toProj4 is uninitialised
Definition at line 874 of file qgscoordinatereferencesystem.cpp.
References mCRS, mIsValidFlag, and mProj4.
Referenced by createFromString(), createFromWkt(), debugPrint(), QgsMapRenderer::destinationCrs(), findMatchingProj(), QgsCoordinateTransform::initialise(), QgsDistanceArea::measureLine(), QgsRasterLayer::metadata(), QgsVectorLayer::metadata(), operator<<(), readXML(), saveAsUserCRS(), QgsMapRenderer::setDestinationCrs(), QgsDistanceArea::setEllipsoid(), QgsCoordinateTransform::transformCoords(), writeXML(), and QgsProjectionSelector::~QgsProjectionSelector().
QString QgsCoordinateReferenceSystem::toWkt () const
A helper to get an wkt representation of this srs
Returns
string containing Wkt of the srs
Definition at line 1142 of file qgscoordinatereferencesystem.cpp.
References mCRS, and mWkt.
Referenced by QgsRasterFileWriter::createVRT(), debugPrint(), QgsRasterCalculator::processCalculation(), QgsVectorFileWriter::QgsVectorFileWriter(), QgsRasterLayer::setDataProvider(), and QgsGridFileWriter::writeFile().
void QgsCoordinateReferenceSystem::validate ()
Perform some validation on this CRS. If the sts doesn't validate the default behaviour settings for layers with unknown CRS will be consulted and acted on accordingly. By hell or high water this method will do its best to make sure that this CRS is valid - even if that involves resorting to a hard coded default of geocs:wgs84.
Note
It is not usually necessary to use this function, unless you are trying to force this srs to be valid.
Definition at line 293 of file qgscoordinatereferencesystem.cpp.
References QgsCRSCache::crsByAuthId(), GEO_EPSG_CRS_AUTHID, QgsCRSCache::instance(), mCustomSrsValidation, and mIsValidFlag.
Referenced by QgsNewVectorLayerDialog::QgsNewVectorLayerDialog(), QgsMapLayer::readLayerXML(), and QgsMapLayer::setCrs().
QString QgsCoordinateReferenceSystem::validationHint ()
Get user hint for validation
Definition at line 1453 of file qgscoordinatereferencesystem.cpp.
References mValidationHint.
bool QgsCoordinateReferenceSystem::writeXML (QDomNode & theNode, QDomDocument & theDoc) const
Stores state to the given Dom node in the given document. Below is an example of the generated tag.
 <spatialrefsys>
     <proj4>+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs </proj4>
      <srsid>2585</srsid>
      <srid>4326</srid>
      <epsg>4326</epsg>
      <description>WGS 84</description>
      <projectionacronym>longlat</projectionacronym>
      <ellipsoidacronym>WGS84</ellipsoidacronym>
  </spatialrefsys>
Parameters
theNode The node in which state will be restored
theDoc The document in which state will be stored
Returns
bool True on success, False on failure
Definition at line 1275 of file qgscoordinatereferencesystem.cpp.
References authid(), description(), ellipsoidAcronym(), geographicFlag(), postgisSrid(), projectionAcronym(), srsid(), and toProj4().
Referenced by QgsMapLayer::writeLayerXML(), QgsMapSettings::writeXML(), and QgsCoordinateTransform::writeXML().
Member Data Documentation
QString QgsCoordinateReferenceSystem::mAuthId private
If available the authority identifier for this srs.
Definition at line 449 of file qgscoordinatereferencesystem.h.
Referenced by authid(), axisInverted(), geographicCRSAuthId(), loadFromDb(), operator=(), setAuthId(), and setEpsg().
int QgsCoordinateReferenceSystem::mAxisInverted mutable private
Whether this is a coordinate system has inverted axis.
Definition at line 475 of file qgscoordinatereferencesystem.h.
Referenced by axisInverted(), createFromOgcWmsCrs(), loadFromDb(), and operator=().
OGRSpatialReferenceH QgsCoordinateReferenceSystem::mCRS private
Definition at line 462 of file qgscoordinatereferencesystem.h.
Referenced by axisInverted(), createFromWkt(), geographicCRSAuthId(), loadFromDb(), operator=(), QgsCoordinateReferenceSystem(), setMapUnits(), setProj4String(), toProj4(), toWkt(), and ~QgsCoordinateReferenceSystem().
CUSTOM_CRS_VALIDATION QgsCoordinateReferenceSystem::mCustomSrsValidation = NULL static private
Definition at line 477 of file qgscoordinatereferencesystem.h.
Referenced by customSrsValidation(), setCustomSrsValidation(), and validate().
QString QgsCoordinateReferenceSystem::mDescription private
A textual description of the srs.
Definition at line 437 of file qgscoordinatereferencesystem.h.
Referenced by debugPrint(), description(), loadFromDb(), operator=(), and setDescription().
QString QgsCoordinateReferenceSystem::mEllipsoidAcronym private
The official proj4 acronym for the ellipoid.
Definition at line 441 of file qgscoordinatereferencesystem.h.
Referenced by createFromProj4(), ellipsoidAcronym(), findMatchingProj(), loadFromDb(), operator=(), and setEllipsoidAcronym().
bool QgsCoordinateReferenceSystem::mGeoFlag private
Whether this is a geographic or projected coordinate system.
Definition at line 443 of file qgscoordinatereferencesystem.h.
Referenced by geographicFlag(), loadFromDb(), operator=(), and setGeographicFlag().
bool QgsCoordinateReferenceSystem::mIsValidFlag private
Whether this srs is properly defined and valid.
Definition at line 451 of file qgscoordinatereferencesystem.h.
Referenced by createFromOgcWmsCrs(), createFromProj4(), createFromWkt(), debugPrint(), findMatchingProj(), isValid(), loadFromDb(), operator=(), operator==(), readXML(), saveAsUserCRS(), setMapUnits(), setProj4String(), toProj4(), and validate().
QGis::UnitType QgsCoordinateReferenceSystem::mMapUnits private
The map units.
Definition at line 445 of file qgscoordinatereferencesystem.h.
Referenced by mapUnits(), operator=(), and setMapUnits().
QString QgsCoordinateReferenceSystem::mProj4 mutable private
Definition at line 468 of file qgscoordinatereferencesystem.h.
Referenced by createFromWkt(), loadFromDb(), operator=(), saveAsUserCRS(), setProj4String(), and toProj4().
QString QgsCoordinateReferenceSystem::mProjectionAcronym private
The official proj4 acronym for the projection family.
Definition at line 439 of file qgscoordinatereferencesystem.h.
Referenced by createFromProj4(), findMatchingProj(), loadFromDb(), operator=(), projectionAcronym(), and setProjectionAcronym().
long QgsCoordinateReferenceSystem::mSRID private
If available, the Postgis spatial_ref_sys identifier for this srs (defaults to 0)
Definition at line 447 of file qgscoordinatereferencesystem.h.
Referenced by loadFromDb(), operator=(), postgisSrid(), and setSrid().
long QgsCoordinateReferenceSystem::mSrsId private
The internal sqlite3 srs.db primary key for this srs.
Definition at line 435 of file qgscoordinatereferencesystem.h.
Referenced by createFromWkt(), debugPrint(), loadFromDb(), operator=(), readXML(), setInternalId(), and srsid().
QString QgsCoordinateReferenceSystem::mValidationHint private
Definition at line 466 of file qgscoordinatereferencesystem.h.
Referenced by operator=(), setValidationHint(), and validationHint().
QString QgsCoordinateReferenceSystem::mWkt mutable private
Definition at line 467 of file qgscoordinatereferencesystem.h.
Referenced by createFromProj4(), createFromWkt(), loadFromDb(), operator=(), setProj4String(), and toWkt().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgscoordinatereferencesystem.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgscoordinatereferencesystem.cpp