QGIS API Documentation: QgsComposerArrow Class Reference
QgsComposerArrow Class Reference
An item that draws an arrow between to points.
#include <qgscomposerarrow.h>
Public Types
enum MarkerMode { DefaultMarker, NoMarker, SVGMarker }
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Public Member Functions
QgsComposerArrow (QgsComposition *c)
QgsComposerArrow (const QPointF &startPoint, const QPointF &stopPoint, QgsComposition *c)
~QgsComposerArrow ()
virtual int type () const
return correct graphics item type.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint - draw on canvas.
void setSceneRect (const QRectF &rectangle)
Modifies position of start and endpoint and calls QgsComposerItem::setSceneRect.
void setArrowHeadWidth (double width)
Sets the width of the arrow head in mm.
double arrowHeadWidth () const
void setOutlineWidth (double width)
double outlineWidth () const
void setStartMarker (const QString &svgPath)
QString startMarker () const
void setEndMarker (const QString &svgPath)
QString endMarker () const
QColor arrowColor () const
void setArrowColor (const QColor &c)
MarkerMode markerMode () const
void setMarkerMode (MarkerMode mode)
bool writeXML (QDomElement &elem, QDomDocument &doc) const
stores state in Dom element
bool readXML (const QDomElement &itemElem, const QDomDocument &doc)
sets state from Dom document
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected () const
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
int page () const
Gets the page the item is currently on.
QPointF pagePos () const
Returns the item's position relative to its current page.
void updatePagePos (double newPageWidth, double newPageHeight)
Moves the item so that it retains its relative position on the page when the paper size changes.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft, int page=-1)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft, bool posIncludesFrame=false, int page=-1)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
virtual void setFrameOutlineWidth (double outlineWidth)
Sets frame outline width.
double frameOutlineWidth () const
Returns the frame's outline width.
Qt::PenJoinStyle frameJoinStyle () const
Returns the join style used for drawing the item's frame.
void setFrameJoinStyle (Qt::PenJoinStyle style)
Sets join style used when drawing the item's frame.
virtual double estimatedFrameBleed () const
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
virtual QRectF rectWithFrame () const
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop, int flags=Qt::TextWordWrap) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font descent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightMillimeters (const QFont &font) const
Returns the font height in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
double itemRotation () const
Returns the rotation for the composer item.
Q_DECL_DEPRECATED double rotation () const
Returns the rotation for the composer item.
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
virtual int numberExportLayers () const
Get the number of layers that this item requires for exporting as layers.
virtual void setCurrentExportLayer (int layerIdx=-1)
Sets the current layer to draw for exporting.
Private Types
enum MarkerType { StartMarker, EndMarker }
Private Member Functions
void adaptItemSceneRect ()
Adapts the item scene rect to contain the start point, the stop point including the arrow marker and the outline.
double computeMarkerMargin () const
Computes the margin around the line necessary to include the markers.
void drawHardcodedMarker (QPainter *p, MarkerType type)
Draws the default marker at the line end.
void drawSVGMarker (QPainter *p, MarkerType type, const QString &markerPath)
Draws a user-defined marker (must be an svg file)
void initGraphicsSettings ()
Apply default graphics settings.
Private Attributes
QPointF mStartPoint
QPointF mStopPoint
int mStartXIdx
Considering the rectangle as spanning [x[0], x[1]] x [y[0], y[1]], these indices specify which index {0, 1} corresponds to the start point coordinate of the respective dimension.
int mStartYIdx
QPen mPen
QBrush mBrush
double mArrowHeadWidth
Width of the arrow marker in mm.
double mStartArrowHeadHeight
Height of the arrow marker in mm.
double mStopArrowHeadHeight
QString mStartMarkerFile
Path to the start marker file.
QString mEndMarkerFile
Path to the end marker file.
MarkerMode mMarkerMode
Default marker, no marker or svg marker.
QColor mArrowColor
int mBoundsBehaviour
Indicates QGIS version to mimic bounding box behaviour for.
Additional Inherited Members
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
Sets the item rotation.
virtual void setItemRotation (double r, bool adjustPosition=false)
Sets the item rotation.
void repaint ()
Signals inherited from QgsComposerItem
void itemRotationChanged (double newRotation)
Is emitted on item rotation change.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
void frameChanged ()
Emitted if the item's frame style changes.
Protected Member Functions inherited from QgsComposerItem
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height, double rotation) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Q_DECL_DEPRECATED bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
QRectF largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height, double rotation) const
Calculates corner point after rotation and scaling.
Q_DECL_DEPRECATED bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height, double rotation)
Calculates width / height of the bounding box of a rotated rectangle.
Q_DECL_DEPRECATED void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Protected Attributes inherited from QgsComposerItem
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
Qt::PenJoinStyle mFrameJoinStyle
Frame join style.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mItemRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
int mCurrentExportLayer
The layer that needs to be exported.
Detailed Description
An item that draws an arrow between to points.
Definition at line 26 of file qgscomposerarrow.h.
Member Enumeration Documentation
enum QgsComposerArrow::MarkerMode
Enumerator
DefaultMarker
NoMarker
SVGMarker
Definition at line 30 of file qgscomposerarrow.h.
enum QgsComposerArrow::MarkerType private
Enumerator
StartMarker
EndMarker
Definition at line 82 of file qgscomposerarrow.h.
Constructor & Destructor Documentation
QgsComposerArrow::QgsComposerArrow (QgsComposition * c)
Definition at line 26 of file qgscomposerarrow.cpp.
References initGraphicsSettings().
QgsComposerArrow::QgsComposerArrow (const QPointF & startPoint, const QPointF & stopPoint, QgsComposition * c)
Definition at line 39 of file qgscomposerarrow.cpp.
References adaptItemSceneRect(), initGraphicsSettings(), mStartPoint, mStartXIdx, mStartYIdx, and mStopPoint.
QgsComposerArrow::~QgsComposerArrow ()
Definition at line 53 of file qgscomposerarrow.cpp.
Member Function Documentation
void QgsComposerArrow::adaptItemSceneRect () private
Adapts the item scene rect to contain the start point, the stop point including the arrow marker and the outline.
Needs to be called whenever the arrow width/height, the outline with or the endpoints are changed
Definition at line 344 of file qgscomposerarrow.cpp.
References computeMarkerMargin(), mStartPoint, mStopPoint, and QgsComposerItem::setSceneRect().
Referenced by QgsComposerArrow(), readXML(), setArrowHeadWidth(), setEndMarker(), setMarkerMode(), setOutlineWidth(), and setStartMarker().
QColor QgsComposerArrow::arrowColor () const inline
Definition at line 62 of file qgscomposerarrow.h.
double QgsComposerArrow::arrowHeadWidth () const inline
Definition at line 52 of file qgscomposerarrow.h.
double QgsComposerArrow::computeMarkerMargin () const private
Computes the margin around the line necessary to include the markers.
Definition at line 302 of file qgscomposerarrow.cpp.
References DefaultMarker, mArrowHeadWidth, mBoundsBehaviour, mMarkerMode, mPen, mStartArrowHeadHeight, mStopArrowHeadHeight, NoMarker, and SVGMarker.
Referenced by adaptItemSceneRect(), and setSceneRect().
void QgsComposerArrow::drawHardcodedMarker (QPainter * p, MarkerType type) private
Draws the default marker at the line end.
Definition at line 138 of file qgscomposerarrow.cpp.
References QgsComposerItem::angle(), QgsComposerItem::drawArrowHead(), mArrowColor, mArrowHeadWidth, mBoundsBehaviour, mStartPoint, and mStopPoint.
Referenced by paint().
void QgsComposerArrow::drawSVGMarker (QPainter * p, MarkerType type, const QString & markerPath) private
Draws a user-defined marker (must be an svg file)
Definition at line 157 of file qgscomposerarrow.cpp.
References QgsComposerItem::angle(), QgsComposerItem::horizontalViewScaleFactor(), M_PI, mArrowHeadWidth, mBoundsBehaviour, QgsComposerItem::mComposition, mEndMarkerFile, mStartArrowHeadHeight, mStartMarkerFile, mStartPoint, mStopArrowHeadHeight, mStopPoint, QgsComposition::plotStyle(), QgsComposition::Preview, and StartMarker.
Referenced by paint().
QString QgsComposerArrow::endMarker () const inline
Definition at line 60 of file qgscomposerarrow.h.
void QgsComposerArrow::initGraphicsSettings () private
Apply default graphics settings.
Definition at line 58 of file qgscomposerarrow.cpp.
References mPen, and setArrowHeadWidth().
Referenced by QgsComposerArrow().
MarkerMode QgsComposerArrow::markerMode () const inline
Definition at line 65 of file qgscomposerarrow.h.
double QgsComposerArrow::outlineWidth () const inline
Definition at line 55 of file qgscomposerarrow.h.
Referenced by writeXML().
void QgsComposerArrow::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget)
Reimplementation of QCanvasItem::paint - draw on canvas.
Definition at line 69 of file qgscomposerarrow.cpp.
References DefaultMarker, QgsComposerItem::drawBackground(), QgsComposerItem::drawFrame(), drawHardcodedMarker(), QgsComposerItem::drawSelectionBoxes(), drawSVGMarker(), EndMarker, mArrowColor, mBoundsBehaviour, mEndMarkerFile, mMarkerMode, mPen, mStartMarkerFile, mStartPoint, mStopPoint, StartMarker, and SVGMarker.
bool QgsComposerArrow::readXML (const QDomElement & itemElem, const QDomDocument & doc) virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is the document to read
Implements QgsComposerItem.
Definition at line 394 of file qgscomposerarrow.cpp.
References QgsComposerItem::_readXML(), adaptItemSceneRect(), QgsComposerItem::itemChanged(), mArrowColor, mArrowHeadWidth, mBoundsBehaviour, mMarkerMode, mPen, mStartPoint, mStartXIdx, mStartYIdx, mStopPoint, setEndMarker(), and setStartMarker().
Referenced by QgsComposition::addItemsFromXML().
void QgsComposerArrow::setArrowColor (const QColor & c) inline
Definition at line 63 of file qgscomposerarrow.h.
void QgsComposerArrow::setArrowHeadWidth (double width)
Sets the width of the arrow head in mm.
Definition at line 294 of file qgscomposerarrow.cpp.
References adaptItemSceneRect(), mArrowHeadWidth, mEndMarkerFile, mStartMarkerFile, setEndMarker(), and setStartMarker().
Referenced by initGraphicsSettings().
void QgsComposerArrow::setEndMarker (const QString & svgPath)
Definition at line 272 of file qgscomposerarrow.cpp.
References adaptItemSceneRect(), mArrowHeadWidth, mEndMarkerFile, and mStopArrowHeadHeight.
Referenced by readXML(), and setArrowHeadWidth().
void QgsComposerArrow::setMarkerMode (MarkerMode mode)
Definition at line 354 of file qgscomposerarrow.cpp.
References adaptItemSceneRect(), and mMarkerMode.
void QgsComposerArrow::setOutlineWidth (double width)
Definition at line 288 of file qgscomposerarrow.cpp.
References adaptItemSceneRect(), and mPen.
void QgsComposerArrow::setSceneRect (const QRectF & rectangle) virtual
Modifies position of start and endpoint and calls QgsComposerItem::setSceneRect.
Reimplemented from QgsComposerItem.
Definition at line 109 of file qgscomposerarrow.cpp.
References computeMarkerMargin(), mStartPoint, mStartXIdx, mStartYIdx, mStopPoint, and QgsComposerItem::setSceneRect().
void QgsComposerArrow::setStartMarker (const QString & svgPath)
Definition at line 256 of file qgscomposerarrow.cpp.
References adaptItemSceneRect(), mArrowHeadWidth, mStartArrowHeadHeight, and mStartMarkerFile.
Referenced by readXML(), and setArrowHeadWidth().
QString QgsComposerArrow::startMarker () const inline
Definition at line 58 of file qgscomposerarrow.h.
virtual int QgsComposerArrow::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerItem.
Definition at line 42 of file qgscomposerarrow.h.
References QgsComposerItem::ComposerArrow.
bool QgsComposerArrow::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
stores state in Dom element
Parameters
elem is Dom element corresponding to 'Composer' tag
doc document
Implements QgsComposerItem.
Definition at line 360 of file qgscomposerarrow.cpp.
References QgsComposerItem::_writeXML(), mArrowColor, mArrowHeadWidth, mBoundsBehaviour, mEndMarkerFile, mMarkerMode, mStartMarkerFile, mStartPoint, mStopPoint, and outlineWidth().
Member Data Documentation
QColor QgsComposerArrow::mArrowColor private
Definition at line 112 of file qgscomposerarrow.h.
Referenced by drawHardcodedMarker(), paint(), readXML(), and writeXML().
double QgsComposerArrow::mArrowHeadWidth private
Width of the arrow marker in mm.
May be specified by the user. The height is automatically adapted
Definition at line 101 of file qgscomposerarrow.h.
Referenced by computeMarkerMargin(), drawHardcodedMarker(), drawSVGMarker(), readXML(), setArrowHeadWidth(), setEndMarker(), setStartMarker(), and writeXML().
int QgsComposerArrow::mBoundsBehaviour private
Indicates QGIS version to mimic bounding box behaviour for.
The line placement changed in version 2.4, so a value of 22 is used to indicate that the line should be drawn using the older placement routine.
Definition at line 116 of file qgscomposerarrow.h.
Referenced by computeMarkerMargin(), drawHardcodedMarker(), drawSVGMarker(), paint(), readXML(), and writeXML().
QBrush QgsComposerArrow::mBrush private
Definition at line 98 of file qgscomposerarrow.h.
QString QgsComposerArrow::mEndMarkerFile private
Path to the end marker file.
Definition at line 109 of file qgscomposerarrow.h.
Referenced by drawSVGMarker(), paint(), setArrowHeadWidth(), setEndMarker(), and writeXML().
MarkerMode QgsComposerArrow::mMarkerMode private
Default marker, no marker or svg marker.
Definition at line 111 of file qgscomposerarrow.h.
Referenced by computeMarkerMargin(), paint(), readXML(), setMarkerMode(), and writeXML().
QPen QgsComposerArrow::mPen private
Definition at line 97 of file qgscomposerarrow.h.
Referenced by computeMarkerMargin(), initGraphicsSettings(), paint(), readXML(), and setOutlineWidth().
double QgsComposerArrow::mStartArrowHeadHeight private
Height of the arrow marker in mm.
Is calculated from arrow marker width and apsect ratio of svg
Definition at line 103 of file qgscomposerarrow.h.
Referenced by computeMarkerMargin(), drawSVGMarker(), and setStartMarker().
QString QgsComposerArrow::mStartMarkerFile private
Path to the start marker file.
Definition at line 107 of file qgscomposerarrow.h.
Referenced by drawSVGMarker(), paint(), setArrowHeadWidth(), setStartMarker(), and writeXML().
QPointF QgsComposerArrow::mStartPoint private
Definition at line 88 of file qgscomposerarrow.h.
Referenced by adaptItemSceneRect(), drawHardcodedMarker(), drawSVGMarker(), paint(), QgsComposerArrow(), readXML(), setSceneRect(), and writeXML().
int QgsComposerArrow::mStartXIdx private
Considering the rectangle as spanning [x[0], x[1]] x [y[0], y[1]], these indices specify which index {0, 1} corresponds to the start point coordinate of the respective dimension.
Definition at line 94 of file qgscomposerarrow.h.
Referenced by QgsComposerArrow(), readXML(), and setSceneRect().
int QgsComposerArrow::mStartYIdx private
Definition at line 95 of file qgscomposerarrow.h.
Referenced by QgsComposerArrow(), readXML(), and setSceneRect().
double QgsComposerArrow::mStopArrowHeadHeight private
Definition at line 104 of file qgscomposerarrow.h.
Referenced by computeMarkerMargin(), drawSVGMarker(), and setEndMarker().
QPointF QgsComposerArrow::mStopPoint private
Definition at line 89 of file qgscomposerarrow.h.
Referenced by adaptItemSceneRect(), drawHardcodedMarker(), drawSVGMarker(), paint(), QgsComposerArrow(), readXML(), setSceneRect(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerarrow.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerarrow.cpp