QGIS API Documentation: QgsMapCanvas Class Reference
QgsMapCanvas Class Reference
QGIS gui library.
Map canvas is a class for displaying all GIS data types on a canvas.
#include <qgsmapcanvas.h>
Classes
class CanvasProperties
Public Types
enum WheelAction { WheelZoom, WheelZoomAndRecenter, WheelZoomToMouseCursor, WheelNothing }
Public Slots
void refresh ()
Repaints the canvas map.
void selectionChangedSlot ()
Receives signal about selection change, and pass it on with layer info.
void saveAsImage (QString theFileName, QPixmap *QPixmap=0, QString="PNG")
Save the convtents of the map canvas to disk as an image.
void layerStateChange ()
This slot is connected to the visibility change of one or more layers.
void setRenderFlag (bool theFlag)
Whether to suppress rendering or not.
bool renderFlag ()
State of render suppression flag.
bool hasCrsTransformEnabled ()
A simple helper method to find out if on the fly projections are enabled or not.
Q_DECL_DEPRECATED void updateMap ()
void stopRendering ()
stop rendering (if there is any right now)
Q_DECL_DEPRECATED void showError (QgsMapLayer *mapLayer)
void readProject (const QDomDocument &)
called to read map canvas settings from project
void writeProject (QDomDocument &)
called to write map canvas settings to project
void getDatumTransformInfo (const QgsMapLayer *ml, const QString &srcAuthId, const QString &destAuthId)
ask user about datum transformation
Signals
Q_DECL_DEPRECATED void setProgress (int, int)
Let the owner know how far we are with render operations.
void xyCoordinates (const QgsPoint &p)
emits current mouse position
void scaleChanged (double)
Emitted when the scale of the map changes.
void extentsChanged ()
Emitted when the extents of the map change.
void renderComplete (QPainter *)
Emitted when the canvas has rendered.
void mapCanvasRefreshed ()
Emitted when canvas finished a refresh request.
void renderStarting ()
Emitted when the canvas is about to be rendered.
void layersChanged ()
Emitted when a new set of layers has been received.
void keyPressed (QKeyEvent *e)
Emit key press event.
void keyReleased (QKeyEvent *e)
Emit key release event.
void mapToolSet (QgsMapTool *tool)
Emit map tool changed event.
void mapToolSet (QgsMapTool *newTool, QgsMapTool *oldTool)
Emit map tool changed with the old tool.
void selectionChanged (QgsMapLayer *layer)
Emitted when selection in any layer gets changed.
void zoomLastStatusChanged (bool)
Emitted when zoom last status changed.
void zoomNextStatusChanged (bool)
Emitted when zoom next status changed.
void hasCrsTransformEnabledChanged (bool flag)
Emitted when on-the-fly projection has been turned on/off.
void destinationCrsChanged ()
Emitted when map CRS has changed.
void mapUnitsChanged ()
Emmitted when map units are changed.
Public Member Functions
QgsMapCanvas (QWidget *parent=0, const char *name=0)
Constructor.
~QgsMapCanvas ()
Destructor.
void setLayerSet (QList< QgsMapCanvasLayer > &layers)
void setCurrentLayer (QgsMapLayer *layer)
void updateOverview ()
void enableOverviewMode (QgsMapOverviewCanvas *overview)
const QgsMapSettings & mapSettings () const
Get access to properties used for map rendering.
void setCrsTransformEnabled (bool enabled)
sets whether to use projections for this layer set
void setDestinationCrs (const QgsCoordinateReferenceSystem &crs)
sets destination coordinate reference system
const QgsLabelingResults * labelingResults () const
Get access to the labeling results (may be null)
void setCachingEnabled (bool enabled)
Set whether to cache images of rendered layers.
bool isCachingEnabled () const
Check whether images of rendered layers are curerently being cached.
void clearCache ()
Make sure to remove any rendered images from cache (does nothing if cache is not enabled)
void setParallelRenderingEnabled (bool enabled)
Set whether the layers are rendered in parallel or sequentially.
bool isParallelRenderingEnabled () const
Check whether the layers are rendered in parallel or sequentially.
void setMapUpdateInterval (int timeMiliseconds)
Set how often map preview should be updated while it is being rendered (in milliseconds)
int mapUpdateInterval () const
Find out how often map preview should be updated while it is being rendered (in milliseconds)
QgsMapCanvasMap * map ()
Q_DECL_DEPRECATED QgsMapRenderer * mapRenderer ()
Q_DECL_DEPRECATED QPaintDevice & canvasPaintDevice ()
Accessor for the canvas paint device.
double scale ()
Get the last reported scale of the canvas.
Q_DECL_DEPRECATED void clear ()
Clear the map canvas.
double mapUnitsPerPixel () const
Returns the mapUnitsPerPixel (map units per pixel) for the canvas.
QgsRectangle extent () const
Returns the current zoom exent of the map canvas.
QgsRectangle fullExtent () const
Returns the combined exent for all layers on the map canvas.
void setExtent (const QgsRectangle &r)
Set the extent of the map canvas.
void zoomToFullExtent ()
Zoom to the full extent of all layers.
void zoomToPreviousExtent ()
Zoom to the previous extent (view)
void zoomToNextExtent ()
Zoom to the next extent (view)
void clearExtentHistory ()
void zoomToSelected (QgsVectorLayer *layer=NULL)
Zoom to the extent of the selected features of current (vector) layer.
void panToSelected (QgsVectorLayer *layer=NULL)
Pan to the selected features of current (vector) layer keeping same extent.
void setMapTool (QgsMapTool *mapTool)
Sets the map tool currently being used on the canvas.
void unsetMapTool (QgsMapTool *mapTool)
Unset the current map tool or last non zoom tool.
QgsMapTool * mapTool ()
Returns the currently active tool.
virtual void setCanvasColor (const QColor &_newVal)
Write property of QColor bgColor.
virtual QColor canvasColor () const
Read property of QColor bgColor.
void setSelectionColor (const QColor &color)
Set color of selected vector features.
void updateScale ()
Emits signal scaleChanged to update scale in main window.
Q_DECL_DEPRECATED void updateFullExtent ()
Updates the full extent.
QgsMapLayer * layer (int index)
return the map layer at position index in the layer stack
int layerCount () const
return number of layers on the map
QList< QgsMapLayer * > layers () const
return list of layers within map canvas. Added in v1.5
void freeze (bool frz=true)
bool isFrozen ()
Q_DECL_DEPRECATED void setDirty (bool _dirty)
Flag the canvas as dirty and needed a refresh.
Q_DECL_DEPRECATED bool isDirty () const
Return the state of the canvas (dirty or not)
void setMapUnits (QGis::UnitType mapUnits)
Set map units (needed by project properties dialog)
QGis::UnitType mapUnits () const
Get the current canvas map units.
const QgsMapToPixel * getCoordinateTransform ()
Get the current coordinate transform.
bool isDrawing ()
Find out whether rendering is in progress.
QgsMapLayer * currentLayer ()
returns current layer (set by legend widget)
void setWheelAction (WheelAction action, double factor=2)
set wheel action and zoom factor (should be greater than 1)
void zoomIn ()
Zoom in with fixed factor.
void zoomOut ()
Zoom out with fixed factor.
void zoomScale (double scale)
Zoom to a specific scale.
void zoomByFactor (double scaleFactor)
Zoom with the factor supplied. Factor > 1 zooms out, interval (0,1) zooms in.
void zoomWithCenter (int x, int y, bool zoomIn)
Zooms in/out with a given center.
void enableAntiAliasing (bool theFlag)
used to determine if anti-aliasing is enabled or not
bool antiAliasingEnabled () const
true if antialising is enabled
Q_DECL_DEPRECATED void useImageToRender (bool theFlag)
Select which Qt class to render with.
void panActionEnd (QPoint releasePoint)
Ends pan action and redraws the canvas.
void panAction (QMouseEvent *event)
Called when mouse is moving and pan is activated.
QPoint mouseLastXY ()
returns last position of mouse cursor
void setPreviewModeEnabled (bool previewEnabled)
Enables a preview mode for the map canvas.
bool previewModeEnabled () const
Returns whether a preview mode is enabled for the map canvas.
void setPreviewMode (QgsPreviewEffect::PreviewMode mode)
Sets a preview mode for the map canvas.
QgsPreviewEffect::PreviewMode previewMode () const
Returns the current preview mode for the map canvas.
Protected Member Functions
void keyPressEvent (QKeyEvent *e)
Overridden key press event.
void keyReleaseEvent (QKeyEvent *e)
Overridden key release event.
void mouseDoubleClickEvent (QMouseEvent *e)
Overridden mouse double click event.
void mouseMoveEvent (QMouseEvent *e)
Overridden mouse move event.
void mousePressEvent (QMouseEvent *e)
Overridden mouse press event.
void mouseReleaseEvent (QMouseEvent *e)
Overridden mouse release event.
void wheelEvent (QWheelEvent *e)
Overridden mouse wheel event.
void resizeEvent (QResizeEvent *e)
Overridden resize event.
void paintEvent (QPaintEvent *e)
Overridden paint event.
void dragEnterEvent (QDragEnterEvent *e)
Overridden drag enter event.
void moveCanvasContents (bool reset=false)
called when panning is in action, reset indicates end of panning
void updateCanvasItemPositions ()
called on resize or changed extent to notify canvas items to change their rectangle
void connectNotify (const char *signal)
debugging member invoked when a connect() is made to this object
void updateDatumTransformEntries ()
Make sure the datum transform store is properly populated.
Protected Attributes
std::auto_ptr< CanvasProperties > mCanvasProperties
Handle pattern for implementation object.
Private Slots
void mapToolDestroyed ()
called when current maptool is destroyed
void rendererJobFinished ()
called when a renderer job has finished successfully or when it was cancelled
void mapUpdateTimeout ()
void refreshMap ()
Private Member Functions
QgsMapCanvas (QgsMapCanvas const &)
this class is non-copyable
Private Attributes
QgsMapSettings mSettings
encompases all map settings necessary for map rendering
QgsMapRenderer * mMapRenderer
all map rendering is done in this class
QgsMapCanvasMap * mMap
owns pixmap with rendered map and controls rendering
QgsMapOverviewCanvas * mMapOverview
map overview widget - it's controlled by QgsMapCanvas
bool mFrozen
Flag indicating if the map canvas is frozen.
bool mRefreshScheduled
Flag that allows squashing multiple refresh() calls into just one delayed rendering job.
bool mRenderFlag
determines whether user has requested to suppress rendering
QgsMapLayer * mCurrentLayer
current layer in legend
QGraphicsScene * mScene
graphics scene manages canvas items
QgsMapTool * mMapTool
pointer to current map tool
QgsMapTool * mLastNonZoomMapTool
previous tool if current is for zooming/panning
QList< QgsRectangle > mLastExtent
recently used extent
int mLastExtentIndex
double mWheelZoomFactor
Scale factor multiple for default zoom in/out.
WheelAction mWheelAction
Mouse wheel action.
QTimer mMapUpdateTimer
Timer that periodically fires while map rendering is in progress to update the visible map.
QgsMapRendererQImageJob * mJob
Job that takes care of map rendering in background.
bool mJobCancelled
Flag determining whether the active job has been cancelled.
QgsLabelingResults * mLabelingResults
Labeling results from the recently rendered map.
bool mUseParallelRendering
Whether layers are rendered sequentially or in parallel.
bool mDrawRenderingStats
Whether to add rendering stats to the rendered image.
QgsMapRendererCache * mCache
Optionally use cache with rendered map layers for the current map settings.
QTimer * mResizeTimer
QgsPreviewEffect * mPreviewEffect
Detailed Description
Map canvas is a class for displaying all GIS data types on a canvas.
Definition at line 104 of file qgsmapcanvas.h.
Member Enumeration Documentation
enum QgsMapCanvas::WheelAction
Enumerator
WheelZoom
WheelZoomAndRecenter
WheelZoomToMouseCursor
WheelNothing
Definition at line 110 of file qgsmapcanvas.h.
Constructor & Destructor Documentation
QgsMapCanvas::QgsMapCanvas (QWidget * parent = 0, const char * name = 0)
Constructor.
Definition at line 172 of file qgsmapcanvas.cpp.
References QgsMapSettings::DrawEditingInfo, QgsProject::instance(), mapUpdateTimeout(), mCurrentLayer, mFrozen, mLastExtentIndex, mLastNonZoomMapTool, mMap, mMapOverview, mMapRenderer, mMapTool, mMapUpdateTimer, moveCanvasContents(), mPreviewEffect, mRefreshScheduled, mRenderFlag, mResizeTimer, mScene, mSettings, QgsMapSettings::outputDpi(), readProject(), refresh(), QgsMapSettings::setFlag(), QgsMapSettings::setOutputSize(), QgsMapRenderer::setOutputSize(), setWheelAction(), QgsMapSettings::UseRenderingOptimization, WheelZoom, and writeProject().
QgsMapCanvas::~QgsMapCanvas ()
Destructor.
Definition at line 254 of file qgsmapcanvas.cpp.
References QgsMapRendererJob::cancel(), QgsMapTool::deactivate(), mCache, mJob, mLabelingResults, mLastNonZoomMapTool, mMapRenderer, mMapTool, and mScene.
QgsMapCanvas::QgsMapCanvas (QgsMapCanvas const &) private
this class is non-copyable
Note
Otherwise std::auto_ptr would pass the object responsiblity on to the copy like a hot potato leaving the copyer in a weird state.
Member Function Documentation
bool QgsMapCanvas::antiAliasingEnabled () const inline
true if antialising is enabled
Definition at line 319 of file qgsmapcanvas.h.
References QgsMapSettings::Antialiasing.
Referenced by QgsMapCanvasItem::paint().
QColor QgsMapCanvas::canvasColor () const virtual
Read property of QColor bgColor.
Definition at line 1457 of file qgsmapcanvas.cpp.
References mScene.
QPaintDevice & QgsMapCanvas::canvasPaintDevice ()
Accessor for the canvas paint device.
Deprecated:
since 2.4
Definition at line 1507 of file qgsmapcanvas.cpp.
References mMap, QgsMapCanvasMap::paintDevice(), Q_NOWARN_DEPRECATED_POP, and Q_NOWARN_DEPRECATED_PUSH.
void QgsMapCanvas::clear ()
Clear the map canvas.
Deprecated:
since 2.4 - use refresh() - clear does the same thing
Definition at line 865 of file qgsmapcanvas.cpp.
References refresh().
void QgsMapCanvas::clearCache ()
Make sure to remove any rendered images from cache (does nothing if cache is not enabled)
Note
added in 2.4
Definition at line 549 of file qgsmapcanvas.cpp.
References QgsMapRendererCache::clear(), and mCache.
void QgsMapCanvas::clearExtentHistory ()
Definition at line 923 of file qgsmapcanvas.cpp.
References extent(), mLastExtent, mLastExtentIndex, zoomLastStatusChanged(), and zoomNextStatusChanged().
Referenced by readProject().
void QgsMapCanvas::connectNotify (const char * signal) protected
debugging member invoked when a connect() is made to this object
Definition at line 1554 of file qgsmapcanvas.cpp.
References QgsDebugMsg.
QgsMapLayer * QgsMapCanvas::currentLayer ()
returns current layer (set by legend widget)
Definition at line 586 of file qgsmapcanvas.cpp.
References mCurrentLayer.
Referenced by QgsMapToolIdentify::identify(), setLayerSet(), QgsMapCanvasSnapper::snapToBackgroundLayers(), and QgsMapCanvasSnapper::snapToCurrentLayer().
void QgsMapCanvas::destinationCrsChanged () signal
Emitted when map CRS has changed.
Note
added in 2.4
Referenced by enableOverviewMode(), and setDestinationCrs().
void QgsMapCanvas::dragEnterEvent (QDragEnterEvent * e) protected
Overridden drag enter event.
Definition at line 1830 of file qgsmapcanvas.cpp.
void QgsMapCanvas::enableAntiAliasing (bool theFlag)
used to determine if anti-aliasing is enabled or not
Definition at line 293 of file qgsmapcanvas.cpp.
References QgsMapSettings::Antialiasing, QgsMapOverviewCanvas::enableAntiAliasing(), mMapOverview, mSettings, and QgsMapSettings::setFlag().
void QgsMapCanvas::enableOverviewMode (QgsMapOverviewCanvas * overview)
Definition at line 449 of file qgsmapcanvas.cpp.
References destinationCrsChanged(), hasCrsTransformEnabled(), hasCrsTransformEnabledChanged(), and mMapOverview.
QgsRectangle QgsMapCanvas::extent () const
Returns the current zoom exent of the map canvas.
Definition at line 799 of file qgsmapcanvas.cpp.
References mapSettings(), and QgsMapSettings::visibleExtent().
Referenced by QgsMapToolZoom::canvasReleaseEvent(), clearExtentHistory(), QgsMapOverviewCanvas::drawExtentRect(), QgsAttributeTableFilterModel::generateListOfVisibleFeatures(), QgsMapToolIdentify::identify(), QgsMapOverviewCanvas::mouseReleaseEvent(), QgsHighlight::paint(), QgsHighlight::paintPoint(), QgsMapToolTouch::pinchTriggered(), setExtent(), QgsHighlight::updateRect(), wheelEvent(), zoomToFullExtent(), and zoomToSelected().
void QgsMapCanvas::extentsChanged () signal
Emitted when the extents of the map change.
Referenced by resizeEvent(), setExtent(), zoomToNextExtent(), and zoomToPreviousExtent().
void QgsMapCanvas::freeze (bool frz = true)
Freeze/thaw the map canvas. This is used to prevent the canvas from responding to events while layers are being added/removed etc.
Parameters
frz Boolean specifying if the canvas should be frozen (true) or thawed (false). Default is true.
Definition at line 1496 of file qgsmapcanvas.cpp.
References mFrozen.
QgsRectangle QgsMapCanvas::fullExtent () const
Returns the combined exent for all layers on the map canvas.
Definition at line 804 of file qgsmapcanvas.cpp.
References QgsMapSettings::fullExtent(), and mapSettings().
Referenced by QgsMapOverviewCanvas::updateFullExtent(), and zoomToFullExtent().
const QgsMapToPixel * QgsMapCanvas::getCoordinateTransform ()
Get the current coordinate transform.
Definition at line 358 of file qgsmapcanvas.cpp.
References mapSettings(), and QgsMapSettings::mapToPixel().
Referenced by QgsMapToolPan::canvasReleaseEvent(), QgsMapToolZoom::canvasReleaseEvent(), QgsMapToolTouch::canvasReleaseEvent(), QgsMapToolIdentify::identify(), mouseMoveEvent(), panActionEnd(), QgsMapToolTouch::pinchTriggered(), QgsRubberBand::setToCanvasRectangle(), QgsMapCanvasSnapper::snapToBackgroundLayers(), QgsMapCanvasItem::toCanvasCoordinates(), QgsMapTool::toCanvasCoordinates(), QgsMapCanvasItem::toMapCoordinates(), QgsMapTool::toMapCoordinates(), wheelEvent(), and zoomWithCenter().
void QgsMapCanvas::getDatumTransformInfo (const QgsMapLayer * ml, const QString & srcAuthId, const QString & destAuthId) slot
ask user about datum transformation
Ask user which datum transform to use.
Definition at line 1746 of file qgsmapcanvas.cpp.
References QgsDatumTransformStore::addEntry(), QgsMapRenderer::addLayerCoordinateTransform(), QgsCoordinateReferenceSystem::authid(), QgsCRSCache::crsByAuthId(), QgsCoordinateTransform::datumTransformations(), QgsMapSettings::datumTransformStore(), QgsMapLayer::id(), QgsCRSCache::instance(), mMapRenderer, mSettings, QgsMapLayer::name(), and QgsDatumTransformDialog::setDatumTransformInfo().
Referenced by updateDatumTransformEntries().
bool QgsMapCanvas::hasCrsTransformEnabled () slot
A simple helper method to find out if on the fly projections are enabled or not.
Definition at line 934 of file qgsmapcanvas.cpp.
References QgsMapSettings::hasCrsTransformEnabled(), and mapSettings().
Referenced by enableOverviewMode(), QgsMapToolIdentify::featureDerivedAttributes(), and QgsMapToolIdentify::identifyRasterLayer().
void QgsMapCanvas::hasCrsTransformEnabledChanged (bool flag) signal
Emitted when on-the-fly projection has been turned on/off.
Note
added in 2.4
Referenced by enableOverviewMode(), and setCrsTransformEnabled().
bool QgsMapCanvas::isCachingEnabled () const
Check whether images of rendered layers are curerently being cached.
Note
added in 2.4
Definition at line 544 of file qgsmapcanvas.cpp.
References mCache.
Referenced by setCachingEnabled().
bool QgsMapCanvas::isDirty () const
Return the state of the canvas (dirty or not)
Deprecated:
since 2.4 - dirty flag is not kept anymore - always returns false
Definition at line 343 of file qgsmapcanvas.cpp.
bool QgsMapCanvas::isDrawing ()
Find out whether rendering is in progress.
Definition at line 350 of file qgsmapcanvas.cpp.
References mJob.
bool QgsMapCanvas::isFrozen ()
Accessor for frozen status of canvas
Definition at line 1501 of file qgsmapcanvas.cpp.
References mFrozen.
bool QgsMapCanvas::isParallelRenderingEnabled () const
Check whether the layers are rendered in parallel or sequentially.
Note
added in 2.4
Definition at line 560 of file qgsmapcanvas.cpp.
References mUseParallelRendering.
void QgsMapCanvas::keyPressed (QKeyEvent * e) signal
Emit key press event.
Referenced by keyPressEvent().
void QgsMapCanvas::keyPressEvent (QKeyEvent * e) protected
Overridden key press event.
Definition at line 1004 of file qgsmapcanvas.cpp.
References keyPressed(), QgsMapTool::keyPressEvent(), mapSettings(), mCanvasProperties, mDrawRenderingStats, mMapTool, mUseParallelRendering, QgsDebugMsg, refresh(), setExtent(), QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsRectangle::setYMaximum(), QgsRectangle::setYMinimum(), QgsMapSettings::visibleExtent(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), QgsRectangle::yMinimum(), zoomIn(), and zoomOut().
void QgsMapCanvas::keyReleased (QKeyEvent * e) signal
Emit key release event.
Referenced by keyReleaseEvent().
void QgsMapCanvas::keyReleaseEvent (QKeyEvent * e) protected
Overridden key release event.
Definition at line 1111 of file qgsmapcanvas.cpp.
References keyReleased(), QgsMapTool::keyReleaseEvent(), mCanvasProperties, mMapTool, panActionEnd(), and QgsDebugMsg.
const QgsLabelingResults * QgsMapCanvas::labelingResults () const
Get access to the labeling results (may be null)
Note
added in 2.4
Definition at line 523 of file qgsmapcanvas.cpp.
References mLabelingResults.
QgsMapLayer * QgsMapCanvas::layer (int index)
return the map layer at position index in the layer stack
Definition at line 317 of file qgsmapcanvas.cpp.
References QgsMapLayerRegistry::instance(), QgsMapSettings::layers(), layers(), QgsMapLayerRegistry::mapLayer(), and mapSettings().
Referenced by QgsMapToolIdentify::identify(), layers(), selectionChangedSlot(), setCurrentLayer(), setLayerSet(), and updateDatumTransformEntries().
int QgsMapCanvas::layerCount () const
return number of layers on the map
Definition at line 1467 of file qgsmapcanvas.cpp.
References QgsMapSettings::layers(), and mapSettings().
Referenced by QgsMapToolIdentify::identify(), and setLayerSet().
QList< QgsMapLayer * > QgsMapCanvas::layers () const
return list of layers within map canvas. Added in v1.5
Definition at line 1473 of file qgsmapcanvas.cpp.
References QgsMapLayerRegistry::instance(), layer(), QgsMapLayerRegistry::mapLayer(), and mapSettings().
Referenced by layer(), QgsFormAnnotationItem::updateVisibility(), and QgsHtmlAnnotationItem::updateVisibility().
void QgsMapCanvas::layersChanged () signal
Emitted when a new set of layers has been received.
Referenced by setLayerSet().
void QgsMapCanvas::layerStateChange () slot
This slot is connected to the visibility change of one or more layers.
Definition at line 1486 of file qgsmapcanvas.cpp.
References refresh().
QgsMapCanvasMap * QgsMapCanvas::map ()
Deprecated:
since 2.4 - there could be more than just one "map" items
Definition at line 306 of file qgsmapcanvas.cpp.
References mMap.
void QgsMapCanvas::mapCanvasRefreshed () signal
Emitted when canvas finished a refresh request.
Note
Added in 2.0
Referenced by rendererJobFinished().
QgsMapRenderer * QgsMapCanvas::mapRenderer ()
Deprecated:
since 2.4 - use mapSettings() for anything related to current renderer settings / SIP: removed /Transfer/ because it crashes after few calls to iface.mapCanvas().mapRenderer().hasCrsTransformEnabled() / and in fact there is no transfer of ownership from c++ to python! / Actually the problem comes from the fact that "hasCrsTransformEnabled" is both a signal and a normal method / /KeepReference/ is necessary because otherwise mapRenderer().hasCrsTransformEnabled() was crashing
Definition at line 311 of file qgsmapcanvas.cpp.
References mMapRenderer.
const QgsMapSettings & QgsMapCanvas::mapSettings () const
Get access to properties used for map rendering.
Note
added in 2.4
Definition at line 474 of file qgsmapcanvas.cpp.
References mSettings.
Referenced by QgsRubberBand::addGeometry(), QgsMapOverviewCanvas::destinationSrsChanged(), extent(), QgsMapToolIdentify::featureDerivedAttributes(), QgsMapTip::fetchFeature(), fullExtent(), QgsAttributeTableFilterModel::generateListOfVisibleFeatures(), getCoordinateTransform(), hasCrsTransformEnabled(), QgsMapToolIdentify::identifyRasterLayer(), QgsMapToolIdentify::identifyVectorLayer(), QgsHighlight::init(), keyPressEvent(), layer(), layerCount(), layers(), mapUnits(), mapUnitsPerPixel(), QgsMapCanvasRendererSync::onCrsTransformC2R(), QgsMapCanvasRendererSync::onDestCrsC2R(), QgsMapCanvasRendererSync::onExtentC2R(), QgsMapCanvasRendererSync::onLayersC2R(), QgsMapCanvasRendererSync::onMapUnitsC2R(), QgsHighlight::paint(), panActionEnd(), panToSelected(), QgsMapCanvasSnapper::QgsMapCanvasSnapper(), saveAsImage(), scale(), QgsMapTool::searchRadiusMU(), setLayerSet(), QgsMapCanvasSnapper::setMapCanvas(), QgsScaleRangeWidget::setMaxScaleFromCanvas(), QgsScaleRangeWidget::setMinScaleFromCanvas(), QgsMapCanvasItem::setRenderContextVariables(), QgsMapCanvasSnapper::snapToBackgroundLayers(), QgsMapCanvasSnapper::snapToCurrentLayer(), QgsMapTool::toLayerCoordinates(), QgsMapTool::toMapCoordinates(), updateScale(), wheelEvent(), zoomByFactor(), zoomToSelected(), and zoomWithCenter().
QgsMapTool * QgsMapCanvas::mapTool ()
Returns the currently active tool.
Definition at line 1585 of file qgsmapcanvas.cpp.
References mMapTool.
void QgsMapCanvas::mapToolDestroyed () private slot
called when current maptool is destroyed
Definition at line 1838 of file qgsmapcanvas.cpp.
References mMapTool, and QgsDebugMsg.
Referenced by setMapTool().
void QgsMapCanvas::mapToolSet (QgsMapTool * tool) signal
Emit map tool changed event.
Referenced by setMapTool(), and unsetMapTool().
void QgsMapCanvas::mapToolSet (QgsMapTool * newTool, QgsMapTool * oldTool) signal
Emit map tool changed with the old tool.
Note
added in 2.3
QGis::UnitType QgsMapCanvas::mapUnits () const
Get the current canvas map units.
Definition at line 1536 of file qgsmapcanvas.cpp.
References mapSettings(), and QgsMapSettings::mapUnits().
Referenced by QgsMapToolIdentify::convertMeasurement(), and QgsMapToolIdentify::displayUnits().
void QgsMapCanvas::mapUnitsChanged () signal
Emmitted when map units are changed.
Note
added in 2.4
Referenced by setMapUnits().
double QgsMapCanvas::mapUnitsPerPixel () const
Returns the mapUnitsPerPixel (map units per pixel) for the canvas.
Definition at line 1514 of file qgsmapcanvas.cpp.
References mapSettings(), and QgsMapSettings::mapUnitsPerPixel().
Referenced by QgsMapToolIdentify::identify(), saveAsImage(), and QgsRubberBand::updateRect().
int QgsMapCanvas::mapUpdateInterval () const
Find out how often map preview should be updated while it is being rendered (in milliseconds)
Note
added in 2.4
Definition at line 570 of file qgsmapcanvas.cpp.
References mMapUpdateTimer.
void QgsMapCanvas::mapUpdateTimeout () private slot
Definition at line 724 of file qgsmapcanvas.cpp.
References mJob, mMap, mSettings, QgsMapRendererQImageJob::renderedImage(), QgsMapCanvasMap::setContent(), and QgsMapSettings::visibleExtent().
Referenced by QgsMapCanvas().
void QgsMapCanvas::mouseDoubleClickEvent (QMouseEvent * e) protected
Overridden mouse double click event.
Definition at line 1143 of file qgsmapcanvas.cpp.
References QgsMapTool::canvasDoubleClickEvent(), and mMapTool.
QPoint QgsMapCanvas::mouseLastXY ()
returns last position of mouse cursor
Definition at line 1658 of file qgsmapcanvas.cpp.
References mCanvasProperties.
void QgsMapCanvas::mouseMoveEvent (QMouseEvent * e) protected
Overridden mouse move event.
Definition at line 1360 of file qgsmapcanvas.cpp.
References QgsMapTool::canvasMoveEvent(), getCoordinateTransform(), mCanvasProperties, mMapTool, panAction(), QgsMapToPixel::toMapCoordinates(), and xyCoordinates().
void QgsMapCanvas::mousePressEvent (QMouseEvent * e) protected
Overridden mouse press event.
Definition at line 1151 of file qgsmapcanvas.cpp.
References QgsMapTool::canvasPressEvent(), mCanvasProperties, and mMapTool.
void QgsMapCanvas::mouseReleaseEvent (QMouseEvent * e) protected
Overridden mouse release event.
Definition at line 1178 of file qgsmapcanvas.cpp.
References QgsMapTool::canvasReleaseEvent(), QgsVectorLayer::isEditable(), QgsMapTool::isEditTool(), QgsMapTool::isTransient(), mCanvasProperties, mCurrentLayer, mLastNonZoomMapTool, mMapTool, panActionEnd(), QgsDebugMsg, and setMapTool().
void QgsMapCanvas::moveCanvasContents (bool reset = false) protected
called when panning is in action, reset indicates end of panning
Definition at line 1644 of file qgsmapcanvas.cpp.
References mCanvasProperties.
Referenced by panAction(), panActionEnd(), QgsMapCanvas(), and resizeEvent().
void QgsMapCanvas::paintEvent (QPaintEvent * e) protected
Overridden paint event.
Definition at line 1245 of file qgsmapcanvas.cpp.
void QgsMapCanvas::panAction (QMouseEvent * event)
Called when mouse is moving and pan is activated.
Definition at line 1636 of file qgsmapcanvas.cpp.
References moveCanvasContents().
Referenced by QgsMapToolPan::canvasMoveEvent(), QgsMapToolTouch::canvasMoveEvent(), and mouseMoveEvent().
void QgsMapCanvas::panActionEnd (QPoint releasePoint)
Ends pan action and redraws the canvas.
Definition at line 1590 of file qgsmapcanvas.cpp.
References getCoordinateTransform(), mapSettings(), mCanvasProperties, moveCanvasContents(), refresh(), setExtent(), QgsRectangle::setXMinimum(), QgsMapToPixel::toMapCoordinates(), QgsMapSettings::visibleExtent(), QgsPoint::x(), and QgsPoint::y().
Referenced by QgsMapToolPan::canvasReleaseEvent(), QgsMapToolTouch::canvasReleaseEvent(), keyReleaseEvent(), and mouseReleaseEvent().
void QgsMapCanvas::panToSelected (QgsVectorLayer * layer = NULL)
Pan to the selected features of current (vector) layer keeping same extent.
Note
added in 2.0
Definition at line 981 of file qgsmapcanvas.cpp.
References QgsVectorLayer::boundingBoxOfSelected(), QgsRectangle::center(), QgsMapSettings::layerExtentToOutputExtent(), mapSettings(), mCurrentLayer, refresh(), QgsVectorLayer::selectedFeatureCount(), and setExtent().
QgsPreviewEffect::PreviewMode QgsMapCanvas::previewMode () const
Returns the current preview mode for the map canvas.
This setting only has an effect if previewModeEnabled is true.
Returns
preview mode for map canvas
See also
setPreviewMode
previewModeEnabled
Note
added in 2.3
Definition at line 1693 of file qgsmapcanvas.cpp.
References QgsPreviewEffect::mode(), mPreviewEffect, and QgsPreviewEffect::PreviewGrayscale.
bool QgsMapCanvas::previewModeEnabled () const
Returns whether a preview mode is enabled for the map canvas.
Returns
true if a preview mode is currently enabled
See also
setPreviewModeEnabled
previewMode
Note
added in 2.3
Definition at line 1673 of file qgsmapcanvas.cpp.
References mPreviewEffect.
void QgsMapCanvas::readProject (const QDomDocument & doc) slot
called to read map canvas settings from project
Definition at line 1703 of file qgsmapcanvas.cpp.
References clearExtentHistory(), QgsMapSettings::datumTransformStore(), QgsMapSettings::destinationCrs(), QgsMapSettings::extent(), QgsMapSettings::hasCrsTransformEnabled(), QgsMapSettings::mapUnits(), mSettings, QgsDebugMsg, QgsMapSettings::readXML(), setCrsTransformEnabled(), setDestinationCrs(), setExtent(), and setMapUnits().
Referenced by QgsMapCanvas().
void QgsMapCanvas::refresh () slot
Repaints the canvas map.
Definition at line 592 of file qgsmapcanvas.cpp.
References QgsMapSettings::hasValidSettings(), mFrozen, mRefreshScheduled, mRenderFlag, mSettings, QgsDebugMsg, and refreshMap().
Referenced by QgsMapToolPan::canvasReleaseEvent(), QgsMapToolZoom::canvasReleaseEvent(), QgsMapToolTouch::canvasReleaseEvent(), clear(), keyPressEvent(), layerStateChange(), QgsMapOverviewCanvas::mouseReleaseEvent(), panActionEnd(), panToSelected(), QgsMapToolTouch::pinchTriggered(), QgsMapCanvas(), selectionChangedSlot(), setCrsTransformEnabled(), setDestinationCrs(), setDirty(), setLayerSet(), setMapUnits(), setRenderFlag(), wheelEvent(), zoomByFactor(), zoomToFullExtent(), zoomToNextExtent(), zoomToPreviousExtent(), zoomToSelected(), and zoomWithCenter().
void QgsMapCanvas::refreshMap () private slot
Definition at line 620 of file qgsmapcanvas.cpp.
References QgsMapLayerRegistry::instance(), QgsMapSettings::layers(), mCache, mJob, mJobCancelled, mMapUpdateTimer, mRefreshScheduled, mSettings, mUseParallelRendering, QgsDebugMsg, rendererJobFinished(), renderStarting(), QgsMapRendererJob::setCache(), QgsMapRendererJob::setRequestedGeometryCacheForLayers(), QgsExpression::setSpecialColumn(), QgsMapRendererJob::start(), stopRendering(), and tr.
Referenced by refresh().
void QgsMapCanvas::renderComplete (QPainter *) signal
Emitted when the canvas has rendered.
Passes a pointer to the painter on which the map was drawn. This is useful for plugins that wish to draw on the map after it has been rendered. Passing the painter allows plugins to work when the map is being rendered onto a pixmap other than the mapCanvas own pixmap member.TODO: deprecate when decorations are reimplemented as map canvas items
anything related to rendering progress is not visible outside of map canvas
additional drawing shall be done directly within the renderer job or independently as a map canvas item
Referenced by rendererJobFinished(), and saveAsImage().
void QgsMapCanvas::rendererJobFinished () private slot
called when a renderer job has finished successfully or when it was cancelled
Definition at line 663 of file qgsmapcanvas.cpp.
References QgsMapRendererJob::errors(), QgsMapRendererJob::Error::layerID, QgsMessageLog::logMessage(), mapCanvasRefreshed(), mDrawRenderingStats, QgsMapRendererJob::Error::message, mJob, mJobCancelled, mLabelingResults, mMap, mMapUpdateTimer, mSettings, mUseParallelRendering, QgsDebugMsg, renderComplete(), QgsMapRendererQImageJob::renderedImage(), QgsMapRendererJob::renderingTime(), QgsMapCanvasMap::setContent(), QgsMapRendererJob::takeLabelingResults(), tr, and QgsMapSettings::visibleExtent().
Referenced by refreshMap().
bool QgsMapCanvas::renderFlag () inline slot
State of render suppression flag.
Definition at line 383 of file qgsmapcanvas.h.
void QgsMapCanvas::renderStarting () signal
Emitted when the canvas is about to be rendered.
Note
Added in 1.5
Referenced by refreshMap().
void QgsMapCanvas::resizeEvent (QResizeEvent * e) protected
Overridden resize event.
Definition at line 1221 of file qgsmapcanvas.cpp.
References extentsChanged(), mMapRenderer, moveCanvasContents(), mResizeTimer, mScene, mSettings, QgsMapSettings::outputDpi(), QgsMapSettings::setOutputSize(), QgsMapRenderer::setOutputSize(), updateCanvasItemPositions(), and updateScale().
void QgsMapCanvas::saveAsImage (QString theFileName, QPixmap * QPixmap = 0, QString theFormat = "PNG") slot
Save the convtents of the map canvas to disk as an image.
Definition at line 746 of file qgsmapcanvas.cpp.
References QgsMapCanvasMap::contentImage(), mapSettings(), mapUnitsPerPixel(), mMap, mSettings, qgsDoubleToString(), renderComplete(), QgsMapRendererCustomPainterJob::start(), QgsMapSettings::visibleExtent(), QgsMapRendererCustomPainterJob::waitForFinished(), QgsRectangle::xMinimum(), and QgsRectangle::yMaximum().
double QgsMapCanvas::scale ()
Get the last reported scale of the canvas.
Definition at line 332 of file qgsmapcanvas.cpp.
References mapSettings(), and QgsMapSettings::scale().
Referenced by QgsMapCanvasItem::setRenderContextVariables(), updateScale(), and zoomScale().
void QgsMapCanvas::scaleChanged (double) signal
Emitted when the scale of the map changes.
Referenced by updateScale().
void QgsMapCanvas::selectionChanged (QgsMapLayer * layer) signal
Emitted when selection in any layer gets changed.
Referenced by selectionChangedSlot(), and setLayerSet().
void QgsMapCanvas::selectionChangedSlot () slot
Receives signal about selection change, and pass it on with layer info.
Definition at line 1822 of file qgsmapcanvas.cpp.
References layer(), refresh(), and selectionChanged().
Referenced by setLayerSet().
void QgsMapCanvas::setCachingEnabled (bool enabled)
Set whether to cache images of rendered layers.
Note
added in 2.4
Definition at line 528 of file qgsmapcanvas.cpp.
References isCachingEnabled(), and mCache.
void QgsMapCanvas::setCanvasColor (const QColor & theColor) virtual
Write property of QColor bgColor.
Definition at line 1439 of file qgsmapcanvas.cpp.
References mScene, mSettings, and QgsMapSettings::setBackgroundColor().
void QgsMapCanvas::setCrsTransformEnabled (bool enabled)
sets whether to use projections for this layer set
Note
added in 2.4
Definition at line 479 of file qgsmapcanvas.cpp.
References QgsMapSettings::hasCrsTransformEnabled(), hasCrsTransformEnabledChanged(), mSettings, refresh(), QgsMapSettings::setCrsTransformEnabled(), and updateDatumTransformEntries().
Referenced by QgsMapCanvasRendererSync::onCrsTransformR2C(), and readProject().
void QgsMapCanvas::setCurrentLayer (QgsMapLayer * layer)
Definition at line 327 of file qgsmapcanvas.cpp.
References layer(), and mCurrentLayer.
void QgsMapCanvas::setDestinationCrs (const QgsCoordinateReferenceSystem & crs)
sets destination coordinate reference system
Note
added in 2.4
Definition at line 493 of file qgsmapcanvas.cpp.
References QgsMapSettings::destinationCrs(), destinationCrsChanged(), QgsMapSettings::hasCrsTransformEnabled(), QgsRectangle::isEmpty(), mSettings, QgsDebugMsg, refresh(), QgsMapSettings::setDestinationCrs(), setExtent(), updateDatumTransformEntries(), and QgsMapSettings::visibleExtent().
Referenced by QgsMapCanvasRendererSync::onDestCrsR2C(), and readProject().
void QgsMapCanvas::setDirty (bool _dirty)
Flag the canvas as dirty and needed a refresh.
Deprecated:
since 2.4 - use refresh() to trigger a refresh (clients should not decide explicitly whether canvas is dirty or not)
Definition at line 337 of file qgsmapcanvas.cpp.
References refresh().
void QgsMapCanvas::setExtent (const QgsRectangle & r)
Set the extent of the map canvas.
Definition at line 810 of file qgsmapcanvas.cpp.
References QgsRectangle::center(), extent(), extentsChanged(), QgsRectangle::height(), QgsRectangle::isEmpty(), mLastExtent, mLastExtentIndex, mSettings, QgsDebugMsg, QgsMapSettings::setExtent(), updateCanvasItemPositions(), updateScale(), QgsRectangle::width(), QgsPoint::x(), QgsPoint::y(), zoomLastStatusChanged(), and zoomNextStatusChanged().
Referenced by QgsMapToolPan::canvasReleaseEvent(), QgsMapToolZoom::canvasReleaseEvent(), QgsMapToolTouch::canvasReleaseEvent(), keyPressEvent(), QgsMapOverviewCanvas::mouseReleaseEvent(), QgsMapCanvasRendererSync::onExtentR2C(), panActionEnd(), panToSelected(), QgsMapToolTouch::pinchTriggered(), readProject(), setDestinationCrs(), wheelEvent(), zoomByFactor(), zoomToFullExtent(), zoomToSelected(), and zoomWithCenter().
void QgsMapCanvas::setLayerSet (QList< QgsMapCanvasLayer > & layers)
Definition at line 363 of file qgsmapcanvas.cpp.
References currentLayer(), QgsMapLayer::id(), QgsMapCanvasLayer::isInOverview(), QgsMapCanvasLayer::isVisible(), QgsMapCanvasLayer::layer(), layer(), layerCount(), QgsMapSettings::layers(), layersChanged(), QgsMapOverviewCanvas::layerSet(), mapSettings(), mMapOverview, mSettings, QgsDebugMsg, refresh(), selectionChanged(), selectionChangedSlot(), QgsMapSettings::setLayers(), QgsMapOverviewCanvas::setLayerSet(), updateDatumTransformEntries(), and updateOverview().
void QgsMapCanvas::setMapTool (QgsMapTool * mapTool)
Sets the map tool currently being used on the canvas.
Definition at line 1384 of file qgsmapcanvas.cpp.
References QgsMapTool::activate(), QgsMapTool::deactivate(), QgsMapTool::isTransient(), mapToolDestroyed(), mapToolSet(), mLastNonZoomMapTool, and mMapTool.
Referenced by mouseReleaseEvent().
void QgsMapCanvas::setMapUnits (QGis::UnitType mapUnits)
Set map units (needed by project properties dialog)
Definition at line 1520 of file qgsmapcanvas.cpp.
References QgsMapSettings::mapUnits(), mapUnitsChanged(), mSettings, QgsDebugMsg, refresh(), QgsMapSettings::setMapUnits(), and updateScale().
Referenced by QgsMapCanvasRendererSync::onMapUnitsR2C(), and readProject().
void QgsMapCanvas::setMapUpdateInterval (int timeMiliseconds)
Set how often map preview should be updated while it is being rendered (in milliseconds)
Note
added in 2.4
Definition at line 565 of file qgsmapcanvas.cpp.
References mMapUpdateTimer.
void QgsMapCanvas::setParallelRenderingEnabled (bool enabled)
Set whether the layers are rendered in parallel or sequentially.
Note
added in 2.4
Definition at line 555 of file qgsmapcanvas.cpp.
References mUseParallelRendering.
void QgsMapCanvas::setPreviewMode (QgsPreviewEffect::PreviewMode mode)
Sets a preview mode for the map canvas.
This setting only has an effect if previewModeEnabled is true.
Parameters
mode preview mode for the canvas
See also
previewMode
setPreviewModeEnabled
previewModeEnabled
Note
added in 2.3
Definition at line 1683 of file qgsmapcanvas.cpp.
References mPreviewEffect, and QgsPreviewEffect::setMode().
void QgsMapCanvas::setPreviewModeEnabled (bool previewEnabled)
Enables a preview mode for the map canvas.
Parameters
previewEnabled set to true to enable a preview mode
See also
setPreviewMode
Note
added in 2.3
Definition at line 1663 of file qgsmapcanvas.cpp.
References mPreviewEffect.
Q_DECL_DEPRECATED void QgsMapCanvas::setProgress (int , int) signal
Let the owner know how far we are with render operations.
Deprecated:
since 2.4 - already unused in 2.0 anyway
void QgsMapCanvas::setRenderFlag (bool theFlag) slot
Whether to suppress rendering or not.
Definition at line 1542 of file qgsmapcanvas.cpp.
References mRenderFlag, refresh(), and stopRendering().
void QgsMapCanvas::setSelectionColor (const QColor & color)
Set color of selected vector features.
Note
added in 2.4
Definition at line 1462 of file qgsmapcanvas.cpp.
References mSettings, and QgsMapSettings::setSelectionColor().
void QgsMapCanvas::setWheelAction (WheelAction action, double factor = 2)
set wheel action and zoom factor (should be greater than 1)
Definition at line 1327 of file qgsmapcanvas.cpp.
References mWheelAction, and mWheelZoomFactor.
Referenced by QgsMapCanvas().
void QgsMapCanvas::showError (QgsMapLayer * mapLayer) slot
Deprecated:
since 2.4 - does nothing - errors are reported by different means
Definition at line 1653 of file qgsmapcanvas.cpp.
void QgsMapCanvas::stopRendering () slot
stop rendering (if there is any right now)
Note
added in 2.4
Definition at line 730 of file qgsmapcanvas.cpp.
References QgsMapRendererJob::cancel(), mJob, mJobCancelled, and QgsDebugMsg.
Referenced by refreshMap(), and setRenderFlag().
void QgsMapCanvas::unsetMapTool (QgsMapTool * mapTool)
Unset the current map tool or last non zoom tool.
This is called from destructor of map tools to make sure that this map tool won't be used any more. You don't have to call it manualy, QgsMapTool takes care of it.
Definition at line 1421 of file qgsmapcanvas.cpp.
References QgsMapTool::deactivate(), mapToolSet(), mLastNonZoomMapTool, and mMapTool.
Referenced by QgsMapTool::~QgsMapTool().
void QgsMapCanvas::updateCanvasItemPositions () protected
called on resize or changed extent to notify canvas items to change their rectangle
Definition at line 1252 of file qgsmapcanvas.cpp.
References mScene, and QgsMapCanvasItem::updatePosition().
Referenced by resizeEvent(), setExtent(), zoomToNextExtent(), and zoomToPreviousExtent().
void QgsMapCanvas::updateDatumTransformEntries () protected
Make sure the datum transform store is properly populated.
Definition at line 1561 of file qgsmapcanvas.cpp.
References QgsCoordinateReferenceSystem::authid(), QgsMapLayer::crs(), QgsMapSettings::datumTransformStore(), QgsMapSettings::destinationCrs(), QgsVectorLayer::geometryType(), getDatumTransformInfo(), QgsMapSettings::hasCrsTransformEnabled(), QgsDatumTransformStore::hasEntryForLayer(), QgsMapLayerRegistry::instance(), layer(), QgsMapSettings::layers(), QgsMapLayerRegistry::mapLayer(), mSettings, and QGis::NoGeometry.
Referenced by setCrsTransformEnabled(), setDestinationCrs(), and setLayerSet().
Q_DECL_DEPRECATED void QgsMapCanvas::updateFullExtent () inline
Updates the full extent.
Deprecated:
since v2.4 - does nothing
Definition at line 252 of file qgsmapcanvas.h.
void QgsMapCanvas::updateMap () slot
Deprecated:
in 2.4 - does nothing - kept for API compatibility
Definition at line 741 of file qgsmapcanvas.cpp.
void QgsMapCanvas::updateOverview ()
Definition at line 576 of file qgsmapcanvas.cpp.
References mMapOverview, and QgsMapOverviewCanvas::refresh().
Referenced by setLayerSet().
void QgsMapCanvas::updateScale ()
Emits signal scaleChanged to update scale in main window.
Definition at line 859 of file qgsmapcanvas.cpp.
References mapSettings(), scale(), and scaleChanged().
Referenced by resizeEvent(), setExtent(), setMapUnits(), zoomToNextExtent(), and zoomToPreviousExtent().
void QgsMapCanvas::useImageToRender (bool theFlag)
Select which Qt class to render with.
Deprecated:
since 2.4 - does nothing because now we always render to QImage
Definition at line 301 of file qgsmapcanvas.cpp.
void QgsMapCanvas::wheelEvent (QWheelEvent * e) protected
Overridden mouse wheel event.
Definition at line 1270 of file qgsmapcanvas.cpp.
References extent(), getCoordinateTransform(), mapSettings(), mMapTool, mWheelAction, mWheelZoomFactor, QgsDebugMsg, refresh(), QgsRectangle::scale(), setExtent(), QgsMapSettings::visibleExtent(), QgsMapTool::wheelEvent(), WheelNothing, WheelZoom, WheelZoomAndRecenter, WheelZoomToMouseCursor, QgsPoint::x(), QgsPoint::y(), zoomIn(), zoomOut(), and zoomWithCenter().
void QgsMapCanvas::writeProject (QDomDocument & doc) slot
called to write map canvas settings to project
Definition at line 1726 of file qgsmapcanvas.cpp.
References mSettings, QgsDebugMsg, and QgsMapSettings::writeXML().
Referenced by QgsMapCanvas().
void QgsMapCanvas::xyCoordinates (const QgsPoint & p) signal
emits current mouse position
Note
changed in 1.3
Referenced by mouseMoveEvent().
void QgsMapCanvas::zoomByFactor (double scaleFactor)
Zoom with the factor supplied. Factor > 1 zooms out, interval (0,1) zooms in.
Definition at line 1814 of file qgsmapcanvas.cpp.
References mapSettings(), refresh(), QgsRectangle::scale(), setExtent(), and QgsMapSettings::visibleExtent().
Referenced by zoomIn(), zoomOut(), and zoomScale().
void QgsMapCanvas::zoomIn ()
Zoom in with fixed factor.
Definition at line 1333 of file qgsmapcanvas.cpp.
References mWheelZoomFactor, and zoomByFactor().
Referenced by keyPressEvent(), and wheelEvent().
void QgsMapCanvas::zoomLastStatusChanged (bool) signal
Emitted when zoom last status changed.
Note
: this signal was added in version 1.4
Referenced by clearExtentHistory(), setExtent(), zoomToNextExtent(), and zoomToPreviousExtent().
void QgsMapCanvas::zoomNextStatusChanged (bool) signal
Emitted when zoom next status changed.
Note
: this signal was added in version 1.4
Referenced by clearExtentHistory(), setExtent(), zoomToNextExtent(), and zoomToPreviousExtent().
void QgsMapCanvas::zoomOut ()
Zoom out with fixed factor.
Definition at line 1338 of file qgsmapcanvas.cpp.
References mWheelZoomFactor, and zoomByFactor().
Referenced by keyPressEvent(), QgsMapToolTouch::pinchTriggered(), and wheelEvent().
void QgsMapCanvas::zoomScale (double scale)
Zoom to a specific scale.
Definition at line 1343 of file qgsmapcanvas.cpp.
References scale(), and zoomByFactor().
void QgsMapCanvas::zoomToFullExtent ()
Zoom to the full extent of all layers.
Definition at line 872 of file qgsmapcanvas.cpp.
References extent(), fullExtent(), QgsRectangle::isEmpty(), refresh(), QgsRectangle::scale(), and setExtent().
void QgsMapCanvas::zoomToNextExtent ()
Zoom to the next extent (view)
Definition at line 906 of file qgsmapcanvas.cpp.
References extentsChanged(), mLastExtent, mLastExtentIndex, mSettings, refresh(), QgsMapSettings::setExtent(), updateCanvasItemPositions(), updateScale(), zoomLastStatusChanged(), and zoomNextStatusChanged().
void QgsMapCanvas::zoomToPreviousExtent ()
Zoom to the previous extent (view)
Definition at line 888 of file qgsmapcanvas.cpp.
References extentsChanged(), mLastExtent, mLastExtentIndex, mSettings, refresh(), QgsMapSettings::setExtent(), updateCanvasItemPositions(), updateScale(), zoomLastStatusChanged(), and zoomNextStatusChanged().
void QgsMapCanvas::zoomToSelected (QgsVectorLayer * layer = NULL)
Zoom to the extent of the selected features of current (vector) layer.
Added in version 1.2: optionally specify different than current layer
Definition at line 939 of file qgsmapcanvas.cpp.
References QgsVectorLayer::boundingBoxOfSelected(), QgsRectangle::center(), extent(), QgsRectangle::isEmpty(), QgsMapSettings::layerExtentToOutputExtent(), mapSettings(), mCurrentLayer, refresh(), QgsRectangle::scale(), QgsVectorLayer::selectedFeatureCount(), and setExtent().
void QgsMapCanvas::zoomWithCenter (int x, int y, bool zoomIn)
Zooms in/out with a given center.
Definition at line 1348 of file qgsmapcanvas.cpp.
References getCoordinateTransform(), mapSettings(), mWheelZoomFactor, refresh(), QgsRectangle::scale(), setExtent(), QgsMapToPixel::toMapPoint(), and QgsMapSettings::visibleExtent().
Referenced by QgsMapToolTouch::canvasDoubleClickEvent(), QgsMapToolZoom::canvasReleaseEvent(), and wheelEvent().
Member Data Documentation
QgsMapRendererCache* QgsMapCanvas::mCache private
Optionally use cache with rendered map layers for the current map settings.
Definition at line 625 of file qgsmapcanvas.h.
Referenced by clearCache(), isCachingEnabled(), refreshMap(), setCachingEnabled(), and ~QgsMapCanvas().
std::auto_ptr<CanvasProperties> QgsMapCanvas::mCanvasProperties protected
Handle pattern for implementation object.
Definition at line 540 of file qgsmapcanvas.h.
Referenced by keyPressEvent(), keyReleaseEvent(), mouseLastXY(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveCanvasContents(), and panActionEnd().
QgsMapLayer* QgsMapCanvas::mCurrentLayer private
current layer in legend
Definition at line 585 of file qgsmapcanvas.h.
Referenced by currentLayer(), mouseReleaseEvent(), panToSelected(), QgsMapCanvas(), setCurrentLayer(), and zoomToSelected().
bool QgsMapCanvas::mDrawRenderingStats private
Whether to add rendering stats to the rendered image.
Definition at line 622 of file qgsmapcanvas.h.
Referenced by keyPressEvent(), and rendererJobFinished().
bool QgsMapCanvas::mFrozen private
Flag indicating if the map canvas is frozen.
Definition at line 576 of file qgsmapcanvas.h.
Referenced by freeze(), isFrozen(), QgsMapCanvas(), and refresh().
QgsMapRendererQImageJob* QgsMapCanvas::mJob private
Job that takes care of map rendering in background.
Definition at line 610 of file qgsmapcanvas.h.
Referenced by isDrawing(), mapUpdateTimeout(), refreshMap(), rendererJobFinished(), stopRendering(), and ~QgsMapCanvas().
bool QgsMapCanvas::mJobCancelled private
Flag determining whether the active job has been cancelled.
Definition at line 613 of file qgsmapcanvas.h.
Referenced by refreshMap(), rendererJobFinished(), and stopRendering().
QgsLabelingResults* QgsMapCanvas::mLabelingResults private
Labeling results from the recently rendered map.
Definition at line 616 of file qgsmapcanvas.h.
Referenced by labelingResults(), rendererJobFinished(), and ~QgsMapCanvas().
QList<QgsRectangle> QgsMapCanvas::mLastExtent private
recently used extent
Definition at line 597 of file qgsmapcanvas.h.
Referenced by clearExtentHistory(), setExtent(), zoomToNextExtent(), and zoomToPreviousExtent().
int QgsMapCanvas::mLastExtentIndex private
Definition at line 598 of file qgsmapcanvas.h.
Referenced by clearExtentHistory(), QgsMapCanvas(), setExtent(), zoomToNextExtent(), and zoomToPreviousExtent().
QgsMapTool* QgsMapCanvas::mLastNonZoomMapTool private
previous tool if current is for zooming/panning
Definition at line 594 of file qgsmapcanvas.h.
Referenced by mouseReleaseEvent(), QgsMapCanvas(), setMapTool(), unsetMapTool(), and ~QgsMapCanvas().
QgsMapCanvasMap* QgsMapCanvas::mMap private
owns pixmap with rendered map and controls rendering
Definition at line 570 of file qgsmapcanvas.h.
Referenced by canvasPaintDevice(), map(), mapUpdateTimeout(), QgsMapCanvas(), rendererJobFinished(), and saveAsImage().
QgsMapOverviewCanvas* QgsMapCanvas::mMapOverview private
map overview widget - it's controlled by QgsMapCanvas
Definition at line 573 of file qgsmapcanvas.h.
Referenced by enableAntiAliasing(), enableOverviewMode(), QgsMapCanvas(), setLayerSet(), and updateOverview().
QgsMapRenderer* QgsMapCanvas::mMapRenderer private
all map rendering is done in this class
Definition at line 567 of file qgsmapcanvas.h.
Referenced by getDatumTransformInfo(), mapRenderer(), QgsMapCanvas(), resizeEvent(), and ~QgsMapCanvas().
QgsMapTool* QgsMapCanvas::mMapTool private
pointer to current map tool
Definition at line 591 of file qgsmapcanvas.h.
Referenced by keyPressEvent(), keyReleaseEvent(), mapTool(), mapToolDestroyed(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), QgsMapCanvas(), setMapTool(), unsetMapTool(), wheelEvent(), and ~QgsMapCanvas().
QTimer QgsMapCanvas::mMapUpdateTimer private
Timer that periodically fires while map rendering is in progress to update the visible map.
Definition at line 607 of file qgsmapcanvas.h.
Referenced by mapUpdateInterval(), QgsMapCanvas(), refreshMap(), rendererJobFinished(), and setMapUpdateInterval().
QgsPreviewEffect* QgsMapCanvas::mPreviewEffect private
Definition at line 629 of file qgsmapcanvas.h.
Referenced by previewMode(), previewModeEnabled(), QgsMapCanvas(), setPreviewMode(), and setPreviewModeEnabled().
bool QgsMapCanvas::mRefreshScheduled private
Flag that allows squashing multiple refresh() calls into just one delayed rendering job.
Definition at line 579 of file qgsmapcanvas.h.
Referenced by QgsMapCanvas(), refresh(), and refreshMap().
bool QgsMapCanvas::mRenderFlag private
determines whether user has requested to suppress rendering
Definition at line 582 of file qgsmapcanvas.h.
Referenced by QgsMapCanvas(), refresh(), and setRenderFlag().
QTimer* QgsMapCanvas::mResizeTimer private
Definition at line 627 of file qgsmapcanvas.h.
Referenced by QgsMapCanvas(), and resizeEvent().
QGraphicsScene* QgsMapCanvas::mScene private
graphics scene manages canvas items
Definition at line 588 of file qgsmapcanvas.h.
Referenced by canvasColor(), QgsMapCanvas(), resizeEvent(), setCanvasColor(), updateCanvasItemPositions(), and ~QgsMapCanvas().
QgsMapSettings QgsMapCanvas::mSettings private
encompases all map settings necessary for map rendering
Definition at line 564 of file qgsmapcanvas.h.
Referenced by enableAntiAliasing(), getDatumTransformInfo(), mapSettings(), mapUpdateTimeout(), QgsMapCanvas(), readProject(), refresh(), refreshMap(), rendererJobFinished(), resizeEvent(), saveAsImage(), setCanvasColor(), setCrsTransformEnabled(), setDestinationCrs(), setExtent(), setLayerSet(), setMapUnits(), setSelectionColor(), updateDatumTransformEntries(), writeProject(), zoomToNextExtent(), and zoomToPreviousExtent().
bool QgsMapCanvas::mUseParallelRendering private
Whether layers are rendered sequentially or in parallel.
Definition at line 619 of file qgsmapcanvas.h.
Referenced by isParallelRenderingEnabled(), keyPressEvent(), refreshMap(), rendererJobFinished(), and setParallelRenderingEnabled().
WheelAction QgsMapCanvas::mWheelAction private
Mouse wheel action.
Definition at line 604 of file qgsmapcanvas.h.
Referenced by setWheelAction(), and wheelEvent().
double QgsMapCanvas::mWheelZoomFactor private
Scale factor multiple for default zoom in/out.
Definition at line 601 of file qgsmapcanvas.h.
Referenced by setWheelAction(), wheelEvent(), zoomIn(), zoomOut(), and zoomWithCenter().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmapcanvas.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmapcanvas.cpp