QGIS API Documentation: QgsComposerGroupItem Class Reference
QgsComposerGroupItem Class Reference
#include <qgscomposerlegenditem.h>
Public Member Functions
QgsComposerGroupItem ()
QgsComposerGroupItem (const QString &text)
virtual ~QgsComposerGroupItem ()
virtual QStandardItem * clone () const
virtual void writeXML (QDomElement &elem, QDomDocument &doc) const
virtual void readXML (const QDomElement &itemElem, bool xServerAvailable=true)
Read item content from xml.
ItemType itemType () const
Public Member Functions inherited from QgsComposerLegendItem
QgsComposerLegendItem (QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
QgsComposerLegendItem (const QString &text, QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
QgsComposerLegendItem (const QIcon &icon, const QString &text, QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
virtual ~QgsComposerLegendItem ()
QgsComposerLegendStyle::Style style () const
void setStyle (QgsComposerLegendStyle::Style style)
virtual QString userText () const
virtual void setUserText (const QString &text)
Additional Inherited Members
Public Types inherited from QgsComposerLegendItem
enum ItemType {
GroupItem = QStandardItem::UserType, LayerItem, SymbologyV2Item, RasterSymbolItem,
StyleItem
}
Protected Member Functions inherited from QgsComposerLegendItem
void writeXMLChildren (QDomElement &elem, QDomDocument &doc) const
Protected Attributes inherited from QgsComposerLegendItem
QgsComposerLegendStyle::Style mStyle
QString mUserText
Detailed Description
Definition at line 149 of file qgscomposerlegenditem.h.
Constructor & Destructor Documentation
QgsComposerGroupItem::QgsComposerGroupItem ()
Definition at line 314 of file qgscomposerlegenditem.cpp.
Referenced by clone(), and readXML().
QgsComposerGroupItem::QgsComposerGroupItem (const QString & text)
Definition at line 318 of file qgscomposerlegenditem.cpp.
QgsComposerGroupItem::~QgsComposerGroupItem () virtual
Definition at line 322 of file qgscomposerlegenditem.cpp.
Member Function Documentation
QStandardItem * QgsComposerGroupItem::clone () const virtual
Implements QgsComposerLegendItem.
Definition at line 326 of file qgscomposerlegenditem.cpp.
References QgsComposerGroupItem().
ItemType QgsComposerGroupItem::itemType () const inline virtual
Implements QgsComposerLegendItem.
Definition at line 160 of file qgscomposerlegenditem.h.
References QgsComposerLegendItem::GroupItem.
void QgsComposerGroupItem::readXML (const QDomElement & itemElem, bool xServerAvailable = true) virtual
Read item content from xml.
Parameters
itemElem item to read from
xServerAvailable Read item icons if true (QIcon needs x-server)
Implements QgsComposerLegendItem.
Definition at line 344 of file qgscomposerlegenditem.cpp.
References QgsComposerGroupItem(), QgsComposerLegendItem::readXML(), QgsComposerLegendItem::setStyle(), QgsComposerLegendItem::setUserText(), QgsComposerLegendStyle::styleFromName(), and QgsComposerLegendItem::userText().
void QgsComposerGroupItem::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
Implements QgsComposerLegendItem.
Definition at line 333 of file qgscomposerlegenditem.cpp.
References QgsComposerLegendItem::mStyle, QgsComposerLegendStyle::styleName(), QgsComposerLegendItem::userText(), and QgsComposerLegendItem::writeXMLChildren().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerlegenditem.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerlegenditem.cpp