QGIS API Documentation: QgsMapRendererParallelJob Class Reference
QgsMapRendererParallelJob Class Reference
Job implementation that renders all layers in parallel.
#include <qgsmaprendererparalleljob.h>
Public Member Functions
QgsMapRendererParallelJob (const QgsMapSettings &settings)
~QgsMapRendererParallelJob ()
virtual void start ()
Start the rendering job and immediately return.
virtual void cancel ()
Stop the rendering job - does not return until the job has terminated.
virtual void waitForFinished ()
Block until the job has finished.
virtual bool isActive () const
Tell whether the rendering job is currently running in background.
virtual QgsLabelingResults * takeLabelingResults ()
Get pointer to internal labeling engine (in order to get access to the results)
virtual QImage renderedImage ()
Get a preview/resulting image.
Public Member Functions inherited from QgsMapRendererQImageJob
QgsMapRendererQImageJob (const QgsMapSettings &settings)
Public Member Functions inherited from QgsMapRendererJob
QgsMapRendererJob (const QgsMapSettings &settings)
virtual ~QgsMapRendererJob ()
Errors errors () const
List of errors that happened during the rendering job - available when the rendering has been finished.
void setCache (QgsMapRendererCache *cache)
Assign a cache to be used for reading and storing rendered images of individual layers.
void setRequestedGeometryCacheForLayers (const QStringList &layerIds)
Set which vector layers should be cached while rendering.
int renderingTime () const
Find out how log it took to finish the job (in miliseconds)
Protected Types
enum { Idle, RenderingLayers, RenderingLabels }
Protected Slots
void renderLayersFinished ()
layers are rendered, labeling is still pending
void renderingFinished ()
all rendering is finished, including labeling
Static Protected Member Functions
static void renderLayerStatic (LayerRenderJob &job)
static void renderLabelsStatic (QgsMapRendererParallelJob *self)
Static Protected Member Functions inherited from QgsMapRendererJob
static bool reprojectToLayerExtent (const QgsCoordinateTransform *ct, bool layerCrsGeographic, QgsRectangle &extent, QgsRectangle &r2)
Convenience function to project an extent into the layer source CRS, but also split it into two extents if it crosses the +/- 180 degree line.
static QImage composeImage (const QgsMapSettings &settings, const LayerRenderJobs &jobs)
static void drawLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext, QgsPalLabeling *labelingEngine, QPainter *painter)
static void drawOldLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext)
static void drawNewLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext, QgsPalLabeling *labelingEngine)
Protected Attributes
QImage mFinalImage
enum
QgsMapRendererParallelJob:: { ... } mStatus
QFuture< void > mFuture
QFutureWatcher< void > mFutureWatcher
LayerRenderJobs mLayerJobs
QgsPalLabeling * mLabelingEngine
QgsRenderContext mLabelingRenderContext
QFuture< void > mLabelingFuture
QFutureWatcher< void > mLabelingFutureWatcher
Protected Attributes inherited from QgsMapRendererJob
QgsMapSettings mSettings
Errors mErrors
QgsMapRendererCache * mCache
QStringList mRequestedGeomCacheForLayers
list of layer IDs for which the geometry cache should be updated
QMap< QString, QgsGeometryCache > mGeometryCaches
map of geometry caches
QTime mRenderingStart
int mRenderingTime
Additional Inherited Members
Public Types inherited from QgsMapRendererJob
typedef QList< Error > Errors
Signals inherited from QgsMapRendererJob
void finished ()
emitted when asynchronous rendering is finished (or canceled).
Protected Member Functions inherited from QgsMapRendererJob
LayerRenderJobs prepareJobs (QPainter *painter, QgsPalLabeling *labelingEngine)
void cleanupJobs (LayerRenderJobs &jobs)
bool needTemporaryImage (QgsMapLayer *ml)
void updateLayerGeometryCaches ()
called when rendering has finished to update all layers' geometry caches
Detailed Description
Job implementation that renders all layers in parallel.
The resulting map image can be retrieved with renderedImage() function. It is safe to call that function while rendering is active to see preview of the map.
Note
added in 2.4
Definition at line 28 of file qgsmaprendererparalleljob.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
Idle
RenderingLayers
RenderingLabels
Definition at line 60 of file qgsmaprendererparalleljob.h.
Constructor & Destructor Documentation
QgsMapRendererParallelJob::QgsMapRendererParallelJob (const QgsMapSettings & settings)
Definition at line 23 of file qgsmaprendererparalleljob.cpp.
QgsMapRendererParallelJob::~QgsMapRendererParallelJob ()
Definition at line 30 of file qgsmaprendererparalleljob.cpp.
References cancel(), isActive(), and mLabelingEngine.
Member Function Documentation
void QgsMapRendererParallelJob::cancel () virtual
Stop the rendering job - does not return until the job has terminated.
Does nothing if the rendering is not active.
Implements QgsMapRendererJob.
Definition at line 73 of file qgsmaprendererparalleljob.cpp.
References QgsMapRendererJob::finished(), Idle, isActive(), mFutureWatcher, mLabelingFutureWatcher, mLabelingRenderContext, mLayerJobs, mStatus, QgsDebugMsg, renderingFinished(), RenderingLabels, RenderingLayers, renderLayersFinished(), and QgsRenderContext::setRenderingStopped().
Referenced by ~QgsMapRendererParallelJob().
bool QgsMapRendererParallelJob::isActive () const virtual
Tell whether the rendering job is currently running in background.
Implements QgsMapRendererJob.
Definition at line 143 of file qgsmaprendererparalleljob.cpp.
References Idle, and mStatus.
Referenced by cancel(), start(), waitForFinished(), and ~QgsMapRendererParallelJob().
QImage QgsMapRendererParallelJob::renderedImage () virtual
Get a preview/resulting image.
Implements QgsMapRendererQImageJob.
Definition at line 153 of file qgsmaprendererparalleljob.cpp.
References QgsMapRendererJob::composeImage(), mFinalImage, mLayerJobs, QgsMapRendererJob::mSettings, mStatus, and RenderingLayers.
void QgsMapRendererParallelJob::renderingFinished () protected slot
all rendering is finished, including labeling
Definition at line 188 of file qgsmaprendererparalleljob.cpp.
References QgsMapRendererJob::finished(), Idle, QgsMapRendererJob::mRenderingStart, QgsMapRendererJob::mRenderingTime, mStatus, and QgsDebugMsg.
Referenced by cancel(), renderLayersFinished(), and waitForFinished().
void QgsMapRendererParallelJob::renderLabelsStatic (QgsMapRendererParallelJob * self) static protected
Definition at line 234 of file qgsmaprendererparalleljob.cpp.
References QgsMapRendererJob::drawLabeling(), QgsDebugMsg, and QgsException::what().
Referenced by renderLayersFinished().
void QgsMapRendererParallelJob::renderLayersFinished () protected slot
layers are rendered, labeling is still pending
Definition at line 161 of file qgsmaprendererparalleljob.cpp.
References QgsMapRendererJob::cleanupJobs(), QgsMapRendererJob::composeImage(), QgsMapSettings::DrawLabeling, QgsMapRendererJob::finished(), mFinalImage, mLabelingFuture, mLabelingFutureWatcher, mLabelingRenderContext, mLayerJobs, QgsMapRendererJob::mSettings, mStatus, QgsDebugMsg, renderingFinished(), RenderingLabels, RenderingLayers, QgsRenderContext::renderingStopped(), renderLabelsStatic(), and QgsMapSettings::testFlag().
Referenced by cancel(), start(), and waitForFinished().
void QgsMapRendererParallelJob::renderLayerStatic (LayerRenderJob & job) static protected
Definition at line 199 of file qgsmaprendererparalleljob.cpp.
References LayerRenderJob::cached, LayerRenderJob::context, QgsDebugMsg, QgsRenderContext::renderingStopped(), and QgsException::what().
Referenced by start().
void QgsMapRendererParallelJob::start () virtual
Start the rendering job and immediately return.
Does nothing if the rendering is already in progress.
Implements QgsMapRendererJob.
Definition at line 41 of file qgsmaprendererparalleljob.cpp.
References QgsMapSettings::DrawLabeling, QgsMapRendererJob::finished(), QgsPalLabeling::init(), isActive(), QgsPalLabeling::loadEngineSettings(), mFuture, mFutureWatcher, mLabelingEngine, mLayerJobs, QgsMapRendererJob::mRenderingStart, QgsMapRendererJob::mSettings, mStatus, QgsMapRendererJob::prepareJobs(), QgsDebugMsg, RenderingLayers, renderLayersFinished(), renderLayerStatic(), and QgsMapSettings::testFlag().
QgsLabelingResults * QgsMapRendererParallelJob::takeLabelingResults () virtual
Get pointer to internal labeling engine (in order to get access to the results)
Implements QgsMapRendererJob.
Definition at line 148 of file qgsmaprendererparalleljob.cpp.
References mLabelingEngine, and QgsPalLabeling::takeResults().
void QgsMapRendererParallelJob::waitForFinished () virtual
Block until the job has finished.
Implements QgsMapRendererJob.
Definition at line 107 of file qgsmaprendererparalleljob.cpp.
References QgsMapRendererJob::finished(), Idle, isActive(), mFutureWatcher, mLabelingFutureWatcher, mStatus, QgsDebugMsg, renderingFinished(), RenderingLabels, RenderingLayers, and renderLayersFinished().
Member Data Documentation
QImage QgsMapRendererParallelJob::mFinalImage protected
Definition at line 58 of file qgsmaprendererparalleljob.h.
Referenced by renderedImage(), and renderLayersFinished().
QFuture<void> QgsMapRendererParallelJob::mFuture protected
Definition at line 62 of file qgsmaprendererparalleljob.h.
Referenced by start().
QFutureWatcher<void> QgsMapRendererParallelJob::mFutureWatcher protected
Definition at line 63 of file qgsmaprendererparalleljob.h.
Referenced by cancel(), start(), and waitForFinished().
QgsPalLabeling* QgsMapRendererParallelJob::mLabelingEngine protected
Definition at line 67 of file qgsmaprendererparalleljob.h.
Referenced by start(), takeLabelingResults(), and ~QgsMapRendererParallelJob().
QFuture<void> QgsMapRendererParallelJob::mLabelingFuture protected
Definition at line 69 of file qgsmaprendererparalleljob.h.
Referenced by renderLayersFinished().
QFutureWatcher<void> QgsMapRendererParallelJob::mLabelingFutureWatcher protected
Definition at line 70 of file qgsmaprendererparalleljob.h.
Referenced by cancel(), renderLayersFinished(), and waitForFinished().
QgsRenderContext QgsMapRendererParallelJob::mLabelingRenderContext protected
Definition at line 68 of file qgsmaprendererparalleljob.h.
Referenced by cancel(), and renderLayersFinished().
LayerRenderJobs QgsMapRendererParallelJob::mLayerJobs protected
Definition at line 65 of file qgsmaprendererparalleljob.h.
Referenced by cancel(), renderedImage(), renderLayersFinished(), and start().
enum { ... } QgsMapRendererParallelJob::mStatus
Referenced by cancel(), isActive(), renderedImage(), renderingFinished(), renderLayersFinished(), start(), and waitForFinished().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsmaprendererparalleljob.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsmaprendererparalleljob.cpp