QGIS API Documentation: QgsMapToolTouch Class Reference
QgsMapToolTouch Class Reference
QGIS gui library.
A map tool for panning the map.
#include <qgsmaptooltouch.h>
Public Member Functions
QgsMapToolTouch (QgsMapCanvas *canvas)
constructor
~QgsMapToolTouch ()
void activate ()
called when set as currently active map tool
void deactivate ()
called when map tool is being deactivated
virtual void canvasMoveEvent (QMouseEvent *e)
Overridden mouse move event.
virtual void canvasReleaseEvent (QMouseEvent *e)
Overridden mouse release event.
virtual void canvasDoubleClickEvent (QMouseEvent *e)
Overridden Mouse double click event.
virtual bool isTransient ()
Check whether this MapTool performs a zoom or pan operation.
bool gestureEvent (QGestureEvent *event)
Public Member Functions inherited from QgsMapTool
virtual ~QgsMapTool ()
virtual destructor
virtual void canvasPressEvent (QMouseEvent *e)
Mouse press event for overriding. Default implementation does nothing.
virtual void wheelEvent (QWheelEvent *e)
Mouse wheel event for overriding.
virtual void keyPressEvent (QKeyEvent *e)
Key event for overriding. Default implementation does nothing.
virtual void keyReleaseEvent (QKeyEvent *e)
Key event for overriding.
virtual Q_DECL_DEPRECATED void renderComplete ()
Called when rendering has finished.
void setAction (QAction *action)
Use this to associate a QAction to this maptool.
QAction * action ()
Return associated action with map tool or NULL if no action is associated.
void setButton (QAbstractButton *button)
Use this to associate a button to this maptool.
QAbstractButton * button ()
Return associated button with map tool or NULL if no button is associated.
virtual void setCursor (QCursor cursor)
Set a user defined cursor.
virtual bool isEditTool ()
Check whether this MapTool performs an edit operation.
QgsMapCanvas * canvas ()
returns pointer to the tool's map canvas
QString toolName ()
Emit map tool changed with the old tool.
Private Member Functions
void pinchTriggered (QPinchGesture *gesture)
Private Attributes
bool mDragging
Flag to indicate a map canvas drag operation is taking place.
bool mPinching
Flag to indicate a pinch gesture is taking place.
Additional Inherited Members
Signals inherited from QgsMapTool
void messageEmitted (QString message, QgsMessageBar::MessageLevel=QgsMessageBar::INFO)
emit a message
void messageDiscarded ()
emit signal to clear previous message
Static Public Member Functions inherited from QgsMapTool
static double searchRadiusMM ()
Get search radius in mm.
static double searchRadiusMU (const QgsRenderContext &context)
Get search radius in map units for given context.
static double searchRadiusMU (QgsMapCanvas *canvas)
Get search radius in map units for given canvas.
Protected Member Functions inherited from QgsMapTool
QgsMapTool (QgsMapCanvas *canvas)
constructor takes map canvas as a parameter
QgsPoint toMapCoordinates (const QPoint &point)
transformation from screen coordinates to map coordinates
QgsPoint toLayerCoordinates (QgsMapLayer *layer, const QPoint &point)
transformation from screen coordinates to layer's coordinates
QgsPoint toLayerCoordinates (QgsMapLayer *layer, const QgsPoint &point)
transformation from map coordinates to layer's coordinates
QgsPoint toMapCoordinates (QgsMapLayer *layer, const QgsPoint &point)
transformation from layer's coordinates to map coordinates (which is different in case reprojection is used)
QgsRectangle toLayerCoordinates (QgsMapLayer *layer, const QgsRectangle &rect)
trnasformation of the rect from map coordinates to layer's coordinates
QPoint toCanvasCoordinates (const QgsPoint &point)
transformation from map coordinates to screen coordinates
Protected Attributes inherited from QgsMapTool
QgsMapCanvas * mCanvas
pointer to map canvas
QCursor mCursor
cursor used in map tool
QAction * mAction
optionally map tool can have pointer to action which will be used to set that action as active
QAbstractButton * mButton
optionally map tool can have pointer to a button which will be used to set that action as active
QString mToolName
translated name of the map tool
Detailed Description
A map tool for panning the map.
See also
QgsMapTool
Definition at line 30 of file qgsmaptooltouch.h.
Constructor & Destructor Documentation
QgsMapToolTouch::QgsMapToolTouch (QgsMapCanvas * canvas)
constructor
Definition at line 26 of file qgsmaptooltouch.cpp.
QgsMapToolTouch::~QgsMapToolTouch ()
Definition at line 35 of file qgsmaptooltouch.cpp.
References QgsMapTool::mCanvas.
Member Function Documentation
void QgsMapToolTouch::activate () virtual
called when set as currently active map tool
Reimplemented from QgsMapTool.
Definition at line 40 of file qgsmaptooltouch.cpp.
References QgsMapTool::activate(), and QgsMapTool::mCanvas.
void QgsMapToolTouch::canvasDoubleClickEvent (QMouseEvent * e) virtual
Overridden Mouse double click event.
Reimplemented from QgsMapTool.
Definition at line 87 of file qgsmaptooltouch.cpp.
References QgsMapTool::mCanvas, mPinching, and QgsMapCanvas::zoomWithCenter().
void QgsMapToolTouch::canvasMoveEvent (QMouseEvent * e) virtual
Overridden mouse move event.
Reimplemented from QgsMapTool.
Definition at line 52 of file qgsmaptooltouch.cpp.
References QgsMapTool::mCanvas, mDragging, mPinching, and QgsMapCanvas::panAction().
void QgsMapToolTouch::canvasReleaseEvent (QMouseEvent * e) virtual
Overridden mouse release event.
Reimplemented from QgsMapTool.
Definition at line 65 of file qgsmaptooltouch.cpp.
References QgsMapCanvas::getCoordinateTransform(), QgsMapTool::mCanvas, mDragging, mPinching, QgsMapCanvas::panActionEnd(), QgsMapCanvas::refresh(), QgsMapCanvas::setExtent(), and QgsMapToPixel::toMapPoint().
void QgsMapToolTouch::deactivate () virtual
called when map tool is being deactivated
Reimplemented from QgsMapTool.
Definition at line 46 of file qgsmaptooltouch.cpp.
References QgsMapTool::deactivate(), and QgsMapTool::mCanvas.
bool QgsMapToolTouch::gestureEvent (QGestureEvent * event)
Definition at line 95 of file qgsmaptooltouch.cpp.
References mPinching, and pinchTriggered().
virtual bool QgsMapToolTouch::isTransient () inline virtual
Check whether this MapTool performs a zoom or pan operation.
If it does, we will be able to perform the zoom and then resume operations with the original / previously used tool.
Reimplemented from QgsMapTool.
Definition at line 50 of file qgsmaptooltouch.h.
void QgsMapToolTouch::pinchTriggered (QPinchGesture * gesture) private
Definition at line 107 of file qgsmaptooltouch.cpp.
References QgsMapCanvas::extent(), QgsMapCanvas::getCoordinateTransform(), QgsMapTool::mCanvas, mPinching, QgsMapCanvas::refresh(), QgsRectangle::scale(), QgsMapCanvas::setExtent(), QgsMapToPixel::toMapPoint(), and QgsMapCanvas::zoomOut().
Referenced by gestureEvent().
Member Data Documentation
bool QgsMapToolTouch::mDragging private
Flag to indicate a map canvas drag operation is taking place.
Definition at line 57 of file qgsmaptooltouch.h.
Referenced by canvasMoveEvent(), and canvasReleaseEvent().
bool QgsMapToolTouch::mPinching private
Flag to indicate a pinch gesture is taking place.
Definition at line 59 of file qgsmaptooltouch.h.
Referenced by canvasDoubleClickEvent(), canvasMoveEvent(), canvasReleaseEvent(), gestureEvent(), and pinchTriggered().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaptooltouch.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaptooltouch.cpp