QGIS API Documentation: GEOSException Class Reference
GEOSException Class Reference
Public Member Functions
GEOSException (QString theMsg)
GEOSException (const GEOSException &rhs)
~GEOSException ()
QString what ()
Private Attributes
QString msg
Static Private Attributes
static QString lastMsg
Detailed Description
Definition at line 50 of file qgsgeometry.cpp.
Constructor & Destructor Documentation
GEOSException::GEOSException (QString theMsg) inline
Definition at line 53 of file qgsgeometry.cpp.
References lastMsg, and msg.
GEOSException::GEOSException (const GEOSException & rhs) inline
Definition at line 67 of file qgsgeometry.cpp.
GEOSException::~GEOSException () inline
Definition at line 72 of file qgsgeometry.cpp.
References lastMsg, and msg.
Member Function Documentation
QString GEOSException::what () inline
Definition at line 78 of file qgsgeometry.cpp.
References msg.
Referenced by QgsGeometry::addPart(), QgsGeometry::addRing(), QgsGeometry::avoidIntersections(), QgsGeometry::closestVertexWithContext(), QgsGeometry::contains(), createGeosCollection(), createGeosCoordSequence(), createGeosLinearRing(), createGeosLineString(), createGeosPolygon(), QgsGeometry::fromMultiPoint(), QgsGeometry::fromMultiPolygon(), QgsGeometry::fromMultiPolyline(), QgsGeometry::fromWkt(), QgsGeometry::isGeosEmpty(), QgsGeometry::isGeosValid(), QgsGeometry::reshapeLine(), and QgsGeometry::reshapePolygon().
Member Data Documentation
QString GEOSException::lastMsg static private
Definition at line 85 of file qgsgeometry.cpp.
Referenced by GEOSException(), and ~GEOSException().
QString GEOSException::msg private
Definition at line 84 of file qgsgeometry.cpp.
Referenced by GEOSException(), what(), and ~GEOSException().
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsgeometry.cpp