QGIS API Documentation: QgsMessageLogViewer Class Reference
QgsMessageLogViewer Class Reference
QGIS gui library.
A generic message for displaying QGIS log messages.
#include <qgsmessagelogviewer.h>
Public Slots
void logMessage (QString message, QString tag, QgsMessageLog::MessageLevel level)
Public Member Functions
QgsMessageLogViewer (QStatusBar *statusBar=0, QWidget *parent=0, Qt::WindowFlags fl=QgisGui::ModalDialogFlags)
~QgsMessageLogViewer ()
void setShowToolTips (bool enabled)
bool showToolTips () const
Protected Member Functions
void showEvent (QShowEvent *)
void hideEvent (QHideEvent *)
Private Slots
void closeTab (int index)
void buttonToggled (bool checked)
void buttonDestroyed ()
Private Attributes
QToolButton * mButton
int mCount
bool mShowToolTips
Detailed Description
A generic message for displaying QGIS log messages.
Note
added in 1.8
Definition at line 35 of file qgsmessagelogviewer.h.
Constructor & Destructor Documentation
QgsMessageLogViewer::QgsMessageLogViewer (QStatusBar * statusBar = 0, QWidget * parent = 0, Qt::WindowFlags fl = QgisGui::ModalDialogFlags)
Definition at line 42 of file qgsmessagelogviewer.cpp.
References buttonDestroyed(), buttonToggled(), closeTab(), icon(), QgsMessageLog::instance(), logMessage(), mButton, and tr.
QgsMessageLogViewer::~QgsMessageLogViewer ()
Definition at line 73 of file qgsmessagelogviewer.cpp.
Member Function Documentation
void QgsMessageLogViewer::buttonDestroyed () private slot
Definition at line 107 of file qgsmessagelogviewer.cpp.
References mButton.
Referenced by QgsMessageLogViewer().
void QgsMessageLogViewer::buttonToggled (bool checked) private slot
Definition at line 94 of file qgsmessagelogviewer.cpp.
Referenced by QgsMessageLogViewer().
void QgsMessageLogViewer::closeTab (int index) private slot
Definition at line 168 of file qgsmessagelogviewer.cpp.
References mButton, mCount, and tr.
Referenced by QgsMessageLogViewer().
void QgsMessageLogViewer::hideEvent (QHideEvent *) protected
Definition at line 77 of file qgsmessagelogviewer.cpp.
References mButton.
void QgsMessageLogViewer::logMessage (QString message, QString tag, QgsMessageLog::MessageLevel level) slot
Definition at line 112 of file qgsmessagelogviewer.cpp.
References QgsMessageLog::INFO, mButton, mCount, mShowToolTips, and tr.
Referenced by QgsMessageLogViewer().
void QgsMessageLogViewer::setShowToolTips (bool enabled) inline
Note
added in 2.4
Definition at line 43 of file qgsmessagelogviewer.h.
void QgsMessageLogViewer::showEvent (QShowEvent *) protected
Definition at line 85 of file qgsmessagelogviewer.cpp.
References mButton.
bool QgsMessageLogViewer::showToolTips () const inline
Note
added in 2.4
Definition at line 45 of file qgsmessagelogviewer.h.
Member Data Documentation
QToolButton* QgsMessageLogViewer::mButton private
Definition at line 55 of file qgsmessagelogviewer.h.
Referenced by buttonDestroyed(), closeTab(), hideEvent(), logMessage(), QgsMessageLogViewer(), and showEvent().
int QgsMessageLogViewer::mCount private
Definition at line 56 of file qgsmessagelogviewer.h.
Referenced by closeTab(), and logMessage().
bool QgsMessageLogViewer::mShowToolTips private
Definition at line 57 of file qgsmessagelogviewer.h.
Referenced by logMessage().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmessagelogviewer.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmessagelogviewer.cpp