QGIS API Documentation: QgsGPSDetector Class Reference
QgsGPSDetector Class Reference
#include <qgsgpsdetector.h>
Public Slots
void advance ()
void detected (const QgsGPSInformation &)
void connDestroyed (QObject *)
Signals
void detected (QgsGPSConnection *)
void detectionFailed ()
Public Member Functions
QgsGPSDetector (QString portName)
~QgsGPSDetector ()
Static Public Member Functions
static QList< QPair< QString,
QString > > availablePorts ()
Private Attributes
int mPortIndex
int mBaudIndex
QList< QPair< QString, QString > > mPortList
QList< BaudRateType > mBaudList
QgsGPSConnection * mConn
Detailed Description
Definition at line 31 of file qgsgpsdetector.h.
Constructor & Destructor Documentation
QgsGPSDetector::QgsGPSDetector (QString portName)
Definition at line 97 of file qgsgpsdetector.cpp.
References availablePorts(), mBaudIndex, mBaudList, mConn, mPortIndex, and mPortList.
QgsGPSDetector::~QgsGPSDetector ()
Definition at line 115 of file qgsgpsdetector.cpp.
References mConn.
Member Function Documentation
void QgsGPSDetector::advance () slot
Definition at line 121 of file qgsgpsdetector.cpp.
References connDestroyed(), detected(), detectionFailed(), mBaudIndex, mBaudList, mConn, mPortIndex, and mPortList.
Referenced by detected().
QList< QPair< QString, QString > > QgsGPSDetector::availablePorts () static
Definition at line 33 of file qgsgpsdetector.cpp.
References tr.
Referenced by QgsGPSDetector().
void QgsGPSDetector::connDestroyed (QObject * obj) slot
Definition at line 212 of file qgsgpsdetector.cpp.
References mConn.
Referenced by advance().
void QgsGPSDetector::detected (const QgsGPSInformation & info) slot
Definition at line 193 of file qgsgpsdetector.cpp.
References advance(), QgsGPSConnection::GPSDataReceived, mConn, and QgsGPSConnection::status().
Referenced by advance().
void QgsGPSDetector::detected (QgsGPSConnection *) signal
void QgsGPSDetector::detectionFailed () signal
Referenced by advance().
Member Data Documentation
int QgsGPSDetector::mBaudIndex private
Definition at line 51 of file qgsgpsdetector.h.
Referenced by advance(), and QgsGPSDetector().
QList<BaudRateType> QgsGPSDetector::mBaudList private
Definition at line 53 of file qgsgpsdetector.h.
Referenced by advance(), and QgsGPSDetector().
QgsGPSConnection* QgsGPSDetector::mConn private
Definition at line 55 of file qgsgpsdetector.h.
Referenced by advance(), connDestroyed(), detected(), QgsGPSDetector(), and ~QgsGPSDetector().
int QgsGPSDetector::mPortIndex private
Definition at line 50 of file qgsgpsdetector.h.
Referenced by advance(), and QgsGPSDetector().
QList< QPair< QString, QString > > QgsGPSDetector::mPortList private
Definition at line 52 of file qgsgpsdetector.h.
Referenced by advance(), and QgsGPSDetector().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/gps/qgsgpsdetector.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/gps/qgsgpsdetector.cpp