QGIS API Documentation: QgsExpression::NodeInOperator Class Reference
QgsExpression::NodeInOperator Class Reference
#include <qgsexpression.h>
Public Member Functions
NodeInOperator (Node *node, NodeList *list, bool notin=false)
virtual ~NodeInOperator ()
Node * node () const
bool isNotIn () const
NodeList * list () const
virtual NodeType nodeType () const
virtual bool prepare (QgsExpression *parent, const QgsFields &fields)
virtual QVariant eval (QgsExpression *parent, const QgsFeature *f)
virtual QString dump () const
virtual QStringList referencedColumns () const
virtual bool needsGeometry () const
virtual void accept (Visitor &v) const
Public Member Functions inherited from QgsExpression::Node
virtual ~Node ()
Protected Attributes
Node * mNode
NodeList * mList
bool mNotIn
Detailed Description
Definition at line 460 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::NodeInOperator::NodeInOperator (Node * node, NodeList * list, bool notin = false) inline
Definition at line 463 of file qgsexpression.h.
virtual QgsExpression::NodeInOperator::~NodeInOperator () inline virtual
Definition at line 464 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::NodeInOperator::accept (Visitor & v) const inline virtual
Implements QgsExpression::Node.
Definition at line 477 of file qgsexpression.h.
References QgsExpression::Visitor::visit().
QString QgsExpression::NodeInOperator::dump () const virtual
Implements QgsExpression::Node.
Definition at line 2376 of file qgsexpression.cpp.
QVariant QgsExpression::NodeInOperator::eval (QgsExpression * parent, const QgsFeature * f) virtual
Implements QgsExpression::Node.
Definition at line 2320 of file qgsexpression.cpp.
References ENSURE_NO_EVAL_ERROR, QgsExpression::Node::eval(), getDoubleValue(), getStringValue(), isDoubleSafe(), isNull(), TVL_False, TVL_True, and TVL_Unknown.
bool QgsExpression::NodeInOperator::isNotIn () const inline
Definition at line 467 of file qgsexpression.h.
NodeList* QgsExpression::NodeInOperator::list () const inline
Definition at line 468 of file qgsexpression.h.
Referenced by QgsOgcUtils::expressionInOperatorToOgcFilter().
virtual bool QgsExpression::NodeInOperator::needsGeometry () const inline virtual
Implements QgsExpression::Node.
Definition at line 476 of file qgsexpression.h.
References QgsExpression::Node::needsGeometry().
Node* QgsExpression::NodeInOperator::node () const inline
Definition at line 466 of file qgsexpression.h.
Referenced by QgsOgcUtils::expressionInOperatorToOgcFilter().
virtual NodeType QgsExpression::NodeInOperator::nodeType () const inline virtual
Implements QgsExpression::Node.
Definition at line 470 of file qgsexpression.h.
References QgsExpression::ntInOperator.
bool QgsExpression::NodeInOperator::prepare (QgsExpression * parent, const QgsFields & fields) virtual
Implements QgsExpression::Node.
Definition at line 2366 of file qgsexpression.cpp.
References QgsExpression::Node::prepare().
virtual QStringList QgsExpression::NodeInOperator::referencedColumns () const inline virtual
Implements QgsExpression::Node.
Definition at line 475 of file qgsexpression.h.
References QgsExpression::Node::referencedColumns().
Member Data Documentation
NodeList* QgsExpression::NodeInOperator::mList protected
Definition at line 481 of file qgsexpression.h.
Node* QgsExpression::NodeInOperator::mNode protected
Definition at line 480 of file qgsexpression.h.
bool QgsExpression::NodeInOperator::mNotIn protected
Definition at line 482 of file qgsexpression.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.cpp