QGIS API Documentation: QgsSingleBandGrayRendererWidget Class Reference
QgsSingleBandGrayRendererWidget Class Reference
#include <qgssinglebandgrayrendererwidget.h>
Public Slots
void loadMinMax (int theBandNo, double theMin, double theMax, int theOrigin)
Public Member Functions
QgsSingleBandGrayRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent=QgsRectangle())
~QgsSingleBandGrayRendererWidget ()
QgsRasterRenderer * renderer ()
void setFromRenderer (const QgsRasterRenderer *r)
QString min (int index=0)
QString max (int index=0)
void setMin (QString value, int index=0)
void setMax (QString value, int index=0)
int selectedBand (int index=0)
Public Member Functions inherited from QgsRasterRendererWidget
QgsRasterRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent)
virtual ~QgsRasterRendererWidget ()
void setRasterLayer (QgsRasterLayer *layer)
const QgsRasterLayer * rasterLayer () const
virtual QString stdDev ()
virtual void setStdDev (QString value)
Static Public Member Functions
static QgsRasterRendererWidget * create (QgsRasterLayer *layer, const QgsRectangle &theExtent)
Private Slots
void on_mGrayBandComboBox_currentIndexChanged (int index)
Private Attributes
QgsRasterMinMaxWidget * mMinMaxWidget
Additional Inherited Members
Public Types inherited from QgsRasterRendererWidget
enum LoadMinMaxAlgo { Estimate, Actual, CurrentExtent, CumulativeCut }
Protected Member Functions inherited from QgsRasterRendererWidget
QString displayBandName (int band) const
Returns a band name for display.
Protected Attributes inherited from QgsRasterRendererWidget
QgsRasterLayer * mRasterLayer
QgsRectangle mExtent
Current extent.
Detailed Description
Definition at line 25 of file qgssinglebandgrayrendererwidget.h.
Constructor & Destructor Documentation
QgsSingleBandGrayRendererWidget::QgsSingleBandGrayRendererWidget (QgsRasterLayer * layer, const QgsRectangle & extent = QgsRectangle())
Definition at line 22 of file qgssinglebandgrayrendererwidget.cpp.
References QgsRasterInterface::bandCount(), QgsSingleBandGrayRenderer::BlackToWhite, QgsRasterLayer::dataProvider(), QgsRasterRendererWidget::displayBandName(), loadMinMax(), mMinMaxWidget, QgsRasterRendererWidget::mRasterLayer, QgsRasterLayer::renderer(), QgsRasterMinMaxWidget::setExtent(), setFromRenderer(), tr, and QgsSingleBandGrayRenderer::WhiteToBlack.
QgsSingleBandGrayRendererWidget::~QgsSingleBandGrayRendererWidget ()
Definition at line 68 of file qgssinglebandgrayrendererwidget.cpp.
Member Function Documentation
static QgsRasterRendererWidget* QgsSingleBandGrayRendererWidget::create (QgsRasterLayer * layer, const QgsRectangle & theExtent) inline static
Definition at line 32 of file qgssinglebandgrayrendererwidget.h.
void QgsSingleBandGrayRendererWidget::loadMinMax (int theBandNo, double theMin, double theMax, int theOrigin) slot
Definition at line 101 of file qgssinglebandgrayrendererwidget.cpp.
References QgsDebugMsg.
Referenced by QgsSingleBandGrayRendererWidget().
QString QgsSingleBandGrayRendererWidget::max (int index = 0) inline virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 39 of file qgssinglebandgrayrendererwidget.h.
References index.
QString QgsSingleBandGrayRendererWidget::min (int index = 0) inline virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 38 of file qgssinglebandgrayrendererwidget.h.
References index.
void QgsSingleBandGrayRendererWidget::on_mGrayBandComboBox_currentIndexChanged (int index) private slot
Definition at line 126 of file qgssinglebandgrayrendererwidget.cpp.
References mMinMaxWidget, and QgsRasterMinMaxWidget::setBands().
QgsRasterRenderer * QgsSingleBandGrayRendererWidget::renderer () virtual
Implements QgsRasterRendererWidget.
Definition at line 72 of file qgssinglebandgrayrendererwidget.cpp.
References QgsRasterLayer::dataProvider(), QgsRasterDataProvider::dataType(), QgsRasterRendererWidget::mRasterLayer, QgsSingleBandGrayRenderer::setContrastEnhancement(), QgsContrastEnhancement::setContrastEnhancementAlgorithm(), QgsSingleBandGrayRenderer::setGradient(), QgsContrastEnhancement::setMaximumValue(), and QgsContrastEnhancement::setMinimumValue().
int QgsSingleBandGrayRendererWidget::selectedBand (int index = 0) inline virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 42 of file qgssinglebandgrayrendererwidget.h.
References index.
void QgsSingleBandGrayRendererWidget::setFromRenderer (const QgsRasterRenderer * r)
Definition at line 133 of file qgssinglebandgrayrendererwidget.cpp.
References QgsSingleBandGrayRenderer::contrastEnhancement(), QgsContrastEnhancement::contrastEnhancementAlgorithm(), QgsSingleBandGrayRenderer::gradient(), QgsSingleBandGrayRenderer::grayBand(), QgsContrastEnhancement::maximumValue(), and QgsContrastEnhancement::minimumValue().
Referenced by QgsSingleBandGrayRendererWidget().
void QgsSingleBandGrayRendererWidget::setMax (QString value, int index = 0) inline virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 41 of file qgssinglebandgrayrendererwidget.h.
References index.
void QgsSingleBandGrayRendererWidget::setMin (QString value, int index = 0) inline virtual
Reimplemented from QgsRasterRendererWidget.
Definition at line 40 of file qgssinglebandgrayrendererwidget.h.
References index.
Member Data Documentation
QgsRasterMinMaxWidget* QgsSingleBandGrayRendererWidget::mMinMaxWidget private
Definition at line 51 of file qgssinglebandgrayrendererwidget.h.
Referenced by on_mGrayBandComboBox_currentIndexChanged(), and QgsSingleBandGrayRendererWidget().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/raster/qgssinglebandgrayrendererwidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/raster/qgssinglebandgrayrendererwidget.cpp