QGIS API Documentation: QgsComposerLegend Class Reference
QgsComposerLegend Class Reference
MapComposer
A legend that can be placed onto a map composition.
#include <qgscomposerlegend.h>
Classes
class Atom
Atom is indivisible set (indivisible into more columns).
class Nucleon
Nucleon is either group title, layer title or layer child item.
Public Slots
void synchronizeWithModel ()
Data changed.
void invalidateCurrentMap ()
Sets mCompositionMap to 0 if the map is deleted.
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
Sets the item rotation.
virtual void setItemRotation (double r, bool adjustPosition=false)
Sets the item rotation.
void repaint ()
Public Member Functions
QgsComposerLegend (QgsComposition *composition)
~QgsComposerLegend ()
virtual int type () const
return correct graphics item type.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint.
QSizeF paintAndDetermineSize (QPainter *painter)
Paints the legend and calculates its size.
void adjustBoxSize ()
Sets item box to the whole content.
QgsLegendModel * model ()
Returns pointer to the legend model.
void setTitle (const QString &t)
QString title () const
Qt::AlignmentFlag titleAlignment () const
Returns the alignment of the legend title.
void setTitleAlignment (Qt::AlignmentFlag alignment)
Sets the alignment of the legend title.
QgsComposerLegendStyle & rstyle (QgsComposerLegendStyle::Style s)
Returns reference to modifiable style.
QgsComposerLegendStyle style (QgsComposerLegendStyle::Style s) const
Returns style.
void setStyle (QgsComposerLegendStyle::Style s, const QgsComposerLegendStyle style)
QFont styleFont (QgsComposerLegendStyle::Style s) const
void setStyleFont (QgsComposerLegendStyle::Style s, const QFont &f)
Set style font.
void setStyleMargin (QgsComposerLegendStyle::Style s, double margin)
Set style margin.
void setStyleMargin (QgsComposerLegendStyle::Style s, QgsComposerLegendStyle::Side side, double margin)
double boxSpace () const
void setBoxSpace (double s)
double columnSpace () const
void setColumnSpace (double s)
QColor fontColor () const
void setFontColor (const QColor &c)
double symbolWidth () const
void setSymbolWidth (double w)
double symbolHeight () const
void setSymbolHeight (double h)
double wmsLegendWidth () const
void setWmsLegendWidth (double w)
double wmsLegendHeight () const
void setWmsLegendHeight (double h)
void setWrapChar (const QString &t)
QString wrapChar () const
int columnCount () const
void setColumnCount (int c)
int splitLayer () const
void setSplitLayer (bool s)
int equalColumnWidth () const
void setEqualColumnWidth (bool s)
void setComposerMap (const QgsComposerMap *map)
const QgsComposerMap * composerMap () const
void updateLegend ()
Updates the model and all legend entries.
bool writeXML (QDomElement &elem, QDomDocument &doc) const
stores state in Dom node
bool readXML (const QDomElement &itemElem, const QDomDocument &doc)
sets state from Dom document
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected () const
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
int page () const
Gets the page the item is currently on.
QPointF pagePos () const
Returns the item's position relative to its current page.
void updatePagePos (double newPageWidth, double newPageHeight)
Moves the item so that it retains its relative position on the page when the paper size changes.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft, int page=-1)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft, bool posIncludesFrame=false, int page=-1)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
virtual void setSceneRect (const QRectF &rectangle)
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
virtual void setFrameOutlineWidth (double outlineWidth)
Sets frame outline width.
double frameOutlineWidth () const
Returns the frame's outline width.
Qt::PenJoinStyle frameJoinStyle () const
Returns the join style used for drawing the item's frame.
void setFrameJoinStyle (Qt::PenJoinStyle style)
Sets join style used when drawing the item's frame.
virtual double estimatedFrameBleed () const
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
virtual QRectF rectWithFrame () const
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop, int flags=Qt::TextWordWrap) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font descent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightMillimeters (const QFont &font) const
Returns the font height in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
double itemRotation () const
Returns the rotation for the composer item.
Q_DECL_DEPRECATED double rotation () const
Returns the rotation for the composer item.
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
virtual int numberExportLayers () const
Get the number of layers that this item requires for exporting as layers.
virtual void setCurrentExportLayer (int layerIdx=-1)
Sets the current layer to draw for exporting.
Protected Attributes
QString mTitle
QString mWrapChar
QColor mFontColor
qreal mBoxSpace
Space between item box and contents.
double mColumnSpace
Space between columns.
double mSymbolWidth
Width of symbol icon.
double mSymbolHeight
Height of symbol icon.
double mWmsLegendWidth
Width of WMS legendGraphic pixmap.
double mWmsLegendHeight
Height of WMS legendGraphic pixmap.
double mlineSpacing
Spacing between lines when wrapped.
Qt::AlignmentFlag mTitleAlignment
Title alignment, one of Qt::AlignLeft, Qt::AlignHCenter, Qt::AlignRight)
int mColumnCount
Number of legend columns.
QgsLegendModel mLegendModel
const QgsComposerMap * mComposerMap
Reference to map (because symbols are sometimes in map units)
bool mSplitLayer
Allow splitting layers into multiple columns.
bool mEqualColumnWidth
Use the same width (maximum) for all columns.
Protected Attributes inherited from QgsComposerItem
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
Qt::PenJoinStyle mFrameJoinStyle
Frame join style.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mItemRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
int mCurrentExportLayer
The layer that needs to be exported.
Private Member Functions
QList< Atom > createAtomList (QStandardItem *rootItem, bool splitLayer)
Create list of atoms according to current layer splitting mode.
void setColumns (QList< Atom > &atomList)
Divide atoms to columns and set columns on atoms.
QgsComposerLegend ()
QSizeF drawTitle (QPainter *painter=0, QPointF point=QPointF(), Qt::AlignmentFlag halignment=Qt::AlignLeft)
Draws title in the legend using the title font and the specified alignment If no painter is specified, function returns the required width/height to draw the title.
QSizeF drawGroupItemTitle (QgsComposerGroupItem *groupItem, QPainter *painter=0, QPointF point=QPointF())
Draws a group item and all subitems Returns list of sizes of layers and groups including this group.
QSizeF drawLayerItemTitle (QgsComposerLayerItem *layerItem, QPainter *painter=0, QPointF point=QPointF())
Draws a layer item and all subitems.
Nucleon drawSymbolItem (QgsComposerLegendItem *symbolItem, QPainter *painter=0, QPointF point=QPointF(), double labelXOffset=0.)
void drawSymbolV2 (QPainter *p, QgsSymbolV2 *s, double currentYCoord, double &currentXPosition, double &symbolHeight, int opacity=255) const
Draws a symbol at the current y position and returns the new x position.
QSizeF drawAtom (Atom atom, QPainter *painter=0, QPointF point=QPointF())
Draw atom and return its actual size, the atom is drawn with the space above it so that first atoms in column are all aligned to the same line regardles their style top space.
double spaceAboveAtom (Atom atom)
QStringList layerIdList () const
Helper function that lists ids of layers contained in map canvas.
QStringList splitStringForWrapping (QString stringToSplt)
Splits a string using the wrap char taking into account handling empty wrap char which means no wrapping.
Private Attributes
QMap
< QgsComposerLegendStyle::Style,
QgsComposerLegendStyle > mStyleMap
Additional Inherited Members
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Signals inherited from QgsComposerItem
void itemRotationChanged (double newRotation)
Is emitted on item rotation change.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
void frameChanged ()
Emitted if the item's frame style changes.
Protected Member Functions inherited from QgsComposerItem
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height, double rotation) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Q_DECL_DEPRECATED bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
QRectF largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height, double rotation) const
Calculates corner point after rotation and scaling.
Q_DECL_DEPRECATED bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height, double rotation)
Calculates width / height of the bounding box of a rotated rectangle.
Q_DECL_DEPRECATED void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Detailed Description
A legend that can be placed onto a map composition.
Definition at line 34 of file qgscomposerlegend.h.
Constructor & Destructor Documentation
QgsComposerLegend::QgsComposerLegend (QgsComposition * composition)
Definition at line 34 of file qgscomposerlegend.cpp.
References adjustBoxSize(), QgsComposerLegendStyle::Bottom, QgsComposerLegendStyle::Group, QgsComposerLegendStyle::Left, mLegendModel, mlineSpacing, mSymbolHeight, mSymbolWidth, mWmsLegendHeight, mWmsLegendWidth, mWrapChar, QgsComposerLegendStyle::rfont(), rstyle(), setStyleMargin(), QgsComposerLegendStyle::Subgroup, QgsComposerLegendStyle::Symbol, QgsComposerLegendStyle::SymbolLabel, synchronizeWithModel(), QgsComposerLegendStyle::Title, and QgsComposerLegendStyle::Top.
QgsComposerLegend::~QgsComposerLegend ()
Definition at line 73 of file qgscomposerlegend.cpp.
QgsComposerLegend::QgsComposerLegend () private
Definition at line 68 of file qgscomposerlegend.cpp.
Member Function Documentation
void QgsComposerLegend::adjustBoxSize ()
Sets item box to the whole content.
Definition at line 325 of file qgscomposerlegend.cpp.
References paintAndDetermineSize(), QgsDebugMsg, QgsComposerItem::setSceneRect(), and size.
Referenced by QgsComposerLegend(), synchronizeWithModel(), and updateLegend().
double QgsComposerLegend::boxSpace () const inline
Definition at line 88 of file qgscomposerlegend.h.
int QgsComposerLegend::columnCount () const inline
Definition at line 112 of file qgscomposerlegend.h.
double QgsComposerLegend::columnSpace () const inline
Definition at line 91 of file qgscomposerlegend.h.
const QgsComposerMap* QgsComposerLegend::composerMap () const inline
Definition at line 122 of file qgscomposerlegend.h.
QList< QgsComposerLegend::Atom > QgsComposerLegend::createAtomList (QStandardItem * rootItem, bool splitLayer) private
Create list of atoms according to current layer splitting mode.
Definition at line 818 of file qgscomposerlegend.cpp.
References drawGroupItemTitle(), drawLayerItemTitle(), drawSymbolItem(), QgsComposerLegendItem::GroupItem, QgsComposerLegendStyle::Hidden, QgsComposerLegend::Nucleon::item, QgsComposerLegendItem::itemType(), QgsComposerLegendItem::LayerItem, QgsComposerLegendStyle::margin(), mSplitLayer, QgsComposerLegend::Atom::nucleons, QgsComposerLegend::Nucleon::size, QgsComposerLegend::Atom::size, spaceAboveAtom(), QgsComposerLegendItem::style(), style(), QgsComposerLegendStyle::Symbol, QgsComposerLegendStyle::Top, and type().
Referenced by paintAndDetermineSize().
QSizeF QgsComposerLegend::drawAtom (Atom atom, QPainter * painter = 0, QPointF point = QPointF()) private
Draw atom and return its actual size, the atom is drawn with the space above it so that first atoms in column are all aligned to the same line regardles their style top space.
Definition at line 918 of file qgscomposerlegend.cpp.
References drawGroupItemTitle(), drawLayerItemTitle(), drawSymbolItem(), QgsComposerLegendItem::GroupItem, QgsComposerLegendStyle::Hidden, QgsComposerLegend::Nucleon::item, QgsComposerLegendItem::itemType(), QgsComposerLegend::Nucleon::labelXOffset, QgsComposerLegendItem::LayerItem, QgsComposerLegendStyle::margin(), QgsComposerLegend::Atom::nucleons, QgsComposerLegendItem::RasterSymbolItem, size, QgsComposerLegend::Nucleon::size, QgsComposerLegend::Atom::size, QgsComposerLegendItem::style(), style(), QgsComposerLegendStyle::Symbol, QgsComposerLegendItem::SymbologyV2Item, QgsComposerLegendStyle::Top, and type().
Referenced by paintAndDetermineSize().
QSizeF QgsComposerLegend::drawGroupItemTitle (QgsComposerGroupItem * groupItem, QPainter * painter = 0, QPointF point = QPointF()) private
Draws a group item and all subitems Returns list of sizes of layers and groups including this group.
Definition at line 271 of file qgscomposerlegend.cpp.
References QgsComposerItem::drawText(), QgsComposerItem::fontAscentMillimeters(), mFontColor, mlineSpacing, size, splitStringForWrapping(), QgsComposerLegendItem::style(), styleFont(), and QgsComposerItem::textWidthMillimeters().
Referenced by createAtomList(), and drawAtom().
QSizeF QgsComposerLegend::drawLayerItemTitle (QgsComposerLayerItem * layerItem, QPainter * painter = 0, QPointF point = QPointF()) private
Draws a layer item and all subitems.
Definition at line 296 of file qgscomposerlegend.cpp.
References QgsComposerItem::drawText(), QgsComposerItem::fontAscentMillimeters(), mFontColor, mlineSpacing, size, splitStringForWrapping(), QgsComposerLegendItem::style(), styleFont(), and QgsComposerItem::textWidthMillimeters().
Referenced by createAtomList(), and drawAtom().
QgsComposerLegend::Nucleon QgsComposerLegend::drawSymbolItem (QgsComposerLegendItem * symbolItem, QPainter * painter = 0, QPointF point = QPointF(), double labelXOffset = 0.) private
Definition at line 335 of file qgscomposerlegend.cpp.
References QgsComposerRasterSymbolItem::color(), drawSymbolV2(), QgsComposerItem::drawText(), QgsComposerItem::fontHeightCharacterMM(), QgsMapLayerRegistry::instance(), QgsComposerLegend::Nucleon::item, QgsComposerLegend::Nucleon::labelSize, QgsComposerLayerItem::layerID(), QgsVectorLayer::layerTransparency(), QgsMapLayerRegistry::mapLayer(), mFontColor, mlineSpacing, mSymbolHeight, mSymbolWidth, mWmsLegendHeight, mWmsLegendWidth, size, QgsComposerLegend::Nucleon::size, splitStringForWrapping(), styleFont(), QgsComposerLegendStyle::SymbolLabel, QgsComposerLegend::Nucleon::symbolSize, QgsComposerSymbolV2Item::symbolV2(), and QgsComposerItem::textWidthMillimeters().
Referenced by createAtomList(), and drawAtom().
void QgsComposerLegend::drawSymbolV2 (QPainter * p, QgsSymbolV2 * s, double currentYCoord, double & currentXPosition, double & symbolHeight, int opacity = 255) const private
Draws a symbol at the current y position and returns the new x position.
Returns real symbol height, because for points, it is possible that it differs from mSymbolHeight
Definition at line 479 of file qgscomposerlegend.cpp.
References QgsSymbolV2::drawPreviewIcon(), QgsSymbolV2::MapUnit, QgsComposerMap::mapUnitsToMM(), mComposerMap, QgsComposerItem::mComposition, QgsSymbolV2::MM, mSymbolHeight, mSymbolWidth, QgsSymbolV2::outputUnit(), QgsSymbolV2::setOutputUnit(), QgsMarkerSymbolV2::setSize(), size, QgsMarkerSymbolV2::size(), and QgsComposition::useAdvancedEffects().
Referenced by drawSymbolItem().
QSizeF QgsComposerLegend::drawTitle (QPainter * painter = 0, QPointF point = QPointF(), Qt::AlignmentFlag halignment = Qt::AlignLeft) private
Draws title in the legend using the title font and the specified alignment If no painter is specified, function returns the required width/height to draw the title.
Definition at line 206 of file qgscomposerlegend.cpp.
References QgsComposerItem::drawText(), QgsComposerItem::fontAscentMillimeters(), QgsComposerItem::fontDescentMillimeters(), mBoxSpace, mFontColor, mlineSpacing, mTitle, size, splitStringForWrapping(), styleFont(), QgsComposerItem::textWidthMillimeters(), and QgsComposerLegendStyle::Title.
Referenced by paintAndDetermineSize().
int QgsComposerLegend::equalColumnWidth () const inline
Definition at line 118 of file qgscomposerlegend.h.
QColor QgsComposerLegend::fontColor () const inline
Definition at line 94 of file qgscomposerlegend.h.
void QgsComposerLegend::invalidateCurrentMap () slot
Sets mCompositionMap to 0 if the map is deleted.
Definition at line 798 of file qgscomposerlegend.cpp.
References mComposerMap.
Referenced by setComposerMap().
QStringList QgsComposerLegend::layerIdList () const private
Helper function that lists ids of layers contained in map canvas.
Definition at line 582 of file qgscomposerlegend.cpp.
References QgsMapSettings::layers(), QgsComposition::mapSettings(), and QgsComposerItem::mComposition.
Referenced by updateLegend().
QgsLegendModel* QgsComposerLegend::model () inline
Returns pointer to the legend model.
Definition at line 55 of file qgscomposerlegend.h.
void QgsComposerLegend::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget)
Reimplementation of QCanvasItem::paint.
Definition at line 78 of file qgscomposerlegend.cpp.
References paintAndDetermineSize().
QSizeF QgsComposerLegend::paintAndDetermineSize (QPainter * painter)
Paints the legend and calculates its size.
If painter is 0, only size is calculated
Definition at line 85 of file qgscomposerlegend.cpp.
References QgsComposerLegendStyle::Bottom, QgsComposerLegend::Atom::column, createAtomList(), drawAtom(), QgsComposerItem::drawBackground(), QgsComposerItem::drawFrame(), QgsComposerItem::drawSelectionBoxes(), drawTitle(), QgsComposerLegendStyle::margin(), mBoxSpace, mColumnSpace, mEqualColumnWidth, mLegendModel, mSplitLayer, mTitle, mTitleAlignment, setColumns(), QgsComposerItem::setSceneRect(), size, QgsComposerLegend::Atom::size, spaceAboveAtom(), style(), and QgsComposerLegendStyle::Title.
Referenced by adjustBoxSize(), and paint().
bool QgsComposerLegend::readXML (const QDomElement & itemElem, const QDomDocument & doc) virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is Dom document
Implements QgsComposerItem.
Definition at line 668 of file qgscomposerlegend.cpp.
References QgsComposerItem::_readXML(), QgsComposition::getComposerMapById(), QgsComposerLegendStyle::Group, QgsComposerItem::itemChanged(), mBoxSpace, mColumnCount, mColumnSpace, mComposerMap, QgsComposerItem::mComposition, mEqualColumnWidth, mFontColor, mLegendModel, mSplitLayer, mSymbolHeight, mSymbolWidth, mTitle, mTitleAlignment, mWmsLegendHeight, mWmsLegendWidth, mWrapChar, QgsComposerLegendStyle::readXML(), QgsLegendModel::readXML(), QgsComposerLegendStyle::rfont(), rstyle(), QgsComposerLegendStyle::setMargin(), setStyle(), style(), QgsComposerLegendStyle::Subgroup, QgsComposerLegendStyle::Symbol, QgsComposerLegendStyle::SymbolLabel, QgsComposerLegendStyle::Title, and QgsComposerLegendStyle::Top.
Referenced by QgsComposition::addItemsFromXML().
QgsComposerLegendStyle& QgsComposerLegend::rstyle (QgsComposerLegendStyle::Style s) inline
Returns reference to modifiable style.
Definition at line 75 of file qgscomposerlegend.h.
Referenced by QgsComposerLegend(), readXML(), setStyleFont(), and setStyleMargin().
void QgsComposerLegend::setBoxSpace (double s) inline
Definition at line 89 of file qgscomposerlegend.h.
void QgsComposerLegend::setColumnCount (int c) inline
Definition at line 113 of file qgscomposerlegend.h.
void QgsComposerLegend::setColumns (QList< Atom > & atomList) private
Divide atoms to columns and set columns on atoms.
Definition at line 1001 of file qgscomposerlegend.cpp.
References QgsComposerLegendItem::itemType(), QgsComposerLegendStyle::Left, QgsComposerLegendStyle::margin(), mColumnCount, QgsComposerLegendItem::RasterSymbolItem, QgsComposerLegendStyle::Right, QgsComposerLegend::Atom::size, spaceAboveAtom(), style(), QgsComposerLegendStyle::Symbol, QgsComposerLegendStyle::SymbolLabel, QgsComposerLegendItem::SymbologyV2Item, and type().
Referenced by paintAndDetermineSize().
void QgsComposerLegend::setColumnSpace (double s) inline
Definition at line 92 of file qgscomposerlegend.h.
void QgsComposerLegend::setComposerMap (const QgsComposerMap * map)
Definition at line 789 of file qgscomposerlegend.cpp.
References invalidateCurrentMap(), and mComposerMap.
void QgsComposerLegend::setEqualColumnWidth (bool s) inline
Definition at line 119 of file qgscomposerlegend.h.
void QgsComposerLegend::setFontColor (const QColor & c) inline
Definition at line 95 of file qgscomposerlegend.h.
void QgsComposerLegend::setSplitLayer (bool s) inline
Definition at line 116 of file qgscomposerlegend.h.
void QgsComposerLegend::setStyle (QgsComposerLegendStyle::Style s, const QgsComposerLegendStyle style) inline
Definition at line 78 of file qgscomposerlegend.h.
Referenced by readXML().
void QgsComposerLegend::setStyleFont (QgsComposerLegendStyle::Style s, const QFont & f)
Set style font.
Definition at line 599 of file qgscomposerlegend.cpp.
References rstyle(), and QgsComposerLegendStyle::setFont().
void QgsComposerLegend::setStyleMargin (QgsComposerLegendStyle::Style s, double margin)
Set style margin.
Definition at line 604 of file qgscomposerlegend.cpp.
References rstyle(), and QgsComposerLegendStyle::setMargin().
Referenced by QgsComposerLegend().
void QgsComposerLegend::setStyleMargin (QgsComposerLegendStyle::Style s, QgsComposerLegendStyle::Side side, double margin)
Definition at line 609 of file qgscomposerlegend.cpp.
References rstyle(), and QgsComposerLegendStyle::setMargin().
void QgsComposerLegend::setSymbolHeight (double h) inline
Definition at line 101 of file qgscomposerlegend.h.
void QgsComposerLegend::setSymbolWidth (double w) inline
Definition at line 98 of file qgscomposerlegend.h.
void QgsComposerLegend::setTitle (const QString & t) inline
Definition at line 58 of file qgscomposerlegend.h.
void QgsComposerLegend::setTitleAlignment (Qt::AlignmentFlag alignment) inline
Sets the alignment of the legend title.
Parameters
alignment Text alignment for drawing the legend title
Note
added in 2.3
See also
titleAlignment
Definition at line 72 of file qgscomposerlegend.h.
void QgsComposerLegend::setWmsLegendHeight (double h) inline
Definition at line 107 of file qgscomposerlegend.h.
void QgsComposerLegend::setWmsLegendWidth (double w) inline
Definition at line 104 of file qgscomposerlegend.h.
void QgsComposerLegend::setWrapChar (const QString & t) inline
Definition at line 109 of file qgscomposerlegend.h.
double QgsComposerLegend::spaceAboveAtom (Atom atom) private
Definition at line 972 of file qgscomposerlegend.cpp.
References QgsComposerLegendItem::GroupItem, QgsComposerLegend::Nucleon::item, QgsComposerLegendItem::itemType(), QgsComposerLegendItem::LayerItem, QgsComposerLegendStyle::margin(), QgsComposerLegend::Atom::nucleons, QgsComposerLegendItem::RasterSymbolItem, QgsComposerLegendItem::style(), style(), QgsComposerLegendStyle::Symbol, QgsComposerLegendItem::SymbologyV2Item, QgsComposerLegendStyle::Top, and type().
Referenced by createAtomList(), paintAndDetermineSize(), and setColumns().
int QgsComposerLegend::splitLayer () const inline
Definition at line 115 of file qgscomposerlegend.h.
QStringList QgsComposerLegend::splitStringForWrapping (QString stringToSplt) private
Splits a string using the wrap char taking into account handling empty wrap char which means no wrapping.
Definition at line 807 of file qgscomposerlegend.cpp.
References mWrapChar.
Referenced by drawGroupItemTitle(), drawLayerItemTitle(), drawSymbolItem(), and drawTitle().
QgsComposerLegendStyle QgsComposerLegend::style (QgsComposerLegendStyle::Style s) const inline
Returns style.
Definition at line 77 of file qgscomposerlegend.h.
Referenced by createAtomList(), drawAtom(), paintAndDetermineSize(), readXML(), setColumns(), spaceAboveAtom(), and writeXML().
QFont QgsComposerLegend::styleFont (QgsComposerLegendStyle::Style s) const inline
Definition at line 80 of file qgscomposerlegend.h.
Referenced by drawGroupItemTitle(), drawLayerItemTitle(), drawSymbolItem(), and drawTitle().
double QgsComposerLegend::symbolHeight () const inline
Definition at line 100 of file qgscomposerlegend.h.
double QgsComposerLegend::symbolWidth () const inline
Definition at line 97 of file qgscomposerlegend.h.
void QgsComposerLegend::synchronizeWithModel () slot
Data changed.
Definition at line 592 of file qgscomposerlegend.cpp.
References adjustBoxSize(), and QgsDebugMsg.
Referenced by QgsComposerLegend().
QString QgsComposerLegend::title () const inline
Definition at line 59 of file qgscomposerlegend.h.
Qt::AlignmentFlag QgsComposerLegend::titleAlignment () const inline
Returns the alignment of the legend title.
Returns
Qt::AlignmentFlag for the legend title
Note
added in 2.3
See also
setTitleAlignment
Definition at line 66 of file qgscomposerlegend.h.
virtual int QgsComposerLegend::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerItem.
Definition at line 43 of file qgscomposerlegend.h.
References QgsComposerItem::ComposerLegend.
Referenced by createAtomList(), drawAtom(), setColumns(), and spaceAboveAtom().
void QgsComposerLegend::updateLegend ()
Updates the model and all legend entries.
Definition at line 614 of file qgscomposerlegend.cpp.
References adjustBoxSize(), layerIdList(), mLegendModel, and QgsLegendModel::setLayerSet().
Referenced by QgsComposerView::mouseReleaseEvent().
double QgsComposerLegend::wmsLegendHeight () const inline
Definition at line 106 of file qgscomposerlegend.h.
double QgsComposerLegend::wmsLegendWidth () const inline
Definition at line 103 of file qgscomposerlegend.h.
QString QgsComposerLegend::wrapChar () const inline
Definition at line 110 of file qgscomposerlegend.h.
bool QgsComposerLegend::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
stores state in Dom node
Parameters
elem is Dom element corresponding to 'Composer' tag
doc Dom document
Implements QgsComposerItem.
Definition at line 621 of file qgscomposerlegend.cpp.
References QgsComposerItem::_writeXML(), QgsComposerLegendStyle::Group, QgsComposerMap::id(), mBoxSpace, mColumnCount, mColumnSpace, mComposerMap, mEqualColumnWidth, mFontColor, mLegendModel, mSplitLayer, mSymbolHeight, mSymbolWidth, mTitle, mTitleAlignment, mWmsLegendHeight, mWmsLegendWidth, mWrapChar, style(), QgsComposerLegendStyle::Subgroup, QgsComposerLegendStyle::Symbol, QgsComposerLegendStyle::SymbolLabel, QgsComposerLegendStyle::Title, QgsComposerLegendStyle::writeXML(), and QgsLegendModel::writeXML().
Member Data Documentation
qreal QgsComposerLegend::mBoxSpace protected
Space between item box and contents.
Definition at line 152 of file qgscomposerlegend.h.
Referenced by drawTitle(), paintAndDetermineSize(), readXML(), and writeXML().
int QgsComposerLegend::mColumnCount protected
Number of legend columns.
Definition at line 173 of file qgscomposerlegend.h.
Referenced by readXML(), setColumns(), and writeXML().
double QgsComposerLegend::mColumnSpace protected
Space between columns.
Definition at line 154 of file qgscomposerlegend.h.
Referenced by paintAndDetermineSize(), readXML(), and writeXML().
const QgsComposerMap* QgsComposerLegend::mComposerMap protected
Reference to map (because symbols are sometimes in map units)
Definition at line 178 of file qgscomposerlegend.h.
Referenced by drawSymbolV2(), invalidateCurrentMap(), readXML(), setComposerMap(), and writeXML().
bool QgsComposerLegend::mEqualColumnWidth protected
Use the same width (maximum) for all columns.
Definition at line 184 of file qgscomposerlegend.h.
Referenced by paintAndDetermineSize(), readXML(), and writeXML().
QColor QgsComposerLegend::mFontColor protected
Definition at line 149 of file qgscomposerlegend.h.
Referenced by drawGroupItemTitle(), drawLayerItemTitle(), drawSymbolItem(), drawTitle(), readXML(), and writeXML().
QgsLegendModel QgsComposerLegend::mLegendModel protected
Definition at line 175 of file qgscomposerlegend.h.
Referenced by paintAndDetermineSize(), QgsComposerLegend(), readXML(), updateLegend(), and writeXML().
double QgsComposerLegend::mlineSpacing protected
Spacing between lines when wrapped.
Definition at line 167 of file qgscomposerlegend.h.
Referenced by drawGroupItemTitle(), drawLayerItemTitle(), drawSymbolItem(), drawTitle(), and QgsComposerLegend().
bool QgsComposerLegend::mSplitLayer protected
Allow splitting layers into multiple columns.
Definition at line 181 of file qgscomposerlegend.h.
Referenced by createAtomList(), paintAndDetermineSize(), readXML(), and writeXML().
QMap<QgsComposerLegendStyle::Style, QgsComposerLegendStyle> QgsComposerLegend::mStyleMap private
Definition at line 265 of file qgscomposerlegend.h.
double QgsComposerLegend::mSymbolHeight protected
Height of symbol icon.
Definition at line 159 of file qgscomposerlegend.h.
Referenced by drawSymbolItem(), drawSymbolV2(), QgsComposerLegend(), readXML(), and writeXML().
double QgsComposerLegend::mSymbolWidth protected
Width of symbol icon.
Definition at line 157 of file qgscomposerlegend.h.
Referenced by drawSymbolItem(), drawSymbolV2(), QgsComposerLegend(), readXML(), and writeXML().
QString QgsComposerLegend::mTitle protected
Definition at line 146 of file qgscomposerlegend.h.
Referenced by drawTitle(), paintAndDetermineSize(), readXML(), and writeXML().
Qt::AlignmentFlag QgsComposerLegend::mTitleAlignment protected
Title alignment, one of Qt::AlignLeft, Qt::AlignHCenter, Qt::AlignRight)
Definition at line 170 of file qgscomposerlegend.h.
Referenced by paintAndDetermineSize(), readXML(), and writeXML().
double QgsComposerLegend::mWmsLegendHeight protected
Height of WMS legendGraphic pixmap.
Definition at line 164 of file qgscomposerlegend.h.
Referenced by drawSymbolItem(), QgsComposerLegend(), readXML(), and writeXML().
double QgsComposerLegend::mWmsLegendWidth protected
Width of WMS legendGraphic pixmap.
Definition at line 162 of file qgscomposerlegend.h.
Referenced by drawSymbolItem(), QgsComposerLegend(), readXML(), and writeXML().
QString QgsComposerLegend::mWrapChar protected
Definition at line 147 of file qgscomposerlegend.h.
Referenced by QgsComposerLegend(), readXML(), splitStringForWrapping(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerlegend.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerlegend.cpp