QGIS API Documentation: QgsMapCanvasRendererSync Class Reference
QgsMapCanvasRendererSync Class Reference
Class that does synchronization between QgsMapCanvas and its associated QgsMapRenderer:
#include <qgsmapcanvas.h>
Public Member Functions
QgsMapCanvasRendererSync (QgsMapCanvas *canvas, QgsMapRenderer *renderer)
Protected Slots
void onExtentC2R ()
void onExtentR2C ()
void onMapUnitsC2R ()
void onMapUnitsR2C ()
void onCrsTransformC2R ()
void onCrsTransformR2C ()
void onDestCrsC2R ()
void onDestCrsR2C ()
void onLayersC2R ()
Protected Attributes
QgsMapCanvas * mCanvas
QgsMapRenderer * mRenderer
bool mSyncingExtent
Detailed Description
Class that does synchronization between QgsMapCanvas and its associated QgsMapRenderer:
changes done in map canvas settings are pushed to map renderer
changes done in map renderer are pushed to map canvas settings
This class can be removed within API cleanup when QgsMapRenderer will not be accessible from canvas API anymore. Added in 2.4. This class is not a part of public API!
Definition at line 643 of file qgsmapcanvas.h.
Constructor & Destructor Documentation
QgsMapCanvasRendererSync::QgsMapCanvasRendererSync (QgsMapCanvas * canvas, QgsMapRenderer * renderer)
Definition at line 90 of file qgsmapcanvas.cpp.
References mCanvas, mRenderer, onCrsTransformC2R(), onCrsTransformR2C(), onDestCrsC2R(), onDestCrsR2C(), onExtentC2R(), onExtentR2C(), onLayersC2R(), onMapUnitsC2R(), and onMapUnitsR2C().
Member Function Documentation
void QgsMapCanvasRendererSync::onCrsTransformC2R () protected slot
Definition at line 145 of file qgsmapcanvas.cpp.
References QgsMapSettings::hasCrsTransformEnabled(), QgsMapCanvas::mapSettings(), mCanvas, mRenderer, and QgsMapRenderer::setProjectionsEnabled().
Referenced by QgsMapCanvasRendererSync().
void QgsMapCanvasRendererSync::onCrsTransformR2C () protected slot
Definition at line 150 of file qgsmapcanvas.cpp.
References QgsMapRenderer::hasCrsTransformEnabled(), mCanvas, mRenderer, and QgsMapCanvas::setCrsTransformEnabled().
Referenced by QgsMapCanvasRendererSync().
void QgsMapCanvasRendererSync::onDestCrsC2R () protected slot
Definition at line 155 of file qgsmapcanvas.cpp.
References QgsMapSettings::destinationCrs(), QgsMapCanvas::mapSettings(), mCanvas, mRenderer, and QgsMapRenderer::setDestinationCrs().
Referenced by QgsMapCanvasRendererSync().
void QgsMapCanvasRendererSync::onDestCrsR2C () protected slot
Definition at line 160 of file qgsmapcanvas.cpp.
References QgsMapRenderer::destinationCrs(), mCanvas, mRenderer, and QgsMapCanvas::setDestinationCrs().
Referenced by QgsMapCanvasRendererSync().
void QgsMapCanvasRendererSync::onExtentC2R () protected slot
Definition at line 113 of file qgsmapcanvas.cpp.
References QgsMapSettings::extent(), QgsMapCanvas::mapSettings(), mCanvas, mRenderer, mSyncingExtent, and QgsMapRenderer::setExtent().
Referenced by QgsMapCanvasRendererSync().
void QgsMapCanvasRendererSync::onExtentR2C () protected slot
Definition at line 124 of file qgsmapcanvas.cpp.
References QgsMapRenderer::extent(), mCanvas, mRenderer, mSyncingExtent, and QgsMapCanvas::setExtent().
Referenced by QgsMapCanvasRendererSync().
void QgsMapCanvasRendererSync::onLayersC2R () protected slot
Definition at line 165 of file qgsmapcanvas.cpp.
References QgsMapSettings::layers(), QgsMapCanvas::mapSettings(), mCanvas, mRenderer, and QgsMapRenderer::setLayerSet().
Referenced by QgsMapCanvasRendererSync().
void QgsMapCanvasRendererSync::onMapUnitsC2R () protected slot
Definition at line 135 of file qgsmapcanvas.cpp.
References QgsMapCanvas::mapSettings(), QgsMapSettings::mapUnits(), mCanvas, mRenderer, and QgsMapRenderer::setMapUnits().
Referenced by QgsMapCanvasRendererSync().
void QgsMapCanvasRendererSync::onMapUnitsR2C () protected slot
Definition at line 140 of file qgsmapcanvas.cpp.
References QgsMapRenderer::mapUnits(), mCanvas, mRenderer, and QgsMapCanvas::setMapUnits().
Referenced by QgsMapCanvasRendererSync().
Member Data Documentation
QgsMapCanvas* QgsMapCanvasRendererSync::mCanvas protected
Definition at line 665 of file qgsmapcanvas.h.
Referenced by onCrsTransformC2R(), onCrsTransformR2C(), onDestCrsC2R(), onDestCrsR2C(), onExtentC2R(), onExtentR2C(), onLayersC2R(), onMapUnitsC2R(), onMapUnitsR2C(), and QgsMapCanvasRendererSync().
QgsMapRenderer* QgsMapCanvasRendererSync::mRenderer protected
Definition at line 666 of file qgsmapcanvas.h.
Referenced by onCrsTransformC2R(), onCrsTransformR2C(), onDestCrsC2R(), onDestCrsR2C(), onExtentC2R(), onExtentR2C(), onLayersC2R(), onMapUnitsC2R(), onMapUnitsR2C(), and QgsMapCanvasRendererSync().
bool QgsMapCanvasRendererSync::mSyncingExtent protected
Definition at line 668 of file qgsmapcanvas.h.
Referenced by onExtentC2R(), and onExtentR2C().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmapcanvas.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmapcanvas.cpp