QGIS API Documentation: QgsComposerMouseHandles Class Reference
QgsComposerMouseHandles Class Reference
MapComposer
Handles drawing of selection outlines and mouse handles.
#include <qgscomposermousehandles.h>
Public Types
enum MouseAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, SelectItem, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
enum SnapGuideMode { Item, Point }
Public Slots
void selectionChanged ()
Sets up listeners to sizeChanged signal for all selected items.
void selectedItemSizeChanged ()
Redraws handles when selected item size changes.
void selectedItemRotationChanged ()
Redraws handles when selected item rotation changes.
Public Member Functions
QgsComposerMouseHandles (QgsComposition *composition)
virtual ~QgsComposerMouseHandles ()
void setComposition (QgsComposition *c)
QgsComposition * composition ()
void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
QgsComposerMouseHandles::MouseAction mouseActionForScenePos (const QPointF &sceneCoordPos)
Finds out which mouse move action to choose depending on the scene cursor position.
bool isDragging ()
Returns true is user is currently dragging the handles.
bool isResizing ()
Returns true is user is currently resizing with the handles.
Protected Member Functions
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
Private Member Functions
QRectF selectionBounds () const
Returns the mouse handle bounds of current selection.
bool selectionRotation (double &rotation) const
Returns true if all selected items have same rotation, and if so, updates passed rotation variable.
void updateHandles ()
Redraws or hides the handles based on the current selection.
void drawHandles (QPainter *painter, double rectHandlerSize)
Draws the handles.
void drawSelectedItemBounds (QPainter *painter)
Draw outlines for selected items.
double rectHandlerBorderTolerance ()
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
Qt::CursorShape cursorForPosition (const QPointF &itemCoordPos)
Finds out the appropriate cursor for the current mouse position in the widget (e.g.
QgsComposerMouseHandles::MouseAction mouseActionForPosition (const QPointF &itemCoordPos)
Finds out which mouse move action to choose depending on the cursor position inside the widget.
void dragMouseMove (const QPointF &currentPosition, bool lockMovement, bool preventSnap)
Handles dragging of items during mouse move.
QSizeF calcCursorEdgeOffset (const QPointF &cursorPos)
Calculates the distance of the mouse cursor from thed edge of the mouse handles.
void resizeMouseMove (const QPointF &currentPosition, bool lockAspect, bool fromCenter)
Handles resizing of items during mouse move.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
QPointF snapPoint (const QPointF &originalPoint, QgsComposerMouseHandles::SnapGuideMode mode)
Snaps an item or point (depending on mode) originating at originalPoint to the grid or align rulers.
QPointF alignItem (double &alignX, double &alignY, double unalignedX, double unalignedY)
Snaps an item originating at unalignedX, unalignedY to the grid or align rulers.
QPointF alignPos (const QPointF &pos, double &alignX, double &alignY)
Snaps a point to to the grid or align rulers.
void collectAlignCoordinates (QMap< double, const QgsComposerItem * > &alignCoordsX, QMap< double, const QgsComposerItem * > &alignCoordsY)
bool nearestItem (const QMap< double, const QgsComposerItem * > &coords, double value, double &nearestValue) const
void checkNearestItem (double checkCoord, const QMap< double, const QgsComposerItem * > &alignCoords, double &smallestDiff, double itemCoordOffset, double &itemCoord, double &alignCoord) const
QGraphicsView * graphicsView ()
void setViewportCursor (Qt::CursorShape cursor)
void resetStatusBar ()
Private Attributes
QgsComposition * mComposition
QGraphicsView * mGraphicsView
QgsComposerMouseHandles::MouseAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QPointF mBeginMouseEventPos
Position of the mouse at beginning of move/resize (in scene coordinates)
QPointF mBeginHandlePos
Position of composer handles at beginning of move/resize (in scene coordinates)
double mBeginHandleWidth
Width and height of composer handles at beginning of resize.
double mBeginHandleHeight
QRectF mResizeRect
double mResizeMoveX
double mResizeMoveY
bool mIsDragging
True if user is currently dragging items.
bool mIsResizing
True is user is currently resizing items.
QGraphicsLineItem * mHAlignSnapItem
Align snap lines.
QGraphicsLineItem * mVAlignSnapItem
QSizeF mCursorOffset
Detailed Description
Handles drawing of selection outlines and mouse handles.
Responsible for mouse interactions such as resizing and moving selected items.
Definition at line 31 of file qgscomposermousehandles.h.
Member Enumeration Documentation
enum QgsComposerMouseHandles::ItemPositionMode
Enumerator
UpperLeft
UpperMiddle
UpperRight
MiddleLeft
Middle
MiddleRight
LowerLeft
LowerMiddle
LowerRight
Definition at line 52 of file qgscomposermousehandles.h.
enum QgsComposerMouseHandles::MouseAction
Describes the action (move or resize in different directon) to be done during mouse move.
Enumerator
MoveItem
ResizeUp
ResizeDown
ResizeLeft
ResizeRight
ResizeLeftUp
ResizeRightUp
ResizeLeftDown
ResizeRightDown
SelectItem
NoAction
Definition at line 37 of file qgscomposermousehandles.h.
enum QgsComposerMouseHandles::SnapGuideMode
Enumerator
Item
Point
Definition at line 65 of file qgscomposermousehandles.h.
Constructor & Destructor Documentation
QgsComposerMouseHandles::QgsComposerMouseHandles (QgsComposition * composition)
Definition at line 32 of file qgscomposermousehandles.cpp.
References mComposition, and selectionChanged().
QgsComposerMouseHandles::~QgsComposerMouseHandles () virtual
Definition at line 52 of file qgscomposermousehandles.cpp.
Member Function Documentation
QPointF QgsComposerMouseHandles::alignItem (double & alignX, double & alignY, double unalignedX, double unalignedY) private
Snaps an item originating at unalignedX, unalignedY to the grid or align rulers.
Definition at line 1178 of file qgscomposermousehandles.cpp.
References checkNearestItem(), and collectAlignCoordinates().
Referenced by snapPoint().
QPointF QgsComposerMouseHandles::alignPos (const QPointF & pos, double & alignX, double & alignY) private
Snaps a point to to the grid or align rulers.
Definition at line 1216 of file qgscomposermousehandles.cpp.
References QgsComposition::alignmentSnapTolerance(), collectAlignCoordinates(), mComposition, and nearestItem().
Referenced by snapPoint().
QSizeF QgsComposerMouseHandles::calcCursorEdgeOffset (const QPointF & cursorPos) private
Calculates the distance of the mouse cursor from thed edge of the mouse handles.
Definition at line 748 of file qgscomposermousehandles.cpp.
References mCurrentMouseMoveAction, ResizeDown, ResizeLeft, ResizeLeftDown, ResizeLeftUp, ResizeRight, ResizeRightDown, ResizeRightUp, and ResizeUp.
Referenced by mousePressEvent().
void QgsComposerMouseHandles::checkNearestItem (double checkCoord, const QMap< double, const QgsComposerItem * > & alignCoords, double & smallestDiff, double itemCoordOffset, double & itemCoord, double & alignCoord) const private
Definition at line 1312 of file qgscomposermousehandles.cpp.
References nearestItem().
Referenced by alignItem().
void QgsComposerMouseHandles::collectAlignCoordinates (QMap< double, const QgsComposerItem * > & alignCoordsX, QMap< double, const QgsComposerItem * > & alignCoordsY) private
Definition at line 1255 of file qgscomposermousehandles.cpp.
References QgsComposition::alignmentSnap(), mComposition, qgsDoubleNear(), QgsComposerItem::rectWithFrame(), QgsComposerItem::selected(), QgsComposition::smartGuidesEnabled(), and QgsComposition::snapLines().
Referenced by alignItem(), and alignPos().
QgsComposition* QgsComposerMouseHandles::composition () inline
Definition at line 75 of file qgscomposermousehandles.h.
Referenced by selectionChanged().
Qt::CursorShape QgsComposerMouseHandles::cursorForPosition (const QPointF & itemCoordPos) private
Finds out the appropriate cursor for the current mouse position in the widget (e.g.
move in the middle, resize at border)
Definition at line 344 of file qgscomposermousehandles.cpp.
References mouseActionForPosition(), MoveItem, NoAction, ResizeDown, ResizeLeft, ResizeLeftDown, ResizeLeftUp, ResizeRight, ResizeRightDown, ResizeRightUp, ResizeUp, and SelectItem.
Referenced by hoverMoveEvent().
void QgsComposerMouseHandles::deleteAlignItems () private
Definition at line 1172 of file qgscomposermousehandles.cpp.
References deleteHAlignSnapItem(), and deleteVAlignSnapItem().
Referenced by dragMouseMove(), mousePressEvent(), mouseReleaseEvent(), and snapPoint().
void QgsComposerMouseHandles::deleteHAlignSnapItem () private
Definition at line 1152 of file qgscomposermousehandles.cpp.
References mHAlignSnapItem.
Referenced by deleteAlignItems(), and snapPoint().
void QgsComposerMouseHandles::deleteVAlignSnapItem () private
Definition at line 1162 of file qgscomposermousehandles.cpp.
References mVAlignSnapItem.
Referenced by deleteAlignItems(), and snapPoint().
void QgsComposerMouseHandles::dragMouseMove (const QPointF & currentPosition, bool lockMovement, bool preventSnap) private
Handles dragging of items during mouse move.
Definition at line 788 of file qgscomposermousehandles.cpp.
References deleteAlignItems(), Item, mBeginHandlePos, mBeginMouseEventPos, mComposition, QgsComposition::setStatusMessage(), snapPoint(), and tr.
Referenced by mouseMoveEvent().
void QgsComposerMouseHandles::drawHandles (QPainter * painter, double rectHandlerSize) private
Draws the handles.
Definition at line 99 of file qgscomposermousehandles.cpp.
Referenced by paint().
void QgsComposerMouseHandles::drawSelectedItemBounds (QPainter * painter) private
Draw outlines for selected items.
Definition at line 130 of file qgscomposermousehandles.cpp.
References mBeginHandleHeight, mBeginHandleWidth, mComposition, mIsDragging, mIsResizing, mResizeMoveX, mResizeMoveY, mResizeRect, QgsComposition::relativeResizeRect(), and QgsComposition::selectedComposerItems().
Referenced by paint().
QGraphicsView * QgsComposerMouseHandles::graphicsView () private
Definition at line 57 of file qgscomposermousehandles.cpp.
References mGraphicsView.
Referenced by rectHandlerBorderTolerance(), and setViewportCursor().
QGraphicsLineItem * QgsComposerMouseHandles::hAlignSnapItem () private
Return horizontal align snap item.
Creates a new graphics line if 0
Definition at line 1128 of file qgscomposermousehandles.cpp.
References mHAlignSnapItem.
Referenced by snapPoint().
void QgsComposerMouseHandles::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected
Definition at line 541 of file qgscomposermousehandles.cpp.
References setViewportCursor().
void QgsComposerMouseHandles::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected
Definition at line 536 of file qgscomposermousehandles.cpp.
References cursorForPosition(), and setViewportCursor().
bool QgsComposerMouseHandles::isDragging () inline
Returns true is user is currently dragging the handles.
Definition at line 83 of file qgscomposermousehandles.h.
Referenced by QgsComposerView::mouseReleaseEvent().
bool QgsComposerMouseHandles::isResizing () inline
Returns true is user is currently resizing with the handles.
Definition at line 86 of file qgscomposermousehandles.h.
Referenced by QgsComposerView::mouseReleaseEvent().
QgsComposerMouseHandles::MouseAction QgsComposerMouseHandles::mouseActionForPosition (const QPointF & itemCoordPos) private
Finds out which mouse move action to choose depending on the cursor position inside the widget.
Definition at line 436 of file qgscomposermousehandles.cpp.
References mComposition, MoveItem, rectHandlerBorderTolerance(), ResizeDown, ResizeLeft, ResizeLeftDown, ResizeLeftUp, ResizeRight, ResizeRightDown, ResizeRightUp, ResizeUp, QgsComposerItem::selected(), and SelectItem.
Referenced by cursorForPosition(), mouseActionForScenePos(), and mousePressEvent().
QgsComposerMouseHandles::MouseAction QgsComposerMouseHandles::mouseActionForScenePos (const QPointF & sceneCoordPos)
Finds out which mouse move action to choose depending on the scene cursor position.
Definition at line 529 of file qgscomposermousehandles.cpp.
References mouseActionForPosition().
Referenced by QgsComposerView::mousePressEvent().
void QgsComposerMouseHandles::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 743 of file qgscomposermousehandles.cpp.
void QgsComposerMouseHandles::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 558 of file qgscomposermousehandles.cpp.
References dragMouseMove(), mIsDragging, mIsResizing, mLastMouseEventPos, and resizeMouseMove().
void QgsComposerMouseHandles::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 709 of file qgscomposermousehandles.cpp.
References calcCursorEdgeOffset(), deleteAlignItems(), mBeginHandleHeight, mBeginHandlePos, mBeginHandleWidth, mBeginMouseEventPos, mCurrentMouseMoveAction, mCursorOffset, mIsDragging, mIsResizing, mLastMouseEventPos, mMouseMoveStartPos, mouseActionForPosition(), MoveItem, mResizeMoveX, mResizeMoveY, mResizeRect, NoAction, and SelectItem.
void QgsComposerMouseHandles::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 587 of file qgscomposermousehandles.cpp.
References deleteAlignItems(), QgsProject::dirty(), QgsProject::instance(), mBeginHandleHeight, mBeginHandlePos, mBeginHandleWidth, mComposition, mCurrentMouseMoveAction, MathUtils::min(), mIsDragging, mIsResizing, mMouseMoveStartPos, MoveItem, mResizeMoveX, mResizeMoveY, mResizeRect, NoAction, QgsComposition::relativeResizeRect(), resetStatusBar(), QgsComposerItemCommand::saveAfterState(), QgsComposerItemCommand::savePreviousState(), QgsComposition::selectedComposerItems(), setViewportCursor(), tr, QgsComposition::undoStack(), updateHandles(), and QgsComposerItem::UpperLeft.
bool QgsComposerMouseHandles::nearestItem (const QMap< double, const QgsComposerItem * > & coords, double value, double & nearestValue) const private
Definition at line 1329 of file qgscomposermousehandles.cpp.
Referenced by alignPos(), and checkNearestItem().
void QgsComposerMouseHandles::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget)
Definition at line 80 of file qgscomposermousehandles.cpp.
References drawHandles(), drawSelectedItemBounds(), mComposition, QgsComposition::plotStyle(), QgsComposition::Preview, and rectHandlerBorderTolerance().
double QgsComposerMouseHandles::rectHandlerBorderTolerance () private
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
Definition at line 323 of file qgscomposermousehandles.cpp.
References graphicsView().
Referenced by mouseActionForPosition(), and paint().
void QgsComposerMouseHandles::resetStatusBar () private
Definition at line 688 of file qgscomposermousehandles.cpp.
References mComposition, QgsComposition::selectedComposerItems(), QgsComposition::setStatusMessage(), and tr.
Referenced by mouseReleaseEvent(), and selectionChanged().
void QgsComposerMouseHandles::resizeMouseMove (const QPointF & currentPosition, bool lockAspect, bool fromCenter) private
Handles resizing of items during mouse move.
Definition at line 842 of file qgscomposermousehandles.cpp.
References mBeginHandleHeight, mBeginHandleWidth, mBeginMouseEventPos, mComposition, mCurrentMouseMoveAction, mCursorOffset, MoveItem, mResizeMoveX, mResizeMoveY, mResizeRect, NoAction, Point, ResizeDown, ResizeLeft, ResizeLeftDown, ResizeLeftUp, ResizeRight, ResizeRightDown, ResizeRightUp, ResizeUp, SelectItem, QgsComposition::setStatusMessage(), snapPoint(), and tr.
Referenced by mouseMoveEvent().
void QgsComposerMouseHandles::selectedItemRotationChanged () slot
Redraws handles when selected item rotation changes.
Definition at line 231 of file qgscomposermousehandles.cpp.
References mIsDragging, mIsResizing, and updateHandles().
Referenced by selectionChanged().
void QgsComposerMouseHandles::selectedItemSizeChanged () slot
Redraws handles when selected item size changes.
Definition at line 222 of file qgscomposermousehandles.cpp.
References mIsDragging, mIsResizing, and updateHandles().
Referenced by selectionChanged().
QRectF QgsComposerMouseHandles::selectionBounds () const private
Returns the mouse handle bounds of current selection.
Definition at line 281 of file qgscomposermousehandles.cpp.
References mComposition, and QgsComposition::selectedComposerItems().
Referenced by updateHandles().
void QgsComposerMouseHandles::selectionChanged () slot
Sets up listeners to sizeChanged signal for all selected items.
Definition at line 193 of file qgscomposermousehandles.cpp.
References composition(), resetStatusBar(), QgsComposerItem::selected(), selectedItemRotationChanged(), selectedItemSizeChanged(), and updateHandles().
Referenced by QgsComposerMouseHandles().
bool QgsComposerMouseHandles::selectionRotation (double & rotation) const private
Returns true if all selected items have same rotation, and if so, updates passed rotation variable.
Definition at line 299 of file qgscomposermousehandles.cpp.
References mComposition, and QgsComposition::selectedComposerItems().
Referenced by updateHandles().
void QgsComposerMouseHandles::setComposition (QgsComposition * c) inline
Definition at line 74 of file qgscomposermousehandles.h.
void QgsComposerMouseHandles::setViewportCursor (Qt::CursorShape cursor) private
Definition at line 547 of file qgscomposermousehandles.cpp.
References graphicsView(), mComposition, and QgsComposition::preventCursorChange().
Referenced by hoverLeaveEvent(), hoverMoveEvent(), and mouseReleaseEvent().
QPointF QgsComposerMouseHandles::snapPoint (const QPointF & originalPoint, QgsComposerMouseHandles::SnapGuideMode mode) private
Snaps an item or point (depending on mode) originating at originalPoint to the grid or align rulers.
Definition at line 1068 of file qgscomposermousehandles.cpp.
References alignItem(), QgsComposition::alignmentSnap(), alignPos(), deleteAlignItems(), deleteHAlignSnapItem(), deleteVAlignSnapItem(), hAlignSnapItem(), Item, mComposition, QgsComposition::numPages(), QgsComposition::paperHeight(), QgsComposition::paperWidth(), Point, QgsComposition::smartGuidesEnabled(), QgsComposition::snapPointToGrid(), QgsComposition::spaceBetweenPages(), and vAlignSnapItem().
Referenced by dragMouseMove(), and resizeMouseMove().
void QgsComposerMouseHandles::updateHandles () private
Redraws or hides the handles based on the current selection.
Definition at line 240 of file qgscomposermousehandles.cpp.
References mComposition, QgsComposition::selectedComposerItems(), selectionBounds(), and selectionRotation().
Referenced by mouseReleaseEvent(), selectedItemRotationChanged(), selectedItemSizeChanged(), and selectionChanged().
QGraphicsLineItem * QgsComposerMouseHandles::vAlignSnapItem () private
Return vertical align snap item.
Creates a new graphics line if 0
Definition at line 1140 of file qgscomposermousehandles.cpp.
References mVAlignSnapItem.
Referenced by snapPoint().
Member Data Documentation
double QgsComposerMouseHandles::mBeginHandleHeight private
Definition at line 124 of file qgscomposermousehandles.h.
Referenced by drawSelectedItemBounds(), mousePressEvent(), mouseReleaseEvent(), and resizeMouseMove().
QPointF QgsComposerMouseHandles::mBeginHandlePos private
Position of composer handles at beginning of move/resize (in scene coordinates)
Definition at line 121 of file qgscomposermousehandles.h.
Referenced by dragMouseMove(), mousePressEvent(), and mouseReleaseEvent().
double QgsComposerMouseHandles::mBeginHandleWidth private
Width and height of composer handles at beginning of resize.
Definition at line 123 of file qgscomposermousehandles.h.
Referenced by drawSelectedItemBounds(), mousePressEvent(), mouseReleaseEvent(), and resizeMouseMove().
QPointF QgsComposerMouseHandles::mBeginMouseEventPos private
Position of the mouse at beginning of move/resize (in scene coordinates)
Definition at line 119 of file qgscomposermousehandles.h.
Referenced by dragMouseMove(), mousePressEvent(), and resizeMouseMove().
QgsComposition* QgsComposerMouseHandles::mComposition private
Definition at line 110 of file qgscomposermousehandles.h.
Referenced by alignPos(), collectAlignCoordinates(), dragMouseMove(), drawSelectedItemBounds(), mouseActionForPosition(), mouseReleaseEvent(), paint(), QgsComposerMouseHandles(), resetStatusBar(), resizeMouseMove(), selectionBounds(), selectionRotation(), setViewportCursor(), snapPoint(), and updateHandles().
QgsComposerMouseHandles::MouseAction QgsComposerMouseHandles::mCurrentMouseMoveAction private
Definition at line 113 of file qgscomposermousehandles.h.
Referenced by calcCursorEdgeOffset(), mousePressEvent(), mouseReleaseEvent(), and resizeMouseMove().
QSizeF QgsComposerMouseHandles::mCursorOffset private
Definition at line 139 of file qgscomposermousehandles.h.
Referenced by mousePressEvent(), and resizeMouseMove().
QGraphicsView* QgsComposerMouseHandles::mGraphicsView private
Definition at line 111 of file qgscomposermousehandles.h.
Referenced by graphicsView().
QGraphicsLineItem* QgsComposerMouseHandles::mHAlignSnapItem private
Align snap lines.
Definition at line 136 of file qgscomposermousehandles.h.
Referenced by deleteHAlignSnapItem(), and hAlignSnapItem().
bool QgsComposerMouseHandles::mIsDragging private
True if user is currently dragging items.
Definition at line 131 of file qgscomposermousehandles.h.
Referenced by drawSelectedItemBounds(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), selectedItemRotationChanged(), and selectedItemSizeChanged().
bool QgsComposerMouseHandles::mIsResizing private
True is user is currently resizing items.
Definition at line 133 of file qgscomposermousehandles.h.
Referenced by drawSelectedItemBounds(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), selectedItemRotationChanged(), and selectedItemSizeChanged().
QPointF QgsComposerMouseHandles::mLastMouseEventPos private
Position of the last mouse move event (in scene coordinates)
Definition at line 117 of file qgscomposermousehandles.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QPointF QgsComposerMouseHandles::mMouseMoveStartPos private
Start point of the last mouse move action (in scene coordinates)
Definition at line 115 of file qgscomposermousehandles.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
double QgsComposerMouseHandles::mResizeMoveX private
Definition at line 127 of file qgscomposermousehandles.h.
Referenced by drawSelectedItemBounds(), mousePressEvent(), mouseReleaseEvent(), and resizeMouseMove().
double QgsComposerMouseHandles::mResizeMoveY private
Definition at line 128 of file qgscomposermousehandles.h.
Referenced by drawSelectedItemBounds(), mousePressEvent(), mouseReleaseEvent(), and resizeMouseMove().
QRectF QgsComposerMouseHandles::mResizeRect private
Definition at line 126 of file qgscomposermousehandles.h.
Referenced by drawSelectedItemBounds(), mousePressEvent(), mouseReleaseEvent(), and resizeMouseMove().
QGraphicsLineItem* QgsComposerMouseHandles::mVAlignSnapItem private
Definition at line 137 of file qgscomposermousehandles.h.
Referenced by deleteVAlignSnapItem(), and vAlignSnapItem().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposermousehandles.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposermousehandles.cpp