QGIS API Documentation: QgsSVGFillSymbolLayer Class Reference
QgsSVGFillSymbolLayer Class Reference
A class for svg fill patterns.
#include <qgsfillsymbollayerv2.h>
Public Member Functions
QgsSVGFillSymbolLayer (const QString &svgFilePath="", double width=20, double rotation=0.0)
QgsSVGFillSymbolLayer (const QByteArray &svgData, double width=20, double rotation=0.0)
~QgsSVGFillSymbolLayer ()
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
void setSvgFilePath (const QString &svgPath)
QString svgFilePath () const
void setPatternWidth (double width)
double patternWidth () const
void setSvgFillColor (const QColor &c)
QColor svgFillColor () const
void setSvgOutlineColor (const QColor &c)
QColor svgOutlineColor () const
void setSvgOutlineWidth (double w)
double svgOutlineWidth () const
void setPatternWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit patternWidthUnit () const
void setPatternWidthMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & patternWidthMapUnitScale () const
void setSvgOutlineWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit svgOutlineWidthUnit () const
void setSvgOutlineWidthMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & svgOutlineWidthMapUnitScale () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
void setMapUnitScale (const QgsMapUnitScale &scale)
QgsMapUnitScale mapUnitScale () const
Public Member Functions inherited from QgsImageFillSymbolLayer
QgsImageFillSymbolLayer ()
virtual ~QgsImageFillSymbolLayer ()
void renderPolygon (const QPolygonF &points, QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
void setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outlineWidthUnit () const
void setOutlineWidthMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & outlineWidthMapUnitScale () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual Qt::PenStyle dxfPenStyle () const
Public Member Functions inherited from QgsFillSymbolLayerV2
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Protected Member Functions
void applyDataDefinedSettings (const QgsSymbolV2RenderContext &context)
Protected Member Functions inherited from QgsFillSymbolLayerV2
QgsFillSymbolLayerV2 (bool locked=false)
void _renderPolygon (QPainter *p, const QPolygonF &points, const QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
Default method to render polygon.
Protected Member Functions inherited from QgsSymbolLayerV2
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsFields *fields, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Protected Attributes
double mPatternWidth
Width of the pattern (in output units)
QgsSymbolV2::OutputUnit mPatternWidthUnit
QgsMapUnitScale mPatternWidthMapUnitScale
QByteArray mSvgData
SVG data.
QString mSvgFilePath
Path to the svg file (or empty if constructed directly from data)
QRectF mSvgViewBox
SVG view box (to keep the aspect ratio.
QImage * mSvgPattern
SVG pattern image.
QColor mSvgFillColor
QColor mSvgOutlineColor
double mSvgOutlineWidth
QgsSymbolV2::OutputUnit mSvgOutlineWidthUnit
QgsMapUnitScale mSvgOutlineWidthMapUnitScale
Protected Attributes inherited from QgsImageFillSymbolLayer
QBrush mBrush
double mNextAngle
double mOutlineWidth
Outline width.
QgsSymbolV2::OutputUnit mOutlineWidthUnit
QgsMapUnitScale mOutlineWidthMapUnitScale
QgsLineSymbolV2 * mOutline
Custom outline.
Protected Attributes inherited from QgsFillSymbolLayerV2
double mAngle
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Private Member Functions
void storeViewBox ()
Helper function that gets the view box from the byte array.
void setDefaultSvgParams ()
void applyPattern (QBrush &brush, const QString &svgFilePath, double patternWidth, QgsSymbolV2::OutputUnit patternWidthUnit, const QColor &svgFillColor, const QColor &svgOutlineColor, double svgOutlineWidth, QgsSymbolV2::OutputUnit svgOutlineWidthUnit, const QgsSymbolV2RenderContext &context, const QgsMapUnitScale &patternWidthMapUnitScale, const QgsMapUnitScale &svgOutlineWidthMapUnitScale)
Applies the svg pattern to the brush.
Additional Inherited Members
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
A class for svg fill patterns.
The class automatically scales the pattern to the appropriate pixel dimensions of the output device
Definition at line 593 of file qgsfillsymbollayerv2.h.
Constructor & Destructor Documentation
QgsSVGFillSymbolLayer::QgsSVGFillSymbolLayer (const QString & svgFilePath = "", double width = 20, double rotation = 0.0)
Definition at line 1564 of file qgsfillsymbollayerv2.cpp.
References QgsFillSymbolLayerV2::angle(), QgsFillSymbolLayerV2::mAngle, QgsImageFillSymbolLayer::mOutlineWidth, mSvgPattern, setDefaultSvgParams(), and setSvgFilePath().
Referenced by clone(), create(), and createFromSld().
QgsSVGFillSymbolLayer::QgsSVGFillSymbolLayer (const QByteArray & svgData, double width = 20, double rotation = 0.0)
Definition at line 1576 of file qgsfillsymbollayerv2.cpp.
References QgsFillSymbolLayerV2::angle(), QgsFillSymbolLayerV2::mAngle, QgsImageFillSymbolLayer::mOutlineWidth, mSvgPattern, setDefaultSvgParams(), QgsImageFillSymbolLayer::setSubSymbol(), and storeViewBox().
QgsSVGFillSymbolLayer::~QgsSVGFillSymbolLayer ()
Definition at line 1590 of file qgsfillsymbollayerv2.cpp.
References mSvgPattern.
Member Function Documentation
void QgsSVGFillSymbolLayer::applyDataDefinedSettings (const QgsSymbolV2RenderContext & context) protected virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 1995 of file qgsfillsymbollayerv2.cpp.
References applyPattern(), QgsSymbolLayerV2Utils::decodeColor(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), QgsImageFillSymbolLayer::mBrush, QgsImageFillSymbolLayer::mNextAngle, mPatternWidth, mPatternWidthMapUnitScale, mPatternWidthUnit, mSvgFilePath, mSvgFillColor, mSvgOutlineColor, mSvgOutlineWidth, mSvgOutlineWidthMapUnitScale, mSvgOutlineWidthUnit, outlineWidth, svgFillColor(), and svgOutlineColor().
void QgsSVGFillSymbolLayer::applyPattern (QBrush & brush, const QString & svgFilePath, double patternWidth, QgsSymbolV2::OutputUnit patternWidthUnit, const QColor & svgFillColor, const QColor & svgOutlineColor, double svgOutlineWidth, QgsSymbolV2::OutputUnit svgOutlineWidthUnit, const QgsSymbolV2RenderContext & context, const QgsMapUnitScale & patternWidthMapUnitScale, const QgsMapUnitScale & svgOutlineWidthMapUnitScale) private
Applies the svg pattern to the brush.
Definition at line 1738 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2RenderContext::alpha(), QgsSvgCache::instance(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mSvgPattern, mSvgViewBox, QgsSymbolLayerV2Utils::multiplyImageOpacity(), outlineWidth, patternWidthMapUnitScale(), patternWidthUnit(), QgsSymbolLayerV2Utils::pixelSizeScaleFactor(), qgsDoubleNear(), QgsRenderContext::rasterScaleFactor(), QgsSymbolV2RenderContext::renderContext(), QgsRenderContext::scaleFactor(), size, QgsSvgCache::svgAsImage(), QgsSvgCache::svgAsPicture(), svgOutlineWidthMapUnitScale(), and svgOutlineWidthUnit().
Referenced by applyDataDefinedSettings(), and startRender().
QgsSymbolLayerV2 * QgsSVGFillSymbolLayer::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1848 of file qgsfillsymbollayerv2.cpp.
References QgsLineSymbolV2::clone(), QgsSymbolLayerV2::copyDataDefinedProperties(), QgsFillSymbolLayerV2::mAngle, QgsImageFillSymbolLayer::mOutline, QgsImageFillSymbolLayer::mOutlineWidthMapUnitScale, QgsImageFillSymbolLayer::mOutlineWidthUnit, mPatternWidth, mPatternWidthMapUnitScale, mPatternWidthUnit, mSvgData, mSvgFilePath, mSvgFillColor, mSvgOutlineColor, mSvgOutlineWidth, mSvgOutlineWidthMapUnitScale, mSvgOutlineWidthUnit, QgsSVGFillSymbolLayer(), QgsImageFillSymbolLayer::setOutlineWidthMapUnitScale(), QgsImageFillSymbolLayer::setOutlineWidthUnit(), setPatternWidthMapUnitScale(), setPatternWidthUnit(), QgsImageFillSymbolLayer::setSubSymbol(), setSvgFillColor(), setSvgOutlineColor(), setSvgOutlineWidth(), setSvgOutlineWidthMapUnitScale(), and setSvgOutlineWidthUnit().
QgsSymbolLayerV2 * QgsSVGFillSymbolLayer::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 1641 of file qgsfillsymbollayerv2.cpp.
References QgsFillSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::decodeColor(), QgsSymbolLayerV2Utils::decodeMapUnitScale(), QgsSymbolLayerV2Utils::decodeOutputUnit(), QgsSVGFillSymbolLayer(), QgsSymbolLayerV2::setDataDefinedProperty(), QgsImageFillSymbolLayer::setOutlineWidthMapUnitScale(), QgsImageFillSymbolLayer::setOutlineWidthUnit(), setPatternWidthMapUnitScale(), setPatternWidthUnit(), setSvgFillColor(), setSvgOutlineColor(), setSvgOutlineWidth(), setSvgOutlineWidthMapUnitScale(), setSvgOutlineWidthUnit(), svgFilePath(), and QgsSymbolLayerV2Utils::symbolNameToPath().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsSVGFillSymbolLayer::createFromSld (QDomElement & element) static
Definition at line 1935 of file qgsfillsymbollayerv2.cpp.
References QgsFillSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::createLineLayerFromSld(), QgsSymbolLayerV2Utils::externalGraphicFromSld(), QgsSymbolLayerV2::fillColor(), QgsSymbolLayerV2Utils::lineFromSld(), QgsDebugMsg, QgsSVGFillSymbolLayer(), QgsSymbolLayerV2Utils::rotationFromSldElement(), QgsImageFillSymbolLayer::setSubSymbol(), setSvgFillColor(), setSvgOutlineColor(), setSvgOutlineWidth(), and size.
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QString QgsSVGFillSymbolLayer::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1733 of file qgsfillsymbollayerv2.cpp.
QgsMapUnitScale QgsSVGFillSymbolLayer::mapUnitScale () const virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 1621 of file qgsfillsymbollayerv2.cpp.
References QgsImageFillSymbolLayer::mapUnitScale(), QgsImageFillSymbolLayer::mOutlineWidthMapUnitScale, mPatternWidthMapUnitScale, and mSvgOutlineWidthMapUnitScale.
QgsSymbolV2::OutputUnit QgsSVGFillSymbolLayer::outputUnit () const virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 1603 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2::Mixed, QgsImageFillSymbolLayer::mOutlineWidthUnit, mPatternWidthUnit, mSvgOutlineWidthUnit, and QgsImageFillSymbolLayer::outputUnit().
double QgsSVGFillSymbolLayer::patternWidth () const inline
Definition at line 620 of file qgsfillsymbollayerv2.h.
const QgsMapUnitScale& QgsSVGFillSymbolLayer::patternWidthMapUnitScale () const inline
Definition at line 633 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern().
QgsSymbolV2::OutputUnit QgsSVGFillSymbolLayer::patternWidthUnit () const inline
Definition at line 630 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern().
QgsStringMap QgsSVGFillSymbolLayer::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 1816 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeColor(), QgsSymbolLayerV2Utils::encodeMapUnitScale(), QgsSymbolLayerV2Utils::encodeOutputUnit(), QgsFillSymbolLayerV2::mAngle, QgsImageFillSymbolLayer::mOutlineWidthMapUnitScale, QgsImageFillSymbolLayer::mOutlineWidthUnit, mPatternWidth, mPatternWidthMapUnitScale, mPatternWidthUnit, mSvgData, mSvgFilePath, mSvgFillColor, mSvgOutlineColor, mSvgOutlineWidth, mSvgOutlineWidthMapUnitScale, mSvgOutlineWidthUnit, QgsSymbolLayerV2::saveDataDefinedProperties(), and QgsSymbolLayerV2Utils::symbolPathToName().
void QgsSVGFillSymbolLayer::setDefaultSvgParams () private
Definition at line 2059 of file qgsfillsymbollayerv2.cpp.
References QgsSvgCache::containsParams(), QgsSvgCache::instance(), mSvgFilePath, mSvgFillColor, mSvgOutlineColor, and mSvgOutlineWidth.
Referenced by QgsSVGFillSymbolLayer(), and setSvgFilePath().
void QgsSVGFillSymbolLayer::setMapUnitScale (const QgsMapUnitScale & scale) virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 1613 of file qgsfillsymbollayerv2.cpp.
References QgsImageFillSymbolLayer::mOutlineWidthMapUnitScale, mPatternWidthMapUnitScale, mSvgOutlineWidthMapUnitScale, and QgsImageFillSymbolLayer::setMapUnitScale().
void QgsSVGFillSymbolLayer::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 1595 of file qgsfillsymbollayerv2.cpp.
References QgsImageFillSymbolLayer::mOutlineWidthUnit, mPatternWidthUnit, mSvgOutlineWidthUnit, and QgsImageFillSymbolLayer::setOutputUnit().
void QgsSVGFillSymbolLayer::setPatternWidth (double width) inline
Definition at line 619 of file qgsfillsymbollayerv2.h.
void QgsSVGFillSymbolLayer::setPatternWidthMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 632 of file qgsfillsymbollayerv2.h.
Referenced by clone(), and create().
void QgsSVGFillSymbolLayer::setPatternWidthUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 629 of file qgsfillsymbollayerv2.h.
Referenced by clone(), and create().
void QgsSVGFillSymbolLayer::setSvgFilePath (const QString & svgPath)
Definition at line 1632 of file qgsfillsymbollayerv2.cpp.
References QgsSvgCache::getImageData(), QgsSvgCache::instance(), mSvgData, mSvgFilePath, setDefaultSvgParams(), and storeViewBox().
Referenced by QgsSVGFillSymbolLayer().
void QgsSVGFillSymbolLayer::setSvgFillColor (const QColor & c) inline
Definition at line 622 of file qgsfillsymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSVGFillSymbolLayer::setSvgOutlineColor (const QColor & c) inline
Definition at line 624 of file qgsfillsymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSVGFillSymbolLayer::setSvgOutlineWidth (double w) inline
Definition at line 626 of file qgsfillsymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSVGFillSymbolLayer::setSvgOutlineWidthMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 638 of file qgsfillsymbollayerv2.h.
Referenced by clone(), and create().
void QgsSVGFillSymbolLayer::setSvgOutlineWidthUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 635 of file qgsfillsymbollayerv2.h.
Referenced by clone(), and create().
void QgsSVGFillSymbolLayer::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 1795 of file qgsfillsymbollayerv2.cpp.
References applyPattern(), QgsSymbolV2RenderContext::fields(), QgsImageFillSymbolLayer::mBrush, QgsImageFillSymbolLayer::mOutline, mPatternWidth, mPatternWidthMapUnitScale, mPatternWidthUnit, mSvgFilePath, mSvgFillColor, mSvgOutlineColor, mSvgOutlineWidth, mSvgOutlineWidthMapUnitScale, mSvgOutlineWidthUnit, QgsSymbolLayerV2::prepareExpressions(), QgsSymbolV2RenderContext::renderContext(), QgsRenderContext::rendererScale(), and QgsSymbolV2::startRender().
void QgsSVGFillSymbolLayer::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 1808 of file qgsfillsymbollayerv2.cpp.
References QgsImageFillSymbolLayer::mOutline, QgsSymbolV2RenderContext::renderContext(), and QgsSymbolV2::stopRender().
void QgsSVGFillSymbolLayer::storeViewBox () private
Helper function that gets the view box from the byte array.
Definition at line 2043 of file qgsfillsymbollayerv2.cpp.
References mSvgData, and mSvgViewBox.
Referenced by QgsSVGFillSymbolLayer(), and setSvgFilePath().
QString QgsSVGFillSymbolLayer::svgFilePath () const inline
Definition at line 618 of file qgsfillsymbollayerv2.h.
Referenced by create().
QColor QgsSVGFillSymbolLayer::svgFillColor () const inline
Definition at line 623 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings().
QColor QgsSVGFillSymbolLayer::svgOutlineColor () const inline
Definition at line 625 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings().
double QgsSVGFillSymbolLayer::svgOutlineWidth () const inline
Definition at line 627 of file qgsfillsymbollayerv2.h.
const QgsMapUnitScale& QgsSVGFillSymbolLayer::svgOutlineWidthMapUnitScale () const inline
Definition at line 639 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern().
QgsSymbolV2::OutputUnit QgsSVGFillSymbolLayer::svgOutlineWidthUnit () const inline
Definition at line 636 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern().
void QgsSVGFillSymbolLayer::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 1878 of file qgsfillsymbollayerv2.cpp.
References QgsFillSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::createGeometryElement(), QgsSymbolLayerV2Utils::createRotationElement(), QgsSymbolLayerV2Utils::externalGraphicToSld(), QgsSymbolLayerV2Utils::lineToSld(), QgsFillSymbolLayerV2::mAngle, QgsImageFillSymbolLayer::mOutline, mPatternWidth, mSvgFilePath, mSvgFillColor, mSvgOutlineColor, mSvgOutlineWidth, and QgsSymbolV2::toSld().
Member Data Documentation
double QgsSVGFillSymbolLayer::mPatternWidth protected
Width of the pattern (in output units)
Definition at line 649 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), properties(), startRender(), and toSld().
QgsMapUnitScale QgsSVGFillSymbolLayer::mPatternWidthMapUnitScale protected
Definition at line 651 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), mapUnitScale(), properties(), setMapUnitScale(), and startRender().
QgsSymbolV2::OutputUnit QgsSVGFillSymbolLayer::mPatternWidthUnit protected
Definition at line 650 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), outputUnit(), properties(), setOutputUnit(), and startRender().
QByteArray QgsSVGFillSymbolLayer::mSvgData protected
SVG data.
Definition at line 654 of file qgsfillsymbollayerv2.h.
Referenced by clone(), properties(), setSvgFilePath(), and storeViewBox().
QString QgsSVGFillSymbolLayer::mSvgFilePath protected
Path to the svg file (or empty if constructed directly from data)
Definition at line 656 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), properties(), setDefaultSvgParams(), setSvgFilePath(), startRender(), and toSld().
QColor QgsSVGFillSymbolLayer::mSvgFillColor protected
Definition at line 665 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), properties(), setDefaultSvgParams(), startRender(), and toSld().
QColor QgsSVGFillSymbolLayer::mSvgOutlineColor protected
Definition at line 666 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), properties(), setDefaultSvgParams(), startRender(), and toSld().
double QgsSVGFillSymbolLayer::mSvgOutlineWidth protected
Definition at line 667 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), properties(), setDefaultSvgParams(), startRender(), and toSld().
QgsMapUnitScale QgsSVGFillSymbolLayer::mSvgOutlineWidthMapUnitScale protected
Definition at line 669 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), mapUnitScale(), properties(), setMapUnitScale(), and startRender().
QgsSymbolV2::OutputUnit QgsSVGFillSymbolLayer::mSvgOutlineWidthUnit protected
Definition at line 668 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), clone(), outputUnit(), properties(), setOutputUnit(), and startRender().
QImage* QgsSVGFillSymbolLayer::mSvgPattern protected
SVG pattern image.
Note
added in 1.9
Definition at line 661 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), QgsSVGFillSymbolLayer(), and ~QgsSVGFillSymbolLayer().
QRectF QgsSVGFillSymbolLayer::mSvgViewBox protected
SVG view box (to keep the aspect ratio.
Definition at line 658 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), and storeViewBox().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsfillsymbollayerv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsfillsymbollayerv2.cpp