QGIS API Documentation: QgsDerivativeFilter Class Reference
QgsDerivativeFilter Class Reference abstract
Adds the ability to calculate derivatives in x- and y-directions.
#include <qgsderivativefilter.h>
Public Member Functions
QgsDerivativeFilter (const QString &inputFile, const QString &outputFile, const QString &outputFormat)
virtual ~QgsDerivativeFilter ()
virtual float processNineCellWindow (float *x11, float *x21, float *x31, float *x12, float *x22, float *x32, float *x13, float *x23, float *x33)=0
Calculates output value from nine input values.
Public Member Functions inherited from QgsNineCellFilter
QgsNineCellFilter (const QString &inputFile, const QString &outputFile, const QString &outputFormat)
Constructor that takes input file, output file and output format (GDAL string)
virtual ~QgsNineCellFilter ()
int processRaster (QProgressDialog *p)
Starts the calculation, reads from mInputFile and stores the result in mOutputFile.
double cellSizeX () const
void setCellSizeX (double size)
double cellSizeY () const
void setCellSizeY (double size)
double zFactor () const
void setZFactor (double factor)
double inputNodataValue () const
void setInputNodataValue (double value)
double outputNodataValue () const
void setOutputNodataValue (double value)
Protected Member Functions
float calcFirstDerX (float *x11, float *x21, float *x31, float *x12, float *x22, float *x32, float *x13, float *x23, float *x33)
Calculates the first order derivative in x-direction according to Horn (1981)
float calcFirstDerY (float *x11, float *x21, float *x31, float *x12, float *x22, float *x32, float *x13, float *x23, float *x33)
Calculates the first order derivative in y-direction according to Horn (1981)
Additional Inherited Members
Protected Attributes inherited from QgsNineCellFilter
QString mInputFile
QString mOutputFile
QString mOutputFormat
double mCellSizeX
double mCellSizeY
float mInputNodataValue
The nodata value of the input layer.
float mOutputNodataValue
The nodata value of the output layer.
double mZFactor
Scale factor for z-value if x-/y- units are different to z-units (111120 for degree->meters and 370400 for degree->feet)
Detailed Description
Adds the ability to calculate derivatives in x- and y-directions.
Needs to be subclassed (e.g. for slope and aspect)
Definition at line 24 of file qgsderivativefilter.h.
Constructor & Destructor Documentation
QgsDerivativeFilter::QgsDerivativeFilter (const QString & inputFile, const QString & outputFile, const QString & outputFormat)
Definition at line 20 of file qgsderivativefilter.cpp.
QgsDerivativeFilter::~QgsDerivativeFilter () virtual
Definition at line 26 of file qgsderivativefilter.cpp.
Member Function Documentation
float QgsDerivativeFilter::calcFirstDerX (float * x11, float * x21, float * x31, float * x12, float * x22, float * x32, float * x13, float * x23, float * x33) protected
Calculates the first order derivative in x-direction according to Horn (1981)
Definition at line 31 of file qgsderivativefilter.cpp.
References QgsNineCellFilter::mCellSizeX, QgsNineCellFilter::mInputNodataValue, QgsNineCellFilter::mOutputNodataValue, and QgsNineCellFilter::mZFactor.
Referenced by QgsAspectFilter::processNineCellWindow(), QgsSlopeFilter::processNineCellWindow(), and QgsHillshadeFilter::processNineCellWindow().
float QgsDerivativeFilter::calcFirstDerY (float * x11, float * x21, float * x31, float * x12, float * x22, float * x32, float * x13, float * x23, float * x33) protected
Calculates the first order derivative in y-direction according to Horn (1981)
Definition at line 98 of file qgsderivativefilter.cpp.
References QgsNineCellFilter::mCellSizeY, QgsNineCellFilter::mInputNodataValue, QgsNineCellFilter::mOutputNodataValue, and QgsNineCellFilter::mZFactor.
Referenced by QgsAspectFilter::processNineCellWindow(), QgsSlopeFilter::processNineCellWindow(), and QgsHillshadeFilter::processNineCellWindow().
virtual float QgsDerivativeFilter::processNineCellWindow (float * x11, float * x21, float * x31, float * x12, float * x22, float * x32, float * x13, float * x23, float * x33) pure virtual
Calculates output value from nine input values.
The input values and the output value can be equal to the nodata value if not present or outside of the border. Must be implemented by subclasses
Implements QgsNineCellFilter.
Implemented in QgsAspectFilter, QgsHillshadeFilter, and QgsSlopeFilter.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/analysis/raster/qgsderivativefilter.h
/tmp/buildd/qgis-2.4.0+unstable1/src/analysis/raster/qgsderivativefilter.cpp