QGIS API Documentation: QgsLinearlyInterpolatedDiagramRenderer Class Reference
QgsLinearlyInterpolatedDiagramRenderer Class Reference
#include <qgsdiagramrendererv2.h>
Public Member Functions
QgsLinearlyInterpolatedDiagramRenderer ()
~QgsLinearlyInterpolatedDiagramRenderer ()
QgsDiagramRendererV2 * clone () const
Returns new instance that is equivalent to this one.
QList< QgsDiagramSettings > diagramSettings () const
Returns list with all diagram settings in the renderer.
void setDiagramSettings (const QgsDiagramSettings &s)
QList< QString > diagramAttributes () const
Returns attribute indices needed for diagram rendering.
QString rendererName () const
void setLowerValue (double val)
double lowerValue () const
void setUpperValue (double val)
double upperValue () const
void setLowerSize (QSizeF s)
QSizeF lowerSize () const
void setUpperSize (QSizeF s)
QSizeF upperSize () const
int classificationAttribute () const
void setClassificationAttribute (int index)
QString classificationAttributeExpression () const
void setClassificationAttributeExpression (QString expression)
bool classificationAttributeIsExpression () const
void setClassificationAttributeIsExpression (bool isExpression)
void readXML (const QDomElement &elem, const QgsVectorLayer *layer)
void writeXML (QDomElement &layerElem, QDomDocument &doc, const QgsVectorLayer *layer) const
Public Member Functions inherited from QgsDiagramRendererV2
QgsDiagramRendererV2 ()
virtual ~QgsDiagramRendererV2 ()
virtual QSizeF sizeMapUnits (const QgsFeature &feature, const QgsRenderContext &c)
Returns size of the diagram for a feature in map units.
void renderDiagram (const QgsFeature &feature, QgsRenderContext &c, const QPointF &pos)
void setDiagram (QgsDiagram *d)
QgsDiagram * diagram () const
Protected Member Functions
bool diagramSettings (const QgsFeature &feature, const QgsRenderContext &c, QgsDiagramSettings &s)
Returns diagram settings for a feature (or false if the diagram for the feature is not to be rendered).
QSizeF diagramSize (const QgsFeature &, const QgsRenderContext &c)
Returns size of the diagram (in painter units) or an invalid size in case of error.
Protected Member Functions inherited from QgsDiagramRendererV2
QgsDiagramRendererV2 (const QgsDiagramRendererV2 &other)
void convertSizeToMapUnits (QSizeF &size, const QgsRenderContext &context) const
Converts size from mm to map units.
void _readXML (const QDomElement &elem, const QgsVectorLayer *layer)
void _writeXML (QDomElement &rendererElem, QDomDocument &doc, const QgsVectorLayer *layer) const
Private Attributes
QgsDiagramSettings mSettings
QgsDiagramInterpolationSettings mInterpolationSettings
Additional Inherited Members
Static Protected Member Functions inherited from QgsDiagramRendererV2
static int dpiPaintDevice (const QPainter *)
Returns the paint device dpi (or -1 in case of error.
Protected Attributes inherited from QgsDiagramRendererV2
QgsDiagram * mDiagram
Reference to the object that does the real diagram rendering.
Detailed Description
Definition at line 241 of file qgsdiagramrendererv2.h.
Constructor & Destructor Documentation
QgsLinearlyInterpolatedDiagramRenderer::QgsLinearlyInterpolatedDiagramRenderer ()
Definition at line 438 of file qgsdiagramrendererv2.cpp.
References QgsDiagramInterpolationSettings::classificationAttributeIsExpression, and mInterpolationSettings.
Referenced by clone().
QgsLinearlyInterpolatedDiagramRenderer::~QgsLinearlyInterpolatedDiagramRenderer ()
Definition at line 443 of file qgsdiagramrendererv2.cpp.
Member Function Documentation
int QgsLinearlyInterpolatedDiagramRenderer::classificationAttribute () const inline
Definition at line 270 of file qgsdiagramrendererv2.h.
Referenced by QgsVectorLayerRenderer::prepareDiagrams().
QString QgsLinearlyInterpolatedDiagramRenderer::classificationAttributeExpression () const inline
Definition at line 273 of file qgsdiagramrendererv2.h.
Referenced by QgsVectorLayerRenderer::prepareDiagrams().
bool QgsLinearlyInterpolatedDiagramRenderer::classificationAttributeIsExpression () const inline
Definition at line 276 of file qgsdiagramrendererv2.h.
Referenced by QgsVectorLayerRenderer::prepareDiagrams().
QgsDiagramRendererV2 * QgsLinearlyInterpolatedDiagramRenderer::clone () const virtual
Returns new instance that is equivalent to this one.
Note
added in 2.4
Implements QgsDiagramRendererV2.
Definition at line 447 of file qgsdiagramrendererv2.cpp.
References QgsLinearlyInterpolatedDiagramRenderer().
QList< QString > QgsLinearlyInterpolatedDiagramRenderer::diagramAttributes () const virtual
Returns attribute indices needed for diagram rendering.
Implements QgsDiagramRendererV2.
Definition at line 466 of file qgsdiagramrendererv2.cpp.
References QgsDiagramSettings::categoryAttributes, and mSettings.
QList< QgsDiagramSettings > QgsLinearlyInterpolatedDiagramRenderer::diagramSettings () const virtual
Returns list with all diagram settings in the renderer.
Implements QgsDiagramRendererV2.
Definition at line 452 of file qgsdiagramrendererv2.cpp.
References mSettings.
bool QgsLinearlyInterpolatedDiagramRenderer::diagramSettings (const QgsFeature & feature, const QgsRenderContext & c, QgsDiagramSettings & s) protected virtual
Returns diagram settings for a feature (or false if the diagram for the feature is not to be rendered).
Used internally within renderDiagram()
Parameters
feature the feature
c render context
s out: diagram settings for the feature
Implements QgsDiagramRendererV2.
Definition at line 459 of file qgsdiagramrendererv2.cpp.
References diagramSize(), mSettings, and QgsDiagramSettings::size.
QSizeF QgsLinearlyInterpolatedDiagramRenderer::diagramSize (const QgsFeature & features, const QgsRenderContext & c) protected virtual
Returns size of the diagram (in painter units) or an invalid size in case of error.
Implements QgsDiagramRendererV2.
Definition at line 471 of file qgsdiagramrendererv2.cpp.
References QgsDiagramRendererV2::mDiagram, mInterpolationSettings, and mSettings.
Referenced by diagramSettings().
QSizeF QgsLinearlyInterpolatedDiagramRenderer::lowerSize () const inline
Definition at line 265 of file qgsdiagramrendererv2.h.
double QgsLinearlyInterpolatedDiagramRenderer::lowerValue () const inline
Definition at line 259 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::readXML (const QDomElement & elem, const QgsVectorLayer * layer) virtual
Implements QgsDiagramRendererV2.
Definition at line 476 of file qgsdiagramrendererv2.cpp.
References QgsDiagramRendererV2::_readXML(), QgsDiagramInterpolationSettings::classificationAttribute, QgsDiagramInterpolationSettings::classificationAttributeExpression, QgsDiagramInterpolationSettings::classificationAttributeIsExpression, QgsDiagramInterpolationSettings::lowerSize, QgsDiagramInterpolationSettings::lowerValue, mInterpolationSettings, mSettings, QgsDiagramSettings::readXML(), QgsDiagramInterpolationSettings::upperSize, and QgsDiagramInterpolationSettings::upperValue.
QString QgsLinearlyInterpolatedDiagramRenderer::rendererName () const inline virtual
Implements QgsDiagramRendererV2.
Definition at line 256 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::setClassificationAttribute (int index) inline
Definition at line 271 of file qgsdiagramrendererv2.h.
References index.
void QgsLinearlyInterpolatedDiagramRenderer::setClassificationAttributeExpression (QString expression) inline
Definition at line 274 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::setClassificationAttributeIsExpression (bool isExpression) inline
Definition at line 277 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::setDiagramSettings (const QgsDiagramSettings & s) inline
Definition at line 252 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::setLowerSize (QSizeF s) inline
Definition at line 264 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::setLowerValue (double val) inline
Definition at line 258 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::setUpperSize (QSizeF s) inline
Definition at line 267 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::setUpperValue (double val) inline
Definition at line 261 of file qgsdiagramrendererv2.h.
QSizeF QgsLinearlyInterpolatedDiagramRenderer::upperSize () const inline
Definition at line 268 of file qgsdiagramrendererv2.h.
double QgsLinearlyInterpolatedDiagramRenderer::upperValue () const inline
Definition at line 262 of file qgsdiagramrendererv2.h.
void QgsLinearlyInterpolatedDiagramRenderer::writeXML (QDomElement & layerElem, QDomDocument & doc, const QgsVectorLayer * layer) const virtual
Implements QgsDiagramRendererV2.
Definition at line 501 of file qgsdiagramrendererv2.cpp.
References QgsDiagramRendererV2::_writeXML(), QgsDiagramInterpolationSettings::classificationAttribute, QgsDiagramInterpolationSettings::classificationAttributeExpression, QgsDiagramInterpolationSettings::classificationAttributeIsExpression, QgsDiagramInterpolationSettings::lowerSize, QgsDiagramInterpolationSettings::lowerValue, mInterpolationSettings, mSettings, QgsDiagramInterpolationSettings::upperSize, QgsDiagramInterpolationSettings::upperValue, and QgsDiagramSettings::writeXML().
Member Data Documentation
QgsDiagramInterpolationSettings QgsLinearlyInterpolatedDiagramRenderer::mInterpolationSettings private
Definition at line 289 of file qgsdiagramrendererv2.h.
Referenced by diagramSize(), QgsLinearlyInterpolatedDiagramRenderer(), readXML(), and writeXML().
QgsDiagramSettings QgsLinearlyInterpolatedDiagramRenderer::mSettings private
Definition at line 288 of file qgsdiagramrendererv2.h.
Referenced by diagramAttributes(), diagramSettings(), diagramSize(), readXML(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdiagramrendererv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdiagramrendererv2.cpp