QGIS API Documentation: QgsCRSCache Class Reference
QgsCRSCache Class Reference
#include <qgscrscache.h>
Public Member Functions
~QgsCRSCache ()
const
QgsCoordinateReferenceSystem & crsByAuthId (const QString &authid)
Returns the CRS for authid, e.g.
const
QgsCoordinateReferenceSystem & crsByEpsgId (long epsg)
void updateCRSCache (const QString &authid)
Static Public Member Functions
static QgsCRSCache * instance ()
Protected Member Functions
QgsCRSCache ()
Private Attributes
QHash< QString,
QgsCoordinateReferenceSystem > mCRS
QgsCoordinateReferenceSystem mInvalidCRS
CRS that is not initialised (returned in case of error)
Detailed Description
Definition at line 48 of file qgscrscache.h.
Constructor & Destructor Documentation
QgsCRSCache::~QgsCRSCache ()
Definition at line 95 of file qgscrscache.cpp.
QgsCRSCache::QgsCRSCache () protected
Definition at line 91 of file qgscrscache.cpp.
Member Function Documentation
const QgsCoordinateReferenceSystem & QgsCRSCache::crsByAuthId (const QString & authid)
Returns the CRS for authid, e.g.
'EPSG:4326' (or an invalid CRS in case of error)
Definition at line 114 of file qgscrscache.cpp.
References QgsCoordinateReferenceSystem::createFromOgcWmsCrs(), mCRS, and mInvalidCRS.
Referenced by crsByEpsgId(), QgsMapCanvas::getDatumTransformInfo(), QgsCoordinateTransform::initialise(), QgsCoordinateTransformCache::transform(), and QgsCoordinateReferenceSystem::validate().
const QgsCoordinateReferenceSystem & QgsCRSCache::crsByEpsgId (long epsg)
Definition at line 132 of file qgscrscache.cpp.
References crsByAuthId().
QgsCRSCache * QgsCRSCache::instance () static
Definition at line 85 of file qgscrscache.cpp.
Referenced by QgsMapCanvas::getDatumTransformInfo(), QgsCoordinateTransform::initialise(), QgsCoordinateReferenceSystem::readXML(), QgsCoordinateTransformCache::transform(), and QgsCoordinateReferenceSystem::validate().
void QgsCRSCache::updateCRSCache (const QString & authid)
Definition at line 99 of file qgscrscache.cpp.
References QgsCoordinateReferenceSystem::createFromOgcWmsCrs(), QgsCoordinateTransformCache::instance(), QgsCoordinateTransformCache::invalidateCrs(), and mCRS.
Member Data Documentation
QHash< QString, QgsCoordinateReferenceSystem > QgsCRSCache::mCRS private
Definition at line 63 of file qgscrscache.h.
Referenced by crsByAuthId(), and updateCRSCache().
QgsCoordinateReferenceSystem QgsCRSCache::mInvalidCRS private
CRS that is not initialised (returned in case of error)
Definition at line 65 of file qgscrscache.h.
Referenced by crsByAuthId().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgscrscache.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgscrscache.cpp