QGIS API Documentation: QgsNetworkAccessManager Class Reference
QgsNetworkAccessManager Class Reference
#include <qgsnetworkaccessmanager.h>
Signals
void requestAboutToBeCreated (QNetworkAccessManager::Operation, const QNetworkRequest &, QIODevice *)
void requestCreated (QNetworkReply *)
void requestTimedOut (QNetworkReply *)
Public Member Functions
QgsNetworkAccessManager (QObject *parent=0)
~QgsNetworkAccessManager ()
destructor
void insertProxyFactory (QNetworkProxyFactory *factory)
insert a factory into the proxy factories list
void removeProxyFactory (QNetworkProxyFactory *factory)
remove a factory from the proxy factories list
const QList
< QNetworkProxyFactory * > proxyFactories () const
retrieve proxy factory list
const QNetworkProxy & fallbackProxy () const
retrieve fall back proxy (for urls that no factory returned proxies for)
const QStringList & excludeList () const
retrieve exclude list (urls shouldn't use the fallback proxy)
void setFallbackProxyAndExcludes (const QNetworkProxy &proxy, const QStringList &excludes)
set fallback proxy and URL that shouldn't use it.
void setupDefaultProxyAndCache ()
Setup the NAM according to the user's settings.
bool useSystemProxy ()
Static Public Member Functions
static QgsNetworkAccessManager * instance ()
returns a pointer to the single instance
static QString cacheLoadControlName (QNetworkRequest::CacheLoadControl theControl)
Get name for QNetworkRequest::CacheLoadControl.
static
QNetworkRequest::CacheLoadControl cacheLoadControlFromName (const QString &theName)
Get QNetworkRequest::CacheLoadControl from name.
Protected Member Functions
virtual QNetworkReply * createRequest (QNetworkAccessManager::Operation op, const QNetworkRequest &req, QIODevice *outgoingData=0)
Private Slots
void abortRequest ()
Private Attributes
QList< QNetworkProxyFactory * > mProxyFactories
QNetworkProxy mFallbackProxy
QStringList mExcludedURLs
bool mUseSystemProxy
Detailed Description
Definition at line 44 of file qgsnetworkaccessmanager.h.
Constructor & Destructor Documentation
QgsNetworkAccessManager::QgsNetworkAccessManager (QObject * parent = 0)
Definition at line 95 of file qgsnetworkaccessmanager.cpp.
QgsNetworkAccessManager::~QgsNetworkAccessManager ()
destructor
Definition at line 102 of file qgsnetworkaccessmanager.cpp.
Member Function Documentation
void QgsNetworkAccessManager::abortRequest () private slot
Definition at line 179 of file qgsnetworkaccessmanager.cpp.
References QgsMessageLog::logMessage(), requestTimedOut(), and tr.
Referenced by createRequest().
QNetworkRequest::CacheLoadControl QgsNetworkAccessManager::cacheLoadControlFromName (const QString & theName) static
Get QNetworkRequest::CacheLoadControl from name.
Definition at line 217 of file qgsnetworkaccessmanager.cpp.
QString QgsNetworkAccessManager::cacheLoadControlName (QNetworkRequest::CacheLoadControl theControl) static
Get name for QNetworkRequest::CacheLoadControl.
Definition at line 195 of file qgsnetworkaccessmanager.cpp.
QNetworkReply * QgsNetworkAccessManager::createRequest (QNetworkAccessManager::Operation op, const QNetworkRequest & req, QIODevice * outgoingData = 0) protected virtual
Definition at line 150 of file qgsnetworkaccessmanager.cpp.
References abortRequest(), QGis::QGIS_VERSION, requestAboutToBeCreated(), and requestCreated().
const QStringList & QgsNetworkAccessManager::excludeList () const
retrieve exclude list (urls shouldn't use the fallback proxy)
Definition at line 121 of file qgsnetworkaccessmanager.cpp.
References mExcludedURLs.
Referenced by QgsNetworkProxyFactory::queryProxy().
const QNetworkProxy & QgsNetworkAccessManager::fallbackProxy () const
retrieve fall back proxy (for urls that no factory returned proxies for)
Definition at line 126 of file qgsnetworkaccessmanager.cpp.
References mFallbackProxy.
Referenced by QgsNetworkProxyFactory::queryProxy().
void QgsNetworkAccessManager::insertProxyFactory (QNetworkProxyFactory * factory)
insert a factory into the proxy factories list
Definition at line 106 of file qgsnetworkaccessmanager.cpp.
References mProxyFactories.
QgsNetworkAccessManager * QgsNetworkAccessManager::instance () static
returns a pointer to the single instance
Definition at line 89 of file qgsnetworkaccessmanager.cpp.
Referenced by QgsGml::getFeatures(), QgsSvgCache::getImageData(), QgsOWSSourceSelect::on_mSearchButton_clicked(), QgsComposerLabel::paint(), QgsComposerHtml::QgsComposerHtml(), QgsHtmlAnnotationItem::QgsHtmlAnnotationItem(), QgsNetworkProxyFactory::queryProxy(), and setupDefaultProxyAndCache().
const QList< QNetworkProxyFactory * > QgsNetworkAccessManager::proxyFactories () const
retrieve proxy factory list
Definition at line 116 of file qgsnetworkaccessmanager.cpp.
References mProxyFactories.
Referenced by QgsNetworkProxyFactory::queryProxy().
void QgsNetworkAccessManager::removeProxyFactory (QNetworkProxyFactory * factory)
remove a factory from the proxy factories list
Definition at line 111 of file qgsnetworkaccessmanager.cpp.
References mProxyFactories.
void QgsNetworkAccessManager::requestAboutToBeCreated (QNetworkAccessManager::Operation , const QNetworkRequest & , QIODevice *) signal
Referenced by createRequest().
void QgsNetworkAccessManager::requestCreated (QNetworkReply *) signal
Referenced by createRequest().
void QgsNetworkAccessManager::requestTimedOut (QNetworkReply *) signal
Referenced by abortRequest(), and setupDefaultProxyAndCache().
void QgsNetworkAccessManager::setFallbackProxyAndExcludes (const QNetworkProxy & proxy, const QStringList & excludes)
set fallback proxy and URL that shouldn't use it.
Definition at line 131 of file qgsnetworkaccessmanager.cpp.
References mExcludedURLs, mFallbackProxy, and QgsDebugMsg.
Referenced by setupDefaultProxyAndCache().
void QgsNetworkAccessManager::setupDefaultProxyAndCache ()
Setup the NAM according to the user's settings.
Definition at line 238 of file qgsnetworkaccessmanager.cpp.
References instance(), mUseSystemProxy, QgsApplication::qgisSettingsDirPath(), QgsDebugMsg, requestTimedOut(), and setFallbackProxyAndExcludes().
bool QgsNetworkAccessManager::useSystemProxy () inline
Definition at line 85 of file qgsnetworkaccessmanager.h.
Referenced by QgsNetworkProxyFactory::queryProxy().
Member Data Documentation
QStringList QgsNetworkAccessManager::mExcludedURLs private
Definition at line 101 of file qgsnetworkaccessmanager.h.
Referenced by excludeList(), and setFallbackProxyAndExcludes().
QNetworkProxy QgsNetworkAccessManager::mFallbackProxy private
Definition at line 100 of file qgsnetworkaccessmanager.h.
Referenced by fallbackProxy(), and setFallbackProxyAndExcludes().
QList<QNetworkProxyFactory*> QgsNetworkAccessManager::mProxyFactories private
Definition at line 99 of file qgsnetworkaccessmanager.h.
Referenced by insertProxyFactory(), proxyFactories(), and removeProxyFactory().
bool QgsNetworkAccessManager::mUseSystemProxy private
Definition at line 102 of file qgsnetworkaccessmanager.h.
Referenced by setupDefaultProxyAndCache().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsnetworkaccessmanager.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsnetworkaccessmanager.cpp