QGIS API Documentation: QgsExpressionSelectionDialog Class Reference
QgsExpressionSelectionDialog Class Reference
This class offers a dialog to change feature selections.
#include <qgsexpressionselectiondialog.h>
Public Slots
void on_mActionSelect_triggered ()
void on_mActionAddToSelection_triggered ()
void on_mActionRemoveFromSelection_triggered ()
void on_mActionSelectInstersect_triggered ()
void on_mPbnClose_clicked ()
Public Member Functions
QgsExpressionSelectionDialog (QgsVectorLayer *layer, QString startText=QString(), QWidget *parent=0)
Creates a new selection dialog.
QgsExpressionBuilderWidget * expressionBuilder ()
The builder widget that is used by the dialog.
void setExpressionText (const QString &text)
Sets the current expression text.
QString expressionText ()
Returns the current expression text.
void setGeomCalculator (const QgsDistanceArea &da)
Sets geometry calculator used in distance/area calculations.
Protected Member Functions
virtual void closeEvent (QCloseEvent *closeEvent)
Implementation for closeEvent Saves the window geometry.
virtual void done (int r)
Implementation for done (default behavior when pressing esc) Calls close, so the window geometry gets saved and the object deleted.
Private Member Functions
void saveRecent ()
Private Attributes
QgsVectorLayer * mLayer
Detailed Description
This class offers a dialog to change feature selections.
To do so, a QgsExpressionBuilderWidget is shown in a dialog. It offers the possibilities to create a new selection, add to the current selection remove from the current selection or select within the current selection.
Note
added in 2.0
Definition at line 30 of file qgsexpressionselectiondialog.h.
Constructor & Destructor Documentation
QgsExpressionSelectionDialog::QgsExpressionSelectionDialog (QgsVectorLayer * layer, QString startText = QString(), QWidget * parent = 0)
Creates a new selection dialog.
Parameters
layer The layer on which the selection is to be performed.
startText A default expression text to be applied (Defaults to empty)
parent parent object (owner)
Definition at line 22 of file qgsexpressionselectiondialog.cpp.
References QgsApplication::getThemeIcon(), and QgsMapLayer::name().
Member Function Documentation
void QgsExpressionSelectionDialog::closeEvent (QCloseEvent * closeEvent) protected virtual
Implementation for closeEvent Saves the window geometry.
Parameters
closeEvent Event object. Unused.
Definition at line 202 of file qgsexpressionselectiondialog.cpp.
void QgsExpressionSelectionDialog::done (int r) protected virtual
Implementation for done (default behavior when pressing esc) Calls close, so the window geometry gets saved and the object deleted.
Parameters
r Result value. Unused.
Definition at line 215 of file qgsexpressionselectiondialog.cpp.
QgsExpressionBuilderWidget * QgsExpressionSelectionDialog::expressionBuilder ()
The builder widget that is used by the dialog.
Returns
The builder widget that is used by the dialog
Definition at line 50 of file qgsexpressionselectiondialog.cpp.
QString QgsExpressionSelectionDialog::expressionText ()
Returns the current expression text.
Returns
The expression text
Definition at line 60 of file qgsexpressionselectiondialog.cpp.
void QgsExpressionSelectionDialog::on_mActionAddToSelection_triggered () slot
Definition at line 99 of file qgsexpressionselectiondialog.cpp.
References QgsFeatureIterator::close(), QgsExpression::evaluate(), QgsVectorLayer::getFeatures(), QgsFeature::id(), mLayer, QgsFeatureIterator::nextFeature(), QgsVectorLayer::pendingFields(), QgsExpression::prepare(), saveRecent(), QgsVectorLayer::selectedFeaturesIds(), and QgsVectorLayer::setSelectedFeatures().
void QgsExpressionSelectionDialog::on_mActionRemoveFromSelection_triggered () slot
Definition at line 164 of file qgsexpressionselectiondialog.cpp.
References QgsFeatureIterator::close(), QgsExpression::evaluate(), QgsVectorLayer::getFeatures(), QgsFeature::id(), mLayer, QgsFeatureIterator::nextFeature(), QgsVectorLayer::pendingFields(), QgsExpression::prepare(), saveRecent(), QgsVectorLayer::selectedFeaturesIds(), and QgsVectorLayer::setSelectedFeatures().
void QgsExpressionSelectionDialog::on_mActionSelect_triggered () slot
Definition at line 71 of file qgsexpressionselectiondialog.cpp.
References QgsFeatureIterator::close(), QgsExpression::evaluate(), QgsVectorLayer::getFeatures(), QgsFeature::id(), mLayer, QgsFeatureIterator::nextFeature(), QgsVectorLayer::pendingFields(), QgsExpression::prepare(), saveRecent(), and QgsVectorLayer::setSelectedFeatures().
void QgsExpressionSelectionDialog::on_mActionSelectInstersect_triggered () slot
Definition at line 127 of file qgsexpressionselectiondialog.cpp.
References QgsFeatureIterator::close(), QgsExpression::evaluate(), QgsVectorLayer::getFeatures(), QgsFeature::id(), mLayer, QgsFeatureIterator::nextFeature(), QgsVectorLayer::pendingFields(), QgsExpression::prepare(), saveRecent(), QgsVectorLayer::selectedFeaturesIds(), and QgsVectorLayer::setSelectedFeatures().
void QgsExpressionSelectionDialog::on_mPbnClose_clicked () slot
Definition at line 210 of file qgsexpressionselectiondialog.cpp.
void QgsExpressionSelectionDialog::saveRecent () private
Definition at line 221 of file qgsexpressionselectiondialog.cpp.
Referenced by on_mActionAddToSelection_triggered(), on_mActionRemoveFromSelection_triggered(), on_mActionSelect_triggered(), and on_mActionSelectInstersect_triggered().
void QgsExpressionSelectionDialog::setExpressionText (const QString & text)
Sets the current expression text.
Parameters
text the expression text to set
Definition at line 55 of file qgsexpressionselectiondialog.cpp.
void QgsExpressionSelectionDialog::setGeomCalculator (const QgsDistanceArea & da)
Sets geometry calculator used in distance/area calculations.
Definition at line 65 of file qgsexpressionselectiondialog.cpp.
Member Data Documentation
QgsVectorLayer* QgsExpressionSelectionDialog::mLayer private
Definition at line 90 of file qgsexpressionselectiondialog.h.
Referenced by on_mActionAddToSelection_triggered(), on_mActionRemoveFromSelection_triggered(), on_mActionSelect_triggered(), and on_mActionSelectInstersect_triggered().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsexpressionselectiondialog.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsexpressionselectiondialog.cpp