QGIS API Documentation: QgsMapTip Class Reference
QgsMapTip Class Reference
QGIS gui library.
A maptip is a class to display a tip on a map canvas when a mouse is hovered over a feature.
#include <qgsmaptip.h>
Public Member Functions
QgsMapTip ()
Default constructor.
virtual ~QgsMapTip ()
Destructor.
void showMapTip (QgsMapLayer *thepLayer, QgsPoint &theMapPosition, QPoint &thePixelPosition, QgsMapCanvas *mpMapCanvas)
Show a maptip at a given point on the map canvas.
void clear (QgsMapCanvas *mpMapCanvas)
Clear the current maptip if it exists.
Private Member Functions
QString fetchFeature (QgsMapLayer *thepLayer, QgsPoint &theMapPosition, QgsMapCanvas *thepMapCanvas)
QString replaceText (QString displayText, QgsVectorLayer *layer, QgsFeature &feat)
Private Attributes
bool mMapTipVisible
QPoint mLastPosition
Detailed Description
A maptip is a class to display a tip on a map canvas when a mouse is hovered over a feature.
Definition at line 29 of file qgsmaptip.h.
Constructor & Destructor Documentation
QgsMapTip::QgsMapTip ()
Default constructor.
Definition at line 29 of file qgsmaptip.cpp.
References mMapTipVisible.
QgsMapTip::~QgsMapTip () virtual
Destructor.
Definition at line 35 of file qgsmaptip.cpp.
Member Function Documentation
void QgsMapTip::clear (QgsMapCanvas * mpMapCanvas)
Clear the current maptip if it exists.
Parameters
mpMapCanvas the canvas from which the tip should be cleared.
Definition at line 65 of file qgsmaptip.cpp.
References mLastPosition, and mMapTipVisible.
QString QgsMapTip::fetchFeature (QgsMapLayer * thepLayer, QgsPoint & theMapPosition, QgsMapCanvas * thepMapCanvas) private
Definition at line 76 of file qgsmaptip.cpp.
References QgsFeature::attribute(), QgsVectorLayer::displayField(), QgsFeatureRequest::ExactIntersect, QgsVectorLayer::fieldNameIndex(), QgsVectorLayer::getFeatures(), QgsMapCanvas::mapSettings(), QgsMapSettings::mapToLayerCoordinates(), QgsFeatureIterator::nextFeature(), QgsExpression::replaceExpressionText(), QgsMapTool::searchRadiusMU(), QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsRectangle::setYMaximum(), QgsRectangle::setYMinimum(), QgsPoint::x(), and QgsPoint::y().
Referenced by showMapTip().
QString QgsMapTip::replaceText (QString displayText, QgsVectorLayer * layer, QgsFeature & feat) private
void QgsMapTip::showMapTip (QgsMapLayer * thepLayer, QgsPoint & theMapPosition, QPoint & thePixelPosition, QgsMapCanvas * mpMapCanvas)
Show a maptip at a given point on the map canvas.
Parameters
thepLayer a qgis vector map layer pointer that will be used to provide the attribute data for the map tip.
theMapPosition a reference to the position of the cursor in map coordinatess.
thePixelPosition a reference to the position of the cursor in pixel coordinates.
mpMapCanvas a map canvas on which the tip is drawn
Definition at line 40 of file qgsmaptip.cpp.
References fetchFeature(), mLastPosition, and mMapTipVisible.
Member Data Documentation
QPoint QgsMapTip::mLastPosition private
Definition at line 68 of file qgsmaptip.h.
Referenced by clear(), and showMapTip().
bool QgsMapTip::mMapTipVisible private
Definition at line 65 of file qgsmaptip.h.
Referenced by clear(), QgsMapTip(), and showMapTip().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaptip.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaptip.cpp