QGIS API Documentation: QgsDatumTransformDialog Class Reference
QgsDatumTransformDialog Class Reference
#include <qgsdatumtransformdialog.h>
Public Slots
void on_mHideDeprecatedCheckBox_stateChanged (int state)
void on_mDatumTransformTreeWidget_currentItemChanged (QTreeWidgetItem *, QTreeWidgetItem *)
Public Member Functions
QgsDatumTransformDialog (const QString &layerName, const QList< QList< int > > &dt, QWidget *parent=0, Qt::WindowFlags f=0)
~QgsDatumTransformDialog ()
void setDatumTransformInfo (const QString &srcCRSauthId, const QString &destCRSauthId)
QList< int > selectedDatumTransform ()
bool rememberSelection () const
Private Member Functions
QgsDatumTransformDialog ()
void updateTitle ()
bool gridShiftTransformation (const QString &itemText) const
bool testGridShiftFileAvailability (QTreeWidgetItem *item, int col) const
Returns false if the location of the grid shift files is known (PROJ_LIB) and the shift file is not there.
void load ()
Private Attributes
const QList< QList< int > > & mDt
QString mLayerName
QString mSrcCRSauthId
QString mDestCRSauthId
Detailed Description
Definition at line 23 of file qgsdatumtransformdialog.h.
Constructor & Destructor Documentation
QgsDatumTransformDialog::QgsDatumTransformDialog (const QString & layerName, const QList< QList< int > > & dt, QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 25 of file qgsdatumtransformdialog.cpp.
References load(), and updateTitle().
QgsDatumTransformDialog::~QgsDatumTransformDialog ()
Definition at line 126 of file qgsdatumtransformdialog.cpp.
QgsDatumTransformDialog::QgsDatumTransformDialog () private
Member Function Documentation
bool QgsDatumTransformDialog::gridShiftTransformation (const QString & itemText) const private
Definition at line 168 of file qgsdatumtransformdialog.cpp.
Referenced by load().
void QgsDatumTransformDialog::load () private
Definition at line 52 of file qgsdatumtransformdialog.cpp.
References QgsCoordinateTransform::datumTransformCrsInfo(), QgsCoordinateTransform::datumTransformString(), gridShiftTransformation(), mDt, QgsDebugMsg, and testGridShiftFileAvailability().
Referenced by on_mHideDeprecatedCheckBox_stateChanged(), and QgsDatumTransformDialog().
void QgsDatumTransformDialog::on_mDatumTransformTreeWidget_currentItemChanged (QTreeWidgetItem * current, QTreeWidgetItem *) slot
Definition at line 231 of file qgsdatumtransformdialog.cpp.
void QgsDatumTransformDialog::on_mHideDeprecatedCheckBox_stateChanged (int state) slot
Definition at line 226 of file qgsdatumtransformdialog.cpp.
References load().
bool QgsDatumTransformDialog::rememberSelection () const
Definition at line 163 of file qgsdatumtransformdialog.cpp.
QList< int > QgsDatumTransformDialog::selectedDatumTransform ()
Definition at line 148 of file qgsdatumtransformdialog.cpp.
void QgsDatumTransformDialog::setDatumTransformInfo (const QString & srcCRSauthId, const QString & destCRSauthId)
Note
added in 2.4
Definition at line 141 of file qgsdatumtransformdialog.cpp.
References mDestCRSauthId, mSrcCRSauthId, and updateTitle().
Referenced by QgsMapCanvas::getDatumTransformInfo().
bool QgsDatumTransformDialog::testGridShiftFileAvailability (QTreeWidgetItem * item, int col) const private
Returns false if the location of the grid shift files is known (PROJ_LIB) and the shift file is not there.
Definition at line 173 of file qgsdatumtransformdialog.cpp.
References tr.
Referenced by load().
void QgsDatumTransformDialog::updateTitle () private
Definition at line 237 of file qgsdatumtransformdialog.cpp.
References QgsCoordinateReferenceSystem::createFromString(), QgsCoordinateReferenceSystem::description(), QgsCoordinateReferenceSystem::isValid(), mDestCRSauthId, mLayerName, mSrcCRSauthId, and tr.
Referenced by QgsDatumTransformDialog(), and setDatumTransformInfo().
Member Data Documentation
QString QgsDatumTransformDialog::mDestCRSauthId private
Definition at line 51 of file qgsdatumtransformdialog.h.
Referenced by setDatumTransformInfo(), and updateTitle().
const QList< QList< int > >& QgsDatumTransformDialog::mDt private
Definition at line 49 of file qgsdatumtransformdialog.h.
Referenced by load().
QString QgsDatumTransformDialog::mLayerName private
Definition at line 50 of file qgsdatumtransformdialog.h.
Referenced by updateTitle().
QString QgsDatumTransformDialog::mSrcCRSauthId private
Definition at line 51 of file qgsdatumtransformdialog.h.
Referenced by setDatumTransformInfo(), and updateTitle().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsdatumtransformdialog.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsdatumtransformdialog.cpp