QGIS API Documentation: QgsMapLayerModel Class Reference
QgsMapLayerModel Class Reference
The QgsMapLayerModel class is a model to display layers in widgets.
#include <qgsmaplayermodel.h>
Public Member Functions
QgsMapLayerModel (QObject *parent=0)
QgsMapLayerModel creates a model to display layers in widgets.
QgsMapLayerModel (QList< QgsMapLayer * > layers, QObject *parent=0)
QgsMapLayerModel creates a model to display a specific list of layers in a widget.
void setItemsCheckable (bool checkable)
setItemsCheckable defines if layers should be selectable in the widget
void checkAll (Qt::CheckState checkState)
checkAll changes the checkstate for all the layers
QList< QgsMapLayer * > layersChecked (Qt::CheckState checkState=Qt::Checked)
layersChecked returns the list of layers which are checked (or unchecked)
bool itemsCheckable ()
returns if the items can be checked or not
QModelIndex indexFromLayer (QgsMapLayer *layer)
indexFromLayer returns the model index for a given layer
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &child) const
int rowCount (const QModelIndex &parent) const
int columnCount (const QModelIndex &parent) const
QVariant data (const QModelIndex &index, int role) const
bool setData (const QModelIndex &index, const QVariant &value, int role)
Qt::ItemFlags flags (const QModelIndex &index) const
Static Public Attributes
static const int LayerIdRole = Qt::UserRole + 1
Protected Slots
void removeLayers (const QStringList layerIds)
void addLayers (QList< QgsMapLayer * > layers)
Protected Attributes
QList< QgsMapLayer * > mLayers
QMap< QString, Qt::CheckState > mLayersChecked
bool mItemCheckable
Detailed Description
The QgsMapLayerModel class is a model to display layers in widgets.
See also
QgsMapLayerProxyModel to sort and/filter the layers
QgsFieldModel to combine in with a field selector.
Note
added in 2.3
Definition at line 32 of file qgsmaplayermodel.h.
Constructor & Destructor Documentation
QgsMapLayerModel::QgsMapLayerModel (QObject * parent = 0) explicit
QgsMapLayerModel creates a model to display layers in widgets.
Definition at line 35 of file qgsmaplayermodel.cpp.
References addLayers(), QgsMapLayerRegistry::instance(), and removeLayers().
QgsMapLayerModel::QgsMapLayerModel (QList< QgsMapLayer * > layers, QObject * parent = 0) explicit
QgsMapLayerModel creates a model to display a specific list of layers in a widget.
Definition at line 26 of file qgsmaplayermodel.cpp.
References addLayers(), QgsMapLayerRegistry::instance(), and removeLayers().
Member Function Documentation
void QgsMapLayerModel::addLayers (QList< QgsMapLayer * > layers) protected slot
Definition at line 95 of file qgsmaplayermodel.cpp.
References QgsMapLayer::id(), mLayers, and mLayersChecked.
Referenced by QgsMapLayerModel().
void QgsMapLayerModel::checkAll (Qt::CheckState checkState)
checkAll changes the checkstate for all the layers
Definition at line 50 of file qgsmaplayermodel.cpp.
References index(), mLayers, and mLayersChecked.
int QgsMapLayerModel::columnCount (const QModelIndex & parent) const
Definition at line 129 of file qgsmaplayermodel.cpp.
QVariant QgsMapLayerModel::data (const QModelIndex & index, int role) const
Definition at line 135 of file qgsmaplayermodel.cpp.
References QgsVectorLayer::geometryType(), QgsApplication::getThemeIcon(), QgsMapLayer::id(), LayerIdRole, QGis::Line, mItemCheckable, mLayersChecked, QgsMapLayer::name(), QGis::NoGeometry, QGis::Point, QGis::Polygon, QgsMapLayer::RasterLayer, QgsMapLayer::type(), and QgsMapLayer::VectorLayer.
Qt::ItemFlags QgsMapLayerModel::flags (const QModelIndex & index) const
Definition at line 215 of file qgsmaplayermodel.cpp.
References mItemCheckable.
QModelIndex QgsMapLayerModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Definition at line 106 of file qgsmaplayermodel.cpp.
References mLayers.
Referenced by checkAll(), indexFromLayer(), and removeLayers().
QModelIndex QgsMapLayerModel::indexFromLayer (QgsMapLayer * layer)
indexFromLayer returns the model index for a given layer
Definition at line 72 of file qgsmaplayermodel.cpp.
References index(), and mLayers.
Referenced by QgsMapLayerComboBox::setLayer().
bool QgsMapLayerModel::itemsCheckable () inline
returns if the items can be checked or not
Definition at line 60 of file qgsmaplayermodel.h.
QList< QgsMapLayer * > QgsMapLayerModel::layersChecked (Qt::CheckState checkState = Qt::Checked)
layersChecked returns the list of layers which are checked (or unchecked)
Definition at line 59 of file qgsmaplayermodel.cpp.
References QgsMapLayer::id(), mLayers, and mLayersChecked.
QModelIndex QgsMapLayerModel::parent (const QModelIndex & child) const
Definition at line 117 of file qgsmaplayermodel.cpp.
void QgsMapLayerModel::removeLayers (const QStringList layerIds) protected slot
Definition at line 78 of file qgsmaplayermodel.cpp.
References index(), LayerIdRole, mLayers, and mLayersChecked.
Referenced by QgsMapLayerModel().
int QgsMapLayerModel::rowCount (const QModelIndex & parent) const
Definition at line 124 of file qgsmaplayermodel.cpp.
References mLayers.
bool QgsMapLayerModel::setData (const QModelIndex & index, const QVariant & value, int role)
Definition at line 231 of file qgsmaplayermodel.cpp.
References QgsMapLayer::id(), and mLayersChecked.
void QgsMapLayerModel::setItemsCheckable (bool checkable)
setItemsCheckable defines if layers should be selectable in the widget
Definition at line 45 of file qgsmaplayermodel.cpp.
References mItemCheckable.
Member Data Documentation
const int QgsMapLayerModel::LayerIdRole = Qt::UserRole + 1 static
Definition at line 36 of file qgsmaplayermodel.h.
Referenced by data(), and removeLayers().
bool QgsMapLayerModel::mItemCheckable protected
Definition at line 75 of file qgsmaplayermodel.h.
Referenced by data(), flags(), and setItemsCheckable().
QList<QgsMapLayer*> QgsMapLayerModel::mLayers protected
Definition at line 73 of file qgsmaplayermodel.h.
Referenced by addLayers(), checkAll(), index(), indexFromLayer(), layersChecked(), removeLayers(), and rowCount().
QMap<QString, Qt::CheckState> QgsMapLayerModel::mLayersChecked protected
Definition at line 74 of file qgsmaplayermodel.h.
Referenced by addLayers(), checkAll(), data(), layersChecked(), removeLayers(), and setData().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaplayermodel.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmaplayermodel.cpp