QGIS API Documentation: QgsRenderContext Class Reference
QgsRenderContext Class Reference
QGIS core library
Contains information about the context of a rendering operation.
#include <qgsrendercontext.h>
Public Member Functions
QgsRenderContext ()
~QgsRenderContext ()
QPainter * painter ()
const QPainter * constPainter () const
const QgsCoordinateTransform * coordinateTransform () const
const QgsRectangle & extent () const
const QgsMapToPixel & mapToPixel () const
double scaleFactor () const
double rasterScaleFactor () const
bool renderingStopped () const
bool forceVectorOutput () const
bool useAdvancedEffects () const
Returns true if advanced effects such as blend modes such be used.
void setUseAdvancedEffects (bool enabled)
Used to enable or disable advanced effects such as blend modes.
bool drawEditingInformation () const
double rendererScale () const
QgsLabelingEngineInterface * labelingEngine () const
Added in QGIS v1.4.
QColor selectionColor () const
Added in QGIS v2.0.
bool showSelection () const
Returns true if vector selections should be shown in the rendered map.
void setCoordinateTransform (const QgsCoordinateTransform *t)
Sets coordinate transformation.
void setMapToPixel (const QgsMapToPixel &mtp)
void setExtent (const QgsRectangle &extent)
void setDrawEditingInformation (bool b)
void setRenderingStopped (bool stopped)
void setScaleFactor (double factor)
void setRasterScaleFactor (double factor)
void setRendererScale (double scale)
void setPainter (QPainter *p)
void setForceVectorOutput (bool force)
Added in QGIS v1.5.
void setLabelingEngine (QgsLabelingEngineInterface *iface)
Added in QGIS v1.4.
void setSelectionColor (const QColor &color)
Added in QGIS v2.0.
void setShowSelection (const bool showSelection)
Sets whether vector selections should be shown in the rendered map.
bool useRenderingOptimization () const
Returns true if the rendering optimization (geometry simplification) can be executed.
void setUseRenderingOptimization (bool enabled)
const QgsVectorSimplifyMethod & vectorSimplifyMethod () const
Added in QGIS v2.4.
void setVectorSimplifyMethod (const QgsVectorSimplifyMethod &simplifyMethod)
Static Public Member Functions
static QgsRenderContext fromMapSettings (const QgsMapSettings &mapSettings)
create initialized QgsRenderContext instance from given QgsMapSettings
Private Attributes
QPainter * mPainter
Painter for rendering operations.
const QgsCoordinateTransform * mCoordTransform
For transformation between coordinate systems.
bool mDrawEditingInformation
True if vertex markers for editing should be drawn.
QgsRectangle mExtent
bool mForceVectorOutput
If true then no rendered vector elements should be cached as image.
bool mUseAdvancedEffects
Flag if advanced visual effects such as blend modes should be used.
QgsMapToPixel mMapToPixel
bool mRenderingStopped
True if the rendering has been canceled.
double mScaleFactor
Factor to scale line widths and point marker sizes.
double mRasterScaleFactor
Factor to scale rasters.
double mRendererScale
Map scale.
QgsLabelingEngineInterface * mLabelingEngine
Labeling engine (can be NULL)
bool mShowSelection
Whether selection should be shown.
QColor mSelectionColor
Color used for features that are marked as selected.
bool mUseRenderingOptimization
True if the rendering optimization (geometry simplification) can be executed.
QgsVectorSimplifyMethod mVectorSimplifyMethod
Simplification object which holds the information about how to simplify the features for fast rendering.
Detailed Description
Contains information about the context of a rendering operation.
The context of a rendering operation defines properties such as the conversion ratio between screen and map units, the extents / bounding box to be rendered etc.
Definition at line 39 of file qgsrendercontext.h.
Constructor & Destructor Documentation
QgsRenderContext::QgsRenderContext ()
Definition at line 23 of file qgsrendercontext.cpp.
References mVectorSimplifyMethod, QgsVectorSimplifyMethod::NoSimplification, and QgsVectorSimplifyMethod::setSimplifyHints().
QgsRenderContext::~QgsRenderContext ()
Definition at line 40 of file qgsrendercontext.cpp.
Member Function Documentation
const QPainter* QgsRenderContext::constPainter () const inline
Definition at line 52 of file qgsrendercontext.h.
const QgsCoordinateTransform* QgsRenderContext::coordinateTransform () const inline
Definition at line 54 of file qgsrendercontext.h.
Referenced by QgsFeatureRendererV2::_getLineString(), QgsFeatureRendererV2::_getPoint(), QgsFeatureRendererV2::_getPolygon(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsVectorLayerRenderer::render(), QgsInvertedPolygonRenderer::renderFeature(), QgsLabel::renderLabel(), and QgsInvertedPolygonRenderer::startRender().
bool QgsRenderContext::drawEditingInformation () const inline
Definition at line 75 of file qgsrendercontext.h.
Referenced by QgsVectorLayerRenderer::drawRendererV2(), and QgsVectorLayerRenderer::drawRendererV2Levels().
const QgsRectangle& QgsRenderContext::extent () const inline
Definition at line 56 of file qgsrendercontext.h.
Referenced by QgsFeatureRendererV2::_getLineString(), QgsFeatureRendererV2::_getPolygon(), QgsPalLabeling::drawLabeling(), QgsVectorLayer::drawLabels(), QgsVectorLayerRenderer::prepareLabeling(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsVectorLayerRenderer::render(), and QgsVectorLayerRenderer::setGeometryCachePointer().
bool QgsRenderContext::forceVectorOutput () const inline
Definition at line 66 of file qgsrendercontext.h.
Referenced by QgsSvgMarkerSymbolLayerV2::renderPoint(), and QgsSimpleMarkerSymbolLayerV2::startRender().
QgsRenderContext QgsRenderContext::fromMapSettings (const QgsMapSettings & mapSettings) static
create initialized QgsRenderContext instance from given QgsMapSettings
Note
added in 2.4
Definition at line 44 of file qgsrendercontext.cpp.
References QgsMapSettings::DrawEditingInfo, QgsMapSettings::DrawSelection, QgsMapSettings::ForceVectorOutput, QgsMapSettings::mapToPixel(), QgsMapSettings::outputDpi(), QgsMapSettings::scale(), QgsMapSettings::selectionColor(), setCoordinateTransform(), setDrawEditingInformation(), setExtent(), setForceVectorOutput(), setMapToPixel(), setRasterScaleFactor(), setRendererScale(), setRenderingStopped(), setScaleFactor(), setSelectionColor(), setShowSelection(), setUseAdvancedEffects(), setUseRenderingOptimization(), QgsMapSettings::testFlag(), QgsMapSettings::UseAdvancedEffects, QgsMapSettings::UseRenderingOptimization, and QgsMapSettings::visibleExtent().
Referenced by QgsComposerMap::drawGrid(), QgsMapRendererJob::drawLabeling(), QgsComposerMap::drawOverviewMapExtent(), QgsComposerShape::drawShapeUsingSymbol(), QgsMapToolIdentify::identifyVectorLayer(), QgsPaperItem::paint(), QgsHighlight::paint(), QgsMapRendererJob::prepareJobs(), and QgsMapTool::searchRadiusMU().
QgsLabelingEngineInterface* QgsRenderContext::labelingEngine () const inline
Added in QGIS v1.4.
Definition at line 80 of file qgsrendercontext.h.
Referenced by QgsVectorLayerRenderer::drawRendererV2(), QgsVectorLayerRenderer::drawRendererV2Levels(), QgsVectorLayerRenderer::prepareDiagrams(), and QgsVectorLayerRenderer::prepareLabeling().
const QgsMapToPixel& QgsRenderContext::mapToPixel () const inline
Definition at line 58 of file qgsrendercontext.h.
Referenced by QgsFeatureRendererV2::_getLineString(), QgsFeatureRendererV2::_getPoint(), QgsFeatureRendererV2::_getPolygon(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsPalLayerSettings::checkMinimumSizeMM(), QgsMapUnitScale::computeMapUnitsPerPixel(), QgsDiagramRendererV2::convertSizeToMapUnits(), QgsPalLabeling::drawLabel(), QgsPalLabeling::drawLabelBackground(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsVectorLayerRenderer::render(), QgsMapRenderer::render(), QgsLabel::renderLabel(), QgsMapTool::searchRadiusMU(), and QgsInvertedPolygonRenderer::startRender().
QPainter* QgsRenderContext::painter () inline
Definition at line 51 of file qgsrendercontext.h.
Referenced by QgsMapRendererJob::cleanupJobs(), QgsPointDisplacementRenderer::drawCircle(), QgsPointDisplacementRenderer::drawGroup(), QgsPalLabeling::drawLabel(), QgsPalLabeling::drawLabelBackground(), QgsPalLabeling::drawLabelBuffer(), QgsPalLabeling::drawLabeling(), QgsPointDisplacementRenderer::drawLabels(), QgsPalLabeling::drawLabelShadow(), QgsVectorFieldSymbolLayer::drawPreviewIcon(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsVectorLayerRenderer::render(), QgsMapRenderer::render(), QgsInvertedPolygonRenderer::renderFeature(), QgsLabel::renderLabel(), QgsEllipseSymbolLayerV2::renderPoint(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsSimpleFillSymbolLayerV2::renderPolygon(), QgsGradientFillSymbolLayerV2::renderPolygon(), QgsShapeburstFillSymbolLayerV2::renderPolygon(), QgsImageFillSymbolLayer::renderPolygon(), QgsSimpleLineSymbolLayerV2::renderPolygonOutline(), QgsSimpleLineSymbolLayerV2::renderPolyline(), QgsFeatureRendererV2::renderVertexMarker(), QgsInvertedPolygonRenderer::startRender(), and QgsInvertedPolygonRenderer::stopRender().
double QgsRenderContext::rasterScaleFactor () const inline
Definition at line 62 of file qgsrendercontext.h.
Referenced by QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology(), QgsSVGFillSymbolLayer::applyPattern(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsPointDisplacementRenderer::drawLabels(), QgsSymbolLayerV2Utils::pixelSizeScaleFactor(), QgsPalLabeling::prepareLayer(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsMapRenderer::render(), QgsLabel::renderLabel(), QgsSimpleMarkerSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsShapeburstFillSymbolLayerV2::renderPolygon(), QgsPalLayerSettings::scaleToPixelContext(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), and QgsSimpleFillSymbolLayerV2::startRender().
double QgsRenderContext::rendererScale () const inline
Definition at line 77 of file qgsrendercontext.h.
Referenced by QgsPointPatternFillSymbolLayer::applyPattern(), QgsMapUnitScale::computeMapUnitsPerPixel(), QgsVectorLayer::drawLabels(), QgsPalLabeling::prepareLayer(), QgsPalLayerSettings::registerFeature(), QgsMapRenderer::render(), QgsVectorLayer::simplifyDrawingCanbeApplied(), QgsEllipseSymbolLayerV2::startRender(), QgsPointDisplacementRenderer::startRender(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsRuleBasedRendererV2::Rule::startRender(), QgsSvgMarkerSymbolLayerV2::startRender(), QgsMarkerLineSymbolLayerV2::startRender(), QgsGradientFillSymbolLayerV2::startRender(), QgsShapeburstFillSymbolLayerV2::startRender(), QgsSVGFillSymbolLayer::startRender(), QgsLinePatternFillSymbolLayer::startRender(), and QgsPointPatternFillSymbolLayer::startRender().
bool QgsRenderContext::renderingStopped () const inline
Definition at line 64 of file qgsrendercontext.h.
Referenced by QgsMapRendererJob::cleanupJobs(), QgsMapRendererCustomPainterJob::doRender(), QgsPalLabeling::drawLabeling(), QgsMapRendererJob::drawNewLabeling(), QgsMapRendererJob::drawOldLabeling(), QgsVectorLayerRenderer::drawRendererV2(), QgsVectorLayerRenderer::drawRendererV2Levels(), QgsMapRenderer::render(), QgsMapRendererParallelJob::renderLayersFinished(), and QgsMapRendererParallelJob::renderLayerStatic().
double QgsRenderContext::scaleFactor () const inline
Definition at line 60 of file qgsrendercontext.h.
Referenced by QgsSVGFillSymbolLayer::applyPattern(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsPalLayerSettings::checkMinimumSizeMM(), QgsDiagramRendererV2::convertSizeToMapUnits(), QgsPalLabeling::drawLabelBackground(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsSymbolLayerV2Utils::pixelSizeScaleFactor(), QgsPalLabeling::prepareLayer(), QgsRasterLayerRenderer::QgsRasterLayerRenderer(), QgsPalLayerSettings::registerFeature(), QgsMapRenderer::render(), QgsLabel::renderLabel(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsPalLayerSettings::scaleToPixelContext(), and QgsMapTool::searchRadiusMU().
QColor QgsRenderContext::selectionColor () const inline
Added in QGIS v2.0.
Definition at line 83 of file qgsrendercontext.h.
Referenced by QgsVectorLayerRenderer::drawRendererV2Levels(), QgsSimpleMarkerSymbolLayerV2::prepareCache(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsFontMarkerSymbolLayerV2::renderPoint(), QgsImageFillSymbolLayer::renderPolygon(), QgsSimpleLineSymbolLayerV2::startRender(), QgsSimpleFillSymbolLayerV2::startRender(), QgsSimpleMarkerSymbolLayerV2::startRender(), QgsGradientFillSymbolLayerV2::startRender(), and QgsShapeburstFillSymbolLayerV2::startRender().
void QgsRenderContext::setCoordinateTransform (const QgsCoordinateTransform * t)
Sets coordinate transformation.
QgsRenderContext does not take ownership
Definition at line 67 of file qgsrendercontext.cpp.
References mCoordTransform.
Referenced by QgsMapRendererJob::drawNewLabeling(), QgsMapRendererJob::drawOldLabeling(), fromMapSettings(), QgsMapRendererJob::prepareJobs(), QgsMapRenderer::render(), and QgsInvertedPolygonRenderer::startRender().
void QgsRenderContext::setDrawEditingInformation (bool b) inline
Definition at line 99 of file qgsrendercontext.h.
Referenced by fromMapSettings(), and QgsMapRenderer::render().
void QgsRenderContext::setExtent (const QgsRectangle & extent) inline
Definition at line 98 of file qgsrendercontext.h.
Referenced by QgsMapRenderer::adjustExtentToSize(), QgsMapRendererJob::drawNewLabeling(), QgsMapRendererJob::drawOldLabeling(), fromMapSettings(), QgsAttributeTableFilterModel::generateListOfVisibleFeatures(), QgsMapRendererJob::prepareJobs(), QgsMapRenderer::render(), and QgsInvertedPolygonRenderer::startRender().
void QgsRenderContext::setForceVectorOutput (bool force) inline
Added in QGIS v1.5.
Definition at line 106 of file qgsrendercontext.h.
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsComposerMap::drawGrid(), QgsComposerMap::drawOverviewMapExtent(), QgsComposerShape::drawShapeUsingSymbol(), fromMapSettings(), QgsPaperItem::paint(), and QgsMapCanvasItem::setRenderContextVariables().
void QgsRenderContext::setLabelingEngine (QgsLabelingEngineInterface * iface) inline
Added in QGIS v1.4.
Definition at line 108 of file qgsrendercontext.h.
Referenced by QgsMapRendererJob::drawLabeling(), QgsMapRendererJob::prepareJobs(), and QgsMapRenderer::render().
void QgsRenderContext::setMapToPixel (const QgsMapToPixel & mtp) inline
Definition at line 97 of file qgsrendercontext.h.
Referenced by QgsMapRenderer::adjustExtentToSize(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsPalLabeling::drawLabelBackground(), fromMapSettings(), QgsAttributeTableFilterModel::generateListOfVisibleFeatures(), and QgsMapRenderer::render().
void QgsRenderContext::setPainter (QPainter * p) inline
Definition at line 104 of file qgsrendercontext.h.
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsMapRendererJob::cleanupJobs(), QgsSymbolLayerV2Utils::createRenderContext(), QgsComposerMap::drawGrid(), QgsPalLabeling::drawLabelBackground(), QgsMapRendererJob::drawLabeling(), QgsComposerMap::drawOverviewMapExtent(), QgsComposerShape::drawShapeUsingSymbol(), QgsPaperItem::paint(), QgsHighlight::paint(), QgsMapRendererJob::prepareJobs(), QgsMapRenderer::render(), and QgsMapCanvasItem::setRenderContextVariables().
void QgsRenderContext::setRasterScaleFactor (double factor) inline
Definition at line 102 of file qgsrendercontext.h.
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsSymbolLayerV2Utils::createRenderContext(), fromMapSettings(), QgsMapRenderer::render(), and QgsMapCanvasItem::setRenderContextVariables().
void QgsRenderContext::setRendererScale (double scale) inline
Definition at line 103 of file qgsrendercontext.h.
Referenced by QgsPointPatternFillSymbolLayer::applyPattern(), QgsVectorLayer::countSymbolFeatures(), fromMapSettings(), QgsAttributeTableFilterModel::generateListOfVisibleFeatures(), QgsMapRenderer::render(), QgsVectorFileWriter::renderContext(), and QgsMapCanvasItem::setRenderContextVariables().
void QgsRenderContext::setRenderingStopped (bool stopped) inline
Definition at line 100 of file qgsrendercontext.h.
Referenced by QgsMapRendererParallelJob::cancel(), QgsMapRendererCustomPainterJob::cancel(), fromMapSettings(), and QgsMapRenderer::render().
void QgsRenderContext::setScaleFactor (double factor) inline
Definition at line 101 of file qgsrendercontext.h.
Referenced by QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsSymbolLayerV2Utils::createRenderContext(), QgsPalLabeling::drawLabelBackground(), fromMapSettings(), QgsMapRenderer::render(), and QgsMapCanvasItem::setRenderContextVariables().
void QgsRenderContext::setSelectionColor (const QColor & color) inline
Added in QGIS v2.0.
Definition at line 110 of file qgsrendercontext.h.
Referenced by fromMapSettings(), and QgsMapRenderer::render().
void QgsRenderContext::setShowSelection (const bool showSelection) inline
Sets whether vector selections should be shown in the rendered map.
Parameters
showSelection set to true if selections should be shown
See also
showSelection
setSelectionColor
Note
Added in QGIS v2.4
Definition at line 118 of file qgsrendercontext.h.
Referenced by fromMapSettings().
void QgsRenderContext::setUseAdvancedEffects (bool enabled) inline
Used to enable or disable advanced effects such as blend modes.
Note
: added in version 1.9
Definition at line 73 of file qgsrendercontext.h.
Referenced by fromMapSettings().
void QgsRenderContext::setUseRenderingOptimization (bool enabled) inline
Definition at line 122 of file qgsrendercontext.h.
Referenced by fromMapSettings().
void QgsRenderContext::setVectorSimplifyMethod (const QgsVectorSimplifyMethod & simplifyMethod) inline
Definition at line 126 of file qgsrendercontext.h.
Referenced by QgsVectorLayerRenderer::render().
bool QgsRenderContext::showSelection () const inline
Returns true if vector selections should be shown in the rendered map.
Returns
true if selections should be shown
See also
setShowSelection
selectionColor
Note
Added in QGIS v2.4
Definition at line 91 of file qgsrendercontext.h.
Referenced by QgsVectorLayerRenderer::drawRendererV2().
bool QgsRenderContext::useAdvancedEffects () const inline
Returns true if advanced effects such as blend modes such be used.
Note
added in 1.9
Definition at line 70 of file qgsrendercontext.h.
Referenced by QgsMapRendererCustomPainterJob::doRender(), QgsPalLabeling::drawLabel(), QgsPalLabeling::drawLabelBackground(), QgsPalLabeling::drawLabelBuffer(), QgsPalLabeling::drawLabelShadow(), QgsVectorLayerRenderer::render(), and QgsMapRenderer::render().
bool QgsRenderContext::useRenderingOptimization () const inline
Returns true if the rendering optimization (geometry simplification) can be executed.
Definition at line 121 of file qgsrendercontext.h.
Referenced by QgsVectorLayer::simplifyDrawingCanbeApplied().
const QgsVectorSimplifyMethod& QgsRenderContext::vectorSimplifyMethod () const inline
Added in QGIS v2.4.
Definition at line 125 of file qgsrendercontext.h.
Referenced by QgsFillSymbolLayerV2::_renderPolygon(), and QgsSimpleLineSymbolLayerV2::renderPolyline().
Member Data Documentation
const QgsCoordinateTransform* QgsRenderContext::mCoordTransform private
For transformation between coordinate systems.
Can be 0 if on-the-fly reprojection is not used
Definition at line 134 of file qgsrendercontext.h.
Referenced by setCoordinateTransform().
bool QgsRenderContext::mDrawEditingInformation private
True if vertex markers for editing should be drawn.
Definition at line 137 of file qgsrendercontext.h.
QgsRectangle QgsRenderContext::mExtent private
Definition at line 139 of file qgsrendercontext.h.
bool QgsRenderContext::mForceVectorOutput private
If true then no rendered vector elements should be cached as image.
Definition at line 142 of file qgsrendercontext.h.
QgsLabelingEngineInterface* QgsRenderContext::mLabelingEngine private
Labeling engine (can be NULL)
Definition at line 162 of file qgsrendercontext.h.
QgsMapToPixel QgsRenderContext::mMapToPixel private
Definition at line 147 of file qgsrendercontext.h.
QPainter* QgsRenderContext::mPainter private
Painter for rendering operations.
Definition at line 131 of file qgsrendercontext.h.
double QgsRenderContext::mRasterScaleFactor private
Factor to scale rasters.
Definition at line 156 of file qgsrendercontext.h.
double QgsRenderContext::mRendererScale private
Map scale.
Definition at line 159 of file qgsrendercontext.h.
bool QgsRenderContext::mRenderingStopped private
True if the rendering has been canceled.
Definition at line 150 of file qgsrendercontext.h.
double QgsRenderContext::mScaleFactor private
Factor to scale line widths and point marker sizes.
Definition at line 153 of file qgsrendercontext.h.
QColor QgsRenderContext::mSelectionColor private
Color used for features that are marked as selected.
Definition at line 168 of file qgsrendercontext.h.
bool QgsRenderContext::mShowSelection private
Whether selection should be shown.
Definition at line 165 of file qgsrendercontext.h.
bool QgsRenderContext::mUseAdvancedEffects private
Flag if advanced visual effects such as blend modes should be used.
True by default
Definition at line 145 of file qgsrendercontext.h.
bool QgsRenderContext::mUseRenderingOptimization private
True if the rendering optimization (geometry simplification) can be executed.
Definition at line 171 of file qgsrendercontext.h.
QgsVectorSimplifyMethod QgsRenderContext::mVectorSimplifyMethod private
Simplification object which holds the information about how to simplify the features for fast rendering.
Definition at line 174 of file qgsrendercontext.h.
Referenced by QgsRenderContext().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsrendercontext.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsrendercontext.cpp