QGIS API Documentation: QgsVectorLayerUndoCommandChangeGeometry Class Reference
QgsVectorLayerUndoCommandChangeGeometry Class Reference
#include <qgsvectorlayerundocommand.h>
Public Member Functions
QgsVectorLayerUndoCommandChangeGeometry (QgsVectorLayerEditBuffer *buffer, QgsFeatureId fid, QgsGeometry *newGeom)
~QgsVectorLayerUndoCommandChangeGeometry ()
virtual void undo ()
virtual void redo ()
virtual int id () const
virtual bool mergeWith (const QUndoCommand *)
Public Member Functions inherited from QgsVectorLayerUndoCommand
QgsVectorLayerUndoCommand (QgsVectorLayerEditBuffer *buffer)
QgsVectorLayer * layer ()
QgsGeometryCache * cache ()
virtual bool mergeWith (QUndoCommand *)
Private Attributes
QgsFeatureId mFid
QgsGeometry * mOldGeom
QgsGeometry * mNewGeom
Additional Inherited Members
Protected Attributes inherited from QgsVectorLayerUndoCommand
QgsVectorLayerEditBuffer * mBuffer
Detailed Description
Definition at line 80 of file qgsvectorlayerundocommand.h.
Constructor & Destructor Documentation
QgsVectorLayerUndoCommandChangeGeometry::QgsVectorLayerUndoCommandChangeGeometry (QgsVectorLayerEditBuffer * buffer, QgsFeatureId fid, QgsGeometry * newGeom)
Definition at line 114 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerUndoCommand::cache(), FID_IS_NEW, QgsGeometryCache::geometry(), QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mChangedGeometries, mFid, mNewGeom, and mOldGeom.
QgsVectorLayerUndoCommandChangeGeometry::~QgsVectorLayerUndoCommandChangeGeometry ()
Definition at line 159 of file qgsvectorlayerundocommand.cpp.
References mNewGeom, and mOldGeom.
Member Function Documentation
int QgsVectorLayerUndoCommandChangeGeometry::id () const virtual
Reimplemented from QgsVectorLayerUndoCommand.
Definition at line 135 of file qgsvectorlayerundocommand.cpp.
Referenced by mergeWith().
bool QgsVectorLayerUndoCommandChangeGeometry::mergeWith (const QUndoCommand * other) virtual
Definition at line 140 of file qgsvectorlayerundocommand.cpp.
References id(), mFid, and mNewGeom.
void QgsVectorLayerUndoCommandChangeGeometry::redo () virtual
Definition at line 202 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerUndoCommand::cache(), QgsGeometryCache::cacheGeometry(), FID_IS_NEW, QgsVectorLayerEditBuffer::geometryChanged(), QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mChangedGeometries, mFid, and mNewGeom.
void QgsVectorLayerUndoCommandChangeGeometry::undo () virtual
Definition at line 165 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerUndoCommand::cache(), QgsGeometryCache::cacheGeometry(), FID_IS_NEW, QgsFeature::geometry(), QgsVectorLayerEditBuffer::geometryChanged(), QgsVectorLayerUndoCommand::layer(), QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mChangedGeometries, mFid, and mOldGeom.
Member Data Documentation
QgsFeatureId QgsVectorLayerUndoCommandChangeGeometry::mFid private
Definition at line 92 of file qgsvectorlayerundocommand.h.
Referenced by mergeWith(), QgsVectorLayerUndoCommandChangeGeometry(), redo(), and undo().
QgsGeometry* QgsVectorLayerUndoCommandChangeGeometry::mNewGeom mutable private
Definition at line 94 of file qgsvectorlayerundocommand.h.
Referenced by mergeWith(), QgsVectorLayerUndoCommandChangeGeometry(), redo(), and ~QgsVectorLayerUndoCommandChangeGeometry().
QgsGeometry* QgsVectorLayerUndoCommandChangeGeometry::mOldGeom private
Definition at line 93 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandChangeGeometry(), undo(), and ~QgsVectorLayerUndoCommandChangeGeometry().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsvectorlayerundocommand.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsvectorlayerundocommand.cpp