QGIS API Documentation: QgsRasterPyramidsOptionsWidget Class Reference
QgsRasterPyramidsOptionsWidget Class Reference
QGIS gui library.
A widget to select format-specific raster saving options.
#include <qgsrasterpyramidsoptionswidget.h>
Public Slots
void apply ()
void checkAllLevels (bool checked)
Signals
void overviewListChanged ()
void someValueChanged ()
Public Member Functions
QgsRasterPyramidsOptionsWidget (QWidget *parent=0, QString provider="gdal")
~QgsRasterPyramidsOptionsWidget ()
QStringList configOptions () const
QgsRasterFormatSaveOptionsWidget * createOptionsWidget ()
const QList< int > overviewList () const
QgsRaster::RasterPyramidsFormat pyramidsFormat () const
QString resamplingMethod () const
void setRasterLayer (QgsRasterLayer *rasterLayer)
void setRasterFileName (const QString &file)
Private Slots
void on_cbxPyramidsLevelsCustom_toggled (bool toggled)
void on_cbxPyramidsFormat_currentIndexChanged (int index)
void setOverviewList ()
void updateUi ()
Private Attributes
QString mProvider
QList< int > mOverviewList
QMap< int, QCheckBox * > mOverviewCheckBoxes
Detailed Description
A widget to select format-specific raster saving options.
Definition at line 29 of file qgsrasterpyramidsoptionswidget.h.
Constructor & Destructor Documentation
QgsRasterPyramidsOptionsWidget::QgsRasterPyramidsOptionsWidget (QWidget * parent = 0, QString provider = "gdal")
Definition at line 31 of file qgsrasterpyramidsoptionswidget.cpp.
References QgsRasterFormatSaveOptionsWidget::ProfileLineEdit, QgsRaster::PyramidsGTiff, and updateUi().
QgsRasterPyramidsOptionsWidget::~QgsRasterPyramidsOptionsWidget ()
Definition at line 43 of file qgsrasterpyramidsoptionswidget.cpp.
Member Function Documentation
void QgsRasterPyramidsOptionsWidget::apply () slot
Definition at line 121 of file qgsrasterpyramidsoptionswidget.cpp.
References mOverviewCheckBoxes, mProvider, and resamplingMethod().
void QgsRasterPyramidsOptionsWidget::checkAllLevels (bool checked) slot
Definition at line 150 of file qgsrasterpyramidsoptionswidget.cpp.
References mOverviewCheckBoxes.
QStringList QgsRasterPyramidsOptionsWidget::configOptions () const inline
Definition at line 39 of file qgsrasterpyramidsoptionswidget.h.
QgsRasterFormatSaveOptionsWidget* QgsRasterPyramidsOptionsWidget::createOptionsWidget () inline
Definition at line 40 of file qgsrasterpyramidsoptionswidget.h.
void QgsRasterPyramidsOptionsWidget::on_cbxPyramidsFormat_currentIndexChanged (int index) private slot
Definition at line 165 of file qgsrasterpyramidsoptionswidget.cpp.
void QgsRasterPyramidsOptionsWidget::on_cbxPyramidsLevelsCustom_toggled (bool toggled) private slot
Definition at line 156 of file qgsrasterpyramidsoptionswidget.cpp.
References mOverviewCheckBoxes, and setOverviewList().
const QList<int> QgsRasterPyramidsOptionsWidget::overviewList () const inline
Definition at line 41 of file qgsrasterpyramidsoptionswidget.h.
Referenced by updateUi().
void QgsRasterPyramidsOptionsWidget::overviewListChanged () signal
Referenced by setOverviewList().
QgsRaster::RasterPyramidsFormat QgsRasterPyramidsOptionsWidget::pyramidsFormat () const inline
Definition at line 42 of file qgsrasterpyramidsoptionswidget.h.
QString QgsRasterPyramidsOptionsWidget::resamplingMethod () const
Definition at line 116 of file qgsrasterpyramidsoptionswidget.cpp.
Referenced by apply().
void QgsRasterPyramidsOptionsWidget::setOverviewList () private slot
Definition at line 171 of file qgsrasterpyramidsoptionswidget.cpp.
References mOverviewCheckBoxes, mOverviewList, overviewListChanged(), and QgsDebugMsg.
Referenced by on_cbxPyramidsLevelsCustom_toggled(), and updateUi().
void QgsRasterPyramidsOptionsWidget::setRasterFileName (const QString & file) inline
Definition at line 46 of file qgsrasterpyramidsoptionswidget.h.
void QgsRasterPyramidsOptionsWidget::setRasterLayer (QgsRasterLayer * rasterLayer) inline
Definition at line 45 of file qgsrasterpyramidsoptionswidget.h.
void QgsRasterPyramidsOptionsWidget::someValueChanged () signal
Referenced by updateUi().
void QgsRasterPyramidsOptionsWidget::updateUi () private slot
Definition at line 48 of file qgsrasterpyramidsoptionswidget.cpp.
References mOverviewCheckBoxes, mProvider, overviewList(), QgsRasterDataProvider::pyramidResamplingMethods(), setOverviewList(), and someValueChanged().
Referenced by QgsRasterPyramidsOptionsWidget().
Member Data Documentation
QMap< int, QCheckBox* > QgsRasterPyramidsOptionsWidget::mOverviewCheckBoxes private
Definition at line 68 of file qgsrasterpyramidsoptionswidget.h.
Referenced by apply(), checkAllLevels(), on_cbxPyramidsLevelsCustom_toggled(), setOverviewList(), and updateUi().
QList< int > QgsRasterPyramidsOptionsWidget::mOverviewList private
Definition at line 67 of file qgsrasterpyramidsoptionswidget.h.
Referenced by setOverviewList().
QString QgsRasterPyramidsOptionsWidget::mProvider private
Definition at line 66 of file qgsrasterpyramidsoptionswidget.h.
Referenced by apply(), and updateUi().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsrasterpyramidsoptionswidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsrasterpyramidsoptionswidget.cpp