QGIS API Documentation: QgsRasterProjector Class Reference
QgsRasterProjector Class Reference
#include <qgsrasterprojector.h>
Public Member Functions
QgsRasterProjector (QgsCoordinateReferenceSystem theSrcCRS, QgsCoordinateReferenceSystem theDestCRS, int theSrcDatumTransform, int theDestDatumTransform, QgsRectangle theDestExtent, int theDestRows, int theDestCols, double theMaxSrcXRes, double theMaxSrcYRes, QgsRectangle theExtent)
QgsRasterProjector implements approximate projection support for it calculates grid of points in source CRS for target CRS + extent which are used to calculate affine transformation matrices.
QgsRasterProjector (QgsCoordinateReferenceSystem theSrcCRS, QgsCoordinateReferenceSystem theDestCRS, QgsRectangle theDestExtent, int theDestRows, int theDestCols, double theMaxSrcXRes, double theMaxSrcYRes, QgsRectangle theExtent)
QgsRasterProjector (QgsCoordinateReferenceSystem theSrcCRS, QgsCoordinateReferenceSystem theDestCRS, double theMaxSrcXRes, double theMaxSrcYRes, QgsRectangle theExtent)
QgsRasterProjector ()
QgsRasterProjector (const QgsRasterProjector &projector)
Copy constructor.
~QgsRasterProjector ()
The destructor.
QgsRasterProjector & operator= (const QgsRasterProjector &projector)
QgsRasterInterface * clone () const
Clone itself, create deep copy.
int bandCount () const
Get number of bands.
QGis::DataType dataType (int bandNo) const
Returns data type for the band specified by number.
void setCRS (const QgsCoordinateReferenceSystem &theSrcCRS, const QgsCoordinateReferenceSystem &theDestCRS, int srcDatumTransform=-1, int destDatumTransform=-1)
set source and destination CRS
QgsCoordinateReferenceSystem srcCrs () const
Get source CRS.
QgsCoordinateReferenceSystem destCrs () const
Get destination CRS.
void setMaxSrcRes (double theMaxSrcXRes, double theMaxSrcYRes)
set maximum source resolution
QgsRasterBlock * block (int bandNo, const QgsRectangle &extent, int width, int height)
Read block of data using given extent and size.
Public Member Functions inherited from QgsRasterInterface
QgsRasterInterface (QgsRasterInterface *input=0)
virtual ~QgsRasterInterface ()
virtual int capabilities () const
Returns a bitmask containing the supported capabilities.
QString capabilitiesString () const
Returns the above in friendly format.
virtual QGis::DataType srcDataType (int bandNo) const
Returns source data type for the band specified by number, source data type may be shorter than dataType.
virtual QgsRectangle extent ()
Get the extent of the interface.
int dataTypeSize (int bandNo)
virtual int xBlockSize () const
Get block size.
virtual int yBlockSize () const
virtual int xSize () const
Get raster size.
virtual int ySize () const
virtual QString generateBandName (int theBandNumber) const
helper function to create zero padded band names
virtual bool setInput (QgsRasterInterface *input)
Set input.
virtual QgsRasterInterface * input () const
Current input.
virtual bool on () const
Is on/off.
virtual void setOn (bool on)
Set on/off.
virtual const QgsRasterInterface * srcInput () const
Get source / raw input, the first in pipe, usually provider.
virtual QgsRasterInterface * srcInput ()
virtual QgsRasterBandStats bandStatistics (int theBandNo, int theStats=QgsRasterBandStats::All, const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0)
Get band statistics.
virtual bool hasStatistics (int theBandNo, int theStats=QgsRasterBandStats::All, const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0)
Returns true if histogram is available (cached, already calculated).
virtual QgsRasterHistogram histogram (int theBandNo, int theBinCount=0, double theMinimum=std::numeric_limits< double >::quiet_NaN(), double theMaximum=std::numeric_limits< double >::quiet_NaN(), const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0, bool theIncludeOutOfRange=false)
Get histogram.
virtual bool hasHistogram (int theBandNo, int theBinCount, double theMinimum=std::numeric_limits< double >::quiet_NaN(), double theMaximum=std::numeric_limits< double >::quiet_NaN(), const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0, bool theIncludeOutOfRange=false)
Returns true if histogram is available (cached, already calculated), the parameters are the same as in histogram()
virtual void cumulativeCut (int theBandNo, double theLowerCount, double theUpperCount, double &theLowerValue, double &theUpperValue, const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0)
Find values for cumulative pixel count cut.
virtual void writeXML (QDomDocument &doc, QDomElement &parentElem) const
Write base class members to xml.
virtual void readXML (const QDomElement &filterElem)
Sets base class members from xml.
Private Member Functions
QgsRectangle srcExtent ()
get source extent
int srcRows ()
get/set source width/height
int srcCols ()
void setSrcRows (int theRows)
void setSrcCols (int theCols)
bool srcRowCol (int theDestRow, int theDestCol, int *theSrcRow, int *theSrcCol, const QgsCoordinateTransform *ct)
Get source row and column indexes for current source extent and resolution If source pixel is outside source extent theSrcRow and theSrcCol are left unchanged.
int dstRows () const
int dstCols () const
void destPointOnCPMatrix (int theRow, int theCol, double *theX, double *theY)
get destination point for current destination position
int matrixRow (int theDestRow)
Get matrix upper left row/col indexes for destination row/col.
int matrixCol (int theDestCol)
QgsPoint srcPoint (int theRow, int theCol)
get destination point for current matrix position
bool preciseSrcRowCol (int theDestRow, int theDestCol, int *theSrcRow, int *theSrcCol, const QgsCoordinateTransform *ct)
Get precise source row and column indexes for current source extent and resolution.
bool approximateSrcRowCol (int theDestRow, int theDestCol, int *theSrcRow, int *theSrcCol)
Get approximate source row and column indexes for current source extent and resolution.
void calc ()
Calculate matrix.
void insertRows (const QgsCoordinateTransform *ct)
insert rows to matrix
void insertCols (const QgsCoordinateTransform *ct)
insert columns to matrix
void calcCP (int theRow, int theCol, const QgsCoordinateTransform *ct)
bool calcRow (int theRow, const QgsCoordinateTransform *ct)
calculate matrix row
bool calcCol (int theCol, const QgsCoordinateTransform *ct)
calculate matrix column
void calcSrcExtent ()
calculate source extent
void calcSrcRowsCols ()
calculate minimum source width and height
bool checkCols (const QgsCoordinateTransform *ct)
check error along columns returns true if within threshold
bool checkRows (const QgsCoordinateTransform *ct)
check error along rows returns true if within threshold
void calcHelper (int theMatrixRow, QgsPoint *thePoints)
Calculate array of src helper points.
void nextHelper ()
Calc / switch helper.
QString cpToString ()
get mCPMatrix as string
Private Attributes
QgsCoordinateReferenceSystem mSrcCRS
Source CRS.
QgsCoordinateReferenceSystem mDestCRS
Destination CRS.
int mSrcDatumTransform
Source datum transformation id (or -1 if none)
int mDestDatumTransform
Destination datum transformation id (or -1 if none)
QgsRectangle mDestExtent
Destination extent.
QgsRectangle mSrcExtent
Source extent.
QgsRectangle mExtent
Source raster extent.
int mDestRows
Number of destination rows.
int mDestCols
Number of destination columns.
double mDestXRes
Destination x resolution.
double mDestYRes
Destination y resolution.
int mSrcRows
Number of source rows.
int mSrcCols
Number of source columns.
double mSrcXRes
Source x resolution.
double mSrcYRes
Source y resolution.
double mDestRowsPerMatrixRow
number of destination rows per matrix row
double mDestColsPerMatrixCol
number of destination cols per matrix col
QList< QList< QgsPoint > > mCPMatrix
Grid of source control points.
QList< QList< bool > > mCPLegalMatrix
Grid of source control points transformation possible indicator.
QgsPoint * pHelperTop
Array of source points for each destination column on top of current CPMatrix grid row.
QgsPoint * pHelperBottom
Array of source points for each destination column on bottom of current CPMatrix grid row.
int mHelperTopRow
Current mHelperTop matrix row.
int mCPCols
Number of mCPMatrix columns.
int mCPRows
Number of mCPMatrix rows.
double mSqrTolerance
Maximum tolerance in destination units.
double mMaxSrcXRes
Maximum source resolution.
double mMaxSrcYRes
bool mApproximate
Use approximation.
Additional Inherited Members
Public Types inherited from QgsRasterInterface
enum Capability {
NoCapabilities = 0, Size = 1 << 1, Create = 1 << 2, Remove = 1 << 3,
BuildPyramids = 1 << 4, Identify = 1 << 5, IdentifyValue = 1 << 6, IdentifyText = 1 << 7,
IdentifyHtml = 1 << 8, IdentifyFeature = 1 << 9
}
If you add to this, please also add to capabilitiesString()
Protected Member Functions inherited from QgsRasterInterface
void initHistogram (QgsRasterHistogram &theHistogram, int theBandNo, int theBinCount=0, double theMinimum=std::numeric_limits< double >::quiet_NaN(), double theMaximum=std::numeric_limits< double >::quiet_NaN(), const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0, bool theIncludeOutOfRange=false)
Fill in histogram defaults if not specified.
void initStatistics (QgsRasterBandStats &theStatistics, int theBandNo, int theStats=QgsRasterBandStats::All, const QgsRectangle &theExtent=QgsRectangle(), int theBinCount=0)
Fill in statistics defaults if not specified.
Protected Attributes inherited from QgsRasterInterface
QgsRasterInterface * mInput
QList< QgsRasterBandStats > mStatistics
List of cached statistics, all bands mixed.
QList< QgsRasterHistogram > mHistograms
List of cached histograms, all bands mixed.
bool mOn
Detailed Description
Definition at line 38 of file qgsrasterprojector.h.
Constructor & Destructor Documentation
QgsRasterProjector::QgsRasterProjector (QgsCoordinateReferenceSystem theSrcCRS, QgsCoordinateReferenceSystem theDestCRS, int theSrcDatumTransform, int theDestDatumTransform, QgsRectangle theDestExtent, int theDestRows, int theDestCols, double theMaxSrcXRes, double theMaxSrcYRes, QgsRectangle theExtent)
QgsRasterProjector implements approximate projection support for it calculates grid of points in source CRS for target CRS + extent which are used to calculate affine transformation matrices.
Definition at line 24 of file qgsrasterprojector.cpp.
References calc(), QgsDebugMsg, and QgsRectangle::toString().
QgsRasterProjector::QgsRasterProjector (QgsCoordinateReferenceSystem theSrcCRS, QgsCoordinateReferenceSystem theDestCRS, QgsRectangle theDestExtent, int theDestRows, int theDestCols, double theMaxSrcXRes, double theMaxSrcYRes, QgsRectangle theExtent)
Definition at line 50 of file qgsrasterprojector.cpp.
References calc(), QgsDebugMsg, and QgsRectangle::toString().
QgsRasterProjector::QgsRasterProjector (QgsCoordinateReferenceSystem theSrcCRS, QgsCoordinateReferenceSystem theDestCRS, double theMaxSrcXRes, double theMaxSrcYRes, QgsRectangle theExtent)
Definition at line 74 of file qgsrasterprojector.cpp.
References QgsDebugMsg.
QgsRasterProjector::QgsRasterProjector ()
Definition at line 91 of file qgsrasterprojector.cpp.
References QgsDebugMsg.
Referenced by clone().
QgsRasterProjector::QgsRasterProjector (const QgsRasterProjector & projector)
Copy constructor.
Definition at line 97 of file qgsrasterprojector.cpp.
References mDestCRS, mDestDatumTransform, mExtent, mMaxSrcXRes, mMaxSrcYRes, mSrcCRS, and mSrcDatumTransform.
QgsRasterProjector::~QgsRasterProjector ()
The destructor.
Definition at line 133 of file qgsrasterprojector.cpp.
References pHelperBottom, and pHelperTop.
Member Function Documentation
bool QgsRasterProjector::approximateSrcRowCol (int theDestRow, int theDestCol, int * theSrcRow, int * theSrcCol) inline private
Get approximate source row and column indexes for current source extent and resolution.
Definition at line 531 of file qgsrasterprojector.cpp.
References QgsRectangle::contains(), destPointOnCPMatrix(), matrixCol(), matrixRow(), mDestExtent, mDestYRes, mExtent, mHelperTopRow, mSrcCols, mSrcExtent, mSrcRows, mSrcXRes, mSrcYRes, nextHelper(), pHelperBottom, pHelperTop, QgsPoint::x(), QgsRectangle::xMinimum(), QgsPoint::y(), and QgsRectangle::yMaximum().
Referenced by srcRowCol().
int QgsRasterProjector::bandCount () const virtual
Get number of bands.
Implements QgsRasterInterface.
Definition at line 139 of file qgsrasterprojector.cpp.
References QgsRasterInterface::bandCount(), and QgsRasterInterface::mInput.
QgsRasterBlock * QgsRasterProjector::block (int bandNo, const QgsRectangle & extent, int width, int height) virtual
Read block of data using given extent and size.
Returns pointer to data. Caller is responsible to free the memory returned.
Parameters
bandNo band number
extent extent of block
width pixel width of block
height pixel height of block
Implements QgsRasterInterface.
Definition at line 767 of file qgsrasterprojector.cpp.
References QgsCoordinateReferenceSystem::authid(), QgsRasterBlock::bits(), QgsRasterInterface::block(), calc(), QgsRasterInterface::dataType(), QgsRasterBlock::dataType(), QgsRasterInterface::extent(), QgsRasterBlock::hasNoData(), QgsRasterBlock::hasNoDataValue(), QgsCoordinateTransformCache::instance(), QgsRasterBlock::isEmpty(), QgsRasterBlock::isNoData(), QgsCoordinateReferenceSystem::isValid(), mApproximate, mDestCols, mDestCRS, mDestDatumTransform, mDestExtent, mDestRows, QgsRasterInterface::mInput, mSrcCols, mSrcCRS, mSrcDatumTransform, QgsRasterBlock::noDataValue(), QgsDebugMsg, QgsDebugMsgLevel, QgsRasterBlock::setIsNoData(), srcCols(), srcExtent(), srcRowCol(), srcRows(), QgsRectangle::toString(), QgsCoordinateTransformCache::transform(), QgsRasterBlock::typeIsNumeric(), and QgsRasterBlock::typeSize().
void QgsRasterProjector::calc () private
Calculate matrix.
Definition at line 161 of file qgsrasterprojector.cpp.
References QgsCoordinateReferenceSystem::authid(), calcHelper(), calcRow(), calcSrcExtent(), calcSrcRowsCols(), QgsRasterInterface::capabilities(), checkCols(), checkRows(), cpToString(), QgsRasterDataProvider::extent(), QgsRectangle::height(), insertCols(), insertRows(), QgsCoordinateTransformCache::instance(), QgsRectangle::isEmpty(), mApproximate, mCPCols, mCPLegalMatrix, mCPMatrix, mCPRows, mDestCols, mDestColsPerMatrixCol, mDestCRS, mDestDatumTransform, mDestExtent, mDestRows, mDestRowsPerMatrixRow, mDestXRes, mDestYRes, mExtent, mHelperTopRow, QgsRasterInterface::mInput, mMaxSrcXRes, mMaxSrcYRes, mSqrTolerance, mSrcCols, mSrcCRS, mSrcDatumTransform, mSrcExtent, mSrcRows, mSrcXRes, mSrcYRes, pHelperBottom, pHelperTop, QgsDebugMsg, QgsDebugMsgLevel, QgsRasterInterface::Size, QgsRasterInterface::srcInput(), QgsCoordinateTransformCache::transform(), QgsRectangle::width(), QgsRasterInterface::xSize(), and QgsRasterInterface::ySize().
Referenced by block(), and QgsRasterProjector().
bool QgsRasterProjector::calcCol (int theCol, const QgsCoordinateTransform * ct) private
calculate matrix column
Definition at line 666 of file qgsrasterprojector.cpp.
References calcCP(), mCPRows, and QgsDebugMsgLevel.
Referenced by insertCols().
void QgsRasterProjector::calcCP (int theRow, int theCol, const QgsCoordinateTransform * ct) private
Definition at line 630 of file qgsrasterprojector.cpp.
References destPointOnCPMatrix(), mCPLegalMatrix, mCPMatrix, and QgsCoordinateTransform::transform().
Referenced by calcCol(), and calcRow().
void QgsRasterProjector::calcHelper (int theMatrixRow, QgsPoint * thePoints) private
Calculate array of src helper points.
Definition at line 434 of file qgsrasterprojector.cpp.
References destPointOnCPMatrix(), matrixCol(), mCPMatrix, mDestCols, mDestExtent, mDestXRes, QgsPoint::setX(), QgsPoint::setY(), QgsPoint::x(), QgsRectangle::xMinimum(), and QgsPoint::y().
Referenced by calc(), and nextHelper().
bool QgsRasterProjector::calcRow (int theRow, const QgsCoordinateTransform * ct) private
calculate matrix row
Definition at line 655 of file qgsrasterprojector.cpp.
References calcCP(), mCPCols, and QgsDebugMsgLevel.
Referenced by calc(), and insertRows().
void QgsRasterProjector::calcSrcExtent () private
calculate source extent
Definition at line 270 of file qgsrasterprojector.cpp.
References QgsRectangle::combineExtentWith(), QgsRectangle::intersect(), QgsRectangle::isEmpty(), mCPCols, mCPLegalMatrix, mCPMatrix, mCPRows, mExtent, mMaxSrcXRes, mMaxSrcYRes, mSrcExtent, QgsDebugMsg, QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsRectangle::setYMaximum(), QgsRectangle::setYMinimum(), QgsRectangle::toString(), QgsPoint::x(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsPoint::y(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by calc().
void QgsRasterProjector::calcSrcRowsCols () private
calculate minimum source width and height
Definition at line 357 of file qgsrasterprojector.cpp.
References QgsRectangle::height(), mCPCols, mCPLegalMatrix, mCPMatrix, mCPRows, mDestCols, mDestRows, mMaxSrcXRes, mMaxSrcYRes, mSrcCols, mSrcExtent, mSrcRows, QgsDebugMsg, QgsPoint::sqrDist(), and QgsRectangle::width().
Referenced by calc().
bool QgsRasterProjector::checkCols (const QgsCoordinateTransform * ct) private
check error along columns returns true if within threshold
Definition at line 677 of file qgsrasterprojector.cpp.
References destPointOnCPMatrix(), mCPCols, mCPLegalMatrix, mCPMatrix, mCPRows, mSqrTolerance, QgsCoordinateTransform::ReverseTransform, QgsPoint::sqrDist(), QgsCoordinateTransform::transform(), QgsPoint::x(), and QgsPoint::y().
Referenced by calc().
bool QgsRasterProjector::checkRows (const QgsCoordinateTransform * ct) private
check error along rows returns true if within threshold
Definition at line 722 of file qgsrasterprojector.cpp.
References destPointOnCPMatrix(), mCPCols, mCPLegalMatrix, mCPMatrix, mCPRows, mSqrTolerance, QgsCoordinateTransform::ReverseTransform, QgsPoint::sqrDist(), QgsCoordinateTransform::transform(), QgsPoint::x(), and QgsPoint::y().
Referenced by calc().
QgsRasterInterface * QgsRasterProjector::clone () const virtual
Clone itself, create deep copy.
Implements QgsRasterInterface.
Definition at line 124 of file qgsrasterprojector.cpp.
References mDestCRS, mDestDatumTransform, mExtent, mMaxSrcXRes, mMaxSrcYRes, mSrcCRS, mSrcDatumTransform, QgsDebugMsg, and QgsRasterProjector().
QString QgsRasterProjector::cpToString () private
get mCPMatrix as string
Definition at line 332 of file qgsrasterprojector.cpp.
References mCPCols, mCPLegalMatrix, mCPMatrix, mCPRows, and QgsPoint::toString().
Referenced by calc().
QGis::DataType QgsRasterProjector::dataType (int bandNo) const virtual
Returns data type for the band specified by number.
Implements QgsRasterInterface.
Definition at line 146 of file qgsrasterprojector.cpp.
References QgsRasterInterface::dataType(), QgsRasterInterface::mInput, and QGis::UnknownDataType.
QgsCoordinateReferenceSystem QgsRasterProjector::destCrs () const inline
Get destination CRS.
Definition at line 96 of file qgsrasterprojector.h.
Referenced by QgsRasterFileWriter::writeDataRaster().
void QgsRasterProjector::destPointOnCPMatrix (int theRow, int theCol, double * theX, double * theY) inline private
get destination point for current destination position
Definition at line 412 of file qgsrasterprojector.cpp.
References QgsRectangle::height(), mCPCols, mCPRows, mDestExtent, QgsRectangle::width(), QgsRectangle::xMinimum(), and QgsRectangle::yMaximum().
Referenced by approximateSrcRowCol(), calcCP(), calcHelper(), checkCols(), and checkRows().
int QgsRasterProjector::dstCols () const inline private
Definition at line 123 of file qgsrasterprojector.h.
int QgsRasterProjector::dstRows () const inline private
Definition at line 122 of file qgsrasterprojector.h.
void QgsRasterProjector::insertCols (const QgsCoordinateTransform * ct) private
insert columns to matrix
Definition at line 610 of file qgsrasterprojector.cpp.
References calcCol(), mCPCols, mCPLegalMatrix, mCPMatrix, and mCPRows.
Referenced by calc().
void QgsRasterProjector::insertRows (const QgsCoordinateTransform * ct) private
insert rows to matrix
Definition at line 588 of file qgsrasterprojector.cpp.
References calcRow(), mCPCols, mCPLegalMatrix, mCPMatrix, mCPRows, and QgsDebugMsgLevel.
Referenced by calc().
int QgsRasterProjector::matrixCol (int theDestCol) inline private
Definition at line 422 of file qgsrasterprojector.cpp.
References mDestColsPerMatrixCol.
Referenced by approximateSrcRowCol(), and calcHelper().
int QgsRasterProjector::matrixRow (int theDestRow) inline private
Get matrix upper left row/col indexes for destination row/col.
Definition at line 418 of file qgsrasterprojector.cpp.
References mDestRowsPerMatrixRow.
Referenced by approximateSrcRowCol().
void QgsRasterProjector::nextHelper () private
Calc / switch helper.
Definition at line 459 of file qgsrasterprojector.cpp.
References calcHelper(), mHelperTopRow, pHelperBottom, and pHelperTop.
Referenced by approximateSrcRowCol().
QgsRasterProjector & QgsRasterProjector::operator= (const QgsRasterProjector & projector)
Definition at line 109 of file qgsrasterprojector.cpp.
References mDestCRS, mDestDatumTransform, mExtent, mMaxSrcXRes, mMaxSrcYRes, mSrcCRS, and mSrcDatumTransform.
bool QgsRasterProjector::preciseSrcRowCol (int theDestRow, int theDestCol, int * theSrcRow, int * theSrcCol, const QgsCoordinateTransform * ct) inline private
Get precise source row and column indexes for current source extent and resolution.
Definition at line 482 of file qgsrasterprojector.cpp.
References QgsRectangle::contains(), mDestExtent, mDestXRes, mDestYRes, mExtent, mSrcCols, mSrcExtent, mSrcRows, mSrcXRes, mSrcYRes, QgsDebugMsgLevel, QgsCoordinateTransform::transformInPlace(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by srcRowCol().
void QgsRasterProjector::setCRS (const QgsCoordinateReferenceSystem & theSrcCRS, const QgsCoordinateReferenceSystem & theDestCRS, int srcDatumTransform = -1, int destDatumTransform = -1)
set source and destination CRS
Definition at line 153 of file qgsrasterprojector.cpp.
References mDestCRS, mDestDatumTransform, mSrcCRS, and mSrcDatumTransform.
Referenced by QgsRasterLayer::draw(), and QgsRasterLayerRenderer::render().
void QgsRasterProjector::setMaxSrcRes (double theMaxSrcXRes, double theMaxSrcYRes) inline
set maximum source resolution
Definition at line 99 of file qgsrasterprojector.h.
void QgsRasterProjector::setSrcCols (int theCols) inline private
Definition at line 114 of file qgsrasterprojector.h.
void QgsRasterProjector::setSrcRows (int theRows) inline private
Definition at line 113 of file qgsrasterprojector.h.
int QgsRasterProjector::srcCols () inline private
Definition at line 112 of file qgsrasterprojector.h.
Referenced by block().
QgsCoordinateReferenceSystem QgsRasterProjector::srcCrs () const inline
Get source CRS.
Definition at line 93 of file qgsrasterprojector.h.
Referenced by QgsRasterFileWriter::writeDataRaster().
QgsRectangle QgsRasterProjector::srcExtent () inline private
get source extent
Definition at line 108 of file qgsrasterprojector.h.
Referenced by block().
QgsPoint QgsRasterProjector::srcPoint (int theRow, int theCol) private
get destination point for current matrix position
Definition at line 427 of file qgsrasterprojector.cpp.
bool QgsRasterProjector::srcRowCol (int theDestRow, int theDestCol, int * theSrcRow, int * theSrcCol, const QgsCoordinateTransform * ct) private
Get source row and column indexes for current source extent and resolution If source pixel is outside source extent theSrcRow and theSrcCol are left unchanged.
Returns
true if inside source
Definition at line 470 of file qgsrasterprojector.cpp.
References approximateSrcRowCol(), mApproximate, and preciseSrcRowCol().
Referenced by block().
int QgsRasterProjector::srcRows () inline private
get/set source width/height
Definition at line 111 of file qgsrasterprojector.h.
Referenced by block().
Member Data Documentation
bool QgsRasterProjector::mApproximate private
Use approximation.
Definition at line 264 of file qgsrasterprojector.h.
Referenced by block(), calc(), and srcRowCol().
int QgsRasterProjector::mCPCols private
Number of mCPMatrix columns.
Definition at line 252 of file qgsrasterprojector.h.
Referenced by calc(), calcRow(), calcSrcExtent(), calcSrcRowsCols(), checkCols(), checkRows(), cpToString(), destPointOnCPMatrix(), insertCols(), and insertRows().
QList< QList<bool> > QgsRasterProjector::mCPLegalMatrix private
Grid of source control points transformation possible indicator.
Definition at line 238 of file qgsrasterprojector.h.
Referenced by calc(), calcCP(), calcSrcExtent(), calcSrcRowsCols(), checkCols(), checkRows(), cpToString(), insertCols(), and insertRows().
QList< QList<QgsPoint> > QgsRasterProjector::mCPMatrix private
Grid of source control points.
Definition at line 234 of file qgsrasterprojector.h.
Referenced by calc(), calcCP(), calcHelper(), calcSrcExtent(), calcSrcRowsCols(), checkCols(), checkRows(), cpToString(), insertCols(), and insertRows().
int QgsRasterProjector::mCPRows private
Number of mCPMatrix rows.
Definition at line 254 of file qgsrasterprojector.h.
Referenced by calc(), calcCol(), calcSrcExtent(), calcSrcRowsCols(), checkCols(), checkRows(), cpToString(), destPointOnCPMatrix(), insertCols(), and insertRows().
int QgsRasterProjector::mDestCols private
Number of destination columns.
Definition at line 207 of file qgsrasterprojector.h.
Referenced by block(), calc(), calcHelper(), and calcSrcRowsCols().
double QgsRasterProjector::mDestColsPerMatrixCol private
number of destination cols per matrix col
Definition at line 231 of file qgsrasterprojector.h.
Referenced by calc(), and matrixCol().
QgsCoordinateReferenceSystem QgsRasterProjector::mDestCRS private
Destination CRS.
Definition at line 186 of file qgsrasterprojector.h.
Referenced by block(), calc(), clone(), operator=(), QgsRasterProjector(), and setCRS().
int QgsRasterProjector::mDestDatumTransform private
Destination datum transformation id (or -1 if none)
Definition at line 192 of file qgsrasterprojector.h.
Referenced by block(), calc(), clone(), operator=(), QgsRasterProjector(), and setCRS().
QgsRectangle QgsRasterProjector::mDestExtent private
Destination extent.
Definition at line 195 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), block(), calc(), calcHelper(), destPointOnCPMatrix(), and preciseSrcRowCol().
int QgsRasterProjector::mDestRows private
Number of destination rows.
Definition at line 204 of file qgsrasterprojector.h.
Referenced by block(), calc(), and calcSrcRowsCols().
double QgsRasterProjector::mDestRowsPerMatrixRow private
number of destination rows per matrix row
Definition at line 228 of file qgsrasterprojector.h.
Referenced by calc(), and matrixRow().
double QgsRasterProjector::mDestXRes private
Destination x resolution.
Definition at line 210 of file qgsrasterprojector.h.
Referenced by calc(), calcHelper(), and preciseSrcRowCol().
double QgsRasterProjector::mDestYRes private
Destination y resolution.
Definition at line 213 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), and preciseSrcRowCol().
QgsRectangle QgsRasterProjector::mExtent private
Source raster extent.
Definition at line 201 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), calcSrcExtent(), clone(), operator=(), preciseSrcRowCol(), and QgsRasterProjector().
int QgsRasterProjector::mHelperTopRow private
Current mHelperTop matrix row.
Definition at line 249 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), and nextHelper().
double QgsRasterProjector::mMaxSrcXRes private
Maximum source resolution.
Definition at line 260 of file qgsrasterprojector.h.
Referenced by calc(), calcSrcExtent(), calcSrcRowsCols(), clone(), operator=(), and QgsRasterProjector().
double QgsRasterProjector::mMaxSrcYRes private
Definition at line 261 of file qgsrasterprojector.h.
Referenced by calc(), calcSrcExtent(), calcSrcRowsCols(), clone(), operator=(), and QgsRasterProjector().
double QgsRasterProjector::mSqrTolerance private
Maximum tolerance in destination units.
Definition at line 257 of file qgsrasterprojector.h.
Referenced by calc(), checkCols(), and checkRows().
int QgsRasterProjector::mSrcCols private
Number of source columns.
Definition at line 219 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), block(), calc(), calcSrcRowsCols(), and preciseSrcRowCol().
QgsCoordinateReferenceSystem QgsRasterProjector::mSrcCRS private
Source CRS.
Definition at line 183 of file qgsrasterprojector.h.
Referenced by block(), calc(), clone(), operator=(), QgsRasterProjector(), and setCRS().
int QgsRasterProjector::mSrcDatumTransform private
Source datum transformation id (or -1 if none)
Definition at line 189 of file qgsrasterprojector.h.
Referenced by block(), calc(), clone(), operator=(), QgsRasterProjector(), and setCRS().
QgsRectangle QgsRasterProjector::mSrcExtent private
Source extent.
Definition at line 198 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), calcSrcExtent(), calcSrcRowsCols(), and preciseSrcRowCol().
int QgsRasterProjector::mSrcRows private
Number of source rows.
Definition at line 216 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), calcSrcRowsCols(), and preciseSrcRowCol().
double QgsRasterProjector::mSrcXRes private
Source x resolution.
Definition at line 222 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), and preciseSrcRowCol().
double QgsRasterProjector::mSrcYRes private
Source y resolution.
Definition at line 225 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), and preciseSrcRowCol().
QgsPoint* QgsRasterProjector::pHelperBottom private
Array of source points for each destination column on bottom of current CPMatrix grid row.
Definition at line 246 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), nextHelper(), and ~QgsRasterProjector().
QgsPoint* QgsRasterProjector::pHelperTop private
Array of source points for each destination column on top of current CPMatrix grid row.
Definition at line 242 of file qgsrasterprojector.h.
Referenced by approximateSrcRowCol(), calc(), nextHelper(), and ~QgsRasterProjector().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/raster/qgsrasterprojector.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/raster/qgsrasterprojector.cpp