QGIS API Documentation: QgsScaleRangeWidget Class Reference
QgsScaleRangeWidget Class Reference
#include <qgsscalerangewidget.h>
Public Slots
void setMinimumScale (double scale)
void setMaximumScale (double scale)
void setScaleRange (double min, double max)
Public Member Functions
QgsScaleRangeWidget (QWidget *parent=0)
~QgsScaleRangeWidget ()
void setMapCanvas (QgsMapCanvas *mapCanvas)
set the map canvas which will be used for the current scale buttons
double minimumScale ()
return the minimum scale
double maximumScale ()
return the maximum scale
double minimumScaleDenom ()
return the minimum scale denominator (= 1 / maximum scale)
double maximumScaleDenom ()
return the maximum scale denominator (= 1 / minimum scale)
void reloadProjectScales ()
call to reload the project scales and apply them to the 2 scales combo boxes
Private Slots
void setMaxScaleFromCanvas ()
void setMinScaleFromCanvas ()
Private Attributes
QgsMapCanvas * mCanvas
pointer to the map canvas used for current buttons.
QGridLayout * mLayout
QLabel * mMaximumScaleIconLabel
QLabel * mMinimumScaleIconLabel
QPushButton * mMaximumScaleSetCurrentPushButton
QPushButton * mMinimumScaleSetCurrentPushButton
QgsScaleComboBox * mMaximumScaleComboBox
QgsScaleComboBox * mMinimumScaleComboBox
Detailed Description
Definition at line 30 of file qgsscalerangewidget.h.
Constructor & Destructor Documentation
QgsScaleRangeWidget::QgsScaleRangeWidget (QWidget * parent = 0) explicit
Definition at line 21 of file qgsscalerangewidget.cpp.
References QgsApplication::getThemePixmap(), mLayout, mMaximumScaleComboBox, mMaximumScaleIconLabel, mMinimumScaleComboBox, mMinimumScaleIconLabel, reloadProjectScales(), and tr.
QgsScaleRangeWidget::~QgsScaleRangeWidget ()
Definition at line 68 of file qgsscalerangewidget.cpp.
Member Function Documentation
double QgsScaleRangeWidget::maximumScale ()
return the maximum scale
Definition at line 125 of file qgsscalerangewidget.cpp.
References mMaximumScaleComboBox, and QgsScaleComboBox::scale().
Referenced by QgsScaleVisibilityDialog::maximumScale(), and minimumScaleDenom().
double QgsScaleRangeWidget::maximumScaleDenom ()
return the maximum scale denominator (= 1 / minimum scale)
Definition at line 135 of file qgsscalerangewidget.cpp.
References minimumScale().
double QgsScaleRangeWidget::minimumScale ()
return the minimum scale
Definition at line 115 of file qgsscalerangewidget.cpp.
References mMinimumScaleComboBox, and QgsScaleComboBox::scale().
Referenced by maximumScaleDenom(), and QgsScaleVisibilityDialog::minimumScale().
double QgsScaleRangeWidget::minimumScaleDenom ()
return the minimum scale denominator (= 1 / maximum scale)
Definition at line 130 of file qgsscalerangewidget.cpp.
References maximumScale().
void QgsScaleRangeWidget::reloadProjectScales ()
call to reload the project scales and apply them to the 2 scales combo boxes
Definition at line 72 of file qgsscalerangewidget.cpp.
References QgsProject::instance(), mMaximumScaleComboBox, mMinimumScaleComboBox, QgsProject::readBoolEntry(), QgsProject::readListEntry(), and QgsScaleComboBox::updateScales().
Referenced by QgsScaleRangeWidget().
void QgsScaleRangeWidget::setMapCanvas (QgsMapCanvas * mapCanvas)
set the map canvas which will be used for the current scale buttons
setMapCanvas set the map canvas which will be used for the current scale buttons if not set, the buttons are hidden.
Definition at line 83 of file qgsscalerangewidget.cpp.
References mCanvas, mLayout, mMaximumScaleSetCurrentPushButton, mMinimumScaleSetCurrentPushButton, setMaxScaleFromCanvas(), setMinScaleFromCanvas(), and tr.
Referenced by QgsScaleVisibilityDialog::QgsScaleVisibilityDialog().
void QgsScaleRangeWidget::setMaximumScale (double scale) slot
Definition at line 120 of file qgsscalerangewidget.cpp.
References mMaximumScaleComboBox, and QgsScaleComboBox::setScale().
Referenced by QgsScaleVisibilityDialog::setMaximumScale(), and setScaleRange().
void QgsScaleRangeWidget::setMaxScaleFromCanvas () private slot
Definition at line 151 of file qgsscalerangewidget.cpp.
References QgsMapCanvas::mapSettings(), mCanvas, mMaximumScaleComboBox, QgsMapSettings::scale(), and QgsScaleComboBox::setScale().
Referenced by setMapCanvas().
void QgsScaleRangeWidget::setMinimumScale (double scale) slot
Definition at line 110 of file qgsscalerangewidget.cpp.
References mMinimumScaleComboBox, and QgsScaleComboBox::setScale().
Referenced by QgsScaleVisibilityDialog::setMinimumScale(), and setScaleRange().
void QgsScaleRangeWidget::setMinScaleFromCanvas () private slot
Definition at line 146 of file qgsscalerangewidget.cpp.
References QgsMapCanvas::mapSettings(), mCanvas, mMinimumScaleComboBox, QgsMapSettings::scale(), and QgsScaleComboBox::setScale().
Referenced by setMapCanvas().
void QgsScaleRangeWidget::setScaleRange (double min, double max) slot
Definition at line 140 of file qgsscalerangewidget.cpp.
References setMaximumScale(), and setMinimumScale().
Member Data Documentation
QgsMapCanvas* QgsScaleRangeWidget::mCanvas private
pointer to the map canvas used for current buttons.
Definition at line 73 of file qgsscalerangewidget.h.
Referenced by setMapCanvas(), setMaxScaleFromCanvas(), and setMinScaleFromCanvas().
QGridLayout* QgsScaleRangeWidget::mLayout private
Definition at line 76 of file qgsscalerangewidget.h.
Referenced by QgsScaleRangeWidget(), and setMapCanvas().
QgsScaleComboBox* QgsScaleRangeWidget::mMaximumScaleComboBox private
Definition at line 81 of file qgsscalerangewidget.h.
Referenced by maximumScale(), QgsScaleRangeWidget(), reloadProjectScales(), setMaximumScale(), and setMaxScaleFromCanvas().
QLabel* QgsScaleRangeWidget::mMaximumScaleIconLabel private
Definition at line 77 of file qgsscalerangewidget.h.
Referenced by QgsScaleRangeWidget().
QPushButton* QgsScaleRangeWidget::mMaximumScaleSetCurrentPushButton private
Definition at line 79 of file qgsscalerangewidget.h.
Referenced by setMapCanvas().
QgsScaleComboBox* QgsScaleRangeWidget::mMinimumScaleComboBox private
Definition at line 82 of file qgsscalerangewidget.h.
Referenced by minimumScale(), QgsScaleRangeWidget(), reloadProjectScales(), setMinimumScale(), and setMinScaleFromCanvas().
QLabel* QgsScaleRangeWidget::mMinimumScaleIconLabel private
Definition at line 78 of file qgsscalerangewidget.h.
Referenced by QgsScaleRangeWidget().
QPushButton* QgsScaleRangeWidget::mMinimumScaleSetCurrentPushButton private
Definition at line 80 of file qgsscalerangewidget.h.
Referenced by setMapCanvas().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsscalerangewidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsscalerangewidget.cpp