QGIS API Documentation: QgsLinePatternFillSymbolLayer Class Reference
QgsLinePatternFillSymbolLayer Class Reference
#include <qgsfillsymbollayerv2.h>
Public Member Functions
QgsLinePatternFillSymbolLayer ()
~QgsLinePatternFillSymbolLayer ()
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
QString ogrFeatureStyleWidth (double widthScaleFactor) const
void setLineAngle (double a)
double lineAngle () const
void setDistance (double d)
double distance () const
void setLineWidth (double w)
double lineWidth () const
void setColor (const QColor &c)
QColor color () const
void setOffset (double offset)
double offset () const
void setDistanceUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit distanceUnit () const
void setDistanceMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & distanceMapUnitScale () const
void setLineWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit lineWidthUnit () const
void setLineWidthMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & lineWidthMapUnitScale () const
void setOffsetUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit offsetUnit () const
void setOffsetMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & offsetMapUnitScale () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
void setMapUnitScale (const QgsMapUnitScale &scale)
QgsMapUnitScale mapUnitScale () const
bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2 * subSymbol ()
Public Member Functions inherited from QgsImageFillSymbolLayer
QgsImageFillSymbolLayer ()
virtual ~QgsImageFillSymbolLayer ()
void renderPolygon (const QPolygonF &points, QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
void setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outlineWidthUnit () const
void setOutlineWidthMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & outlineWidthMapUnitScale () const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual Qt::PenStyle dxfPenStyle () const
Public Member Functions inherited from QgsFillSymbolLayerV2
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Protected Member Functions
void applyDataDefinedSettings (const QgsSymbolV2RenderContext &context)
Protected Member Functions inherited from QgsFillSymbolLayerV2
QgsFillSymbolLayerV2 (bool locked=false)
void _renderPolygon (QPainter *p, const QPolygonF &points, const QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
Default method to render polygon.
Protected Member Functions inherited from QgsSymbolLayerV2
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsFields *fields, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Protected Attributes
double mDistance
Distance (in mm or map units) between lines.
QgsSymbolV2::OutputUnit mDistanceUnit
QgsMapUnitScale mDistanceMapUnitScale
double mLineWidth
Line width (in mm or map units)
QgsSymbolV2::OutputUnit mLineWidthUnit
QgsMapUnitScale mLineWidthMapUnitScale
QColor mColor
double mLineAngle
Vector line angle in degrees (0 = horizontal, counterclockwise)
double mOffset
Offset perpendicular to line direction.
QgsSymbolV2::OutputUnit mOffsetUnit
QgsMapUnitScale mOffsetMapUnitScale
Protected Attributes inherited from QgsImageFillSymbolLayer
QBrush mBrush
double mNextAngle
double mOutlineWidth
Outline width.
QgsSymbolV2::OutputUnit mOutlineWidthUnit
QgsMapUnitScale mOutlineWidthMapUnitScale
QgsLineSymbolV2 * mOutline
Custom outline.
Protected Attributes inherited from QgsFillSymbolLayerV2
double mAngle
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Private Member Functions
void applyPattern (const QgsSymbolV2RenderContext &context, QBrush &brush, double lineAngle, double distance, double lineWidth, const QColor &color)
Applies the svg pattern to the brush.
Private Attributes
QgsLineSymbolV2 * mFillLineSymbol
Fill line.
Additional Inherited Members
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 683 of file qgsfillsymbollayerv2.h.
Constructor & Destructor Documentation
QgsLinePatternFillSymbolLayer::QgsLinePatternFillSymbolLayer ()
Definition at line 2092 of file qgsfillsymbollayerv2.cpp.
References QgsImageFillSymbolLayer::setSubSymbol(), and setSubSymbol().
Referenced by create(), and createFromSld().
QgsLinePatternFillSymbolLayer::~QgsLinePatternFillSymbolLayer ()
Definition at line 2111 of file qgsfillsymbollayerv2.cpp.
References mFillLineSymbol.
Member Function Documentation
void QgsLinePatternFillSymbolLayer::applyDataDefinedSettings (const QgsSymbolV2RenderContext & context) protected virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2678 of file qgsfillsymbollayerv2.cpp.
References applyPattern(), color(), QgsSymbolLayerV2Utils::decodeColor(), distance(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), lineAngle(), lineWidth(), QgsImageFillSymbolLayer::mBrush, mColor, mDistance, mLineAngle, and mLineWidth.
void QgsLinePatternFillSymbolLayer::applyPattern (const QgsSymbolV2RenderContext & context, QBrush & brush, double lineAngle, double distance, double lineWidth, const QColor & color) private
Applies the svg pattern to the brush.
Definition at line 2286 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2RenderContext::alpha(), QgsLineSymbolV2::clone(), QgsSymbolLayerV2::estimateMaxBleed(), QgsSymbolV2RenderContext::feature(), QgsSymbolV2RenderContext::fields(), QgsMarkerLineSymbolLayerV2::interval(), QgsMarkerLineSymbolLayerV2::intervalMapUnitScale(), QgsMarkerLineSymbolLayerV2::intervalUnit(), M_PI, QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), QgsImageFillSymbolLayer::mBrush, mDistanceMapUnitScale, mDistanceUnit, mFillLineSymbol, QgsSymbolV2::MM, mOffset, mOffsetMapUnitScale, mOffsetUnit, QgsSymbolLayerV2Utils::multiplyImageOpacity(), QgsSymbolLayerV2Utils::pixelSizeScaleFactor(), QgsSymbolLayerV2Utils::pointOnLineWithDistance(), qgsDoubleNear(), QgsRenderContext::rasterScaleFactor(), QgsSymbolV2RenderContext::renderContext(), QgsLineSymbolV2::renderPolyline(), QgsRenderContext::scaleFactor(), QgsSymbolV2RenderContext::selected(), QgsRenderContext::setForceVectorOutput(), QgsMarkerLineSymbolLayerV2::setInterval(), QgsRenderContext::setMapToPixel(), QgsRenderContext::setPainter(), QgsRenderContext::setRasterScaleFactor(), QgsRenderContext::setScaleFactor(), QgsSymbolV2::startRender(), QgsSymbolV2::stopRender(), QgsSymbolV2::symbolLayer(), and QgsSymbolV2::symbolLayerCount().
Referenced by applyDataDefinedSettings(), and startRender().
QgsSymbolLayerV2 * QgsLinePatternFillSymbolLayer::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2610 of file qgsfillsymbollayerv2.cpp.
References QgsLineSymbolV2::clone(), create(), mFillLineSymbol, properties(), and setSubSymbol().
QColor QgsLinePatternFillSymbolLayer::color (void) const inline virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 716 of file qgsfillsymbollayerv2.h.
References QgsSymbolLayerV2::mColor.
Referenced by applyDataDefinedSettings(), and create().
QgsSymbolLayerV2 * QgsLinePatternFillSymbolLayer::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 2185 of file qgsfillsymbollayerv2.cpp.
References color(), QgsSymbolLayerV2Utils::decodeColor(), QgsSymbolLayerV2Utils::decodeMapUnitScale(), QgsSymbolLayerV2Utils::decodeOutputUnit(), distance(), lineAngle(), lineWidth(), offset(), QgsLinePatternFillSymbolLayer(), setColor(), QgsSymbolLayerV2::setDataDefinedProperty(), setDistance(), setDistanceMapUnitScale(), setDistanceUnit(), setLineAngle(), setLineWidth(), setLineWidthMapUnitScale(), setLineWidthUnit(), setOffset(), setOffsetMapUnitScale(), setOffsetUnit(), QgsImageFillSymbolLayer::setOutlineWidthMapUnitScale(), and QgsImageFillSymbolLayer::setOutlineWidthUnit().
Referenced by clone(), and QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsLinePatternFillSymbolLayer::createFromSld (QDomElement & element) static
Definition at line 2712 of file qgsfillsymbollayerv2.cpp.
References QgsFillSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::createLineLayerFromSld(), QgsSymbolLayerV2Utils::displacementFromSldElement(), QgsSymbolLayerV2::fillColor(), lineWidth(), offset(), QgsDebugMsg, QgsLinePatternFillSymbolLayer(), QgsSymbolLayerV2Utils::rotationFromSldElement(), setColor(), setDistance(), setLineAngle(), setLineWidth(), setOffset(), setSubSymbol(), size, and QgsSymbolLayerV2Utils::wellKnownMarkerFromSld().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
double QgsLinePatternFillSymbolLayer::distance () const inline
Definition at line 712 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), and create().
const QgsMapUnitScale& QgsLinePatternFillSymbolLayer::distanceMapUnitScale () const inline
Definition at line 724 of file qgsfillsymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsLinePatternFillSymbolLayer::distanceUnit () const inline
Definition at line 721 of file qgsfillsymbollayerv2.h.
double QgsLinePatternFillSymbolLayer::estimateMaxBleed () const virtual
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
Eg, polygons drawn with an outline will draw half the width of the outline outside of the polygon. This amount is estimated, since it may be affected by data defined symbology rules.
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2143 of file qgsfillsymbollayerv2.cpp.
QString QgsLinePatternFillSymbolLayer::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2281 of file qgsfillsymbollayerv2.cpp.
double QgsLinePatternFillSymbolLayer::lineAngle () const inline
Definition at line 710 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), and create().
double QgsLinePatternFillSymbolLayer::lineWidth () const inline
Definition at line 714 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), create(), createFromSld(), and toSld().
const QgsMapUnitScale& QgsLinePatternFillSymbolLayer::lineWidthMapUnitScale () const inline
Definition at line 730 of file qgsfillsymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsLinePatternFillSymbolLayer::lineWidthUnit () const inline
Definition at line 727 of file qgsfillsymbollayerv2.h.
QgsMapUnitScale QgsLinePatternFillSymbolLayer::mapUnitScale () const virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2174 of file qgsfillsymbollayerv2.cpp.
References QgsImageFillSymbolLayer::mapUnitScale(), mDistanceMapUnitScale, mLineWidthMapUnitScale, and mOffsetMapUnitScale.
double QgsLinePatternFillSymbolLayer::offset () const inline
Definition at line 718 of file qgsfillsymbollayerv2.h.
Referenced by create(), and createFromSld().
const QgsMapUnitScale& QgsLinePatternFillSymbolLayer::offsetMapUnitScale () const inline
Definition at line 736 of file qgsfillsymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsLinePatternFillSymbolLayer::offsetUnit () const inline
Definition at line 733 of file qgsfillsymbollayerv2.h.
QString QgsLinePatternFillSymbolLayer::ogrFeatureStyleWidth (double widthScaleFactor) const
Definition at line 2663 of file qgsfillsymbollayerv2.cpp.
References mColor, mDistance, mLineAngle, and mLineWidth.
QgsSymbolV2::OutputUnit QgsLinePatternFillSymbolLayer::outputUnit () const virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2156 of file qgsfillsymbollayerv2.cpp.
References mDistanceUnit, QgsSymbolV2::Mixed, mLineWidthUnit, mOffsetUnit, and QgsImageFillSymbolLayer::outputUnit().
QgsStringMap QgsLinePatternFillSymbolLayer::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2590 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeColor(), QgsSymbolLayerV2Utils::encodeMapUnitScale(), QgsSymbolLayerV2Utils::encodeOutputUnit(), mColor, mDistance, mDistanceMapUnitScale, mDistanceUnit, mLineAngle, mLineWidth, mLineWidthMapUnitScale, mLineWidthUnit, mOffset, mOffsetMapUnitScale, mOffsetUnit, QgsImageFillSymbolLayer::mOutlineWidthMapUnitScale, QgsImageFillSymbolLayer::mOutlineWidthUnit, and QgsSymbolLayerV2::saveDataDefinedProperties().
Referenced by clone().
void QgsLinePatternFillSymbolLayer::setColor (const QColor & c) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2105 of file qgsfillsymbollayerv2.cpp.
References mColor, mFillLineSymbol, and QgsSymbolV2::setColor().
Referenced by create(), and createFromSld().
void QgsLinePatternFillSymbolLayer::setDistance (double d) inline
Definition at line 711 of file qgsfillsymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsLinePatternFillSymbolLayer::setDistanceMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 723 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsLinePatternFillSymbolLayer::setDistanceUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 720 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsLinePatternFillSymbolLayer::setLineAngle (double a) inline
Definition at line 709 of file qgsfillsymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsLinePatternFillSymbolLayer::setLineWidth (double w)
Definition at line 2099 of file qgsfillsymbollayerv2.cpp.
References mFillLineSymbol, mLineWidth, and QgsLineSymbolV2::setWidth().
Referenced by create(), and createFromSld().
void QgsLinePatternFillSymbolLayer::setLineWidthMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 729 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsLinePatternFillSymbolLayer::setLineWidthUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 726 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsLinePatternFillSymbolLayer::setMapUnitScale (const QgsMapUnitScale & scale) virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2166 of file qgsfillsymbollayerv2.cpp.
References mDistanceMapUnitScale, mLineWidthMapUnitScale, mOffsetMapUnitScale, and QgsImageFillSymbolLayer::setMapUnitScale().
void QgsLinePatternFillSymbolLayer::setOffset (double offset) inline
Definition at line 717 of file qgsfillsymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsLinePatternFillSymbolLayer::setOffsetMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 735 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsLinePatternFillSymbolLayer::setOffsetUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 732 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsLinePatternFillSymbolLayer::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2148 of file qgsfillsymbollayerv2.cpp.
References mDistanceUnit, mLineWidthUnit, mOffsetUnit, and QgsImageFillSymbolLayer::setOutputUnit().
bool QgsLinePatternFillSymbolLayer::setSubSymbol (QgsSymbolV2 * symbol) virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2116 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2::Line, mFillLineSymbol, and QgsSymbolV2::type().
Referenced by clone(), createFromSld(), and QgsLinePatternFillSymbolLayer().
void QgsLinePatternFillSymbolLayer::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 2574 of file qgsfillsymbollayerv2.cpp.
References applyPattern(), QgsSymbolV2RenderContext::fields(), QgsImageFillSymbolLayer::mBrush, mColor, mDistance, mFillLineSymbol, mLineAngle, mLineWidth, QgsSymbolLayerV2::prepareExpressions(), QgsSymbolV2RenderContext::renderContext(), QgsRenderContext::rendererScale(), and QgsSymbolV2::startRender().
void QgsLinePatternFillSymbolLayer::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 2586 of file qgsfillsymbollayerv2.cpp.
QgsSymbolV2 * QgsLinePatternFillSymbolLayer::subSymbol () virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2138 of file qgsfillsymbollayerv2.cpp.
References mFillLineSymbol.
void QgsLinePatternFillSymbolLayer::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2620 of file qgsfillsymbollayerv2.cpp.
References QgsFillSymbolLayerV2::angle(), QgsSymbolV2::color(), QgsSymbolLayerV2Utils::createDisplacementElement(), QgsSymbolLayerV2Utils::createGeometryElement(), QgsSymbolLayerV2Utils::createRotationElement(), lineWidth(), mDistance, mFillLineSymbol, mLineAngle, mOffset, QgsSymbolLayerV2Utils::wellKnownMarkerToSld(), and QgsLineSymbolV2::width().
Member Data Documentation
QColor QgsLinePatternFillSymbolLayer::mColor protected
Definition at line 756 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), ogrFeatureStyleWidth(), properties(), setColor(), and startRender().
double QgsLinePatternFillSymbolLayer::mDistance protected
Distance (in mm or map units) between lines.
Definition at line 749 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), ogrFeatureStyleWidth(), properties(), startRender(), and toSld().
QgsMapUnitScale QgsLinePatternFillSymbolLayer::mDistanceMapUnitScale protected
Definition at line 751 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), mapUnitScale(), properties(), and setMapUnitScale().
QgsSymbolV2::OutputUnit QgsLinePatternFillSymbolLayer::mDistanceUnit protected
Definition at line 750 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), outputUnit(), properties(), and setOutputUnit().
QgsLineSymbolV2* QgsLinePatternFillSymbolLayer::mFillLineSymbol private
Fill line.
Definition at line 771 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), clone(), setColor(), setLineWidth(), setSubSymbol(), startRender(), subSymbol(), toSld(), and ~QgsLinePatternFillSymbolLayer().
double QgsLinePatternFillSymbolLayer::mLineAngle protected
Vector line angle in degrees (0 = horizontal, counterclockwise)
Definition at line 758 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), ogrFeatureStyleWidth(), properties(), startRender(), and toSld().
double QgsLinePatternFillSymbolLayer::mLineWidth protected
Line width (in mm or map units)
Definition at line 753 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), ogrFeatureStyleWidth(), properties(), setLineWidth(), and startRender().
QgsMapUnitScale QgsLinePatternFillSymbolLayer::mLineWidthMapUnitScale protected
Definition at line 755 of file qgsfillsymbollayerv2.h.
Referenced by mapUnitScale(), properties(), and setMapUnitScale().
QgsSymbolV2::OutputUnit QgsLinePatternFillSymbolLayer::mLineWidthUnit protected
Definition at line 754 of file qgsfillsymbollayerv2.h.
Referenced by outputUnit(), properties(), and setOutputUnit().
double QgsLinePatternFillSymbolLayer::mOffset protected
Offset perpendicular to line direction.
Definition at line 760 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), properties(), and toSld().
QgsMapUnitScale QgsLinePatternFillSymbolLayer::mOffsetMapUnitScale protected
Definition at line 762 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), mapUnitScale(), properties(), and setMapUnitScale().
QgsSymbolV2::OutputUnit QgsLinePatternFillSymbolLayer::mOffsetUnit protected
Definition at line 761 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), outputUnit(), properties(), and setOutputUnit().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsfillsymbollayerv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsfillsymbollayerv2.cpp