QGIS API Documentation: QgsFillSymbolLayerV2 Class Reference
QgsFillSymbolLayerV2 Class Reference abstract
#include <qgssymbollayerv2.h>
Public Member Functions
virtual void renderPolygon (const QPolygonF &points, QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)=0
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString layerType () const =0
virtual void startRender (QgsSymbolV2RenderContext &context)=0
virtual void stopRender (QgsSymbolV2RenderContext &context)=0
virtual QgsSymbolLayerV2 * clone () const =0
virtual void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
virtual QgsStringMap properties () const =0
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
virtual void setOutputUnit (QgsSymbolV2::OutputUnit unit)
virtual QgsSymbolV2::OutputUnit outputUnit () const
virtual void setMapUnitScale (const QgsMapUnitScale &scale)
virtual QgsMapUnitScale mapUnitScale () const
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
virtual Qt::PenStyle dxfPenStyle () const
Protected Member Functions
QgsFillSymbolLayerV2 (bool locked=false)
void _renderPolygon (QPainter *p, const QPolygonF &points, const QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
Default method to render polygon.
Protected Member Functions inherited from QgsSymbolLayerV2
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsFields *fields, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Protected Attributes
double mAngle
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Additional Inherited Members
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 294 of file qgssymbollayerv2.h.
Constructor & Destructor Documentation
QgsFillSymbolLayerV2::QgsFillSymbolLayerV2 (bool locked = false) protected
Definition at line 209 of file qgssymbollayerv2.cpp.
Member Function Documentation
void QgsFillSymbolLayerV2::_renderPolygon (QPainter * p, const QPolygonF & points, const QList< QPolygonF > * rings, QgsSymbolV2RenderContext & context) protected
Default method to render polygon.
Definition at line 422 of file qgssymbollayerv2.cpp.
References QgsVectorSimplifyMethod::AntialiasingSimplification, QgsAbstractGeometrySimplifier::canbeGeneralizedByDeviceBoundingBox(), QgsSymbolV2RenderContext::renderContext(), QgsVectorSimplifyMethod::simplifyHints(), QgsVectorSimplifyMethod::threshold(), and QgsRenderContext::vectorSimplifyMethod().
Referenced by QgsSimpleFillSymbolLayerV2::renderPolygon(), QgsGradientFillSymbolLayerV2::renderPolygon(), QgsShapeburstFillSymbolLayerV2::renderPolygon(), and QgsImageFillSymbolLayer::renderPolygon().
double QgsFillSymbolLayerV2::angle (void) const inline
Definition at line 302 of file qgssymbollayerv2.h.
Referenced by QgsSVGFillSymbolLayer::create(), QgsSVGFillSymbolLayer::createFromSld(), QgsLinePatternFillSymbolLayer::createFromSld(), QgsSVGFillSymbolLayer::QgsSVGFillSymbolLayer(), QgsGradientFillSymbolLayerV2::setAngle(), QgsSVGFillSymbolLayer::toSld(), and QgsLinePatternFillSymbolLayer::toSld().
void QgsFillSymbolLayerV2::drawPreviewIcon (QgsSymbolV2RenderContext & context, QSize size) virtual
Implements QgsSymbolLayerV2.
Definition at line 414 of file qgssymbollayerv2.cpp.
References renderPolygon(), QgsSymbolLayerV2::startRender(), and QgsSymbolLayerV2::stopRender().
virtual void QgsFillSymbolLayerV2::renderPolygon (const QPolygonF & points, QList< QPolygonF > * rings, QgsSymbolV2RenderContext & context) pure virtual
Implemented in QgsCentroidFillSymbolLayerV2, QgsImageFillSymbolLayer, QgsShapeburstFillSymbolLayerV2, QgsGradientFillSymbolLayerV2, and QgsSimpleFillSymbolLayerV2.
Referenced by drawPreviewIcon(), and QgsFillSymbolV2::renderPolygon().
void QgsFillSymbolLayerV2::setAngle (double angle) inline
Definition at line 301 of file qgssymbollayerv2.h.
References MathUtils::angle().
Referenced by QgsFillSymbolV2::setAngle().
Member Data Documentation
double QgsFillSymbolLayerV2::mAngle protected
Definition at line 309 of file qgssymbollayerv2.h.
Referenced by QgsGradientFillSymbolLayerV2::angle(), QgsSVGFillSymbolLayer::clone(), QgsCentroidFillSymbolLayerV2::clone(), QgsSVGFillSymbolLayer::properties(), QgsSVGFillSymbolLayer::QgsSVGFillSymbolLayer(), QgsImageFillSymbolLayer::renderPolygon(), and QgsSVGFillSymbolLayer::toSld().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2.cpp