QGIS API Documentation: QgsRasterFormatSaveOptionsWidget Class Reference
QgsRasterFormatSaveOptionsWidget Class Reference
QGIS gui library.
A widget to select format-specific raster saving options.
#include <qgsrasterformatsaveoptionswidget.h>
Public Types
enum Type {
Default, Full, Table, LineEdit,
ProfileLineEdit
}
Public Slots
void apply ()
void helpOptions ()
QString validateOptions (bool gui=true, bool reportOk=true)
void updateProfiles ()
Signals
void optionsChanged ()
Public Member Functions
QgsRasterFormatSaveOptionsWidget (QWidget *parent=0, QString format="GTiff", QgsRasterFormatSaveOptionsWidget::Type type=Default, QString provider="gdal")
~QgsRasterFormatSaveOptionsWidget ()
void setFormat (QString format)
void setProvider (QString provider)
void setRasterLayer (QgsRasterLayer *rasterLayer)
void setRasterFileName (const QString &file)
QStringList options () const
void setType (QgsRasterFormatSaveOptionsWidget::Type type=Default)
void setPyramidsFormat (QgsRaster::RasterPyramidsFormat format)
Protected Member Functions
virtual void showEvent (QShowEvent *event)
Private Slots
void on_mProfileNewButton_clicked ()
void on_mProfileDeleteButton_clicked ()
void on_mProfileResetButton_clicked ()
void on_mOptionsAddButton_clicked ()
void on_mOptionsDeleteButton_clicked ()
void on_mOptionsLineEdit_editingFinished ()
void optionsTableChanged ()
void optionsTableEnableDeleteButton ()
void updateOptions ()
void swapOptionsUI (int newIndex=-1)
void updateControls ()
Private Member Functions
QString settingsKey (QString profile) const
QString currentProfileKey () const
QString createOptions (QString profile) const
void deleteCreateOptions (QString profile)
void setCreateOptions ()
void setCreateOptions (QString profile, QString options)
void setCreateOptions (QString profile, QStringList list)
QStringList profiles () const
bool eventFilter (QObject *obj, QEvent *event)
Private Attributes
QString mFormat
QString mProvider
QgsRasterLayer * mRasterLayer
QString mRasterFileName
QMap< QString, QString > mOptionsMap
bool mPyramids
QgsRaster::RasterPyramidsFormat mPyramidsFormat
Static Private Attributes
static QMap< QString, QStringList > mBuiltinProfiles
Detailed Description
A widget to select format-specific raster saving options.
Definition at line 30 of file qgsrasterformatsaveoptionswidget.h.
Member Enumeration Documentation
enum QgsRasterFormatSaveOptionsWidget::Type
Enumerator
Default
Full
Table
LineEdit
ProfileLineEdit
Definition at line 37 of file qgsrasterformatsaveoptionswidget.h.
Constructor & Destructor Documentation
QgsRasterFormatSaveOptionsWidget::QgsRasterFormatSaveOptionsWidget (QWidget * parent = 0, QString format = "GTiff", QgsRasterFormatSaveOptionsWidget::Type type = Default, QString provider = "gdal")
Definition at line 34 of file qgsrasterformatsaveoptionswidget.cpp.
References helpOptions(), mBuiltinProfiles, optionsTableChanged(), QgsDebugMsg, setType(), tr, updateControls(), updateOptions(), updateProfiles(), and validateOptions().
QgsRasterFormatSaveOptionsWidget::~QgsRasterFormatSaveOptionsWidget ()
Definition at line 100 of file qgsrasterformatsaveoptionswidget.cpp.
Member Function Documentation
void QgsRasterFormatSaveOptionsWidget::apply () slot
Definition at line 231 of file qgsrasterformatsaveoptionswidget.cpp.
References setCreateOptions().
QString QgsRasterFormatSaveOptionsWidget::createOptions (QString profile) const private
Definition at line 499 of file qgsrasterformatsaveoptionswidget.cpp.
References settingsKey().
Referenced by updateProfiles(), and validateOptions().
QString QgsRasterFormatSaveOptionsWidget::currentProfileKey () const private
Definition at line 489 of file qgsrasterformatsaveoptionswidget.cpp.
Referenced by on_mOptionsLineEdit_editingFinished(), on_mProfileDeleteButton_clicked(), on_mProfileResetButton_clicked(), options(), optionsTableChanged(), setCreateOptions(), and updateOptions().
void QgsRasterFormatSaveOptionsWidget::deleteCreateOptions (QString profile) private
Definition at line 505 of file qgsrasterformatsaveoptionswidget.cpp.
References settingsKey().
bool QgsRasterFormatSaveOptionsWidget::eventFilter (QObject * obj, QEvent * event) private
Definition at line 578 of file qgsrasterformatsaveoptionswidget.cpp.
References swapOptionsUI(), and tr.
void QgsRasterFormatSaveOptionsWidget::helpOptions () slot
Definition at line 240 of file qgsrasterformatsaveoptionswidget.cpp.
References cast_to_fptr, QgsProviderRegistry::instance(), QgsDialog::layout(), mFormat, mProvider, mPyramids, QgsProviderRegistry::providerLibrary(), and tr.
Referenced by QgsRasterFormatSaveOptionsWidget().
void QgsRasterFormatSaveOptionsWidget::on_mOptionsAddButton_clicked () private slot
Definition at line 457 of file qgsrasterformatsaveoptionswidget.cpp.
void QgsRasterFormatSaveOptionsWidget::on_mOptionsDeleteButton_clicked () private slot
Definition at line 467 of file qgsrasterformatsaveoptionswidget.cpp.
References optionsTableChanged().
void QgsRasterFormatSaveOptionsWidget::on_mOptionsLineEdit_editingFinished () private slot
Definition at line 408 of file qgsrasterformatsaveoptionswidget.cpp.
References currentProfileKey(), and mOptionsMap.
void QgsRasterFormatSaveOptionsWidget::on_mProfileDeleteButton_clicked () private slot
Definition at line 425 of file qgsrasterformatsaveoptionswidget.cpp.
References currentProfileKey(), index, mBuiltinProfiles, and mOptionsMap.
void QgsRasterFormatSaveOptionsWidget::on_mProfileNewButton_clicked () private slot
Definition at line 413 of file qgsrasterformatsaveoptionswidget.cpp.
References mOptionsMap, and tr.
void QgsRasterFormatSaveOptionsWidget::on_mProfileResetButton_clicked () private slot
Definition at line 436 of file qgsrasterformatsaveoptionswidget.cpp.
References currentProfileKey(), mBuiltinProfiles, mOptionsMap, and updateOptions().
QStringList QgsRasterFormatSaveOptionsWidget::options () const
Definition at line 494 of file qgsrasterformatsaveoptionswidget.cpp.
References currentProfileKey(), and mOptionsMap.
Referenced by optionsTableChanged(), and validateOptions().
void QgsRasterFormatSaveOptionsWidget::optionsChanged () signal
Referenced by updateOptions().
void QgsRasterFormatSaveOptionsWidget::optionsTableChanged () private slot
Definition at line 388 of file qgsrasterformatsaveoptionswidget.cpp.
References currentProfileKey(), mOptionsMap, and options().
Referenced by on_mOptionsDeleteButton_clicked(), and QgsRasterFormatSaveOptionsWidget().
void QgsRasterFormatSaveOptionsWidget::optionsTableEnableDeleteButton () private slot
Definition at line 452 of file qgsrasterformatsaveoptionswidget.cpp.
QStringList QgsRasterFormatSaveOptionsWidget::profiles () const private
Definition at line 539 of file qgsrasterformatsaveoptionswidget.cpp.
References mFormat, and mProvider.
Referenced by updateProfiles().
void QgsRasterFormatSaveOptionsWidget::setCreateOptions () private
Definition at line 511 of file qgsrasterformatsaveoptionswidget.cpp.
References currentProfileKey(), mFormat, mOptionsMap, and mProvider.
Referenced by apply(), and setCreateOptions().
void QgsRasterFormatSaveOptionsWidget::setCreateOptions (QString profile, QString options) private
Definition at line 528 of file qgsrasterformatsaveoptionswidget.cpp.
References settingsKey().
void QgsRasterFormatSaveOptionsWidget::setCreateOptions (QString profile, QStringList list) private
Definition at line 534 of file qgsrasterformatsaveoptionswidget.cpp.
References setCreateOptions().
void QgsRasterFormatSaveOptionsWidget::setFormat (QString format)
Definition at line 104 of file qgsrasterformatsaveoptionswidget.cpp.
References mFormat, updateControls(), and updateProfiles().
void QgsRasterFormatSaveOptionsWidget::setProvider (QString provider)
Definition at line 111 of file qgsrasterformatsaveoptionswidget.cpp.
References mProvider, and updateControls().
void QgsRasterFormatSaveOptionsWidget::setPyramidsFormat (QgsRaster::RasterPyramidsFormat format) inline
Definition at line 57 of file qgsrasterformatsaveoptionswidget.h.
void QgsRasterFormatSaveOptionsWidget::setRasterFileName (const QString & file) inline
Definition at line 54 of file qgsrasterformatsaveoptionswidget.h.
References file.
void QgsRasterFormatSaveOptionsWidget::setRasterLayer (QgsRasterLayer * rasterLayer) inline
Definition at line 53 of file qgsrasterformatsaveoptionswidget.h.
QString QgsRasterFormatSaveOptionsWidget::settingsKey (QString profile) const private
Definition at line 480 of file qgsrasterformatsaveoptionswidget.cpp.
References mFormat, and mProvider.
Referenced by createOptions(), deleteCreateOptions(), and setCreateOptions().
void QgsRasterFormatSaveOptionsWidget::setType (QgsRasterFormatSaveOptionsWidget::Type type = Default)
Definition at line 118 of file qgsrasterformatsaveoptionswidget.cpp.
References Full, LineEdit, ProfileLineEdit, swapOptionsUI(), and Table.
Referenced by QgsRasterFormatSaveOptionsWidget().
void QgsRasterFormatSaveOptionsWidget::showEvent (QShowEvent * event) protected virtual
Definition at line 610 of file qgsrasterformatsaveoptionswidget.cpp.
References QgsDebugMsg.
void QgsRasterFormatSaveOptionsWidget::swapOptionsUI (int newIndex = -1) private slot
Definition at line 545 of file qgsrasterformatsaveoptionswidget.cpp.
References updateOptions().
Referenced by eventFilter(), and setType().
void QgsRasterFormatSaveOptionsWidget::updateControls () private slot
Definition at line 570 of file qgsrasterformatsaveoptionswidget.cpp.
References mFormat, and mProvider.
Referenced by QgsRasterFormatSaveOptionsWidget(), setFormat(), and setProvider().
void QgsRasterFormatSaveOptionsWidget::updateOptions () private slot
Definition at line 203 of file qgsrasterformatsaveoptionswidget.cpp.
References currentProfileKey(), mOptionsMap, and optionsChanged().
Referenced by on_mProfileResetButton_clicked(), QgsRasterFormatSaveOptionsWidget(), swapOptionsUI(), and updateProfiles().
void QgsRasterFormatSaveOptionsWidget::updateProfiles () slot
Definition at line 150 of file qgsrasterformatsaveoptionswidget.cpp.
References createOptions(), mBuiltinProfiles, mFormat, mOptionsMap, mProvider, mPyramids, profiles(), and updateOptions().
Referenced by QgsRasterFormatSaveOptionsWidget(), and setFormat().
QString QgsRasterFormatSaveOptionsWidget::validateOptions (bool gui = true, bool reportOk = true) slot
Definition at line 291 of file qgsrasterformatsaveoptionswidget.cpp.
References cast_to_fptr, createOptions(), QgsRasterLayer::dataProvider(), QgsMapLayer::id(), QgsProviderRegistry::instance(), mFormat, mProvider, mPyramids, mPyramidsFormat, mRasterFileName, mRasterLayer, options(), QgsProviderRegistry::providerLibrary(), QgsDebugMsg, and tr.
Referenced by QgsRasterFormatSaveOptionsWidget().
Member Data Documentation
QMap< QString, QStringList > QgsRasterFormatSaveOptionsWidget::mBuiltinProfiles static private
Definition at line 94 of file qgsrasterformatsaveoptionswidget.h.
Referenced by on_mProfileDeleteButton_clicked(), on_mProfileResetButton_clicked(), QgsRasterFormatSaveOptionsWidget(), and updateProfiles().
QString QgsRasterFormatSaveOptionsWidget::mFormat private
Definition at line 89 of file qgsrasterformatsaveoptionswidget.h.
Referenced by helpOptions(), profiles(), setCreateOptions(), setFormat(), settingsKey(), updateControls(), updateProfiles(), and validateOptions().
QMap< QString, QString> QgsRasterFormatSaveOptionsWidget::mOptionsMap private
Definition at line 93 of file qgsrasterformatsaveoptionswidget.h.
Referenced by on_mOptionsLineEdit_editingFinished(), on_mProfileDeleteButton_clicked(), on_mProfileNewButton_clicked(), on_mProfileResetButton_clicked(), options(), optionsTableChanged(), setCreateOptions(), updateOptions(), and updateProfiles().
QString QgsRasterFormatSaveOptionsWidget::mProvider private
Definition at line 90 of file qgsrasterformatsaveoptionswidget.h.
Referenced by helpOptions(), profiles(), setCreateOptions(), setProvider(), settingsKey(), updateControls(), updateProfiles(), and validateOptions().
bool QgsRasterFormatSaveOptionsWidget::mPyramids private
Definition at line 95 of file qgsrasterformatsaveoptionswidget.h.
Referenced by helpOptions(), updateProfiles(), and validateOptions().
QgsRaster::RasterPyramidsFormat QgsRasterFormatSaveOptionsWidget::mPyramidsFormat private
Definition at line 96 of file qgsrasterformatsaveoptionswidget.h.
Referenced by validateOptions().
QString QgsRasterFormatSaveOptionsWidget::mRasterFileName private
Definition at line 92 of file qgsrasterformatsaveoptionswidget.h.
Referenced by validateOptions().
QgsRasterLayer* QgsRasterFormatSaveOptionsWidget::mRasterLayer private
Definition at line 91 of file qgsrasterformatsaveoptionswidget.h.
Referenced by validateOptions().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsrasterformatsaveoptionswidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsrasterformatsaveoptionswidget.cpp