QGIS API Documentation: QgsNetworkReplyParser Class Reference
QgsNetworkReplyParser Class Reference
Multipart QNetworkReply parser.
#include <qgsnetworkreplyparser.h>
Public Types
typedef QMap< QByteArray,
QByteArray > RawHeaderMap
Public Member Functions
QgsNetworkReplyParser (QNetworkReply *reply)
Constructor.
bool isValid () const
Indicates if successfully parsed.
int parts () const
Get number of parts.
QByteArray rawHeader (int part, const QByteArray &headerName) const
Get part header.
QList< RawHeaderMap > headers () const
Get headers.
QByteArray body (int part) const
Get part part body.
QList< QByteArray > bodies () const
Get bodies.
QString error () const
Parsing error.
Static Public Member Functions
static bool isMultipart (QNetworkReply *reply)
Test if reply is multipart.
Private Attributes
QNetworkReply * mReply
bool mValid
QString mError
QList< RawHeaderMap > mHeaders
QList< QByteArray > mBodies
Detailed Description
Multipart QNetworkReply parser.
It seams that Qt does not have currently support for multipart reply and it is not even possible to create QNetworkReply from raw data so we need a class for multipart QNetworkReply parsing.
Definition at line 33 of file qgsnetworkreplyparser.h.
Member Typedef Documentation
typedef QMap<QByteArray, QByteArray> QgsNetworkReplyParser::RawHeaderMap
Definition at line 38 of file qgsnetworkreplyparser.h.
Constructor & Destructor Documentation
QgsNetworkReplyParser::QgsNetworkReplyParser (QNetworkReply * reply)
Constructor.
Parameters
reply
Definition at line 28 of file qgsnetworkreplyparser.cpp.
References headers(), isMultipart(), mBodies, mError, mHeaders, mReply, mValid, QgsDebugMsg, and tr.
Member Function Documentation
QList<QByteArray> QgsNetworkReplyParser::bodies () const inline
Get bodies.
Definition at line 67 of file qgsnetworkreplyparser.h.
QByteArray QgsNetworkReplyParser::body (int part) const inline
Get part part body.
Parameters
part part index
Returns
part body
Definition at line 64 of file qgsnetworkreplyparser.h.
QString QgsNetworkReplyParser::error () const inline
Parsing error.
Definition at line 70 of file qgsnetworkreplyparser.h.
QList< RawHeaderMap > QgsNetworkReplyParser::headers () const inline
Get headers.
Definition at line 59 of file qgsnetworkreplyparser.h.
Referenced by QgsNetworkReplyParser().
bool QgsNetworkReplyParser::isMultipart (QNetworkReply * reply) static
Test if reply is multipart.
Returns
true if reply is multipart
Definition at line 138 of file qgsnetworkreplyparser.cpp.
References QgsDebugMsg.
Referenced by QgsNetworkReplyParser().
bool QgsNetworkReplyParser::isValid () const inline
Indicates if successfully parsed.
Returns
true if successfully parsed
Definition at line 46 of file qgsnetworkreplyparser.h.
int QgsNetworkReplyParser::parts () const inline
Get number of parts.
Returns
number of parts
Definition at line 50 of file qgsnetworkreplyparser.h.
QByteArray QgsNetworkReplyParser::rawHeader (int part, const QByteArray & headerName) const inline
Get part header.
Parameters
part part index
headerName header name
Returns
raw header
Definition at line 56 of file qgsnetworkreplyparser.h.
Member Data Documentation
QList<QByteArray> QgsNetworkReplyParser::mBodies private
Definition at line 87 of file qgsnetworkreplyparser.h.
Referenced by QgsNetworkReplyParser().
QString QgsNetworkReplyParser::mError private
Definition at line 81 of file qgsnetworkreplyparser.h.
Referenced by QgsNetworkReplyParser().
QList< RawHeaderMap > QgsNetworkReplyParser::mHeaders private
Definition at line 84 of file qgsnetworkreplyparser.h.
Referenced by QgsNetworkReplyParser().
QNetworkReply* QgsNetworkReplyParser::mReply private
Definition at line 77 of file qgsnetworkreplyparser.h.
Referenced by QgsNetworkReplyParser().
bool QgsNetworkReplyParser::mValid private
Definition at line 79 of file qgsnetworkreplyparser.h.
Referenced by QgsNetworkReplyParser().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsnetworkreplyparser.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsnetworkreplyparser.cpp