QGIS API Documentation: QgsMapRendererSequentialJob Class Reference
QgsMapRendererSequentialJob Class Reference
Job implementation that renders everything sequentially in one thread.
#include <qgsmaprenderersequentialjob.h>
Public Slots
void internalFinished ()
Public Member Functions
QgsMapRendererSequentialJob (const QgsMapSettings &settings)
~QgsMapRendererSequentialJob ()
virtual void start ()
Start the rendering job and immediately return.
virtual void cancel ()
Stop the rendering job - does not return until the job has terminated.
virtual void waitForFinished ()
Block until the job has finished.
virtual bool isActive () const
Tell whether the rendering job is currently running in background.
virtual QgsLabelingResults * takeLabelingResults ()
Get pointer to internal labeling engine (in order to get access to the results)
virtual QImage renderedImage ()
Get a preview/resulting image.
Public Member Functions inherited from QgsMapRendererQImageJob
QgsMapRendererQImageJob (const QgsMapSettings &settings)
Public Member Functions inherited from QgsMapRendererJob
QgsMapRendererJob (const QgsMapSettings &settings)
virtual ~QgsMapRendererJob ()
Errors errors () const
List of errors that happened during the rendering job - available when the rendering has been finished.
void setCache (QgsMapRendererCache *cache)
Assign a cache to be used for reading and storing rendered images of individual layers.
void setRequestedGeometryCacheForLayers (const QStringList &layerIds)
Set which vector layers should be cached while rendering.
int renderingTime () const
Find out how log it took to finish the job (in miliseconds)
Protected Attributes
QgsMapRendererCustomPainterJob * mInternalJob
QImage mImage
QPainter * mPainter
QgsLabelingResults * mLabelingResults
Protected Attributes inherited from QgsMapRendererJob
QgsMapSettings mSettings
Errors mErrors
QgsMapRendererCache * mCache
QStringList mRequestedGeomCacheForLayers
list of layer IDs for which the geometry cache should be updated
QMap< QString, QgsGeometryCache > mGeometryCaches
map of geometry caches
QTime mRenderingStart
int mRenderingTime
Additional Inherited Members
Public Types inherited from QgsMapRendererJob
typedef QList< Error > Errors
Signals inherited from QgsMapRendererJob
void finished ()
emitted when asynchronous rendering is finished (or canceled).
Protected Member Functions inherited from QgsMapRendererJob
LayerRenderJobs prepareJobs (QPainter *painter, QgsPalLabeling *labelingEngine)
void cleanupJobs (LayerRenderJobs &jobs)
bool needTemporaryImage (QgsMapLayer *ml)
void updateLayerGeometryCaches ()
called when rendering has finished to update all layers' geometry caches
Static Protected Member Functions inherited from QgsMapRendererJob
static bool reprojectToLayerExtent (const QgsCoordinateTransform *ct, bool layerCrsGeographic, QgsRectangle &extent, QgsRectangle &r2)
Convenience function to project an extent into the layer source CRS, but also split it into two extents if it crosses the +/- 180 degree line.
static QImage composeImage (const QgsMapSettings &settings, const LayerRenderJobs &jobs)
static void drawLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext, QgsPalLabeling *labelingEngine, QPainter *painter)
static void drawOldLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext)
static void drawNewLabeling (const QgsMapSettings &settings, QgsRenderContext &renderContext, QgsPalLabeling *labelingEngine)
Detailed Description
Job implementation that renders everything sequentially in one thread.
The resulting map image can be retrieved with renderedImage() function. It is safe to call that function while rendering is active to see preview of the map.
Note
added in 2.4
Definition at line 30 of file qgsmaprenderersequentialjob.h.
Constructor & Destructor Documentation
QgsMapRendererSequentialJob::QgsMapRendererSequentialJob (const QgsMapSettings & settings)
Definition at line 23 of file qgsmaprenderersequentialjob.cpp.
References mImage, QgsMapRendererJob::mSettings, QgsMapSettings::outputImageFormat(), QgsMapSettings::outputSize(), and QgsDebugMsg.
QgsMapRendererSequentialJob::~QgsMapRendererSequentialJob ()
Definition at line 34 of file qgsmaprenderersequentialjob.cpp.
References cancel(), isActive(), mInternalJob, mLabelingResults, mPainter, and QgsDebugMsg.
Member Function Documentation
void QgsMapRendererSequentialJob::cancel () virtual
Stop the rendering job - does not return until the job has terminated.
Does nothing if the rendering is not active.
Implements QgsMapRendererJob.
Definition at line 75 of file qgsmaprenderersequentialjob.cpp.
References QgsMapRendererCustomPainterJob::cancel(), isActive(), mInternalJob, mPainter, and QgsDebugMsg.
Referenced by ~QgsMapRendererSequentialJob().
void QgsMapRendererSequentialJob::internalFinished () slot
Definition at line 117 of file qgsmaprenderersequentialjob.cpp.
References QgsMapRendererJob::errors(), QgsMapRendererJob::finished(), QgsMapRendererJob::mErrors, mInternalJob, mLabelingResults, mPainter, QgsMapRendererJob::mRenderingStart, QgsMapRendererJob::mRenderingTime, QgsDebugMsg, and QgsMapRendererCustomPainterJob::takeLabelingResults().
Referenced by start().
bool QgsMapRendererSequentialJob::isActive () const virtual
Tell whether the rendering job is currently running in background.
Implements QgsMapRendererJob.
Definition at line 94 of file qgsmaprenderersequentialjob.cpp.
References mInternalJob.
Referenced by cancel(), renderedImage(), start(), waitForFinished(), and ~QgsMapRendererSequentialJob().
QImage QgsMapRendererSequentialJob::renderedImage () virtual
Get a preview/resulting image.
Implements QgsMapRendererQImageJob.
Definition at line 107 of file qgsmaprenderersequentialjob.cpp.
References QgsMapRendererJob::composeImage(), isActive(), QgsMapRendererCustomPainterJob::jobs(), QgsMapRendererJob::mCache, mImage, mInternalJob, and QgsMapRendererJob::mSettings.
Referenced by QgsRenderChecker::runTest().
void QgsMapRendererSequentialJob::start () virtual
Start the rendering job and immediately return.
Does nothing if the rendering is already in progress.
Implements QgsMapRendererJob.
Definition at line 51 of file qgsmaprenderersequentialjob.cpp.
References QgsMapRendererJob::finished(), internalFinished(), isActive(), QgsMapRendererJob::mCache, QgsMapRendererJob::mErrors, mImage, mInternalJob, mPainter, QgsMapRendererJob::mRenderingStart, QgsMapRendererJob::mSettings, QgsDebugMsg, QgsMapRendererJob::setCache(), and QgsMapRendererCustomPainterJob::start().
Referenced by QgsRenderChecker::runTest().
QgsLabelingResults * QgsMapRendererSequentialJob::takeLabelingResults () virtual
Get pointer to internal labeling engine (in order to get access to the results)
Implements QgsMapRendererJob.
Definition at line 99 of file qgsmaprenderersequentialjob.cpp.
References mLabelingResults.
void QgsMapRendererSequentialJob::waitForFinished () virtual
Block until the job has finished.
Implements QgsMapRendererJob.
Definition at line 86 of file qgsmaprenderersequentialjob.cpp.
References isActive(), mInternalJob, and QgsMapRendererCustomPainterJob::waitForFinished().
Referenced by QgsRenderChecker::runTest().
Member Data Documentation
QImage QgsMapRendererSequentialJob::mImage protected
Definition at line 54 of file qgsmaprenderersequentialjob.h.
Referenced by QgsMapRendererSequentialJob(), renderedImage(), and start().
QgsMapRendererCustomPainterJob* QgsMapRendererSequentialJob::mInternalJob protected
Definition at line 53 of file qgsmaprenderersequentialjob.h.
Referenced by cancel(), internalFinished(), isActive(), renderedImage(), start(), waitForFinished(), and ~QgsMapRendererSequentialJob().
QgsLabelingResults* QgsMapRendererSequentialJob::mLabelingResults protected
Definition at line 56 of file qgsmaprenderersequentialjob.h.
Referenced by internalFinished(), takeLabelingResults(), and ~QgsMapRendererSequentialJob().
QPainter* QgsMapRendererSequentialJob::mPainter protected
Definition at line 55 of file qgsmaprenderersequentialjob.h.
Referenced by cancel(), internalFinished(), start(), and ~QgsMapRendererSequentialJob().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsmaprenderersequentialjob.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsmaprenderersequentialjob.cpp