QGIS API Documentation: QgsFeatureRequest Class Reference
QgsFeatureRequest Class Reference
This class wraps a request for features to a vector layer (or directly its vector data provider).
#include <qgsfeaturerequest.h>
Public Types
enum Flag { NoFlags = 0, NoGeometry = 1, SubsetOfAttributes = 2, ExactIntersect = 4 }
enum FilterType {
FilterNone, FilterRect, FilterFid, FilterExpression,
FilterFids
}
Public Member Functions
QgsFeatureRequest ()
construct a default request: for all features get attributes and geometries
QgsFeatureRequest (QgsFeatureId fid)
construct a request with feature ID filter
QgsFeatureRequest (const QgsRectangle &rect)
construct a request with rectangle filter
QgsFeatureRequest (const QgsExpression &expr)
construct a request with a filter expression
QgsFeatureRequest (const QgsFeatureRequest &rh)
copy constructor
QgsFeatureRequest & operator= (const QgsFeatureRequest &rh)
~QgsFeatureRequest ()
FilterType filterType () const
QgsFeatureRequest & setFilterRect (const QgsRectangle &rect)
Set rectangle from which features will be taken.
const QgsRectangle & filterRect () const
QgsFeatureRequest & setFilterFid (QgsFeatureId fid)
Set feature ID that should be fetched.
const QgsFeatureId & filterFid () const
QgsFeatureRequest & setFilterFids (QgsFeatureIds fids)
Set feature ID that should be fetched.
const QgsFeatureIds & filterFids () const
QgsFeatureRequest & setFilterExpression (const QString &expression)
Set filter expression. {.
QgsExpression * filterExpression () const
QgsFeatureRequest & setFlags (Flags flags)
Set flags that affect how features will be fetched.
const Flags & flags () const
QgsFeatureRequest & setSubsetOfAttributes (const QgsAttributeList &attrs)
Set a subset of attributes that will be fetched.
const QgsAttributeList & subsetOfAttributes () const
QgsFeatureRequest & setSubsetOfAttributes (const QStringList &attrNames, const QgsFields &fields)
Set a subset of attributes by names that will be fetched.
QgsFeatureRequest & setSimplifyMethod (const QgsSimplifyMethod &simplifyMethod)
Set a simplification method for geometries that will be fetched.
const QgsSimplifyMethod & simplifyMethod () const
Get simplification method for geometries that will be fetched.
bool acceptFeature (const QgsFeature &feature)
Check if a feature is accepted by this requests filter.
Protected Attributes
FilterType mFilter
QgsRectangle mFilterRect
QgsFeatureId mFilterFid
QgsFeatureIds mFilterFids
QgsExpression * mFilterExpression
Flags mFlags
QgsAttributeList mAttrs
QgsSimplifyMethod mSimplifyMethod
Detailed Description
This class wraps a request for features to a vector layer (or directly its vector data provider).
The request may apply a filter to fetch only a particular subset of features. Currently supported filters:
no filter - all features are returned
feature id - only feature that matches given feature id is returned
rectangle - only features that intersect given rectangle should be fetched. For the sake of speed, the intersection is often done only using feature's bounding box. There is a flag ExactIntersect that makes sure that only intersecting features will be returned.
For efficiency, it is also possible to tell provider that some data is not required:
NoGeometry flag
SubsetOfAttributes flag
SimplifyMethod for geometries to fetch
The options may be chained, e.g.: QgsFeatureRequest().setFilterRect(QgsRectangle(0,0,1,1)).setFlags(QgsFeatureRequest::ExactIntersect)
Examples:
fetch all features: QgsFeatureRequest()
fetch all features, only one attribute QgsFeatureRequest().setSubsetOfAttributes(QStringList("myfield"), provider->fieldMap())
fetch all features, without geometries QgsFeatureRequest().setFlags(QgsFeatureRequest::NoGeometry)
fetch only features from particular extent QgsFeatureRequest().setFilterRect(QgsRectangle(0,0,1,1))
fetch only one feature QgsFeatureRequest().setFilterFid(45)
Definition at line 58 of file qgsfeaturerequest.h.
Member Enumeration Documentation
enum QgsFeatureRequest::FilterType
Enumerator
FilterNone
No filter is applied.
FilterRect
Filter using a rectangle, no need to set NoGeometry.
FilterFid
Filter using feature ID.
FilterExpression
Filter using expression.
FilterFids
Filter using feature IDs.
Definition at line 70 of file qgsfeaturerequest.h.
enum QgsFeatureRequest::Flag
Enumerator
NoFlags
NoGeometry
Geometry is not required. It may still be returned if e.g. required for a filter condition.
SubsetOfAttributes
Fetch only a subset of attributes (setSubsetOfAttributes sets this flag)
ExactIntersect
Use exact geometry intersection (slower) instead of bounding boxes.
Definition at line 61 of file qgsfeaturerequest.h.
Constructor & Destructor Documentation
QgsFeatureRequest::QgsFeatureRequest ()
construct a default request: for all features get attributes and geometries
Definition at line 22 of file qgsfeaturerequest.cpp.
QgsFeatureRequest::QgsFeatureRequest (QgsFeatureId fid) explicit
construct a request with feature ID filter
Definition at line 29 of file qgsfeaturerequest.cpp.
QgsFeatureRequest::QgsFeatureRequest (const QgsRectangle & rect) explicit
construct a request with rectangle filter
Definition at line 37 of file qgsfeaturerequest.cpp.
QgsFeatureRequest::QgsFeatureRequest (const QgsExpression & expr) explicit
construct a request with a filter expression
Definition at line 45 of file qgsfeaturerequest.cpp.
QgsFeatureRequest::QgsFeatureRequest (const QgsFeatureRequest & rh)
copy constructor
Definition at line 52 of file qgsfeaturerequest.cpp.
References operator=().
QgsFeatureRequest::~QgsFeatureRequest ()
Definition at line 77 of file qgsfeaturerequest.cpp.
References mFilterExpression.
Member Function Documentation
bool QgsFeatureRequest::acceptFeature (const QgsFeature & feature)
Check if a feature is accepted by this requests filter.
Parameters
feature The feature which will be tested
Returns
true, if the filter accepts the feature
Note
added in 2.1
Definition at line 145 of file qgsfeaturerequest.cpp.
References QgsExpression::evaluate(), FilterExpression, FilterFid, FilterFids, FilterNone, FilterRect, QgsFeature::geometry(), QgsFeature::id(), QgsGeometry::intersects(), mFilter, mFilterExpression, mFilterFid, mFilterFids, and mFilterRect.
Referenced by QgsAttributeTableModel::attributeValueChanged(), QgsAttributeTableModel::featureAdded(), QgsCachedFeatureIterator::fetchFeature(), and QgsVectorLayerFeatureIterator::fetchNextAddedFeature().
QgsExpression* QgsFeatureRequest::filterExpression () const inline
Definition at line 111 of file qgsfeaturerequest.h.
Referenced by QgsVectorLayerFeatureIterator::fetchNextChangedAttributeFeature(), QgsAbstractFeatureIterator::nextFeatureFilterExpression(), and QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator().
const QgsFeatureId& QgsFeatureRequest::filterFid () const inline
Definition at line 103 of file qgsfeaturerequest.h.
Referenced by QgsCacheIndexFeatureId::getCacheIterator(), QgsVectorLayerFeatureIterator::nextFeatureFid(), and QgsCachedFeatureIterator::QgsCachedFeatureIterator().
const QgsFeatureIds& QgsFeatureRequest::filterFids () const inline
Definition at line 107 of file qgsfeaturerequest.h.
Referenced by QgsAbstractFeatureIterator::nextFeatureFilterFids(), and QgsCachedFeatureIterator::QgsCachedFeatureIterator().
const QgsRectangle& QgsFeatureRequest::filterRect () const inline
Definition at line 99 of file qgsfeaturerequest.h.
Referenced by QgsVectorLayerFeatureIterator::fetchNextChangedGeomFeature().
FilterType QgsFeatureRequest::filterType () const inline
Definition at line 94 of file qgsfeaturerequest.h.
Referenced by QgsAttributeTableModel::attributeValueChanged(), QgsAttributeTableModel::featureAdded(), QgsAttributeTableModel::featureDeleted(), QgsVectorLayerFeatureIterator::fetchFeature(), QgsVectorLayerFeatureIterator::fetchNextChangedAttributeFeature(), QgsCacheIndexFeatureId::getCacheIterator(), QgsAbstractFeatureIterator::nextFeature(), QgsCachedFeatureIterator::QgsCachedFeatureIterator(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), and QgsVectorLayerFeatureIterator::rewind().
const Flags& QgsFeatureRequest::flags () const inline
Definition at line 115 of file qgsfeaturerequest.h.
Referenced by QgsVectorLayerCache::checkInformationCovered(), QgsVectorLayerFeatureIterator::fetchFeature(), QgsVectorLayerCache::getFeatures(), QgsVectorLayerFeatureIterator::nextFeatureFid(), QgsVectorLayerFeatureIterator::prepareJoins(), QgsVectorLayerFeatureIterator::prepareSimplification(), QgsAbstractFeatureIterator::prepareSimplification(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), setFlags(), QgsAttributeTableModel::setRequest(), QgsVectorLayerFeatureIterator::useAddedFeature(), and QgsVectorLayerFeatureIterator::useChangedAttributeFeature().
QgsFeatureRequest & QgsFeatureRequest::operator= (const QgsFeatureRequest & rh)
Definition at line 57 of file qgsfeaturerequest.cpp.
References QgsExpression::expression(), mAttrs, mFilter, mFilterExpression, mFilterFid, mFilterFids, mFilterRect, mFlags, and mSimplifyMethod.
Referenced by QgsFeatureRequest().
QgsFeatureRequest & QgsFeatureRequest::setFilterExpression (const QString & expression)
Set filter expression. {.
See also
QgsExpression}
Definition at line 103 of file qgsfeaturerequest.cpp.
References FilterExpression, mFilter, and mFilterExpression.
Referenced by QgsRelation::getRelatedFeaturesRequest().
QgsFeatureRequest & QgsFeatureRequest::setFilterFid (QgsFeatureId fid)
Set feature ID that should be fetched.
Definition at line 89 of file qgsfeaturerequest.cpp.
References FilterFid, mFilter, and mFilterFid.
Referenced by QgsVectorLayer::selectedFeatures(), QgsVectorLayerUndoCommandChangeAttribute::undo(), QgsVectorLayer::updateFeature(), and QgsVectorLayerFeatureIterator::useChangedAttributeFeature().
QgsFeatureRequest & QgsFeatureRequest::setFilterFids (QgsFeatureIds fids)
Set feature ID that should be fetched.
Definition at line 96 of file qgsfeaturerequest.cpp.
References FilterFids, mFilter, and mFilterFids.
Referenced by QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator().
QgsFeatureRequest & QgsFeatureRequest::setFilterRect (const QgsRectangle & rect)
Set rectangle from which features will be taken.
Empty rectangle removes the filter.
Definition at line 82 of file qgsfeaturerequest.cpp.
References FilterRect, mFilter, and mFilterRect.
Referenced by QgsComposerAttributeTable::getFeatureAttributes(), and QgsVectorLayerRenderer::render().
QgsFeatureRequest & QgsFeatureRequest::setFlags (Flags flags)
Set flags that affect how features will be fetched.
Definition at line 111 of file qgsfeaturerequest.cpp.
References flags(), and mFlags.
Referenced by QgsVectorLayerFeatureIterator::FetchJoinInfo::addJoinedAttributesDirect(), QgsComposerAttributeTable::getFeatureAttributes(), QgsVectorLayerCache::getFeatures(), QgsVectorLayerImport::importLayer(), QgsAttributeTableModel::QgsAttributeTableModel(), QgsVectorLayer::selectedFeatures(), QgsAttributeTableModel::setRequest(), QgsVectorLayerUndoCommandChangeAttribute::undo(), QgsVectorLayer::updateFeature(), QgsVectorLayerFeatureIterator::useChangedAttributeFeature(), and QgsVectorFileWriter::writeAsVectorFormat().
QgsFeatureRequest & QgsFeatureRequest::setSimplifyMethod (const QgsSimplifyMethod & simplifyMethod)
Set a simplification method for geometries that will be fetched.
Note
added in 2.2
Definition at line 139 of file qgsfeaturerequest.cpp.
References mSimplifyMethod, and simplifyMethod().
Referenced by QgsVectorLayerRenderer::render().
QgsFeatureRequest & QgsFeatureRequest::setSubsetOfAttributes (const QgsAttributeList & attrs)
Set a subset of attributes that will be fetched.
Empty list means that all attributes are used. To disable fetching attributes, reset the FetchAttributes flag (which is set by default)
Definition at line 117 of file qgsfeaturerequest.cpp.
References mAttrs, mFlags, and SubsetOfAttributes.
Referenced by QgsVectorLayerFeatureIterator::FetchJoinInfo::addJoinedAttributesDirect(), QgsZonalStatistics::calculateStatistics(), QgsTransectSample::createSample(), QgsVectorLayerCache::getFeatures(), QgsVectorLayerImport::importLayer(), QgsVectorLayerFeatureIterator::prepareJoins(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), QgsVectorLayerUndoCommandChangeAttribute::undo(), QgsVectorLayer::updateFeature(), QgsVectorLayerFeatureIterator::useChangedAttributeFeature(), and QgsVectorFileWriter::writeAsVectorFormat().
QgsFeatureRequest & QgsFeatureRequest::setSubsetOfAttributes (const QStringList & attrNames, const QgsFields & fields)
Set a subset of attributes by names that will be fetched.
Definition at line 124 of file qgsfeaturerequest.cpp.
References QgsFields::fieldNameIndex(), mAttrs, mFlags, and SubsetOfAttributes.
const QgsSimplifyMethod& QgsFeatureRequest::simplifyMethod () const inline
Get simplification method for geometries that will be fetched.
Note
added in 2.2
Definition at line 130 of file qgsfeaturerequest.h.
Referenced by QgsAbstractFeatureIterator::ref(), and setSimplifyMethod().
const QgsAttributeList& QgsFeatureRequest::subsetOfAttributes () const inline
Definition at line 120 of file qgsfeaturerequest.h.
Referenced by QgsVectorLayerCache::checkInformationCovered(), QgsVectorLayerCache::getFeatures(), QgsVectorLayerFeatureIterator::prepareJoins(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), and QgsVectorLayerFeatureIterator::useChangedAttributeFeature().
Member Data Documentation
QgsAttributeList QgsFeatureRequest::mAttrs protected
Definition at line 154 of file qgsfeaturerequest.h.
Referenced by operator=(), and setSubsetOfAttributes().
FilterType QgsFeatureRequest::mFilter protected
Definition at line 148 of file qgsfeaturerequest.h.
Referenced by acceptFeature(), operator=(), setFilterExpression(), setFilterFid(), setFilterFids(), and setFilterRect().
QgsExpression* QgsFeatureRequest::mFilterExpression protected
Definition at line 152 of file qgsfeaturerequest.h.
Referenced by acceptFeature(), operator=(), setFilterExpression(), and ~QgsFeatureRequest().
QgsFeatureId QgsFeatureRequest::mFilterFid protected
Definition at line 150 of file qgsfeaturerequest.h.
Referenced by acceptFeature(), operator=(), and setFilterFid().
QgsFeatureIds QgsFeatureRequest::mFilterFids protected
Definition at line 151 of file qgsfeaturerequest.h.
Referenced by acceptFeature(), operator=(), and setFilterFids().
QgsRectangle QgsFeatureRequest::mFilterRect protected
Definition at line 149 of file qgsfeaturerequest.h.
Referenced by acceptFeature(), operator=(), and setFilterRect().
Flags QgsFeatureRequest::mFlags protected
Definition at line 153 of file qgsfeaturerequest.h.
Referenced by operator=(), setFlags(), and setSubsetOfAttributes().
QgsSimplifyMethod QgsFeatureRequest::mSimplifyMethod protected
Definition at line 155 of file qgsfeaturerequest.h.
Referenced by operator=(), and setSimplifyMethod().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsfeaturerequest.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsfeaturerequest.cpp