QGIS API Documentation: QgsXmlUtils Class Reference
QgsXmlUtils Class Reference
Assorted helper methods for reading and writing chunks of XML.
#include <qgsxmlutils.h>
Static Public Member Functions
static QGis::UnitType readMapUnits (const QDomElement &element)
static QgsRectangle readRectangle (const QDomElement &element)
static QDomElement writeMapUnits (QGis::UnitType units, QDomDocument &doc)
static QDomElement writeRectangle (const QgsRectangle &rect, QDomDocument &doc)
Detailed Description
Assorted helper methods for reading and writing chunks of XML.
Definition at line 14 of file qgsxmlutils.h.
Member Function Documentation
QGis::UnitType QgsXmlUtils::readMapUnits (const QDomElement & element) static
Definition at line 9 of file qgsxmlutils.cpp.
References QGis::Degrees, QGis::Feet, QGis::Meters, QGis::NauticalMiles, QgsDebugMsg, and QGis::UnknownUnit.
Referenced by QgsMapSettings::readXML().
QgsRectangle QgsXmlUtils::readRectangle (const QDomElement & element) static
Definition at line 38 of file qgsxmlutils.cpp.
References QgsRectangle::setXMaximum(), QgsRectangle::setXMinimum(), QgsRectangle::setYMaximum(), and QgsRectangle::setYMinimum().
Referenced by QgsMapSettings::readXML().
QDomElement QgsXmlUtils::writeMapUnits (QGis::UnitType units, QDomDocument & doc) static
Definition at line 68 of file qgsxmlutils.cpp.
References QGis::Degrees, QGis::Feet, QGis::Meters, QGis::NauticalMiles, and QGis::UnknownUnit.
Referenced by QgsMapSettings::writeXML().
QDomElement QgsXmlUtils::writeRectangle (const QgsRectangle & rect, QDomDocument & doc) static
Definition at line 96 of file qgsxmlutils.cpp.
References qgsDoubleToString(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by QgsMapSettings::writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsxmlutils.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsxmlutils.cpp