QGIS API Documentation: QgsOWSConnection Class Reference
QgsOWSConnection Class Reference
Connections management.
#include <qgsowsconnection.h>
Public Member Functions
QgsOWSConnection (const QString &theService, const QString &theConnName)
Constructor.
~QgsOWSConnection ()
Destructor.
QString connectionInfo ()
QgsDataSourceURI uri ()
Static Public Member Functions
static QStringList connectionList (const QString &theService)
static void deleteConnection (const QString &theService, const QString &name)
static QString selectedConnection (const QString &theService)
static void setSelectedConnection (const QString &theService, const QString &name)
Public Attributes
QString mConnName
QString mConnectionInfo
Private Attributes
QgsDataSourceURI mUri
QString mService
Detailed Description
Connections management.
Definition at line 41 of file qgsowsconnection.h.
Constructor & Destructor Documentation
QgsOWSConnection::QgsOWSConnection (const QString & theService, const QString & theConnName)
Constructor.
Parameters
theService service name: WMS,WFS,WCS
theConnName connection name
Definition at line 38 of file qgsowsconnection.cpp.
References mConnectionInfo, mConnName, mService, mUri, QgsDebugMsg, QgsDataSourceURI::setParam(), and tr.
QgsOWSConnection::~QgsOWSConnection ()
Destructor.
Definition at line 93 of file qgsowsconnection.cpp.
Member Function Documentation
QString QgsOWSConnection::connectionInfo ()
Definition at line 98 of file qgsowsconnection.cpp.
References mConnectionInfo.
QStringList QgsOWSConnection::connectionList (const QString & theService) static
Definition at line 126 of file qgsowsconnection.cpp.
Referenced by QgsOWSSourceSelect::populateConnectionList().
void QgsOWSConnection::deleteConnection (const QString & theService, const QString & name) static
Definition at line 145 of file qgsowsconnection.cpp.
Referenced by QgsOWSSourceSelect::on_mDeleteButton_clicked().
QString QgsOWSConnection::selectedConnection (const QString & theService) static
Definition at line 133 of file qgsowsconnection.cpp.
Referenced by QgsOWSSourceSelect::setConnectionListPosition().
void QgsOWSConnection::setSelectedConnection (const QString & theService, const QString & name) static
Definition at line 139 of file qgsowsconnection.cpp.
Referenced by QgsOWSSourceSelect::on_mConnectionsComboBox_activated(), and QgsOWSSourceSelect::setConnectionListPosition().
QgsDataSourceURI QgsOWSConnection::uri ()
Definition at line 103 of file qgsowsconnection.cpp.
References mUri.
Member Data Documentation
QString QgsOWSConnection::mConnectionInfo
Definition at line 66 of file qgsowsconnection.h.
Referenced by connectionInfo(), and QgsOWSConnection().
QString QgsOWSConnection::mConnName
Definition at line 65 of file qgsowsconnection.h.
Referenced by QgsOWSConnection().
QString QgsOWSConnection::mService private
Definition at line 70 of file qgsowsconnection.h.
Referenced by QgsOWSConnection().
QgsDataSourceURI QgsOWSConnection::mUri private
Definition at line 69 of file qgsowsconnection.h.
Referenced by QgsOWSConnection(), and uri().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsowsconnection.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsowsconnection.cpp