QGIS API Documentation: QgsUnitSelectionWidget Class Reference
QgsUnitSelectionWidget Class Reference
Widget displaying a combobox allowing the user to choose between millimeter and map units If the user chooses map units, a button appears allowing the specification of minimum and maximum scale.
#include <qgsunitselectionwidget.h>
Signals
void changed ()
Public Member Functions
QgsUnitSelectionWidget (QWidget *parent=0)
void setUnits (const QStringList &units, int mapUnitIdx)
Sets the units which the user can choose from in the combobox.
int getUnit () const
Get the selected unit index.
void setUnit (int unitIndex)
Sets the selected unit index.
QgsMapUnitScale getMapUnitScale () const
Returns the map unit scale.
void setMapUnitScale (const QgsMapUnitScale &scale)
Sets the map unit scale.
Private Slots
void showDialog ()
void toggleUnitRangeButton ()
Private Attributes
QgsMapUnitScaleDialog * mUnitScaleDialog
int mMapUnitIdx
Detailed Description
Widget displaying a combobox allowing the user to choose between millimeter and map units If the user chooses map units, a button appears allowing the specification of minimum and maximum scale.
Definition at line 47 of file qgsunitselectionwidget.h.
Constructor & Destructor Documentation
QgsUnitSelectionWidget::QgsUnitSelectionWidget (QWidget * parent = 0)
Definition at line 70 of file qgsunitselectionwidget.cpp.
References changed(), mMapUnitIdx, mUnitScaleDialog, showDialog(), toggleUnitRangeButton(), and tr.
Member Function Documentation
void QgsUnitSelectionWidget::changed () signal
Referenced by QgsUnitSelectionWidget(), and showDialog().
QgsMapUnitScale QgsUnitSelectionWidget::getMapUnitScale () const inline
Returns the map unit scale.
Definition at line 66 of file qgsunitselectionwidget.h.
int QgsUnitSelectionWidget::getUnit () const inline
Get the selected unit index.
Definition at line 62 of file qgsunitselectionwidget.h.
void QgsUnitSelectionWidget::setMapUnitScale (const QgsMapUnitScale & scale) inline
Sets the map unit scale.
Definition at line 68 of file qgsunitselectionwidget.h.
void QgsUnitSelectionWidget::setUnit (int unitIndex)
Sets the selected unit index.
Definition at line 93 of file qgsunitselectionwidget.cpp.
void QgsUnitSelectionWidget::setUnits (const QStringList & units, int mapUnitIdx)
Sets the units which the user can choose from in the combobox.
mapUnitIdx specifies which entry corresponds to the map units, or -1 if none
Definition at line 85 of file qgsunitselectionwidget.cpp.
References mMapUnitIdx.
void QgsUnitSelectionWidget::showDialog () private slot
Definition at line 100 of file qgsunitselectionwidget.cpp.
References changed(), QgsMapUnitScaleDialog::getMapUnitScale(), QgsMapUnitScale::maxScale, QgsMapUnitScale::minScale, mUnitScaleDialog, and QgsMapUnitScaleDialog::setMapUnitScale().
Referenced by QgsUnitSelectionWidget().
void QgsUnitSelectionWidget::toggleUnitRangeButton () private slot
Definition at line 117 of file qgsunitselectionwidget.cpp.
References mMapUnitIdx.
Referenced by QgsUnitSelectionWidget().
Member Data Documentation
int QgsUnitSelectionWidget::mMapUnitIdx private
Definition at line 53 of file qgsunitselectionwidget.h.
Referenced by QgsUnitSelectionWidget(), setUnits(), and toggleUnitRangeButton().
QgsMapUnitScaleDialog* QgsUnitSelectionWidget::mUnitScaleDialog private
Definition at line 52 of file qgsunitselectionwidget.h.
Referenced by QgsUnitSelectionWidget(), and showDialog().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsunitselectionwidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsunitselectionwidget.cpp