QGIS API Documentation: QgsDataCollectionItem Class Reference
QgsDataCollectionItem Class Reference
A Collection: logical collection of layers or subcollections, e.g.
#include <qgsdataitem.h>
Public Member Functions
QgsDataCollectionItem (QgsDataItem *parent, QString name, QString path=QString::null)
~QgsDataCollectionItem ()
void setPopulated ()
void addChild (QgsDataItem *item)
Public Member Functions inherited from QgsDataItem
QgsDataItem (QgsDataItem::Type type, QgsDataItem *parent, QString name, QString path)
virtual ~QgsDataItem ()
bool hasChildren ()
int rowCount ()
virtual void refresh ()
virtual QVector< QgsDataItem * > createChildren ()
virtual void populate ()
bool isPopulated ()
virtual void addChildItem (QgsDataItem *child, bool refresh=false)
virtual void deleteChildItem (QgsDataItem *child)
virtual QgsDataItem * removeChildItem (QgsDataItem *child)
virtual bool equal (const QgsDataItem *other)
virtual QWidget * paramWidget ()
virtual QList< QAction * > actions ()
virtual bool acceptDrop ()
virtual bool handleDrop (const QMimeData *, Qt::DropAction)
virtual bool setCrs (QgsCoordinateReferenceSystem crs)
virtual Capability capabilities ()
Type type () const
QgsDataItem * parent () const
void setParent (QgsDataItem *parent)
QVector< QgsDataItem * > children () const
QIcon icon () const
QString name () const
QString path () const
void setIcon (QIcon icon)
void setToolTip (QString msg)
QString toolTip () const
Static Public Member Functions
static const QIcon & iconDir ()
static const QIcon & iconDataCollection ()
Static Public Member Functions inherited from QgsDataItem
static int findItem (QVector< QgsDataItem * > items, QgsDataItem *item)
Additional Inherited Members
Public Types inherited from QgsDataItem
enum Type {
Collection, Directory, Layer, Error,
Favourites
}
enum Capability { NoCapabilities = 0, SetCrs = 1 }
Public Slots inherited from QgsDataItem
void emitBeginInsertItems (QgsDataItem *parent, int first, int last)
void emitEndInsertItems ()
void emitBeginRemoveItems (QgsDataItem *parent, int first, int last)
void emitEndRemoveItems ()
Signals inherited from QgsDataItem
void beginInsertItems (QgsDataItem *parent, int first, int last)
void endInsertItems ()
void beginRemoveItems (QgsDataItem *parent, int first, int last)
void endRemoveItems ()
Protected Attributes inherited from QgsDataItem
Type mType
QgsDataItem * mParent
QVector< QgsDataItem * > mChildren
bool mPopulated
QString mName
QString mPath
QString mToolTip
QIcon mIcon
Detailed Description
A Collection: logical collection of layers or subcollections, e.g.
GRASS location/mapset, database? wms source?
Definition at line 208 of file qgsdataitem.h.
Constructor & Destructor Documentation
QgsDataCollectionItem::QgsDataCollectionItem (QgsDataItem * parent, QString name, QString path = QString::null)
Definition at line 385 of file qgsdataitem.cpp.
References iconDataCollection(), and QgsDataItem::mIcon.
QgsDataCollectionItem::~QgsDataCollectionItem ()
Definition at line 391 of file qgsdataitem.cpp.
References QgsDataItem::mChildren, and QgsDebugMsgLevel.
Member Function Documentation
void QgsDataCollectionItem::addChild (QgsDataItem * item) inline
Definition at line 216 of file qgsdataitem.h.
const QIcon & QgsDataCollectionItem::iconDataCollection () static
Definition at line 103 of file qgsdataitem.cpp.
References QgsApplication::getThemeIcon(), and QgsDataItem::icon().
Referenced by QgsDataCollectionItem().
const QIcon & QgsDataCollectionItem::iconDir () static
Definition at line 113 of file qgsdataitem.cpp.
References QgsDataItem::icon().
Referenced by QgsDirectoryItem::QgsDirectoryItem().
void QgsDataCollectionItem::setPopulated () inline
Definition at line 215 of file qgsdataitem.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdataitem.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdataitem.cpp