QGIS API Documentation: QgsAttributeTableView Class Reference
QgsAttributeTableView Class Reference
Provides a table view of features of a QgsVectorLayer.
#include <qgsattributetableview.h>
Public Slots
void repaintRequested (QModelIndexList indexes)
void repaintRequested ()
virtual void selectAll ()
virtual void selectRow (int row)
virtual void _q_selectRow (int row)
Signals
void willShowContextMenu (QMenu *menu, QModelIndex atIndex)
Is emitted, in order to provide a hook to add aditional menu entries to the context menu.
void finished ()
Public Member Functions
QgsAttributeTableView (QWidget *parent=0)
virtual ~QgsAttributeTableView ()
virtual void setModel (QgsAttributeTableFilterModel *filterModel)
void setFeatureSelectionManager (QgsIFeatureSelectionManager *featureSelectionManager)
setFeatureSelectionManager
virtual bool eventFilter (QObject *object, QEvent *event)
This event filter is installed on the verticalHeader to intercept mouse press and release events.
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
Called for mouse press events on a table cell.
void mouseReleaseEvent (QMouseEvent *event)
Called for mouse release events on a table cell.
void mouseMoveEvent (QMouseEvent *event)
Called for mouse move events on a table cell.
void keyPressEvent (QKeyEvent *event)
Called for key press events Disables selection change by only pressing an arrow key.
void contextMenuEvent (QContextMenuEvent *event)
Is called when the context menu will be shown.
void closeEvent (QCloseEvent *event)
Saves geometry to the settings on close.
Private Member Functions
void selectRow (int row, bool anchor)
Private Attributes
QgsAttributeTableModel * mMasterModel
QgsAttributeTableFilterModel * mFilterModel
QgsFeatureSelectionModel * mFeatureSelectionModel
QgsIFeatureSelectionManager * mFeatureSelectionManager
QgsAttributeTableDelegate * mTableDelegate
QAbstractItemModel * mModel
QMenu * mActionPopup
QgsVectorLayerCache * mLayerCache
int mRowSectionAnchor
QItemSelectionModel::SelectionFlag mCtrlDragSelectionFlag
Detailed Description
Provides a table view of features of a QgsVectorLayer.
This can either be used as a standalone widget. QgsBrowser features a reference implementation. Or this can be used within the QgsDualView stacked widget.
Definition at line 44 of file qgsattributetableview.h.
Constructor & Destructor Documentation
QgsAttributeTableView::QgsAttributeTableView (QWidget * parent = 0)
Definition at line 33 of file qgsattributetableview.cpp.
References _q_selectRow(), mTableDelegate, and selectRow().
QgsAttributeTableView::~QgsAttributeTableView () virtual
Definition at line 60 of file qgsattributetableview.cpp.
References mActionPopup.
Member Function Documentation
void QgsAttributeTableView::_q_selectRow (int row) virtual slot
Definition at line 259 of file qgsattributetableview.cpp.
References selectRow().
Referenced by QgsAttributeTableView().
void QgsAttributeTableView::closeEvent (QCloseEvent * event) protected
Saves geometry to the settings on close.
Parameters
event not used
Definition at line 153 of file qgsattributetableview.cpp.
void QgsAttributeTableView::contextMenuEvent (QContextMenuEvent * event) protected
Is called when the context menu will be shown.
Emits a willShowContextMenu signal, so the menu can be populated by other parts of the application.
Parameters
event The associated event object.
Definition at line 223 of file qgsattributetableview.cpp.
References QgsAttributeTableFilterModel::layer(), mActionPopup, mFilterModel, selectAll(), tr, and willShowContextMenu().
bool QgsAttributeTableView::eventFilter (QObject * object, QEvent * event) virtual
This event filter is installed on the verticalHeader to intercept mouse press and release events.
These are used to disable / enable live synchronisation with the map canvas selection which can be slow due to recurring canvas repaints. Updating the
Parameters
object The object which is the target of the event.
event The intercepted event
Returns
Returns always false, so the event gets processed
Definition at line 91 of file qgsattributetableview.cpp.
References QgsFeatureSelectionModel::enableSync(), and mFeatureSelectionModel.
void QgsAttributeTableView::finished () signal
void QgsAttributeTableView::keyPressEvent (QKeyEvent * event) protected
Called for key press events Disables selection change by only pressing an arrow key.
Parameters
event The mouse event
Definition at line 181 of file qgsattributetableview.cpp.
void QgsAttributeTableView::mouseMoveEvent (QMouseEvent * event) protected
Called for mouse move events on a table cell.
Disables selection change for these events.
Parameters
event The mouse event
Definition at line 174 of file qgsattributetableview.cpp.
void QgsAttributeTableView::mousePressEvent (QMouseEvent * event) protected
Called for mouse press events on a table cell.
Disables selection change for these events.
Parameters
event The mouse event
Definition at line 160 of file qgsattributetableview.cpp.
void QgsAttributeTableView::mouseReleaseEvent (QMouseEvent * event) protected
Called for mouse release events on a table cell.
Disables selection change for these events.
Parameters
event The mouse event
Definition at line 167 of file qgsattributetableview.cpp.
void QgsAttributeTableView::repaintRequested (QModelIndexList indexes) slot
Definition at line 203 of file qgsattributetableview.cpp.
References index.
void QgsAttributeTableView::repaintRequested () slot
Definition at line 211 of file qgsattributetableview.cpp.
Referenced by setModel().
void QgsAttributeTableView::selectAll () virtual slot
Definition at line 216 of file qgsattributetableview.cpp.
References mFeatureSelectionModel, mFilterModel, and QgsFeatureSelectionModel::selectFeatures().
Referenced by contextMenuEvent().
void QgsAttributeTableView::selectRow (int row) virtual slot
Definition at line 254 of file qgsattributetableview.cpp.
Referenced by _q_selectRow(), and QgsAttributeTableView().
void QgsAttributeTableView::selectRow (int row, bool anchor) private
Definition at line 264 of file qgsattributetableview.cpp.
References index, QgsFeatureSelectionModel::isSelected(), mCtrlDragSelectionFlag, mFeatureSelectionModel, mRowSectionAnchor, and QgsFeatureSelectionModel::selectFeatures().
void QgsAttributeTableView::setFeatureSelectionManager (QgsIFeatureSelectionManager * featureSelectionManager)
setFeatureSelectionManager
Parameters
featureSelectionManager We will take ownership
Definition at line 142 of file qgsattributetableview.cpp.
References mFeatureSelectionManager, mFeatureSelectionModel, and QgsFeatureSelectionModel::setFeatureSelectionManager().
void QgsAttributeTableView::setModel (QgsAttributeTableFilterModel * filterModel) virtual
Definition at line 112 of file qgsattributetableview.cpp.
References QgsAttributeTableFilterModel::layer(), mFeatureSelectionManager, mFeatureSelectionModel, mFilterModel, mTableDelegate, repaintRequested(), and QgsAttributeTableDelegate::setFeatureSelectionModel().
void QgsAttributeTableView::willShowContextMenu (QMenu * menu, QModelIndex atIndex) signal
Is emitted, in order to provide a hook to add aditional menu entries to the context menu.
Parameters
menu If additional QMenuItems are added, they will show up in the context menu.
atIndex The QModelIndex, to which the context menu belongs. Relative to the source model. In most cases, this will be a QgsAttributeTableFilterModel
Referenced by contextMenuEvent().
Member Data Documentation
QMenu* QgsAttributeTableView::mActionPopup private
Definition at line 148 of file qgsattributetableview.h.
Referenced by contextMenuEvent(), and ~QgsAttributeTableView().
QItemSelectionModel::SelectionFlag QgsAttributeTableView::mCtrlDragSelectionFlag private
Definition at line 151 of file qgsattributetableview.h.
Referenced by selectRow().
QgsIFeatureSelectionManager* QgsAttributeTableView::mFeatureSelectionManager private
Definition at line 145 of file qgsattributetableview.h.
Referenced by setFeatureSelectionManager(), and setModel().
QgsFeatureSelectionModel* QgsAttributeTableView::mFeatureSelectionModel private
Definition at line 144 of file qgsattributetableview.h.
Referenced by eventFilter(), selectAll(), selectRow(), setFeatureSelectionManager(), and setModel().
QgsAttributeTableFilterModel* QgsAttributeTableView::mFilterModel private
Definition at line 143 of file qgsattributetableview.h.
Referenced by contextMenuEvent(), selectAll(), and setModel().
QgsVectorLayerCache* QgsAttributeTableView::mLayerCache private
Definition at line 149 of file qgsattributetableview.h.
QgsAttributeTableModel* QgsAttributeTableView::mMasterModel private
Definition at line 142 of file qgsattributetableview.h.
QAbstractItemModel* QgsAttributeTableView::mModel private
Definition at line 147 of file qgsattributetableview.h.
int QgsAttributeTableView::mRowSectionAnchor private
Definition at line 150 of file qgsattributetableview.h.
Referenced by selectRow().
QgsAttributeTableDelegate* QgsAttributeTableView::mTableDelegate private
Definition at line 146 of file qgsattributetableview.h.
Referenced by QgsAttributeTableView(), and setModel().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsattributetableview.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/attributetable/qgsattributetableview.cpp