QGIS API Documentation: QgsRelationEditorWidget Class Reference
QgsRelationEditorWidget Class Reference
#include <qgsrelationeditor.h>
Static Public Member Functions
static QgsRelationEditorWidget * createRelationEditor (const QgsRelation &relation, const QgsFeature &feature, QgsAttributeEditorContext context, QWidget *parent=NULL)
Private Slots
void onCollapsedStateChanged (bool state)
void referencingLayerEditingToggled ()
void viewModeChanged (int mode)
void on_mAddFeatureButton_clicked ()
void on_mLinkFeatureButton_clicked ()
void on_mDeleteFeatureButton_clicked ()
void on_mUnlinkFeatureButton_clicked ()
void on_mToggleEditingButton_toggled (bool state)
Private Member Functions
QgsRelationEditorWidget (const QgsRelation &relation, const QgsFeature &feature, QgsAttributeEditorContext context, QWidget *parent=NULL)
You should use the static method createRelationEditor.
Private Attributes
QgsDualView * mDualView
QgsGenericFeatureSelectionManager * mFeatureSelectionMgr
QgsAttributeEditorContext mEditorContext
QgsRelation mRelation
QgsFeature mFeature
Additional Inherited Members
Public Slots inherited from QgsCollapsibleGroupBoxBasic
void checkToggled (bool ckd)
void checkClicked (bool ckd)
void toggleCollapsed ()
Signals inherited from QgsCollapsibleGroupBoxBasic
void collapsedStateChanged (bool collapsed)
Signal emitted when groupbox collapsed/expanded state is changed, and when first shown.
Public Member Functions inherited from QgsCollapsibleGroupBox
QgsCollapsibleGroupBox (QWidget *parent=0, QSettings *settings=0)
QgsCollapsibleGroupBox (const QString &title, QWidget *parent=0, QSettings *settings=0)
~QgsCollapsibleGroupBox ()
void setSettings (QSettings *settings)
void setSaveCollapsedState (bool save)
set this to false to not save/restore collapsed state
void setSaveCheckedState (bool save)
set this to true to save/restore checked state
bool saveCollapsedState ()
bool saveCheckedState ()
void setSettingGroup (const QString &group)
set this to a defined string to share save/restore states across different parent dialogs
QString settingGroup () const
Public Member Functions inherited from QgsCollapsibleGroupBoxBasic
QgsCollapsibleGroupBoxBasic (QWidget *parent=0)
QgsCollapsibleGroupBoxBasic (const QString &title, QWidget *parent=0)
~QgsCollapsibleGroupBoxBasic ()
bool isCollapsed () const
void setCollapsed (bool collapse)
QString syncGroup () const
Named group which synchronizes collapsing action when triangle is clicked while holding alt modifier key.
void setSyncGroup (QString grp)
void setScrollOnExpand (bool scroll)
set this to false to not automatically scroll parent QScrollArea to this widget's contents when expanded
bool scrollOnExpand ()
Protected Slots inherited from QgsCollapsibleGroupBox
void loadState ()
void saveState ()
Protected Member Functions inherited from QgsCollapsibleGroupBox
void init ()
void showEvent (QShowEvent *event)
QString saveKey () const
Protected Member Functions inherited from QgsCollapsibleGroupBoxBasic
void init ()
void collapseExpandFixes ()
Visual fixes for when group box is collapsed/expanded.
void showEvent (QShowEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void changeEvent (QEvent *event)
void updateStyle ()
QRect titleRect () const
void clearModifiers ()
Protected Attributes inherited from QgsCollapsibleGroupBox
QPointer< QSettings > mSettings
bool mDelSettings
bool mSaveCollapsedState
bool mSaveCheckedState
QString mSettingGroup
Protected Attributes inherited from QgsCollapsibleGroupBoxBasic
bool mCollapsed
bool mInitFlat
bool mInitFlatChecked
bool mScrollOnExpand
bool mShown
QScrollArea * mParentScrollArea
QgsGroupBoxCollapseButton * mCollapseButton
QWidget * mSyncParent
QString mSyncGroup
bool mAltDown
bool mShiftDown
bool mTitleClicked
Static Protected Attributes inherited from QgsCollapsibleGroupBoxBasic
static QIcon mCollapseIcon
static QIcon mExpandIcon
Properties inherited from QgsCollapsibleGroupBox
bool collapsed
bool saveCollapsedState
bool saveCheckedState
QString syncGroup
bool scrollOnExpand
Properties inherited from QgsCollapsibleGroupBoxBasic
bool collapsed
QString syncGroup
bool scrollOnExpand
Detailed Description
Definition at line 31 of file qgsrelationeditor.h.
Constructor & Destructor Documentation
QgsRelationEditorWidget::QgsRelationEditorWidget (const QgsRelation & relation, const QgsFeature & feature, QgsAttributeEditorContext context, QWidget * parent = NULL) private
You should use the static method createRelationEditor.
Parameters
relation
feature
context
parent
Definition at line 32 of file qgsrelationeditor.cpp.
References QgsCollapsibleGroupBoxBasic::collapsedStateChanged(), onCollapsedStateChanged(), QgsRelation::referencingLayer(), and referencingLayerEditingToggled().
Referenced by createRelationEditor().
Member Function Documentation
QgsRelationEditorWidget * QgsRelationEditorWidget::createRelationEditor (const QgsRelation & relation, const QgsFeature & feature, QgsAttributeEditorContext context, QWidget * parent = NULL) static
Definition at line 49 of file qgsrelationeditor.cpp.
References QgsDualView::AttributeEditor, QgsDualView::AttributeTable, QgsVectorDataProvider::capabilities(), QgsVectorDataProvider::ChangeAttributeValues, QgsVectorLayer::dataProvider(), QgsRelation::getRelatedFeaturesRequest(), QgsDualView::init(), QgsVectorLayer::isReadOnly(), mDualView, mFeatureSelectionMgr, QgsRelationEditorWidget(), QgsRelation::referencingLayer(), QgsDualView::setFeatureSelectionManager(), and viewModeChanged().
void QgsRelationEditorWidget::on_mAddFeatureButton_clicked () private slot
Definition at line 104 of file qgsrelationeditor.cpp.
References QgsVectorLayerTools::addFeature(), QgsFeature::attribute(), QgsRelation::fieldPairs(), QgsFields::indexFromName(), QgsAttributeTableModel::layer(), QgsDualView::masterModel(), mDualView, mEditorContext, mFeature, mRelation, QgsVectorLayer::pendingFields(), QgsRelation::FieldPair::referencedField(), QgsRelation::FieldPair::referencingField(), QgsRelation::referencingLayer(), and QgsAttributeEditorContext::vectorLayerTools().
void QgsRelationEditorWidget::on_mDeleteFeatureButton_clicked () private slot
Definition at line 144 of file qgsrelationeditor.cpp.
References QgsVectorLayer::deleteFeature(), mFeatureSelectionMgr, mRelation, QgsRelation::referencingLayer(), and QgsGenericFeatureSelectionManager::selectedFeaturesIds().
void QgsRelationEditorWidget::on_mLinkFeatureButton_clicked () private slot
Definition at line 118 of file qgsrelationeditor.cpp.
References QgsFeature::attribute(), QgsVectorLayer::changeAttributeValue(), QgsVectorLayer::fieldNameIndex(), QgsRelation::fieldPairs(), mFeature, mRelation, QgsRelation::FieldPair::referencedField(), QgsRelation::FieldPair::referencingField(), and QgsRelation::referencingLayer().
void QgsRelationEditorWidget::on_mToggleEditingButton_toggled (bool state) private slot
Definition at line 173 of file qgsrelationeditor.cpp.
References mEditorContext, mRelation, QgsRelation::referencingLayer(), QgsVectorLayerTools::startEditing(), QgsVectorLayerTools::stopEditing(), and QgsAttributeEditorContext::vectorLayerTools().
void QgsRelationEditorWidget::on_mUnlinkFeatureButton_clicked () private slot
Definition at line 152 of file qgsrelationeditor.cpp.
References QgsFields::at(), QgsVectorLayer::changeAttributeValue(), QgsVectorLayer::fieldNameIndex(), QgsRelation::fieldPairs(), mFeatureSelectionMgr, mRelation, QgsVectorLayer::pendingFields(), QgsRelation::FieldPair::referencingField(), QgsRelation::referencingLayer(), and QgsGenericFeatureSelectionManager::selectedFeaturesIds().
void QgsRelationEditorWidget::onCollapsedStateChanged (bool state) private slot
Definition at line 80 of file qgsrelationeditor.cpp.
References QgsDualView::masterModel(), and mDualView.
Referenced by QgsRelationEditorWidget().
void QgsRelationEditorWidget::referencingLayerEditingToggled () private slot
Definition at line 88 of file qgsrelationeditor.cpp.
References QgsVectorLayer::isEditable(), mRelation, and QgsRelation::referencingLayer().
Referenced by QgsRelationEditorWidget().
void QgsRelationEditorWidget::viewModeChanged (int mode) private slot
Definition at line 99 of file qgsrelationeditor.cpp.
Referenced by createRelationEditor().
Member Data Documentation
QgsDualView* QgsRelationEditorWidget::mDualView private
Definition at line 60 of file qgsrelationeditor.h.
Referenced by createRelationEditor(), on_mAddFeatureButton_clicked(), and onCollapsedStateChanged().
QgsAttributeEditorContext QgsRelationEditorWidget::mEditorContext private
Definition at line 62 of file qgsrelationeditor.h.
Referenced by on_mAddFeatureButton_clicked(), and on_mToggleEditingButton_toggled().
QgsFeature QgsRelationEditorWidget::mFeature private
Definition at line 64 of file qgsrelationeditor.h.
Referenced by on_mAddFeatureButton_clicked(), and on_mLinkFeatureButton_clicked().
QgsGenericFeatureSelectionManager* QgsRelationEditorWidget::mFeatureSelectionMgr private
Definition at line 61 of file qgsrelationeditor.h.
Referenced by createRelationEditor(), on_mDeleteFeatureButton_clicked(), and on_mUnlinkFeatureButton_clicked().
QgsRelation QgsRelationEditorWidget::mRelation private
Definition at line 63 of file qgsrelationeditor.h.
Referenced by on_mAddFeatureButton_clicked(), on_mDeleteFeatureButton_clicked(), on_mLinkFeatureButton_clicked(), on_mToggleEditingButton_toggled(), on_mUnlinkFeatureButton_clicked(), and referencingLayerEditingToggled().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsrelationeditor.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsrelationeditor.cpp