QGIS API Documentation: QgsExpression::NodeCondition Class Reference
QgsExpression::NodeCondition Class Reference
#include <qgsexpression.h>
Public Member Functions
NodeCondition (WhenThenList *conditions, Node *elseExp=NULL)
~NodeCondition ()
virtual NodeType nodeType () const
virtual QVariant eval (QgsExpression *parent, const QgsFeature *f)
virtual bool prepare (QgsExpression *parent, const QgsFields &fields)
virtual QString dump () const
virtual QStringList referencedColumns () const
virtual bool needsGeometry () const
virtual void accept (Visitor &v) const
Public Member Functions inherited from QgsExpression::Node
virtual ~Node ()
Protected Attributes
WhenThenList mConditions
Node * mElseExp
Detailed Description
Definition at line 564 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::NodeCondition::NodeCondition (WhenThenList * conditions, Node * elseExp = NULL) inline
Definition at line 567 of file qgsexpression.h.
QgsExpression::NodeCondition::~NodeCondition () inline
Definition at line 568 of file qgsexpression.h.
Member Function Documentation
virtual void QgsExpression::NodeCondition::accept (Visitor & v) const inline virtual
Implements QgsExpression::Node.
Definition at line 577 of file qgsexpression.h.
References QgsExpression::Visitor::visit().
QString QgsExpression::NodeCondition::dump () const virtual
Implements QgsExpression::Node.
Definition at line 2536 of file qgsexpression.cpp.
References QgsExpression::Node::dump(), QgsExpression::WhenThen::mThenExp, and QgsExpression::WhenThen::mWhenExp.
QVariant QgsExpression::NodeCondition::eval (QgsExpression * parent, const QgsFeature * f) virtual
Implements QgsExpression::Node.
Definition at line 2494 of file qgsexpression.cpp.
References ENSURE_NO_EVAL_ERROR, QgsExpression::Node::eval(), getTVLValue(), QgsExpression::WhenThen::mThenExp, QgsExpression::WhenThen::mWhenExp, and True.
bool QgsExpression::NodeCondition::needsGeometry () const virtual
Implements QgsExpression::Node.
Definition at line 2563 of file qgsexpression.cpp.
References QgsExpression::WhenThen::mThenExp, QgsExpression::WhenThen::mWhenExp, and QgsExpression::Node::needsGeometry().
virtual NodeType QgsExpression::NodeCondition::nodeType () const inline virtual
Implements QgsExpression::Node.
Definition at line 570 of file qgsexpression.h.
References QgsExpression::ntCondition.
bool QgsExpression::NodeCondition::prepare (QgsExpression * parent, const QgsFields & fields) virtual
Implements QgsExpression::Node.
Definition at line 2520 of file qgsexpression.cpp.
References QgsExpression::WhenThen::mThenExp, QgsExpression::WhenThen::mWhenExp, and QgsExpression::Node::prepare().
QStringList QgsExpression::NodeCondition::referencedColumns () const virtual
Implements QgsExpression::Node.
Definition at line 2549 of file qgsexpression.cpp.
References QgsExpression::WhenThen::mThenExp, QgsExpression::WhenThen::mWhenExp, and QgsExpression::Node::referencedColumns().
Member Data Documentation
WhenThenList QgsExpression::NodeCondition::mConditions protected
Definition at line 580 of file qgsexpression.h.
Node* QgsExpression::NodeCondition::mElseExp protected
Definition at line 581 of file qgsexpression.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.cpp