QGIS API Documentation: HistogramItem Class Reference
HistogramItem Class Reference
#include <qwt5_histogram_item.h>
Classes
class PrivateData
Public Types
enum HistogramAttribute { Auto = 0, Xfy = 1 }
Public Member Functions
HistogramItem (const QString &title=QString::null)
HistogramItem (const QwtText &title)
virtual ~HistogramItem ()
void setData (const QwtIntervalData &data)
const QwtIntervalData & data () const
void setColor (const QColor &)
QColor color () const
virtual QwtDoubleRect boundingRect () const
virtual int rtti () const
virtual void draw (QPainter *, const QwtScaleMap &xMap, const QwtScaleMap &yMap, const QRect &) const
virtual void updateLegend (QwtLegend *) const
Update the widget that represents the curve on the legend.
void setBaseline (double reference)
double baseline () const
void setHistogramAttribute (HistogramAttribute, bool on=true)
bool testHistogramAttribute (HistogramAttribute) const
Protected Member Functions
virtual void drawBar (QPainter *, Qt::Orientation o, const QRect &) const
Private Member Functions
void init ()
Private Attributes
PrivateData * d_data
Detailed Description
Definition at line 21 of file qwt5_histogram_item.h.
Member Enumeration Documentation
enum HistogramItem::HistogramAttribute
Enumerator
Auto
Xfy
Definition at line 46 of file qwt5_histogram_item.h.
Constructor & Destructor Documentation
HistogramItem::HistogramItem (const QString & title = QString::null) explicit
Definition at line 89 of file qwt5_histogram_item.h.
References init().
HistogramItem::HistogramItem (const QwtText & title) explicit
Definition at line 83 of file qwt5_histogram_item.h.
References init().
HistogramItem::~HistogramItem () virtual
Definition at line 95 of file qwt5_histogram_item.h.
References d_data.
Member Function Documentation
double HistogramItem::baseline () const
Definition at line 121 of file qwt5_histogram_item.h.
References d_data, and HistogramItem::PrivateData::reference.
Referenced by draw().
QwtDoubleRect HistogramItem::boundingRect () const virtual
Definition at line 151 of file qwt5_histogram_item.h.
References HistogramItem::PrivateData::attributes, d_data, HistogramItem::PrivateData::data, HistogramItem::PrivateData::reference, and Xfy.
QColor HistogramItem::color (void) const
Definition at line 146 of file qwt5_histogram_item.h.
References HistogramItem::PrivateData::color, and d_data.
Referenced by drawBar(), setColor(), and updateLegend().
const QwtIntervalData & HistogramItem::data () const
Definition at line 132 of file qwt5_histogram_item.h.
References d_data, and HistogramItem::PrivateData::data.
Referenced by setData().
void HistogramItem::draw (QPainter * painter, const QwtScaleMap & xMap, const QwtScaleMap & yMap, const QRect &) const virtual
Definition at line 202 of file qwt5_histogram_item.h.
References HistogramItem::PrivateData::attributes, baseline(), HistogramItem::PrivateData::color, d_data, HistogramItem::PrivateData::data, drawBar(), and Xfy.
void HistogramItem::drawBar (QPainter * painter, Qt::Orientation o, const QRect & rect) const protected virtual
Definition at line 279 of file qwt5_histogram_item.h.
References color().
Referenced by draw().
void HistogramItem::init () private
Definition at line 100 of file qwt5_histogram_item.h.
References HistogramItem::PrivateData::attributes, Auto, d_data, and HistogramItem::PrivateData::reference.
Referenced by HistogramItem().
int HistogramItem::rtti () const virtual
Definition at line 179 of file qwt5_histogram_item.h.
void HistogramItem::setBaseline (double reference)
Definition at line 112 of file qwt5_histogram_item.h.
References d_data, and HistogramItem::PrivateData::reference.
void HistogramItem::setColor (const QColor & color)
Definition at line 137 of file qwt5_histogram_item.h.
References color(), HistogramItem::PrivateData::color, and d_data.
Referenced by QgsRasterHistogramWidget::refreshHistogram().
void HistogramItem::setData (const QwtIntervalData & data)
Definition at line 126 of file qwt5_histogram_item.h.
References d_data, data(), and HistogramItem::PrivateData::data.
Referenced by QgsRasterHistogramWidget::refreshHistogram().
void HistogramItem::setHistogramAttribute (HistogramAttribute attribute, bool on = true)
Definition at line 184 of file qwt5_histogram_item.h.
References HistogramItem::PrivateData::attributes, and d_data.
bool HistogramItem::testHistogramAttribute (HistogramAttribute attribute) const
Definition at line 197 of file qwt5_histogram_item.h.
References HistogramItem::PrivateData::attributes, and d_data.
void HistogramItem::updateLegend (QwtLegend * legend) const virtual
Update the widget that represents the curve on the legend.
Definition at line 352 of file qwt5_histogram_item.h.
References color().
Member Data Documentation
PrivateData* HistogramItem::d_data private
Definition at line 62 of file qwt5_histogram_item.h.
Referenced by baseline(), boundingRect(), color(), data(), draw(), init(), setBaseline(), setColor(), setData(), setHistogramAttribute(), testHistogramAttribute(), and ~HistogramItem().
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/raster/qwt5_histogram_item.h