QGIS API Documentation: QgsComposerPicture Class Reference
QgsComposerPicture Class Reference
MapComposer
A composer class that displays svg files or raster format (jpg, png, ...)
#include <qgscomposerpicture.h>
Public Types
enum ResizeMode {
Zoom, Stretch, Clip, ZoomResizeFrame,
FrameToImageSize
}
enum Mode { SVG, RASTER, Unknown }
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Public Slots
virtual void setRotation (double r)
Sets the picture rotation within the item bounds.
virtual void setPictureRotation (double r)
Sets the picture rotation within the item bounds.
virtual void setResizeMode (ResizeMode mode)
Sets the resize mode used for drawing the picture within the item bounds.
virtual void setUsePictureExpression (bool useExpression)
Sets whether the picture should use an expression based image source path.
virtual void setPictureExpression (QString expression)
Sets an expression to use for the picture source.
void refreshPicture ()
Recalculates the source image (if using an expression for picture's source) and reloads and redraws the picture.
void updatePictureExpression ()
Prepares the picture's source expression after it is altered or the compositions atlas coverage layer changes.
void recalculateSize ()
Forces a recalculation of the picture's frame size.
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
Sets the item rotation.
virtual void setItemRotation (double r, bool adjustPosition=false)
Sets the item rotation.
void repaint ()
Signals
void pictureRotationChanged (double newRotation)
Is emitted on picture rotation change.
Signals inherited from QgsComposerItem
void itemRotationChanged (double newRotation)
Is emitted on item rotation change.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
void frameChanged ()
Emitted if the item's frame style changes.
Public Member Functions
QgsComposerPicture (QgsComposition *composition)
~QgsComposerPicture ()
virtual int type () const
return correct graphics item type.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint.
void setPictureFile (const QString &path)
Sets the source file of the image (may be svg or a raster format).
QString pictureFile () const
Returns the path of the source image file.
void setSceneRect (const QRectF &rectangle)
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit and resizes the svg symbol / image.
bool writeXML (QDomElement &elem, QDomDocument &doc) const
stores state in Dom element
bool readXML (const QDomElement &itemElem, const QDomDocument &doc)
sets state from Dom document
Q_DECL_DEPRECATED double rotation () const
Returns the rotation used for drawing the picture within the composer item.
double pictureRotation () const
Returns the rotation used for drawing the picture within the item's frame.
void setRotationMap (int composerMapId)
Sets the map object for rotation (by id).
int rotationMap () const
Returns the id of the rotation map.
bool useRotationMap () const
True if the picture rotation is matched to a map item.
ResizeMode resizeMode () const
Returns the resize mode used for drawing the picture within the composer item's frame.
void setPictureAnchor (QgsComposerItem::ItemPositionMode anchor)
Sets the picture's anchor point, which controls how it is placed within the picture item's frame.
ItemPositionMode pictureAnchor () const
Returns the picture's current anchor, which controls how it is placed within the picture item's frame.
bool usePictureExpression () const
Returns whether the picture item is using an expression for the image source.
QString pictureExpression () const
Returns the expression the item is using for the picture source.
Q_DECL_DEPRECATED bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Q_DECL_DEPRECATED bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
Q_DECL_DEPRECATED void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
Mode mode () const
Returns the current picture mode (image format).
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected () const
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
int page () const
Gets the page the item is currently on.
QPointF pagePos () const
Returns the item's position relative to its current page.
void updatePagePos (double newPageWidth, double newPageHeight)
Moves the item so that it retains its relative position on the page when the paper size changes.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft, int page=-1)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft, bool posIncludesFrame=false, int page=-1)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
virtual void setFrameOutlineWidth (double outlineWidth)
Sets frame outline width.
double frameOutlineWidth () const
Returns the frame's outline width.
Qt::PenJoinStyle frameJoinStyle () const
Returns the join style used for drawing the item's frame.
void setFrameJoinStyle (Qt::PenJoinStyle style)
Sets join style used when drawing the item's frame.
virtual double estimatedFrameBleed () const
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
virtual QRectF rectWithFrame () const
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop, int flags=Qt::TextWordWrap) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font descent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightMillimeters (const QFont &font) const
Returns the font height in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
double itemRotation () const
Returns the rotation for the composer item.
Q_DECL_DEPRECATED double rotation () const
Returns the rotation for the composer item.
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
virtual int numberExportLayers () const
Get the number of layers that this item requires for exporting as layers.
virtual void setCurrentExportLayer (int layerIdx=-1)
Sets the current layer to draw for exporting.
Private Member Functions
QgsComposerPicture ()
QRectF boundedSVGRect (double deviceWidth, double deviceHeight)
Calculates bounding rect for svg file (mSourcefile) such that aspect ratio is correct.
QRectF boundedImageRect (double deviceWidth, double deviceHeight)
Calculates bounding rect for image such that aspect ratio is correct.
QSizeF pictureSize ()
Returns size of current raster or svg picture.
void loadPicture (const QFile &file)
loads an image file into the picture item and redraws the item
QString evalPictureExpression ()
evaluates the picture expression and returns the calculated image path
void init ()
sets up the picture item and connects to relevant signals
QRect clippedImageRect (double &boundRectWidthMM, double &boundRectHeightMM, QSize imageRectPixels)
Returns part of a raster image which will be shown, given current picture anchor settings.
Private Attributes
QImage mImage
QSvgRenderer mSVG
QFile mSourceFile
Mode mMode
bool mUseSourceExpression
QString mSourceExpression
QSize mDefaultSvgSize
double mPictureRotation
Image rotation.
const QgsComposerMap * mRotationMap
Map that sets the rotation (or 0 if this picture uses map independent rotation)
double mPictureWidth
Width of the picture (in mm)
double mPictureHeight
Height of the picture (in mm)
ResizeMode mResizeMode
QgsComposerItem::ItemPositionMode mPictureAnchor
QgsExpression * mPictureExpr
Additional Inherited Members
Protected Member Functions inherited from QgsComposerItem
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height, double rotation) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Q_DECL_DEPRECATED bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
QRectF largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height, double rotation) const
Calculates corner point after rotation and scaling.
Q_DECL_DEPRECATED bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height, double rotation)
Calculates width / height of the bounding box of a rotated rectangle.
Q_DECL_DEPRECATED void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Protected Attributes inherited from QgsComposerItem
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
Qt::PenJoinStyle mFrameJoinStyle
Frame join style.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mItemRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
int mCurrentExportLayer
The layer that needs to be exported.
Detailed Description
A composer class that displays svg files or raster format (jpg, png, ...)
Definition at line 31 of file qgscomposerpicture.h.
Member Enumeration Documentation
enum QgsComposerPicture::Mode
Format of source image
Enumerator
SVG
RASTER
Unknown
Definition at line 49 of file qgscomposerpicture.h.
enum QgsComposerPicture::ResizeMode
Controls how pictures are scaled within the item's frame
Enumerator
Zoom
enlarges image to fit frame while maintaining aspect ratio of picture
Stretch
stretches image to fit frame, ignores aspect ratio
Clip
draws image at original size and clips any portion which falls outside frame
ZoomResizeFrame
enlarges image to fit frame, then resizes frame to fit resultant image
FrameToImageSize
sets size of frame to match original size of image without scaling
Definition at line 38 of file qgscomposerpicture.h.
Constructor & Destructor Documentation
QgsComposerPicture::QgsComposerPicture (QgsComposition * composition)
Definition at line 34 of file qgscomposerpicture.cpp.
References init(), and mPictureWidth.
QgsComposerPicture::~QgsComposerPicture ()
Definition at line 73 of file qgscomposerpicture.cpp.
QgsComposerPicture::QgsComposerPicture () private
Definition at line 48 of file qgscomposerpicture.cpp.
References init(), and mPictureHeight.
Member Function Documentation
QRectF QgsComposerPicture::boundedImageRect (double deviceWidth, double deviceHeight) private
Calculates bounding rect for image such that aspect ratio is correct.
Definition at line 419 of file qgscomposerpicture.cpp.
References mImage.
QRectF QgsComposerPicture::boundedSVGRect (double deviceWidth, double deviceHeight) private
Calculates bounding rect for svg file (mSourcefile) such that aspect ratio is correct.
Definition at line 436 of file qgscomposerpicture.cpp.
References mDefaultSvgSize.
QRect QgsComposerPicture::clippedImageRect (double & boundRectWidthMM, double & boundRectHeightMM, QSize imageRectPixels) private
Returns part of a raster image which will be shown, given current picture anchor settings.
Definition at line 206 of file qgscomposerpicture.cpp.
References QgsComposerItem::LowerLeft, QgsComposerItem::LowerMiddle, QgsComposerItem::LowerRight, QgsComposerItem::mComposition, QgsComposerItem::Middle, QgsComposerItem::MiddleLeft, QgsComposerItem::MiddleRight, mPictureAnchor, QgsComposition::printResolution(), QgsComposerItem::UpperLeft, QgsComposerItem::UpperMiddle, and QgsComposerItem::UpperRight.
Referenced by paint().
bool QgsComposerPicture::cornerPointOnRotatedAndScaledRect (double & x, double & y, double width, double height) const
Calculates corner point after rotation and scaling.
Deprecated:
Use QgsComposerItem::cornerPointOnRotatedAndScaledRect(double& x, double& y, double width, double height, double rotation) instead
Definition at line 788 of file qgscomposerpicture.cpp.
References QgsComposerItem::cornerPointOnRotatedAndScaledRect(), and mPictureRotation.
QString QgsComposerPicture::evalPictureExpression () private
evaluates the picture expression and returns the calculated image path
Definition at line 300 of file qgscomposerpicture.cpp.
References QgsComposition::atlasComposition(), QgsAtlasComposition::coverageLayer(), QgsAtlasComposition::currentFeature(), QgsAtlasComposition::enabled(), QgsExpression::evalErrorString(), QgsExpression::evaluate(), QgsExpression::hasEvalError(), QgsMessageLog::logMessage(), QgsComposerItem::mComposition, mPictureExpr, mSourceExpression, mUseSourceExpression, QgsVectorLayer::pendingFields(), and tr.
Referenced by refreshPicture().
bool QgsComposerPicture::imageSizeConsideringRotation (double & width, double & height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Deprecated:
Use bool QgsComposerItem::imageSizeConsideringRotation(double& width, double& height, double rotation) instead
Definition at line 782 of file qgscomposerpicture.cpp.
References QgsComposerItem::imageSizeConsideringRotation(), and mPictureRotation.
void QgsComposerPicture::init () private
sets up the picture item and connects to relevant signals
Definition at line 61 of file qgscomposerpicture.cpp.
References QgsComposition::atlasComposition(), QgsComposerItem::mComposition, recalculateSize(), and refreshPicture().
Referenced by QgsComposerPicture().
void QgsComposerPicture::loadPicture (const QFile & file) private
loads an image file into the picture item and redraws the item
Definition at line 354 of file qgscomposerpicture.cpp.
References QgsExpression::hasEvalError(), QgsComposerItem::itemChanged(), mDefaultSvgSize, mImage, mMode, mPictureExpr, mSVG, mUseSourceExpression, RASTER, recalculateSize(), SVG, and Unknown.
Referenced by refreshPicture().
Mode QgsComposerPicture::mode () const inline
Returns the current picture mode (image format).
Returns
picture mode
Note
added in 2.3
Definition at line 199 of file qgscomposerpicture.h.
Referenced by setResizeMode().
void QgsComposerPicture::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget)
Reimplementation of QCanvasItem::paint.
Definition at line 78 of file qgscomposerpicture.cpp.
References Clip, clippedImageRect(), QgsComposerItem::drawBackground(), QgsComposerItem::drawFrame(), QgsComposerItem::drawSelectionBoxes(), QgsComposerItem::LowerLeft, QgsComposerItem::LowerMiddle, QgsComposerItem::LowerRight, QgsComposerItem::mComposition, QgsComposerItem::Middle, QgsComposerItem::MiddleLeft, QgsComposerItem::MiddleRight, mImage, mMode, mPictureAnchor, mPictureHeight, mPictureRotation, mPictureWidth, mResizeMode, mSVG, QgsComposition::printResolution(), RASTER, Stretch, SVG, Unknown, QgsComposerItem::UpperLeft, QgsComposerItem::UpperMiddle, QgsComposerItem::UpperRight, Zoom, and ZoomResizeFrame.
ItemPositionMode QgsComposerPicture::pictureAnchor () const inline
Returns the picture's current anchor, which controls how it is placed within the picture item's frame.
Returns
anchor point for picture
Note
added in 2.3
See also
setPictureAnchor
Definition at line 158 of file qgscomposerpicture.h.
QString QgsComposerPicture::pictureExpression () const inline
Returns the expression the item is using for the picture source.
This is only used if usePictureExpression() is true.
Returns
expression for the picture item's image path
Note
added in 2.3
See also
setPictureExpression
usePictureExpression
Definition at line 177 of file qgscomposerpicture.h.
QString QgsComposerPicture::pictureFile () const
Returns the path of the source image file.
This is only used if usePictureExpression() is false.
Returns
path to the source image
See also
usePictureExpression
setPictureFile
Definition at line 646 of file qgscomposerpicture.cpp.
References mSourceFile.
double QgsComposerPicture::pictureRotation () const inline
Returns the rotation used for drawing the picture within the item's frame.
Returns
picture rotation in degrees
Note
added in 2.2
See also
setPictureRotation
rotationMap
Definition at line 108 of file qgscomposerpicture.h.
void QgsComposerPicture::pictureRotationChanged (double newRotation) signal
Is emitted on picture rotation change.
Referenced by setPictureRotation(), and setRotationMap().
QSizeF QgsComposerPicture::pictureSize () private
Returns size of current raster or svg picture.
Definition at line 453 of file qgscomposerpicture.cpp.
References mDefaultSvgSize, mImage, mMode, RASTER, and SVG.
Referenced by setPictureRotation(), and setSceneRect().
bool QgsComposerPicture::readXML (const QDomElement & itemElem, const QDomDocument & doc) virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is Dom document
Implements QgsComposerItem.
Definition at line 690 of file qgscomposerpicture.cpp.
References QgsComposerItem::_readXML(), QgsComposition::getComposerMapById(), QgsProject::instance(), QgsComposerItem::itemChanged(), QgsComposerItem::mComposition, mDefaultSvgSize, QgsComposerItem::Middle, mPictureAnchor, mPictureHeight, mPictureRotation, mPictureWidth, mResizeMode, mRotationMap, mSourceExpression, mSourceFile, mUseSourceExpression, QgsProject::readPath(), refreshPicture(), setRotation(), and updatePictureExpression().
Referenced by QgsComposition::addItemsFromXML().
void QgsComposerPicture::recalculateSize () slot
Forces a recalculation of the picture's frame size.
Note
added in 2.3
Definition at line 607 of file qgscomposerpicture.cpp.
References setSceneRect().
Referenced by init(), loadPicture(), and setResizeMode().
void QgsComposerPicture::refreshPicture () slot
Recalculates the source image (if using an expression for picture's source) and reloads and redraws the picture.
Note
added in 2.3
Definition at line 336 of file qgscomposerpicture.cpp.
References evalPictureExpression(), loadPicture(), mSourceFile, and mUseSourceExpression.
Referenced by init(), readXML(), setPictureExpression(), setPictureFile(), and setUsePictureExpression().
ResizeMode QgsComposerPicture::resizeMode () const inline
Returns the resize mode used for drawing the picture within the composer item's frame.
Returns
resize mode of picture
Note
added in 2.3
See also
setResizeMode
Definition at line 142 of file qgscomposerpicture.h.
Q_DECL_DEPRECATED double QgsComposerPicture::rotation () const inline
Returns the rotation used for drawing the picture within the composer item.
Deprecated:
Use pictureRotation() instead
Definition at line 100 of file qgscomposerpicture.h.
int QgsComposerPicture::rotationMap () const
Returns the id of the rotation map.
A value of -1 means map rotation is disabled. If this is set then the picture is rotated by the same amount as the specified map object.
Returns
id of map object
See also
setRotationMap
useRotationMap
Definition at line 764 of file qgscomposerpicture.cpp.
References QgsComposerMap::id(), and mRotationMap.
void QgsComposerPicture::setPictureAnchor (QgsComposerItem::ItemPositionMode anchor)
Sets the picture's anchor point, which controls how it is placed within the picture item's frame.
Parameters
anchor anchor point for picture
Note
added in 2.3
See also
pictureAnchor
Definition at line 776 of file qgscomposerpicture.cpp.
References mPictureAnchor.
void QgsComposerPicture::setPictureExpression (QString expression) virtual slot
Sets an expression to use for the picture source.
This expression is only used if usePictureExpression() is true.
Parameters
expression to use for picture path
Note
added in 2.3
See also
setUsePictureExpression
pictureExpression
Definition at line 630 of file qgscomposerpicture.cpp.
References mSourceExpression, mUseSourceExpression, refreshPicture(), and updatePictureExpression().
void QgsComposerPicture::setPictureFile (const QString & path)
Sets the source file of the image (may be svg or a raster format).
This is only used if usePictureExpression() is false.
Parameters
path full path to the source image
See also
usePictureExpression
pictureFile
Definition at line 264 of file qgscomposerpicture.cpp.
References mSourceFile, and refreshPicture().
void QgsComposerPicture::setPictureRotation (double r) virtual slot
Sets the picture rotation within the item bounds.
This does not affect the item's frame, only the way the picture is drawn within the item.
Parameters
r rotation in degrees clockwise
See also
pictureRotation
Note
added in 2.2
Definition at line 549 of file qgscomposerpicture.cpp.
References QgsComposerItem::largestRotatedRectWithinBounds(), mPictureHeight, mPictureRotation, mPictureWidth, mResizeMode, pictureRotationChanged(), pictureSize(), and Zoom.
Referenced by setRotation(), and setRotationMap().
void QgsComposerPicture::setResizeMode (QgsComposerPicture::ResizeMode mode) virtual slot
Sets the resize mode used for drawing the picture within the item bounds.
Parameters
mode ResizeMode to use for image file
Note
added in 2.3
See also
resizeMode
Definition at line 595 of file qgscomposerpicture.cpp.
References FrameToImageSize, mode(), mPictureRotation, mResizeMode, recalculateSize(), Zoom, and ZoomResizeFrame.
void QgsComposerPicture::setRotation (double r) virtual slot
Sets the picture rotation within the item bounds.
This does not affect the item rectangle, only the way the picture is drawn within the item.
Deprecated:
Use setPictureRotation(double rotation) instead
Definition at line 543 of file qgscomposerpicture.cpp.
References setPictureRotation().
Referenced by readXML().
void QgsComposerPicture::setRotationMap (int composerMapId)
Sets the map object for rotation (by id).
A value of -1 disables the map rotation. If this is set then the picture will be rotated by the same amount as the specified map object. This is useful especially for syncing north arrows with a map item.
Parameters
composerMapId composer map id to sync rotation with
See also
setPictureRotation
rotationMap
Definition at line 566 of file qgscomposerpicture.cpp.
References QgsComposition::getComposerMapById(), QgsComposerMap::mapRotation(), QgsComposerItem::mComposition, mPictureRotation, mRotationMap, pictureRotationChanged(), and setPictureRotation().
void QgsComposerPicture::setSceneRect (const QRectF & rectangle) virtual
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit and resizes the svg symbol / image.
Reimplemented from QgsComposerItem.
Definition at line 488 of file qgscomposerpicture.cpp.
References Clip, FrameToImageSize, QgsComposerItem::itemChanged(), QgsComposerItem::largestRotatedRectWithinBounds(), QgsComposerItem::mComposition, mPictureHeight, mPictureRotation, mPictureWidth, mResizeMode, pictureSize(), QgsComposition::printResolution(), QgsComposerItem::setSceneRect(), Zoom, and ZoomResizeFrame.
Referenced by QgsComposerView::mouseReleaseEvent(), and recalculateSize().
void QgsComposerPicture::setUsePictureExpression (bool useExpression) virtual slot
Sets whether the picture should use an expression based image source path.
Parameters
useExpression set to true to use an expression based image source, set to false to use a single image source path
Note
added in 2.3
See also
usePictureExpression
setPictureFile
setPictureExpression
Definition at line 614 of file qgscomposerpicture.cpp.
References mUseSourceExpression, refreshPicture(), and updatePictureExpression().
void QgsComposerPicture::sizeChangedByRotation (double & width, double & height)
Calculates width / height of the bounding box of a rotated rectangle.
Deprecated:
Use QgsComposerItem::sizeChangedByRotation(double& width, double& height, double rotation) instead
Definition at line 794 of file qgscomposerpicture.cpp.
References mPictureRotation, and QgsComposerItem::sizeChangedByRotation().
virtual int QgsComposerPicture::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerItem.
Definition at line 60 of file qgscomposerpicture.h.
References QgsComposerItem::ComposerPicture.
void QgsComposerPicture::updatePictureExpression () slot
Prepares the picture's source expression after it is altered or the compositions atlas coverage layer changes.
Note
added in 2.3
Definition at line 270 of file qgscomposerpicture.cpp.
References QgsComposition::atlasComposition(), QgsAtlasComposition::coverageLayer(), QgsAtlasComposition::enabled(), QgsExpression::hasParserError(), QgsMessageLog::logMessage(), QgsComposerItem::mComposition, mPictureExpr, mSourceExpression, QgsExpression::parserErrorString(), QgsVectorLayer::pendingFields(), QgsExpression::prepare(), and tr.
Referenced by readXML(), setPictureExpression(), and setUsePictureExpression().
bool QgsComposerPicture::usePictureExpression () const inline
Returns whether the picture item is using an expression for the image source.
Returns
true if the picture is using an expression for the source, false if it is using a single static file path for the source.
Note
added in 2.3
See also
setUsePictureExpression
pictureFile
pictureExpression
Definition at line 168 of file qgscomposerpicture.h.
bool QgsComposerPicture::useRotationMap () const inline
True if the picture rotation is matched to a map item.
Returns
true if rotation map is in use
See also
rotationMap
setRotationMap
Definition at line 134 of file qgscomposerpicture.h.
bool QgsComposerPicture::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
stores state in Dom element
Parameters
elem is Dom element corresponding to 'Composer' tag
doc is Dom document
Implements QgsComposerItem.
Definition at line 651 of file qgscomposerpicture.cpp.
References QgsComposerItem::_writeXML(), QgsComposerMap::id(), QgsProject::instance(), mPictureAnchor, mPictureHeight, mPictureRotation, mPictureWidth, mResizeMode, mRotationMap, mSourceExpression, mSourceFile, and mUseSourceExpression.
Member Data Documentation
QSize QgsComposerPicture::mDefaultSvgSize private
Definition at line 282 of file qgscomposerpicture.h.
Referenced by boundedSVGRect(), loadPicture(), pictureSize(), and readXML().
QImage QgsComposerPicture::mImage private
Definition at line 275 of file qgscomposerpicture.h.
Referenced by boundedImageRect(), loadPicture(), paint(), and pictureSize().
Mode QgsComposerPicture::mMode private
Definition at line 278 of file qgscomposerpicture.h.
Referenced by loadPicture(), paint(), and pictureSize().
QgsComposerItem::ItemPositionMode QgsComposerPicture::mPictureAnchor private
Definition at line 294 of file qgscomposerpicture.h.
Referenced by clippedImageRect(), paint(), readXML(), setPictureAnchor(), and writeXML().
QgsExpression* QgsComposerPicture::mPictureExpr private
Definition at line 296 of file qgscomposerpicture.h.
Referenced by evalPictureExpression(), loadPicture(), and updatePictureExpression().
double QgsComposerPicture::mPictureHeight private
Height of the picture (in mm)
Definition at line 291 of file qgscomposerpicture.h.
Referenced by paint(), QgsComposerPicture(), readXML(), setPictureRotation(), setSceneRect(), and writeXML().
double QgsComposerPicture::mPictureRotation private
Image rotation.
Definition at line 285 of file qgscomposerpicture.h.
Referenced by cornerPointOnRotatedAndScaledRect(), imageSizeConsideringRotation(), paint(), readXML(), setPictureRotation(), setResizeMode(), setRotationMap(), setSceneRect(), sizeChangedByRotation(), and writeXML().
double QgsComposerPicture::mPictureWidth private
Width of the picture (in mm)
Definition at line 289 of file qgscomposerpicture.h.
Referenced by paint(), QgsComposerPicture(), readXML(), setPictureRotation(), setSceneRect(), and writeXML().
ResizeMode QgsComposerPicture::mResizeMode private
Definition at line 293 of file qgscomposerpicture.h.
Referenced by paint(), readXML(), setPictureRotation(), setResizeMode(), setSceneRect(), and writeXML().
const QgsComposerMap* QgsComposerPicture::mRotationMap private
Map that sets the rotation (or 0 if this picture uses map independent rotation)
Definition at line 287 of file qgscomposerpicture.h.
Referenced by readXML(), rotationMap(), setRotationMap(), and writeXML().
QString QgsComposerPicture::mSourceExpression private
Definition at line 280 of file qgscomposerpicture.h.
Referenced by evalPictureExpression(), readXML(), setPictureExpression(), updatePictureExpression(), and writeXML().
QFile QgsComposerPicture::mSourceFile private
Definition at line 277 of file qgscomposerpicture.h.
Referenced by pictureFile(), readXML(), refreshPicture(), setPictureFile(), and writeXML().
QSvgRenderer QgsComposerPicture::mSVG private
Definition at line 276 of file qgscomposerpicture.h.
Referenced by loadPicture(), and paint().
bool QgsComposerPicture::mUseSourceExpression private
Definition at line 279 of file qgscomposerpicture.h.
Referenced by evalPictureExpression(), loadPicture(), readXML(), refreshPicture(), setPictureExpression(), setUsePictureExpression(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerpicture.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposerpicture.cpp