QGIS API Documentation: QgsPaperItem Class Reference
QgsPaperItem Class Reference
Item representing the paper.
#include <qgspaperitem.h>
Public Member Functions
QgsPaperItem (QgsComposition *c)
QgsPaperItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition)
~QgsPaperItem ()
virtual int type () const
return correct graphics item type.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint.
bool writeXML (QDomElement &elem, QDomDocument &doc) const
stores state in Dom element
bool readXML (const QDomElement &itemElem, const QDomDocument &doc)
sets state from Dom document
virtual void setSceneRect (const QRectF &rectangle)
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected () const
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
int page () const
Gets the page the item is currently on.
QPointF pagePos () const
Returns the item's position relative to its current page.
void updatePagePos (double newPageWidth, double newPageHeight)
Moves the item so that it retains its relative position on the page when the paper size changes.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft, int page=-1)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft, bool posIncludesFrame=false, int page=-1)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
virtual void setFrameOutlineWidth (double outlineWidth)
Sets frame outline width.
double frameOutlineWidth () const
Returns the frame's outline width.
Qt::PenJoinStyle frameJoinStyle () const
Returns the join style used for drawing the item's frame.
void setFrameJoinStyle (Qt::PenJoinStyle style)
Sets join style used when drawing the item's frame.
virtual double estimatedFrameBleed () const
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
virtual QRectF rectWithFrame () const
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop, int flags=Qt::TextWordWrap) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font descent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightMillimeters (const QFont &font) const
Returns the font height in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
double itemRotation () const
Returns the rotation for the composer item.
Q_DECL_DEPRECATED double rotation () const
Returns the rotation for the composer item.
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
virtual int numberExportLayers () const
Get the number of layers that this item requires for exporting as layers.
virtual void setCurrentExportLayer (int layerIdx=-1)
Sets the current layer to draw for exporting.
Private Member Functions
QgsPaperItem ()
void initialize ()
Set flags and z-value.
void calculatePageMargin ()
Private Attributes
QgsPaperGrid * mPageGrid
double mPageMargin
Additional Inherited Members
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
Sets the item rotation.
virtual void setItemRotation (double r, bool adjustPosition=false)
Sets the item rotation.
void repaint ()
Signals inherited from QgsComposerItem
void itemRotationChanged (double newRotation)
Is emitted on item rotation change.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
void frameChanged ()
Emitted if the item's frame style changes.
Protected Member Functions inherited from QgsComposerItem
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height, double rotation) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Q_DECL_DEPRECATED bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
QRectF largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height, double rotation) const
Calculates corner point after rotation and scaling.
Q_DECL_DEPRECATED bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height, double rotation)
Calculates width / height of the bounding box of a rotated rectangle.
Q_DECL_DEPRECATED void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Protected Attributes inherited from QgsComposerItem
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
Qt::PenJoinStyle mFrameJoinStyle
Frame join style.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mItemRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
int mCurrentExportLayer
The layer that needs to be exported.
Detailed Description
Item representing the paper.
Definition at line 40 of file qgspaperitem.h.
Constructor & Destructor Documentation
QgsPaperItem::QgsPaperItem (QgsComposition * c)
Definition at line 125 of file qgspaperitem.cpp.
References initialize().
QgsPaperItem::QgsPaperItem (qreal x, qreal y, qreal width, qreal height, QgsComposition * composition)
Definition at line 131 of file qgspaperitem.cpp.
References initialize().
QgsPaperItem::~QgsPaperItem ()
Definition at line 143 of file qgspaperitem.cpp.
References mPageGrid.
QgsPaperItem::QgsPaperItem () private
Definition at line 137 of file qgspaperitem.cpp.
References initialize().
Member Function Documentation
void QgsPaperItem::calculatePageMargin () private
Definition at line 213 of file qgspaperitem.cpp.
References QgsSymbolLayerV2Utils::estimateMaxSymbolBleed(), QgsComposerItem::mComposition, mPageMargin, QgsComposition::pageStyleSymbol(), and QgsComposition::printResolution().
Referenced by paint().
void QgsPaperItem::initialize () private
Set flags and z-value.
Definition at line 246 of file qgspaperitem.cpp.
References QgsComposition::atlasComposition(), QgsComposerItem::mComposition, mPageGrid, and QgsComposerItem::repaint().
Referenced by QgsPaperItem().
void QgsPaperItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget)
Reimplementation of QCanvasItem::paint.
Definition at line 148 of file qgspaperitem.cpp.
References QgsComposition::atlasComposition(), QgsComposition::atlasMode(), QgsComposition::AtlasOff, calculatePageMargin(), QgsAtlasComposition::currentFeature(), QgsAtlasComposition::enabled(), QgsRenderContext::fromMapSettings(), QgsComposition::mapSettings(), QgsComposerItem::mComposition, mPageMargin, QgsComposition::pageStyleSymbol(), QgsComposition::plotStyle(), QgsComposition::Preview, QgsFillSymbolV2::renderPolygon(), QgsRenderContext::setForceVectorOutput(), QgsMapSettings::setOutputDpi(), QgsRenderContext::setPainter(), QgsSymbolV2::startRender(), and QgsSymbolV2::stopRender().
bool QgsPaperItem::readXML (const QDomElement & itemElem, const QDomDocument & doc) virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is the Dom document
Implements QgsComposerItem.
Definition at line 231 of file qgspaperitem.cpp.
void QgsPaperItem::setSceneRect (const QRectF & rectangle) virtual
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
Reimplemented from QgsComposerItem.
Definition at line 238 of file qgspaperitem.cpp.
References mPageGrid, and QgsComposerItem::setSceneRect().
virtual int QgsPaperItem::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerItem.
Definition at line 48 of file qgspaperitem.h.
References QgsComposerItem::ComposerPaper.
bool QgsPaperItem::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
stores state in Dom element
Parameters
elem is Dom element corresponding to 'Composer' tag
doc Dom document
Implements QgsComposerItem.
Definition at line 224 of file qgspaperitem.cpp.
Member Data Documentation
QgsPaperGrid* QgsPaperItem::mPageGrid private
Definition at line 74 of file qgspaperitem.h.
Referenced by initialize(), setSceneRect(), and ~QgsPaperItem().
double QgsPaperItem::mPageMargin private
Definition at line 75 of file qgspaperitem.h.
Referenced by calculatePageMargin(), and paint().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgspaperitem.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgspaperitem.cpp