QGIS API Documentation: QgsDistanceArea Class Reference
QgsDistanceArea Class Reference
QGIS core library
General purpose distance and area calculator.
#include <qgsdistancearea.h>
Public Member Functions
QgsDistanceArea ()
Constructor.
~QgsDistanceArea ()
Destructor.
QgsDistanceArea (const QgsDistanceArea &origDA)
Copy constructor.
QgsDistanceArea & operator= (const QgsDistanceArea &origDA)
Assignment operator.
void setEllipsoidalMode (bool flag)
sets whether coordinates must be projected to ellipsoid before measuring
bool ellipsoidalEnabled () const
returns projections enabled flag
void setSourceCrs (long srsid)
sets source spatial reference system (by QGIS CRS)
void setSourceCrs (const QgsCoordinateReferenceSystem &srcCRS)
Sets source spatial reference system (by QGIS CRS)
void setSourceAuthId (QString authid)
sets source spatial reference system by authid
long sourceCrs () const
returns source spatial reference system
bool geographic () const
What sort of coordinate system is being used?
bool setEllipsoid (const QString &ellipsoid)
sets ellipsoid by its acronym
bool setEllipsoid (double semiMajor, double semiMinor)
Sets ellipsoid by supplied radii.
const QString & ellipsoid () const
returns ellipsoid's acronym
double ellipsoidSemiMajor () const
returns ellipsoid's semi major axis
double ellipsoidSemiMinor () const
returns ellipsoid's semi minor axis
double ellipsoidInverseFlattening () const
returns ellipsoid's inverse flattening
double measure (QgsGeometry *geometry)
general measurement (line distance or polygon area)
double measurePerimeter (QgsGeometry *geometry)
measures perimeter of polygon
double measureLine (const QList< QgsPoint > &points)
measures line
double measureLine (const QgsPoint &p1, const QgsPoint &p2)
measures line with one segment
double measurePolygon (const QList< QgsPoint > &points)
measures polygon area
double bearing (const QgsPoint &p1, const QgsPoint &p2)
compute bearing - in radians
void convertMeasurement (double &measure, QGis::UnitType &measureUnits, QGis::UnitType displayUnits, bool isArea)
Helper for conversion between physical units.
Static Public Member Functions
static QString textUnit (double value, int decimals, QGis::UnitType u, bool isArea, bool keepBaseUnit=false)
Protected Member Functions
const unsigned char * measureLine (const unsigned char *feature, double *area, bool hasZptr=false)
measures line distance, line points are extracted from WKB
const unsigned char * measurePolygon (const unsigned char *feature, double *area, double *perimeter, bool hasZptr=false)
measures polygon area and perimeter, vertices are extracted from WKB
double computeDistanceBearing (const QgsPoint &p1, const QgsPoint &p2, double *course1=NULL, double *course2=NULL)
calculates distance from two points on ellipsoid based on inverse Vincenty's formulae
double computeDistanceFlat (const QgsPoint &p1, const QgsPoint &p2)
uses flat / planimetric / Euclidean distance
double computeDistance (const QList< QgsPoint > &points)
calculate distance with given coordinates (does not do a transform anymore)
double computePolygonArea (const QList< QgsPoint > &points)
calculates area of polygon on ellipsoid algorithm has been taken from GRASS: gis/area_poly1.c
double computePolygonFlatArea (const QList< QgsPoint > &points)
void computeAreaInit ()
precalculates some values (must be called always when changing ellipsoid)
Private Member Functions
void _copy (const QgsDistanceArea &origDA)
Copy helper.
double getQ (double x)
double getQbar (double x)
Private Attributes
QgsCoordinateTransform * mCoordTransform
used for transforming coordinates from source CRS to ellipsoid's coordinates
bool mEllipsoidalMode
indicates whether we will transform coordinates
QString mEllipsoid
ellipsoid acronym (from table tbl_ellipsoids)
double mSemiMajor
ellipsoid parameters
double mSemiMinor
double mInvFlattening
double m_QA
double m_QB
double m_QC
double m_QbarA
double m_QbarB
double m_QbarC
double m_QbarD
double m_AE
double m_Qp
double m_E
double m_TwoPI
Detailed Description
General purpose distance and area calculator.
calculations are done on ellipsoid
it's possible to pass points/features in any CRS, coordinates are transformed
two options how to use it
use measure() takes QgsGeometry as a parameter and calculates distance or area
use directly measureLine(), measurePolygon() which take list of QgsPoints (both cases transform the coordinates from source CRS to the ellipse coords)
returned values are in meters resp. square meters
Definition at line 34 of file qgsdistancearea.h.
Constructor & Destructor Documentation
QgsDistanceArea::QgsDistanceArea ()
Constructor.
Definition at line 41 of file qgsdistancearea.cpp.
References GEO_NONE, GEOCRS_ID, mCoordTransform, mEllipsoidalMode, setEllipsoid(), and setSourceCrs().
QgsDistanceArea::~QgsDistanceArea ()
Destructor.
Definition at line 57 of file qgsdistancearea.cpp.
References mCoordTransform.
QgsDistanceArea::QgsDistanceArea (const QgsDistanceArea & origDA)
Copy constructor.
Definition at line 52 of file qgsdistancearea.cpp.
References _copy().
Member Function Documentation
void QgsDistanceArea::_copy (const QgsDistanceArea & origDA) private
Copy helper.
Copy helper. Avoid Sqlite3 accesses.
Definition at line 75 of file qgsdistancearea.cpp.
References computeAreaInit(), QgsCoordinateTransform::destCRS(), mCoordTransform, mEllipsoid, mEllipsoidalMode, mInvFlattening, mSemiMajor, mSemiMinor, and QgsCoordinateTransform::sourceCrs().
Referenced by operator=(), and QgsDistanceArea().
double QgsDistanceArea::bearing (const QgsPoint & p1, const QgsPoint & p2)
compute bearing - in radians
Definition at line 613 of file qgsdistancearea.cpp.
References computeDistanceBearing(), GEO_NONE, mCoordTransform, mEllipsoid, mEllipsoidalMode, QgsCoordinateTransform::transform(), QgsPoint::x(), and QgsPoint::y().
Referenced by QgsTransectSample::createSample().
void QgsDistanceArea::computeAreaInit () protected
precalculates some values (must be called always when changing ellipsoid)
Definition at line 786 of file qgsdistancearea.cpp.
References getQ(), m_AE, m_E, M_PI, m_QA, m_QB, m_QbarA, m_QbarB, m_QbarC, m_QbarD, m_QC, m_Qp, m_TwoPI, mSemiMajor, and mSemiMinor.
Referenced by _copy(), and setEllipsoid().
double QgsDistanceArea::computeDistance (const QList< QgsPoint > & points) protected
calculate distance with given coordinates (does not do a transform anymore)
Definition at line 720 of file qgsdistancearea.cpp.
References computeDistanceBearing(), computeDistanceFlat(), GEO_NONE, QgsMessageLog::logMessage(), mEllipsoid, mEllipsoidalMode, and tr.
Referenced by measurePolygon().
double QgsDistanceArea::computeDistanceBearing (const QgsPoint & p1, const QgsPoint & p2, double * course1 = NULL, double * course2 = NULL) protected
calculates distance from two points on ellipsoid based on inverse Vincenty's formulae
Points p1 and p2 are expected to be in degrees and in currently used ellipsoid
Note
if course1 is not NULL, bearing (in radians) from first point is calculated (the same for course2)
Returns
distance in meters
Definition at line 638 of file qgsdistancearea.cpp.
References DEG2RAD, M_PI, mInvFlattening, mSemiMajor, mSemiMinor, QgsPoint::x(), and QgsPoint::y().
Referenced by bearing(), computeDistance(), and measureLine().
double QgsDistanceArea::computeDistanceFlat (const QgsPoint & p1, const QgsPoint & p2) protected
uses flat / planimetric / Euclidean distance
Definition at line 715 of file qgsdistancearea.cpp.
References QgsPoint::x(), and QgsPoint::y().
Referenced by computeDistance(), and measureLine().
double QgsDistanceArea::computePolygonArea (const QList< QgsPoint > & points) protected
calculates area of polygon on ellipsoid algorithm has been taken from GRASS: gis/area_poly1.c
Definition at line 815 of file qgsdistancearea.cpp.
References computePolygonFlatArea(), DEG2RAD, GEO_NONE, getQ(), getQbar(), m_AE, m_E, M_PI, m_Qp, m_TwoPI, mEllipsoid, mEllipsoidalMode, and QgsDebugMsgLevel.
Referenced by measurePolygon().
double QgsDistanceArea::computePolygonFlatArea (const QList< QgsPoint > & points) protected
Definition at line 872 of file qgsdistancearea.cpp.
References size.
Referenced by computePolygonArea().
void QgsDistanceArea::convertMeasurement (double & measure, QGis::UnitType & measureUnits, QGis::UnitType displayUnits, bool isArea)
Helper for conversion between physical units.
Definition at line 1022 of file qgsdistancearea.cpp.
References QGis::Degrees, QGis::Feet, QGis::fromUnitToUnitFactor(), GEO_NONE, QgsCoordinateReferenceSystem::mapUnits(), mCoordTransform, mEllipsoid, mEllipsoidalMode, QGis::Meters, QGis::NauticalMiles, QgsDebugMsg, QgsCoordinateTransform::sourceCrs(), and QGis::toLiteral().
Referenced by QgsMapToolIdentify::convertMeasurement().
const QString& QgsDistanceArea::ellipsoid () const inline
returns ellipsoid's acronym
Definition at line 80 of file qgsdistancearea.h.
Referenced by setEllipsoid().
bool QgsDistanceArea::ellipsoidalEnabled () const inline
returns projections enabled flag
Definition at line 53 of file qgsdistancearea.h.
double QgsDistanceArea::ellipsoidInverseFlattening () const inline
returns ellipsoid's inverse flattening
Definition at line 87 of file qgsdistancearea.h.
double QgsDistanceArea::ellipsoidSemiMajor () const inline
returns ellipsoid's semi major axis
Definition at line 83 of file qgsdistancearea.h.
double QgsDistanceArea::ellipsoidSemiMinor () const inline
returns ellipsoid's semi minor axis
Definition at line 85 of file qgsdistancearea.h.
bool QgsDistanceArea::geographic () const inline
What sort of coordinate system is being used?
Definition at line 70 of file qgsdistancearea.h.
double QgsDistanceArea::getQ (double x) private
Definition at line 764 of file qgsdistancearea.cpp.
References m_QA, m_QB, and m_QC.
Referenced by computeAreaInit(), and computePolygonArea().
double QgsDistanceArea::getQbar (double x) private
Definition at line 775 of file qgsdistancearea.cpp.
References m_QbarA, m_QbarB, m_QbarC, and m_QbarD.
Referenced by computePolygonArea().
double QgsDistanceArea::measure (QgsGeometry * geometry)
general measurement (line distance or polygon area)
Definition at line 257 of file qgsdistancearea.cpp.
References QgsGeometry::asWkb(), measureLine(), measurePolygon(), QgsDebugMsg, QGis::WKBLineString, QGis::WKBLineString25D, QGis::WKBMultiLineString, QGis::WKBMultiLineString25D, QGis::WKBMultiPolygon, QGis::WKBMultiPolygon25D, QGis::WKBPolygon, and QGis::WKBPolygon25D.
Referenced by QgsTransectSample::createSample(), fcnGeomArea(), fcnGeomLength(), QgsMapToolIdentify::featureDerivedAttributes(), QgsGeometryAnalyzer::perimeterMeasure(), and QgsGeometryAnalyzer::simpleMeasure().
double QgsDistanceArea::measureLine (const QList< QgsPoint > & points)
measures line
Definition at line 413 of file qgsdistancearea.cpp.
References computeDistanceBearing(), GEO_NONE, QgsMessageLog::logMessage(), mCoordTransform, mEllipsoid, mEllipsoidalMode, tr, and QgsCoordinateTransform::transform().
Referenced by QgsComposerScaleBar::mapWidth(), measure(), measureLine(), and QgsTransectSample::otherTransectWithinDistance().
double QgsDistanceArea::measureLine (const QgsPoint & p1, const QgsPoint & p2)
measures line with one segment
Definition at line 455 of file qgsdistancearea.cpp.
References computeDistanceBearing(), computeDistanceFlat(), QgsCoordinateTransform::destCRS(), GEO_NONE, QgsMessageLog::logMessage(), mCoordTransform, mEllipsoid, mEllipsoidalMode, QgsDebugMsgLevel, QgsCoordinateTransform::sourceCrs(), QgsCoordinateReferenceSystem::toProj4(), QgsPoint::toString(), tr, and QgsCoordinateTransform::transform().
const unsigned char * QgsDistanceArea::measureLine (const unsigned char * feature, double * area, bool hasZptr = false) protected
measures line distance, line points are extracted from WKB
Definition at line 386 of file qgsdistancearea.cpp.
References measureLine(), and QgsDebugMsg.
double QgsDistanceArea::measurePerimeter (QgsGeometry * geometry)
measures perimeter of polygon
Definition at line 328 of file qgsdistancearea.cpp.
References QgsGeometry::asWkb(), measurePolygon(), QgsDebugMsg, QGis::WKBLineString, QGis::WKBLineString25D, QGis::WKBMultiLineString, QGis::WKBMultiLineString25D, QGis::WKBMultiPolygon, QGis::WKBMultiPolygon25D, QGis::WKBPolygon, and QGis::WKBPolygon25D.
Referenced by fcnGeomPerimeter(), and QgsMapToolIdentify::featureDerivedAttributes().
double QgsDistanceArea::measurePolygon (const QList< QgsPoint > & points)
measures polygon area
Definition at line 586 of file qgsdistancearea.cpp.
References computePolygonArea(), GEO_NONE, QgsMessageLog::logMessage(), mCoordTransform, mEllipsoid, mEllipsoidalMode, tr, and QgsCoordinateTransform::transform().
Referenced by measure(), and measurePerimeter().
const unsigned char * QgsDistanceArea::measurePolygon (const unsigned char * feature, double * area, double * perimeter, bool hasZptr = false) protected
measures polygon area and perimeter, vertices are extracted from WKB
Definition at line 491 of file qgsdistancearea.cpp.
References computeDistance(), computePolygonArea(), GEO_NONE, QgsMessageLog::logMessage(), mCoordTransform, mEllipsoid, mEllipsoidalMode, QgsDebugMsg, tr, and QgsCoordinateTransform::transform().
QgsDistanceArea & QgsDistanceArea::operator= (const QgsDistanceArea & origDA)
Assignment operator.
Definition at line 63 of file qgsdistancearea.cpp.
References _copy().
bool QgsDistanceArea::setEllipsoid (const QString & ellipsoid)
sets ellipsoid by its acronym
Definition at line 112 of file qgsdistancearea.cpp.
References computeAreaInit(), QgsCoordinateReferenceSystem::createFromProj4(), ellipsoid(), GEO_NONE, QgsMessageLog::logMessage(), mCoordTransform, mEllipsoid, mInvFlattening, mSemiMajor, mSemiMinor, QgsDebugMsg, QgsCoordinateReferenceSystem::saveAsUserCRS(), QgsCoordinateTransform::setDestCRS(), QgsApplication::srsDbFilePath(), QgsCoordinateReferenceSystem::srsid(), QgsCoordinateReferenceSystem::toProj4(), and tr.
Referenced by QgsMapToolIdentify::featureDerivedAttributes(), QgsComposerScaleBar::mapWidth(), and QgsDistanceArea().
bool QgsDistanceArea::setEllipsoid (double semiMajor, double semiMinor)
Sets ellipsoid by supplied radii.
Definition at line 245 of file qgsdistancearea.cpp.
References computeAreaInit(), mEllipsoid, mInvFlattening, mSemiMajor, and mSemiMinor.
void QgsDistanceArea::setEllipsoidalMode (bool flag)
sets whether coordinates must be projected to ellipsoid before measuring
Definition at line 88 of file qgsdistancearea.cpp.
References mEllipsoidalMode.
Referenced by QgsTransectSample::createSample(), QgsMapToolIdentify::featureDerivedAttributes(), QgsExpression::initGeomCalculator(), QgsComposerScaleBar::mapWidth(), and QgsMapRenderer::setProjectionsEnabled().
void QgsDistanceArea::setSourceAuthId (QString authid)
sets source spatial reference system by authid
Definition at line 105 of file qgsdistancearea.cpp.
References QgsCoordinateReferenceSystem::createFromOgcWmsCrs(), mCoordTransform, and QgsCoordinateTransform::setSourceCrs().
void QgsDistanceArea::setSourceCrs (long srsid)
sets source spatial reference system (by QGIS CRS)
Definition at line 93 of file qgsdistancearea.cpp.
References QgsCoordinateReferenceSystem::createFromSrsId(), mCoordTransform, and QgsCoordinateTransform::setSourceCrs().
Referenced by QgsAttributeEditorContext::adjustForLayer(), QgsTransectSample::createSample(), QgsMapToolIdentify::featureDerivedAttributes(), QgsComposerScaleBar::mapWidth(), QgsDistanceArea(), and QgsMapRenderer::setDestinationCrs().
void QgsDistanceArea::setSourceCrs (const QgsCoordinateReferenceSystem & srcCRS)
Sets source spatial reference system (by QGIS CRS)
Note
: missing in Python bindings in QGIS < 2.2
Definition at line 100 of file qgsdistancearea.cpp.
References mCoordTransform, and QgsCoordinateTransform::setSourceCrs().
long QgsDistanceArea::sourceCrs () const inline
returns source spatial reference system
Definition at line 68 of file qgsdistancearea.h.
QString QgsDistanceArea::textUnit (double value, int decimals, QGis::UnitType u, bool isArea, bool keepBaseUnit = false) static
Definition at line 893 of file qgsdistancearea.cpp.
References QGis::Degrees, QGis::Feet, QGis::Meters, QGis::NauticalMiles, QgsDebugMsg, tr, and QGis::UnknownUnit.
Referenced by QgsMapToolIdentify::featureDerivedAttributes().
Member Data Documentation
double QgsDistanceArea::m_AE private
Definition at line 179 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and computePolygonArea().
double QgsDistanceArea::m_E private
Definition at line 181 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and computePolygonArea().
double QgsDistanceArea::m_QA private
Definition at line 177 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and getQ().
double QgsDistanceArea::m_QB private
Definition at line 177 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and getQ().
double QgsDistanceArea::m_QbarA private
Definition at line 178 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and getQbar().
double QgsDistanceArea::m_QbarB private
Definition at line 178 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and getQbar().
double QgsDistanceArea::m_QbarC private
Definition at line 178 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and getQbar().
double QgsDistanceArea::m_QbarD private
Definition at line 178 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and getQbar().
double QgsDistanceArea::m_QC private
Definition at line 177 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and getQ().
double QgsDistanceArea::m_Qp private
Definition at line 180 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and computePolygonArea().
double QgsDistanceArea::m_TwoPI private
Definition at line 182 of file qgsdistancearea.h.
Referenced by computeAreaInit(), and computePolygonArea().
QgsCoordinateTransform* QgsDistanceArea::mCoordTransform private
used for transforming coordinates from source CRS to ellipsoid's coordinates
Definition at line 159 of file qgsdistancearea.h.
Referenced by _copy(), bearing(), convertMeasurement(), measureLine(), measurePolygon(), QgsDistanceArea(), setEllipsoid(), setSourceAuthId(), setSourceCrs(), and ~QgsDistanceArea().
QString QgsDistanceArea::mEllipsoid private
ellipsoid acronym (from table tbl_ellipsoids)
Definition at line 165 of file qgsdistancearea.h.
Referenced by _copy(), bearing(), computeDistance(), computePolygonArea(), convertMeasurement(), measureLine(), measurePolygon(), and setEllipsoid().
bool QgsDistanceArea::mEllipsoidalMode private
indicates whether we will transform coordinates
Definition at line 162 of file qgsdistancearea.h.
Referenced by _copy(), bearing(), computeDistance(), computePolygonArea(), convertMeasurement(), measureLine(), measurePolygon(), QgsDistanceArea(), and setEllipsoidalMode().
double QgsDistanceArea::mInvFlattening private
Definition at line 168 of file qgsdistancearea.h.
Referenced by _copy(), computeDistanceBearing(), and setEllipsoid().
double QgsDistanceArea::mSemiMajor private
ellipsoid parameters
Definition at line 168 of file qgsdistancearea.h.
Referenced by _copy(), computeAreaInit(), computeDistanceBearing(), and setEllipsoid().
double QgsDistanceArea::mSemiMinor private
Definition at line 168 of file qgsdistancearea.h.
Referenced by _copy(), computeAreaInit(), computeDistanceBearing(), and setEllipsoid().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdistancearea.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdistancearea.cpp