QGIS API Documentation: QgsSingleBandPseudoColorRendererWidget Class Reference
QgsSingleBandPseudoColorRendererWidget Class Reference
#include <qgssinglebandpseudocolorrendererwidget.h>
Public Types
enum Mode { Continuous = 1, EqualInterval = 2 }
Public Types inherited from QgsRasterRendererWidget
enum LoadMinMaxAlgo { Estimate, Actual, CurrentExtent, CumulativeCut }
Public Slots
void loadMinMax (int theBandNo, double theMin, double theMax, int theOrigin)
Public Member Functions
QgsSingleBandPseudoColorRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent=QgsRectangle())
~QgsSingleBandPseudoColorRendererWidget ()
QgsRasterRenderer * renderer ()
void setFromRenderer (const QgsRasterRenderer *r)
Public Member Functions inherited from QgsRasterRendererWidget
QgsRasterRendererWidget (QgsRasterLayer *layer, const QgsRectangle &extent)
virtual ~QgsRasterRendererWidget ()
void setRasterLayer (QgsRasterLayer *layer)
const QgsRasterLayer * rasterLayer () const
virtual QString min (int index=0)
virtual QString max (int index=0)
virtual void setMin (QString value, int index=0)
virtual void setMax (QString value, int index=0)
virtual QString stdDev ()
virtual void setStdDev (QString value)
virtual int selectedBand (int index=0)
Static Public Member Functions
static QgsRasterRendererWidget * create (QgsRasterLayer *layer, const QgsRectangle &theExtent)
Private Slots
void on_mAddEntryButton_clicked ()
void on_mDeleteEntryButton_clicked ()
void on_mSortButton_clicked ()
void on_mClassifyButton_clicked ()
void on_mLoadFromBandButton_clicked ()
void on_mLoadFromFileButton_clicked ()
void on_mExportToFileButton_clicked ()
void on_mColormapTreeWidget_itemDoubleClicked (QTreeWidgetItem *item, int column)
void on_mBandComboBox_currentIndexChanged (int index)
void on_mMinLineEdit_textChanged (const QString &text)
void on_mMaxLineEdit_textChanged (const QString &text)
void on_mMinLineEdit_textEdited (const QString &text)
void on_mMaxLineEdit_textEdited (const QString &text)
void on_mClassificationModeComboBox_currentIndexChanged (int index)
void on_mColorRampComboBox_currentIndexChanged (int index)
Private Member Functions
void populateColormapTreeWidget (const QList< QgsColorRampShader::ColorRampItem > &colorRampItems)
void setLineEditValue (QLineEdit *theLineEdit, double theValue)
double lineEditValue (const QLineEdit *theLineEdit) const
void resetClassifyButton ()
void showMinMaxOrigin ()
Private Attributes
QgsRasterMinMaxWidget * mMinMaxWidget
int mMinMaxOrigin
Additional Inherited Members
Protected Member Functions inherited from QgsRasterRendererWidget
QString displayBandName (int band) const
Returns a band name for display.
Protected Attributes inherited from QgsRasterRendererWidget
QgsRasterLayer * mRasterLayer
QgsRectangle mExtent
Current extent.
Detailed Description
Definition at line 26 of file qgssinglebandpseudocolorrendererwidget.h.
Member Enumeration Documentation
enum QgsSingleBandPseudoColorRendererWidget::Mode
Enumerator
Continuous
EqualInterval
Definition at line 31 of file qgssinglebandpseudocolorrendererwidget.h.
Constructor & Destructor Documentation
QgsSingleBandPseudoColorRendererWidget::QgsSingleBandPseudoColorRendererWidget (QgsRasterLayer * layer, const QgsRectangle & extent = QgsRectangle())
Definition at line 32 of file qgssinglebandpseudocolorrendererwidget.cpp.
References QgsRasterInterface::bandCount(), Continuous, QgsRasterLayer::dataProvider(), QgsStyleV2::defaultStyle(), QgsRasterRendererWidget::displayBandName(), EqualInterval, QgsRasterMinMaxWidget::load(), loadMinMax(), mMinMaxWidget, QgsRasterRendererWidget::mRasterLayer, on_mClassificationModeComboBox_currentIndexChanged(), QgsDebugMsg, QgsRasterLayer::renderer(), resetClassifyButton(), QgsRasterMinMaxWidget::setExtent(), setFromRenderer(), and tr.
QgsSingleBandPseudoColorRendererWidget::~QgsSingleBandPseudoColorRendererWidget ()
Definition at line 103 of file qgssinglebandpseudocolorrendererwidget.cpp.
Member Function Documentation
static QgsRasterRendererWidget* QgsSingleBandPseudoColorRendererWidget::create (QgsRasterLayer * layer, const QgsRectangle & theExtent) inline static
Definition at line 40 of file qgssinglebandpseudocolorrendererwidget.h.
double QgsSingleBandPseudoColorRendererWidget::lineEditValue (const QLineEdit * theLineEdit) const private
Definition at line 651 of file qgssinglebandpseudocolorrendererwidget.cpp.
Referenced by on_mClassifyButton_clicked(), renderer(), and resetClassifyButton().
void QgsSingleBandPseudoColorRendererWidget::loadMinMax (int theBandNo, double theMin, double theMax, int theOrigin) slot
Definition at line 609 of file qgssinglebandpseudocolorrendererwidget.cpp.
References mMinMaxOrigin, QgsDebugMsg, and showMinMaxOrigin().
Referenced by QgsSingleBandPseudoColorRendererWidget().
void QgsSingleBandPseudoColorRendererWidget::on_mAddEntryButton_clicked () private slot
Definition at line 157 of file qgssinglebandpseudocolorrendererwidget.cpp.
References tr.
void QgsSingleBandPseudoColorRendererWidget::on_mBandComboBox_currentIndexChanged (int index) private slot
Definition at line 602 of file qgssinglebandpseudocolorrendererwidget.cpp.
References mMinMaxWidget, and QgsRasterMinMaxWidget::setBands().
void QgsSingleBandPseudoColorRendererWidget::on_mClassificationModeComboBox_currentIndexChanged (int index) private slot
Definition at line 341 of file qgssinglebandpseudocolorrendererwidget.cpp.
References EqualInterval.
Referenced by QgsSingleBandPseudoColorRendererWidget().
void QgsSingleBandPseudoColorRendererWidget::on_mClassifyButton_clicked () private slot
Definition at line 227 of file qgssinglebandpseudocolorrendererwidget.cpp.
References QgsVectorColorRampV2::color(), Continuous, QgsVectorColorRampV2::count(), lineEditValue(), QgsRasterRendererWidget::max(), QgsRasterRendererWidget::min(), QgsRasterRendererWidget::mRasterLayer, and QgsVectorColorRampV2::value().
void QgsSingleBandPseudoColorRendererWidget::on_mColormapTreeWidget_itemDoubleClicked (QTreeWidgetItem * item, int column) private slot
Definition at line 537 of file qgssinglebandpseudocolorrendererwidget.cpp.
void QgsSingleBandPseudoColorRendererWidget::on_mColorRampComboBox_currentIndexChanged (int index) private slot
Definition at line 346 of file qgssinglebandpseudocolorrendererwidget.cpp.
void QgsSingleBandPseudoColorRendererWidget::on_mDeleteEntryButton_clicked () private slot
Definition at line 165 of file qgssinglebandpseudocolorrendererwidget.cpp.
void QgsSingleBandPseudoColorRendererWidget::on_mExportToFileButton_clicked () private slot
Definition at line 474 of file qgssinglebandpseudocolorrendererwidget.cpp.
References tr.
void QgsSingleBandPseudoColorRendererWidget::on_mLoadFromBandButton_clicked () private slot
Definition at line 366 of file qgssinglebandpseudocolorrendererwidget.cpp.
References QgsRasterDataProvider::colorTable(), QgsRasterLayer::dataProvider(), QgsRasterRendererWidget::mRasterLayer, populateColormapTreeWidget(), and tr.
void QgsSingleBandPseudoColorRendererWidget::on_mLoadFromFileButton_clicked () private slot
Definition at line 388 of file qgssinglebandpseudocolorrendererwidget.cpp.
References populateColormapTreeWidget(), and tr.
void QgsSingleBandPseudoColorRendererWidget::on_mMaxLineEdit_textChanged (const QString & text) inline private slot
Definition at line 62 of file qgssinglebandpseudocolorrendererwidget.h.
void QgsSingleBandPseudoColorRendererWidget::on_mMaxLineEdit_textEdited (const QString & text) inline private slot
Definition at line 64 of file qgssinglebandpseudocolorrendererwidget.h.
References QgsRasterRenderer::MinMaxUser.
void QgsSingleBandPseudoColorRendererWidget::on_mMinLineEdit_textChanged (const QString & text) inline private slot
Definition at line 61 of file qgssinglebandpseudocolorrendererwidget.h.
void QgsSingleBandPseudoColorRendererWidget::on_mMinLineEdit_textEdited (const QString & text) inline private slot
Definition at line 63 of file qgssinglebandpseudocolorrendererwidget.h.
References QgsRasterRenderer::MinMaxUser.
void QgsSingleBandPseudoColorRendererWidget::on_mSortButton_clicked () private slot
Definition at line 174 of file qgssinglebandpseudocolorrendererwidget.cpp.
References QgsColorRampShader::ColorRampItem::color, QgsColorRampShader::ColorRampItem::label, populateColormapTreeWidget(), and QgsColorRampShader::ColorRampItem::value.
void QgsSingleBandPseudoColorRendererWidget::populateColormapTreeWidget (const QList< QgsColorRampShader::ColorRampItem > & colorRampItems) private
Definition at line 353 of file qgssinglebandpseudocolorrendererwidget.cpp.
Referenced by on_mLoadFromBandButton_clicked(), on_mLoadFromFileButton_clicked(), and on_mSortButton_clicked().
QgsRasterRenderer * QgsSingleBandPseudoColorRendererWidget::renderer () virtual
Implements QgsRasterRendererWidget.
Definition at line 107 of file qgssinglebandpseudocolorrendererwidget.cpp.
References QgsColorRampShader::ColorRampItem::color, QgsRasterLayer::dataProvider(), QgsColorRampShader::DISCRETE, QgsColorRampShader::EXACT, QgsColorRampShader::INTERPOLATED, QgsColorRampShader::ColorRampItem::label, lineEditValue(), mMinMaxOrigin, QgsRasterRendererWidget::mRasterLayer, QgsSingleBandPseudoColorRenderer::setClassificationMax(), QgsSingleBandPseudoColorRenderer::setClassificationMin(), QgsSingleBandPseudoColorRenderer::setClassificationMinMaxOrigin(), QgsColorRampShader::setClip(), QgsColorRampShader::setColorRampItemList(), QgsColorRampShader::setColorRampType(), QgsRasterShader::setRasterShaderFunction(), tr, and QgsColorRampShader::ColorRampItem::value.
void QgsSingleBandPseudoColorRendererWidget::resetClassifyButton () private
Definition at line 661 of file qgssinglebandpseudocolorrendererwidget.cpp.
References lineEditValue(), QgsRasterRendererWidget::max(), and QgsRasterRendererWidget::min().
Referenced by QgsSingleBandPseudoColorRendererWidget().
void QgsSingleBandPseudoColorRendererWidget::setFromRenderer (const QgsRasterRenderer * r)
Definition at line 559 of file qgssinglebandpseudocolorrendererwidget.cpp.
References QgsSingleBandPseudoColorRenderer::classificationMax(), QgsSingleBandPseudoColorRenderer::classificationMin(), QgsSingleBandPseudoColorRenderer::classificationMinMaxOrigin(), QgsColorRampShader::clip(), QgsColorRampShader::colorRampItemList(), QgsColorRampShader::colorRampType(), QgsColorRampShader::DISCRETE, QgsColorRampShader::INTERPOLATED, mMinMaxOrigin, QgsRasterShader::rasterShaderFunction(), setLineEditValue(), QgsSingleBandPseudoColorRenderer::shader(), showMinMaxOrigin(), and tr.
Referenced by QgsSingleBandPseudoColorRendererWidget().
void QgsSingleBandPseudoColorRendererWidget::setLineEditValue (QLineEdit * theLineEdit, double theValue) private
Definition at line 641 of file qgssinglebandpseudocolorrendererwidget.cpp.
Referenced by setFromRenderer().
void QgsSingleBandPseudoColorRendererWidget::showMinMaxOrigin () private
Definition at line 636 of file qgssinglebandpseudocolorrendererwidget.cpp.
References QgsRasterRenderer::minMaxOriginLabel(), and mMinMaxOrigin.
Referenced by loadMinMax(), and setFromRenderer().
Member Data Documentation
int QgsSingleBandPseudoColorRendererWidget::mMinMaxOrigin private
Definition at line 74 of file qgssinglebandpseudocolorrendererwidget.h.
Referenced by loadMinMax(), renderer(), setFromRenderer(), and showMinMaxOrigin().
QgsRasterMinMaxWidget* QgsSingleBandPseudoColorRendererWidget::mMinMaxWidget private
Definition at line 73 of file qgssinglebandpseudocolorrendererwidget.h.
Referenced by on_mBandComboBox_currentIndexChanged(), and QgsSingleBandPseudoColorRendererWidget().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/raster/qgssinglebandpseudocolorrendererwidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/raster/qgssinglebandpseudocolorrendererwidget.cpp