QGIS API Documentation: QgsSimpleMarkerSymbolLayerV2 Class Reference
QgsSimpleMarkerSymbolLayerV2 Class Reference
#include <qgsmarkersymbollayerv2.h>
Public Member Functions
QgsSimpleMarkerSymbolLayerV2 (QString name=DEFAULT_SIMPLEMARKER_NAME, QColor color=DEFAULT_SIMPLEMARKER_COLOR, QColor borderColor=DEFAULT_SIMPLEMARKER_BORDERCOLOR, double size=DEFAULT_SIMPLEMARKER_SIZE, double angle=DEFAULT_SIMPLEMARKER_ANGLE, QgsSymbolV2::ScaleMethod scaleMethod=DEFAULT_SCALE_METHOD)
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
void renderPoint (const QPointF &point, QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
void writeSldMarker (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
QString name () const
void setName (QString name)
QColor borderColor () const
void setBorderColor (QColor color)
Qt::PenStyle outlineStyle () const
void setOutlineStyle (Qt::PenStyle outlineStyle)
QColor outlineColor () const
Get outline color.
void setOutlineColor (const QColor &color)
Set outline color.
QColor fillColor () const
Get fill color.
void setFillColor (const QColor &color)
Set fill color.
double outlineWidth () const
void setOutlineWidth (double w)
void setOutlineWidthUnit (QgsSymbolV2::OutputUnit u)
QgsSymbolV2::OutputUnit outlineWidthUnit () const
void setOutlineWidthMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & outlineWidthMapUnitScale () const
bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
void setMapUnitScale (const QgsMapUnitScale &scale)
QgsMapUnitScale mapUnitScale () const
Public Member Functions inherited from QgsMarkerSymbolLayerV2
void startRender (QgsSymbolV2RenderContext &context)
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
void setSize (double size)
double size () const
void setScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod)
QgsSymbolV2::ScaleMethod scaleMethod () const
void setOffset (QPointF offset)
QPointF offset ()
virtual void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
void setOffsetUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit offsetUnit () const
void setOffsetMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & offsetMapUnitScale () const
void setSizeUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit sizeUnit () const
void setSizeMapUnitScale (const QgsMapUnitScale &scale)
const QgsMapUnitScale & sizeMapUnitScale () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
void setMapUnitScale (const QgsMapUnitScale &scale)
QgsMapUnitScale mapUnitScale () const
void setHorizontalAnchorPoint (HorizontalAnchorPoint h)
HorizontalAnchorPoint horizontalAnchorPoint () const
void setVerticalAnchorPoint (VerticalAnchorPoint v)
VerticalAnchorPoint verticalAnchorPoint () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual ~QgsSymbolLayerV2 ()
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
virtual Qt::PenStyle dxfPenStyle () const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Protected Member Functions
void drawMarker (QPainter *p, QgsSymbolV2RenderContext &context)
bool prepareShape (QString name=QString())
bool preparePath (QString name=QString())
bool prepareCache (QgsSymbolV2RenderContext &context)
Prepares cache image.
Protected Member Functions inherited from QgsMarkerSymbolLayerV2
QgsMarkerSymbolLayerV2 (bool locked=false)
void markerOffset (const QgsSymbolV2RenderContext &context, double &offsetX, double &offsetY) const
void markerOffset (const QgsSymbolV2RenderContext &context, double width, double height, double &offsetX, double &offsetY) const
void markerOffset (const QgsSymbolV2RenderContext &context, double width, double height, QgsSymbolV2::OutputUnit widthUnit, QgsSymbolV2::OutputUnit heightUnit, double &offsetX, double &offsetY, const QgsMapUnitScale &widthMapUnitScale, const QgsMapUnitScale &heightMapUnitScale) const
Protected Member Functions inherited from QgsSymbolLayerV2
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsFields *fields, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Protected Attributes
QColor mBorderColor
Qt::PenStyle mOutlineStyle
double mOutlineWidth
QgsSymbolV2::OutputUnit mOutlineWidthUnit
QgsMapUnitScale mOutlineWidthMapUnitScale
QPen mPen
QBrush mBrush
QPolygonF mPolygon
QPainterPath mPath
QString mName
QImage mCache
QPen mSelPen
QBrush mSelBrush
QImage mSelCache
bool mUsingCache
Protected Attributes inherited from QgsMarkerSymbolLayerV2
double mAngle
double mSize
QgsSymbolV2::OutputUnit mSizeUnit
QgsMapUnitScale mSizeMapUnitScale
QPointF mOffset
QgsSymbolV2::OutputUnit mOffsetUnit
QgsMapUnitScale mOffsetMapUnitScale
QgsSymbolV2::ScaleMethod mScaleMethod
HorizontalAnchorPoint mHorizontalAnchorPoint
VerticalAnchorPoint mVerticalAnchorPoint
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Static Protected Attributes
static const int mMaximumCacheWidth = 3000
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Private Attributes
QgsExpression * mAngleExpression
QgsExpression * mNameExpression
Additional Inherited Members
Public Types inherited from QgsMarkerSymbolLayerV2
enum HorizontalAnchorPoint { Left, HCenter, Right }
enum VerticalAnchorPoint { Top, VCenter, Bottom }
Static Protected Member Functions inherited from QgsMarkerSymbolLayerV2
static QPointF _rotatedOffset (const QPointF &offset, double angle)
Detailed Description
Definition at line 34 of file qgsmarkersymbollayerv2.h.
Constructor & Destructor Documentation
QgsSimpleMarkerSymbolLayerV2::QgsSimpleMarkerSymbolLayerV2 (QString name = DEFAULT_SIMPLEMARKER_NAME, QColor color = DEFAULT_SIMPLEMARKER_COLOR, QColor borderColor = DEFAULT_SIMPLEMARKER_BORDERCOLOR, double size = DEFAULT_SIMPLEMARKER_SIZE, double angle = DEFAULT_SIMPLEMARKER_ANGLE, QgsSymbolV2::ScaleMethod scaleMethod = DEFAULT_SCALE_METHOD)
Definition at line 50 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), borderColor(), QgsSymbolLayerV2::color(), QgsMarkerSymbolLayerV2::mAngle, mAngleExpression, mBorderColor, QgsSymbolLayerV2::mColor, QgsSymbolV2::MM, mName, mNameExpression, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetUnit, QgsMarkerSymbolLayerV2::mScaleMethod, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeUnit, name(), QgsMarkerSymbolLayerV2::scaleMethod(), and QgsMarkerSymbolLayerV2::size().
Referenced by clone(), create(), and createFromSld().
Member Function Documentation
QColor QgsSimpleMarkerSymbolLayerV2::borderColor (void) const inline
Definition at line 70 of file qgsmarkersymbollayerv2.h.
Referenced by create(), createFromSld(), and QgsSimpleMarkerSymbolLayerV2().
QgsSymbolLayerV2 * QgsSimpleMarkerSymbolLayerV2::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 613 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolLayerV2::copyDataDefinedProperties(), QgsMarkerSymbolLayerV2::mAngle, mBorderColor, QgsSymbolLayerV2::mColor, QgsMarkerSymbolLayerV2::mHorizontalAnchorPoint, mName, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetMapUnitScale, QgsMarkerSymbolLayerV2::mOffsetUnit, mOutlineStyle, mOutlineWidth, mOutlineWidthMapUnitScale, mOutlineWidthUnit, QgsMarkerSymbolLayerV2::mScaleMethod, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, QgsMarkerSymbolLayerV2::mVerticalAnchorPoint, QgsSimpleMarkerSymbolLayerV2(), QgsMarkerSymbolLayerV2::setHorizontalAnchorPoint(), QgsMarkerSymbolLayerV2::setOffset(), QgsMarkerSymbolLayerV2::setOffsetMapUnitScale(), QgsMarkerSymbolLayerV2::setOffsetUnit(), setOutlineStyle(), setOutlineWidth(), setOutlineWidthMapUnitScale(), setOutlineWidthUnit(), QgsMarkerSymbolLayerV2::setSizeMapUnitScale(), QgsMarkerSymbolLayerV2::setSizeUnit(), and QgsMarkerSymbolLayerV2::setVerticalAnchorPoint().
QgsSymbolLayerV2 * QgsSimpleMarkerSymbolLayerV2::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 66 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), borderColor(), QgsSymbolLayerV2::color(), QgsSymbolLayerV2Utils::decodeColor(), QgsSymbolLayerV2Utils::decodeMapUnitScale(), QgsSymbolLayerV2Utils::decodeOutputUnit(), QgsSymbolLayerV2Utils::decodePenStyle(), QgsSymbolLayerV2Utils::decodePoint(), QgsSymbolLayerV2Utils::decodeScaleMethod(), DEFAULT_SCALE_METHOD, DEFAULT_SIMPLEMARKER_ANGLE, DEFAULT_SIMPLEMARKER_BORDERCOLOR, DEFAULT_SIMPLEMARKER_COLOR, DEFAULT_SIMPLEMARKER_NAME, DEFAULT_SIMPLEMARKER_SIZE, name(), QgsSimpleMarkerSymbolLayerV2(), QgsMarkerSymbolLayerV2::scaleMethod(), QgsSymbolLayerV2::setDataDefinedProperty(), QgsMarkerSymbolLayerV2::setHorizontalAnchorPoint(), QgsMarkerSymbolLayerV2::setOffset(), QgsMarkerSymbolLayerV2::setOffsetMapUnitScale(), QgsMarkerSymbolLayerV2::setOffsetUnit(), setOutlineStyle(), setOutlineWidth(), setOutlineWidthMapUnitScale(), setOutlineWidthUnit(), QgsMarkerSymbolLayerV2::setSizeMapUnitScale(), QgsMarkerSymbolLayerV2::setSizeUnit(), QgsMarkerSymbolLayerV2::setVerticalAnchorPoint(), and QgsMarkerSymbolLayerV2::size().
Referenced by QgsMarkerSymbolV2::createSimple(), QgsSymbolLayerV2Registry::defaultSymbolLayer(), and QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsSimpleMarkerSymbolLayerV2::createFromSld (QDomElement & element) static
Definition at line 719 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), borderColor(), QgsSymbolLayerV2::color(), QgsSymbolLayerV2Utils::displacementFromSldElement(), name(), QgsMarkerSymbolLayerV2::offset(), QgsDebugMsg, QgsSimpleMarkerSymbolLayerV2(), QgsSymbolLayerV2Utils::rotationFromSldElement(), QgsMarkerSymbolLayerV2::setAngle(), QgsMarkerSymbolLayerV2::setOffset(), setOutlineStyle(), QgsMarkerSymbolLayerV2::size(), and QgsSymbolLayerV2Utils::wellKnownMarkerFromSld().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
void QgsSimpleMarkerSymbolLayerV2::drawMarker (QPainter * p, QgsSymbolV2RenderContext & context) protected
Definition at line 755 of file qgsmarkersymbollayerv2.cpp.
References mPath, and mPolygon.
Referenced by prepareCache().
QColor QgsSimpleMarkerSymbolLayerV2::fillColor () const inline virtual
Get fill color.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 85 of file qgsmarkersymbollayerv2.h.
References QgsSymbolLayerV2::color().
QString QgsSimpleMarkerSymbolLayerV2::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 167 of file qgsmarkersymbollayerv2.cpp.
QgsMapUnitScale QgsSimpleMarkerSymbolLayerV2::mapUnitScale () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 967 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::mapUnitScale(), and mOutlineWidthMapUnitScale.
QString QgsSimpleMarkerSymbolLayerV2::name () const inline
Definition at line 67 of file qgsmarkersymbollayerv2.h.
Referenced by create(), createFromSld(), QgsSimpleMarkerSymbolLayerV2(), and renderPoint().
QString QgsSimpleMarkerSymbolLayerV2::ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 657 of file qgsmarkersymbollayerv2.cpp.
References mBorderColor, QgsSymbolLayerV2::mColor, mName, and QgsMarkerSymbolLayerV2::mSize.
QColor QgsSimpleMarkerSymbolLayerV2::outlineColor () const inline virtual
Get outline color.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 78 of file qgsmarkersymbollayerv2.h.
Qt::PenStyle QgsSimpleMarkerSymbolLayerV2::outlineStyle () const inline
Definition at line 73 of file qgsmarkersymbollayerv2.h.
double QgsSimpleMarkerSymbolLayerV2::outlineWidth () const inline
Definition at line 90 of file qgsmarkersymbollayerv2.h.
Referenced by renderPoint(), QgsHighlight::setSymbol(), and writeDxf().
const QgsMapUnitScale& QgsSimpleMarkerSymbolLayerV2::outlineWidthMapUnitScale () const inline
Definition at line 97 of file qgsmarkersymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsSimpleMarkerSymbolLayerV2::outlineWidthUnit () const inline
Definition at line 94 of file qgsmarkersymbollayerv2.h.
Referenced by QgsHighlight::setSymbol().
QgsSymbolV2::OutputUnit QgsSimpleMarkerSymbolLayerV2::outputUnit () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 952 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolV2::Mixed, mOutlineWidthUnit, and QgsMarkerSymbolLayerV2::outputUnit().
bool QgsSimpleMarkerSymbolLayerV2::prepareCache (QgsSymbolV2RenderContext & context) protected
Prepares cache image.
Returns
true in case of success, false if cache image size too large
Definition at line 270 of file qgsmarkersymbollayerv2.cpp.
References drawMarker(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mBrush, mCache, mMaximumCacheWidth, mPen, mSelBrush, mSelCache, mSelPen, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, QgsSymbolV2RenderContext::renderContext(), and QgsRenderContext::selectionColor().
Referenced by startRender().
bool QgsSimpleMarkerSymbolLayerV2::preparePath (QString name = QString()) protected
Definition at line 429 of file qgsmarkersymbollayerv2.cpp.
References mName, and mPath.
Referenced by renderPoint(), and startRender().
bool QgsSimpleMarkerSymbolLayerV2::prepareShape (QString name = QString()) protected
Definition at line 335 of file qgsmarkersymbollayerv2.cpp.
References DEG2RAD, mName, and mPolygon.
Referenced by renderPoint(), and startRender().
QgsStringMap QgsSimpleMarkerSymbolLayerV2::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 586 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeColor(), QgsSymbolLayerV2Utils::encodeMapUnitScale(), QgsSymbolLayerV2Utils::encodeOutputUnit(), QgsSymbolLayerV2Utils::encodePenStyle(), QgsSymbolLayerV2Utils::encodePoint(), QgsSymbolLayerV2Utils::encodeScaleMethod(), QgsMarkerSymbolLayerV2::mAngle, mBorderColor, QgsSymbolLayerV2::mColor, QgsMarkerSymbolLayerV2::mHorizontalAnchorPoint, mName, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetMapUnitScale, QgsMarkerSymbolLayerV2::mOffsetUnit, mOutlineStyle, mOutlineWidth, mOutlineWidthMapUnitScale, mOutlineWidthUnit, QgsMarkerSymbolLayerV2::mScaleMethod, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, QgsMarkerSymbolLayerV2::mVerticalAnchorPoint, and QgsSymbolLayerV2::saveDataDefinedProperties().
void QgsSimpleMarkerSymbolLayerV2::renderPoint (const QPointF & point, QgsSymbolV2RenderContext & context) virtual
Implements QgsMarkerSymbolLayerV2.
Definition at line 476 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::_rotatedOffset(), QgsMarkerSymbolLayerV2::angle(), QgsSymbolV2::DataDefinedRotation, QgsSymbolV2::DataDefinedSizeScale, QgsSymbolLayerV2Utils::decodeColor(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsMarkerSymbolLayerV2::mAngle, mAngleExpression, QgsMarkerSymbolLayerV2::markerOffset(), mBrush, mCache, mNameExpression, mOutlineWidthMapUnitScale, mOutlineWidthUnit, mPath, mPen, mPolygon, QgsMarkerSymbolLayerV2::mScaleMethod, mSelBrush, mSelCache, mSelPen, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, mUsingCache, name(), outlineWidth(), QgsRenderContext::painter(), preparePath(), prepareShape(), QgsRenderContext::rasterScaleFactor(), QgsSymbolV2RenderContext::renderContext(), QgsSymbolV2RenderContext::renderHints(), QgsSymbolV2::ScaleArea, and QgsSymbolV2RenderContext::selected().
void QgsSimpleMarkerSymbolLayerV2::setBorderColor (QColor color) inline
Definition at line 71 of file qgsmarkersymbollayerv2.h.
References QgsSymbolLayerV2::color().
void QgsSimpleMarkerSymbolLayerV2::setFillColor (const QColor & color) inline virtual
Set fill color.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 88 of file qgsmarkersymbollayerv2.h.
References QgsSymbolLayerV2::setColor().
void QgsSimpleMarkerSymbolLayerV2::setMapUnitScale (const QgsMapUnitScale & scale) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 961 of file qgsmarkersymbollayerv2.cpp.
References mOutlineWidthMapUnitScale, and QgsMarkerSymbolLayerV2::setMapUnitScale().
void QgsSimpleMarkerSymbolLayerV2::setName (QString name) inline
Definition at line 68 of file qgsmarkersymbollayerv2.h.
void QgsSimpleMarkerSymbolLayerV2::setOutlineColor (const QColor & color) inline virtual
Set outline color.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 81 of file qgsmarkersymbollayerv2.h.
void QgsSimpleMarkerSymbolLayerV2::setOutlineStyle (Qt::PenStyle outlineStyle) inline
Definition at line 74 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSimpleMarkerSymbolLayerV2::setOutlineWidth (double w) inline
Definition at line 91 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), create(), and QgsHighlight::setSymbol().
void QgsSimpleMarkerSymbolLayerV2::setOutlineWidthMapUnitScale (const QgsMapUnitScale & scale) inline
Definition at line 96 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), and create().
void QgsSimpleMarkerSymbolLayerV2::setOutlineWidthUnit (QgsSymbolV2::OutputUnit u) inline
Definition at line 93 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), and create().
void QgsSimpleMarkerSymbolLayerV2::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 946 of file qgsmarkersymbollayerv2.cpp.
References mOutlineWidthUnit, and QgsMarkerSymbolLayerV2::setOutputUnit().
void QgsSimpleMarkerSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 172 of file qgsmarkersymbollayerv2.cpp.
References QgsSymbolV2RenderContext::alpha(), QgsSymbolLayerV2::dataDefinedProperty(), QgsSymbolV2::DataDefinedRotation, QgsSymbolV2::DataDefinedSizeScale, QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::fields(), QgsRenderContext::forceVectorOutput(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsMarkerSymbolLayerV2::mAngle, mAngleExpression, mBorderColor, mBrush, mCache, QgsSymbolLayerV2::mColor, mName, mNameExpression, mOutlineStyle, mOutlineWidth, mOutlineWidthMapUnitScale, mOutlineWidthUnit, mPath, mPen, mPolygon, mSelBrush, mSelCache, mSelPen, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, mUsingCache, prepareCache(), QgsSymbolLayerV2::prepareExpressions(), preparePath(), prepareShape(), QgsDebugMsg, QgsRenderContext::rasterScaleFactor(), QgsSymbolV2RenderContext::renderContext(), QgsRenderContext::rendererScale(), QgsSymbolV2RenderContext::renderHints(), QgsRenderContext::selectionColor(), and QgsMarkerSymbolLayerV2::startRender().
void QgsSimpleMarkerSymbolLayerV2::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 330 of file qgsmarkersymbollayerv2.cpp.
bool QgsSimpleMarkerSymbolLayerV2::writeDxf (QgsDxfExport & e, double mmMapUnitScaleFactor, const QString & layerName, const QgsSymbolV2RenderContext * context, const QgsFeature * f, const QPointF & shift = QPointF(0.0, 0.0)) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 769 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::_rotatedOffset(), QgsMarkerSymbolLayerV2::angle(), QgsSymbolV2::DataDefinedSizeScale, QgsSymbolLayerV2Utils::decodeColor(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsMarkerSymbolLayerV2::mAngle, QgsMarkerSymbolLayerV2::markerOffset(), mBrush, QgsSymbolV2::MM, mName, mOutlineWidth, mPen, QgsMarkerSymbolLayerV2::mScaleMethod, QgsMarkerSymbolLayerV2::mSize, QgsMarkerSymbolLayerV2::mSizeMapUnitScale, QgsMarkerSymbolLayerV2::mSizeUnit, outlineWidth(), QgsSymbolV2RenderContext::renderContext(), QgsSymbolV2RenderContext::renderHints(), QgsSymbolV2::ScaleArea, QgsSymbolV2::ScaleDiameter, and QgsMarkerSymbolLayerV2::size().
void QgsSimpleMarkerSymbolLayerV2::writeSldMarker (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsMarkerSymbolLayerV2.
Definition at line 631 of file qgsmarkersymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::createDisplacementElement(), QgsSymbolLayerV2Utils::createRotationElement(), QgsMarkerSymbolLayerV2::mAngle, mBorderColor, QgsSymbolLayerV2::mColor, mName, QgsMarkerSymbolLayerV2::mOffset, mOutlineStyle, mOutlineWidth, QgsMarkerSymbolLayerV2::mSize, and QgsSymbolLayerV2Utils::wellKnownMarkerToSld().
Member Data Documentation
QgsExpression* QgsSimpleMarkerSymbolLayerV2::mAngleExpression private
Definition at line 137 of file qgsmarkersymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2(), renderPoint(), and startRender().
QColor QgsSimpleMarkerSymbolLayerV2::mBorderColor protected
Definition at line 117 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), ogrFeatureStyle(), properties(), QgsSimpleMarkerSymbolLayerV2(), startRender(), and writeSldMarker().
QBrush QgsSimpleMarkerSymbolLayerV2::mBrush protected
Definition at line 123 of file qgsmarkersymbollayerv2.h.
Referenced by prepareCache(), renderPoint(), startRender(), and writeDxf().
QImage QgsSimpleMarkerSymbolLayerV2::mCache protected
Definition at line 127 of file qgsmarkersymbollayerv2.h.
Referenced by prepareCache(), renderPoint(), and startRender().
const int QgsSimpleMarkerSymbolLayerV2::mMaximumCacheWidth = 3000 static protected
Definition at line 134 of file qgsmarkersymbollayerv2.h.
Referenced by prepareCache().
QString QgsSimpleMarkerSymbolLayerV2::mName protected
Definition at line 126 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), ogrFeatureStyle(), preparePath(), prepareShape(), properties(), QgsSimpleMarkerSymbolLayerV2(), startRender(), writeDxf(), and writeSldMarker().
QgsExpression* QgsSimpleMarkerSymbolLayerV2::mNameExpression private
Definition at line 138 of file qgsmarkersymbollayerv2.h.
Referenced by QgsSimpleMarkerSymbolLayerV2(), renderPoint(), and startRender().
Qt::PenStyle QgsSimpleMarkerSymbolLayerV2::mOutlineStyle protected
Definition at line 118 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), properties(), startRender(), and writeSldMarker().
double QgsSimpleMarkerSymbolLayerV2::mOutlineWidth protected
Definition at line 119 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), properties(), startRender(), writeDxf(), and writeSldMarker().
QgsMapUnitScale QgsSimpleMarkerSymbolLayerV2::mOutlineWidthMapUnitScale protected
Definition at line 121 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), mapUnitScale(), properties(), renderPoint(), setMapUnitScale(), and startRender().
QgsSymbolV2::OutputUnit QgsSimpleMarkerSymbolLayerV2::mOutlineWidthUnit protected
Definition at line 120 of file qgsmarkersymbollayerv2.h.
Referenced by clone(), outputUnit(), properties(), renderPoint(), setOutputUnit(), and startRender().
QPainterPath QgsSimpleMarkerSymbolLayerV2::mPath protected
Definition at line 125 of file qgsmarkersymbollayerv2.h.
Referenced by drawMarker(), preparePath(), renderPoint(), and startRender().
QPen QgsSimpleMarkerSymbolLayerV2::mPen protected
Definition at line 122 of file qgsmarkersymbollayerv2.h.
Referenced by prepareCache(), renderPoint(), startRender(), and writeDxf().
QPolygonF QgsSimpleMarkerSymbolLayerV2::mPolygon protected
Definition at line 124 of file qgsmarkersymbollayerv2.h.
Referenced by drawMarker(), prepareShape(), renderPoint(), and startRender().
QBrush QgsSimpleMarkerSymbolLayerV2::mSelBrush protected
Definition at line 129 of file qgsmarkersymbollayerv2.h.
Referenced by prepareCache(), renderPoint(), and startRender().
QImage QgsSimpleMarkerSymbolLayerV2::mSelCache protected
Definition at line 130 of file qgsmarkersymbollayerv2.h.
Referenced by prepareCache(), renderPoint(), and startRender().
QPen QgsSimpleMarkerSymbolLayerV2::mSelPen protected
Definition at line 128 of file qgsmarkersymbollayerv2.h.
Referenced by prepareCache(), renderPoint(), and startRender().
bool QgsSimpleMarkerSymbolLayerV2::mUsingCache protected
Definition at line 131 of file qgsmarkersymbollayerv2.h.
Referenced by renderPoint(), and startRender().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsmarkersymbollayerv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgsmarkersymbollayerv2.cpp