QGIS API Documentation: QgsFieldExpressionWidget Class Reference
QgsFieldExpressionWidget Class Reference
The QgsFieldExpressionWidget class reates a widget to choose fields and edit expressions It contains a combo boxto display the fields and expression and a button to open the expression dialog.
#include <qgsfieldexpressionwidget.h>
Public Slots
void setLayer (QgsVectorLayer *layer)
set the layer used to display the fields and expression
void setLayer (QgsMapLayer *layer)
convenience slot to connect QgsMapLayerComboBox layer signal
void setField (const QString &fieldName)
sets the current field or expression in the widget
Signals
void fieldChanged (QString fieldName)
the signal is emitted when the currently selected field changes
void fieldChanged (QString fieldName, bool isValid)
fieldChanged signal with indication of the validity of the expression
Public Member Functions
QgsFieldExpressionWidget (QWidget *parent=0)
QgsFieldExpressionWidget creates a widget with a combo box to display the fields and expression and a button to open the expression dialog.
void setExpressionDialogTitle (QString title)
define the title used in the expression dialog
const QString expressionDialogTitle ()
return the title used for the expression dialog
void setFilters (QgsFieldProxyModel::Filters filters)
setFilters allows fitering according to the type of field
void setLeftHandButtonStyle (bool isLeft)
QgsFieldProxyModel::Filters filters ()
currently used filter on list of fields
void setGeomCalculator (const QgsDistanceArea &da)
set the geometry calculator used in the expression dialog
QString currentField (bool *isExpression=0, bool *isValid=0)
currentField returns the currently selected field or expression if allowed
bool isValidExpression (QString *expressionError=0)
Return true if the current expression is valid.
bool isExpression ()
QString currentText ()
Return the current text that is set in the expression area.
QgsVectorLayer * layer ()
Returns the currently used layer.
Protected Slots
void editExpression ()
open the expression dialog to edit the current or add a new expression
void expressionEdited (const QString expression)
when expression is edited by the user in the line edit, it will be checked for validity
void expressionEditingFinished ()
when expression has been edited (finished) it will be added to the model
void currentFieldChanged ()
void updateLineEditStyle (const QString expression=QString())
updateLineEditStyle will re-style (color/font) the line edit depending on content and status
bool isExpressionValid (const QString expressionStr)
Protected Member Functions
void changeEvent (QEvent *event)
Properties
QString expressionDialogTitle
QgsFieldProxyModel::Filters filters
Private Attributes
QComboBox * mCombo
QToolButton * mButton
QgsFieldProxyModel * mFieldProxyModel
QString mExpressionDialogTitle
QSharedPointer< const
QgsDistanceArea > mDa
Detailed Description
The QgsFieldExpressionWidget class reates a widget to choose fields and edit expressions It contains a combo boxto display the fields and expression and a button to open the expression dialog.
The combo box is editable, allowing expressions to be edited inline. The validity of the expression is checked live on key press, invalid expressions are displayed in red. The expression will be added to the model (and the fieldChanged signals emitted) only when editing in the line edit is finished (focus lost, enter key pressed).
Definition at line 40 of file qgsfieldexpressionwidget.h.
Constructor & Destructor Documentation
QgsFieldExpressionWidget::QgsFieldExpressionWidget (QWidget * parent = 0) explicit
QgsFieldExpressionWidget creates a widget with a combo box to display the fields and expression and a button to open the expression dialog.
Definition at line 25 of file qgsfieldexpressionwidget.cpp.
References currentFieldChanged(), editExpression(), expressionEdited(), expressionEditingFinished(), QgsApplication::getThemeIcon(), mButton, mCombo, mFieldProxyModel, QgsFieldModel::setAllowExpression(), and QgsFieldProxyModel::sourceFieldModel().
Member Function Documentation
void QgsFieldExpressionWidget::changeEvent (QEvent * event) protected
Definition at line 200 of file qgsfieldexpressionwidget.cpp.
References updateLineEditStyle().
QString QgsFieldExpressionWidget::currentField (bool * isExpression = 0, bool * isValid = 0)
currentField returns the currently selected field or expression if allowed
Parameters
isExpression determines if the string returned is the name of a field or an expression
isValid determines if the expression (or field) returned is valid
Definition at line 103 of file qgsfieldexpressionwidget.cpp.
References currentText(), isExpression(), and isValidExpression().
Referenced by currentFieldChanged(), and updateLineEditStyle().
void QgsFieldExpressionWidget::currentFieldChanged () protected slot
Definition at line 208 of file qgsfieldexpressionwidget.cpp.
References currentField(), fieldChanged(), isExpression(), mCombo, and updateLineEditStyle().
Referenced by expressionEditingFinished(), QgsFieldExpressionWidget(), and setField().
QString QgsFieldExpressionWidget::currentText ()
Return the current text that is set in the expression area.
Definition at line 86 of file qgsfieldexpressionwidget.cpp.
References mCombo.
Referenced by currentField(), editExpression(), isExpression(), and isValidExpression().
void QgsFieldExpressionWidget::editExpression () protected slot
open the expression dialog to edit the current or add a new expression
Definition at line 164 of file qgsfieldexpressionwidget.cpp.
References currentText(), QgsExpressionBuilderDialog::expressionText(), layer(), mDa, mExpressionDialogTitle, setField(), and QgsExpressionBuilderDialog::setGeomCalculator().
Referenced by QgsFieldExpressionWidget().
const QString QgsFieldExpressionWidget::expressionDialogTitle () inline
return the title used for the expression dialog
Definition at line 57 of file qgsfieldexpressionwidget.h.
void QgsFieldExpressionWidget::expressionEdited (const QString expression) protected slot
when expression is edited by the user in the line edit, it will be checked for validity
Definition at line 183 of file qgsfieldexpressionwidget.cpp.
References fieldChanged(), isValidExpression(), and updateLineEditStyle().
Referenced by QgsFieldExpressionWidget().
void QgsFieldExpressionWidget::expressionEditingFinished () protected slot
when expression has been edited (finished) it will be added to the model
Definition at line 189 of file qgsfieldexpressionwidget.cpp.
References currentFieldChanged(), QgsFieldModel::indexFromName(), mCombo, mFieldProxyModel, QgsDebugMsg, QgsFieldModel::setExpression(), and QgsFieldProxyModel::sourceFieldModel().
Referenced by QgsFieldExpressionWidget().
void QgsFieldExpressionWidget::fieldChanged (QString fieldName) signal
the signal is emitted when the currently selected field changes
Referenced by currentFieldChanged(), and expressionEdited().
void QgsFieldExpressionWidget::fieldChanged (QString fieldName, bool isValid) signal
fieldChanged signal with indication of the validity of the expression
QgsFieldProxyModel::Filters QgsFieldExpressionWidget::filters () inline
currently used filter on list of fields
Definition at line 65 of file qgsfieldexpressionwidget.h.
bool QgsFieldExpressionWidget::isExpression ()
Definition at line 98 of file qgsfieldexpressionwidget.cpp.
References currentText(), QgsFieldModel::isField(), mFieldProxyModel, and QgsFieldProxyModel::sourceFieldModel().
Referenced by currentField(), currentFieldChanged(), and updateLineEditStyle().
bool QgsFieldExpressionWidget::isExpressionValid (const QString expressionStr) protected slot
Definition at line 265 of file qgsfieldexpressionwidget.cpp.
References QgsExpression::hasParserError(), layer(), QgsVectorLayer::pendingFields(), and QgsExpression::prepare().
Referenced by updateLineEditStyle().
bool QgsFieldExpressionWidget::isValidExpression (QString * expressionError = 0)
Return true if the current expression is valid.
Definition at line 91 of file qgsfieldexpressionwidget.cpp.
References currentText(), QgsExpression::isValid(), layer(), and QgsVectorLayer::pendingFields().
Referenced by currentField(), and expressionEdited().
QgsVectorLayer * QgsFieldExpressionWidget::layer ()
Returns the currently used layer.
Definition at line 117 of file qgsfieldexpressionwidget.cpp.
References QgsFieldModel::layer(), mFieldProxyModel, and QgsFieldProxyModel::sourceFieldModel().
Referenced by editExpression(), isExpressionValid(), isValidExpression(), and setLayer().
void QgsFieldExpressionWidget::setExpressionDialogTitle (QString title)
define the title used in the expression dialog
Definition at line 59 of file qgsfieldexpressionwidget.cpp.
References mExpressionDialogTitle.
void QgsFieldExpressionWidget::setField (const QString & fieldName) slot
sets the current field or expression in the widget
Definition at line 136 of file qgsfieldexpressionwidget.cpp.
References currentFieldChanged(), QgsFieldModel::indexFromName(), mCombo, mFieldProxyModel, QgsFieldModel::setExpression(), and QgsFieldProxyModel::sourceFieldModel().
Referenced by editExpression().
void QgsFieldExpressionWidget::setFilters (QgsFieldProxyModel::Filters filters)
setFilters allows fitering according to the type of field
Definition at line 64 of file qgsfieldexpressionwidget.cpp.
References mFieldProxyModel, and QgsFieldProxyModel::setFilters().
void QgsFieldExpressionWidget::setGeomCalculator (const QgsDistanceArea & da)
set the geometry calculator used in the expression dialog
Definition at line 81 of file qgsfieldexpressionwidget.cpp.
References mDa.
void QgsFieldExpressionWidget::setLayer (QgsVectorLayer * layer) slot
set the layer used to display the fields and expression
Definition at line 131 of file qgsfieldexpressionwidget.cpp.
References mFieldProxyModel, QgsFieldModel::setLayer(), and QgsFieldProxyModel::sourceFieldModel().
Referenced by setLayer().
void QgsFieldExpressionWidget::setLayer (QgsMapLayer * layer) slot
convenience slot to connect QgsMapLayerComboBox layer signal
Definition at line 122 of file qgsfieldexpressionwidget.cpp.
References layer(), and setLayer().
void QgsFieldExpressionWidget::setLeftHandButtonStyle (bool isLeft)
Definition at line 69 of file qgsfieldexpressionwidget.cpp.
References mCombo.
void QgsFieldExpressionWidget::updateLineEditStyle (const QString expression = QString()) protected slot
updateLineEditStyle will re-style (color/font) the line edit depending on content and status
Parameters
expression if expression is given it will be evaluated for the given string, otherwise it takes current expression from the model
Definition at line 230 of file qgsfieldexpressionwidget.cpp.
References currentField(), isExpression(), isExpressionValid(), and mCombo.
Referenced by changeEvent(), currentFieldChanged(), and expressionEdited().
Member Data Documentation
QToolButton* QgsFieldExpressionWidget::mButton private
Definition at line 136 of file qgsfieldexpressionwidget.h.
Referenced by QgsFieldExpressionWidget().
QComboBox* QgsFieldExpressionWidget::mCombo private
Definition at line 135 of file qgsfieldexpressionwidget.h.
Referenced by currentFieldChanged(), currentText(), expressionEditingFinished(), QgsFieldExpressionWidget(), setField(), setLeftHandButtonStyle(), and updateLineEditStyle().
QSharedPointer<const QgsDistanceArea> QgsFieldExpressionWidget::mDa private
Definition at line 139 of file qgsfieldexpressionwidget.h.
Referenced by editExpression(), and setGeomCalculator().
QString QgsFieldExpressionWidget::mExpressionDialogTitle private
Definition at line 138 of file qgsfieldexpressionwidget.h.
Referenced by editExpression(), and setExpressionDialogTitle().
QgsFieldProxyModel* QgsFieldExpressionWidget::mFieldProxyModel private
Definition at line 137 of file qgsfieldexpressionwidget.h.
Referenced by expressionEditingFinished(), isExpression(), layer(), QgsFieldExpressionWidget(), setField(), setFilters(), and setLayer().
Property Documentation
QString QgsFieldExpressionWidget::expressionDialogTitle read write
Definition at line 43 of file qgsfieldexpressionwidget.h.
QgsFieldProxyModel::Filters QgsFieldExpressionWidget::filters read write
Definition at line 45 of file qgsfieldexpressionwidget.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsfieldexpressionwidget.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsfieldexpressionwidget.cpp