QGIS API Documentation: QgsFeatureIterator Class Reference
QgsFeatureIterator Class Reference
QGIS core library
Wrapper for iterator of features from vector data provider or vector layer.
#include <qgsfeatureiterator.h>
Public Member Functions
QgsFeatureIterator ()
construct invalid iterator
QgsFeatureIterator (QgsAbstractFeatureIterator *iter)
construct a valid iterator
QgsFeatureIterator (const QgsFeatureIterator &fi)
copy constructor copies the iterator, increases ref.count
~QgsFeatureIterator ()
destructor deletes the iterator if it has no more references
QgsFeatureIterator & operator= (const QgsFeatureIterator &other)
bool nextFeature (QgsFeature &f)
bool rewind ()
bool close ()
bool isClosed () const
find out whether the iterator is still valid or closed already
Protected Attributes
QgsAbstractFeatureIterator * mIter
Friends
bool operator== (const QgsFeatureIterator &fi1, const QgsFeatureIterator &fi2)
bool operator!= (const QgsFeatureIterator &fi1, const QgsFeatureIterator &fi2)
Detailed Description
Wrapper for iterator of features from vector data provider or vector layer.
Definition at line 139 of file qgsfeatureiterator.h.
Constructor & Destructor Documentation
QgsFeatureIterator::QgsFeatureIterator () inline
construct invalid iterator
Definition at line 169 of file qgsfeatureiterator.h.
QgsFeatureIterator::QgsFeatureIterator (QgsAbstractFeatureIterator * iter) inline
construct a valid iterator
Definition at line 174 of file qgsfeatureiterator.h.
References QgsAbstractFeatureIterator::ref().
QgsFeatureIterator::QgsFeatureIterator (const QgsFeatureIterator & fi) inline
copy constructor copies the iterator, increases ref.count
Definition at line 181 of file qgsfeatureiterator.h.
References mIter, and QgsAbstractFeatureIterator::ref().
QgsFeatureIterator::~QgsFeatureIterator () inline
destructor deletes the iterator if it has no more references
Definition at line 188 of file qgsfeatureiterator.h.
References QgsAbstractFeatureIterator::deref(), and mIter.
Member Function Documentation
bool QgsFeatureIterator::close () inline
Definition at line 204 of file qgsfeatureiterator.h.
References QgsAbstractFeatureIterator::close(), and mIter.
Referenced by QgsVectorLayerFeatureIterator::close(), QgsCachedFeatureWriterIterator::close(), QgsVectorLayerFeatureIterator::fetchFeature(), QgsAttributeTableFilterModel::generateListOfVisibleFeatures(), QgsExpressionSelectionDialog::on_mActionAddToSelection_triggered(), QgsExpressionSelectionDialog::on_mActionRemoveFromSelection_triggered(), QgsExpressionSelectionDialog::on_mActionSelect_triggered(), and QgsExpressionSelectionDialog::on_mActionSelectInstersect_triggered().
bool QgsFeatureIterator::isClosed () const inline
find out whether the iterator is still valid or closed already
Definition at line 209 of file qgsfeatureiterator.h.
References QgsAbstractFeatureIterator::mClosed, and mIter.
Referenced by QgsVectorLayerFeatureIterator::fetchFeature().
bool QgsFeatureIterator::nextFeature (QgsFeature & f) inline
Definition at line 194 of file qgsfeatureiterator.h.
References mIter, and QgsAbstractFeatureIterator::nextFeature().
Referenced by QgsVectorLayerFeatureIterator::FetchJoinInfo::addJoinedAttributesDirect(), QgsVectorLayerEditUtils::addPart(), QgsVectorLayerEditUtils::addRing(), QgsVectorLayer::allFeatureIds(), QgsOfflineEditing::applyFeaturesAdded(), QgsGeometry::avoidIntersections(), QgsVectorLayer::boundingBoxOfSelected(), QgsGeometryAnalyzer::buffer(), QgsInterpolator::cacheBaseData(), QgsVectorLayerJoinBuffer::cacheJoinLayer(), QgsZonalStatistics::calculateStatistics(), QgsGeometryAnalyzer::centroids(), QgsGeometryAnalyzer::convexHull(), QgsOfflineEditing::copyVectorLayer(), QgsSearchQueryBuilder::countRecords(), QgsVectorLayer::countSymbolFeatures(), QgsFormAnnotationItem::createDesignerWidget(), QgsAttributeTypeLoadDialog::createPreview(), QgsPointSample::createRandomPoints(), QgsGraduatedSymbolRendererV2::createRenderer(), QgsTransectSample::createSample(), QgsVectorLayerEditUtils::deleteVertex(), QgsGeometryAnalyzer::dissolve(), QgsVectorLayer::drawLabels(), QgsVectorLayerRenderer::drawRendererV2(), QgsVectorLayerRenderer::drawRendererV2Levels(), QgsGeometryAnalyzer::eventLayer(), QgsVectorFileWriter::exportFeaturesSymbolLevels(), QgsVectorLayer::extent(), QgsVectorLayerCache::featureAtId(), QgsMapTip::fetchFeature(), QgsVectorLayerFeatureIterator::fetchFeature(), QgsCachedFeatureWriterIterator::fetchFeature(), QgsVectorLayerFeatureIterator::fetchNextChangedAttributeFeature(), QgsVectorDataProvider::fillMinMaxCache(), QgsTransectSample::findBaselineGeometry(), QgsAttributeTableFilterModel::generateListOfVisibleFeatures(), QgsComposerAttributeTable::getFeatureAttributes(), QgsSearchQueryBuilder::getFieldValues(), QgsMapToolIdentify::identifyVectorLayer(), QgsVectorLayerImport::importLayer(), QgsTINInterpolator::initialize(), QgsVectorLayerEditUtils::insertVertex(), QgsOverlayAnalyzer::intersectFeature(), QgsOverlayAnalyzer::intersection(), QgsVectorLayer::invertSelectionInRectangle(), QgsAttributeTypeLoadDialog::loadDataToValueMap(), QgsAttributeTableModel::loadLayer(), QgsVectorLayer::maximumValue(), QgsVectorLayer::minimumValue(), QgsVectorLayerEditUtils::moveVertex(), QgsVectorLayerFeatureIterator::nextFeatureFid(), QgsExpressionSelectionDialog::on_mActionAddToSelection_triggered(), QgsExpressionSelectionDialog::on_mActionRemoveFromSelection_triggered(), QgsExpressionSelectionDialog::on_mActionSelect_triggered(), QgsExpressionSelectionDialog::on_mActionSelectInstersect_triggered(), QgsExpressionBuilderWidget::on_txtExpressionString_textChanged(), QgsAttributeTableModel::prefetchColumnData(), QgsAtlasComposition::prepareForFeature(), QgsVectorLayerRenderer::prepareLabeling(), QgsVectorLayer::removePolygonIntersections(), QgsVectorLayer::select(), QgsAtlasComposition::setCoverageLayer(), QgsGeometryAnalyzer::simplify(), QgsVectorLayer::snapWithContext(), QgsVectorLayerEditUtils::splitFeatures(), QgsVectorLayerEditUtils::splitParts(), QgsVectorLayerEditUtils::translateFeature(), QgsVectorLayerUndoCommandChangeAttribute::undo(), QgsVectorDataProvider::uniqueValues(), QgsVectorLayer::uniqueValues(), QgsAtlasComposition::updateFeatures(), QgsOfflineEditing::updateFidLookup(), QgsVectorLayerFeatureIterator::useChangedAttributeFeature(), and QgsVectorFileWriter::writeAsVectorFormat().
QgsFeatureIterator & QgsFeatureIterator::operator= (const QgsFeatureIterator & other)
Definition at line 143 of file qgsfeatureiterator.cpp.
References QgsAbstractFeatureIterator::deref(), mIter, and QgsAbstractFeatureIterator::ref().
bool QgsFeatureIterator::rewind () inline
Definition at line 199 of file qgsfeatureiterator.h.
References mIter, and QgsAbstractFeatureIterator::rewind().
Referenced by QgsVectorLayerFeatureIterator::rewind(), and QgsCachedFeatureWriterIterator::rewind().
Friends And Related Function Documentation
bool operator!= (const QgsFeatureIterator & fi1, const QgsFeatureIterator & fi2) friend
Definition at line 219 of file qgsfeatureiterator.h.
bool operator== (const QgsFeatureIterator & fi1, const QgsFeatureIterator & fi2) friend
Definition at line 214 of file qgsfeatureiterator.h.
Member Data Documentation
QgsAbstractFeatureIterator* QgsFeatureIterator::mIter protected
Definition at line 164 of file qgsfeatureiterator.h.
Referenced by close(), isClosed(), nextFeature(), operator=(), operator==(), QgsFeatureIterator(), rewind(), and ~QgsFeatureIterator().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsfeatureiterator.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsfeatureiterator.cpp