QGIS API Documentation: QgsExpressionItem Class Reference
QgsExpressionItem Class Reference
An expression item that can be used in the QgsExpressionBuilderWidget tree.
#include <qgsexpressionbuilderwidget.h>
Public Types
enum ItemType { Header, Field, ExpressionNode }
Public Member Functions
QgsExpressionItem (QString label, QString expressionText, QString helpText, QgsExpressionItem::ItemType itemType=ExpressionNode)
QgsExpressionItem (QString label, QString expressionText, QgsExpressionItem::ItemType itemType=ExpressionNode)
QString getExpressionText ()
QString getHelpText ()
Get the help text that is associated with this expression item.
void setHelpText (QString helpText)
Set the help text for the current item.
QgsExpressionItem::ItemType getItemType ()
Get the type of expression item eg header, field, ExpressionNode.
Private Attributes
QString mExpressionText
QString mHelpText
QgsExpressionItem::ItemType mType
Detailed Description
An expression item that can be used in the QgsExpressionBuilderWidget tree.
Definition at line 49 of file qgsexpressionbuilderwidget.h.
Member Enumeration Documentation
enum QgsExpressionItem::ItemType
Enumerator
Header
Field
ExpressionNode
Definition at line 52 of file qgsexpressionbuilderwidget.h.
Constructor & Destructor Documentation
QgsExpressionItem::QgsExpressionItem (QString label, QString expressionText, QString helpText, QgsExpressionItem::ItemType itemType = ExpressionNode) inline
Definition at line 59 of file qgsexpressionbuilderwidget.h.
References mExpressionText, mHelpText, and mType.
QgsExpressionItem::QgsExpressionItem (QString label, QString expressionText, QgsExpressionItem::ItemType itemType = ExpressionNode) inline
Definition at line 70 of file qgsexpressionbuilderwidget.h.
References mExpressionText, and mType.
Member Function Documentation
QString QgsExpressionItem::getExpressionText () inline
Definition at line 79 of file qgsexpressionbuilderwidget.h.
References mExpressionText.
Referenced by QgsExpressionBuilderWidget::on_expressionTree_doubleClicked().
QString QgsExpressionItem::getHelpText () inline
Get the help text that is associated with this expression item.
Returns
The help text.
Definition at line 85 of file qgsexpressionbuilderwidget.h.
References mHelpText.
Referenced by QgsExpressionBuilderWidget::loadFunctionHelp().
QgsExpressionItem::ItemType QgsExpressionItem::getItemType () inline
Get the type of expression item eg header, field, ExpressionNode.
Returns
The QgsExpressionItem::ItemType
Definition at line 96 of file qgsexpressionbuilderwidget.h.
References mType.
Referenced by QgsExpressionBuilderWidget::currentChanged(), QgsExpressionBuilderWidget::loadFunctionHelp(), QgsExpressionBuilderWidget::on_expressionTree_doubleClicked(), and QgsExpressionBuilderWidget::showContextMenu().
void QgsExpressionItem::setHelpText (QString helpText) inline
Set the help text for the current item.
Note
The help text can be set as a html string.
Definition at line 90 of file qgsexpressionbuilderwidget.h.
References mHelpText.
Member Data Documentation
QString QgsExpressionItem::mExpressionText private
Definition at line 99 of file qgsexpressionbuilderwidget.h.
Referenced by getExpressionText(), and QgsExpressionItem().
QString QgsExpressionItem::mHelpText private
Definition at line 100 of file qgsexpressionbuilderwidget.h.
Referenced by getHelpText(), QgsExpressionItem(), and setHelpText().
QgsExpressionItem::ItemType QgsExpressionItem::mType private
Definition at line 101 of file qgsexpressionbuilderwidget.h.
Referenced by getItemType(), and QgsExpressionItem().
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsexpressionbuilderwidget.h