QGIS API Documentation: QgsDiagramRendererV2 Class Reference
QgsDiagramRendererV2 Class Reference abstract
Returns diagram settings for a feature.
#include <qgsdiagramrendererv2.h>
Public Member Functions
QgsDiagramRendererV2 ()
virtual ~QgsDiagramRendererV2 ()
virtual QgsDiagramRendererV2 * clone () const =0
Returns new instance that is equivalent to this one.
virtual QSizeF sizeMapUnits (const QgsFeature &feature, const QgsRenderContext &c)
Returns size of the diagram for a feature in map units.
virtual QString rendererName () const =0
virtual QList< QString > diagramAttributes () const =0
Returns attribute indices needed for diagram rendering.
void renderDiagram (const QgsFeature &feature, QgsRenderContext &c, const QPointF &pos)
void setDiagram (QgsDiagram *d)
QgsDiagram * diagram () const
virtual QList< QgsDiagramSettings > diagramSettings () const =0
Returns list with all diagram settings in the renderer.
virtual void readXML (const QDomElement &elem, const QgsVectorLayer *layer)=0
virtual void writeXML (QDomElement &layerElem, QDomDocument &doc, const QgsVectorLayer *layer) const =0
Protected Member Functions
QgsDiagramRendererV2 (const QgsDiagramRendererV2 &other)
virtual bool diagramSettings (const QgsFeature &feature, const QgsRenderContext &c, QgsDiagramSettings &s)=0
Returns diagram settings for a feature (or false if the diagram for the feature is not to be rendered).
virtual QSizeF diagramSize (const QgsFeature &features, const QgsRenderContext &c)=0
Returns size of the diagram (in painter units) or an invalid size in case of error.
void convertSizeToMapUnits (QSizeF &size, const QgsRenderContext &context) const
Converts size from mm to map units.
void _readXML (const QDomElement &elem, const QgsVectorLayer *layer)
void _writeXML (QDomElement &rendererElem, QDomDocument &doc, const QgsVectorLayer *layer) const
Static Protected Member Functions
static int dpiPaintDevice (const QPainter *)
Returns the paint device dpi (or -1 in case of error.
Protected Attributes
QgsDiagram * mDiagram
Reference to the object that does the real diagram rendering.
Detailed Description
Returns diagram settings for a feature.
Definition at line 155 of file qgsdiagramrendererv2.h.
Constructor & Destructor Documentation
QgsDiagramRendererV2::QgsDiagramRendererV2 ()
Definition at line 272 of file qgsdiagramrendererv2.cpp.
QgsDiagramRendererV2::~QgsDiagramRendererV2 () virtual
Definition at line 277 of file qgsdiagramrendererv2.cpp.
References mDiagram.
QgsDiagramRendererV2::QgsDiagramRendererV2 (const QgsDiagramRendererV2 & other) protected
Definition at line 288 of file qgsdiagramrendererv2.cpp.
Member Function Documentation
void QgsDiagramRendererV2::_readXML (const QDomElement & elem, const QgsVectorLayer * layer) protected
Definition at line 350 of file qgsdiagramrendererv2.cpp.
References mDiagram.
Referenced by QgsSingleCategoryDiagramRenderer::readXML(), and QgsLinearlyInterpolatedDiagramRenderer::readXML().
void QgsDiagramRendererV2::_writeXML (QDomElement & rendererElem, QDomDocument & doc, const QgsVectorLayer * layer) const protected
Definition at line 374 of file qgsdiagramrendererv2.cpp.
References mDiagram.
Referenced by QgsSingleCategoryDiagramRenderer::writeXML(), and QgsLinearlyInterpolatedDiagramRenderer::writeXML().
virtual QgsDiagramRendererV2* QgsDiagramRendererV2::clone () const pure virtual
Returns new instance that is equivalent to this one.
Note
added in 2.4
Implemented in QgsLinearlyInterpolatedDiagramRenderer, and QgsSingleCategoryDiagramRenderer.
Referenced by QgsPalLabeling::addDiagramLayer().
void QgsDiagramRendererV2::convertSizeToMapUnits (QSizeF & size, const QgsRenderContext & context) const protected
Converts size from mm to map units.
Definition at line 325 of file qgsdiagramrendererv2.cpp.
References QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), and QgsRenderContext::scaleFactor().
Referenced by sizeMapUnits().
QgsDiagram* QgsDiagramRendererV2::diagram () const inline
Definition at line 177 of file qgsdiagramrendererv2.h.
Referenced by QgsVectorLayerRenderer::prepareDiagrams().
virtual QList<QString> QgsDiagramRendererV2::diagramAttributes () const pure virtual
Returns attribute indices needed for diagram rendering.
Implemented in QgsLinearlyInterpolatedDiagramRenderer, and QgsSingleCategoryDiagramRenderer.
Referenced by QgsVectorLayerRenderer::prepareDiagrams().
virtual QList<QgsDiagramSettings> QgsDiagramRendererV2::diagramSettings () const pure virtual
Returns list with all diagram settings in the renderer.
Implemented in QgsLinearlyInterpolatedDiagramRenderer, and QgsSingleCategoryDiagramRenderer.
Referenced by renderDiagram(), and sizeMapUnits().
virtual bool QgsDiagramRendererV2::diagramSettings (const QgsFeature & feature, const QgsRenderContext & c, QgsDiagramSettings & s) protected pure virtual
Returns diagram settings for a feature (or false if the diagram for the feature is not to be rendered).
Used internally within renderDiagram()
Parameters
feature the feature
c render context
s out: diagram settings for the feature
Implemented in QgsLinearlyInterpolatedDiagramRenderer, and QgsSingleCategoryDiagramRenderer.
virtual QSizeF QgsDiagramRendererV2::diagramSize (const QgsFeature & features, const QgsRenderContext & c) protected pure virtual
Returns size of the diagram (in painter units) or an invalid size in case of error.
Implemented in QgsLinearlyInterpolatedDiagramRenderer, and QgsSingleCategoryDiagramRenderer.
Referenced by sizeMapUnits().
int QgsDiagramRendererV2::dpiPaintDevice (const QPainter * painter) static protected
Returns the paint device dpi (or -1 in case of error.
Definition at line 337 of file qgsdiagramrendererv2.cpp.
virtual void QgsDiagramRendererV2::readXML (const QDomElement & elem, const QgsVectorLayer * layer) pure virtual
Implemented in QgsLinearlyInterpolatedDiagramRenderer, and QgsSingleCategoryDiagramRenderer.
Referenced by QgsVectorLayer::readSymbology().
void QgsDiagramRendererV2::renderDiagram (const QgsFeature & feature, QgsRenderContext & c, const QPointF & pos)
Definition at line 293 of file qgsdiagramrendererv2.cpp.
References diagramSettings(), and mDiagram.
virtual QString QgsDiagramRendererV2::rendererName () const pure virtual
Implemented in QgsLinearlyInterpolatedDiagramRenderer, and QgsSingleCategoryDiagramRenderer.
void QgsDiagramRendererV2::setDiagram (QgsDiagram * d)
Definition at line 282 of file qgsdiagramrendererv2.cpp.
References mDiagram.
QSizeF QgsDiagramRendererV2::sizeMapUnits (const QgsFeature & feature, const QgsRenderContext & c) virtual
Returns size of the diagram for a feature in map units.
Returns an invalid QSizeF in case of error
Definition at line 309 of file qgsdiagramrendererv2.cpp.
References convertSizeToMapUnits(), diagramSettings(), diagramSize(), QgsDiagramSettings::MM, size, and QgsDiagramSettings::sizeType.
Referenced by QgsPalLabeling::registerDiagramFeature().
virtual void QgsDiagramRendererV2::writeXML (QDomElement & layerElem, QDomDocument & doc, const QgsVectorLayer * layer) const pure virtual
Implemented in QgsLinearlyInterpolatedDiagramRenderer, and QgsSingleCategoryDiagramRenderer.
Referenced by QgsVectorLayer::writeSymbology().
Member Data Documentation
QgsDiagram* QgsDiagramRendererV2::mDiagram protected
Reference to the object that does the real diagram rendering.
Definition at line 209 of file qgsdiagramrendererv2.h.
Referenced by _readXML(), _writeXML(), QgsSingleCategoryDiagramRenderer::diagramSize(), QgsLinearlyInterpolatedDiagramRenderer::diagramSize(), renderDiagram(), setDiagram(), and ~QgsDiagramRendererV2().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdiagramrendererv2.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsdiagramrendererv2.cpp