QGIS API Documentation: QgsComposerTextTable Class Reference
QgsComposerTextTable Class Reference
A text table item that reads text from string lists.
#include <qgscomposertexttable.h>
Public Member Functions
QgsComposerTextTable (QgsComposition *c)
~QgsComposerTextTable ()
virtual int type () const
return correct graphics item type.
void setHeaderLabels (const QStringList &labels)
Sets the text to use for the header row for the table.
void addRow (const QStringList &row)
Adds a row to the table.
bool writeXML (QDomElement &elem, QDomDocument &doc) const
Writes properties specific to text tables.
bool readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads the properties specific to a text table from xml.
bool getFeatureAttributes (QList< QgsAttributeMap > &attributeMaps)
Queries the text table for text to show in the cells.
Public Member Functions inherited from QgsComposerTable
QgsComposerTable (QgsComposition *composition)
virtual ~QgsComposerTable ()
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint.
void setLineTextDistance (double d)
Sets the margin distance between cell borders and their contents.
double lineTextDistance () const
Returns the margin distance between cell borders and their contents.
void setHeaderFont (const QFont &f)
Sets the font used to draw header text in the table.
QFont headerFont () const
Returns the font used to draw header text in the table.
void setHeaderHAlignment (const HeaderHAlignment alignment)
Sets the horizontal alignment for table headers.
HeaderHAlignment headerHAlignment () const
Returns the horizontal alignment for table headers.
void setContentFont (const QFont &f)
Sets the font used to draw text in table body cells.
QFont contentFont () const
Returns the font used to draw text in table body cells.
void setShowGrid (bool show)
Sets whether grid lines should be drawn in the table.
bool showGrid () const
Returns whether grid lines are drawn in the table.
void setGridStrokeWidth (double w)
Sets the width for grid lines in the table.
double gridStrokeWidth () const
Returns the width of grid lines in the table.
void setGridColor (const QColor &c)
Sets color used for grid lines in the table.
QColor gridColor () const
Returns the color used for grid lines in the table.
virtual QMap< int, QString > headerLabels () const
Returns the text used in the column headers for the table.
QList< QgsComposerTableColumn * > * columns ()
Returns a pointer to the list of QgsComposerTableColumns shown in the table.
void setColumns (QList< QgsComposerTableColumn * > columns)
Replaces the columns in the table with a specified list of QgsComposerTableColumns.
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected () const
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
int page () const
Gets the page the item is currently on.
QPointF pagePos () const
Returns the item's position relative to its current page.
void updatePagePos (double newPageWidth, double newPageHeight)
Moves the item so that it retains its relative position on the page when the paper size changes.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft, int page=-1)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft, bool posIncludesFrame=false, int page=-1)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
virtual void setSceneRect (const QRectF &rectangle)
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
virtual void setFrameOutlineWidth (double outlineWidth)
Sets frame outline width.
double frameOutlineWidth () const
Returns the frame's outline width.
Qt::PenJoinStyle frameJoinStyle () const
Returns the join style used for drawing the item's frame.
void setFrameJoinStyle (Qt::PenJoinStyle style)
Sets join style used when drawing the item's frame.
virtual double estimatedFrameBleed () const
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
virtual QRectF rectWithFrame () const
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop, int flags=Qt::TextWordWrap) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font descent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightMillimeters (const QFont &font) const
Returns the font height in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
double itemRotation () const
Returns the rotation for the composer item.
Q_DECL_DEPRECATED double rotation () const
Returns the rotation for the composer item.
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
virtual int numberExportLayers () const
Get the number of layers that this item requires for exporting as layers.
virtual void setCurrentExportLayer (int layerIdx=-1)
Sets the current layer to draw for exporting.
Private Attributes
QList< QStringList > mRowText
One stringlist per row.
Additional Inherited Members
Public Types inherited from QgsComposerTable
enum HeaderHAlignment { FollowColumn, HeaderLeft, HeaderCenter, HeaderRight }
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Public Slots inherited from QgsComposerTable
virtual void refreshAttributes ()
Refreshes the attributes shown in the table by querying the vector layer for new data.
virtual void adjustFrameToSize ()
Adapts the size of the frame to match the content.
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
Sets the item rotation.
virtual void setItemRotation (double r, bool adjustPosition=false)
Sets the item rotation.
void repaint ()
Signals inherited from QgsComposerItem
void itemRotationChanged (double newRotation)
Is emitted on item rotation change.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
void frameChanged ()
Emitted if the item's frame style changes.
Protected Member Functions inherited from QgsComposerTable
virtual bool calculateMaxColumnWidths (QMap< int, double > &maxWidthMap, const QList< QgsAttributeMap > &attributeMaps) const
Calculates the maximum width of text shown in columns.
void adaptItemFrame (const QMap< int, double > &maxWidthMap, const QList< QgsAttributeMap > &attributeMaps)
Adapts the size of the item frame to match the table's content.
void drawHorizontalGridLines (QPainter *p, int nAttributes)
Draws the horizontal grid lines for the table.
void drawVerticalGridLines (QPainter *p, const QMap< int, double > &maxWidthMap)
Draws the vertical grid lines for the table.
bool tableWriteXML (QDomElement &itemElem, QDomDocument &doc) const
Writes common table properties to xml for storage.
bool tableReadXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads the table's common properties from xml.
Protected Member Functions inherited from QgsComposerItem
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height, double rotation) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
Q_DECL_DEPRECATED bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
QRectF largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height, double rotation) const
Calculates corner point after rotation and scaling.
Q_DECL_DEPRECATED bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height, double rotation)
Calculates width / height of the bounding box of a rotated rectangle.
Q_DECL_DEPRECATED void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Protected Attributes inherited from QgsComposerTable
double mLineTextDistance
Distance between table lines and text.
QFont mHeaderFont
QFont mContentFont
HeaderHAlignment mHeaderHAlignment
bool mShowGrid
double mGridStrokeWidth
QColor mGridColor
QList< QgsAttributeMap > mAttributeMaps
QMap< int, double > mMaxColumnWidthMap
QList< QgsComposerTableColumn * > mColumns
Protected Attributes inherited from QgsComposerItem
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
Qt::PenJoinStyle mFrameJoinStyle
Frame join style.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mItemRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
int mCurrentExportLayer
The layer that needs to be exported.
Detailed Description
A text table item that reads text from string lists.
Definition at line 24 of file qgscomposertexttable.h.
Constructor & Destructor Documentation
QgsComposerTextTable::QgsComposerTextTable (QgsComposition * c)
Definition at line 21 of file qgscomposertexttable.cpp.
QgsComposerTextTable::~QgsComposerTextTable ()
Definition at line 26 of file qgscomposertexttable.cpp.
Member Function Documentation
void QgsComposerTextTable::addRow (const QStringList & row) inline
Adds a row to the table.
Parameters
row list of strings to use for each cell's value in the newly added row
Note
If row is shorter than the number of columns in the table than blank cells will be inserted at the end of the row. If row contains more strings then the number of columns in the table then these extra strings will be ignored.
Definition at line 45 of file qgscomposertexttable.h.
bool QgsComposerTextTable::getFeatureAttributes (QList< QgsAttributeMap > & attributeMaps) virtual
Queries the text table for text to show in the cells.
Parameters
attributeMaps list of QgsAttributeMaps where the cell text will be stored
Returns
true if attribute values were successfully set from table's text
Note
not available in python bindings
Reimplemented from QgsComposerTable.
Definition at line 68 of file qgscomposertexttable.cpp.
References mRowText.
bool QgsComposerTextTable::readXML (const QDomElement & itemElem, const QDomDocument & doc) virtual
Reads the properties specific to a text table from xml.
Parameters
itemElem a QDomElement holding the text table's desired properties.
doc QDomDocument for the source xml.
See also
writeXML
Implements QgsComposerTable.
Definition at line 62 of file qgscomposertexttable.cpp.
References QgsComposerTable::tableReadXML().
void QgsComposerTextTable::setHeaderLabels (const QStringList & labels)
Sets the text to use for the header row for the table.
Parameters
labels list of strings to use for each column's header row
See also
headerLabels
Definition at line 31 of file qgscomposertexttable.cpp.
References QgsComposerTable::mColumns, and QgsComposerTableColumn::setHeading().
virtual int QgsComposerTextTable::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerTable.
Definition at line 31 of file qgscomposertexttable.h.
References QgsComposerItem::ComposerTextTable.
bool QgsComposerTextTable::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
Writes properties specific to text tables.
Parameters
elem an existing QDomElement in which to store the text table's properties.
doc QDomDocument for the destination xml.
See also
readXML
Implements QgsComposerTable.
Definition at line 53 of file qgscomposertexttable.cpp.
References QgsComposerItem::_writeXML().
Member Data Documentation
QList< QStringList > QgsComposerTextTable::mRowText private
One stringlist per row.
Definition at line 70 of file qgscomposertexttable.h.
Referenced by getFeatureAttributes().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposertexttable.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposertexttable.cpp