QGIS API Documentation: QgsAttributeEditorContext Class Reference
QgsAttributeEditorContext Class Reference
This class contains context information for attribute editor widgets.
#include <qgsattributeeditorcontext.h>
Public Member Functions
QgsAttributeEditorContext ()
QWidget * proxyWidget (QgsVectorLayer *vl, int fieldIdx)
void addProxyWidgets (QgsVectorLayer *vl, QMap< int, QWidget * > proxyWidgets)
void addProxyWidget (QgsVectorLayer *vl, int idx, QWidget *widget)
void setDistanceArea (const QgsDistanceArea &distanceArea)
const QgsDistanceArea & distanceArea ()
void setVectorLayerTools (QgsVectorLayerTools *vlTools)
QgsVectorLayerTools * vectorLayerTools ()
void adjustForLayer (QgsVectorLayer *layer)
When copying the context for another layer, call this.
Private Attributes
QgsVectorLayerTools * mVectorLayerTools
QMap< QgsVectorLayer *, QMap
< int, QWidget * > > mProxyWidgets
vectorlayer => (fieldIdx, proxyWidget)
QgsDistanceArea mDistanceArea
Detailed Description
This class contains context information for attribute editor widgets.
It will be passed to embedded widgets whenever this occurs (e.g. when showing an embedded form due to relations)
Definition at line 33 of file qgsattributeeditorcontext.h.
Constructor & Destructor Documentation
QgsAttributeEditorContext::QgsAttributeEditorContext ()
Definition at line 18 of file qgsattributeeditorcontext.cpp.
Member Function Documentation
void QgsAttributeEditorContext::addProxyWidget (QgsVectorLayer * vl, int idx, QWidget * widget)
void QgsAttributeEditorContext::addProxyWidgets (QgsVectorLayer * vl, QMap< int, QWidget * > proxyWidgets)
Note
not available in python bindings
void QgsAttributeEditorContext::adjustForLayer (QgsVectorLayer * layer)
When copying the context for another layer, call this.
Will adjast the distance area for this layer
Parameters
layer The layer to adjust for.
Definition at line 24 of file qgsattributeeditorcontext.cpp.
References QgsMapLayer::crs(), mDistanceArea, and QgsDistanceArea::setSourceCrs().
const QgsDistanceArea& QgsAttributeEditorContext::distanceArea () inline
Definition at line 44 of file qgsattributeeditorcontext.h.
QWidget* QgsAttributeEditorContext::proxyWidget (QgsVectorLayer * vl, int fieldIdx)
void QgsAttributeEditorContext::setDistanceArea (const QgsDistanceArea & distanceArea) inline
Definition at line 43 of file qgsattributeeditorcontext.h.
Referenced by QgsAttributeDialog::QgsAttributeDialog().
void QgsAttributeEditorContext::setVectorLayerTools (QgsVectorLayerTools * vlTools) inline
Definition at line 46 of file qgsattributeeditorcontext.h.
QgsVectorLayerTools* QgsAttributeEditorContext::vectorLayerTools () inline
Definition at line 47 of file qgsattributeeditorcontext.h.
Referenced by QgsRelationEditorWidget::on_mAddFeatureButton_clicked(), and QgsRelationEditorWidget::on_mToggleEditingButton_toggled().
Member Data Documentation
QgsDistanceArea QgsAttributeEditorContext::mDistanceArea private
Definition at line 63 of file qgsattributeeditorcontext.h.
Referenced by adjustForLayer().
QMap<QgsVectorLayer*, QMap<int, QWidget*> > QgsAttributeEditorContext::mProxyWidgets private
vectorlayer => (fieldIdx, proxyWidget)
Definition at line 61 of file qgsattributeeditorcontext.h.
QgsVectorLayerTools* QgsAttributeEditorContext::mVectorLayerTools private
Definition at line 58 of file qgsattributeeditorcontext.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsattributeeditorcontext.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsattributeeditorcontext.cpp