QGIS API Documentation: QgsGridFileWriter Class Reference
QgsGridFileWriter Class Reference
A class that does interpolation to a grid and writes the results to an ascii grid.
#include <qgsgridfilewriter.h>
Public Member Functions
QgsGridFileWriter (QgsInterpolator *i, QString outputPath, QgsRectangle extent, int nCols, int nRows, double cellSizeX, double cellSizeY)
~QgsGridFileWriter ()
int writeFile (bool showProgressDialog=false)
Writes the grid file.
Private Member Functions
QgsGridFileWriter ()
int writeHeader (QTextStream &outStream)
Private Attributes
QgsInterpolator * mInterpolator
QString mOutputFilePath
QgsRectangle mInterpolationExtent
int mNumColumns
int mNumRows
double mCellSizeX
double mCellSizeY
Detailed Description
A class that does interpolation to a grid and writes the results to an ascii grid.
Definition at line 29 of file qgsgridfilewriter.h.
Constructor & Destructor Documentation
QgsGridFileWriter::QgsGridFileWriter (QgsInterpolator * i, QString outputPath, QgsRectangle extent, int nCols, int nRows, double cellSizeX, double cellSizeY)
Definition at line 25 of file qgsgridfilewriter.cpp.
QgsGridFileWriter::~QgsGridFileWriter ()
Definition at line 37 of file qgsgridfilewriter.cpp.
QgsGridFileWriter::QgsGridFileWriter () private
Definition at line 32 of file qgsgridfilewriter.cpp.
Member Function Documentation
int QgsGridFileWriter::writeFile (bool showProgressDialog = false)
Writes the grid file.
Parameters
showProgressDialog shows a dialog with the possibility to cancel
Returns
0 in case of success
Definition at line 42 of file qgsgridfilewriter.cpp.
References QgsMapLayer::crs(), QgsInterpolator::interpolatePoint(), QgsInterpolator::layerData(), mCellSizeX, mCellSizeY, mInterpolationExtent, mInterpolator, mNumColumns, mNumRows, mOutputFilePath, QgsCoordinateReferenceSystem::toWkt(), tr, QgsInterpolator::LayerData::vectorLayer, writeHeader(), QgsRectangle::xMinimum(), and QgsRectangle::yMaximum().
int QgsGridFileWriter::writeHeader (QTextStream & outStream) private
Definition at line 122 of file qgsgridfilewriter.cpp.
References mCellSizeX, mCellSizeY, mInterpolationExtent, mNumColumns, mNumRows, QgsRectangle::xMinimum(), and QgsRectangle::yMinimum().
Referenced by writeFile().
Member Data Documentation
double QgsGridFileWriter::mCellSizeX private
Definition at line 52 of file qgsgridfilewriter.h.
Referenced by writeFile(), and writeHeader().
double QgsGridFileWriter::mCellSizeY private
Definition at line 53 of file qgsgridfilewriter.h.
Referenced by writeFile(), and writeHeader().
QgsRectangle QgsGridFileWriter::mInterpolationExtent private
Definition at line 48 of file qgsgridfilewriter.h.
Referenced by writeFile(), and writeHeader().
QgsInterpolator* QgsGridFileWriter::mInterpolator private
Definition at line 46 of file qgsgridfilewriter.h.
Referenced by writeFile().
int QgsGridFileWriter::mNumColumns private
Definition at line 49 of file qgsgridfilewriter.h.
Referenced by writeFile(), and writeHeader().
int QgsGridFileWriter::mNumRows private
Definition at line 50 of file qgsgridfilewriter.h.
Referenced by writeFile(), and writeHeader().
QString QgsGridFileWriter::mOutputFilePath private
Definition at line 47 of file qgsgridfilewriter.h.
Referenced by writeFile().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/analysis/interpolation/qgsgridfilewriter.h
/tmp/buildd/qgis-2.4.0+unstable1/src/analysis/interpolation/qgsgridfilewriter.cpp