QGIS API Documentation: QgsHtmlAnnotationItem Class Reference
QgsHtmlAnnotationItem Class Reference
An annotation item that embedds a designer form showing the feature attribute.
#include <qgshtmlannotationitem.h>
Public Member Functions
QgsHtmlAnnotationItem (QgsMapCanvas *canvas, QgsVectorLayer *vlayer=0, bool hasFeature=false, int feature=0)
~QgsHtmlAnnotationItem ()
void paint (QPainter *painter)
function to be implemented by derived classes
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
paint function called by map canvas
QSizeF minimumFrameSize () const
void setMapPosition (const QgsPoint &pos)
Reimplemented from QgsAnnotationItem.
void setHTMLPage (const QString &htmlFile)
QString htmlPage () const
void writeXML (QDomDocument &doc) const
void readXML (const QDomDocument &doc, const QDomElement &itemElem)
QgsVectorLayer * vectorLayer () const
Public Member Functions inherited from QgsAnnotationItem
QgsAnnotationItem (QgsMapCanvas *mapCanvas)
virtual ~QgsAnnotationItem ()
void updatePosition ()
called on changed extent or resize event to update position of the item
QRectF boundingRect () const
default implementation for canvas items
QgsAnnotationItem::MouseMoveAction moveActionForPosition (const QPointF &pos) const
Returns the mouse move behaviour for a given position.
Qt::CursorShape cursorShapeForAction (MouseMoveAction moveAction) const
Returns suitable cursor shape for mouse move action.
void setMapPositionFixed (bool fixed)
bool mapPositionFixed () const
QgsPoint mapPosition () const
void setFrameSize (const QSizeF &size)
QSizeF frameSize () const
void setOffsetFromReferencePoint (const QPointF &offset)
QPointF offsetFromReferencePoint () const
void setMarkerSymbol (QgsMarkerSymbolV2 *symbol)
Set symbol that is drawn on map position.
const QgsMarkerSymbolV2 * markerSymbol () const
void setFrameBorderWidth (double w)
double frameBorderWidth () const
void setFrameColor (const QColor &c)
QColor frameColor () const
void setFrameBackgroundColor (const QColor &c)
QColor frameBackgroundColor () const
void _writeXML (QDomDocument &doc, QDomElement &itemElem) const
void _readXML (const QDomDocument &doc, const QDomElement &annotationElem)
Public Member Functions inherited from QgsMapCanvasItem
Q_DECL_DEPRECATED void setPanningOffset (const QPoint &point)
sets current offset, to be called from QgsMapCanvas
QgsRectangle rect () const
returns canvas item rectangle
void setRect (const QgsRectangle &r)
sets canvas item rectangle
QgsPoint toMapCoordinates (const QPoint &point)
transformation from screen coordinates to map coordinates
QPointF toCanvasCoordinates (const QgsPoint &point)
transformation from map coordinates to screen coordinates
Private Slots
void setFeatureForMapPosition ()
Sets a feature for the current map position and updates the dialog.
void updateVisibility ()
Sets visibility status based on mVectorLayer visibility.
void javascript ()
Private Member Functions
QString replaceText (QString displayText, QgsVectorLayer *layer, QgsFeature &feat)
Private Attributes
QGraphicsProxyWidget * mWidgetContainer
QWebView * mWebView
QgsVectorLayer * mVectorLayer
Associated vectorlayer (or 0 if attributes are not supposed to be replaced)
bool mHasAssociatedFeature
True if the item is related to a vector feature.
QgsFeatureId mFeatureId
Associated feature.
QgsFeature mFeature
QString mHtmlFile
QString mHtmlSource
Additional Inherited Members
Public Types inherited from QgsAnnotationItem
enum MouseMoveAction {
NoAction, MoveMapPosition, MoveFramePosition, ResizeFrameUp,
ResizeFrameDown, ResizeFrameLeft, ResizeFrameRight, ResizeFrameLeftUp,
ResizeFrameRightUp, ResizeFrameLeftDown, ResizeFrameRightDown
}
Protected Member Functions inherited from QgsAnnotationItem
void updateBoundingRect ()
void updateBalloon ()
Check where to attach the balloon connection between frame and map point.
void drawFrame (QPainter *p)
void drawMarkerSymbol (QPainter *p)
void drawSelectionBoxes (QPainter *p)
QLineF segment (int index)
Returns frame width in painter units.
QPointF pointOnLineWithDistance (const QPointF &startPoint, const QPointF &directionPoint, double distance) const
Returns a point on the line from startPoint to directionPoint that is a certain distance away from the starting point.
double scaledSymbolSize () const
Returns the symbol size scaled in (mapcanvas) pixels.
Protected Member Functions inherited from QgsMapCanvasItem
QgsMapCanvasItem (QgsMapCanvas *mapCanvas)
protected constructor: cannot be constructed directly
virtual ~QgsMapCanvasItem ()
void updateCanvas ()
schedules map canvas for repaint
bool setRenderContextVariables (QPainter *p, QgsRenderContext &context) const
Sets render context parameters.
Protected Attributes inherited from QgsAnnotationItem
bool mMapPositionFixed
True: the item stays at the same map position, False: the item stays on same screen position.
QgsPoint mMapPosition
Map position (in case mMapPositionFixed is true)
QPointF mOffsetFromReferencePoint
Describes the shift of the item content box to the reference point.
QSizeF mFrameSize
Size of the frame (without balloon)
QRectF mBoundingRect
Bounding rect (including item frame and balloon)
QgsMarkerSymbolV2 * mMarkerSymbol
Point symbol that is to be drawn at the map reference location.
double mFrameBorderWidth
Width of the frame.
QColor mFrameColor
Frame / balloon color.
QColor mFrameBackgroundColor
int mBalloonSegment
Segment number where the connection to the map point is attached.
QPointF mBalloonSegmentPoint1
First segment point for drawing the connection (ccw direction)
QPointF mBalloonSegmentPoint2
Second segment point for drawing the balloon connection (ccw direction)
Protected Attributes inherited from QgsMapCanvasItem
QgsMapCanvas * mMapCanvas
pointer to map canvas
QgsRectangle mRect
canvas item rectangle (in map coordinates)
QPoint mPanningOffset
offset from normal position due current panning operation, used when converting map coordinates to move map canvas items
QSizeF mItemSize
cached size of the item (to return in boundingRect())
Detailed Description
An annotation item that embedds a designer form showing the feature attribute.
Definition at line 30 of file qgshtmlannotationitem.h.
Constructor & Destructor Documentation
QgsHtmlAnnotationItem::QgsHtmlAnnotationItem (QgsMapCanvas * canvas, QgsVectorLayer * vlayer = 0, bool hasFeature = false, int feature = 0)
Definition at line 39 of file qgshtmlannotationitem.cpp.
References QgsNetworkAccessManager::instance(), javascript(), QgsMapCanvasItem::mMapCanvas, mVectorLayer, mWebView, mWidgetContainer, setFeatureForMapPosition(), and updateVisibility().
QgsHtmlAnnotationItem::~QgsHtmlAnnotationItem ()
Definition at line 61 of file qgshtmlannotationitem.cpp.
References mWebView.
Member Function Documentation
QString QgsHtmlAnnotationItem::htmlPage () const inline
Definition at line 48 of file qgshtmlannotationitem.h.
Referenced by writeXML().
void QgsHtmlAnnotationItem::javascript () private slot
Definition at line 231 of file qgshtmlannotationitem.cpp.
References QgsMapCanvasItem::mMapCanvas, mVectorLayer, and mWebView.
Referenced by QgsHtmlAnnotationItem().
QSizeF QgsHtmlAnnotationItem::minimumFrameSize () const virtual
Reimplemented from QgsAnnotationItem.
Definition at line 125 of file qgshtmlannotationitem.cpp.
References QgsAnnotationItem::mFrameBorderWidth, and mWebView.
void QgsHtmlAnnotationItem::paint (QPainter * painter) virtual
function to be implemented by derived classes
Implements QgsMapCanvasItem.
Definition at line 91 of file qgshtmlannotationitem.cpp.
void QgsHtmlAnnotationItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) virtual
paint function called by map canvas
Reimplemented from QgsMapCanvasItem.
Definition at line 96 of file qgshtmlannotationitem.cpp.
References QgsAnnotationItem::drawFrame(), QgsAnnotationItem::drawMarkerSymbol(), QgsAnnotationItem::drawSelectionBoxes(), QgsAnnotationItem::mFrameBorderWidth, QgsAnnotationItem::mFrameSize, QgsAnnotationItem::mMapPositionFixed, QgsAnnotationItem::mOffsetFromReferencePoint, and mWidgetContainer.
void QgsHtmlAnnotationItem::readXML (const QDomDocument & doc, const QDomElement & itemElem) virtual
Implements QgsAnnotationItem.
Definition at line 159 of file qgshtmlannotationitem.cpp.
References QgsAnnotationItem::_readXML(), QgsMapLayerRegistry::instance(), QgsMapLayerRegistry::mapLayer(), mFeatureId, mHasAssociatedFeature, mHtmlFile, QgsMapCanvasItem::mMapCanvas, mVectorLayer, mWebView, setFeatureForMapPosition(), setHTMLPage(), and updateVisibility().
QString QgsHtmlAnnotationItem::replaceText (QString displayText, QgsVectorLayer * layer, QgsFeature & feat) private
void QgsHtmlAnnotationItem::setFeatureForMapPosition () private slot
Sets a feature for the current map position and updates the dialog.
Definition at line 188 of file qgshtmlannotationitem.cpp.
References QgsFeatureRequest::ExactIntersect, QgsVectorLayer::getFeatures(), QgsFeature::id(), mFeature, mFeatureId, mHasAssociatedFeature, mHtmlSource, QgsMapCanvasItem::mMapCanvas, QgsAnnotationItem::mMapPosition, mVectorLayer, mWebView, QgsFeatureRequest::NoGeometry, QgsExpression::replaceExpressionText(), QgsMapTool::searchRadiusMU(), vectorLayer(), QgsPoint::x(), and QgsPoint::y().
Referenced by QgsHtmlAnnotationItem(), readXML(), setHTMLPage(), and setMapPosition().
void QgsHtmlAnnotationItem::setHTMLPage (const QString & htmlFile)
Definition at line 66 of file qgshtmlannotationitem.cpp.
References file, mHtmlFile, mHtmlSource, and setFeatureForMapPosition().
Referenced by readXML().
void QgsHtmlAnnotationItem::setMapPosition (const QgsPoint & pos) virtual
Reimplemented from QgsAnnotationItem.
Reimplemented from QgsAnnotationItem.
Definition at line 85 of file qgshtmlannotationitem.cpp.
References setFeatureForMapPosition(), and QgsAnnotationItem::setMapPosition().
void QgsHtmlAnnotationItem::updateVisibility () private slot
Sets visibility status based on mVectorLayer visibility.
Definition at line 221 of file qgshtmlannotationitem.cpp.
References QgsMapCanvas::layers(), QgsMapCanvasItem::mMapCanvas, and mVectorLayer.
Referenced by QgsHtmlAnnotationItem(), and readXML().
QgsVectorLayer* QgsHtmlAnnotationItem::vectorLayer () const inline
Definition at line 53 of file qgshtmlannotationitem.h.
Referenced by setFeatureForMapPosition().
void QgsHtmlAnnotationItem::writeXML (QDomDocument & doc) const virtual
Implements QgsAnnotationItem.
Definition at line 138 of file qgshtmlannotationitem.cpp.
References QgsAnnotationItem::_writeXML(), htmlPage(), QgsMapLayer::id(), mFeatureId, mHasAssociatedFeature, and mVectorLayer.
Member Data Documentation
QgsFeature QgsHtmlAnnotationItem::mFeature private
Definition at line 72 of file qgshtmlannotationitem.h.
Referenced by setFeatureForMapPosition().
QgsFeatureId QgsHtmlAnnotationItem::mFeatureId private
Associated feature.
Definition at line 71 of file qgshtmlannotationitem.h.
Referenced by readXML(), setFeatureForMapPosition(), and writeXML().
bool QgsHtmlAnnotationItem::mHasAssociatedFeature private
True if the item is related to a vector feature.
Definition at line 69 of file qgshtmlannotationitem.h.
Referenced by readXML(), setFeatureForMapPosition(), and writeXML().
QString QgsHtmlAnnotationItem::mHtmlFile private
Definition at line 73 of file qgshtmlannotationitem.h.
Referenced by readXML(), and setHTMLPage().
QString QgsHtmlAnnotationItem::mHtmlSource private
Definition at line 74 of file qgshtmlannotationitem.h.
Referenced by setFeatureForMapPosition(), and setHTMLPage().
QgsVectorLayer* QgsHtmlAnnotationItem::mVectorLayer private
Associated vectorlayer (or 0 if attributes are not supposed to be replaced)
Definition at line 67 of file qgshtmlannotationitem.h.
Referenced by javascript(), QgsHtmlAnnotationItem(), readXML(), setFeatureForMapPosition(), updateVisibility(), and writeXML().
QWebView* QgsHtmlAnnotationItem::mWebView private
Definition at line 65 of file qgshtmlannotationitem.h.
Referenced by javascript(), minimumFrameSize(), QgsHtmlAnnotationItem(), readXML(), setFeatureForMapPosition(), and ~QgsHtmlAnnotationItem().
QGraphicsProxyWidget* QgsHtmlAnnotationItem::mWidgetContainer private
Definition at line 64 of file qgshtmlannotationitem.h.
Referenced by paint(), and QgsHtmlAnnotationItem().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgshtmlannotationitem.h
/tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgshtmlannotationitem.cpp