QGIS API Documentation: QgsExpression::Function Class Reference
QgsExpression::Function Class Reference abstract
A abstract base class for defining QgsExpression functions.
#include <qgsexpression.h>
Public Member Functions
Function (QString fnname, int params, QString group, QString helpText=QString(), bool usesGeometry=false)
QString name ()
The name of the function.
int params ()
The number of parameters this function takes.
bool usesgeometry ()
Does this function use a geometry object.
QString group ()
The group the function belongs to.
QString helptext ()
The help text for the function.
virtual QVariant func (const QVariantList &values, const QgsFeature *f, QgsExpression *parent)=0
bool operator== (const Function &other) const
Private Attributes
QString mName
int mParams
bool mUsesGeometry
QString mGroup
QString mHelpText
Detailed Description
A abstract base class for defining QgsExpression functions.
Definition at line 244 of file qgsexpression.h.
Constructor & Destructor Documentation
QgsExpression::Function::Function (QString fnname, int params, QString group, QString helpText = QString(), bool usesGeometry = false) inline
Definition at line 247 of file qgsexpression.h.
Member Function Documentation
virtual QVariant QgsExpression::Function::func (const QVariantList & values, const QgsFeature * f, QgsExpression * parent) pure virtual
Implemented in QgsExpression::StaticFunction.
Referenced by QgsExpression::NodeFunction::eval().
QString QgsExpression::Function::group () inline
The group the function belongs to.
Definition at line 256 of file qgsexpression.h.
Referenced by QgsExpressionBuilderWidget::QgsExpressionBuilderWidget().
QString QgsExpression::Function::helptext () inline
The help text for the function.
Definition at line 258 of file qgsexpression.h.
References QgsExpression::helptext().
Referenced by QgsExpressionBuilderWidget::QgsExpressionBuilderWidget().
QString QgsExpression::Function::name () inline
The name of the function.
Definition at line 250 of file qgsexpression.h.
Referenced by QgsExpression::NodeFunction::dump(), QgsExpression::NodeFunction::eval(), QgsOgcUtils::expressionFunctionToOgcFilter(), geometryFromConstExpr(), isGeometryColumn(), QgsOgcUtils::nodeFunctionFromOgcFilter(), and QgsExpressionBuilderWidget::QgsExpressionBuilderWidget().
bool QgsExpression::Function::operator== (const Function & other) const inline
Definition at line 262 of file qgsexpression.h.
References mName.
int QgsExpression::Function::params () inline
The number of parameters this function takes.
Definition at line 252 of file qgsexpression.h.
Referenced by QgsExpression::NodeFunction::dump(), QgsOgcUtils::expressionFunctionToOgcFilter(), and QgsExpressionBuilderWidget::QgsExpressionBuilderWidget().
bool QgsExpression::Function::usesgeometry () inline
Does this function use a geometry object.
Definition at line 254 of file qgsexpression.h.
Member Data Documentation
QString QgsExpression::Function::mGroup private
Definition at line 274 of file qgsexpression.h.
QString QgsExpression::Function::mHelpText private
Definition at line 275 of file qgsexpression.h.
QString QgsExpression::Function::mName private
Definition at line 271 of file qgsexpression.h.
Referenced by operator==().
int QgsExpression::Function::mParams private
Definition at line 272 of file qgsexpression.h.
bool QgsExpression::Function::mUsesGeometry private
Definition at line 273 of file qgsexpression.h.
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/qgsexpression.h