QGIS API Documentation: QgsComposerTableColumn Class Reference
QgsComposerTableColumn Class Reference
Stores properties of a column in a QgsComposerTable.
#include <qgscomposertablecolumn.h>
Public Member Functions
QgsComposerTableColumn ()
virtual ~QgsComposerTableColumn ()
virtual bool writeXML (QDomElement &columnElem, QDomDocument &doc) const
Writes the column's properties to xml for storage.
virtual bool readXML (const QDomElement &columnElem)
Reads the column's properties from xml.
QString heading () const
Returns the heading for a column, which is the value displayed in the columns header cell.
void setHeading (QString heading)
Sets the heading for a column, which is the value displayed in the columns header cell.
Qt::AlignmentFlag hAlignment () const
Returns the horizontal alignment for a column, which controls the alignment used for drawing column values within cells.
void setHAlignment (Qt::AlignmentFlag alignment)
Sets the horizontal alignment for a column, which controls the alignment used for drawing column values within cells.
QString attribute () const
Returns the attribute name or expression used for the column's values.
void setAttribute (QString attribute)
Sets the attribute name or expression used for the column's values.
Qt::SortOrder sortOrder () const
Returns the sort order for the column.
void setSortOrder (Qt::SortOrder sortOrder)
Sets the sort order for the column.
int sortByRank () const
Returns the sort rank for the column.
void setSortByRank (int sortByRank)
Sets the sort rank for the column.
QgsComposerTableColumn * clone ()
Creates a duplicate column which is a deep copy of this column.
Private Attributes
QColor mBackgroundColor
Qt::AlignmentFlag mHAlignment
QString mHeading
QString mAttribute
int mSortByRank
Qt::SortOrder mSortOrder
Detailed Description
Stores properties of a column in a QgsComposerTable.
Some properties of a QgsComposerTableColumn are applicable only in certain contexts. For instance, the attribute and setAttribute methods only have an effect for QgsComposerAttributeTables, and have no effect for QgsComposerTextTables.
Definition at line 27 of file qgscomposertablecolumn.h.
Constructor & Destructor Documentation
QgsComposerTableColumn::QgsComposerTableColumn ()
Definition at line 20 of file qgscomposertablecolumn.cpp.
Referenced by clone().
QgsComposerTableColumn::~QgsComposerTableColumn () virtual
Definition at line 29 of file qgscomposertablecolumn.cpp.
Member Function Documentation
QString QgsComposerTableColumn::attribute () const inline
Returns the attribute name or expression used for the column's values.
This property is only used when the column is part of a QgsComposerAttributeTable.
Returns
attribute name or expression text for column
Note
added in 2.3
only applicable when used in a QgsComposerAttributeTable
See also
setAttribute
Definition at line 90 of file qgscomposertablecolumn.h.
Referenced by QgsComposerAttributeTableColumnModel::data(), QgsComposerTableSortColumnsProxyModel::data(), and QgsComposerAttributeTableColumnModel::setData().
QgsComposerTableColumn * QgsComposerTableColumn::clone ()
Creates a duplicate column which is a deep copy of this column.
Returns
a new QgsComposerTableColumn with same properties as this column.
Note
added in 2.3
Definition at line 82 of file qgscomposertablecolumn.cpp.
References mAttribute, mHAlignment, mHeading, mSortByRank, mSortOrder, QgsComposerTableColumn(), setAttribute(), setHAlignment(), setHeading(), setSortByRank(), and setSortOrder().
Qt::AlignmentFlag QgsComposerTableColumn::hAlignment () const inline
Returns the horizontal alignment for a column, which controls the alignment used for drawing column values within cells.
Returns
horizontal alignment.
Note
added in 2.3
See also
setHAlignment
Definition at line 73 of file qgscomposertablecolumn.h.
Referenced by QgsComposerAttributeTableColumnModel::data().
QString QgsComposerTableColumn::heading () const inline
Returns the heading for a column, which is the value displayed in the columns header cell.
Returns
Heading for column.
Note
added in 2.3
See also
setHeading
Definition at line 57 of file qgscomposertablecolumn.h.
Referenced by QgsComposerAttributeTableColumnModel::data(), and QgsComposerAttributeTableColumnModel::setData().
bool QgsComposerTableColumn::readXML (const QDomElement & columnElem) virtual
Reads the column's properties from xml.
Parameters
columnElem a QDomElement holding the column's desired properties.
Note
added in 2.3
See also
writeXML
Definition at line 55 of file qgscomposertablecolumn.cpp.
References mAttribute, mBackgroundColor, mHAlignment, mHeading, mSortByRank, and mSortOrder.
Referenced by QgsComposerTable::tableReadXML().
void QgsComposerTableColumn::setAttribute (QString attribute) inline
Sets the attribute name or expression used for the column's values.
This property is only used when the column is part of a QgsComposerAttributeTable.
Parameters
attribute attribute name or expression text for column
Note
added in 2.3
only applicable when used in a QgsComposerAttributeTable
See also
attribute
Definition at line 99 of file qgscomposertablecolumn.h.
Referenced by clone(), QgsComposerAttributeTable::resetColumns(), QgsComposerAttributeTableColumnModel::setData(), and QgsComposerAttributeTable::setDisplayAttributes().
void QgsComposerTableColumn::setHAlignment (Qt::AlignmentFlag alignment) inline
Sets the horizontal alignment for a column, which controls the alignment used for drawing column values within cells.
Parameters
alignment horizontal alignment for cell.
Note
added in 2.3
See also
hAlignment
Definition at line 81 of file qgscomposertablecolumn.h.
Referenced by clone(), and QgsComposerAttributeTableColumnModel::setData().
void QgsComposerTableColumn::setHeading (QString heading) inline
Sets the heading for a column, which is the value displayed in the columns header cell.
Parameters
heading Heading for column.
Note
added in 2.3
See also
heading
Definition at line 65 of file qgscomposertablecolumn.h.
Referenced by clone(), QgsComposerAttributeTable::resetColumns(), QgsComposerAttributeTableColumnModel::setData(), QgsComposerAttributeTable::setDisplayAttributes(), and QgsComposerTextTable::setHeaderLabels().
void QgsComposerTableColumn::setSortByRank (int sortByRank) inline
Sets the sort rank for the column.
If the sort rank is > 0 then the column will be sorted in the table. The sort rank specifies the priority given to the column when the table is sorted by multiple columns, with lower sort ranks having higher priority. This property is only used when the column is part of a QgsComposerAttributeTable.
Parameters
sortByRank sort rank for column. If sort rank is <= 0 then the column is not being sorted.
Note
added in 2.3
only applicable when used in a QgsComposerAttributeTable
See also
sortByRank
setSortOrder
Definition at line 147 of file qgscomposertablecolumn.h.
Referenced by clone(), QgsComposerAttributeTableColumnModel::moveColumnInSortRank(), QgsComposerAttributeTableColumnModel::setColumnAsSorted(), and QgsComposerAttributeTableColumnModel::setColumnAsUnsorted().
void QgsComposerTableColumn::setSortOrder (Qt::SortOrder sortOrder) inline
Sets the sort order for the column.
This property is only used when the column is part of a QgsComposerAttributeTable and when sortByRank is > 0.
Parameters
sortOrder sort order for column
Note
added in 2.3
only applicable when used in a QgsComposerAttributeTable
See also
sortOrder
setSortByRank
Definition at line 119 of file qgscomposertablecolumn.h.
Referenced by clone(), QgsComposerAttributeTableColumnModel::setColumnAsSorted(), and QgsComposerTableSortColumnsProxyModel::setData().
int QgsComposerTableColumn::sortByRank () const inline
Returns the sort rank for the column.
If the sort rank is > 0 then the column will be sorted in the table. The sort rank specifies the priority given to the column when the table is sorted by multiple columns, with lower sort ranks having higher priority. This property is only used when the column is part of a QgsComposerAttributeTable.
Returns
sort rank for column. If sort rank is <= 0 then the column is not being sorted.
Note
added in 2.3
only applicable when used in a QgsComposerAttributeTable
See also
setSortByRank
sortOrder
Definition at line 133 of file qgscomposertablecolumn.h.
Referenced by columnsBySortRank(), QgsComposerTableSortColumnsProxyModel::filterAcceptsRow(), QgsComposerTableSortColumnsProxyModel::lessThan(), and QgsComposerAttributeTableColumnModel::moveColumnInSortRank().
Qt::SortOrder QgsComposerTableColumn::sortOrder () const inline
Returns the sort order for the column.
This property is only used when the column is part of a QgsComposerAttributeTable and when sortByRank is > 0.
Returns
sort order for column
Note
added in 2.3
only applicable when used in a QgsComposerAttributeTable
See also
setSortOrder
sortByRank
Definition at line 109 of file qgscomposertablecolumn.h.
Referenced by QgsComposerTableSortColumnsProxyModel::data().
bool QgsComposerTableColumn::writeXML (QDomElement & columnElem, QDomDocument & doc) const virtual
Writes the column's properties to xml for storage.
Parameters
columnElem an existing QDomElement in which to store the column's properties.
doc QDomDocument for the destination xml.
Note
added in 2.3
See also
readXML
Definition at line 34 of file qgscomposertablecolumn.cpp.
References mAttribute, mBackgroundColor, mHAlignment, mHeading, mSortByRank, and mSortOrder.
Member Data Documentation
QString QgsComposerTableColumn::mAttribute private
Definition at line 160 of file qgscomposertablecolumn.h.
Referenced by clone(), readXML(), and writeXML().
QColor QgsComposerTableColumn::mBackgroundColor private
Definition at line 157 of file qgscomposertablecolumn.h.
Referenced by readXML(), and writeXML().
Qt::AlignmentFlag QgsComposerTableColumn::mHAlignment private
Definition at line 158 of file qgscomposertablecolumn.h.
Referenced by clone(), readXML(), and writeXML().
QString QgsComposerTableColumn::mHeading private
Definition at line 159 of file qgscomposertablecolumn.h.
Referenced by clone(), readXML(), and writeXML().
int QgsComposerTableColumn::mSortByRank private
Definition at line 161 of file qgscomposertablecolumn.h.
Referenced by clone(), readXML(), and writeXML().
Qt::SortOrder QgsComposerTableColumn::mSortOrder private
Definition at line 162 of file qgscomposertablecolumn.h.
Referenced by clone(), readXML(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposertablecolumn.h
/tmp/buildd/qgis-2.4.0+unstable1/src/core/composer/qgscomposertablecolumn.cpp