QGIS API Documentation: /tmp/buildd/qgis-2.4.0+unstable1/src/core/qgis.h File Reference
qgis.h File Reference
#include <QEvent>
#include <QString>
#include <QRegExp>
#include <QMetaType>
#include <QVariant>
#include <stdlib.h>
#include <cfloat>
#include <cmath>
#include <qnumeric.h>
Classes
class QGis
The QGis class provides global constants for use throughout the application.
Macros
#define Q_NOWARN_DEPRECATED_PUSH
#define Q_NOWARN_DEPRECATED_POP
#define QGISEXTERN extern "C"
Typedefs
typedef QMap< QString, QString > QgsStringMap
typedef unsigned long long qgssize
qgssize is used instead of size_t, because size_t is stdlib type, unknown by SIP, and it would be hard to define size_t correctly in SIP.
Functions
QString qgsDoubleToString (const double &a)
bool qgsDoubleNear (double a, double b, double epsilon=4 *DBL_EPSILON)
bool qgsDoubleNearSig (double a, double b, int significantDigits=10)
bool qgsVariantLessThan (const QVariant &lhs, const QVariant &rhs)
bool qgsVariantGreaterThan (const QVariant &lhs, const QVariant &rhs)
QString qgsVsiPrefix (QString path)
void CORE_EXPORT * qgsMalloc (size_t size)
Allocates size bytes and returns a pointer to the allocated memory.
void CORE_EXPORT * qgsCalloc (size_t nmemb, size_t size)
Allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated memory.
void CORE_EXPORT qgsFree (void *ptr)
Frees the memory space pointed to by ptr.
Variables
void(*)() cast_to_fptr (void *p)
CORE_EXPORT const QString GEOWKT
Wkt string that represents a geographic coord sys.
CORE_EXPORT const QString PROJECT_SCALES
CORE_EXPORT const QString GEOPROJ4
PROJ4 string that represents a geographic coord sys.
const long GEOSRID = 4326
Magic number for a geographic coord sys in POSTGIS SRID.
const long GEOCRS_ID = 3452
Magic number for a geographic coord sys in QGIS srs.db tbl_srs.srs_id.
const long GEO_EPSG_CRS_ID = 4326
Magic number for a geographic coord sys in EpsgCrsId ID format.
CORE_EXPORT const QString GEO_EPSG_CRS_AUTHID
Geographic coord sys from EPSG authority.
const int PROJ_PREFIX_LEN = 6
The length of the string "+proj=".
const int ELLPS_PREFIX_LEN = 7
The length of the string "+ellps=".
const int LAT_PREFIX_LEN = 7
The length of the string "+lat_1=".
const int USER_CRS_START_ID = 100000
Magick number that determines whether a projection crsid is a system (srs.db) or user (~/.qgis.qgis.db) defined projection.
CORE_EXPORT const QString GEO_NONE
Constant that holds the string representation for "No ellips/No CRS".
const double MINIMUM_POINT_SIZE = 0.1
Magic number that determines the minimum allowable point size for point symbols.
const double DEFAULT_POINT_SIZE = 2.0
Magic number that determines the default point size for point symbols.
const double DEFAULT_LINE_WIDTH = 0.26
const double DEFAULT_SEGMENT_EPSILON = 1e-8
default snapping tolerance for segments (
Macro Definition Documentation
#define Q_NOWARN_DEPRECATED_POP
Definition at line 440 of file qgis.h.
Referenced by QgsMapCanvas::canvasPaintDevice(), QgsVectorLayer::editType(), QgsComposerMap::mapRenderer(), QgsVectorLayer::setEditType(), and QgsMapRenderer::setProjectionsEnabled().
#define Q_NOWARN_DEPRECATED_PUSH
Definition at line 439 of file qgis.h.
Referenced by QgsMapCanvas::canvasPaintDevice(), QgsVectorLayer::editType(), QgsComposerMap::mapRenderer(), QgsVectorLayer::setEditType(), and QgsMapRenderer::setProjectionsEnabled().
#define QGISEXTERN extern "C"
Definition at line 452 of file qgis.h.
Typedef Documentation
typedef unsigned long long qgssize
qgssize is used instead of size_t, because size_t is stdlib type, unknown by SIP, and it would be hard to define size_t correctly in SIP.
Currently used "unsigned long long" was introduced in C++11 (2011) but it was supported already before C++11 on common platforms. "unsigned long long int" gives syntax error in SIP. KEEP IN SYNC WITH qgssize defined in SIP!
Definition at line 424 of file qgis.h.
typedef QMap<QString, QString> QgsStringMap
Definition at line 416 of file qgis.h.
Function Documentation
void CORE_EXPORT* qgsCalloc (size_t nmemb, size_t size)
Allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated memory.
Works like C calloc() but prints debug message by QgsLogger if allocation fails.
Parameters
nmemb number of elements
size size of element in bytes
Definition at line 190 of file qgis.cpp.
References QgsDebugMsg, and qgsMalloc().
bool qgsDoubleNear (double a, double b, double epsilon = 4 * DBL_EPSILON) inline
Definition at line 324 of file qgis.h.
Referenced by QgsRasterTransparency::alphaValue(), QgsSVGFillSymbolLayer::applyPattern(), QgsLinePatternFillSymbolLayer::applyPattern(), QgsPointPatternFillSymbolLayer::applyPattern(), QgsMultiBandColorRenderer::block(), QgsSingleBandGrayRenderer::block(), QgsRasterResampleFilter::block(), QgsRasterDataProvider::block(), QgsSvgCache::cacheEntry(), QgsTransectSample::closestSegmentPoints(), QgsComposerMouseHandles::collectAlignCoordinates(), compareWkt(), QgsClipper::connectSeparatedLines(), QgsRasterRange::contains(), QgsSymbolLayerV2Utils::convertPolygonSymbolizerToPointMarker(), QgsEllipseSymbolLayerV2::createFromSld(), QgsGeometryAnalyzer::eventLayer(), QgsSymbolLayerV2Utils::externalMarkerToSld(), QgsComposerItem::imageSizeConsideringRotation(), QgsClipper::intersectRect(), QgsRasterBlock::isNoDataValue(), QgsSymbolLayerV2Utils::lineToSld(), QgsGeometryAnalyzer::locateAlongSegment(), QgsComposition::nearestSnapLine(), QgsSymbolLayerV2Utils::ogrFeatureStylePen(), QgsRelief::optimiseClassBreaks(), QgsComposerRuler::paintEvent(), QgsEllipseSymbolLayerV2::renderPoint(), QgsSvgMarkerSymbolLayerV2::renderPoint(), QgsImageFillSymbolLayer::renderPolygon(), QgsCoordinateReferenceSystem::setMapUnits(), QgsPoint::sqrDistToSegment(), QgsMarkerLineSymbolLayerV2::toSld(), QgsRasterCalculator::transformationsEqual(), QgsRasterRenderer::usesTransparency(), QgsSymbolLayerV2Utils::wellKnownMarkerToSld(), QgsEllipseSymbolLayerV2::writeDxf(), QgsSvgMarkerSymbolLayerV2::writeDxf(), QgsEllipseSymbolLayerV2::writeSldMarker(), QgsComposerMap::xGridLines(), and QgsComposerMap::yGridLines().
bool qgsDoubleNearSig (double a, double b, int significantDigits = 10) inline
Definition at line 333 of file qgis.h.
QString qgsDoubleToString (const double & a) inline
Definition at line 316 of file qgis.h.
Referenced by QgsMapRenderer::adjustExtentToSize(), QgsRectangle::asWktCoordinates(), QgsRectangle::asWktPolygon(), QgsOgcUtils::createGMLCoordinates(), QgsOgcUtils::createGMLPositions(), QgsGeometry::exportToGeoJSON(), QgsGeometry::exportToWkt(), QgsOgcUtils::geometryToGML(), QgsOgcUtils::rectangleToGMLBox(), QgsOgcUtils::rectangleToGMLEnvelope(), QgsRenderChecker::runTest(), QgsMapCanvas::saveAsImage(), QgsCoordinateReferenceSystem::syncDatumTransform(), QgsMapSettings::updateDerived(), QgsPoint::wellKnownText(), QgsXmlUtils::writeRectangle(), and QgsComposerMap::writeXML().
void CORE_EXPORT qgsFree (void * ptr)
Frees the memory space pointed to by ptr.
Works like C free().
Parameters
ptr pointer to memory space
Definition at line 205 of file qgis.cpp.
Referenced by QgsRasterBlock::convert(), QgsRasterBlock::reset(), QgsRasterBlock::setImage(), QgsRasterFileWriter::writeImageRaster(), and QgsRasterBlock::~QgsRasterBlock().
void CORE_EXPORT* qgsMalloc (size_t size)
Allocates size bytes and returns a pointer to the allocated memory.
Works like C malloc() but prints debug message by QgsLogger if allocation fails.
Parameters
size size in bytes
Definition at line 175 of file qgis.cpp.
References QgsDebugMsg.
Referenced by QgsRasterBlock::convert(), QgsRasterBlock::createNoDataBitmap(), qgsCalloc(), QgsRasterBlock::reset(), and QgsRasterFileWriter::writeImageRaster().
bool qgsVariantGreaterThan (const QVariant & lhs, const QVariant & rhs)
Definition at line 237 of file qgis.cpp.
References qgsVariantLessThan().
Referenced by QgsSymbolLayerV2Utils::sortVariantList(), and valueGreaterThan().
bool qgsVariantLessThan (const QVariant & lhs, const QVariant & rhs)
Definition at line 210 of file qgis.cpp.
Referenced by qgsVariantGreaterThan(), QgsSymbolLayerV2Utils::sortVariantList(), and valueLessThan().
QString qgsVsiPrefix (QString path)
Definition at line 242 of file qgis.cpp.
Referenced by QgsProject::readPath(), QgsZipItem::vsiPrefix(), and QgsProject::writePath().
Variable Documentation
void(*)() cast_to_fptr(void *p) inline
Definition at line 301 of file qgis.h.
Referenced by QgsBrowserModel::addRootItems(), QgsRasterDataProvider::create(), QgsDirectoryItem::createChildren(), QgsVectorLayer::getStyleFromDatabase(), QgsRasterFormatSaveOptionsWidget::helpOptions(), QgsRasterLayer::isValidRasterFileName(), QgsVectorLayer::listStylesInDatabase(), QgsVectorLayer::loadNamedStyle(), QgsProviderRegistry::provider(), QgsRasterDataProvider::pyramidResamplingMethods(), QgsDirectoryItem::QgsDirectoryItem(), QgsProviderRegistry::QgsProviderRegistry(), QgsVectorLayerImport::QgsVectorLayerImport(), QgsZipItem::QgsZipItem(), QgsProviderRegistry::registerGuis(), QgsNewVectorLayerDialog::runAndCreateLayer(), QgsVectorLayer::saveStyleToDatabase(), QgsProviderRegistry::selectWidget(), QgsRasterFormatSaveOptionsWidget::validateOptions(), and QgsProviderRegistry::~QgsProviderRegistry().
const double DEFAULT_LINE_WIDTH = 0.26
Definition at line 411 of file qgis.h.
const double DEFAULT_POINT_SIZE = 2.0
Magic number that determines the default point size for point symbols.
Definition at line 410 of file qgis.h.
Referenced by readMarkerSymbolSize().
const double DEFAULT_SEGMENT_EPSILON = 1e-8
default snapping tolerance for segments (
Note
added in 1.8)
Definition at line 414 of file qgis.h.
const int ELLPS_PREFIX_LEN = 7
The length of the string "+ellps=".
Definition at line 392 of file qgis.h.
CORE_EXPORT const QString GEO_EPSG_CRS_AUTHID
Geographic coord sys from EPSG authority.
Definition at line 71 of file qgis.cpp.
Referenced by QgsOWSSourceSelect::on_mChangeCRSButton_clicked(), QgsOWSSourceSelect::populateCRS(), QgsNewVectorLayerDialog::QgsNewVectorLayerDialog(), QgsVectorLayer::setCoordinateSystem(), and QgsCoordinateReferenceSystem::validate().
const long GEO_EPSG_CRS_ID = 4326
Magic number for a geographic coord sys in EpsgCrsId ID format.
Definition at line 386 of file qgis.h.
CORE_EXPORT const QString GEO_NONE
Constant that holds the string representation for "No ellips/No CRS".
Definition at line 73 of file qgis.cpp.
Referenced by QgsDistanceArea::bearing(), QgsDistanceArea::computeDistance(), QgsDistanceArea::computePolygonArea(), QgsDistanceArea::convertMeasurement(), QgsMapToolIdentify::featureDerivedAttributes(), QgsDistanceArea::measureLine(), QgsDistanceArea::measurePolygon(), QgsDistanceArea::QgsDistanceArea(), and QgsDistanceArea::setEllipsoid().
const long GEOCRS_ID = 3452
Magic number for a geographic coord sys in QGIS srs.db tbl_srs.srs_id.
Definition at line 384 of file qgis.h.
Referenced by QgsDistanceArea::QgsDistanceArea(), QgsMapRenderer::QgsMapRenderer(), and QgsCoordinateReferenceSystem::readXML().
CORE_EXPORT const QString GEOPROJ4
PROJ4 string that represents a geographic coord sys.
Definition at line 51 of file qgis.cpp.
const long GEOSRID = 4326
Magic number for a geographic coord sys in POSTGIS SRID.
Definition at line 382 of file qgis.h.
CORE_EXPORT const QString GEOWKT
Wkt string that represents a geographic coord sys.
Note
added in 1.8 to replace GEOWkt
Definition at line 54 of file qgis.cpp.
const int LAT_PREFIX_LEN = 7
The length of the string "+lat_1=".
Definition at line 394 of file qgis.h.
Referenced by QgsCoordinateReferenceSystem::createFromProj4().
const double MINIMUM_POINT_SIZE = 0.1
Magic number that determines the minimum allowable point size for point symbols.
Definition at line 408 of file qgis.h.
const int PROJ_PREFIX_LEN = 6
The length of the string "+proj=".
Definition at line 390 of file qgis.h.
CORE_EXPORT const QString PROJECT_SCALES
Definition at line 67 of file qgis.cpp.
Referenced by QgsScaleComboBox::updateScales().
const int USER_CRS_START_ID = 100000
Magick number that determines whether a projection crsid is a system (srs.db) or user (~/.qgis.qgis.db) defined projection.
Definition at line 397 of file qgis.h.
Referenced by QgsCoordinateReferenceSystem::createFromSrsId(), QgsProjectionSelector::getSelectedExpression(), QgsCoordinateReferenceSystem::loadFromDb(), QgsCoordinateReferenceSystem::proj4FromSrsId(), QgsCoordinateReferenceSystem::readXML(), QgsCoordinateReferenceSystem::saveAsUserCRS(), QgsProjectionSelector::selectedAuthId(), and QgsProjectionSelector::selectedProj4String().