QGIS API Documentation: /tmp/buildd/qgis-2.4.0+unstable1/src/core/qgscoordinatetransform.h File Reference
qgscoordinatetransform.h File Reference
#include <QObject>
#include "qgspoint.h"
#include "qgsrectangle.h"
#include "qgscsexception.h"
#include "qgscoordinatereferencesystem.h"
#include <iostream>
#include <vector>
Classes
class QgsCoordinateTransform
Class for doing transforms between two map coordinate systems.
Typedefs
typedef void * projPJ
Functions
std::ostream & operator<< (std::ostream &os, const QgsCoordinateTransform &r)
Output stream operator.
Typedef Documentation
typedef void* projPJ
Definition at line 30 of file qgscoordinatetransform.h.
Function Documentation
std::ostream& operator<< (std::ostream & os, const QgsCoordinateTransform & r) inline
Output stream operator.
Definition at line 303 of file qgscoordinatetransform.h.
References QgsCoordinateTransform::destCRS(), QgsCoordinateTransform::isInitialised(), QgsCoordinateTransform::isShortCircuited(), and QgsCoordinateTransform::sourceCrs().