QGIS API Documentation: /tmp/buildd/qgis-2.4.0+unstable1/src/gui/qgsmessagelogviewer.cpp File Reference
qgsmessagelogviewer.cpp File Reference
#include "qgsmessagelogviewer.h"
#include "qgsmessagelog.h"
#include "qgsapplication.h"
#include <QFile>
#include <QDateTime>
#include <QTableWidget>
#include <QToolButton>
#include <QStatusBar>
#include <QToolTip>
#include <QDockWidget>
Functions
static QIcon icon (QString icon)
Function Documentation
static QIcon icon (QString icon) static
Definition at line 30 of file qgsmessagelogviewer.cpp.
References QgsApplication::activeThemePath(), and QgsApplication::defaultThemePath().
Referenced by QgsDualView::columnBoxInit(), QgsFeatureListViewDelegate::paint(), QgsDirectoryParamWidget::QgsDirectoryParamWidget(), QgsMessageLogViewer::QgsMessageLogViewer(), QgsRendererV2AbstractMetadata::setIcon(), QgsMessageBarItem::setIcon(), QgsRubberBand::setIcon(), QgsDataItem::setIcon(), QgsCptCityDataItem::setIcon(), QgsDataDefinedButton::updateGui(), and QgsMessageBarItem::writeContent().