QGIS API Documentation: /tmp/buildd/qgis-2.4.0+unstable1/src/core/qgspoint.h File Reference
qgspoint.h File Reference
#include <qgis.h>
#include <iostream>
#include <QString>
#include <QPoint>
Classes
class QgsVector
A class to represent a vector.
class QgsPoint
A class to represent a point geometry.
Functions
bool operator== (const QgsPoint &p1, const QgsPoint &p2)
std::ostream & operator<< (std::ostream &os, const QgsPoint &p)
uint qHash (const QgsPoint &p)
Function Documentation
std::ostream& operator<< (std::ostream & os, const QgsPoint & p) inline
Definition at line 209 of file qgspoint.h.
References QgsPoint::toString().
bool operator== (const QgsPoint & p1, const QgsPoint & p2) inline
Definition at line 201 of file qgspoint.h.
References QgsPoint::x(), and QgsPoint::y().
uint qHash (const QgsPoint & p) inline
Definition at line 216 of file qgspoint.h.
References QgsPoint::m_x, and QgsPoint::m_y.