QGIS API Documentation: /tmp/buildd/qgis-2.4.0+unstable1/src/core/qgspallabeling.cpp File Reference
qgspallabeling.cpp File Reference
#include "qgspallabeling.h"
#include "qgspalgeometry.h"
#include <list>
#include <pal/pal.h>
#include <pal/feature.h>
#include <pal/layer.h>
#include <pal/palgeometry.h>
#include <pal/palexception.h>
#include <pal/problem.h>
#include <pal/labelposition.h>
#include <geos_c.h>
#include <cmath>
#include <QApplication>
#include <QByteArray>
#include <QString>
#include <QFontMetrics>
#include <QTime>
#include <QPainter>
#include "diagram/qgsdiagram.h"
#include "qgsdiagramrendererv2.h"
#include "qgsfontutils.h"
#include "qgslabelsearchtree.h"
#include "qgsexpression.h"
#include "qgsdatadefined.h"
#include <qgslogger.h>
#include <qgsvectorlayer.h>
#include <qgsmaplayerregistry.h>
#include <qgsvectordataprovider.h>
#include <qgsgeometry.h>
#include <qgsmaprenderer.h>
#include <qgsmarkersymbollayerv2.h>
#include <qgsproject.h>
#include "qgssymbolv2.h"
#include "qgssymbollayerv2utils.h"
#include <QMessageBox>
Functions
Q_GUI_EXPORT int qt_defaultDpiX ()
Q_GUI_EXPORT int qt_defaultDpiY ()
static void _fixQPictureDPI (QPainter *p)
static QColor _readColor (QgsVectorLayer *layer, QString property, QColor defaultColor=Qt::black, bool withAlpha=true)
static void _writeColor (QgsVectorLayer *layer, QString property, QColor color, bool withAlpha=true)
static
QgsPalLayerSettings::SizeUnit _decodeUnits (const QString &str)
static QPainter::CompositionMode _decodeBlendMode (const QString &str)
static Qt::PenJoinStyle _decodePenJoinStyle (const QString &str)
static bool _palIsCancelled (void *ctx)
Function Documentation
static QPainter::CompositionMode _decodeBlendMode (const QString & str) static
Definition at line 657 of file qgspallabeling.cpp.
Referenced by QgsPalLayerSettings::dataDefinedValEval().
static Qt::PenJoinStyle _decodePenJoinStyle (const QString & str) static
Definition at line 674 of file qgspallabeling.cpp.
Referenced by QgsPalLayerSettings::dataDefinedValEval().
static QgsPalLayerSettings::SizeUnit _decodeUnits (const QString & str) static
Definition at line 647 of file qgspallabeling.cpp.
References QgsPalLayerSettings::MapUnits, QgsPalLayerSettings::MM, QgsPalLayerSettings::Percent, and QgsPalLayerSettings::Points.
Referenced by QgsPalLayerSettings::dataDefinedValEval(), QgsPalLabeling::prepareLayer(), and QgsPalLayerSettings::registerFeature().
static void _fixQPictureDPI (QPainter * p) static
Definition at line 65 of file qgspallabeling.cpp.
References qt_defaultDpiX(), and qt_defaultDpiY().
Referenced by QgsPalLabeling::drawLabel(), QgsPalLabeling::drawLabelBackground(), and QgsPalLabeling::drawLabelBuffer().
static bool _palIsCancelled (void * ctx) static
Definition at line 3995 of file qgspallabeling.cpp.
Referenced by QgsPalLabeling::drawLabeling().
static QColor _readColor (QgsVectorLayer * layer, QString property, QColor defaultColor = Qt::black, bool withAlpha = true) static
Definition at line 629 of file qgspallabeling.cpp.
References QgsMapLayer::customProperty().
Referenced by QgsPalLayerSettings::readFromLayer().
static void _writeColor (QgsVectorLayer * layer, QString property, QColor color, bool withAlpha = true) static
Definition at line 638 of file qgspallabeling.cpp.
References QgsMapLayer::setCustomProperty().
Referenced by QgsPalLayerSettings::writeToLayer().
Q_GUI_EXPORT int qt_defaultDpiX ()
Referenced by _fixQPictureDPI().
Q_GUI_EXPORT int qt_defaultDpiY ()
Referenced by _fixQPictureDPI().