QGIS API Documentation: /tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2utils.cpp File Reference
qgssymbollayerv2utils.cpp File Reference
#include "qgssymbollayerv2utils.h"
#include "qgssymbollayerv2.h"
#include "qgssymbollayerv2registry.h"
#include "qgssymbolv2.h"
#include "qgsvectorcolorrampv2.h"
#include "qgsexpression.h"
#include "qgsapplication.h"
#include "qgsproject.h"
#include "qgsogcutils.h"
#include "qgslogger.h"
#include "qgsrendercontext.h"
#include <QColor>
#include <QFont>
#include <QDomDocument>
#include <QDomNode>
#include <QDomElement>
#include <QIcon>
#include <QPainter>
#include <QSettings>
#include <QPolygonF>
#include <cmath>
#include <cfloat>
Functions
static bool lineInfo (QPointF p1, QPointF p2, double &angle, double &t)
static QPointF offsetPoint (QPointF pt, double angle, double dist)
static QPointF linesIntersection (QPointF p1, double t1, QPointF p2, double t2)
QList< QPolygonF > offsetLine (QPolygonF polyline, double dist, QGis::GeometryType geometryType)
calculate geometry shifted by a specified distance
QList< QPolygonF > offsetLine (QPolygonF polyline, double dist)
static QString _nameForSymbolType (QgsSymbolV2::SymbolType type)
Function Documentation
static QString _nameForSymbolType (QgsSymbolV2::SymbolType type) static
Definition at line 926 of file qgssymbollayerv2utils.cpp.
References QgsSymbolV2::Fill, QgsSymbolV2::Line, and QgsSymbolV2::Marker.
Referenced by QgsSymbolLayerV2Utils::saveSymbol().
static bool lineInfo (QPointF p1, QPointF p2, double & angle, double & t) static
Definition at line 604 of file qgssymbollayerv2utils.cpp.
References M_PI.
Referenced by offsetLine().
static QPointF linesIntersection (QPointF p1, double t1, QPointF p2, double t2) static
Definition at line 634 of file qgssymbollayerv2utils.cpp.
Referenced by offsetLine().
QList<QPolygonF> offsetLine (QPolygonF polyline, double dist, QGis::GeometryType geometryType)
calculate geometry shifted by a specified distance
Definition at line 685 of file qgssymbollayerv2utils.cpp.
References MathUtils::angle(), QgsGeometry::asMultiPolygon(), QgsGeometry::asMultiPolyline(), QgsGeometry::asPolygon(), QgsGeometry::asPolyline(), QgsGeometry::buffer(), QGis::flatType(), QgsGeometry::fromPolygon(), QgsGeometry::fromPolyline(), lineInfo(), linesIntersection(), M_PI, QgsGeometry::offsetCurve(), offsetPoint(), QGis::Polygon, QGis::WKBLineString, QGis::WKBMultiLineString, QGis::WKBMultiPolygon, QGis::WKBPolygon, and QgsGeometry::wkbType().
Referenced by offsetLine(), QgsSimpleLineSymbolLayerV2::renderPolyline(), and QgsMarkerLineSymbolLayerV2::renderPolyline().
QList<QPolygonF> offsetLine (QPolygonF polyline, double dist)
Deprecated:
since 2.4 - calculate line shifted by a specified distance
Definition at line 808 of file qgssymbollayerv2utils.cpp.
References QGis::Line, offsetLine(), QGis::Point, and QGis::Polygon.
static QPointF offsetPoint (QPointF pt, double angle, double dist) static
Definition at line 628 of file qgssymbollayerv2utils.cpp.
Referenced by offsetLine().