QGIS API Documentation: /tmp/buildd/qgis-2.4.0+unstable1/src/core/symbology-ng/qgssymbollayerv2utils.h File Reference
qgssymbollayerv2utils.h File Reference
#include <QMap>
#include <Qt>
#include <QtCore>
#include <QFont>
#include <QColor>
#include "qgssymbolv2.h"
#include "qgis.h"
#include "qgsmapunitscale.h"
Classes
class QgsSymbolLayerV2Utils
Typedefs
typedef QMap< QString, QString > QgsStringMap
typedef QMap< QString,
QgsSymbolV2 * > QgsSymbolV2Map
Functions
QList< QPolygonF > offsetLine (QPolygonF polyline, double dist)
QList< QPolygonF > offsetLine (QPolygonF polyline, double dist, QGis::GeometryType geometryType)
calculate geometry shifted by a specified distance
Typedef Documentation
typedef QMap<QString, QString> QgsStringMap
Definition at line 31 of file qgssymbollayerv2utils.h.
typedef QMap<QString, QgsSymbolV2* > QgsSymbolV2Map
Definition at line 34 of file qgssymbollayerv2utils.h.
Function Documentation
QList<QPolygonF> offsetLine (QPolygonF polyline, double dist)
Deprecated:
since 2.4 - calculate line shifted by a specified distance
Definition at line 808 of file qgssymbollayerv2utils.cpp.
References QGis::Line, offsetLine(), QGis::Point, and QGis::Polygon.
QList<QPolygonF> offsetLine (QPolygonF polyline, double dist, QGis::GeometryType geometryType)
calculate geometry shifted by a specified distance
Definition at line 685 of file qgssymbollayerv2utils.cpp.
References MathUtils::angle(), QgsGeometry::asMultiPolygon(), QgsGeometry::asMultiPolyline(), QgsGeometry::asPolygon(), QgsGeometry::asPolyline(), QgsGeometry::buffer(), QGis::flatType(), QgsGeometry::fromPolygon(), QgsGeometry::fromPolyline(), lineInfo(), linesIntersection(), M_PI, QgsGeometry::offsetCurve(), offsetPoint(), QGis::Polygon, QGis::WKBLineString, QGis::WKBMultiLineString, QGis::WKBMultiPolygon, QGis::WKBPolygon, and QgsGeometry::wkbType().
Referenced by offsetLine(), QgsSimpleLineSymbolLayerV2::renderPolyline(), and QgsMarkerLineSymbolLayerV2::renderPolyline().