QGIS API Documentation: QgsTicksScaleBarStyle Class Reference
QgsTicksScaleBarStyle Class Reference
MapComposer
A scale bar that draws segments using short ticks.
#include <qgsticksscalebarstyle.h>
Public Types
enum TickPosition { TicksUp, TicksDown, TicksMiddle }
Public Member Functions
QgsTicksScaleBarStyle (const QgsComposerScaleBar *bar)
~QgsTicksScaleBarStyle ()
QString name () const
void draw (QPainter *p, double xOffset=0) const
void setTickPosition (TickPosition p)
Public Member Functions inherited from QgsScaleBarStyle
QgsScaleBarStyle (const QgsComposerScaleBar *bar)
virtual ~QgsScaleBarStyle ()
virtual void drawLabels (QPainter *p) const
virtual QRectF calculateBoxSize () const
Private Member Functions
QgsTicksScaleBarStyle ()
Private Attributes
TickPosition mTickPosition
Additional Inherited Members
Protected Attributes inherited from QgsScaleBarStyle
const QgsComposerScaleBar * mScaleBar
Detailed Description
A scale bar that draws segments using short ticks.
Definition at line 25 of file qgsticksscalebarstyle.h.
Member Enumeration Documentation
enum QgsTicksScaleBarStyle::TickPosition
Enumerator:
TicksUp
TicksDown
TicksMiddle
Definition at line 28 of file qgsticksscalebarstyle.h.
Constructor & Destructor Documentation
QgsTicksScaleBarStyle::QgsTicksScaleBarStyle (const QgsComposerScaleBar * bar)
Definition at line 21 of file qgsticksscalebarstyle.cpp.
References mTickPosition, and TicksMiddle.
QgsTicksScaleBarStyle::~QgsTicksScaleBarStyle ()
Definition at line 31 of file qgsticksscalebarstyle.cpp.
QgsTicksScaleBarStyle::QgsTicksScaleBarStyle () private
Definition at line 26 of file qgsticksscalebarstyle.cpp.
References mTickPosition, and TicksMiddle.
Member Function Documentation
void QgsTicksScaleBarStyle::draw (QPainter * p, double xOffset = 0) const virtual
draw method
Parameters
p painter object
xOffset offset
Implements QgsScaleBarStyle.
Definition at line 50 of file qgsticksscalebarstyle.cpp.
References QgsComposerScaleBar::boxContentSpace(), QgsScaleBarStyle::drawLabels(), QgsComposerScaleBar::font(), QgsComposerItem::fontAscentMillimeters(), QgsComposerScaleBar::height(), QgsComposerScaleBar::labelBarSpace(), QgsScaleBarStyle::mScaleBar, mTickPosition, QgsComposerScaleBar::pen(), QgsComposerScaleBar::segmentMillimeters(), QgsComposerScaleBar::segmentPositions(), TicksDown, TicksMiddle, and TicksUp.
QString QgsTicksScaleBarStyle::name () const virtual
Implements QgsScaleBarStyle.
Definition at line 36 of file qgsticksscalebarstyle.cpp.
References mTickPosition, TicksDown, TicksMiddle, and TicksUp.
void QgsTicksScaleBarStyle::setTickPosition (TickPosition p) inline
Definition at line 46 of file qgsticksscalebarstyle.h.
Referenced by QgsComposerScaleBar::setStyle().
Member Data Documentation
TickPosition QgsTicksScaleBarStyle::mTickPosition private
Definition at line 51 of file qgsticksscalebarstyle.h.
Referenced by draw(), name(), and QgsTicksScaleBarStyle().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgsticksscalebarstyle.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgsticksscalebarstyle.cpp