QGIS API Documentation: QgsEncodingFileDialog Class Reference
QgsEncodingFileDialog Class Reference
QGIS gui library.
A file dialog which lets the user select the preferred encoding type for a data provider.
#include <qgsencodingfiledialog.h>
Public Slots
void saveUsedEncoding ()
void pbnCancelAll_clicked ()
Public Member Functions
QgsEncodingFileDialog (QWidget *parent=0, const QString &caption=QString(), const QString &directory=QString(), const QString &filter=QString(), const QString &encoding=QString())
~QgsEncodingFileDialog ()
QString encoding () const
Returns a string describing the chosen encoding.
void addCancelAll ()
bool cancelAll ()
Private Attributes
QComboBox * mEncodingComboBox
Box to choose the encoding type.
QPushButton * mCancelAllButton
bool mCancelAll
Detailed Description
A file dialog which lets the user select the preferred encoding type for a data provider.
Definition at line 26 of file qgsencodingfiledialog.h.
Constructor & Destructor Documentation
QgsEncodingFileDialog::QgsEncodingFileDialog (QWidget * parent = 0, const QString & caption = QString(), const QString & directory = QString(), const QString & filter = QString(), const QString & encoding = QString())
Definition at line 28 of file qgsencodingfiledialog.cpp.
References QgsVectorDataProvider::availableEncodings(), encoding(), mCancelAll, mCancelAllButton, mEncodingComboBox, saveUsedEncoding(), and tr.
QgsEncodingFileDialog::~QgsEncodingFileDialog ()
Definition at line 72 of file qgsencodingfiledialog.cpp.
Member Function Documentation
void QgsEncodingFileDialog::addCancelAll ()
Definition at line 89 of file qgsencodingfiledialog.cpp.
References mCancelAllButton, pbnCancelAll_clicked(), and tr.
Referenced by QgisGui::openFilesRememberingFilter().
bool QgsEncodingFileDialog::cancelAll ()
Definition at line 99 of file qgsencodingfiledialog.cpp.
References mCancelAll.
Referenced by QgisGui::openFilesRememberingFilter().
QString QgsEncodingFileDialog::encoding () const
Returns a string describing the chosen encoding.
Definition at line 77 of file qgsencodingfiledialog.cpp.
References mEncodingComboBox.
Referenced by QgsEncodingFileDialog(), QgsNewVectorLayerDialog::runAndCreateLayer(), and saveUsedEncoding().
void QgsEncodingFileDialog::pbnCancelAll_clicked () slot
Definition at line 104 of file qgsencodingfiledialog.cpp.
References mCancelAll.
Referenced by addCancelAll().
void QgsEncodingFileDialog::saveUsedEncoding () slot
Definition at line 82 of file qgsencodingfiledialog.cpp.
References encoding(), and QgsDebugMsg.
Referenced by QgsEncodingFileDialog().
Member Data Documentation
bool QgsEncodingFileDialog::mCancelAll private
Definition at line 54 of file qgsencodingfiledialog.h.
Referenced by cancelAll(), pbnCancelAll_clicked(), and QgsEncodingFileDialog().
QPushButton* QgsEncodingFileDialog::mCancelAllButton private
Definition at line 51 of file qgsencodingfiledialog.h.
Referenced by addCancelAll(), and QgsEncodingFileDialog().
QComboBox* QgsEncodingFileDialog::mEncodingComboBox private
Box to choose the encoding type.
Definition at line 48 of file qgsencodingfiledialog.h.
Referenced by encoding(), and QgsEncodingFileDialog().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsencodingfiledialog.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsencodingfiledialog.cpp