QGIS API Documentation: QgsDoubleBoxScaleBarStyle Class Reference
QgsDoubleBoxScaleBarStyle Class Reference
MapComposer
Double box with alternating colors.
#include <qgsdoubleboxscalebarstyle.h>
Public Member Functions
QgsDoubleBoxScaleBarStyle (const QgsComposerScaleBar *bar)
~QgsDoubleBoxScaleBarStyle ()
QString name () const
void draw (QPainter *p, double xOffset=0) const
Draws the style.
Public Member Functions inherited from QgsScaleBarStyle
QgsScaleBarStyle (const QgsComposerScaleBar *bar)
virtual ~QgsScaleBarStyle ()
virtual void drawLabels (QPainter *p) const
virtual QRectF calculateBoxSize () const
Private Member Functions
QgsDoubleBoxScaleBarStyle ()
Additional Inherited Members
Protected Attributes inherited from QgsScaleBarStyle
const QgsComposerScaleBar * mScaleBar
Detailed Description
Double box with alternating colors.
Definition at line 25 of file qgsdoubleboxscalebarstyle.h.
Constructor & Destructor Documentation
QgsDoubleBoxScaleBarStyle::QgsDoubleBoxScaleBarStyle (const QgsComposerScaleBar * bar)
Definition at line 22 of file qgsdoubleboxscalebarstyle.cpp.
QgsDoubleBoxScaleBarStyle::~QgsDoubleBoxScaleBarStyle ()
Definition at line 32 of file qgsdoubleboxscalebarstyle.cpp.
QgsDoubleBoxScaleBarStyle::QgsDoubleBoxScaleBarStyle () private
Definition at line 27 of file qgsdoubleboxscalebarstyle.cpp.
Member Function Documentation
void QgsDoubleBoxScaleBarStyle::draw (QPainter * p, double xOffset = 0) const virtual
Draws the style.
Parameters
p painter object
xOffset offset to account for centered labeling
Implements QgsScaleBarStyle.
Definition at line 42 of file qgsdoubleboxscalebarstyle.cpp.
References QgsComposerScaleBar::boxContentSpace(), QgsComposerScaleBar::brush(), QgsScaleBarStyle::drawLabels(), QgsComposerScaleBar::font(), QgsComposerItem::fontAscentMillimeters(), QgsComposerScaleBar::height(), QgsComposerScaleBar::labelBarSpace(), QgsScaleBarStyle::mScaleBar, QgsComposerScaleBar::pen(), and QgsComposerScaleBar::segmentPositions().
QString QgsDoubleBoxScaleBarStyle::name () const virtual
Implements QgsScaleBarStyle.
Definition at line 37 of file qgsdoubleboxscalebarstyle.cpp.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgsdoubleboxscalebarstyle.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgsdoubleboxscalebarstyle.cpp