QGIS API Documentation: QgsEllipseSymbolLayerV2 Class Reference
QgsEllipseSymbolLayerV2 Class Reference
A symbol layer for rendering objects with major and minor axis (e.g.
#include <qgsellipsesymbollayerv2.h>
Public Member Functions
QgsEllipseSymbolLayerV2 ()
~QgsEllipseSymbolLayerV2 ()
void renderPoint (const QPointF &point, QgsSymbolV2RenderContext &context)
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
QgsSymbolLayerV2 * clone () const
QgsStringMap properties () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
void writeSldMarker (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
void setSymbolName (const QString &name)
QString symbolName () const
void setSymbolWidth (double w)
double symbolWidth () const
void setSymbolHeight (double h)
double symbolHeight () const
Qt::PenStyle outlineStyle () const
void setOutlineStyle (Qt::PenStyle outlineStyle)
void setOutlineWidth (double w)
double outlineWidth () const
void setFillColor (const QColor &c)
Set fill color.
QColor fillColor () const
Get fill color.
void setOutlineColor (const QColor &c)
Set outline color.
QColor outlineColor () const
Get outline color.
void setSymbolWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit symbolWidthUnit () const
void setSymbolHeightUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit symbolHeightUnit () const
void setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outlineWidthUnit () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
Public Member Functions inherited from QgsMarkerSymbolLayerV2
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
void setSize (double size)
double size () const
void setScaleMethod (QgsSymbolV2::ScaleMethod scaleMethod)
QgsSymbolV2::ScaleMethod scaleMethod () const
void setOffset (QPointF offset)
QPointF offset ()
void setOffsetUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit offsetUnit () const
void setSizeUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit sizeUnit () const
void setHorizontalAnchorPoint (HorizontalAnchorPoint h)
HorizontalAnchorPoint horizontalAnchorPoint () const
void setVerticalAnchorPoint (VerticalAnchorPoint v)
VerticalAnchorPoint verticalAnchorPoint () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual ~QgsSymbolLayerV2 ()
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
virtual Qt::PenStyle dxfPenStyle () const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Private Member Functions
void preparePath (const QString &symbolName, QgsSymbolV2RenderContext &context, const QgsFeature *f=0)
Setup mPainterPath.
bool hasDataDefinedProperty () const
True if this symbol layer uses a data defined property.
Private Attributes
QString mSymbolName
double mSymbolWidth
QgsSymbolV2::OutputUnit mSymbolWidthUnit
double mSymbolHeight
QgsSymbolV2::OutputUnit mSymbolHeightUnit
QColor mFillColor
QColor mOutlineColor
Qt::PenStyle mOutlineStyle
double mOutlineWidth
QgsSymbolV2::OutputUnit mOutlineWidthUnit
QPainterPath mPainterPath
QPen mPen
QBrush mBrush
Additional Inherited Members
Public Types inherited from QgsMarkerSymbolLayerV2
enum HorizontalAnchorPoint { Left, HCenter, Right }
enum VerticalAnchorPoint { Top, VCenter, Bottom }
Protected Member Functions inherited from QgsMarkerSymbolLayerV2
QgsMarkerSymbolLayerV2 (bool locked=false)
void markerOffset (const QgsSymbolV2RenderContext &context, double &offsetX, double &offsetY) const
void markerOffset (const QgsSymbolV2RenderContext &context, double width, double height, QgsSymbolV2::OutputUnit widthUnit, QgsSymbolV2::OutputUnit heightUnit, double &offsetX, double &offsetY) const
Static Protected Member Functions inherited from QgsMarkerSymbolLayerV2
static QPointF _rotatedOffset (const QPointF &offset, double angle)
Protected Attributes inherited from QgsMarkerSymbolLayerV2
double mAngle
double mSize
QgsSymbolV2::OutputUnit mSizeUnit
QPointF mOffset
QgsSymbolV2::OutputUnit mOffsetUnit
QgsSymbolV2::ScaleMethod mScaleMethod
HorizontalAnchorPoint mHorizontalAnchorPoint
VerticalAnchorPoint mVerticalAnchorPoint
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
A symbol layer for rendering objects with major and minor axis (e.g.
ellipse, rectangle)
Definition at line 24 of file qgsellipsesymbollayerv2.h.
Constructor & Destructor Documentation
QgsEllipseSymbolLayerV2::QgsEllipseSymbolLayerV2 ()
Definition at line 28 of file qgsellipsesymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::mAngle, mBrush, mFillColor, QgsMarkerSymbolLayerV2::mOffset, mOutlineColor, mOutlineStyle, and mPen.
Referenced by create(), and createFromSld().
QgsEllipseSymbolLayerV2::~QgsEllipseSymbolLayerV2 ()
Definition at line 42 of file qgsellipsesymbollayerv2.cpp.
Member Function Documentation
QgsSymbolLayerV2 * QgsEllipseSymbolLayerV2::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 280 of file qgsellipsesymbollayerv2.cpp.
References create(), and properties().
QgsSymbolLayerV2 * QgsEllipseSymbolLayerV2::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 46 of file qgsellipsesymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::decodeColor(), QgsSymbolLayerV2Utils::decodeOutputUnit(), QgsSymbolLayerV2Utils::decodePenStyle(), QgsSymbolLayerV2Utils::decodePoint(), QgsEllipseSymbolLayerV2(), QgsMarkerSymbolLayerV2::setAngle(), QgsSymbolLayerV2::setDataDefinedProperty(), setFillColor(), QgsMarkerSymbolLayerV2::setHorizontalAnchorPoint(), QgsMarkerSymbolLayerV2::setOffset(), QgsMarkerSymbolLayerV2::setOffsetUnit(), setOutlineColor(), setOutlineStyle(), setOutlineWidth(), setOutlineWidthUnit(), setSymbolHeight(), setSymbolHeightUnit(), setSymbolName(), setSymbolWidth(), setSymbolWidthUnit(), and QgsMarkerSymbolLayerV2::setVerticalAnchorPoint().
Referenced by clone(), and QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsEllipseSymbolLayerV2::createFromSld (QDomElement & element) static
Definition at line 347 of file qgsellipsesymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), fillColor(), QgsSymbolLayerV2Utils::getVendorOptionList(), QgsDebugMsg, qgsDoubleNear(), QgsEllipseSymbolLayerV2(), QgsSymbolLayerV2Utils::rotationFromSldElement(), QgsMarkerSymbolLayerV2::setAngle(), setFillColor(), setOutlineColor(), setOutlineStyle(), setOutlineWidth(), setSymbolHeight(), setSymbolName(), setSymbolWidth(), QgsMarkerSymbolLayerV2::size(), and QgsSymbolLayerV2Utils::wellKnownMarkerFromSld().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QColor QgsEllipseSymbolLayerV2::fillColor () const inline virtual
Get fill color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 61 of file qgsellipsesymbollayerv2.h.
Referenced by createFromSld().
bool QgsEllipseSymbolLayerV2::hasDataDefinedProperty () const private
True if this symbol layer uses a data defined property.
Definition at line 420 of file qgsellipsesymbollayerv2.cpp.
References QgsSymbolLayerV2::dataDefinedProperty().
Referenced by startRender().
QString QgsEllipseSymbolLayerV2::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 258 of file qgsellipsesymbollayerv2.cpp.
QColor QgsEllipseSymbolLayerV2::outlineColor () const inline virtual
Get outline color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 64 of file qgsellipsesymbollayerv2.h.
Qt::PenStyle QgsEllipseSymbolLayerV2::outlineStyle () const inline
Definition at line 54 of file qgsellipsesymbollayerv2.h.
double QgsEllipseSymbolLayerV2::outlineWidth () const inline
Definition at line 58 of file qgsellipsesymbollayerv2.h.
Referenced by writeDxf().
QgsSymbolV2::OutputUnit QgsEllipseSymbolLayerV2::outlineWidthUnit () const inline
Definition at line 73 of file qgsellipsesymbollayerv2.h.
QgsSymbolV2::OutputUnit QgsEllipseSymbolLayerV2::outputUnit () const virtual
Reimplemented from QgsMarkerSymbolLayerV2.
Definition at line 496 of file qgsellipsesymbollayerv2.cpp.
References QgsSymbolV2::Mixed, mOutlineWidthUnit, mSymbolHeightUnit, and mSymbolWidthUnit.
void QgsEllipseSymbolLayerV2::preparePath (const QString & symbolName, QgsSymbolV2RenderContext & context, const QgsFeature * f = 0) private
Setup mPainterPath.
Parameters
symbolName name of symbol
context render context
f feature f to render (0 if no data defined rendering)
Definition at line 427 of file qgsellipsesymbollayerv2.cpp.
References QgsSymbolV2::DataDefinedSizeScale, QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mPainterPath, QgsMarkerSymbolLayerV2::mSize, mSymbolHeight, mSymbolHeightUnit, mSymbolWidth, mSymbolWidthUnit, QgsSymbolV2RenderContext::renderContext(), and QgsSymbolV2RenderContext::renderHints().
Referenced by renderPoint(), and startRender().
QgsStringMap QgsEllipseSymbolLayerV2::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 398 of file qgsellipsesymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeColor(), QgsSymbolLayerV2Utils::encodeOutputUnit(), QgsSymbolLayerV2Utils::encodePenStyle(), QgsSymbolLayerV2Utils::encodePoint(), QgsMarkerSymbolLayerV2::mAngle, mFillColor, QgsMarkerSymbolLayerV2::mHorizontalAnchorPoint, QgsMarkerSymbolLayerV2::mOffset, QgsMarkerSymbolLayerV2::mOffsetUnit, mOutlineColor, mOutlineStyle, mOutlineWidth, mOutlineWidthUnit, mSymbolHeight, mSymbolHeightUnit, mSymbolName, mSymbolWidth, mSymbolWidthUnit, QgsMarkerSymbolLayerV2::mVerticalAnchorPoint, and QgsSymbolLayerV2::saveDataDefinedProperties().
Referenced by clone().
void QgsEllipseSymbolLayerV2::renderPoint (const QPointF & point, QgsSymbolV2RenderContext & context) virtual
Implements QgsMarkerSymbolLayerV2.
Definition at line 185 of file qgsellipsesymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::_rotatedOffset(), QgsSymbolLayerV2Utils::decodeColor(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsMarkerSymbolLayerV2::mAngle, QgsMarkerSymbolLayerV2::markerOffset(), mBrush, mOutlineWidthUnit, mPainterPath, mPen, mSymbolHeight, mSymbolHeightUnit, mSymbolName, mSymbolWidth, mSymbolWidthUnit, QgsRenderContext::painter(), preparePath(), qgsDoubleNear(), QgsSymbolV2RenderContext::renderContext(), and symbolName().
void QgsEllipseSymbolLayerV2::setFillColor (const QColor & color) inline virtual
Set fill color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 60 of file qgsellipsesymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsEllipseSymbolLayerV2::setOutlineColor (const QColor & color) inline virtual
Set outline color.
Supported by marker and fill layers.
Note
added in 2.1
Reimplemented from QgsSymbolLayerV2.
Definition at line 63 of file qgsellipsesymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsEllipseSymbolLayerV2::setOutlineStyle (Qt::PenStyle outlineStyle) inline
Definition at line 55 of file qgsellipsesymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsEllipseSymbolLayerV2::setOutlineWidth (double w) inline
Definition at line 57 of file qgsellipsesymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsEllipseSymbolLayerV2::setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 72 of file qgsellipsesymbollayerv2.h.
Referenced by create().
void QgsEllipseSymbolLayerV2::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsMarkerSymbolLayerV2.
Definition at line 489 of file qgsellipsesymbollayerv2.cpp.
References mOutlineWidthUnit, mSymbolHeightUnit, and mSymbolWidthUnit.
void QgsEllipseSymbolLayerV2::setSymbolHeight (double h) inline
Definition at line 51 of file qgsellipsesymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsEllipseSymbolLayerV2::setSymbolHeightUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 69 of file qgsellipsesymbollayerv2.h.
Referenced by create().
void QgsEllipseSymbolLayerV2::setSymbolName (const QString & name) inline
Definition at line 45 of file qgsellipsesymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsEllipseSymbolLayerV2::setSymbolWidth (double w) inline
Definition at line 48 of file qgsellipsesymbollayerv2.h.
Referenced by create(), and createFromSld().
void QgsEllipseSymbolLayerV2::setSymbolWidthUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 66 of file qgsellipsesymbollayerv2.h.
Referenced by create().
void QgsEllipseSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) virtual
Reimplemented from QgsMarkerSymbolLayerV2.
Definition at line 263 of file qgsellipsesymbollayerv2.cpp.
References QgsSymbolV2RenderContext::feature(), hasDataDefinedProperty(), QgsSymbolV2RenderContext::layer(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mBrush, mFillColor, mOutlineColor, mOutlineStyle, mOutlineWidth, mOutlineWidthUnit, mPen, mSymbolName, QgsSymbolLayerV2::prepareExpressions(), preparePath(), QgsSymbolV2RenderContext::renderContext(), and QgsRenderContext::rendererScale().
void QgsEllipseSymbolLayerV2::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 276 of file qgsellipsesymbollayerv2.cpp.
double QgsEllipseSymbolLayerV2::symbolHeight () const inline
Definition at line 52 of file qgsellipsesymbollayerv2.h.
Referenced by writeDxf().
QgsSymbolV2::OutputUnit QgsEllipseSymbolLayerV2::symbolHeightUnit () const inline
Definition at line 70 of file qgsellipsesymbollayerv2.h.
QString QgsEllipseSymbolLayerV2::symbolName () const inline
Definition at line 46 of file qgsellipsesymbollayerv2.h.
Referenced by renderPoint(), and writeDxf().
double QgsEllipseSymbolLayerV2::symbolWidth () const inline
Definition at line 49 of file qgsellipsesymbollayerv2.h.
Referenced by writeDxf().
QgsSymbolV2::OutputUnit QgsEllipseSymbolLayerV2::symbolWidthUnit () const inline
Definition at line 67 of file qgsellipsesymbollayerv2.h.
void QgsEllipseSymbolLayerV2::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsMarkerSymbolLayerV2.
Definition at line 285 of file qgsellipsesymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::createGeometryElement(), and writeSldMarker().
bool QgsEllipseSymbolLayerV2::writeDxf (QgsDxfExport & e, double mmMapUnitScaleFactor, const QString & layerName, const QgsSymbolV2RenderContext * context, const QgsFeature * f, const QPointF & shift = QPointF(0.0, 0.0)) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 506 of file qgsellipsesymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::_rotatedOffset(), QgsSymbolV2::DataDefinedSizeScale, QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), QgsMarkerSymbolLayerV2::mAngle, QgsMarkerSymbolLayerV2::markerOffset(), mFillColor, QgsSymbolV2::MM, mOutlineWidth, mOutlineWidthUnit, QgsMarkerSymbolLayerV2::mSize, mSymbolHeight, mSymbolHeightUnit, mSymbolName, mSymbolWidth, mSymbolWidthUnit, outlineWidth(), qgsDoubleNear(), QgsSymbolV2RenderContext::renderHints(), symbolHeight(), symbolName(), and symbolWidth().
void QgsEllipseSymbolLayerV2::writeSldMarker (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsMarkerSymbolLayerV2.
Definition at line 298 of file qgsellipsesymbollayerv2.cpp.
References QgsMarkerSymbolLayerV2::angle(), QgsSymbolLayerV2Utils::createRotationElement(), QgsSymbolLayerV2Utils::createVendorOptionElement(), QgsSymbolLayerV2::dataDefinedProperty(), QgsExpression::expression(), QgsMarkerSymbolLayerV2::mAngle, mFillColor, mOutlineColor, mOutlineStyle, mOutlineWidth, mSymbolHeight, mSymbolName, mSymbolWidth, qgsDoubleNear(), and QgsSymbolLayerV2Utils::wellKnownMarkerToSld().
Referenced by toSld().
Member Data Documentation
QBrush QgsEllipseSymbolLayerV2::mBrush private
Definition at line 93 of file qgsellipsesymbollayerv2.h.
Referenced by QgsEllipseSymbolLayerV2(), renderPoint(), and startRender().
QColor QgsEllipseSymbolLayerV2::mFillColor private
Definition at line 84 of file qgsellipsesymbollayerv2.h.
Referenced by properties(), QgsEllipseSymbolLayerV2(), startRender(), writeDxf(), and writeSldMarker().
QColor QgsEllipseSymbolLayerV2::mOutlineColor private
Definition at line 85 of file qgsellipsesymbollayerv2.h.
Referenced by properties(), QgsEllipseSymbolLayerV2(), startRender(), and writeSldMarker().
Qt::PenStyle QgsEllipseSymbolLayerV2::mOutlineStyle private
Definition at line 86 of file qgsellipsesymbollayerv2.h.
Referenced by properties(), QgsEllipseSymbolLayerV2(), startRender(), and writeSldMarker().
double QgsEllipseSymbolLayerV2::mOutlineWidth private
Definition at line 87 of file qgsellipsesymbollayerv2.h.
Referenced by properties(), startRender(), writeDxf(), and writeSldMarker().
QgsSymbolV2::OutputUnit QgsEllipseSymbolLayerV2::mOutlineWidthUnit private
Definition at line 88 of file qgsellipsesymbollayerv2.h.
Referenced by outputUnit(), properties(), renderPoint(), setOutputUnit(), startRender(), and writeDxf().
QPainterPath QgsEllipseSymbolLayerV2::mPainterPath private
Definition at line 90 of file qgsellipsesymbollayerv2.h.
Referenced by preparePath(), and renderPoint().
QPen QgsEllipseSymbolLayerV2::mPen private
Definition at line 92 of file qgsellipsesymbollayerv2.h.
Referenced by QgsEllipseSymbolLayerV2(), renderPoint(), and startRender().
double QgsEllipseSymbolLayerV2::mSymbolHeight private
Definition at line 82 of file qgsellipsesymbollayerv2.h.
Referenced by preparePath(), properties(), renderPoint(), writeDxf(), and writeSldMarker().
QgsSymbolV2::OutputUnit QgsEllipseSymbolLayerV2::mSymbolHeightUnit private
Definition at line 83 of file qgsellipsesymbollayerv2.h.
Referenced by outputUnit(), preparePath(), properties(), renderPoint(), setOutputUnit(), and writeDxf().
QString QgsEllipseSymbolLayerV2::mSymbolName private
Definition at line 79 of file qgsellipsesymbollayerv2.h.
Referenced by properties(), renderPoint(), startRender(), writeDxf(), and writeSldMarker().
double QgsEllipseSymbolLayerV2::mSymbolWidth private
Definition at line 80 of file qgsellipsesymbollayerv2.h.
Referenced by preparePath(), properties(), renderPoint(), writeDxf(), and writeSldMarker().
QgsSymbolV2::OutputUnit QgsEllipseSymbolLayerV2::mSymbolWidthUnit private
Definition at line 81 of file qgsellipsesymbollayerv2.h.
Referenced by outputUnit(), preparePath(), properties(), renderPoint(), setOutputUnit(), and writeDxf().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsellipsesymbollayerv2.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsellipsesymbollayerv2.cpp