QGIS API Documentation: QgsRasterLayerSaveAsDialog Class Reference
QgsRasterLayerSaveAsDialog Class Reference
#include <qgsrasterlayersaveasdialog.h>
Public Types
enum Mode { RawDataMode, RenderedImageMode }
enum CrsState { OriginalCrs, CurrentCrs, UserCrs }
enum ExtentState { OriginalExtent, CurrentExtent, UserExtent }
enum ResolutionState { OriginalResolution, UserResolution }
Public Slots
virtual void accept ()
Public Member Functions
QgsRasterLayerSaveAsDialog (QgsRasterLayer *rasterLayer, QgsRasterDataProvider *sourceProvider, const QgsRectangle &currentExtent, const QgsCoordinateReferenceSystem &layerCrs, const QgsCoordinateReferenceSystem &currentCrs, QWidget *parent=0, Qt::WindowFlags f=0)
~QgsRasterLayerSaveAsDialog ()
Mode mode () const
int nColumns () const
int nRows () const
double xResolution () const
double yResolution () const
int maximumTileSizeX () const
int maximumTileSizeY () const
bool tileMode () const
QString outputFileName () const
QString outputFormat () const
QgsCoordinateReferenceSystem outputCrs ()
QStringList createOptions () const
QgsRectangle outputRectangle () const
QgsRasterRangeList noData () const
QList< int > pyramidsList () const
QgsRaster::RasterBuildPyramids buildPyramidsFlag () const
QString pyramidsResamplingMethod () const
QgsRaster::RasterPyramidsFormat pyramidsFormat () const
QStringList pyramidsConfigOptions () const
void hideFormat ()
void hideOutput ()
Private Slots
void on_mRawModeRadioButton_toggled (bool)
void on_mBrowseButton_clicked ()
void on_mSaveAsLineEdit_textChanged (const QString &text)
void on_mCurrentExtentButton_clicked ()
void on_mOriginalExtentButton_clicked ()
void on_mFormatComboBox_currentIndexChanged (const QString &text)
void on_mResolutionRadioButton_toggled (bool)
void on_mOriginalResolutionPushButton_clicked ()
void on_mXResolutionLineEdit_textEdited (const QString &)
void on_mYResolutionLineEdit_textEdited (const QString &)
void on_mOriginalSizePushButton_clicked ()
void on_mColumnsLineEdit_textEdited (const QString &)
void on_mRowsLineEdit_textEdited (const QString &)
void on_mXMinLineEdit_textEdited (const QString &)
void on_mXMaxLineEdit_textEdited (const QString &)
void on_mYMinLineEdit_textEdited (const QString &)
void on_mYMaxLineEdit_textEdited (const QString &)
void on_mChangeCrsPushButton_clicked ()
void on_mCrsComboBox_currentIndexChanged (int)
void on_mAddNoDataManuallyToolButton_clicked ()
void on_mLoadTransparentNoDataToolButton_clicked ()
void on_mRemoveSelectedNoDataToolButton_clicked ()
void on_mRemoveAllNoDataToolButton_clicked ()
void noDataCellTextEdited (const QString &text)
void on_mTileModeCheckBox_toggled (bool toggled)
void on_mPyramidsGroupBox_toggled (bool toggled)
void populatePyramidsLevels ()
Private Member Functions
void setValidators ()
void setOutputExtent (const QgsRectangle &r, const QgsCoordinateReferenceSystem &srcCrs, ExtentState state)
void extentChanged ()
void updateExtentStateMsg ()
void toggleResolutionSize ()
void setResolution (double xRes, double yRes, const QgsCoordinateReferenceSystem &srcCrs)
void setOriginalResolution ()
void setOriginalSize ()
void recalcSize ()
void recalcResolution ()
void updateResolutionStateMsg ()
void recalcResolutionSize ()
void crsChanged ()
void updateCrsGroup ()
void addNoDataRow (double min, double max)
void setNoDataToEdited (int row)
double noDataCellValue (int row, int column) const
void adjustNoDataCellWidth (int row, int column)
bool validate () const
Private Attributes
QgsRasterLayer * mRasterLayer
QgsRasterDataProvider * mDataProvider
QgsRectangle mCurrentExtent
QgsCoordinateReferenceSystem mLayerCrs
QgsCoordinateReferenceSystem mCurrentCrs
QgsCoordinateReferenceSystem mUserCrs
QgsCoordinateReferenceSystem mPreviousCrs
ExtentState mExtentState
ResolutionState mResolutionState
QVector< bool > mNoDataToEdited
Detailed Description
Definition at line 27 of file qgsrasterlayersaveasdialog.h.
Member Enumeration Documentation
enum QgsRasterLayerSaveAsDialog::CrsState
Enumerator:
OriginalCrs
CurrentCrs
UserCrs
Definition at line 36 of file qgsrasterlayersaveasdialog.h.
enum QgsRasterLayerSaveAsDialog::ExtentState
Enumerator:
OriginalExtent
CurrentExtent
UserExtent
Definition at line 42 of file qgsrasterlayersaveasdialog.h.
enum QgsRasterLayerSaveAsDialog::Mode
Enumerator:
RawDataMode
RenderedImageMode
Definition at line 31 of file qgsrasterlayersaveasdialog.h.
enum QgsRasterLayerSaveAsDialog::ResolutionState
Enumerator:
OriginalResolution
UserResolution
Definition at line 48 of file qgsrasterlayersaveasdialog.h.
Constructor & Destructor Documentation
QgsRasterLayerSaveAsDialog::QgsRasterLayerSaveAsDialog (QgsRasterLayer * rasterLayer, QgsRasterDataProvider * sourceProvider, const QgsRectangle & currentExtent, const QgsCoordinateReferenceSystem & layerCrs, const QgsCoordinateReferenceSystem & currentCrs, QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 28 of file qgsrasterlayersaveasdialog.cpp.
References QgsRasterInterface::BuildPyramids, QgsRasterInterface::capabilities(), QgsCoordinateReferenceSystem::createFromOgcWmsCrs(), CurrentCrs, QgsRasterDataProvider::extent(), QgsApplication::getThemeIcon(), mDataProvider, mLayerCrs, mRasterLayer, mUserCrs, QgsDataProvider::name(), on_mRawModeRadioButton_toggled(), OriginalCrs, OriginalExtent, populatePyramidsLevels(), setOriginalResolution(), setOutputExtent(), setValidators(), QgsRasterInterface::Size, toggleResolutionSize(), tr, updateCrsGroup(), UserCrs, QgsRasterInterface::xSize(), and QgsRasterInterface::ySize().
QgsRasterLayerSaveAsDialog::~QgsRasterLayerSaveAsDialog ()
Definition at line 152 of file qgsrasterlayersaveasdialog.cpp.
Member Function Documentation
virtual void QgsRasterLayerSaveAsDialog::accept () inline virtual slot
Definition at line 85 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::addNoDataRow (double min, double max) private
Definition at line 624 of file qgsrasterlayersaveasdialog.cpp.
References adjustNoDataCellWidth(), QgsRasterLayer::dataProvider(), QGis::Float32, QGis::Float64, MathUtils::max(), mRasterLayer, noDataCellTextEdited(), QgsRasterBlock::printValue(), and QgsRasterDataProvider::srcDataType().
Referenced by on_mAddNoDataManuallyToolButton_clicked(), and on_mLoadTransparentNoDataToolButton_clicked().
void QgsRasterLayerSaveAsDialog::adjustNoDataCellWidth (int row, int column) private
Definition at line 789 of file qgsrasterlayersaveasdialog.cpp.
Referenced by addNoDataRow().
QgsRaster::RasterBuildPyramids QgsRasterLayerSaveAsDialog::buildPyramidsFlag () const
Definition at line 820 of file qgsrasterlayersaveasdialog.cpp.
References QgsRaster::PyramidsCopyExisting, QgsRaster::PyramidsFlagNo, and QgsRaster::PyramidsFlagYes.
QStringList QgsRasterLayerSaveAsDialog::createOptions () const
Definition at line 286 of file qgsrasterlayersaveasdialog.cpp.
void QgsRasterLayerSaveAsDialog::crsChanged () private
Definition at line 498 of file qgsrasterlayersaveasdialog.cpp.
References CurrentExtent, QgsRasterDataProvider::extent(), mCurrentCrs, mCurrentExtent, mDataProvider, mExtentState, mLayerCrs, mPreviousCrs, mResolutionState, OriginalExtent, OriginalResolution, outputCrs(), outputRectangle(), QgsDebugMsg, recalcResolution(), setOriginalResolution(), setOutputExtent(), setResolution(), updateCrsGroup(), xResolution(), and yResolution().
Referenced by on_mChangeCrsPushButton_clicked().
void QgsRasterLayerSaveAsDialog::extentChanged () private
Definition at line 452 of file qgsrasterlayersaveasdialog.cpp.
References mResolutionState, recalcResolutionSize(), updateExtentStateMsg(), and UserResolution.
Referenced by setOutputExtent().
void QgsRasterLayerSaveAsDialog::hideFormat ()
Definition at line 318 of file qgsrasterlayersaveasdialog.cpp.
void QgsRasterLayerSaveAsDialog::hideOutput ()
Definition at line 324 of file qgsrasterlayersaveasdialog.cpp.
int QgsRasterLayerSaveAsDialog::maximumTileSizeX () const
Definition at line 261 of file qgsrasterlayersaveasdialog.cpp.
int QgsRasterLayerSaveAsDialog::maximumTileSizeY () const
Definition at line 266 of file qgsrasterlayersaveasdialog.cpp.
QgsRasterLayerSaveAsDialog::Mode QgsRasterLayerSaveAsDialog::mode () const
Definition at line 576 of file qgsrasterlayersaveasdialog.cpp.
References RawDataMode, and RenderedImageMode.
int QgsRasterLayerSaveAsDialog::nColumns () const
Definition at line 241 of file qgsrasterlayersaveasdialog.cpp.
Referenced by recalcResolution().
QgsRasterRangeList QgsRasterLayerSaveAsDialog::noData () const
Definition at line 800 of file qgsrasterlayersaveasdialog.cpp.
References noDataCellValue().
void QgsRasterLayerSaveAsDialog::noDataCellTextEdited (const QString & text) private slot
Definition at line 663 of file qgsrasterlayersaveasdialog.cpp.
References mNoDataToEdited, QgsDebugMsg, and setNoDataToEdited().
Referenced by addNoDataRow().
double QgsRasterLayerSaveAsDialog::noDataCellValue (int row, int column) const private
Definition at line 779 of file qgsrasterlayersaveasdialog.cpp.
Referenced by noData().
int QgsRasterLayerSaveAsDialog::nRows () const
Definition at line 246 of file qgsrasterlayersaveasdialog.cpp.
Referenced by recalcResolution().
void QgsRasterLayerSaveAsDialog::on_mAddNoDataManuallyToolButton_clicked () private slot
Definition at line 587 of file qgsrasterlayersaveasdialog.cpp.
References addNoDataRow().
void QgsRasterLayerSaveAsDialog::on_mBrowseButton_clicked () private slot
Definition at line 156 of file qgsrasterlayersaveasdialog.cpp.
References tr.
void QgsRasterLayerSaveAsDialog::on_mChangeCrsPushButton_clicked () private slot
Definition at line 484 of file qgsrasterlayersaveasdialog.cpp.
References QgsCoordinateReferenceSystem::createFromId(), crsChanged(), QgsCoordinateReferenceSystem::InternalCrsId, mUserCrs, QgsGenericProjectionSelector::selectedCrsId(), QgsGenericProjectionSelector::setMessage(), QgsGenericProjectionSelector::setSelectedCrsId(), QgsCoordinateReferenceSystem::srsid(), and UserCrs.
void QgsRasterLayerSaveAsDialog::on_mColumnsLineEdit_textEdited (const QString &) inline private slot
Definition at line 100 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mCrsComboBox_currentIndexChanged (int) inline private slot
Definition at line 110 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mCurrentExtentButton_clicked () private slot
Definition at line 218 of file qgsrasterlayersaveasdialog.cpp.
References CurrentExtent, mCurrentCrs, mCurrentExtent, and setOutputExtent().
void QgsRasterLayerSaveAsDialog::on_mFormatComboBox_currentIndexChanged (const QString & text) private slot
Definition at line 231 of file qgsrasterlayersaveasdialog.cpp.
References mDataProvider, and QgsDataProvider::name().
void QgsRasterLayerSaveAsDialog::on_mLoadTransparentNoDataToolButton_clicked () private slot
Definition at line 592 of file qgsrasterlayersaveasdialog.cpp.
References addNoDataRow(), QgsRasterTransparency::TransparentSingleValuePixel::max, QgsRasterTransparency::TransparentSingleValuePixel::min, mRasterLayer, QgsRasterTransparency::TransparentSingleValuePixel::percentTransparent, QgsRasterRenderer::rasterTransparency(), QgsRasterLayer::renderer(), setNoDataToEdited(), and QgsRasterTransparency::transparentSingleValuePixelList().
void QgsRasterLayerSaveAsDialog::on_mOriginalExtentButton_clicked () private slot
Definition at line 223 of file qgsrasterlayersaveasdialog.cpp.
References QgsRasterDataProvider::extent(), mDataProvider, mLayerCrs, OriginalExtent, and setOutputExtent().
void QgsRasterLayerSaveAsDialog::on_mOriginalResolutionPushButton_clicked () inline private slot
Definition at line 95 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mOriginalSizePushButton_clicked () inline private slot
Definition at line 99 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mPyramidsGroupBox_toggled (bool toggled) private slot
Definition at line 730 of file qgsrasterlayersaveasdialog.cpp.
References populatePyramidsLevels().
void QgsRasterLayerSaveAsDialog::on_mRawModeRadioButton_toggled (bool checked) private slot
Definition at line 582 of file qgsrasterlayersaveasdialog.cpp.
References QgsRasterInterface::bandCount(), and mDataProvider.
Referenced by QgsRasterLayerSaveAsDialog().
void QgsRasterLayerSaveAsDialog::on_mRemoveAllNoDataToolButton_clicked () private slot
Definition at line 616 of file qgsrasterlayersaveasdialog.cpp.
void QgsRasterLayerSaveAsDialog::on_mRemoveSelectedNoDataToolButton_clicked () private slot
Definition at line 611 of file qgsrasterlayersaveasdialog.cpp.
void QgsRasterLayerSaveAsDialog::on_mResolutionRadioButton_toggled (bool) inline private slot
Definition at line 94 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mRowsLineEdit_textEdited (const QString &) inline private slot
Definition at line 101 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mSaveAsLineEdit_textChanged (const QString & text) private slot
Definition at line 207 of file qgsrasterlayersaveasdialog.cpp.
void QgsRasterLayerSaveAsDialog::on_mTileModeCheckBox_toggled (bool toggled) private slot
Definition at line 703 of file qgsrasterlayersaveasdialog.cpp.
void QgsRasterLayerSaveAsDialog::on_mXMaxLineEdit_textEdited (const QString &) inline private slot
Definition at line 104 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mXMinLineEdit_textEdited (const QString &) inline private slot
Definition at line 103 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mXResolutionLineEdit_textEdited (const QString &) inline private slot
Definition at line 96 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mYMaxLineEdit_textEdited (const QString &) inline private slot
Definition at line 106 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mYMinLineEdit_textEdited (const QString &) inline private slot
Definition at line 105 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::on_mYResolutionLineEdit_textEdited (const QString &) inline private slot
Definition at line 97 of file qgsrasterlayersaveasdialog.h.
QgsCoordinateReferenceSystem QgsRasterLayerSaveAsDialog::outputCrs ()
Definition at line 562 of file qgsrasterlayersaveasdialog.cpp.
References CurrentCrs, mCurrentCrs, mLayerCrs, mUserCrs, and OriginalCrs.
Referenced by crsChanged(), setOutputExtent(), and setResolution().
QString QgsRasterLayerSaveAsDialog::outputFileName () const
Definition at line 276 of file qgsrasterlayersaveasdialog.cpp.
QString QgsRasterLayerSaveAsDialog::outputFormat () const
Definition at line 281 of file qgsrasterlayersaveasdialog.cpp.
QgsRectangle QgsRasterLayerSaveAsDialog::outputRectangle () const
Definition at line 291 of file qgsrasterlayersaveasdialog.cpp.
Referenced by crsChanged(), recalcResolution(), recalcSize(), and setResolution().
void QgsRasterLayerSaveAsDialog::populatePyramidsLevels () private slot
Definition at line 736 of file qgsrasterlayersaveasdialog.cpp.
References QgsRasterDataProvider::buildPyramidList(), and mDataProvider.
Referenced by on_mPyramidsGroupBox_toggled(), and QgsRasterLayerSaveAsDialog().
QStringList QgsRasterLayerSaveAsDialog::pyramidsConfigOptions () const inline
Definition at line 79 of file qgsrasterlayersaveasdialog.h.
QgsRaster::RasterPyramidsFormat QgsRasterLayerSaveAsDialog::pyramidsFormat () const inline
Definition at line 78 of file qgsrasterlayersaveasdialog.h.
QList< int > QgsRasterLayerSaveAsDialog::pyramidsList () const
Definition at line 815 of file qgsrasterlayersaveasdialog.cpp.
QString QgsRasterLayerSaveAsDialog::pyramidsResamplingMethod () const inline
Definition at line 77 of file qgsrasterlayersaveasdialog.h.
void QgsRasterLayerSaveAsDialog::recalcResolution () private
Definition at line 409 of file qgsrasterlayersaveasdialog.cpp.
References QgsRectangle::height(), nColumns(), nRows(), outputRectangle(), QgsDebugMsg, updateResolutionStateMsg(), and QgsRectangle::width().
Referenced by crsChanged(), recalcResolutionSize(), and setOriginalSize().
void QgsRasterLayerSaveAsDialog::recalcResolutionSize () private
Definition at line 420 of file qgsrasterlayersaveasdialog.cpp.
References mResolutionState, QgsDebugMsg, recalcResolution(), recalcSize(), and UserResolution.
Referenced by extentChanged().
void QgsRasterLayerSaveAsDialog::recalcSize () private
Definition at line 391 of file qgsrasterlayersaveasdialog.cpp.
References QgsRectangle::height(), outputRectangle(), QgsDebugMsg, updateResolutionStateMsg(), QgsRectangle::width(), xResolution(), and yResolution().
Referenced by recalcResolutionSize(), and setOriginalResolution().
void QgsRasterLayerSaveAsDialog::setNoDataToEdited (int row) private
Definition at line 770 of file qgsrasterlayersaveasdialog.cpp.
References mNoDataToEdited.
Referenced by noDataCellTextEdited(), and on_mLoadTransparentNoDataToolButton_clicked().
void QgsRasterLayerSaveAsDialog::setOriginalResolution () private
Definition at line 349 of file qgsrasterlayersaveasdialog.cpp.
References QgsRasterInterface::capabilities(), QgsRasterDataProvider::extent(), QgsRectangle::height(), mDataProvider, mLayerCrs, mResolutionState, OriginalResolution, recalcSize(), setResolution(), QgsRasterInterface::Size, QgsRectangle::width(), QgsRasterInterface::xSize(), and QgsRasterInterface::ySize().
Referenced by crsChanged(), and QgsRasterLayerSaveAsDialog().
void QgsRasterLayerSaveAsDialog::setOriginalSize () private
Definition at line 402 of file qgsrasterlayersaveasdialog.cpp.
References mDataProvider, recalcResolution(), QgsRasterInterface::xSize(), and QgsRasterInterface::ySize().
void QgsRasterLayerSaveAsDialog::setOutputExtent (const QgsRectangle & r, const QgsCoordinateReferenceSystem & srcCrs, ExtentState state) private
Definition at line 296 of file qgsrasterlayersaveasdialog.cpp.
References extentChanged(), mExtentState, outputCrs(), QgsRasterBlock::printValue(), QgsCoordinateTransform::transformBoundingBox(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by crsChanged(), on_mCurrentExtentButton_clicked(), on_mOriginalExtentButton_clicked(), and QgsRasterLayerSaveAsDialog().
void QgsRasterLayerSaveAsDialog::setResolution (double xRes, double yRes, const QgsCoordinateReferenceSystem & srcCrs) private
Definition at line 368 of file qgsrasterlayersaveasdialog.cpp.
References QgsRectangle::center(), outputCrs(), outputRectangle(), QgsCoordinateTransform::ReverseTransform, QgsCoordinateTransform::transform(), QgsPoint::x(), and QgsPoint::y().
Referenced by crsChanged(), and setOriginalResolution().
void QgsRasterLayerSaveAsDialog::setValidators () private
Definition at line 138 of file qgsrasterlayersaveasdialog.cpp.
Referenced by QgsRasterLayerSaveAsDialog().
bool QgsRasterLayerSaveAsDialog::tileMode () const
Definition at line 271 of file qgsrasterlayersaveasdialog.cpp.
void QgsRasterLayerSaveAsDialog::toggleResolutionSize () private
Definition at line 336 of file qgsrasterlayersaveasdialog.cpp.
References QgsRasterInterface::capabilities(), mDataProvider, and QgsRasterInterface::Size.
Referenced by QgsRasterLayerSaveAsDialog().
void QgsRasterLayerSaveAsDialog::updateCrsGroup () private
Definition at line 548 of file qgsrasterlayersaveasdialog.cpp.
References QgsCoordinateReferenceSystem::authid(), CurrentCrs, QgsCoordinateReferenceSystem::description(), mCurrentCrs, mLayerCrs, mUserCrs, OriginalCrs, QgsDebugMsg, tr, and UserCrs.
Referenced by crsChanged(), and QgsRasterLayerSaveAsDialog().
void QgsRasterLayerSaveAsDialog::updateExtentStateMsg () private
Definition at line 463 of file qgsrasterlayersaveasdialog.cpp.
References CurrentExtent, mExtentState, OriginalExtent, tr, and UserExtent.
Referenced by extentChanged().
void QgsRasterLayerSaveAsDialog::updateResolutionStateMsg () private
Definition at line 434 of file qgsrasterlayersaveasdialog.cpp.
References mResolutionState, OriginalResolution, tr, and UserResolution.
Referenced by recalcResolution(), and recalcSize().
bool QgsRasterLayerSaveAsDialog::validate () const private
Definition at line 830 of file qgsrasterlayersaveasdialog.cpp.
double QgsRasterLayerSaveAsDialog::xResolution () const
Definition at line 251 of file qgsrasterlayersaveasdialog.cpp.
Referenced by crsChanged(), and recalcSize().
double QgsRasterLayerSaveAsDialog::yResolution () const
Definition at line 256 of file qgsrasterlayersaveasdialog.cpp.
Referenced by crsChanged(), and recalcSize().
Member Data Documentation
QgsCoordinateReferenceSystem QgsRasterLayerSaveAsDialog::mCurrentCrs private
Definition at line 126 of file qgsrasterlayersaveasdialog.h.
Referenced by crsChanged(), on_mCurrentExtentButton_clicked(), outputCrs(), and updateCrsGroup().
QgsRectangle QgsRasterLayerSaveAsDialog::mCurrentExtent private
Definition at line 124 of file qgsrasterlayersaveasdialog.h.
Referenced by crsChanged(), and on_mCurrentExtentButton_clicked().
QgsRasterDataProvider* QgsRasterLayerSaveAsDialog::mDataProvider private
Definition at line 123 of file qgsrasterlayersaveasdialog.h.
Referenced by crsChanged(), on_mFormatComboBox_currentIndexChanged(), on_mOriginalExtentButton_clicked(), on_mRawModeRadioButton_toggled(), populatePyramidsLevels(), QgsRasterLayerSaveAsDialog(), setOriginalResolution(), setOriginalSize(), and toggleResolutionSize().
ExtentState QgsRasterLayerSaveAsDialog::mExtentState private
Definition at line 129 of file qgsrasterlayersaveasdialog.h.
Referenced by crsChanged(), setOutputExtent(), and updateExtentStateMsg().
QgsCoordinateReferenceSystem QgsRasterLayerSaveAsDialog::mLayerCrs private
Definition at line 125 of file qgsrasterlayersaveasdialog.h.
Referenced by crsChanged(), on_mOriginalExtentButton_clicked(), outputCrs(), QgsRasterLayerSaveAsDialog(), setOriginalResolution(), and updateCrsGroup().
QVector<bool> QgsRasterLayerSaveAsDialog::mNoDataToEdited private
Definition at line 131 of file qgsrasterlayersaveasdialog.h.
Referenced by noDataCellTextEdited(), and setNoDataToEdited().
QgsCoordinateReferenceSystem QgsRasterLayerSaveAsDialog::mPreviousCrs private
Definition at line 128 of file qgsrasterlayersaveasdialog.h.
Referenced by crsChanged().
QgsRasterLayer* QgsRasterLayerSaveAsDialog::mRasterLayer private
Definition at line 122 of file qgsrasterlayersaveasdialog.h.
Referenced by addNoDataRow(), on_mLoadTransparentNoDataToolButton_clicked(), and QgsRasterLayerSaveAsDialog().
ResolutionState QgsRasterLayerSaveAsDialog::mResolutionState private
Definition at line 130 of file qgsrasterlayersaveasdialog.h.
Referenced by crsChanged(), extentChanged(), recalcResolutionSize(), setOriginalResolution(), and updateResolutionStateMsg().
QgsCoordinateReferenceSystem QgsRasterLayerSaveAsDialog::mUserCrs private
Definition at line 127 of file qgsrasterlayersaveasdialog.h.
Referenced by on_mChangeCrsPushButton_clicked(), outputCrs(), QgsRasterLayerSaveAsDialog(), and updateCrsGroup().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsrasterlayersaveasdialog.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsrasterlayersaveasdialog.cpp