QGIS API Documentation: QgsGpsdConnection Class Reference
QgsGpsdConnection Class Reference
Evaluates NMEA sentences coming from gpsd.
#include <qgsgpsdconnection.h>
Public Member Functions
QgsGpsdConnection (QString host, qint16 port, QString device)
~QgsGpsdConnection ()
Public Member Functions inherited from QgsNMEAConnection
QgsNMEAConnection (QIODevice *dev)
~QgsNMEAConnection ()
Public Member Functions inherited from QgsGPSConnection
QgsGPSConnection (QIODevice *dev)
Constructor.
virtual ~QgsGPSConnection ()
bool connect ()
Opens connection to device.
bool close ()
Closes connection to device.
void setSource (QIODevice *source)
Sets the GPS source.
Status status () const
Returns the status.
QgsGPSInformation currentGPSInformation () const
Returns the current gps information (lat, lon, etc.)
Private Slots
void connected ()
void error (QAbstractSocket::SocketError)
Private Attributes
QString mDevice
Additional Inherited Members
Public Types inherited from QgsGPSConnection
enum Status { NotConnected, Connected, DataReceived, GPSDataReceived }
Signals inherited from QgsGPSConnection
void stateChanged (const QgsGPSInformation &info)
void nmeaSentenceReceived (const QString &substring)
Protected Slots inherited from QgsNMEAConnection
void parseData ()
Parse available data source content.
Protected Member Functions inherited from QgsNMEAConnection
void processStringBuffer ()
Splits mStringBuffer into sentences and calls libnmea.
void processGGASentence (const char *data, int len)
void processRMCSentence (const char *data, int len)
void processGSVSentence (const char *data, int len)
void processVTGSentence (const char *data, int len)
void processGSASentence (const char *data, int len)
Protected Attributes inherited from QgsNMEAConnection
QString mStringBuffer
Store data from the device before it is processed.
Detailed Description
Evaluates NMEA sentences coming from gpsd.
Definition at line 26 of file qgsgpsdconnection.h.
Constructor & Destructor Documentation
QgsGpsdConnection::QgsGpsdConnection (QString host, qint16 port, QString device)
Definition at line 23 of file qgsgpsdconnection.cpp.
References QgsGPSConnection::connect(), connected(), error(), and QgsGPSConnection::mSource.
QgsGpsdConnection::~QgsGpsdConnection ()
Definition at line 34 of file qgsgpsdconnection.cpp.
References QgsDebugMsg.
Member Function Documentation
void QgsGpsdConnection::connected () private slot
Definition at line 40 of file qgsgpsdconnection.cpp.
References mDevice, QgsGPSConnection::mSource, and QgsDebugMsg.
Referenced by QgsGpsdConnection().
void QgsGpsdConnection::error (QAbstractSocket::SocketError socketError) private slot
Definition at line 47 of file qgsgpsdconnection.cpp.
References QgsGPSConnection::mSource, and QgsDebugMsg.
Referenced by QgsGpsdConnection().
Member Data Documentation
QString QgsGpsdConnection::mDevice private
Definition at line 38 of file qgsgpsdconnection.h.
Referenced by connected().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/gps/qgsgpsdconnection.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/gps/qgsgpsdconnection.cpp