QGIS API Documentation: QgsPaperGrid Class Reference
QgsPaperGrid Class Reference
Item representing a grid.
#include <qgspaperitem.h>
Public Member Functions
QgsPaperGrid (double x, double y, double width, double height, QgsComposition *composition)
~QgsPaperGrid ()
void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint.
Private Attributes
QgsComposition * mComposition
Detailed Description
Item representing a grid.
This is drawn separately to the underlying paper item since the grid needs to be drawn above all other composer items, while the paper item is drawn below all others.
Definition at line 26 of file qgspaperitem.h.
Constructor & Destructor Documentation
QgsPaperGrid::QgsPaperGrid (double x, double y, double width, double height, QgsComposition * composition)
Definition at line 27 of file qgspaperitem.cpp.
QgsPaperGrid::~QgsPaperGrid ()
Definition at line 35 of file qgspaperitem.cpp.
Member Function Documentation
void QgsPaperGrid::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget)
Reimplementation of QCanvasItem::paint.
Definition at line 39 of file qgspaperitem.cpp.
References QgsComposition::Crosses, QgsComposition::Dots, QgsComposition::gridPen(), QgsComposition::gridStyle(), QgsComposition::gridVisible(), mComposition, QgsComposition::plotStyle(), QgsComposition::Preview, QgsComposition::snapGridOffsetX(), QgsComposition::snapGridOffsetY(), QgsComposition::snapGridResolution(), and QgsComposition::Solid.
Member Data Documentation
QgsComposition* QgsPaperGrid::mComposition private
Definition at line 36 of file qgspaperitem.h.
Referenced by paint().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgspaperitem.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgspaperitem.cpp