QGIS API Documentation: QgsFileDropEdit Class Reference
QgsFileDropEdit Class Reference
QGIS gui library.
A line edit for capturing file names that can have files dropped onto it via drag & drop.
#include <qgsfiledropedit.h>
Public Member Functions
QgsFileDropEdit (QWidget *parent=0)
virtual ~QgsFileDropEdit ()
bool isDirOnly () const
void setDirOnly (bool isDirOnly)
bool isFileOnly () const
void setFileOnly (bool isFileOnly)
const QString & suffixFilter () const
void setSuffixFilter (const QString &suffix)
Protected Member Functions
virtual void dragEnterEvent (QDragEnterEvent *event)
virtual void dragLeaveEvent (QDragLeaveEvent *event)
virtual void dropEvent (QDropEvent *event)
virtual void paintEvent (QPaintEvent *e)
Private Member Functions
QString acceptableFilePath (QDropEvent *event) const
Private Attributes
QString mSuffix
bool mDirOnly
bool mFileOnly
bool mDragActive
Detailed Description
A line edit for capturing file names that can have files dropped onto it via drag & drop.
The QgsDropNameEdit class provides a line edit widget which accepts file drops.
Dropping can be limited to files only, files with a specific extension or directories only. By default, dropping is limited to files only.
Definition at line 24 of file qgsfiledropedit.h.
Constructor & Destructor Documentation
QgsFileDropEdit::QgsFileDropEdit (QWidget * parent = 0)
Definition at line 32 of file qgsfiledropedit.cpp.
References mDirOnly, mDragActive, and mFileOnly.
QgsFileDropEdit::~QgsFileDropEdit () virtual
Definition at line 41 of file qgsfiledropedit.cpp.
Member Function Documentation
QString QgsFileDropEdit::acceptableFilePath (QDropEvent * event) const private
Return file name if object meets drop criteria.
Definition at line 79 of file qgsfiledropedit.cpp.
References file, mDirOnly, mFileOnly, and mSuffix.
Referenced by dragEnterEvent(), and dropEvent().
void QgsFileDropEdit::dragEnterEvent (QDragEnterEvent * event) protected virtual
Check if dragged object is acceptible. Called when a drag is in progress and the mouse enters this widget.
Definition at line 97 of file qgsfiledropedit.cpp.
References acceptableFilePath(), and mDragActive.
void QgsFileDropEdit::dragLeaveEvent (QDragLeaveEvent * event) protected virtual
Called when a drag is in progress and the mouse leaves this widget.
Definition at line 115 of file qgsfiledropedit.cpp.
References mDragActive.
void QgsFileDropEdit::dropEvent (QDropEvent * event) protected virtual
Receive the dragged object. Called when the drag is dropped on this widget.
Definition at line 126 of file qgsfiledropedit.cpp.
References acceptableFilePath(), and mDragActive.
bool QgsFileDropEdit::isDirOnly () const inline
Definition at line 30 of file qgsfiledropedit.h.
Referenced by setDirOnly().
bool QgsFileDropEdit::isFileOnly () const inline
Definition at line 33 of file qgsfiledropedit.h.
Referenced by setFileOnly().
void QgsFileDropEdit::paintEvent (QPaintEvent * e) protected virtual
Paints line edit with drag highlight in response to a paint event.
Definition at line 147 of file qgsfiledropedit.cpp.
References mDragActive.
void QgsFileDropEdit::setDirOnly (bool isDirOnly)
Limit drops to directories.
Definition at line 47 of file qgsfiledropedit.cpp.
References isDirOnly(), mDirOnly, and mFileOnly.
void QgsFileDropEdit::setFileOnly (bool isFileOnly)
Limit drops to files.
Definition at line 59 of file qgsfiledropedit.cpp.
References isFileOnly(), mDirOnly, and mFileOnly.
void QgsFileDropEdit::setSuffixFilter (const QString & suffix)
Limit drops to files with specified extension.
Definition at line 71 of file qgsfiledropedit.cpp.
References mSuffix.
const QString& QgsFileDropEdit::suffixFilter () const inline
Definition at line 36 of file qgsfiledropedit.h.
Member Data Documentation
bool QgsFileDropEdit::mDirOnly private
Definition at line 50 of file qgsfiledropedit.h.
Referenced by acceptableFilePath(), QgsFileDropEdit(), setDirOnly(), and setFileOnly().
bool QgsFileDropEdit::mDragActive private
Definition at line 52 of file qgsfiledropedit.h.
Referenced by dragEnterEvent(), dragLeaveEvent(), dropEvent(), paintEvent(), and QgsFileDropEdit().
bool QgsFileDropEdit::mFileOnly private
Definition at line 51 of file qgsfiledropedit.h.
Referenced by acceptableFilePath(), QgsFileDropEdit(), setDirOnly(), and setFileOnly().
QString QgsFileDropEdit::mSuffix private
Definition at line 49 of file qgsfiledropedit.h.
Referenced by acceptableFilePath(), and setSuffixFilter().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsfiledropedit.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsfiledropedit.cpp