QGIS API Documentation: QgsComposerSymbolV2Item Class Reference
QgsComposerSymbolV2Item Class Reference
#include <qgscomposerlegenditem.h>
Public Member Functions
QgsComposerSymbolV2Item ()
QgsComposerSymbolV2Item (const QString &text)
QgsComposerSymbolV2Item (const QIcon &icon, const QString &text)
virtual ~QgsComposerSymbolV2Item ()
virtual QStandardItem * clone () const
virtual void writeXML (QDomElement &elem, QDomDocument &doc) const
virtual void readXML (const QDomElement &itemElem, bool xServerAvailable=true)
Read item content from xml.
void setSymbolV2 (QgsSymbolV2 *s)
Set symbol (takes ownership)
QgsSymbolV2 * symbolV2 ()
ItemType itemType () const
Public Member Functions inherited from QgsComposerLegendItem
QgsComposerLegendItem (QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
QgsComposerLegendItem (const QString &text, QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
QgsComposerLegendItem (const QIcon &icon, const QString &text, QgsComposerLegendStyle::Style s=QgsComposerLegendStyle::Undefined)
virtual ~QgsComposerLegendItem ()
QgsComposerLegendStyle::Style style () const
void setStyle (QgsComposerLegendStyle::Style style)
virtual QString userText () const
virtual void setUserText (const QString &text)
Private Attributes
QgsSymbolV2 * mSymbolV2
Additional Inherited Members
Public Types inherited from QgsComposerLegendItem
enum ItemType {
GroupItem = QStandardItem::UserType, LayerItem, SymbologyV2Item, RasterSymbolItem,
StyleItem
}
Protected Member Functions inherited from QgsComposerLegendItem
void writeXMLChildren (QDomElement &elem, QDomDocument &doc) const
Protected Attributes inherited from QgsComposerLegendItem
QgsComposerLegendStyle::Style mStyle
QString mUserText
Detailed Description
Definition at line 74 of file qgscomposerlegenditem.h.
Constructor & Destructor Documentation
QgsComposerSymbolV2Item::QgsComposerSymbolV2Item ()
Definition at line 69 of file qgscomposerlegenditem.cpp.
Referenced by clone().
QgsComposerSymbolV2Item::QgsComposerSymbolV2Item (const QString & text)
Definition at line 73 of file qgscomposerlegenditem.cpp.
QgsComposerSymbolV2Item::QgsComposerSymbolV2Item (const QIcon & icon, const QString & text)
Definition at line 77 of file qgscomposerlegenditem.cpp.
QgsComposerSymbolV2Item::~QgsComposerSymbolV2Item () virtual
Definition at line 81 of file qgscomposerlegenditem.cpp.
References mSymbolV2.
Member Function Documentation
QStandardItem * QgsComposerSymbolV2Item::clone () const virtual
Implements QgsComposerLegendItem.
Definition at line 86 of file qgscomposerlegenditem.cpp.
References QgsSymbolV2::clone(), mSymbolV2, QgsComposerSymbolV2Item(), and setSymbolV2().
ItemType QgsComposerSymbolV2Item::itemType () const inline virtual
Implements QgsComposerLegendItem.
Definition at line 91 of file qgscomposerlegenditem.h.
References QgsComposerLegendItem::SymbologyV2Item.
void QgsComposerSymbolV2Item::readXML (const QDomElement & itemElem, bool xServerAvailable = true) virtual
Read item content from xml.
Parameters
itemElem item to read from
xServerAvailable Read item icons if true (QIcon needs x-server)
Implements QgsComposerLegendItem.
Definition at line 112 of file qgscomposerlegenditem.cpp.
References QgsSymbolLayerV2Utils::loadSymbols(), setSymbolV2(), QgsComposerLegendItem::setUserText(), and QgsSymbolLayerV2Utils::symbolPreviewIcon().
void QgsComposerSymbolV2Item::setSymbolV2 (QgsSymbolV2 * s)
Set symbol (takes ownership)
Definition at line 142 of file qgscomposerlegenditem.cpp.
References mSymbolV2.
Referenced by QgsLegendModel::addVectorLayerItemsV2(), clone(), and readXML().
QgsSymbolV2* QgsComposerSymbolV2Item::symbolV2 () inline
Definition at line 89 of file qgscomposerlegenditem.h.
Referenced by QgsComposerLegend::drawSymbolItem().
void QgsComposerSymbolV2Item::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
Implements QgsComposerLegendItem.
Definition at line 97 of file qgscomposerlegenditem.cpp.
References mSymbolV2, QgsSymbolLayerV2Utils::saveSymbols(), and QgsComposerLegendItem::userText().
Member Data Documentation
QgsSymbolV2* QgsComposerSymbolV2Item::mSymbolV2 private
Definition at line 94 of file qgscomposerlegenditem.h.
Referenced by clone(), setSymbolV2(), writeXML(), and ~QgsComposerSymbolV2Item().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgscomposerlegenditem.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgscomposerlegenditem.cpp