QGIS API Documentation: QgsCentroidFillSymbolLayerV2 Class Reference
QgsCentroidFillSymbolLayerV2 Class Reference
#include <qgsfillsymbollayerv2.h>
Public Member Functions
QgsCentroidFillSymbolLayerV2 ()
~QgsCentroidFillSymbolLayerV2 ()
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
void renderPolygon (const QPolygonF &points, QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
void setColor (const QColor &color)
QgsSymbolV2 * subSymbol ()
bool setSubSymbol (QgsSymbolV2 *symbol)
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
virtual QSet< QString > usedAttributes () const
Public Member Functions inherited from QgsFillSymbolLayerV2
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
virtual Qt::PenStyle dxfPenStyle () const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Protected Attributes
QgsMarkerSymbolV2 * mMarker
Protected Attributes inherited from QgsFillSymbolLayerV2
double mAngle
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Additional Inherited Members
Protected Member Functions inherited from QgsFillSymbolLayerV2
QgsFillSymbolLayerV2 (bool locked=false)
void _renderPolygon (QPainter *p, const QPolygonF &points, const QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
Default method to render polygon.
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 539 of file qgsfillsymbollayerv2.h.
Constructor & Destructor Documentation
QgsCentroidFillSymbolLayerV2::QgsCentroidFillSymbolLayerV2 ()
Definition at line 2347 of file qgsfillsymbollayerv2.cpp.
References setSubSymbol().
Referenced by clone(), create(), and createFromSld().
QgsCentroidFillSymbolLayerV2::~QgsCentroidFillSymbolLayerV2 ()
Definition at line 2352 of file qgsfillsymbollayerv2.cpp.
References mMarker.
Member Function Documentation
QgsSymbolLayerV2 * QgsCentroidFillSymbolLayerV2::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2398 of file qgsfillsymbollayerv2.cpp.
References QgsMarkerSymbolV2::clone(), mMarker, QgsCentroidFillSymbolLayerV2(), and setSubSymbol().
QgsSymbolLayerV2 * QgsCentroidFillSymbolLayerV2::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 2357 of file qgsfillsymbollayerv2.cpp.
References QgsCentroidFillSymbolLayerV2().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsCentroidFillSymbolLayerV2::createFromSld (QDomElement & element) static
Definition at line 2413 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::createMarkerLayerFromSld(), QgsCentroidFillSymbolLayerV2(), QgsDebugMsg, and setSubSymbol().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QString QgsCentroidFillSymbolLayerV2::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2363 of file qgsfillsymbollayerv2.cpp.
QgsSymbolV2::OutputUnit QgsCentroidFillSymbolLayerV2::outputUnit () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2462 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2::Mixed, mMarker, and QgsSymbolV2::outputUnit().
QgsStringMap QgsCentroidFillSymbolLayerV2::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2393 of file qgsfillsymbollayerv2.cpp.
void QgsCentroidFillSymbolLayerV2::renderPolygon (const QPolygonF & points, QList< QPolygonF > * rings, QgsSymbolV2RenderContext & context) virtual
Implements QgsFillSymbolLayerV2.
Definition at line 2385 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2RenderContext::feature(), mMarker, QgsSymbolLayerV2Utils::polygonCentroid(), QgsSymbolV2RenderContext::renderContext(), QgsMarkerSymbolV2::renderPoint(), and QgsSymbolV2RenderContext::selected().
void QgsCentroidFillSymbolLayerV2::setColor (const QColor & color) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2368 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolLayerV2::color(), QgsSymbolLayerV2::mColor, mMarker, and QgsSymbolV2::setColor().
void QgsCentroidFillSymbolLayerV2::setOutputUnit (QgsSymbolV2::OutputUnit unit) inline virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 571 of file qgsfillsymbollayerv2.h.
bool QgsCentroidFillSymbolLayerV2::setSubSymbol (QgsSymbolV2 * symbol) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2436 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2::color(), QgsSymbolV2::Marker, QgsSymbolLayerV2::mColor, mMarker, and QgsSymbolV2::type().
Referenced by clone(), createFromSld(), and QgsCentroidFillSymbolLayerV2().
void QgsCentroidFillSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 2374 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2RenderContext::alpha(), mMarker, QgsSymbolV2RenderContext::renderContext(), QgsSymbolV2::setAlpha(), and QgsSymbolV2::startRender().
void QgsCentroidFillSymbolLayerV2::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 2380 of file qgsfillsymbollayerv2.cpp.
References mMarker, QgsSymbolV2RenderContext::renderContext(), and QgsSymbolV2::stopRender().
QgsSymbolV2 * QgsCentroidFillSymbolLayerV2::subSymbol () virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2431 of file qgsfillsymbollayerv2.cpp.
References mMarker.
void QgsCentroidFillSymbolLayerV2::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2405 of file qgsfillsymbollayerv2.cpp.
References mMarker, and QgsSymbolV2::toSld().
QSet< QString > QgsCentroidFillSymbolLayerV2::usedAttributes () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2450 of file qgsfillsymbollayerv2.cpp.
References mMarker, QgsSymbolLayerV2::usedAttributes(), and QgsSymbolV2::usedAttributes().
Member Data Documentation
QgsMarkerSymbolV2* QgsCentroidFillSymbolLayerV2::mMarker protected
Definition at line 577 of file qgsfillsymbollayerv2.h.
Referenced by clone(), outputUnit(), renderPolygon(), setColor(), setSubSymbol(), startRender(), stopRender(), subSymbol(), toSld(), usedAttributes(), and ~QgsCentroidFillSymbolLayerV2().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsfillsymbollayerv2.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsfillsymbollayerv2.cpp