QGIS API Documentation: QgsComposerAttributeTable Class Reference
QgsComposerAttributeTable Class Reference
A table class that displays a vector attribute table.
#include <qgscomposerattributetable.h>
Signals
void maximumNumberOfFeaturesChanged (int n)
This signal is emitted if the maximum number of feature changes (interactively)
Public Member Functions
QgsComposerAttributeTable (QgsComposition *composition)
~QgsComposerAttributeTable ()
virtual int type () const
return correct graphics item type.
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint.
bool writeXML (QDomElement &elem, QDomDocument &doc) const
stores state in Dom element
bool readXML (const QDomElement &itemElem, const QDomDocument &doc)
sets state from Dom document
void setVectorLayer (QgsVectorLayer *vl)
const QgsVectorLayer * vectorLayer () const
void setComposerMap (const QgsComposerMap *map)
const QgsComposerMap * composerMap () const
void setMaximumNumberOfFeatures (int nr)
int maximumNumberOfFeatures () const
void setDisplayOnlyVisibleFeatures (bool b)
bool displayOnlyVisibleFeatures () const
QSet< int > displayAttributes () const
void setDisplayAttributes (const QSet< int > &attr)
QMap< int, QString > fieldAliasMap () const
void setFieldAliasMap (const QMap< int, QString > &map)
void setSceneRect (const QRectF &rectangle)
Adapts mMaximumNumberOfFeatures depending on the rectangle height.
void setSortAttributes (const QList< QPair< int, bool > > att)
QList< QPair< int, bool > > sortAttributes () const
Public Member Functions inherited from QgsComposerTable
QgsComposerTable (QgsComposition *composition)
virtual ~QgsComposerTable ()
void setLineTextDistance (double d)
double lineTextDistance () const
void setHeaderFont (const QFont &f)
QFont headerFont () const
void setContentFont (const QFont &f)
QFont contentFont () const
void setShowGrid (bool show)
bool showGrid () const
void setGridStrokeWidth (double w)
double gridStrokeWidth () const
void setGridColor (const QColor &c)
QColor gridColor () const
void adjustFrameToSize ()
Adapts the size of the frame to match the content.
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected () const
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft, bool posIncludesFrame=false)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
virtual void setFrameOutlineWidth (double outlineWidth)
Sets frame outline width.
virtual double estimatedFrameBleed () const
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
virtual QRectF rectWithFrame () const
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
double itemRotation () const
Returns the rotation for the composer item.
double rotation () const
Returns the rotation for the composer item.
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
Protected Member Functions
bool getFeatureAttributes (QList< QgsAttributeMap > &attributeMaps)
Retrieves feature attributes.
QMap< int, QString > getHeaderLabels () const
Protected Member Functions inherited from QgsComposerTable
virtual bool calculateMaxColumnWidths (QMap< int, double > &maxWidthMap, const QList< QgsAttributeMap > &attributeMaps) const
Calculate the maximum width values of the vector attributes.
void adaptItemFrame (const QMap< int, double > &maxWidthMap, const QList< QgsAttributeMap > &attributeMaps)
Adapts the size of the item frame to match the content.
void drawHorizontalGridLines (QPainter *p, int nAttributes)
void drawVerticalGridLines (QPainter *p, const QMap< int, double > &maxWidthMap)
bool tableWriteXML (QDomElement &itemElem, QDomDocument &doc) const
bool tableReadXML (const QDomElement &itemElem, const QDomDocument &doc)
Protected Member Functions inherited from QgsComposerItem
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height, double rotation) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
QRectF largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height, double rotation) const
Calculates corner point after rotation and scaling.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height, double rotation)
Calculates width / height of the bounding box of a rotated rectangle.
void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Private Slots
void removeLayer (QString layerId)
Checks if this vector layer will be removed (and sets mVectorLayer to 0 if yes)
Private Member Functions
void initializeAliasMap ()
Inserts aliases from vector layer as starting configuration to the alias map.
QString attributeDisplayName (int attributeIndex, const QString &name) const
Returns the attribute name to display in the item (attribute name or an alias if present)
Private Attributes
QgsVectorLayer * mVectorLayer
Associated vector layer.
const QgsComposerMap * mComposerMap
Associated composer map (used to display the visible features)
int mMaximumNumberOfFeatures
Maximum number of features that is displayed.
bool mShowOnlyVisibleFeatures
Shows only the features that are visible in the associated composer map (true by default)
QSet< int > mDisplayAttributes
List of attribute indices to display (or all attributes if list is empty)
QMap< int, QString > mFieldAliasMap
Map of attribute name aliases.
QList< QPair< int, bool > > mSortInformation
Contains information about sort attribute index / ascending (true/false).
Additional Inherited Members
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
Sets the item rotation.
virtual void setItemRotation (double r, bool adjustPosition=false)
Sets the item rotation.
void repaint ()
Protected Attributes inherited from QgsComposerTable
double mLineTextDistance
Distance between table lines and text.
QFont mHeaderFont
QFont mContentFont
bool mShowGrid
double mGridStrokeWidth
QColor mGridColor
Detailed Description
A table class that displays a vector attribute table.
Definition at line 40 of file qgscomposerattributetable.h.
Constructor & Destructor Documentation
QgsComposerAttributeTable::QgsComposerAttributeTable (QgsComposition * composition)
Definition at line 47 of file qgscomposerattributetable.cpp.
References QgsMapLayerRegistry::instance(), QgsMapLayerRegistry::mapLayers(), mVectorLayer, and removeLayer().
QgsComposerAttributeTable::~QgsComposerAttributeTable ()
Definition at line 69 of file qgscomposerattributetable.cpp.
Member Function Documentation
QString QgsComposerAttributeTable::attributeDisplayName (int attributeIndex, const QString & name) const private
Returns the attribute name to display in the item (attribute name or an alias if present)
Definition at line 209 of file qgscomposerattributetable.cpp.
References mFieldAliasMap.
Referenced by getHeaderLabels().
const QgsComposerMap* QgsComposerAttributeTable::composerMap () const inline
Definition at line 60 of file qgscomposerattributetable.h.
QSet<int> QgsComposerAttributeTable::displayAttributes () const inline
Definition at line 68 of file qgscomposerattributetable.h.
bool QgsComposerAttributeTable::displayOnlyVisibleFeatures () const inline
Definition at line 66 of file qgscomposerattributetable.h.
QMap<int, QString> QgsComposerAttributeTable::fieldAliasMap () const inline
Definition at line 71 of file qgscomposerattributetable.h.
bool QgsComposerAttributeTable::getFeatureAttributes (QList< QgsAttributeMap > & attributeMaps) protected virtual
Retrieves feature attributes.
Note
not available in python bindings
Reimplemented from QgsComposerTable.
Definition at line 122 of file qgscomposerattributetable.cpp.
References QgsFeature::attributes(), QgsMapLayer::crs(), QgsComposerMap::currentMapExtent(), QgsMapRenderer::destinationCrs(), QgsFeatureRequest::ExactIntersect, QgsVectorLayer::getFeatures(), QgsMapRenderer::hasCrsTransformEnabled(), QgsRectangle::isEmpty(), QgsComposerMap::mapRenderer(), mComposerMap, mDisplayAttributes, mMaximumNumberOfFeatures, mShowOnlyVisibleFeatures, mSortInformation, mVectorLayer, QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, QgsCoordinateTransform::ReverseTransform, QgsComposerAttributeTableCompare::setAscending(), QgsFeatureRequest::setFilterRect(), QgsFeatureRequest::setFlags(), QgsComposerAttributeTableCompare::setSortColumn(), and QgsFeatureRequest::setSubsetOfAttributes().
QMap< int, QString > QgsComposerAttributeTable::getHeaderLabels () const protected virtual
Note
not available in python bindings
Reimplemented from QgsComposerTable.
Definition at line 191 of file qgscomposerattributetable.cpp.
References attributeDisplayName(), QgsFields::count(), mDisplayAttributes, mVectorLayer, and QgsVectorLayer::pendingFields().
void QgsComposerAttributeTable::initializeAliasMap () private
Inserts aliases from vector layer as starting configuration to the alias map.
Definition at line 82 of file qgscomposerattributetable.cpp.
References QgsVectorLayer::attributeAlias(), QgsFields::count(), mFieldAliasMap, mVectorLayer, and QgsVectorLayer::pendingFields().
Referenced by setVectorLayer().
int QgsComposerAttributeTable::maximumNumberOfFeatures () const inline
Definition at line 63 of file qgscomposerattributetable.h.
void QgsComposerAttributeTable::maximumNumberOfFeaturesChanged (int n) signal
This signal is emitted if the maximum number of feature changes (interactively)
Referenced by setSceneRect().
void QgsComposerAttributeTable::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget) virtual
Reimplementation of QCanvasItem::paint.
Reimplemented from QgsComposerTable.
Definition at line 73 of file qgscomposerattributetable.cpp.
References QgsComposerMap::isDrawing(), and mComposerMap.
bool QgsComposerAttributeTable::readXML (const QDomElement & itemElem, const QDomDocument & doc) virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is Dom document
Implements QgsComposerTable.
Definition at line 299 of file qgscomposerattributetable.cpp.
References QgsComposerItem::composition(), QgsComposition::getComposerMapById(), index, QgsMapLayerRegistry::instance(), QgsComposerItem::itemChanged(), QgsMapLayerRegistry::mapLayer(), mComposerMap, mDisplayAttributes, mFieldAliasMap, mMaximumNumberOfFeatures, mShowOnlyVisibleFeatures, mSortInformation, mVectorLayer, and QgsComposerTable::tableReadXML().
Referenced by QgsComposition::addItemsFromXML().
void QgsComposerAttributeTable::removeLayer (QString layerId) private slot
Checks if this vector layer will be removed (and sets mVectorLayer to 0 if yes)
Definition at line 214 of file qgscomposerattributetable.cpp.
References QgsMapLayer::id(), and mVectorLayer.
Referenced by QgsComposerAttributeTable().
void QgsComposerAttributeTable::setComposerMap (const QgsComposerMap * map)
Definition at line 109 of file qgscomposerattributetable.cpp.
References mComposerMap, and QgsComposerItem::repaint().
void QgsComposerAttributeTable::setDisplayAttributes (const QSet< int > & attr) inline
Definition at line 69 of file qgscomposerattributetable.h.
void QgsComposerAttributeTable::setDisplayOnlyVisibleFeatures (bool b) inline
Definition at line 65 of file qgscomposerattributetable.h.
void QgsComposerAttributeTable::setFieldAliasMap (const QMap< int, QString > & map) inline
Definition at line 72 of file qgscomposerattributetable.h.
void QgsComposerAttributeTable::setMaximumNumberOfFeatures (int nr) inline
Definition at line 62 of file qgscomposerattributetable.h.
void QgsComposerAttributeTable::setSceneRect (const QRectF & rectangle) virtual
Adapts mMaximumNumberOfFeatures depending on the rectangle height.
Reimplemented from QgsComposerItem.
Definition at line 225 of file qgscomposerattributetable.cpp.
References QgsComposerItem::fontAscentMillimeters(), maximumNumberOfFeaturesChanged(), QgsComposerTable::mContentFont, QgsComposerTable::mGridStrokeWidth, QgsComposerTable::mHeaderFont, QgsComposerTable::mLineTextDistance, and mMaximumNumberOfFeatures.
Referenced by QgsComposerView::mousePressEvent().
void QgsComposerAttributeTable::setSortAttributes (const QList< QPair< int, bool > > att) inline
Definition at line 78 of file qgscomposerattributetable.h.
void QgsComposerAttributeTable::setVectorLayer (QgsVectorLayer * vl)
Definition at line 99 of file qgscomposerattributetable.cpp.
References initializeAliasMap(), mDisplayAttributes, and mVectorLayer.
QList<QPair<int, bool> > QgsComposerAttributeTable::sortAttributes () const inline
Definition at line 81 of file qgscomposerattributetable.h.
virtual int QgsComposerAttributeTable::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerTable.
Definition at line 48 of file qgscomposerattributetable.h.
References QgsComposerItem::ComposerAttributeTable.
const QgsVectorLayer* QgsComposerAttributeTable::vectorLayer () const inline
Definition at line 57 of file qgscomposerattributetable.h.
bool QgsComposerAttributeTable::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
stores state in Dom element
Parameters
elem is Dom element corresponding to 'Composer' tag
doc is the Dom document
Implements QgsComposerTable.
Definition at line 241 of file qgscomposerattributetable.cpp.
References QgsMapLayer::id(), QgsComposerMap::id(), mComposerMap, mDisplayAttributes, mFieldAliasMap, mMaximumNumberOfFeatures, mShowOnlyVisibleFeatures, mSortInformation, mVectorLayer, and QgsComposerTable::tableWriteXML().
Member Data Documentation
const QgsComposerMap* QgsComposerAttributeTable::mComposerMap private
Associated composer map (used to display the visible features)
Definition at line 96 of file qgscomposerattributetable.h.
Referenced by getFeatureAttributes(), paint(), readXML(), setComposerMap(), and writeXML().
QSet<int> QgsComposerAttributeTable::mDisplayAttributes private
List of attribute indices to display (or all attributes if list is empty)
Definition at line 104 of file qgscomposerattributetable.h.
Referenced by getFeatureAttributes(), getHeaderLabels(), readXML(), setVectorLayer(), and writeXML().
QMap<int, QString> QgsComposerAttributeTable::mFieldAliasMap private
Map of attribute name aliases.
The aliases might be different to those of QgsVectorLayer (but those from the vector layer are the default)
Definition at line 106 of file qgscomposerattributetable.h.
Referenced by attributeDisplayName(), initializeAliasMap(), readXML(), and writeXML().
int QgsComposerAttributeTable::mMaximumNumberOfFeatures private
Maximum number of features that is displayed.
Definition at line 98 of file qgscomposerattributetable.h.
Referenced by getFeatureAttributes(), readXML(), setSceneRect(), and writeXML().
bool QgsComposerAttributeTable::mShowOnlyVisibleFeatures private
Shows only the features that are visible in the associated composer map (true by default)
Definition at line 101 of file qgscomposerattributetable.h.
Referenced by getFeatureAttributes(), readXML(), and writeXML().
QList< QPair<int, bool> > QgsComposerAttributeTable::mSortInformation private
Contains information about sort attribute index / ascending (true/false).
First entry has the highest priority
Definition at line 109 of file qgscomposerattributetable.h.
Referenced by getFeatureAttributes(), readXML(), and writeXML().
QgsVectorLayer* QgsComposerAttributeTable::mVectorLayer private
Associated vector layer.
Definition at line 94 of file qgscomposerattributetable.h.
Referenced by getFeatureAttributes(), getHeaderLabels(), initializeAliasMap(), QgsComposerAttributeTable(), readXML(), removeLayer(), setVectorLayer(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgscomposerattributetable.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgscomposerattributetable.cpp