QGIS API Documentation: QgsRasterCalcNode Class Reference
QgsRasterCalcNode Class Reference
#include <qgsrastercalcnode.h>
Public Types
enum Type { tOperator = 1, tNumber, tRasterRef }
defines possible types of node
enum Operator {
opPLUS, opMINUS, opMUL, opDIV,
opPOW, opSQRT, opSIN, opCOS,
opTAN, opASIN, opACOS, opATAN,
opEQ, opNE, opGT, opLT,
opGE, opLE, opAND, opOR,
opSIGN
}
possible operators
Public Member Functions
QgsRasterCalcNode ()
QgsRasterCalcNode (double number)
QgsRasterCalcNode (Operator op, QgsRasterCalcNode *left, QgsRasterCalcNode *right)
QgsRasterCalcNode (const QString &rasterName)
~QgsRasterCalcNode ()
Type type () const
void setLeft (QgsRasterCalcNode *left)
void setRight (QgsRasterCalcNode *right)
bool calculate (QMap< QString, QgsRasterMatrix * > &rasterData, QgsRasterMatrix &result) const
Calculates result (might be real matrix or single number)
Static Public Member Functions
static QgsRasterCalcNode * parseRasterCalcString (const QString &str, QString &parserErrorMsg)
Private Attributes
Type mType
QgsRasterCalcNode * mLeft
QgsRasterCalcNode * mRight
double mNumber
QString mRasterName
Operator mOperator
Detailed Description
Definition at line 26 of file qgsrastercalcnode.h.
Member Enumeration Documentation
enum QgsRasterCalcNode::Operator
possible operators
Enumerator:
opPLUS
opMINUS
opMUL
opDIV
opPOW
opSQRT
opSIN
opCOS
opTAN
opASIN
opACOS
opATAN
opEQ
opNE
opGT
=
opLT
opGE
opLE
opAND
opOR
opSIGN
Definition at line 38 of file qgsrastercalcnode.h.
enum QgsRasterCalcNode::Type
defines possible types of node
Enumerator:
tOperator
tNumber
tRasterRef
Definition at line 30 of file qgsrastercalcnode.h.
Constructor & Destructor Documentation
QgsRasterCalcNode::QgsRasterCalcNode ()
Definition at line 18 of file qgsrastercalcnode.cpp.
QgsRasterCalcNode::QgsRasterCalcNode (double number)
Definition at line 25 of file qgsrastercalcnode.cpp.
QgsRasterCalcNode::QgsRasterCalcNode (Operator op, QgsRasterCalcNode * left, QgsRasterCalcNode * right)
Definition at line 33 of file qgsrastercalcnode.cpp.
QgsRasterCalcNode::QgsRasterCalcNode (const QString & rasterName)
Definition at line 42 of file qgsrastercalcnode.cpp.
QgsRasterCalcNode::~QgsRasterCalcNode ()
Definition at line 51 of file qgsrastercalcnode.cpp.
References mLeft, and mRight.
Member Function Documentation
bool QgsRasterCalcNode::calculate (QMap< QString, QgsRasterMatrix * > & rasterData, QgsRasterMatrix & result) const
Calculates result (might be real matrix or single number)
Definition at line 63 of file qgsrastercalcnode.cpp.
References QgsRasterMatrix::acosinus(), QgsRasterMatrix::add(), QgsRasterMatrix::asinus(), QgsRasterMatrix::atangens(), calculate(), QgsRasterMatrix::changeSign(), QgsRasterMatrix::cosinus(), QgsRasterMatrix::divide(), QgsRasterMatrix::equal(), QgsRasterMatrix::greaterEqual(), QgsRasterMatrix::greaterThan(), QgsRasterMatrix::lesserEqual(), QgsRasterMatrix::lesserThan(), QgsRasterMatrix::logicalAnd(), QgsRasterMatrix::logicalOr(), mLeft, mNumber, mOperator, mRasterName, mRight, mType, QgsRasterMatrix::multiply(), QgsRasterMatrix::nColumns(), QgsRasterMatrix::nodataValue(), QgsRasterMatrix::notEqual(), QgsRasterMatrix::nRows(), opACOS, opAND, opASIN, opATAN, opCOS, opDIV, opEQ, opGE, opGT, opLE, opLT, opMINUS, opMUL, opNE, opOR, opPLUS, opPOW, opSIGN, opSIN, opSQRT, opTAN, QgsRasterMatrix::power(), QgsRasterMatrix::setData(), QgsRasterMatrix::sinus(), QgsRasterMatrix::squareRoot(), QgsRasterMatrix::subtract(), QgsRasterMatrix::takeData(), QgsRasterMatrix::tangens(), tNumber, tOperator, and tRasterRef.
Referenced by calculate(), and QgsRasterCalculator::processCalculation().
QgsRasterCalcNode * QgsRasterCalcNode::parseRasterCalcString (const QString & str, QString & parserErrorMsg) static
Definition at line 177 of file qgsrastercalcnode.cpp.
Referenced by QgsRasterCalculator::processCalculation().
void QgsRasterCalcNode::setLeft (QgsRasterCalcNode * left) inline
Definition at line 72 of file qgsrastercalcnode.h.
void QgsRasterCalcNode::setRight (QgsRasterCalcNode * right) inline
Definition at line 73 of file qgsrastercalcnode.h.
Type QgsRasterCalcNode::type () const inline
Definition at line 69 of file qgsrastercalcnode.h.
Member Data Documentation
QgsRasterCalcNode* QgsRasterCalcNode::mLeft private
Definition at line 82 of file qgsrastercalcnode.h.
Referenced by calculate(), and ~QgsRasterCalcNode().
double QgsRasterCalcNode::mNumber private
Definition at line 84 of file qgsrastercalcnode.h.
Referenced by calculate().
Operator QgsRasterCalcNode::mOperator private
Definition at line 86 of file qgsrastercalcnode.h.
Referenced by calculate().
QString QgsRasterCalcNode::mRasterName private
Definition at line 85 of file qgsrastercalcnode.h.
Referenced by calculate().
QgsRasterCalcNode* QgsRasterCalcNode::mRight private
Definition at line 83 of file qgsrastercalcnode.h.
Referenced by calculate(), and ~QgsRasterCalcNode().
Type QgsRasterCalcNode::mType private
Definition at line 81 of file qgsrastercalcnode.h.
Referenced by calculate().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/analysis/raster/qgsrastercalcnode.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/analysis/raster/qgsrastercalcnode.cpp