QGIS API Documentation: QgsRasterMinMaxWidget Class Reference
QgsRasterMinMaxWidget Class Reference
#include <qgsrasterminmaxwidget.h>
Signals
void load (int theBandNo, double theMin, double theMax, int origin)
Public Member Functions
QgsRasterMinMaxWidget (QgsRasterLayer *theLayer, QWidget *parent=0)
~QgsRasterMinMaxWidget ()
void setExtent (const QgsRectangle &theExtent)
void setBands (const QList< int > &theBands)
void load ()
Private Slots
void on_mLoadPushButton_clicked ()
Private Attributes
QgsRasterLayer * mLayer
QList< int > mBands
QgsRectangle mExtent
Detailed Description
Definition at line 25 of file qgsrasterminmaxwidget.h.
Constructor & Destructor Documentation
QgsRasterMinMaxWidget::QgsRasterMinMaxWidget (QgsRasterLayer * theLayer, QWidget * parent = 0)
Definition at line 23 of file qgsrasterminmaxwidget.cpp.
References QgsRasterLayer::CUMULATIVE_CUT_LOWER, QgsRasterLayer::CUMULATIVE_CUT_UPPER, and QgsDebugMsg.
QgsRasterMinMaxWidget::~QgsRasterMinMaxWidget ()
Definition at line 37 of file qgsrasterminmaxwidget.cpp.
Member Function Documentation
void QgsRasterMinMaxWidget::load () inline
Definition at line 37 of file qgsrasterminmaxwidget.h.
Referenced by on_mLoadPushButton_clicked(), and QgsSingleBandPseudoColorRendererWidget::QgsSingleBandPseudoColorRendererWidget().
void QgsRasterMinMaxWidget::load (int theBandNo, double theMin, double theMax, int origin) signal
void QgsRasterMinMaxWidget::on_mLoadPushButton_clicked () private slot
Definition at line 41 of file qgsrasterminmaxwidget.cpp.
References QgsRasterInterface::bandCount(), QgsRasterInterface::bandStatistics(), QgsRasterInterface::cumulativeCut(), QgsRasterLayer::dataProvider(), QgsRectangle::isEmpty(), load(), QgsRasterBandStats::Max, QgsRasterBandStats::maximumValue, mBands, QgsRasterBandStats::Mean, QgsRasterBandStats::mean, mExtent, QgsRasterBandStats::Min, QgsRasterBandStats::minimumValue, QgsRasterRenderer::MinMaxCumulativeCut, QgsRasterRenderer::MinMaxEstimated, QgsRasterRenderer::MinMaxExact, QgsRasterRenderer::MinMaxFullExtent, QgsRasterRenderer::MinMaxMinMax, QgsRasterRenderer::MinMaxStdDev, QgsRasterRenderer::MinMaxSubExtent, QgsRasterRenderer::MinMaxUnknown, mLayer, QgsDebugMsg, QgsRasterBandStats::StdDev, and QgsRasterBandStats::stdDev.
void QgsRasterMinMaxWidget::setBands (const QList< int > & theBands) inline
Definition at line 34 of file qgsrasterminmaxwidget.h.
Referenced by QgsSingleBandPseudoColorRendererWidget::on_mBandComboBox_currentIndexChanged(), QgsSingleBandGrayRendererWidget::on_mGrayBandComboBox_currentIndexChanged(), and QgsMultiBandColorRendererWidget::onBandChanged().
void QgsRasterMinMaxWidget::setExtent (const QgsRectangle & theExtent) inline
Definition at line 32 of file qgsrasterminmaxwidget.h.
Referenced by QgsMultiBandColorRendererWidget::QgsMultiBandColorRendererWidget(), QgsSingleBandGrayRendererWidget::QgsSingleBandGrayRendererWidget(), and QgsSingleBandPseudoColorRendererWidget::QgsSingleBandPseudoColorRendererWidget().
Member Data Documentation
QList<int> QgsRasterMinMaxWidget::mBands private
Definition at line 47 of file qgsrasterminmaxwidget.h.
Referenced by on_mLoadPushButton_clicked().
QgsRectangle QgsRasterMinMaxWidget::mExtent private
Definition at line 48 of file qgsrasterminmaxwidget.h.
Referenced by on_mLoadPushButton_clicked().
QgsRasterLayer* QgsRasterMinMaxWidget::mLayer private
Definition at line 46 of file qgsrasterminmaxwidget.h.
Referenced by on_mLoadPushButton_clicked().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/raster/qgsrasterminmaxwidget.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/raster/qgsrasterminmaxwidget.cpp