QGIS API Documentation: QgsGenericFeatureSelectionManager Class Reference
QgsGenericFeatureSelectionManager Class Reference
This selection manager synchronizes a local set of selected features with an attribute table.
#include <qgsgenericfeatureselectionmanager.h>
Public Member Functions
QgsGenericFeatureSelectionManager (QObject *parent=NULL)
QgsGenericFeatureSelectionManager (const QgsFeatureIds &initialSelection, QObject *parent=NULL)
virtual int selectedFeatureCount ()
The number of features that are selected in this layer.
virtual void select (const QgsFeatureIds &ids)
Select features.
virtual void deselect (const QgsFeatureIds &ids)
Deselect features.
virtual void setSelectedFeatures (const QgsFeatureIds &ids)
Change selection to the new set of features.
virtual const QgsFeatureIds & selectedFeaturesIds () const
Return reference to identifiers of selected features.
Public Member Functions inherited from QgsIFeatureSelectionManager
QgsIFeatureSelectionManager (QObject *parent)
Private Attributes
QgsFeatureIds mSelectedFeatures
Additional Inherited Members
Signals inherited from QgsIFeatureSelectionManager
void selectionChanged (const QgsFeatureIds selected, const QgsFeatureIds deselected, const bool clearAndSelect)
This signal is emitted when selection was changed.
Detailed Description
This selection manager synchronizes a local set of selected features with an attribute table.
If you want to synchronize the attribute table selection with the map canvas selection, you should use QgsVectorLayerSelectionManager instead.
Definition at line 27 of file qgsgenericfeatureselectionmanager.h.
Constructor & Destructor Documentation
QgsGenericFeatureSelectionManager::QgsGenericFeatureSelectionManager (QObject * parent = NULL) explicit
Definition at line 18 of file qgsgenericfeatureselectionmanager.cpp.
QgsGenericFeatureSelectionManager::QgsGenericFeatureSelectionManager (const QgsFeatureIds & initialSelection, QObject * parent = NULL)
Definition at line 23 of file qgsgenericfeatureselectionmanager.cpp.
Member Function Documentation
void QgsGenericFeatureSelectionManager::deselect (const QgsFeatureIds & ids) virtual
Deselect features.
Parameters
ids Feature ids to deselect
Implements QgsIFeatureSelectionManager.
Definition at line 40 of file qgsgenericfeatureselectionmanager.cpp.
References mSelectedFeatures, and QgsIFeatureSelectionManager::selectionChanged().
void QgsGenericFeatureSelectionManager::select (const QgsFeatureIds & ids) virtual
Select features.
Parameters
ids Feature ids to select
Implements QgsIFeatureSelectionManager.
Definition at line 34 of file qgsgenericfeatureselectionmanager.cpp.
References mSelectedFeatures, and QgsIFeatureSelectionManager::selectionChanged().
int QgsGenericFeatureSelectionManager::selectedFeatureCount () virtual
The number of features that are selected in this layer.
Returns
See description
Implements QgsIFeatureSelectionManager.
Definition at line 29 of file qgsgenericfeatureselectionmanager.cpp.
References mSelectedFeatures.
const QgsFeatureIds & QgsGenericFeatureSelectionManager::selectedFeaturesIds () const virtual
Return reference to identifiers of selected features.
Returns
A list of QgsFeatureId 's
See Also
selectedFeatures()
Implements QgsIFeatureSelectionManager.
Definition at line 55 of file qgsgenericfeatureselectionmanager.cpp.
References mSelectedFeatures.
Referenced by QgsRelationEditorWidget::on_mDeleteFeatureButton_clicked(), QgsRelationEditorWidget::on_mUnlinkFeatureButton_clicked(), and QgsFeatureSelectionDlg::selectedFeatures().
void QgsGenericFeatureSelectionManager::setSelectedFeatures (const QgsFeatureIds & ids) virtual
Change selection to the new set of features.
Dismisses the current selection. Will emit the selectionChanged(QgsFeatureIds, QgsFeatureIds, bool) signal with the clearAndSelect flag set.
Parameters
ids The ids which will be the new selection
Implements QgsIFeatureSelectionManager.
Definition at line 46 of file qgsgenericfeatureselectionmanager.cpp.
References mSelectedFeatures, and QgsIFeatureSelectionManager::selectionChanged().
Member Data Documentation
QgsFeatureIds QgsGenericFeatureSelectionManager::mSelectedFeatures private
Definition at line 43 of file qgsgenericfeatureselectionmanager.h.
Referenced by deselect(), select(), selectedFeatureCount(), selectedFeaturesIds(), and setSelectedFeatures().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/attributetable/qgsgenericfeatureselectionmanager.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/attributetable/qgsgenericfeatureselectionmanager.cpp