QGIS API Documentation: QgsRasterIdentifyResult Class Reference
QgsRasterIdentifyResult Class Reference
QGIS core library
Raster identify results container.
#include <qgsrasteridentifyresult.h>
Public Member Functions
QgsRasterIdentifyResult ()
QgsRasterIdentifyResult (QgsRaster::IdentifyFormat theFormat, QMap< int, QVariant > theResults)
Constructor.
QgsRasterIdentifyResult (QgsError theError)
Constructor.
virtual ~QgsRasterIdentifyResult ()
bool isValid () const
Returns true if valid.
QgsRaster::IdentifyFormat format () const
Get results format.
QMap< int, QVariant > results () const
Get results.
void setParams (const QMap< QString, QVariant > &theParams)
Set map of optional parameters.
QMap< QString, QVariant > params () const
Get map of optional parameters.
QgsError error () const
Get error.
void setError (const QgsError &theError)
Set error.
Private Attributes
bool mValid
Is valid.
QgsRaster::IdentifyFormat mFormat
Results format.
QMap< int, QVariant > mResults
Results.
QMap< QString, QVariant > mParams
Additional params (e.g.
QgsError mError
Error.
Detailed Description
Raster identify results container.
Definition at line 29 of file qgsrasteridentifyresult.h.
Constructor & Destructor Documentation
QgsRasterIdentifyResult::QgsRasterIdentifyResult ()
Definition at line 25 of file qgsrasteridentifyresult.cpp.
QgsRasterIdentifyResult::QgsRasterIdentifyResult (QgsRaster::IdentifyFormat theFormat, QMap< int, QVariant > theResults)
Constructor.
Creates valid result.
Parameters
theFormat the result format
theResults the results
Definition at line 31 of file qgsrasteridentifyresult.cpp.
QgsRasterIdentifyResult::QgsRasterIdentifyResult (QgsError theError)
Constructor.
Creates invalid result with error.
Parameters
theError the error
Definition at line 38 of file qgsrasteridentifyresult.cpp.
QgsRasterIdentifyResult::~QgsRasterIdentifyResult () virtual
Definition at line 45 of file qgsrasteridentifyresult.cpp.
Member Function Documentation
QgsError QgsRasterIdentifyResult::error () const inline
Get error.
Definition at line 67 of file qgsrasteridentifyresult.h.
Referenced by QgsMapToolIdentify::identifyRasterLayer().
QgsRaster::IdentifyFormat QgsRasterIdentifyResult::format () const inline
Get results format.
Definition at line 51 of file qgsrasteridentifyresult.h.
bool QgsRasterIdentifyResult::isValid () const inline
Returns true if valid.
Definition at line 48 of file qgsrasteridentifyresult.h.
Referenced by QgsMapToolIdentify::identifyRasterLayer().
QMap<QString, QVariant> QgsRasterIdentifyResult::params () const inline
Get map of optional parameters.
Definition at line 64 of file qgsrasteridentifyresult.h.
QMap<int, QVariant> QgsRasterIdentifyResult::results () const inline
Get results.
Results are different for each format: QgsRaster::IdentifyFormatValue: map of values for each band, keys are band numbers (from 1). QgsRaster::IdentifyFormatFeature: map of QgsRasterFeatureList for each sublayer (WMS) QgsRaster::IdentifyFormatHtml: map of HTML strings for each sublayer (WMS).
Definition at line 58 of file qgsrasteridentifyresult.h.
Referenced by QgsMapToolIdentify::identifyRasterLayer().
void QgsRasterIdentifyResult::setError (const QgsError & theError) inline
Set error.
Definition at line 70 of file qgsrasteridentifyresult.h.
void QgsRasterIdentifyResult::setParams (const QMap< QString, QVariant > & theParams) inline
Set map of optional parameters.
Definition at line 61 of file qgsrasteridentifyresult.h.
Member Data Documentation
QgsError QgsRasterIdentifyResult::mError private
Error.
Definition at line 88 of file qgsrasteridentifyresult.h.
QgsRaster::IdentifyFormat QgsRasterIdentifyResult::mFormat private
Results format.
Definition at line 77 of file qgsrasteridentifyresult.h.
QMap<QString, QVariant> QgsRasterIdentifyResult::mParams private
Additional params (e.g.
request url used by WMS)
Definition at line 85 of file qgsrasteridentifyresult.h.
Referenced by QgsMapToolIdentify::identifyRasterLayer().
QMap<int, QVariant> QgsRasterIdentifyResult::mResults private
Results.
Definition at line 82 of file qgsrasteridentifyresult.h.
bool QgsRasterIdentifyResult::mValid private
Is valid.
Definition at line 74 of file qgsrasteridentifyresult.h.
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/raster/qgsrasteridentifyresult.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/raster/qgsrasteridentifyresult.cpp