QGIS API Documentation: QgsImageFillSymbolLayer Class Reference
QgsImageFillSymbolLayer Class Reference
Base class for polygon renderers generating texture images.
#include <qgsfillsymbollayerv2.h>
Public Member Functions
QgsImageFillSymbolLayer ()
virtual ~QgsImageFillSymbolLayer ()
void renderPolygon (const QPolygonF &points, QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
void setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outlineWidthUnit () const
virtual double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual Qt::PenStyle dxfPenStyle () const
Public Member Functions inherited from QgsFillSymbolLayerV2
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString layerType () const =0
virtual void startRender (QgsSymbolV2RenderContext &context)=0
virtual void stopRender (QgsSymbolV2RenderContext &context)=0
virtual QgsSymbolLayerV2 * clone () const =0
virtual void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
virtual QgsStringMap properties () const =0
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
virtual void setOutputUnit (QgsSymbolV2::OutputUnit unit)
virtual QgsSymbolV2::OutputUnit outputUnit () const
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
Protected Member Functions
virtual void applyDataDefinedSettings (const QgsSymbolV2RenderContext &context)
Protected Member Functions inherited from QgsFillSymbolLayerV2
QgsFillSymbolLayerV2 (bool locked=false)
void _renderPolygon (QPainter *p, const QPolygonF &points, const QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
Default method to render polygon.
Protected Member Functions inherited from QgsSymbolLayerV2
QgsSymbolLayerV2 (QgsSymbolV2::SymbolType type, bool locked=false)
virtual void prepareExpressions (const QgsVectorLayer *vl, double scale=-1.0)
virtual QgsExpression * expression (const QString &property) const
void saveDataDefinedProperties (QgsStringMap &stringMap) const
Saves data defined properties to string map.
void copyDataDefinedProperties (QgsSymbolLayerV2 *destLayer) const
Copies data defined properties of this layer to another symbol layer.
Protected Attributes
QBrush mBrush
double mNextAngle
double mOutlineWidth
Outline width.
QgsSymbolV2::OutputUnit mOutlineWidthUnit
QgsLineSymbolV2 * mOutline
Custom outline.
Protected Attributes inherited from QgsFillSymbolLayerV2
double mAngle
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Additional Inherited Members
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Base class for polygon renderers generating texture images.
Definition at line 275 of file qgsfillsymbollayerv2.h.
Constructor & Destructor Documentation
QgsImageFillSymbolLayer::QgsImageFillSymbolLayer ()
Definition at line 786 of file qgsfillsymbollayerv2.cpp.
References setSubSymbol().
QgsImageFillSymbolLayer::~QgsImageFillSymbolLayer () virtual
Definition at line 791 of file qgsfillsymbollayerv2.cpp.
Member Function Documentation
virtual void QgsImageFillSymbolLayer::applyDataDefinedSettings (const QgsSymbolV2RenderContext & context) inline protected virtual
Reimplemented in QgsPointPatternFillSymbolLayer, QgsLinePatternFillSymbolLayer, and QgsSVGFillSymbolLayer.
Definition at line 305 of file qgsfillsymbollayerv2.h.
Referenced by renderPolygon().
QColor QgsImageFillSymbolLayer::dxfColor (const QgsSymbolV2RenderContext & context) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 893 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2::color(), and mOutline.
Qt::PenStyle QgsImageFillSymbolLayer::dxfPenStyle () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 903 of file qgsfillsymbollayerv2.cpp.
References mOutline.
double QgsImageFillSymbolLayer::dxfWidth (const QgsDxfExport & e, const QgsSymbolV2RenderContext & context) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 882 of file qgsfillsymbollayerv2.cpp.
References QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), mOutlineWidth, and mOutlineWidthUnit.
double QgsImageFillSymbolLayer::estimateMaxBleed () const virtual
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
Eg, polygons drawn with an outline will draw half the width of the outline outside of the polygon. This amount is estimated, since it may be affected by data defined symbology rules.
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsPointPatternFillSymbolLayer, and QgsLinePatternFillSymbolLayer.
Definition at line 872 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolLayerV2::estimateMaxBleed(), mOutline, and QgsSymbolV2::symbolLayer().
QgsSymbolV2::OutputUnit QgsImageFillSymbolLayer::outlineWidthUnit () const inline
Definition at line 286 of file qgsfillsymbollayerv2.h.
void QgsImageFillSymbolLayer::renderPolygon (const QPolygonF & points, QList< QPolygonF > * rings, QgsSymbolV2RenderContext & context) virtual
Implements QgsFillSymbolLayerV2.
Definition at line 795 of file qgsfillsymbollayerv2.cpp.
References QgsFillSymbolLayerV2::_renderPolygon(), applyDataDefinedSettings(), QgsSymbolV2RenderContext::feature(), QgsFillSymbolLayerV2::mAngle, mBrush, mNextAngle, mOutline, QgsRenderContext::painter(), qgsDoubleNear(), QgsSymbolV2RenderContext::renderContext(), QgsLineSymbolV2::renderPolyline(), QgsSymbolV2RenderContext::selected(), QgsSymbolLayerV2::selectFillBorder, and QgsRenderContext::selectionColor().
void QgsImageFillSymbolLayer::setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 285 of file qgsfillsymbollayerv2.h.
Referenced by QgsSVGFillSymbolLayer::clone(), and QgsSVGFillSymbolLayer::create().
bool QgsImageFillSymbolLayer::setSubSymbol (QgsSymbolV2 * symbol) virtual
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsPointPatternFillSymbolLayer, and QgsLinePatternFillSymbolLayer.
Definition at line 844 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2::Line, mOutline, and QgsSymbolV2::type().
Referenced by QgsSVGFillSymbolLayer::clone(), QgsSVGFillSymbolLayer::createFromSld(), QgsImageFillSymbolLayer(), and QgsSVGFillSymbolLayer::QgsSVGFillSymbolLayer().
virtual QgsSymbolV2* QgsImageFillSymbolLayer::subSymbol () inline virtual
Reimplemented from QgsSymbolLayerV2.
Reimplemented in QgsPointPatternFillSymbolLayer, and QgsLinePatternFillSymbolLayer.
Definition at line 282 of file qgsfillsymbollayerv2.h.
Member Data Documentation
QBrush QgsImageFillSymbolLayer::mBrush protected
Definition at line 295 of file qgsfillsymbollayerv2.h.
Referenced by QgsSVGFillSymbolLayer::applyDataDefinedSettings(), QgsLinePatternFillSymbolLayer::applyDataDefinedSettings(), QgsPointPatternFillSymbolLayer::applyDataDefinedSettings(), QgsLinePatternFillSymbolLayer::applyPattern(), renderPolygon(), QgsSVGFillSymbolLayer::startRender(), QgsLinePatternFillSymbolLayer::startRender(), and QgsPointPatternFillSymbolLayer::startRender().
double QgsImageFillSymbolLayer::mNextAngle protected
Definition at line 296 of file qgsfillsymbollayerv2.h.
Referenced by QgsSVGFillSymbolLayer::applyDataDefinedSettings(), and renderPolygon().
QgsLineSymbolV2* QgsImageFillSymbolLayer::mOutline protected
Custom outline.
Definition at line 303 of file qgsfillsymbollayerv2.h.
Referenced by QgsSVGFillSymbolLayer::clone(), dxfColor(), dxfPenStyle(), estimateMaxBleed(), renderPolygon(), setSubSymbol(), QgsSVGFillSymbolLayer::startRender(), QgsPointPatternFillSymbolLayer::startRender(), QgsSVGFillSymbolLayer::stopRender(), QgsPointPatternFillSymbolLayer::stopRender(), and QgsSVGFillSymbolLayer::toSld().
double QgsImageFillSymbolLayer::mOutlineWidth protected
Outline width.
Definition at line 299 of file qgsfillsymbollayerv2.h.
Referenced by dxfWidth(), and QgsSVGFillSymbolLayer::QgsSVGFillSymbolLayer().
QgsSymbolV2::OutputUnit QgsImageFillSymbolLayer::mOutlineWidthUnit protected
Definition at line 300 of file qgsfillsymbollayerv2.h.
Referenced by QgsSVGFillSymbolLayer::clone(), dxfWidth(), QgsSVGFillSymbolLayer::outputUnit(), QgsSVGFillSymbolLayer::properties(), and QgsSVGFillSymbolLayer::setOutputUnit().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsfillsymbollayerv2.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsfillsymbollayerv2.cpp