QGIS API Documentation: QgsZipItem Class Reference
QgsZipItem Class Reference
A zip file: contains layers, using GDAL/OGR VSIFILE mechanism.
#include <qgsdataitem.h>
Public Member Functions
QgsZipItem (QgsDataItem *parent, QString name, QString path)
~QgsZipItem ()
QVector< QgsDataItem * > createChildren ()
const QStringList & getZipFileList ()
Public Member Functions inherited from QgsDataCollectionItem
QgsDataCollectionItem (QgsDataItem *parent, QString name, QString path=QString::null)
~QgsDataCollectionItem ()
void setPopulated ()
void addChild (QgsDataItem *item)
Public Member Functions inherited from QgsDataItem
QgsDataItem (QgsDataItem::Type type, QgsDataItem *parent, QString name, QString path)
virtual ~QgsDataItem ()
bool hasChildren ()
int rowCount ()
virtual void refresh ()
virtual void populate ()
bool isPopulated ()
virtual void addChildItem (QgsDataItem *child, bool refresh=false)
virtual void deleteChildItem (QgsDataItem *child)
virtual QgsDataItem * removeChildItem (QgsDataItem *child)
virtual bool equal (const QgsDataItem *other)
virtual QWidget * paramWidget ()
virtual QList< QAction * > actions ()
virtual bool acceptDrop ()
virtual bool handleDrop (const QMimeData *, Qt::DropAction)
virtual bool setCrs (QgsCoordinateReferenceSystem crs)
virtual Capability capabilities ()
Type type () const
QgsDataItem * parent () const
void setParent (QgsDataItem *parent)
QVector< QgsDataItem * > children () const
QIcon icon () const
QString name () const
QString path () const
void setIcon (QIcon icon)
void setToolTip (QString msg)
QString toolTip () const
Static Public Member Functions
static QString vsiPrefix (QString uri)
static QgsDataItem * itemFromPath (QgsDataItem *parent, QString path, QString name)
static const QIcon & iconZip ()
Static Public Member Functions inherited from QgsDataCollectionItem
static const QIcon & iconDir ()
static const QIcon & iconDataCollection ()
Static Public Member Functions inherited from QgsDataItem
static int findItem (QVector< QgsDataItem * > items, QgsDataItem *item)
Static Public Attributes
static QVector< dataItem_t * > mDataItemPtr = QVector<dataItem_t*>()
static QStringList mProviderNames = QStringList()
Protected Attributes
QString mVsiPrefix
QStringList mZipFileList
Additional Inherited Members
Public Types inherited from QgsDataItem
enum Type {
Collection, Directory, Layer, Error,
Favourites
}
enum Capability { NoCapabilities = 0, SetCrs = 1 }
Public Slots inherited from QgsDataItem
void emitBeginInsertItems (QgsDataItem *parent, int first, int last)
void emitEndInsertItems ()
void emitBeginRemoveItems (QgsDataItem *parent, int first, int last)
void emitEndRemoveItems ()
Signals inherited from QgsDataItem
void beginInsertItems (QgsDataItem *parent, int first, int last)
void endInsertItems ()
void beginRemoveItems (QgsDataItem *parent, int first, int last)
void endRemoveItems ()
Detailed Description
A zip file: contains layers, using GDAL/OGR VSIFILE mechanism.
Definition at line 298 of file qgsdataitem.h.
Constructor & Destructor Documentation
QgsZipItem::QgsZipItem (QgsDataItem * parent, QString name, QString path)
Definition at line 749 of file qgsdataitem.cpp.
References cast_to_fptr, QgsDataItem::Collection, iconZip(), QgsProviderRegistry::instance(), mDataItemPtr, QgsDataItem::mIcon, mProviderNames, QgsDataItem::mType, mVsiPrefix, QgsDataProvider::NoDataCapabilities, QgsProviderRegistry::providerLibrary(), QgsDebugMsg, and vsiPrefix().
Referenced by itemFromPath().
QgsZipItem::~QgsZipItem ()
Definition at line 806 of file qgsdataitem.cpp.
Member Function Documentation
QVector< QgsDataItem * > QgsZipItem::createChildren () virtual
Reimplemented from QgsDataItem.
Definition at line 881 of file qgsdataitem.cpp.
References QgsDataItem::children(), getZipFileList(), mDataItemPtr, QgsDataItem::mPath, mProviderNames, mVsiPrefix, mZipFileList, QgsDataItem::name(), QgsDataItem::path(), and QgsDebugMsgLevel.
const QStringList & QgsZipItem::getZipFileList ()
Definition at line 1050 of file qgsdataitem.cpp.
References mVsiPrefix, mZipFileList, QgsDataItem::name(), QgsDataItem::path(), QgsDebugMsg, QgsDebugMsgLevel, and VSIReadDirRecursive1().
Referenced by createChildren(), and itemFromPath().
const QIcon & QgsZipItem::iconZip () static
Definition at line 139 of file qgsdataitem.cpp.
References QgsApplication::getThemeIcon(), and QgsDataItem::icon().
Referenced by QgsZipItem().
QgsDataItem * QgsZipItem::itemFromPath (QgsDataItem * parent, QString path, QString name) static
Definition at line 957 of file qgsdataitem.cpp.
References getZipFileList(), mDataItemPtr, mProviderNames, QgsDataItem::name(), QgsDataItem::path(), QgsDataItem::populate(), QgsDebugMsgLevel, QgsZipItem(), QgsDataItem::rowCount(), and vsiPrefix().
Referenced by QgsDirectoryItem::createChildren().
static QString QgsZipItem::vsiPrefix (QString uri) inline static
Definition at line 317 of file qgsdataitem.h.
References qgsVsiPrefix().
Referenced by itemFromPath(), and QgsZipItem().
Member Data Documentation
QVector< dataItem_t * > QgsZipItem::mDataItemPtr = QVector<dataItem_t*>() static
Note
not available via python bindings
Definition at line 314 of file qgsdataitem.h.
Referenced by createChildren(), itemFromPath(), and QgsZipItem().
QStringList QgsZipItem::mProviderNames = QStringList() static
Definition at line 315 of file qgsdataitem.h.
Referenced by createChildren(), itemFromPath(), and QgsZipItem().
QString QgsZipItem::mVsiPrefix protected
Definition at line 303 of file qgsdataitem.h.
Referenced by createChildren(), getZipFileList(), and QgsZipItem().
QStringList QgsZipItem::mZipFileList protected
Definition at line 304 of file qgsdataitem.h.
Referenced by createChildren(), and getZipFileList().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsdataitem.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsdataitem.cpp