QGIS API Documentation: QgsSingleBandColorDataRenderer Class Reference
QgsSingleBandColorDataRenderer Class Reference
QGIS core library
Raster renderer pipe for single band color.
#include <qgssinglebandcolordatarenderer.h>
Public Member Functions
QgsSingleBandColorDataRenderer (QgsRasterInterface *input, int band)
~QgsSingleBandColorDataRenderer ()
QgsRasterInterface * clone () const
Clone itself, create deep copy.
bool setInput (QgsRasterInterface *input)
Set input.
QgsRasterBlock * block (int bandNo, const QgsRectangle &extent, int width, int height)
Read block of data using given extent and size.
void writeXML (QDomDocument &doc, QDomElement &parentElem) const
Write base class members to xml.
QList< int > usesBands () const
Returns a list of band numbers used by the renderer.
Public Member Functions inherited from QgsRasterRenderer
QgsRasterRenderer (QgsRasterInterface *input=0, const QString &type="")
virtual ~QgsRasterRenderer ()
virtual int bandCount () const
Get number of bands.
virtual QGis::DataType dataType (int bandNo) const
Returns data type for the band specified by number.
virtual QString type () const
bool usesTransparency () const
void setOpacity (double opacity)
double opacity () const
void setRasterTransparency (QgsRasterTransparency *t)
const QgsRasterTransparency * rasterTransparency () const
void setAlphaBand (int band)
int alphaBand () const
virtual void legendSymbologyItems (QList< QPair< QString, QColor > > &symbolItems) const
Get symbology items if provided by renderer.
void readXML (const QDomElement &rendererElem)
Sets base class members from xml.
Public Member Functions inherited from QgsRasterInterface
QgsRasterInterface (QgsRasterInterface *input=0)
virtual ~QgsRasterInterface ()
virtual int capabilities () const
Returns a bitmask containing the supported capabilities.
QString capabilitiesString () const
Returns the above in friendly format.
virtual QGis::DataType srcDataType (int bandNo) const
Returns source data type for the band specified by number, source data type may be shorter than dataType.
virtual QgsRectangle extent ()
Get the extent of the interface.
int dataTypeSize (int bandNo)
virtual int xBlockSize () const
Get block size.
virtual int yBlockSize () const
virtual int xSize () const
Get raster size.
virtual int ySize () const
virtual QString generateBandName (int theBandNumber) const
helper function to create zero padded band names
virtual QgsRasterInterface * input () const
Current input.
virtual bool on () const
Is on/off.
virtual void setOn (bool on)
Set on/off.
virtual const QgsRasterInterface * srcInput () const
Get source / raw input, the first in pipe, usually provider.
virtual QgsRasterInterface * srcInput ()
virtual QgsRasterBandStats bandStatistics (int theBandNo, int theStats=QgsRasterBandStats::All, const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0)
Get band statistics.
virtual bool hasStatistics (int theBandNo, int theStats=QgsRasterBandStats::All, const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0)
Returns true if histogram is available (cached, already calculated).
virtual QgsRasterHistogram histogram (int theBandNo, int theBinCount=0, double theMinimum=std::numeric_limits< double >::quiet_NaN(), double theMaximum=std::numeric_limits< double >::quiet_NaN(), const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0, bool theIncludeOutOfRange=false)
Get histogram.
virtual bool hasHistogram (int theBandNo, int theBinCount, double theMinimum=std::numeric_limits< double >::quiet_NaN(), double theMaximum=std::numeric_limits< double >::quiet_NaN(), const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0, bool theIncludeOutOfRange=false)
Returns true if histogram is available (cached, already calculated), the parameters are the same as in histogram()
virtual void cumulativeCut (int theBandNo, double theLowerCount, double theUpperCount, double &theLowerValue, double &theUpperValue, const QgsRectangle &theExtent=QgsRectangle(), int theSampleSize=0)
Find values for cumulative pixel count cut.
Static Public Member Functions
static QgsRasterRenderer * create (const QDomElement &elem, QgsRasterInterface *input)
Static Public Member Functions inherited from QgsRasterRenderer
static QString minMaxOriginName (int theOrigin)
static QString minMaxOriginLabel (int theOrigin)
static int minMaxOriginFromName (QString theName)
Private Attributes
int mBand
Additional Inherited Members
Public Types inherited from QgsRasterRenderer
enum MinMaxOrigin {
MinMaxUnknown = 0, MinMaxUser = 1, MinMaxMinMax = 1 << 1, MinMaxCumulativeCut = 1 << 2,
MinMaxStdDev = 1 << 3, MinMaxFullExtent = 1 << 4, MinMaxSubExtent = 1 << 5, MinMaxEstimated = 1 << 6,
MinMaxExact = 1 << 7
}
Static Public Attributes inherited from QgsRasterRenderer
static const QRgb NODATA_COLOR = qRgba(0, 0, 0, 0)
Protected Member Functions inherited from QgsRasterRenderer
void _writeXML (QDomDocument &doc, QDomElement &rasterRendererElem) const
Write upper class info into rasterrenderer element (called by writeXML method of subclasses)
Protected Attributes inherited from QgsRasterRenderer
QString mType
double mOpacity
Global alpha value (0-1)
QgsRasterTransparency * mRasterTransparency
Raster transparency per color or value.
int mAlphaBand
Read alpha value from band.
Detailed Description
Raster renderer pipe for single band color.
Definition at line 28 of file qgssinglebandcolordatarenderer.h.
Constructor & Destructor Documentation
QgsSingleBandColorDataRenderer::QgsSingleBandColorDataRenderer (QgsRasterInterface * input, int band)
Definition at line 24 of file qgssinglebandcolordatarenderer.cpp.
Referenced by clone(), and create().
QgsSingleBandColorDataRenderer::~QgsSingleBandColorDataRenderer ()
Definition at line 30 of file qgssinglebandcolordatarenderer.cpp.
Member Function Documentation
QgsRasterBlock * QgsSingleBandColorDataRenderer::block (int bandNo, const QgsRectangle & extent, int width, int height) virtual
Read block of data using given extent and size.
Returns pointer to data. Caller is responsible to free the memory returned.
Parameters
bandNo band number
extent extent of block
width pixel width of block
height pixel height of block
Implements QgsRasterRenderer.
Definition at line 56 of file qgssinglebandcolordatarenderer.cpp.
References QGis::ARGB32_Premultiplied, QgsRasterInterface::block(), QgsRasterBlock::color(), QgsRasterBlock::convert(), QgsRasterBlock::isEmpty(), mBand, QgsRasterInterface::mInput, QgsRasterRenderer::mOpacity, QgsDebugMsg, QgsRasterBlock::reset(), QgsRasterBlock::setColor(), and QgsRasterRenderer::usesTransparency().
QgsRasterInterface * QgsSingleBandColorDataRenderer::clone () const virtual
Clone itself, create deep copy.
Implements QgsRasterRenderer.
Definition at line 34 of file qgssinglebandcolordatarenderer.cpp.
References QgsRasterRenderer::mAlphaBand, mBand, QgsRasterRenderer::mOpacity, QgsRasterRenderer::mRasterTransparency, QgsSingleBandColorDataRenderer(), QgsRasterRenderer::setAlphaBand(), QgsRasterRenderer::setOpacity(), and QgsRasterRenderer::setRasterTransparency().
QgsRasterRenderer * QgsSingleBandColorDataRenderer::create (const QDomElement & elem, QgsRasterInterface * input) static
Definition at line 43 of file qgssinglebandcolordatarenderer.cpp.
References QgsSingleBandColorDataRenderer(), and QgsRasterRenderer::readXML().
Referenced by QgsRasterRendererRegistry::QgsRasterRendererRegistry().
bool QgsSingleBandColorDataRenderer::setInput (QgsRasterInterface * input) virtual
Set input.
Returns true if set correctly, false if cannot use that input
Reimplemented from QgsRasterRenderer.
Definition at line 123 of file qgssinglebandcolordatarenderer.cpp.
References QGis::ARGB32, QGis::ARGB32_Premultiplied, QgsRasterInterface::dataType(), QgsRasterInterface::input(), QgsRasterInterface::mInput, and QgsRasterInterface::mOn.
QList< int > QgsSingleBandColorDataRenderer::usesBands () const virtual
Returns a list of band numbers used by the renderer.
Reimplemented from QgsRasterRenderer.
Definition at line 113 of file qgssinglebandcolordatarenderer.cpp.
References mBand.
void QgsSingleBandColorDataRenderer::writeXML (QDomDocument & doc, QDomElement & parentElem) const virtual
Write base class members to xml.
Reimplemented from QgsRasterInterface.
Definition at line 102 of file qgssinglebandcolordatarenderer.cpp.
References QgsRasterRenderer::_writeXML(), and mBand.
Member Data Documentation
int QgsSingleBandColorDataRenderer::mBand private
Definition at line 46 of file qgssinglebandcolordatarenderer.h.
Referenced by block(), clone(), usesBands(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/raster/qgssinglebandcolordatarenderer.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/raster/qgssinglebandcolordatarenderer.cpp