QGIS API Documentation: QgsVectorFileWriter Class Reference
QgsVectorFileWriter Class Reference
QGIS core library
A convenience class for writing vector files to disk.
#include <qgsvectorfilewriter.h>
Classes
class BoolOption
class HiddenOption
class IntOption
struct MetaData
class Option
class SetOption
class StringOption
Public Types
enum OptionType { Set, String, Int, Hidden }
enum WriterError {
NoError = 0, ErrDriverNotFound, ErrCreateDataSource, ErrCreateLayer,
ErrAttributeTypeUnsupported, ErrAttributeCreationFailed, ErrProjection, ErrFeatureWriteFailed,
ErrInvalidLayer
}
enum SymbologyExport { NoSymbology = 0, FeatureSymbology, SymbolLayerSymbology }
Public Member Functions
QgsVectorFileWriter (const QString &vectorFileName, const QString &fileEncoding, const QgsFields &fields, QGis::WkbType geometryType, const QgsCoordinateReferenceSystem *srs, const QString &driverName="ESRI Shapefile", const QStringList &datasourceOptions=QStringList(), const QStringList &layerOptions=QStringList(), QString *newFilename=0, SymbologyExport symbologyExport=NoSymbology)
create shapefile and initialize it
WriterError hasError ()
checks whether there were any errors in constructor
QString errorMessage ()
retrieves error message
bool addFeature (QgsFeature &feature, QgsFeatureRendererV2 *renderer=0, QGis::UnitType outputUnit=QGis::Meters)
add feature to the currently opened shapefile
QMap< int, int > attrIdxToOgrIdx ()
~QgsVectorFileWriter ()
close opened shapefile for writing
SymbologyExport symbologyExport () const
void setSymbologyExport (SymbologyExport symExport)
double symbologyScaleDenominator () const
void setSymbologyScaleDenominator (double d)
Static Public Member Functions
static WriterError writeAsVectorFormat (QgsVectorLayer *layer, const QString &fileName, const QString &fileEncoding, const QgsCoordinateReferenceSystem *destCRS, const QString &driverName="ESRI Shapefile", bool onlySelected=false, QString *errorMessage=0, const QStringList &datasourceOptions=QStringList(), const QStringList &layerOptions=QStringList(), bool skipAttributeCreation=false, QString *newFilename=0, SymbologyExport symbologyExport=NoSymbology, double symbologyScale=1.0)
Write contents of vector layer to an (OGR supported) vector formt.
static WriterError writeAsVectorFormat (QgsVectorLayer *layer, const QString &fileName, const QString &fileEncoding, const QgsCoordinateTransform *ct, const QString &driverName="ESRI Shapefile", bool onlySelected=false, QString *errorMessage=0, const QStringList &datasourceOptions=QStringList(), const QStringList &layerOptions=QStringList(), bool skipAttributeCreation=false, QString *newFilename=0, SymbologyExport symbologyExport=NoSymbology, double symbologyScale=1.0)
static QMap< QString, QString > supportedFiltersAndFormats ()
Returns map with format filter string as key and OGR format key as value.
static QMap< QString, QString > ogrDriverList ()
Returns driver list that can be used for dialogs.
static QString fileFilterString ()
Returns filter string that can be used for dialogs.
static QString filterForDriver (const QString &driverName)
Creates a filter for an OGR driver key.
static QString convertCodecNameForEncodingOption (const QString &codecName)
Converts codec name to string passed to ENCODING layer creation option of OGR Shapefile.
static bool deleteShapeFile (QString theFileName)
Delete a shapefile (and its accompanying shx / dbf / prf)
static bool driverMetadata (const QString &driverName, MetaData &driverMetadata)
Protected Member Functions
OGRGeometryH createEmptyGeometry (QGis::WkbType wkbType)
Protected Attributes
OGRDataSourceH mDS
OGRLayerH mLayer
OGRGeometryH mGeom
QgsFields mFields
WriterError mError
contains error value if construction was not successful
QString mErrorMessage
QTextCodec * mCodec
QGis::WkbType mWkbType
geometry type which is being used
QMap< int, int > mAttrIdxToOgrIdx
map attribute indizes to OGR field indexes
SymbologyExport mSymbologyExport
double mSymbologyScaleDenominator
Scale for symbology export (e.g.
Private Member Functions
void createSymbolLayerTable (QgsVectorLayer *vl, const QgsCoordinateTransform *ct, OGRDataSourceH ds)
OGRFeatureH createFeature (QgsFeature &feature)
bool writeFeature (OGRLayerH layer, OGRFeatureH feature)
WriterError exportFeaturesSymbolLevels (QgsVectorLayer *layer, QgsFeatureIterator &fit, const QgsCoordinateTransform *ct, QString *errorMessage=0)
Writes features considering symbol level order.
double mmScaleFactor (double scaleDenominator, QgsSymbolV2::OutputUnit symbolUnits, QGis::UnitType mapUnits)
double mapUnitScaleFactor (double scaleDenominator, QgsSymbolV2::OutputUnit symbolUnits, QGis::UnitType mapUnits)
QgsRenderContext renderContext () const
void startRender (QgsVectorLayer *vl) const
void stopRender (QgsVectorLayer *vl) const
QgsFeatureRendererV2 * symbologyRenderer (QgsVectorLayer *vl) const
void addRendererAttributes (QgsVectorLayer *vl, QgsAttributeList &attList)
Adds attributes needed for classification.
Static Private Member Functions
static QMap< QString, MetaData > initMetaData ()
static bool driverMetadata (QString driverName, QString &longName, QString &trLongName, QString &glob, QString &ext)
Static Private Attributes
static QMap< QString, MetaData > sDriverMetadata
Detailed Description
A convenience class for writing vector files to disk.
There are two possibilities how to use this class:
static call to QgsVectorFileWriter::writeAsShapefile(...) which saves the whole vector layer
create an instance of the class and issue calls to addFeature(...)
Currently supports only writing to shapefiles, but shouldn't be a problem to add capability to support other OGR-writable formats.
Definition at line 42 of file qgsvectorfilewriter.h.
Member Enumeration Documentation
enum QgsVectorFileWriter::OptionType
Enumerator:
Set
String
Int
Hidden
Definition at line 45 of file qgsvectorfilewriter.h.
enum QgsVectorFileWriter::SymbologyExport
Enumerator:
NoSymbology
FeatureSymbology
SymbolLayerSymbology
Definition at line 157 of file qgsvectorfilewriter.h.
enum QgsVectorFileWriter::WriterError
Enumerator:
NoError
ErrDriverNotFound
ErrCreateDataSource
ErrCreateLayer
ErrAttributeTypeUnsupported
ErrAttributeCreationFailed
ErrProjection
ErrFeatureWriteFailed
ErrInvalidLayer
Definition at line 143 of file qgsvectorfilewriter.h.
Constructor & Destructor Documentation
QgsVectorFileWriter::QgsVectorFileWriter (const QString & vectorFileName, const QString & fileEncoding, const QgsFields & fields, QGis::WkbType geometryType, const QgsCoordinateReferenceSystem * srs, const QString & driverName = "ESRI Shapefile", const QStringList & datasourceOptions = QStringList(), const QStringList & layerOptions = QStringList(), QString * newFilename = 0, SymbologyExport symbologyExport = NoSymbology)
create shapefile and initialize it
Definition at line 57 of file qgsvectorfilewriter.cpp.
References convertCodecNameForEncodingOption(), QgsFields::count(), createEmptyGeometry(), deleteShapeFile(), driverMetadata(), ErrAttributeCreationFailed, ErrAttributeTypeUnsupported, ErrCreateDataSource, ErrCreateLayer, ErrDriverNotFound, QgsField::length(), QgsMessageLog::logMessage(), mAttrIdxToOgrIdx, mCodec, mDS, mError, mErrorMessage, mFields, mGeom, mLayer, mWkbType, QgsField::name(), QgsField::precision(), QgsDebugMsg, QgsApplication::registerOgrDrivers(), QgsFields::size(), TO8F, QgsCoordinateReferenceSystem::toWkt(), tr, QgsField::type(), and QGis::WKBNoGeometry.
Referenced by writeAsVectorFormat().
QgsVectorFileWriter::~QgsVectorFileWriter ()
close opened shapefile for writing
Definition at line 1768 of file qgsvectorfilewriter.cpp.
References mDS, and mGeom.
Member Function Documentation
bool QgsVectorFileWriter::addFeature (QgsFeature & feature, QgsFeatureRendererV2 * renderer = 0, QGis::UnitType outputUnit = QGis::Meters)
add feature to the currently opened shapefile
Definition at line 1547 of file qgsvectorfilewriter.cpp.
References createFeature(), FeatureSymbology, mapUnitScaleFactor(), mLayer, mmScaleFactor(), mSymbologyExport, mSymbologyScaleDenominator, NoSymbology, SymbolLayerSymbology, QgsFeatureRendererV2::symbolsForFeature(), and writeFeature().
Referenced by QgsGeometryAnalyzer::addEventLayerFeature(), QgsPointSample::addSamplePoints(), QgsGeometryAnalyzer::bufferFeature(), QgsGeometryAnalyzer::centroidFeature(), QgsTransectSample::createSample(), QgsOverlayAnalyzer::intersectFeature(), QgsGeometryAnalyzer::simplifyFeature(), and writeAsVectorFormat().
void QgsVectorFileWriter::addRendererAttributes (QgsVectorLayer * vl, QgsAttributeList & attList) private
Adds attributes needed for classification.
Definition at line 2629 of file qgsvectorfilewriter.cpp.
References QgsVectorLayer::fieldNameIndex(), index, symbologyRenderer(), and QgsFeatureRendererV2::usedAttributes().
Referenced by writeAsVectorFormat().
QMap<int, int> QgsVectorFileWriter::attrIdxToOgrIdx () inline
Note
not available in python bindings
Definition at line 253 of file qgsvectorfilewriter.h.
QString QgsVectorFileWriter::convertCodecNameForEncodingOption (const QString & codecName) static
Converts codec name to string passed to ENCODING layer creation option of OGR Shapefile.
Definition at line 2166 of file qgsvectorfilewriter.cpp.
Referenced by QgsVectorFileWriter().
OGRGeometryH QgsVectorFileWriter::createEmptyGeometry (QGis::WkbType wkbType) protected
Note
not available in python bindings
Definition at line 483 of file qgsvectorfilewriter.cpp.
Referenced by createFeature(), and QgsVectorFileWriter().
OGRFeatureH QgsVectorFileWriter::createFeature (QgsFeature & feature) private
Definition at line 1611 of file qgsvectorfilewriter.cpp.
References QgsGeometry::asWkb(), QgsFeature::attribute(), QgsGeometry::convertToMultiType(), QgsFields::count(), createEmptyGeometry(), ErrFeatureWriteFailed, FID_TO_NUMBER, QgsFeature::geometry(), QgsFeature::id(), QgsMessageLog::logMessage(), mAttrIdxToOgrIdx, MathUtils::max(), mCodec, mError, mErrorMessage, mFields, mGeom, mLayer, mWkbType, QgsDebugMsg, QGis::singleType(), tr, QGis::WKBNoGeometry, QgsGeometry::wkbSize(), and QgsGeometry::wkbType().
Referenced by addFeature(), and exportFeaturesSymbolLevels().
void QgsVectorFileWriter::createSymbolLayerTable (QgsVectorLayer * vl, const QgsCoordinateTransform * ct, OGRDataSourceH ds) private
Definition at line 2363 of file qgsvectorfilewriter.cpp.
References QgsMapLayer::crs(), QgsCoordinateTransform::destCRS(), QgsCoordinateReferenceSystem::mapUnits(), mapUnitScaleFactor(), mmScaleFactor(), mSymbologyScaleDenominator, QgsVectorLayer::rendererV2(), and QgsFeatureRendererV2::symbols().
bool QgsVectorFileWriter::deleteShapeFile (QString theFileName) static
Delete a shapefile (and its accompanying shx / dbf / prf)
Parameters
theFileName /path/to/file.shp
Returns
bool true if the file was deleted successfully
Definition at line 2015 of file qgsvectorfilewriter.cpp.
References file, and QgsDebugMsg.
Referenced by QgsPointSample::createRandomPoints(), and QgsVectorFileWriter().
bool QgsVectorFileWriter::driverMetadata (const QString & driverName, QgsVectorFileWriter::MetaData & driverMetadata) static
Definition at line 1518 of file qgsvectorfilewriter.cpp.
References initMetaData(), and sDriverMetadata.
Referenced by filterForDriver(), initMetaData(), ogrDriverList(), and QgsVectorFileWriter().
bool QgsVectorFileWriter::driverMetadata (QString driverName, QString & longName, QString & trLongName, QString & glob, QString & ext) static private
Deprecated:
Definition at line 2183 of file qgsvectorfilewriter.cpp.
References tr.
QString QgsVectorFileWriter::errorMessage ()
retrieves error message
Note
added in 1.5
Definition at line 1542 of file qgsvectorfilewriter.cpp.
References mErrorMessage.
Referenced by writeAsVectorFormat().
QgsVectorFileWriter::WriterError QgsVectorFileWriter::exportFeaturesSymbolLevels (QgsVectorLayer * layer, QgsFeatureIterator & fit, const QgsCoordinateTransform * ct, QString * errorMessage = 0) private
Writes features considering symbol level order.
Definition at line 2410 of file qgsvectorfilewriter.cpp.
References createFeature(), QgsMapLayer::crs(), QgsCoordinateTransform::destCRS(), ErrFeatureWriteFailed, ErrProjection, QgsFeature::geometry(), QgsSymbolV2LevelItem::layer(), QgsCoordinateReferenceSystem::mapUnits(), mapUnitScaleFactor(), mLayer, mmScaleFactor(), mSymbologyScaleDenominator, QgsFeatureIterator::nextFeature(), NoError, QgsVectorLayer::rendererV2(), QgsSymbolLayerV2::renderingPass(), startRender(), stopRender(), QgsSymbolV2LevelItem::symbol(), QgsFeatureRendererV2::symbolForFeature(), QgsSymbolV2::symbolLayer(), QgsSymbolV2::symbolLayerCount(), QgsFeatureRendererV2::symbols(), tr, QgsGeometry::transform(), QgsLogger::warning(), QgsException::what(), and writeFeature().
Referenced by writeAsVectorFormat().
QString QgsVectorFileWriter::fileFilterString () static
Returns filter string that can be used for dialogs.
Definition at line 2139 of file qgsvectorfilewriter.cpp.
References supportedFiltersAndFormats().
QString QgsVectorFileWriter::filterForDriver (const QString & driverName) static
Creates a filter for an OGR driver key.
Definition at line 2154 of file qgsvectorfilewriter.cpp.
References driverMetadata().
Referenced by supportedFiltersAndFormats().
QgsVectorFileWriter::WriterError QgsVectorFileWriter::hasError ()
checks whether there were any errors in constructor
Definition at line 1537 of file qgsvectorfilewriter.cpp.
References mError.
Referenced by QgsPointSample::createRandomPoints(), QgsTransectSample::createSample(), and writeAsVectorFormat().
QMap< QString, QgsVectorFileWriter::MetaData > QgsVectorFileWriter::initMetaData () static private
Definition at line 488 of file qgsvectorfilewriter.cpp.
References driverMetadata(), and tr.
Referenced by driverMetadata().
double QgsVectorFileWriter::mapUnitScaleFactor (double scaleDenominator, QgsSymbolV2::OutputUnit symbolUnits, QGis::UnitType mapUnits) private
Definition at line 2568 of file qgsvectorfilewriter.cpp.
References QgsSymbolV2::MapUnit, QGis::Meters, and QgsSymbolV2::MM.
Referenced by addFeature(), createSymbolLayerTable(), and exportFeaturesSymbolLevels().
double QgsVectorFileWriter::mmScaleFactor (double scaleDenominator, QgsSymbolV2::OutputUnit symbolUnits, QGis::UnitType mapUnits) private
Definition at line 2550 of file qgsvectorfilewriter.cpp.
References QGis::Meters, and QgsSymbolV2::MM.
Referenced by addFeature(), createSymbolLayerTable(), and exportFeaturesSymbolLevels().
QMap< QString, QString > QgsVectorFileWriter::ogrDriverList () static
Returns driver list that can be used for dialogs.
It contains all OGR drivers
some additional internal QGIS driver names to distinguish between more supported formats of the same OGR driver
Definition at line 2067 of file qgsvectorfilewriter.cpp.
References driverMetadata(), QgsApplication::registerOgrDrivers(), and TO8F.
QgsRenderContext QgsVectorFileWriter::renderContext () const private
Definition at line 2584 of file qgsvectorfilewriter.cpp.
References mSymbologyScaleDenominator, and QgsRenderContext::setRendererScale().
Referenced by startRender(), and stopRender().
void QgsVectorFileWriter::setSymbologyExport (SymbologyExport symExport) inline
Definition at line 265 of file qgsvectorfilewriter.h.
void QgsVectorFileWriter::setSymbologyScaleDenominator (double d) inline
Definition at line 268 of file qgsvectorfilewriter.h.
Referenced by writeAsVectorFormat().
void QgsVectorFileWriter::startRender (QgsVectorLayer * vl) const private
Definition at line 2591 of file qgsvectorfilewriter.cpp.
References renderContext(), QgsFeatureRendererV2::startRender(), and symbologyRenderer().
Referenced by exportFeaturesSymbolLevels(), and writeAsVectorFormat().
void QgsVectorFileWriter::stopRender (QgsVectorLayer * vl) const private
Definition at line 2603 of file qgsvectorfilewriter.cpp.
References renderContext(), QgsFeatureRendererV2::stopRender(), and symbologyRenderer().
Referenced by exportFeaturesSymbolLevels(), and writeAsVectorFormat().
QMap< QString, QString > QgsVectorFileWriter::supportedFiltersAndFormats () static
Returns map with format filter string as key and OGR format key as value.
Definition at line 2040 of file qgsvectorfilewriter.cpp.
References filterForDriver(), and QgsApplication::registerOgrDrivers().
Referenced by fileFilterString().
SymbologyExport QgsVectorFileWriter::symbologyExport () const inline
Definition at line 264 of file qgsvectorfilewriter.h.
Referenced by writeAsVectorFormat().
QgsFeatureRendererV2 * QgsVectorFileWriter::symbologyRenderer (QgsVectorLayer * vl) const private
Definition at line 2615 of file qgsvectorfilewriter.cpp.
References mSymbologyExport, NoSymbology, and QgsVectorLayer::rendererV2().
Referenced by addRendererAttributes(), startRender(), and stopRender().
double QgsVectorFileWriter::symbologyScaleDenominator () const inline
Definition at line 267 of file qgsvectorfilewriter.h.
QgsVectorFileWriter::WriterError QgsVectorFileWriter::writeAsVectorFormat (QgsVectorLayer * layer, const QString & fileName, const QString & fileEncoding, const QgsCoordinateReferenceSystem * destCRS, const QString & driverName = "ESRI Shapefile", bool onlySelected = false, QString * errorMessage = 0, const QStringList & datasourceOptions = QStringList(), const QStringList & layerOptions = QStringList(), bool skipAttributeCreation = false, QString * newFilename = 0, SymbologyExport symbologyExport = NoSymbology, double symbologyScale = 1.0) static
Write contents of vector layer to an (OGR supported) vector formt.
@note: this method was added in version 1.5
Parameters
layer layer to write
fileName file name to write to
fileEncoding encoding to use
destCRS pointer to CRS to reproject exported geometries to
driverName OGR driver to use
onlySelected write only selected features of layer
errorMessage pointer to buffer fo error message
datasourceOptions list of OGR data source creation options
layerOptions list of OGR layer creation options
skipAttributeCreation only write geometries
newFilename QString pointer which will contain the new file name created (in case it is different to fileName).
symbologyExport symbology to export
symbologyScale scale of symbology
Definition at line 1782 of file qgsvectorfilewriter.cpp.
References QgsMapLayer::crs().
QgsVectorFileWriter::WriterError QgsVectorFileWriter::writeAsVectorFormat (QgsVectorLayer * layer, const QString & fileName, const QString & fileEncoding, const QgsCoordinateTransform * ct, const QString & driverName = "ESRI Shapefile", bool onlySelected = false, QString * errorMessage = 0, const QStringList & datasourceOptions = QStringList(), const QStringList & layerOptions = QStringList(), bool skipAttributeCreation = false, QString * newFilename = 0, SymbologyExport symbologyExport = NoSymbology, double symbologyScale = 1.0) static
Definition at line 1808 of file qgsvectorfilewriter.cpp.
References addFeature(), addRendererAttributes(), QgsFeatureRendererV2::capabilities(), QgsMapLayer::crs(), QgsVectorLayer::dataProvider(), QgsDataProvider::dataSourceUri(), QgsCoordinateTransform::destCRS(), ErrCreateDataSource, ErrFeatureWriteFailed, ErrInvalidLayer, errorMessage(), ErrProjection, exportFeaturesSymbolLevels(), QgsFeature::geometry(), QgsVectorLayer::getFeatures(), hasError(), QgsFeature::id(), QgsFeature::initAttributes(), QgsCoordinateReferenceSystem::mapUnits(), mLayer, QgsFeatureIterator::nextFeature(), NoError, QgsFeatureRequest::NoGeometry, NoSymbology, QgsVectorLayer::pendingAllAttributesList(), QgsVectorLayer::pendingFields(), QgsVectorLayer::providerType(), QgsDebugMsg, QgsVectorFileWriter(), QgsVectorLayer::rendererV2(), QgsVectorLayer::selectedFeaturesIds(), QgsFeatureRequest::setFlags(), QgsFeatureRequest::setSubsetOfAttributes(), setSymbologyScaleDenominator(), startRender(), stopRender(), SymbolLayerSymbology, QgsFeatureRendererV2::SymbolLevels, symbologyExport(), tr, QgsGeometry::transform(), QgsFeatureRendererV2::usingSymbolLevels(), QgsLogger::warning(), QgsException::what(), QGis::WKBNoGeometry, and QgsVectorLayer::wkbType().
bool QgsVectorFileWriter::writeFeature (OGRLayerH layer, OGRFeatureH feature) private
Definition at line 1755 of file qgsvectorfilewriter.cpp.
References ErrFeatureWriteFailed, QgsMessageLog::logMessage(), mError, mErrorMessage, and tr.
Referenced by addFeature(), and exportFeaturesSymbolLevels().
Member Data Documentation
QMap<int, int> QgsVectorFileWriter::mAttrIdxToOgrIdx protected
map attribute indizes to OGR field indexes
Definition at line 292 of file qgsvectorfilewriter.h.
Referenced by createFeature(), and QgsVectorFileWriter().
QTextCodec* QgsVectorFileWriter::mCodec protected
Definition at line 286 of file qgsvectorfilewriter.h.
Referenced by createFeature(), and QgsVectorFileWriter().
OGRDataSourceH QgsVectorFileWriter::mDS protected
Definition at line 276 of file qgsvectorfilewriter.h.
Referenced by QgsVectorFileWriter(), and ~QgsVectorFileWriter().
WriterError QgsVectorFileWriter::mError protected
contains error value if construction was not successful
Definition at line 283 of file qgsvectorfilewriter.h.
Referenced by createFeature(), hasError(), QgsVectorFileWriter(), and writeFeature().
QString QgsVectorFileWriter::mErrorMessage protected
Definition at line 284 of file qgsvectorfilewriter.h.
Referenced by createFeature(), errorMessage(), QgsVectorFileWriter(), and writeFeature().
QgsFields QgsVectorFileWriter::mFields protected
Definition at line 280 of file qgsvectorfilewriter.h.
Referenced by createFeature(), and QgsVectorFileWriter().
OGRGeometryH QgsVectorFileWriter::mGeom protected
Definition at line 278 of file qgsvectorfilewriter.h.
Referenced by createFeature(), QgsVectorFileWriter(), and ~QgsVectorFileWriter().
OGRLayerH QgsVectorFileWriter::mLayer protected
Definition at line 277 of file qgsvectorfilewriter.h.
Referenced by addFeature(), createFeature(), exportFeaturesSymbolLevels(), QgsVectorFileWriter(), and writeAsVectorFormat().
SymbologyExport QgsVectorFileWriter::mSymbologyExport protected
Definition at line 294 of file qgsvectorfilewriter.h.
Referenced by addFeature(), and symbologyRenderer().
double QgsVectorFileWriter::mSymbologyScaleDenominator protected
Scale for symbology export (e.g.
for symbols units in map units)
Definition at line 301 of file qgsvectorfilewriter.h.
Referenced by addFeature(), createSymbolLayerTable(), exportFeaturesSymbolLevels(), and renderContext().
QGis::WkbType QgsVectorFileWriter::mWkbType protected
geometry type which is being used
Definition at line 289 of file qgsvectorfilewriter.h.
Referenced by createFeature(), and QgsVectorFileWriter().
QMap<QString, MetaData> QgsVectorFileWriter::sDriverMetadata static private
Definition at line 323 of file qgsvectorfilewriter.h.
Referenced by driverMetadata().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorfilewriter.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorfilewriter.cpp