QGIS API Documentation: QgsNewHttpConnection Class Reference
QgsNewHttpConnection Class Reference
Dialog to allow the user to configure and save connection information for an HTTP Server for WMS, etc.
#include <qgsnewhttpconnection.h>
Public Slots
void accept ()
Saves the connection to ~/.qt/qgisrc.
void on_txtName_textChanged (const QString &)
void on_txtUrl_textChanged (const QString &)
void on_buttonBox_helpRequested ()
Public Member Functions
QgsNewHttpConnection (QWidget *parent=0, const QString &baseKey="/Qgis/connections-wms/", const QString &connName=QString::null, Qt::WFlags fl=QgisGui::ModalDialogFlags)
Constructor.
~QgsNewHttpConnection ()
Destructor.
Private Attributes
QString mBaseKey
QString mCredentialsBaseKey
QString mOriginalConnName
Detailed Description
Dialog to allow the user to configure and save connection information for an HTTP Server for WMS, etc.
Definition at line 26 of file qgsnewhttpconnection.h.
Constructor & Destructor Documentation
QgsNewHttpConnection::QgsNewHttpConnection (QWidget * parent = 0, const QString & baseKey = "/Qgis/connections-wms/", const QString & connName = QString::null, Qt::WFlags fl = QgisGui::ModalDialogFlags)
Constructor.
Definition at line 25 of file qgsnewhttpconnection.cpp.
References mBaseKey, mCredentialsBaseKey, on_txtName_textChanged(), and tr.
QgsNewHttpConnection::~QgsNewHttpConnection ()
Destructor.
Definition at line 138 of file qgsnewhttpconnection.cpp.
Member Function Documentation
void QgsNewHttpConnection::accept () slot
Saves the connection to ~/.qt/qgisrc.
Definition at line 154 of file qgsnewhttpconnection.cpp.
References mBaseKey, mCredentialsBaseKey, mOriginalConnName, and tr.
void QgsNewHttpConnection::on_buttonBox_helpRequested () inline slot
Definition at line 43 of file qgsnewhttpconnection.h.
References QgsContextHelp::run().
void QgsNewHttpConnection::on_txtName_textChanged (const QString & text) slot
Definition at line 142 of file qgsnewhttpconnection.cpp.
Referenced by QgsNewHttpConnection().
void QgsNewHttpConnection::on_txtUrl_textChanged (const QString & text) slot
Definition at line 148 of file qgsnewhttpconnection.cpp.
Member Data Documentation
QString QgsNewHttpConnection::mBaseKey private
Definition at line 46 of file qgsnewhttpconnection.h.
Referenced by accept(), and QgsNewHttpConnection().
QString QgsNewHttpConnection::mCredentialsBaseKey private
Definition at line 47 of file qgsnewhttpconnection.h.
Referenced by accept(), and QgsNewHttpConnection().
QString QgsNewHttpConnection::mOriginalConnName private
Definition at line 48 of file qgsnewhttpconnection.h.
Referenced by accept().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsnewhttpconnection.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsnewhttpconnection.cpp