QGIS API Documentation: QgsRelationManagerDialog Class Reference
QgsRelationManagerDialog Class Reference
#include <qgsrelationmanagerdialog.h>
Public Slots
void on_mBtnAddRelation_clicked ()
void on_mBtnRemoveRelation_clicked ()
Public Member Functions
QgsRelationManagerDialog (QgsRelationManager *relationMgr, QWidget *parent=0)
~QgsRelationManagerDialog ()
void setLayers (QList< QgsVectorLayer * >)
void addRelation (const QgsRelation &rel)
QList< QgsRelation > relations ()
Private Attributes
QgsRelationManager * mRelationManager
QList< QgsVectorLayer * > mLayers
Detailed Description
Definition at line 27 of file qgsrelationmanagerdialog.h.
Constructor & Destructor Documentation
QgsRelationManagerDialog::QgsRelationManagerDialog (QgsRelationManager * relationMgr, QWidget * parent = 0) explicit
Definition at line 21 of file qgsrelationmanagerdialog.cpp.
QgsRelationManagerDialog::~QgsRelationManagerDialog ()
Definition at line 29 of file qgsrelationmanagerdialog.cpp.
Member Function Documentation
void QgsRelationManagerDialog::addRelation (const QgsRelation & rel)
Definition at line 45 of file qgsrelationmanagerdialog.cpp.
References QgsRelation::fieldPairs(), QgsRelation::id(), QgsMapLayer::name(), QgsRelation::name(), QgsRelation::referencedLayer(), and QgsRelation::referencingLayer().
Referenced by on_mBtnAddRelation_clicked(), and setLayers().
void QgsRelationManagerDialog::on_mBtnAddRelation_clicked () slot
Definition at line 77 of file qgsrelationmanagerdialog.cpp.
References QgsRelation::addFieldPair(), QgsRelationAddDlg::addLayers(), addRelation(), QgsRelation::id(), mLayers, QgsRelationAddDlg::referencedLayerId(), QgsRelationAddDlg::references(), QgsRelationAddDlg::referencingLayerId(), QgsRelationAddDlg::relationId(), QgsRelationAddDlg::relationName(), relations(), QgsRelation::setReferencedLayer(), QgsRelation::setReferencingLayer(), QgsRelation::setRelationId(), and QgsRelation::setRelationName().
void QgsRelationManagerDialog::on_mBtnRemoveRelation_clicked () slot
Definition at line 119 of file qgsrelationmanagerdialog.cpp.
QList< QgsRelation > QgsRelationManagerDialog::relations ()
Definition at line 125 of file qgsrelationmanagerdialog.cpp.
References QgsRelation::setRelationName().
Referenced by on_mBtnAddRelation_clicked(), and setLayers().
void QgsRelationManagerDialog::setLayers (QList< QgsVectorLayer * > layers)
Definition at line 33 of file qgsrelationmanagerdialog.cpp.
References addRelation(), mLayers, mRelationManager, relations(), and QgsRelationManager::relations().
Member Data Documentation
QList< QgsVectorLayer* > QgsRelationManagerDialog::mLayers private
Definition at line 46 of file qgsrelationmanagerdialog.h.
Referenced by on_mBtnAddRelation_clicked(), and setLayers().
QgsRelationManager* QgsRelationManagerDialog::mRelationManager private
Definition at line 45 of file qgsrelationmanagerdialog.h.
Referenced by setLayers().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsrelationmanagerdialog.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsrelationmanagerdialog.cpp