QGIS API Documentation: QgsFeatureSelectionModel Class Reference
QgsFeatureSelectionModel Class Reference
#include <qgsfeatureselectionmodel.h>
Public Slots
virtual void select (const QModelIndex &index, SelectionFlags command)
Overwritten to do NOTHING (we handle selection ourselves)
virtual void select (const QItemSelection &selection, SelectionFlags command)
Overwritten to do NOTHING (we handle selection ourselves)
virtual void selectFeatures (const QItemSelection &selection, SelectionFlags command)
Select features on this table.
virtual void setFeatureSelectionManager (QgsIFeatureSelectionManager *featureSelectionManager)
Signals
void requestRepaint (QModelIndexList indexes)
Request a repaint of a list of model indexes.
void requestRepaint ()
Request a repaint of the visible items of connected views.
Public Member Functions
QgsFeatureSelectionModel (QAbstractItemModel *model, QgsFeatureModel *featureModel, QgsIFeatureSelectionManager *featureSelectionHandler, QObject *parent)
void enableSync (bool enable)
Enables or disables synchronisation to the QgsVectorLayer When synchronisation is disabled, any selection change will be buffered inside this selection model.
virtual bool isSelected (QgsFeatureId fid)
Returns the selection status of a given feature id.
virtual bool isSelected (const QModelIndex &index)
Returns the selection status of a given QModelIndex.
Private Slots
virtual void layerSelectionChanged (QgsFeatureIds selected, QgsFeatureIds deselected, bool clearAndSelect)
Private Member Functions
QModelIndexList expandIndexToRow (const QModelIndex &index) const
Private Attributes
QgsFeatureModel * mFeatureModel
QgsIFeatureSelectionManager * mFeatureSelectionManager
bool mSyncEnabled
QgsFeatureIds mSelectedBuffer
If sync is disabled Holds a list of newly selected features which will be synced when re-enabled.
QgsFeatureIds mDeselectedBuffer
If sync is disabled Holds a list of newly deselected features which will be synced when re-enabled.
bool mClearAndSelectBuffer
If sync is disabled Is set to true, if a clear and select operation should be performed before syncing.
Detailed Description
Definition at line 12 of file qgsfeatureselectionmodel.h.
Constructor & Destructor Documentation
QgsFeatureSelectionModel::QgsFeatureSelectionModel (QAbstractItemModel * model, QgsFeatureModel * featureModel, QgsIFeatureSelectionManager * featureSelectionHandler, QObject * parent) explicit
Definition at line 8 of file qgsfeatureselectionmodel.cpp.
References setFeatureSelectionManager().
Member Function Documentation
void QgsFeatureSelectionModel::enableSync (bool enable)
Enables or disables synchronisation to the QgsVectorLayer When synchronisation is disabled, any selection change will be buffered inside this selection model.
When enabled, any buffered changes are communicated to the layer and the buffer is emptied. Mainly to be used for performance reasons, because selection change on the layer can cost time as it repaints the layer.
Parameters
enable The synchronisation status to set.
Definition at line 17 of file qgsfeatureselectionmodel.cpp.
References QgsIFeatureSelectionManager::deselect(), mClearAndSelectBuffer, mDeselectedBuffer, mFeatureSelectionManager, mSelectedBuffer, mSyncEnabled, QgsIFeatureSelectionManager::select(), and QgsIFeatureSelectionManager::setSelectedFeatures().
Referenced by QgsAttributeTableView::eventFilter(), QgsFeatureListView::mousePressEvent(), and QgsFeatureListView::mouseReleaseEvent().
QModelIndexList QgsFeatureSelectionModel::expandIndexToRow (const QModelIndex & index) const private
Definition at line 165 of file qgsfeatureselectionmodel.cpp.
Referenced by layerSelectionChanged(), and selectFeatures().
bool QgsFeatureSelectionModel::isSelected (QgsFeatureId fid) virtual
Returns the selection status of a given feature id.
Parameters
fid The featureid to determine the selection status of
Returns
The selection status
Definition at line 39 of file qgsfeatureselectionmodel.cpp.
References mClearAndSelectBuffer, mDeselectedBuffer, mFeatureSelectionManager, mSelectedBuffer, and QgsIFeatureSelectionManager::selectedFeaturesIds().
Referenced by isSelected(), QgsFeatureListViewDelegate::paint(), QgsAttributeTableDelegate::paint(), QgsAttributeTableView::selectRow(), and QgsFeatureListView::selectRow().
bool QgsFeatureSelectionModel::isSelected (const QModelIndex & index) virtual
Returns the selection status of a given QModelIndex.
Parameters
index The index to determine the selection status of
Returns
The selection status
Definition at line 53 of file qgsfeatureselectionmodel.cpp.
References QgsAttributeTableModel::FeatureIdRole, and isSelected().
void QgsFeatureSelectionModel::layerSelectionChanged (QgsFeatureIds selected, QgsFeatureIds deselected, bool clearAndSelect) private virtual slot
Definition at line 142 of file qgsfeatureselectionmodel.cpp.
References expandIndexToRow(), QgsFeatureModel::fidToIndex(), mFeatureModel, and requestRepaint().
Referenced by selectFeatures(), and setFeatureSelectionManager().
void QgsFeatureSelectionModel::requestRepaint (QModelIndexList indexes) signal
Request a repaint of a list of model indexes.
Views using this model should connect to and properly process this signal.
Parameters
indexes The model indexes which need to be repainted
void QgsFeatureSelectionModel::requestRepaint () signal
Request a repaint of the visible items of connected views.
Views using this model should connect to and properly process this signal.
Referenced by layerSelectionChanged(), and selectFeatures().
virtual void QgsFeatureSelectionModel::select (const QModelIndex & index, SelectionFlags command) inline virtual slot
Overwritten to do NOTHING (we handle selection ourselves)
See Also
selectFeatures(const QItemSelection&, SelectionFlags)
Definition at line 68 of file qgsfeatureselectionmodel.h.
virtual void QgsFeatureSelectionModel::select (const QItemSelection & selection, SelectionFlags command) inline virtual slot
Overwritten to do NOTHING (we handle selection ourselves)
See Also
selectFeatures(const QItemSelection&, SelectionFlags)
Definition at line 75 of file qgsfeatureselectionmodel.h.
void QgsFeatureSelectionModel::selectFeatures (const QItemSelection & selection, SelectionFlags command) virtual slot
Select features on this table.
Is to be used in favor of the stock select methods.
Parameters
selection The QItemSelection which will be selected
command The command to apply. Select, Deselect and ClearAndSelect are processed.
Definition at line 58 of file qgsfeatureselectionmodel.cpp.
References QgsIFeatureSelectionManager::deselect(), expandIndexToRow(), QgsAttributeTableModel::FeatureIdRole, index, layerSelectionChanged(), mClearAndSelectBuffer, mDeselectedBuffer, mFeatureSelectionManager, mSelectedBuffer, mSyncEnabled, requestRepaint(), QgsIFeatureSelectionManager::select(), and QgsIFeatureSelectionManager::setSelectedFeatures().
Referenced by QgsAttributeTableView::selectAll(), QgsFeatureListView::selectAll(), QgsAttributeTableView::selectRow(), and QgsFeatureListView::selectRow().
void QgsFeatureSelectionModel::setFeatureSelectionManager (QgsIFeatureSelectionManager * featureSelectionManager) virtual slot
Definition at line 135 of file qgsfeatureselectionmodel.cpp.
References layerSelectionChanged(), and mFeatureSelectionManager.
Referenced by QgsFeatureSelectionModel(), and QgsAttributeTableView::setFeatureSelectionManager().
Member Data Documentation
bool QgsFeatureSelectionModel::mClearAndSelectBuffer private
If sync is disabled Is set to true, if a clear and select operation should be performed before syncing.
Definition at line 108 of file qgsfeatureselectionmodel.h.
Referenced by enableSync(), isSelected(), and selectFeatures().
QgsFeatureIds QgsFeatureSelectionModel::mDeselectedBuffer private
If sync is disabled Holds a list of newly deselected features which will be synced when re-enabled.
Definition at line 104 of file qgsfeatureselectionmodel.h.
Referenced by enableSync(), isSelected(), and selectFeatures().
QgsFeatureModel* QgsFeatureSelectionModel::mFeatureModel private
Definition at line 94 of file qgsfeatureselectionmodel.h.
Referenced by layerSelectionChanged().
QgsIFeatureSelectionManager* QgsFeatureSelectionModel::mFeatureSelectionManager private
Definition at line 95 of file qgsfeatureselectionmodel.h.
Referenced by enableSync(), isSelected(), selectFeatures(), and setFeatureSelectionManager().
QgsFeatureIds QgsFeatureSelectionModel::mSelectedBuffer private
If sync is disabled Holds a list of newly selected features which will be synced when re-enabled.
Definition at line 100 of file qgsfeatureselectionmodel.h.
Referenced by enableSync(), isSelected(), and selectFeatures().
bool QgsFeatureSelectionModel::mSyncEnabled private
Definition at line 96 of file qgsfeatureselectionmodel.h.
Referenced by enableSync(), and selectFeatures().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/attributetable/qgsfeatureselectionmodel.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/attributetable/qgsfeatureselectionmodel.cpp