QGIS API Documentation: QgsVectorLayerUndoCommandChangeAttribute Class Reference
QgsVectorLayerUndoCommandChangeAttribute Class Reference
#include <qgsvectorlayerundocommand.h>
Public Member Functions
QgsVectorLayerUndoCommandChangeAttribute (QgsVectorLayerEditBuffer *buffer, QgsFeatureId fid, int fieldIndex, const QVariant &newValue, const QVariant &oldValue)
virtual void undo ()
virtual void redo ()
Public Member Functions inherited from QgsVectorLayerUndoCommand
QgsVectorLayerUndoCommand (QgsVectorLayerEditBuffer *buffer)
QgsVectorLayer * layer ()
QgsGeometryCache * cache ()
virtual int id () const
virtual bool mergeWith (QUndoCommand *)
Private Attributes
QgsFeatureId mFid
int mFieldIndex
QVariant mOldValue
QVariant mNewValue
bool mFirstChange
Additional Inherited Members
Protected Attributes inherited from QgsVectorLayerUndoCommand
QgsVectorLayerEditBuffer * mBuffer
Detailed Description
Definition at line 98 of file qgsvectorlayerundocommand.h.
Constructor & Destructor Documentation
QgsVectorLayerUndoCommandChangeAttribute::QgsVectorLayerUndoCommandChangeAttribute (QgsVectorLayerEditBuffer * buffer, QgsFeatureId fid, int fieldIndex, const QVariant & newValue, const QVariant & oldValue)
Definition at line 220 of file qgsvectorlayerundocommand.cpp.
References FID_IS_NEW, QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mChangedAttributeValues, mFid, mFieldIndex, mFirstChange, and mOldValue.
Member Function Documentation
void QgsVectorLayerUndoCommandChangeAttribute::redo () virtual
Definition at line 286 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerEditBuffer::attributeValueChanged(), FID_IS_NEW, QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mChangedAttributeValues, mFid, mFieldIndex, and mNewValue.
void QgsVectorLayerUndoCommandChangeAttribute::undo () virtual
Definition at line 247 of file qgsvectorlayerundocommand.cpp.
References QgsFeature::attribute(), QgsVectorLayerEditBuffer::attributeValueChanged(), FID_IS_NEW, QgsVectorLayer::getFeatures(), QgsVectorLayerUndoCommand::layer(), QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, QgsVectorLayerEditBuffer::mChangedAttributeValues, mFid, mFieldIndex, mFirstChange, mOldValue, QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, QgsFeatureRequest::setFilterFid(), QgsFeatureRequest::setFlags(), and QgsFeatureRequest::setSubsetOfAttributes().
Member Data Documentation
QgsFeatureId QgsVectorLayerUndoCommandChangeAttribute::mFid private
Definition at line 106 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandChangeAttribute(), redo(), and undo().
int QgsVectorLayerUndoCommandChangeAttribute::mFieldIndex private
Definition at line 107 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandChangeAttribute(), redo(), and undo().
bool QgsVectorLayerUndoCommandChangeAttribute::mFirstChange private
Definition at line 110 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandChangeAttribute(), and undo().
QVariant QgsVectorLayerUndoCommandChangeAttribute::mNewValue private
Definition at line 109 of file qgsvectorlayerundocommand.h.
Referenced by redo().
QVariant QgsVectorLayerUndoCommandChangeAttribute::mOldValue private
Definition at line 108 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandChangeAttribute(), and undo().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayerundocommand.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayerundocommand.cpp