QGIS API Documentation: QgsRelationAddDlg Class Reference
QgsRelationAddDlg Class Reference
#include <qgsrelationadddlg.h>
Public Member Functions
QgsRelationAddDlg (QWidget *parent=0)
void addLayers (QList< QgsVectorLayer * > layers)
QString referencingLayerId ()
QString referencedLayerId ()
QList< QPair< QString, QString > > references ()
QString relationId ()
QString relationName ()
Private Slots
void on_mCbxReferencingLayer_currentIndexChanged (int index)
void on_mCbxReferencedLayer_currentIndexChanged (int index)
Private Member Functions
void loadLayerAttributes (QComboBox *cbx, QgsVectorLayer *layer)
Private Attributes
QMap< QString, QgsVectorLayer * > mLayers
Detailed Description
Definition at line 9 of file qgsrelationadddlg.h.
Constructor & Destructor Documentation
QgsRelationAddDlg::QgsRelationAddDlg (QWidget * parent = 0) explicit
Definition at line 4 of file qgsrelationadddlg.cpp.
References tr.
Member Function Documentation
void QgsRelationAddDlg::addLayers (QList< QgsVectorLayer * > layers)
Definition at line 12 of file qgsrelationadddlg.cpp.
References QgsMapLayer::id(), mLayers, and QgsMapLayer::name().
Referenced by QgsRelationManagerDialog::on_mBtnAddRelation_clicked().
void QgsRelationAddDlg::loadLayerAttributes (QComboBox * cbx, QgsVectorLayer * layer) private
Definition at line 68 of file qgsrelationadddlg.cpp.
References QgsField::name(), QgsVectorLayer::pendingFields(), and QgsFields::toList().
Referenced by on_mCbxReferencedLayer_currentIndexChanged(), and on_mCbxReferencingLayer_currentIndexChanged().
void QgsRelationAddDlg::on_mCbxReferencedLayer_currentIndexChanged (int index) private slot
Definition at line 63 of file qgsrelationadddlg.cpp.
References loadLayerAttributes(), and mLayers.
void QgsRelationAddDlg::on_mCbxReferencingLayer_currentIndexChanged (int index) private slot
Definition at line 58 of file qgsrelationadddlg.cpp.
References loadLayerAttributes(), and mLayers.
QString QgsRelationAddDlg::referencedLayerId ()
Definition at line 31 of file qgsrelationadddlg.cpp.
Referenced by QgsRelationManagerDialog::on_mBtnAddRelation_clicked().
QList< QPair< QString, QString > > QgsRelationAddDlg::references ()
Definition at line 36 of file qgsrelationadddlg.cpp.
Referenced by QgsRelationManagerDialog::on_mBtnAddRelation_clicked().
QString QgsRelationAddDlg::referencingLayerId ()
Definition at line 26 of file qgsrelationadddlg.cpp.
Referenced by QgsRelationManagerDialog::on_mBtnAddRelation_clicked().
QString QgsRelationAddDlg::relationId ()
Definition at line 48 of file qgsrelationadddlg.cpp.
Referenced by QgsRelationManagerDialog::on_mBtnAddRelation_clicked().
QString QgsRelationAddDlg::relationName ()
Definition at line 53 of file qgsrelationadddlg.cpp.
Referenced by QgsRelationManagerDialog::on_mBtnAddRelation_clicked().
Member Data Documentation
QMap< QString, QgsVectorLayer* > QgsRelationAddDlg::mLayers private
Definition at line 32 of file qgsrelationadddlg.h.
Referenced by addLayers(), on_mCbxReferencedLayer_currentIndexChanged(), and on_mCbxReferencingLayer_currentIndexChanged().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsrelationadddlg.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsrelationadddlg.cpp