QGIS API Documentation: QgsRasterDrawer Class Reference
QgsRasterDrawer Class Reference
QGIS core library
The drawing pipe for raster layers.
#include <qgsrasterdrawer.h>
Public Member Functions
QgsRasterDrawer (QgsRasterIterator *iterator)
~QgsRasterDrawer ()
void draw (QPainter *p, QgsRasterViewPort *viewPort, const QgsMapToPixel *theQgsMapToPixel)
Protected Member Functions
void drawImage (QPainter *p, QgsRasterViewPort *viewPort, const QImage &img, int topLeftCol, int topLeftRow) const
Draws raster part.
Private Attributes
QgsRasterIterator * mIterator
Detailed Description
The drawing pipe for raster layers.
Definition at line 33 of file qgsrasterdrawer.h.
Constructor & Destructor Documentation
QgsRasterDrawer::QgsRasterDrawer (QgsRasterIterator * iterator)
Definition at line 27 of file qgsrasterdrawer.cpp.
QgsRasterDrawer::~QgsRasterDrawer ()
Definition at line 31 of file qgsrasterdrawer.cpp.
Member Function Documentation
void QgsRasterDrawer::draw (QPainter * p, QgsRasterViewPort * viewPort, const QgsMapToPixel * theQgsMapToPixel)
Definition at line 35 of file qgsrasterdrawer.cpp.
References drawImage(), QgsRasterBlock::image(), QgsRasterViewPort::mDrawnExtent, QgsRasterViewPort::mHeight, mIterator, QgsRasterViewPort::mWidth, QgsDebugMsg, QgsRasterIterator::readNextRasterPart(), and QgsRasterIterator::startRasterRead().
void QgsRasterDrawer::drawImage (QPainter * p, QgsRasterViewPort * viewPort, const QImage & img, int topLeftCol, int topLeftRow) const protected
Draws raster part.
Parameters
p the painter to draw to
viewPort view port to draw to
img image to draw
topLeftCol Left position relative to left border of viewport
topLeftRow Top position relative to top border of viewport
Definition at line 98 of file qgsrasterdrawer.cpp.
References QgsRasterViewPort::mTopLeftPoint, QgsPoint::x(), and QgsPoint::y().
Referenced by draw().
Member Data Documentation
QgsRasterIterator* QgsRasterDrawer::mIterator private
Definition at line 51 of file qgsrasterdrawer.h.
Referenced by draw().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/raster/qgsrasterdrawer.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/raster/qgsrasterdrawer.cpp