QGIS API Documentation: QgsFieldValidator Class Reference
QgsFieldValidator Class Reference
#include <qgsfieldvalidator.h>
Public Member Functions
QgsFieldValidator (QObject *parent, const QgsField &field, QString dateFormat)
~QgsFieldValidator ()
virtual State validate (QString &, int &) const
virtual void fixup (QString &) const
QString dateFormat () const
Private Attributes
QValidator * mValidator
QgsField mField
QString mNullValue
QString mDateFormat
Detailed Description
Definition at line 29 of file qgsfieldvalidator.h.
Constructor & Destructor Documentation
QgsFieldValidator::QgsFieldValidator (QObject * parent, const QgsField & field, QString dateFormat)
Definition at line 32 of file qgsfieldvalidator.cpp.
References QgsField::length(), mField, mNullValue, mValidator, QgsField::precision(), and QgsField::type().
QgsFieldValidator::~QgsFieldValidator ()
Definition at line 89 of file qgsfieldvalidator.cpp.
References mValidator.
Member Function Documentation
QString QgsFieldValidator::dateFormat () const inline
Definition at line 40 of file qgsfieldvalidator.h.
Referenced by QgsAttributeEditor::selectDate().
void QgsFieldValidator::fixup (QString & s) const virtual
Definition at line 143 of file qgsfieldvalidator.cpp.
References QgsField::length(), mField, mNullValue, mValidator, and QgsField::type().
QValidator::State QgsFieldValidator::validate (QString & s, int & i) const virtual
Definition at line 94 of file qgsfieldvalidator.cpp.
References QgsField::length(), mDateFormat, mField, mNullValue, mValidator, QgsDebugMsg, and QgsField::type().
Member Data Documentation
QString QgsFieldValidator::mDateFormat private
Definition at line 49 of file qgsfieldvalidator.h.
Referenced by validate().
QgsField QgsFieldValidator::mField private
Definition at line 47 of file qgsfieldvalidator.h.
Referenced by fixup(), QgsFieldValidator(), and validate().
QString QgsFieldValidator::mNullValue private
Definition at line 48 of file qgsfieldvalidator.h.
Referenced by fixup(), QgsFieldValidator(), and validate().
QValidator* QgsFieldValidator::mValidator private
Definition at line 46 of file qgsfieldvalidator.h.
Referenced by fixup(), QgsFieldValidator(), validate(), and ~QgsFieldValidator().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsfieldvalidator.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/gui/qgsfieldvalidator.cpp