QGIS API Documentation: QgsVectorLayerUndoCommandAddFeature Class Reference
QgsVectorLayerUndoCommandAddFeature Class Reference
#include <qgsvectorlayerundocommand.h>
Public Member Functions
QgsVectorLayerUndoCommandAddFeature (QgsVectorLayerEditBuffer *buffer, QgsFeature &f)
virtual void undo ()
virtual void redo ()
Public Member Functions inherited from QgsVectorLayerUndoCommand
QgsVectorLayerUndoCommand (QgsVectorLayerEditBuffer *buffer)
QgsVectorLayer * layer ()
QgsGeometryCache * cache ()
virtual int id () const
virtual bool mergeWith (QUndoCommand *)
Private Attributes
QgsFeature mFeature
Additional Inherited Members
Protected Attributes inherited from QgsVectorLayerUndoCommand
QgsVectorLayerEditBuffer * mBuffer
Detailed Description
Definition at line 53 of file qgsvectorlayerundocommand.h.
Constructor & Destructor Documentation
QgsVectorLayerUndoCommandAddFeature::QgsVectorLayerUndoCommandAddFeature (QgsVectorLayerEditBuffer * buffer, QgsFeature & f)
Definition at line 27 of file qgsvectorlayerundocommand.cpp.
References mFeature, QgsDebugMsg, and QgsFeature::setFeatureId().
Member Function Documentation
void QgsVectorLayerUndoCommandAddFeature::redo () virtual
Definition at line 59 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerUndoCommand::cache(), QgsGeometryCache::cacheGeometry(), QgsVectorLayerEditBuffer::featureAdded(), QgsFeature::geometry(), QgsFeature::id(), QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, and mFeature.
void QgsVectorLayerUndoCommandAddFeature::undo () virtual
Definition at line 45 of file qgsvectorlayerundocommand.cpp.
References QgsVectorLayerUndoCommand::cache(), QgsVectorLayerEditBuffer::featureDeleted(), QgsFeature::geometry(), QgsFeature::id(), QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerUndoCommand::mBuffer, mFeature, and QgsGeometryCache::removeGeometry().
Member Data Documentation
QgsFeature QgsVectorLayerUndoCommandAddFeature::mFeature private
Definition at line 62 of file qgsvectorlayerundocommand.h.
Referenced by QgsVectorLayerUndoCommandAddFeature(), redo(), and undo().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayerundocommand.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayerundocommand.cpp