QGIS API Documentation: QgsLabelComponent Class Reference
QgsLabelComponent Class Reference
QGIS core library
Maintains current state of more grainular and temporal values when creating/painting component parts of an individual label (e.g.
#include <qgspallabeling.h>
Public Member Functions
QgsLabelComponent ()
const QString & text ()
void setText (const QString &text)
const QgsPoint & origin ()
void setOrigin (QgsPoint point)
bool useOrigin () const
void setUseOrigin (bool use)
double rotation () const
void setRotation (double rotation)
double rotationOffset () const
void setRotationOffset (double rotation)
bool useRotation () const
void setUseRotation (bool use)
const QgsPoint & center ()
void setCenter (QgsPoint point)
bool useCenter () const
void setUseCenter (bool use)
const QgsPoint & size ()
void setSize (QgsPoint point)
const QgsPoint & offset ()
void setOffset (QgsPoint point)
const QPicture * picture ()
void setPicture (QPicture *picture)
double pictureBuffer () const
void setPictureBuffer (double buffer)
double dpiRatio () const
void setDpiRatio (double ratio)
Private Attributes
QString mText
QgsPoint mOrigin
bool mUseOrigin
double mRotation
double mRotationOffset
bool mUseRotation
QgsPoint mCenter
bool mUseCenter
QgsPoint mSize
QgsPoint mOffset
QPicture * mPicture
double mPictureBuffer
double mDpiRatio
Detailed Description
Maintains current state of more grainular and temporal values when creating/painting component parts of an individual label (e.g.
buffer, background, shadow, etc.).
Definition at line 563 of file qgspallabeling.h.
Constructor & Destructor Documentation
QgsLabelComponent::QgsLabelComponent () inline
Definition at line 566 of file qgspallabeling.h.
Member Function Documentation
const QgsPoint& QgsLabelComponent::center () inline
Definition at line 600 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabelBackground().
double QgsLabelComponent::dpiRatio () const inline
Definition at line 618 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), QgsPalLabeling::drawLabelBackground(), QgsPalLabeling::drawLabelBuffer(), and QgsPalLabeling::drawLabelShadow().
const QgsPoint& QgsLabelComponent::offset () inline
Definition at line 609 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabelShadow().
const QgsPoint& QgsLabelComponent::origin () inline
Definition at line 585 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabelShadow().
const QPicture* QgsLabelComponent::picture () inline
Definition at line 612 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabelShadow().
double QgsLabelComponent::pictureBuffer () const inline
Definition at line 615 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabelShadow().
double QgsLabelComponent::rotation () const inline
Definition at line 591 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), QgsPalLabeling::drawLabelBackground(), and QgsPalLabeling::drawLabelShadow().
double QgsLabelComponent::rotationOffset () const inline
Definition at line 594 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabelBackground(), and QgsPalLabeling::drawLabelShadow().
void QgsLabelComponent::setCenter (QgsPoint point) inline
Definition at line 601 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel().
void QgsLabelComponent::setDpiRatio (double ratio) inline
Definition at line 619 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel().
void QgsLabelComponent::setOffset (QgsPoint point) inline
Definition at line 610 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), and QgsPalLabeling::drawLabelBackground().
void QgsLabelComponent::setOrigin (QgsPoint point) inline
Definition at line 586 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), and QgsPalLabeling::drawLabelBuffer().
void QgsLabelComponent::setPicture (QPicture * picture) inline
Definition at line 613 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), QgsPalLabeling::drawLabelBackground(), and QgsPalLabeling::drawLabelBuffer().
void QgsLabelComponent::setPictureBuffer (double buffer) inline
Definition at line 616 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), QgsPalLabeling::drawLabelBackground(), and QgsPalLabeling::drawLabelBuffer().
void QgsLabelComponent::setRotation (double rotation) inline
Definition at line 592 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), and QgsPalLabeling::drawLabelBackground().
void QgsLabelComponent::setRotationOffset (double rotation) inline
Definition at line 595 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), and QgsPalLabeling::drawLabelBackground().
void QgsLabelComponent::setSize (QgsPoint point) inline
Definition at line 607 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), and QgsPalLabeling::drawLabelBackground().
void QgsLabelComponent::setText (const QString & text) inline
Definition at line 583 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel().
void QgsLabelComponent::setUseCenter (bool use) inline
Definition at line 604 of file qgspallabeling.h.
void QgsLabelComponent::setUseOrigin (bool use) inline
Definition at line 589 of file qgspallabeling.h.
void QgsLabelComponent::setUseRotation (bool use) inline
Definition at line 598 of file qgspallabeling.h.
const QgsPoint& QgsLabelComponent::size (void) inline
Definition at line 606 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabelBackground(), and QgsPalLabeling::drawLabelShadow().
const QString& QgsLabelComponent::text (void) inline
Definition at line 582 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabel(), and QgsPalLabeling::drawLabelBuffer().
bool QgsLabelComponent::useCenter () const inline
Definition at line 603 of file qgspallabeling.h.
bool QgsLabelComponent::useOrigin () const inline
Definition at line 588 of file qgspallabeling.h.
Referenced by QgsPalLabeling::drawLabelShadow().
bool QgsLabelComponent::useRotation () const inline
Definition at line 597 of file qgspallabeling.h.
Member Data Documentation
QgsPoint QgsLabelComponent::mCenter private
Definition at line 636 of file qgspallabeling.h.
double QgsLabelComponent::mDpiRatio private
Definition at line 651 of file qgspallabeling.h.
QgsPoint QgsLabelComponent::mOffset private
Definition at line 642 of file qgspallabeling.h.
QgsPoint QgsLabelComponent::mOrigin private
Definition at line 626 of file qgspallabeling.h.
QPicture* QgsLabelComponent::mPicture private
Definition at line 645 of file qgspallabeling.h.
double QgsLabelComponent::mPictureBuffer private
Definition at line 648 of file qgspallabeling.h.
double QgsLabelComponent::mRotation private
Definition at line 630 of file qgspallabeling.h.
double QgsLabelComponent::mRotationOffset private
Definition at line 632 of file qgspallabeling.h.
QgsPoint QgsLabelComponent::mSize private
Definition at line 640 of file qgspallabeling.h.
QString QgsLabelComponent::mText private
Definition at line 624 of file qgspallabeling.h.
bool QgsLabelComponent::mUseCenter private
Definition at line 638 of file qgspallabeling.h.
bool QgsLabelComponent::mUseOrigin private
Definition at line 628 of file qgspallabeling.h.
bool QgsLabelComponent::mUseRotation private
Definition at line 634 of file qgspallabeling.h.
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgspallabeling.h