QGIS API Documentation: QgsAttributeEditorRelation Class Reference
QgsAttributeEditorRelation Class Reference
#include <qgsvectorlayer.h>
Public Member Functions
QgsAttributeEditorRelation (QString name, const QString &relationId, QObject *parent)
QgsAttributeEditorRelation (QString name, const QgsRelation &relation, QObject *parent)
~QgsAttributeEditorRelation ()
virtual QDomElement toDomElement (QDomDocument &doc) const
const QgsRelation & relation () const
bool init (QgsRelationManager *relManager)
Initializes the relation from the id.
Public Member Functions inherited from QgsAttributeEditorElement
QgsAttributeEditorElement (AttributeEditorType type, QString name, QObject *parent=NULL)
virtual ~QgsAttributeEditorElement ()
QString name () const
AttributeEditorType type () const
Private Attributes
QString mRelationId
QgsRelation mRelation
Additional Inherited Members
Public Types inherited from QgsAttributeEditorElement
enum AttributeEditorType { AeTypeContainer, AeTypeField, AeTypeRelation, AeTypeInvalid }
Protected Attributes inherited from QgsAttributeEditorElement
AttributeEditorType mType
QString mName
Detailed Description
Note
Added in 2.1
Definition at line 131 of file qgsvectorlayer.h.
Constructor & Destructor Documentation
QgsAttributeEditorRelation::QgsAttributeEditorRelation (QString name, const QString & relationId, QObject * parent) inline
Definition at line 134 of file qgsvectorlayer.h.
QgsAttributeEditorRelation::QgsAttributeEditorRelation (QString name, const QgsRelation & relation, QObject * parent) inline
Definition at line 138 of file qgsvectorlayer.h.
QgsAttributeEditorRelation::~QgsAttributeEditorRelation () inline
Definition at line 143 of file qgsvectorlayer.h.
Member Function Documentation
bool QgsAttributeEditorRelation::init (QgsRelationManager * relManager)
Initializes the relation from the id.
Parameters
relManager The relation manager to use for the initialization
Returns
true if the relation was found in the relationmanager
Definition at line 4480 of file qgsvectorlayer.cpp.
References QgsRelation::isValid(), mRelation, mRelationId, and QgsRelationManager::relation().
Referenced by QgsVectorLayer::onRelationsLoaded().
const QgsRelation& QgsAttributeEditorRelation::relation () const inline
Definition at line 146 of file qgsvectorlayer.h.
Referenced by QgsAttributeEditor::createWidgetFromDef().
QDomElement QgsAttributeEditorRelation::toDomElement (QDomDocument & doc) const virtual
Implements QgsAttributeEditorElement.
Definition at line 4472 of file qgsvectorlayer.cpp.
References QgsRelation::id(), QgsAttributeEditorElement::mName, and mRelation.
Member Data Documentation
QgsRelation QgsAttributeEditorRelation::mRelation private
Definition at line 158 of file qgsvectorlayer.h.
Referenced by init(), and toDomElement().
QString QgsAttributeEditorRelation::mRelationId private
Definition at line 157 of file qgsvectorlayer.h.
Referenced by init().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayer.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayer.cpp