QGIS API Documentation: QgsSimpleLineSymbolLayerV2 Class Reference
QgsSimpleLineSymbolLayerV2 Class Reference
#include <qgslinesymbollayerv2.h>
Public Member Functions
QgsSimpleLineSymbolLayerV2 (QColor color=DEFAULT_SIMPLELINE_COLOR, double width=DEFAULT_SIMPLELINE_WIDTH, Qt::PenStyle penStyle=DEFAULT_SIMPLELINE_PENSTYLE)
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
void renderPolyline (const QPolygonF &points, QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
Qt::PenStyle penStyle () const
void setPenStyle (Qt::PenStyle style)
Qt::PenJoinStyle penJoinStyle () const
void setPenJoinStyle (Qt::PenJoinStyle style)
Qt::PenCapStyle penCapStyle () const
void setPenCapStyle (Qt::PenCapStyle style)
double offset () const
void setOffset (double offset)
QgsSymbolV2::OutputUnit offsetUnit () const
void setOffsetUnit (QgsSymbolV2::OutputUnit unit)
bool useCustomDashPattern () const
void setUseCustomDashPattern (bool b)
QgsSymbolV2::OutputUnit customDashPatternUnit () const
void setCustomDashPatternUnit (QgsSymbolV2::OutputUnit unit)
QVector< qreal > customDashVector () const
void setCustomDashVector (const QVector< qreal > &vector)
bool drawInsidePolygon () const
void setDrawInsidePolygon (bool drawInsidePolygon)
QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
Qt::PenStyle dxfPenStyle () const
double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
QColor dxfColor (const QgsSymbolV2RenderContext &context) const
Public Member Functions inherited from QgsLineSymbolLayerV2
virtual void renderPolygonOutline (const QPolygonF &points, QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
virtual void setWidth (double width)
virtual double width () const
void setWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit widthUnit () const
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QgsSymbolV2 * subSymbol ()
virtual bool setSubSymbol (QgsSymbolV2 *symbol)
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual QSet< QString > usedAttributes () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Protected Attributes
Qt::PenStyle mPenStyle
Qt::PenJoinStyle mPenJoinStyle
Qt::PenCapStyle mPenCapStyle
QPen mPen
QPen mSelPen
double mOffset
QgsSymbolV2::OutputUnit mOffsetUnit
bool mUseCustomDashPattern
QgsSymbolV2::OutputUnit mCustomDashPatternUnit
QVector< qreal > mCustomDashVector
Vector with an even number of entries for the.
bool mDrawInsidePolygon
Protected Attributes inherited from QgsLineSymbolLayerV2
double mWidth
QgsSymbolV2::OutputUnit mWidthUnit
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Private Member Functions
void applyDataDefinedSymbology (QgsSymbolV2RenderContext &context, QPen &pen, QPen &selPen, double &offset)
Additional Inherited Members
Protected Member Functions inherited from QgsLineSymbolLayerV2
QgsLineSymbolLayerV2 (bool locked=false)
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 33 of file qgslinesymbollayerv2.h.
Constructor & Destructor Documentation
QgsSimpleLineSymbolLayerV2::QgsSimpleLineSymbolLayerV2 (QColor color = DEFAULT_SIMPLELINE_COLOR, double width = DEFAULT_SIMPLELINE_WIDTH, Qt::PenStyle penStyle = DEFAULT_SIMPLELINE_PENSTYLE)
Definition at line 31 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2::color(), QgsSymbolLayerV2::mColor, mCustomDashVector, QgsLineSymbolLayerV2::mWidth, and QgsLineSymbolLayerV2::width().
Referenced by clone(), create(), and createFromSld().
Member Function Documentation
void QgsSimpleLineSymbolLayerV2::applyDataDefinedSymbology (QgsSymbolV2RenderContext & context, QPen & pen, QPen & selPen, double & offset) private
Definition at line 345 of file qgslinesymbollayerv2.cpp.
References QgsSymbolV2::DataDefinedSizeScale, QgsSymbolLayerV2Utils::decodeColor(), QgsSymbolLayerV2Utils::decodePenCapStyle(), QgsSymbolLayerV2Utils::decodePenJoinStyle(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mCustomDashPatternUnit, mOffset, mPen, QgsLineSymbolLayerV2::mWidth, QgsLineSymbolLayerV2::mWidthUnit, QgsSymbolV2RenderContext::renderContext(), and QgsSymbolV2RenderContext::renderHints().
Referenced by renderPolyline().
QgsSymbolLayerV2 * QgsSimpleLineSymbolLayerV2::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 244 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2::copyDataDefinedProperties(), QgsSymbolLayerV2::mColor, mCustomDashPatternUnit, mCustomDashVector, mDrawInsidePolygon, mOffset, mOffsetUnit, mPenCapStyle, mPenJoinStyle, mPenStyle, mUseCustomDashPattern, QgsLineSymbolLayerV2::mWidth, QgsLineSymbolLayerV2::mWidthUnit, QgsSimpleLineSymbolLayerV2(), setCustomDashPatternUnit(), setCustomDashVector(), setDrawInsidePolygon(), setOffset(), setOffsetUnit(), setPenCapStyle(), setPenJoinStyle(), setUseCustomDashPattern(), and QgsLineSymbolLayerV2::setWidthUnit().
QgsSymbolLayerV2 * QgsSimpleLineSymbolLayerV2::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 58 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2::color(), QgsSymbolLayerV2Utils::decodeColor(), QgsSymbolLayerV2Utils::decodeOutputUnit(), QgsSymbolLayerV2Utils::decodePenCapStyle(), QgsSymbolLayerV2Utils::decodePenJoinStyle(), QgsSymbolLayerV2Utils::decodePenStyle(), QgsSymbolLayerV2Utils::decodeRealVector(), DEFAULT_SIMPLELINE_COLOR, DEFAULT_SIMPLELINE_PENSTYLE, DEFAULT_SIMPLELINE_WIDTH, penStyle(), QgsSimpleLineSymbolLayerV2(), setCustomDashPatternUnit(), setCustomDashVector(), QgsSymbolLayerV2::setDataDefinedProperty(), setDrawInsidePolygon(), setOffset(), setOffsetUnit(), setPenCapStyle(), setPenJoinStyle(), setUseCustomDashPattern(), QgsLineSymbolLayerV2::setWidthUnit(), and QgsLineSymbolLayerV2::width().
Referenced by QgsLineSymbolV2::createSimple(), QgsSymbolLayerV2Registry::defaultSymbolLayer(), and QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsSimpleLineSymbolLayerV2::createFromSld (QDomElement & element) static
Definition at line 305 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2::color(), customDashVector(), QgsSymbolLayerV2Utils::lineFromSld(), offset(), penCapStyle(), penJoinStyle(), penStyle(), QgsDebugMsg, QgsSimpleLineSymbolLayerV2(), setCustomDashVector(), setOffset(), setPenCapStyle(), setPenJoinStyle(), setUseCustomDashPattern(), and QgsLineSymbolLayerV2::width().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolV2::OutputUnit QgsSimpleLineSymbolLayerV2::customDashPatternUnit () const inline
Definition at line 88 of file qgslinesymbollayerv2.h.
QVector<qreal> QgsSimpleLineSymbolLayerV2::customDashVector () const inline
Definition at line 91 of file qgslinesymbollayerv2.h.
Referenced by createFromSld().
bool QgsSimpleLineSymbolLayerV2::drawInsidePolygon () const inline
Definition at line 95 of file qgslinesymbollayerv2.h.
QColor QgsSimpleLineSymbolLayerV2::dxfColor (const QgsSymbolV2RenderContext & context) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 450 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::decodeColor(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), and QgsSymbolLayerV2::mColor.
QVector< qreal > QgsSimpleLineSymbolLayerV2::dxfCustomDashPattern (QgsSymbolV2::OutputUnit & unit) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 423 of file qgslinesymbollayerv2.cpp.
References mCustomDashPatternUnit, mCustomDashVector, and mUseCustomDashPattern.
Qt::PenStyle QgsSimpleLineSymbolLayerV2::dxfPenStyle () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 429 of file qgslinesymbollayerv2.cpp.
References mPenStyle.
double QgsSimpleLineSymbolLayerV2::dxfWidth (const QgsDxfExport & e, const QgsSymbolV2RenderContext & context) const virtual
Reimplemented from QgsLineSymbolLayerV2.
Definition at line 434 of file qgslinesymbollayerv2.cpp.
References QgsSymbolV2::DataDefinedSizeScale, QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsLineSymbolLayerV2::mWidth, QgsLineSymbolLayerV2::mWidthUnit, QgsSymbolV2RenderContext::renderContext(), QgsSymbolV2RenderContext::renderHints(), QgsLineSymbolLayerV2::width(), and QgsLineSymbolLayerV2::widthUnit().
double QgsSimpleLineSymbolLayerV2::estimateMaxBleed () const virtual
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
Eg, polygons drawn with an outline will draw half the width of the outline outside of the polygon. This amount is estimated, since it may be affected by data defined symbology rules.
Reimplemented from QgsSymbolLayerV2.
Definition at line 410 of file qgslinesymbollayerv2.cpp.
References mDrawInsidePolygon, mOffset, and QgsLineSymbolLayerV2::mWidth.
QString QgsSimpleLineSymbolLayerV2::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 120 of file qgslinesymbollayerv2.cpp.
double QgsSimpleLineSymbolLayerV2::offset () const inline
Definition at line 79 of file qgslinesymbollayerv2.h.
Referenced by createFromSld(), and renderPolyline().
QgsSymbolV2::OutputUnit QgsSimpleLineSymbolLayerV2::offsetUnit () const inline
Definition at line 82 of file qgslinesymbollayerv2.h.
QString QgsSimpleLineSymbolLayerV2::ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 290 of file qgslinesymbollayerv2.cpp.
References mCustomDashVector, mOffset, mPen, mPenCapStyle, mPenJoinStyle, mUseCustomDashPattern, QgsLineSymbolLayerV2::mWidth, and QgsSymbolLayerV2Utils::ogrFeatureStylePen().
QgsSymbolV2::OutputUnit QgsSimpleLineSymbolLayerV2::outputUnit () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 47 of file qgslinesymbollayerv2.cpp.
References mCustomDashPatternUnit, QgsSymbolV2::Mixed, mOffsetUnit, and QgsLineSymbolLayerV2::mWidthUnit.
Qt::PenCapStyle QgsSimpleLineSymbolLayerV2::penCapStyle () const inline
Definition at line 76 of file qgslinesymbollayerv2.h.
Referenced by createFromSld().
Qt::PenJoinStyle QgsSimpleLineSymbolLayerV2::penJoinStyle () const inline
Definition at line 73 of file qgslinesymbollayerv2.h.
Referenced by createFromSld().
Qt::PenStyle QgsSimpleLineSymbolLayerV2::penStyle () const inline
Definition at line 70 of file qgslinesymbollayerv2.h.
Referenced by create(), createFromSld(), and toSld().
QgsStringMap QgsSimpleLineSymbolLayerV2::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 225 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeColor(), QgsSymbolLayerV2Utils::encodeOutputUnit(), QgsSymbolLayerV2Utils::encodePenCapStyle(), QgsSymbolLayerV2Utils::encodePenJoinStyle(), QgsSymbolLayerV2Utils::encodePenStyle(), QgsSymbolLayerV2Utils::encodeRealVector(), QgsSymbolLayerV2::mColor, mCustomDashPatternUnit, mCustomDashVector, mDrawInsidePolygon, mOffset, mOffsetUnit, mPenCapStyle, mPenJoinStyle, mPenStyle, mUseCustomDashPattern, QgsLineSymbolLayerV2::mWidth, QgsLineSymbolLayerV2::mWidthUnit, and QgsSymbolLayerV2::saveDataDefinedProperties().
void QgsSimpleLineSymbolLayerV2::renderPolyline (const QPolygonF & points, QgsSymbolV2RenderContext & context) virtual
Implements QgsLineSymbolLayerV2.
Definition at line 177 of file qgslinesymbollayerv2.cpp.
References QgsVectorSimplifyMethod::AntialiasingSimplification, applyDataDefinedSymbology(), QgsAbstractGeometrySimplifier::canbeGeneralizedByDeviceBoundingBox(), QgsSymbolV2RenderContext::layer(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), mDrawInsidePolygon, mOffsetUnit, mPen, mSelPen, offset(), offsetLine(), QgsRenderContext::painter(), QgsSymbolV2RenderContext::renderContext(), QgsSymbolV2RenderContext::selected(), QgsVectorLayer::simplifyDrawingCanbeApplied(), QgsVectorLayer::simplifyMethod(), and QgsVectorSimplifyMethod::threshold().
void QgsSimpleLineSymbolLayerV2::setCustomDashPatternUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 89 of file qgslinesymbollayerv2.h.
Referenced by clone(), and create().
void QgsSimpleLineSymbolLayerV2::setCustomDashVector (const QVector< qreal > & vector) inline
Definition at line 92 of file qgslinesymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSimpleLineSymbolLayerV2::setDrawInsidePolygon (bool drawInsidePolygon) inline
Definition at line 97 of file qgslinesymbollayerv2.h.
Referenced by clone(), and create().
void QgsSimpleLineSymbolLayerV2::setOffset (double offset) inline
Definition at line 80 of file qgslinesymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSimpleLineSymbolLayerV2::setOffsetUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 83 of file qgslinesymbollayerv2.h.
Referenced by clone(), and create().
void QgsSimpleLineSymbolLayerV2::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 40 of file qgslinesymbollayerv2.cpp.
References mCustomDashPatternUnit, mOffsetUnit, and QgsLineSymbolLayerV2::mWidthUnit.
void QgsSimpleLineSymbolLayerV2::setPenCapStyle (Qt::PenCapStyle style) inline
Definition at line 77 of file qgslinesymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSimpleLineSymbolLayerV2::setPenJoinStyle (Qt::PenJoinStyle style) inline
Definition at line 74 of file qgslinesymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSimpleLineSymbolLayerV2::setPenStyle (Qt::PenStyle style) inline
Definition at line 71 of file qgslinesymbollayerv2.h.
void QgsSimpleLineSymbolLayerV2::setUseCustomDashPattern (bool b) inline
Definition at line 86 of file qgslinesymbollayerv2.h.
Referenced by clone(), create(), and createFromSld().
void QgsSimpleLineSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 125 of file qgslinesymbollayerv2.cpp.
References QgsSymbolV2RenderContext::alpha(), QgsSymbolV2RenderContext::layer(), QgsSymbolLayerV2Utils::lineWidthScaleFactor(), QgsSymbolLayerV2::mColor, mCustomDashPatternUnit, mCustomDashVector, mPen, mPenCapStyle, mPenJoinStyle, mPenStyle, mSelPen, mUseCustomDashPattern, QgsLineSymbolLayerV2::mWidth, QgsLineSymbolLayerV2::mWidthUnit, QgsSymbolLayerV2::prepareExpressions(), QgsRenderContext::rasterScaleFactor(), QgsSymbolV2RenderContext::renderContext(), QgsRenderContext::rendererScale(), QgsRenderContext::selectionColor(), and QgsSymbolLayerV2::selectionIsOpaque.
void QgsSimpleLineSymbolLayerV2::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 172 of file qgslinesymbollayerv2.cpp.
void QgsSimpleLineSymbolLayerV2::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 260 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::createGeometryElement(), QgsSymbolLayerV2Utils::lineToSld(), QgsSymbolLayerV2::mColor, mCustomDashVector, mOffset, mPenCapStyle, mPenJoinStyle, mPenStyle, mUseCustomDashPattern, QgsLineSymbolLayerV2::mWidth, and penStyle().
bool QgsSimpleLineSymbolLayerV2::useCustomDashPattern () const inline
Definition at line 85 of file qgslinesymbollayerv2.h.
Member Data Documentation
QgsSymbolV2::OutputUnit QgsSimpleLineSymbolLayerV2::mCustomDashPatternUnit protected
Definition at line 116 of file qgslinesymbollayerv2.h.
Referenced by applyDataDefinedSymbology(), clone(), dxfCustomDashPattern(), outputUnit(), properties(), setOutputUnit(), and startRender().
QVector<qreal> QgsSimpleLineSymbolLayerV2::mCustomDashVector protected
Vector with an even number of entries for the.
Definition at line 119 of file qgslinesymbollayerv2.h.
Referenced by clone(), dxfCustomDashPattern(), ogrFeatureStyle(), properties(), QgsSimpleLineSymbolLayerV2(), startRender(), and toSld().
bool QgsSimpleLineSymbolLayerV2::mDrawInsidePolygon protected
Definition at line 121 of file qgslinesymbollayerv2.h.
Referenced by clone(), estimateMaxBleed(), properties(), and renderPolyline().
double QgsSimpleLineSymbolLayerV2::mOffset protected
Definition at line 111 of file qgslinesymbollayerv2.h.
Referenced by applyDataDefinedSymbology(), clone(), estimateMaxBleed(), ogrFeatureStyle(), properties(), and toSld().
QgsSymbolV2::OutputUnit QgsSimpleLineSymbolLayerV2::mOffsetUnit protected
Definition at line 112 of file qgslinesymbollayerv2.h.
Referenced by clone(), outputUnit(), properties(), renderPolyline(), and setOutputUnit().
QPen QgsSimpleLineSymbolLayerV2::mPen protected
Definition at line 109 of file qgslinesymbollayerv2.h.
Referenced by applyDataDefinedSymbology(), ogrFeatureStyle(), renderPolyline(), and startRender().
Qt::PenCapStyle QgsSimpleLineSymbolLayerV2::mPenCapStyle protected
Definition at line 108 of file qgslinesymbollayerv2.h.
Referenced by clone(), ogrFeatureStyle(), properties(), startRender(), and toSld().
Qt::PenJoinStyle QgsSimpleLineSymbolLayerV2::mPenJoinStyle protected
Definition at line 107 of file qgslinesymbollayerv2.h.
Referenced by clone(), ogrFeatureStyle(), properties(), startRender(), and toSld().
Qt::PenStyle QgsSimpleLineSymbolLayerV2::mPenStyle protected
Definition at line 106 of file qgslinesymbollayerv2.h.
Referenced by clone(), dxfPenStyle(), properties(), startRender(), and toSld().
QPen QgsSimpleLineSymbolLayerV2::mSelPen protected
Definition at line 110 of file qgslinesymbollayerv2.h.
Referenced by renderPolyline(), and startRender().
bool QgsSimpleLineSymbolLayerV2::mUseCustomDashPattern protected
Definition at line 115 of file qgslinesymbollayerv2.h.
Referenced by clone(), dxfCustomDashPattern(), ogrFeatureStyle(), properties(), startRender(), and toSld().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgslinesymbollayerv2.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgslinesymbollayerv2.cpp