QGIS API Documentation: QgsComposerScaleBar Class Reference
QgsComposerScaleBar Class Reference
MapComposer
A scale bar item that can be added to a map composition.
#include <qgscomposerscalebar.h>
Public Types
enum Alignment { Left = 0, Middle, Right }
Added in version 1.8.
enum ScaleBarUnits { MapUnits = 0, Meters, Feet, NauticalMiles }
Added in version 1.9.
Public Types inherited from QgsComposerItem
enum ItemType {
ComposerItem = UserType + 100, ComposerArrow, ComposerItemGroup, ComposerLabel,
ComposerLegend, ComposerMap, ComposerPaper, ComposerPicture,
ComposerScaleBar, ComposerShape, ComposerTable, ComposerAttributeTable,
ComposerTextTable, ComposerFrame
}
enum MouseMoveAction {
MoveItem, ResizeUp, ResizeDown, ResizeLeft,
ResizeRight, ResizeLeftUp, ResizeRightUp, ResizeLeftDown,
ResizeRightDown, NoAction
}
Describes the action (move or resize in different directon) to be done during mouse move.
enum ItemPositionMode {
UpperLeft, UpperMiddle, UpperRight, MiddleLeft,
Middle, MiddleRight, LowerLeft, LowerMiddle,
LowerRight
}
Public Slots
void updateSegmentSize ()
void invalidateCurrentMap ()
Sets mCompositionMap to 0 if the map is deleted.
Public Slots inherited from QgsComposerItem
virtual void setRotation (double r)
Sets the item rotation.
virtual void setItemRotation (double r, bool adjustPosition=false)
Sets the item rotation.
void repaint ()
Public Member Functions
QgsComposerScaleBar (QgsComposition *composition)
~QgsComposerScaleBar ()
virtual int type () const
return correct graphics item type.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *itemStyle, QWidget *pWidget)
Reimplementation of QCanvasItem::paint.
int numSegments () const
void setNumSegments (int nSegments)
int numSegmentsLeft () const
void setNumSegmentsLeft (int nSegmentsLeft)
double numUnitsPerSegment () const
void setNumUnitsPerSegment (double units)
double numMapUnitsPerScaleBarUnit () const
void setNumMapUnitsPerScaleBarUnit (double d)
QString unitLabeling () const
void setUnitLabeling (const QString &label)
QFont font () const
QColor fontColor () const
void setFontColor (const QColor &c)
void setFont (const QFont &font)
QPen pen () const
void setPen (const QPen &pen)
QBrush brush () const
void setBrush (const QBrush &brush)
double height () const
void setHeight (double h)
void setComposerMap (const QgsComposerMap *map)
const QgsComposerMap * composerMap () const
double labelBarSpace () const
void setLabelBarSpace (double space)
double boxContentSpace () const
void setBoxContentSpace (double space)
double segmentMillimeters () const
Alignment alignment () const
Left / Middle/ Right.
void setAlignment (Alignment a)
ScaleBarUnits units () const
void setUnits (ScaleBarUnits u)
void applyDefaultSettings ()
Apply default settings.
void applyDefaultSize (ScaleBarUnits u=Meters)
Apply default size (scale bar 1/5 of map item width)
void setStyle (const QString &styleName)
Sets style by name.
QString style () const
Returns style name.
void segmentPositions (QList< QPair< double, double > > &posWidthList) const
Returns the x - positions of the segment borders (in item coordinates) and the width of the segment.
void adjustBoxSize ()
Sets box size suitable to content.
void update ()
Adjusts box size and calls QgsComposerItem::update()
QString firstLabelString () const
Returns string of first label (important for drawing, labeling, size calculation.
bool writeXML (QDomElement &elem, QDomDocument &doc) const
stores state in Dom element
bool readXML (const QDomElement &itemElem, const QDomDocument &doc)
sets state from Dom document
void correctXPositionAlignment (double width, double widthAfter)
Moves scalebar position to the left / right depending on alignment and change in item width.
Public Member Functions inherited from QgsComposerItem
QgsComposerItem (QgsComposition *composition, bool manageZValue=true)
Constructor.
QgsComposerItem (qreal x, qreal y, qreal width, qreal height, QgsComposition *composition, bool manageZValue=true)
Constructor with box position and composer object.
virtual ~QgsComposerItem ()
virtual void setSelected (bool s)
Set selected, selected item should be highlighted.
virtual bool selected () const
Is selected.
virtual bool writeSettings ()
stores state in project
virtual bool readSettings ()
read state from project
virtual bool removeSettings ()
delete settings from project file
void move (double dx, double dy)
Moves item in canvas coordinates.
virtual void moveContent (double dx, double dy)
Move Content of item.
virtual void zoomContent (int delta, double x, double y)
Zoom content of item.
void setItemPosition (double x, double y, ItemPositionMode itemPoint=UpperLeft)
Moves the item to a new position (in canvas coordinates)
void setItemPosition (double x, double y, double width, double height, ItemPositionMode itemPoint=UpperLeft, bool posIncludesFrame=false)
Sets item position and width / height in one go.
ItemPositionMode lastUsedPositionMode ()
Returns item's last used position mode.
virtual void setSceneRect (const QRectF &rectangle)
Sets this items bound in scene coordinates such that 1 item size units corresponds to 1 scene size unit.
bool _writeXML (QDomElement &itemElem, QDomDocument &doc) const
Writes parameter that are not subclass specific in document.
bool _readXML (const QDomElement &itemElem, const QDomDocument &doc)
Reads parameter that are not subclass specific in document.
bool hasFrame () const
Whether this item has a frame or not.
void setFrameEnabled (bool drawFrame)
Set whether this item has a frame drawn around it or not.
virtual void setFrameOutlineWidth (double outlineWidth)
Sets frame outline width.
virtual double estimatedFrameBleed () const
Returns the estimated amount the item's frame bleeds outside the item's actual rectangle.
virtual QRectF rectWithFrame () const
Returns the item's rectangular bounds, including any bleed caused by the item's frame.
bool hasBackground () const
Whether this item has a Background or not.
void setBackgroundEnabled (bool drawBackground)
Set whether this item has a Background drawn around it or not.
QColor backgroundColor () const
Gets the background color for this item.
void setBackgroundColor (const QColor &backgroundColor)
Sets the background color for this item.
QPainter::CompositionMode blendMode () const
Returns the item's composition blending mode.
void setBlendMode (QPainter::CompositionMode blendMode)
Sets the item's composition blending mode.
int transparency () const
Returns the item's transparency.
void setTransparency (int transparency)
Sets the item's transparency.
bool effectsEnabled () const
Returns true if effects (eg blend modes) are enabled for the item.
void setEffectsEnabled (bool effectsEnabled)
Sets whether effects (eg blend modes) are enabled for the item.
virtual void addItem (QgsComposerItem *item)
Composite operations for item groups do nothing per default.
virtual void removeItems ()
const QgsComposition * composition () const
QgsComposition * composition ()
virtual void beginItemCommand (const QString &text)
void beginCommand (const QString &commandText, QgsComposerMergeCommand::Context c=QgsComposerMergeCommand::Unknown)
Starts new composer undo command.
virtual void endItemCommand ()
void endCommand ()
Finish current command and push it onto the undo stack.
void cancelCommand ()
void drawText (QPainter *p, double x, double y, const QString &text, const QFont &font) const
Draws Text.
void drawText (QPainter *p, const QRectF &rect, const QString &text, const QFont &font, Qt::AlignmentFlag halignment=Qt::AlignLeft, Qt::AlignmentFlag valignment=Qt::AlignTop) const
Like the above, but with a rectangle for multiline text.
double textWidthMillimeters (const QFont &font, const QString &text) const
Returns the font width in millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontHeightCharacterMM (const QFont &font, const QChar &c) const
Returns the font height of a character in millimeters.
double fontAscentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double fontDescentMillimeters (const QFont &font) const
Returns the font ascent in Millimeters (considers upscaling and downscaling with FONT_WORKAROUND_SCALE.
double pixelFontSize (double pointSize) const
Calculates font to from point size to pixel size.
QFont scaledFontPixelSize (const QFont &font) const
Returns a font where size is in pixel and font size is upscaled with FONT_WORKAROUND_SCALE.
void setPositionLock (bool lock)
Locks / unlocks the item position for mouse drags.
bool positionLock () const
Returns position lock for mouse drags (true means locked)
double itemRotation () const
Returns the rotation for the composer item.
double rotation () const
Returns the rotation for the composer item.
virtual void updateItem ()
Updates item, with the possibility to do custom update for subclasses.
QString id () const
Get item's id (which is not necessarly unique)
virtual void setId (const QString &id)
Set item's id (which is not necessarly unique)
QString uuid () const
Get item identification name.
Protected Member Functions
void refreshSegmentMillimeters ()
Calculates with of a segment in mm and stores it in mSegmentMillimeters.
double mapWidth () const
Returns diagonal of composer map in selected units (map units / meters / feet / nautical miles)
Protected Member Functions inherited from QgsComposerItem
virtual void drawSelectionBoxes (QPainter *p)
Draw selection boxes around item.
virtual void drawFrame (QPainter *p)
Draw black frame around item.
virtual void drawBackground (QPainter *p)
Draw background.
void drawArrowHead (QPainter *p, double x, double y, double angle, double arrowHeadWidth) const
Draws arrowhead.
double angle (const QPointF &p1, const QPointF &p2) const
Returns angle of the line from p1 to p2 (clockwise, starting at N)
double rectHandlerBorderTolerance () const
Returns the current (zoom level dependent) tolerance to decide if mouse position is close enough to the item border for resizing.
double lockSymbolSize () const
Returns the size of the lock symbol depending on the composer zoom level and the item size.
double horizontalViewScaleFactor () const
Returns the zoom factor of the graphics view.
bool imageSizeConsideringRotation (double &width, double &height, double rotation) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
bool imageSizeConsideringRotation (double &width, double &height) const
Calculates width and hight of the picture (in mm) such that it fits into the item frame with the given rotation.
QRectF largestRotatedRectWithinBounds (QRectF originalRect, QRectF boundsRect, double rotation) const
Calculates the largest scaled version of originalRect which fits within boundsRect, when it is rotated by a specified amount.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height, double rotation) const
Calculates corner point after rotation and scaling.
bool cornerPointOnRotatedAndScaledRect (double &x, double &y, double width, double height) const
Calculates corner point after rotation and scaling.
void sizeChangedByRotation (double &width, double &height, double rotation)
Calculates width / height of the bounding box of a rotated rectangle.
void sizeChangedByRotation (double &width, double &height)
Calculates width / height of the bounding box of a rotated rectangle.
void rotate (double angle, double &x, double &y) const
Rotates a point / vector.
QGraphicsLineItem * hAlignSnapItem ()
Return horizontal align snap item.
void deleteHAlignSnapItem ()
QGraphicsLineItem * vAlignSnapItem ()
Return vertical align snap item.
void deleteVAlignSnapItem ()
void deleteAlignItems ()
Protected Attributes
const QgsComposerMap * mComposerMap
Reference to composer map object.
int mNumSegments
Number of segments on right side.
int mNumSegmentsLeft
Number of segments on left side.
double mNumUnitsPerSegment
Size of a segment (in map units)
double mNumMapUnitsPerScaleBarUnit
Number of map units per scale bar units (e.g.
QString mUnitLabeling
Labeling of map units.
QFont mFont
Font.
QColor mFontColor
QPen mPen
Outline.
QBrush mBrush
Fill.
double mHeight
Height of bars/lines.
QgsScaleBarStyle * mStyle
Scalebar style.
double mLabelBarSpace
Space between bar and Text labels.
double mBoxContentSpace
Space between content and item box.
double mSegmentMillimeters
Width of a segment (in mm)
Alignment mAlignment
ScaleBarUnits mUnits
Protected Attributes inherited from QgsComposerItem
QgsComposition * mComposition
QgsComposerItem::MouseMoveAction mCurrentMouseMoveAction
QPointF mMouseMoveStartPos
Start point of the last mouse move action (in scene coordinates)
QPointF mLastMouseEventPos
Position of the last mouse move event (in scene coordinates)
QGraphicsRectItem * mBoundingResizeRectangle
Rectangle used during move and resize actions.
QGraphicsLineItem * mHAlignSnapItem
QGraphicsLineItem * mVAlignSnapItem
bool mFrame
True if item fram needs to be painted.
bool mBackground
True if item background needs to be painted.
QColor mBackgroundColor
Background color.
bool mItemPositionLocked
True if item position and size cannot be changed with mouse move.
double mLastValidViewScaleFactor
Backup to restore item appearance if no view scale factor is available.
double mItemRotation
Item rotation in degrees, clockwise.
QPainter::CompositionMode mBlendMode
Composition blend mode for item.
bool mEffectsEnabled
QgsComposerEffect * mEffect
int mTransparency
Item transparency.
ItemPositionMode mLastUsedPositionMode
The item's position mode.
Additional Inherited Members
Signals inherited from QgsComposerItem
void itemRotationChanged (double newRotation)
Is emitted on item rotation change.
void itemChanged ()
Used e.g.
void sizeChanged ()
Emitted if the rectangle changes.
void frameChanged ()
Emitted if the item's frame style changes.
Detailed Description
A scale bar item that can be added to a map composition.
Definition at line 30 of file qgscomposerscalebar.h.
Member Enumeration Documentation
enum QgsComposerScaleBar::Alignment
Added in version 1.8.
Enumerator:
Left
Middle
Right
Definition at line 37 of file qgscomposerscalebar.h.
enum QgsComposerScaleBar::ScaleBarUnits
Added in version 1.9.
Enumerator:
MapUnits
Meters
Feet
NauticalMiles
Definition at line 45 of file qgscomposerscalebar.h.
Constructor & Destructor Documentation
QgsComposerScaleBar::QgsComposerScaleBar (QgsComposition * composition)
Definition at line 36 of file qgscomposerscalebar.cpp.
References applyDefaultSettings(), and applyDefaultSize().
QgsComposerScaleBar::~QgsComposerScaleBar ()
Definition at line 50 of file qgscomposerscalebar.cpp.
References mStyle.
Member Function Documentation
void QgsComposerScaleBar::adjustBoxSize ()
Sets box size suitable to content.
Definition at line 341 of file qgscomposerscalebar.cpp.
References QgsScaleBarStyle::calculateBoxSize(), mStyle, and QgsComposerItem::setSceneRect().
Referenced by applyDefaultSize(), and update().
Alignment QgsComposerScaleBar::alignment (void) const inline
Left / Middle/ Right.
Note
: this method was added in version 1.8
Definition at line 107 of file qgscomposerscalebar.h.
Referenced by QgsNumericScaleBarStyle::draw().
void QgsComposerScaleBar::applyDefaultSettings ()
Apply default settings.
Definition at line 231 of file qgscomposerscalebar.cpp.
References QgsComposerItem::itemChanged(), mBoxContentSpace, mBrush, mFont, mFontColor, mHeight, mLabelBarSpace, mNumMapUnitsPerScaleBarUnit, mNumSegments, mNumSegmentsLeft, mPen, and mStyle.
Referenced by QgsComposerScaleBar().
void QgsComposerScaleBar::applyDefaultSize (QgsComposerScaleBar::ScaleBarUnits u = Meters)
Apply default size (scale bar 1/5 of map item width)
Note
this method was added in version 1.7
Definition at line 266 of file qgscomposerscalebar.cpp.
References adjustBoxSize(), Feet, QgsComposerItem::itemChanged(), MapUnits, mapWidth(), mComposerMap, Meters, mUnits, NauticalMiles, refreshSegmentMillimeters(), setNumMapUnitsPerScaleBarUnit(), setNumSegments(), setNumSegmentsLeft(), setNumUnitsPerSegment(), setUnitLabeling(), setUnits(), and tr.
Referenced by QgsComposerView::mousePressEvent(), and QgsComposerScaleBar().
double QgsComposerScaleBar::boxContentSpace () const inline
Definition at line 100 of file qgscomposerscalebar.h.
Referenced by QgsNumericScaleBarStyle::calculateBoxSize(), QgsScaleBarStyle::calculateBoxSize(), QgsNumericScaleBarStyle::draw(), QgsDoubleBoxScaleBarStyle::draw(), QgsSingleBoxScaleBarStyle::draw(), QgsTicksScaleBarStyle::draw(), and QgsScaleBarStyle::drawLabels().
QBrush QgsComposerScaleBar::brush () const inline
Definition at line 88 of file qgscomposerscalebar.h.
Referenced by QgsDoubleBoxScaleBarStyle::draw(), and QgsSingleBoxScaleBarStyle::draw().
const QgsComposerMap* QgsComposerScaleBar::composerMap () const inline
Definition at line 95 of file qgscomposerscalebar.h.
Referenced by readXML(), and QgsNumericScaleBarStyle::scaleText().
void QgsComposerScaleBar::correctXPositionAlignment (double width, double widthAfter)
Moves scalebar position to the left / right depending on alignment and change in item width.
Definition at line 579 of file qgscomposerscalebar.cpp.
References mAlignment, Middle, QgsComposerItem::move(), mStyle, QgsScaleBarStyle::name(), and Right.
Referenced by setBoxContentSpace(), setNumSegments(), setNumSegmentsLeft(), setNumUnitsPerSegment(), and updateSegmentSize().
QString QgsComposerScaleBar::firstLabelString () const
Returns string of first label (important for drawing, labeling, size calculation.
Definition at line 446 of file qgscomposerscalebar.cpp.
References mNumMapUnitsPerScaleBarUnit, mNumSegmentsLeft, and mNumUnitsPerSegment.
Referenced by QgsScaleBarStyle::calculateBoxSize(), QgsScaleBarStyle::drawLabels(), and paint().
QFont QgsComposerScaleBar::font () const
Definition at line 458 of file qgscomposerscalebar.cpp.
References mFont.
Referenced by QgsNumericScaleBarStyle::calculateBoxSize(), QgsScaleBarStyle::calculateBoxSize(), QgsDoubleBoxScaleBarStyle::draw(), QgsNumericScaleBarStyle::draw(), QgsSingleBoxScaleBarStyle::draw(), QgsTicksScaleBarStyle::draw(), QgsScaleBarStyle::drawLabels(), and setFont().
QColor QgsComposerScaleBar::fontColor () const inline
Definition at line 80 of file qgscomposerscalebar.h.
Referenced by QgsNumericScaleBarStyle::draw(), and QgsScaleBarStyle::drawLabels().
double QgsComposerScaleBar::height () const inline
Definition at line 91 of file qgscomposerscalebar.h.
Referenced by QgsScaleBarStyle::calculateBoxSize(), QgsNumericScaleBarStyle::draw(), QgsDoubleBoxScaleBarStyle::draw(), QgsSingleBoxScaleBarStyle::draw(), and QgsTicksScaleBarStyle::draw().
void QgsComposerScaleBar::invalidateCurrentMap () slot
Sets mCompositionMap to 0 if the map is deleted.
Definition at line 158 of file qgscomposerscalebar.cpp.
References mComposerMap, and updateSegmentSize().
Referenced by readXML(), and setComposerMap().
double QgsComposerScaleBar::labelBarSpace () const inline
Definition at line 97 of file qgscomposerscalebar.h.
Referenced by QgsScaleBarStyle::calculateBoxSize(), QgsDoubleBoxScaleBarStyle::draw(), QgsSingleBoxScaleBarStyle::draw(), and QgsTicksScaleBarStyle::draw().
double QgsComposerScaleBar::mapWidth () const protected
Returns diagonal of composer map in selected units (map units / meters / feet / nautical miles)
Definition at line 185 of file qgscomposerscalebar.cpp.
References QgsComposerMap::currentMapExtent(), QgsMapRenderer::destinationCrs(), Feet, QGis::Feet, QGis::fromUnitToUnitFactor(), QgsMapRenderer::hasCrsTransformEnabled(), QgsProject::instance(), QgsComposerMap::mapRenderer(), MapUnits, mComposerMap, QgsDistanceArea::measureLine(), QGis::Meters, mUnits, NauticalMiles, QGis::NauticalMiles, QgsDistanceArea::setEllipsoid(), QgsDistanceArea::setEllipsoidalMode(), QgsDistanceArea::setSourceCrs(), QgsCoordinateReferenceSystem::srsid(), QgsRectangle::width(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), and QgsRectangle::yMinimum().
Referenced by applyDefaultSize(), and refreshSegmentMillimeters().
double QgsComposerScaleBar::numMapUnitsPerScaleBarUnit () const inline
Definition at line 72 of file qgscomposerscalebar.h.
Referenced by QgsScaleBarStyle::calculateBoxSize(), and QgsScaleBarStyle::drawLabels().
int QgsComposerScaleBar::numSegments () const inline
Definition at line 63 of file qgscomposerscalebar.h.
Referenced by QgsScaleBarStyle::calculateBoxSize().
int QgsComposerScaleBar::numSegmentsLeft () const inline
Definition at line 66 of file qgscomposerscalebar.h.
Referenced by QgsScaleBarStyle::drawLabels().
double QgsComposerScaleBar::numUnitsPerSegment () const inline
Definition at line 69 of file qgscomposerscalebar.h.
Referenced by QgsScaleBarStyle::calculateBoxSize(), and QgsScaleBarStyle::drawLabels().
void QgsComposerScaleBar::paint (QPainter * painter, const QStyleOptionGraphicsItem * itemStyle, QWidget * pWidget)
Reimplementation of QCanvasItem::paint.
Definition at line 55 of file qgscomposerscalebar.cpp.
References QgsScaleBarStyle::draw(), QgsComposerItem::drawBackground(), QgsComposerItem::drawFrame(), QgsComposerItem::drawSelectionBoxes(), firstLabelString(), mFont, mStyle, and QgsComposerItem::textWidthMillimeters().
QPen QgsComposerScaleBar::pen () const inline
Definition at line 85 of file qgscomposerscalebar.h.
Referenced by QgsNumericScaleBarStyle::calculateBoxSize(), QgsScaleBarStyle::calculateBoxSize(), QgsDoubleBoxScaleBarStyle::draw(), QgsSingleBoxScaleBarStyle::draw(), and QgsTicksScaleBarStyle::draw().
bool QgsComposerScaleBar::readXML (const QDomElement & itemElem, const QDomDocument & doc) virtual
sets state from Dom document
Parameters
itemElem is Dom node corresponding to item tag
doc is Dom document
Implements QgsComposerItem.
Definition at line 515 of file qgscomposerscalebar.cpp.
References QgsComposerItem::_readXML(), composerMap(), QgsComposition::getComposerMapById(), invalidateCurrentMap(), mAlignment, mBoxContentSpace, mBrush, mComposerMap, QgsComposerItem::mComposition, mFont, mFontColor, mHeight, mLabelBarSpace, mNumMapUnitsPerScaleBarUnit, mNumSegments, mNumSegmentsLeft, mNumUnitsPerSegment, mPen, mSegmentMillimeters, mStyle, mUnitLabeling, mUnits, setStyle(), tr, and updateSegmentSize().
Referenced by QgsComposition::addItemsFromXML().
void QgsComposerScaleBar::refreshSegmentMillimeters () protected
Calculates with of a segment in mm and stores it in mSegmentMillimeters.
Definition at line 170 of file qgscomposerscalebar.cpp.
References QgsComposerMap::currentMapExtent(), mapWidth(), mComposerMap, mNumUnitsPerSegment, and mSegmentMillimeters.
Referenced by applyDefaultSize(), setComposerMap(), setNumUnitsPerSegment(), setUnits(), and updateSegmentSize().
double QgsComposerScaleBar::segmentMillimeters () const inline
Definition at line 103 of file qgscomposerscalebar.h.
Referenced by QgsTicksScaleBarStyle::draw(), and QgsScaleBarStyle::drawLabels().
void QgsComposerScaleBar::segmentPositions (QList< QPair< double, double > > & posWidthList) const
Returns the x - positions of the segment borders (in item coordinates) and the width of the segment.
Note
python bindings not available on android
Definition at line 376 of file qgscomposerscalebar.cpp.
References mBoxContentSpace, mNumSegments, mNumSegmentsLeft, mPen, and mSegmentMillimeters.
Referenced by QgsScaleBarStyle::calculateBoxSize(), QgsDoubleBoxScaleBarStyle::draw(), QgsSingleBoxScaleBarStyle::draw(), QgsTicksScaleBarStyle::draw(), and QgsScaleBarStyle::drawLabels().
void QgsComposerScaleBar::setAlignment (Alignment a)
Note
: this method was added in version 1.8
Definition at line 217 of file qgscomposerscalebar.cpp.
References QgsComposerItem::itemChanged(), mAlignment, and update().
void QgsComposerScaleBar::setBoxContentSpace (double space)
Definition at line 123 of file qgscomposerscalebar.cpp.
References QgsScaleBarStyle::calculateBoxSize(), correctXPositionAlignment(), QgsComposerItem::itemChanged(), mBoxContentSpace, and mStyle.
void QgsComposerScaleBar::setBrush (const QBrush & brush) inline
Definition at line 89 of file qgscomposerscalebar.h.
void QgsComposerScaleBar::setComposerMap (const QgsComposerMap * map)
Definition at line 137 of file qgscomposerscalebar.cpp.
References invalidateCurrentMap(), QgsComposerItem::itemChanged(), mComposerMap, refreshSegmentMillimeters(), and updateSegmentSize().
Referenced by QgsComposerView::mousePressEvent().
void QgsComposerScaleBar::setFont (const QFont & font)
Definition at line 463 of file qgscomposerscalebar.cpp.
References font(), QgsComposerItem::itemChanged(), mFont, and update().
void QgsComposerScaleBar::setFontColor (const QColor & c) inline
Definition at line 81 of file qgscomposerscalebar.h.
void QgsComposerScaleBar::setHeight (double h) inline
Definition at line 92 of file qgscomposerscalebar.h.
void QgsComposerScaleBar::setLabelBarSpace (double space) inline
Definition at line 98 of file qgscomposerscalebar.h.
void QgsComposerScaleBar::setNumMapUnitsPerScaleBarUnit (double d) inline
Definition at line 73 of file qgscomposerscalebar.h.
Referenced by applyDefaultSize().
void QgsComposerScaleBar::setNumSegments (int nSegments)
Definition at line 80 of file qgscomposerscalebar.cpp.
References QgsScaleBarStyle::calculateBoxSize(), correctXPositionAlignment(), QgsComposerItem::itemChanged(), mNumSegments, and mStyle.
Referenced by applyDefaultSize().
void QgsComposerScaleBar::setNumSegmentsLeft (int nSegmentsLeft)
Definition at line 109 of file qgscomposerscalebar.cpp.
References QgsScaleBarStyle::calculateBoxSize(), correctXPositionAlignment(), QgsComposerItem::itemChanged(), mNumSegmentsLeft, and mStyle.
Referenced by applyDefaultSize().
void QgsComposerScaleBar::setNumUnitsPerSegment (double units)
Definition at line 94 of file qgscomposerscalebar.cpp.
References QgsScaleBarStyle::calculateBoxSize(), correctXPositionAlignment(), QgsComposerItem::itemChanged(), mNumUnitsPerSegment, mStyle, refreshSegmentMillimeters(), and units().
Referenced by applyDefaultSize().
void QgsComposerScaleBar::setPen (const QPen & pen) inline
Definition at line 86 of file qgscomposerscalebar.h.
void QgsComposerScaleBar::setStyle (const QString & styleName)
Sets style by name.
Parameters
styleName (untranslated) style name. Possibilities are: 'Single Box', 'Double Box', 'Line Ticks Middle', 'Line Ticks Down', 'Line Ticks Up', 'Numeric'
Definition at line 396 of file qgscomposerscalebar.cpp.
References QgsComposerItem::itemChanged(), mStyle, QgsTicksScaleBarStyle::setTickPosition(), QgsTicksScaleBarStyle::TicksDown, QgsTicksScaleBarStyle::TicksMiddle, and QgsTicksScaleBarStyle::TicksUp.
Referenced by readXML().
void QgsComposerScaleBar::setUnitLabeling (const QString & label) inline
Definition at line 76 of file qgscomposerscalebar.h.
Referenced by applyDefaultSize().
void QgsComposerScaleBar::setUnits (ScaleBarUnits u)
Note
: this method was added in version 1.9
Definition at line 224 of file qgscomposerscalebar.cpp.
References QgsComposerItem::itemChanged(), mUnits, and refreshSegmentMillimeters().
Referenced by applyDefaultSize().
QString QgsComposerScaleBar::style () const
Returns style name.
Definition at line 434 of file qgscomposerscalebar.cpp.
References mStyle, and QgsScaleBarStyle::name().
virtual int QgsComposerScaleBar::type () const inline virtual
return correct graphics item type.
Added in v1.7
Reimplemented from QgsComposerItem.
Definition at line 57 of file qgscomposerscalebar.h.
References QgsComposerItem::ComposerScaleBar.
QString QgsComposerScaleBar::unitLabeling () const inline
Definition at line 75 of file qgscomposerscalebar.h.
Referenced by QgsScaleBarStyle::calculateBoxSize(), and QgsScaleBarStyle::drawLabels().
ScaleBarUnits QgsComposerScaleBar::units () const inline
Note
: this method was added in version 1.9
Definition at line 113 of file qgscomposerscalebar.h.
Referenced by setNumUnitsPerSegment().
void QgsComposerScaleBar::update ()
Adjusts box size and calls QgsComposerItem::update()
Definition at line 352 of file qgscomposerscalebar.cpp.
References adjustBoxSize(), mStyle, and QgsScaleBarStyle::name().
Referenced by setAlignment(), setFont(), and updateSegmentSize().
void QgsComposerScaleBar::updateSegmentSize () slot
Definition at line 362 of file qgscomposerscalebar.cpp.
References QgsScaleBarStyle::calculateBoxSize(), correctXPositionAlignment(), QgsComposerItem::itemChanged(), mStyle, refreshSegmentMillimeters(), and update().
Referenced by invalidateCurrentMap(), readXML(), and setComposerMap().
bool QgsComposerScaleBar::writeXML (QDomElement & elem, QDomDocument & doc) const virtual
stores state in Dom element
Parameters
elem is Dom element corresponding to 'Composer' tag
doc Dom document
Implements QgsComposerItem.
Definition at line 470 of file qgscomposerscalebar.cpp.
References QgsComposerItem::_writeXML(), QgsComposerMap::id(), mAlignment, mBoxContentSpace, mBrush, mComposerMap, mFont, mFontColor, mHeight, mLabelBarSpace, mNumMapUnitsPerScaleBarUnit, mNumSegments, mNumSegmentsLeft, mNumUnitsPerSegment, mPen, mSegmentMillimeters, mStyle, mUnitLabeling, mUnits, and QgsScaleBarStyle::name().
Member Data Documentation
Alignment QgsComposerScaleBar::mAlignment protected
Definition at line 202 of file qgscomposerscalebar.h.
Referenced by correctXPositionAlignment(), readXML(), setAlignment(), and writeXML().
double QgsComposerScaleBar::mBoxContentSpace protected
Space between content and item box.
Definition at line 197 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), readXML(), segmentPositions(), setBoxContentSpace(), and writeXML().
QBrush QgsComposerScaleBar::mBrush protected
Fill.
Definition at line 187 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), readXML(), and writeXML().
const QgsComposerMap* QgsComposerScaleBar::mComposerMap protected
Reference to composer map object.
Definition at line 169 of file qgscomposerscalebar.h.
Referenced by applyDefaultSize(), invalidateCurrentMap(), mapWidth(), readXML(), refreshSegmentMillimeters(), setComposerMap(), and writeXML().
QFont QgsComposerScaleBar::mFont protected
Font.
Definition at line 182 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), font(), paint(), readXML(), setFont(), and writeXML().
QColor QgsComposerScaleBar::mFontColor protected
Definition at line 183 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), readXML(), and writeXML().
double QgsComposerScaleBar::mHeight protected
Height of bars/lines.
Definition at line 189 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), readXML(), and writeXML().
double QgsComposerScaleBar::mLabelBarSpace protected
Space between bar and Text labels.
Definition at line 194 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), readXML(), and writeXML().
double QgsComposerScaleBar::mNumMapUnitsPerScaleBarUnit protected
Number of map units per scale bar units (e.g.
1000 to have km for a map with m units)
Definition at line 177 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), firstLabelString(), readXML(), and writeXML().
int QgsComposerScaleBar::mNumSegments protected
Number of segments on right side.
Definition at line 171 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), readXML(), segmentPositions(), setNumSegments(), and writeXML().
int QgsComposerScaleBar::mNumSegmentsLeft protected
Number of segments on left side.
Definition at line 173 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), firstLabelString(), readXML(), segmentPositions(), setNumSegmentsLeft(), and writeXML().
double QgsComposerScaleBar::mNumUnitsPerSegment protected
Size of a segment (in map units)
Definition at line 175 of file qgscomposerscalebar.h.
Referenced by firstLabelString(), readXML(), refreshSegmentMillimeters(), setNumUnitsPerSegment(), and writeXML().
QPen QgsComposerScaleBar::mPen protected
Outline.
Definition at line 185 of file qgscomposerscalebar.h.
Referenced by applyDefaultSettings(), readXML(), segmentPositions(), and writeXML().
double QgsComposerScaleBar::mSegmentMillimeters protected
Width of a segment (in mm)
Definition at line 200 of file qgscomposerscalebar.h.
Referenced by readXML(), refreshSegmentMillimeters(), segmentPositions(), and writeXML().
QgsScaleBarStyle* QgsComposerScaleBar::mStyle protected
Scalebar style.
Definition at line 191 of file qgscomposerscalebar.h.
Referenced by adjustBoxSize(), applyDefaultSettings(), correctXPositionAlignment(), paint(), readXML(), setBoxContentSpace(), setNumSegments(), setNumSegmentsLeft(), setNumUnitsPerSegment(), setStyle(), style(), update(), updateSegmentSize(), writeXML(), and ~QgsComposerScaleBar().
QString QgsComposerScaleBar::mUnitLabeling protected
Labeling of map units.
Definition at line 180 of file qgscomposerscalebar.h.
Referenced by readXML(), and writeXML().
ScaleBarUnits QgsComposerScaleBar::mUnits protected
Definition at line 204 of file qgscomposerscalebar.h.
Referenced by applyDefaultSize(), mapWidth(), readXML(), setUnits(), and writeXML().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgscomposerscalebar.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgscomposerscalebar.cpp