QGIS API Documentation: QgsVectorLayer Class Reference
QgsVectorLayer Class Reference
QGIS core library
Represents a vector layer which manages a vector based data sets.
#include <qgsvectorlayer.h>
Classes
struct GroupData
struct RangeData
struct TabData
struct ValueRelationData
Public Types
enum EditorLayout { GeneratedLayout = 0, TabLayout = 1, UiFileLayout = 2 }
The different types to layout the attribute editor.
enum EditType {
LineEdit, UniqueValues, UniqueValuesEditable, ValueMap,
Classification, EditRange, SliderRange, CheckBox,
FileName, Enumeration, Immutable, Hidden,
TextEdit, Calendar, DialRange, ValueRelation,
UuidGenerator, Photo, WebView, Color,
EditorWidgetV2
}
enum FeatureFormSuppress { SuppressDefault = 0, SuppressOn = 1, SuppressOff = 2 }
Types of feature form suppression after feature creation.
enum VertexMarkerType { SemiTransparentCircle, Cross, NoMarker }
Editing vertex markers.
Public Types inherited from QgsMapLayer
enum LayerType { VectorLayer, RasterLayer, PluginLayer }
Layers enum defining the types of layers that can be added to a map.
Public Slots
void select (const QgsFeatureId &featureId)
Select feature by its ID.
void select (const QgsFeatureIds &featureIds)
Select features by their ID.
void deselect (const QgsFeatureId featureId)
Deselect feature by its ID.
void deselect (const QgsFeatureIds &featureIds)
Deselect features by their ID.
void removeSelection ()
Clear selection.
void triggerRepaint ()
virtual void updateExtents ()
Update the extents for the layer.
void checkJoinLayerRemove (QString theLayerId)
Check if there is a join with a layer that will be removed.
virtual void onCacheImageDelete ()
Is called when the cache image is being deleted.
Public Slots inherited from QgsMapLayer
virtual void invalidTransformInput ()
Event handler for when a coordinate transform fails due to bad vertex error.
void setMinimumScale (float theMinScale)
Accessor and mutator for the minimum scale denominator member.
float minimumScale () const
void setMaximumScale (float theMaxScale)
Accessor and mutator for the maximum scale denominator member.
float maximumScale () const
void toggleScaleBasedVisibility (bool theVisibilityFlag)
Accessor and mutator for the scale based visilibility flag.
bool hasScaleBasedVisibility () const
void clearCacheImage ()
Clear cached image added in 1.5.
virtual QDateTime timestamp () const
Time stamp of data source in the moment when data/metadata were loaded by provider.
Signals
void selectionChanged (const QgsFeatureIds selected, const QgsFeatureIds deselected, const bool clearAndSelect)
This signal is emitted when selection was changed.
void selectionChanged ()
This signal is emitted when selection was changed.
void layerModified ()
This signal is emitted when modifications has been done on layer.
void editingStarted ()
Is emitted, when editing on this layer has started.
void editingStopped ()
Is emitted, when edited changes successfully have been written to the data provider.
void beforeCommitChanges ()
Is emitted, before changes are commited to the data provider.
void beforeRollBack ()
Is emitted, before changes are rolled back.
void attributeAdded (int idx)
Will be emitted, when a new attribute has been added to this vector layer.
void attributeDeleted (int idx)
Will be emitted, when an attribute has been deleted from this vector layer.
void featureAdded (QgsFeatureId fid)
void featureDeleted (QgsFeatureId fid)
void updatedFields ()
Is emitted, whenever the fields available from this layer have been changed.
void layerDeleted ()
void attributeValueChanged (QgsFeatureId fid, int idx, const QVariant &)
void geometryChanged (QgsFeatureId fid, QgsGeometry &geom)
void committedAttributesDeleted (const QString &layerId, const QgsAttributeList &deletedAttributes)
Signals emitted after committing changes.
void committedAttributesAdded (const QString &layerId, const QList< QgsField > &addedAttributes)
void committedFeaturesAdded (const QString &layerId, const QgsFeatureList &addedFeatures)
void committedFeaturesRemoved (const QString &layerId, const QgsFeatureIds &deletedFeatureIds)
void committedAttributeValuesChanges (const QString &layerId, const QgsChangedAttributesMap &changedAttributesValues)
void committedGeometriesChanges (const QString &layerId, const QgsGeometryMap &changedGeometries)
void saveLayerToProject ()
void labelingFontNotFound (QgsVectorLayer *layer, const QString &fontfamily)
Emitted when the font family defined for labeling layer is not found on system.
void rendererChanged ()
Signal emitted on symbology changes, when setRendererV2() is called.
void featureBlendModeChanged (const QPainter::CompositionMode &blendMode)
Signal emitted when setFeatureBlendMode() is called.
void layerTransparencyChanged (int layerTransparency)
Signal emitted when setLayerTransparency() is called.
void editCommandStarted (const QString &text)
Signal emitted when a new edit command has been started.
void editCommandEnded ()
Signal emitted, when an edit command successfully ended.
void editCommandDestroyed ()
Signal emitted, whan an edit command is destroyed.
Signals inherited from QgsMapLayer
void drawingProgress (int theProgress, int theTotalSteps)
Emit a signal to notify of a progress event.
void statusChanged (QString theStatus)
Emit a signal with status (e.g.
void layerNameChanged ()
Emit a signal that the layer name has been changed.
void layerCrsChanged ()
Emit a signal that layer's CRS has been reset added in 1.4.
void repaintRequested ()
This signal should be connected with the slot QgsMapCanvas::refresh()
void screenUpdateRequested ()
The layer emits this signal when a screen update is requested.
void recalculateExtents ()
This is used to send a request that any mapcanvas using this layer update its extents.
void dataChanged ()
data of layer changed added in 1.5
void blendModeChanged (const QPainter::CompositionMode &blendMode)
Signal emitted when the blend mode is changed, through QgsMapLayer::setBlendMode()
Public Member Functions
QgsVectorLayer (QString path=QString::null, QString baseName=QString::null, QString providerLib=QString::null, bool loadDefaultStyleFlag=true)
Constructor - creates a vector layer.
virtual ~QgsVectorLayer ()
Destructor.
QString storageType () const
Returns the permanent storage type for this layer as a friendly name.
QString capabilitiesString () const
Capabilities for this layer in a friendly format.
QString dataComment () const
Returns a comment for the data in the layer.
void setDisplayField (QString fldName="")
Set the primary display field to be used in the identify results dialog.
const QString displayField () const
Returns the primary display field name used in the identify results dialog.
void setDisplayExpression (const QString &displayExpression)
Set the preview expression, used to create a human readable preview string.
const QString displayExpression ()
Get the preview expression, used to create a human readable preview string.
QgsVectorDataProvider * dataProvider ()
Returns the data provider.
const QgsVectorDataProvider * dataProvider () const
Returns the data provider in a const-correct manner.
void setProviderEncoding (const QString &encoding)
Sets the textencoding of the data provider.
void setCoordinateSystem ()
Setup the coordinate system tranformation for the layer.
void addJoin (const QgsVectorJoinInfo &joinInfo)
Joins another vector layer to this layer.
void removeJoin (const QString &joinLayerId)
Removes a vector layer join.
const QList< QgsVectorJoinInfo > & vectorJoins () const
QgsLabel * label ()
Get the label object associated with this layer.
const QgsLabel * label () const
QgsAttributeAction * actions ()
int selectedFeatureCount ()
The number of features that are selected in this layer.
void select (QgsRectangle &rect, bool addToSelection)
Select features found within the search rectangle (in layer's coordinates)
void modifySelection (QgsFeatureIds selectIds, QgsFeatureIds deselectIds)
Modifies the current selection on this layer.
void invertSelection ()
Select not selected features and deselect selected ones.
void selectAll ()
Select all the features.
QgsFeatureIds allFeatureIds ()
Get all feature Ids.
void invertSelectionInRectangle (QgsRectangle &rect)
Invert selection of features found within the search rectangle (in layer's coordinates)
QgsFeatureList selectedFeatures ()
Get a copy of the user-selected features.
const QgsFeatureIds & selectedFeaturesIds () const
Return reference to identifiers of selected features.
void setSelectedFeatures (const QgsFeatureIds &ids)
Change selection to the new set of features.
QgsRectangle boundingBoxOfSelected ()
Returns the bounding box of the selected features.
void setDiagramRenderer (QgsDiagramRendererV2 *r)
Sets diagram rendering object (takes ownership)
const QgsDiagramRendererV2 * diagramRenderer () const
void setDiagramLayerSettings (const QgsDiagramLayerSettings &s)
const QgsDiagramLayerSettings * diagramLayerSettings () const
QgsFeatureRendererV2 * rendererV2 ()
Return renderer V2.
void setRendererV2 (QgsFeatureRendererV2 *r)
Set renderer V2.
void drawRendererV2 (QgsFeatureIterator &fit, QgsRenderContext &rendererContext, bool labeling)
Draw layer with renderer V2.
void drawRendererV2Levels (QgsFeatureIterator &fit, QgsRenderContext &rendererContext, bool labeling)
Draw layer with renderer V2 using symbol levels.
QGis::GeometryType geometryType () const
Returns point, line or polygon.
bool hasGeometryType () const
Returns true if this is a geometry layer and false in case of NoGeometry (table only) or UnknownGeometry.
QGis::WkbType wkbType () const
Returns the WKBType or WKBUnknown in case of error.
QString providerType () const
Return the provider type for this layer.
virtual bool readXml (const QDomNode &layer_node)
reads vector layer specific state from project file Dom node.
virtual bool writeXml (QDomNode &layer_node, QDomDocument &doc)
write vector layer specific state to project file Dom node.
virtual void saveStyleToDatabase (QString name, QString description, bool useAsDefault, QString uiFileContent, QString &msgError)
Save named and sld style of the layer to the style table in the db.
virtual int listStylesInDatabase (QStringList &ids, QStringList &names, QStringList &descriptions, QString &msgError)
Lists all the style in db split into related to the layer and not related to.
virtual QString getStyleFromDatabase (QString styleId, QString &msgError)
Will return the named style corresponding to style id provided.
virtual QString loadNamedStyle (const QString &theURI, bool &theResultFlag, bool loadFromLocalDb)
Load a named style from file/local db/datasource db.
virtual QString loadNamedStyle (const QString &theURI, bool &theResultFlag)
Calls loadNamedStyle(theURI, theResultFlag, false); Retained for backward compatibility.
virtual bool applyNamedStyle (QString namedStyle, QString errorMsg)
QgsAttributeEditorElement * attributeEditorElementFromDomElement (QDomElement &elem, QObject *parent)
convert a saved attribute editor element into a AttributeEditor structure as it's used internally.
bool readSymbology (const QDomNode &node, QString &errorMessage)
Read the symbology for the current layer from the Dom node supplied.
bool writeSymbology (QDomNode &node, QDomDocument &doc, QString &errorMessage) const
Write the symbology for the layer into the docment provided.
bool writeSld (QDomNode &node, QDomDocument &doc, QString &errorMessage) const
bool readSld (const QDomNode &node, QString &errorMessage)
virtual long featureCount () const
Number of features in the layer.
long featureCount (QgsSymbolV2 *symbol)
Number of features rendered with specified symbol.
bool countSymbolFeatures (bool showProgress=true)
Count features for symbols.
virtual bool setSubsetString (QString subset)
Set the string (typically sql) used to define a subset of the layer.
virtual QString subsetString ()
Get the string (typically sql) used to define a subset of the layer.
QgsFeatureIterator getFeatures (const QgsFeatureRequest &request=QgsFeatureRequest())
Query the provider for features specified in request.
bool addFeature (QgsFeature &f, bool alsoUpdateExtent=true)
Adds a feature.
bool updateFeature (QgsFeature &f)
Updates an existing feature.
bool insertVertex (double x, double y, QgsFeatureId atFeatureId, int beforeVertex)
Insert a new vertex before the given vertex number, in the given ring, item (first number is index 0), and feature Not meaningful for Point geometries.
bool moveVertex (double x, double y, QgsFeatureId atFeatureId, int atVertex)
Moves the vertex at the given position number, ring and item (first number is index 0), and feature to the given coordinates.
bool deleteVertex (QgsFeatureId atFeatureId, int atVertex)
Deletes a vertex from a feature.
bool deleteSelectedFeatures ()
Deletes the selected features.
int addRing (const QList< QgsPoint > &ring)
Adds a ring to polygon/multipolygon features.
int addPart (const QList< QgsPoint > &ring)
Adds a new part polygon to a multipart feature.
int translateFeature (QgsFeatureId featureId, double dx, double dy)
Translates feature by dx, dy.
int splitParts (const QList< QgsPoint > &splitLine, bool topologicalEditing=false)
Splits parts cut by the given line.
int splitFeatures (const QList< QgsPoint > &splitLine, bool topologicalEditing=false)
Splits features cut by the given line.
Q_DECL_DEPRECATED int removePolygonIntersections (QgsGeometry *geom, QgsFeatureIds ignoreFeatures=QgsFeatureIds())
Changes the specified geometry such that it has no intersections with other polygon (or multipolygon) geometries in this vector layer.
int addTopologicalPoints (QgsGeometry *geom)
Adds topological points for every vertex of the geometry.
int addTopologicalPoints (const QgsPoint &p)
Adds a vertex to segments which intersect point p but don't already have a vertex there.
int insertSegmentVerticesForSnap (const QList< QgsSnappingResult > &snapResults)
Inserts vertices to the snapped segments.
void enableLabels (bool on)
Set labels on.
bool hasLabelsEnabled () const
Label is on.
virtual bool isEditable () const
Returns true if the provider is in editing mode.
virtual bool isReadOnly () const
Returns true if the provider is in read-only mode.
virtual bool isModified () const
Returns true if the provider has been modified since the last commit.
bool snapPoint (QgsPoint &point, double tolerance)
Snaps a point to the closest vertex if there is one within the snapping tolerance.
int snapWithContext (const QgsPoint &startPoint, double snappingTolerance, QMultiMap< double, QgsSnappingResult > &snappingResults, QgsSnapper::SnappingType snap_to)
Snaps to segment or vertex within given tolerance.
virtual void reload ()
Synchronises with changes in the datasource.
bool draw (QgsRenderContext &rendererContext)
Draws the layer.
void drawLabels (QgsRenderContext &rendererContext)
Draws the layer labels using coordinate transformation.
QgsRectangle extent ()
Return the extent of the layer as a QRect.
const QgsFields & pendingFields () const
returns field list in the to-be-committed state
QgsAttributeList pendingAllAttributesList ()
returns list of attributes
QgsAttributeList pendingPkAttributesList ()
returns list of attribute making up the primary key
int pendingFeatureCount ()
returns feature count after commit
bool setReadOnly (bool readonly=true)
Make layer read-only (editing disabled) or not.
bool startEditing ()
Make layer editable.
bool changeGeometry (QgsFeatureId fid, QgsGeometry *geom)
change feature's geometry
Q_DECL_DEPRECATED bool changeAttributeValue (QgsFeatureId fid, int field, QVariant value, bool emitSignal)
Changes an attribute value (but does not commit it)
bool changeAttributeValue (QgsFeatureId fid, int field, const QVariant &newValue, const QVariant &oldValue=QVariant())
Changes an attribute value (but does not commit it)
bool addAttribute (const QgsField &field)
add an attribute field (but does not commit it) returns true if the field was added
void addAttributeAlias (int attIndex, QString aliasString)
Sets an alias (a display name) for attributes to display in dialogs.
void addAttributeEditorWidget (QgsAttributeEditorElement *data)
Adds a tab (for the attribute editor form) holding groups and fields.
const QString editorWidgetV2 (int fieldIdx)
Get the id for the editor widget used to represent the field at the given index.
const QgsEditorWidgetConfig editorWidgetV2Config (int fieldIdx)
Get the configuration for the editor widget used to represent the field at the given index.
QList
< QgsAttributeEditorElement * > & attributeEditorElements ()
Returns a list of tabs holding groups and fields.
void clearAttributeEditorWidgets ()
Clears all the tabs for the attribute editor form.
QString attributeAlias (int attributeIndex) const
Returns the alias of an attribute name or an empty string if there is no alias.
QString attributeDisplayName (int attributeIndex) const
Convenience function that returns the attribute alias if defined or the field name else.
const QMap< QString, QString > & attributeAliases () const
const QSet< QString > & excludeAttributesWMS () const
void setExcludeAttributesWMS (const QSet< QString > &att)
const QSet< QString > & excludeAttributesWFS () const
void setExcludeAttributesWFS (const QSet< QString > &att)
bool deleteAttribute (int attr)
delete an attribute field (but does not commit it)
bool deleteAttributes (QList< int > attrs)
Deletes a list of attribute fields (but does not commit it)
bool addFeatures (QgsFeatureList features, bool makeSelected=true)
Insert a copy of the given features into the layer (but does not commit it)
bool deleteFeature (QgsFeatureId fid)
delete a feature from the layer (but does not commit it)
bool commitChanges ()
Attempts to commit any changes to disk.
const QStringList & commitErrors ()
bool rollBack (bool deleteBuffer=true)
Stop editing and discard the edits.
EditType editType (int idx)
get edit type
void setEditType (int idx, EditType edit)
set edit type
EditorLayout editorLayout ()
get the active layout for the attribute editor for this layer (added in 1.9)
void setEditorLayout (EditorLayout editorLayout)
set the active layout for the attribute editor for this layer (added in 1.9)
void setEditorWidgetV2 (int attrIdx, const QString &widgetType)
void setEditorWidgetV2Config (int attrIdx, const QMap< QString, QVariant > &config)
void setCheckedState (int idx, QString checked, QString notChecked)
set string representing 'true' for a checkbox (added in 1.4)
QPair< QString, QString > checkedState (int idx)
return string representing 'true' for a checkbox (added in 1.4)
QString editForm ()
get edit form (added in 1.4)
void setEditForm (QString ui)
set edit form (added in 1.4)
QgsVectorLayer::FeatureFormSuppress featureFormSuppress () const
Type of feature form pop-up suppression after feature creation (overrides app setting)
void setFeatureFormSuppress (QgsVectorLayer::FeatureFormSuppress s)
Set type of feature form pop-up suppression after feature creation (overrides app setting)
QString annotationForm () const
get annotation form (added in 1.5)
void setAnnotationForm (const QString &ui)
set annotation form for layer (added in 1.5)
QString editFormInit ()
get python function for edit form initialization (added in 1.4)
void setEditFormInit (QString function)
set python function for edit form initialization (added in 1.4)
QMap< QString, QVariant > & valueMap (int idx)
access value map
RangeData & range (int idx)
access range
ValueRelationData & valueRelation (int idx)
access relations
QList< QgsRelation > referencingRelations (int idx)
Get relations, where the foreign key is on this layer.
QString & dateFormat (int idx)
access date format
QSize & widgetSize (int idx)
access widget size for photo and webview widget
bool fieldEditable (int idx)
is edit widget editable
bool labelOnTop (int idx)
label widget on top
void setFieldEditable (int idx, bool editable)
set edit widget editable
void setLabelOnTop (int idx, bool onTop)
label widget on top
QgsVectorLayerEditBuffer * editBuffer ()
Buffer with uncommitted editing operations. Only valid after editing has been turned on.
void beginEditCommand (QString text)
Create edit command for undo/redo operations.
void endEditCommand ()
Finish edit command and add it to undo/redo stack.
void destroyEditCommand ()
Destroy active command and reverts all changes in it.
int fieldNameIndex (const QString &fieldName) const
Returns the index of a field name or -1 if the field does not exist.
void updateFields ()
Assembles mUpdatedFields considering provider fields, joined fields and added fields.
void createJoinCaches ()
Caches joined attributes if required (and not already done)
void uniqueValues (int index, QList< QVariant > &uniqueValues, int limit=-1)
Returns unique values for column.
QVariant minimumValue (int index)
Returns minimum value for an attribute column or invalid variant in case of error.
QVariant maximumValue (int index)
Returns maximum value for an attribute column or invalid variant in case of error.
void setFeatureBlendMode (const QPainter::CompositionMode &blendMode)
Write blend mode for features.
QPainter::CompositionMode featureBlendMode () const
Read blend mode for layer.
void setLayerTransparency (int layerTransparency)
Write transparency for layer.
int layerTransparency () const
Read transparency for layer.
QString metadata ()
Obtain Metadata for this layer.
QgsGeometryCache * cache ()
void setSimplifyMethod (const QgsVectorSimplifyMethod &simplifyMethod)
Set the simplification settings for fast rendering of features.
const QgsVectorSimplifyMethod & simplifyMethod () const
Returns the simplification settings for fast rendering of features.
bool simplifyDrawingCanbeApplied (const QgsRenderContext &renderContext, QgsVectorSimplifyMethod::SimplifyHint simplifyHint) const
Returns whether the VectorLayer can apply the specified simplification hint.
Public Member Functions inherited from QgsMapLayer
QgsMapLayer (QgsMapLayer::LayerType type=VectorLayer, QString lyrname=QString::null, QString source=QString::null)
Constructor.
virtual ~QgsMapLayer ()
Destructor.
QgsMapLayer::LayerType type () const
Get the type of the layer.
QString id () const
Get this layer's unique ID, this ID is used to access this layer from map layer registry.
void setLayerName (const QString &name)
Set the display name of the layer.
const QString & name () const
Get the display name of the layer.
const QString & originalName () const
Get the original name of the layer.
void setTitle (const QString &title)
const QString & title () const
void setAbstract (const QString &abstract)
const QString & abstract () const
void setKeywordList (const QString &keywords)
const QString & keywordList () const
void setDataUrl (const QString &dataUrl)
const QString & dataUrl () const
void setDataUrlFormat (const QString &dataUrlFormat)
const QString & dataUrlFormat () const
void setAttribution (const QString &attrib)
const QString & attribution () const
void setAttributionUrl (const QString &attribUrl)
const QString & attributionUrl () const
void setMetadataUrl (const QString &metaUrl)
const QString & metadataUrl () const
void setMetadataUrlType (const QString &metaUrlType)
const QString & metadataUrlType () const
void setMetadataUrlFormat (const QString &metaUrlFormat)
const QString & metadataUrlFormat () const
void setBlendMode (const QPainter::CompositionMode &blendMode)
Write blend mode for layer.
QPainter::CompositionMode blendMode () const
Read blend mode for layer.
bool isValid ()
QString publicSource () const
const QString & source () const
Returns the source for the layer.
virtual QStringList subLayers () const
Returns the sublayers of this layer (Useful for providers that manage their own layers, such as WMS)
virtual void setLayerOrder (const QStringList &layers)
Reorders the previously selected sublayers of this layer from bottom to top (Useful for providers that manage their own layers, such as WMS)
virtual void setSubLayerVisibility (QString name, bool vis)
Set the visibility of the given sublayer name.
bool readLayerXML (const QDomElement &layerElement)
sets state from Dom document
bool writeLayerXML (QDomElement &layerElement, QDomDocument &document)
stores state in Dom node
void setCustomProperty (const QString &key, const QVariant &value)
Set a custom property for layer.
QVariant customProperty (const QString &value, const QVariant &defaultValue=QVariant()) const
Read a custom property from layer.
void removeCustomProperty (const QString &key)
Remove a custom property from layer.
virtual QString lastErrorTitle ()
If an operation returns 0 (e.g.
virtual QString lastError ()
If an operation returns 0 (e.g.
virtual QgsError error () const
Get current status error.
const
QgsCoordinateReferenceSystem & crs () const
Returns layer's spatial reference system.
void setCrs (const QgsCoordinateReferenceSystem &srs, bool emitSignal=true)
Sets layer's spatial reference system.
virtual QString styleURI ()
Retrieve the style URI for this layer (either as a .qml file on disk or as a record in the users style table in their personal qgis.db)
virtual QString loadDefaultStyle (bool &theResultFlag)
Retrieve the default style for this layer if one exists (either as a .qml file on disk or as a record in the users style table in their personal qgis.db)
virtual bool loadNamedStyleFromDb (const QString &db, const QString &theURI, QString &qml)
virtual void exportNamedStyle (QDomDocument &doc, QString &errorMsg)
Export the properties of this layer as named style in a QDomDocument.
virtual void exportSldStyle (QDomDocument &doc, QString &errorMsg)
Export the properties of this layer as SLD style in a QDomDocument.
virtual QString saveDefaultStyle (bool &theResultFlag)
Save the properties of this layer as the default style (either as a .qml file on disk or as a record in the users style table in their personal qgis.db)
virtual QString saveNamedStyle (const QString &theURI, bool &theResultFlag)
Save the properties of this layer as a named style (either as a .qml file on disk or as a record in the users style table in their personal qgis.db)
virtual QString saveSldStyle (const QString &theURI, bool &theResultFlag)
virtual QString loadSldStyle (const QString &theURI, bool &theResultFlag)
QUndoStack * undoStack ()
Return pointer to layer's undo stack.
QImage * cacheImage ()
Get the QImage used for caching render operations.
void setCacheImage (QImage *thepImage)
Set the QImage used for caching render operations.
virtual void onCacheImageDelete ()
Is called when the cache image is being deleted.
Static Public Member Functions
static void drawVertexMarker (double x, double y, QPainter &p, QgsVectorLayer::VertexMarkerType type, int vertexSize)
Draws a vertex symbol at (screen) coordinates x, y.
Static Public Member Functions inherited from QgsMapLayer
static QString capitaliseLayerName (const QString &name)
A convenience function to (un)capitalise the layer name.
Protected Slots
void invalidateSymbolCountedFlag ()
Protected Member Functions
void setExtent (const QgsRectangle &rect)
Set the extent.
Protected Member Functions inherited from QgsMapLayer
void setValid (bool valid)
set whether layer is valid or not - should be used in constructor.
void readCustomProperties (const QDomNode &layerNode, const QString &keyStartsWith="")
Read custom properties from project file.
void writeCustomProperties (QDomNode &layerNode, QDomDocument &doc) const
Write custom properties to project file.
void connectNotify (const char *signal)
debugging member - invoked when a connect() is made to this object
void appendError (const QgsErrorMessage &theMessage)
Add error message.
void setError (const QgsError &theError)
Set error message.
Private Slots
void onRelationsLoaded ()
Private Member Functions
QgsVectorLayer (const QgsVectorLayer &rhs)
vector layers are not copyable
QgsVectorLayer & operator= (QgsVectorLayer const &rhs)
vector layers are not copyable
bool setDataProvider (QString const &provider)
bind layer to a specific data provider
QgsFeatureId findFreeId ()
Goes through all features and finds a free id (e.g.
void snapToGeometry (const QgsPoint &startPoint, QgsFeatureId featureId, QgsGeometry *geom, double sqrSnappingTolerance, QMultiMap< double, QgsSnappingResult > &snappingResults, QgsSnapper::SnappingType snap_to) const
Snaps to a geometry and adds the result to the multimap if it is within the snapping result.
void stopRendererV2 (QgsRenderContext &rendererContext, QgsSingleSymbolRendererV2 *selRenderer)
Add joined attributes to a feature.
void prepareLabelingAndDiagrams (QgsRenderContext &rendererContext, QgsAttributeList &attributes, bool &labeling)
Registers label and diagram layer.
void readSldLabeling (const QDomNode &node)
Read labeling from SLD.
Static Private Member Functions
static
QgsVectorLayer::VertexMarkerType currentVertexMarkerType ()
Reads vertex marker type from settings.
static int currentVertexMarkerSize ()
Reads vertex marker size from settings.
Private Attributes
int mUpdateThreshold
Update threshold for drawing features as they are read.
bool mEnableBackbuffer
Enables backbuffering for the map window.
QgsVectorDataProvider * mDataProvider
Pointer to data provider derived from the abastract base class QgsDataProvider.
QgsFeatureIterator mProviderIterator
QString mDisplayField
index of the primary label field
QString mDisplayExpression
the preview expression used to generate a human readable preview string for features
QString mProviderKey
Data provider key.
QgsAttributeAction * mActions
The user-defined actions that are accessed from the Identify Results dialog box.
bool mReadOnly
Flag indicating whether the layer is in read-only mode (editing disabled) or not.
QgsFeatureIds mSelectedFeatureIds
Set holding the feature IDs that are activated.
QgsFields mUpdatedFields
field map to commit
QMap< QString, QString > mAttributeAliasMap
Map that stores the aliases for attributes.
QList
< QgsAttributeEditorElement * > mAttributeEditorElements
Stores a list of attribute editor elements (Each holding a tree structure for a tab in the attribute editor)
QSet< QString > mExcludeAttributesWMS
Attributes which are not published in WMS.
QSet< QString > mExcludeAttributesWFS
Attributes which are not published in WFS.
QList< TabData > mTabs
Map that stores the tab for attributes in the edit form.
int mWkbType
Geometry type as defined in enum WkbType (qgis.h)
QgsFeatureRendererV2 * mRendererV2
Renderer object which holds the information about how to display the features.
QgsVectorSimplifyMethod mSimplifyMethod
Simplification object which holds the information about how to simplify the features for fast rendering.
QgsLabel * mLabel
Label.
bool mLabelOn
Display labels.
bool mLabelFontNotFoundNotified
Whether 'labeling font not found' has be shown for this layer (only show once in QgsMessageBar, on first rendering)
QPainter::CompositionMode mFeatureBlendMode
Blend mode for features.
int mLayerTransparency
Layer transparency.
QgsVectorLayer::VertexMarkerType mCurrentVertexMarkerType
The current type of editing marker.
int mCurrentVertexMarkerSize
The current size of editing marker.
bool mVertexMarkerOnlyForSelection
Flag if the vertex markers should be drawn only for selection (true) or for all features (false)
QStringList mCommitErrors
QMap< QString, EditType > mEditTypes
QMap< QString, bool > mFieldEditables
QMap< QString, bool > mLabelOnTop
QMap< QString, QMap< QString,
QVariant > > mValueMaps
QMap< QString, RangeData > mRanges
QMap< QString, QPair< QString,
QString > > mCheckedStates
QMap< QString, ValueRelationData > mValueRelations
QMap< QString, QString > mDateFormats
QMap< QString, QSize > mWidgetSize
QMap< int, QString > mEditorWidgetV2Types
QMap< int, QMap< QString,
QVariant > > mEditorWidgetV2Configs
EditorLayout mEditorLayout
Defines the default layout to use for the attribute editor (Drag and drop, UI File, Generated)
QString mEditForm
QString mEditFormInit
QgsVectorLayer::FeatureFormSuppress mFeatureFormSuppress
Type of feature form suppression after feature creation.
QString mAnnotationForm
QgsGeometryCache * mCache
cache for some vector layer data - currently only geometries for faster editing
QgsVectorLayerEditBuffer * mEditBuffer
stores information about uncommitted changes to layer
QgsVectorLayerJoinBuffer * mJoinBuffer
QgsDiagramRendererV2 * mDiagramRenderer
QgsDiagramLayerSettings * mDiagramLayerSettings
bool mValidExtent
bool mLazyExtent
bool mSymbolFeatureCounted
QMap< QgsSymbolV2 *, long > mSymbolFeatureCountMap
QgsRenderContext * mCurrentRendererContext
Friends
class QgsVectorLayerEditBuffer
class QgsVectorLayerFeatureIterator
Additional Inherited Members
Protected Attributes inherited from QgsMapLayer
QgsRectangle mExtent
Extent of the layer.
bool mValid
Indicates if the layer is valid and can be drawn.
QString mDataSource
data source description string, varies by layer type
QString mLayerName
Name of the layer - used for display.
QString mLayerOrigName
Original name of the layer.
QString mTitle
QString mAbstract
Description of the layer.
QString mKeywordList
QString mDataUrl
DataUrl of the layer.
QString mDataUrlFormat
QString mAttribution
Attribution of the layer.
QString mAttributionUrl
QString mMetadataUrl
MetadataUrl of the layer.
QString mMetadataUrlType
QString mMetadataUrlFormat
QgsError mError
Error.
Detailed Description
Represents a vector layer which manages a vector based data sets.
The QgsVectorLayer is instantiated by specifying the name of a data provider, such as postgres or wfs, and url defining the specific data set to connect to. The vector layer constructor in turn instantiates a QgsVectorDataProvider subclass corresponding to the provider type, and passes it the url. The data provider connects to the data source.
The QgsVectorLayer provides a common interface to the different data types. It also manages editing transactions.
Sample usage of the QgsVectorLayer class:
QString uri = "point?crs=epsg:4326&field=id:integer";
QgsVectorLayer *scratchLayer = new QgsVectorLayer(uri, "Scratch point layer",  "memory");
The main data providers supported by QGIS are listed below.
Vector data providers
Memory data providerType (memory)
The memory data provider is used to construct in memory data, for example scratch data or data generated from spatial operations such as contouring. There is no inherent persistent storage of the data. The data source uri is constructed. The url specifies the geometry type ("point", "linestring", "polygon", "multipoint","multilinestring","multipolygon"), optionally followed by url parameters as follows:
crs=definition Defines the coordinate reference system to use for the layer. definition is any string accepted by QgsCoordinateReferenceSystem::createFromString()
index=yes Specifies that the layer will be constructed with a spatial index
field=name:type(length,precision) Defines an attribute of the layer. Multiple field parameters can be added to the data provider definition. type is one of "integer", "double", "string".
An example url is "Point?crs=epsg:4326&field=id:integer&field=name:string(20)&index=yes"
OGR data provider (ogr)
Accesses data using the OGR drivers (http://www.gdal.org/ogr/ogr_formats.html). The url is the OGR connection string. A wide variety of data formats can be accessed using this driver, including file based formats used by many GIS systems, database formats, and web services. Some of these formats are also supported by custom data providers listed below.
Spatialite data provider (spatialite)
Access data in a spatialite database. The url defines the connection parameters, table, geometry column, and other attributes. The url can be constructed using the QgsDataSourceURI class.
Postgresql data provider (postgres)
Connects to a postgresql database. The url defines the connection parameters, table, geometry column, and other attributes. The url can be constructed using the QgsDataSourceURI class.
Microsoft SQL server data provider (mssql)
Connects to a Microsoft SQL server database. The url defines the connection parameters, table, geometry column, and other attributes. The url can be constructed using the QgsDataSourceURI class.
SQL Anywhere data provider (sqlanywhere)
Connects to an SQLanywhere database. The url defines the connection parameters, table, geometry column, and other attributes. The url can be constructed using the QgsDataSourceURI class.
WFS (web feature service) data provider (wfs)
Used to access data provided by a web feature service.
The url can be a HTTP url to a WFS 1.0.0 server or a GML2 data file path. Examples are http://foobar/wfs or /foo/bar/file.gml
If a GML2 file path is provided the driver will attempt to read the schema from a file in the same directory with the same basename + .xsd. This xsd file must be in the same format as a WFS describe feature type response. If no xsd file is provide then the driver will attempt to guess the attribute types from the file.
In the case of a HTTP URL the FILTER query string parameter can be used to filter the WFS feature type. The FILTER key value can either be a QGIS expression or an OGC XML filter. If the value is set to a QGIS expression the driver will turn it into OGC XML filter before passing it to the WFS server. Beware the QGIS expression filter only supports =, != ,<,> ,<= ,>= ,AND ,OR ,NOT, LIKE, IS NULL attribute operators, BBOX, Disjoint, Intersects, Touches, Crosses, Contains, Overlaps, Within spatial binary operators and the QGIS local geomFromWKT, geomFromGML geometry constructor functions.
Also note:
You can use various functions available in the QGIS Expression list, however the function must exist server side and have the same name and arguments to work.
Use the special $geometry parameter to provide the layer geometry column as input into the spatial binary operators e.g intersects($geometry, geomFromWKT('POINT (5 6)'))
Delimited text file data provider (delimitedtext)
Accesses data in a delimited text file, for example CSV files generated by spreadsheets. The contents of the file are split into columns based on specified delimiter characters. Each record may be represented spatially either by an X and Y coordinate column, or by a WKT (well known text) formatted columns.
The url defines the filename, the formatting options (how the text in the file is divided into data fields, and which fields contain the X,Y coordinates or WKT text definition. The options are specified as url query items.
At its simplest the url can just be the filename, in which case it will be loaded as a CSV formatted file.
The url may include the following items:
encoding=UTF-8
Defines the character encoding in the file. The default is UTF-8. To use the default encoding for the operating system use "System".
type=(csv|regexp|whitespace|plain)
Defines the algorithm used to split records into columns. Records are defined by new lines, except for csv format files for which quoted fields may span multiple records. The default type is csv.
"csv" splits the file based on three sets of characters: delimiter characters, quote characters, and escape characters. Delimiter characters mark the end of a field. Quote characters enclose a field which can contain delimiter characters, and newlines. Escape characters cause the following character to be treated literally (including delimiter, quote, and newline characters). Escape and quote characters must be different from delimiter characters. Escape characters that are also quote characters are treated specially - they can only escape themselves within quotes. Elsewhere they are treated as quote characters. The defaults for delimiter, quote, and escape are ',', '"', '"'.
"regexp" splits each record using a regular expression (see QRegExp documentation for details).
"whitespace" splits each record based on whitespace (on or more whitespace characters. Leading whitespace in the record is ignored.
"plain" is provided for backwards compatibility. It is equivalent to CSV except that the default quote characters are single and double quotes, and there is no escape characters.
delimiter=characters
Defines the delimiter characters used for csv and plain type files, or the regular expression for regexp type files. It is a literal string of characters except that "\t" may be used to represent a tab character.
quote=characters
Defines the characters that are used as quote characters for csv and plain type files.
escape=characters
Defines the characters used to escape delimiter, quote, and newline characters.
skipLines=n
Defines the number of lines to ignore at the beginning of the file (default 0)
useHeader=(yes|no)
Defines whether the first record in the file (after skipped lines) contains column names (default yes)
trimFields=(yes|no)
If yes then leading and trailing whitespace will be removed from fields
skipEmptyFields=(yes|no)
If yes then empty fields will be discarded (eqivalent to concatenating consecutive delimiters)
maxFields=#
Specifies the maximum number of fields to load for each record. Additional fields will be discarded. Default is 0 - load all fields.
decimalPoint=c
Defines a character that is used as a decimal point in the numeric columns The default is '.'.
xField=column yField=column
Defines the name of the columns holding the x and y coordinates for XY point geometries. If the useHeader is no (ie there are no column names), then this is the column number (with the first column as 1).
xyDms=(yes|no)
If yes then the X and Y coordinates are interpreted as degrees/minutes/seconds format (fairly permissively), or degree/minutes format.
wktField=column
Defines the name of the columns holding the WKT geometry definition for WKT geometries. If the useHeader is no (ie there are no column names), then this is the column number (with the first column as 1).
geomType=(point|line|polygon|none)
Defines the geometry type for WKT type geometries. QGIS will only display one type of geometry for the layer - any others will be ignored when the file is loaded. By default the provider uses the type of the first geometry in the file. Use geomType to override this type.
geomType can also be set to none, in which case the layer is loaded without geometries.
subset=expression
Defines an expression that will identify a subset of records to display
crs=crsstring
Defines the coordinate reference system used for the layer. This can be any string accepted by QgsCoordinateReferenceSystem::createFromString()
-subsetIndex=(yes|no)
Determines whether the provider generates an index to improve the efficiency of subsets. The default is yes
-spatialIndex=(yes|no)
Determines whether the provider generates a spatial index. The default is no.
-watchFile=(yes|no)
Defines whether the file will be monitored for changes. The default is to monitor for changes.
quiet
Errors encountered loading the file will not be reported in a user dialog if quiet is included (They will still be shown in the output log).
GPX data provider (gpx)
Provider reads tracks, routes, and waypoints from a GPX file. The url defines the name of the file, and the type of data to retrieve from it ("track", "route", or "waypoint").
An example url is "/home/user/data/holiday.gpx?type=route"
Grass data provider (grass)
Provider to display vector data in a GRASS GIS layer.
Definition at line 451 of file qgsvectorlayer.h.
Member Enumeration Documentation
enum QgsVectorLayer::EditorLayout
The different types to layout the attribute editor.
Note
added in 1.9
Enumerator:
GeneratedLayout
TabLayout
UiFileLayout
Definition at line 457 of file qgsvectorlayer.h.
enum QgsVectorLayer::EditType
Enumerator:
LineEdit
UniqueValues
UniqueValuesEditable
ValueMap
Classification
EditRange
SliderRange
CheckBox
Note
added in 1.4
FileName
Enumeration
Immutable
The attribute value should not be changed in the attribute form.
Hidden
The attribute value should not be shown in the attribute form.
Note
added in 1.4
TextEdit
multiline edit
Note
added in 1.4
Calendar
calendar widget
Note
added in 1.5
DialRange
dial range
Note
added in 1.5
ValueRelation
value map from an table
Note
added in 1.8
UuidGenerator
uuid generator - readonly and automatically intialized
Note
added in 1.9
Photo
phote widget
Note
added in 1.9
WebView
webview widget
Note
added in 1.9
Color
color
Note
added in 1.9
EditorWidgetV2
modularized edit widgets
Note
added in 2.1
Definition at line 464 of file qgsvectorlayer.h.
enum QgsVectorLayer::FeatureFormSuppress
Types of feature form suppression after feature creation.
Note
added in 2.1
Enumerator:
SuppressDefault
SuppressOn
SuppressOff
Definition at line 491 of file qgsvectorlayer.h.
enum QgsVectorLayer::VertexMarkerType
Editing vertex markers.
Note
public from version 1.4
Enumerator:
SemiTransparentCircle
Cross
NoMarker
Definition at line 1322 of file qgsvectorlayer.h.
Constructor & Destructor Documentation
QgsVectorLayer::QgsVectorLayer (QString path = QString::null, QString baseName = QString::null, QString providerLib = QString::null, bool loadDefaultStyleFlag = true)
Constructor - creates a vector layer.
The QgsVectorLayer is constructed by instantiating a data provider. The provider interprets the supplied path (url) of the data source to connect to and access the data.
Parameters
path The path or url of the parameter. Typically this encodes parameters used by the data provider as url query items.
baseName The name used to represent the layer in the legend
providerLib The name of the data provider, eg "memory", "postgres"
loadDefaultStyleFlag whether to load the default style
Definition at line 116 of file qgsvectorlayer.cpp.
References checkJoinLayerRemove(), QgsFeatureRendererV2::defaultRenderer(), QgsVectorSimplifyMethod::forceLocalOptimization(), geometryType(), hasGeometryType(), QgsMapLayerRegistry::instance(), QgsProject::instance(), QgsMapLayer::loadDefaultStyle(), mActions, QgsVectorSimplifyMethod::maximumScale(), mProviderKey, mSimplifyMethod, QgsMapLayer::mValid, onRelationsLoaded(), selectionChanged(), setCoordinateSystem(), setDataProvider(), QgsVectorSimplifyMethod::setForceLocalOptimization(), QgsVectorSimplifyMethod::setMaximumScale(), setRendererV2(), QgsVectorSimplifyMethod::setSimplifyHints(), QgsVectorSimplifyMethod::setThreshold(), QgsVectorSimplifyMethod::simplifyHints(), and QgsVectorSimplifyMethod::threshold().
QgsVectorLayer::~QgsVectorLayer () virtual
Destructor.
Definition at line 198 of file qgsvectorlayer.cpp.
References layerDeleted(), mActions, mCache, mDataProvider, mDiagramLayerSettings, mEditBuffer, mJoinBuffer, mLabel, mRendererV2, QgsMapLayer::mValid, and QgsDebugMsg.
QgsVectorLayer::QgsVectorLayer (const QgsVectorLayer & rhs) private
vector layers are not copyable
Member Function Documentation
QgsAttributeAction* QgsVectorLayer::actions () inline
Definition at line 636 of file qgsvectorlayer.h.
Referenced by QgsAttributeTableModel::executeAction(), and QgsDualView::viewWillShowContextMenu().
bool QgsVectorLayer::addAttribute (const QgsField & field)
add an attribute field (but does not commit it) returns true if the field was added
Note
added in version 1.2
Definition at line 2591 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditBuffer::addAttribute(), mDataProvider, and mEditBuffer.
Referenced by QgsOfflineEditing::applyAttributesAdded().
void QgsVectorLayer::addAttributeAlias (int attIndex, QString aliasString)
Sets an alias (a display name) for attributes to display in dialogs.
Note
added in version 1.2
Definition at line 2599 of file qgsvectorlayer.cpp.
References layerModified(), mAttributeAliasMap, QgsMapLayer::name(), and pendingFields().
void QgsVectorLayer::addAttributeEditorWidget (QgsAttributeEditorElement * data)
Adds a tab (for the attribute editor form) holding groups and fields.
Note
added in version 2.0
Definition at line 2610 of file qgsvectorlayer.cpp.
References mAttributeEditorElements.
bool QgsVectorLayer::addFeature (QgsFeature & f, bool alsoUpdateExtent = true)
Adds a feature.
Parameters
f feature to add
alsoUpdateExtent If True, will also go to the effort of e.g. updating the extents.
Returns
True in case of success and False in case of error
Definition at line 1317 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditBuffer::addFeature(), mDataProvider, mEditBuffer, and updateExtents().
Referenced by QgsOfflineEditing::applyFeaturesAdded(), and QgsOfflineEditing::copyVectorLayer().
bool QgsVectorLayer::addFeatures (QgsFeatureList features, bool makeSelected = true)
Insert a copy of the given features into the layer (but does not commit it)
Definition at line 2855 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditBuffer::addFeatures(), mDataProvider, mEditBuffer, setSelectedFeatures(), and updateExtents().
void QgsVectorLayer::addJoin (const QgsVectorJoinInfo & joinInfo)
Joins another vector layer to this layer.
Parameters
joinInfo join object containing join layer id, target and source field
Note
added in 1.7
Definition at line 3344 of file qgsvectorlayer.cpp.
References QgsVectorLayerJoinBuffer::addJoin(), mJoinBuffer, and updateFields().
int QgsVectorLayer::addPart (const QList< QgsPoint > & ring)
Adds a new part polygon to a multipart feature.
Returns
0 in case of success, 1 if selected feature is not multipart, 2 if ring is not a valid geometry, 3 if new polygon ring not disjoint with existing rings, 4 if no feature was selected, 5 if several features are selected, 6 if selected geometry not found 7 layer not editable
Definition at line 1443 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditUtils::addPart(), mDataProvider, mEditBuffer, mSelectedFeatureIds, and QgsDebugMsg.
int QgsVectorLayer::addRing (const QList< QgsPoint > & ring)
Adds a ring to polygon/multipolygon features.
Returns
0 in case of success, 1 problem with feature type, 2 ring not closed, 3 ring not valid, 4 ring crosses existing rings, 5 no feature found where ring can be inserted 6 layer not editable
Definition at line 1434 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditUtils::addRing(), mDataProvider, and mEditBuffer.
int QgsVectorLayer::addTopologicalPoints (QgsGeometry * geom)
Adds topological points for every vertex of the geometry.
Parameters
geom the geometry where each vertex is added to segments of other features
Note
geom is not going to be modified by the function
Returns
0 in case of success
Definition at line 1537 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditUtils::addTopologicalPoints(), mDataProvider, and mEditBuffer.
int QgsVectorLayer::addTopologicalPoints (const QgsPoint & p)
Adds a vertex to segments which intersect point p but don't already have a vertex there.
If a feature already has a vertex at position p, no additional vertex is inserted. This method is useful for topological editing.
Parameters
p position of the vertex
Returns
0 in case of success
Definition at line 1546 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditUtils::addTopologicalPoints(), mDataProvider, and mEditBuffer.
QgsFeatureIds QgsVectorLayer::allFeatureIds ()
Get all feature Ids.
Definition at line 877 of file qgsvectorlayer.cpp.
References getFeatures(), QgsFeature::id(), QgsFeatureIterator::nextFeature(), and QgsFeatureRequest::NoGeometry.
Referenced by invertSelection(), and selectAll().
QString QgsVectorLayer::annotationForm () const inline
get annotation form (added in 1.5)
Definition at line 1240 of file qgsvectorlayer.h.
Referenced by QgsFormAnnotationItem::QgsFormAnnotationItem().
bool QgsVectorLayer::applyNamedStyle (QString namedStyle, QString errorMsg) virtual
Definition at line 4440 of file qgsvectorlayer.cpp.
References readSymbology(), QgsMapLayer::setMaximumScale(), QgsMapLayer::setMinimumScale(), QgsMapLayer::toggleScaleBasedVisibility(), and tr.
Referenced by loadNamedStyle().
void QgsVectorLayer::attributeAdded (int idx) signal
Will be emitted, when a new attribute has been added to this vector layer.
Applies only to types QgsFields::OriginEdit and QgsFields::OriginProvider
Parameters
idx The index of the new attribute
See Also
updatedFields()
Referenced by startEditing().
QString QgsVectorLayer::attributeAlias (int attributeIndex) const
Returns the alias of an attribute name or an empty string if there is no alias.
Note
added in version 1.2
Definition at line 2625 of file qgsvectorlayer.cpp.
References mAttributeAliasMap, QgsMapLayer::name(), and pendingFields().
Referenced by attributeDisplayName(), QgsAttributeTableModel::headerData(), QgsAttributeDialog::init(), and QgsComposerAttributeTable::initializeAliasMap().
const QMap< QString, QString >& QgsVectorLayer::attributeAliases () const inline
Definition at line 1151 of file qgsvectorlayer.h.
void QgsVectorLayer::attributeDeleted (int idx) signal
Will be emitted, when an attribute has been deleted from this vector layer.
Applies only to types QgsFields::OriginEdit and QgsFields::OriginProvider
Parameters
idx The index of the deleted attribute
See Also
updatedFields()
Referenced by startEditing().
QString QgsVectorLayer::attributeDisplayName (int attributeIndex) const
Convenience function that returns the attribute alias if defined or the field name else.
Note
added in version 1.2
Definition at line 2635 of file qgsvectorlayer.cpp.
References attributeAlias(), QgsFields::count(), and pendingFields().
Referenced by QgsAttributeEditor::createWidgetFromDef(), QgsAttributeAction::expandAction(), and QgsAttributeDialog::init().
QgsAttributeEditorElement * QgsVectorLayer::attributeEditorElementFromDomElement (QDomElement & elem, QObject * parent)
convert a saved attribute editor element into a AttributeEditor structure as it's used internally.
Parameters
elem the DOM element
parent the QObject which will own this object
Definition at line 2197 of file qgsvectorlayer.cpp.
References QgsAttributeEditorContainer::addChildElement(), dataProvider(), QgsVectorDataProvider::fieldNameMap(), and QgsMapLayer::name().
Referenced by readSymbology().
QList< QgsAttributeEditorElement * > & QgsVectorLayer::attributeEditorElements ()
Returns a list of tabs holding groups and fields.
Note
added in version 2.0
Definition at line 4268 of file qgsvectorlayer.cpp.
References mAttributeEditorElements.
Referenced by QgsAttributeDialog::init().
void QgsVectorLayer::attributeValueChanged (QgsFeatureId fid, int idx, const QVariant &) signal
Referenced by startEditing().
void QgsVectorLayer::beforeCommitChanges () signal
Is emitted, before changes are commited to the data provider.
Referenced by commitChanges().
void QgsVectorLayer::beforeRollBack () signal
Is emitted, before changes are rolled back.
Referenced by rollBack().
void QgsVectorLayer::beginEditCommand (QString text)
Create edit command for undo/redo operations.
Parameters
text text which is to be displayed in undo window
Definition at line 3294 of file qgsvectorlayer.cpp.
References editCommandStarted(), and QgsMapLayer::undoStack().
Referenced by QgsDualView::saveEditChanges(), and QgsAttributeTableDelegate::setModelData().
QgsRectangle QgsVectorLayer::boundingBoxOfSelected ()
Returns the bounding box of the selected features.
If there is no selection, QgsRectangle(0,0,0,0) is returned
Definition at line 1023 of file qgsvectorlayer.cpp.
References QgsGeometry::boundingBox(), QgsVectorDataProvider::capabilities(), QgsRectangle::combineExtentWith(), QgsFeature::geometry(), getFeatures(), QgsRectangle::height(), QgsFeature::id(), mDataProvider, mSelectedFeatureIds, QgsFeatureIterator::nextFeature(), QgsVectorDataProvider::SelectAtId, QgsRectangle::set(), QgsRectangle::setMinimal(), QgsRectangle::width(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by QgsGeometryAnalyzer::extent(), QgsMapCanvas::panToSelected(), and QgsMapCanvas::zoomToSelected().
QgsGeometryCache* QgsVectorLayer::cache () inline
Note
not available in python bindings
Definition at line 1377 of file qgsvectorlayer.h.
Referenced by QgsVectorLayerUndoCommand::cache().
QString QgsVectorLayer::capabilitiesString () const
Capabilities for this layer in a friendly format.
Definition at line 228 of file qgsvectorlayer.cpp.
References QgsVectorDataProvider::capabilitiesString(), and mDataProvider.
Referenced by metadata().
bool QgsVectorLayer::changeAttributeValue (QgsFeatureId fid, int field, QVariant value, bool emitSignal)
Changes an attribute value (but does not commit it)
Deprecated:
The emitSignal parameter is obsolete and not considered at the moment. It will be removed in future releases. Remove it to be prepared for the future. (Since 2.1)
Definition at line 2577 of file qgsvectorlayer.cpp.
Referenced by QgsOfflineEditing::applyAttributeValueChanges(), QgsRelationEditorWidget::on_mLinkFeatureButton_clicked(), QgsRelationEditorWidget::on_mUnlinkFeatureButton_clicked(), QgsDualView::saveEditChanges(), QgsAttributeTableDelegate::setModelData(), and updateFeature().
bool QgsVectorLayer::changeAttributeValue (QgsFeatureId fid, int field, const QVariant & newValue, const QVariant & oldValue = QVariant())
Changes an attribute value (but does not commit it)
Parameters
fid The feature id of the feature to be changed
field The index of the field to be updated
newValue The value which will be assigned to the field
oldValue The previous value to restore on undo (will otherwise be retrieved)
Returns
true in case of success
Definition at line 2583 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditBuffer::changeAttributeValue(), mDataProvider, and mEditBuffer.
bool QgsVectorLayer::changeGeometry (QgsFeatureId fid, QgsGeometry * geom)
change feature's geometry
Note
added in version 1.2
Definition at line 2564 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditBuffer::changeGeometry(), mDataProvider, mEditBuffer, and updateExtents().
Referenced by QgsOfflineEditing::applyGeometryChanges(), and updateFeature().
QPair< QString, QString > QgsVectorLayer::checkedState (int idx)
return string representing 'true' for a checkbox (added in 1.4)
Note
not available in python bindings FIXME: need SIP binding for QPair<QString, QString>
Definition at line 3321 of file qgsvectorlayer.cpp.
References QgsFields::count(), mCheckedStates, QgsMapLayer::name(), and pendingFields().
Referenced by QgsAttributeEditor::retrieveValue(), and QgsAttributeEditor::setValue().
void QgsVectorLayer::checkJoinLayerRemove (QString theLayerId) slot
Check if there is a join with a layer that will be removed.
Note
added in 1.7
Definition at line 3350 of file qgsvectorlayer.cpp.
References removeJoin().
Referenced by QgsVectorLayer(), and readXml().
void QgsVectorLayer::clearAttributeEditorWidgets ()
Clears all the tabs for the attribute editor form.
Note
added in version 2.0
Definition at line 4273 of file qgsvectorlayer.cpp.
References mAttributeEditorElements.
bool QgsVectorLayer::commitChanges ()
Attempts to commit any changes to disk.
Returns the result of the attempt. If a commit fails, the in-memory changes are left alone.
This allows editing to continue if the commit failed on e.g. a disallowed value in a Postgres database - the user can re-edit and try again.
The commits occur in distinct stages, (add attributes, add features, change attribute values, change geometries, delete features, delete attributes) so if a stage fails, it's difficult to roll back cleanly. Therefore any error message also includes which stage failed so that the user has some chance of repairing the damage cleanly.
Definition at line 2725 of file qgsvectorlayer.cpp.
References beforeCommitChanges(), QgsVectorLayerEditBuffer::commitChanges(), QgsGeometryCache::deleteCachedGeometries(), editingStopped(), QgsMessageLog::logMessage(), mCache, mCommitErrors, mDataProvider, mEditBuffer, QgsMapLayer::setCacheImage(), tr, QgsMapLayer::undoStack(), QgsDataProvider::updateExtents(), and updateFields().
Referenced by QgsOfflineEditing::copyVectorLayer(), and QgsOfflineEditing::synchronize().
const QStringList & QgsVectorLayer::commitErrors ()
Definition at line 2771 of file qgsvectorlayer.cpp.
References mCommitErrors.
Referenced by QgsOfflineEditing::copyVectorLayer(), and QgsOfflineEditing::synchronize().
void QgsVectorLayer::committedAttributesAdded (const QString & layerId, const QList< QgsField > & addedAttributes) signal
void QgsVectorLayer::committedAttributesDeleted (const QString & layerId, const QgsAttributeList & deletedAttributes) signal
Signals emitted after committing changes.
Note
added in v1.6
void QgsVectorLayer::committedAttributeValuesChanges (const QString & layerId, const QgsChangedAttributesMap & changedAttributesValues) signal
void QgsVectorLayer::committedFeaturesAdded (const QString & layerId, const QgsFeatureList & addedFeatures) signal
Referenced by startEditing().
void QgsVectorLayer::committedFeaturesRemoved (const QString & layerId, const QgsFeatureIds & deletedFeatureIds) signal
Referenced by startEditing().
void QgsVectorLayer::committedGeometriesChanges (const QString & layerId, const QgsGeometryMap & changedGeometries) signal
bool QgsVectorLayer::countSymbolFeatures (bool showProgress = true)
Count features for symbols.
Feature counts may be get by featureCount(QgsSymbolV2*).
Parameters
showProgress show progress dialog
Returns
true if calculated, false if failed or was canceled by user
Definition at line 1100 of file qgsvectorlayer.cpp.
References getFeatures(), QgsFeatureRendererV2::legendSymbolItems(), mDataProvider, mRendererV2, mSymbolFeatureCounted, mSymbolFeatureCountMap, QgsMapLayer::name(), QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, pendingFeatureCount(), QgsDebugMsg, QgsRenderContext::setRendererScale(), QgsFeatureRendererV2::startRender(), QgsFeatureRendererV2::stopRender(), QgsFeatureRendererV2::symbolsForFeature(), and tr.
Referenced by QgsLegendModel::addVectorLayerItemsV2(), and QgsLegendModel::updateSymbolV2ItemText().
void QgsVectorLayer::createJoinCaches ()
Caches joined attributes if required (and not already done)
Note
added in 1.7
Definition at line 3385 of file qgsvectorlayer.cpp.
References QgsVectorLayerJoinBuffer::containsJoins(), QgsVectorLayerJoinBuffer::createJoinCaches(), and mJoinBuffer.
int QgsVectorLayer::currentVertexMarkerSize () static private
Reads vertex marker size from settings.
Definition at line 3043 of file qgsvectorlayer.cpp.
Referenced by draw(), and drawRendererV2Levels().
QgsVectorLayer::VertexMarkerType QgsVectorLayer::currentVertexMarkerType () static private
Reads vertex marker type from settings.
Definition at line 3025 of file qgsvectorlayer.cpp.
References Cross, NoMarker, and SemiTransparentCircle.
Referenced by draw(), and drawRendererV2Levels().
QString QgsVectorLayer::dataComment () const
Returns a comment for the data in the layer.
Definition at line 237 of file qgsvectorlayer.cpp.
References QgsVectorDataProvider::dataComment(), and mDataProvider.
Referenced by metadata().
QgsVectorDataProvider * QgsVectorLayer::dataProvider ()
Returns the data provider.
Definition at line 936 of file qgsvectorlayer.cpp.
References mDataProvider.
Referenced by QgsQueryBuilder::accept(), QgsVectorLayerEditBuffer::addAttribute(), QgsVectorLayerEditBuffer::addFeature(), QgsVectorLayerEditBuffer::addFeatures(), QgsOfflineEditing::applyAttributesAdded(), QgsOfflineEditing::applyFeaturesAdded(), attributeEditorElementFromDomElement(), QgsGeometryAnalyzer::buffer(), QgsZonalStatistics::calculateStatistics(), QgsGeometryAnalyzer::centroids(), QgsVectorLayerEditBuffer::changeAttributeValue(), QgsVectorLayerEditBuffer::changeGeometry(), QgsVectorLayerEditBuffer::commitChanges(), QgsGeometryAnalyzer::convexHull(), QgsOfflineEditing::copyVectorLayer(), QgsAttributeEditor::createAttributeEditor(), QgsRelationEditorWidget::createRelationEditor(), QgsVectorLayerEditBuffer::deleteAttribute(), QgsVectorLayerEditBuffer::deleteFeature(), QgsGeometryAnalyzer::dissolve(), QgsGeometryAnalyzer::eventLayer(), QgsGeometryAnalyzer::extent(), QgsVectorLayerFeatureIterator::fetchFeature(), QgsVectorLayerCache::getFeatures(), QgsZonalStatistics::getUniqueFieldName(), QgsAttributeDialog::init(), QgsOverlayAnalyzer::intersection(), metadata(), QgsVectorLayerFeatureIterator::nextFeatureFid(), QgsVectorLayerFeatureIterator::providerCanSimplify(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), QgsPalLayerSettings::readDataDefinedProperty(), QgsFeatureListModel::setDisplayExpression(), QgsGeometryAnalyzer::simplify(), QgsVectorLayerEditUtils::splitFeatures(), QgsQueryBuilder::test(), QgsProjectFileTransform::transform0110to1000(), uniqueValues(), QgsVectorLayerFeatureIterator::useChangedAttributeFeature(), and QgsVectorFileWriter::writeAsVectorFormat().
const QgsVectorDataProvider * QgsVectorLayer::dataProvider () const
Returns the data provider in a const-correct manner.
Note
not available in python bindings
Definition at line 941 of file qgsvectorlayer.cpp.
References mDataProvider.
QString & QgsVectorLayer::dateFormat (int idx)
access date format
Note
added in 1.9
Definition at line 3211 of file qgsvectorlayer.cpp.
References mDateFormats, and pendingFields().
Referenced by QgsAttributeEditor::createAttributeEditor(), QgsAttributeDialog::init(), QgsAttributeEditor::retrieveValue(), and QgsAttributeEditor::setValue().
bool QgsVectorLayer::deleteAttribute (int attr)
delete an attribute field (but does not commit it)
Definition at line 2649 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditBuffer::deleteAttribute(), mDataProvider, and mEditBuffer.
Referenced by deleteAttributes().
bool QgsVectorLayer::deleteAttributes (QList< int > attrs)
Deletes a list of attribute fields (but does not commit it)
Parameters
attrs the indices of the attributes to delete
Returns
true if at least one attribute has been deleted
Definition at line 2657 of file qgsvectorlayer.cpp.
References deleteAttribute().
bool QgsVectorLayer::deleteFeature (QgsFeatureId fid)
delete a feature from the layer (but does not commit it)
Definition at line 2677 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditBuffer::deleteFeature(), mEditBuffer, mSelectedFeatureIds, and updateExtents().
Referenced by QgsOfflineEditing::applyFeaturesRemoved(), deleteSelectedFeatures(), and QgsRelationEditorWidget::on_mDeleteFeatureButton_clicked().
bool QgsVectorLayer::deleteSelectedFeatures ()
Deletes the selected features.
Returns
true in case of success and false otherwise
Definition at line 1405 of file qgsvectorlayer.cpp.
References QgsVectorDataProvider::capabilities(), deleteFeature(), QgsVectorDataProvider::DeleteFeatures, isEditable(), mDataProvider, mSelectedFeatureIds, QgsMapLayer::setCacheImage(), triggerRepaint(), and updateExtents().
bool QgsVectorLayer::deleteVertex (QgsFeatureId atFeatureId, int atVertex)
Deletes a vertex from a feature.
Definition at line 1395 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditUtils::deleteVertex(), mDataProvider, and mEditBuffer.
void QgsVectorLayer::deselect (const QgsFeatureId featureId) slot
Deselect feature by its ID.
Parameters
featureId The id of the feature to deselect
See Also
deselect(QgsFeatureIds)
Definition at line 804 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds, selectionChanged(), and QgsMapLayer::setCacheImage().
Referenced by QgsVectorLayerSelectionManager::deselect().
void QgsVectorLayer::deselect (const QgsFeatureIds & featureIds) slot
Deselect features by their ID.
Parameters
featureIds The ids of the features to deselect
See Also
deselect(QgsFeatureId)
Definition at line 812 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds, selectionChanged(), and QgsMapLayer::setCacheImage().
void QgsVectorLayer::destroyEditCommand ()
Destroy active command and reverts all changes in it.
Definition at line 3306 of file qgsvectorlayer.cpp.
References editCommandDestroyed(), and QgsMapLayer::undoStack().
const QgsDiagramLayerSettings* QgsVectorLayer::diagramLayerSettings () const inline
Definition at line 720 of file qgsvectorlayer.h.
const QgsDiagramRendererV2* QgsVectorLayer::diagramRenderer () const inline
Definition at line 717 of file qgsvectorlayer.h.
const QString QgsVectorLayer::displayExpression ()
Get the preview expression, used to create a human readable preview string.
Uses QgsExpression
Returns
The expression which will be used to preview features for this layer
Note
added in 2.0
Definition at line 3082 of file qgsvectorlayer.cpp.
References mDisplayExpression.
Referenced by QgsDualView::columnBoxInit(), QgsDualView::previewExpressionBuilder(), and setDisplayExpression().
const QString QgsVectorLayer::displayField () const
Returns the primary display field name used in the identify results dialog.
Definition at line 3072 of file qgsvectorlayer.cpp.
References mDisplayField.
Referenced by QgsDualView::columnBoxInit(), QgsMapTip::fetchFeature(), and writeSymbology().
bool QgsVectorLayer::draw (QgsRenderContext & rendererContext) virtual
Draws the layer.
Returns
false if an error occurred during drawing
Reimplemented from QgsMapLayer.
Definition at line 653 of file qgsvectorlayer.cpp.
References QgsFeatureRendererV2::capabilities(), QgsRectangle::center(), QgsRenderContext::coordinateTransform(), currentVertexMarkerSize(), currentVertexMarkerType(), QgsGeometryCache::deleteCachedGeometries(), drawRendererV2(), drawRendererV2Levels(), QgsFeatureRendererV2::dump(), QgsRenderContext::extent(), fieldNameIndex(), QgsVectorSimplifyMethod::forceLocalOptimization(), QgsCoordinateReferenceSystem::geographicFlag(), QgsVectorSimplifyMethod::GeometrySimplification, getFeatures(), hasGeometryType(), QgsRectangle::isEmpty(), QgsRectangle::isFinite(), QgsMessageLog::logMessage(), QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), mCache, mEditBuffer, mEnableBackbuffer, mRendererV2, mSimplifyMethod, mUpdateThreshold, QgsSimplifyMethod::OptimizeForRendering, QgsRenderContext::painter(), prepareLabelingAndDiagrams(), QgsDebugMsg, QgsGeometryCache::setCachedGeometriesRect(), QgsFeatureRequest::setFilterRect(), QgsSimplifyMethod::setForceLocalOptimization(), QgsSimplifyMethod::setMethodType(), QgsFeatureRequest::setSimplifyMethod(), QgsSimplifyMethod::setTolerance(), QgsFeatureRendererV2::setVertexMarkerAppearance(), simplifyDrawingCanbeApplied(), simplifyMethod(), QgsCoordinateTransform::sourceCrs(), QgsFeatureRendererV2::startRender(), QgsFeatureRendererV2::SymbolLevels, QgsVectorSimplifyMethod::threshold(), QgsRectangle::toString(), tr, QgsCoordinateTransform::transform(), QgsFeatureRendererV2::usedAttributes(), QgsFeatureRendererV2::usingSymbolLevels(), QgsException::what(), QgsPoint::x(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsPoint::y(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
void QgsVectorLayer::drawLabels (QgsRenderContext & rendererContext) virtual
Draws the layer labels using coordinate transformation.
Reimplemented from QgsMapLayer.
Definition at line 335 of file qgsvectorlayer.cpp.
References QgsLabel::addRequiredFields(), QgsRenderContext::extent(), featureCount(), fieldNameIndex(), getFeatures(), hasGeometryType(), QgsLabel::maxScale(), QgsLabel::minScale(), mLabel, mLabelOn, mRendererV2, mSelectedFeatureIds, QgsFeatureIterator::nextFeature(), QgsDebugMsg, QgsRenderContext::rendererScale(), QgsLabel::renderLabel(), QgsLabel::scaleBasedVisibility(), QgsFeatureRendererV2::startRender(), QgsFeatureRendererV2::stopRender(), QgsFeatureRendererV2::usedAttributes(), and QgsFeatureRendererV2::willRenderFeature().
void QgsVectorLayer::drawRendererV2 (QgsFeatureIterator & fit, QgsRenderContext & rendererContext, bool labeling)
Draw layer with renderer V2.
QgsFeatureRenderer::startRender() needs to be called before using this method
Note
added in 1.4
Definition at line 404 of file qgsvectorlayer.cpp.
References QgsGeometryCache::cacheGeometry(), featureCount(), QgsFeature::geometry(), hasGeometryType(), QgsFeature::id(), QgsRenderContext::labelingEngine(), mCache, mCurrentRendererContext, mDiagramRenderer, mEditBuffer, mEnableBackbuffer, mRendererV2, mSelectedFeatureIds, mUpdateThreshold, QgsFeatureIterator::nextFeature(), QgsDebugMsg, QgsLabelingEngineInterface::registerDiagramFeature(), QgsLabelingEngineInterface::registerFeature(), QgsFeatureRendererV2::renderFeature(), QgsRenderContext::renderingStopped(), QgsMapLayer::screenUpdateRequested(), stopRendererV2(), and QgsException::what().
Referenced by draw().
void QgsVectorLayer::drawRendererV2Levels (QgsFeatureIterator & fit, QgsRenderContext & rendererContext, bool labeling)
Draw layer with renderer V2 using symbol levels.
QgsFeatureRenderer::startRender() needs to be called before using this method
Note
added in 1.4
Definition at line 497 of file qgsvectorlayer.cpp.
References QgsGeometryCache::cacheGeometry(), currentVertexMarkerSize(), currentVertexMarkerType(), QgsSymbolV2::defaultSymbol(), featureCount(), QgsFeature::geometry(), geometryType(), hasGeometryType(), QgsFeature::id(), QgsRenderContext::labelingEngine(), QgsSymbolV2LevelItem::layer(), mCache, mDiagramRenderer, mEditBuffer, mRendererV2, mSelectedFeatureIds, QgsFeatureIterator::nextFeature(), QgsDebugMsg, QgsLabelingEngineInterface::registerDiagramFeature(), QgsLabelingEngineInterface::registerFeature(), QgsFeatureRendererV2::renderFeature(), QgsSymbolLayerV2::renderingPass(), QgsRenderContext::renderingStopped(), QgsRenderContext::selectionColor(), QgsSymbolV2::setColor(), QgsFeatureRendererV2::setVertexMarkerAppearance(), QgsSingleSymbolRendererV2::startRender(), stopRendererV2(), QgsSingleSymbolRendererV2::symbol(), QgsSymbolV2LevelItem::symbol(), QgsFeatureRendererV2::symbolForFeature(), QgsSymbolV2::symbolLayer(), QgsSymbolV2::symbolLayerCount(), QgsFeatureRendererV2::symbols(), and QgsException::what().
Referenced by draw().
void QgsVectorLayer::drawVertexMarker (double x, double y, QPainter & p, QgsVectorLayer::VertexMarkerType type, int vertexSize) static
Draws a vertex symbol at (screen) coordinates x, y.
(Useful to assist vertex editing.)
Note
public and static from version 1.4
Definition at line 772 of file qgsvectorlayer.cpp.
References Cross, and SemiTransparentCircle.
Referenced by QgsFeatureRendererV2::renderVertexMarker().
QgsVectorLayerEditBuffer* QgsVectorLayer::editBuffer () inline
Buffer with uncommitted editing operations. Only valid after editing has been turned on.
Definition at line 1301 of file qgsvectorlayer.h.
Referenced by QgsVectorLayerEditUtils::addPart(), QgsVectorLayerEditUtils::addRing(), QgsFeatureListModel::data(), QgsVectorLayerEditUtils::deleteVertex(), QgsAttributeTableFilterModel::filterAcceptsRow(), QgsVectorLayerEditUtils::insertVertex(), QgsVectorLayerEditUtils::moveVertex(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), QgsVectorLayerEditUtils::splitFeatures(), QgsVectorLayerEditUtils::splitParts(), QgsOfflineEditing::startListenFeatureChanges(), QgsOfflineEditing::stopListenFeatureChanges(), and QgsVectorLayerEditUtils::translateFeature().
void QgsVectorLayer::editCommandDestroyed () signal
Signal emitted, whan an edit command is destroyed.
Note
This is not a rollback, it is only related to the current edit command. See beforeRollBack()
Referenced by destroyEditCommand().
void QgsVectorLayer::editCommandEnded () signal
Signal emitted, when an edit command successfully ended.
Note
This does not mean it is also committed, only that it is written to the edit buffer. See beforeCommitChanges()
Referenced by endEditCommand().
void QgsVectorLayer::editCommandStarted (const QString & text) signal
Signal emitted when a new edit command has been started.
Parameters
text Description for this edit command
Referenced by beginEditCommand().
QString QgsVectorLayer::editForm ()
get edit form (added in 1.4)
Definition at line 3148 of file qgsvectorlayer.cpp.
References mEditForm.
Referenced by QgsAttributeDialog::init().
QString QgsVectorLayer::editFormInit ()
get python function for edit form initialization (added in 1.4)
Definition at line 3163 of file qgsvectorlayer.cpp.
References mEditFormInit.
Referenced by QgsAttributeDialog::init().
void QgsVectorLayer::editingStarted () signal
Is emitted, when editing on this layer has started.
Referenced by startEditing().
void QgsVectorLayer::editingStopped () signal
Is emitted, when edited changes successfully have been written to the data provider.
Referenced by commitChanges(), and rollBack().
QgsVectorLayer::EditorLayout QgsVectorLayer::editorLayout ()
get the active layout for the attribute editor for this layer (added in 1.9)
Definition at line 3128 of file qgsvectorlayer.cpp.
References mEditorLayout.
Referenced by QgsAttributeDialog::init(), setEditorLayout(), and QgsAttributeDialog::~QgsAttributeDialog().
const QString QgsVectorLayer::editorWidgetV2 (int fieldIdx)
Get the id for the editor widget used to represent the field at the given index.
Parameters
fieldIdx The index of the field
Returns
The id for the editor widget or a NULL string if not applicable
Definition at line 2615 of file qgsvectorlayer.cpp.
References mEditorWidgetV2Types.
Referenced by QgsAttributeEditor::createAttributeEditor().
const QgsEditorWidgetConfig QgsVectorLayer::editorWidgetV2Config (int fieldIdx)
Get the configuration for the editor widget used to represent the field at the given index.
Parameters
fieldIdx The index of the field
Returns
The id for the editor widget or a NULL string if not configured
Definition at line 2620 of file qgsvectorlayer.cpp.
References mEditorWidgetV2Configs.
Referenced by QgsAttributeEditor::createAttributeEditor().
QgsVectorLayer::EditType QgsVectorLayer::editType (int idx)
get edit type
Definition at line 3112 of file qgsvectorlayer.cpp.
References QgsFields::count(), LineEdit, mEditTypes, QgsMapLayer::name(), and pendingFields().
Referenced by QgsDualView::columnBoxInit(), QgsAttributeEditor::createAttributeEditor(), QgsAttributeTableDelegate::createEditor(), QgsAttributeEditor::createWidgetFromDef(), QgsAttributeTableModel::data(), QgsAttributeDialog::init(), QgsAttributeTableModel::loadAttributes(), readSymbology(), QgsAttributeEditor::retrieveValue(), and QgsAttributeEditor::setValue().
void QgsVectorLayer::enableLabels (bool on)
Set labels on.
Definition at line 1565 of file qgsvectorlayer.cpp.
References mLabelOn.
Referenced by readSymbology().
void QgsVectorLayer::endEditCommand ()
Finish edit command and add it to undo/redo stack.
Definition at line 3300 of file qgsvectorlayer.cpp.
References editCommandEnded(), and QgsMapLayer::undoStack().
Referenced by QgsDualView::saveEditChanges(), and QgsAttributeTableDelegate::setModelData().
const QSet<QString>& QgsVectorLayer::excludeAttributesWFS () const inline
Definition at line 1156 of file qgsvectorlayer.h.
const QSet<QString>& QgsVectorLayer::excludeAttributesWMS () const inline
Definition at line 1153 of file qgsvectorlayer.h.
QgsRectangle QgsVectorLayer::extent () virtual
Return the extent of the layer as a QRect.
Reimplemented from QgsMapLayer.
Definition at line 1181 of file qgsvectorlayer.cpp.
References QgsGeometry::boundingBox(), QgsRectangle::combineExtentWith(), QgsDataProvider::extent(), QgsVectorDataProvider::featureCount(), QgsFeature::geometry(), getFeatures(), hasGeometryType(), QgsVectorLayerEditBuffer::mAddedFeatures, QgsVectorLayerEditBuffer::mChangedGeometries, mDataProvider, QgsVectorLayerEditBuffer::mDeletedFeatureIds, mEditBuffer, mLazyExtent, mValidExtent, QgsFeatureIterator::nextFeature(), QgsDebugMsg, QgsMapLayer::recalculateExtents(), setExtent(), QgsRectangle::setMinimal(), QgsRectangle::toString(), QgsGeometry::type(), QGis::UnknownGeometry, QgsDataProvider::updateExtents(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
Referenced by QgsGeometryAnalyzer::extent(), and metadata().
void QgsVectorLayer::featureAdded (QgsFeatureId fid) signal
Referenced by startEditing().
QPainter::CompositionMode QgsVectorLayer::featureBlendMode () const
Read blend mode for layer.
Definition at line 3581 of file qgsvectorlayer.cpp.
References mFeatureBlendMode.
Referenced by QgsComposerMap::containsAdvancedEffects(), QgsMapRenderer::render(), setFeatureBlendMode(), and writeSymbology().
void QgsVectorLayer::featureBlendModeChanged (const QPainter::CompositionMode & blendMode) signal
Signal emitted when setFeatureBlendMode() is called.
Referenced by setFeatureBlendMode().
long QgsVectorLayer::featureCount () const virtual
Number of features in the layer.
This is necessary if features are added/deleted or the layer has been subsetted. If the data provider chooses not to support this feature, the total number of features can be returned.
Returns
long containing number of features
Definition at line 1083 of file qgsvectorlayer.cpp.
References QgsVectorDataProvider::featureCount(), mDataProvider, and QgsDebugMsg.
Referenced by QgsGeometryAnalyzer::buffer(), QgsGeometryAnalyzer::centroids(), QgsGeometryAnalyzer::convexHull(), QgsOfflineEditing::copyVectorLayer(), QgsTransectSample::createSample(), QgsGeometryAnalyzer::dissolve(), drawLabels(), drawRendererV2(), drawRendererV2Levels(), QgsVectorLayerImport::importLayer(), QgsOverlayAnalyzer::intersection(), metadata(), QgsVectorLayerCache::onFeatureAdded(), QgsVectorLayerCache::setFullCache(), QgsGeometryAnalyzer::simplify(), QgsQueryBuilder::test(), QgsOfflineEditing::updateFidLookup(), QgsLegendModel::updateLayerItemText(), and QgsLegendModel::updateSymbolV2ItemText().
long QgsVectorLayer::featureCount (QgsSymbolV2 * symbol)
Number of features rendered with specified symbol.
Features must be first calculated by countSymbolFeatures()
Parameters
symbol the symbol
Returns
number of features rendered by symbol or -1 if failed or counts are not available
Definition at line 1094 of file qgsvectorlayer.cpp.
References mSymbolFeatureCounted, and mSymbolFeatureCountMap.
void QgsVectorLayer::featureDeleted (QgsFeatureId fid) signal
Referenced by startEditing().
QgsVectorLayer::FeatureFormSuppress QgsVectorLayer::featureFormSuppress () const inline
Type of feature form pop-up suppression after feature creation (overrides app setting)
Note
added in 2.1
Definition at line 1233 of file qgsvectorlayer.h.
Referenced by writeSymbology().
bool QgsVectorLayer::fieldEditable (int idx)
is edit widget editable
Note
added in 1.9
Definition at line 3235 of file qgsvectorlayer.cpp.
References QgsFields::count(), QgsFields::fieldOrigin(), mFieldEditables, mUpdatedFields, QgsMapLayer::name(), QgsFields::OriginJoin, and pendingFields().
Referenced by QgsAttributeTableDelegate::createEditor(), QgsAttributeEditor::createWidgetFromDef(), and QgsAttributeDialog::init().
int QgsVectorLayer::fieldNameIndex (const QString & fieldName) const
Returns the index of a field name or -1 if the field does not exist.
Note
this method was added in version 1.4
Definition at line 3330 of file qgsvectorlayer.cpp.
References QgsFields::count(), QgsMapLayer::name(), and pendingFields().
Referenced by QgsVectorFileWriter::addRendererAttributes(), QgsDualView::columnBoxInit(), QgsAttributeEditor::createAttributeEditor(), QgsPointDisplacementRenderer::createDisplacementGroups(), QgsGraduatedSymbolRendererV2::createRenderer(), draw(), drawLabels(), QgsMapTip::fetchFeature(), QgsExpressionBuilderWidget::loadAllValues(), QgsAttributeTableModel::loadAttributes(), QgsExpressionBuilderWidget::loadSampleValues(), QgsRelationEditorWidget::on_mLinkFeatureButton_clicked(), QgsRelationEditorWidget::on_mUnlinkFeatureButton_clicked(), prepareLabelingAndDiagrams(), QgsPalLabeling::prepareLayer(), readSldLabeling(), readSymbology(), QgsRelationManager::referencingRelations(), QgsPointDisplacementRenderer::startRender(), QgsVectorFieldSymbolLayer::startRender(), QgsGraduatedSymbolRendererV2::startRender(), QgsCategorizedSymbolRendererV2::startRender(), QgsRelation::updateRelationStatus(), and writeSymbology().
QgsFeatureId QgsVectorLayer::findFreeId () private
Goes through all features and finds a free id (e.g.
to give it temporarily to a not-commited feature)
void QgsVectorLayer::geometryChanged (QgsFeatureId fid, QgsGeometry & geom) signal
Referenced by startEditing().
QGis::GeometryType QgsVectorLayer::geometryType () const
Returns point, line or polygon.
Definition at line 961 of file qgsvectorlayer.cpp.
References QgsVectorDataProvider::geometryType(), QGis::Line, mDataProvider, QGis::NoGeometry, QGis::Point, QGis::Polygon, QgsDebugMsg, QgsMapLayer::type(), QGis::UnknownGeometry, QGis::WKBLineString, QGis::WKBLineString25D, QGis::WKBMultiLineString, QGis::WKBMultiLineString25D, QGis::WKBMultiPoint, QGis::WKBMultiPoint25D, QGis::WKBMultiPolygon, QGis::WKBMultiPolygon25D, QGis::WKBNoGeometry, QGis::WKBPoint, QGis::WKBPoint25D, QGis::WKBPolygon, and QGis::WKBPolygon25D.
Referenced by QgsVectorLayerEditUtils::addPart(), QgsZonalStatistics::calculateStatistics(), QgsPointSample::createRandomPoints(), drawRendererV2Levels(), hasGeometryType(), QgsMapToolIdentify::identify(), metadata(), QgsVectorLayerFeatureIterator::prepareSimplification(), QgsAttributeTableModel::QgsAttributeTableModel(), QgsVectorLayer(), readSld(), readSymbology(), selectedFeatures(), simplifyDrawingCanbeApplied(), snapToGeometry(), and writeXml().
QgsFeatureIterator QgsVectorLayer::getFeatures (const QgsFeatureRequest & request = QgsFeatureRequest())
Query the provider for features specified in request.
Definition at line 1308 of file qgsvectorlayer.cpp.
References mDataProvider, and QgsVectorLayerFeatureIterator.
Referenced by QgsVectorLayerEditUtils::addPart(), QgsVectorLayerEditUtils::addRing(), allFeatureIds(), QgsOfflineEditing::applyFeaturesAdded(), QgsGeometry::avoidIntersections(), boundingBoxOfSelected(), QgsGeometryAnalyzer::buffer(), QgsInterpolator::cacheBaseData(), QgsVectorLayerJoinBuffer::cacheJoinLayer(), QgsGeometryAnalyzer::centroids(), QgsGeometryAnalyzer::convexHull(), QgsOfflineEditing::copyVectorLayer(), QgsSearchQueryBuilder::countRecords(), countSymbolFeatures(), QgsAttributeEditor::createAttributeEditor(), QgsFormAnnotationItem::createDesignerWidget(), QgsPointDisplacementRenderer::createDisplacementGroups(), QgsPointSample::createRandomPoints(), QgsGraduatedSymbolRendererV2::createRenderer(), QgsTransectSample::createSample(), QgsGeometryAnalyzer::dissolve(), draw(), drawLabels(), QgsGeometryAnalyzer::eventLayer(), extent(), QgsVectorLayerCache::featureAtId(), QgsMapTip::fetchFeature(), QgsTransectSample::findBaselineGeometry(), QgsComposerAttributeTable::getFeatureAttributes(), QgsVectorLayerCache::getFeatures(), QgsSearchQueryBuilder::getFieldValues(), QgsRelation::getRelatedFeatures(), QgsMapToolIdentify::identifyVectorLayer(), QgsVectorLayerImport::importLayer(), QgsAttributeDialog::init(), QgsOverlayAnalyzer::intersectFeature(), QgsOverlayAnalyzer::intersection(), invertSelectionInRectangle(), QgsAttributeTableModel::loadAttributes(), maximumValue(), minimumValue(), QgsExpressionSelectionDialog::on_mActionAddToSelection_triggered(), QgsExpressionSelectionDialog::on_mActionRemoveFromSelection_triggered(), QgsExpressionSelectionDialog::on_mActionSelect_triggered(), QgsExpressionSelectionDialog::on_mActionSelectInstersect_triggered(), QgsExpressionBuilderWidget::on_txtExpressionString_textChanged(), QgsAtlasComposition::prepareForFeature(), prepareLabelingAndDiagrams(), QgsCachedFeatureWriterIterator::QgsCachedFeatureWriterIterator(), removePolygonIntersections(), select(), selectedFeatures(), QgsAtlasComposition::setCoverageLayer(), QgsFormAnnotationItem::setFeatureForMapPosition(), QgsHtmlAnnotationItem::setFeatureForMapPosition(), QgsGeometryAnalyzer::simplify(), snapWithContext(), QgsVectorLayerEditUtils::splitFeatures(), QgsVectorLayerEditUtils::splitParts(), QgsVectorLayerEditUtils::translateFeature(), QgsVectorLayerUndoCommandChangeAttribute::undo(), uniqueValues(), updateFeature(), QgsAtlasComposition::updateFeatures(), QgsOfflineEditing::updateFidLookup(), and QgsVectorFileWriter::writeAsVectorFormat().
QString QgsVectorLayer::getStyleFromDatabase (QString styleId, QString & msgError) virtual
Will return the named style corresponding to style id provided.
Definition at line 4345 of file qgsvectorlayer.cpp.
References cast_to_fptr, QgsProviderRegistry::instance(), QgsMapLayer::mDataSource, mProviderKey, QgsProviderRegistry::providerLibrary(), and tr.
bool QgsVectorLayer::hasGeometryType () const
Returns true if this is a geometry layer and false in case of NoGeometry (table only) or UnknownGeometry.
Note
added in 1.7
Definition at line 1012 of file qgsvectorlayer.cpp.
References geometryType(), QGis::NoGeometry, and QGis::UnknownGeometry.
Referenced by QgsVectorLayerEditUtils::addPart(), QgsVectorLayerEditUtils::addRing(), QgsVectorLayerEditUtils::addTopologicalPoints(), QgsVectorLayerEditBuffer::changeGeometry(), QgsVectorLayerEditUtils::deleteVertex(), draw(), drawLabels(), drawRendererV2(), drawRendererV2Levels(), extent(), QgsVectorLayerCache::getFeatures(), QgsVectorLayerEditUtils::insertSegmentVerticesForSnap(), QgsVectorLayerEditUtils::insertVertex(), QgsVectorLayerEditUtils::moveVertex(), QgsVectorLayerFeatureIterator::prepareSimplification(), QgsVectorLayer(), readSld(), readSymbology(), removePolygonIntersections(), QgsVectorLayerCache::setCacheGeometry(), setCoordinateSystem(), setDisplayField(), setRendererV2(), simplifyDrawingCanbeApplied(), snapPoint(), QgsMapCanvasSnapper::snapToBackgroundLayers(), snapWithContext(), QgsVectorLayerEditUtils::splitFeatures(), QgsVectorLayerEditUtils::splitParts(), QgsVectorLayerEditUtils::translateFeature(), writeSld(), and writeSymbology().
bool QgsVectorLayer::hasLabelsEnabled (void) const
Label is on.
Definition at line 1570 of file qgsvectorlayer.cpp.
References mLabelOn.
Referenced by QgsOfflineEditing::copyVectorLayer(), readSymbology(), and writeSymbology().
int QgsVectorLayer::insertSegmentVerticesForSnap (const QList< QgsSnappingResult > & snapResults)
Inserts vertices to the snapped segments.
This is useful for topological editing if snap to segment is enabled.
Parameters
snapResults results collected from the snapping operation
Returns
0 in case of success
Definition at line 3018 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditUtils::insertSegmentVerticesForSnap().
bool QgsVectorLayer::insertVertex (double x, double y, QgsFeatureId atFeatureId, int beforeVertex)
Insert a new vertex before the given vertex number, in the given ring, item (first number is index 0), and feature Not meaningful for Point geometries.
Definition at line 1375 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditUtils::insertVertex(), mDataProvider, and mEditBuffer.
void QgsVectorLayer::invalidateSymbolCountedFlag () protected slot
Definition at line 4220 of file qgsvectorlayer.cpp.
References mSymbolFeatureCounted.
Referenced by startEditing().
void QgsVectorLayer::invertSelection ()
Select not selected features and deselect selected ones.
Definition at line 865 of file qgsvectorlayer.cpp.
References allFeatureIds(), mSelectedFeatureIds, and setSelectedFeatures().
void QgsVectorLayer::invertSelectionInRectangle (QgsRectangle & rect)
Invert selection of features found within the search rectangle (in layer's coordinates)
Parameters
rect The rectangle in which the selection of features will be inverted
See Also
invertSelection()
Definition at line 894 of file qgsvectorlayer.cpp.
References QgsFeatureRequest::ExactIntersect, getFeatures(), QgsFeature::id(), modifySelection(), mSelectedFeatureIds, QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, and QgsRectangle::normalize().
bool QgsVectorLayer::isEditable () const virtual
Returns true if the provider is in editing mode.
Reimplemented from QgsMapLayer.
Definition at line 3087 of file qgsvectorlayer.cpp.
References mDataProvider, and mEditBuffer.
Referenced by QgsAttributeDialog::accept(), QgsAttributeEditor::createWidgetFromDef(), deleteSelectedFeatures(), QgsAttributeDialog::init(), QgsMapCanvas::mouseReleaseEvent(), QgsRelationEditorWidget::referencingLayerEditingToggled(), QgsMapRenderer::render(), and QgsAttributeTableModel::setData().
bool QgsVectorLayer::isModified () const virtual
Returns true if the provider has been modified since the last commit.
Definition at line 3107 of file qgsvectorlayer.cpp.
References QgsVectorLayerEditBuffer::isModified(), and mEditBuffer.
Referenced by rollBack(), and QgsAttributeTableModel::setData().
bool QgsVectorLayer::isReadOnly () const virtual
Returns true if the provider is in read-only mode.
Note
added in 1.6
Definition at line 3092 of file qgsvectorlayer.cpp.
References mReadOnly.
Referenced by QgsRelationEditorWidget::createRelationEditor().
QgsLabel * QgsVectorLayer::label ()
Get the label object associated with this layer.
Definition at line 1555 of file qgsvectorlayer.cpp.
References mLabel.
const QgsLabel * QgsVectorLayer::label () const
Definition at line 1560 of file qgsvectorlayer.cpp.
References mLabel.
void QgsVectorLayer::labelingFontNotFound (QgsVectorLayer * layer, const QString & fontfamily) signal
Emitted when the font family defined for labeling layer is not found on system.
Note
added in 1.9
Referenced by prepareLabelingAndDiagrams().
bool QgsVectorLayer::labelOnTop (int idx)
label widget on top
Note
added in 1.9
Definition at line 3248 of file qgsvectorlayer.cpp.
References QgsFields::count(), mLabelOnTop, and pendingFields().
Referenced by QgsAttributeEditor::createWidgetFromDef(), QgsAttributeDialog::init(), and readSymbology().
void QgsVectorLayer::layerDeleted () signal
Referenced by ~QgsVectorLayer().
void QgsVectorLayer::layerModified () signal
This signal is emitted when modifications has been done on layer.
Referenced by addAttributeAlias(), and startEditing().
int QgsVectorLayer::layerTransparency () const
Read transparency for layer.
Definition at line 3594 of file qgsvectorlayer.cpp.
References mLayerTransparency.
Referenced by QgsComposerMap::containsAdvancedEffects(), QgsMapRenderer::render(), setLayerTransparency(), and writeSymbology().
void QgsVectorLayer::layerTransparencyChanged (int layerTransparency) signal
Signal emitted when setLayerTransparency() is called.
Referenced by setLayerTransparency().
int QgsVectorLayer::listStylesInDatabase (QStringList & ids, QStringList & names, QStringList & descriptions, QString & msgError) virtual
Lists all the style in db split into related to the layer and not related to.
Parameters
ids the list in which will be stored the style db ids
names the list in which will be stored the style names
descriptions the list in which will be stored the style descriptions
msgError
Returns
the number of styles related to current layer
Definition at line 4324 of file qgsvectorlayer.cpp.
References cast_to_fptr, QgsProviderRegistry::instance(), QgsMapLayer::mDataSource, mProviderKey, QgsProviderRegistry::providerLibrary(), and tr.
QString QgsVectorLayer::loadNamedStyle (const QString & theURI, bool & theResultFlag, bool loadFromLocalDb) virtual
Load a named style from file/local db/datasource db.
Parameters
theURI the URI of the style or the URI of the layer
theResultFlag will be set to true if a named style is correctly loaded
loadFromLocalDb if true forces to load from local db instead of datasource one
Definition at line 4414 of file qgsvectorlayer.cpp.
References applyNamedStyle(), cast_to_fptr, QgsDataSourceURI::database(), QgsProviderRegistry::instance(), QgsMapLayer::mDataSource, mProviderKey, QgsProviderRegistry::providerLibrary(), and tr.
Referenced by loadNamedStyle().
QString QgsVectorLayer::loadNamedStyle (const QString & theURI, bool & theResultFlag) virtual
Calls loadNamedStyle(theURI, theResultFlag, false); Retained for backward compatibility.
Reimplemented from QgsMapLayer.
Definition at line 4409 of file qgsvectorlayer.cpp.
References loadNamedStyle().
QVariant QgsVectorLayer::maximumValue (int index)
Returns maximum value for an attribute column or invalid variant in case of error.
Note
added in 1.7
Definition at line 3512 of file qgsvectorlayer.cpp.
References QgsFeature::attribute(), QgsFields::fieldOrigin(), getFeatures(), index, QgsMapLayerRegistry::instance(), QgsVectorLayerJoinBuffer::joinForFieldIndex(), QgsVectorJoinInfo::joinLayerId, QgsVectorLayerEditBuffer::mAddedFeatures, QgsMapLayerRegistry::mapLayer(), MathUtils::max(), QgsVectorDataProvider::maximumValue(), maximumValue(), QgsVectorLayerEditBuffer::mChangedAttributeValues, mDataProvider, QgsVectorLayerEditBuffer::mDeletedAttributeIds, QgsVectorLayerEditBuffer::mDeletedFeatureIds, mEditBuffer, mJoinBuffer, mUpdatedFields, QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, QgsFields::OriginEdit, QgsFields::OriginJoin, and QgsFields::OriginProvider.
Referenced by QgsGraduatedSymbolRendererV2::createRenderer(), and maximumValue().
QString QgsVectorLayer::metadata () virtual
Obtain Metadata for this layer.
Reimplemented from QgsMapLayer.
Definition at line 3960 of file qgsvectorlayer.cpp.
References capabilitiesString(), QgsField::comment(), QgsMapLayer::crs(), dataComment(), dataProvider(), QgsDataProvider::description(), extent(), featureCount(), geometryType(), QgsRectangle::isEmpty(), QgsField::length(), QgsField::name(), QGis::NoGeometry, pendingFields(), pendingPkAttributesList(), QgsField::precision(), QgsMapLayer::publicSource(), QgsDebugMsg, storageType(), QgsCoordinateReferenceSystem::toProj4(), tr, QgsMapLayer::type(), QgsField::typeName(), QGis::vectorGeometryType(), QgsException::what(), QgsRectangle::xMaximum(), QgsRectangle::xMinimum(), QgsRectangle::yMaximum(), and QgsRectangle::yMinimum().
QVariant QgsVectorLayer::minimumValue (int index)
Returns minimum value for an attribute column or invalid variant in case of error.
Note
added in 1.7
Definition at line 3454 of file qgsvectorlayer.cpp.
References QgsFeature::attribute(), QgsFields::fieldOrigin(), getFeatures(), index, QgsMapLayerRegistry::instance(), QgsVectorLayerJoinBuffer::joinForFieldIndex(), QgsVectorJoinInfo::joinLayerId, QgsVectorLayerEditBuffer::mAddedFeatures, QgsMapLayerRegistry::mapLayer(), MathUtils::max(), QgsVectorLayerEditBuffer::mChangedAttributeValues, mDataProvider, QgsVectorLayerEditBuffer::mDeletedAttributeIds, QgsVectorLayerEditBuffer::mDeletedFeatureIds, mEditBuffer, QgsVectorDataProvider::minimumValue(), minimumValue(), mJoinBuffer, mUpdatedFields, QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, QgsFields::OriginEdit, QgsFields::OriginJoin, and QgsFields::OriginProvider.
Referenced by QgsGraduatedSymbolRendererV2::createRenderer(), and minimumValue().
void QgsVectorLayer::modifySelection (QgsFeatureIds selectIds, QgsFeatureIds deselectIds)
Modifies the current selection on this layer.
Parameters
selectIds Select these ids
deselectIds Deselect these ids
See Also
select(QgsFeatureIds)
select(QgsFeatureId)
deselect(QgsFeatureIds)
deselect(QgsFeatureId)
Definition at line 849 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds, QgsDebugMsg, selectionChanged(), and QgsMapLayer::setCacheImage().
Referenced by invertSelectionInRectangle().
bool QgsVectorLayer::moveVertex (double x, double y, QgsFeatureId atFeatureId, int atVertex)
Moves the vertex at the given position number, ring and item (first number is index 0), and feature to the given coordinates.
Definition at line 1385 of file qgsvectorlayer.cpp.
References mDataProvider, mEditBuffer, and QgsVectorLayerEditUtils::moveVertex().
void QgsVectorLayer::onCacheImageDelete () virtual slot
Is called when the cache image is being deleted.
Overwrite and use to clean up.
Note
added in 2.0
Definition at line 4214 of file qgsvectorlayer.cpp.
References mCurrentRendererContext, and QgsRenderContext::setRenderingStopped().
void QgsVectorLayer::onRelationsLoaded () private slot
Definition at line 4225 of file qgsvectorlayer.cpp.
References QgsAttributeEditorElement::AeTypeContainer, QgsAttributeEditorElement::AeTypeRelation, QgsAttributeEditorContainer::findElements(), QgsAttributeEditorRelation::init(), QgsProject::instance(), mAttributeEditorElements, and QgsAttributeEditorElement::type().
Referenced by QgsVectorLayer().
QgsVectorLayer& QgsVectorLayer::operator= (QgsVectorLayer const & rhs) private
vector layers are not copyable
QgsAttributeList QgsVectorLayer::pendingAllAttributesList ()
returns list of attributes
Definition at line 2696 of file qgsvectorlayer.cpp.
References QgsFields::count(), and mUpdatedFields.
Referenced by QgsOfflineEditing::attributeLookup(), QgsVectorLayerCache::checkInformationCovered(), QgsVectorLayerImport::importLayer(), QgsVectorLayerFeatureIterator::prepareJoins(), QgsVectorLayerCache::QgsVectorLayerCache(), and QgsVectorFileWriter::writeAsVectorFormat().
int QgsVectorLayer::pendingFeatureCount ()
returns feature count after commit
Definition at line 2719 of file qgsvectorlayer.cpp.
References QgsVectorDataProvider::featureCount(), QgsVectorLayerEditBuffer::mAddedFeatures, mDataProvider, QgsVectorLayerEditBuffer::mDeletedFeatureIds, and mEditBuffer.
Referenced by countSymbolFeatures(), and QgsGeometryAnalyzer::eventLayer().
const QgsFields & QgsVectorLayer::pendingFields () const
returns field list in the to-be-committed state
Definition at line 2691 of file qgsvectorlayer.cpp.
References mUpdatedFields.
Referenced by QgsAttributeDialog::accept(), QgsVectorLayerEditBuffer::addAttribute(), addAttributeAlias(), QgsVectorLayerFeatureIterator::addJoinedAttributes(), QgsOfflineEditing::applyFeaturesAdded(), attributeAlias(), attributeDisplayName(), QgsGeometryAnalyzer::buffer(), QgsVectorLayerJoinBuffer::cacheJoinLayer(), QgsGeometryAnalyzer::centroids(), QgsVectorLayerEditBuffer::changeAttributeValue(), checkedState(), QgsDualView::columnBoxInit(), QgsVectorLayerEditBuffer::commitChanges(), QgsSearchQueryBuilder::countRecords(), QgsAttributeEditor::createAttributeEditor(), QgsFormAnnotationItem::createDesignerWidget(), QgsPointSample::createRandomPoints(), QgsGraduatedSymbolRendererV2::createRenderer(), QgsTransectSample::createSample(), QgsFeatureListModel::data(), QgsAttributeTableModel::data(), dateFormat(), QgsVectorLayerEditBuffer::deleteAttribute(), QgsGeometryAnalyzer::dissolve(), editType(), QgsAtlasComposition::evalFeatureFilename(), QgsGeometryAnalyzer::eventLayer(), QgsAttributeAction::expandAction(), fieldEditable(), fieldNameIndex(), QgsTransectSample::findBaselineGeometry(), QgsSearchQueryBuilder::getFieldValues(), QgsComposerAttributeTable::getHeaderLabels(), QgsRelation::getRelatedFeaturesRequest(), QgsAttributeTableModel::headerData(), QgsVectorLayerImport::importLayer(), QgsDataDefinedButton::init(), QgsAttributeDialog::init(), QgsComposerAttributeTable::initializeAliasMap(), QgsOverlayAnalyzer::intersection(), labelOnTop(), QgsAttributeTableModel::loadAttributes(), QgsExpressionBuilderWidget::loadFieldNames(), QgsRelationAddDlg::loadLayerAttributes(), metadata(), QgsQueryBuilder::on_lstFields_doubleClicked(), QgsExpressionSelectionDialog::on_mActionAddToSelection_triggered(), QgsExpressionSelectionDialog::on_mActionRemoveFromSelection_triggered(), QgsExpressionSelectionDialog::on_mActionSelect_triggered(), QgsExpressionSelectionDialog::on_mActionSelectInstersect_triggered(), QgsRelationEditorWidget::on_mAddFeatureButton_clicked(), QgsRelationEditorWidget::on_mUnlinkFeatureButton_clicked(), QgsExpressionBuilderWidget::on_txtExpressionString_textChanged(), QgsSearchQueryBuilder::populateFields(), QgsQueryBuilder::populateFields(), QgsAttributeTableModel::prefetchColumnData(), QgsDataDefined::prepareExpression(), QgsSymbolLayerV2::prepareExpressions(), QgsVectorLayerFeatureIterator::prepareJoins(), prepareLabelingAndDiagrams(), QgsPalLabeling::prepareLayer(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), QgsVectorLayerUndoCommandAddAttribute::QgsVectorLayerUndoCommandAddAttribute(), QgsVectorLayerUndoCommandDeleteAttribute::QgsVectorLayerUndoCommandDeleteAttribute(), range(), readSymbology(), QgsExpression::replaceExpressionText(), QgsAttributeEditor::retrieveValue(), setCheckedState(), setDisplayField(), setEditType(), setFieldEditable(), setLabelOnTop(), QgsAttributeEditor::setValue(), QgsGeometryAnalyzer::simplify(), QgsGraduatedSymbolRendererV2::startRender(), QgsCategorizedSymbolRendererV2::startRender(), QgsRuleBasedRendererV2::Rule::startRender(), QgsVectorLayerUndoCommandAddAttribute::undo(), QgsAtlasComposition::updateFeatures(), QgsVectorLayerJoinBuffer::updateFields(), QgsAtlasComposition::updateFilenameExpression(), valueMap(), valueRelation(), widgetSize(), and QgsVectorFileWriter::writeAsVectorFormat().
QgsAttributeList QgsVectorLayer::pendingPkAttributesList ()
returns list of attribute making up the primary key
Note
added in 2.0
Definition at line 2704 of file qgsvectorlayer.cpp.
References QgsFields::count(), QgsFields::fieldOrigin(), QgsFields::fieldOriginIndex(), mDataProvider, mUpdatedFields, QgsFields::OriginProvider, and QgsVectorDataProvider::pkAttributeIndexes().
Referenced by QgsDualView::columnBoxInit(), and metadata().
void QgsVectorLayer::prepareLabelingAndDiagrams (QgsRenderContext & rendererContext, QgsAttributeList & attributes, bool & labeling) private
Registers label and diagram layer.
Parameters
rendererContext render context
attributes attributes needed for labeling and diagrams will be added to the list
labeling out: true if there will be labeling (ng) for this layer
Definition at line 3609 of file qgsvectorlayer.cpp.
References QgsLabelingEngineInterface::addDiagramLayer(), QgsLinearlyInterpolatedDiagramRenderer::classificationAttribute(), QgsLinearlyInterpolatedDiagramRenderer::classificationAttributeExpression(), QgsLinearlyInterpolatedDiagramRenderer::classificationAttributeIsExpression(), QgsDiagramRendererV2::diagram(), QgsDiagramRendererV2::diagramAttributes(), QgsRenderContext::extent(), fieldNameIndex(), getFeatures(), index, QgsRenderContext::labelingEngine(), labelingFontNotFound(), QgsLabelingEngineInterface::layer(), QgsPalLayerSettings::limitNumLabels, QgsPalLayerSettings::maxNumLabels, mDiagramLayerSettings, mDiagramRenderer, QgsPalLayerSettings::mFeaturesToLabel, mLabelFontNotFoundNotified, QgsPalLayerSettings::mTextFontFamily, QgsPalLayerSettings::mTextFontFound, QgsFeatureIterator::nextFeature(), pendingFields(), QgsLabelingEngineInterface::prepareLayer(), QgsExpression::referencedColumns(), QgsDiagramLayerSettings::renderer, QgsDiagramLayerSettings::xPosColumn, and QgsDiagramLayerSettings::yPosColumn.
Referenced by draw().
QString QgsVectorLayer::providerType () const
Return the provider type for this layer.
Definition at line 247 of file qgsvectorlayer.cpp.
References mProviderKey.
Referenced by QgsVectorLayerEditBuffer::commitChanges(), QgsOfflineEditing::copyVectorLayer(), QgsQueryBuilder::fillValues(), QgsVectorLayerImport::importLayer(), QgsQueryBuilder::on_lstValues_doubleClicked(), QgsMapLayer::saveNamedStyle(), QgsMapLayer::saveSldStyle(), QgsVectorFileWriter::writeAsVectorFormat(), QgsMapLayer::writeLayerXML(), and writeXml().
QgsVectorLayer::RangeData & QgsVectorLayer::range (int idx)
access range
Definition at line 3192 of file qgsvectorlayer.cpp.
References QgsFields::count(), mRanges, pendingFields(), and QgsDebugMsg.
Referenced by QgsAttributeEditor::createAttributeEditor().
bool QgsVectorLayer::readSld (const QDomNode & node, QString & errorMessage) virtual
Reimplemented from QgsMapLayer.
Definition at line 2523 of file qgsvectorlayer.cpp.
References geometryType(), hasGeometryType(), QgsFeatureRendererV2::loadSld(), readSldLabeling(), and setRendererV2().
void QgsVectorLayer::readSldLabeling (const QDomNode & node) private
Read labeling from SLD.
Definition at line 3718 of file qgsvectorlayer.cpp.
References QgsPalLayerSettings::AroundPoint, QgsOgcUtils::colorFromOgcFill(), QgsExpression::evalErrorString(), fieldNameIndex(), QgsExpression::hasEvalError(), QgsPalLayerSettings::OverPoint, QgsDebugMsg, and QgsMapLayer::setCustomProperty().
Referenced by readSld().
bool QgsVectorLayer::readSymbology (const QDomNode & node, QString & errorMessage) virtual
Read the symbology for the current layer from the Dom node supplied.
Parameters
node node that will contain the symbology definition for this layer.
errorMessage reference to string that will be updated with any error messages
Returns
true in case of success.
Implements QgsMapLayer.
Definition at line 1844 of file qgsvectorlayer.cpp.
References attributeEditorElementFromDomElement(), Calendar, CheckBox, Classification, Color, QgsFeatureRendererV2::defaultRenderer(), DialRange, EditorWidgetV2, EditRange, editType(), enableLabels(), Enumeration, fieldNameIndex(), FileName, GeneratedLayout, geometryType(), QgsMapRenderer::getCompositionMode(), hasGeometryType(), hasLabelsEnabled(), Hidden, Immutable, index, QgsProject::instance(), labelOnTop(), LineEdit, QgsFeatureRendererV2::load(), mActions, mAnnotationForm, mAttributeAliasMap, mAttributeEditorElements, MathUtils::max(), mCheckedStates, mDateFormats, mDiagramLayerSettings, mDiagramRenderer, mEditForm, mEditFormInit, mEditorLayout, mEditTypes, mExcludeAttributesWFS, mExcludeAttributesWMS, mFeatureFormSuppress, mFieldEditables, MathUtils::min(), mLabel, mLabelOnTop, mRanges, mSimplifyMethod, mValueMaps, mValueRelations, mWidgetSize, QgsMapLayer::name(), pendingFields(), Photo, QgsDebugMsg, QgsMapLayer::readCustomProperties(), QgsSymbologyV2Conversion::readOldRenderer(), QgsProject::readPath(), QgsDiagramLayerSettings::readXML(), QgsLabel::readXML(), QgsAttributeAction::readXML(), QgsDiagramRendererV2::readXML(), RENDERER_TAG_NAME, QgsMapLayer::setBlendMode(), setDisplayField(), setFeatureBlendMode(), QgsVectorSimplifyMethod::setForceLocalOptimization(), setLayerTransparency(), QgsVectorSimplifyMethod::setMaximumScale(), QgsLabel::setMaxScale(), QgsLabel::setMinScale(), setRendererV2(), QgsLabel::setScaleBasedVisibility(), QgsVectorSimplifyMethod::setSimplifyHints(), QgsVectorSimplifyMethod::setThreshold(), SliderRange, SuppressDefault, TabLayout, TextEdit, UiFileLayout, UniqueValues, UniqueValuesEditable, UuidGenerator, ValueMap, ValueRelation, and WebView.
Referenced by applyNamedStyle(), QgsOfflineEditing::copySymbology(), and readXml().
bool QgsVectorLayer::readXml (const QDomNode & layer_node) virtual
reads vector layer specific state from project file Dom node.
Note
Called by QgsMapLayer::readXML().
Reimplemented from QgsMapLayer.
Definition at line 1620 of file qgsvectorlayer.cpp.
References checkJoinLayerRemove(), QgsMapLayerRegistry::instance(), mDataProvider, QgsMapLayer::mDataSource, mDisplayExpression, mJoinBuffer, mProviderKey, QgsMapLayer::mValid, QgsDebugMsg, readSymbology(), QgsVectorLayerJoinBuffer::readXml(), setDataProvider(), QgsVectorDataProvider::setEncoding(), and updateFields().
QList< QgsRelation > QgsVectorLayer::referencingRelations (int idx)
Get relations, where the foreign key is on this layer.
Parameters
idx Only get relations, where idx forms part of the foreign key
Returns
A list of relations
Definition at line 4263 of file qgsvectorlayer.cpp.
References QgsProject::instance(), QgsRelationManager::referencingRelations(), and QgsProject::relationManager().
void QgsVectorLayer::reload () virtual
Synchronises with changes in the datasource.
Note
added in version 1.6
Reimplemented from QgsMapLayer.
Definition at line 645 of file qgsvectorlayer.cpp.
References mDataProvider, and QgsDataProvider::reloadData().
Referenced by QgsOfflineEditing::synchronize().
void QgsVectorLayer::removeJoin (const QString & joinLayerId)
Removes a vector layer join.
Note
added in 1.7
Definition at line 3355 of file qgsvectorlayer.cpp.
References mJoinBuffer, QgsVectorLayerJoinBuffer::removeJoin(), and updateFields().
Referenced by checkJoinLayerRemove().
int QgsVectorLayer::removePolygonIntersections (QgsGeometry * geom, QgsFeatureIds ignoreFeatures = QgsFeatureIds())
Changes the specified geometry such that it has no intersections with other polygon (or multipolygon) geometries in this vector layer.
Parameters
geom geometry to modify
ignoreFeatures list of feature ids where intersections should be ignored
Returns
0 in case of success
Deprecated:
since 2.2 - not being used for "avoid intersections" functionality anymore
Definition at line 1493 of file qgsvectorlayer.cpp.
References QgsGeometry::boundingBox(), QgsFeatureRequest::ExactIntersect, QgsFeature::geometry(), getFeatures(), hasGeometryType(), QgsFeature::id(), QgsGeometry::makeDifference(), QgsFeatureIterator::nextFeature(), QGis::Polygon, and QgsGeometry::type().
void QgsVectorLayer::removeSelection () slot
Clear selection.
See Also
setSelectedFeatures(const QgsFeatureIds&)
Definition at line 923 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds, and setSelectedFeatures().
void QgsVectorLayer::rendererChanged () signal
Signal emitted on symbology changes, when setRendererV2() is called.
Referenced by setRendererV2().
QgsFeatureRendererV2 * QgsVectorLayer::rendererV2 ()
Return renderer V2.
Note
added in 1.4
Definition at line 3271 of file qgsvectorlayer.cpp.
References mRendererV2.
Referenced by QgsLegendModel::addVectorLayerItemsV2(), QgsAttributeEditor::createAttributeEditor(), QgsVectorFileWriter::createSymbolLayerTable(), QgsVectorFileWriter::exportFeaturesSymbolLevels(), QgsAttributeTableFilterModel::generateListOfVisibleFeatures(), QgsMapToolIdentify::identifyVectorLayer(), QgsHighlight::setColor(), QgsComposerLayerItem::setDefaultStyle(), QgsVectorFileWriter::symbologyRenderer(), QgsLegendModel::updateSymbolV2ItemText(), and QgsVectorFileWriter::writeAsVectorFormat().
bool QgsVectorLayer::rollBack (bool deleteBuffer = true)
Stop editing and discard the edits.
Parameters
deleteBuffer whether to delete editing buffer (added in 1.9)
Definition at line 2776 of file qgsvectorlayer.cpp.
References beforeRollBack(), QgsGeometryCache::deleteCachedGeometries(), editingStopped(), isModified(), mCache, mEditBuffer, QgsVectorLayerEditBuffer::rollBack(), QgsMapLayer::setCacheImage(), QgsMapLayer::undoStack(), and updateFields().
void QgsVectorLayer::saveLayerToProject () signal
void QgsVectorLayer::saveStyleToDatabase (QString name, QString description, bool useAsDefault, QString uiFileContent, QString & msgError) virtual
Save named and sld style of the layer to the style table in the db.
Parameters
name
description
useAsDefault
uiFileContent
msgError
Definition at line 4367 of file qgsvectorlayer.cpp.
References cast_to_fptr, QgsMapLayer::exportNamedStyle(), QgsMapLayer::exportSldStyle(), QgsProviderRegistry::instance(), QgsMapLayer::mDataSource, mProviderKey, QgsProviderRegistry::providerLibrary(), and tr.
void QgsVectorLayer::select (QgsRectangle & rect, bool addToSelection)
Select features found within the search rectangle (in layer's coordinates)
Parameters
rect The search rectangle
addToSelection If set to true will not clear before selecting
See Also
invertSelectionInRectangle(QgsRectangle & rect)
Definition at line 820 of file qgsvectorlayer.cpp.
References QgsFeatureRequest::ExactIntersect, getFeatures(), QgsFeature::id(), mSelectedFeatureIds, QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, QgsRectangle::normalize(), and setSelectedFeatures().
Referenced by QgsVectorLayerSelectionManager::select().
void QgsVectorLayer::select (const QgsFeatureId & featureId) slot
Select feature by its ID.
Parameters
featureId The id of the feature to select
See Also
select(QgsFeatureIds)
Definition at line 788 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds, selectionChanged(), and QgsMapLayer::setCacheImage().
void QgsVectorLayer::select (const QgsFeatureIds & featureIds) slot
Select features by their ID.
Parameters
featureIds The ids of the features to select
See Also
select(QgsFeatureId)
Definition at line 796 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds, selectionChanged(), and QgsMapLayer::setCacheImage().
void QgsVectorLayer::selectAll ()
Select all the features.
Definition at line 872 of file qgsvectorlayer.cpp.
References allFeatureIds(), and setSelectedFeatures().
int QgsVectorLayer::selectedFeatureCount ()
The number of features that are selected in this layer.
Returns
See description
Definition at line 2827 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds.
Referenced by QgsMapCanvas::panToSelected(), QgsVectorLayerSelectionManager::selectedFeatureCount(), and QgsMapCanvas::zoomToSelected().
QgsFeatureList QgsVectorLayer::selectedFeatures ()
Get a copy of the user-selected features.
Returns
A list of QgsFeature 's
See Also
selectedFeaturesIds()
Definition at line 2838 of file qgsvectorlayer.cpp.
References geometryType(), getFeatures(), mSelectedFeatureIds, QgsFeatureRequest::NoGeometry, QGis::NoGeometry, QgsFeatureRequest::setFilterFid(), and QgsFeatureRequest::setFlags().
Referenced by QgsVectorLayerEditUtils::splitFeatures(), and QgsVectorLayerEditUtils::splitParts().
const QgsFeatureIds & QgsVectorLayer::selectedFeaturesIds () const
Return reference to identifiers of selected features.
Returns
A list of QgsFeatureId 's
See Also
selectedFeatures()
Definition at line 2832 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds.
Referenced by QgsGeometryAnalyzer::buffer(), QgsGeometryAnalyzer::centroids(), QgsGeometryAnalyzer::convexHull(), QgsGeometryAnalyzer::dissolve(), QgsAttributeTableFilterModel::filterAcceptsRow(), QgsVectorLayerImport::importLayer(), QgsOverlayAnalyzer::intersection(), QgsAttributeTableFilterModel::lessThan(), QgsExpressionSelectionDialog::on_mActionAddToSelection_triggered(), QgsExpressionSelectionDialog::on_mActionRemoveFromSelection_triggered(), QgsExpressionSelectionDialog::on_mActionSelectInstersect_triggered(), QgsVectorLayerSelectionManager::selectedFeaturesIds(), QgsGeometryAnalyzer::simplify(), QgsVectorLayerEditUtils::splitFeatures(), QgsVectorLayerEditUtils::splitParts(), and QgsVectorFileWriter::writeAsVectorFormat().
void QgsVectorLayer::selectionChanged (const QgsFeatureIds selected, const QgsFeatureIds deselected, const bool clearAndSelect) signal
This signal is emitted when selection was changed.
Parameters
selected Newly selected feature ids
deselected Ids of all features which have previously been selected but are not any more
clearAndSelect In case this is set to true, the old selection was dismissed and the new selection corresponds to selected
void QgsVectorLayer::selectionChanged () signal
This signal is emitted when selection was changed.
Referenced by deselect(), modifySelection(), QgsVectorLayer(), select(), and setSelectedFeatures().
void QgsVectorLayer::setAnnotationForm (const QString & ui)
set annotation form for layer (added in 1.5)
Definition at line 3158 of file qgsvectorlayer.cpp.
References mAnnotationForm.
void QgsVectorLayer::setCheckedState (int idx, QString checked, QString notChecked)
set string representing 'true' for a checkbox (added in 1.4)
Definition at line 3314 of file qgsvectorlayer.cpp.
References QgsFields::count(), mCheckedStates, QgsMapLayer::name(), and pendingFields().
void QgsVectorLayer::setCoordinateSystem ()
Setup the coordinate system tranformation for the layer.
Definition at line 3051 of file qgsvectorlayer.cpp.
References QgsDataProvider::crs(), GEO_EPSG_CRS_AUTHID, hasGeometryType(), mDataProvider, QgsDebugMsg, and QgsMapLayer::setCrs().
Referenced by QgsVectorLayer().
bool QgsVectorLayer::setDataProvider (QString const & provider) private
bind layer to a specific data provider
Parameters
provider should be "postgres", "ogr", or ??
Todo:
XXX should this return bool? Throw exceptions?
Definition at line 1700 of file qgsvectorlayer.cpp.
References QgsDataProvider::dataSourceUri(), QgsVectorDataProvider::fields(), QgsVectorDataProvider::geometryType(), QgsMapLayerRegistry::instance(), QgsProviderRegistry::instance(), QgsDataProvider::isValid(), QgsMapLayerRegistry::mapLayers(), mDataProvider, QgsMapLayer::mDataSource, mJoinBuffer, mLabel, mLabelOn, mProviderKey, QgsMapLayer::mValid, mWkbType, QgsMapLayer::name(), QgsProviderRegistry::provider(), QgsDebugMsg, setDisplayField(), QgsMapLayer::setLayerName(), updateExtents(), and updateFields().
Referenced by QgsVectorLayer(), and readXml().
void QgsVectorLayer::setDiagramLayerSettings (const QgsDiagramLayerSettings & s)
Definition at line 3953 of file qgsvectorlayer.cpp.
References mDiagramLayerSettings.
void QgsVectorLayer::setDiagramRenderer (QgsDiagramRendererV2 * r)
Sets diagram rendering object (takes ownership)
Definition at line 955 of file qgsvectorlayer.cpp.
References mDiagramRenderer.
void QgsVectorLayer::setDisplayExpression (const QString & displayExpression)
Set the preview expression, used to create a human readable preview string.
Used e.g. in the attribute table feature list. Uses QgsExpression.
Parameters
displayExpression The expression which will be used to preview features for this layer
Note
added in 2.0
Definition at line 3077 of file qgsvectorlayer.cpp.
References displayExpression(), and mDisplayExpression.
Referenced by QgsDualView::previewExpressionChanged().
void QgsVectorLayer::setDisplayField (QString fldName = "")
Set the primary display field to be used in the identify results dialog.
sets the preferred display field based on some fuzzy logic
Definition at line 255 of file qgsvectorlayer.cpp.
References QgsFields::count(), hasGeometryType(), mDisplayField, pendingFields(), QgsDebugMsg, and QgsFields::size().
Referenced by readSymbology(), and setDataProvider().
void QgsVectorLayer::setEditForm (QString ui)
set edit form (added in 1.4)
Definition at line 3153 of file qgsvectorlayer.cpp.
References mEditForm.
void QgsVectorLayer::setEditFormInit (QString function)
set python function for edit form initialization (added in 1.4)
Definition at line 3168 of file qgsvectorlayer.cpp.
References mEditFormInit.
void QgsVectorLayer::setEditorLayout (EditorLayout editorLayout)
set the active layout for the attribute editor for this layer (added in 1.9)
Definition at line 3133 of file qgsvectorlayer.cpp.
References editorLayout(), and mEditorLayout.
void QgsVectorLayer::setEditorWidgetV2 (int attrIdx, const QString & widgetType)
Definition at line 3138 of file qgsvectorlayer.cpp.
References mEditorWidgetV2Types.
void QgsVectorLayer::setEditorWidgetV2Config (int attrIdx, const QMap< QString, QVariant > & config)
Definition at line 3143 of file qgsvectorlayer.cpp.
References mEditorWidgetV2Configs.
void QgsVectorLayer::setEditType (int idx, EditType edit)
set edit type
Definition at line 3121 of file qgsvectorlayer.cpp.
References QgsFields::count(), mEditTypes, QgsMapLayer::name(), pendingFields(), and QgsMapLayer::type().
void QgsVectorLayer::setExcludeAttributesWFS (const QSet< QString > & att) inline
Definition at line 1157 of file qgsvectorlayer.h.
void QgsVectorLayer::setExcludeAttributesWMS (const QSet< QString > & att) inline
Definition at line 1154 of file qgsvectorlayer.h.
void QgsVectorLayer::setExtent (const QgsRectangle & rect) protected virtual
Set the extent.
Reimplemented from QgsMapLayer.
Definition at line 1175 of file qgsvectorlayer.cpp.
References mValidExtent.
Referenced by extent().
void QgsVectorLayer::setFeatureBlendMode (const QPainter::CompositionMode & blendMode)
Write blend mode for features.
Definition at line 3574 of file qgsvectorlayer.cpp.
References featureBlendMode(), featureBlendModeChanged(), and mFeatureBlendMode.
Referenced by readSymbology().
void QgsVectorLayer::setFeatureFormSuppress (QgsVectorLayer::FeatureFormSuppress s) inline
Set type of feature form pop-up suppression after feature creation (overrides app setting)
Note
added in 2.1
Definition at line 1237 of file qgsvectorlayer.h.
void QgsVectorLayer::setFieldEditable (int idx, bool editable)
set edit widget editable
Note
added in 1.9
Definition at line 3257 of file qgsvectorlayer.cpp.
References QgsFields::count(), mFieldEditables, QgsMapLayer::name(), and pendingFields().
void QgsVectorLayer::setLabelOnTop (int idx, bool onTop)
label widget on top
Note
added in 1.9
Definition at line 3264 of file qgsvectorlayer.cpp.
References QgsFields::count(), mLabelOnTop, QgsMapLayer::name(), and pendingFields().
void QgsVectorLayer::setLayerTransparency (int layerTransparency)
Write transparency for layer.
Definition at line 3587 of file qgsvectorlayer.cpp.
References layerTransparency(), layerTransparencyChanged(), and mLayerTransparency.
Referenced by readSymbology().
void QgsVectorLayer::setProviderEncoding (const QString & encoding)
Sets the textencoding of the data provider.
Definition at line 946 of file qgsvectorlayer.cpp.
References mDataProvider, QgsVectorDataProvider::setEncoding(), and updateFields().
bool QgsVectorLayer::setReadOnly (bool readonly = true)
Make layer read-only (editing disabled) or not.
Returns
false if the layer is in editing yet
Note
added in 1.6
Definition at line 3097 of file qgsvectorlayer.cpp.
References mEditBuffer, and mReadOnly.
void QgsVectorLayer::setRendererV2 (QgsFeatureRendererV2 * r)
Set renderer V2.
Note
added in 1.4
Definition at line 3276 of file qgsvectorlayer.cpp.
References hasGeometryType(), mRendererV2, mSymbolFeatureCounted, mSymbolFeatureCountMap, and rendererChanged().
Referenced by QgsVectorLayer(), readSld(), and readSymbology().
void QgsVectorLayer::setSelectedFeatures (const QgsFeatureIds & ids)
Change selection to the new set of features.
Dismisses the current selection. Will emit the selectionChanged(QgsFeatureIds, QgsFeatureIds, bool) signal with the clearAndSelect flag set.
Parameters
ids The ids which will be the new selection
Definition at line 2815 of file qgsvectorlayer.cpp.
References mSelectedFeatureIds, selectionChanged(), and QgsMapLayer::setCacheImage().
Referenced by addFeatures(), invertSelection(), QgsExpressionSelectionDialog::on_mActionAddToSelection_triggered(), QgsExpressionSelectionDialog::on_mActionRemoveFromSelection_triggered(), QgsExpressionSelectionDialog::on_mActionSelect_triggered(), QgsExpressionSelectionDialog::on_mActionSelectInstersect_triggered(), removeSelection(), select(), selectAll(), and QgsVectorLayerSelectionManager::setSelectedFeatures().
void QgsVectorLayer::setSimplifyMethod (const QgsVectorSimplifyMethod & simplifyMethod) inline
Set the simplification settings for fast rendering of features.
Note
added in 2.2
Definition at line 1382 of file qgsvectorlayer.h.
bool QgsVectorLayer::setSubsetString (QString subset) virtual
Set the string (typically sql) used to define a subset of the layer.
Parameters
subset The subset string. This may be the where clause of a sql statement or other defintion string specific to the underlying dataprovider and data store.
Returns
true, when setting the subset string was successful, false otherwise (added in 1.4)
Definition at line 1273 of file qgsvectorlayer.cpp.
References QgsDataProvider::dataSourceUri(), mDataProvider, QgsMapLayer::mDataSource, QgsDebugMsg, QgsMapLayer::setCacheImage(), QgsDataProvider::setSubsetString(), and updateExtents().
Referenced by QgsQueryBuilder::accept(), QgsQueryBuilder::clear(), QgsOfflineEditing::copyVectorLayer(), QgsQueryBuilder::on_btnGetAllValues_clicked(), QgsQueryBuilder::on_btnSampleValues_clicked(), QgsQueryBuilder::reject(), and QgsQueryBuilder::test().
bool QgsVectorLayer::simplifyDrawingCanbeApplied (const QgsRenderContext & renderContext, QgsVectorSimplifyMethod::SimplifyHint simplifyHint) const
Returns whether the VectorLayer can apply the specified simplification hint.
Note
Do not use in 3rd party code - may be removed in future version!
added in 2.2
Definition at line 1293 of file qgsvectorlayer.cpp.
References geometryType(), hasGeometryType(), QgsVectorSimplifyMethod::maximumScale(), mDataProvider, mEditBuffer, mSimplifyMethod, QGis::Point, QgsRenderContext::rendererScale(), QgsVectorSimplifyMethod::simplifyHints(), and QgsRenderContext::useRenderingOptimization().
Referenced by QgsFillSymbolLayerV2::_renderPolygon(), draw(), and QgsSimpleLineSymbolLayerV2::renderPolyline().
const QgsVectorSimplifyMethod& QgsVectorLayer::simplifyMethod () const inline
Returns the simplification settings for fast rendering of features.
Note
added in 2.2
Definition at line 1386 of file qgsvectorlayer.h.
Referenced by QgsFillSymbolLayerV2::_renderPolygon(), draw(), and QgsSimpleLineSymbolLayerV2::renderPolyline().
bool QgsVectorLayer::snapPoint (QgsPoint & point, double tolerance)
Snaps a point to the closest vertex if there is one within the snapping tolerance.
Parameters
point The point which is set to the position of a vertex if there is one within the snapping tolerance. If there is no point within this tolerance, point is left unchanged.
tolerance The snapping tolerance
Returns
true if the point has been snapped, false if no vertex within search tolerance
Definition at line 2878 of file qgsvectorlayer.cpp.
References hasGeometryType(), QgsPoint::setX(), QgsPoint::setY(), QgsSnapper::SnapToVertex, and snapWithContext().
void QgsVectorLayer::snapToGeometry (const QgsPoint & startPoint, QgsFeatureId featureId, QgsGeometry * geom, double sqrSnappingTolerance, QMultiMap< double, QgsSnappingResult > & snappingResults, QgsSnapper::SnappingType snap_to) const private
Snaps to a geometry and adds the result to the multimap if it is within the snapping result.
Parameters
startPoint start point of the snap
featureId id of feature
geom geometry to snap
sqrSnappingTolerance squared search tolerance of the snap
snappingResults list to which the result is appended
snap_to snap to vertex or to segment
Definition at line 2955 of file qgsvectorlayer.cpp.
References QgsSnappingResult::afterVertex, QgsSnappingResult::afterVertexNr, QgsSnappingResult::beforeVertex, QgsSnappingResult::beforeVertexNr, QgsGeometry::closestSegmentWithContext(), QgsGeometry::closestVertex(), QgsMapLayer::crs(), geometryType(), QgsSnappingResult::layer, QGis::Point, QgsSnappingResult::snappedAtGeometry, QgsSnappingResult::snappedVertex, QgsSnappingResult::snappedVertexNr, QgsSnapper::SnapToSegment, QgsSnapper::SnapToVertex, QgsSnapper::SnapToVertexAndSegment, and QgsGeometry::vertexAt().
Referenced by snapWithContext().
int QgsVectorLayer::snapWithContext (const QgsPoint & startPoint, double snappingTolerance, QMultiMap< double, QgsSnappingResult > & snappingResults, QgsSnapper::SnappingType snap_to)
Snaps to segment or vertex within given tolerance.
Parameters
startPoint point to snap (in layer coordinates)
snappingTolerance distance tolerance for snapping
snappingResults snapping results. Key is the distance between startPoint and snapping target
snap_to to segment / to vertex
Returns
0 in case of success
Definition at line 2903 of file qgsvectorlayer.cpp.
References QgsGeometry::boundingBox(), QgsGeometryCache::cachedGeometries(), QgsGeometryCache::cachedGeometriesRect(), QgsRectangle::contains(), QgsFeatureRequest::ExactIntersect, QgsFeature::geometry(), getFeatures(), hasGeometryType(), QgsFeature::id(), QgsRectangle::intersects(), mCache, mDataProvider, QgsFeatureIterator::nextFeature(), snapToGeometry(), QgsPoint::x(), and QgsPoint::y().
Referenced by QgsVectorLayerEditUtils::addTopologicalPoints(), and snapPoint().
int QgsVectorLayer::splitFeatures (const QList< QgsPoint > & splitLine, bool topologicalEditing = false)
Splits features cut by the given line.
Parameters
splitLine line that splits the layer features
topologicalEditing true if topological editing is enabled
Returns
0 in case of success, 4 if there is a selection but no feature split
Definition at line 1484 of file qgsvectorlayer.cpp.
References mDataProvider, mEditBuffer, and QgsVectorLayerEditUtils::splitFeatures().
int QgsVectorLayer::splitParts (const QList< QgsPoint > & splitLine, bool topologicalEditing = false)
Splits parts cut by the given line.
Parameters
splitLine line that splits the layer features
topologicalEditing true if topological editing is enabled
Returns
0 in case of success, 4 if there is a selection but no feature split
Definition at line 1475 of file qgsvectorlayer.cpp.
References mDataProvider, mEditBuffer, and QgsVectorLayerEditUtils::splitParts().
bool QgsVectorLayer::startEditing ()
Make layer editable.
Definition at line 1575 of file qgsvectorlayer.cpp.
References attributeAdded(), attributeDeleted(), attributeValueChanged(), QgsVectorDataProvider::capabilities(), committedFeaturesAdded(), committedFeaturesRemoved(), QgsVectorDataProvider::EditingCapabilities, editingStarted(), featureAdded(), featureDeleted(), geometryChanged(), invalidateSymbolCountedFlag(), layerModified(), mDataProvider, mEditBuffer, mReadOnly, QgsVectorLayerEditBuffer, and updateFields().
Referenced by QgsOfflineEditing::copyVectorLayer(), and QgsOfflineEditing::synchronize().
void QgsVectorLayer::stopRendererV2 (QgsRenderContext & rendererContext, QgsSingleSymbolRendererV2 * selRenderer) private
Add joined attributes to a feature.
Stop version 2 renderer and selected renderer (if required)
Definition at line 3599 of file qgsvectorlayer.cpp.
References mRendererV2, QgsSingleSymbolRendererV2::stopRender(), and QgsFeatureRendererV2::stopRender().
Referenced by drawRendererV2(), and drawRendererV2Levels().
QString QgsVectorLayer::storageType () const
Returns the permanent storage type for this layer as a friendly name.
Definition at line 218 of file qgsvectorlayer.cpp.
References mDataProvider, and QgsVectorDataProvider::storageType().
Referenced by QgsVectorLayerEditBuffer::commitChanges(), QgsQueryBuilder::fillValues(), QgsVectorLayerImport::importLayer(), metadata(), and QgsQueryBuilder::on_lstValues_doubleClicked().
QString QgsVectorLayer::subsetString () virtual
Get the string (typically sql) used to define a subset of the layer.
Returns
The subset string or QString::null if not implemented by the provider
Definition at line 1263 of file qgsvectorlayer.cpp.
References mDataProvider, QgsDebugMsg, and QgsDataProvider::subsetString().
Referenced by QgsQueryBuilder::on_btnGetAllValues_clicked(), QgsQueryBuilder::on_btnSampleValues_clicked(), QgsQueryBuilder::QgsQueryBuilder(), QgsQueryBuilder::reject(), and QgsQueryBuilder::test().
int QgsVectorLayer::translateFeature (QgsFeatureId featureId, double dx, double dy)
Translates feature by dx, dy.
Parameters
featureId id of the feature to translate
dx translation of x-coordinate
dy translation of y-coordinate
Returns
0 in case of success
Definition at line 1466 of file qgsvectorlayer.cpp.
References mDataProvider, mEditBuffer, and QgsVectorLayerEditUtils::translateFeature().
void QgsVectorLayer::triggerRepaint () slot
Definition at line 931 of file qgsvectorlayer.cpp.
References QgsMapLayer::repaintRequested().
Referenced by deleteSelectedFeatures().
void QgsVectorLayer::uniqueValues (int index, QList< QVariant > & uniqueValues, int limit = -1)
Returns unique values for column.
Parameters
index column index for attribute
uniqueValues out: result list
limit maximum number of values to return (-1 if unlimited)
Note
this method was added in version 1.7
Definition at line 3393 of file qgsvectorlayer.cpp.
References QgsFeature::attribute(), dataProvider(), QgsFields::fieldOrigin(), getFeatures(), index, QgsMapLayerRegistry::instance(), QgsVectorLayerJoinBuffer::joinForFieldIndex(), QgsVectorJoinInfo::joinLayerId, QgsVectorLayerEditBuffer::mAddedFeatures, QgsMapLayerRegistry::mapLayer(), QgsVectorLayerEditBuffer::mChangedAttributeValues, mDataProvider, QgsVectorLayerEditBuffer::mDeletedAttributeIds, QgsVectorLayerEditBuffer::mDeletedFeatureIds, mEditBuffer, mJoinBuffer, mUpdatedFields, QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, QgsFields::OriginEdit, QgsFields::OriginJoin, QgsFields::OriginProvider, and QgsVectorDataProvider::uniqueValues().
Referenced by QgsExpressionBuilderWidget::fillFieldValues(), and QgsQueryBuilder::fillValues().
void QgsVectorLayer::updatedFields () signal
Is emitted, whenever the fields available from this layer have been changed.
This can be due to manually adding attributes or due to a join.
Note
Added in 2.0
Referenced by updateFields().
void QgsVectorLayer::updateExtents () virtual slot
Update the extents for the layer.
This is necessary if features are added/deleted or the layer has been subsetted.
Definition at line 1170 of file qgsvectorlayer.cpp.
References mValidExtent.
Referenced by addFeature(), QgsVectorLayerEditBuffer::addFeatures(), addFeatures(), changeGeometry(), deleteFeature(), deleteSelectedFeatures(), setDataProvider(), and setSubsetString().
bool QgsVectorLayer::updateFeature (QgsFeature & f)
Updates an existing feature.
This method needs to query the datasource on every call. Consider using changeAttributeValue() or changeGeometry() instead.
Parameters
f Feature to update
Returns
True in case of success and False in case of error
Note
Added in 1.8
Definition at line 1331 of file qgsvectorlayer.cpp.
References QgsFeature::attributes(), changeAttributeValue(), changeGeometry(), QgsFeature::geometry(), getFeatures(), QgsFeature::id(), QgsGeometry::isGeosEqual(), QgsFeatureRequest::NoGeometry, QgsDebugMsg, QgsFeatureRequest::setFilterFid(), QgsFeatureRequest::setFlags(), and QgsFeatureRequest::setSubsetOfAttributes().
void QgsVectorLayer::updateFields ()
Assembles mUpdatedFields considering provider fields, joined fields and added fields.
Note
added in 1.7
Definition at line 3366 of file qgsvectorlayer.cpp.
References QgsVectorLayerJoinBuffer::containsJoins(), QgsVectorDataProvider::fields(), mDataProvider, mEditBuffer, mJoinBuffer, mUpdatedFields, updatedFields(), QgsVectorLayerJoinBuffer::updateFields(), and QgsVectorLayerEditBuffer::updateFields().
Referenced by addJoin(), QgsZonalStatistics::calculateStatistics(), QgsVectorLayerEditBuffer::commitChanges(), commitChanges(), readXml(), removeJoin(), rollBack(), setDataProvider(), setProviderEncoding(), startEditing(), and QgsVectorLayerEditBuffer::updateLayerFields().
QMap< QString, QVariant > & QgsVectorLayer::valueMap (int idx)
access value map
Definition at line 3173 of file qgsvectorlayer.cpp.
References QgsFields::count(), mValueMaps, pendingFields(), and QgsDebugMsg.
Referenced by QgsAttributeEditor::createAttributeEditor().
QgsVectorLayer::ValueRelationData & QgsVectorLayer::valueRelation (int idx)
access relations
Note
added in 1.8
Definition at line 4242 of file qgsvectorlayer.cpp.
References QgsFields::count(), mValueRelations, pendingFields(), and QgsDebugMsg.
Referenced by QgsAttributeEditor::createAttributeEditor(), and QgsAttributeTableModel::loadAttributes().
const QList< QgsVectorJoinInfo > & QgsVectorLayer::vectorJoins () const
Note
added in 1.7
Definition at line 3361 of file qgsvectorlayer.cpp.
References mJoinBuffer, and QgsVectorLayerJoinBuffer::vectorJoins().
Referenced by QgsProject::addLayer().
QSize & QgsVectorLayer::widgetSize (int idx)
access widget size for photo and webview widget
Note
added in 1.9
Definition at line 3223 of file qgsvectorlayer.cpp.
References mWidgetSize, and pendingFields().
Referenced by QgsAttributeEditor::createAttributeEditor(), and QgsAttributeEditor::loadPixmap().
QGis::WkbType QgsVectorLayer::wkbType () const
Returns the WKBType or WKBUnknown in case of error.
Definition at line 1018 of file qgsvectorlayer.cpp.
References mWkbType.
Referenced by QgsOfflineEditing::copyVectorLayer(), QgsPointDisplacementRenderer::createDisplacementGroups(), QgsVectorLayerImport::importLayer(), and QgsVectorFileWriter::writeAsVectorFormat().
bool QgsVectorLayer::writeSld (QDomNode & node, QDomDocument & doc, QString & errorMessage) const
Definition at line 2547 of file qgsvectorlayer.cpp.
References hasGeometryType(), mRendererV2, QgsMapLayer::name(), and QgsFeatureRendererV2::writeSld().
Referenced by QgsMapLayer::exportSldStyle().
bool QgsVectorLayer::writeSymbology (QDomNode & node, QDomDocument & doc, QString & errorMessage) const virtual
Write the symbology for the layer into the docment provided.
Parameters
node the node that will have the style element added to it.
doc the document that will have the QDomNode added.
errorMessage reference to string that will be updated with any error messages
Returns
true in case of success.
Implements QgsMapLayer.
Definition at line 2233 of file qgsvectorlayer.cpp.
References QgsMapLayer::blendMode(), Calendar, CheckBox, Classification, Color, DialRange, displayField(), EditorWidgetV2, EditRange, Enumeration, featureBlendMode(), featureFormSuppress(), fieldNameIndex(), FileName, QgsVectorSimplifyMethod::forceLocalOptimization(), GeneratedLayout, QgsMapRenderer::getBlendModeEnum(), hasGeometryType(), hasLabelsEnabled(), Hidden, Immutable, QgsProject::instance(), QgsLabel::labelField(), layerTransparency(), LineEdit, mActions, QgsVectorLayer::ValueRelationData::mAllowMulti, QgsVectorLayer::ValueRelationData::mAllowNull, mAnnotationForm, mAttributeAliasMap, mAttributeEditorElements, QgsVectorSimplifyMethod::maximumScale(), QgsLabel::maxScale(), mCheckedStates, mDateFormats, mDiagramLayerSettings, mDiagramRenderer, mEditForm, mEditFormInit, mEditorLayout, mEditTypes, mExcludeAttributesWFS, mExcludeAttributesWMS, mFieldEditables, QgsVectorLayer::ValueRelationData::mFilterExpression, QgsLabel::minScale(), QgsVectorLayer::ValueRelationData::mKey, mLabel, mLabelOnTop, QgsVectorLayer::ValueRelationData::mLayer, QgsVectorLayer::ValueRelationData::mOrderByValue, mRanges, mRendererV2, mSimplifyMethod, QgsVectorLayer::ValueRelationData::mValue, mValueMaps, mValueRelations, mWidgetSize, Photo, QgsFeatureRendererV2::save(), QgsLabel::scaleBasedVisibility(), QgsVectorSimplifyMethod::simplifyHints(), SliderRange, TabLayout, QgsLabel::Text, TextEdit, QgsVectorSimplifyMethod::threshold(), UiFileLayout, UniqueValues, UniqueValuesEditable, UuidGenerator, ValueMap, ValueRelation, WebView, QgsMapLayer::writeCustomProperties(), QgsDiagramLayerSettings::writeXML(), QgsLabel::writeXML(), QgsAttributeAction::writeXML(), and QgsDiagramRendererV2::writeXML().
Referenced by QgsOfflineEditing::copySymbology(), and writeXml().
bool QgsVectorLayer::writeXml (QDomNode & layer_node, QDomDocument & doc) virtual
write vector layer specific state to project file Dom node.
Note
Called by QgsMapLayer::writeXML().
Reimplemented from QgsMapLayer.
Definition at line 1802 of file qgsvectorlayer.cpp.
References QgsVectorDataProvider::encoding(), geometryType(), mDataProvider, mDisplayExpression, mJoinBuffer, providerType(), QgsDebugMsg, QGis::vectorGeometryType(), writeSymbology(), and QgsVectorLayerJoinBuffer::writeXml().
Friends And Related Function Documentation
friend class QgsVectorLayerEditBuffer friend
Definition at line 1746 of file qgsvectorlayer.h.
Referenced by startEditing().
friend class QgsVectorLayerFeatureIterator friend
Definition at line 1768 of file qgsvectorlayer.h.
Referenced by getFeatures().
Member Data Documentation
QgsAttributeAction* QgsVectorLayer::mActions private
The user-defined actions that are accessed from the Identify Results dialog box.
Definition at line 1653 of file qgsvectorlayer.h.
Referenced by QgsVectorLayer(), readSymbology(), writeSymbology(), and ~QgsVectorLayer().
QString QgsVectorLayer::mAnnotationForm private
Definition at line 1739 of file qgsvectorlayer.h.
Referenced by readSymbology(), setAnnotationForm(), and writeSymbology().
QMap< QString, QString > QgsVectorLayer::mAttributeAliasMap private
Map that stores the aliases for attributes.
Key is the attribute name and value the alias for that attribute
Definition at line 1668 of file qgsvectorlayer.h.
Referenced by addAttributeAlias(), attributeAlias(), readSymbology(), and writeSymbology().
QList< QgsAttributeEditorElement* > QgsVectorLayer::mAttributeEditorElements private
Stores a list of attribute editor elements (Each holding a tree structure for a tab in the attribute editor)
Definition at line 1671 of file qgsvectorlayer.h.
Referenced by addAttributeEditorWidget(), attributeEditorElements(), clearAttributeEditorWidgets(), onRelationsLoaded(), readSymbology(), and writeSymbology().
QgsGeometryCache* QgsVectorLayer::mCache private
cache for some vector layer data - currently only geometries for faster editing
Definition at line 1742 of file qgsvectorlayer.h.
Referenced by commitChanges(), draw(), drawRendererV2(), drawRendererV2Levels(), rollBack(), snapWithContext(), and ~QgsVectorLayer().
QMap< QString, QPair<QString, QString> > QgsVectorLayer::mCheckedStates private
Definition at line 1721 of file qgsvectorlayer.h.
Referenced by checkedState(), readSymbology(), setCheckedState(), and writeSymbology().
QStringList QgsVectorLayer::mCommitErrors private
Definition at line 1714 of file qgsvectorlayer.h.
Referenced by commitChanges(), and commitErrors().
QgsRenderContext* QgsVectorLayer::mCurrentRendererContext private
Definition at line 1766 of file qgsvectorlayer.h.
Referenced by drawRendererV2(), and onCacheImageDelete().
int QgsVectorLayer::mCurrentVertexMarkerSize private
The current size of editing marker.
Definition at line 1709 of file qgsvectorlayer.h.
QgsVectorLayer::VertexMarkerType QgsVectorLayer::mCurrentVertexMarkerType private
The current type of editing marker.
Definition at line 1706 of file qgsvectorlayer.h.
QgsVectorDataProvider* QgsVectorLayer::mDataProvider private
Pointer to data provider derived from the abastract base class QgsDataProvider.
Definition at line 1639 of file qgsvectorlayer.h.
Referenced by addAttribute(), addFeature(), addFeatures(), addPart(), addRing(), addTopologicalPoints(), boundingBoxOfSelected(), capabilitiesString(), changeAttributeValue(), changeGeometry(), commitChanges(), countSymbolFeatures(), dataComment(), dataProvider(), deleteAttribute(), deleteSelectedFeatures(), deleteVertex(), extent(), featureCount(), geometryType(), getFeatures(), insertVertex(), isEditable(), maximumValue(), minimumValue(), moveVertex(), pendingFeatureCount(), pendingPkAttributesList(), readXml(), reload(), setCoordinateSystem(), setDataProvider(), setProviderEncoding(), setSubsetString(), simplifyDrawingCanbeApplied(), snapWithContext(), splitFeatures(), splitParts(), startEditing(), storageType(), subsetString(), translateFeature(), uniqueValues(), updateFields(), writeXml(), and ~QgsVectorLayer().
QMap< QString, QString> QgsVectorLayer::mDateFormats private
Definition at line 1723 of file qgsvectorlayer.h.
Referenced by dateFormat(), readSymbology(), and writeSymbology().
QgsDiagramLayerSettings* QgsVectorLayer::mDiagramLayerSettings private
Definition at line 1755 of file qgsvectorlayer.h.
Referenced by prepareLabelingAndDiagrams(), readSymbology(), setDiagramLayerSettings(), writeSymbology(), and ~QgsVectorLayer().
QgsDiagramRendererV2* QgsVectorLayer::mDiagramRenderer private
Definition at line 1752 of file qgsvectorlayer.h.
Referenced by drawRendererV2(), drawRendererV2Levels(), prepareLabelingAndDiagrams(), readSymbology(), setDiagramRenderer(), and writeSymbology().
QString QgsVectorLayer::mDisplayExpression private
the preview expression used to generate a human readable preview string for features
Definition at line 1647 of file qgsvectorlayer.h.
Referenced by displayExpression(), readXml(), setDisplayExpression(), and writeXml().
QString QgsVectorLayer::mDisplayField private
index of the primary label field
Definition at line 1644 of file qgsvectorlayer.h.
Referenced by displayField(), and setDisplayField().
QgsVectorLayerEditBuffer* QgsVectorLayer::mEditBuffer private
stores information about uncommitted changes to layer
Definition at line 1745 of file qgsvectorlayer.h.
Referenced by addAttribute(), addFeature(), addFeatures(), addPart(), addRing(), addTopologicalPoints(), changeAttributeValue(), changeGeometry(), commitChanges(), deleteAttribute(), deleteFeature(), deleteVertex(), draw(), drawRendererV2(), drawRendererV2Levels(), extent(), insertVertex(), isEditable(), isModified(), maximumValue(), minimumValue(), moveVertex(), pendingFeatureCount(), rollBack(), setReadOnly(), simplifyDrawingCanbeApplied(), splitFeatures(), splitParts(), startEditing(), translateFeature(), uniqueValues(), updateFields(), and ~QgsVectorLayer().
QString QgsVectorLayer::mEditForm private
Definition at line 1732 of file qgsvectorlayer.h.
Referenced by editForm(), readSymbology(), setEditForm(), and writeSymbology().
QString QgsVectorLayer::mEditFormInit private
Definition at line 1732 of file qgsvectorlayer.h.
Referenced by editFormInit(), readSymbology(), setEditFormInit(), and writeSymbology().
EditorLayout QgsVectorLayer::mEditorLayout private
Defines the default layout to use for the attribute editor (Drag and drop, UI File, Generated)
Definition at line 1730 of file qgsvectorlayer.h.
Referenced by editorLayout(), readSymbology(), setEditorLayout(), and writeSymbology().
QMap<int, QMap<QString, QVariant> > QgsVectorLayer::mEditorWidgetV2Configs private
Definition at line 1727 of file qgsvectorlayer.h.
Referenced by editorWidgetV2Config(), and setEditorWidgetV2Config().
QMap<int, QString> QgsVectorLayer::mEditorWidgetV2Types private
Definition at line 1726 of file qgsvectorlayer.h.
Referenced by editorWidgetV2(), and setEditorWidgetV2().
QMap< QString, EditType > QgsVectorLayer::mEditTypes private
Definition at line 1716 of file qgsvectorlayer.h.
Referenced by editType(), readSymbology(), setEditType(), and writeSymbology().
bool QgsVectorLayer::mEnableBackbuffer private
Enables backbuffering for the map window.
This improves graphics performance, but the possibility to cancel rendering and incremental feature drawing will be lost.
Definition at line 1636 of file qgsvectorlayer.h.
Referenced by draw(), and drawRendererV2().
QSet<QString> QgsVectorLayer::mExcludeAttributesWFS private
Attributes which are not published in WFS.
Definition at line 1676 of file qgsvectorlayer.h.
Referenced by readSymbology(), and writeSymbology().
QSet<QString> QgsVectorLayer::mExcludeAttributesWMS private
Attributes which are not published in WMS.
Definition at line 1674 of file qgsvectorlayer.h.
Referenced by readSymbology(), and writeSymbology().
QPainter::CompositionMode QgsVectorLayer::mFeatureBlendMode private
Blend mode for features.
Definition at line 1700 of file qgsvectorlayer.h.
Referenced by featureBlendMode(), and setFeatureBlendMode().
QgsVectorLayer::FeatureFormSuppress QgsVectorLayer::mFeatureFormSuppress private
Type of feature form suppression after feature creation.
Note
added in 2.1
Definition at line 1736 of file qgsvectorlayer.h.
Referenced by readSymbology().
QMap< QString, bool> QgsVectorLayer::mFieldEditables private
Definition at line 1717 of file qgsvectorlayer.h.
Referenced by fieldEditable(), readSymbology(), setFieldEditable(), and writeSymbology().
QgsVectorLayerJoinBuffer* QgsVectorLayer::mJoinBuffer private
Definition at line 1749 of file qgsvectorlayer.h.
Referenced by addJoin(), createJoinCaches(), maximumValue(), minimumValue(), QgsVectorLayerFeatureIterator::prepareJoins(), QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator(), readXml(), removeJoin(), setDataProvider(), uniqueValues(), updateFields(), vectorJoins(), writeXml(), and ~QgsVectorLayer().
QgsLabel* QgsVectorLayer::mLabel private
Label.
Definition at line 1691 of file qgsvectorlayer.h.
Referenced by drawLabels(), label(), readSymbology(), setDataProvider(), writeSymbology(), and ~QgsVectorLayer().
bool QgsVectorLayer::mLabelFontNotFoundNotified private
Whether 'labeling font not found' has be shown for this layer (only show once in QgsMessageBar, on first rendering)
Definition at line 1697 of file qgsvectorlayer.h.
Referenced by prepareLabelingAndDiagrams().
bool QgsVectorLayer::mLabelOn private
Display labels.
Definition at line 1694 of file qgsvectorlayer.h.
Referenced by drawLabels(), enableLabels(), hasLabelsEnabled(), and setDataProvider().
QMap< QString, bool> QgsVectorLayer::mLabelOnTop private
Definition at line 1718 of file qgsvectorlayer.h.
Referenced by labelOnTop(), readSymbology(), setLabelOnTop(), and writeSymbology().
int QgsVectorLayer::mLayerTransparency private
Layer transparency.
Definition at line 1703 of file qgsvectorlayer.h.
Referenced by layerTransparency(), and setLayerTransparency().
bool QgsVectorLayer::mLazyExtent private
Definition at line 1758 of file qgsvectorlayer.h.
Referenced by extent().
QgsFeatureIterator QgsVectorLayer::mProviderIterator private
Definition at line 1641 of file qgsvectorlayer.h.
QString QgsVectorLayer::mProviderKey private
Data provider key.
Definition at line 1650 of file qgsvectorlayer.h.
Referenced by getStyleFromDatabase(), listStylesInDatabase(), loadNamedStyle(), providerType(), QgsVectorLayer(), readXml(), saveStyleToDatabase(), and setDataProvider().
QMap< QString, RangeData > QgsVectorLayer::mRanges private
Definition at line 1720 of file qgsvectorlayer.h.
Referenced by range(), readSymbology(), and writeSymbology().
bool QgsVectorLayer::mReadOnly private
Flag indicating whether the layer is in read-only mode (editing disabled) or not.
Definition at line 1656 of file qgsvectorlayer.h.
Referenced by isReadOnly(), setReadOnly(), and startEditing().
QgsFeatureRendererV2* QgsVectorLayer::mRendererV2 private
Renderer object which holds the information about how to display the features.
Definition at line 1685 of file qgsvectorlayer.h.
Referenced by countSymbolFeatures(), draw(), drawLabels(), drawRendererV2(), drawRendererV2Levels(), rendererV2(), setRendererV2(), stopRendererV2(), writeSld(), writeSymbology(), and ~QgsVectorLayer().
QgsFeatureIds QgsVectorLayer::mSelectedFeatureIds private
Set holding the feature IDs that are activated.
Note that if a feature subsequently gets deleted (i.e. by its addition to mDeletedFeatureIds), it always needs to be removed from mSelectedFeatureIds as well.
Definition at line 1662 of file qgsvectorlayer.h.
Referenced by addPart(), boundingBoxOfSelected(), QgsVectorLayerEditBuffer::commitChanges(), deleteFeature(), deleteSelectedFeatures(), deselect(), drawLabels(), drawRendererV2(), drawRendererV2Levels(), invertSelection(), invertSelectionInRectangle(), modifySelection(), removeSelection(), select(), selectedFeatureCount(), selectedFeatures(), selectedFeaturesIds(), and setSelectedFeatures().
QgsVectorSimplifyMethod QgsVectorLayer::mSimplifyMethod private
Simplification object which holds the information about how to simplify the features for fast rendering.
Definition at line 1688 of file qgsvectorlayer.h.
Referenced by draw(), QgsVectorLayer(), readSymbology(), simplifyDrawingCanbeApplied(), and writeSymbology().
bool QgsVectorLayer::mSymbolFeatureCounted private
Definition at line 1761 of file qgsvectorlayer.h.
Referenced by countSymbolFeatures(), featureCount(), invalidateSymbolCountedFlag(), and setRendererV2().
QMap<QgsSymbolV2*, long> QgsVectorLayer::mSymbolFeatureCountMap private
Definition at line 1764 of file qgsvectorlayer.h.
Referenced by countSymbolFeatures(), featureCount(), and setRendererV2().
QList< TabData > QgsVectorLayer::mTabs private
Map that stores the tab for attributes in the edit form.
Key is the tab order and value the tab name
Definition at line 1679 of file qgsvectorlayer.h.
QgsFields QgsVectorLayer::mUpdatedFields private
field map to commit
Definition at line 1665 of file qgsvectorlayer.h.
Referenced by QgsVectorLayerEditBuffer::addFeature(), QgsVectorLayerFeatureIterator::fetchFeature(), fieldEditable(), maximumValue(), minimumValue(), pendingAllAttributesList(), pendingFields(), pendingPkAttributesList(), uniqueValues(), updateFields(), QgsVectorLayerFeatureIterator::useAddedFeature(), and QgsVectorLayerFeatureIterator::useChangedAttributeFeature().
int QgsVectorLayer::mUpdateThreshold private
Update threshold for drawing features as they are read.
A value of zero indicates that no features will be drawn until all have been read
Definition at line 1630 of file qgsvectorlayer.h.
Referenced by draw(), and drawRendererV2().
bool QgsVectorLayer::mValidExtent private
Definition at line 1757 of file qgsvectorlayer.h.
Referenced by extent(), setExtent(), and updateExtents().
QMap< QString, QMap<QString, QVariant> > QgsVectorLayer::mValueMaps private
Definition at line 1719 of file qgsvectorlayer.h.
Referenced by readSymbology(), valueMap(), and writeSymbology().
QMap< QString, ValueRelationData > QgsVectorLayer::mValueRelations private
Definition at line 1722 of file qgsvectorlayer.h.
Referenced by readSymbology(), valueRelation(), and writeSymbology().
bool QgsVectorLayer::mVertexMarkerOnlyForSelection private
Flag if the vertex markers should be drawn only for selection (true) or for all features (false)
Definition at line 1712 of file qgsvectorlayer.h.
QMap< QString, QSize> QgsVectorLayer::mWidgetSize private
Definition at line 1724 of file qgsvectorlayer.h.
Referenced by readSymbology(), widgetSize(), and writeSymbology().
int QgsVectorLayer::mWkbType private
Geometry type as defined in enum WkbType (qgis.h)
Definition at line 1682 of file qgsvectorlayer.h.
Referenced by setDataProvider(), and wkbType().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayer.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayer.cpp