QGIS API Documentation: QgsSymbolV2LevelItem Class Reference
QgsSymbolV2LevelItem Class Reference
#include <qgsrendererv2.h>
Public Member Functions
QgsSymbolV2LevelItem (QgsSymbolV2 *symbol, int layer)
QgsSymbolV2 * symbol ()
int layer ()
Protected Attributes
QgsSymbolV2 * mSymbol
int mLayer
Detailed Description
Definition at line 47 of file qgsrendererv2.h.
Constructor & Destructor Documentation
QgsSymbolV2LevelItem::QgsSymbolV2LevelItem (QgsSymbolV2 * symbol, int layer) inline
Definition at line 50 of file qgsrendererv2.h.
Member Function Documentation
int QgsSymbolV2LevelItem::layer () inline
Definition at line 52 of file qgsrendererv2.h.
Referenced by QgsVectorLayer::drawRendererV2Levels(), and QgsVectorFileWriter::exportFeaturesSymbolLevels().
QgsSymbolV2* QgsSymbolV2LevelItem::symbol () inline
Definition at line 51 of file qgsrendererv2.h.
Referenced by QgsVectorLayer::drawRendererV2Levels(), and QgsVectorFileWriter::exportFeaturesSymbolLevels().
Member Data Documentation
int QgsSymbolV2LevelItem::mLayer protected
Definition at line 55 of file qgsrendererv2.h.
QgsSymbolV2* QgsSymbolV2LevelItem::mSymbol protected
Definition at line 54 of file qgsrendererv2.h.
The documentation for this class was generated from the following file:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsrendererv2.h