QGIS API Documentation: QgsComposerMultiFrameCommand Class Reference
QgsComposerMultiFrameCommand Class Reference
#include <qgscomposermultiframecommand.h>
Public Member Functions
QgsComposerMultiFrameCommand (QgsComposerMultiFrame *multiFrame, const QString &text, QUndoCommand *parent=0)
~QgsComposerMultiFrameCommand ()
void undo ()
void redo ()
void savePreviousState ()
void saveAfterState ()
bool containsChange () const
Returns true if previous state and after state are valid and different.
Private Member Functions
QgsComposerMultiFrameCommand ()
void saveState (QDomDocument &stateDoc)
void restoreState (QDomDocument &stateDoc)
bool checkFirstRun ()
Private Attributes
QgsComposerMultiFrame * mMultiFrame
QDomDocument mPreviousState
QDomDocument mAfterState
bool mFirstRun
Detailed Description
Definition at line 26 of file qgscomposermultiframecommand.h.
Constructor & Destructor Documentation
QgsComposerMultiFrameCommand::QgsComposerMultiFrameCommand (QgsComposerMultiFrame * multiFrame, const QString & text, QUndoCommand * parent = 0)
Definition at line 22 of file qgscomposermultiframecommand.cpp.
QgsComposerMultiFrameCommand::~QgsComposerMultiFrameCommand ()
Definition at line 31 of file qgscomposermultiframecommand.cpp.
QgsComposerMultiFrameCommand::QgsComposerMultiFrameCommand () private
Definition at line 27 of file qgscomposermultiframecommand.cpp.
Member Function Documentation
bool QgsComposerMultiFrameCommand::checkFirstRun () private
Definition at line 79 of file qgscomposermultiframecommand.cpp.
References mFirstRun.
Referenced by redo().
bool QgsComposerMultiFrameCommand::containsChange () const
Returns true if previous state and after state are valid and different.
Definition at line 89 of file qgscomposermultiframecommand.cpp.
References mAfterState, and mPreviousState.
Referenced by QgsComposition::endMultiFrameCommand().
void QgsComposerMultiFrameCommand::redo ()
Definition at line 40 of file qgscomposermultiframecommand.cpp.
References checkFirstRun(), mAfterState, and restoreState().
void QgsComposerMultiFrameCommand::restoreState (QDomDocument & stateDoc) private
Definition at line 70 of file qgscomposermultiframecommand.cpp.
References QgsProject::dirty(), QgsProject::instance(), mMultiFrame, and QgsComposerMultiFrame::readXML().
Referenced by redo(), and undo().
void QgsComposerMultiFrameCommand::saveAfterState ()
Definition at line 54 of file qgscomposermultiframecommand.cpp.
References mAfterState, and saveState().
Referenced by QgsComposition::endMultiFrameCommand().
void QgsComposerMultiFrameCommand::savePreviousState ()
Definition at line 49 of file qgscomposermultiframecommand.cpp.
References mPreviousState, and saveState().
Referenced by QgsComposition::beginMultiFrameCommand().
void QgsComposerMultiFrameCommand::saveState (QDomDocument & stateDoc) private
Definition at line 59 of file qgscomposermultiframecommand.cpp.
References mMultiFrame, and QgsComposerMultiFrame::writeXML().
Referenced by saveAfterState(), and savePreviousState().
void QgsComposerMultiFrameCommand::undo ()
Definition at line 35 of file qgscomposermultiframecommand.cpp.
References mPreviousState, and restoreState().
Member Data Documentation
QDomDocument QgsComposerMultiFrameCommand::mAfterState private
Definition at line 45 of file qgscomposermultiframecommand.h.
Referenced by containsChange(), redo(), and saveAfterState().
bool QgsComposerMultiFrameCommand::mFirstRun private
Definition at line 47 of file qgscomposermultiframecommand.h.
Referenced by checkFirstRun().
QgsComposerMultiFrame* QgsComposerMultiFrameCommand::mMultiFrame private
Definition at line 42 of file qgscomposermultiframecommand.h.
Referenced by restoreState(), and saveState().
QDomDocument QgsComposerMultiFrameCommand::mPreviousState private
Definition at line 44 of file qgscomposermultiframecommand.h.
Referenced by containsChange(), savePreviousState(), and undo().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgscomposermultiframecommand.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/composer/qgscomposermultiframecommand.cpp