QGIS API Documentation: QgsPointPatternFillSymbolLayer Class Reference
QgsPointPatternFillSymbolLayer Class Reference
#include <qgsfillsymbollayerv2.h>
Public Member Functions
QgsPointPatternFillSymbolLayer ()
~QgsPointPatternFillSymbolLayer ()
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
void toSld (QDomDocument &doc, QDomElement &element, QgsStringMap props) const
double estimateMaxBleed () const
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
double distanceX () const
void setDistanceX (double d)
double distanceY () const
void setDistanceY (double d)
double displacementX () const
void setDisplacementX (double d)
double displacementY () const
void setDisplacementY (double d)
bool setSubSymbol (QgsSymbolV2 *symbol)
virtual QgsSymbolV2 * subSymbol ()
void setDistanceXUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit distanceXUnit () const
void setDistanceYUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit distanceYUnit () const
void setDisplacementXUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit displacementXUnit () const
void setDisplacementYUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit displacementYUnit () const
void setOutputUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outputUnit () const
virtual QSet< QString > usedAttributes () const
Public Member Functions inherited from QgsImageFillSymbolLayer
QgsImageFillSymbolLayer ()
virtual ~QgsImageFillSymbolLayer ()
void renderPolygon (const QPolygonF &points, QList< QPolygonF > *rings, QgsSymbolV2RenderContext &context)
void setOutlineWidthUnit (QgsSymbolV2::OutputUnit unit)
QgsSymbolV2::OutputUnit outlineWidthUnit () const
virtual double dxfWidth (const QgsDxfExport &e, const QgsSymbolV2RenderContext &context) const
virtual QColor dxfColor (const QgsSymbolV2RenderContext &context) const
virtual Qt::PenStyle dxfPenStyle () const
Public Member Functions inherited from QgsFillSymbolLayerV2
void drawPreviewIcon (QgsSymbolV2RenderContext &context, QSize size)
void setAngle (double angle)
double angle () const
Public Member Functions inherited from QgsSymbolLayerV2
virtual QColor color () const
virtual void setColor (const QColor &color)
virtual void setOutlineColor (const QColor &color)
Set outline color.
virtual QColor outlineColor () const
Get outline color.
virtual void setFillColor (const QColor &color)
Set fill color.
virtual QColor fillColor () const
Get fill color.
virtual ~QgsSymbolLayerV2 ()
virtual QString ogrFeatureStyle (double mmScaleFactor, double mapUnitScaleFactor) const
QgsSymbolV2::SymbolType type () const
void setLocked (bool locked)
bool isLocked () const
void setRenderingPass (int renderingPass)
int renderingPass () const
virtual const QgsExpression * dataDefinedProperty (const QString &property) const
virtual QString dataDefinedPropertyString (const QString &property) const
virtual void setDataDefinedProperty (const QString &property, const QString &expressionString)
virtual void removeDataDefinedProperty (const QString &property)
virtual void removeDataDefinedProperties ()
bool hasDataDefinedProperties () const
virtual bool writeDxf (QgsDxfExport &e, double mmMapUnitScaleFactor, const QString &layerName, const QgsSymbolV2RenderContext *context, const QgsFeature *f, const QPointF &shift=QPointF(0.0, 0.0)) const
virtual QVector< qreal > dxfCustomDashPattern (QgsSymbolV2::OutputUnit &unit) const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
static QgsSymbolLayerV2 * createFromSld (QDomElement &element)
Protected Member Functions
void applyDataDefinedSettings (const QgsSymbolV2RenderContext &context)
Protected Attributes
QgsMarkerSymbolV2 * mMarkerSymbol
double mDistanceX
QgsSymbolV2::OutputUnit mDistanceXUnit
double mDistanceY
QgsSymbolV2::OutputUnit mDistanceYUnit
double mDisplacementX
QgsSymbolV2::OutputUnit mDisplacementXUnit
double mDisplacementY
QgsSymbolV2::OutputUnit mDisplacementYUnit
Protected Attributes inherited from QgsImageFillSymbolLayer
QBrush mBrush
double mNextAngle
double mOutlineWidth
Outline width.
QgsSymbolV2::OutputUnit mOutlineWidthUnit
QgsLineSymbolV2 * mOutline
Custom outline.
Protected Attributes inherited from QgsFillSymbolLayerV2
double mAngle
Protected Attributes inherited from QgsSymbolLayerV2
QgsSymbolV2::SymbolType mType
bool mLocked
QColor mColor
int mRenderingPass
QMap< QString, QgsExpression * > mDataDefinedProperties
Private Member Functions
void applyPattern (const QgsSymbolV2RenderContext &context, QBrush &brush, double distanceX, double distanceY, double displacementX, double displacementY)
Additional Inherited Members
Static Protected Attributes inherited from QgsSymbolLayerV2
static const bool selectionIsOpaque = true
static const bool selectFillBorder = false
static const bool selectFillStyle = false
Detailed Description
Definition at line 465 of file qgsfillsymbollayerv2.h.
Constructor & Destructor Documentation
QgsPointPatternFillSymbolLayer::QgsPointPatternFillSymbolLayer ()
Definition at line 2025 of file qgsfillsymbollayerv2.cpp.
References mDisplacementX, mDisplacementY, mDistanceX, mDistanceY, and setSubSymbol().
Referenced by create().
QgsPointPatternFillSymbolLayer::~QgsPointPatternFillSymbolLayer ()
Definition at line 2037 of file qgsfillsymbollayerv2.cpp.
Member Function Documentation
void QgsPointPatternFillSymbolLayer::applyDataDefinedSettings (const QgsSymbolV2RenderContext & context) protected virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2291 of file qgsfillsymbollayerv2.cpp.
References applyPattern(), displacementX(), displacementY(), distanceX(), distanceY(), QgsExpression::evaluate(), QgsSymbolLayerV2::expression(), QgsSymbolV2RenderContext::feature(), QgsImageFillSymbolLayer::mBrush, mDisplacementX, mDisplacementY, mDistanceX, and mDistanceY.
void QgsPointPatternFillSymbolLayer::applyPattern (const QgsSymbolV2RenderContext & context, QBrush & brush, double distanceX, double distanceY, double displacementX, double displacementY) private
Definition at line 2121 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2RenderContext::alpha(), QgsSymbolV2RenderContext::feature(), QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), mDisplacementXUnit, mDisplacementYUnit, mDistanceXUnit, mDistanceYUnit, mMarkerSymbol, QgsSymbolLayerV2Utils::multiplyImageOpacity(), QgsSymbolLayerV2Utils::pixelSizeScaleFactor(), qgsDoubleNear(), QgsRenderContext::rasterScaleFactor(), QgsSymbolV2RenderContext::renderContext(), QgsMarkerSymbolV2::renderPoint(), QgsRenderContext::scaleFactor(), QgsRenderContext::setForceVectorOutput(), QgsRenderContext::setMapToPixel(), QgsRenderContext::setPainter(), QgsRenderContext::setRasterScaleFactor(), QgsRenderContext::setScaleFactor(), QgsSymbolV2::startRender(), and QgsSymbolV2::stopRender().
Referenced by applyDataDefinedSettings(), and startRender().
QgsSymbolLayerV2 * QgsPointPatternFillSymbolLayer::clone () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2221 of file qgsfillsymbollayerv2.cpp.
References QgsMarkerSymbolV2::clone(), QgsSymbolLayerV2::copyDataDefinedProperties(), create(), mMarkerSymbol, properties(), and setSubSymbol().
QgsSymbolLayerV2 * QgsPointPatternFillSymbolLayer::create (const QgsStringMap & properties = QgsStringMap()) static
Definition at line 2059 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::decodeOutputUnit(), QgsPointPatternFillSymbolLayer(), QgsSymbolLayerV2::setDataDefinedProperty(), setDisplacementX(), setDisplacementXUnit(), setDisplacementY(), setDisplacementYUnit(), setDistanceX(), setDistanceXUnit(), setDistanceY(), and setDistanceYUnit().
Referenced by clone(), and QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QgsSymbolLayerV2 * QgsPointPatternFillSymbolLayer::createFromSld (QDomElement & element) static
Definition at line 2269 of file qgsfillsymbollayerv2.cpp.
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
double QgsPointPatternFillSymbolLayer::displacementX () const inline
Definition at line 495 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings().
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::displacementXUnit () const inline
Definition at line 511 of file qgsfillsymbollayerv2.h.
double QgsPointPatternFillSymbolLayer::displacementY () const inline
Definition at line 498 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings().
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::displacementYUnit () const inline
Definition at line 514 of file qgsfillsymbollayerv2.h.
double QgsPointPatternFillSymbolLayer::distanceX () const inline
Definition at line 489 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings().
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::distanceXUnit () const inline
Definition at line 505 of file qgsfillsymbollayerv2.h.
double QgsPointPatternFillSymbolLayer::distanceY () const inline
Definition at line 492 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings().
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::distanceYUnit () const inline
Definition at line 508 of file qgsfillsymbollayerv2.h.
double QgsPointPatternFillSymbolLayer::estimateMaxBleed () const virtual
Returns the estimated maximum distance which the layer style will bleed outside the drawn shape.
Eg, polygons drawn with an outline will draw half the width of the outline outside of the polygon. This amount is estimated, since it may be affected by data defined symbology rules.
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2329 of file qgsfillsymbollayerv2.cpp.
QString QgsPointPatternFillSymbolLayer::layerType () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2116 of file qgsfillsymbollayerv2.cpp.
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::outputUnit () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2049 of file qgsfillsymbollayerv2.cpp.
References mDisplacementXUnit, mDisplacementYUnit, mDistanceXUnit, mDistanceYUnit, and QgsSymbolV2::Mixed.
QgsStringMap QgsPointPatternFillSymbolLayer::properties () const virtual
Implements QgsSymbolLayerV2.
Definition at line 2206 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeOutputUnit(), mDisplacementX, mDisplacementXUnit, mDisplacementY, mDisplacementYUnit, mDistanceX, mDistanceXUnit, mDistanceY, mDistanceYUnit, and QgsSymbolLayerV2::saveDataDefinedProperties().
Referenced by clone().
void QgsPointPatternFillSymbolLayer::setDisplacementX (double d) inline
Definition at line 496 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsPointPatternFillSymbolLayer::setDisplacementXUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 510 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsPointPatternFillSymbolLayer::setDisplacementY (double d) inline
Definition at line 499 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsPointPatternFillSymbolLayer::setDisplacementYUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 513 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsPointPatternFillSymbolLayer::setDistanceX (double d) inline
Definition at line 490 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsPointPatternFillSymbolLayer::setDistanceXUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 504 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsPointPatternFillSymbolLayer::setDistanceY (double d) inline
Definition at line 493 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsPointPatternFillSymbolLayer::setDistanceYUnit (QgsSymbolV2::OutputUnit unit) inline
Definition at line 507 of file qgsfillsymbollayerv2.h.
Referenced by create().
void QgsPointPatternFillSymbolLayer::setOutputUnit (QgsSymbolV2::OutputUnit unit) virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2041 of file qgsfillsymbollayerv2.cpp.
References mDisplacementXUnit, mDisplacementYUnit, mDistanceXUnit, and mDistanceYUnit.
bool QgsPointPatternFillSymbolLayer::setSubSymbol (QgsSymbolV2 * symbol) virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 2275 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolV2::Marker, mMarkerSymbol, and QgsSymbolV2::type().
Referenced by clone(), and QgsPointPatternFillSymbolLayer().
void QgsPointPatternFillSymbolLayer::startRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 2187 of file qgsfillsymbollayerv2.cpp.
References applyPattern(), QgsSymbolV2RenderContext::layer(), QgsImageFillSymbolLayer::mBrush, mDisplacementX, mDisplacementY, mDistanceX, mDistanceY, QgsImageFillSymbolLayer::mOutline, QgsSymbolLayerV2::prepareExpressions(), QgsSymbolV2RenderContext::renderContext(), QgsRenderContext::rendererScale(), and QgsSymbolV2::startRender().
void QgsPointPatternFillSymbolLayer::stopRender (QgsSymbolV2RenderContext & context) virtual
Implements QgsSymbolLayerV2.
Definition at line 2198 of file qgsfillsymbollayerv2.cpp.
References QgsImageFillSymbolLayer::mOutline, QgsSymbolV2RenderContext::renderContext(), and QgsSymbolV2::stopRender().
virtual QgsSymbolV2* QgsPointPatternFillSymbolLayer::subSymbol () inline virtual
Reimplemented from QgsImageFillSymbolLayer.
Definition at line 502 of file qgsfillsymbollayerv2.h.
void QgsPointPatternFillSymbolLayer::toSld (QDomDocument & doc, QDomElement & element, QgsStringMap props) const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2232 of file qgsfillsymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::createGeometryElement(), QgsSymbolLayerV2Utils::createVendorOptionElement(), QgsSymbolLayerV2Utils::encodePoint(), QgsSymbolLayerV2::layerType(), mDistanceX, mDistanceY, mMarkerSymbol, QgsSymbolV2::symbolLayer(), QgsSymbolV2::symbolLayerCount(), and QgsMarkerSymbolLayerV2::writeSldMarker().
QSet< QString > QgsPointPatternFillSymbolLayer::usedAttributes () const virtual
Reimplemented from QgsSymbolLayerV2.
Definition at line 2334 of file qgsfillsymbollayerv2.cpp.
References mMarkerSymbol, and QgsSymbolV2::usedAttributes().
Member Data Documentation
double QgsPointPatternFillSymbolLayer::mDisplacementX protected
Definition at line 527 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), properties(), QgsPointPatternFillSymbolLayer(), and startRender().
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::mDisplacementXUnit protected
Definition at line 528 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), outputUnit(), properties(), and setOutputUnit().
double QgsPointPatternFillSymbolLayer::mDisplacementY protected
Definition at line 529 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), properties(), QgsPointPatternFillSymbolLayer(), and startRender().
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::mDisplacementYUnit protected
Definition at line 530 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), outputUnit(), properties(), and setOutputUnit().
double QgsPointPatternFillSymbolLayer::mDistanceX protected
Definition at line 523 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), properties(), QgsPointPatternFillSymbolLayer(), startRender(), and toSld().
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::mDistanceXUnit protected
Definition at line 524 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), outputUnit(), properties(), and setOutputUnit().
double QgsPointPatternFillSymbolLayer::mDistanceY protected
Definition at line 525 of file qgsfillsymbollayerv2.h.
Referenced by applyDataDefinedSettings(), properties(), QgsPointPatternFillSymbolLayer(), startRender(), and toSld().
QgsSymbolV2::OutputUnit QgsPointPatternFillSymbolLayer::mDistanceYUnit protected
Definition at line 526 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), outputUnit(), properties(), and setOutputUnit().
QgsMarkerSymbolV2* QgsPointPatternFillSymbolLayer::mMarkerSymbol protected
Definition at line 522 of file qgsfillsymbollayerv2.h.
Referenced by applyPattern(), clone(), setSubSymbol(), toSld(), and usedAttributes().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsfillsymbollayerv2.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgsfillsymbollayerv2.cpp