QGIS API Documentation: QgsLayerItem Class Reference
QgsLayerItem Class Reference
Item that represents a layer that can be opened with one of the providers.
#include <qgsdataitem.h>
Public Types
enum LayerType {
NoType, Vector, Raster, Point,
Line, Polygon, TableLayer, Database,
Table
}
Public Types inherited from QgsDataItem
enum Type {
Collection, Directory, Layer, Error,
Favourites
}
enum Capability { NoCapabilities = 0, SetCrs = 1 }
Public Member Functions
QgsLayerItem (QgsDataItem *parent, QString name, QString path, QString uri, LayerType layerType, QString providerKey)
virtual bool equal (const QgsDataItem *other)
QgsMapLayer::LayerType mapLayerType ()
QString uri ()
QString providerKey ()
virtual QString layerName () const
Public Member Functions inherited from QgsDataItem
QgsDataItem (QgsDataItem::Type type, QgsDataItem *parent, QString name, QString path)
virtual ~QgsDataItem ()
bool hasChildren ()
int rowCount ()
virtual void refresh ()
virtual QVector< QgsDataItem * > createChildren ()
virtual void populate ()
bool isPopulated ()
virtual void addChildItem (QgsDataItem *child, bool refresh=false)
virtual void deleteChildItem (QgsDataItem *child)
virtual QgsDataItem * removeChildItem (QgsDataItem *child)
virtual QWidget * paramWidget ()
virtual QList< QAction * > actions ()
virtual bool acceptDrop ()
virtual bool handleDrop (const QMimeData *, Qt::DropAction)
virtual bool setCrs (QgsCoordinateReferenceSystem crs)
virtual Capability capabilities ()
Type type () const
QgsDataItem * parent () const
void setParent (QgsDataItem *parent)
QVector< QgsDataItem * > children () const
QIcon icon () const
QString name () const
QString path () const
void setIcon (QIcon icon)
void setToolTip (QString msg)
QString toolTip () const
Static Public Member Functions
static const QIcon & iconPoint ()
static const QIcon & iconLine ()
static const QIcon & iconPolygon ()
static const QIcon & iconTable ()
static const QIcon & iconRaster ()
static const QIcon & iconDefault ()
Static Public Member Functions inherited from QgsDataItem
static int findItem (QVector< QgsDataItem * > items, QgsDataItem *item)
Protected Attributes
QString mProviderKey
QString mUri
LayerType mLayerType
Protected Attributes inherited from QgsDataItem
Type mType
QgsDataItem * mParent
QVector< QgsDataItem * > mChildren
bool mPopulated
QString mName
QString mPath
QString mToolTip
QIcon mIcon
Additional Inherited Members
Public Slots inherited from QgsDataItem
void emitBeginInsertItems (QgsDataItem *parent, int first, int last)
void emitEndInsertItems ()
void emitBeginRemoveItems (QgsDataItem *parent, int first, int last)
void emitEndRemoveItems ()
Signals inherited from QgsDataItem
void beginInsertItems (QgsDataItem *parent, int first, int last)
void endInsertItems ()
void beginRemoveItems (QgsDataItem *parent, int first, int last)
void endRemoveItems ()
Detailed Description
Item that represents a layer that can be opened with one of the providers.
Definition at line 155 of file qgsdataitem.h.
Member Enumeration Documentation
enum QgsLayerItem::LayerType
Enumerator:
NoType
Vector
Raster
Point
Line
Polygon
TableLayer
Database
Table
Definition at line 159 of file qgsdataitem.h.
Constructor & Destructor Documentation
QgsLayerItem::QgsLayerItem (QgsDataItem * parent, QString name, QString path, QString uri, LayerType layerType, QString providerKey)
Definition at line 346 of file qgsdataitem.cpp.
References iconDefault(), iconLine(), iconPoint(), iconPolygon(), iconRaster(), iconTable(), Line, QgsDataItem::mIcon, Point, Polygon, Raster, TableLayer, and Vector.
Member Function Documentation
bool QgsLayerItem::equal (const QgsDataItem * other) virtual
Reimplemented from QgsDataItem.
Definition at line 372 of file qgsdataitem.cpp.
References QgsDataItem::mName, QgsDataItem::mPath, mProviderKey, mUri, and QgsDataItem::type().
const QIcon & QgsLayerItem::iconDefault () static
Definition at line 93 of file qgsdataitem.cpp.
References QgsApplication::getThemeIcon(), and QgsDataItem::icon().
Referenced by QgsLayerItem().
const QIcon & QgsLayerItem::iconLine () static
Definition at line 53 of file qgsdataitem.cpp.
References QgsApplication::getThemeIcon(), and QgsDataItem::icon().
Referenced by QgsLayerItem().
const QIcon & QgsLayerItem::iconPoint () static
Definition at line 43 of file qgsdataitem.cpp.
References QgsApplication::getThemeIcon(), and QgsDataItem::icon().
Referenced by QgsLayerItem().
const QIcon & QgsLayerItem::iconPolygon () static
Definition at line 63 of file qgsdataitem.cpp.
References QgsApplication::getThemeIcon(), and QgsDataItem::icon().
Referenced by QgsLayerItem().
const QIcon & QgsLayerItem::iconRaster () static
Definition at line 83 of file qgsdataitem.cpp.
References QgsApplication::getThemeIcon(), and QgsDataItem::icon().
Referenced by QgsLayerItem().
const QIcon & QgsLayerItem::iconTable () static
Definition at line 73 of file qgsdataitem.cpp.
References QgsApplication::getThemeIcon(), and QgsDataItem::icon().
Referenced by QgsLayerItem().
virtual QString QgsLayerItem::layerName () const inline virtual
Definition at line 203 of file qgsdataitem.h.
References QgsDataItem::name().
QgsMapLayer::LayerType QgsLayerItem::mapLayerType ()
Definition at line 365 of file qgsdataitem.cpp.
References mLayerType, Raster, QgsMapLayer::RasterLayer, and QgsMapLayer::VectorLayer.
Referenced by QgsMimeDataUtils::Uri::Uri().
QString QgsLayerItem::providerKey () inline
Definition at line 187 of file qgsdataitem.h.
QString QgsLayerItem::uri () inline
Definition at line 184 of file qgsdataitem.h.
Member Data Documentation
LayerType QgsLayerItem::mLayerType protected
Definition at line 193 of file qgsdataitem.h.
Referenced by mapLayerType().
QString QgsLayerItem::mProviderKey protected
Definition at line 191 of file qgsdataitem.h.
Referenced by equal().
QString QgsLayerItem::mUri protected
Definition at line 192 of file qgsdataitem.h.
Referenced by equal().
The documentation for this class was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsdataitem.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsdataitem.cpp