QGIS API Documentation: /tmp/buildd/qgis-2.2.0+wheezy1/src/core/gps/parse.h File Reference
parse.h File Reference
#include "sentence.h"
Functions
int nmea_pack_type (const char *buff, int buff_sz)
int nmea_find_tail (const char *buff, int buff_sz, int *res_crc)
int nmea_parse_GPGGA (const char *buff, int buff_sz, nmeaGPGGA *pack)
int nmea_parse_GPGSA (const char *buff, int buff_sz, nmeaGPGSA *pack)
int nmea_parse_GPGSV (const char *buff, int buff_sz, nmeaGPGSV *pack)
int nmea_parse_GPRMC (const char *buff, int buff_sz, nmeaGPRMC *pack)
int nmea_parse_GPVTG (const char *buff, int buff_sz, nmeaGPVTG *pack)
void nmea_GPGGA2info (nmeaGPGGA *pack, nmeaINFO *info)
void nmea_GPGSA2info (nmeaGPGSA *pack, nmeaINFO *info)
void nmea_GPGSV2info (nmeaGPGSV *pack, nmeaINFO *info)
void nmea_GPRMC2info (nmeaGPRMC *pack, nmeaINFO *info)
void nmea_GPVTG2info (nmeaGPVTG *pack, nmeaINFO *info)
Function Documentation
int nmea_find_tail (const char * buff, int buff_sz, int * res_crc)
void nmea_GPGGA2info (nmeaGPGGA * pack, nmeaINFO * info)
void nmea_GPGSA2info (nmeaGPGSA * pack, nmeaINFO * info)
void nmea_GPGSV2info (nmeaGPGSV * pack, nmeaINFO * info)
void nmea_GPRMC2info (nmeaGPRMC * pack, nmeaINFO * info)
void nmea_GPVTG2info (nmeaGPVTG * pack, nmeaINFO * info)
int nmea_pack_type (const char * buff, int buff_sz)
int nmea_parse_GPGGA (const char * buff, int buff_sz, nmeaGPGGA * pack)
Referenced by QgsNMEAConnection::processGGASentence().
int nmea_parse_GPGSA (const char * buff, int buff_sz, nmeaGPGSA * pack)
Referenced by QgsNMEAConnection::processGSASentence().
int nmea_parse_GPGSV (const char * buff, int buff_sz, nmeaGPGSV * pack)
Referenced by QgsNMEAConnection::processGSVSentence().
int nmea_parse_GPRMC (const char * buff, int buff_sz, nmeaGPRMC * pack)
Referenced by QgsNMEAConnection::processRMCSentence().
int nmea_parse_GPVTG (const char * buff, int buff_sz, nmeaGPVTG * pack)
Referenced by QgsNMEAConnection::processVTGSentence().