QGIS API Documentation: /tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgis.cpp File Reference
qgis.cpp File Reference
#include "qgis.h"
#include "qgsversion.h"
#include <QCoreApplication>
#include <QDate>
#include <QTime>
#include <QDateTime>
#include "qgsconfig.h"
#include "qgslogger.h"
#include <ogr_api.h>
Macros
#define DEGREE_TO_METER 111319.49079327358
#define FEET_TO_METER 0.3048
#define NMILE_TO_METER 1852.0
Functions
void * qgsMalloc (size_t size)
Allocates size bytes and returns a pointer to the allocated memory.
void * qgsCalloc (size_t nmemb, size_t size)
Allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated memory.
void qgsFree (void *ptr)
Frees the memory space pointed to by ptr.
bool qgsVariantLessThan (const QVariant &lhs, const QVariant &rhs)
bool qgsVariantGreaterThan (const QVariant &lhs, const QVariant &rhs)
QString qgsVsiPrefix (QString path)
Variables
const CORE_EXPORT QString GEOPROJ4 = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
PROJ4 string that represents a geographic coord sys.
const CORE_EXPORT QString GEOWKT = " AUTHORITY[\"EPSG\",4326]]"
Wkt string that represents a geographic coord sys.
const CORE_EXPORT QString PROJECT_SCALES = "1:10000,1:5000,1:2500,1:1000,1:500"
const CORE_EXPORT QString GEO_EPSG_CRS_AUTHID = "EPSG:4326"
Geographic coord sys from EPSG authority.
const CORE_EXPORT QString GEO_NONE = "NONE"
Constant that holds the string representation for "No ellips/No CRS".
Macro Definition Documentation
#define DEGREE_TO_METER 111319.49079327358
Referenced by QGis::fromUnitToUnitFactor().
#define FEET_TO_METER 0.3048
Referenced by QGis::fromUnitToUnitFactor().
#define NMILE_TO_METER 1852.0
Referenced by QGis::fromUnitToUnitFactor().
Function Documentation
void* qgsCalloc (size_t nmemb, size_t size)
Allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated memory.
Works like C calloc() but prints debug message by QgsLogger if allocation fails.
Parameters
nmemb number of elements
size size of element in bytes
Definition at line 182 of file qgis.cpp.
References QgsDebugMsg, and qgsMalloc().
void qgsFree (void * ptr)
Frees the memory space pointed to by ptr.
Works like C free().
Parameters
ptr pointer to memory space
Definition at line 197 of file qgis.cpp.
Referenced by QgsRasterBlock::convert(), QgsRasterBlock::reset(), QgsRasterBlock::setImage(), QgsRasterFileWriter::writeImageRaster(), and QgsRasterBlock::~QgsRasterBlock().
void* qgsMalloc (size_t size)
Allocates size bytes and returns a pointer to the allocated memory.
Works like C malloc() but prints debug message by QgsLogger if allocation fails.
Parameters
size size in bytes
Definition at line 167 of file qgis.cpp.
References QgsDebugMsg.
Referenced by QgsRasterBlock::convert(), QgsRasterBlock::createNoDataBitmap(), qgsCalloc(), QgsRasterBlock::reset(), and QgsRasterFileWriter::writeImageRaster().
bool qgsVariantGreaterThan (const QVariant & lhs, const QVariant & rhs)
Definition at line 229 of file qgis.cpp.
References qgsVariantLessThan().
Referenced by QgsSymbolLayerV2Utils::sortVariantList(), and valueGreaterThan().
bool qgsVariantLessThan (const QVariant & lhs, const QVariant & rhs)
Definition at line 202 of file qgis.cpp.
Referenced by qgsVariantGreaterThan(), QgsSymbolLayerV2Utils::sortVariantList(), and valueLessThan().
QString qgsVsiPrefix (QString path)
Definition at line 234 of file qgis.cpp.
Referenced by QgsProject::readPath(), QgsZipItem::vsiPrefix(), and QgsProject::writePath().
Variable Documentation
const CORE_EXPORT QString GEO_EPSG_CRS_AUTHID = "EPSG:4326"
Geographic coord sys from EPSG authority.
Definition at line 70 of file qgis.cpp.
Referenced by QgsOWSSourceSelect::on_mChangeCRSButton_clicked(), QgsOWSSourceSelect::populateCRS(), QgsNewVectorLayerDialog::QgsNewVectorLayerDialog(), QgsVectorLayer::setCoordinateSystem(), and QgsCoordinateReferenceSystem::validate().
const CORE_EXPORT QString GEO_NONE = "NONE"
Constant that holds the string representation for "No ellips/No CRS".
Definition at line 72 of file qgis.cpp.
Referenced by QgsDistanceArea::bearing(), QgsDistanceArea::computePolygonArea(), QgsDistanceArea::convertMeasurement(), QgsMapToolIdentify::featureDerivedAttributes(), QgsAttributeDialog::init(), QgsDistanceArea::measureLine(), QgsDistanceArea::measurePolygon(), QgsDistanceArea::QgsDistanceArea(), and QgsDistanceArea::setEllipsoid().
const CORE_EXPORT QString GEOPROJ4 = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
PROJ4 string that represents a geographic coord sys.
Definition at line 50 of file qgis.cpp.
const CORE_EXPORT QString GEOWKT = " AUTHORITY[\"EPSG\",4326]]"
Wkt string that represents a geographic coord sys.
Note
added in 1.8 to replace GEOWkt
Definition at line 53 of file qgis.cpp.
const CORE_EXPORT QString PROJECT_SCALES = "1:10000,1:5000,1:2500,1:1000,1:500"
Definition at line 66 of file qgis.cpp.
Referenced by QgsScaleComboBox::updateScales().