QGIS API Documentation: /tmp/buildd/qgis-2.2.0+wheezy1/src/core/symbology-ng/qgscategorizedsymbolrendererv2.cpp File Reference
qgscategorizedsymbolrendererv2.cpp File Reference
#include <algorithm>
#include "qgscategorizedsymbolrendererv2.h"
#include "qgssymbolv2.h"
#include "qgssymbollayerv2utils.h"
#include "qgsvectorcolorrampv2.h"
#include "qgsfeature.h"
#include "qgsvectorlayer.h"
#include "qgslogger.h"
#include <QDomDocument>
#include <QDomElement>
#include <QSettings>
Functions
bool valueLessThan (const QgsRendererCategoryV2 &c1, const QgsRendererCategoryV2 &c2)
bool valueGreaterThan (const QgsRendererCategoryV2 &c1, const QgsRendererCategoryV2 &c2)
bool labelLessThan (const QgsRendererCategoryV2 &c1, const QgsRendererCategoryV2 &c2)
bool labelGreaterThan (const QgsRendererCategoryV2 &c1, const QgsRendererCategoryV2 &c2)
Function Documentation
bool labelGreaterThan (const QgsRendererCategoryV2 & c1, const QgsRendererCategoryV2 & c2)
Definition at line 325 of file qgscategorizedsymbolrendererv2.cpp.
References labelLessThan().
Referenced by QgsCategorizedSymbolRendererV2::sortByLabel(), and QgsGraduatedSymbolRendererV2::sortByLabel().
bool labelLessThan (const QgsRendererCategoryV2 & c1, const QgsRendererCategoryV2 & c2)
Definition at line 320 of file qgscategorizedsymbolrendererv2.cpp.
References QgsRendererCategoryV2::label().
Referenced by labelGreaterThan(), QgsGraduatedSymbolRendererV2::sortByLabel(), and QgsCategorizedSymbolRendererV2::sortByLabel().
bool valueGreaterThan (const QgsRendererCategoryV2 & c1, const QgsRendererCategoryV2 & c2)
Definition at line 303 of file qgscategorizedsymbolrendererv2.cpp.
References qgsVariantGreaterThan(), and QgsRendererCategoryV2::value().
Referenced by QgsCategorizedSymbolRendererV2::sortByValue(), and QgsGraduatedSymbolRendererV2::sortByValue().
bool valueLessThan (const QgsRendererCategoryV2 & c1, const QgsRendererCategoryV2 & c2)
Definition at line 299 of file qgscategorizedsymbolrendererv2.cpp.
References qgsVariantLessThan(), and QgsRendererCategoryV2::value().
Referenced by QgsCategorizedSymbolRendererV2::sortByValue(), QgsGraduatedSymbolRendererV2::sortByValue(), and valueGreaterThan().