QGIS API Documentation: /tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgscoordinatereferencesystem.h File Reference
qgscoordinatereferencesystem.h File Reference
#include <ostream>
#include <QString>
#include <QMap>
#include <QHash>
#include "qgis.h"
Classes
class QgsCoordinateReferenceSystem
Class for storing a coordinate reference system (CRS)
Typedefs
typedef struct sqlite3 sqlite3
typedef void * OGRSpatialReferenceH
typedef void(* CUSTOM_CRS_VALIDATION)(QgsCoordinateReferenceSystem &)
Functions
std::ostream & operator<< (std::ostream &os, const QgsCoordinateReferenceSystem &r)
Output stream operator.
Typedef Documentation
typedef void(* CUSTOM_CRS_VALIDATION)(QgsCoordinateReferenceSystem &)
Definition at line 45 of file qgscoordinatereferencesystem.h.
typedef void* OGRSpatialReferenceH
Definition at line 41 of file qgscoordinatereferencesystem.h.
typedef struct sqlite3 sqlite3
Definition at line 33 of file qgscoordinatereferencesystem.h.
Function Documentation
std::ostream& operator<< (std::ostream & os, const QgsCoordinateReferenceSystem & r) inline
Output stream operator.
Definition at line 482 of file qgscoordinatereferencesystem.h.
References QgsCoordinateReferenceSystem::description(), QgsCoordinateReferenceSystem::ellipsoidAcronym(), QgsCoordinateReferenceSystem::projectionAcronym(), and QgsCoordinateReferenceSystem::toProj4().