QGIS API Documentation: QgsVectorLayerFeatureIterator::FetchJoinInfo Struct Reference
QgsVectorLayerFeatureIterator::FetchJoinInfo Struct Reference
Join information prepared for fast attribute id mapping in QgsVectorLayerJoinBuffer::updateFeatureAttributes().
#include <qgsvectorlayerfeatureiterator.h>
Public Member Functions
void addJoinedAttributesCached (QgsFeature &f, const QVariant &joinValue) const
void addJoinedAttributesDirect (QgsFeature &f, const QVariant &joinValue) const
Public Attributes
const QgsVectorJoinInfo * joinInfo
cannonical source of information about the join
QgsAttributeList attributes
attributes to fetch
int indexOffset
at what position the joined fields start
QgsVectorLayer * joinLayer
resolved pointer to the joined layer
int targetField
index of field (of this layer) that drives the join
int joinField
index of field (of the joined layer) must have equal value
Detailed Description
Join information prepared for fast attribute id mapping in QgsVectorLayerJoinBuffer::updateFeatureAttributes().
Created in the select() method of QgsVectorLayerJoinBuffer for the joins that contain fetched attributes
Definition at line 94 of file qgsvectorlayerfeatureiterator.h.
Member Function Documentation
void QgsVectorLayerFeatureIterator::FetchJoinInfo::addJoinedAttributesCached (QgsFeature & f, const QVariant & joinValue) const
Definition at line 509 of file qgsvectorlayerfeatureiterator.cpp.
References QgsVectorJoinInfo::cachedAttributes, index, indexOffset, joinField, joinInfo, and QgsFeature::setAttribute().
Referenced by QgsVectorLayerFeatureIterator::addJoinedAttributes().
void QgsVectorLayerFeatureIterator::FetchJoinInfo::addJoinedAttributesDirect (QgsFeature & f, const QVariant & joinValue) const
Definition at line 531 of file qgsvectorlayerfeatureiterator.cpp.
References QgsFeature::attributes(), index, QgsFeatureIterator::nextFeature(), QgsFeatureRequest::NoGeometry, QgsFeature::setAttribute(), QgsFeatureRequest::setFlags(), and QgsFeatureRequest::setSubsetOfAttributes().
Referenced by QgsVectorLayerFeatureIterator::addJoinedAttributes().
Member Data Documentation
QgsAttributeList QgsVectorLayerFeatureIterator::FetchJoinInfo::attributes
attributes to fetch
Definition at line 97 of file qgsvectorlayerfeatureiterator.h.
int QgsVectorLayerFeatureIterator::FetchJoinInfo::indexOffset
at what position the joined fields start
Definition at line 98 of file qgsvectorlayerfeatureiterator.h.
Referenced by addJoinedAttributesCached(), and QgsVectorLayerFeatureIterator::prepareJoins().
int QgsVectorLayerFeatureIterator::FetchJoinInfo::joinField
index of field (of the joined layer) must have equal value
Definition at line 101 of file qgsvectorlayerfeatureiterator.h.
Referenced by addJoinedAttributesCached(), and QgsVectorLayerFeatureIterator::prepareJoins().
const QgsVectorJoinInfo* QgsVectorLayerFeatureIterator::FetchJoinInfo::joinInfo
cannonical source of information about the join
Definition at line 96 of file qgsvectorlayerfeatureiterator.h.
Referenced by QgsVectorLayerFeatureIterator::addJoinedAttributes(), addJoinedAttributesCached(), and QgsVectorLayerFeatureIterator::prepareJoins().
QgsVectorLayer* QgsVectorLayerFeatureIterator::FetchJoinInfo::joinLayer
resolved pointer to the joined layer
Definition at line 99 of file qgsvectorlayerfeatureiterator.h.
Referenced by QgsVectorLayerFeatureIterator::prepareJoins().
int QgsVectorLayerFeatureIterator::FetchJoinInfo::targetField
index of field (of this layer) that drives the join
Definition at line 100 of file qgsvectorlayerfeatureiterator.h.
Referenced by QgsVectorLayerFeatureIterator::addJoinedAttributes(), and QgsVectorLayerFeatureIterator::prepareJoins().
The documentation for this struct was generated from the following files:
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayerfeatureiterator.h
/tmp/buildd/qgis-2.2.0+wheezy1/src/core/qgsvectorlayerfeatureiterator.cpp