var searchData=
[
  ['undoavailable',['undoAvailable',['/usr/share/qt4/doc/html/qlineedit.html#undoAvailable-prop',1,'QLineEdit']]],
  ['undodepth',['undoDepth',['/usr/share/qt4/doc/html/q3textedit.html#undoDepth-prop',1,'Q3TextEdit']]],
  ['undolimit',['undoLimit',['/usr/share/qt4/doc/html/qundostack.html#undoLimit-prop',1,'QUndoStack']]],
  ['undoredoenabled',['undoRedoEnabled',['/usr/share/qt4/doc/html/qtextdocument.html#undoRedoEnabled-prop',1,'QTextDocument::undoRedoEnabled()'],['/usr/share/qt4/doc/html/qtextbrowser.html#undoRedoEnabled-prop',1,'QTextBrowser::undoRedoEnabled()'],['/usr/share/qt4/doc/html/qplaintextedit.html#undoRedoEnabled-prop',1,'QPlainTextEdit::undoRedoEnabled()'],['/usr/share/qt4/doc/html/qtextedit.html#undoRedoEnabled-prop',1,'QTextEdit::undoRedoEnabled()'],['/usr/share/qt4/doc/html/q3textedit.html#undoRedoEnabled-prop',1,'Q3TextEdit::undoRedoEnabled()']]],
  ['unifiedtitleandtoolbaronmac',['unifiedTitleAndToolBarOnMac',['/usr/share/qt4/doc/html/qmainwindow.html#unifiedTitleAndToolBarOnMac-prop',1,'QMainWindow']]],
  ['uniformitemsizes',['uniformItemSizes',['/usr/share/qt4/doc/html/qlistview.html#uniformItemSizes-prop',1,'QListView']]],
  ['uniformrowheights',['uniformRowHeights',['/usr/share/qt4/doc/html/qtreeview.html#uniformRowHeights-prop',1,'QTreeView']]],
  ['updateinterval',['updateInterval',['/usr/share/qt4/doc/html/qtimeline.html#updateInterval-prop',1,'QTimeLine']]],
  ['updatesenabled',['updatesEnabled',['/usr/share/qt4/doc/html/qwidget.html#updatesEnabled-prop',1,'QWidget']]],
  ['url',['url',['/usr/share/qt4/doc/html/qdeclarativecomponent.html#url-prop',1,'QDeclarativeComponent::url()'],['/usr/share/qt4/doc/html/qgraphicswebview.html#url-prop',1,'QGraphicsWebView::url()'],['/usr/share/qt4/doc/html/qwebview.html#url-prop',1,'QWebView::url()'],['/usr/share/qt4/doc/html/qwebframe.html#url-prop',1,'QWebFrame::url()']]],
  ['usageinfo',['usageInfo',['../classQgsDataDefinedButton.html#a12b2e2c6717b128d4ed2196cfcc87b25',1,'QgsDataDefinedButton']]],
  ['usedesignmetrics',['useDesignMetrics',['/usr/share/qt4/doc/html/qtextdocument.html#useDesignMetrics-prop',1,'QTextDocument']]],
  ['usesbigpixmaps',['usesBigPixmaps',['/usr/share/qt4/doc/html/q3mainwindow.html#usesBigPixmaps-prop',1,'Q3MainWindow']]],
  ['usesdropdown',['usesDropDown',['/usr/share/qt4/doc/html/q3actiongroup.html#usesDropDown-prop',1,'Q3ActionGroup']]],
  ['usesscrollbuttons',['usesScrollButtons',['/usr/share/qt4/doc/html/qtabwidget.html#usesScrollButtons-prop',1,'QTabWidget::usesScrollButtons()'],['/usr/share/qt4/doc/html/qtabbar.html#usesScrollButtons-prop',1,'QTabBar::usesScrollButtons()']]],
  ['usestextlabel',['usesTextLabel',['/usr/share/qt4/doc/html/q3mainwindow.html#usesTextLabel-prop',1,'Q3MainWindow']]]
];
