var searchData=
[
  ['handleposition',['handlePosition',['/usr/share/qt4/doc/html/q3dockarea.html#handlePosition-prop',1,'Q3DockArea']]],
  ['handlewidth',['handleWidth',['/usr/share/qt4/doc/html/qsplitter.html#handleWidth-prop',1,'QSplitter']]],
  ['hashotspot',['hasHotSpot',['/usr/share/qt4/doc/html/qgesture.html#hasHotSpot-prop',1,'QGesture']]],
  ['hasselectedtext',['hasSelectedText',['/usr/share/qt4/doc/html/qlabel.html#hasSelectedText-prop',1,'QLabel::hasSelectedText()'],['/usr/share/qt4/doc/html/q3textedit.html#hasSelectedText-prop',1,'Q3TextEdit::hasSelectedText()'],['/usr/share/qt4/doc/html/qlineedit.html#hasSelectedText-prop',1,'QLineEdit::hasSelectedText()']]],
  ['hasselection',['hasSelection',['/usr/share/qt4/doc/html/qwebview.html#hasSelection-prop',1,'QWebView::hasSelection()'],['/usr/share/qt4/doc/html/qwebpage.html#hasSelection-prop',1,'QWebPage::hasSelection()']]],
  ['headerhidden',['headerHidden',['/usr/share/qt4/doc/html/qtreeview.html#headerHidden-prop',1,'QTreeView']]],
  ['headervisible',['headerVisible',['/usr/share/qt4/doc/html/qcalendarwidget-obsolete.html#headerVisible-prop',1,'QCalendarWidget']]],
  ['height',['height',['/usr/share/qt4/doc/html/qwidget.html#height-prop',1,'QWidget']]],
  ['highlightsections',['highlightSections',['/usr/share/qt4/doc/html/qheaderview.html#highlightSections-prop',1,'QHeaderView']]],
  ['historytype',['historyType',['/usr/share/qt4/doc/html/qhistorystate.html#historyType-prop',1,'QHistoryState']]],
  ['horizontaldirection',['horizontalDirection',['/usr/share/qt4/doc/html/qswipegesture.html#horizontalDirection-prop',1,'QSwipeGesture']]],
  ['horizontalheaderformat',['horizontalHeaderFormat',['/usr/share/qt4/doc/html/qcalendarwidget.html#horizontalHeaderFormat-prop',1,'QCalendarWidget']]],
  ['horizontallystretchable',['horizontallyStretchable',['/usr/share/qt4/doc/html/q3dockwindow.html#horizontallyStretchable-prop',1,'Q3DockWindow']]],
  ['horizontalscrollbarpolicy',['horizontalScrollBarPolicy',['/usr/share/qt4/doc/html/qabstractscrollarea.html#horizontalScrollBarPolicy-prop',1,'QAbstractScrollArea']]],
  ['horizontalscrollmode',['horizontalScrollMode',['/usr/share/qt4/doc/html/qabstractitemview.html#horizontalScrollMode-prop',1,'QAbstractItemView']]],
  ['horizontalspacing',['horizontalSpacing',['/usr/share/qt4/doc/html/qformlayout.html#horizontalSpacing-prop',1,'QFormLayout::horizontalSpacing()'],['/usr/share/qt4/doc/html/qgridlayout.html#horizontalSpacing-prop',1,'QGridLayout::horizontalSpacing()']]],
  ['hotspot',['hotSpot',['/usr/share/qt4/doc/html/qgesture.html#hotSpot-prop',1,'QGesture']]],
  ['hscrollbarmode',['hScrollBarMode',['/usr/share/qt4/doc/html/q3scrollview.html#hScrollBarMode-prop',1,'Q3ScrollView']]],
  ['html',['html',['/usr/share/qt4/doc/html/qtextedit.html#html-prop',1,'QTextEdit']]],
  ['hue',['hue',['/usr/share/qt4/doc/html/phonon-videowidget.html#hue-prop',1,'Phonon::VideoWidget']]]
];
