var searchData=
[
  ['background',['background',['http://doc.qt.io/qt-4.8/qmdiarea.html#background-prop',1,'QMdiArea::background()'],['http://doc.qt.io/qt-4.8/qworkspace.html#background-prop',1,'QWorkspace::background()']]],
  ['backgroundbrush',['backgroundBrush',['http://doc.qt.io/qt-4.8/qgraphicsscene.html#backgroundBrush-prop',1,'QGraphicsScene::backgroundBrush()'],['http://doc.qt.io/qt-4.8/qgraphicsview.html#backgroundBrush-prop',1,'QGraphicsView::backgroundBrush()']]],
  ['backgroundvisible',['backgroundVisible',['http://doc.qt.io/qt-4.8/qplaintextedit.html#backgroundVisible-prop',1,'QPlainTextEdit']]],
  ['baselineoffset',['baselineOffset',['http://doc.qt.io/qt-4.8/qdeclarativeitem.html#baselineOffset-prop',1,'QDeclarativeItem']]],
  ['basesize',['baseSize',['http://doc.qt.io/qt-4.8/qwidget.html#baseSize-prop',1,'QWidget']]],
  ['baseurl',['baseUrl',['http://doc.qt.io/qt-4.8/qwebframe.html#baseUrl-prop',1,'QWebFrame']]],
  ['batchsize',['batchSize',['http://doc.qt.io/qt-4.8/qlistview.html#batchSize-prop',1,'QListView']]],
  ['behaviour',['behaviour',['../classQgsColorButtonV2.html#a567c8c183eeb2bfec5908ac267c28b47',1,'QgsColorButtonV2']]],
  ['blockcount',['blockCount',['http://doc.qt.io/qt-4.8/qplaintextedit.html#blockCount-prop',1,'QPlainTextEdit::blockCount()'],['http://doc.qt.io/qt-4.8/qtextdocument.html#blockCount-prop',1,'QTextDocument::blockCount()']]],
  ['blurhints',['blurHints',['http://doc.qt.io/qt-4.8/qgraphicsblureffect.html#blurHints-prop',1,'QGraphicsBlurEffect']]],
  ['blurradius',['blurRadius',['http://doc.qt.io/qt-4.8/qgraphicsblureffect.html#blurRadius-prop',1,'QGraphicsBlurEffect::blurRadius()'],['http://doc.qt.io/qt-4.8/qgraphicsdropshadoweffect.html#blurRadius-prop',1,'QGraphicsDropShadowEffect::blurRadius()']]],
  ['bottom',['bottom',['http://doc.qt.io/qt-4.8/qintvalidator.html#bottom-prop',1,'QIntValidator::bottom()'],['http://doc.qt.io/qt-4.8/qdoublevalidator.html#bottom-prop',1,'QDoubleValidator::bottom()']]],
  ['boundarychecking',['boundaryChecking',['http://doc.qt.io/qt-4.8/q3databrowser.html#boundaryChecking-prop',1,'Q3DataBrowser']]],
  ['brightness',['brightness',['http://doc.qt.io/qt-4.8/phonon-videowidget.html#brightness-prop',1,'Phonon::VideoWidget']]],
  ['bsptreedepth',['bspTreeDepth',['http://doc.qt.io/qt-4.8/qgraphicsscene.html#bspTreeDepth-prop',1,'QGraphicsScene']]],
  ['button',['button',['http://doc.qt.io/qt-4.8/qmouseeventtransition.html#button-prop',1,'QMouseEventTransition']]],
  ['buttonsymbols',['buttonSymbols',['http://doc.qt.io/qt-4.8/qabstractspinbox.html#buttonSymbols-prop',1,'QAbstractSpinBox']]]
];
