Quantum GIS API Documentation: QgsComposerSymbolItem Class Reference
QgsComposerSymbolItem Class Reference
#include <qgscomposerlegenditem.h>
Public Member Functions
QgsComposerSymbolItem ()
QgsComposerSymbolItem (const QString &text)
QgsComposerSymbolItem (const QIcon &icon, const QString &text)
virtual ~QgsComposerSymbolItem ()
virtual QStandardItem * clone () const
virtual void writeXML (QDomElement &elem, QDomDocument &doc) const
virtual void readXML (const QDomElement &itemElem, bool xServerAvailable=true)
Read item content from xml.
void setSymbol (QgsSymbol *s)
Set symbol (takes ownership)
QgsSymbol * symbol ()
void setLayerID (const QString &id)
QString layerID () const
ItemType itemType () const
Private Attributes
QgsSymbol * mSymbol
QString mLayerID
Detailed Description
Definition at line 59 of file qgscomposerlegenditem.h.
Constructor & Destructor Documentation
QgsComposerSymbolItem::QgsComposerSymbolItem ()
Definition at line 61 of file qgscomposerlegenditem.cpp.
Referenced by clone().
QgsComposerSymbolItem::QgsComposerSymbolItem (const QString & text)
Definition at line 65 of file qgscomposerlegenditem.cpp.
QgsComposerSymbolItem::QgsComposerSymbolItem (const QIcon & icon, const QString & text)
Definition at line 69 of file qgscomposerlegenditem.cpp.
QgsComposerSymbolItem::~QgsComposerSymbolItem () [virtual]
Definition at line 73 of file qgscomposerlegenditem.cpp.
References mSymbol.
Member Function Documentation
QStandardItem * QgsComposerSymbolItem::clone () const [virtual]
Implements QgsComposerLegendItem.
Definition at line 84 of file qgscomposerlegenditem.cpp.
References mSymbol, QgsComposerSymbolItem(), and setSymbol().
ItemType QgsComposerSymbolItem::itemType () const [inline, virtual]
Implements QgsComposerLegendItem.
Definition at line 79 of file qgscomposerlegenditem.h.
References QgsComposerLegendItem::SymbologyItem.
QString QgsComposerSymbolItem::layerID () const [inline]
Definition at line 77 of file qgscomposerlegenditem.h.
void QgsComposerSymbolItem::readXML (const QDomElement & itemElem, bool xServerAvailable = true) [virtual]
Read item content from xml.
Parameters:
itemElem item to read from
xServerAvailable Read item icons if true (QIcon needs x-server)
Implements QgsComposerLegendItem.
Definition at line 108 of file qgscomposerlegenditem.cpp.
References QgsApplication::activeThemePath(), QgsSymbol::getLineSymbolAsImage(), QgsSymbol::getPointSymbolAsImage(), QgsSymbol::getPolygonSymbolAsImage(), QgsMapLayerRegistry::instance(), QGis::Line, QgsMapLayerRegistry::mapLayer(), mLayerID, QGis::NoGeometry, QGis::Point, QGis::Polygon, QgsSymbol::readXML(), setLayerID(), setSymbol(), symbol(), QgsSymbol::type(), and QGis::UnknownGeometry.
void QgsComposerSymbolItem::setLayerID (const QString & id) [inline]
Definition at line 76 of file qgscomposerlegenditem.h.
Referenced by QgsLegendModel::itemFromSymbol(), and readXML().
void QgsComposerSymbolItem::setSymbol (QgsSymbol * s)
Set symbol (takes ownership)
Definition at line 78 of file qgscomposerlegenditem.cpp.
References mSymbol.
Referenced by clone(), QgsLegendModel::itemFromSymbol(), and readXML().
QgsSymbol* QgsComposerSymbolItem::symbol () [inline]
Definition at line 74 of file qgscomposerlegenditem.h.
Referenced by QgsComposerLegend::drawLayerChildItems(), and readXML().
void QgsComposerSymbolItem::writeXML (QDomElement & elem, QDomDocument & doc) const [virtual]
Implements QgsComposerLegendItem.
Definition at line 95 of file qgscomposerlegenditem.cpp.
References mLayerID, mSymbol, and QgsSymbol::writeXML().
Member Data Documentation
QString QgsComposerSymbolItem::mLayerID [private]
Definition at line 83 of file qgscomposerlegenditem.h.
Referenced by readXML(), and writeXML().
QgsSymbol* QgsComposerSymbolItem::mSymbol [private]
Definition at line 82 of file qgscomposerlegenditem.h.
Referenced by clone(), setSymbol(), writeXML(), and ~QgsComposerSymbolItem().
The documentation for this class was generated from the following files:
src/core/composer/qgscomposerlegenditem.h
src/core/composer/qgscomposerlegenditem.cpp