Quantum GIS API Documentation: QgsSingleSymbolRenderer Class Reference
QgsSingleSymbolRenderer Class Reference
Render class to display all the features with a single QgsSymbol.
#include <qgssinglesymbolrenderer.h>
Public Member Functions
QgsSingleSymbolRenderer (QGis::GeometryType type)
QgsSingleSymbolRenderer (const QgsSingleSymbolRenderer &other)
QgsSingleSymbolRenderer & operator= (const QgsSingleSymbolRenderer &other)
virtual ~QgsSingleSymbolRenderer ()
void addSymbol (QgsSymbol *sy)
Replaces the current mSymbol by sy.
const QgsSymbol * symbol () const
void renderFeature (QgsRenderContext &renderContext, QgsFeature &f, QImage *img, bool selected, double opacity=1.0)
Renders a feature added in 1.2.
virtual int readXML (const QDomNode &rnode, QgsVectorLayer &vl)
Reads the renderer configuration from an XML file.
virtual bool writeXML (QDomNode &layer_node, QDomDocument &document, const QgsVectorLayer &vl) const
Writes the contents of the renderer to a configuration file.
bool needsAttributes () const
Returns true, attributes needed for single symbol.
QgsAttributeList classificationAttributes () const
Returns a list of all needed attributes.
void updateSymbolAttributes ()
virtual QString name () const
Returns the renderers name.
const QList< QgsSymbol * > symbols () const
Returns a list containing mSymbol.
QgsRenderer * clone () const
Returns a deep copy of this renderer.
QgsSymbol * symbolForFeature (const QgsFeature *f)
Returns renderer symbol for a feature.
Protected Attributes
QgsSymbol * mSymbol0
Object containing symbology information.
QMap< QString, QgsSymbol * > mSymbols
QgsAttributeList mSymbolAttributes
Cached copy of all underlying symbols required attribute fields.
Detailed Description
Render class to display all the features with a single QgsSymbol.
Definition at line 28 of file qgssinglesymbolrenderer.h.
Constructor & Destructor Documentation
QgsSingleSymbolRenderer::QgsSingleSymbolRenderer (QGis::GeometryType type)
Definition at line 35 of file qgssinglesymbolrenderer.cpp.
References QGis::Line, QgsRenderer::mGeometryType, mSymbol0, mSymbols, QgsSymbol::setColor(), QgsSymbol::setFillColor(), QgsSymbol::setFillStyle(), and updateSymbolAttributes().
Referenced by clone().
QgsSingleSymbolRenderer::QgsSingleSymbolRenderer (const QgsSingleSymbolRenderer & other)
Definition at line 62 of file qgssinglesymbolrenderer.cpp.
QgsSingleSymbolRenderer::~QgsSingleSymbolRenderer () [virtual]
Definition at line 89 of file qgssinglesymbolrenderer.cpp.
References mSymbols.
Member Function Documentation
void QgsSingleSymbolRenderer::addSymbol (QgsSymbol * sy)
Replaces the current mSymbol by sy.
Definition at line 95 of file qgssinglesymbolrenderer.cpp.
References mSymbol0, mSymbols, and updateSymbolAttributes().
Referenced by readXML(), and QgsSymbologyV2Conversion::rendererV2toV1().
QgsAttributeList QgsSingleSymbolRenderer::classificationAttributes () const [virtual]
Returns a list of all needed attributes.
Implements QgsRenderer.
Definition at line 240 of file qgssinglesymbolrenderer.cpp.
References mSymbolAttributes.
QgsRenderer * QgsSingleSymbolRenderer::clone () const [virtual]
Returns a deep copy of this renderer.
Implements QgsRenderer.
Definition at line 278 of file qgssinglesymbolrenderer.cpp.
References QgsSingleSymbolRenderer().
QString QgsSingleSymbolRenderer::name () const [virtual]
Returns the renderers name.
Implements QgsRenderer.
Definition at line 268 of file qgssinglesymbolrenderer.cpp.
Referenced by renderFeature().
bool QgsSingleSymbolRenderer::needsAttributes () const [inline, virtual]
Returns true, attributes needed for single symbol.
Implements QgsRenderer.
Definition at line 85 of file qgssinglesymbolrenderer.h.
QgsSingleSymbolRenderer & QgsSingleSymbolRenderer::operator= (const QgsSingleSymbolRenderer & other)
Definition at line 67 of file qgssinglesymbolrenderer.cpp.
References QgsRenderer::mGeometryType, mSymbol0, mSymbols, and updateSymbolAttributes().
int QgsSingleSymbolRenderer::readXML (const QDomNode & rnode, QgsVectorLayer & vl) [virtual]
Reads the renderer configuration from an XML file.
Parameters:
rnode the Dom node to read
vl the vector layer which will be associated with the renderer
Returns:
0 in case of success, 1 if vector layer has no renderer, 2 if classification field not found
Implements QgsRenderer.
Definition at line 202 of file qgssinglesymbolrenderer.cpp.
References addSymbol(), QgsVectorLayer::geometryType(), QgsRenderer::mGeometryType, QgsDebugMsg, QgsSymbol::readXML(), QgsVectorLayer::setRenderer(), and updateSymbolAttributes().
void QgsSingleSymbolRenderer::renderFeature (QgsRenderContext & renderContext, QgsFeature & f, QImage * img, bool selected, double opacity = 1.0) [virtual]
Renders a feature added in 1.2.
Implements QgsRenderer.
Definition at line 106 of file qgssinglesymbolrenderer.cpp.
References QgsFeature::attributeMap(), QgsSymbol::brush(), QgsSymbol::getPointSymbolAsImage(), QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), QgsRenderer::mGeometryType, QgsRenderer::mSelectionColor, mSymbol0, mSymbols, name(), QgsRenderContext::painter(), QgsSymbol::pen(), QGis::Point, QgsSymbol::pointSize(), QgsSymbol::pointSizeUnits(), QGis::Polygon, QgsDebugMsgLevel, QgsRenderContext::rasterScaleFactor(), QgsSymbol::rotationClassificationField(), QgsRenderer::scaleBrush(), QgsSymbol::scaleClassificationField(), QgsRenderContext::scaleFactor(), QgsSymbol::setNamedPointSymbol(), QgsSymbol::setPointSize(), QgsSymbol::setPointSizeUnits(), and QgsSymbol::symbolField().
const QgsSymbol * QgsSingleSymbolRenderer::symbol () const [inline]
Definition at line 80 of file qgssinglesymbolrenderer.h.
References mSymbol0.
Referenced by QgsSymbologyV2Conversion::rendererV1toV2().
QgsSymbol* QgsSingleSymbolRenderer::symbolForFeature (const QgsFeature * f) [inline, virtual]
Returns renderer symbol for a feature.
Note:
: this method was added in version 1.6
Reimplemented from QgsRenderer.
Definition at line 70 of file qgssinglesymbolrenderer.h.
const QList< QgsSymbol * > QgsSingleSymbolRenderer::symbols () const [virtual]
Returns a list containing mSymbol.
Implements QgsRenderer.
Definition at line 273 of file qgssinglesymbolrenderer.cpp.
References mSymbols.
void QgsSingleSymbolRenderer::updateSymbolAttributes ()
Definition at line 245 of file qgssinglesymbolrenderer.cpp.
References mSymbol0, mSymbolAttributes, QgsSymbol::rotationClassificationField(), QgsSymbol::scaleClassificationField(), and QgsSymbol::symbolField().
Referenced by addSymbol(), operator=(), QgsSingleSymbolRenderer(), and readXML().
bool QgsSingleSymbolRenderer::writeXML (QDomNode & layer_node, QDomDocument & document, const QgsVectorLayer & vl) const [virtual]
Writes the contents of the renderer to a configuration file.
Writes the contents of the renderer to a configuration file @ return true in case of success
Implements QgsRenderer.
Definition at line 226 of file qgssinglesymbolrenderer.cpp.
References mSymbol0, and QgsSymbol::writeXML().
Member Data Documentation
QgsSymbol* QgsSingleSymbolRenderer::mSymbol0 [protected]
Object containing symbology information.
Definition at line 74 of file qgssinglesymbolrenderer.h.
Referenced by addSymbol(), operator=(), QgsSingleSymbolRenderer(), renderFeature(), symbol(), updateSymbolAttributes(), and writeXML().
QgsAttributeList QgsSingleSymbolRenderer::mSymbolAttributes [protected]
Cached copy of all underlying symbols required attribute fields.
Definition at line 77 of file qgssinglesymbolrenderer.h.
Referenced by classificationAttributes(), and updateSymbolAttributes().
QMap<QString, QgsSymbol*> QgsSingleSymbolRenderer::mSymbols [protected]
Definition at line 75 of file qgssinglesymbolrenderer.h.
Referenced by addSymbol(), operator=(), QgsSingleSymbolRenderer(), renderFeature(), symbols(), and ~QgsSingleSymbolRenderer().
The documentation for this class was generated from the following files:
src/core/renderer/qgssinglesymbolrenderer.h
src/core/renderer/qgssinglesymbolrenderer.cpp