Quantum GIS API Documentation: QgsOverlayObjectPositionManager Class Reference
QgsOverlayObjectPositionManager Class Reference
Interface for classes that arrange overlay objects of different layers on the map.
#include <qgsoverlayobjectpositionmanager.h>
Public Member Functions
virtual ~QgsOverlayObjectPositionManager ()
virtual void addLayer (QgsVectorLayer *vl, QList< QgsVectorOverlay * > &overlays)=0
Adds a layer that may contain * overlays to the position manager.
virtual void removeLayers ()=0
Removes all the layers.
virtual void findObjectPositions (const QgsRenderContext &context, QGis::UnitType unitType)=0
Calculate positions for the overlay objects.
Detailed Description
Interface for classes that arrange overlay objects of different layers on the map.
Note:
This class has been added in version 1.1
Definition at line 31 of file qgsoverlayobjectpositionmanager.h.
Constructor & Destructor Documentation
virtual QgsOverlayObjectPositionManager::~QgsOverlayObjectPositionManager () [inline, virtual]
Definition at line 35 of file qgsoverlayobjectpositionmanager.h.
Member Function Documentation
virtual void QgsOverlayObjectPositionManager::addLayer (QgsVectorLayer * vl, QList< QgsVectorOverlay * > & overlays) [pure virtual]
Adds a layer that may contain * overlays to the position manager.
The overlay objects contained in the overlays will then be considered in label placement
Implemented in QgsCentralPointPositionManager, and QgsPALObjectPositionManager.
Referenced by QgsMapRenderer::render().
virtual void QgsOverlayObjectPositionManager::findObjectPositions (const QgsRenderContext & context, QGis::UnitType unitType) [pure virtual]
Calculate positions for the overlay objects.
Parameters:
context Context of rendering operation (Painter, scale factor)
unitType meters, feet, degrees
Implemented in QgsCentralPointPositionManager, and QgsPALObjectPositionManager.
Referenced by QgsMapRenderer::render().
virtual void QgsOverlayObjectPositionManager::removeLayers () [pure virtual]
Removes all the layers.
Implemented in QgsCentralPointPositionManager, and QgsPALObjectPositionManager.
Referenced by QgsMapRenderer::render().
The documentation for this class was generated from the following file:
src/core/qgsoverlayobjectpositionmanager.h