Quantum GIS API Documentation: QgsMapCanvasMap Class Reference
QgsMapCanvasMap Class Reference
QGIS gui library.
A rectangular graphics item representing the map on the canvas.
#include <qgsmapcanvasmap.h>
Public Member Functions
QgsMapCanvasMap (QgsMapCanvas *canvas)
constructor
void resize (QSize size)
resize canvas item and pixmap
void enableAntiAliasing (bool flag)
void useImageToRender (bool flag)
void render ()
renders map using QgsMapRenderer to mPixmap
void setBackgroundColor (const QColor &color)
void setPanningOffset (const QPoint &point)
Q_DECL_DEPRECATED QPixmap & pixmap ()
QPaintDevice & paintDevice ()
void paint (QPainter *p, const QStyleOptionGraphicsItem *, QWidget *)
QRectF boundingRect () const
void updateContents ()
Update contents - can be called while drawing to show the status.
Private Attributes
bool mAntiAliasing
indicates whether antialiasing will be used for rendering
bool mUseQImageToRender
Whether to use a QPixmap or a QImage for the rendering.
QPixmap mPixmap
QImage mImage
QgsMapCanvas * mCanvas
QColor mBgColor
QPoint mOffset
Detailed Description
A rectangular graphics item representing the map on the canvas.
Definition at line 31 of file qgsmapcanvasmap.h.
Constructor & Destructor Documentation
QgsMapCanvasMap::QgsMapCanvasMap (QgsMapCanvas * canvas)
constructor
Definition at line 24 of file qgsmapcanvasmap.cpp.
References mUseQImageToRender, and resize().
Member Function Documentation
QRectF QgsMapCanvasMap::boundingRect () const
Definition at line 39 of file qgsmapcanvasmap.cpp.
References mPixmap.
void QgsMapCanvasMap::enableAntiAliasing (bool flag) [inline]
Definition at line 41 of file qgsmapcanvasmap.h.
Referenced by QgsMapCanvas::enableAntiAliasing().
void QgsMapCanvasMap::paint (QPainter * p, const QStyleOptionGraphicsItem * , QWidget *)
Definition at line 33 of file qgsmapcanvasmap.cpp.
References mPixmap.
Referenced by render().
QPaintDevice & QgsMapCanvasMap::paintDevice ()
Definition at line 108 of file qgsmapcanvasmap.cpp.
References mPixmap.
Referenced by QgsMapCanvas::canvasPaintDevice(), QgsMapCanvas::canvasPixmap(), QgsMapCanvas::refresh(), and QgsMapCanvas::saveAsImage().
Q_DECL_DEPRECATED QPixmap& QgsMapCanvasMap::pixmap () [inline]
Deprecated:
Please use paintDevice() function which is also save in case QImage is used
Definition at line 53 of file qgsmapcanvasmap.h.
void QgsMapCanvasMap::render ()
renders map using QgsMapRenderer to mPixmap
Definition at line 62 of file qgsmapcanvasmap.cpp.
References mAntiAliasing, QgsMapCanvas::mapRenderer(), mBgColor, mCanvas, mImage, mPixmap, mUseQImageToRender, paint(), and QgsMapRenderer::render().
Referenced by QgsMapCanvas::refresh().
void QgsMapCanvasMap::resize (QSize size)
resize canvas item and pixmap
Definition at line 45 of file qgsmapcanvasmap.cpp.
References QgsMapCanvas::mapRenderer(), mBgColor, mCanvas, mImage, mPixmap, QgsDebugMsg, and QgsMapRenderer::setOutputSize().
Referenced by QgsMapCanvas::paintEvent(), QgsMapCanvas::QgsMapCanvas(), and QgsMapCanvasMap().
void QgsMapCanvasMap::setBackgroundColor (const QColor & color) [inline]
Definition at line 48 of file qgsmapcanvasmap.h.
Referenced by QgsMapCanvas::setCanvasColor().
void QgsMapCanvasMap::setPanningOffset (const QPoint & point)
Definition at line 56 of file qgsmapcanvasmap.cpp.
References mOffset.
Referenced by QgsMapCanvas::moveCanvasContents().
void QgsMapCanvasMap::updateContents ()
Update contents - can be called while drawing to show the status.
Added in version 1.2
Definition at line 113 of file qgsmapcanvasmap.cpp.
References mImage, mPixmap, and mUseQImageToRender.
Referenced by QgsMapCanvas::updateMap().
void QgsMapCanvasMap::useImageToRender (bool flag) [inline]
Definition at line 43 of file qgsmapcanvasmap.h.
Referenced by QgsMapCanvas::useImageToRender().
Member Data Documentation
bool QgsMapCanvasMap::mAntiAliasing [private]
indicates whether antialiasing will be used for rendering
Definition at line 68 of file qgsmapcanvasmap.h.
Referenced by render().
QColor QgsMapCanvasMap::mBgColor [private]
Definition at line 79 of file qgsmapcanvasmap.h.
Referenced by render(), and resize().
QgsMapCanvas* QgsMapCanvasMap::mCanvas [private]
Definition at line 77 of file qgsmapcanvasmap.h.
Referenced by render(), and resize().
QImage QgsMapCanvasMap::mImage [private]
Definition at line 74 of file qgsmapcanvasmap.h.
Referenced by render(), resize(), and updateContents().
QPoint QgsMapCanvasMap::mOffset [private]
Definition at line 81 of file qgsmapcanvasmap.h.
Referenced by setPanningOffset().
QPixmap QgsMapCanvasMap::mPixmap [private]
Definition at line 73 of file qgsmapcanvasmap.h.
Referenced by boundingRect(), paint(), paintDevice(), render(), resize(), and updateContents().
bool QgsMapCanvasMap::mUseQImageToRender [private]
Whether to use a QPixmap or a QImage for the rendering.
Definition at line 71 of file qgsmapcanvasmap.h.
Referenced by QgsMapCanvasMap(), render(), and updateContents().
The documentation for this class was generated from the following files:
src/gui/qgsmapcanvasmap.h
src/gui/qgsmapcanvasmap.cpp