Quantum GIS API Documentation: QgsRendererCategoryV2 Class Reference
QgsRendererCategoryV2 Class Reference
#include <qgscategorizedsymbolrendererv2.h>
Public Member Functions
QgsRendererCategoryV2 (QVariant value, QgsSymbolV2 *symbol, QString label)
takes ownership of symbol
QgsRendererCategoryV2 (const QgsRendererCategoryV2 &cat)
copy constructor
~QgsRendererCategoryV2 ()
QVariant value () const
QgsSymbolV2 * symbol () const
QString label () const
void setValue (const QVariant &value)
void setSymbol (QgsSymbolV2 *s)
void setLabel (const QString &label)
QString dump ()
Protected Attributes
QVariant mValue
QgsSymbolV2 * mSymbol
QString mLabel
Detailed Description
Definition at line 12 of file qgscategorizedsymbolrendererv2.h.
Constructor & Destructor Documentation
QgsRendererCategoryV2::QgsRendererCategoryV2 (QVariant value, QgsSymbolV2 * symbol, QString label)
takes ownership of symbol
Definition at line 16 of file qgscategorizedsymbolrendererv2.cpp.
QgsRendererCategoryV2::QgsRendererCategoryV2 (const QgsRendererCategoryV2 & cat)
copy constructor
Definition at line 21 of file qgscategorizedsymbolrendererv2.cpp.
References QgsSymbolV2::clone(), and mSymbol.
QgsRendererCategoryV2::~QgsRendererCategoryV2 ()
Definition at line 28 of file qgscategorizedsymbolrendererv2.cpp.
References mSymbol.
Member Function Documentation
QString QgsRendererCategoryV2::dump ()
Definition at line 66 of file qgscategorizedsymbolrendererv2.cpp.
References QgsSymbolV2::dump(), mLabel, mSymbol, and mValue.
QString QgsRendererCategoryV2::label () const
Definition at line 43 of file qgscategorizedsymbolrendererv2.cpp.
References mLabel.
Referenced by QgsCategorizedSymbolRendererV2::legendSymbologyItems(), QgsCategorizedSymbolRendererV2::save(), and setLabel().
void QgsRendererCategoryV2::setLabel (const QString & label)
Definition at line 61 of file qgscategorizedsymbolrendererv2.cpp.
References label(), and mLabel.
void QgsRendererCategoryV2::setSymbol (QgsSymbolV2 * s)
Definition at line 53 of file qgscategorizedsymbolrendererv2.cpp.
References mSymbol.
void QgsRendererCategoryV2::setValue (const QVariant & value)
Definition at line 48 of file qgscategorizedsymbolrendererv2.cpp.
References mValue, and value().
QgsSymbolV2 * QgsRendererCategoryV2::symbol () const
Definition at line 38 of file qgscategorizedsymbolrendererv2.cpp.
References mSymbol.
Referenced by QgsCategorizedSymbolRendererV2::addCategory(), QgsCategorizedSymbolRendererV2::legendSymbologyItems(), QgsCategorizedSymbolRendererV2::QgsCategorizedSymbolRendererV2(), QgsCategorizedSymbolRendererV2::rebuildHash(), QgsRuleBasedRendererV2::refineRuleCategories(), QgsSymbologyV2Conversion::rendererV2toV1(), and QgsCategorizedSymbolRendererV2::save().
QVariant QgsRendererCategoryV2::value () const
Definition at line 33 of file qgscategorizedsymbolrendererv2.cpp.
References mValue.
Referenced by QgsCategorizedSymbolRendererV2::rebuildHash(), QgsRuleBasedRendererV2::refineRuleCategories(), QgsSymbologyV2Conversion::rendererV2toV1(), QgsCategorizedSymbolRendererV2::save(), and setValue().
Member Data Documentation
QString QgsRendererCategoryV2::mLabel [protected]
Definition at line 38 of file qgscategorizedsymbolrendererv2.h.
Referenced by dump(), label(), and setLabel().
QgsSymbolV2* QgsRendererCategoryV2::mSymbol [protected]
Definition at line 37 of file qgscategorizedsymbolrendererv2.h.
Referenced by dump(), QgsRendererCategoryV2(), setSymbol(), symbol(), and ~QgsRendererCategoryV2().
QVariant QgsRendererCategoryV2::mValue [protected]
Definition at line 36 of file qgscategorizedsymbolrendererv2.h.
Referenced by dump(), setValue(), and value().
The documentation for this class was generated from the following files:
src/core/symbology-ng/qgscategorizedsymbolrendererv2.h
src/core/symbology-ng/qgscategorizedsymbolrendererv2.cpp