Quantum GIS API Documentation: QgsLineDecorationSymbolLayerV2 Class Reference
QgsLineDecorationSymbolLayerV2 Class Reference
#include <qgslinesymbollayerv2.h>
Public Member Functions
QgsLineDecorationSymbolLayerV2 (QColor color=DEFAULT_LINEDECORATION_COLOR, double width=DEFAULT_LINEDECORATION_WIDTH)
~QgsLineDecorationSymbolLayerV2 ()
QString layerType () const
void startRender (QgsSymbolV2RenderContext &context)
void stopRender (QgsSymbolV2RenderContext &context)
void renderPolyline (const QPolygonF &points, QgsSymbolV2RenderContext &context)
QgsStringMap properties () const
QgsSymbolLayerV2 * clone () const
Static Public Member Functions
static QgsSymbolLayerV2 * create (const QgsStringMap &properties=QgsStringMap())
Protected Attributes
QPen mPen
QPen mSelPen
Detailed Description
Definition at line 155 of file qgslinesymbollayerv2.h.
Constructor & Destructor Documentation
QgsLineDecorationSymbolLayerV2::QgsLineDecorationSymbolLayerV2 (QColor color = DEFAULT_LINEDECORATION_COLOR, double width = DEFAULT_LINEDECORATION_WIDTH)
Definition at line 587 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2::color(), QgsSymbolLayerV2::mColor, QgsLineSymbolLayerV2::mWidth, and QgsLineSymbolLayerV2::width().
Referenced by clone(), and create().
QgsLineDecorationSymbolLayerV2::~QgsLineDecorationSymbolLayerV2 ()
Definition at line 593 of file qgslinesymbollayerv2.cpp.
Member Function Documentation
QgsSymbolLayerV2 * QgsLineDecorationSymbolLayerV2::clone () const [virtual]
Implements QgsSymbolLayerV2.
Definition at line 677 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2::mColor, QgsLineSymbolLayerV2::mWidth, and QgsLineDecorationSymbolLayerV2().
QgsSymbolLayerV2 * QgsLineDecorationSymbolLayerV2::create (const QgsStringMap & properties = QgsStringMap()) [static]
Definition at line 597 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2::color(), QgsSymbolLayerV2Utils::decodeColor(), DEFAULT_LINEDECORATION_COLOR, DEFAULT_LINEDECORATION_WIDTH, QgsLineDecorationSymbolLayerV2(), and QgsLineSymbolLayerV2::width().
Referenced by QgsSymbolLayerV2Registry::QgsSymbolLayerV2Registry().
QString QgsLineDecorationSymbolLayerV2::layerType () const [virtual]
Implements QgsSymbolLayerV2.
Definition at line 610 of file qgslinesymbollayerv2.cpp.
QgsStringMap QgsLineDecorationSymbolLayerV2::properties () const [virtual]
Implements QgsSymbolLayerV2.
Definition at line 669 of file qgslinesymbollayerv2.cpp.
References QgsSymbolLayerV2Utils::encodeColor(), QgsSymbolLayerV2::mColor, and QgsLineSymbolLayerV2::mWidth.
void QgsLineDecorationSymbolLayerV2::renderPolyline (const QPolygonF & points, QgsSymbolV2RenderContext & context) [virtual]
Implements QgsLineSymbolLayerV2.
Definition at line 631 of file qgslinesymbollayerv2.cpp.
References MathUtils::angle(), M_PI, mPen, mSelPen, QgsLineSymbolLayerV2::mWidth, QgsSymbolV2RenderContext::outputLineWidth(), QgsRenderContext::painter(), QgsSymbolV2RenderContext::renderContext(), and QgsSymbolV2RenderContext::selected().
void QgsLineDecorationSymbolLayerV2::startRender (QgsSymbolV2RenderContext & context) [virtual]
Implements QgsSymbolLayerV2.
Definition at line 615 of file qgslinesymbollayerv2.cpp.
References QgsSymbolV2RenderContext::alpha(), QgsSymbolLayerV2::mColor, mPen, mSelPen, QgsLineSymbolLayerV2::mWidth, QgsSymbolV2RenderContext::outputLineWidth(), QgsSymbolV2RenderContext::selectionColor(), and QgsSymbolLayerV2::selectionIsOpaque.
void QgsLineDecorationSymbolLayerV2::stopRender (QgsSymbolV2RenderContext & context) [virtual]
Implements QgsSymbolLayerV2.
Definition at line 627 of file qgslinesymbollayerv2.cpp.
Member Data Documentation
QPen QgsLineDecorationSymbolLayerV2::mPen [protected]
Definition at line 182 of file qgslinesymbollayerv2.h.
Referenced by renderPolyline(), and startRender().
QPen QgsLineDecorationSymbolLayerV2::mSelPen [protected]
Definition at line 183 of file qgslinesymbollayerv2.h.
Referenced by renderPolyline(), and startRender().
The documentation for this class was generated from the following files:
src/core/symbology-ng/qgslinesymbollayerv2.h
src/core/symbology-ng/qgslinesymbollayerv2.cpp