Quantum GIS API Documentation: QgsGraduatedSymbolRenderer Class Reference
QgsGraduatedSymbolRenderer Class Reference
This class contains the information for graduate symbol rendering.
#include <qgsgraduatedsymbolrenderer.h>
Public Types
enum Mode { EqualInterval, Quantile, Empty }
Public Member Functions
QgsGraduatedSymbolRenderer (QGis::GeometryType type, Mode theMode=EqualInterval)
QgsGraduatedSymbolRenderer (const QgsGraduatedSymbolRenderer &other)
QgsGraduatedSymbolRenderer & operator= (const QgsGraduatedSymbolRenderer &other)
virtual ~QgsGraduatedSymbolRenderer ()
Mode mode () const
Get the mode - which is only really used to be able to reinstate the graduated dialog properties properly, so we don't do anything else besides accessors and mutators in this class.
void setMode (Mode theMode)
Set the mode - which is only really used to be able to reinstate the graduated dialog properties properly, so we don't do anything else besides accessors and mutators in this class.
void addSymbol (QgsSymbol *sy)
Adds a new item.
int classificationField () const
Returns the indes of the classification field.
void removeSymbols ()
Removes all symbols.
virtual bool willRenderFeature (QgsFeature *f)
Determines if a feature will be rendered or not.
void renderFeature (QgsRenderContext &renderContext, QgsFeature &f, QImage *img, bool selected, double opacity=1.0)
Renders a feature.
void setClassificationField (int field)
Sets the classicifation field by index.
virtual int readXML (const QDomNode &rnode, QgsVectorLayer &vl)
Reads the renderer configuration from an XML file.
virtual bool writeXML (QDomNode &layer_node, QDomDocument &document, const QgsVectorLayer &vl) const
Writes the contents of the renderer to a configuration file @ return true in case of success.
bool needsAttributes () const
Returns true.
QgsAttributeList classificationAttributes () const
Returns a list of all needed attributes.
void updateSymbolAttributes ()
QString name () const
Returns the renderers name.
const QList< QgsSymbol * > symbols () const
Returns the symbols of the items.
QgsRenderer * clone () const
Returns a copy of the renderer (a deep copy on the heap)
QgsSymbol * symbolForFeature (const QgsFeature *f)
Returns renderer symbol for a feature.
Protected Attributes
Mode mMode
The graduation mode.
int mClassificationField
Index of the classification field (it must be a numerical field)
QList< QgsSymbol * > mSymbols
List holding the symbols for the individual classes.
QgsAttributeList mSymbolAttributes
Cached copy of all underlying symbols required attribute fields.
Detailed Description
This class contains the information for graduate symbol rendering.
Definition at line 27 of file qgsgraduatedsymbolrenderer.h.
Member Enumeration Documentation
enum QgsGraduatedSymbolRenderer::Mode
Enumerator:
EqualInterval
Quantile
Empty
Definition at line 30 of file qgsgraduatedsymbolrenderer.h.
Constructor & Destructor Documentation
QgsGraduatedSymbolRenderer::QgsGraduatedSymbolRenderer (QGis::GeometryType type, Mode theMode = EqualInterval)
Definition at line 35 of file qgsgraduatedsymbolrenderer.cpp.
References QgsRenderer::mGeometryType.
Referenced by clone().
QgsGraduatedSymbolRenderer::QgsGraduatedSymbolRenderer (const QgsGraduatedSymbolRenderer & other)
Definition at line 40 of file qgsgraduatedsymbolrenderer.cpp.
References addSymbol(), mClassificationField, QgsRenderer::mGeometryType, mMode, symbols(), and updateSymbolAttributes().
QgsGraduatedSymbolRenderer::~QgsGraduatedSymbolRenderer () [virtual]
Definition at line 72 of file qgsgraduatedsymbolrenderer.cpp.
Member Function Documentation
void QgsGraduatedSymbolRenderer::addSymbol (QgsSymbol * sy) [inline]
Adds a new item.
Parameters:
sy a pointer to the QgsSymbol to be inserted. It has to be created using the new operator and is automatically destroyed when 'removeItems' is called or when this object is destroyed
Definition at line 126 of file qgsgraduatedsymbolrenderer.h.
References mSymbols.
Referenced by operator=(), QgsGraduatedSymbolRenderer(), readXML(), and QgsSymbologyV2Conversion::rendererV2toV1().
QgsAttributeList QgsGraduatedSymbolRenderer::classificationAttributes () const [virtual]
Returns a list of all needed attributes.
Implements QgsRenderer.
Definition at line 292 of file qgsgraduatedsymbolrenderer.cpp.
References mClassificationField, and mSymbolAttributes.
int QgsGraduatedSymbolRenderer::classificationField () const [inline]
Returns the indes of the classification field.
Definition at line 131 of file qgsgraduatedsymbolrenderer.h.
References mClassificationField.
Referenced by readXML(), and QgsSymbologyV2Conversion::rendererV1toV2().
QgsRenderer * QgsGraduatedSymbolRenderer::clone () const [virtual]
Returns a copy of the renderer (a deep copy on the heap)
Implements QgsRenderer.
Definition at line 396 of file qgsgraduatedsymbolrenderer.cpp.
References QgsGraduatedSymbolRenderer().
QgsGraduatedSymbolRenderer::Mode QgsGraduatedSymbolRenderer::mode () const
Get the mode - which is only really used to be able to reinstate the graduated dialog properties properly, so we don't do anything else besides accessors and mutators in this class.
Definition at line 78 of file qgsgraduatedsymbolrenderer.cpp.
References mMode.
Referenced by QgsSymbologyV2Conversion::rendererV1toV2().
QString QgsGraduatedSymbolRenderer::name () const [virtual]
Returns the renderers name.
Implements QgsRenderer.
Definition at line 330 of file qgsgraduatedsymbolrenderer.cpp.
Referenced by renderFeature().
bool QgsGraduatedSymbolRenderer::needsAttributes () const [inline, virtual]
Returns true.
Implements QgsRenderer.
Definition at line 141 of file qgsgraduatedsymbolrenderer.h.
QgsGraduatedSymbolRenderer & QgsGraduatedSymbolRenderer::operator= (const QgsGraduatedSymbolRenderer & other)
Definition at line 53 of file qgsgraduatedsymbolrenderer.cpp.
References addSymbol(), mClassificationField, QgsRenderer::mGeometryType, mMode, removeSymbols(), symbols(), and updateSymbolAttributes().
int QgsGraduatedSymbolRenderer::readXML (const QDomNode & rnode, QgsVectorLayer & vl) [virtual]
Reads the renderer configuration from an XML file.
Parameters:
rnode the Dom node to read
vl the vector layer which will be associated with the renderer
Returns:
0 in case of success, 1 if vector layer has no renderer, 2 if classification field not found
Implements QgsRenderer.
Definition at line 245 of file qgsgraduatedsymbolrenderer.cpp.
References addSymbol(), classificationField(), QgsVectorLayer::dataProvider(), Empty, EqualInterval, QgsVectorLayer::fieldNameIndex(), QgsVectorLayer::geometryType(), QgsRenderer::mGeometryType, mMode, Quantile, QgsSymbol::readXML(), setClassificationField(), QgsVectorLayer::setRenderer(), and updateSymbolAttributes().
void QgsGraduatedSymbolRenderer::removeSymbols ()
Removes all symbols.
Definition at line 101 of file qgsgraduatedsymbolrenderer.cpp.
References mSymbols, and updateSymbolAttributes().
Referenced by operator=().
void QgsGraduatedSymbolRenderer::renderFeature (QgsRenderContext & renderContext, QgsFeature & f, QImage * img, bool selected, double opacity = 1.0) [virtual]
Renders a feature.
Parameters:
renderContext the render context
f a pointer to a feature to render
img image to render in
selected feature is selected
opacity opacity of feature
Note:
added in 1.2
Implements QgsRenderer.
Definition at line 119 of file qgsgraduatedsymbolrenderer.cpp.
References QgsFeature::attributeMap(), QgsSymbol::brush(), QgsSymbol::getPointSymbolAsImage(), QgsRenderContext::mapToPixel(), QgsMapToPixel::mapUnitsPerPixel(), QgsRenderer::mGeometryType, QgsRenderer::mSelectionColor, name(), QgsRenderContext::painter(), QgsSymbol::pen(), QGis::Point, QgsSymbol::pointSizeUnits(), QgsSymbol::pointSymbolName(), QGis::Polygon, QgsDebugMsgLevel, QgsRenderContext::rasterScaleFactor(), QgsSymbol::rotationClassificationField(), QgsRenderer::scaleBrush(), QgsSymbol::scaleClassificationField(), QgsRenderContext::scaleFactor(), QgsSymbol::setNamedPointSymbol(), QgsSymbol::symbolField(), and symbolForFeature().
void QgsGraduatedSymbolRenderer::setClassificationField (int field) [inline]
Sets the classicifation field by index.
Parameters:
field the number of the field to classify
Definition at line 136 of file qgsgraduatedsymbolrenderer.h.
References mClassificationField.
Referenced by readXML(), and QgsSymbologyV2Conversion::rendererV2toV1().
void QgsGraduatedSymbolRenderer::setMode (QgsGraduatedSymbolRenderer::Mode theMode)
Set the mode - which is only really used to be able to reinstate the graduated dialog properties properly, so we don't do anything else besides accessors and mutators in this class.
Definition at line 87 of file qgsgraduatedsymbolrenderer.cpp.
References mMode.
QgsSymbol * QgsGraduatedSymbolRenderer::symbolForFeature (const QgsFeature * f) [virtual]
Returns renderer symbol for a feature.
Note:
: this method was added in version 1.6
Reimplemented from QgsRenderer.
Definition at line 222 of file qgsgraduatedsymbolrenderer.cpp.
References QgsFeature::attributeMap(), mClassificationField, and mSymbols.
Referenced by renderFeature(), and willRenderFeature().
const QList< QgsSymbol * > QgsGraduatedSymbolRenderer::symbols () const [virtual]
Returns the symbols of the items.
Implements QgsRenderer.
Definition at line 96 of file qgsgraduatedsymbolrenderer.cpp.
References mSymbols.
Referenced by operator=(), QgsGraduatedSymbolRenderer(), and QgsSymbologyV2Conversion::rendererV1toV2().
void QgsGraduatedSymbolRenderer::updateSymbolAttributes ()
Definition at line 302 of file qgsgraduatedsymbolrenderer.cpp.
References mSymbolAttributes, and mSymbols.
Referenced by operator=(), QgsGraduatedSymbolRenderer(), readXML(), and removeSymbols().
bool QgsGraduatedSymbolRenderer::willRenderFeature (QgsFeature * f) [virtual]
Determines if a feature will be rendered or not.
Parameters:
f a pointer to the feature to determine if rendering will happen
Reimplemented from QgsRenderer.
Definition at line 114 of file qgsgraduatedsymbolrenderer.cpp.
References symbolForFeature().
bool QgsGraduatedSymbolRenderer::writeXML (QDomNode & layer_node, QDomDocument & document, const QgsVectorLayer & vl) const [virtual]
Writes the contents of the renderer to a configuration file @ return true in case of success.
Implements QgsRenderer.
Definition at line 335 of file qgsgraduatedsymbolrenderer.cpp.
References QgsVectorLayer::dataProvider(), Empty, mClassificationField, mMode, mSymbols, QgsVectorLayer::pendingFields(), and Quantile.
Member Data Documentation
int QgsGraduatedSymbolRenderer::mClassificationField [protected]
Index of the classification field (it must be a numerical field)
Definition at line 117 of file qgsgraduatedsymbolrenderer.h.
Referenced by classificationAttributes(), classificationField(), operator=(), QgsGraduatedSymbolRenderer(), setClassificationField(), symbolForFeature(), and writeXML().
Mode QgsGraduatedSymbolRenderer::mMode [protected]
The graduation mode.
Definition at line 114 of file qgsgraduatedsymbolrenderer.h.
Referenced by mode(), operator=(), QgsGraduatedSymbolRenderer(), readXML(), setMode(), and writeXML().
QgsAttributeList QgsGraduatedSymbolRenderer::mSymbolAttributes [protected]
Cached copy of all underlying symbols required attribute fields.
Definition at line 123 of file qgsgraduatedsymbolrenderer.h.
Referenced by classificationAttributes(), and updateSymbolAttributes().
QList<QgsSymbol*> QgsGraduatedSymbolRenderer::mSymbols [protected]
List holding the symbols for the individual classes.
Definition at line 120 of file qgsgraduatedsymbolrenderer.h.
Referenced by addSymbol(), removeSymbols(), symbolForFeature(), symbols(), updateSymbolAttributes(), and writeXML().
The documentation for this class was generated from the following files:
src/core/renderer/qgsgraduatedsymbolrenderer.h
src/core/renderer/qgsgraduatedsymbolrenderer.cpp