Quantum GIS API Documentation: QgsRunProcess Class Reference
QgsRunProcess Class Reference
[QGIS core library]
A class that executes an external program/script.
#include <qgsrunprocess.h>
Public Slots
void stdoutAvailable ()
void stderrAvailable ()
void processError (QProcess::ProcessError)
void processExit (int, QProcess::ExitStatus)
void dialogGone ()
Static Public Member Functions
static QgsRunProcess * create (const QString &action, bool capture)
Private Member Functions
QgsRunProcess (const QString &action, bool capture)
~QgsRunProcess ()
void die ()
Private Attributes
QProcess * mProcess
QgsMessageOutput * mOutput
QString mCommand
Detailed Description
A class that executes an external program/script.
It can optionally capture the standard output and error from the process and displays them in a dialog box.
Definition at line 35 of file qgsrunprocess.h.
Constructor & Destructor Documentation
QgsRunProcess::QgsRunProcess (const QString & action, bool capture) [private]
Definition at line 29 of file qgsrunprocess.cpp.
References QgsMessageOutput::createMessageOutput(), dialogGone(), die(), mCommand, QgsMessageOutput::MessageHtml, mOutput, mProcess, processError(), processExit(), QgsDebugMsg, QgsMessageOutput::setMessage(), QgsMessageOutput::setTitle(), QgsMessageOutput::showMessage(), stderrAvailable(), and stdoutAvailable().
QgsRunProcess::~QgsRunProcess () [private]
Definition at line 81 of file qgsrunprocess.cpp.
References mProcess.
Member Function Documentation
static QgsRunProcess* QgsRunProcess::create (const QString & action, bool capture) [inline, static]
Definition at line 47 of file qgsrunprocess.h.
Referenced by QgsAttributeAction::doAction().
void QgsRunProcess::stdoutAvailable () [slot]
Definition at line 92 of file qgsrunprocess.cpp.
References QgsMessageOutput::appendMessage(), mOutput, and mProcess.
Referenced by dialogGone(), and QgsRunProcess().
void QgsRunProcess::stderrAvailable () [slot]
Definition at line 100 of file qgsrunprocess.cpp.
References QgsMessageOutput::appendMessage(), mOutput, and mProcess.
Referenced by dialogGone(), and QgsRunProcess().
void QgsRunProcess::processError (QProcess::ProcessError err) [slot]
Definition at line 147 of file qgsrunprocess.cpp.
References QgsMessageOutput::createMessageOutput(), die(), mCommand, QgsMessageOutput::MessageText, mOutput, QgsDebugMsg, and QgsMessageOutput::setMessage().
Referenced by dialogGone(), and QgsRunProcess().
void QgsRunProcess::processExit (int , QProcess::ExitStatus) [slot]
Definition at line 108 of file qgsrunprocess.cpp.
References QgsMessageOutput::appendMessage(), die(), and mOutput.
Referenced by dialogGone(), and QgsRunProcess().
void QgsRunProcess::dialogGone () [slot]
Definition at line 128 of file qgsrunprocess.cpp.
References die(), mOutput, mProcess, processError(), processExit(), stderrAvailable(), and stdoutAvailable().
Referenced by QgsRunProcess().
void QgsRunProcess::die () [private]
Definition at line 86 of file qgsrunprocess.cpp.
Referenced by dialogGone(), processError(), processExit(), and QgsRunProcess().
Member Data Documentation
QProcess* QgsRunProcess::mProcess [private]
Definition at line 64 of file qgsrunprocess.h.
Referenced by dialogGone(), QgsRunProcess(), stderrAvailable(), stdoutAvailable(), and ~QgsRunProcess().
QgsMessageOutput* QgsRunProcess::mOutput [private]
Definition at line 65 of file qgsrunprocess.h.
Referenced by dialogGone(), processError(), processExit(), QgsRunProcess(), stderrAvailable(), and stdoutAvailable().
QString QgsRunProcess::mCommand [private]
Definition at line 66 of file qgsrunprocess.h.
Referenced by processError(), and QgsRunProcess().
The documentation for this class was generated from the following files:
src/core/qgsrunprocess.h
src/core/qgsrunprocess.cpp