Quantum GIS API Documentation: QgsTextAnnotationItem Class Reference
QgsTextAnnotationItem Class Reference
An annotation item that displays formated text.
#include <qgstextannotationitem.h>
Public Member Functions
QgsTextAnnotationItem (QgsMapCanvas *canvas)
~QgsTextAnnotationItem ()
QTextDocument * document () const
Returns document (caller takes ownership).
void setDocument (const QTextDocument *doc)
Sets document (does not take ownership).
void writeXML (QDomDocument &doc) const
void readXML (const QDomDocument &doc, const QDomElement &itemElem)
void paint (QPainter *painter)
function to be implemented by derived classes
Private Attributes
QTextDocument * mDocument
Detailed Description
An annotation item that displays formated text.
Definition at line 25 of file qgstextannotationitem.h.
Constructor & Destructor Documentation
QgsTextAnnotationItem::QgsTextAnnotationItem (QgsMapCanvas * canvas)
Definition at line 22 of file qgstextannotationitem.cpp.
References mDocument.
QgsTextAnnotationItem::~QgsTextAnnotationItem ()
Definition at line 27 of file qgstextannotationitem.cpp.
References mDocument.
Member Function Documentation
QTextDocument * QgsTextAnnotationItem::document () const
Returns document (caller takes ownership).
Definition at line 32 of file qgstextannotationitem.cpp.
References mDocument.
void QgsTextAnnotationItem::setDocument (const QTextDocument * doc)
Sets document (does not take ownership).
Definition at line 42 of file qgstextannotationitem.cpp.
References mDocument.
void QgsTextAnnotationItem::writeXML (QDomDocument & doc) const [virtual]
Implements QgsAnnotationItem.
Definition at line 76 of file qgstextannotationitem.cpp.
References QgsAnnotationItem::_writeXML(), and mDocument.
void QgsTextAnnotationItem::readXML (const QDomDocument & doc, const QDomElement & itemElem) [virtual]
Implements QgsAnnotationItem.
Definition at line 92 of file qgstextannotationitem.cpp.
References QgsAnnotationItem::_readXML(), and mDocument.
void QgsTextAnnotationItem::paint (QPainter * painter) [virtual]
function to be implemented by derived classes
Implements QgsMapCanvasItem.
Definition at line 48 of file qgstextannotationitem.cpp.
References QgsAnnotationItem::drawFrame(), QgsAnnotationItem::drawMarkerSymbol(), QgsAnnotationItem::drawSelectionBoxes(), mDocument, QgsAnnotationItem::mFrameBorderWidth, QgsAnnotationItem::mFrameSize, QgsAnnotationItem::mMapPositionFixed, and QgsAnnotationItem::mOffsetFromReferencePoint.
Member Data Documentation
QTextDocument* QgsTextAnnotationItem::mDocument [private]
Definition at line 42 of file qgstextannotationitem.h.
Referenced by document(), paint(), QgsTextAnnotationItem(), readXML(), setDocument(), writeXML(), and ~QgsTextAnnotationItem().
The documentation for this class was generated from the following files:
src/gui/qgstextannotationitem.h
src/gui/qgstextannotationitem.cpp