Quantum GIS API Documentation: QgsAction Class Reference
QgsAction Class Reference
[QGIS core library]
Utility class that encapsulates an action based on vector attributes.
#include <qgsattributeaction.h>
Public Types
enum ActionType {
Generic, GenericPython, Mac, Windows,
Unix
}
Public Member Functions
QgsAction (ActionType type, QString name, QString action, bool capture)
QString name () const
The name of the action.
QString action () const
The action.
ActionType type () const
The action type.
bool capture () const
Whether to capture output for display when this action is run.
bool runable () const
Whether the action is runable on the current platform.
Private Attributes
ActionType mType
QString mName
QString mAction
bool mCaptureOutput
Detailed Description
Utility class that encapsulates an action based on vector attributes.
Definition at line 41 of file qgsattributeaction.h.
Member Enumeration Documentation
enum QgsAction::ActionType
Enumerator:
Generic
GenericPython
Mac
Windows
Unix
Definition at line 44 of file qgsattributeaction.h.
Constructor & Destructor Documentation
QgsAction::QgsAction (ActionType type, QString name, QString action, bool capture) [inline]
Definition at line 53 of file qgsattributeaction.h.
Member Function Documentation
QString QgsAction::name () const [inline]
The name of the action.
Definition at line 57 of file qgsattributeaction.h.
QString QgsAction::action () const [inline]
The action.
Definition at line 60 of file qgsattributeaction.h.
Referenced by QgsAttributeAction::doAction().
ActionType QgsAction::type () const [inline]
The action type.
Definition at line 63 of file qgsattributeaction.h.
Referenced by QgsAttributeAction::doAction().
bool QgsAction::capture () const [inline]
Whether to capture output for display when this action is run.
Definition at line 66 of file qgsattributeaction.h.
Referenced by QgsAttributeAction::doAction().
bool QgsAction::runable () const [inline]
Whether the action is runable on the current platform.
Definition at line 69 of file qgsattributeaction.h.
Referenced by QgsAttributeAction::doAction().
Member Data Documentation
ActionType QgsAction::mType [private]
Definition at line 84 of file qgsattributeaction.h.
QString QgsAction::mName [private]
Definition at line 85 of file qgsattributeaction.h.
QString QgsAction::mAction [private]
Definition at line 86 of file qgsattributeaction.h.
bool QgsAction::mCaptureOutput [private]
Definition at line 87 of file qgsattributeaction.h.
The documentation for this class was generated from the following file:
src/core/qgsattributeaction.h