Quantum GIS API Documentation: QgsSearchString Class Reference
QgsSearchString Class Reference
[QGIS core library]
A class to represent a search string.
#include <qgssearchstring.h>
Public Member Functions
QgsSearchString ()
construct an empty string
QgsSearchString (const QString &str)
construct and parse a string
QgsSearchString (const QgsSearchString &str)
copy constructor - makes also copy of search tree
~QgsSearchString ()
destructor - deletes node tree
QgsSearchString & operator= (const QgsSearchString &str)
assignment operator takes care to copy search tree correctly
bool setString (QString str)
sets search string and parses search tree on success returns true and sets member variables to the new values
bool setTree (QgsSearchTreeNode *tree)
QgsSearchTreeNode * tree ()
getter functions
QString string ()
const QString & parserErrorMsg ()
returns parser error message - valid only after unsuccessfull parsing
bool isEmpty ()
returns true if no string is set
void clear ()
clear search string
Private Attributes
QgsSearchTreeNode * mTree
search string and coresponding tree
QString mString
QString mParserErrorMsg
error message from parser
Detailed Description
A class to represent a search string.
interface for 'search string' parser
when a string is set, it parses it and creates parsed tree of it
owns node tree and coresponding search string
keeps string and node tree always in sync
Definition at line 35 of file qgssearchstring.h.
Constructor & Destructor Documentation
QgsSearchString::QgsSearchString ()
construct an empty string
Definition at line 28 of file qgssearchstring.cpp.
References mTree.
QgsSearchString::QgsSearchString (const QString & str)
construct and parse a string
Note:
added in v1.6
Definition at line 33 of file qgssearchstring.cpp.
References mTree, and setString().
QgsSearchString::QgsSearchString (const QgsSearchString & str)
copy constructor - makes also copy of search tree
Definition at line 39 of file qgssearchstring.cpp.
References mString, and mTree.
QgsSearchString::~QgsSearchString ()
destructor - deletes node tree
Definition at line 62 of file qgssearchstring.cpp.
References mTree.
Member Function Documentation
QgsSearchString & QgsSearchString::operator= (const QgsSearchString & str)
assignment operator takes care to copy search tree correctly
Definition at line 48 of file qgssearchstring.cpp.
References clear(), mString, and mTree.
bool QgsSearchString::setString (QString str)
sets search string and parses search tree on success returns true and sets member variables to the new values
Definition at line 68 of file qgssearchstring.cpp.
References clear(), mParserErrorMsg, mString, mTree, parseSearchString(), and tree().
Referenced by QgsRuleBasedRendererV2::Rule::initFilter(), and QgsSearchString().
bool QgsSearchString::setTree (QgsSearchTreeNode * tree)
Definition at line 93 of file qgssearchstring.cpp.
References clear(), QgsSearchTreeNode::makeSearchString(), mString, and mTree.
QgsSearchTreeNode* QgsSearchString::tree () [inline]
getter functions
Definition at line 63 of file qgssearchstring.h.
Referenced by QgsRuleBasedRendererV2::Rule::initFilter(), and setString().
QString QgsSearchString::string () [inline]
Definition at line 64 of file qgssearchstring.h.
const QString& QgsSearchString::parserErrorMsg () [inline]
returns parser error message - valid only after unsuccessfull parsing
Definition at line 67 of file qgssearchstring.h.
bool QgsSearchString::isEmpty ()
returns true if no string is set
Definition at line 108 of file qgssearchstring.cpp.
References mTree.
void QgsSearchString::clear ()
clear search string
Definition at line 113 of file qgssearchstring.cpp.
References mString, and mTree.
Referenced by operator=(), setString(), and setTree().
Member Data Documentation
QgsSearchTreeNode* QgsSearchString::mTree [private]
search string and coresponding tree
Definition at line 77 of file qgssearchstring.h.
Referenced by clear(), isEmpty(), operator=(), QgsSearchString(), setString(), setTree(), and ~QgsSearchString().
QString QgsSearchString::mString [private]
Definition at line 78 of file qgssearchstring.h.
Referenced by clear(), operator=(), QgsSearchString(), setString(), and setTree().
QString QgsSearchString::mParserErrorMsg [private]
error message from parser
Definition at line 81 of file qgssearchstring.h.
Referenced by setString().
The documentation for this class was generated from the following files:
src/core/qgssearchstring.h
src/core/qgssearchstring.cpp