Quantum GIS API Documentation: QgsMapCanvasLayer Class Reference
QgsMapCanvasLayer Class Reference
[QGIS gui library.]
A class that stores visibility and presence in overview flags together with pointer to the layer.
#include <qgsmapcanvas.h>
Public Member Functions
QgsMapCanvasLayer (QgsMapLayer *layer, bool visible=true, bool isInOverview=false)
void setVisible (bool visible)
void setInOverview (bool isInOverview)
bool isVisible () const
bool isInOverview () const
QgsMapLayer * layer ()
const QgsMapLayer * layer () const
Private Attributes
QgsMapLayer * mLayer
bool mVisible
Flag whether layer is visible.
bool mInOverview
Flag whether layer is shown in overview.
Detailed Description
A class that stores visibility and presence in overview flags together with pointer to the layer.
Definition at line 64 of file qgsmapcanvas.h.
Constructor & Destructor Documentation
QgsMapCanvasLayer::QgsMapCanvasLayer (QgsMapLayer * layer, bool visible = true, bool isInOverview = false) [inline]
Definition at line 67 of file qgsmapcanvas.h.
Member Function Documentation
void QgsMapCanvasLayer::setVisible (bool visible) [inline]
Definition at line 70 of file qgsmapcanvas.h.
void QgsMapCanvasLayer::setInOverview (bool isInOverview) [inline]
Definition at line 71 of file qgsmapcanvas.h.
bool QgsMapCanvasLayer::isVisible () const [inline]
Definition at line 73 of file qgsmapcanvas.h.
Referenced by QgsMapCanvas::setLayerSet().
bool QgsMapCanvasLayer::isInOverview () const [inline]
Definition at line 74 of file qgsmapcanvas.h.
Referenced by QgsMapCanvas::setLayerSet().
QgsMapLayer* QgsMapCanvasLayer::layer () [inline]
Definition at line 76 of file qgsmapcanvas.h.
Referenced by QgsMapCanvas::setLayerSet().
const QgsMapLayer* QgsMapCanvasLayer::layer () const [inline]
Definition at line 77 of file qgsmapcanvas.h.
Member Data Documentation
QgsMapLayer* QgsMapCanvasLayer::mLayer [private]
Definition at line 81 of file qgsmapcanvas.h.
bool QgsMapCanvasLayer::mVisible [private]
Flag whether layer is visible.
Definition at line 84 of file qgsmapcanvas.h.
bool QgsMapCanvasLayer::mInOverview [private]
Flag whether layer is shown in overview.
Definition at line 87 of file qgsmapcanvas.h.
The documentation for this class was generated from the following file:
src/gui/qgsmapcanvas.h