Quantum GIS API Documentation: QgsPluginLayerRegistry Class Reference
QgsPluginLayerRegistry Class Reference
[QGIS core library]
a registry of plugin layers types
#include <qgspluginlayerregistry.h>
Public Member Functions
~QgsPluginLayerRegistry ()
bool addPluginLayerType (QgsPluginLayerType *pluginLayerType)
add plugin layer type (take ownership) and return true on success
bool removePluginLayerType (QString typeName)
remove plugin layer type and return true on success
QgsPluginLayerType * pluginLayerType (QString typeName)
return plugin layer type metadata or NULL if doesn't exist
QgsPluginLayer * createLayer (QString typeName)
return new layer if corresponding plugin has been found, else return NULL
Static Public Member Functions
static QgsPluginLayerRegistry * instance ()
means of accessing canonical single instance
Private Types
typedef QMap< QString,
QgsPluginLayerType * > PluginLayerTypes
Private Member Functions
QgsPluginLayerRegistry ()
private since instance() creates it
Private Attributes
PluginLayerTypes mPluginLayerTypes
Static Private Attributes
static QgsPluginLayerRegistry * _instance = NULL
pointer to canonical Singleton object
Detailed Description
a registry of plugin layers types
Note:
added in v1.5
Definition at line 59 of file qgspluginlayerregistry.h.
Member Typedef Documentation
typedef QMap<QString, QgsPluginLayerType*> QgsPluginLayerRegistry::PluginLayerTypes [private]
Definition at line 82 of file qgspluginlayerregistry.h.
Constructor & Destructor Documentation
QgsPluginLayerRegistry::~QgsPluginLayerRegistry ()
Definition at line 67 of file qgspluginlayerregistry.cpp.
References mPluginLayerTypes, QgsDebugMsg, and removePluginLayerType().
QgsPluginLayerRegistry::QgsPluginLayerRegistry () [private]
private since instance() creates it
Definition at line 63 of file qgspluginlayerregistry.cpp.
Referenced by instance().
Member Function Documentation
QgsPluginLayerRegistry * QgsPluginLayerRegistry::instance () [static]
means of accessing canonical single instance
Definition at line 53 of file qgspluginlayerregistry.cpp.
References _instance, and QgsPluginLayerRegistry().
Referenced by QgsProject::_getMapLayers(), and QgsProject::read().
bool QgsPluginLayerRegistry::addPluginLayerType (QgsPluginLayerType * pluginLayerType)
add plugin layer type (take ownership) and return true on success
Definition at line 77 of file qgspluginlayerregistry.cpp.
References mPluginLayerTypes, and QgsPluginLayerType::name().
bool QgsPluginLayerRegistry::removePluginLayerType (QString typeName)
remove plugin layer type and return true on success
Definition at line 89 of file qgspluginlayerregistry.cpp.
References QgsMapLayer::getLayerID(), QgsMapLayerRegistry::instance(), QgsMapLayerRegistry::mapLayers(), mPluginLayerTypes, QgsMapLayer::PluginLayer, QgsPluginLayer::pluginLayerType(), QgsMapLayerRegistry::removeMapLayer(), and QgsMapLayer::type().
Referenced by ~QgsPluginLayerRegistry().
QgsPluginLayerType * QgsPluginLayerRegistry::pluginLayerType (QString typeName)
return plugin layer type metadata or NULL if doesn't exist
Definition at line 112 of file qgspluginlayerregistry.cpp.
References mPluginLayerTypes.
Referenced by createLayer().
QgsPluginLayer * QgsPluginLayerRegistry::createLayer (QString typeName)
return new layer if corresponding plugin has been found, else return NULL
Definition at line 118 of file qgspluginlayerregistry.cpp.
References QgsPluginLayerType::createLayer(), pluginLayerType(), and QgsDebugMsg.
Referenced by QgsProject::_getMapLayers(), and QgsProject::read().
Member Data Documentation
QgsPluginLayerRegistry * QgsPluginLayerRegistry::_instance = NULL [static, private]
pointer to canonical Singleton object
Static calls to enforce singleton behaviour.
Definition at line 88 of file qgspluginlayerregistry.h.
Referenced by instance().
PluginLayerTypes QgsPluginLayerRegistry::mPluginLayerTypes [private]
Definition at line 90 of file qgspluginlayerregistry.h.
Referenced by addPluginLayerType(), pluginLayerType(), removePluginLayerType(), and ~QgsPluginLayerRegistry().
The documentation for this class was generated from the following files:
src/core/qgspluginlayerregistry.h
src/core/qgspluginlayerregistry.cpp