Quantum GIS API Documentation: QgsComposerLayerItem Class Reference
QgsComposerLayerItem Class Reference
#include <qgscomposerlegenditem.h>
Public Member Functions
QgsComposerLayerItem ()
QgsComposerLayerItem (const QString &text)
virtual ~QgsComposerLayerItem ()
virtual QStandardItem * clone () const
virtual void writeXML (QDomElement &elem, QDomDocument &doc) const
virtual void readXML (const QDomElement &itemElem)
ItemType itemType () const
void setLayerID (const QString &id)
QString layerID () const
Private Attributes
QString mLayerID
Detailed Description
Definition at line 129 of file qgscomposerlegenditem.h.
Constructor & Destructor Documentation
QgsComposerLayerItem::QgsComposerLayerItem ()
Definition at line 280 of file qgscomposerlegenditem.cpp.
Referenced by clone().
QgsComposerLayerItem::QgsComposerLayerItem (const QString & text)
Definition at line 284 of file qgscomposerlegenditem.cpp.
QgsComposerLayerItem::~QgsComposerLayerItem () [virtual]
Definition at line 288 of file qgscomposerlegenditem.cpp.
Member Function Documentation
QStandardItem * QgsComposerLayerItem::clone () const [virtual]
Implements QgsComposerLegendItem.
Definition at line 292 of file qgscomposerlegenditem.cpp.
References mLayerID, QgsComposerLayerItem(), and setLayerID().
void QgsComposerLayerItem::writeXML (QDomElement & elem, QDomDocument & doc) const [virtual]
Implements QgsComposerLegendItem.
Definition at line 300 of file qgscomposerlegenditem.cpp.
References mLayerID, and QgsComposerLegendItem::writeXMLChildren().
void QgsComposerLayerItem::readXML (const QDomElement & itemElem) [virtual]
Implements QgsComposerLegendItem.
Definition at line 309 of file qgscomposerlegenditem.cpp.
References QgsComposerLegendItem::readXML(), and setLayerID().
ItemType QgsComposerLayerItem::itemType () const [inline, virtual]
Implements QgsComposerLegendItem.
Definition at line 140 of file qgscomposerlegenditem.h.
void QgsComposerLayerItem::setLayerID (const QString & id) [inline]
Definition at line 142 of file qgscomposerlegenditem.h.
Referenced by QgsLegendModel::addLayer(), clone(), and readXML().
QString QgsComposerLayerItem::layerID () const [inline]
Definition at line 143 of file qgscomposerlegenditem.h.
Referenced by QgsComposerLegend::drawLayerItem(), QgsLegendModel::setLayerSetAndGroups(), and QgsLegendModel::updateLayer().
Member Data Documentation
QString QgsComposerLayerItem::mLayerID [private]
Definition at line 146 of file qgscomposerlegenditem.h.
Referenced by clone(), and writeXML().
The documentation for this class was generated from the following files:
src/core/composer/qgscomposerlegenditem.h
src/core/composer/qgscomposerlegenditem.cpp