Quantum GIS API Documentation: QgsMessageViewer Class Reference
QgsMessageViewer Class Reference
[QGIS gui library.]
A generic message view for displaying QGIS messages.
#include <qgsmessageviewer.h>
Public Member Functions
QgsMessageViewer (QWidget *parent=0, Qt::WFlags fl=QgisGui::ModalDialogFlags)
~QgsMessageViewer ()
virtual void setMessage (const QString &message, MessageType msgType)
set message, it won't be displayed until
virtual void appendMessage (const QString &message)
message to be appended to the current text
virtual void showMessage (bool blocking=true)
display the message to the user
virtual void setTitle (const QString &title)
set title for the messages
void setMessageAsHtml (const QString &msg)
void setMessageAsPlainText (const QString &msg)
void setCheckBoxText (const QString &text)
void setCheckBoxVisible (bool visible)
void setCheckBoxState (Qt::CheckState state)
Qt::CheckState checkBoxState ()
void setCheckBoxQSettingsLabel (QString label)
Private Slots
void on_checkBox_toggled (bool)
Private Attributes
QString mCheckBoxQSettingsLabel
Detailed Description
A generic message view for displaying QGIS messages.
Definition at line 31 of file qgsmessageviewer.h.
Constructor & Destructor Documentation
QgsMessageViewer::QgsMessageViewer (QWidget * parent = 0, Qt::WFlags fl = QgisGui::ModalDialogFlags)
Definition at line 22 of file qgsmessageviewer.cpp.
References mCheckBoxQSettingsLabel, setCheckBoxState(), and setCheckBoxVisible().
QgsMessageViewer::~QgsMessageViewer ()
Definition at line 35 of file qgsmessageviewer.cpp.
Member Function Documentation
void QgsMessageViewer::setMessage (const QString & message, MessageType msgType) [virtual]
set message, it won't be displayed until
Implements QgsMessageOutput.
Definition at line 55 of file qgsmessageviewer.cpp.
References QgsMessageOutput::MessageHtml, setMessageAsHtml(), and setMessageAsPlainText().
void QgsMessageViewer::appendMessage (const QString & message) [virtual]
message to be appended to the current text
Implements QgsMessageOutput.
Definition at line 49 of file qgsmessageviewer.cpp.
void QgsMessageViewer::showMessage (bool blocking = true) [virtual]
display the message to the user
Implements QgsMessageOutput.
Definition at line 63 of file qgsmessageviewer.cpp.
void QgsMessageViewer::setTitle (const QString & title) [virtual]
set title for the messages
Implements QgsMessageOutput.
Definition at line 71 of file qgsmessageviewer.cpp.
void QgsMessageViewer::setMessageAsHtml (const QString & msg)
Definition at line 39 of file qgsmessageviewer.cpp.
Referenced by setMessage().
void QgsMessageViewer::setMessageAsPlainText (const QString & msg)
Definition at line 44 of file qgsmessageviewer.cpp.
Referenced by setMessage(), and QgsMapCanvas::showError().
void QgsMessageViewer::setCheckBoxText (const QString & text)
Definition at line 76 of file qgsmessageviewer.cpp.
void QgsMessageViewer::setCheckBoxVisible (bool visible)
Definition at line 81 of file qgsmessageviewer.cpp.
Referenced by QgsMessageViewer().
void QgsMessageViewer::setCheckBoxState (Qt::CheckState state)
Definition at line 86 of file qgsmessageviewer.cpp.
Referenced by QgsMessageViewer().
Qt::CheckState QgsMessageViewer::checkBoxState ()
Definition at line 91 of file qgsmessageviewer.cpp.
void QgsMessageViewer::setCheckBoxQSettingsLabel (QString label)
Definition at line 96 of file qgsmessageviewer.cpp.
References mCheckBoxQSettingsLabel.
void QgsMessageViewer::on_checkBox_toggled (bool toggled) [private, slot]
Definition at line 102 of file qgsmessageviewer.cpp.
References mCheckBoxQSettingsLabel.
Member Data Documentation
QString QgsMessageViewer::mCheckBoxQSettingsLabel [private]
Definition at line 72 of file qgsmessageviewer.h.
Referenced by on_checkBox_toggled(), QgsMessageViewer(), and setCheckBoxQSettingsLabel().
The documentation for this class was generated from the following files:
src/gui/qgsmessageviewer.h
src/gui/qgsmessageviewer.cpp