Quantum GIS API Documentation: QgsContinuousColorRenderer Class Reference
QgsContinuousColorRenderer Class Reference
Renderer class which interpolates rgb values linear between the minimum and maximum value of the classification field.
#include <qgscontinuouscolorrenderer.h>
Public Member Functions
QgsContinuousColorRenderer (QGis::GeometryType type)
QgsContinuousColorRenderer (const QgsContinuousColorRenderer &other)
QgsContinuousColorRenderer & operator= (const QgsContinuousColorRenderer &other)
virtual ~QgsContinuousColorRenderer ()
void renderFeature (QgsRenderContext &renderContext, QgsFeature &f, QImage *img, bool selected, double opacity=1.0)
Renders the feature using the minimum and maximum value of the classification field added in 1.2.
int classificationField () const
Returns the number of the classification field.
void setClassificationField (int id)
Sets the id of the classification field.
void setMinimumSymbol (QgsSymbol *sy)
Sets the symbol for the minimum value.
void setMaximumSymbol (QgsSymbol *sy)
Sets the symbol for the maximum value.
void setDrawPolygonOutline (bool draw)
Sets whether to draw the polygon outline.
const QgsSymbol * minimumSymbol () const
Returns the symbol for the minimum value.
const QgsSymbol * maximumSymbol () const
Returns the symbol for the maximum value.
bool drawPolygonOutline () const
whether to draw a polygon outline
virtual int readXML (const QDomNode &rnode, QgsVectorLayer &vl)
Reads the renderer configuration from an XML file.
virtual bool writeXML (QDomNode &layer_node, QDomDocument &document, const QgsVectorLayer &vl) const
Writes the contents of the renderer to a configuration file @ return true in case of success.
bool needsAttributes () const
Returns true.
QgsAttributeList classificationAttributes () const
Returns a list with the index of the classification attribute.
QString name () const
Returns the renderers name.
const QList< QgsSymbol * > symbols () const
Return symbology items.
QgsRenderer * clone () const
Returns a copy of the renderer (a deep copy on the heap).
Protected Attributes
int mClassificationField
Number of the classification field (it must be a numerical field).
QgsSymbol * mMinimumSymbol
Item for the minimum value.
QgsSymbol * mMaximumSymbol
Item for the maximum value.
bool mDrawPolygonOutline
Whether to draw the polygon outline or not.
Detailed Description
Renderer class which interpolates rgb values linear between the minimum and maximum value of the classification field.
Definition at line 31 of file qgscontinuouscolorrenderer.h.
Constructor & Destructor Documentation
QgsContinuousColorRenderer::QgsContinuousColorRenderer (QGis::GeometryType type)
Definition at line 32 of file qgscontinuouscolorrenderer.cpp.
References QgsRenderer::mGeometryType.
Referenced by clone().
QgsContinuousColorRenderer::QgsContinuousColorRenderer (const QgsContinuousColorRenderer & other)
Definition at line 37 of file qgscontinuouscolorrenderer.cpp.
References mClassificationField, QgsRenderer::mGeometryType, mMaximumSymbol, and mMinimumSymbol.
QgsContinuousColorRenderer::~QgsContinuousColorRenderer () [virtual]
Definition at line 59 of file qgscontinuouscolorrenderer.cpp.
References mMaximumSymbol, and mMinimumSymbol.
Member Function Documentation
QgsContinuousColorRenderer & QgsContinuousColorRenderer::operator= (const QgsContinuousColorRenderer & other)
Definition at line 45 of file qgscontinuouscolorrenderer.cpp.
References mClassificationField, QgsRenderer::mGeometryType, mMaximumSymbol, and mMinimumSymbol.
void QgsContinuousColorRenderer::renderFeature (QgsRenderContext & renderContext, QgsFeature & f, QImage * img, bool selected, double opacity = 1.0) [virtual]
Renders the feature using the minimum and maximum value of the classification field added in 1.2.
Implements QgsRenderer.
Definition at line 77 of file qgscontinuouscolorrenderer.cpp.
References QgsFeature::attributeMap(), QgsSymbol::brush(), QgsSymbol::fillColor(), QgsMarkerCatalogue::imageMarker(), QgsMarkerCatalogue::instance(), QGis::Line, QgsSymbol::lowerValue(), mClassificationField, mDrawPolygonOutline, QgsRenderer::mGeometryType, mMaximumSymbol, mMinimumSymbol, QgsRenderer::mSelectionColor, QgsRenderContext::painter(), QgsSymbol::pen(), QGis::Point, QgsSymbol::pointSize(), QgsSymbol::pointSymbolName(), QGis::Polygon, QgsRenderContext::rasterScaleFactor(), and QgsRenderContext::scaleFactor().
int QgsContinuousColorRenderer::classificationField () const [inline]
Returns the number of the classification field.
Definition at line 88 of file qgscontinuouscolorrenderer.h.
References mClassificationField.
Referenced by readXML().
void QgsContinuousColorRenderer::setClassificationField (int id) [inline]
Sets the id of the classification field.
Definition at line 93 of file qgscontinuouscolorrenderer.h.
References mClassificationField.
Referenced by readXML().
void QgsContinuousColorRenderer::setMinimumSymbol (QgsSymbol * sy)
Sets the symbol for the minimum value.
The symbol has to be created using the new operator and is automatically deleted when inserting a new symbol or when the instance is destroyed
Definition at line 65 of file qgscontinuouscolorrenderer.cpp.
References mMinimumSymbol.
Referenced by readXML().
void QgsContinuousColorRenderer::setMaximumSymbol (QgsSymbol * sy)
Sets the symbol for the maximum value.
The symbol has to be created using the new operator and is automatically deleted when inserting a new symbol or when the instance is destroyed
Definition at line 71 of file qgscontinuouscolorrenderer.cpp.
References mMaximumSymbol.
Referenced by readXML().
void QgsContinuousColorRenderer::setDrawPolygonOutline (bool draw) [inline]
Sets whether to draw the polygon outline.
Definition at line 52 of file qgscontinuouscolorrenderer.h.
const QgsSymbol * QgsContinuousColorRenderer::minimumSymbol () const [inline]
Returns the symbol for the minimum value.
Definition at line 98 of file qgscontinuouscolorrenderer.h.
References mMinimumSymbol.
const QgsSymbol * QgsContinuousColorRenderer::maximumSymbol () const [inline]
Returns the symbol for the maximum value.
Definition at line 103 of file qgscontinuouscolorrenderer.h.
References mMaximumSymbol.
bool QgsContinuousColorRenderer::drawPolygonOutline () const [inline]
whether to draw a polygon outline
Definition at line 58 of file qgscontinuouscolorrenderer.h.
int QgsContinuousColorRenderer::readXML (const QDomNode & rnode, QgsVectorLayer & vl) [virtual]
Reads the renderer configuration from an XML file.
Parameters:
rnode the Dom node to read
vl the vector layer which will be associated with the renderer
Returns:
0 in case of success, 1 if vector layer has no renderer, 2 if classification field not found
Implements QgsRenderer.
Definition at line 194 of file qgscontinuouscolorrenderer.cpp.
References classificationField(), QgsVectorLayer::dataProvider(), QgsVectorDataProvider::fieldNameIndex(), QgsVectorLayer::geometryType(), mDrawPolygonOutline, QgsRenderer::mGeometryType, QgsSymbol::readXML(), setClassificationField(), setMaximumSymbol(), setMinimumSymbol(), and QgsVectorLayer::setRenderer().
bool QgsContinuousColorRenderer::writeXML (QDomNode & layer_node, QDomDocument & document, const QgsVectorLayer & vl) const [virtual]
Writes the contents of the renderer to a configuration file @ return true in case of success.
Implements QgsRenderer.
Definition at line 257 of file qgscontinuouscolorrenderer.cpp.
References QgsVectorLayer::dataProvider(), QgsVectorDataProvider::fields(), mClassificationField, mDrawPolygonOutline, mMaximumSymbol, mMinimumSymbol, and QgsSymbol::writeXML().
bool QgsContinuousColorRenderer::needsAttributes () const [inline, virtual]
Returns true.
Implements QgsRenderer.
Definition at line 108 of file qgscontinuouscolorrenderer.h.
QgsAttributeList QgsContinuousColorRenderer::classificationAttributes () const [virtual]
Returns a list with the index of the classification attribute.
Implements QgsRenderer.
Definition at line 245 of file qgscontinuouscolorrenderer.cpp.
References mClassificationField.
QString QgsContinuousColorRenderer::name () const [virtual]
Returns the renderers name.
Implements QgsRenderer.
Definition at line 252 of file qgscontinuouscolorrenderer.cpp.
const QList< QgsSymbol * > QgsContinuousColorRenderer::symbols () const [virtual]
Return symbology items.
Implements QgsRenderer.
Definition at line 303 of file qgscontinuouscolorrenderer.cpp.
References mMaximumSymbol, and mMinimumSymbol.
QgsRenderer * QgsContinuousColorRenderer::clone () const [virtual]
Returns a copy of the renderer (a deep copy on the heap).
Implements QgsRenderer.
Definition at line 311 of file qgscontinuouscolorrenderer.cpp.
References QgsContinuousColorRenderer().
Member Data Documentation
int QgsContinuousColorRenderer::mClassificationField [protected]
Number of the classification field (it must be a numerical field).
Definition at line 79 of file qgscontinuouscolorrenderer.h.
Referenced by classificationAttributes(), classificationField(), operator=(), QgsContinuousColorRenderer(), renderFeature(), setClassificationField(), and writeXML().
QgsSymbol* QgsContinuousColorRenderer::mMinimumSymbol [protected]
Item for the minimum value.
Definition at line 81 of file qgscontinuouscolorrenderer.h.
Referenced by minimumSymbol(), operator=(), QgsContinuousColorRenderer(), renderFeature(), setMinimumSymbol(), symbols(), writeXML(), and ~QgsContinuousColorRenderer().
QgsSymbol* QgsContinuousColorRenderer::mMaximumSymbol [protected]
Item for the maximum value.
Definition at line 83 of file qgscontinuouscolorrenderer.h.
Referenced by maximumSymbol(), operator=(), QgsContinuousColorRenderer(), renderFeature(), setMaximumSymbol(), symbols(), writeXML(), and ~QgsContinuousColorRenderer().
bool QgsContinuousColorRenderer::mDrawPolygonOutline [protected]
Whether to draw the polygon outline or not.
Definition at line 85 of file qgscontinuouscolorrenderer.h.
Referenced by readXML(), renderFeature(), and writeXML().
The documentation for this class was generated from the following files:
src/core/renderer/qgscontinuouscolorrenderer.h
src/core/renderer/qgscontinuouscolorrenderer.cpp