Quantum GIS API Documentation: QgsColorBrewerPalette Class Reference
QgsColorBrewerPalette Class Reference
#include <qgscolorbrewerpalette.h>
Static Public Member Functions
static QList< QColor > listSchemeColors (QString schemeName, int colors)
static QStringList listSchemes ()
static QList< int > listSchemeVariants (QString schemeName)
static QColor parseColor (QString color)
Detailed Description
Definition at line 7 of file qgscolorbrewerpalette.h.
Member Function Documentation
static QList<QColor> QgsColorBrewerPalette::listSchemeColors (QString schemeName, int colors) [inline, static]
Definition at line 10 of file qgscolorbrewerpalette.h.
References brewerString.
Referenced by QgsVectorColorBrewerColorRampV2::loadPalette().
static QStringList QgsColorBrewerPalette::listSchemes () [inline, static]
Definition at line 27 of file qgscolorbrewerpalette.h.
References brewerString.
Referenced by QgsVectorColorBrewerColorRampV2::listSchemeNames().
static QList<int> QgsColorBrewerPalette::listSchemeVariants (QString schemeName) [inline, static]
Definition at line 43 of file qgscolorbrewerpalette.h.
References brewerString.
Referenced by QgsVectorColorBrewerColorRampV2::listSchemeVariants().
static QColor QgsColorBrewerPalette::parseColor (QString color) [inline, static]
Definition at line 59 of file qgscolorbrewerpalette.h.
The documentation for this class was generated from the following file:
src/core/symbology-ng/qgscolorbrewerpalette.h