Quantum GIS API Documentation: QGIS core library
QGIS core library
Contains all basic GIS functionality.
Classes
class QGis
The QGis class provides global constants for use throughout the application.
class QgsApplication
Extends QApplication to provide access to QGIS specific resources such as theme paths, database paths etc.
class QgsAction
Utility class that encapsulates an action based on vector attributes.
class QgsClipper
A class to trim lines and polygons to within a rectangular region.
class QgsContextHelp
Provides a context based help browser for a dialog.
class QgsCoordinateReferenceSystem
Class for storing a coordinate reference system (CRS).
class QgsCoordinateTransform
Class for doing transforms between two map coordinate systems.
class QgsCredentials
Interface for requesting credentials in QGIS in GUI independent way.
class QgsCsException
Custom exception class for Coordinate Reference System related exceptions.
class QgsDataProvider
Abstract base class for spatial data provider implementations.
class QgsDataSourceURI
Class for storing the component parts of a PostgreSQL/RDBMS datasource URI.
class QgsDistanceArea
General purpose distance and area calculator.
class QgsException
Defines a qgis exception class.
class QgsFeature
The feature class encapsulates a single feature including its id, geometry and a list of field/values attributes.
class QgsField
Encapsulate a field in an attribute table or data source.
class QgsGeometry
A geometry is the spatial representation of a feature.
class QgsHttpTransaction
HTTP request/response manager that is redirect-aware.
class QgsLabel
A class to render labels.
class QgsLabelAttributes
A class to store attributes needed for label rendering.
class QgsLogger
QgsLogger is a class to print debug/warning/error messages to the console.
class QgsMapLayer
Base class for all map layer types.
class QgsMapLayerRegistry
This class tracks map layers that are currently loaded and provides a means to fetch a pointer to a map layer and delete it.
class QgsMapRenderer
A non GUI class for rendering a map layer set onto a QPainter.
class QgsMapToPixel
Perform transforms between map coordinates and device coordinates.
class QgsMessageOutput
Interface for showing messages from QGIS in GUI independent way.
class QgsPluginLayer
Base class for plugin layers.
class QgsPluginLayerType
class for creating plugin specific layers
class QgsPluginLayerRegistry
a registry of plugin layers types
class QgsVector
A class to represent a vector.
class QgsPoint
A class to represent a point geometry.
class QgsProject
Reads and writes project states.
class QgsProjectFileTransform
Class to convert from older project file versions to newer.
class QgsProperty
An Abstract Base Class for QGIS project property hierarchies.
class QgsProjectVersion
A class to describe the version of a project.
class QgsProviderCountCalcEvent
A custom event that is designed to be fired when a layer count has been fully calculated.
class QgsProviderExtentCalcEvent
A custom event that is designed to be fired when a layer extent has been fully calculated.
class QgsProviderMetadata
Holds data provider key, description, and associated shared library file information.
class QgsProviderRegistry
A registry / canonical manager of data providers.
class QgsRasterDataProvider
Base class for raster data providers.
class QgsRectangle
A rectangle specified with double values.
class QgsRenderContext
Contains information about the context of a rendering operation.
class QgsRunProcess
A class that executes an external program/script.
class QgsScaleCalculator
Calculates scale for a given combination of canvas size, map extent, and monitor dpi.
class QgsSearchString
A class to represent a search string.
class QgsSearchTreeNode
A representation of a node in a search tree.
struct QgsSnappingResult
Represents the result of a snapping operation.
class QgsTolerance
This is the class is providing tolerance value in map unit values.
class QgsVectorDataProvider
This is the base class for vector data providers.
class QgsVectorFileWriter
A convenience class for writing vector files to disk.
class QgsVectorLayer
Vector layer backed by a data source provider.
class QgsClipToMinMaxEnhancement
A raster contrast enhancement that will clip a value to the specified min/max range.
class QgsColorRampShader
A ramp shader will color a raster pixel based on a list of values ranges in a ramp.
class QgsContrastEnhancement
Manipulates raster pixel values so that they enhanceContrast or clip into a specified numerical range according to the specified ContrastEnhancementAlgorithm.
class QgsContrastEnhancementFunction
A contrast enhancement funcion is the base class for all raster contrast enhancements.
class QgsFreakOutShader
A colorful false color shader that will frighten your granny and make your dogs howl.
class QgsLinearMinMaxEnhancement
A color enhancement function that performs a linear enhanceContrast between min and max.
class QgsLinearMinMaxEnhancementWithClip
A linear enhanceContrast enhancement that first clips to min max and then enhanceContrastes linearly between min and max.
class QgsPseudoColorShader
A raster color shader that highlighs low values in blue and high values in red.
class QgsRasterBandStats
The RasterBandStats struct is a container for statistics about a single raster band.
class QgsRasterLayer
This class provides qgis with the ability to render raster datasets onto the mapcanvas.
class QgsRasterPyramid
This struct is used to store pyramid info for the raster layer.
class QgsRasterShader
Interface for all raster shaders.
class QgsRasterShaderFunction
The raster shade function applies a shader to a pixel at render time - typically used to render grayscale images as false color.
class QgsRasterTransparency
Defines the list of pixel values to be considered as transparent or semi transparent when rendering rasters.
struct QgsRasterViewPort
This class provides details of the viewable area that a raster will be rendered into.
Functions
int CPL_STDCALL progressCallback (double dfComplete, const char *pszMessage, void *pProgressArg)
A call back function for showing progress of gdal operations.
Detailed Description
Contains all basic GIS functionality.
Function Documentation
int CPL_STDCALL progressCallback (double dfComplete, const char * pszMessage, void * pProgressArg)
A call back function for showing progress of gdal operations.
Definition at line 576 of file qgsrasterlayer.cpp.
References QgsRasterLayer::showProgress().
Referenced by QgsRasterLayer::buildPyramids(), and QgsRasterLayer::populateHistogram().