Quantum GIS API Documentation: QgsSymbologyUtils Namespace Reference
QgsSymbologyUtils Namespace Reference
Namespace containing static methods which are useful for the symbology widgets.
Functions
QString penStyle2QString (Qt::PenStyle penstyle)
Qt::PenStyle qString2PenStyle (QString penString)
QString brushStyle2QString (Qt::BrushStyle brushstyle)
Qt::BrushStyle qString2BrushStyle (QString brushString)
QPixmap qString2LinePixmap (QString lineString)
QPixmap qString2PatternPixmap (QString patternString)
const char * penStyle2Char (Qt::PenStyle penstyle)
const char * brushStyle2Char (Qt::BrushStyle brushstyle)
QPixmap char2LinePixmap (const char *c)
QPixmap char2PatternPixmap (const char *c)
Qt::PenStyle char2PenStyle (const char *c)
Qt::BrushStyle char2BrushStyle (const char *c)
QPixmap penStyle2Pixmap (Qt::PenStyle penstyle)
QPixmap brushStyle2Pixmap (Qt::BrushStyle brushstyle)
Detailed Description
Namespace containing static methods which are useful for the symbology widgets.
Function Documentation
const char CORE_EXPORT * QgsSymbologyUtils::brushStyle2Char (Qt::BrushStyle brushstyle)
Definition at line 1025 of file qgssymbologyutils.cpp.
QPixmap CORE_EXPORT QgsSymbologyUtils::brushStyle2Pixmap (Qt::BrushStyle brushstyle)
Definition at line 1348 of file qgssymbologyutils.cpp.
References bdiagData, crossData, dense1Data, dense2Data, dense3Data, dense4Data, dense5Data, dense6Data, dense7Data, diagCrossData, fdiagData, horizontalData, nobrush, QgsDebugMsg, solidData, texturePatternData, and verticalData.
QString CORE_EXPORT QgsSymbologyUtils::brushStyle2QString (Qt::BrushStyle brushstyle)
Definition at line 736 of file qgssymbologyutils.cpp.
References QgsDebugMsg.
Referenced by QgsSymbol::writeXML().
Qt::BrushStyle CORE_EXPORT QgsSymbologyUtils::char2BrushStyle (const char * c)
Definition at line 1247 of file qgssymbologyutils.cpp.
References QgsDebugMsg.
QPixmap CORE_EXPORT QgsSymbologyUtils::char2LinePixmap (const char * c)
Definition at line 1097 of file qgssymbologyutils.cpp.
References dashDotDotLineData, dashDotLineData, dashLineData, dotLineData, noPenLineData, QgsDebugMsg, and solidLineData.
QPixmap CORE_EXPORT QgsSymbologyUtils::char2PatternPixmap (const char * c)
Definition at line 1136 of file qgssymbologyutils.cpp.
References bdiagData, crossData, dense1Data, dense2Data, dense3Data, dense4Data, dense5Data, dense6Data, dense7Data, diagCrossData, fdiagData, horizontalData, nobrush, QgsDebugMsg, solidData, texturePatternData, and verticalData.
Qt::PenStyle CORE_EXPORT QgsSymbologyUtils::char2PenStyle (const char * c)
Definition at line 1210 of file qgssymbologyutils.cpp.
References QgsDebugMsg.
const char CORE_EXPORT * QgsSymbologyUtils::penStyle2Char (Qt::PenStyle penstyle)
Definition at line 989 of file qgssymbologyutils.cpp.
QPixmap CORE_EXPORT QgsSymbologyUtils::penStyle2Pixmap (Qt::PenStyle penstyle)
Definition at line 1320 of file qgssymbologyutils.cpp.
References dashDotDotLineData, dashDotLineData, dashLineData, dotLineData, noPenLineData, QgsDebugMsg, and solidLineData.
QString CORE_EXPORT QgsSymbologyUtils::penStyle2QString (Qt::PenStyle penstyle)
Definition at line 664 of file qgssymbologyutils.cpp.
Referenced by QgsSymbol::writeXML().
Qt::BrushStyle CORE_EXPORT QgsSymbologyUtils::qString2BrushStyle (QString brushString)
Definition at line 809 of file qgssymbologyutils.cpp.
References QgsDebugMsg.
Referenced by QgsSymbol::readXML().
QPixmap CORE_EXPORT QgsSymbologyUtils::qString2LinePixmap (QString lineString)
Definition at line 882 of file qgssymbologyutils.cpp.
References dashDotDotLineData, dashDotLineData, dashLineData, dotLineData, noPenLineData, and solidLineData.
QPixmap CORE_EXPORT QgsSymbologyUtils::qString2PatternPixmap (QString patternString)
Definition at line 916 of file qgssymbologyutils.cpp.
References bdiagData, crossData, dense1Data, dense2Data, dense3Data, dense4Data, dense5Data, dense6Data, dense7Data, diagCrossData, fdiagData, horizontalData, nobrush, QgsDebugMsg, solidData, texturePatternData, and verticalData.
Qt::PenStyle CORE_EXPORT QgsSymbologyUtils::qString2PenStyle (QString penString)
Definition at line 700 of file qgssymbologyutils.cpp.
Referenced by QgsSymbol::readXML().