Quantum GIS API Documentation: QgsProject::Imp Struct Reference
QgsProject::Imp Struct Reference
Public Member Functions
Imp ()
void clear ()
clear project properties when a new project is started
Public Attributes
QFile file
current physical project file
QgsPropertyKey properties_
property hierarchy
QString title
project title
bool dirty
true if project has been modified since it has been read or saved
Detailed Description
Definition at line 294 of file qgsproject.cpp.
Constructor & Destructor Documentation
QgsProject::Imp::Imp () [inline]
Definition at line 308 of file qgsproject.cpp.
References QgsPropertyKey::name(), and properties_.
Member Function Documentation
void QgsProject::Imp::clear () [inline]
clear project properties when a new project is started
Definition at line 319 of file qgsproject.cpp.
References QgsPropertyKey::clearKeys(), QgsProject::instance(), properties_, title, and QgsProject::writeEntry().
Member Data Documentation
QFile QgsProject::Imp::file
current physical project file
Definition at line 297 of file qgsproject.cpp.
QgsPropertyKey QgsProject::Imp::properties_
property hierarchy
Definition at line 300 of file qgsproject.cpp.
Referenced by clear(), and Imp().
QString QgsProject::Imp::title
project title
Definition at line 303 of file qgsproject.cpp.
Referenced by clear().
bool QgsProject::Imp::dirty
true if project has been modified since it has been read or saved
Definition at line 306 of file qgsproject.cpp.
The documentation for this struct was generated from the following file:
src/core/qgsproject.cpp